### ISSUE TITLE
Xxeus anti-flying?

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#100]
If you have flight from another mod (i.e. Extra Utilities) I noticed that while battling Xxeus, Krasaun punishes you for doing so by poisoning you. This is also said in chat (while calling you a coward). My question is, why is this not implemented for more bosses? It would make the bosses more of a challenge plus it is a cool idea. I already know the Baroness literally pulls you to the ground if you are flying against her. I only noticed both of these through battling the bosses in survival. Can you please add this in for more bosses please?

**Comment by Immortallis1** [comment]
Pretty sure this was done for ALL bosses in the 2.5 snapshot. Not sure what happened but I'll assume Tslat only ported it for craexxeus

**Comment by EatingSilencer** [comment]
Yeah, Scimiguy/Tslat ported xxeus code from 2.5 snapshot which had punishment for flying attached. The other bosses (except for tyrosaur, mechbot, and baroness) are taken from 2.4.B and thus don't have punishment for flying on them. 

Personally, something like this needs reworked. Its currently form isn't very good in my opinion for multiple reasons:
*chat spam in creative mode
*easily bypassable
