### ISSUE TITLE
[snapshot] Trading with a corrupted traveler once should unlock a second trade that's just the blank realmstone

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1001]
**Describe/name the existing feature this suggestion relates to**
Corrupted traveler

**Describe the change or feature you think would be good to see**
Not sure how possible it is, but currently to get a blank realmstone you have to open a Worn book, meaning that if you want to get many you have to keep buying and opening multiple books, which can be a bit annoying.

Basically, once you get 1 book from a Corrupted Traveler, it should open up a second trade that's just the Blank realmstone. It would have the same cost of any food, it would just skip the need to get more than 1 Worn book,

Was originally suggested by someone on the discord, I just made this post for them because I think it's a pretty good idea.

**Comment by Immortallis1** [comment]
probably slightly better for lore purposes too, since it's more conceivable for him to have several copies of the realmstones given he represents a traveller who once visited them all, instead of having several copies of the exact same book that have the stones in them

**Comment by Tslat** [comment]
Not needed anymore
