### ISSUE TITLE
Make ores that drop gems smeltable

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1003]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
All ores that drop gems

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
In the mod, ores that drop gems cannot be smelted in a furnace to obtain the gem. This is inconsistent with vanilla mc, which allows you to do this.

I suggest adding smelting recipes to these ores: Shyregem Ore, Jewelyte Ore, Gemenyte Ore, Ornamyte Ore, Amethyst Ore, Sapphire Ore, Jade Ore, Crystallite Ore, Bloodstone Ore, Skull Fragment Ore, Chest Fargment Ore, Leg Fragment Ore, Foot Fragment Ore.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?

Only other way I can think of handling this is providing lore for why these ores can't be smelted, only mined.

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Its probably been mentioned before, but I'm not sure.

**Comment by Tslat** [comment]
Weird, this should already be the case?

**Comment by EatingSilencer** [comment]
I was trying out the 3.2 snapshot 6. Perhaps the smelting recipes got deleted along by mistake? As far as I can tell, it was not present in the snapshot.

**Comment by Tslat** [comment]
Not sure. They're present post-snapshot 6 at least
