### ISSUE TITLE
Gyro Music

### ISSUE THREAD

**Issue by Firch** [Tslat/Advent-Of-Ascension#1005]
Third music suggestion. This for Gyro boss
https://soundcloud.com/hvab6gxlzwis/nevermine-gyro-coulrophobia
(OUTDATED)

**Comment by Firch** [comment]
Um, oops, not new feature
E.C.C. Because previous suggestion is E.C.C.
#878

**Comment by Tslat** [comment]
Sounds great.
If you can make it 30-60 seconds longer and clean up the ending so it's not such a sharp cutoff, I'll use it in 3.2

**Comment by Firch** [comment]
https://soundcloud.com/hvab6gxlzwis/nevermine-gyro-coulrophobia-v2

**Comment by Tslat** [comment]
Awesome
Do you consent to the above track being used without royalty in AoA?

**Comment by Firch** [comment]
Yes

**Comment by Firch** [comment]
https://www.dropbox.com/s/6n9y4dia9wdvwfz/GyrocopterFinal1.wav?dl=0

**Comment by Firch** [comment]
https://soundcloud.com/hvab6gxlzwis/nevermine-gyro-coulrophobia-v3
Or you can this version (just slightly more intense)
download: https://www.dropbox.com/s/2774mwxamdqi4xr/GyrocopterFinal2.wav?dl=0
