### ISSUE TITLE
Having Smash in the Bestiary causes the boss music to play while the bestiary is open

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1008]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
When I placed the boss Smash into the bestiary, and then checked the bestiary, the boss music started to play.

The boss music does not play ordinarily on the entity select screen, it starts repeatedly looping itself/starting over and over again.

Have tried testing this with Corallus but have not turned up the same results so far.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add Smash to the player's bestiary.
2. Make sure the music is turned up. 
3. Go to the bestiary.
4. See error, or rather, listen to the error.

**Expected behavior**

The boss music does not play when I look at Smash in the bestiary.

**Comment by Tslat** [comment]
Fixed
