### ISSUE TITLE
[Balance] Candlefire sword

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#101]
**Describe/name the item/content this suggestion relates to**
The candlefire sword is too op since it is an early-game weapon and does quadruple damage to entity on fire, making it able to kill a player in a hit or two.

**Describe the change/balance you think would be good to see**
Make the candlefire sword do triple or double damage.

**Add any alternative implementations you think might work**
Maybe use some more slightly more late-game material to craft like minerals in underground barathos.

**Include any additional background information**
It was reported on the Chinese community and the suggestions were proposed by myself. That player also thinks that there is a bug which the sword’s damage isn’t reduced by armor, but I haven’t tested it.

**Comment by Sagisolar** [comment]
The candlefire sword is to situwaitinal to be nerfed

**Comment by Cruuk** [comment]
It was already nerfed in the 3.0 snapshot, it does 6 base damage now and fire doubles the damage, kind of nerfed a little too hard to be honest... (though I already made a suggestion on that a while ago, before the github stuff haha).
Please play the 3.0 snapshot before making balance suggestions.

@Sagisolar Fire aspect doesn't make it "very situational" anymore, even then you have many other ways of dealing fire damage like Embrodium armor, fire weapons, etc.

**Comment by masterbobli** [comment]
I should
