### ISSUE TITLE
Candy Armor's new ability can eat return crystals, potentially causing the player to be ejected from Immortallis unwantedly.

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1015]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
In the 3.2 snapshot 6, Candy Armor automatically consumes food when wearing any piece. If a food item has an ability gained upon being eaten, the ability is granted to the player.

Return Crystals count as food. If the player is missing hunger at any time in Immortallis, and the return crystal happens to be the next food item in the player's inventory, the armor will eat it and eject the player out of Immortallis without the player's interaction.

**To Reproduce**
Steps to reproduce the behaviour:
1. Wear at least on piece of candy armor.
2. Go to Immortallis (anywhere in it works).
3. Make sure the player is missing some hunger bars.
4. Place a return crystal in the player's inventory.
5. See the player immediately teleported back to the main room.

**Expected behavior**

Return crystals are not consumed by candy armor.

**Comment by Tslat** [comment]
Fixed
