### ISSUE TITLE
Candy armor's new ability does not return bowls to inventory upon eating food in bowls

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1016]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
When the player is hungry and is wearing at least one piece of candy armor, food items in the player's inventory are automatically consumed.

Most items that give back other items upon consumption successfully give back their other items: all tea types and lunarade, as well as halycon milk, all successfully give back the cup/lunarade mug/bucket.

Mushroom Stew/Beetroot Soup/Rabbit Stew do not give back their bowls however.

**To Reproduce**
Steps to reproduce the behaviour:
1. Put on at least one piece of candy armor.
2. Make sure the player is hungry.
3. Add Beetroot Soup/Mushroom Stew/Rabbit Stew to the player's inventory.
4. See the food get consumed without a bowl returning to the player's inventory.

**Expected behavior**
The bowls are returned to the player's inventory - making it consistent with the other items.

**Comment by Tslat** [comment]
Fixed
