### ISSUE TITLE
Rune Crafting/Infusion and Rune Rituals [preliminary]

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#102]
Want to suggest this now because it might sort of tie into the loot system changes. A little bit rough right now but the core idea is clear.

**THE PROBLEM:**

Runes are boring and useless. EDIT: going to check on 1.12 changes again but the rest still holds

~~<s>Scratch that, staves as a whole I've never really found much reason to use. Some of them are cool, and and some are really good like Joker staff or Concussion staff, but most are "ehh" and kind of just extra weapons to fill up the mob drop lists or make it take longer for you to collect them all.

There's not much that weapon staff can do that a gun, a bow, a sword, etc. really can't. It even says on the wiki that Staves deal "Gun" damage. Support staves exist, I understand, but again a lot of them don't seem like the kind that anybody would need to use. AoE weakness is pretty much useless espeically with ranged mobs in play. AoE slowness is also mostly useless. And anything that heals requires Life Runes with their Level 72 runation requirement, which is generally going to be far more annoying to get than a couple healing potions or golden apples, or pretty much any healing method in any other mod. I've personally rarely used staves and never had much trouble.

Utility staves exist too but most of them are also kind of useless. According to the wiki there are 8 although Joker Staff is actually a combat staff so just 7 really:
**Atlantic**: AoE slowness, useless especially given that by the time you fight Pinchers you are almost guaranteed to have such good gear that this is irrelevant anyways. Honestly not sure why Xolova said this was his favorite staff in the game (possible connections to Atlantis Rising?)
**Formation**: trashed
**Fungal**: Creating more runes doesn't make runes any more useful, it just makes more useless stuff. Creating food is cool I guess
**Runic**: Kind of useless. Backpacks, gravestones, portable ender chest pouch mods, etc. all reduce its efficacy. Even without those, in most situations your inventory will be stacked almost to the brim with copper coins so everything will fall out. Would be better if you could just access your ender chest.
**Reef**: Probably my favorite.
**Shyre**: While the shyre staff is cool, ender pearls are usually better and far easier to obtain (and surprise surprise looting actually does something to them). Shyre staff does no damage but if you are low on health you might just end up teleporting into a pack of mobs.
**Sky**: Just stack up lol

It got to the point where an entire boss that could only be hurt with staves was added. Whether or not it was just to give the staves use or make the Cotton Candor "challenging" is debatable but still...</s>

Now back to runes. Runes exist SOLELY as ammunition for staves. They are to staves as pellets are to guns, but more annoying to get and oftentimes aren't even that useful in combat even with "annoyingness" equalized. If you don't use staves, runes are useless. That's it.

Note that runes also have a level requirement to get. If I want to use a gun, I just pop in a bunch of bullets and call it a day (made from limonite which you are really likely to find while mining for runium). Bows/archerguns, arrows. But to use staves I have to get to a certain Runation level and then find a structure and get a bunch of runes and go back whenever I need new runes...it's just really not worth the hassle.

-------------------------------

In my opinion, runes have a LOT more potential.

The thing is, other mods like Thaumcraft, or Ars Magica, or Blood Magic, and a lot of other things in general (Pokemon, for instance) use elements as a base in some way. Thaumcraft in particular splits stuff into "aspects". 
For example, fire has the fire aspect, and magical wood has the magic and wood aspects. You can use the aspects in creation of utility items (and some weapons). You might not want to use them but if you do you can do some fancy stuff with them.

We already have something similar, in the form of runes. Runes come in basic varieties such as Fire, Water, Air (Wind), Life, Poison, etc. plus some more "niche" runes like Compass or Storm that can have their uses. 

(Not sure why we have no Earth runes honestly). 

Imagine if you could draw the magic from these runes to create various items, or to upgrade the items and weapons you already have. Or create "magic tech" of sorts - not stuff that runs off of RF, but things that add slight automation to certain mundane tasks.

Imagine if you could use them to create rituals, to change the weather, or speed up plant growth (not terribly original), or light everything near it on fire.

This would give another use to the Runation skill besides gating staves which are often kind of useless anyway. I think that Runation might need another training method but that's for another day.

------------------------
I don't want to include anything technical, but the general gist is that runes, in addition to their current staff usages, should be usable for a couple more things.

RUNIC CRAFTING:
Usage of runes and their magical powers to add magical energy to various different items or weapons or utility blocks.
Something like infusion in Thaumcraft.

It should be done outside the crafting table using a new system. While crafting is all right it feels so cheap compared to the fancy animation potential it could have, with sparks flying or the items floating in midair and combining with sound effects and particle effects and whatnot.  

RUNIC RITUALS:
Use runes on an altar block of sorts.
For example I can use a storm ritual to call a thunderstorm, or a life ritual to boost the growth speed of plants in the area...or even summon a miniboss that you can fight anywhere. Lots of potential here. Would likely be moderately expensive and require some other items but would require predominantly runes, giving them a more consistent use.

The important part is that they feel more like a more developed mod, with either a GUI or a more complex GUI-less system with animations (like how I described above, making better use of sounds, particles, item sprites floating in midair, blocks being placed nearby affecting the results, etc.) AoA currently lacks these, with most "tables" and crafting systems - the rune shrines included - just being right clicking a block with an item to get another item.

Admittedly, my creativity at this point is starting to run dry but there are plenty of other minds who can think of all sorts of useful utility and combat items or blocks or rituals, and expand the usage of Runes beyond annoying-to-get ammunition for redundant projectile weapon (or AoE slowness/weakness stick) #2795.

------------------------

**Include any additional background information**
It hasn't been touched upon too much before, to my knowledge. I'd wager that it's because runes just aren't seen as important.

**Comment by Cruuk** [comment]
In 1.12.2 ALL staves now do magic damage now, completely different from gun damage. And even then damage staves can still be useful in my opinion. You have ones like Aquatic staff that can rack up a whopping 56 DPS (compared to Megagun's 40 DPS) as long as the enemy is touching water. You also have ones like Primordial staff that get 38 DPS while also having one of the most powerful ways of healing in the whole game. (19 base damage, all staves have a 2.0 fire rate)
Also Runic staff was changed to allow you to open an ender chest from anywhere.

Though yeah it would be nice if runes in general did more than just be used for staves. As you mentioned it would be cool if you were able to augment items with runes and/or use them to initiate various things in the world.
