### ISSUE TITLE
Bloodstone sword recipe makes a bloodstone instead of a bloodstone sword

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1021]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
The recipe for a bloodstone sword (2 bloodstones and 1 stick) does not make a bloodstone sword, it instead makes a bloodstone.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a crafting table, 2 bloodstones, and 1 stick.
2. Try to craft a bloodstone sword in the crafting table.
3. See that it makes a bloodstone.

**Expected behavior**
The bloodstone sword recipe makes a bloodstone sword.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/71420492-930d2d00-2643-11ea-8a63-be060c24e165.png)

**Comment by Tslat** [comment]
Fixed
