### ISSUE TITLE
Mineralzation Station's new ability doesn't seem to work

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1022]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
In the 3.2 changelog, it says that the mineralization station is supposed to give tokens for using ingots on it. However, upon attempting to do this in-game, it does not seem to be working: no ingots are consumed when right-clicked onto it, and no tokens are given.

**To Reproduce**
Steps to reproduce the behaviour:
1. Grab a mineralization station and any ingot or mineral in the mod.
2. Place down the mineralization station.
3. Right-click the mineralization station with the ingot/mineral.

**Expected behavior**
The mineralization station works as intended.

**Comment by EatingSilencer** [comment]
I'll also note that looking at the way it is coded, the Iromine task is a part of the code. Due to the way it is coded, the player would probably get 13-24 iromine realmstones if the blank realmstone were to be used on it.

**Comment by Tslat** [comment]
Has been fixed
