### ISSUE TITLE
Permissions for various AoA commands

### ISSUE THREAD

**Issue by theStrobilus** [Tslat/Advent-Of-Ascension#1025]
I've been wanting to run a server with Advent of Ascension, but none of my friends and I think that the fact you have to be a certain level to fight something is restrictive and bad, but the /aoaskill command exists! Only problem is, an administrator would have to do it for you, and if you run an actual server, this could be an issue if you had lots of players. A simple permission maybe to allow for plugins such as Luckperms or some other permission plugin/mod to actually allow players to set their own level would be very convenient. No clue how it would be made, though.

As for an alternative, maybe just have an option to toggle off certain skills or just sort of disable/ignore the levelling system in the config file. Though, I am sure this has been suggested before in other suggestion, "issues."

**Comment by Tslat** [comment]
The leveling system is central to the mod.

However, the next update does allow you to configure what mobs are hunter mobs and their level requirements, so that might actually solve your problem anyway

**Comment by Tslat** [comment]
The best permissions system I could find for Forge is ForgeEssentials, and that doesn't even seem very popular...
Permissions probably isn't very likely as there's just no popular permissions systems for forge, they're all on bukkit apparently.
