### ISSUE TITLE
Very small issue with leaves in Shyrelands

### ISSUE THREAD

**Issue by NeoVolt** [Tslat/Advent-Of-Ascension#1027]
**Mod Version**
What version of the mod are you on?

3.1.2b

**Describe the bug**

The leaves in Shyrelands don't render like other leaves in the mod or in vanilla (as in you can't see the sides of connected leaf blocks by looking at them like you can with other leaves, I've left some example screenshots of what I mean since I'm not the best at explaining things.

**To Reproduce**
Steps to reproduce the behaviour:

1. You'd kinda have to edit the leaf textures for shyrelands and add in some blank space to be able to see this, but since I'm working on a more 1.14-ish styled texture pack, this not working correctly means that I have to make these leaves not look like the others.
2. Look at leaves and compare to other leaves

**Expected behavior**

The leaves should look like other leaves.

Along with Shyrelands leaves not working correctly, Runic Leaves also don't work correctly, but I'm unsure if I would even call Runic Leaves "Leaves", they're more or less a type of glass that has a plant sound.

(Also, just a guess as to what the problem is, maybe when you were programming these leaves into existence, you accidentally might have told them to take properties from a different class rather than the one the other leaves use.)

![2019-09-08_13 26 46](https://user-images.githubusercontent.com/57927345/71551115-89b5f480-29a4-11ea-9ab4-65152519a2f1.png)

![2019-12-28_19 46 19](https://user-images.githubusercontent.com/57927345/71551102-4fe4ee00-29a4-11ea-9c29-fe973b24bdff.png)

**Comment by NeoVolt** [comment]
Oh, one more thing as well.
![image](https://user-images.githubusercontent.com/57927345/71551365-5b87e300-29ab-11ea-808c-f052e7cac443.png)
Didn't notice this last post, but the Lucalus trees in Precasia also are missing a leaf block on them.

**Comment by Tslat** [comment]
Yeah.. I have shyrelands leaves marked as translucent, which causes this.
I'm actually a bit confused because they don't appear to be translucent, so I'm not sure why they're marked as such..
I've removed it in the next update so that'll fix your problem
