### ISSUE TITLE
Primordial Wizard

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#1028]
**Describe/name the existing feature this suggestion relates to**
There are two mobs that primordial wizards:
One is an NPC that spawns in the primordial village:[https://adventofascension.gamepedia.com/Primordial_Wizard](url)
The other is a member of the Primordial Five (Miskel the Primordial Wizard)
[https://adventofascension.gamepedia.com/Primordial_Five](url)

**Describe the change or feature you think would be good to see**
One of the mobs should have a different name.

**Add any alternative implementations you think might work**
Just change "Miskel the Primordial Wizard" to Miskel, and do the same with all other members of the primordial five.

**Include any additional background information**
No

**Comment by Tslat** [comment]
I don't think I see the problem here..

Miskel is called Miskel.

**Comment by masterbobli** [comment]
The description of Miskel is also "primordial wizard", which means two different mobs have the same name.

**Comment by Tslat** [comment]
That's his description though, not his name.

**Comment by masterbobli** [comment]
But wouldn't it cause confusion?

**Comment by Tslat** [comment]
No-one else has mentioned it.. but maybe
