### ISSUE TITLE
Display glitch occurs on commander leggings

### ISSUE THREAD

**Issue by SkyFuInMC** [Tslat/Advent-Of-Ascension#1034]
## Mod Version
3.1.2b

## Describe the bug
This kind of display glitch occurs when the player wears or puts the commander leggings on armour stands.

## To Reproduce
Steps to reproduce the behaviour:
* Obtain the item.
* Wear it or place it on an armour stand.

## Expected behavior
Glitch reproduced.

## Screenshots
![https://cdn.discordapp.com/attachments/462790175555190784/663009104830398469/17c9ee7ce7c0dc0f.jpg]()
![https://cdn.discordapp.com/attachments/462790175555190784/663009105757208609/1c9f6b980004db3f.png]()

**Comment by EatingSilencer** [comment]
Your links to your screenshots don't seem to work for me. You can upload them into the github post itself by dragging and dropping them onto the text field I think.

**Comment by Tslat** [comment]
[Pic](https://cdn.discordapp.com/attachments/462790175555190784/663009104830398469/17c9ee7ce7c0dc0f.jpg)

[Pic](https://cdn.discordapp.com/attachments/462790175555190784/663009105757208609/1c9f6b980004db3f.png)

Fixed links

**Comment by Tslat** [comment]
Fixed
