### ISSUE TITLE
Shadow has a loot table for itself when similar mobs (Hiding Fungi and Dead Tree) don't

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1035]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
The Shadow mob (the mob that spawns a Shade when you defeat it) has a loot table for itself. This loot table contains a single drop: shadow can drop an item from the Overworld Loot Table when it is defeated.

Hiding Fungi and Dead Tree however, do not have loot tables. I reckon that this is intended due to the nature of these mobs.

**To Reproduce**
Steps to reproduce the behaviour:
It is easy enough to tell that shadow has a loot table by looking in the mod's files and see a shadow.json file in the loot_tables/overworld folder.

**Expected behavior**
Shadow should not have a loot table if hiding fungi/dead tree don't either, or hiding fungi/dead tree should have loot tables.

**Comment by Tslat** [comment]
Yeah it shouldn't have one, thanks
