### ISSUE TITLE
Skolle's loot table is missing

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1036]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
I was looking in the 3.2 snapshot 6's files and noticed that a loot table for skolle is absent. 

**To Reproduce**
Steps to reproduce the behaviour:
Go into the mod's files and look for skolle's loot table. None will be found.

**Expected behavior**
Skolle should have a loot table.

**Comment by Tslat** [comment]
Good pickup
