### ISSUE TITLE
Idea for a new weapon

### ISSUE THREAD

**Issue by Armakeen** [Tslat/Advent-Of-Ascension#1038]
When you hold this Bow, you get Nausea, but it deals slightly more damage than the other Bows in the Mod. Maybe it could deal the same amount of damage than Deep Bow or a little more.

The effect could also be Blindness instead of Nausea, idk which effect would be funnier :)

**Comment by Immortallis1** [comment]
Nausea is an incredibly annoying effect that can give motion sickness and makes aiming near impossible, this really isn't a good idea for an optional item that does "slightly more damage" tbh

**Comment by Armakeen** [comment]
As you said, it would just be an optional item, so I don't see where is the problem ^^

You could choose this Bow as your main weapon, funny & unconventional :)

**Comment by Immortallis1** [comment]
"It is just an optional item" is never a good justification for anything. Why make an item that nobody is going to use because it actively annoys you? That's just adding stuff just because.

**Comment by Armakeen** [comment]
ok
