### ISSUE TITLE
Construct of Range's legs don't move

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1043]
**Mod Version**
3.1.2.b

**Describe the bug**
The Construct of Range's legs don't move as part of it's walking animation

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn a Construct of Range in creative
2. Observe it walking naturally

**Expected behavior**
The Construct of Range's legs should move

**Comment by Tslat** [comment]
Nice

**Comment by Cruuk** [comment]
Nice

**Comment by Tslat** [comment]
Fixed
