### ISSUE TITLE
Make Enforcer and Mechyon neutral, but turn hostile when their iro crate is broken

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1045]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Enforcers and Mechyons spawn in structures in Iromine, giving the appearance of them guarding the iro crates inside. Both mobs are hostile in 3.1.2.b but enforcers will become neutral to players that don't have the correct hunter level in 3.2.

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
If it is the case that enforcers and mechyons are guarding the iro crates, I think it would be cool if instead of straight up attacking the player (e.g.: being hostile), they would be neutral by default and attack if the player breaks open the iro crate they are guarding. They will then remain hostile to the player forever.

They will also aggro onto the player if the player attacks them first. Maybe as an added touch, other enforcers and mechyons not aggroed onto the player will join the fight if one is attacked. Unlike breaking the iro crate, this form of aggro isn't permanent.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
No

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Not that I know of.

**Comment by Criterion6** [comment]
If the Enforcers and Mechyons are guarding the crates against being looted/destroyed, wouldn't it make more sense for them to defend the crates from the player up front (be hostile)? Can't guard the crates if they're already gone.
