### ISSUE TITLE
Items placed in slots in mending table or whitewashing table will disappear forever if the player closes the gui

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1047]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
If you insert an item into any of the non-inventory slots of a mending table or whitewashing table, and then close the gui without taking them out, the items will disappear. They do not return to the player's inventory, nor do they get dropped on the ground.

Infusion Table and Frame Bench appear to be unaffected by this.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place a mending table or whitewashing table into your world.
2. Grab an item that can be used in it (any damaged tool or weapon/magic mending solution/magic repair dust for mending table, obsidian or whitewashing solution for whitewashing table).
3. Open the gui for mending table/whitewashing table.
4. Insert the items into the non-inventory slots.
5. Close the gui before taking them out.
6. Reopen to the gui to see that they are no longer present.

**Expected behavior**
The items will return to the player's inventory or drop on the ground when the player closes the gui with the items in the non-inventory slots.

**Comment by Tslat** [comment]
Fixed
