### ISSUE TITLE
Making an item on the infusion table gives the player a recipe in the vanilla crafting recipe book

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1048]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
Whenever you make an item in an infusion table for the first time, it causes a recipe to be unlocked in the vanilla recipe book.

Clicking on such a recipe in the book places all items except the frames into the crafting table slots, but the recipe is bogus: it doesn't make anything.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place an infusion table into the world.
2. Gather the ingredients to make a weapon at the infusion table (note: you must never have made the weapon before in the world).
3. Open the gui and make the weapon.
4. Close the gui and see yourself get a new recipe unlocked for the vanilla recipe book.
5. Check the vanilla recipe book in a crafting table to see the recipe.

**Expected behavior**
A  new recipe would not get unlocked in the vanilla crafting recipe book.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/72125928-5a09d380-3338-11ea-8dab-f97125083a07.png)

**Comment by Tslat** [comment]
Yeah this is a weird artifact of the vanilla recipe system.. I'm not sure if it's fixable from my side without removing the item crafted stat from players

**Comment by Tslat** [comment]
Fixed
