### ISSUE TITLE
Exiting a frame bench's gui with another button clicked besides the helmet frame button will cause a graphical glitch 

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1049]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
The Frame Bench gui functions as follows: you open the gui, insert a scrap metal into the leftmost slot, click the corresponding frame button that you want to create, and the frame will appear in the rightmost slot.

But, there is a bug. If you open the gui, click a button other than helmet frame, close the gui, then reopen it, the button that you clicked appears to remain clicked, but inserting a scrap metal will still craft a helmet frame.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a Frame Bench and place it down, and also get a scrap metal in your inventory.
2. Open the frame bench gui.
3. Click one of the buttons for the frames besides the helmet frame. Do not make the frame.
4. Close the gui.
5. Reopen the gui. Notice that the button you pressed when you closed the gui is still pressed.
6. Insert the scrap metal into the leftmost slot as if you were going to make a frame.
7. See that a Helmet Frame is made instead of the frame you previously selected, despite it graphically displaying as the other frame's button being clicked.

**Expected behavior**
Either the button's graphic resets to helmet frame, or the frame bench updates to craft the item it appears to be selected on.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/72126491-4f503e00-333a-11ea-9109-b75b58a8c1c2.png)

**Comment by Tslat** [comment]
Fixed
