### ISSUE TITLE
Toxxulous loot table is missing

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1057]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
A loot table for the Toxxulous mob in the Vox Ponds is not present in the mod's files.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into the mod's (for 3.2 snapshot 6) files and look for toxxulous.json (toxxulous loot table).
2. You won't find it.

**Expected behavior**
Toxxulous has a loot table.

**Comment by Tslat** [comment]
Has been fixed
