### ISSUE TITLE
New Config Option

### ISSUE THREAD

**Issue by ddteam90** [Tslat/Advent-Of-Ascension#1058]
Hi, i'm a creator of Minecraft modpack Multiversum: Crazy Sky!
We are using AoA as the main mod, but AoA Skills make some problems for us. 
Is it possible to add config option for disabling certain skill or setting it on the max level by default?

Have a good day
DigimasterHiro

**Comment by Tslat** [comment]
Is this about hunter?

**Comment by ddteam90** [comment]
Hunter and Creation. May be it would be a good idea to make a command, that will set necessary level.

**Comment by ddteam90** [comment]
Something like /aoa skill hunter set 100

**Comment by EatingSilencer** [comment]
A command already does exist. Its called aoaskill.

**Comment by Tslat** [comment]
https://adventofascension.gamepedia.com/Commands
