### ISSUE TITLE
Some blocks in creative mode are or will be unobtainable in survival mode

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1059]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
Certain blocks in the game currently are or will be unobtainable in survival mode in the next update. These blocks are:
*Green Candy - Spearmint Slugs drop these in 3.1.2.b but in 3.2 they do not. 
*Abyssal Glass
*Iro Lamp
*Blood Spikes

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into the game in 3.1.2.b or 3.2 snapshot 6.
2. Try to obtain these blocks in survival.
3. Find that you cannot.

**Expected behavior**
All these blocks are obtainable in survival.

**Comment by Tslat** [comment]
Fixed all, thanks
