### ISSUE TITLE
Another idea

### ISSUE THREAD

**Issue by KiroTheBlueFox** [Tslat/Advent-Of-Ascension#106]
What is my idea about? 

My idea is about new villages. 

The mod would add new villages to the world, villages which would be a bit more fantasy-themed, and the houses and all would be all based about the biome they generate in. 

In a village like that, there would have NPCs that have each one a job, and with who you could talk, get quests, receive rewards, exchange stuff, buy things, etc. 

Is it only that? 

Nope, if accepted, my idea could add a new biome : Mystical Forests.
The mystical forest would be a forest with normal-sized trees and giant trees, the biome would be flashy and coloful, the leaves of the trees could be blue, pink, red, yellow, green, etc. The grass would be way greener and a bit going to cyan. 

What are all the biomes I think the villages could generate in? 

Well here is the list of biomes I want the villages to generate in :
Forest : Village about forest elemental
Flower forest : same
Plains : Village about nature elemental
Hills : Village about stone elemental
Deserts : Village about fire elemental
Mesa : same
Ocean : (Villages spawn on kinds of bridges on oceans) Village about water elemental
Air : (Village floating high in the airs) Village about air elemental
Mystical Forests : Village spawning on ground or in big trees and about magic elemental

I hope you like that idea! 
Thanks for reading! 
~Kiro

**Comment by Jesuistondieux** [comment]
Maybe each village could have a pnj specialized in Runation 
For exemple:
- Forest, Flower Forest, Plains -> Life Rune
- Desert, Mesa -> Fire Rune
- Ocean -> Water Rune
- Air -> Wind rune
- Hill -> why not add a Stone or Ground Rune
- Mystical Forest -> Distortion Rune
- And we can also add a Jungle village(probably generate in trees) -> Poison Rune
