### ISSUE TITLE
Vinocorne's Blue minion (Blue Flower) is missing a loot table

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1061]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
In the files for 3.2 snapshot 6, most of Vinocorne's minions (Green Flower, Orange Flower, Purple Flower, Yellow Flower) have loot tables of their own. Blue Flower does not however.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into the mod's files and look for a blue_flower.json.
2. You won't be able to find it.

**Expected behavior**
Blue Flower should have a loot table.

**Comment by Tslat** [comment]
Fixed
