### ISSUE TITLE
Little Bam's loot table is missing

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1062]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
I know it is possible that it just isn't added yet, but seeing as King BamBamBam's loot table was worked on, I'll post this here just in case.

It appears that a loot table for Little Bam is not present in the mod's files.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into the mod's files and try to find a little_bam.json.
2. You won't be able to find it.

**Expected behavior**
Little Bam has a loot table.

**Comment by Tslat** [comment]
Yeah little bam doesn't have a loot table since he's just a spawned minion

**Comment by EatingSilencer** [comment]
> 
> 
> Yeah little bam doesn't have a loot table since he's just a spawned minion

The other boss minions have loot tables though...

**Comment by Tslat** [comment]
Not anymore
