### ISSUE TITLE
Inconsistency with boss minion loot tables

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1063]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
Most boss minions are able to drop items from their corresponding dimension world table. Vinocorne's minions (excluding Blue Flower, but that is another issue: #1061) and hydrolon can drop items from the Gardencia and L'Borean world tables respectively. If they count, the Skeletal Army mobs (minus Skeletron) drop items from the Precasia world/loot table.

Hive Worker however, cannot drop items from the Barathos World Table.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to into the loot table files for any of Vinocorne's minions, any of the Skeletal Army mobs except Skeletron, and Hydrolon.
2. See that they drop items from their dimension's world table.
3. Go into hive worker's loot table.
4. See that he doesn't drop items from the Barathos loot/world table.

**Expected behavior**
Either Hive Worker drops items from the Barathos Loot/World table, or none of the other minions drop items from their world/loot tables.

**Comment by Tslat** [comment]
All fixed, thanks
