### ISSUE TITLE
Hydrolon doesn't drop hydro stone anymore, making fighting the hydrolisk boss impossible

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1064]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
In 3.2 snapshot 6, hydrolons don't drop hydro stones anymore, making the hydrolisk boss fight impossible to complete.

Just in case this hasn't been resolved already, I'm posting this issue here.

**To Reproduce**
Steps to reproduce the behaviour:
1. Check hydrolon's loot table for hydro stones.
2. See that hydrolon doesn't drop them.

**Expected behavior**
Hydrolon drops hydro stones again or a different way to get hydro stones/fight hydrolisk is made.

**Comment by Tslat** [comment]
Has been fixed
