### ISSUE TITLE
Emberstone Axe's ability doesn't seem to work

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1067]
**Mod Version**
What version of the mod are you on?
3.2 snapshot 6

**Describe the bug**
Emberstone Axe's description states that it incinerates logs that are mined and drops xp. This only half-happens: xp is dropped but the logs aren't destroyed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place down a wooden log.
2. Grab an emberstone axe.
3. Mine the wooden log.
4. See XP get dropped but the log is still intact.

**Expected behavior**
The log gets destroyed.

**Comment by Tslat** [comment]
Fixed
