### ISSUE TITLE
Formerly a dimension suggestion

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#107]
Realized I don't actually want this

**Comment by Sagisolar** [comment]
HOLY FUCKING SHIT that's a lot to take in. This is probably one of the best suggestion I've ever seen (and I'm skeptical on added new dimension). My only critique Is that Mortician sounds like it would have the same problem with Hydrolisk. Not being very "Mini game" like. I think mini games should be about challenging your skill. Mortician sounds like a powerful mob like a boss. However Mortician sounds like interesting boss fight nether the less. Anyway amazing suggestion I'll give it a 👍.

**Comment by Immortallis1** [comment]
Thanks lol. The Mortician isn't really a boss, it's just an entity that spawns and starts chasing you and is hard to kill. The actual boss I didn't think up mechanics for as I am not too good in that department at the moment.

**Comment by Obsinym** [comment]
A fine suggestion and all, but my only complaint would be that I think we have enough chunk based dimensions already; though they may be easier to generate.  Otherwise, this is the most well thought out dimension suggestion I've seen.

**Comment by Immortallis1** [comment]
Well there's no real way to do an infinite house kind of dimension without chunk based "structures". Thanks though

**Comment by vrextachropthus** [comment]
it reminds me shyrelands a bit
