### ISSUE TITLE
Rockrider name inconsistent spelling

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1070]
**Mod Version**
What version of the mod are you on?
A bug I noticed in the 3.2 pre-sync #2

**Describe the bug**
Rockrider's name is spelled inconsistently in the 3.2 pre-sync #2. He is called both Rockrider and Rock Rider.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into the 3.2 pre-sync #2 (english file on github) ([link](https://github.com/Tslat/Advent-Of-Ascension/blob/master/lang/en_us.lang)).
2. Press Crtl + F (or equivalent on other computers) and search for "rockrider". 
3. Do Ctrl + F again and search for "Rock Rider".
4. Notice how both are used.

**Expected behavior**
Only one spelling of the boss' name is used.

**Comment by Tslat** [comment]
Fixed
