### ISSUE TITLE
All the Chargers config option does not affect certain mobs

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1072]
**Mod Version**
3.2

**Describe the bug**
Title speaks for itself, so far i've seen it does not affect Lunarchers and Runicorns

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the All the Chargers config option to true
2. Spawn the unaffected mobs

**Expected behavior**
They should be chargers

**Screenshots**
![2020-01-17_21 54 32](https://user-images.githubusercontent.com/52132442/72650332-25b99700-3978-11ea-8f3b-41f518f3bbc6.png)
![2020-01-17_22 22 15](https://user-images.githubusercontent.com/52132442/72650356-3702a380-3978-11ea-9079-95d14b570640.png)

**Comment by Tslat** [comment]
Fixed for Lunarcher & Runicorn
