### ISSUE TITLE
Crash with Pam's Harvestcraft and AoA

### ISSUE THREAD

**Issue by goreae** [Tslat/Advent-Of-Ascension#1073]
Pam's Harvestcraft crashes with AoA 3.2. The game loads up fine, but create or join a world and it'll crash. I tested it with only harvestcraft and AoA installed in the instance and still crashed. Crash log attached.
[crash-2020-01-17_14.23.37-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4079363/crash-2020-01-17_14.23.37-server.txt)

**Comment by Tslat** [comment]
Fixed
