### ISSUE TITLE
Crash involving the gamerules

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1074]
**Mod Version**
What version of the mod are you on?
3.2

**Describe the bug**
Upon joining a world, the following crash occured:

[crash-2020-01-17_16.44.53-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4079379/crash-2020-01-17_16.44.53-server.txt)

The world was an old world created in 3.1.2.b, with several other mods.

**To Reproduce**
Steps to reproduce the behaviour:
1. I guess you could try recreating the mod setup the best you can. Not sure what caused the crash - I was told by the person it crashed for that it could be applied energistics.

**Expected behavior**
The game doesn't crash.

**Comment by Tslat** [comment]
Fixed
