### ISSUE TITLE
Fragmented anima stones don't consume in survival

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1075]
**Mod Version**
What version of the mod are you on?
3.2

**Describe the bug**
When using fragmented anima stones in survival mode, they don't consume, allowing them to be used infinitely

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to survival mode.
2. Get a fragmented anima stone.
3. Use it as bonemeal (on a crop, grass block, etc)
4. See the fragmented anima stone not consume.

**Expected behavior**
The fragmented anima stone consumes when used in survival mode.

**Comment by Tslat** [comment]
Fixed
