### ISSUE TITLE
No clue what is happening

### ISSUE THREAD

**Issue by Nessark007** [Tslat/Advent-Of-Ascension#1076]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2020-01-17 18:28:19 EST
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Advent Of Ascension (aoa3)
Caused by: java.lang.NullPointerException
    at net.tslat.aoa3.advent.AdventOfAscension.registerGameRules(AdventOfAscension.java:162)
    at net.tslat.aoa3.advent.AdventOfAscension.fmlServerStarted(AdventOfAscension.java:128)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:804)
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:302)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:488)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3633527096 bytes (3465 MB) / 8489271296 bytes (8096 MB) up to 10737418240 bytes (10240 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 29, tallocated: 77
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 35 mods loaded, 35 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State   | ID                   | Version                   | Source                                                    | Signature                                |
       |:------- |:-------------------- |:------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA  | minecraft            | 1.12.2                    | minecraft.jar                                             | None                                     |
       | LCHIJA  | mcp                  | 9.42                      | minecraft.jar                                             | None                                     |
       | LCHIJA  | FML                  | 8.0.99.99                 | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
       | LCHIJA  | forge                | 14.23.5.2847              | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
       | LCHIJA  | techguns_core        | 1.12.2-1.0                | minecraft.jar                                             | None                                     |
       | LCHIJAE | aoa3                 | 3.2                       | aoa3-3.2.jar                                              | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCHIJA  | jei                  | 4.15.0.291                | jei_1.12.2-4.15.0.291.jar                                 | None                                     |
       | LCHIJA  | quark                | r1.6-177                  | Quark-r1.6-177.jar                                        | None                                     |
       | LCHIJA  | autoreglib           | 1.3-32                    | AutoRegLib-1.3-32.jar                                     | None                                     |
       | LCHIJA  | betternether         | 0.1.8.6                   | betternether-0.1.8.6.jar                                  | None                                     |
       | LCHIJA  | bookworm             | 1.12.2-2.3.0              | bookworm-1.12.2-2.3.0.jar                                 | None                                     |
       | LCHIJA  | casinocraft          | v06                       | CasinoCraft_1.12.2_v06.jar                                | None                                     |
       | LCHIJA  | coloredredstone      | 1.3.2                     | Colored+Redstone-1.3.2.jar                                | None                                     |
       | LCHIJA  | customnpcs           | 1.12                      | CustomNPCs_1.12.2-(01Oct19).jar                           | None                                     |
       | LCHIJA  | ptrmodellib          | 1.0.4                     | PTRLib-1.0.4.jar                                          | None                                     |
       | LCHIJA  | props                | 2.6.3                     | Decocraft-2.6.3_1.12.2.jar                                | None                                     |
       | LCHIJA  | cfm                  | 6.3.1                     | furniture-6.3.1-1.12.2.jar                                | None                                     |
       | LCHIJA  | justenoughdimensions | 1.6.0-dev.20191019.172643 | justenoughdimensions-1.12.2-1.6.0-dev.20191019.172643.jar | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA  | jeid                 | 1.0.3-48                  | JustEnoughIDs-1.0.3-48.jar                                | None                                     |
       | LCHIJA  | libraryex            | 1.0.12                    | LibraryEx-1.12.2-1.0.12.jar                               | None                                     |
       | LCHIJA  | testdummy            | 1.12                      | MmmMmmMmmMmm-1.12-1.14.jar                                | None                                     |
       | LCHIJA  | moarsigns            | 6.0.0.11                  | MoarSigns-1.12.2-6.0.0.11.jar                             | 5a57c7d1420cf4c58f53ea2a298ebef8215ede63 |
       | LCHIJA  | morecommands         | 2.1.1                     | MoreCommands_2.1.1_mc1.12-1.12.2.jar                      | None                                     |
       | LCHIJA  | moreplayermodels     | 1.12.2                    | MorePlayerModels_1.12.2-(05Dec19).jar                     | None                                     |
       | LCHIJA  | neat                 | 1.4-17                    | Neat+1.4-17.jar                                           | None                                     |
       | LCHIJA  | netherex             | 2.0.15                    | NetherEx-1.12.2-2.0.15.jar                                | None                                     |
       | LCHIJA  | reborncore           | 3.16.4.478                | RebornCore-1.12.2-3.16.4.478-universal.jar                | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA  | simpledimensions     | 1.3.1                     | SimpleDimensions-MC1.12-1.3.1.jar                         | None                                     |
       | LCHIJA  | techguns             | 2.0.2.0                   | techguns-1.12.2-2.0.2.0_pre3.1.jar                        | None                                     |
       | LCHIJA  | tfa                  | 1.1                       | TFA_1.1.jar                                               | None                                     |
       | LCHIJA  | personal_server      | 1.0.0                     | Trial5.jar                                                | None                                     |
       | LCHIJA  | vanillafix           | 1.0.10-SNAPSHOT           | VanillaFix-1.0.10-99.jar                                  | None                                     |
       | LCHIJA  | variedcommodities    | 1.12.2                    | VariedCommodities_1.12.2(21nov19).jar                     | None                                     |
       | LCHIJA  | worldhandler         | 2.2.2                     | WorldHandler-1.12.2-2.2.2.jar                             | d6261bb645f41db84c74f98e512c2bb43f188af2 |
       | LCHIJA  | woc                  | 0.5                       | WorldOfChemistry-0.5.jar                                  | None                                     |
  Loaded coremods (and transformers): JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
                                        techguns.core.TechgunsASMTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.16.4.478
              Runtime Debofucsation 1
              RenderEngine: 1
  Suspected Mods: Advent Of Ascension (aoa3)
  Profiler Position: N/A (disabled)
  Player Count: 0 / 8; []
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 1

**Comment by Tslat** [comment]
Has been fixed in next update -is a mod conflict
