### ISSUE TITLE
New version crash about loot table did not happen before!

### ISSUE THREAD

**Issue by MagicMaxcer** [Tslat/Advent-Of-Ascension#1077]
**Mod Version**
What version of the mod are you on?

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

Loot table did not happen before it work fine but now it crashes
https://paste.dimdev.org/yufeloxecu.mccrash

**Comment by Tslat** [comment]
Known issue, fixed in next version
