### ISSUE TITLE
Four Guardians Music Bug

### ISSUE THREAD

**Issue by Criterion6** [Tslat/Advent-Of-Ascension#1078]
**Mod Version**
What version of the mod are you on?
3.2.1
**Describe the bug**
The Four Guardians' music stops in the middle of the fight.
**To Reproduce**
Steps to reproduce the behaviour:
1. Summon the Four Guardians.
2. Kill one of them.
3. The music will stop after the death of one Guardian.

**Expected behavior**
The music will persist throughout the entire battle, until the last Guardian is slain.

**Comment by Tslat** [comment]
Fixed in 3.2.2
