### ISSUE TITLE
The knockback of the "sprayer" weapons is pretty crazy

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#108]
**Describe/name the item/content this suggestion relates to**
Most of the weapons with a fire rate of 10 or 20. Mainly the sprayer weapons like Soul Storm, Eradicator, Froster, and Beamer.

**Describe the change/balance you think would be good to see**
I think the damage output of these things are fine where they are. They're basically Energy shotguns.
But a big issue I've noticed is that the massive amount of knockback these weapons put out kind of guts their damage output. The amount of knockback is absurd, it's actually kind of overpowered for all the wrong reasons. This knockback makes the sprayers knockback weapons rather than close-ranged higher damage weapons...

https://www.youtube.com/watch?v=PJYeRUYqdWo (Video demonstration)

Even if it is unintended, I don't see it as a good way to balance these weapons at all. Pretty much every other weapon that deals high damage at close range don't have this same issue. The sprayer weapons already have downsides like a low range and high energy consumption (60 Energy per second for Beamer I think!).
And I know many AoA mobs have a chance to not take knockback, but the sheer amount of projectiles coming from these things kind of nullifies that. Even for the mobs that don't take knockback at all the sprayers shouldn't have to be relegated to those specific mobs to be useful (besides I can use something like Blast Barrel for more DPS without the slow walk speed from using energy weapons and the crazy knockback haha).
Weapons like Laser Blaster and Fragment don't really have too much of the same issue but they still feature that "kind-of-overpowered" knockback.

Basically, I'm suggesting for the knockback on these types of weapons to be reduced by a pretty significant amount. It's almost sort of a buff and a nerf- nerfing the absurd knockback so that these types of weapons can utilize their damage output more, sort of buffing them in a way.
As you've seen in the video the knockback makes Beamer only deal around like 30+ damage before it knocks the mob out of range...
They can still deal a decent amount of knockback but not this much

**Add any alternative implementations you think might work**
If that doesn't work, include a hidden stat of each projectile having a 50% chance to do no knockback? I don't know.

**Include any additional background information**
Hmm... Even if Beamer's knockback is heavily reduced it seems Swarm-o-tron will still be able to compete with it in terms of close-ranged Energy weapons...

**Comment by Tslat** [comment]
Done after snapshot 9
