### ISSUE TITLE
Empowered/Nightmare Weab Reaper's HP boost doesn't work right

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1081]
**Mod Version**
3.2.1

**Describe the bug**
When a Web Reaper gets more HP from being turned into Empowered/Nightmare Web reaper, hitting it suddenly makes it lose lots of HP- bringing it back to its normal HP. It appears the extra HP isn't doing anything. When spawned from a spawn egg, the Web reaper doesn't seem to get an HP boost at all when using Nightmare flakes/Enchanted book.

Using a healing potion on it does heal it, but oddly enough it doesn't go above 122 HP when healing it. I am using Torohealth to see the HP, but it doesn't seem like a purely visual bug.

**To Reproduce**
Steps to reproduce the behaviour:
Go to a naturally spawned Web Reaper, power it up with the required items.

**Expected behavior**
Empowered/Web Reaper's extra HP working.

**Comment by Tslat** [comment]
Fixed
