### ISSUE TITLE
Lunalus portal says "the portal is strangely quiet in your presence" but the Nature portal sound plays

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1082]
**Mod Version**
3.2.1

**Describe the bug**
Post-3.0, Lunalus' portal noise intentionally has no noise. But post-3.2 it plays the Nature portal sound (the one used for Lelyetia, Precasia, +more). I think it's unintentional because it contradicts what the portal text says, and it's a bit unfitting to something like Lunalus.

**To Reproduce**
Right click Lunalus realmstone on ancient teleporter and hear the sound.

**Expected behavior**
Lunalus portal having no sound(?)

**Comment by Tslat** [comment]
Done in 3.3
