### ISSUE TITLE
Botania Integration

### ISSUE THREAD

**Issue by EnderConstructor13** [Tslat/Advent-Of-Ascension#1084]
**Describe the new feature you think would be good to add**
Life aggregator to be able to pick up AoA monster spawners

**Include any additional background information**
Its an item that lets you pick up a spawner once and I think it would be nice if it worked for AoA monster spawners aswell.

**Comment by Tslat** [comment]
Just had a look at this one
Without converting all our spawners to vanilla ones (which I can't do without removing functionality from AoA), this isn't possible as Botania hardcoded their block check to only work on vanilla spawners.

It also looks like Botania has finished development on 1.12 too so this might just be a no-go

**Comment by masterbobli** [comment]
Maybe you can add an item that works for AoA spawners




On 05/16/2020 11:06, Tslat wrote:

Just had a look at this one
Without converting all our spawners to vanilla ones (which I can't do without removing functionality from AoA), this isn't possible as Botania hardcoded their block check to only work on vanilla spawners.

It also looks like Botania has finished development on 1.12 too so this might just be a no-go
