### ISSUE TITLE
Using the Runandor portal in Mysterium screws with portal sequence

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1085]
**Mod Version**
3.2.1

**Describe the bug**
If you've entered Mysterium from somewhere like the Overworld, then go through the Runandor portal on the portal tower, it messes with the dimension sequence thing. When you go back through the Runandor portal you're back at Mysterium, but going back through the Mysterium portal just brings you to Runandor. This creates an infinite loop.

Also, doing all this generates a Mysterium portal in Runandor.

**To Reproduce**
Steps to reproduce the behaviour:
Go to Mysterium, then Runandor via portal tower, then go back to Mysterium, then try getting out of the loop without /kill.

**Expected behavior**
The portal tower Runandor portal not messing with the sequence thing

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/72664077-94194c00-39ae-11ea-895f-2f532a61e210.png)

**Comment by Tslat** [comment]
Sigh.. damned portal system

**Comment by Tslat** [comment]
Fixed
