### ISSUE TITLE
Ancient Teleporter Runandor portal shouldn't require Realm travel ticket

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1086]
**Describe/name the existing feature this suggestion relates to**
Runandor portal and realm travel ticket

**Describe the change or feature you think would be good to see**
The portal tower Runandor portal requiring Realm ticket is fine, but the Ancient teleporter version shouldn't. It doesn't make much sense, and it would be annoying having to carry the ticket every time you want to use your own portal.

I think the best way to fix this would be to make the portal tower Runandor portal and Ancient teleporter Runandor portal separate blocks. Besides the teleporter version not requiring the ticket, they'd be functionally the same.

**Include any additional background information**
Making them separate blocks could be the best way to fix this? https://github.com/Tslat/Advent-Of-Ascension/issues/1085

**Comment by Tslat** [comment]
Has been changed in 3.2.2
