### ISSUE TITLE
Hive Chamber (Dimension Idea).

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#109]
### INFO ###

This is a structure dimension like AC and Immortalist. Is not control by any god, Its controlled by the royal family of the hive.

### GENERATION ### 

Pretty much this dimension is model after a Ants nest.
The gen is under ground like. A bunch of tubes all connecting to each other make a maze in witch mobs spawn every where.

### HOW TO GET THERE ### 

The realm stones drop of the Hive King. But the realmstones are covered in bugs so you need bug spray to clean them before lighting the portal.

### MOBS ### 

Most of the mobs are textured off the hive king. Pink and bloody.

### PASSIVE ###

Hive Fly

Pretty much a bat with a head similar to Hive King.
30 seconds after spawning, It will turn into any of the hostile mobs (Doesn't count the infected mobs) from the dimension. (See below for more info).
If you kill it early It won't transform.

Hive Rebel

NPC that trades items and totems from the dimensions.
Once you trade something, the hostile mobs will then attack the rebel.

### HOSTILE ###

Lots of mobs are mobs from other dimensions but they are infected by the Hive Virus.

Hivesite

- Parasite.
- 70hp
- Inflicts melee damages.

Hivetis

- Praying Mantis.
- 80hp
- Inflicts melee damages which gives you slowness.

Hivee

- Bee
- 65hp
- Flies like the Nightfly.

Hivetula

- Tarantula
- 145hp
- They have a web that connects them to the ceiling.
- They swing with there web on the ceiling, When they hit you, you get flung back.

Hiveardier

- Bombardier beetle.
- 85hp
- Shoots projectiles which lights you on fire.

Hivematon

- 120hp
- A Automaton that has the Hive Virus.

Hivevine

- 150hp
- A Archvine but has the head of a Hive King.
- Also has the same ability as the normal Archvine.

Hive Hunter

- 100hp
- A Hunter but has the head of a Hive King.
- Has the same ability as the normal Hunter.

Royal Hive

- Rare Mob.
- 500hp
- Chooks up blood which acts like a projectile.
- Drops 1 Lunaver Coin, also a staff and spawner for the boss.
 
### BOSSES ###

Hive Emperor

- 8000hp
- Attacks using melee.
- Very slow.
- The arena you spawn in him has all normal mobs spawn (except the Royal).

His design would be similar to a Xenomorph Queen I guess.

### RAIDS ###

This dimension commits raids in Haven, Gardencia, Greckon.

Pretty much theres a chance in these dimension you find a dungeon that spawns Hivesite, Hivetis, Hivee, Hivetula, and Hiveardier. In there you can find loot and coins from the dimension. This is also how they Infect Automaton, Archvine, and Hunters.

**Comment by Immortallis1** [comment]
Upvoting because unlike cruuk I'm a nut for dimension suggestions. It's a good idea but you should add some more details and probably some more mobs that aren't based off of other mobs, to keep originality. (In other words more stuff like the mantis) I like the rebel idea.

Also what's the prince? The word "prince" doesn't appear anywhere else in the suggestion.

**Comment by Sagisolar** [comment]
Dammit I renamed to Royal Hive but didn't know I put it somewhere else.
