### ISSUE TITLE
Radiant Infusion Stones only gives 22 XP.

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1091]
**Mod Version**
What version of the mod are you on?
3.2.1

**Describe the bug**
When you use a radiant infusion stone on the Infusion Table, it only gives 22 XP. Judging by the pre-3.2 Infusion page, this is likely a typo as it should give 220 XP.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place down an Infusion Table and give yourself/get a Radiant Infusion Stone.
2. Go to creative mode to skip level requirements.
3. Use the radiant infusion stone on the Infusion Table.
4. See that it only gives 22 XP.

**Expected behavior**
The Radiant Infusion Stone gives more XP - for a level 70 Infusion Stone 22 is far too small.

**Comment by Tslat** [comment]
Fixed
