### ISSUE TITLE
Nethengeic Wither dropping stuff from its old table and not the new one

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1093]
**Mod Version**
3.2.1

**Describe the bug**
Nethengeic Wither still drops its old drops in the same way, not pulling from its new table at all.

**To Reproduce**
Steps to reproduce the behaviour:
Kill Nethengeic Wither and see the drops.

**Expected behavior**
Nethengeic Wither only pulling from its new loot table.

**Comment by Tslat** [comment]
Fixed
