### ISSUE TITLE
Shadowlord also dropping stuff from its old table and not the new one

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1094]
**Mod Version**
3.2.1

**Describe the bug**
Shadowlord still drops its old drops in the same way, not pulling from its new table at all.

**To Reproduce**
Steps to reproduce the behaviour:
Kill Shadowlord and see the drops.

**Expected behavior**
Shadowlord only pulling from its new loot table.

**Comment by Tslat** [comment]
Fixed
