### ISSUE TITLE
Full Moon event mobs spawning on first night

### ISSUE THREAD

**Issue by Criterion6** [Tslat/Advent-Of-Ascension#1095]
**Mod Version**
3.2.1

**Describe the bug**
Without using commands to change the time, the full moon event mobs spawn on the first night despite not being supposed to.

**To Reproduce**
1. Create a new world.
2. Wait until night time.
3. Observe as full moon mobs spawn.

**Expected behavior**
Full moon mobs will not spawn on the first night, but will spawn on every full moon night after that.

**Comment by Tslat** [comment]
Fixed
