### ISSUE TITLE
Unify "Energy" and "Magic" damage for mobs

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1096]
**Describe/name the existing feature this suggestion relates to**
The mob damage types "Energy" and "Magic".

**Describe the change or feature you think would be good to see**
When testing Runic armor's full set effect, I noticed that it wasn't working with stuff like Goblin, Kaiyu, Construct of range, Shyre troll, etc. When it was working with Arc wizard. Arc wizard was also dealing kb, which isn't something the magic-looking projectiles usually do.

Upon looking in the source, I noticed that only 3 mobs actually deal magic damage- Arc wizard being one of them. Everything else with a "magic"-looking projectile deal "Energy damage" (the one with no kb).
![image](https://user-images.githubusercontent.com/38159897/72670482-9e5d3980-39f2-11ea-8ed3-1c1c019e08ba.png)

Probably unintentional, because if it isn't then it feels unintuitive to have 2 damage types that look the exact same. Only having 3 mobs with magic damage doesn't help Runic armor very much. "Physical" ranged damage defines itself pretty well- just any physical-looking projectiles and kb.

Whether they're unified or all turned to energy damage or magic damage, I really want the non-kb to stay around for the "non-physical" damage. I think it's a really cool way of differentiating physical and non-physical damage without having to look up the mob to see what type of damage it does.

**Comment by Criterion6** [comment]
Perhaps this is related to a previous suggestion of yours, #739

**Comment by Tslat** [comment]
Done
