### ISSUE TITLE
Ender Dragon doesn't drop anything

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#1097]
Was on 3.2 because I forgot to update before testing and it wasn't in the changelog

The Ender Dragon doesn't pull anything from its loot table. To reproduce, just kill it and nothing will drop (have even tried teleporting all entities to me). Have done multiple times in creative and once in survival and nothing has dropped except experience orbs.

**Comment by Tslat** [comment]
Fixed
