### ISSUE TITLE
Vox ponds' task doesn't work

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1099]
**Mod Version**
3.2.1

**Describe the bug**
Right clicking a Creeponia trader with the blank realmstone while wearing makes the text pop up, but the Blank realmstone remains the same.
Also, it doesn't seem you actually need Hazmat armor to trigger the dialogue at all, just the Blank realmstone. I'm guessing that's also unintentional.

**To Reproduce**
Steps to reproduce the behaviour:
Attempt to do the Vox ponds task, both with and without Hazmat armor.

**Expected behavior**
The Blank realmstone turning into Vox ponds realmstone and needing the armor to trigger it.

**Comment by Tslat** [comment]
Fixed
