### ISSUE TITLE
Make realm travel ticket non-stackable

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#110]
Mainly so that we can put Innervation on it.

I've never had it happen to me, but the thought of losing a realm travel ticket in Runandor and Greckon is a very terrifying one, mainly because they're expensive and no one likes farming Runic golems.

I don't see any harm in making it non-stackable, it's already a pretty important item, and wouldn't really negatively affect anyone since you don't even see people with more than 1 ticket at time (unless they're super rich from pre-nerf Foraging).

Losing a Megagun may suck... but at least I don't need it to access certain dimensions.

**Comment by Sagisolar** [comment]
Yeah but you need the Megagun to actess to the ### BIG GUN ### dimension

**Comment by Sagisolar** [comment]
Yeah but you need the Megagun to actess to the ### BIG GUN ### dimension

**Comment by papabean** [comment]
Seems like a simple addition and it's a game-changing one at that (in terms of how much intervention on a realm travel ticket can save you from a lot of grinding).

Support.
