### ISSUE TITLE
Redstone ore doesn't work with Deeplands' task

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1100]
**Mod Version**
3.2.1

**Describe the bug**
Mining Redstone ore at Bedrock level does not seem to change Blank realmstone to Deeplands. All the other ores seem to work fine. Only Redstone is the exception.

**To Reproduce**
Steps to reproduce the behaviour:
Mine Redstone ore at Bedrock level.

**Expected behavior**
Redstone ore working with Deeplands' task.

**Comment by Tslat** [comment]
Fixed
