### ISSUE TITLE
Hungry Mending table 

### ISSUE THREAD

**Issue by Sageking10** [Tslat/Advent-Of-Ascension#1101]
**Mod Version**
Aoa3 3.2.1
**Describe the bug**
The mending table uses a full stack of magic mending solution, for it should only use one.
**To Reproduce**
Steps to reproduce the behaviour:
1. get mending table and 64 of magic mending solution.
2. get a damaged item and repair it.
3. ???
4. All magic solution is gone...

**Expected behavior**
It should only use one
**Screenshots**

**Comment by Tslat** [comment]
Fixed
