### ISSUE TITLE
Gardencia mobs become invincible in Candied water (except Carrotop)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1103]
**Mod Version**
3.2.1

**Describe the bug**
When a Gardencia mob touches Candied Water, they seem to heal back to full HP every tick, essentially making them invincible.
In contrast, Carrotop only gets minor regen, and only has to touch Candied water once to drop the realmstone, whether it's still in it or not. The others do not drop it even after being pushed out of the Candied water and then slain.

**To Reproduce**
Steps to reproduce the behaviour:
Attempt to kill a Gardencian mob in Candied water/Push them out and try to get L'Borean realmstone from them. (other than Carrotop)

**Expected behavior**
Gardencia mobs not being invincible when in Candied Water. Also I think it's safe to assume that Carrotop was working correctly so yeah.

**Comment by Tslat** [comment]
Fixed
