### ISSUE TITLE
Lelyetia Gravity Trap

### ISSUE THREAD

**Issue by Fleega** [Tslat/Advent-Of-Ascension#1104]
**Mod Version**
What version of the mod are you on?
3.2.1
**Describe the bug**

It is possible to get stuck hovering at y=56 in Lelyetia by falling down the + shaped holes

**To Reproduce**
Steps to reproduce the behaviour:
Travel into Lelyetia
Find one of the holes with a + shape that is two blocks tall
Jump into it and move under the + shaped part of the grass
Get caught under the grass blocks and attempt to move out from under it

**Expected behavior**
Falling or rising gravity to send the player back up or drop them down

Video example for simplicity:
https://youtu.be/LwR4fUuQX2s

**Comment by Tslat** [comment]
Fixed
