### ISSUE TITLE
Runicorn rider spawns a Runicorn every time it's hit

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1105]
**Mod Version**
3.2.1

**Describe the bug**
Every time Runicorn rider takes damage, a Runicorn spawns where it's standing. Doesn't seem too intentional to me lol

**To Reproduce**
Deal damage to a Runicorn rider

**Expected behavior**
Runicorn rider only spawning a Runicorn after it dies, like it did in 3.1.2.b and lower.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/72674012-8f907a00-3a26-11ea-9de5-6a0a11923969.png)

**Comment by Tslat** [comment]
Fixed
