### ISSUE TITLE
Add a cooldown to Runic armor's full set effect

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1111]
**Describe/name the existing feature this suggestion relates to**
Runic armor's full set effect.

**Describe the change or feature you think would be good to see**
Runic armor's full set bonus makes it so that when you get hit by magic damage you get 2 absorption hearts for ~10 seconds. The thing with this effect is that it has no cooldown- it always get reapplied when hit by magic damage. Essentially this makes you near-invincible to magic damage. An Arc Wizard could not kill me at all, I never even took any damage at all since the absorption hearts kept refreshing.

Which is why I think it would be good to add a small cooldown to the absorption activating. I think a cooldown of 5-10 seconds after the effect ends before it can be applied again would be best. Would still be useful but not busted.

**Comment by Tslat** [comment]
Done
