### ISSUE TITLE
Troll Trader's name is whited out

### ISSUE THREAD

**Issue by VBGaming** [Tslat/Advent-Of-Ascension#1112]
**Mod Version**
3.2.1

**Describe the bug**
Sorry for not having a screenshot, but yesterday when I was testing 3.2 on a creative world I happened to find a Troll Trader. However, when I interacted with it to see if it had any change in its drops, I noticed that its name on the GUI was a completely white box, as if it was both written in white and had a white background.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a Troll Trader
2. Interact with it to open its GUI
3. Look at the box that should have its name in the GUI

**Expected behavior**
I expected to see "Troll Trader" written in the box

**Screenshots**
Didn't think of taking one on the spot, I can go do one if you really need one

**Comment by Tslat** [comment]
Fixed
