### ISSUE TITLE
Occulent/Visage's illusions should be able to look around

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1113]
**Describe/name the existing feature this suggestion relates to**
The fake mobs Occulent/Visage spawns

**Describe the change or feature you think would be good to see**
Occulent and Visage's new ability is pretty cool, though one thing that bugs me is that the clones always face in the exact same direction (south).

(The ones not looking in that direction are the real ones)
![image](https://user-images.githubusercontent.com/38159897/72684488-a5895380-3a95-11ea-9d11-c77ffb178ed6.png)

It doesn't exactly make the illusion ability very subtle. And even if it is intended, it feels out of place. I think the illusions should be able to passively look around like any mob does (if possible). It would allow the illusions to be a bit more subtle and wouldn't stick out like a sore thumb.

**Comment by Tslat** [comment]
They don't move because they're only on the client (not on the server and so don't get ticked to move)
I'll put it on the list to look at sometime

**Comment by Sonicwave** [comment]
Even if they can't look around, it might be nice if they were spawned looking in random horizontal directions for the same reasons.
