### ISSUE TITLE
You can get the Greed curse from enchantment table

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1114]
**Mod Version**
3.2.1

**Describe the bug**
When enchanting via the Enchantment table, it appears you can get the Greed enchantment from it. The other curse enchantments cannot be obtained from the Enchantment table, leading me to believe it's not supposed to be here.

**To Reproduce**
Steps to reproduce the behaviour:
Enchant items in the Enchantment table (mainly guns) until you get one with Greed.

**Expected behavior**
Greed not appearing in the Enchantment table. It seems silly to have a detrimental enchantment that can screw over weapons if you get unlucky.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/72684848-e5056f00-3a98-11ea-8695-f9ad9a52dd0f.png)
![image](https://user-images.githubusercontent.com/38159897/72684859-ffd7e380-3a98-11ea-87b5-99d83081cd29.png)

**Comment by Chubblezap** [comment]
Still happening as of 3.2.3

**Comment by Tslat** [comment]
Is intended at the moment to help balance out enchantments
