### ISSUE TITLE
Knight armor gives strength regardless of current HP

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1116]
**Mod Version**
3.2.1

**Describe the bug**
It seems that when wearing a full set of Knight armor, you get the strength boost no matter what your HP currently is. The description says you get it at when below 20% HP, leading me to believe it's not working right.

**To Reproduce**
Steps to reproduce the behaviour:
Wear a full set of Knight armor.

**Expected behavior**
Knight armor only giving strength at below 20% HP.

**Comment by Tslat** [comment]
Fixed
