### ISSUE TITLE
I feel like Brace shouldn't be in enchantment table

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1118]
**Describe/name the existing feature this suggestion relates to**
Brace in enchantment table

**Describe the change or feature you think would be good to see**
Brace is an interesting enchantment, it's a specific enchantment that forces- but also allow guns to be used in offhand. 
With this is mind, I feel like having Brace be a possible enchantment from Enchantment table isn't the best idea. If you happen to get Brace you kind of get screwed over to an extent, as the gun essentially becomes unusable other than in the offhand, which may not be ideal for some, especially with the -speed you get with a gun in offhand.

**Add any alternative implementations you think might work**
You could also make it so Brace doesn't completely restrict a weapon to offhand-only.

**Comment by Tslat** [comment]
That's the point of the enchanting table

You don't get to choose good and bad enchants, you just get enchants

**Comment by Cruuk** [comment]
> 
> 
> That's the point of the enchanting table
> 
> You don't get to choose good and bad enchants, you just get enchants

The random factor is fine. But in the case of vanilla MC you don't really have to worry about enchantments that can be hugely detrimental depending on someone's playstyle (other than thorns consuming more dura but that's way more minor). I feel like people may feel frustrated at the prospect of such a gameplay-changing enchantment that can be randomly applied. Even if you get really shitty RNG at an enchantment table, it doesn't restrict your item to a specific playstyle.
It's like having an enchantment that doubles sword damage but only when looking straight down and dealing no damage otherwise, not everyone will want it.
