### ISSUE TITLE
Re-using Angels & Demons assets (+possible way to implement Necromancer without stress)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#112]
**Describe/name the existing feature this suggestion relates to**
The weapons and armor related to Angels & Demons that were in the game for a bit before being removed (+Demon Staff because that wasn't in the game). Also Necromancer.

**Angels & Demons sprites**
Ah yes, "Angels & Demons", a phrase that will forever live in infamy. What made this mentioned update slightly more special from other ones was that we did actually have some of it's content in the game at some point: Demon Bow, Demonic Destroyer, and Demon Armor (didn't work because no mobs but hey it was there). Demon staff wasn't in the game, but considering we have a sprite and a rough idea of the ability, I guess it counts...
![image](https://user-images.githubusercontent.com/38159897/48636705-7acad900-e980-11e8-8dda-fa94eb0bd209.png) 
![image](https://user-images.githubusercontent.com/38159897/48636715-81595080-e980-11e8-81a9-0a9fb9c9b108.png)
![image](https://user-images.githubusercontent.com/38159897/48636726-87e7c800-e980-11e8-925a-340ab4ff675d.png)
![image](https://user-images.githubusercontent.com/38159897/48636728-8cac7c00-e980-11e8-9b6e-0d8d8b3ecae2.png)

I know this is not even close enough to "revive" the update at all (please no), but it would be sad to leave these sprites in the dust. They look pretty cool, and (as far as I know) aren't ripped from anything. So yes I think these sprites can be re-used for future content. They don't need to have the same abilities they had/planned to have, nor does it even have to specifically be "demonic"-themed, can just be something red or something. These sprites can be used for potential new content relating to Abyss, Nether, or Barathos Underworld for example.

**Necromancer**
I'm sure Scimi just loves hearing this name again. I know Necromancer has become sort of a joke now because of being "mentioned" and all, but to this day I still find the concept interesting. Unfortunately the reality is is that implementing that concept would be very strenuous. Just imagine having to think of 20+ different abilities for 1 boss, along with having to make a new one every time you want to add a new dimension.

However, if adjustments are made to the concept then I believe it can become more manageable to implement.

1. Necromancer would still be spawnable in multiple dimensions, but would be **limited** to the **Erebon dimensions**. Coming up with 6-7 abilities would be a lot more tolerable than 20+. (to be honest they don't even need to be completely different abilities, can just be the same ability(s) but modified per dimension). Adding new dimensions wouldn't be as much of a concern either since it's only 1 faction you have to worry about. (Immortallis wouldn't count because he probably shouldn't be spawnable in dimensions like that or AC to be honest)

Or

2. (probably the easier one) Necromancer could still be spawned in any dimension (except AC/Immortallis), but his ability would depend on **what god rules it**. No matter how many new dimensions are added, Necromancer would always be limited to 5-6 abilities. Depending on if Luxon, Erebon, Selyan, Pluton, Krasaun(?), or no one rules it (Overworld).
*Note: Krasaun's a bit of a special case, because I get the feeling Necromancer wouldn't work in Labricon. Maybe he's go through walls or something? I don't know. Basically Krasaun doesn't need an exclusive ability for Necro and it could just be the abilities of all 4 gods in one.*

You could even make the abilities themselves based on the god, health regen/life steal for Luxon, fire/wither for Erebon, etc.
If a dimension is ruled by more than 1 god (and isn't a minigame dimension), Necromancer would simply use both abilities of the gods that rule it. (would use his Luxon and Selyan abilities in Everland, etc.)

**Include any additional background information**
If Necromancer is actually implemented, where would you get his spawning item if he doesn't have a true home dimension?

The way I always saw it is that it would be some out of the way thing where you would get various materials from different dimensions (mainly Erebon ones +Barathos underworld?) to make his spawner. But it's just a thought.

**Comment by Sagisolar** [comment]
Back in 2.4b I was quite hyped about Necromancer. Don't know why, probably because his design give a good character.

I don't think you should be able to spawn him in the Overworld, that would be quite cheap. I really like the idea of a Non-Dimensional Boss, but I think the drops should differ by what dimension is harder than others. Lunalus is probably going to biggest loser if the drops were all the same cause of that generation.

**Comment by Immortallis1** [comment]
jazz hands hydra

**Comment by Immortallis1** [comment]
jazz hands hydra

**Comment by Cruuk** [comment]
> 
> 
> jazz hands hydra

Gamer

**Comment by DiamondWalker** [comment]
Good ideas. I do think the Demonic items should stay as Necromancer drops (or maybe Necromancer would drop different materials depending on the dimension and those can be combined into the items?). I do think the abilities should stay the same. Having an army of demons sounds satisfying.

**Comment by Cruuk** [comment]
> 
> 
> Good ideas. I do think the Demonic items should stay as Necromancer drops (or maybe Necromancer would drop different materials depending on the dimension and those can be combined into the items?). I do think the abilities should stay the same. Having an army of demons sounds satisfying.

I didn't really mention the whole "combine drops into weapons/armor" thing since I figured that was more of a given with Necro's concept.

As for the abilities, I think it's ok if they stayed the same as well.
IIRC Demonic Destroyer was just a regular gun that did like 25 damage at a moderate speed with no abilities, it would perfectly fit in. Though it's sprite suggests it could become a shotgun instead.
I think Demon bow's ability is gonna become an attribute for all Archerguns (arrows doing more damage the farther they fly), so it may likely be changed if the sprite is offivially added.
Demon staff along with Demon armor always seemed like alternative latergame versions of the Rosidian stuff which does sound pretty neat. Would be nice to not be limited to Rosidian and Creation armor when it came to armor sets for Summoners.

**Comment by Cruuk** [comment]
To be honest, it would probably be better to actually make completely original content at this point instead of relying on stuff from a dead update. And yet some people still yearn for it, how sad.
