### ISSUE TITLE
wonky sniper recoil when scoped

### ISSUE THREAD

**Issue by Epic428** [Tslat/Advent-Of-Ascension#1120]
Testing different rifles out I noticed that when scoped the recoil return is at least twice the distance as the initial recoil. To be more clear, if you place a block down as a target and stand say 16 blocks away, and fire at the center of the target the sniper will raise up about 1-2 blocks and then when returning back to center it actually drops down about 1-2 blocks past center.

When using a sniper without the scope the gun recoils and returns to roughly starting position. 

If more info is needed or a clearer example, I can produce a video showing what happens.

**Comment by Epic428** [comment]
https://clips.twitch.tv/SuspiciousEnjoyablePicklesThisIsSparta

Streaming mod currently, clipped what the sniper recoil looks like

**Comment by Tslat** [comment]
Thanks for the vid

**Comment by Epic428** [comment]
No problem. I tried looking through the code to see if I could figure out what was wrong in the math. But I got as far as when the data gets sent to the client. And couldn’t figure out what happened after that.

From what I could tell the time for the animation was dependent upon the firing delay value but from what it looked like it made one massive jump on the return and stepped on initial raise. Not sure if that’s the issue or not. Later when I’m home I could find the relative class file and lines.

**Comment by Epic428** [comment]
Actually I found the class and lines. It’s in a lentEventHandler.java the doRecoil function lines 204-209

Specifically,

‘
private void doRecoil() {
		final EntityPlayerSP player = Minecraft.getMinecraft().player;

		if (player == null)
			return;

		if (recoilTicksRemaining >= recoilTicks - 5) {
			player.rotationPitch -= recoilAngle / (4.0f * (SniperGuiRenderer.isSniping ? 4 : 1));
		}
		else {
			player.rotationPitch += recoilAngle / (35.0f  * (SniperGuiRenderer.isSniping ? 2 : 1));
		}
	}’

(Can’t get code to format correctly)

From what I’m seeing the first half of the recoil is increments each tick and then when “recoilTicksRemaining” reaches the right value and it reverses, the reverse is done in one massive jump. As far as I can tell this code runs as is regardless of what gun is used and whether the player is sneaking/scoped or not. In addition the baseSniper.java applies the “control” enchantment modifier only when scoped. But it seems no matter what calculation is done in the sniper class the result gets passed to this client event handler function.
