### ISSUE TITLE
Big Blast/Blissful Blast's projectile causes an explosion on impact but has no description mentioning this

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1124]
**Describe/name the existing feature this suggestion relates to**
Big Blast/Blissful Blast

**Describe the change or feature you think would be good to see**
As the title says, I think it should have a description saying the projectile explodes on hit, mainly for the sake of consistency.

**Comment by Tslat** [comment]
Done
