### ISSUE TITLE
Increase certain overworld mob spawnrates

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#1125]
It the 4-6 hours I have in 3.2, I've only seen about 10 AoA mobs total. While this is fine for the daytime mobs, I think the nighttime, event, and (especially) the underground mobs should have a higher spawn rate.

The reason I think night mobs should spawn more often is because night is meant to be dangerous, but currently there isn't much reason to hide from the night. That might just be personal preference tho.

Events should probably get more spawns too. Usually events end up being 1-2 mobs, if any at all.

And finally, the one I think _absolutely need to be changed_ are the underground mob spawns. I mined for 1-2 hours; enough to get:

-A ruined teleporter
-~15 diamonds
-~13 amethyst
-1 jade
-Several pieces of runium

In all that time, the only mobs I saw or heard (even using a minimap) were a ghost and a void charger. _That's it._ Not only does this make it horribly difficult to grind certain items (like void scales), it's also extremely boring. There isn't any challenge or threat. If you want you can just rush into unexplored caves with little to no chance of death, because I doubt anyone will die because of having to fight a single mob every 30 minutes or so.

**Comment by Tslat** [comment]
Try playing with the spawn modifier set to 1, let me know what the spawns are like then

**Comment by DiamondWalker** [comment]
What's the spawn modifier? Is it something in the config?

**Comment by Tslat** [comment]
yes

**Comment by Eneeee** [comment]
same problem here but sorry i can find the modifier in the config, can u help me

**Comment by Tslat** [comment]
The AoA config doesn't have those options in 1.7.10
