### ISSUE TITLE
CreativeCore outline issue

### ISSUE THREAD

**Issue by Zack7292** [Tslat/Advent-Of-Ascension#1126]
**Mod Version**
3.2.1

**Describe the bug**
here a screen of my issue since its a visual issue: https://imgur.com/rw7vyfW

**To Reproduce**
Steps to reproduce the behaviour:
1. open minecraft with the latest version of this mod and creative core
2. go in a game
3. open the gui
**Expected behavior**
i expected it to not have this weird black outline

**Screenshots**
https://imgur.com/rw7vyfW

Btw in 3.1.2b it was completely black and we weren't even seeing the icons

**Comment by Zack7292** [comment]
forgot to say, take the latest version of creative core

**Comment by CreativeMD** [comment]
Not sure what could cause this issue, but maybe my mod does not set alpha to enabled. So you might need to do that before rendering `GlStateManager.enabledAlpha();`.

**Comment by Tslat** [comment]
@CreativeMD If you're disabling alpha for your operations, you should be reverting it to its default state.

**Comment by Tslat** [comment]
This one should be fixed in 3.2.2

**Comment by CreativeMD** [comment]
@Tslat I usually reset everything after rendering, but there is no default for these things. Glad you could solve it!
