### ISSUE TITLE
Hitting Hive King while he is growing makes him disappear and stop spawning

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#1127]
Using 3.2.1. Thought this was because I had a really strong Strength effect, but then I removed it and changed to survival mode and he still despawned when hitting him.

**Comment by Tslat** [comment]
I had two ways of handling this. I either make him invulnerable, or I allow players to cancel his spawn.
Allowing him to take a hit messes with his position and healing and... stuff
