### ISSUE TITLE
[1.12.2] Stray White Pixels appear on the skill icons if you have Thamucraft installed+ Skill Icon Fade-Out oddity.

### ISSUE THREAD

**Issue by Z-Tunic** [Tslat/Advent-Of-Ascension#1128]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 4
AoA3-3.2.1
Baubles-1.12-1.5.2
jei_1.12.2-4.15.0.291
Thaumcraft-1.12.2-6.1.BETA26

-----

Figure I post here first... anyways... there's a minor visual oddity that occurs if you have Thaumcraft installed. The skill icons get these stray white pixels in both the GUI & the icon that appears at the top of the sceen. Here's an image of what it looks like.

![](https://cdn.discordapp.com/attachments/377171551155650560/669015168356712461/aoathaumcraftstraypixel.PNG)
Left Side:
Thaumcraft is installed. I highlighted the spots with red square outlines which shows the stray white pixels.

Right Side:
No signs of stray pixels.

-----

One more thing to mention is that the skill icons don't fade-away if Thaumcraft is installed, it appears and then disappears with no fading. If it isn't installed... the icon fades away as usual... kinda, it fades and then sometimes it instantly reappears and then disappears a half second or so later.

**Comment by Tslat** [comment]
Is the bottom of the screen purple too?

**Comment by Tslat** [comment]
Have no idea why this would be happening..

**Comment by Tslat** [comment]
Finally found it
