### ISSUE TITLE
Rock Candy and Crystal grass aren't transparent

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#113]
**Mod Version**
3.0 snapshot 7

**Describe the bug**
Normally these blocks are transparent (crystal grass is very partially transparent) but they don't appear to be transparent here.

Oddly enough though, they still retain their transparent qualities when held in the player's hand, but don't retain it once placed down. They also retain the transparency as a dropped item as well. 

**To Reproduce**
Place the block down

**Expected behavior**
... I expected it to be transparent when placed down?

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/48668508-ed80a500-eaa3-11e8-8a2d-290aa2634793.png)
![image](https://user-images.githubusercontent.com/38159897/48668523-2f115000-eaa4-11e8-922a-eb3c35e881d0.png)

**Comment by Tslat** [comment]
I don't believe this was intentionally done in 1.7.10. Minecraft's renderer auto-selects values roughly in the colour region that crystal grass uses, and makes it transparent based on the hue.

I don't intend to replicate it in 1.12 as it's not a function that will work properly in any regards, either offering full transparency through the block for some reason, or only partially (as is present currently).

I'll have a look at making the item non-transparent instead
