### ISSUE TITLE
Just ideas for new enchantments

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1130]
**Describe the new feature you think would be good to add**
Mainly just spitballing. The AoA enchantments are a lot more accessible so I don't think it would hurt to have more.

**__Reserve__** - Applicable to Archerguns, Guns, Shotguns, Snipers, and Cannons.
Adds a chance to not consume ammo, I know it's a bit of an injoke but I seriously think it could work as an enchantment. It would add a 10% chance to not consume ammo per tier, going up to II, with maybe a Reserve III from the Infusion skill.

**__Unholster__** - Applicable to Archerguns, Guns, Shotguns, Snipers, Cannons, and Blasters.
Slightly reduces Unholster time because why not. It would reduce unholster time by 5% per level, going up to III-IV (maybe the highest one would be Infusion only).

**__Blast__** - Applicable to Cannons.
Increases a cannon's additional armor damage, basically like Shell but for armored enemies. Would go up to III(?).

**__Surge__** - Applicable to Blasters.
When getting a kill with a Blaster that has this Enchantment, gain some Energy back. It could be 6 Energy gained per level, going up to III, with a IV being Infusion-only.

**__Revenge__** - Applicable to Vulcanes.
Adds +4 damage to Vulcanes. Goes up to I, with a II and maybe even a III being Infusion-only.

**__Scorched Shot__** - Applicable to Snipers.
Like Flame/Fire Aspect... but for Snipers. I imagine such a fast bullet would be hot to the touch. Could deal the same amount of fire damage as Fire aspect, going up to II. I was thinking maybe just making the Flame enchantment work on Snipers, but I wasn't sure if that was possible so there is this.

**__Lightweight__** - Applicable to Guns, Archergun, and Staves (and maybe Scythes?).
When holding an item enchanted with this, gain a small speed boost. Would add +5% speed per level, going up to II, with II being Infusion only? (Honestly I could not think of any other Staff enchantment that wasn't just Archmage but with a TWIST)

**__Influence__** - Applicable to Tablets.
Increases a tablet's radius of effect. A tablet's radius is increased by 25% per level, goes up to II. Since this one is a bit more odd, it could be Infusion-only (other than books in chests). Though if we're moving away from that, maybe just make II Infusion-only.

One thing to note: I checked, and tablets are unstackable so they can be candidates for an enchantment, but if you place one on the ground and pick it back up the enchantment disappears so...

**Comment by Fleega** [comment]
I support this because I was told to.
(This comment was NOT collected as part of a promotion)
