### ISSUE TITLE
Greatblades do not deal damage when changing controls

### ISSUE THREAD

**Issue by egogowa** [Tslat/Advent-Of-Ascension#1134]
**Mod Version**
3.2.1

**Describe the bug**
When you change the attack button, greatblades stop dealing damage. Swords or mauls seem working correct

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to control settings
2. Сhange the attack from the left mouse button to any other
3. Attack the mob with any greatblade

**Expected behavior**
Greatblades deal damage as usual

**Comment by Tslat** [comment]
Fixed
