### ISSUE TITLE
Runic gb's magic damage is not blocked by magic-immune mobs

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1138]
**Mod Version**
3.2.1

**Describe the bug**
Runic gb is able to damage melee-immune mobs with 4 magic damage, but when it comes to magic-immune mobs like Arc wizard or Construct of Range, Runic gb appears to be dealing its normal damage. I made sure that it wasn't boosted damage from stuff like Battle rage.

**To Reproduce**
Steps to reproduce the behaviour:
Hit a mob with magic immunity.

**Expected behavior**
Since the amount of magic damage appears to be 4, I imagine Runic gb should deal 21.5 damage to magic-immune mobs.

**Comment by Tslat** [comment]
Fixed
