### ISSUE TITLE
Sun staff/Kaiyu staff not dropped by their mobs

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1139]
**Mod Version**
3.2.1

**Describe the bug**
According to Scimi, Kaiyu staff is supposed to be dropped by Kaiyu, and Sun staff is supposed to drop from Inmate X. However their loot tables do not have these items.

**To Reproduce**
Steps to reproduce the behaviour:
Look in the loot tables of Kaiyu and Inmate X.

**Expected behavior**
Those mobs dropping their respective weapons.

**Comment by Tslat** [comment]
Fixed
