### ISSUE TITLE
Realmstone hunting

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#114]
Getting realmstones to other dimensions are difficult, mainly becuase only specific mobs drop them, and those mobs drop it rarely. Instead you should be able to buy realmstones with the silver coins. You can base this of the realm shifter's trades, but specific realmstones are only available from certain NPC's, some of which spawn in specific dimensions. This means that you can buy realmstones to the dimensions, as well as force the player to save up coins (as after a few lunaver coins it is almost worthless to the player) throughout the mod. They can also be part of the Vanilla Loot tables, but have an extremely low chance (similar to an enchanted golden apple's chance). You could start with the corrupted traveller only trading realmstones to the Abyss and Haven, and then you can encounter another traveller in those dimensions giving access to more realmstones.
Also you could have some bosses drop realmstones to other dimensions (corallus already has this with L'Borean), so you could have Rockrider drop realmstones to the Deeplands. Or Clunkhead drop reamstones to Shyrelands. This can also help with the Labricon Realmstone, as the fragments could be infused with another realmstone to work, i.e. the four fragments combine with the Iromine realmstone to form the Labricon Realmstone. This could be done on the crafting table.

**Comment by Sagisolar** [comment]
But The Deeplands should be early game since its the easiest dimension. Rock Rider is a bit of stretch even if hes early game.

**Comment by Seishan123** [comment]
True but's it's boss is late game to summon. Seriously you need to get to Dustopia to get Primordial Dust to make the Boulder Dash. Also the Deep Cases found in Deeplands are a bit too OP. Making it a bit more difficult to get to dimensions like that will make the whole mod give players a better experience.

**Comment by Sagisolar** [comment]
Imo its more intresting to fight for realmstones instead of just buying it. Also some rare mobs relie of realmstones so there drops arent useless.

**Comment by Tslat** [comment]
Realmstone obtaining has changed in 3.2
