### ISSUE TITLE
Astral Sorcery compatibility bug

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#1142]
**Mod Version**
v3.2.1

**Describe the bug**
Having Advent of Ascension and Astral Sorcery installed at the same time breaks infusion weapon crafting. Recipes still appear in JEI, but you can't actually craft them.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install both mods.
2. Try to craft a weapon in the infusion table, I tested this with Deadlock
3. Cry at your lack of guns

**Expected behavior**
Working crafting recipes

**Screenshots**
![test](https://user-images.githubusercontent.com/28516513/72950484-62064200-3d40-11ea-878c-f5e3d5c25faa.png)

**Comment by Tslat** [comment]
Please provide a log file

**Comment by Chubblezap** [comment]
From what I gather this has happened with a lot of mods due to hard-checking NBT data in recipes for non-stackable items.
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/4100978/latest.log)

**Comment by Tslat** [comment]
That log doesn't seem to have any issues to do with AS

**Comment by Immortallis1** [comment]
https://www.curseforge.com/minecraft/mc-mods/placebo

**Comment by Tslat** [comment]
This really needs to be tested and confirmed with _just_ aoa and AS

**Comment by Chubblezap** [comment]
Confirmed with just AoA and AS.
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/4101155/latest.log)
I believe this is not an issue with the way recipes are implemented in AoA (JEI still shows them after all), but with how the infusion table checks for a valid recipe.
AS seems to add an NBT tag to every non-stackable item for the Resplendent Prism, which breaks any modded crafter that's expecting a specific set of NBT tags (probably none in this case) in its output. My guess would be this happens in either "source/crafting/recipes/InfusionTableRecipe.java/matches", the use of copy() in "source/crafting/recipes/InfusionTableRecipe.java/getCraftingResult", or "source/common/containers/ContainerInfusionTable.java/slotChangedCraftingGrid".
I don't know how copy() would be interacting with NBT in this case, but it would seem that the Infusion Table is simply not finding a recipe output that matches the inputs because it's expecting specific NBT data that was changed externally by AS. I don't know how other mods handle custom crafters like this but it could be worth looking into.

**Comment by Tslat** [comment]
AS should really be fixing this ontheir end. The fact that they've just been ignoring it and making other mods solve it to be compatible is disgusting

**Comment by Chubblezap** [comment]
Frames are also non-stackable and could be causing issues as an input as well, if the recipes are specifically calling for untagged frames. If there's a way to change the infusion recipe handler to ignore extra NBT in the input/output when not enchanting shouldn't be too hard of a fix in theory.
It's not exactly bad practice either since this does give modpack makers less headaches when modifying recipes, but it does seem like something AS really could have gone about differently.

**Comment by Tslat** [comment]
The thing is, it breaks strict equality rules.

By doing so, essentially I've made all NBT modifications of that item useless.
What if someone wanted to have a recipe added where they can craft a certain item, but only if they got given that item in a special manner? This happens all the time on modded and plugin'd servers, where NBT is applied and checked to allow for special recipes.
By being forced to ignore additional NBT, you're essentially saying all items of that type are equal, when they're not.

Sake of example - what if I wanted to make a system where you could 'charge up' your item frames by combining them with augury essences. This would add a capability or NBT tag to that itemstack, identifying the level of 'charge up' the frame has. When crafting, you could then specify recipes that use that 'charge' level to create more powerful weapons or variants of the items.

By being forced to adhere to AS's bs, I am no longer able to do so, and have therefore limited my functionality.

**Comment by Chubblezap** [comment]
I can confirm it doesn't seem to be an issue with the output of the Infusion Table, but the input specifically. I tested this by checking NBT data with NBT Manipulator; with AS installed I was able to craft a vulcane even though the output vulcane has extra NBT attached, because none of the inputs do. I was not able to craft amethynd armor however, because the armor frames have NBT. And lastly, I gave myself a custom Limonite Rod with NBT data I added myself, and was not able to craft a vulcane with it, but _was_ when I gave myself a similarly NBT'd damage enhancer. This has to do with **specifically** the frame slot. I also feel the need to elaborate that this is no longer simply a conflict with AS, but with any Infusion frame inputs that might have extra NBT tags. Plenty of other mods would allow this, see: any mod that would allow frames to be enchanted. Hell, AoA itself could run into this problem if you made some kind of easter egg frame with special text.

With all due respect, could you not simply check if a tag on an item exists if you need it, but ignore all irrelevant tags? You could still have a charging system for frames, following your example, if you checked your frame input for the "Charge level" tag, rather than check for a frame that _only_ has the "Charge level" tag, and nothing else. An item that has both the "Charge level" tag _and_ any number of other meaningless tags should still work. The problem is the Infusion table is checking for an _exact_ NBT match in the frame slot, when it should be ignoring any irrelevant tags.

**Comment by Chubblezap** [comment]
I suppose a bandaid solution could be to simply make frames stackable, just as a side thought.

**Comment by Tslat** [comment]
Regardless of the possible solutions on my side - could AS not simply apply the tag they need when they need it, rather than to all items all the time?

My issue with this isn't the repercussions of the fix, it's that it's AS doing something stupid and making it everyone else's fault

**Comment by Chubblezap** [comment]
It's frustrating that AS uses tags in this way, yes. But again, AS isn't really causing the problem here more than highlighting it. If it hadn't come up now, this same issue would have come up another time with another NBT-changing mod. If I were a pack builder and I gave my players a named shotgun frame to make their first gun with, it wouldn't work because of the name NBT tag and it wouldn't have anything to do with AS.

**Comment by Tslat** [comment]
But it _would_ allow you to give a named shotgun frame which locks recipes behind it.

There's uses both ways to be honest. I'll remove the requirement for strict nbt matching on infusion recipes, but AS should definitely be fixing this on their end. They _are_ causing a problem by default, and for no real good reason.
