### ISSUE TITLE
Firefly staff's projectiles can stack infinitely

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1143]
**Mod Version**
3.2.1

**Describe the bug**
It seems that if you hit a mob from a specific angle with Firefly staff, the projectiles can infinitely stack, instantly killing that mob.

**To Reproduce**
Steps to reproduce the behaviour:
Shoot a mob (mainly a big one) with Firely staff. It is pretty finicky, though it seems to happen the most when firing under a mob.

**Expected behavior**
Firefly staff's projectiles not infinitely stacking lol

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/72960112-81619700-3d61-11ea-8206-f5f9ece17c40.png)
![image](https://user-images.githubusercontent.com/38159897/72960126-8cb4c280-3d61-11ea-90c8-9b7acc414b08.png)

**Comment by Tslat** [comment]
Fixed
