### ISSUE TITLE
Predatorian Blaster doesn't wither (even though its earlier version does)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1144]
**Mod Version**
3.2.1

**Describe the bug**
Predatorian Blaster, the upgrade of Ghast blaster, doesn't wither enemies even though Ghast Blaster withers enemies. (It doesn't have a description saying so either)

**To Reproduce**
Steps to reproduce the behaviour:
Compare the two.

**Expected behavior**
Predatorian blaster withering targets like its downgrade can.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/72960639-5d9f5080-3d63-11ea-98c1-22331feaa1ae.png)
![image](https://user-images.githubusercontent.com/38159897/72960650-67c14f00-3d63-11ea-8df3-feaf48838a15.png)

**Comment by Tslat** [comment]
Fixed
