### ISSUE TITLE
Rosidian Staff Description

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#1145]
**Mod Version**
What version of the mod are you on?
3.2.1

**Describe the bug**

The description of Rosidian staff is ambiguous.
According to the language file,
item.RosidianStaff.desc.1=Steals Health on Impact
item.RosidianStaff.desc.2=Spawns Life-Stealing Roots on Impact
the triggering condition for both abilities are said to be the same (which is on impact), but the description failed to mention the slight difference between the two triggering conditions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Give yourself a rosidian staff
2. Check the description
3. See error

**Expected behavior**

There slight difference between the two triggering should be explicitly stated by adding “on impacting blocks/mobs”

**Screenshots**
None

**Comment by Tslat** [comment]
Fixed in 3.2.2
