### ISSUE TITLE
Infernal armor doesn't have a recipe when it should(?)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1146]
**Mod Version**
3.2.1

**Describe the bug**
According to the MaterialsRegister, Infernal armor is supposed to be a set that is crafted with Nether stuff. It does not have a recipe ingame though, and I have not seen any other way to obtain it, leading me to believe that it doesn't have its recipe implemented.

**To Reproduce**
Steps to reproduce the behaviour:
Attempt to craft Infernal armor and try and see if it has a recipe at all.

**Expected behavior**
Infernal armor having a recipe, according to the MaterialsRegister at least.

**Comment by Tslat** [comment]
Fixed
