### ISSUE TITLE
"Surface-To-Air" Advancement awarded for any RPG kill

### ISSUE THREAD

**Issue by Criterion6** [Tslat/Advent-Of-Ascension#1147]
**Mod Version**
3.2.1

**Describe the bug**
When any mob is killed using the RPG or Floro RPG, the player is awarded the advancement "Surface-To-Air".

**To Reproduce**
1. Create a new world.
2. Kill a mob in the world using either the RPG or Floro RPG.
3. Observe as the advancement is earned.
4. Note that this might take a couple kills.

**Expected behavior**
The advancement is only awarded to the player when they kill a flying mob, on impact, using either RPG.

**Comment by Tslat** [comment]
Fixed
