### ISSUE TITLE
Add Config to change weapon values

### ISSUE THREAD

**Issue by Epic428** [Tslat/Advent-Of-Ascension#1148]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.

Relates to weapon damage/speed/recoil/delay values. 

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.

I’m currently making a pack that uses AoA as a main focus mod. Having the ability to go into a Config file and modify weapon values would make it far easier to balance the pack to my liking vs using Crafttweaker/zen script to redo everything. 

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?

Obviously crafttweaker scripts would work but are a far more tedious and time consuming option.

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?

It seems guns have been changed for the 3.2 update, based on recent discussions in discord. I think balancing the guns to do less damage per hit with a higher rate of fire would make them feel more smooth, at the expense of using more ammo. An option to counteract the increase in ammo usage could be to implement a “magazine” of sorts that ammo could be consumed from, ultimately, minimizing usage of precious inventory space.

**Comment by Tslat** [comment]
Guns fire slower because blasters are the fast-firing weapon.

Also, there's a cap on how fast guns can fire, functionally. 5.0 is the max fire rate for guns no matter what you do

**Comment by Epic428** [comment]
That makes sense. I haven’t played with the blasters yet to see how they work. Assault rifles are probably the ones that feel slower than they should out of what I have used. But I definitely think they all could use more balancing tweaks.

**Comment by Tslat** [comment]
Such as?
