### ISSUE TITLE
Emberstone Tools sometimes crash while mining unsmeltable blocks

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#1149]
**Mod Version**
3.2.1

**Describe the bug**
Digging blocks with Emberstone tools that are not smeltable crashes the game after awhile (tested with grass and leaves). After mining a block that _is_ smeltable first, it seems fine for awhile, then crashes (crashed while in my inventory that time).

There was also a possibly unrelated crash with water that crashed while I was testing, no idea what caused it but I'll include the crash report there as well just in case.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn in an Emberstone pickaxe (though I imagine they all work the same way)
2. Dig up leaves and grass until the game crashes.

**Expected behavior**
Behaving like a standard tool if the block cannot be smelted.

**Crash Reports/Logs**
[bushcrash.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4110843/bushcrash.txt)
[bush.log](https://github.com/Tslat/Advent-Of-Ascension/files/4110865/bush.log)
[leafcrash.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4110846/leafcrash.txt)
[leaflog.log](https://github.com/Tslat/Advent-Of-Ascension/files/4110868/leaflog.log)
[crashafterinventory.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4110847/crashafterinventory.txt)
[inventorylog.log](https://github.com/Tslat/Advent-Of-Ascension/files/4110870/inventorylog.log)
[watercrash.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4110848/watercrash.txt)
[waterlog.log](https://github.com/Tslat/Advent-Of-Ascension/files/4110872/waterlog.log)

**Comment by Tslat** [comment]
Fixed, thanks for the reports
