### ISSUE TITLE
Enchantment Descriptions Support?

### ISSUE THREAD

**Issue by Z-Tunic** [Tslat/Advent-Of-Ascension#1153]
The mod:
https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

What that mod does is that it shows a description in the Enchanted Book's Tooltip, showing you what the enchantment does if there's a entry in their language file.

Here's an example with the description from the Fire Protection Enchantment.
![](https://cdn.discordapp.com/attachments/377171551155650560/670697682775310365/EDFireProtection.PNG)

If no entry exists, then it shows this alongside a localization key.
![](https://cdn.discordapp.com/attachments/377171551155650560/670699126811525146/EDRecharge.PNG)

Was wondering if descriptions could be added to the enchanted books within AoA. These are the current localization keys for the enchanted books:
enchantment.aoa3.brace.desc
enchantment.aoa3.intervention.desc
enchantment.aoa3.archmage.desc
enchantment.aoa3.sever.desc
enchantment.aoa3.recharge.desc
enchantment.aoa3.control.desc
enchantment.aoa3.shell.desc
enchantment.aoa3.crush.desc
enchantment.aoa3.form.desc
enchantment.aoa3.greed.desc

**Comment by Tslat** [comment]
Done
