### ISSUE TITLE
Outdated translations are potentially misleading

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1154]
**Mod Version**
What version of the mod are you on?
3.2.2

**Describe the bug**
The 3.2 update changed lots of descriptions on items, including the describing of abilities. However, in some translations, the old ability text is still present, which is potentially misleading.

An example of this is the elecanyte armor's description in the Russian language, The armor still mentions the old ability in russian, despite it being changed in English.

Having these straight out incorrect descriptions can cause problems, as people will think these descriptions are supposed to be accurate, when they actually aren't.

**To Reproduce**
Steps to reproduce the behaviour:
1. Check the translation of Elecanyte Armor in Russian or a description of a weapon/armor that got an ability change.
2. See if it matches what it should be in 3.2.2, or if it refers to an old ability.

**Expected behavior**
Naturally, I'd expect for the translations to be fixed, but unless someone comes around to do it, I'm not sure what we'd do...

**Comment by Tslat** [comment]
Not much I can do about this really

**Comment by Tslat** [comment]
Dealt with
