### ISSUE TITLE
Luxon tribute impossible to get

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1155]
**Mod Version**
3.2.2

**Describe the bug**
Now that Essences and the Ascension shrine have essentially been kicked out, the only way to get Luxon tribute is now by harvesting Pixons. However that does not appear to work either, making it impossible to gain Luxon tribute at all.

**To Reproduce**
Steps to reproduce the behaviour:
Harvest Pixons with Stone/Diamond bowl and see no Tribute go up.

**Expected behavior**
Harvesting pixons making Luxon tribute go up, it was the only other way to gain Luxon tribute.

**Comment by Tslat** [comment]
Fixed
