### ISSUE TITLE
Skill armor sets duping when not at the right level?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1156]
**Mod Version**
3.2.2

**Describe the bug**
From going through the skill armors in a specific way, it appears you can dupe pieces of skill armor if you are not at the right level to wear them. They seem to be real items, both logging out and logging back in and throwing them does not make them vanish.

**To Reproduce**
Steps to reproduce the behaviour:
Not sure how it works exactly, but here's how I got it to happen:
Put the Engineering set on in creative mode (this was for the sake of wiki stuff lol)
Walk up to cactus, switch gamemode to survival.
Armor pieces pop to hotbar, helmet was 1 space away from everything else.
Move helmet to a slot. upon putting helmet in a slot, another helmet with no durability lost pops up
(Neither slot was selected at the time)

**Expected behavior**
No duping. Not sure if this is an AoA bug, it appears to be very inconsistent. Doesn't hurt to have this here though

**Comment by Tslat** [comment]
-.-
