### ISSUE TITLE
Abyss WebReaper cause crash with spongeforge

### ISSUE THREAD

**Issue by SSKirillSS** [Tslat/Advent-Of-Ascension#1157]
**Mod Version**
forge-1.12.2-14.23.5.2847-universal
AoA3-3.2.2
spongeforge-1.12.2-2838-7.1.9-RC3972

**Describe the bug**
Player just entered to the Abyss, after that server was crashed
https://pastebin.com/gEtEDj6E

**To Reproduce**
Steps to reproduce the behaviour:
1. Just go to Abyss

**Comment by Chubblezap** [comment]
Getting a similar crash with the Web Reaper's projectiles, though it only seems to happen on servers. I was told this happened when the Web Reaper killed the player but I wasn't able to recreate it in singleplayer.
[crash-2020-01-26_10.17.13-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4114349/crash-2020-01-26_10.17.13-server.txt)
[crash-2020-01-26_10.24.28-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4114350/crash-2020-01-26_10.24.28-server.txt)

**Comment by Tslat** [comment]
Stupid mojang..

Fixed
