### ISSUE TITLE
Knight armor not having a recipe

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1158]
**Mod Version**
3.2.2

**Describe the bug**
According to MaterialsRegister, Knight armor is supposed to have a recipe, and I remember it having a recipe in the versions before this. However, it doesn't have a recipe ingame.

**To Reproduce**
Steps to reproduce the behaviour:
Attempt to craft Knight armor

**Expected behavior**
Knight armor having a recipe. I know it's not another mod messing with it, every other craftable thing has a recipe that works.

**Comment by Tslat** [comment]
Fixed
