### ISSUE TITLE
Mob spawning config

### ISSUE THREAD

**Issue by Zack7292** [Tslat/Advent-Of-Ascension#1160]
**Describe/name the existing feature this suggestion relates to**
Mobs and configs

**Describe the change or feature you think would be good to see**
i'll like to be able to adjust the spawn rate of every mobs individually and to to it with dimensions mobs too, how should it work:
it should be pretty, you set a spawn rate chance by the mobs and for the dimensions , its like a % of all those mobs for example:
if you put 100 to crow(this is just has an exemple) but put 25 to the overworld, his spawn rate will 25% of 100 (i think that if you put like 100 like a % it could help calculate) 
but if you put 25 to mouse and put 300% for the overworld his spawn rate will be 75,
The goal of this is to be able to have 2 way to adjust spawn rate of mobs, mobs by mobs, and dimensions by dimensions
i also think in the config file they should be separated by dimension and after in alphabetical order

**Add any alternative implementations you think might work**
No
**Include any additional background information**
i don't know

**Comment by Tslat** [comment]
Here you go:
https://www.curseforge.com/minecraft/mc-mods/increasemobs

https://www.curseforge.com/minecraft/mc-mods/in-control
