### ISSUE TITLE
Hitting Boats with greatblades

### ISSUE THREAD

**Issue by kalelongley** [Tslat/Advent-Of-Ascension#1164]
**Mod Version**
What version of the mod are you on?

3.2.3

**Describe the bug**

If you have a greatblade out whilst in a boat you can left click and break it

**To Reproduce**
Steps to reproduce the behaviour:
1. Get in a boat
2. Pull out Greatblade
3. Look Down
4. Attack boat
5. See error

**Expected behavior**

Boats can not usually be destroyed by the user whilst they are inside of it

If more detail is needed DM me on Discord.         NoDestiny#9518

**Comment by Tslat** [comment]
Lol of course this is a thing

**Comment by kalelongley** [comment]
I am not currently able to test it but I would assume this works with minecarts aswell

**Comment by Tslat** [comment]
Yeah likely. All good, I know what the cause is

**Comment by Tslat** [comment]
Fixed
