### ISSUE TITLE
Exoplate Armor crashes when falling into the void

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#1166]
**Mod Version**
3.2.3

**Describe the bug**
Exoplate's armor effect causes a crash when falling into the void and taking damage, likely due to the light level there.

**To Reproduce**
Steps to reproduce the behaviour:
1) Equip any Exoplate armor piece
2) Fall into the void

**Expected behavior**
Taking normal void damage.

[crash-2020-01-28_01.53.51-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4121770/crash-2020-01-28_01.53.51-server.txt)

**Comment by Tslat** [comment]
Lol.

**Comment by Tslat** [comment]
Fixed
