### ISSUE TITLE
Expanded Spawnrate Modifiers

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#1167]
**Describe/name the existing feature this suggestion relates to**
entities_config.cfg already has a modifier for the overall spawnrate of every hostile in every dimension, it would be nice to have a bit more control over this.

**Describe the change or feature you think would be good to see**
Primarily, being able to control spawnrates for individual dimensions. Some dimensions cause players to encounter mobs more or less due to terrain generation, making a blanket spawnrate modifier rather inflexible to work with when it comes to balancing. The Nether, for example, has much more spawning surface than Lelyetia, meaning normally-paced encounters in one dimension could mean very little in the other, or worse, too many for the player to reasonably deal with.

**Add any alternative implementations you think might work**
Rather than having each dimension have its own config line and being unable to account for modded dimensions, it could be cool to see a modular approach. There could be a field where the player could specify dimensions and spawnrates to change; kinda like the hunter mob config but with dimension IDs instead of entity IDs. Also like the hunter mob config, each aoa dimension could have a "default" entry here. Unlisted dimensions would have the unchanged, vanilla spawnrate.

**Include any additional background information**
This suggestion mostly stems from the various issues finding mobs/NPCs in the Overworld and Nether, but being afraid to change the spawnrate modifier because other dimensions feel dangerous enough already.

**Comment by Tslat** [comment]
I mean, the problem with this is that it's just never ending. I implement one thing, and someone just wants more. The fact that this suggestion even exists proves that point.

My concern is, where do I draw the line? There's already mob spawn control mods out there that both decrease and increase - at what point do I just say use them, since that's literally what they exist for?

**Comment by Chubblezap** [comment]
That's also true, mods probably exist that already do this. I don't know how they interact with AoA's spawnrate modifications though, it would require some testing to make sure they're compatible given it's two mods trying to accomplish the same thing. Having a way to at least disable spawnrate modifications as a failsafe/default value could be handy though.

**Comment by Tslat** [comment]
AoA's spawnrate modifications are just a layer above the vanilla spawn system.
So other mods that increase spawnrate will work just fine with it.

If you want to disable AoA's spawnrate modifier, just set the value to 1. 1 is 100% chance to continue spawn, relative to the other spawn conditions normally implied anyway.

**Comment by Chubblezap** [comment]
Alright, that's good to know. Then yeah, something like this might as well be left to other mods in the long run unless an actual conflict comes up somehow.
