### ISSUE TITLE
The unmentioned extra 10% boost you get when wearing a full set of a damage-boosting armor set

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1170]
**Describe/name the item/content this suggestion relates to**
Ghoulish, Nethengeic, Omni(?), Predatious, Sharpshot, and Zargonite armor.

**Describe the change/balance you think would be good to see**
From testing, these sets appear to give an extra 10% boost to the damage type they boost when wearing a full set. This isn't mentioned anywhere ingame, which seems a bit odd considering stuff like Speed armor mention that it gives an extra speed boost as a full set bonus.

Anyway, I feel like this extra damage boost shouldn't be a thing. Because one: a 40% damage boost is already a pretty strong boost.
And two: I feel like it kind of undermines the whole mix-and-match thing the new armor system is going for. Other than Zargonite, all these sets already have full set bonuses that benefit those who want to wear the full set, making the extra damage boost feel like an unnecessary thing that makes wearing a full set feel more like an obligation rather than an option (at least in terms of these specific sets). This extra boost not being mentioned doesn't help much either.

**Include any additional background information**
I'm not sure if it's actually intended at all, but I can never be too sure with anything.

**Comment by Tslat** [comment]
Fixed
