### ISSUE TITLE
Predatious full set thorns not working

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1171]
**Mod Version**
3.2.3

**Describe the bug**
Predatious' full set mentions that it deals minor thorns damage to melee attackers. Upon testing, it does not appear to deal any damage to melee attackers, no matter how many times they hit me.

**To Reproduce**
Steps to reproduce the behaviour:
Get hit by melee mobs in full Predatious armor.

**Expected behavior**
Predatious armor dealing minor thorns damage while wearing a full set

**Comment by Tslat** [comment]
Fixed
