### ISSUE TITLE
Purity armor's full set bonus working even when wearing 1 piece

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1172]
**Mod Version**
3.2.3

**Describe the bug**
Purity armor's description says that its effect is full set-only. However, the effect appears to work even when only wearing 1 piece. Whether you wear 1 piece, or 3 pieces of the set the effect works, despite saying that you need to wear the full set.

**To Reproduce**
Steps to reproduce the behaviour:
Wear at least 1 piece of Purity armor.
Attempt to get inflicted with any of the effects it removes.

**Expected behavior**
Purity armor's effect only activating when the full set is worn.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/73333621-3216dd00-421f-11ea-9b3a-29508ada84af.png)

**Comment by Tslat** [comment]
Fixed
