### ISSUE TITLE
Fully grown Heart fruit, Magic Marang, Eye bulb, and Mystic shroom crops don't give extra seeds/copies if harvested in certain ways

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1173]
**Mod Version**
3.2.3

**Describe the bug**
Fully grown AoA crops can be harvested by left-clicking to break it or right-clicking to immediately plant another crop after harvesting the other one. With any crop other than the ones in the title, both methods can also give extra seeds when harvesting.

With this in mind, fully grown Heart fruit, Magic Marang, Eye bulb, and Mystic shroom crops *do not* give extra seeds when harvesting them. By **right-clicking** to harvest, you still get 1 extra item, only the 1 though- no extra seeds.

If they are harvested by **left-clicking**, you only get the item and no seeds, making you unable to plant any more of those crops if left-clicking to harvest. (in the case of Eye bulb and Mystic shrooms, you just don't get anything extra at all when left-clicking..)

And I did try many times to get seeds, but to no avail. I doubt it's just luck, since I went through every crop multiple times and they gave seeds from both left-clicking and right-clicking, with the exception of these 4.

**To Reproduce**
Steps to reproduce the behaviour:
Harvest these crops- fully grown via left-click or right-click.

**Expected behavior**
Heart Fruit/Magic Marang giving extra seeds when harvested in both ways. In the case of Eye bulb/Mystic shrooms, I imagine them being able to give extra copies of themselves since they are harvested just like Potatoes and Carrots, otherwise you get no benefit from harvesting by left-clicking, and that's the only way to harvest vanilla crops IIRC.

**Screenshots**
Here is a video instead (Made a small while back, only shows Heart fruit)
https://youtu.be/2Kjdx7lZILE

**Comment by Tslat** [comment]
Sure
