### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by DraganNotDragon** [Tslat/Advent-Of-Ascension#1175]
I've noticed the big mods usually have really nice textures and 3D models, you have a huge pack so it must be hard, but have you ever thought or commissioning better textures or making some new ones yourself? Just a thought, but I think everything might start to fit in with minecraft more if the textures were a little better, and im sure some other people would want that to.

**Comment by Tslat** [comment]
We have been. We've redone several hundred textures over the last 12 months
