### ISSUE TITLE
Radiant Pixons only give 40 Infusion XP

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#1177]
**Mod Version**
3.2.3

**Describe the bug**
Harvesting Radiant Pixons gives 40 Infusion XP per harvest, which appears to be a typo given that the previous tier, gives 350 and the next tier gives 900. Tested on both Stone and Diamond Bowls, with Diamond giving 200 (5x40).

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn a Radiant Pixon
2. Harvest it with a Stone Bowl or Diamond Bowl
3. Note the lack of XP

**Expected behavior**
The wiki claims these should be giving 700 XP.

**Screenshots**
![2020-01-30_00 50 52](https://user-images.githubusercontent.com/28516513/73433943-ad998c80-42fa-11ea-8c37-f132d9384c16.png)

**Comment by Tslat** [comment]
Fixed
