### ISSUE TITLE
Shadonantium, Emberium, and Skeletanium don't have recipes

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1179]
**Mod Version**
3.2.3

**Describe the bug**
Crystallanium has a new recipe, but the other 3 utility blocks do not. The only thing I can really assume is that they were forgotten in terms of gaining new recipes. Don't think there's any other way to obtain them.

**To Reproduce**
Steps to reproduce the behaviour:
Attempt to see if they have recipes

**Expected behavior**
The other -antium blocks having recipes.

**Comment by Tslat** [comment]
Done
