### ISSUE TITLE
The neck of the Runicorn of the Runicorn rider breaks

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1180]
**Mod Version**
3.2.3

**Describe the bug**
When looking around... I think. It seems the Runicorn on Runicorn rider's neck isn't "synced" up with the rest of the body, resulting in the neck detaching. This does not appear to happen with Rainicorn, Alluricorn, and regular Runicorn. Just the version with the rider.

**To Reproduce**
Steps to reproduce the behaviour:
Spawn Runicorn rider and watch the neck of the Runicorn.

**Expected behavior**
The Runicorn of Runicorn Rider not doing the scary thing with the neck.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/73489876-3991cf80-4360-11ea-95aa-2ba32f0cbe7a.png)

**Comment by Tslat** [comment]
Fixed
