### ISSUE TITLE
Bosses still have the tp-in-your-face ability

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1182]
**Mod Version**
3.2.3

**Describe the bug**
The reason this isn't formatted as a suggestion was cause that Scimi did say it got removed/is going to be removed a while back, which makes me think he forgot about it.

Basically, the bosses that can randomly tp into your face can still do that.

**To Reproduce**
Steps to reproduce the behaviour:
Aggro the bosses Bane, Coniferon, Goldorth, Horon, Hydrolisk, Kajaros, Okazor, Rockrider, and Tyrosaur(?)

**Expected behavior**
Judging by that message made a while back, these bosses not having that nasty ability. Apologies if this more of a suggestion than a bug report.

**Comment by DiamondWalker** [comment]
Tyrosaur doesn't tp in your face, he jumps at you. The ability could still be tweaked tho

**Comment by Tslat** [comment]
Done
