### ISSUE TITLE
Give mother void walkers a higher chance to drop void scales

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#1187]
I think mother void walkers should have a 50% chance to drop void scales (or maybe even 100%) to make up for their hunter level. Sure they drop the sword, but if you're not interested in that all they do is take up spawns that could be used for other void mobs (unless you have the hunter levels). The other thing is I've killed 40 total void mobs, and I've only gotten around 4 scales. I feel the ability to get them quicker would be a fair prize for the hunter levels, since by the time you start training hunter you probably have gear around the same tier as void (such as amethind).

**Comment by Tslat** [comment]
I've increased it a bit in 3.2.5
