### ISSUE TITLE
Placeholder rework for smash/silverfoot

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#1192]
Normally I'd make a complex AI suggestion for boss reworks, however the point of this suggestion is to provide a simple rework until the boss update comes (since I know major design flaws like the tp attack are intended to be solved soon).

Anyways, the focus of this suggestion is smash and the fact that his only ability instakills you if you try to fight him fairly and using appropriate gear. I'd suggest just giving him silverfoot's AI for now (I used to fight him in the overworld when I was bored; it was a bit boring, but at least it was more fun than dying from nearly unavoidable fall damage).

Now, having two bosses with identical AI wouldn't be fun at all, so I came up with a rework I think wouldn't take too long to code (at least until it gets a legitimate rework). He would have three on-hit effects (slowness on player, weakness on player, and strength for himself) which start at level 0 (aka non-existent). Every time he hits you, his effects will go in a loop, increasing in power. To sum it up, it'd work like this:

Hit 1: nothing
Hit 2: player receives slowness 1
Hit 3: player receives slowness 1 and weakness 1
Hit 4: player receives slowness 1 and weakness 1, while silverfoot receives strength 1
Hit 5: player receives slowness 2 and weakness 1, while silverfoot receives strength 1
Hit 6: player receives slowness 2 and weakness 2, while silverfoot receives strength 1
Hit 7: player receives slowness 2 and weakness 2, while silverfoot receives strength 2
Hit 8: player receives slowness 3 and weakness 2, while silverfoot receives strength 2
Hit 9: player receives slowness 3 and weakness 3, while silverfoot receives strength 3

This would go on and on during the entire battle, and eventually you'll probably end up dying. Not exactly AAA design, but I think it'd be a slight upgrade that shouldn't take too much time I think.

**Comment by Tslat** [comment]
I'm not.. entirely sure how this would improve anything, even as an intermediate solution

**Comment by DiamondWalker** [comment]
> 
> 
> I'm not.. entirely sure how this would improve anything, even as an intermediate solution

The smash thing was just so you wouldn't be forced to cheese him. imo a fair but boring boss is better than an unbalanced and boring boss.

As for the silverfoot rework, that was made up on the spot, and in retrospect isn't a good idea at all. I guess I just really want to avoid another situation like crae or gyro where they do basically nothing.
