### ISSUE TITLE
Overworld Mobs not Spawning with a ModPack.

### ISSUE THREAD

**Issue by keennn** [Tslat/Advent-Of-Ascension#1195]
**Mod Version**
3.2.3

**Describe the bug**
OVERWORLD AOA Mobs doesn't spawn(the other dimensions don't have this issue), sometimes they do spawn but its like 1 mob in 50+ Chunks, i think its related to my modpack and BIOMES O PLENTY, it also happened in the 3.2.2 version, ill attach some logs.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
Mobs spawning normally.

**Screenshots**
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/4162701/latest.log)
[debug.log](https://github.com/Tslat/Advent-Of-Ascension/files/4162703/debug.log)

**Comment by Tslat** [comment]
Mobs spawn significantly less than they used to. That is intended.

You can adjust the mob spawn rate a bit via the spawn modifier in the AoA config. The default value should be 0.3, raise it to 1 if you want more spawns
