### ISSUE TITLE
Halos are not displayed in the server

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1197]
**Mod Version**
3.2.3

**Describe the bug**
Halos are not displayed in the server

**To Reproduce**
Have a halo.
Then go to the server.
Although the halo display has been turned on in the settings.

**Expected behavior**
There should be a halo on my head.

**Screenshots**
Do you need my picture?

**Comment by Tslat** [comment]
Unable to replicate - they're working just fine for me
