### ISSUE TITLE
Effect Lamps

### ISSUE THREAD

**Issue by TsavyPrince** [Tslat/Advent-Of-Ascension#120]
**Describe the new feature you think would be good to add**
After looking at a few suggestions, I decided to make my own, inspired by theirs.
Introducing Effect Lamps.
In essence, these blocks are lamps that have an effect in a certain radius, similar to beacons. They could go very well with the Engineering skill since the Engineering skill has to do with placing traps and whatnot. Here are some of my ideas.

Moonstone Lamp - This has already been suggested, but this lamp wards off enemies.
Growth Lamp - Speeds crop growth.
Fertility Lamp - Reduces intervals between breeding animals.
Water Lamp - Attracts enemies. (reference to Terraria water candle.)
Solar Lamp - Makes mobs burn up when near death.
Hunger Lamp - Makes regenerating hunger faster.
Suppression Lamp - Makes explosives not damage terrain,

This may also provide more uses for runes in crafting, and may be useful in lots of situations. They may even add another use for the Anima skill.

**Add any alternative implementations you think might work**
Perhaps maybe add tablets that focus their effects on one area for a long time.

**Include any additional background information**
N/A

**Comment by profilename14** [comment]
This seems like a great suggestion, but does the hunger lamp make hunger decay slower or make hunger regenerate?

**Comment by TsavyPrince** [comment]
Read again.
