### ISSUE TITLE
Unable to craft Construct of Servility Slab

### ISSUE THREAD

**Issue by jttheghost** [Tslat/Advent-Of-Ascension#1202]
**Mod Version**
3.2.3

**Describe the bug**
Recipe in NEI shows as the same as the Healing Golem slab. When putting the ingredients into an infusion table (Slab|iron,iron,glistening melon), only the Healing Golem is craftable

**To Reproduce**
Put the ingredients into an infusion table (Slab|iron,iron,glistening melon), shows healing golem

**Expected behavior**
Recipe is separate from healing golem, Construct of Servility slab is craftable

**Screenshots**
NEI Construct of Servility
![image](https://user-images.githubusercontent.com/28493765/73998189-d3dcaf00-492e-11ea-918c-1ef292d8278a.png)
NEI Healing Golem
![image](https://user-images.githubusercontent.com/28493765/73998207-e3f48e80-492e-11ea-9977-db9b8ae20abf.png)
Actual craft using infusion table
![image](https://user-images.githubusercontent.com/28493765/73998236-fcfd3f80-492e-11ea-8c8c-681e1bd6871f.png)

**Comment by Tslat** [comment]
Fixed
