### ISSUE TITLE
Nature melon slice unontainable?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1204]
**Mod Version**
3.2.3
(to be honest I am rushing this, I'm gonna sleep after making this and I'm sure 3.2.4 is very close, so maybe I did miss something? Don't want to leave it behind and potentially have a 3.2.5 haha)

**Describe the bug**
It appears there's no way to obtain Nature melon slice, the only way to make Natural tea. I looked all around the git, the loot tables of structures, Natura, Gardencia mobs, various mobs, skills, etc. My search wasn't super meticulous, but I can't really think of anywhere else without just going through every mob table. No thank you

**To Reproduce**
Steps to reproduce the behaviour:
Attempt to obtain Nature Melon slice

**Expected behavior**
Nature melon slice being obtainable, whether it be Natura or somewhere else (or just cut it and have something else be the way to make Natural tea lol)

**Comment by Tslat** [comment]
Yep
