### ISSUE TITLE
IndustrialCraft 2 Integration

### ISSUE THREAD

**Issue by ErasoftMx** [Tslat/Advent-Of-Ascension#1207]
**Describe the new feature you think would be good to add**
IndustrialCraft 2 is friendly with a lot of mods and has full integration with them.
I think this AoA-IC2 integration is a MUST, as we could use IC2 machines with AoA content.

**Add any alternative implementations you think might work**
none

**Include any additional background information**
Integration may start from very basics like smeltable ores being able to be used on IC2 machines.

**Comment by Tslat** [comment]
I need more info than this. Give me specifics. What machines? What should I do with them? Give me details.

**Comment by ErasoftMx** [comment]
Sure. IndustrialCraft2 main purpose is to provide a variety of treatments that gives a engineering feeling.

I should say the [Macerator](https://wiki.industrial-craft.net/index.php/Macerator) is one of the first IC2 machines that should be supported. In gross terms, this machine serves as a "ore multiplier", as this refines them and generates an output of 2 dust per 1 ore. But wait, there's a lot of work behind building this machine, so, if you think this machine is too cheaty, NOPE, it's not.
Examples of integration: All the AoA ores may fit perfectly in the functionality of this machine. Check IC2 Wiki for further information.

The [Extractor](https://wiki.industrial-craft.net/index.php?title=Extractor) is also a very important machine, as you can convert an useless item into something useful. IC2 implements the extraction of [Rubber](https://wiki.industrial-craft.net/index.php?title=Rubber) from some kind of special wood.  Examples of integration: This could be used in advantage to extract something useful from AoA dimensional wood or anything that may fit into this behavior.

The [Ore Washing Plant](https://wiki.industrial-craft.net/index.php?title=Ore_Washing_Plant) is somewhat similar to a macerator. This machine decomposes the item into small items that are supposed to be "components" of that item. The input for that machine is the output of a Macerator. For example, a pile of crushed iron ore on this machine produces purified iron ore, a bit of iron ore dust and some stone dust. All those dusts can be combined togheter to create the entire version of the object.
Examples of integration: A variety of items may fit for this machine, but the ones that also fit on the macerator are a must.

**Comment by Tslat** [comment]
Done in 3.3
