### ISSUE TITLE
Leaderboard don't work

### ISSUE THREAD

**Issue by GuerreroCraft61** [Tslat/Advent-Of-Ascension#1210]
**Mod Version**
What version of the mod are you on?
3.2.3/3.2.4

**Describe the bug**
Leaderboard don't load (server)

Log: https://gist.github.com/GuerreroCraft61/a77cd42d6a781fbf0ed7bd770d33b192

**To Reproduce**
Steps to reproduce the behaviour:
1. Load the game
2. Open aoa menu
3. Leaderboard isn't available

**Expected behavior**
Allow use leaderboard

**Screenshots**
![Captura1](https://user-images.githubusercontent.com/30746531/74087174-1797fb80-4a8a-11ea-8128-36072e0acd5c.PNG)

**Comment by EatingSilencer** [comment]
I don't believe it has been added yet.

**Comment by Tslat** [comment]
The leaderboards haven't been added yet
