### ISSUE TITLE
1.7.10 Continue to update?

### ISSUE THREAD

**Issue by nnn950711** [Tslat/Advent-Of-Ascension#1211]
Will you continue to update the 1.7.10 version? I found a lot of problems with 1.7.10,
This will make it impossible to play with other modules, will you continue to repair it?

**Comment by masterbobli** [comment]
No. 1.7.10 will not be continued. Make sure to update to the latest version (Tslat 1.1.3). This should be a stable version.




On 02/09/2020 07:42, nnn950711 wrote:

Will you continue to update the 1.7.10 version? I found a lot of problems with 1.7.10,
This will make it impossible to play with other modules, will you continue to repair it?

**Comment by nnn950711** [comment]
> No. 1.7.10 will not be continued. Make sure to update to the latest version (Tslat 1.1.3). This should be a stable version. On 02/09/2020 07:42, nnn950711 wrote: Will you continue to update the 1.7.10 version? I found a lot of problems with 1.7.10, This will make it impossible to play with other modules, will you continue to repair it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


I updated to the latest version, but there are many errors.

**Comment by nnn950711** [comment]
> 第1.7.10節將不會繼續。確保更新到最新版本（Tslat 1.1.3）。這應該是一個穩定的版本。nnn950711在02/09/2020 07:42寫道：您將繼續更新1.7.10版本嗎？我在1.7.10中發現了很多問題，這將使其無法與其他模塊一起使用，您會繼續修復嗎？—您收到此消息是因為您已訂閱該線程。直接回复此電子郵件，在GitHub上查看或取消訂閱。

我能确定我的版本是最新的版本, 但扔然有许多的错误

**Comment by Tslat** [comment]
1.7.10 is dead. Use 1.12.2.
It's time to move on

**Comment by vinicius1222** [comment]
So we are simply obliged to use the new versions just because you don't want to fix the bugs you left.  Very noble of you!  Really when success goes to the head arrogance also grows.  You are acting the same as the developer of the orespawn mod.

**Comment by Tslat** [comment]
> So we are simply obliged to use the new versions just because you don't want to fix the bugs you left. Very noble of you! Really when success goes to the head arrogance also grows. You are acting the same as the developer of the orespawn mod.

You can continue to play the old versions if you want?

I'm not at all obligated to continue to work on them.

**Comment by vinicius1222** [comment]
So let's analyze the options, I can't play with the morph and hat mods, not to mention some magic mods too, because every time I enter and leave the world, these mods are reset, apart from the bug with the boss bane. This happens from versions 1.0.2 - 1.1.3, 1.0 and 1.0.1 to crash when entering the dimension of immortalis. My options are to use snapshot versions 2.5 and below. And maybe I can go for the new versions of mine, but there are mods that were never updated for those versions, so either I deal with the bugs, or I just abandon the mods that I like. That is all.

**Comment by vinicius1222** [comment]
Forget it, I'm being a spoiled idiot, the sensible thing is for me to use the new versions anyway, when you guys are done with 1.16 are you going to version 1.19 or newer?  I think 1.20 is almost ready to launch.

**Comment by Tslat** [comment]
1.16 is in a steady state right now, and is only getting rare updates
Apart from that, we're just following whatever minecraft version is current

**Comment by vinicius1222** [comment]
Well, sorry for making unnecessary fuss, as much as I like the mod in version 1.7, this version doesn't even support forge anymore.  I will be waiting for future features in the mod and future versions.
