### ISSUE TITLE
Baubles Integration

### ISSUE THREAD

**Issue by ErasoftMx** [Tslat/Advent-Of-Ascension#1215]
**Describe the new feature you think would be good to add**
Baubles was intended to be used for other mods to implement their own items that could be used on baubles slots (rings, belts, amulets, and so on).
It could be really nice to have an AoA-Baubles integration and getting a brand new set of objects. I.E. Bloodstone rings/amulets that could be imbued with help of Augury or Anima skills.

**Add any alternative implementations you think might work**
This integration may fit better after the 'Skills Update', but it's up to the developer to decide if this integration is viable and when is the best moment to introduce it.
If it is introduced before 'Skills Update', then objects may be imbued with an infusion table or a crafting recipe directly.

**Include any additional background information**
none.

**Comment by Tslat** [comment]
This one may be tricky as any content I add to baubles will effectively be unavailable if you don't have baubles installed...
I don't really want to make Baubles a hard dependency
