### ISSUE TITLE
Ancient Cavern Rework

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#1216]
As we all know opinion of Ancient Cavern (the Atlantis Rising holdover) is not very high:

![image](https://user-images.githubusercontent.com/11131230/74114352-9dde3b80-4b77-11ea-80da-94d106aa4e28.png)

(information about this poster censored to protect them from the change aversion-fueled ancient cavern apologists)

Here are my ideas to make it slightly better.

1.
Add some lore. As proof of the situation being dire allow me to present the developer not knowing what the place even is:

![image](https://user-images.githubusercontent.com/11131230/74114431-075e4a00-4b78-11ea-88a0-368f4797f580.png)

Ok here's my take without actually writing the entire lore

AC was once a thriving magical civilization that worshipped the gods back when they weren't dormant. But then the eternally indifferent gods went dormant, or "turned their back" on them, and reality started crumbling away, and over long periods of time it was reduced to its current state. There weren't enough resources, and the people moved elsewhere and had descendants or something idk. Maybe they didn't and all died of dehydration/starvation

Maybe they didn't go dormant or some outside force or even erebon went and destroyed them. IDK, I'm not the detail writer I'm just giving the framework.

What's left of the dying world is just the landmass the temple is on and the counter guardians that have devoted their entire being to the gods so much that the gods made them their own personal champions, and they do nothing but fight challengers and get resurrected whenever they are killed and new challengers come. Nobody quite knows if the champions like this or regret that they have consigned themselves to being basically spirit beings who have the singular goal of eternally beating on people who enter their chamber, while they, the guardians, have zero freedom to do anything else.

The temple still stands in the middle of the dying landmass, which the gods still watch intently, but for whatever incomprehensible reason none of them have taken to restoring it. Some say that the temple and the remaining amount of land to hold it is all that really matters to them, and they just let the rest crumble away for that reason. But again this is just a general idea.

Now, in keeping with this:

2. Add generation to the outside. Maybe make it a cavern, but maybe change the name and make it an End-style island or something.

![image](https://user-images.githubusercontent.com/11131230/74113784-6ae67880-4b74-11ea-9ffa-14de4dd755be.png)

2a. There would be random ruins dotted around the island which would signify the status of this island. These would be fairly common and look like broken houses or facilities or whatever. There may be some random loot chests inside the ruins with magical resources in them - or rotten flesh and bones like the desert temples have. These are common enough to be useful, and have good loot befitting a T3 dimension.

Also it may be worth changing the name from "Ancient Cavern" to "Ancient Temple" or something. It is NOT a cavern in its current state so it's not like it's a drastic thing.

2b. Inside the landmass are ores of some sort, as well as potentially some other natural resources that you can imagine being in a crumbling, ancient world (similar but far more magical and runic-type than the toxic/futuristic vox ponds). As the landmass is limited these ores aren't renewable however they their drops may be obtainable as drops from an Ancient Cavern drop table in order to have the drops renewable. These are pretty good T3 tier stuff. Also ancient upgrade kit could come from here.

2c. The portal, instead of dumping you in the temple, or working like the other portals, dumps you at a random point on the outside (however the End does it maybe). The return portal spawns as normal at your entry point and is no longer in the temple.

2d. The generation of the temple is modified, because as it currently is the boss rooms just float some distance from the temple. That doesn't come into play for current AC as seeing them from the outside is impossible legitimately, but it would definitely come into play now and honestly it feels too awkward to be kept that way.

3. Roaming the landmass are "Ancient Guardians" or something. Basically giant golem-like statues that were created to protect the temple by the magical civilization before it, they no longer have masters but they continue to serve their purpose. They roam around and try to kill players (maybe they're neutral idk) that get close, and have cool animations beyond what we have in AoA right now (low bar, I know), but have pretty good drops. The gods in their eternal indifference leave them there to test players who want to come close to their temple.

3a. Some other mobs on the outskirts would be cool but I don't have any ideas

4. In order to prevent the issue with mob drops allowing players to bypass tier requirements, AC no longer spawns the versions of the mobs we are used to. Instead, the inside spawns "ancient" versions, which look older/grayer/cooler/more metallic idk that are tougher and have different drops, such as loot unique to AC or maintain generic loot like chitin that doesn't mess with progression. In this way it becomes trivial to prevent any weird progression errors while simultaneously making the place feel better. Penumbra minion drops are still blocked.

5. The temple itself is unbreakable, but there's a temple keeper npc somewhere that sells you breakable versions of the blocks just like the immortallis dungeon keeper does. He's immortal like the dungeon keepers, and what that means for the "character" in our mod with half a paragraph of lore is up to you.

So what's the result? Yeah it's a glorified farm but it has an extra mob (plus cooler looking versions of the original four mobs), some actual unique resources, looks cooler, feels better, and is less pathetic than it is now (low bar but whatever). Upvote if this is your cup of tea, if not than upvote anyway, thanks.

**Comment by Tslat** [comment]
I like the idea of converting it into a floating world type thing rather than just an isolated structure

**Comment by Sagisolar** [comment]
Could you have a biome that starts spawning 1000s of blocks away from the center. Basically like the End City thing. Idk what would be there but just thought I had.

**Comment by Immortallis1** [comment]
I'm not a big fan of that kind of thing. The outer end is really barren too and it'd just be a copy

**Comment by Cruuk** [comment]
If I could add my own idea to this (2 months later)- I do like the idea of AC becoming a floating island with a temple in the middle. However, part of me still wants it to become a "cavern", I guess "Ancient temple" just doesn't resonate with me as much as "Ancient cavern" does.

I like to think of the Deeplands route as going deeper and deeper in a metaphysical way, with AC and Immortallis being at the very "bottom" of reality. In an attempt to justify this mindset without compromising this whole suggestion, I think it would be cool if AC also had a **ceiling**.

It'd be like a reverse-Bedrock layer. The island would probably be around maybe uhh y=64 or something, then at y=128 you'd have this endless ceiling made of an unbreakable block, looking like a more extreme version of a roofed dimension's bedrock/dim fabric ceiling- maybe with stalactites and all that fun stuff.

Having a ceiling in an old, desolate void dimension could really drive home the fact that you're at the very bottom, and that the place is definitely very very old.
I know that MC doesn't like big floating things in void dimensions, but I imagine that a place like this wouldn't have skylight, right? In that case it shouldn't cause an issue for performance, yes?
