### ISSUE TITLE
[Suggestion] Config option to prevent Bloodlust / Heartstone spawning from certain mobs?

### ISSUE THREAD

**Issue by Z-Tunic** [Tslat/Advent-Of-Ascension#1217]
I wonder if there could be a configurable blacklist option to prevent Bloodlusts & Heartstones spawning from mobs.

The blacklist would work by either the 'modid' or 'modid:entity'. If I were to add... say 'minecraft' in this list then all mobs that are from minecraft will no longer spawn Bloodlusts when damaging them or spawn Heartstones when KO'd. If I instead add in 'minecraft:villager' then all villagers from minecraft won't spawn them while allowing other mobs to spawn them... as long as they aren't in the list.

**Comment by Tslat** [comment]
Done in 3.3
