### ISSUE TITLE
Resources of some items are lost

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1218]
**Mod Version**
3.2.4

**Describe the bug**
The raw fish dropped by corallus and the flower in garden castle are all resource lost.

**Screenshots**
Raw fish without resource
![bug1](https://user-images.githubusercontent.com/59332746/74118411-4fbc4d00-4bf6-11ea-997e-14d36f81ab8f.png)
![bug2](https://user-images.githubusercontent.com/59332746/74118414-521ea700-4bf6-11ea-876b-ab3cd90e24c7.png)
Flower without resource
![bug3](https://user-images.githubusercontent.com/59332746/74118459-74182980-4bf6-11ea-8409-fe58aba275d5.png)
What it should look like (from MC)
![bug4](https://user-images.githubusercontent.com/59332746/74118486-8db97100-4bf6-11ea-8a26-863475465cff.png)

**Comment by Tslat** [comment]
Fixed
