### ISSUE TITLE
Utopian Armor can't work

### ISSUE THREAD

**Issue by kuanmi** [Tslat/Advent-Of-Ascension#1220]
**Mod Version**
v3.2.3

**Describe the bug**
The increse xp get doesn't work. The number which told you how many you get in the screen is right. But in the delete menu, it only add the xp without utopian armor.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get and equip utopian armor
2. Choose one skill and remember the number
3. Get some skill xp(skill summon is a good way to test it).
4. See the xp you got, then see the xp you exactly got.
5. See error 

**Expected behavior**
It turelly get increase xp, or it just a joke. 

**Screenshots**
![20200210-1](https://user-images.githubusercontent.com/60880276/74149183-22958c00-4c42-11ea-8c80-48828fc59588.png)
![20200210-2](https://user-images.githubusercontent.com/60880276/74149185-245f4f80-4c42-11ea-8ecf-c39810622759.png)
![20200210-3](https://user-images.githubusercontent.com/60880276/74149188-24f7e600-4c42-11ea-87e4-656e7ebf8fee.png)

**Comment by EatingSilencer** [comment]
3.2.4 is the latest version, not 3.2.3.

**Comment by Tslat** [comment]
Fixed
