### ISSUE TITLE
hunter mob aggro

### ISSUE THREAD

**Issue by free-muffin** [Tslat/Advent-Of-Ascension#1221]
version: 3.2.4

bug: mobs that require higher hunter level than you have aggro to you when they should not

don't really think this needs more explanation, if i need to provide more info tho just say something

**Comment by Tslat** [comment]
Hunter mobs that spawn from spawners are intentionally aggressive.
The non-aggro only applies to naturally-spawning mobs

**Comment by free-muffin** [comment]
got it, thanks!
