### ISSUE TITLE
AOA3 Crashed in Multiplayer Mode！

### ISSUE THREAD

**Issue by Alesteria** [Tslat/Advent-Of-Ascension#1222]
AoA3.1.2.b-AoA3.2.4 and so on

Minecraft is Crashed by
![2020-02-11_17 34 34](https://user-images.githubusercontent.com/60919062/74224779-6e087280-4cf4-11ea-8afc-9890a844b0f9.png)
this guy
and then the bug report
![image](https://user-images.githubusercontent.com/60919062/74224519-f9353880-4cf3-11ea-881c-149078482057.png)

and not only in Multiplayer Mode, Singleplay can meet it too(IF U OPEN TO LAN)!
**** helpme!

**Comment by Tslat** [comment]
This is caused by the SoundPhysics mod, not AoA.
