### ISSUE TITLE
Baron castle generates with the neon lights off

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1224]
**Mod Version**
3.2.4

**Describe the bug**
When Baron castle spawns, the neon lights on it are not on by default. The one I spawned in my test world before 3.2.4 still has the lights on, but the same cannot be said for newly spawned ones.

**To Reproduce**
Steps to reproduce the behaviour:
Find or spawn a Baron castle

**Expected behavior**
The neon lights being on

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/74269857-0b48b400-4cbf-11ea-82a2-3e75a72ddedd.png)
(I spawned this one in but I saw it happen with naturally-spawned ones as well)

**Comment by Tslat** [comment]
Intentional.

When the lights are on, the Tharafly spawners don't work because it's all lit up.

**Comment by Cruuk** [comment]
> 
> 
> Intentional.
> 
> When the lights are on, the Tharafly spawners don't work because it's all lit up.

Huh so that's why they weren't working a while back

At least it's still a source of free neon blocks
