### ISSUE TITLE
The green Crystal under the Crystevia lotto structure is off center

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1225]
**Mod Version**
3.2.4

**Describe the bug**
The green crystal that generates under the Crystevia lotto structure is off-center. Unplayable.
![image](https://user-images.githubusercontent.com/38159897/74270339-e86acf80-4cbf-11ea-9e5c-664d2261d6d3.png)
![image](https://user-images.githubusercontent.com/38159897/74270437-0fc19c80-4cc0-11ea-8323-e6c95e297d77.png)

**Comment by Tslat** [comment]
Fixed
