### ISSUE TITLE
Living Fungi spawns as its living form and not hiding

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1226]
**Mod Version**
3.2.4

**Describe the bug**
Living Fungi appears to spawn naturally as its second form, skipping the hiding form. I know it's not just them taking damage, since I've seen them spawn in flat areas with no hazards around. I don't think it's intentional either, Hiding fungi is still in the mod.

**To Reproduce**
Steps to reproduce the behaviour:
Go to any Taiga biomes and see Living fungi spawn as itself and not hiding.

**Expected behavior**
Hiding Fungi spawning instead of the living form

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/74271404-b0fd2280-4cc1-11ea-8669-e0036a423561.png)
![image](https://user-images.githubusercontent.com/38159897/74271484-d25e0e80-4cc1-11ea-8cff-fa2e30c5747a.png)
(EntitySpawnRegister file)

**Comment by Tslat** [comment]
Fixed
