### ISSUE TITLE
NPC villages should have 1 of the naturally-spawned Overworld NPCs upon generating

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1227]
**Describe/name the existing feature this suggestion relates to**
The Overworld NPCs (other than troll trader?)

**Describe the change or feature you think would be good to see**
The Overworld NPCs are absurdly rare. I've spent a lot of time in the Overworld from exploring a few thousand blocks and being at my base in a plains biome, and I have not seen one. I know it's not just me either. Even if you do win the lottery and see one, what are the chances you'll happen to have a name tag on you, have the things needed to trade, and if it's an NPC that's actually useful to you?

Though from what I've heard, MC's spawning system is limited and can be quite finicky. I think it would be best if vanilla NPC villages were guaranteed (or at least have a pretty high chance) to have one of the Overworld NPCs in them upon generating.
They could still be the same otherwise, being able to despawn and wander out of villages.

I think this would be a good way to make the Overworld NPCs more reliable in terms of accessibility without messing with the spawns, they're just currently far too rare to actually be useful. I don't think it would be OP either, since there are a finite amount of villages and if you're careless with NPC despawning, the nearest villages that haven't been generated may be a thousand+ blocks away. Also, you still have to actually have the required items for trading, this just removes the extreme RNG of finding them in the first place.

----------------

Troll trader is a tricky one, as it wouldn't be very fitting for him to be in villages. I'll probably make another git post for Troll Trader and Nether Lottoman. (from my experience, the latter has similar spawning issues)

**Comment by Tslat** [comment]
Sure
