### ISSUE TITLE
Modifications for Lelyetia

### ISSUE THREAD

**Issue by KiroTheBlueFox** [Tslat/Advent-Of-Ascension#123]
Quote :
Cruuk said : "I kind of feel like you should need an item that reverses your gravity in Lelyetia or something. Being able to just freely walk to the underside without anything would make it easy to avoid the mobs, and I imagine it would be very annoying to code an animation of the player actively switching their gravity when walking through any of the holes."
I like that idea

The Lands of Lelyetia are kinda first very flat, so yeah maybe make them more 3D.
But this isn't the main suggestion I had. 
The main suggestion I had is :
The Lands of Lelyetia have an underside, which is dark and kinda empty as it is unaccessible. So my idea was that falling through the holes instead of making you fall in the undersky, would inverse your gravity, and make you upside down. The underside would be kinda the night side, and the upperside would be the day side. It would make Lelyetia even more interesting to go and it would make both sides more living, with different structures, mobs and bosses.

**Comment by 22zhuyansong** [comment]
I'm surely agree with this idea that you mentioned!

**Comment by Sagisolar** [comment]
This is what the dimension should of been. Lelyetia is the most unfun dimension for me cause i'm forced to be on the upside with those annoying bee things. So the upside can help lelyetia get more content in the future.

**Comment by Cruuk** [comment]
I kind of feel like you should need an item that reverses your gravity in Lelyetia or something. Being able to just freely walk to the underside without anything would make it easy to avoid the mobs, and I imagine it would be very annoying to code an animation of the player actively switching their gravity when walking through any of the holes.
