### ISSUE TITLE
Transferring from the lower level of lelyetia to other dimensions will cause players to float

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1230]
**Mod Version**
3.2.4

**Describe the bug**
Transferring from the lower level of lelyetia to other dimensions will cause players to float

**To Reproduce**
1.Enter the lower level of lelyetia
2.Transfer to other dimensions with TP instruction(For example, TP, a player in overworld)

**Comment by Tslat** [comment]
What were you using to teleport? This shouldn't happen with normal teleportation methods

**Comment by Tslat** [comment]
Try this again in the next version

**Comment by Wind-Xing** [comment]
Retry in 3.2.6: the bug still exists in the server
Just go to the lower level of lelyetia, and then /spawn
If your home is outside of lelyetia, /home can also
It doesn't seem to trigger in single player mode, I ignored this in my report

**Comment by Tslat** [comment]
It may be the server plugin not calling the proper events..
