### ISSUE TITLE
nullpointer

### ISSUE THREAD

**Issue by AnimalLover567** [Tslat/Advent-Of-Ascension#1234]
**Mod Version**
3.2.4

**Describe the bug**
When i initially created the world it loads in fine, i exited the world and now everytime i try to go into the world it crashes with a  java.lang.NullPointerException. [here](https://pastebin.com/wRFGfipd) is the crashlog and no i'm not playing on a multiplayer server.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create World
2. Exit World
3. Try to load said world

**Expected behavior**
I expect to be able to reenter my current world without an issue

**Screenshots**

**Comment by Tslat** [comment]
Oh ffs

Haven't looked yet
But it's probably BetterAdvancement's fault

**Comment by Tslat** [comment]
Nope, this is Triumph's fault.

**Comment by Tslat** [comment]
Ok so Triumph has a config option to stop it from removing other mod's advancements. Set that to false
