### ISSUE TITLE
Implementing anima and logging

### ISSUE THREAD

**Issue by xCrimsonCursex** [Tslat/Advent-Of-Ascension#1235]
The skills of anima and logging
I believe anima and logging can be implemented into one skill. This can be done in a skill tree aspect, logging on its own feels a bit too straightforward and you can just afk chop logs and be 100 eventually. As for anima you can have a massive farm and be level 50 in a day of doing so. It's like playing skyrim and cheating the sneak skill for 6 hours to get max. 

I feel making anima into a multi-dimensional training experience through gardening only would be better than farming leaves. Each dimension could have it's own crops and you'd have to grow them to increase levels beyond a certain point, each would give a different level of experience depending on how difficult they are to obtain. As for logging, implementing it in a way to have multi-dimensional use would be nice to see as well. As of now just farming trees and having a full inventory of wood, doesn't feel that rewarding and I feel we could use that area for a new skill instead by combining both anima and logging in a way that feels more rewarding and balancing. Those 2 skills in general feel as though you don't need exploration to other dimensions in order to have 100 levels. It's as if they're disconnected from the dimensions completely

You could also make logging part of anima in a way where a skill tree doesn't exist, but both are implemented into leveling up anima as well. I just feel like logging on its own isn't really a skill as much as a grind and everyday task and the same with anima. If you like to farm it really doesn't feel like a skill, it's just a typical Minecraft feel.
For anima, you could add a few crops to each dimension or rare crop drops from mobs that will help improve your anima when harvested a lot. Example would be creepberry has a 6% drop from creepbirds. Make it so if you want to level up further you can have tasks for each dimension to level up the skill. Example would be to harvest 30 of this or 5 of these rare crops. These crops can implement into potions or give bonus effects as well as additional rewards for completing the task instead of being rewarded as often. As for logging, there isn't really a task setup. It's just about getting wood, so implementing it into anima and tasks within anima would provide more in depth gameplay without having the grind.

Not sure if it's been talked about before nor if there's anything existing on it. I just feel that those 2 skills being implemented into one, would open up a spot for a new skill as well as broaden the in-game depth and feel of anima in general. This would make it more rewarding and combine well with dimensional exploration.

**Comment by ErasoftMx** [comment]
Based on your logic explained here, then why not merge Foraging as well?

**Comment by xCrimsonCursex** [comment]
I feel if the skill tree option exists, then extraction could be a skill
tree within foraging. The principal of obtaining resources through mining
or extracting could be under the same skill. You would have the option to
go through the extraction tree or a miner skill tree in that aspect. If
that makes sense, since they revolve around getting resources from below
the earth

**Comment by xCrimsonCursex** [comment]
With anima and logging, I feel they are based on life on plants, so by
that means, implementing them together would bring more synergy between
both since you get anima from leaves which are attached to the trees. So
they exist together in a tree aspect, why not have them coexist together in
a skill aspect. Whether it be 2 skill trees in the anima skill or combining
them both together into one skill.
   With foraging it's based on mining and extraction based on lava and
obtaining resources from it. So those both could be implemented into one
skill if not a set of skill trees that take you to other paths. Each tree
would have tasks to complete to level them up as well and later on could
have a quest line added to them to make them even more in depth. For quest
line you could implement a quest line for each skill as well. This would
consist of several tasks to complete in each dimension.

**Comment by Tslat** [comment]
Wouldn't it be weird to have a skill based around life and plants be merged with a skill about killing trees?

**Comment by xCrimsonCursex** [comment]
In a way yes, but at the same time killing crops to get resources is the
same as killing a tree to get its resources. You're creating and destroying
life both, well if you replant the trees anyways, think about it with
magic, you have the good magic and then you have necromancy and such. You
usually have a dark side of a skill tree and a light side. So by
implementing them both together, the killing of trees could be the dark
side of the skill tree.
