### ISSUE TITLE
Runic Greatblade's magic damage doesn't work(?)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1237]
**Mod Version**
3.2.4

**Describe the bug**
It appears that Runic greatblade is dealing around ~4 less damage that it's supposed to, which leads me to believe that its magic damage isn't working. Oddly enough though, it still deals 4 damage to melee-immune mobs, but everything else is taking 4 less damage. This also includes a Sever 5 Runic greatblade dealing 28 damage instead of 33 like it's supposed to.

Staves and harming potions still work, so I doubt I have a mod messing with magic damage. A 50-HP mob died in 3 hits from Runic greatblade, which is supposed to deal 25.5 damage, so it's not a visual bug from Torohealth either.

**To Reproduce**
Steps to reproduce the behaviour:
Hit a mob that doesn't have armor nor attributes with Runic Greatblade.

**Expected behavior**
Runic greatblade dealing its full damage.

**Comment by Tslat** [comment]
Fixed
