### ISSUE TITLE
Kaiyu temple trap blocks do not laugh (sad)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1238]
**Mod Version**
3.2.4

**Describe the bug**
When you step on the Kaiyu temple trap blocks, they do not laugh. I have checked all types of sounds I usually have off, nothing. The sound is still in the files as well, so I don't think it was intentional. They appear to function correctly otherwise, but there is no laughing.

**To Reproduce**
Step on the blocks. (in survival mode)

**Expected behavior**
I want them to laugh.

**Comment by Tslat** [comment]
Intended

**Comment by Cruuk** [comment]
> 
> 
> Intended

Nooooooooooooooooooooooooooooooooooooooooooo
