### ISSUE TITLE
Permission request

### ISSUE THREAD

**Issue by ViceEye** [Tslat/Advent-Of-Ascension#1240]
Hello, 

I am a big fun of AOA, so I would like to request permission of using your texture images to reprint the wonderful weapons and blocks in bedrock edition. And also upgrade them to higher resolution, and share what I made with you undoubtedly. To do these I really need your permissions. 

It would be great if we could talk about these.

**Comment by EatingSilencer** [comment]
I'm not the developer, but just curious, what would you be using them for in bedrock edition? A BlockLauncher script? An addon? A resourcepack?

**Comment by Tslat** [comment]
I do not give permission for any of my assets to be used elsewhere, and I do **not** give permission for the mod to be recreated or simulated on any other modloader or version of Minecraft.
