### ISSUE TITLE
Elytra Config option

### ISSUE THREAD

**Issue by CandyPoeperRuben** [Tslat/Advent-Of-Ascension#1241]
well, currently, i heard the elytra will decay it's durability faster, when you have AoA installed...

so i'd like to see a config option, to disable/enable this feature, because currently, aoa will do this over all dimensions, not just the AoA dimensions, while i really want to be able to use my elytra, especially in places like the twilight forest or the end itself, because i installed some end base mods

an alternative option should be to enable/disable this feature in specific dimesions, so enable it in the aoa dimensions, and disable it in the overworld, and nether and end etc...

i actually don't know if it has been suggested before, but please think about it, because i really want to be able to use my elytra in some dimensions,

thanks from Ruben (CandyPoeperRuben)

**Comment by Tslat** [comment]
This has already been removed :)
