### ISSUE TITLE
Hive King doesn't render correctly in bestiary menu

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1242]
**Mod Version**
3.2.4

**Describe the bug**
In the bestiary menu, Hive King's section is there, but no model is seen on the icon. I'm guessing this is because of Hive King's spawning animation- starting out super small then growing into regular size. and the bestiary is just displaying the first frame of said animation(?)

Every other mob model works fine as far as I know. (Pixons also don't have a model displayed but that's because it's all particles so oh well)

Interestingly enough, even if you start a new world and kill Hive king from a spawn egg (skipping the animation), the bestiary icon for Hive King still displays nothing.

**To Reproduce**
Steps to reproduce the behaviour:
Kill Hive King and have his section appear in the bestiary

**Expected behavior**
Hive King's model displaying like everything else.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/74590063-d76fd600-4fbf-11ea-94ac-4c1c5e6eb1b6.png)

**Comment by Tslat** [comment]
Fixed
