### ISSUE TITLE
Too much lag for server

### ISSUE THREAD

**Issue by Allalous** [Tslat/Advent-Of-Ascension#1243]
**Mod Version**
What version of the mod are you on? 
AoA3-3.2.4

**Describe the bug**
Had a server running this mod (and of course some other mods) and even if everyone (4 people were on last time before we disabled the mod) are standing still we would lag for a few seconds and/or rubber-band backward a few ticks back. This happened enough times within minutes of each other that we had to disable to mod in our pack in order to just walk around without it lagging.

**To Reproduce**
Play with mod on a small server with others

**Expected behavior**
Would love to play more with this mod if the lagging stops

**Screenshots**
If you need it, I can give you our little pack that we made with the mods in it

**Comment by Tslat** [comment]
Provide a server log file if you want further help

**Comment by archmichaeliii** [comment]
i am the server admin and from what i can tell it is something conflicting with AoA. i have attached our debug log and server log.
[2020-02-15-2.log](https://github.com/Tslat/Advent-Of-Ascension/files/4209307/2020-02-15-2.log)
[debug-5.log](https://github.com/Tslat/Advent-Of-Ascension/files/4209304/debug-5.log)

**Comment by Tslat** [comment]
You have a lot of mods, including many big ones. You even have some buggy and broken ones in there.
It could very well just be that your hardware isn't up to the task.

If it were something conflicting with AoA, you'd see errors
All I see is a lot of hefty mods trying to run at once
