### ISSUE TITLE
Coniferon drops invalid logs

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#1244]
**Mod Version**
3.2.4

**Describe the bug**
Coniferon seems to have a drop for wooden logs, but they come with a damage value of 32767, making them an invalid item.

**To Reproduce**
Steps to reproduce the behaviour:
1. Kill Coniferon and get the log drop
2. Instead of logs, you'll get a purple/black checkerboard item like you didn't install Counter-Strike: Source

**Expected behavior**
I assume he's intended to drop regular old oak logs, or some other log type.

**Screenshots**
![2020-02-15_22 00 55](https://user-images.githubusercontent.com/28516513/74599928-bbf7e000-503e-11ea-8b43-271521a1690a.png)
Both stacks are identical damage values.

**Comment by Tslat** [comment]
Fixed
