### ISSUE TITLE
Wearing expedition armor on the server will cause crash

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1245]
**Mod Version**
3.2.4

**Describe the bug**
Wearing all of Expedition Armor on the server will cause crash

Error report attached
[crash-2020-02-16_19.41.02-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4209802/crash-2020-02-16_19.41.02-server.txt)

**Comment by Tslat** [comment]
Fixed
