### ISSUE TITLE
y thing don't work

### ISSUE THREAD

**Issue by 404cofee** [Tslat/Advent-Of-Ascension#1246]
**Mod Version**
the most recent one for 1.12.2

**Describe the bug**
crashes on start up
[crash-2020-02-16_12.54.24-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4210882/crash-2020-02-16_12.54.24-client.txt)

**Comment by EatingSilencer** [comment]
I think you have run out of ids. You will need to install the JEID (Just enough ids) or NEID (Not enough ids) mods in order to play, or remove some mods.
