### ISSUE TITLE
Nether Portal Crash

### ISSUE THREAD

**Issue by Konin-Sensei** [Tslat/Advent-Of-Ascension#1247]
Was trying out portals in creative mode. Whenever I step through a nether portal (in the nether) to return to the overworld, the game crashes. Crash report attached.
[crash-2020-02-17_18.46.36-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4216743/crash-2020-02-17_18.46.36-server.txt)

**Comment by Tslat** [comment]
Try it without other mods
There's no circumstance in which this crash should be happening

**Comment by Konin-Sensei** [comment]
Did what you said. With no other mods installed, the portal worked fine. Interestingly enough, was unable to recreate the issue with all my mods reinstalled. I added them back one at a time to try and determine what was responsible but never got the same behavior again.

**Comment by Tslat** [comment]
Could've been a freak accident.

The bit that crashed isn't specifically caused by AoA, it just so happened AoA was doing something at the time.
The circumstances in which it crashed just.. shouldn't be able to happen.
