### ISSUE TITLE
Harvesting Pixons in other dimensions gives Luxon tribute

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1248]
**Mod Version**
3.2.4

**Describe the bug**
When harvesting Pixons in any dimension (not just Overworld), it appears to give Luxon tribute. It doesn't seem to actually do anything though, even when it's full(?).

**To Reproduce**
Steps to reproduce the behaviour:
Harvest Pixons in any dimension besides Overworld.

**Expected behavior**
Not gaining Luxon tribute when harvesting Pixons in non-Overworld dims. Other than AC/Immortallis, it's not normal to gain tribute inside the dimensions themselves.

**Comment by Tslat** [comment]
Fixed
