### ISSUE TITLE
Foliage/other stuff able to break portals

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1249]
**Mod Version**
3.2.4

**Describe the bug**
It seems any foliage or structure is capable of overriding portals and making the portal blocks not appear at all. In terms of specific ones, I'd say that Creep vines and L'Borean's ponds are notable from personal experience. In the images below, it seems Creep vines is able to prioritize spawning over the portal blocks.
And for L'Borean's ponds, it seems in general they can delete stuff that spawn above them, like the pieces of an Aquatic Castle's first floor being bitten off due to spawning on a pond, so it could be the cause(?).

There could be other notable cases that I missed, though it seems foliage in general can mess with portals. I've seen Lelyetia's foliage delete 1-2 blocks of a portal frame- the portal itself still stayed intact though.

**To Reproduce**
Get unlucky with where a portal spawns

**Expected behavior**
Portals staying intact no matter what spawns on it. If all portal blocks get deleted, it can be quite an issue, since there's no way out other than cheating and placing the portal blocks down yourself, or happen to have the materials used to make the portal on you for some reason.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/74809260-9d455380-52a1-11ea-94d3-61a4830022af.png)
![image](https://user-images.githubusercontent.com/38159897/74809274-a3d3cb00-52a1-11ea-85aa-4742ddd53750.png)

**Comment by Tslat** [comment]
Most of this should be fixed in 3.2.5. Hopefully.
