### ISSUE TITLE
Can't carry over tribute effects to other dimensions

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1250]
**Mod Version**
3.2.4

**Describe the bug**
It seems that even if you get full Tribute and have it activate at night, going to another dimension makes it vanish completely. This happens with both the Ancient teleporter and vanilla Nether portal. Even after waiting 20-30 seconds after the message popped up in chat and the effect appears, going into another dimension removes the effect.

**To Reproduce**
Steps to reproduce the behaviour:
Fully gain tribute for any god, then head into a dimension after night falls.

**Expected behavior**
The effect carrying over with you upon going to a dimension.

**Screenshots**

**Comment by Tslat** [comment]
Intended for now - not because I don't want tribute to carry over to other dimensions, but because functionally it's far more painful than it sounds to code in.
I'm looking at my options, but for now this is just how it is, sorry
