### ISSUE TITLE
Whitewashing table acts a bit odd when making multiple sets of bricks

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1251]
**Mod Version**
3.2.4

**Describe the bug**
When having 1 of each applicable item in a Whitewashing table, everything works fine.
![image](https://user-images.githubusercontent.com/38159897/74812141-c79a0f80-52a7-11ea-960d-753c2d357229.png)

But when having multiple of an applicable item, it works fine for the first time, then it doesn't allow you to make any more.
![image](https://user-images.githubusercontent.com/38159897/74812286-134cb900-52a8-11ea-9baa-6c4441bd07fc.png)

However, if you take one of the applicable items out of the slots and put it back in, then it resets, allowing you to make another set. Rinse and repeat.

**To Reproduce**
Make Whitewash/Darkwash bricks with more than 1 set of the required items.

**Expected behavior**
Being able to make multiple sets of bricks without it stopping you and having to "reset" it every time.

**Comment by Tslat** [comment]
Fixed
