### ISSUE TITLE
server can`t install the mod

### ISSUE THREAD

**Issue by Aleks233** [Tslat/Advent-Of-Ascension#1252]
**Mod Version**
3.2.4

**Describe the bug**
This recipe cannot be loaded:'aoa3:ghastly_ingot_off'

**Comment by Tslat** [comment]
Known bug and fixed, thanks :)

That won't stop you from installing the mod though, it just breaks one recipe

**Comment by Aleks233** [comment]
OK,I Installation succeeded.But the mod is unamiable for server,Because CPU usage is very high.

**Comment by Tslat** [comment]
Make sure the leaderboards is turned off in the configs file on the server side
