### ISSUE TITLE
custom shields

### ISSUE THREAD

**Issue by agagsg** [Tslat/Advent-Of-Ascension#1253]
add shields you can craft with aoa items, for example Saphir schields, that have more durability and unique bonus

**Comment by Tslat** [comment]
Shields are already ridiculously powerful, I'm not sure I can do much more with them without making OP as hell items.

Tinkers does it and you basically become an untouchable god

**Comment by ErasoftMx** [comment]
Could you unregister the vanilla shield and then make new ones, starting from a new range of shields that starts with less protection/duration than vanilla one?

**Comment by Tslat** [comment]
I don't think I can think of a single example of a mod removing or changing vanilla content and it being received well..

**Comment by Sagisolar** [comment]
I think most mods tend to do them as purely cosmetic and nothing else.
