### ISSUE TITLE
Inconsistencies with Heat wave and other upgrade kit weapons

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1255]
**Describe/name the item/content this suggestion relates to**
Heat wave

**Describe the change/balance you think would be good to see**
I've noticed that something is off with Heat wave, it has less durability than Hot Shot and far less durability than other upgrade kit weapons. All of its stats are pretty much unchanged from 3.1.2.b, it just so happens to roughly line up with the average gun DPS, even it is throttled by 0.5 less damage and 450 durability.

Also, I doubt it's intentional that Heat wave has a different firing rate and less damage than Hot Shot. It still has higher DPS than Hot Shot, but pretty much no other upgrade kit weapon has this change- the closest thing is RPG Floro, but that still feels like a direct upgrade since it's the same damage with a higher firing rate. Even if Heat wave is still an "upgrade", it doesn't feel like it.

I think it would be best if Heat wave's stats got changed to balance around 0.83 fire rate like Hot Shot. (wasn't sure to label this as bug report or item balancing lol)

**Comment by Tslat** [comment]
Fixed
