### ISSUE TITLE
Add Crafttweaker/Modtweaker integration. 

### ISSUE THREAD

**Issue by Epic428** [Tslat/Advent-Of-Ascension#1256]
**Describe the new feature you think would be good to add**

Add crafttweaker/modtweaker integration. Primarily for the various machines since standard crafting recipes can be modified already. There may be other instances where integration could be used outside of just the machines as well. 

**Add any alternative implementations you think might work**
None outside of creating an addon mod to include the integrations if possible.

**Include any additional background information**

I’d really like to be able to modify recipes for the infusion table or even add recipes to it. In addition, being able to integrate the machines into a pack with other mods might give more use to the associated skills. Perhaps, even adding crafttweaker support for the skills themselves could be viable when they get overhauled in the skills update.

**Comment by Epic428** [comment]
First and Foremost sorry for this being really long. 

Adding to this per our discussion on Discord. 

[First, a link to the docs:](https://docs.blamejared.com/1.12/en/)
[Second, the Crafttweaker 1.12 github branch for reference](https://github.com/CraftTweaker/CraftTweaker/tree/1.12)
[Third, a link to the Crafttweaker discord](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fdiscord.blamejared.com%252f) -  the community is extremely active and can assist with any questions regarding adding support to AoA. (I had to copy the link from curseforge website because their discord doesn't have option for invite links to be made.)

CraftTweaker operates at various stages of the forge mod loading process. Primarily it runs in PreInit, but you can make scripts with preprocessors and define script priorities or have certain code execute after specific mods have loaded or during a mods loading phase. Any item that has a crafting table or furnace recipe I can already modify regardless if you support it or not. The main reason for asking for CraftTweaker support is to be able to access the parts of the mod that are exclusive to AoA. Infusion table, Skills, etc. <- more on this at the bottom. 

[per this doc](https://docs.blamejared.com/1.12/en/#Dev_Area/Ingredients/) most recipes will use [IIngredient](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/api/item/IIngredient.java) ([pack dev doc](https://docs.blamejared.com/1.12/en/#Vanilla/Variable_Types/IIngredient/)) in the java code. [IItemstack](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/api/item/IItemStack.java), [ILiquidStack](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/api/liquid/ILiquidStack.java), and [IOreDictEntry ](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/api/oredict/IOreDictEntry.java)all extend off of it and when creating a custom recipe some devs may choose to use a specific itemstack or an oredict entry. For example, maybe I want a recipe to use only vanilla leather or I want a recipe to use any item from any mod that has been added to the leather ore dictionary.

Most classes in your Java code that you would want to be exposed to ZenScript for pack devs to make use of will need to be [annotated.](https://docs.blamejared.com/1.12/en/#Dev_Area/ZenAnnotations/ZenAnnotation/). Depending on the annotation used, it will determine what is exposed or why it is exposed. The linked page lists all of the annotations that can be used and what they're used for.

Some examples:

[@ZenClass](https://docs.blamejared.com/1.12/en/#Dev_Area/ZenAnnotations/Annotation_ZenClass/) Exposes the Java class to the script
[@ZenRegister](https://docs.blamejared.com/1.12/en/#Dev_Area/ZenAnnotations/Annotation_ZenRegister/) will register the class to ZenScript

Any Method in a Java class that you want exposed will use an [annotation ](https://docs.blamejared.com/1.12/en/#Dev_Area/ZenAnnotations/Annotation_ZenMethod/)based on what the method is for.

Examples would be @ZenGetter or @ZenSetter, or maybe @ ZenDoc. (space due to dumb link)


You can also make custom ZenClasses or even expand on Crafttweaker to do various things. For example Loottweaker mod is an addon that allows me to modify loot tables. ModTweaker allows for deeper integration into certain mods. For example I can make custom Tinker's Construct Alloy recipes, or custom smelting recipes. I can make new materials from scratch for tinker's or new parts.

There is plenty of examples and information in the docs on how to add support for crafttweaker to a mod. It's also relatively simple after reviewing the docs and the amount of extra stuff needed is minimal. There's literally 18 pages of docs specifically for this purpose covering everything needed to know. I also have not listed everything but hopefully enough to get started and grasp what's going on. 

----------------- below is why I request this and what I've been able to use it for --------------


To show you how I was able to so far integrate AoA into my mod pack with the use of Crafttweaker, Contenttweaker, and Modtweaker: https://imgur.com/VgnkXd5

I made a custom item with ContentTweaker. It's the cast you see on the right. I then made a recipe for the smeltery so that 576mb of liquid steel poured into that cast would output the AoA gun frame on the left.

The vision for my pack is one that has a heavy focus on both technology and exploration. I want to combine them together. I played a lot of tech packs and spend a lot of time in a hole. But I love exploring Minecraft worlds. My example above is part of an idea I have for my pack where the player builds a factory that can produce weapons. The weapons can then be sold to merchants and in return the player gets AoA coins. These coins will be used not only for their normal AoA purposes but also to obtain other more rare items/ores. For example I am combining this mod with Gregtech CE. I have vanilla ore gen disabled. So some ores will be extremely hard to find and as such I want to entice the player to build up a factory to get money to get stuff that's harder to find. That's only one facet of the pack, as I have many other ideas.

To expand on this further and why I request the Infusion table be the first to get CraftTweaker support. I have made two custom fluids. One called Ink and the other Enchanted Ink. The ink is gotten by putting ink sacs into a cauldron. The Enchanted Ink is made by putting ender dust from Tiny Progressions into a cauldron filled with ink that's "boiling". I then plan to use Artisan Worktables (scribe table) to make enchantment books. The table uses an amount of Enchanted ink and other ingredients to make the book. I plan to then use the infusion table to apply the enchantment to whatever item by putting the item and the book into the table,

https://imgur.com/BohtIHk

I have everything done so far but the infusion table stuff. And thus far I wouldn't have been able to accomplish any of it if the numerous mods I used didn't have crafttweaker support. Specifically, Crafttweaker, Inspirations, ContentTweaker, Tiny Progressions, SimpleCampfire (campfire can be used to heat the cauldron). I wouldn't have been able to make custom Tinker's recipes without it having support.

To also expand on why Jar Hacking is not good for pack development. When I upload a mod pack to curseforge, anyone downloading the pack will download the mods from the site itself. It's how the packs work. As such players won't get any of the changes I have made to the AoA jar file because Curseforge isn't hosting my modified version.

Lastly, some other additions I would like. If I could customize the realmstone that would be awesome. (might be more difficult though) Primarily, I'd like to access the end with it. The extraction device might also be a good one to support, you could use the device to then create things other than lava. Other blocks which perform a function or act as a machine of sorts would work.

And finally the biggest reason for implementation: Adding the ability to interact and customize skills better. Maybe I want a certain mod or action to become compatible with logging or mining. or maybe I want to make it so certain parts of the pack are gated behind infusion levels or butchery levels. so being able to obtain info about the players levels would be very useful. Also when pack creators or end users can integrate into the mod deeper you might find that they are able to add to the community by coming up with ideas you might add to the mod and support directly. they might find ways to use the mod for things you didn't think of that enhance the experience.


OK I'm done, This is really long and I hope I have provided enough info. If there's any questions please ask. You can pm/ping in discord. I can't follow chat all the time.

**Comment by Epic428** [comment]
I should also note that unless CraftTweaker does something in the background I'm unaware of. It basically uses a custom scripting language that hooks into forge. Other mods then expose their classes and methods to this scripting language. Because everything happens at the PreInit stage it can be modified before it gets baked into the forge registries. That's why recipes can be changed, items added, items hidden in JEI or recipes removed, etc. In addition, the mod was design to allow novice pack devs to make and customize a pack but so that more experienced developers could do some really powerful stuff with the mods available.

**Comment by Epic428** [comment]
Immersive engineering has crafttweaker support. Checked out the blast furnace as it’s a basic machine and class structure/functionality is somewhat similar. Linking the relevant files as points of reference for implementation. Over the next few days I’ll see if I can try and get basic functionality working with AoA. Can’t guarantee code will be great but it’ll be a good place to start from. After perusing how blast furnace has support implemented it seems trivially simple to add in.


https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/api/crafting/BlastFurnaceRecipe.java

https://github.com/BluSunrize/ImmersiveEngineering/blob/b3b193048359eb8a145ae797119895a4a794220a/src/main/java/blusunrize/immersiveengineering/common/IERecipes.java

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/BlastFurnace.java

**Comment by Tslat** [comment]
Are you on Discord @Epic428 ?
I'd like to discuss this a bit further with you if possible

**Comment by Epic428** [comment]
@Tslat Hey sorry been buried deep in Mod Dev last couple days. I do have discord Epic_Oreo#3283

**Comment by Tslat** [comment]
Done in 3.3
