### ISSUE TITLE
Spectral Wizard Spawner works in the Overworld but not in Runandor.

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1257]
**Mod Version**
3.2.4

**Describe the bug**
Spectral Wizard spawner doesn't spawn Spectral Wizards when standing near it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the difficulty to Easy, Normal or Hard
2. Go to Runandor and place a Spectral Wizard Spawner or stand near one in a Spectral Wizard cage.
3. Wait

**Expected behavior**
Spectral Wizards should appear.

**Comment by Tslat** [comment]
It's not that they don't work, it's that the structure generates with 2 light-emitting lamps right on top of the spawner lol.

I'll turn em off
