### ISSUE TITLE
Breakable version of Archaic ladder is wonky

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1258]
**Mod Version**
3.2.4

**Describe the bug**
The breakable version of Archaic ladder appears to have some odd properties, mainly 2 of them from what I've seen.

1: It displays really weirdly while held, both in first and third person. (pictures can be seen in the screenshots section.)

2: Breaking it does not give the item back. Even if mined with a silk touch Axe it does not give the item back, same thing happens if you break the block the ladder is attached to. Doing any of these methods with the vanilla Ladder does give the item back.

**To Reproduce**
Steps to reproduce the behaviour:
Hold the Archaic ladder

Attempt to break the Archaic ladder.

**Expected behavior**
Archaic Ladder having similar properties to the vanilla Ladder.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/75100408-010d9c00-5582-11ea-8c27-54859a6201a2.png)
![image](https://user-images.githubusercontent.com/38159897/75100420-15ea2f80-5582-11ea-8d60-0ea96cc0a2b5.png)

**Comment by Tslat** [comment]
Fixed
