### ISSUE TITLE
Return portals not returning to the teleporter.

### ISSUE THREAD

**Issue by goreae** [Tslat/Advent-Of-Ascension#1259]
Tested using AoA version 3.2.4, in a pack with only AoA, JEI, JEI Integration, and Just Enough Resources installed. For reference, "teleporter" is used to refer to the player-built portal that allows access to other dimensions and "return portal" is used for the portal that's generated once you go into a dimension. 

Return portals can in some situations get stuck not returning you to the teleporter. It seems if you put the teleporter at sea level and then have a return portal at a lower Y level, then move the teleporter to a higher elevation, it causes return teleporters to break, sending you somewhere near the teleporter, but not at the teleporter itself.

Reproduction steps:
1. create a new world.
2. Find a mountain in said world
3. Build a teleporter near sea level.
4. Activate the teleporter with a Barathos realmstone, enter it, then go back to the Overworld.
5. Destroy the teleporter and build a new one on top of the mountain.
6. Activate it with a Deeplands realmstone and enter it and return to the Overworld.
7. You'll find you do not come back in the teleporter, but somewhere nearby.

I used seed -8682720438014382403 for my testing. I put the first teleporter at -148,32 and the second at -177,26. The return portal placed me at -300,-17.5, though the exact position changes.

Also interesting is when I went back to Barathos using the new teleporter and destroy the return portal and use /kill to get back to the Overworld, suddenly the deeplands return portal works just fine again. Which is why I think it's some weird linking thing. Like the return portals think they're going to a specific teleporter even though that teleporter doesn't exist anymore. 

Also interesting is the reproduction steps don't work if you do it the other way around. If the first teleporter is on the mountain and the second at sea level, return portals work just fine. But if you then the teleporter on the mountain back, return portals start breaking again. High>low works just fine but low>high breaks return portals.

I discovered this because on my world, I tried to create a teleporter in a dimensional doors pocket dimension, the floor of which is Y level 4, but it didn't work for reasons on dimdoors' side. I then tried to move my teleporter to my mountain base, but it kept returning me to this lower-elevation field away from the teleporter no matter what realmstone I used. While it was in the pocket dim, I opened the portal with a barathos and nether realmstone. I also tried deleting all of AoA's dimensions folders and the dim-1 folder to try and fix it but that didn't help either.

All the explanations I have here are basically just guesses. I'm not sure what the issue is so I'm just providing all the info I can.

**Comment by Tslat** [comment]
Try this again in 3.2.5, it should be fixed

**Comment by goreae** [comment]
Just to update, it does indeed seem to be fixed. As an added bonus, the issue with dimensional doors seems to be fixed by the update as well. Hurrah.
