### ISSUE TITLE
Compatibility with Better Portals

### ISSUE THREAD

**Issue by noswanson1982** [Tslat/Advent-Of-Ascension#1261]
I think it would be cool to have functionality with the Betterportals mod.  Being able to see through the portal into the dimension you are teleporting to, would just look cool.  He can't/won't do anything like that with the mod as "close-source," so I was hoping it would be possible to extend the possibility of functionality there.

**Comment by Tslat** [comment]
Ask the BetterPortals guys - I already question them about this very early onto their dev, and they said that compat with other mods would have to be done by them

**Comment by noswanson1982** [comment]
I did ask this of the person behind Better Portals.  He said that due to a lack of visible source or lack of usable source, he could not do that.  His reply was:

>  Yes, read the description. It lists all mods for which explicit support has been added to BP.

>  In general, if you're wondering whether a specific mod which isn't listed works, check the issue tracker. If it hasn't been rejected yet, feel free to open a new issue. In this specific case, I can already tell you that the answer will be the same as https://github.com/Johni0702/BetterPortals/issues/447 (without the sentence about lack of visible source but instead with one complaining about lack of usable source).

So, apparently unless he has a source, he can't work on it.

**Comment by Tslat** [comment]
Yeah I'm not a fan of having other mods have to recode _my_ mod to have to work.
The source is visible here:
https://github.com/Tslat/Advent-Of-Ascension/tree/master/source

But if wants to be able to PR my code it won't happen because AoA isn't developed like that
