### ISSUE TITLE
Battle rage should have a cooldown similar to Energy's

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#127]
Something of an issue I've always noticed with battle rage is that you have a chance to get multiple rage crits in a row. I know the chance is pretty low, but the chance is still there. Even at a 1 it's still a 0.5% chance, and rage regen moving faster at higher levels amplifies this.

I know it's a very small request, but I think Battle rage should have the same cooldown Energy has (maybe even like a second longer?). I just feel like it would make sense for a chance-based resource, especially considering how strong rage crits get. Just something to keep the rage crits a little more "controlled".

**Comment by Tslat** [comment]
Done after snapshot 9.
