### ISSUE TITLE
Bukkit create world problem

### ISSUE THREAD

**Issue by 2191746730** [Tslat/Advent-Of-Ascension#1271]
When the new world comes into being.
The world will not generate blocks and monsters with modules.
Request for solution,Thank you.
If you can, please leave your contact information,Thanks again!

**Comment by Tslat** [comment]
AoA is a forge mod, not a bukkit plugin

**Comment by 2191746730** [comment]
Forge server create world is also.

**Comment by 2191746730** [comment]
Normally, when forge server creates a new world, module blocks and monsters should be generated normally, but they will not

**Comment by Tslat** [comment]
provide a latest.log file from your logs folder on the server

**Comment by 2191746730** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/4271307/latest.log)

**Comment by Tslat** [comment]
Catserver doesn't support AoA

**Comment by 2191746730** [comment]
OK,Do you have a service like catserver that supports bukkit and forge.

**Comment by 2191746730** [comment]
Or let the module support catserver (I can also modify the code, but I need your help)

**Comment by Tslat** [comment]
No I don't

Services like those tend to have compatibility problems, because Bukkit and Forge were not designed to run together

**Comment by 2191746730** [comment]
Do you have a forge server that supports modules? Is it convenient to recommend one

**Comment by Tslat** [comment]
Modules?

Forge supports mods

**Comment by 2191746730** [comment]
Forge server name?

**Comment by Tslat** [comment]
Forge?

Forge is a server wrapper

**Comment by 2191746730** [comment]
It is the server core that can be perfectly compatible with this module.
