### ISSUE TITLE
Are Undead Herald's token trades too expensive?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1272]
**Describe/name the existing feature this suggestion relates to**
Any of the 32 token Undead Herald trades

**Describe the change or feature you think would be good to see**
I know comparing functional items (Lottomen trades) vs. decoration items (banners) is no contest, it's more about the perception of I think. 1 basic banner costs more than Lotto totem, which doesn't make the banners feel very "accessible" I think.

I'd group the Lottomen trades into 2 groups: the "ammo" trades (rune and weapon box, runes are technically ammo), and the "useful item" trades (Treasure box and Lotto totem). The latter can be quite useful, but is harder to buy in bulk, so you have to be careful with how you spend. So when you see a decoration item that is more expensive than the useful item trades, it just makes it seem very unappealing. The banner is also the lowest tier out of 4 tiers, who would want to hang up the boring grey one? You have 3 upgrades but the high price makes it even more unappealing to try and buy enough to make the first banner upgrade.
If I did the math right you need 40.5 stacks of tokens for the 2nd highest tier banner, a player's inventory has 36 slots + the 1 offhand slot. I know the 2nd highest tier banner should be expensive, but I feel like that's a bit much. Bejewelled banners require 364.5 stacks lol, at that point it just becomes more worthless than colored bricks because of the price and space needed.

As a player, I like banners quite a lot, but the prospect of them being more expensive than Treasure box/Lotto totem just doesn't seem right. I just don't see a good reason for the basic banner to be 32 tokens. Other than Lotto banner, the only Gold banner I had was a Gold clown banner because 1: you know me and 2: I only got it because the Lotto structure would be annoying to get to, and I could just use other Lottomen.

Anyway, I feel like it would at least make more sense for the basic banner to be in a similar price range to Rune/Weapon box, something like **12-16** tokens. Again, I know functional items vs. decoration items is a losing battle for the latter, but I think it would make the banners feel a bit more appealing and accessible. Just half a stack can be seen as a high price considering the other options you have. It's fine if the higher tiers stay expensive, but the basic one should be easy to get after spending a bit of time in a dimension.

**Comment by Cruuk** [comment]
To be honest I wasn't thinking perfectly straight typing that whole tangent lol, though it is something that has been bugging me for a while now. I just figured I'd let it out now rather than wait a long time to do so.

**Comment by Tslat** [comment]
Actually I've been thinking about this a bit post-3.2.4, and I agree
