### ISSUE TITLE
Floracle seed is unobtainable due to Red Waterweed not generating

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1276]
**Mod Version**
3.2.4

**Describe the bug**
The foliage that drops Floracle seeds, Red Waterweed, is one of the biome blocks originating from 2.5 snapshot, and does not generate in current versions. This means that there is no way to obtain Floracle seeds. I'm guessing Scimi just wasn't aware of Red Waterweed's difference from the others at the time when making it drop from that foliage..

**To Reproduce**
Steps to reproduce the behaviour:
I do not believe Red Waterweed generates naturally, so good luck trying to find one.

**Expected behavior**
Floracle seeds being obtainable. Whether it be making Red Waterweeds generate, or making something else like Pink Coral block drop it instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/75765549-8c123300-5cf4-11ea-97af-b7e461fc7976.png)
(Tslat 1.1 was the first time biomes were in a fully released version)

**Comment by Tslat** [comment]
No it's not I made red waterweeds spawn rarely in lborean in 3.2

**Comment by Cruuk** [comment]
> 
> 
> No it's not I made red waterweeds spawn rarely in lborean in 3.2

oooooooooooooooooooooooooooooooooooooooooooooooops
