### ISSUE TITLE
Vile Vanquisher extremely overpowered (urgent)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1279]
**Describe/name the item/content this suggestion relates to**
Vile Vanquisher

**Describe the change/balance you think would be good to see**
Vile Vanquisher is a T2 gun you get by infusing, that's about it. Though, its damage output seems to match with T3 weapons despite it not being something special like a boss drop. In terms of DPS it very much contends with MK, Squad Gun, Abominator, Haunters Rifle, Purity Rifle (without boost), and more. This only considers the base damage, not the poison effect. This can simply be fixed by changing the damage number, or changing the fire rate.

**Comment by Tslat** [comment]
Fixed
