### ISSUE TITLE
Variety of seed ammunition for Gardener/Dart Gun

### ISSUE THREAD

**Issue by Cicopath** [Tslat/Advent-Of-Ascension#1280]
**Describe/name the existing feature this suggestion relates to**
_Dart Gun_, _Gardener_ and all of the seeds (_Beetroot Seeds_, _Tea Seeds_, _Holly Top Seeds_, etc.)

**Describe the change or feature you think would be good to see**
When you first encounter the Gardener gun from harvesting wheat, you would expect by the description of it when you hover over it that it will accept any kind of seeds, until you try to attempt using other seeds rather than just wheat seeds. Based on the name of this weapon and how you obtain it, all seeds from both Vanilla Minecraft and Advent of Ascension should be able to be used as ammunition for the Gardener. This should also apply to the Dart Gun, since it uses seeds as ammunition.

**Add any alternative implementations you think might work**
Since other mods are bound to add some seeds to your gameplay, I would suggest adding a configuration file where you can add the IDs of any seeds from Vanilla, AoA, or other mods to be compatible with weapons that use seeds as ammunition. (Gardener and Dart Gun.)

**Comment by Tslat** [comment]
Done in 3.3.2
