### ISSUE TITLE
Gyro can be summoned with the Toy Gyrocopter outside Celeve

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1281]
**Mod Version**
3.2.4

**Describe the bug**
When I used the Toy Gyrocopter in my base in the Overworld his spawn sequence started and he appeared as he would if you spawned him in Celeve. I don't know whether this is intended.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the difficulty to Easy, Normal or Hard
2. Use the Toy Gyrocopter in the Overworld, or another dimension (Not tested this myself)
3. The message "Time to play, player" will appear in chat, his intro sequence will begin and Gyro spawns after a few seconds as normal.

**Expected behavior**
There should be a chat message saying "Gyro can only be summoned in Celeve."

**Screenshots**
![2020-03-04_09 51 20](https://user-images.githubusercontent.com/52132442/75867043-e34ffa80-5dfd-11ea-9817-e44eeb264ce5.png)
![2020-03-04_09 51 30](https://user-images.githubusercontent.com/52132442/75867052-e64aeb00-5dfd-11ea-839f-b3b3d6fbed44.png)

**Comment by Tslat** [comment]
Yeah I don't really have an issue with him being spawned outside of Celeve to be honest
