### ISSUE TITLE
Link to mod page?

### ISSUE THREAD

**Issue by squiig** [Tslat/Advent-Of-Ascension#1282]
Is there a curseforge/minecraftforum/other page for this mod? Would be helpful if that link was in this repo description or readme

**Comment by EatingSilencer** [comment]
There is a curseforge page:
[](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine)

There is also a minecraft forum thread, but its old and we don't really use it anymore:

[](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1286381-aoa-25-new-dimensions-330-mobs-27-bosses-skills)

Unrelated, but there is also a discord server for this mod:

[](https://discordapp.com/invite/DNYqNNq)
