### ISSUE TITLE
Energy/Moon Cannon's unusual bonus damage calculations against armor

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1283]
**Mod Version**
3.2.4

**Describe the bug**
Energy Cannon and Moon Cannon's higher damage against armor seems a bit unusual compared to others. I compared Energy Cannon to Super Cannon, which has the same base damage (and I made sure Super Cannon also did bonus armor damage).

Against a Paladin, Super Cannon did 17-18 damage, and Energy Cannon did 36 damage. Moon Cannon also did around 40 damage when cannons of similar/higher damage did less. I'm guessing the magic damage is messing with the calculations. Stuff like Ancient Golem also took more damage from Energy/Moon Cannon compared to other cannons.

**To Reproduce**
Steps to reproduce the behaviour:
Shoot any armored mob with Energy/Moon Cannon, and compare it to cannons of similar damage.

**Expected behavior**
Energy/Moon Cannon dealing similar bonus armor damage to other cannons. I'm sure the magic damage will still pierce armor, but more than twice the usual bonus armor damage? Damn

**Comment by Tslat** [comment]
Fixed
