### ISSUE TITLE
Vox Cannon is sad

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1285]
**Describe/name the item/content this suggestion relates to**
![image](https://user-images.githubusercontent.com/38159897/76034537-0b218a00-5ef4-11ea-9eef-820904b23e8d.png)

**Describe the change/balance you think would be good to see**
Vox Cannon has always been sad, I just forgot about it for a while which is why I didn't make this sooner. Even if did good poison damage back then, it was still probably the worst weapon in the mod. Now the poison does 3 damage. But hey its fire rate was buffed to 0.76!

It drops from Nightwing, who is a hunter mob, so it is very much T2. I think the damage was just missed when Scimi was rebalancing the weapons. There's nothing else really special to balance that 6 damage, it just gives poison I for 5 seconds.

**Comment by Tslat** [comment]
Done, looks like it got missed somehow
