### ISSUE TITLE
Modded Repair Support

### ISSUE THREAD

**Issue by goreae** [Tslat/Advent-Of-Ascension#1287]
For the future mod support update that's planned, it would be fantastic to have some repair support for guns, staves and bows. 

For context, I play with an incredibly unbalanced selection of mods, and one key feature that I love having available is the Evilcraft Blood Chest, which repairs items using the blood of your enemies. Issue being the the only AoA items that really repair in it are armor, swords, and tools. Everything else is only repairable via mending or the mending table. It's not only the blood chest either. They weren't repairable in either of Cyclic's anvils nor in Actually Addition's item repairer.

It'd just be nice to have the option to enable repairability for AoA weaponry. Even if it's disabled by default.

**Comment by Tslat** [comment]
Done in 3.3
