### ISSUE TITLE
Enigma Stations do not spawn in Vox Ponds

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1288]
**Mod Version**
3.2.4

**Describe the bug**
No matter what the spawn chance is for the Enigma station in the config file, even when the number is set to 1, Enigma Stations don't seem to spawn underground in Vox Ponds. Setting the spawn chance to 1 also seems to stop all other Vox Ponds structures from spawning entirely, except for Poison Rune Shrines.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the Enigma Station Spawn Chance to 1 in the aoa structures config file
2. Create a new world and go to the Vox Ponds
3. Go underground and attempt to find an Enigma station

**Expected behavior**
Enigma stations should spawn in every chunk

**Screenshots**
First screenshot shows a birds eye view of Vox Ponds via VoxelMap. No structures are seen except for rune shrines.
![2020-03-07_22 53 01](https://user-images.githubusercontent.com/52132442/76153651-af5b2a80-60c6-11ea-8285-157c239305df.png)

Second screenshot shows underground. No Enigma Stations or Nightwing spawners anywhere.
![2020-03-07_22 54 13](https://user-images.githubusercontent.com/52132442/76153652-aff3c100-60c6-11ea-939b-1c00896715b6.png)

**Comment by Tslat** [comment]
Fixed in 3.2.5
