### ISSUE TITLE
repair dis

### ISSUE THREAD

**Issue by NuggetKitten** [Tslat/Advent-Of-Ascension#1292]
**Mod Version**
What version of the mod are you on?
3.2.4
**Describe the bug**
repair dust too op ( repairs above 20% as intended
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to dust
2. Click on repair
3. use 3 to repair to 120%
**Expected behavior**
it doesn't repair 20% as intended

**Comment by Tslat** [comment]
Fixed in 3.2.5
