### ISSUE TITLE
cotton candy are unobtainable

### ISSUE THREAD

**Issue by Ryunari** [Tslat/Advent-Of-Ascension#1294]
**Mod Version**
What version of the mod are you on?
3.2.4
**Describe the bug**
I tried to obtain the cotton candy (rose or blue) with many "tools" (sword, axe, pickaxe, shovel, hands and shears ; all with silk touch and not) and nothing is obtainable.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
This block should be obtainable (with silk touch or not).

**Screenshots**

**Comment by Tslat** [comment]
Fixed in next version
