### ISSUE TITLE
Add a new profile switch to control world generation

### ISSUE THREAD

**Issue by 1640946640** [Tslat/Advent-Of-Ascension#1295]
As the title shows.
I am building the mod server of bungeecord on 1.12.2.
But I find a problem,It cannot cancel world generation.
When this mod working at my "Sub-Server"of lobby,It takes up a lot of my server resources because of world generation.
And I want to divide the adventure world of the virtual world and the main world into two sub servers.
So I need this feature to save my server resources.
I hope you can add this function :)

**Comment by Tslat** [comment]
You want to "Cancel" world generation? How does that even work?

**Comment by 1640946640** [comment]
Just add a cancel switch, you can choose not to open.

**Comment by 1640946640** [comment]
Can you generate a configuration file to modify the world to configure

**Comment by jtrent238** [comment]
Lobby don't need world to be generated
