### ISSUE TITLE
Silent gem's quivers compatibility

### ISSUE THREAD

**Issue by Zack7292** [Tslat/Advent-Of-Ascension#1299]
**Describe/name the existing feature this suggestion relates to**
it relate to all the bows and arrows of the mod
**Describe the change or feature you think would be good to see**
i think we should be able to shoot while the arrow are in the quiver 

**Add any alternative implementations you think might work**
adding its own quiver to the mod

**Comment by Tslat** [comment]
I can't find anything relating to quivers from Silent's gems, can you link me to something?
If not, I'll be dropping this suggestion

**Comment by Zack7292** [comment]
Wdym, the mod?

**Comment by Tslat** [comment]
Can't find anything about quivers?

**Comment by Zack7292** [comment]
in either silent gem or silent gear (since i always got both, i might have done an error) there is a quiver.

**Comment by Tslat** [comment]
Can't find it in either of them.

I'm closing this suggestion until you're able to actually find & link the thing you're suggesting
