### ISSUE TITLE
Duplicate portals

### ISSUE THREAD

**Issue by Jokniserous** [Tslat/Advent-Of-Ascension#1300]
**Mod Version**
3.2.4

**Describe the bug**
When passing through some portals (in my case it was The Deeplands and Lelyetia), it creates another portal next to the one which was already created.  This was not all the time, but sometimes.  I had up to 5 different portals next to each other in The Deeplands at one point and 2 in Lelyetia.

**To Reproduce**
1. Create a portal
2.  Pass through portal multiple itmes

**Expected behavior**
It should pass you through the portal which was already created/

**Screenshots**
![2020-03-08_15 48 50](https://user-images.githubusercontent.com/35971384/76414194-2595b080-6397-11ea-84e0-d799579aa43e.png)

**Comment by Tslat** [comment]
Update to the latest version of the mod and try again
