### ISSUE TITLE
Staves firing faster then they're supposed to?/Rapidly tapping right click makes staves fire even faster

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1303]
**Mod Version**
3.2.5

**Describe the bug**
According to Scimi, staves are supposed to have a fire rate of 1.66. They definitely did seem to fire that fast in 3.2.4, via comparing to 1.66 fire rate guns like Core Rifle. But in 3.2.5, they're definitely firing faster than Core Rifle, Power Ray, and other 1.66 fire rate weapons. They now feel very very similar to 2.5 fire rate weapons like Aqua Magnum, Megagun, and Spectral Archergun in terms of rate of fire. This is just from holding the use button down, by the way.

This appears to be the same case for the staves that don't fire projectiles when used.
My game runs at 60 FPS, and I'm definitely not having any tick lag.

Also, just like old times it seems you can make staves fire even faster by quickly tapping the use key. Since this doesn't work with guns and especially blasters, I doubt it's intended.

To be honest I can't be bothered to make video footage, but if you really need it I guess I can provide.

**To Reproduce**
Steps to reproduce the behaviour:
Use a staff multiple times and compare it to 1.66/2.5 fire rate weapons. And also try quickly tapping the use button when holding a staff.

**Expected behavior**
Staves having the same fire rate as other 1.66 fire rate weapons, and not being able to increase it by quickly tapping the use button.

**Comment by Tslat** [comment]
Found it, fixed it
