### ISSUE TITLE
Expedition armor's fall damage reduction does not seem to be working

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1304]
**Mod Version**
3.2.5

**Describe the bug**
At level 100 Expedition, a 27.5 block fall deals 8 fall damage (instead of 24 damage at level 1 Expedition). Expedition armor is supposed to further reduce fall damage, but when wearing the full set, a 27.5 block fall still deals 8 damage. Testing other levels of fall damage produce the same results.

**To Reproduce**
Steps to reproduce the behaviour:
Take fall damage at level 100 Expedition, then take the same amount of fall damage again while wearing Expedition armor.

**Expected behavior**
Expedition armor further reducing fall damage, presumably reducing it from 8 damage to 4 damage from a 27.5 block fall?

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/76489260-0d4c8280-63e5-11ea-9f49-829dc1abe3fc.png)
![image](https://user-images.githubusercontent.com/38159897/76489366-63b9c100-63e5-11ea-89ef-12f73bfdcfa7.png)
![image](https://user-images.githubusercontent.com/38159897/76489425-8b108e00-63e5-11ea-8046-501a222e1417.png)
![image](https://user-images.githubusercontent.com/38159897/76489452-9b286d80-63e5-11ea-8bba-02039b54b893.png)

**Comment by Tslat** [comment]
Fixed in next version.
