### ISSUE TITLE
It is recommended to add the function of slab calling restriction

### ISSUE THREAD

**Issue by 1640946640** [Tslat/Advent-Of-Ascension#1305]
![2020-03-12_17 16 00](https://user-images.githubusercontent.com/40906001/76507652-21958b80-6488-11ea-98b2-2f86b4d580c7.png)
  I found a serious problem.
  Players can use the Slab without any limit on the number of servers
  I suggest adding a player's maximum number of creatures that can be summoned by calling board to the configuration file.
 If the player has the corresponding hunting level and the number of summoned creatures is less than the maximum limit, he can summon
For example,[Mob farm manager](https://www.spigotmc.org/resources/mob-farm-manager-supports-1-7-10-up-to-1-15-hopper-support.15127/) .This plugin can not limit the number of calls at all.
 I'm afraid that the server will get stuck due to too many entities
 So,could u please add this this function in the next update?

**Comment by Tslat** [comment]
Done in 3.3
