### ISSUE TITLE
Mod Compatibility: New Imbuing Recipes

### ISSUE THREAD

**Issue by Cicopath** [Tslat/Advent-Of-Ascension#1308]
**Describe the new feature you think would be good to add**
With the Mod Compatibility Update that was voted for, a suggestion I have for the update is to add some new Imbuing enchantment recipes. Many mods offer a variety of enchantments, such as Better Survival, etcetera. Knowing you can already imbue Vanilla and AoA enchantments via Infusion Table, it would be even better if we could use the Infusion Table to imbue enchantments from other mods.

**Add any alternative implementations you think might work**
An alternative implementation I believe would be a good idea, especially since there are many mods to count that add Enchanted Books, is to somehow make the ability to let players create their own recipes for these enchantments. And the enchantments only work on the weapons/tools they are able to be put on.

For example, Better Survival adds an enchantment called Vampirism, which is used on swords, along with other weapons Better Survival adds. (Nunchakus, daggers, etc.) I feel it could be made with one damage enhancer, one magic enhancer, and one glaring power stone for Vampirism I. For Vampirism II, I can simply require one more damage enhancer. For levels that are over the default (ex. Sharpness VI, etc.), I can make it use a Radiant Power Stone instead, where Vampirism III would be the maximum enchantment possible, no more.

**Include any additional background information**
A similar suggestion based on creating our own recipes has _partially_ been spoken about: [https://github.com/Tslat/Advent-Of-Ascension/issues/1256](url)

**Comment by Cicopath** [comment]
For some reason the link doesn't work. (At least for me.)

See GitHub Suggestion #1256

**Comment by Cicopath** [comment]
Another cool addition with mod compatibility, while on the topic of enchantments would be certain enchantment compatibility. For example, the Pickmax being enchanted with Tunneling. (From Better Survival.)

In the images, the glass is what you end up mining, while the stone is what you don't mine.

In this first image, you see Tunneling I on the left and Tunneling II on the right when put on a normal pickaxe.
![2020-03-13_21 07 45](https://user-images.githubusercontent.com/61031176/76671829-ad291e00-6555-11ea-9b91-57fb5e35e437.png)

In this second image, you see the regular Pickmax on the left, a Pickmax with Tunneling I in the middle, and a Pickmax with Tunelling II on the right.
![2020-03-13_21 07 35](https://user-images.githubusercontent.com/61031176/76671820-a39fb600-6555-11ea-8890-7dce0bfef94e.png)

Now, the funny thing is that you are able to enchant the Pickmax with Tunneling I and II, and it does mine what is shown in the second picture. The problem being is that when the Pickmax drops out of your inventory and you pick it up again, the enchantments suddenly don't work.

**Comment by Tslat** [comment]
The tunneling dropping item thing might actually be a bug on that other mod. Take it to them as well, since I don't see how anything I'm doing would cause that

**Comment by Tslat** [comment]
I've looked through my entire list of suggested mods, and none of them have enchantments for me to add compat for.

Better Survival has some, are there any other mods you think I should look at specifically for infusion-enchant compatibility?
