### ISSUE TITLE
GUI for Ascension Shrine

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#131]
**THE PROBLEM:**

The Ascension Shrine right now is so boring.

You just take a stack of essences, hold right click on it, and you watch as that little bar in the top right corner goes up and up and up. Fair enough, right? Yeah...for the first 30 levels or so.

At higher levels you are going to have stacks of weak and Molten essence from foraging training. Throwing it away is a waste. Nothing can be done with it, yet you have vast quantities. However it's inefficient to sit there and use them when you could be doing fun things, including getting more essences that are actually somewhat worthwhile. Also weak essences do almost nothing at 60+ level. At that point using those the bar isn't going to go up and up and up but rather just sit there.

Even for the higher levels, this is kind of a bad system to hold right click on the shrine for a while. I mean **that can be an option** if you like to see your little bar go up and up and up. But there should be a faster way. There is nothing immersive about sitting and holding right click, no skill required, etc. It's just time consuming and unnecessary. There is no reason to not make it snappy.

**THE SOLUTION:**

Add a GUI to the Ascension Shrine. This GUI has 2 things:

1. One slot where you can insert up to a stack of essence (only one type). In other words, a typical item input slot.
2. One "burn" button.

Clicking the burn button consumes the entire essence stack and uses it to train Augury.

**NOTE:** The GUI opens up when you right click the ascension shrine with anything that is not an essence in hand. **If you right click with essence it consumes them one at a time just like the old way.**
This gives you an option to consume a small amount of essence without opening the GUI if you feel like it.

**Alternative implementations?** nah

**Comment by Immortallis1** [comment]
What happens to my knowledge is that when you right click with X essence, it just calls a method that consumes one of item X from the inventory, which will usually be the "first" one there instead of necessarily the one you are right clicking with.

I prefer the idea of a GUI. While the ctrl thing would probably be simpler it just feels more polished for there to be a GUI, even if it's a simple one.

**Comment by Tslat** [comment]
I tried to do the crouch-click action in the 1.12 snapshot. Minecraft ignores any block interactions while crouching by default, I don't even get to choose.

**Comment by TekterBR** [comment]
I need this

**Comment by Immortallis1** [comment]
@TekterBR leave an upvote if you do please, thanks

**Comment by BlueAgent** [comment]
Maybe sneak right click with an essence to consume all stacks of the same type?

**Comment by BlueAgent** [comment]
> I tried to do the crouch-click action in the 1.12 snapshot. Minecraft ignores any block interactions while crouching by default, I don't even get to choose.

You could maybe implement this on the right click event of the essences instead.

**Comment by BlueAgent** [comment]
> I tried to do the crouch-click action in the 1.12 snapshot. Minecraft ignores any block interactions while crouching by default, I don't even get to choose.

This could possibly be implemented on the right click event of the essences/
Having it consume one stack, or better, all the stacks of the same type would greatly speed things up (the essences aren't used for anything else iirc?)
