### ISSUE TITLE
Omni armor should have 3 (or 2) toughness per piece

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1310]
**Describe/name the existing feature this suggestion relates to**
Omni armor

**Describe the change or feature you think would be good to see**
It always seemed a bit odd that Omni armor has 1 toughness rather than the usual 3. Even Overworld sets have 2 toughness per piece. At first I thought it was to make the set more glassy since the damage boost can be strong, but that doesn't make much sense when you think about it. Every other damage-boosting set follows exact armor baselines, like Nethengeic.
Also it seems when a set deliberately has lower armor to balance it out, it seems it's the armor value itself that's lower, not the toughness. (See Speed and Purity).

And even though Mercurial is more expensive, Omni still has the very similar requirement of mining for a Creeponia ore and killing shit for Unstable Gunpowder. ~~Omni also has the additional challenge of not getting unlucky with the 42 duration fireworks trade while trading with Explosives expert.~~

Anyway, it seems that all of Omni's stats are completely unchanged from 3.1.2.b, which makes me think it having 1 toughness per piece is unintended. Either way, it just feels odd for Omni to get kicked in the knees when Nethengeic/Ghoulish/Archaic follow baselines just fine.

**Comment by Tslat** [comment]
Fixed in next version
