### ISSUE TITLE
Unobtainable stuff in 3.2.5

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#1313]
Eye Candy is unobtainable, before Eye Bulb was inedible but now it is I guess and the Eye Candy recipe is gone. Also was told that Hot Rod and Sweet Sword are unobtainable

**Comment by Cruuk** [comment]
The act of forgetting about them warrants 40 belt whippings

**Comment by Tslat** [comment]
Fixed in next version
