### ISSUE TITLE
Additional Advancements.

### ISSUE THREAD

**Issue by TheArcReactor** [Tslat/Advent-Of-Ascension#1316]
Currently, the only advancements added are obtaining realmstones and killing bosses. There is so much more potential for advancements. Killing one of every mob in a specific dimension, kill 50 of a mob, obtain all the equipment of a boss, or something silly.
examples:
[Overcooked]:  Cook some meat using a Sun Staff.
[Cretaceous Killer]: complete the Precasia Bestiary.
[Frequent Customer] Interact with every Lottoman.
[Corny Joke] Kill 50 Candy Corny.
[Warmonger] Collect God's Greatblade, Chainsaw, Ultimatum Staff, and Paralyzer.

The possibilities are basically endles.

**Comment by Tslat** [comment]
There's over 250 advancements in AoA?

https://adventofascension.gamepedia.com/Advancements

**Comment by EatingSilencer** [comment]
I'm late on this but I think their point was to add a larger variety of advancements. As indeed, a huge chunk of them are traveling to dimensions or battling some boss, or leveling skills.

**Comment by Tslat** [comment]
There's more advancements in 3.3 :)
