### ISSUE TITLE
Overkill, Schmoverkill and The Almighty Touch advancements can't be obtained

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1318]
**Mod Version**
3.2.5

**Describe the bug**
When you deal 200 damage or more, you don't get either Overkill, Schmoverkill or The Almighty Touch advancements

**To Reproduce**
Steps to reproduce the behaviour:
1. Load a Creative world
2. Use commands to increase your Butchery skill level to 90+
3. Put on a set of Archaic Armor and poison yourself until you're at half a heart
4. Spawn the Hive King and drink a Strength II potion
5. Critically hit the Hive King with a Harvester/Runic sword enchanted with Bane of Arthropods VI while your battle rage is at 200. This should deal 200 or more damage in one hit

**Expected behavior**
Both the Overkill, Schmoverkill and the Almighty Touch advancements should be obtained.

**Comment by Tslat** [comment]
Eh.. people have obtained it
For some reason Minecraft's damage detection thing is super iffy

**Comment by Tslat** [comment]
Not much further I can do with this - this is minecraft's damage thing being super weird.

It _is_ obtainable functionally, whether possible with AoA I'm not yet sure...
