### ISSUE TITLE
Custom fishing loot table doesn't work.

### ISSUE THREAD

**Issue by ThomasBonomo** [Tslat/Advent-Of-Ascension#1319]
There's not really anything to explain or describe here, it just doesn't work.
I've been fishing until my Hauling skill was at level 38, and through all of that, I haven't caught a single modded fish or crate.
Please get this fixed.

Mod Version 3.2.5 (MC 1.12.2)

**Comment by Tslat** [comment]
Fixed in next version

**Comment by ThomasBonomo** [comment]
Thx, I absolutely love fishing in Minecraft. <3
