### ISSUE TITLE
wiki boss preparation suggestion

### ISSUE THREAD

**Issue by chocobars678** [Tslat/Advent-Of-Ascension#1321]
this isn't really an issue but i think it would be helpful.
i think that on the pages for all the bosses there should be a section where it gives recommendations for armor, weapons, etc. to fight the boss

**Comment by Cruuk** [comment]
We're planning to axe strategy guides in general. Subjective text doesn't belong in an objective page, and dedicated strategy pages aren't very feasible because basically none of the active editors want to deal with upkeeping them and making sure they're always updated.
