### ISSUE TITLE
Using Gas Blaster on untamed minions/pets crashes game

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1322]
**Mod Version**
3.2.5

**Describe the bug**
It seems that if you use Gas Blaster on untamed minions like naturally spawning Wolves or AoA minions spawned from spawn eggs and not slabs, the game crashes.

Crash report: https://pastebin.com/PX5KYvUX (from using on untamed Penguin)

**To Reproduce**
Using Gas Blaster on an untamed minion.

**Expected behavior**
I guess uhh poisoning them while untamed, Gas Blaster poisons animals and untamed minions are essentially animals.

**Comment by Tslat** [comment]
Fixed in next version
