### ISSUE TITLE
Hell Horn's lingering projectiles don't damage mobs unlike Bubble Horn's

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1323]
**Mod Version**
3.2.5

**Describe the bug**
From testing on stuff like Grocculate and Soulvyre, I could not get Hell Horn's lingering/floating projectiles to damage them no matter what, yet I was easily able to with Bubble Horn.

From looking at the code, it seems that the entity files for Bubble Horn and Hell Horn's projectiles aren't the same- Bubble Horn has some lines of code that Hell Horn does not. If I had to guess those lines of code pertain to the lingering projectiles damaging stuff.

**To Reproduce**
Steps to reproduce the behaviour:
Try to damage mobs via the floating bubbles Hell Horn spawns, then try doing the same thing with Bubble Horn.

**Expected behavior**
Hell Horn's lingering projectiles also being able to damage mobs.

**Comment by Tslat** [comment]
Fixed in next version
