### ISSUE TITLE
advancement typo

### ISSUE THREAD

**Issue by chocobars678** [Tslat/Advent-Of-Ascension#1324]
1.12.2

in the nether advancements the advancement named "obtain a nethengeic callstone" there is a typo where callstone is spelled with three L's and not two

1. Go to main menu by pressing escape
2. Click on advancements
3. Click on the nether advancements
4. hover mouse over obtain a nethengeic callstone advancement

![2020-03-18_13 23 01](https://user-images.githubusercontent.com/62275303/76999086-bf230c00-691b-11ea-9bf7-60540bfee8c3.png)

**Comment by Tslat** [comment]
Fixed in next version
