### ISSUE TITLE
Too much Undead Herald in dimensions

### ISSUE THREAD

**Issue by Ryunari** [Tslat/Advent-Of-Ascension#1325]
**Mod Version**
3.2.5 (and 3.2.4 too)

**Describe the bug**
When I come in Gardencia or Vox Ponds (perhaps some more dimensions, I don't know for the moment), there is too much undeads Heralds who spawn on the map. Ok I clear the land of all foliages, woods or tentacles but it's just for being safe and see the path where I can search something (structures, runes shrines, etc...).

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
The Undead herald must disappear when you are too far of them.

**Screenshots**
![2020-03-17_11 32 55](https://user-images.githubusercontent.com/48478090/77048786-4b3e3d80-69c7-11ea-9f25-5a3514d5598a.png)
![2020-03-19_09 37 15](https://user-images.githubusercontent.com/48478090/77048811-542f0f00-69c7-11ea-9d52-8662d7262590.png)

**Comment by Tslat** [comment]
I'll do a few things in the next update
