### ISSUE TITLE
The Occult Pickaxe highlights the world's origin.

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1327]
**Mod Version**
3.2.5

**Describe the bug**
The Occult Pickaxe's ability creates a green cube located at the world's origin in the overworld, and when in the camera's field of view drastically reduces my framerate.

**To Reproduce**
Steps to reproduce the behaviour:
1. Hold Right click while holding an Occult Pickaxe
2. Look for a green block towards the world's origin

**Expected behavior**
It probably shouldn't appear

**Screenshots**
![2020-03-20_22 29 55](https://user-images.githubusercontent.com/52132442/77211308-7e81e900-6afb-11ea-836d-2f66b7b4ef42.png)

**Comment by Tslat** [comment]
Fixed in next version
