### ISSUE TITLE
Hydrolisk still teleports in its second phase

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1328]
**Mod Version**
3.2.5

**Describe the bug**
When the Hydrolisk's Armor Coating is completely depleted and it's vulnerable to damage it can still teleport to the player. Ignore this issue if this is intended.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn the Hyrdolisk
2. Use Hydro Stones to deplete its armor coating
3. Stay near it in survival mode and it should still teleport

**Expected behavior**
Ideally it shouldn't be able to teleport at all in its second phase

**Comment by Tslat** [comment]
Fixed in next version
