### ISSUE TITLE
维度之门不生成的问题

### ISSUE THREAD

**Issue by rechalow** [Tslat/Advent-Of-Ascension#1331]
**Mod Version**
3.2.5

**Describe the bug**
在中国服务器上，我进入了一个维度之门后，这个维度将不会出现回去的传送门。
我试着更改了一个纯净版本的Advent of Ascention服务器，依然不行。

**To Reproduce**
Steps to reproduce the behaviour:
1.在overworld建立一个任意维度的传送门
2.进入这个维度之门。
3.这个维度将不会生成一个相同的门。

**Expected behavior**
未来的Advent of Ascention将会支持中国服务器。

**Comment by Tslat** [comment]
Spongeforge servers and the like are not compatible with custom teleportation stuff that AoA does. This includes chinese server wrappers, since they all seem to just be ripoffs of spongeforge

**Comment by rechalow** [comment]
So will future versions fix this bug
