### ISSUE TITLE
Skeleton army doesn't spawn

### ISSUE THREAD

**Issue by rechalow** [Tslat/Advent-Of-Ascension#1333]
**Mod Version**
3.2.5

**Describe the bug**
When I found the army block, there was a skeleton elder nearby. I killed it and there was no skeleton army

**Expected behavior**
To enable skeleton to spawn

**Comment by rechalow** [comment]
When I found an army block in precasia, I also found a skeleton elder around. I killed it now, but no army appeared. I tried to right-click army block, but it didn't work. I tried to look around for army, but it didn't work.

**Comment by Tslat** [comment]
I've made some changes in the next update. We'll see how it goes
