### ISSUE TITLE
找不到玩家的饱食度，严重bug请求修复

### ISSUE THREAD

**Issue by songyuesheng** [Tslat/Advent-Of-Ascension#1338]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/4386678/latest.log)
![QQ图片20200326183520](https://user-images.githubusercontent.com/62697884/77639305-7f02ff80-6f93-11ea-8c99-6628597577c0.png)
![QQ图片20200326183526](https://user-images.githubusercontent.com/62697884/77639311-80342c80-6f93-11ea-84f8-d432a64565ef.png)
[crash-2020-03-26_11.26.24-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4386680/crash-2020-03-26_11.26.24-server.txt)
[debug.log](https://github.com/Tslat/Advent-Of-Ascension/files/4386681/debug.log)

Server World 3 can not find players satiation, will lead to server crash, mod version 3.2.4, asked the server core author, the author feedback is mod problems, server core is CATSERVER, request repair! There is also the problem of the void world portal, can only enter the portal to the dimension, can not be transferred from the void world back to the main world, request repair! Server crash record, debug crashreport report report the record has been uploaded, request repair

服务器虚无世界3找不到玩家饱食度，会导致服务器崩服，mod版本3.2.4，问过服务端核心的作者，作者反馈说是mod的问题，服务器核心是catserver，请求修复！
还有就是虚无世界传送门的问题，只能进传送门传送到维度，不能从虚无附属世界传送回主世界，请求修复！
服务器崩溃记录，debug crashreport报告记录已经上传，请求修复

**Comment by Tslat** [comment]
Update the mod. 3.2.6 is the latest version

**Comment by songyuesheng** [comment]
Ok，I will try it
