### ISSUE TITLE
Labricon Progression Idea

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#134]
I been thinking of a cool idea for Labricon. Pretty much, I think the layers should be linked to boss progression. Labricon will be its own progression but the progression only moves with your boss progression.

To get to the a lower layer you need to kill the boss from the layer your in. I will give Klokwerk as a example. To get Klokwerk's spawn item you need to craft it with special hearts that bosses drop (For example Smash's Heart).

You need at least 7 hearts from the respective tier to craft it. This crafting recipe would look like. (It doesn't matter where you put the items.)
![crafting_gui](https://user-images.githubusercontent.com/44548547/49164419-fb95b780-f326-11e8-8c8b-c941730cbb21.png)

All bosses in Labricon have the same crafting recipe but it depends what hearts you put in.
I made a tier system. Bosses placements depend on how early to late game a boss is. Or how difficult the boss is.

Klokwerk (1st Tier)
- Smash
- Corallus
- King BamBamBam
- Rock Rider
- Four Guardians
- Shadowlord
- Elusive
- Silverfoot

Pack (2nd Tier)
- Tyrosaur
- King Shroomus
- Hive King
- Clunkhead
- Vinocorne
- Visualent
- Mechbot
- Bane
- Voxxulon
- Gyro
- Crystocore
- C.R.E.E.P

Exo (3rd Tier)
- Nethengic Wither
- Skeletal Army
- Kror
- Dracyon
- Baroness
- Primordial Five
- Graw
- Cotton Candor

Note: Ancient Caverns and Immortalis bosses don't drop hearts. And Craexxeus probably will not have one because why fight it if you can fight easier bosses to get the Exo spawn item.
Also you can not use boss hearts from the Exo tier to craft Leveled and Eternal spawn items, same goes for Leveled to Eternal.
Evercron, Cuddlehugs, and Daemon placements depend on how late game they are.

**Comment by Immortallis1** [comment]
honestly I'd avoid making ideas for labricon. we don't know how much of it is done and if what you suggest is a complete revamp of what was the original plan, or if the original plan was better, or if there was an original plan at all.

**Comment by Sagisolar** [comment]
I know, but its called suggestion lol.

**Comment by Immortallis1** [comment]
Fair enough
