### ISSUE TITLE
Immortallis boss (Klobber) not spawning 

### ISSUE THREAD

**Issue by Dimaster54** [Tslat/Advent-Of-Ascension#1340]
**Mod Version**
What version of the mod are you on?
version 3.2.5

**Describe the bug**

Sometimes the boss klobber doesn't spawn (from the immortals) so I can't advance to the next room and I'm forced to eat the return crystal and waste 10 gold coins. 

**To Reproduce**
Steps to reproduce the behaviour:
Passing the first stage of the immortallis and getting into the first boss' room

**Expected behavior**
I expected the boss klobber to spawn so that I can get his coin and pass onto the next stage

**Screenshots**
I don't have screen shots ;(

**Comment by Tslat** [comment]
Update your mod, 3.2.6 is the latest version

**Comment by Dimaster54** [comment]
the log in a creative cheat world: 
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/4399221/latest.log)
I was trying to replicate it in a creative world by using the starting coin, using 5 impure gold in gold accumulator, right clicking on the immortallis progressor, killing klobber if he spawned, going to survival to use the return crystal and repeating untill klobber didn't spawn 
I updated the game yesterday and it happened again in 3.2.6.

**Comment by Tslat** [comment]
Fixed
