### ISSUE TITLE
The two flags will coincide

### ISSUE THREAD

**Issue by rechalow** [Tslat/Advent-Of-Ascension#1341]
**Mod Version**
3.2.6

**Describe the bug**
The two flags will coincide

**Expected behavior**
These flags will not coincide, they will become ugly

**Screenshots**
![coincide](https://user-images.githubusercontent.com/61784773/77845138-f5477200-71de-11ea-9184-b912dc658aeb.png)

**Comment by Tslat** [comment]
While this does create some interesting looking things, I originally implemented this as intentional and have decided to keep it as such.
It allows players to build around and through the banner as they want, and it stops players being blocked from placing or breaking things through a banner
