### ISSUE TITLE
Can't turn off friendly fire/pvp with AOA guns.... 

### ISSUE THREAD

**Issue by lunarmaximum** [Tslat/Advent-Of-Ascension#1343]
I'm on 1.7.10 version of AOA but I'm unable to stop the gun damage from hitting friends on my server.
Was there a config in place to stop the PVP. I tried using scoreboard command, changing the server configs to turn off PVP but AOA seems to ignore all that for some annoying reason.

**Comment by Tslat** [comment]
Update the mod to 1.12 if you want updates and bug fixes
