### ISSUE TITLE
Portal not work in server

### ISSUE THREAD

**Issue by youwen233** [Tslat/Advent-Of-Ascension#1344]
**Mod Version**
AoA3-3.2.6

**Describe the bug**
I'm running AoA3-3.2.6 on 1.12.2 server,In AoA3's dimension, the portal doesn't work, it can't telpport me to Overworld, there is a portal sound, but I am still standing in the portal door.

**Server**
The server client has 9GB memory
Using the latest version of Catserver(universal,not async)

**Screenshots**
![Ohmygod](https://dl.youwenqwq.workers.dev/Temp/001315c035rdbdnpp5t0t2.jpg)

**Comment by Tslat** [comment]
Provide your latest.log file from the server

**Comment by youwen233** [comment]
> Provide your latest.log file from the server

ok,can I just put the recurrent log to here?

**Comment by youwen233** [comment]
> Provide your latest.log file from the server

``
[16:31:19] [Netty Server IO #0/INFO] []: <YTrump> 1
[16:31:41] [Netty Server IO #0/INFO] []: <YTrump> 2
``
there is no output when recurrenting this bug

1 means test started
2 means test ended

(I copied that output in debug.log)

**Comment by youwen233** [comment]
and here is the full log.
 https://dl.youwenqwq.workers.dev/Temp/latest.log

**Comment by Tslat** [comment]
First, you're not using 3.2.6, you're using 3.2.5.

Second, try it without any other mods present and see if it happens

**Comment by youwen233** [comment]
> First, you're not using 3.2.6, you're using 3.2.5.
> 
> Second, try it without any other mods present and see if it happens

Ahh,sorry about that, I just forgot to update the mod in my main server😂 I will send back results in next few days thanks

**Comment by Wind-Xing** [comment]
Scimi, this bug has been alive since 3.0
And it makes it impossible for the server players to enter the runandor normally
Just tried. 3.2.6 didn't fix this bug

**Comment by youwen233** [comment]
> Scimi, this bug has been alive since 3.0
> And it makes it impossible for the server players to enter the runandor normally
> Just tried. 3.2.6 didn't fix this bug

thx🤔 i searched this problem in google, and there are some server admins have the same problem on mcbbs

**Comment by Tslat** [comment]
Try it with a normal forge server. Catserver is an illegal repackage of forge, and is known to break stuff

**Comment by youwen233** [comment]
> Try it with a normal forge server. Catserver is an illegal repackage of forge, and is known to break stuff

Okay, I will have a try, thanks for helping!

**Comment by youwen233** [comment]
> Try it with a normal forge server. Catserver is an illegal repackage of forge, and is known to break stuff

Thanks for replying! The problem caused by catserver and I reported this bug to catserver's owner ;)

**Comment by youwen233** [comment]
> Try it with a normal forge server. Catserver is an illegal repackage of forge, and is known to break stuff

Hello, I

**Comment by Tslat** [comment]
That's not how this works lol

AoA works just fine on Forge, which it's intended for.
I'm not going out of my way to support an illegal chinese server wrapper.

**Comment by youwen233** [comment]
> That's not how this works lol
> 
> AoA works just fine on Forge, which it's intended for.
> I'm not going out of my way to support an illegal chinese server wrapper.

Okay,thanks

**Comment by Memfivosfey** [comment]
Hello. The situation is exactly the same. I make portals, activate them. Visually the portal is working. But I can’t enter it, I pass by and stay in this world. There is Sound and nothing else.

Only the portal to the Nether worked. No other portal is working.

I play on my home computer. Minecraft Client 1.19.2 Forge. Local world.

AoA3-1.19.2-3.6.18.jar

**Comment by EatingSilencer** [comment]
> Hello. The situation is exactly the same. I make portals, activate them. Visually the portal is working. But I can’t enter it, I pass by and stay in this world. There is Sound and nothing else.
> 
> Only the portal to the Nether worked. No other portal is working.
> 
> I play on my home computer. Minecraft Client 1.19.2 Forge. Local world.
> 
> AoA3-1.19.2-3.6.18.jar

This is because those other dimensions are not implemented yet, and never will be on 1.19.2.

**Comment by Memfivosfey** [comment]
I'm sorry, I don't understand a bit
and for which version of minecraft will these portals be fully implemented?

**Comment by EatingSilencer** [comment]
> I'm sorry, I don't understand a bit and for which version of minecraft will these portals be fully implemented?

Unknown at this time.
