### ISSUE TITLE
the lower layer of lelyetia and the Distorting Artifact

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1345]
**Mod Version**
3.2.6

entering the lower layer of lelyetia and putting the Distorting Artifact into hotbar will cause players to float permanently and can only move horizontally and slowly

Take away the hotbar or die to fix this bug

Reported on discord, put it here to record

**Comment by Tslat** [comment]
Take it out of your hotbar?
