### ISSUE TITLE
Weird pixel scaling on Vox Logs

### ISSUE THREAD

**Issue by NeoVolt** [Tslat/Advent-Of-Ascension#1346]
**Mod Version**
3.2.5, though the bug wasn't fixed in 3.2.6 according to the changelog.

**Describe the bug**
Vox Logs (Not the tree type, the ground object) have a weird issue where some pixels on the side of the log aren't the same size as all the others.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter Game
2. Place down either vox_log or vox_log2
3. Look at the side and suffer internally

**Expected behavior**
The pixels on the side should be the same size as the pixels on the top and bottom

**Screenshots**

yea
![image](https://user-images.githubusercontent.com/57927345/77963763-913ab180-72a3-11ea-99ce-ca49018424f1.png)

**Comment by Tslat** [comment]
They're actually a custom blockmodel.. might need to adjust the model itself

**Comment by Tslat** [comment]
Fixed
