### ISSUE TITLE
Item rendering issues

### ISSUE THREAD

**Issue by DarkChinelo** [Tslat/Advent-Of-Ascension#1347]
**Mod Version**
3.2.6
**Describe the bug**
When I use the lotto totem and the tablets, i get the problem, the screenshots explain better.
And I'm not using optfine.

All the items are working fine, the issue is just with the appearance

**Screenshots**
![Lotton totem](https://user-images.githubusercontent.com/62222265/78026625-56cc2580-7332-11ea-89ef-b2e461e44748.png)
![Tablet](https://user-images.githubusercontent.com/62222265/78026662-63e91480-7332-11ea-8611-a9e0f6daca8d.png)
![Tablet 2](https://user-images.githubusercontent.com/62222265/78026672-66e40500-7332-11ea-815f-2bce29771975.png)

**Comment by Tslat** [comment]
Provide your latest.log file please

**Comment by DarkChinelo** [comment]
Here:
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/4412538/latest.log)

**Comment by Tslat** [comment]
Merging into #1515
