### ISSUE TITLE
Ariel's model doesn't touch the ground

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1348]
According to the bestiary entry for Ariels, "It appears to have wings of some kind, though they're filled with too many holes to be able to actually take flight." Contrary to this, their models are slightly raised above the ground to give the impression they can hover.
![2020-03-31_14 50 37](https://user-images.githubusercontent.com/52132442/78034748-0a97da00-7360-11ea-8749-5a83b6e1e89f.png)

**Comment by Tslat** [comment]
Fixed
