### ISSUE TITLE
Ender Dimension Additions. 

### ISSUE THREAD

**Issue by Kaldonis1** [Tslat/Advent-Of-Ascension#1349]
Hi AoA team! I actually made this suggestion as an image, so here is a link to an imgur.
https://imgur.com/gallery/zrsjoIr
What i am suggesting are a couple of nice goodies to be added to the Ender dimension, since AoA add some features to the Nether and Overworld. Currently there is nothing in AoA that relates to the End other than the Ender Carrier. I feel like this would make great use of Minecrafts infinite End generation and would provide the player some extra reason to explore this underrated dimension. Enjoy! :D 
 
~Kaldonis

**Comment by Nebula240** [comment]
Sweet concept

**Comment by jtrent238** [comment]
![](https://i.imgur.com/CYrRKLQ.png)
