### ISSUE TITLE
The Lemonlands

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1351]
Despite my hate for dimension suggestions, I've always wanted to make one myself to tell the truth. So here it is: **The Lemonlands**
**Describe the new feature you think would be good to add**
The Lemonlands

**Add any alternative implementations you think might work**
no thanks

**Include any additional background information**
Despite my hate for dimension suggestions, I've always wanted to make one myself to tell the truth. So here it is: **The Lemonlands**

The general color scheme is yellow and a more pastel yellow. The sky is a pastel yellow color. The generation would be a bit mountainous, with cave systems wider than Creeponia.
This would result in huge pits, making fall damage a bit dangerous. Every major structure except one floats in the sky.

There would be 2 types of trees: Sarvis and Weetor trees. Weetor is yellow, while Sarvis is white. They can be used to make Sarvis and Weetor planks. If you have level 50 Logging, 
mining Weetor wood can give the Sour Lemon item, and mining Sarvis Wood can give the boss spawner: Bulbous fruit.

There are 3 types of foliage blocks: Sour Stalks, Sweetweeds, and Pricklours.
Sour Stalks is decoration, Sweetweeds disables fall damage if you're on it, and Pricklours will deal damage and give nausea when touching them.

Lemonyte Ore can spawn underground, has around the same rarity as Diamond.

The Lemonlands is ruled by Selyan.

**Realmstone Task**: Throw a Lunarade and Tea into the waters of L'Borean.

-------------------------------------------------

**Mobs**:

__Lemounous__: Melee mob with the same speed as Cyclops. Looks like a sheep but lemon-themed with horns. When it's at 50% HP it will give poison and Nausea on hit. Has 75 HP and 7 damage. Takes damage
from Candied water.

__Lemonine__: Ranged mob that can move very quickly unlike Goblin. Shoots slower but higher damage and launches the player into the air on hit like Evercron. 95 HP and 12 damage. Takes
damage from candied water. And is immune to gun and magic damage. Looks a bit like Arc Wizard but more floating pieces and is yellow. Has a 1.5% chance to drop Lemos.

__Lemon Demon__: Big uncommon melee mob that only spawns underground. It has around the same speed as a Charger, has high knockback and a vision of 32. Has 150 HP, 11 damage, and 14 armor. It
 is also immune to bow and gun damage. Looks like Rag'lok Gogdure from Divine RPG mod but slightly smaller and yellow. Has a 2% chance to drop Lemonic Helmet and chestplate.

__Lemonic Wizard__: Ranged mob that also spawns underground but not as deep as Lemon Demon. Acts similar to Enderman but ranged and always hostile. Whenever it hits you it'll teleport to a random spot.
Has the same speed and firing speed as Goblin. Has 80 HP and 5 damage. Looking at it gives you blindness. Has a 1% chance to drop 1 Lemon Bunch. Looks like a shorter, yellow/dark Enderman with 1 eye.

__Levead__: Flying mob that acts like Polytom, but fires slightly slower. It fires yellow projectiles that explode and give Nausea and Levitation on hit. Looks like Urioh from Immortallis, but not see through
and the head is a lemon, and yellow. Has 65 HP and 14 damage.

__Sourior__: Level 43 hunter mob. Melee mob that takes away 5 hunger on hit and heals itself for 30 HP on hit. Has 65 HP and 7 damage. Spawns in the Sour Tower structure. It is immune to fire and explosions. Has a 
0.7% chance to drop the Sour Staff. Looks like a creepy hunched over Skeleton, 3-4 blocks tall and colored yellow/black/gray.

__Sourous__: Level 81 hunter mob, it an upgrade to Sourior. Takes away 10 hunger on hit, and heals itself for 50 HP on hit. Has 160 HP, 17 damage, and 9 armor. Spawns in the Lemonic Crypt structure.
Has a 1.8% chance to drop the Sour Staff and a 10% chance to drop 1 Lemon Bunch. It is also immune to fire and explosions. It can also give Nasuea to everything in a 16 block radius occasionally.
Looks like Sourior, but slightly larger and has 4 heads, with each head having 3 eyes.

__Living Lemon__: It is the rare mob. It moves slow, but when it hits you it has the same knockback as Smash at very low HP. It looks like a fat Lemon with legs. It has 100 HP, 10 attack, and 10 armor.
It has a 50% chance to drop the Bulbous fruit, the boss spawner. Also has a 50% chance to drop Yeller.

Every mob here can also drop "Sour Lemon" and Lemon tokens from the "world table".

-------------------------------

**NPCs**:
__Lemizen__: Spawns in the Lemizen villages, has text when you right click them. Does nothing else. The other Lemizens have the same text. They sort of resemble Zals, but the head is in the regular place.
*"Will you be sour savior from the evil king?"*
*"I'd never mine down there. It leaves a sour feeling in my stomach just thinking about it!"*
*"Pretty sweet day today."*

__Lemizen Banker__: Has the same trades as other bankers.

Lemizen Tinker: Has various trades.
10 Sour Lemons + 4 Gold coins= Lemon Bunch
30 Sour Lemons + 1 Lunaver coin= Lemonsquirt
1 Lemon Bunch + 1 Silver Coin= 16 Lemonic Juice

Lemizen Tinker also has 2 extra lines other than the regular ones.
*"Anyone who faces that king will only have a sour fate."*
*"Ever since King Lemocous came into rule, the sweet days ended."*

__Lemonade Seller.__
Young Lemizen that sells Lemonade:
2 Sour Lemons + 2 Silver Coins= 1 Lemonade

Lemonade Seller has 1 extra line other than the regular one.
"I hope my friend the Zal Vendor is doing alright..."

Lemon Lottoman: Lottoman but yellow. Has usual trades but requires Lemon Tokens.

Undead Herald also spawns here and sells the Lemonic and Sour Banners.

---------------------------

**Structures**:

__Sour Tower__: Big Tower that can rarely spawn. It has 3 floors, with each floor having a Sourior spawner. Made of Lemon bricks and Lemon Lamps.

__Lemonic Crypt__: Underground structure. Box-shaped structure with 2 rooms. 1 room has 2 Sourous spawners and the other has a Lemonic Block.

__Giant Lemon__: Huge structure shaped like a Lemon, it's where the Lottoman spawns.

__Lemizen Village__: Village full of the Lemizens. It looks like a mix of the Gorb and Primordial village.

__Lemocous Castle__: Huge castle that is just 1 big room with the spawner block in the center. This is where you fight King Lemocous.

---------------------------------

Special Blocks:

__Lemonic Block__: Spawns in the Lemonic Crypt. Right clicking with bullets, Metal slugs, Spreadshots or cannonballs with Lemonic Juice in your inventory will turn them into juiced versions of themselves.
They have the same damage as regular ammo, but has higher knockback.

__Lemon Altar__: Spawns in Lemocous Castle. Using a Bulbous fruit on it summons King Lemocous.

----------------------------------

Items:
__Sour Lemon__: World table item.
__Lemonyte Ingot__: Ingot smelted from Lemonyte ore. Used to make the Sour Sword, Lemonic Armor and Sour Shooter.
__Lemon Bunch__: Upgrade of Sour Lemon that can be eaten and used to make Lemonic armor. Slightly stronger than Baked Potato but eating too much gives blindness.
__Lemonade__: Like Lunarade, but gives speed instead of night vision. It also removes slowness.
__Bulbous Fruit__: The boss spawner for King Lemocous.

--------------------------------------

**Weapons**:

__Lemonic Greatblade__: 28 damage, deals more damage the less hunger the player has. Dropped from King Lemocous.

__Sour Sword__: 17 damage, deals more damage the less HP the player has. Crafted with Sour Lemon and Lemonyte Ingot.

__Sour Shooter (archergun)__: 20 damage, 1.33 fire rate. Arrows have extreme gravity. Holding crouch while firing changes gravity to normal, but gives player blindness. Crafted from Lemon Bunch and Lunar Archergun.

__Sour Squasher (gun)__: Shoots a burst of projectiles. 4 damage per projectile, 4-6 shots, 0.8 fire rate. Dropped from King Lemocous.
Can be upgraded with Gardencia upgrade kit to **Grapefruit Galvanizer**. Damage is increased from 4 to 7.

__Lemos (shotgun)__: Slows mobs, random range of 1-11 projectiles when firing. 5 damage per shot, 1.66 fire rate. Dropped from King Lemocous.

__Yeller (cannon)__: The projectiles deals more knockback the more mobs there close to the player. 26 damage, 0.8 fire rate. Very high recoil. Drops from Living Lemon.

__Lemonsquirt (energy weapon)__: Works like Soul Storm where it shoots a stream. The stream is yellow and will color mobs yellow on hit. When colored they take 35% more damage from Lemonsquirt.
They will stop being yellow after 4 seconds have passed. 1 damage, 20 fire rate. Traded from Lemizen Tinker.

__Sour Staff__: Shoots a projectile that slows mobs and gives them levitation. Killing a mob with it can make them drop Lemonade. Deals 15 damage. Dropped from Sourior and Sourous.

**Armor**:

__Lemonic armor__: Each piece gives a 10% damage boost to weapons firing the juiced ammo version of ammo. The full set makes it so pressing crouch makes you jump like a Squasher.
Pressing crouch in water makes you jump super high. The helmet and chestplate can drop from Lemon Demon, while the leggings and boots are crafted with Lemon Bunches and Lemonyte Ingot.

------------------------

**Boss**:

__**King Lemocous**__: He was sent by Pluton to introduce a harsh monarchy to the Lemonlands.
Has 3200 HP, 22 attack, and 4 armor.
Looks like a huge Living Lemon with a crown and a sinister face, along with a pastel yellow robe.

Has the same speed as a Cyclops, can jump like the Squasher mob. After jumping and landing on the ground, the player is pushed back a little. This will also spawn a Mini Lemon.

The Mini Lemons have 50 HP, 5 damage, and Charger Speed.

When King Lemocous reaches 1000 HP, he will change to his sour forme. In this he looks a little moldier, moves slightly faster, and jumps more frequently. When he lands after jumping,
an explosion is created. He also summons Giga Lemons instead of Mini Lemons.

The Giga Lemons have 75 HP, 15 damage, and speed between Cyclops and Charger. They are also immune to knockback.

When King Lemocous is killed, he drops his statue. He can also drop the Sour Squasher, Lemonic Greatblade, or Lemos.

----------------------------------------

Thank you for reading.

**Comment by EatingSilencer** [comment]
So the realmstone task requires Lunalus and L'Borean?

**Comment by RugratCoder94** [comment]
Now this is pod racing

**Comment by Golden-Extreme** [comment]
I wish I could add it in the next version of version 1.16.5.

**Comment by Tslat** [comment]
I'll have to add this right away
