### ISSUE TITLE
New Boss Idea

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1352]
Cruuk's dimension suggestion for the Lemonlands inspired me to come up with a post of my own.

I give you: The Sweaty Wither. I spent like 45 minutes on the texture
![Sweaty Wither](https://user-images.githubusercontent.com/52132442/78134813-a258ff00-7418-11ea-812d-5a9408114c65.png)

One of my long time YouTube subscribers brainstormed some ideas for abilities and statistics over Discord. This is what they came up with, along with some of my own additions:

The Sweaty Wither has 6000 points of health. It deals 15 damage from range and 50 damage from melee. It's behaviour is similar to that of the Wither/Nethengeic Wither. It fires Sweaty Skulls (Wither Skulls that look like the head from my Minecraft skin) at a super fast pace (5/sec) but will sometimes swoop down to ram into you, knocking you back a large distance. Occasionally the Sweaty Wither fires a larger skull which deals 30 ranged damage and has far greater explosive power. These super skulls become more frequent as it's health gets lower, firing at most 2 each second when at 25% health or less.

Possible drops include Nether Stars, Enchanted gunpowder, Lunaver Coins and pieces of "Sweaty Armor". Each piece has +9 Armor toughness and adds up to +30 points of Armor altogether. Effects: Grants heavily increased strength and resistance(5), when below 50% health however, it also grants increased speed, jump boost, and haste(5).

Happy April Fools Day, everyone.

**Comment by Cruuk** [comment]
I skimmed this post by only looking at the picture. It looks alright though

**Comment by Cruuk** [comment]
This is not a joke ^
