### ISSUE TITLE
Any mobs won't drop any Heart Stones

### ISSUE THREAD

**Issue by Chuckpopper** [Tslat/Advent-Of-Ascension#1353]
**Mod Version**
AoA-Tslat-1.0 Minecraft 1.7.10

**Describe the bug**
whenever i kill a mob it really won't drop any Heart Stones (the items that levels up the innervation skills) and i can't go on updated version because it's broken, but the thing is some skills are working fine, i think the only thing is the Heart stones..

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
It says it drops from any mobs from 1 to 8 so that won't be too rare but when i realize that i'm not getting any that's when i found that, that is a bug

**Screenshots**

**Comment by Tslat** [comment]
1.7.10 is no longer supported. If you want updates. Update.
