### ISSUE TITLE
EntityBloodLust spaming console

### ISSUE THREAD

**Issue by TheKlimoT** [Tslat/Advent-Of-Ascension#1355]
VERSION: AoA3-3.2.6
https://paste.dimdev.org/vetimokocu.coffeescript
Spaming console

**Comment by Tslat** [comment]
It literally says do not report this.

**Comment by TheKlimoT** [comment]
It says don't report to sponge or forge, because that's not the problem.

**Comment by Tslat** [comment]
It's an intentional log entry caused by a vanilla bug, not AoA
