### ISSUE TITLE
Crash on World Creation

### ISSUE THREAD

**Issue by D-Fink** [Tslat/Advent-Of-Ascension#1361]
**Mod Version**
AoA3-3.2.6

**Describe the bug**
On world creation:
    `The game crashed whilst ticking memory connection
    Error: java.lang.NullPointerException: Ticking memory connection`
On world reload:
    `The game crashed whilst loading entity nbt
    Error: java.lang.NullPointerException: Loading entity NBT`

**To Reproduce**
Steps to reproduce the behaviour:
1. Download OTG, Far From Home, BoP, AoA, Reskillable/Compatskills
2. Start an OTG FarFromHome_BOP world

**Expected behavior**
World Creation

**Screenshots**
crash reports:
On Startup- (https://pastebin.com/tAsUjk7y)
On Reload- (https://pastebin.com/9k7wFXtV)

**Comment by Tslat** [comment]
In the AoA config, turn on verbose debugging and re-run it to generate new logs and provide the new log file (not just the crash report)

**Comment by D-Fink** [comment]
Debug On Creation- (https://pastebin.com/BzubxmKR)
Debug On Reload- (https://pastebin.com/ktYn6J3E)

**Comment by Tslat** [comment]
Yeah - another mod is doing stupid stuff. Most likely reskillable.

The fact that the mod couldn't find ANY advancements is pretty bad, it means another mod has removed all the advancements from the game
![image](https://user-images.githubusercontent.com/7098525/78591197-6c87a080-7886-11ea-8f3d-d1c94190fc0d.png)

**Comment by D-Fink** [comment]
well what's strange is that if you leave out one of those mods, the other starts working (i.e. remove OTG/FFH). I was just wondering if you had any insight into this problem and to who exactly this should be addressed to.

**Comment by Tslat** [comment]
Triumph does this too, but they have a config option to turn off removing other mod's advancements. Maybe the mod that is causing your problem has a config option too? If not, ask them to add one
