### ISSUE TITLE
Web Staff is janky

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1366]
**Mod Version**
3.2.6

**Describe the bug**
When it comes to damaging effects like wither and poison, Web staff will make those effects stop damaging the player, but the hearts will still stay green/black. Also, the effect timer still counts down but it always get stuck at 0, meaning the effect is stuck on the player. Drinking milk or using Shroomus sword to transfer the effect does not work (it doesn't transfer the effect at all). 
The only way to get rid of the green/black hearts is by dying, or getting inflicted by the same effect again, reactivating it. Doing so makes the effect work as normal, and goes away when time runs out.

When it comes to the physical effects like slowness and weakness, Web staff... doesn't seem to work at all lol. Using it with slowness doesn't get rid of the slowness, if anything it gets the timer stuck at 0 again. Same thing happened with weakness. Like the damaging effects, it seems dying or re-inflicting yourself with the same effect are the only ways to get the effects unstuck.

I think it's been like this since 3.2 released, but no one noticed because no one uses Web staff lol.

**To Reproduce**
Steps to reproduce the behaviour:
Use Web staff while inflicted with a negative potion effect.

**Expected behavior**
Web Staff just removing the negative potion effect.

**Comment by Tslat** [comment]
Fixed
