### ISSUE TITLE
Creeponia and Shyrelands shouldn't have multiple banners.

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#137]
**Describe/name the existing feature this suggestion relates to**
Creepoid, Creepy, Light, Shiny, and Shyre banner.

**Describe the change or feature you think would be good to see**
Usually when a dimension has more than 1 banner, the banners themselves are usually different enough to justify it. Shadow and Illusion banner. Fungal and Haunted banner. I know some are a stretch like Candy/Gingerbread banner and Nether/Nethengeic banner, but I think they're sort of fine... For Nether/Nethengeic, at least they're separated from each other.

But it makes no sense on why Creeponia and Shyrelands have multiple banners, there's really no difference between "Creepy" and "Creepoid", nor is there really a difference between "Light", "Shiny", and "Shyre" banners. It just adds clutter in general as well.
You'd think that the mobs who drop the banners, but no, they're all mixed with each other in both Creeponia's and Shyrelands' case. Well... the mobs that drop the Shiny banner are all underground, but a dimension should never ever have 3 different banners unless they're distinct enough between each other. (Labricon?). 

I like Shyrelands, but there'a really nothing in it that's really different from it's primary theme. Don't even need to talk about Creeponia.

----------------------------------------

Creepoid banner should be removed, and the mobs that dropped it should drop the Creepy banner instead. Besides, Creepy banner is the cooler looking one to me... Creepoid is just item sprites while Creepy has the creeper face and has a neat shade of Dark green.

Shiny and Light banner should be removed, and have Shyre banner be the one banner dropped by most of the mobs instead. It is the "Shyre" banner so I think it would make sense for this one not to get removed...

**Include any additional background information**
Only I could go this crazy over banners...

**Comment by Immortallis1** [comment]
IMO existing banners should just flat out not be removed. Just avoid making new banners for future dimensions.

**Comment by Sagisolar** [comment]
Who cares, banners are cool :).

**Comment by Tslat** [comment]
Banned are changed in 3.2
