### ISSUE TITLE
Concussion staff doesn't work on flying mobs

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1371]
**Mod Version**
3.2.6

**Describe the bug**
Concussion staff works fine on hostile mobs, but it does not seem to spawn explosions on flying mobs. Even when non-flying hostiles are in the vicinity, Concussion still does not spawn explosions on flying mobs.

**To Reproduce**
Steps to reproduce the behaviour:
Try to use Concussion staff on flying mobs. 

**Expected behavior**
Concussion staff working on flying mobs. I'm not sure it is intended, but I guess I am using this git post to see if it is or not.

**Comment by Tslat** [comment]
Fixed
