### ISSUE TITLE
Infinite Lava Glitch for Extraction 

### ISSUE THREAD

**Issue by KaleThyself** [Tslat/Advent-Of-Ascension#1372]
+ Mod Version: 3.2.6

+ Bug Description: 
   I can place multiple source blocks of lava above the extraction block and infinitely mine/extract without having to replace the lava. 

+ Steps to reproduce the behavior:
   1. Go to the Nether with 9 extraction blocks, a diamond bowl, and make an extraction area near some lava. 
   2. Instead of making a 1 high 3x3 area of lava source blocks above the extraction devices, make it 3 layers high so it would be a 3x3x3 of lava source blocks with every empty air block filled with lava in the pit you made above the extraction devices. 
   3. Begin extraction on every extraction block and mine them with either a hammer from tinkers construct or any area of effect obsidian breaking device. Normal pickaxe mining appears to have the same result. 

+ Expected behavior: 
   (4.) Continue extracting and realize that you do not ever need to replace the lava on the top since the source blocks simply stay there infinitely and do not get sucked into the extraction devices. 

+ Additional Note:
   1. I have gone up to level 50 for extraction so far without having to replace the lava; expected level grind would easily get to level 100 within a few hours, not including the use of utopian armor.

**Comment by Tslat** [comment]
Fixed in next version
