### ISSUE TITLE
Greatblade no attack cd

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1374]
3.2.6

Put the bow on the left hand, pull the string, and then take out the greatblade, you can attack without CD.

Not sure whether to repair in 3.2.7

**Comment by EatingSilencer** [comment]
Try it in 3.2.7 and see if it happens. Though I think this is a known issue if its what I think it is.

**Comment by Tslat** [comment]
Fixed in next version

**Comment by Wind-Xing** [comment]
> 
> 
> Try it in 3.2.7 and see if it happens. Though I think this is a known issue if its what I think it is.

There is still this bug in 3.2.7

**Comment by Tslat** [comment]
Unable to replicate. In 3.2.7 enemies aren't even attackable with greatblades if you're using a bow
