### ISSUE TITLE
Bug in Lelyetia and Distorting Artifact (still not fixed)

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1375]
**Mod Version**
3.2.7

**Describe the bug**
At the bottom of Lelyetia, when you block the top of your head, take out the Distorting Artifact, and then you will float in the air.

If you lose the block on your head at this time, you will be kicked out of the game, even if it is single player mode.

Description in the game log:Wind_xing was kicked for floating too long!

**Screenshots**
![1](https://user-images.githubusercontent.com/59332746/79067988-0e2f4780-7cf6-11ea-8f01-a96cdfd3d69a.png)
![2](https://user-images.githubusercontent.com/59332746/79067989-0f607480-7cf6-11ea-9a25-ef7d3c305ac0.png)
![3](https://user-images.githubusercontent.com/59332746/79067991-1091a180-7cf6-11ea-82e2-e22928e09f10.png)
![4](https://user-images.githubusercontent.com/59332746/79067992-11c2ce80-7cf6-11ea-862c-e2258d253de5.png)
![5](https://user-images.githubusercontent.com/59332746/79067994-12f3fb80-7cf6-11ea-936c-8a4600e34e0d.png)

**Comment by Wind-Xing** [comment]
Add: the above five pictures are all screenshots in single person mode
Automatically jump to server list after being kicked out

**Comment by Tslat** [comment]
This should hopefully be fixed in 3.3
