### ISSUE TITLE
Fischer does not spawn

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1376]
**Mod Version**
3.2.7

**Describe the bug**
Fischer does not spawn in Vox Ponds.

It seems that this has been the case since 3.0.
Perhaps longer.

**Screenshots**
hard mode.
![233](https://user-images.githubusercontent.com/59332746/79068182-95c98600-7cf7-11ea-90a8-7f235fa8e8d1.png)

**Comment by Cruuk** [comment]
It could be a similar reason to me not having seen any Pinchers and Skippers, Scimi has said that water mob spawns are awful to work with.

**Comment by Tslat** [comment]
Works fine for me in 3.2.7?

You sure another mod isn't messing with it?

![image](https://user-images.githubusercontent.com/7098525/79082657-17a6c700-7d6b-11ea-8f60-986756ba9810.png)

**Comment by TheSaikos** [comment]
Are you playing on a server or singleplayer world?
