### ISSUE TITLE
Forge version check not working maybe

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#1377]
Every time this is bought up in discord it is forgotten so I thought to put it here.
This relates to #658. The check is missed for significantly out of date forge versions (this has happened a bunch), is this fixable or is the crash always going to occur before the check?

**Comment by Tslat** [comment]
I think it may be a different style of dependency req. I've changed it, hopefully it's more consistent with this alternate setup
