### ISSUE TITLE
Hazmat Suit and possible IC2 overall compatibility

### ISSUE THREAD

**Issue by Gorantev** [Tslat/Advent-Of-Ascension#1378]
I'd want to see Hazmat Suit from IC2, working as protective gear (in same way as Hazmat Armor in AoA) in Vox Ponds (with less armor). The same with Hazmat Armor from AoA, working as protection against Radiation Poisoning (with better overall protection).

Hazmat Armor and Hazmat suit already exists in AoA and IC2 respectively. Why not to make them interchangeable (with varying levels of overall protection of course). This may be included as addition to probable expansion pack for AoA-IC2 compatibility.

I hope, this suggestion doesn't sound too stupid, doesn't replicate already existing ones and/or too hard to code... Anyways, good luck for anyone, involved in the project!

Good Luck, Commander!

----------------------

Also, first time, doing suggestions on GitHub. I hope, I didn't broke any rules, regarding them... Anyways, good luck! And stay safe!
Gorantev.

**Comment by Tslat** [comment]
Done in 3.3
