### ISSUE TITLE
AE 2 and Thermal Expansion Intergration

### ISSUE THREAD

**Issue by SKnight1207** [Tslat/Advent-Of-Ascension#1379]
**Describe the new feature you think would be good to add**
Adding the option to charge Runium/Runium Ore with a charger from AE 2 or an Energetic Infuser from Thermal Expansion might be a good idea , just some compatibility features to be honest =))

**Add any alternative implementations you think might work**
Maybe the option to infuse golden apples into notch apples with magic enhancers , durability enhancers and divine enhancers ?

**Include any additional background information**
AoA3 is awesome and playing it has been a wonderful experience,
Cheers to Scimiguy for making such a brutal and fun mod to play

**Comment by Tslat** [comment]
Had a look at this - 
Applied Energistics 2 is hardcoded, I can't add compat for the charger without making it a required dependency.

I Checked out the one from Thermal Expansion too, and I just don't think it fits
Thanks though
