### ISSUE TITLE
Advancements 

### ISSUE THREAD

**Issue by ddteam90** [Tslat/Advent-Of-Ascension#1380]
Hi! Is it possible to remove mod's advancements only for the pack? Because our pack uses advancements system and it not so cool, when there are so many pages. May be config option? Or, i think it will be a good variant, to add more useful information to your descriptions, such as "where can we find this items and structures. Because in the descriptions not enough information and I should always look up in the official wiki.

I tried to remove them via Triumph, as I removed advancements from other mods, but AoA gave out a crash. 

https://hatebin.com/jtlwfmuelj

![Inked2020-04-13_21 05 32_LI](https://user-images.githubusercontent.com/47353693/79149175-69813880-7dcf-11ea-94a3-040926ad6708.jpg)

**Comment by Tslat** [comment]
Should be able to do this in 3.3
