### ISSUE TITLE
Using Random Animal Textures from Quark or something similar to it, causes the affected mobs to flicker like crazy

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1390]
**Mod Version**
3.2.7

**Describe the bug**
Using any mod that gives a mob random textures, most notably Random Animal Textures from Quark, will cause their models on the bestiary to flicker through the randomized textures very fast.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Quark or any mod that introduces randomized textures for existing mobs.
2. Kill the affected mob.
3. Head into the Bestiary and hope you're not epileptic.

**Expected behavior**
Seems like when you click on their entry, it'll show a randomized texture without flashing through different ones. That's how it should of worked.

**Comment by Tslat** [comment]
Fixed in next version
