### ISSUE TITLE
Bug with Bow damage

### ISSUE THREAD

**Issue by EvgeniyMist** [Tslat/Advent-Of-Ascension#1392]
Minecraft 1.7.10 version and mod Tslat-1.1.3 version.

I think, there is some bug connected with max damage, that player can deal with the help of any bow and Holly Arrow.

So what tests have I done already.
Firstly, I determined, that the Void Bow deals about 15-16 damage to the Dark Beast. And after putting on the Predatious Armor, which increases the damage from Holly Arrow by 70%, my shots stably did 25 damage. Secondly, I created Void Bow with Power5 enchantment. Without set of the Predatious Armor it deals the same 25 damage, and with set ... also 25 damage. It is very strange situatation.
Finally, I gave me the Sunshine Bow with record 34 damage, but I also saw only 25... And it isn't connected with the Dark Beast, I have the same problem with any mob. As if there is a limit on the maximum allowable damage

Thank you in advance

**Comment by EatingSilencer** [comment]
There is in fact a limit in 1.7.10. If you want to disable it, go into the mod's config file and set the DMG Limit to 0.

This is not a bug as far as I know.

**Comment by Cruuk** [comment]
1.7.10 is no longer supported. Update to 1.12.2 if you want updates.

**Comment by Immortallis1** [comment]
As Silencer said there is a 25 damage limit that's enabled by default, remove it in the config file
