### ISSUE TITLE
some advancement can't be completed

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1394]
**Mod Version**
3.2.7

**Advancement**
Heckfire
Going to Hell For This..
Overkill, Schmoverkill.
The Almighty Touch

**picture(If you need it?)**
![2](https://user-images.githubusercontent.com/59332746/79627978-583d8080-816f-11ea-8a10-d0b0836d5866.png)

**Comment by Wind-Xing** [comment]
Additional:Guard That!

**Comment by Wind-Xing** [comment]
Additional:
Should Be A Mechanic(Because mecha staff (incomplete) cannot get)(But the description says 5)

**Comment by Tslat** [comment]
Fixed in 3.3 for all mentioned
