### ISSUE TITLE
Should Ornamyte pickaxe still have its downside?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1395]
**Describe/name the existing feature this suggestion relates to**
Ornamyte pickaxe

**Describe the change or feature you think would be good to see**
Don't get me wrong, being able to quickly mine Obsidian can be quite powerful, but in the grand scheme of things it's very situational, with the only exception being Extraction. I don't hate it though, I think it's good and very much fits with Ornamyte's supposed theme of "better on 'tougher' blocks"(?).
Not everything has to always be super useful, so it's good.

What I do take issue with though, is its downside of mining any other block slower. I do not see a good reason for it to still be around. The aforementioned situational nature of Obsidian makes it feel like more of a harsh punishment than a proper way of balancing its increased effectiveness against **1 block**.

It's basically relegated to being the Extraction Pickaxe, and *only* the Extraction pickaxe. This limiting nature feels very unfitting with the less limiting and non-constrained abilities the other tools have. It's like making Gemcracker destroy smelted ores and not stack with Fortune, or giving the other Ornamyte tools a similar downside.

I notice that the mod is trying to get away from these types of downsides in general, which is why I think it would be beneficial to remove this unnecessary crippling downside. I highly doubt it'll become this insanely overpowered monster. Seriously, where else is Obsidian used as a gameplay function outside the Nether portal and Extraction?
Other than the Obsidian stuff, it just has the exact same efficiency as Emberstone pickaxe, with higher durability.

**Comment by Tslat** [comment]
Done in 3.3
