### ISSUE TITLE
The damage gain of sharpshot armor is too high

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1399]
**Mod Version**
3.2.7

**Screenshots**
Normal damage of Baron SSR(35)
![1](https://user-images.githubusercontent.com/59332746/79679587-9a32f900-8239-11ea-99ca-f4e0f43370da.png)
Damage after wearing a full set of sharpshot armor(61)
![2](https://user-images.githubusercontent.com/59332746/79679595-b20a7d00-8239-11ea-946e-6f3c098d2580.png)
Damage increased by about 74%.
But it should be 38%.
No problem with other guns,only sniper.

**Comment by Tslat** [comment]
That's what sharpshot says it does

**Comment by Wind-Xing** [comment]
> 
> 
> That's what sharpshot says it does

That's the description problem, because it says + 10% sniper damage

**Comment by Wind-Xing** [comment]
![1](https://user-images.githubusercontent.com/59332746/79680050-f26bfa00-823d-11ea-86bd-a2cdfabe2805.png)
From wiki

**Comment by Tslat** [comment]
Fixed in next version
