### ISSUE TITLE
Ideas for Tinkers material abilities

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1400]
I have not played Tinkers in years, but fuck it I have some ideas. No need to just hold them in until it's too late. Time to spitball.

**Baronyte**: Won't lose durability if in hot environments, or something involving hot environments and durability. 

**Bloodstone**: I don't know if something in Tinkers already withers, but I think the wither effect would be best- or something that relates to it like increasing wither effect damage. 

**Blazium**: Increases damage/efficiency/etc. if player is set on fire. 

**Crystallite**: Increases damage/efficiency/other stuff if the player is not touching the ground.

**Elecanium**; Drain Energy from mobs when hitting them.

**Ghastly ingot**: Damaging a mob has a very low chance to tp the player to that mob.

**Lyon**: Getting struck by lightning increases damage/efficiency/whatever for x amount of time.

**Lunar Ingot**: No gravity and/or something involving floating stuff.

**Mystite**: Increase damage/efficiency/blah blah blah if player is poisoned.

**Rusted Iron Ingot**: Using a tool with anything made of Rusted Iron Ingots has a chance to poison the player. "tetanus"

**Rainbow druse**: Don't know if paper still has lots of modifiers or whatever, but it should have a shit ton of modifiers- even more than paper but have... minor self recoil because it's sharp. Take this one with a grain of salt haha

**Varsium**: Hitting mobs stops their regen for x amount of time because it's uhh... dry and barren/baron.

Thanks for readi

**Comment by Tslat** [comment]
Done in 3.3
