### ISSUE TITLE
More Tinker's Construct Ideas

### ISSUE THREAD

**Issue by profilename14** [Tslat/Advent-Of-Ascension#1404]
I am going to try to add abilities for many of the materials with less obvious uses here.

**Varsium (Any Part):** _Intensify:_ Chance to increase the power of a status effect on the target. 

Varsium has no obvious abilities in infusion recipes as it is always paired with something else, but it is combined with a wide variety of materials. Because of this, perhaps it could be an "amplifier" metal or something, and cause other effects to become more powerful

**Baronyte (Tool Head)** _Barony:_ Slightly increases the strength of minions against the hit target for a short time. In return, Baronyte deals weak damage as a tool head/blade, forcing the player to rely on their minions just like a ruler relies on their subjects.

**Amethyst (Any Part)** _Finisher:_ Similar to the supremacy sword, finishes off a mob if it would have had 5 heath per level left after death, allowing quick dispatches of weaker mobs in earlygame.

**Runium (Tool Head)** _Arcane:_ Enemies hit by a weapon with this ability receive extra damage from staves for a short time after being hit, allowing a spellsword style character build. Charged runium could have a higher level of this ability but in return be weaker statistically.

**Ornamyte  (Tool Head)** _Disassembler:_ Similar to the Ornamyte pickaxe's ability (but to lesser extent in that it still work fine on most hard blocks), a tool with this ability mines harder materials like ores, planks, and obsidian quicker but softer materials like stone slower.

**Jewelyte (Any Part)** _Unstable:_ Creates explosions upon hitting mobs, which scale in knockback and damage with the level of the ability.

**Gemenyte (Any Part)** _Blast Breaker:_ Extra mining speed on materials with less blast resistance. 

**Bloodstone (Tool Rod)** _Butcher:_ Higher chance to create Bloodlusts upon hitting a mob, allowing quicker training of butchery. 

**Bloodstone (Tool Head or Extra)** _Wrathful:_ Upon dealing a critical hit, the player resets to 10 battle rage per level instead of zero, potentially allowing successive critical hits. 

**Charger Material (Any)** _Impact:_ Tool deals more damage and mines faster when the player is sprinting. Higher levels enhance the effect. 

### Update

Here I will add some abilities for modifiers:

**Rosid Root** _Solar:_ Higher damage/mine speed with open access to daylight. Power of damage or mine speed increases with each level.

**Primordial Skull** _Tenebrous:_ Higher damage/mine speed in darkness, with the highest effect being in zero light level. Power of damage or mine speed increases with each level.

**Rainbow Druse** _Bejeweled:_ Causes Foraging drops to occur slightly more often, increasing with each level.

**Floating Stone** _Levitator:_ Causes enemies to float upwards when hit for about 1.5 seconds per level. Could potentially be very interesting with bows.

**Hardened Confetti Ball** _Surprise:_ Increases damage moderately, but also causes damage to become somewhat random. Both increased damage and randomness increase with each level.

**Sharp Claw** _Sweeping:_ Did you know that Tinker's Construct doesn't have a replacement for the sweeping edge enchantment? It's a really nice enchantment, but Tinker's Constructs swords just don't have the ability to get it normally. This would basically act the same as the vanilla enchantment where it increases the sword slash damage to a percentage of the normal damage.

**Runic Energy** _Runic Power:_ Allows the sword to have different effects when a rune is held in the offhand, similar to the Runic Sword. Could also have different effects for mining tools, like having pickaxes auto-smelt with fire runes, mining faster with kinetic runes, ignoring mining penalties underwater with water runes... Maybe I could expand this into a whole suggestion actually, as even the weapons could take special abilities from new runes, like having weapons heal the player slightly with life runes, creating lightning with strike runes, or teleport the target somewhere random nearby with distortion runes.

**Ghostly Powder** _Spectral Strike:_ Causes a 1/3 of the damage dealt by a weapon per level to deal magic damage instead of normal damage, but also slightly reduces damage by a slight percentage per level. Capped at level 3

**Comment by Tslat** [comment]
Done in 3.3
