### ISSUE TITLE
Some errors in lang

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1406]
**Mod Version**
3.2.7

**Describe the bug**
1.Description does not match reality
1.1:item.WebStaff.desc.1=Clears All Debuffs From The Holder
It can only clear one
1.2:item.FungalArmour.desc.1=+20%% Chance to Stun Nearby Attackers on Hit
The effect cannot be overlapped. It is suggested to add remarks
2.Don't show in the game, no effect
2.1:item.LuxonScythe.desc.1=Leeches Soul Power on Hit
item.LuxonScythe.desc.2=Steals Health if Not Enough Energy Available
2.2:item.NatureStaff.desc.2=Grants Brief Massive Speed Buff

**Comment by Tslat** [comment]
I don't understand what you mean by this?

> 1.2:item.FungalArmour.desc.1=+20%% Chance to Stun Nearby Attackers on Hit
> The effect cannot be overlapped. It is suggested to add remarks

**Comment by Wind-Xing** [comment]
> 
> 
> I don't understand what you mean by this?
> 
> > 1.2:item.FungalArmour.desc.1=+20%% Chance to Stun Nearby Attackers on Hit
> > The effect cannot be overlapped. It is suggested to add remarks

No matter how many you wear, it's only a 20% chance to trigger this effect
But the game shows + 20% of each

**Comment by Tslat** [comment]
Fixed in next version
