### ISSUE TITLE
Allow Jade/Rosite to be mined with Iron/Limonite picks?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1408]
**Describe/name the existing feature this suggestion relates to**
Jade and Rosite ore

**Describe the change or feature you think would be good to see**
If I recall correctly, Jade and Rosite were balanced to be sidegrades of Diamond/inbetween Iron and Diamond(?). Amethyst is much more equal, and Sapphire is superior. The Jade/Rosite/Amethyst swords are stronger than Diamond, but have less durability.

In terms of the tools though, Amethyst is roughly equal with Diamond, while the Jade and Rosite tools are **objectively** inferior in terms of efficiency and durability. On paper this still makes sense- Jade/Rosite fall more into the "between iron and diamond" category than stuff like Amethyst.

However, the balancing of Iron < Rosite < Jade < Amethyst < Diamond doesn't accurately reflect the requirement of their ores. Amethyst has the same reqs as Diamond ore, which makes sense. 
But Jade/Rosite ore *require* Diamond/Amethyst tools to mine, which doesn't make much sense considering the power of Jade/Rosite compared to Diamond and Amethyst. Diamond/Amethyst tools are superior to Jade/Rosite tools, and an Amethyst sword is superior to Jade/Rosite swords in terms of damage and durability.

Perhaps there is something I'm missing, like maybe the Jade/Rosite tools are supposed to be bad like the Gold tools. Or they're meant to be alternatives for when you don't want to make tools with the more valuable Diamond and Amethyst.
No, if that were all true, that would be goddamn stupid in my opinion. You still need Diamond/Amethyst picks to mine the damn things in the first place.

So yes, it is quite odd that Jade and Rosite still have higher reqs than Diamond/Amethyst ore despite being inferior.

------------------------

Funnily enough, Jade and Rosite picks are able to successfully mine Obsidian. Whether Jade/Rosite picks should be able to successfully harvest Obsidian or not- I have no clue.

**Comment by Tslat** [comment]
Yeah alright
