### ISSUE TITLE
AoA incompatible with morph mod, wipes morphs after exiting the game.

### ISSUE THREAD

**Issue by goinghyperion14** [Tslat/Advent-Of-Ascension#141]
**Mod Version**
Tslat 1.1.3

**Describe the bug**
For some reason, when i have this mod installed with the morph mod, any time i leave the game it wipes my morphs.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by Tslat** [comment]
This one involves a changeup of how data is saved in the mod, which I'm treating very carefully.
I am aware of the issue though

**Comment by zHawky** [comment]
Same troubles with **"Hats"** mod from the same author. **AoA-Tslat-1.0.1** worked fine with hats.

**Comment by Tslat** [comment]
AoA No longer updates 1.7.10 as it is an ancient version of MC
