### ISSUE TITLE
There are some problems in the generation logic of some boss

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1414]
**Mod Version**
3.2.7

**Describe the problems**
1.Silverfoot will jam itself during spawned
(Because the maze is not high enough
2.The Skeletal Army often gets stuck in the wall
(In addition, they should be generated in 24x20 instead of 26x22, the latter causes them to spawned in the walls of the arena

By the way, Skeleton Army is too powerful as a T1 level boss, and the things dropped by Skeletron are not good enough

**Comment by Tslat** [comment]
Adjusted in 3.3
