### ISSUE TITLE
Buffing throwing weapons

### ISSUE THREAD

**Issue by CCtuhulu** [Tslat/Advent-Of-Ascension#1416]
They feel very useless by the time you get one.

**Comment by profilename14** [comment]
If throwing weapons are not buffed, making a few throwing weapons as crafted items in later dimensions could also be done too. Some example are a weapon in Lunalus that inflicts levitation on a target and is crafted from Orbulons, a weapon in Dustopia that inflicts weakness on a target and is crafted with Darkly Powder, or a high damage and knockback but low speed weapon in the Deeplands crafted with Dense Rocks. Consumable items like this could help in making certain crafting materials feel more useful.

**Comment by Cruuk** [comment]
You can get most of them before leaving Overworld via Assassin or Overworld Lottoman. They are also cheap items that can be instantly unholstered and can be thrown while running, so I'd say their weaker damage output is justified.
The only other weapon type that can be instantly unholstered and fired while running are Staves, and those are definitely more expensive to fire.

Slice Star by itself has more DPS than most T0-1 guns at base.
