### ISSUE TITLE
Baroness tweaks

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#142]
(I'm in a rush when writing this so this will be short)
Baroness is a fairly fun fight already, but a few changes that might make it better are:

1. Making the mines be pulled towards the player instead of the opposite way around. Being thrown across the arena into an explosion is a bit cheap and can end the fight quickly and unfairly.

2. Making her summon 8 mines in a ring around her instead of spawning one on top of herself. This would compensate for the nerf in change one and fix the issue where she leaches onto her newly spawned mines for an infinite shield.

**Comment by EatingSilencer** [comment]
I like the idea about spawning a ring of mines around her. Maybe there could be a combination - where sometimes there's one mine and sometimes there's a ring of mines.

**Comment by DiamondWalker** [comment]
> 
> 
> I like the idea about spawning a ring of mines around her. Maybe there could be a combination - where sometimes there's one mine and sometimes there's a ring of mines.

The issue is preventing them from spawning on top of her. Maybe instead of spawning the mine on her when she does the single mine attack, maybe she could fire a red projectile that spawns the mine?
