### ISSUE TITLE
Baroness causes the game to crash

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1424]
**Mod Version**
3.2.7

**Describe the bug**
If the Baroness doesn't move after spawned, and then calls Baron bomb, the game will crash

**Crash report**
[crash-2020-04-22_17.12.23-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4515132/crash-2020-04-22_17.12.23-server.txt)

**Comment by Tslat** [comment]
Fixed in 3.3
