### ISSUE TITLE
Smiley upgrade kit needs 5 transactions to update the transaction

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1425]
![2](https://user-images.githubusercontent.com/59332746/79965177-48e76b80-84be-11ea-9f65-08efcb312266.png)
Smiley upgrade kit needs 5 transactions to update the transaction
That's 10 groups of circle coin
Why do we have to get so many circle coins for Gold Gyro Statue?

**Comment by Cruuk** [comment]
Welcome to the clown economy. Pay up

**Comment by Tslat** [comment]
Fixed in 3.3
