### ISSUE TITLE
Ornate Clunkhead Statue advancement is not hidden

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1426]
**Mod Version**
3.2.7

**Screenshots**
![1](https://user-images.githubusercontent.com/59332746/79965678-e6db3600-84be-11ea-803c-5cd0dfdcc56e.png)

**Comment by Tslat** [comment]
Fixed in 3.3

**Comment by Wind-Xing** [comment]
> 
> 
> Fixed in 3.3

Add:
Advancement related to Baroness is also hidden
