### ISSUE TITLE
Possible Fungal armor change?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1428]
**Describe/name the existing feature this suggestion relates to**
Fungal armor

**Describe the change or feature you think would be good to see**
Yesterday it occurred to me that we have 3 different armor sets based around giving slowness to mobs that hit you. (Void, Biogenic, Fungal)

Now, I don't mind this much, they are different enough for the most part. But when I looked at Fungal more, I saw a golden opportunity.

For the longest time, I wanted an ability that would boost the damage from potion effects. And while I like the new armor abilities, I am sad that that there is nothing to boost potion effect damage.

Additionally, there's not really any support for Poison. What I mean is that Fire has the insanely powerful Nethengeic armor, Wither has Primordial armor, and Poison has nothing.
Considering that Fungal is made with materials from both the "poison" dimensions, I see this as my one big chance to suggest this. I could just suggest a new armor set but uhh...

--------------------------

Anyway, here's my idea for a change to Fungal:

**Per piece worn**: +0.5 poison damage
**Full set bonus**: Poison melee mobs when they attack you

Pretty self-explanatory, could adjust it to 0.4 per piece but that is up to you. Hopefully this is something that would work codewise, I would be sad otherwise.

**Add any alternative implementations you think might work**
Here is another way it could be implemented:

Poisons melee attackers that come into contact
**Per piece worn**: +20% chance
**Full set bonus**: +1.5 Poison damage

This was the first one I came up with, though I personally prefer the other one, as that one allows more flexibility with the bonus poison damage. Might as well not keep it in my head though...

Fungal armor's current ability isn't bad, though it doesn't seem to impress too many people. I think turning it into a poison damage armor would make it more interesting.

**Comment by Tslat** [comment]
Done in 3.3
