### ISSUE TITLE
Small Eeo rework

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#143]
**Describe/name the existing feature this suggestion relates to**
Eeo

**Describe the change or feature you think would be good to see**
Eeos as a concept have always felt a little loose and iffy in their current state, it's not a bad concept, but I think it could be done better.

First off, Eeos would simply be 1 entity now. They would have ~30-35 HP, and walk into the player to deal damage, blinding on hit like they currently do. Hitting an Eeo once will cause it to run away for 15 seconds (so that they're not as much of a pain in the ass to catch up to).

Hitting an Eeo will also cause a Spirit Guardian or Spirit Protector to spawn, 1 Eeo can spawn up to 2 spirit Guardians/Protectors (must be damaged 2 different times) and cannot spawn any more after that.

If you 1-hit kill an Eeo, or kill it in 2 hits, it will still spawn a Spirit Guardian/Protector on death.

I think this makes the concept a little more focused and refined. The increase in HP also makes it so Eeos can no longer dive-bomb you from high places and kill their first form via fall-damage, and spawning a spirit. (It's annoying)

**Comment by Sagisolar** [comment]
Intresting.
