### ISSUE TITLE
More consistent metal storage block names

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1433]
Here's a few examples on what I mean.

**Vanilla:**
_Block of Iron
Block of Gold
Block of Diamond_

**AoA:**
_Rosite Block
Amethyst Block
Bloodstone Block_

**How it should've been:**
_Block of Rosite
Block of Amethyst
Block of Bloodstone_

**Comment by Tslat** [comment]
I'm not sure I agree though.
Personally I think vanilla's system is the worse one.

It becomes a bit more interesting when you have adjective names.

Like - 

Block of Ghoulish?
Block of Ghastly?

**Comment by EnderdragonLord** [comment]
Yeah, I forgot to mention those lol.

They'd still be the same with no changes, but if they have to be changed I'd suggest adding metal to the end of them, like Block of Ghastly Metal, that's how Thaumcraft did it with their Void metal.

I mostly suggested it because it would make it easier for creative mode searching,  and typing 'Block of' would yield all the storage blocks available.

**Comment by Tslat** [comment]
Wouldn't it then be inconsistent with itself?

**Comment by EnderdragonLord** [comment]
True, there probably could be other solutions to it.

**Comment by Tslat** [comment]
Such as accepting it's better this way? ;)

**Comment by EnderdragonLord** [comment]
Okay yeah, I reckon it's best for it to stay how it is lol.

Gonna close this one down since it's pretty much resolved.

**Comment by EatingSilencer** [comment]
> 
> 
> Wouldn't it then be inconsistent with itself?

I don't get what you mean by this?
