### ISSUE TITLE
Change the tier of some ores from level 3 to level 4 (Cobalt/Ardite Tier from TConstruct)

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1434]
Whenever I play this with TConstruct, I always found it weird how all the ores added by this mod can be easily mined with a Diamond Pickaxe while Cobalt and Ardite still require a higher level pickaxe, which are found quite frequently in the Nether.

I was thinking that once you reach the other dimensions, some ores would require a level 4 pickaxe, so it would make more sense when using the mod with TConstruct, especially when there's official support coming soon.

**Comment by Tslat** [comment]
Yeah alright
