### ISSUE TITLE
Bow Sprite Issues

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1436]
Few things I've noticed about the bows, compared to the ol' fashioned bow.

![bow_sprites](https://user-images.githubusercontent.com/58011699/80267047-c5b44a00-8664-11ea-86da-f9ff11826107.png)

**1. The center stretches weirdly to the south.**

**2. The last frame makes it look like you're not pulling the bow anymore.**

**3. The arrowhead is not getting pulled so it looks like the arrow is growing in size.**

**1 affects:**
_Alacrity Bow
Ancient Bow
Nightmare Bow
Infernal Bow
Poison Bow
Runic Bow
Speed Bow
Screamer Bow
Soulfire Bow
Void Bow
Wither Bow_

**2 affects:**
_Explosive Bow
Ice Bow
Lunar Bow
Skeletal Bow
Weaken Bow_

**3 affects:**
_Deep Bow
Mecha Bow
Rosidian Bow
Spectral Bow_

![bow_sprite2](https://user-images.githubusercontent.com/58011699/80267455-ac140200-8666-11ea-8d69-365b840be6cd.png)
**(Sorry for the smaller size on the second image here btw)**

**The arrowhead on Sunshine Bow disappears during the second animation frame instead of moving down while it's being pulled.**

**The arrow in Predatious Bow are not the same alignment in both sides, so it looks like they've been cut in half.**

**Sometimes the arrows can end up getting really long in the bow pull sprite, I mostly noticed this on the Baron Bow.**

**Also noticed for all bows, the arrow goes behind the bow instead of on front like the normal bow has it. (Same applies to the bowstring, the arrow should be on front of it instead of behind)**

**I might have missed a few more but these are what I found.**

**Comment by Tslat** [comment]
Bow textures were redone in 3.3.2
