### ISSUE TITLE
Halycon And Creep Cow Change.

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#144]
Pretty much instead of them spawn in 1. Have them Spawn in herds instead. Also allow them breed, that would be fun. There already very forgettable so having them spawn in larger quantities will make them stick out in there respected dimensions more.

**Comment by Immortallis1** [comment]
would also like to add that there should be proper baby versions of them

**Comment by Sagisolar** [comment]
Discord is down

**Comment by Sagisolar** [comment]
ffs

**Comment by Tslat** [comment]
3.2 Did things
