### ISSUE TITLE
Thermal Expansion Compatibility

### ISSUE THREAD

**Issue by zero-breaker** [Tslat/Advent-Of-Ascension#1440]
Some compatiblity ideas for Thermal Expansion. Most of these are just for fun, while some might have some use for... uhhh automation? iunno.
This is not including things almost universal to all industrial mods like pulverized metals/dusts, gears and plates.

Pulverizer:
Frames -> Scrap Metal (2 or 3 frames to 1 scrap?)
Red/Blue/Orange/Purple Petal Blocks -> Small Red/Blue/Orange/Purple Petals (no green, unfortunately)
Crystal Blocks/Crystal Foliages -> Gemstones (or Crystals)
Gingerbread Block -> Gingerbread Cookies
(Dark) Chocolate Block -> Cocoa Beans
Hardened Confetti Ball -> Confetti Pile

Sawmill:
Crops -> Pulped Biomass + Crop Seeds
Logs -> Pulped Biomass + Sawdust (or perhaps other items for certain logs like Runic Energy for Runic Log?)
Foliage -> Pulped Biomass (+ other items for certain foliage like Gunpowder from Creeponia plants)
Armor Plating -> Chitin

Phytogenic Insolator:
Crop Seeds -> Crops + Crop Seeds
Foliage -> more foliage, really, check how it works with vanilla flowers and tall flowers
Rosid Roots -> Small Petals + Rosid Roots
Orange/Yellow/Mushroom Spores -> more spores
Jungle Thorns -> more thorns

Compactor - Numismatic Press:
Coins of all metal ingots (This isn't really necessary by any means, like, if at all, just suggesting this to be comprehensive; Also technically this is Thermal Foundation compatibility but you can't make coins without TE so)

Fractionating Still:
Candied Water -> Sugar + Water

Glacial Precipitator:
Water -> Ice Crystal

Igneous Extruder:
Water + Lava -> Flammable Dust

Arboreal Extractor:
Logs -> Mainly Sap and Resin, but some might reasonably give other liquids like blood from Blood Log (even if it's only used in mods outside of AoA3 and Thermal)
Cotton Candy -> Candied Water

Aquatic Entangler:
Making it able to catch Hauling-exclusive fishes would be great, but given the Skill reliance it seems unlikely. Still would be great, though.

Enervation Dynamo:
Can consume: Power Core, Runic Energy, Charged Runium Chunk/Rune, Runes

Numismatic Dynamo:
Can consume: Copper/Iron/Gold/Lunaver/Circus Coins, Tokens, Druses, Gems in general

Bonus:
Thermal Innovation - Alchemical Quiver:
Can store Holly Arrows

**Comment by Tslat** [comment]
Done in 3.3
