### ISSUE TITLE
Rockbasher Sword

### ISSUE THREAD

**Issue by ddteam90** [Tslat/Advent-Of-Ascension#1442]
Hi! There is one one problem with Rockbasher Sword. It says, that Enemies with armors cause an explosion on hit, but every mob in Minecraft has at least 1 armor point, so this sword will cause an explosion on every enemy even without the armor.
![2020-04-25_13 56 42](https://user-images.githubusercontent.com/47353693/80278218-2d1dd880-86fd-11ea-8acd-69b6d2360894.png)

**Comment by Tslat** [comment]
This is not true. The default value for armor is 0.
