### ISSUE TITLE
Tslat 1.1.3 AoA/No mob spawning in Shyrelands

### ISSUE THREAD

**Issue by TheSaikos** [Tslat/Advent-Of-Ascension#1455]
**Mod Version**
Tslat 1.1.3

**Describe the bug**
I have the problem that every mob from the Shyrelands dont spawn naturally but in spawners and I can also summon them.Works for every other dimension except Shyrelands.I attached a screenshot of my mods which Im currently using and the latest log.

[mods.zip](https://github.com/Tslat/Advent-Of-Ascension/files/4553506/mods.zip)
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/4553458/latest.log)

**Comment by EatingSilencer** [comment]
What biome is the Shyrelands set to? (when you press F3) Maybe there is a biome id conflict?

Though I will note that 1.7.10 is not supported any longer, so this issue won't be getting fixed unless its a problem on your end.

**Comment by Tslat** [comment]
If you want bug fixes, update your mod.
