### ISSUE TITLE
When installed with AE2, server console reads: "[FML]: Cannot Hotload Dim: -11"

### ISSUE THREAD

**Issue by MarshTheBacca** [Tslat/Advent-Of-Ascension#1456]
AoA3 Version: 3.2.7 for Minecraft 1.12.2
Forge Version: 1.12.2-14.23.5.2847
Applied Energistics 2 Version: rv6 stable 7

Description of behaviour:
There is an error in the server console saying it was unable to hotload dimension -11. This only occurs when Applied Energistics 2 is installed with AoA3, but in the error it shows AoA3 is to blame

Steps to reproduce the behaviour:
1. Create a blank forge server
2. Add the mods, AoA3 and Applied Energistics 2 (version rv6 stable 7)
3. Start the server and see in the console an erorr for hotloading DIM -11

Expected behavior:
I expect there to be no error

My server log:
https://pastebin.com/btNaZhF9

**Comment by EatingSilencer** [comment]
I can't seem to find the error you're talking about in the log. You sure this is the right one/is complete?

**Comment by Tslat** [comment]
I know  the error he's talking about.
The error is fine to ignore, don't worry about it

**Comment by MarshTheBacca** [comment]
Sorry I must've pasted the wrong log, I updated it in my original comment ^^

It's here too: https://pastebin.com/MYgVdmfG
