### ISSUE TITLE
Remove the "Waking the Ancient Undead" Advancement

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1457]
Of course since the Ancient Orb isn't used to spawn the Skeletal Army anymore the related Advancement is obsolete.

**Comment by Cruuk** [comment]
I think it could still work if you instead got the advancement after first killing the Skele elder and starting the first wave. You are "waking" them by killing the guy needed to start it. It would also work as a way of telling the player that they better be prepared.

**Comment by Tslat** [comment]
Done in 3.3
