### ISSUE TITLE
Thaumcraft Aspects

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1459]
Not saying that EVERY item should have aspects, it's a huge mod after all.

Aspects would mostly be for common items such as Minerals, Scrap Metal, Tokens, Dirt, Wood, Stone, and Coins. 

So a Limonite Ingot would probably have:
_-10 Metallum
-5 Aqua/Perditio_

Limonite is basically hydrated iron so Aqua or Perditio fit perfectly as potential aspects for it.

**Comment by Tslat** [comment]
That would take an insane amount of time.
Feel free to write up a list of items with what you think is a balanced amount of what aspects if you want to help.

Otherwise the time sink involved in this would probably be too much for me to consider doing

**Comment by EnderdragonLord** [comment]
Alright, I took most of the common items and blocks and attempted to add aspects into each one, the list might be a bit messy though, sorry for that if it makes it harder to read.

Hope it helps!

[List.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4644909/List.txt)

**Comment by Tslat** [comment]
Awesome thanks

**Comment by Tslat** [comment]
Done in 3.3
