### ISSUE TITLE
Bosses not summonable in peaceful message displays twice

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#146]
**Mod Version**
AoA3-Snapshot 7

**Describe the bug**
When trying to spawn a boss through its altar on peaceful difficulty, two messages pop up instead of one.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get any boss altar.
2. Set difficulty to peaceful.
3. Try to summon boss with boss-spawning item.
4. Two chat messages pop up instead of one.

**Expected behavior**
Only one message appears upon attempting to spawn a boss on peaceful difficulty.

**Comment by Tslat** [comment]
Resolved in Snapshot 8
