### ISSUE TITLE
Sweet Sword is too cheap to make

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1460]
_-16 Damage
-1850 Durability
-Literally has an ability that gives you excess candy and sugar_

Recipe:
![Recipe](https://user-images.githubusercontent.com/58011699/80788581-1b01c700-8b4f-11ea-954d-7511254861d6.png)

Honestly I always found this sword way too powerful for what you use to craft it, in fact you can easily get more Sour Gummies from the swords ability so you can just make an infinite supply of them. I'd say either remove the recipe completely and make it as a drop by Cotton Candor or nerf the sword. (Replacing the current candy drops and sugar with a new type of food that's not usable for any recipes would be nice too)

**Comment by Tslat** [comment]
Done in 3.3
