### ISSUE TITLE
AoA Spiders don't flip upside down on death

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1461]
When spiders die including most spiders added by mods like Twilight Forest, they would flip upside down right before the puff of smoke occurs.

AoA Spiders don't seem to  do this, which includes:
_-Mushroom Spider
-Nightmare Spider
-Sea Spider
-Arocknid
-Rock Critter
-Rock Crawler_

**Comment by profilename14** [comment]
This is a thing that insects generally do in real life (not sure about crustaceans though), so it could also be added to general arthopod type mobs like the Hive King, Tharafly, and Bloodsucker. The animation would look strange on bipedal insect mobs though, like the Parasect and Hive Soldier, so they should probably be excluded.

**Comment by Tslat** [comment]
Done in 3.3
