### ISSUE TITLE
Boss Summoning Item Descriptions

### ISSUE THREAD

**Issue by Tourmaline-Iris** [Tslat/Advent-Of-Ascension#1467]
This is for the boss summoning items like Treat Bag, Shroom Stone and Petals

The idea is to add something to their item tooltips to say that they're used to summon whichever boss they're used to summon. The reasoning behind this is that some of the items look like other crafting materials in the mod and there's nothing short of looking on the wiki to tell you what to do with these items from a first glance (unless I'm wrong which I might be)

An alternative is to change the advancement description for the boss summoning to include something along the lines of "use it to summon [boss name]". Less ideal since a lot of people don't check advancement descriptions but it's an alternative

I don't know if it has been suggested before but I assume it has since it's something that's not super complex nor super niche

**Comment by Tslat** [comment]
Do the current tooltips not work for this?
