### ISSUE TITLE
The exchange merchant of customnpcs cannot exchange the empty items correctly

### ISSUE THREAD

**Issue by MMotherFucker** [Tslat/Advent-Of-Ascension#1468]
I added a customnpcs mod to make NPC merchants to exchange the items of advance of ascension, but I found that the exchange mechanism of customnpcs could not correctly identify the items of advance of ascension.
But the original items can deduct the exchange items correctly
This indicates that there is a problem with your item property code. Please help to solve it

**Comment by Tslat** [comment]
Or it indicates that you set up the merchant wrong.

Provide screenshots
