### ISSUE TITLE
Goofy tools strange behavior - ability doesn't work correctly

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#147]
**Mod Version**
AoA3-Snapshot 7

**Describe the bug**
Goofy tools are not functioning the way they are intended all of the time. 

Goofy pickaxe:

The goofy pickaxe's ability does not work on ores that drop gems (diamond ore, green gemstone ore, crystallite ore, etc). It will always drop nothing. If the goofy pickaxe is enchanted with Silk Touch, the ore drops itself - not tripled/nothing.

The goofy pickaxe oddly behaves differently with vanilla Redstone ore - the ore drops 5 redstone when mined like normal, not tripled/nothing. Perhaps this has something to do with the ore switching to a new id upon being interacted with?

Goofy shovel:

The goofy shovel's ability does not work on grass blocks unless it is enchanted with Silk Touch. If it is enchanted with Silk Touch, grass block drops are either tripled or nothing drops. If not enchanted with Silk Touch, a single dirt block drops, not triple/nothing.

Unlike the goofy pickaxe, whose ability is ignored when Silk Touch is present, the goofy shovel's ability still functions if it is enchanted with Silk Touch.

Goofy axe:

The goofy's axe ability does not work on bookshelves. Possibly intended?

The goofy axe's ability still functions if it is enchanted with Silk Touch, like the goofy shovel, but unlike the goofy pickaxe.

**Comment by Tslat** [comment]
Fixed in snapshot 9
