### ISSUE TITLE
Guardian Altar and Rockrider Shrine are in the wrong creative tab

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1473]
**Mod Version**
What version of the mod are you on?
3.2.7

**Describe the bug**
Guardian Altar and Rockrider Shrine are in the "Advent Generation Blocks" tab instead of the "Advent Functional Blocks" tab, like the rest of the boss altars.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Advent Generation Blocks tab.
2. Scroll down until you find the Guardian Altar and Rockrider Shrine.
Alternatively,
1. Go to the Advent Functional Blocks tab.
2. Scroll down and try to find Guardian Altar and Rockrider Shrine.
3. Notice that you can't find them.

**Expected behavior**
The Guardian Altar is in the Advent Functional Blocks tab. The Rockrider Shrine should also be in that tab, presuming it isn't removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/80937093-b4c0b280-8da1-11ea-92fc-3f346661048c.png)

**Comment by Tslat** [comment]
Fixed
