### ISSUE TITLE
Aqua Fungi (yellow) is called Aqua Fungi

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1474]
**Mod Version**
What version of the mod are you on?
3.2.7

**Describe the bug**
Not sure if this is a bug, but I will post this here anyway.

There are two types of fungi plants from Gardencia that were a part of the Gardencia Fungi biome: one was aqua-colored and the other was peach/yellow colored. But both of them are called "Aqua Fungi", despite the fact that one of them is clearly not aqua-colored.

**To Reproduce**
Steps to reproduce the behaviour:
1. Obtain both colors of Aqua Fungi into the player's inventory.
2. Check both their tooltips for their names.
3. Notice that both are called Aqua Fungi despite one not being the color aqua.

**Expected behavior**
If they remain in the game, the yellow one should be renamed to Peach Fungi or Yellow Fungi.
**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/80937256-64962000-8da2-11ea-8e53-464e6055bf87.png)
![image](https://user-images.githubusercontent.com/44556728/80937264-6cee5b00-8da2-11ea-8c6d-a1eee89de24a.png)

**Comment by Tslat** [comment]
Intended
