### ISSUE TITLE
Waterweeds names are inconsistent

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1475]
**Mod Version**
What version of the mod are you on?
3.2.7

**Describe the bug**
There are 4 types of waterweeds: yellow, green, white, and red. The first 3 are just called "Waterweeds". The last is called "Waterweeds Red".

**To Reproduce**
Steps to reproduce the behaviour:
1. Obtain all 4 waterweed colors in the player's inventory.
2. Check their tooltip for their names.
3. Notice the inconsistency.

**Expected behavior**
The Waterweeds names are more consistent.
**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/80937544-922f9900-8da3-11ea-88c9-f279e75a1f35.png)
![image](https://user-images.githubusercontent.com/44556728/80937552-9a87d400-8da3-11ea-8015-8fe339448867.png)

**Comment by Tslat** [comment]
Fixed
