### ISSUE TITLE
Pickmax can break blocks intended to be unbreakable

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#148]
**Mod Version**
AoA3-Snapshot 7

**Describe the bug**
The Pickmax can break blocks that are intended to be unbreakable in placed next to the stone that the Pickmax mines.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place an unbreakable block, such as a boss altar, next to stone.
2. Mine the stone with a Pickmax.
3. The stone and unbreakable block will drop. 

Doesn't work on dimensional fabric or portals.

**Expected behavior**
The Pickmax is not able to mine unbreakable blocks.

**Comment by Tslat** [comment]
Resolved in Snapshot 8
