### ISSUE TITLE
Graw Model Redesign

### ISSUE THREAD

**Issue by zero-breaker** [Tslat/Advent-Of-Ascension#1480]
A redesign/rework of Graw's model, based vaguely on sperm whales and mycelium.
Features of the original model like the underbite, the humps on its back and the three-finned tail are kept.
At proper scale the whole model would be roughly 6x2x7 blocks large, though most of the width comes from the wings.

Preview images:
[https://imgur.com/zC0Y05L](https://imgur.com/zC0Y05L)
[https://imgur.com/WWzIsCH](https://imgur.com/WWzIsCH)
[https://imgur.com/hwdJlux](https://imgur.com/hwdJlux)
[https://imgur.com/gTv516n](https://imgur.com/gTv516n)

Files
(include .bbmodel files for t-pose and neutral pose, as well as texture with and without noise applied)
[https://drive.google.com/open?id=1ez3X8g5VRFUf9He_RayRKd9oETL_47eg](https://drive.google.com/open?id=1ez3X8g5VRFUf9He_RayRKd9oETL_47eg)

**Comment by Firch** [comment]
I think it's good, but it fits worse in game than original model
