### ISSUE TITLE
Creation armor adds to 26 in a different way than the other skill armors

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1482]
Very small thing to complain about it, but it's bugging me dammit. All the other skill sets add to 26 via 4 9 7 6, but Creation armor adds to it with 5 8 8 5. I assume they're all supposed to be 4 9 7 6, maybe he made Creation different on purpose to screw with people.

Even more less important, but Engineering armor also has less durability than the other skill sets. Just thought I should mention it.

**Comment by Tslat** [comment]
I mean.. it doesn't matter at all... but ok done in 3.3 lol
