### ISSUE TITLE
Portal Generation

### ISSUE THREAD

**Issue by Obsinym** [Tslat/Advent-Of-Ascension#149]
**Mod Version**
Snapshot 8

**Describe the bug**
When teleporting to Runandor, an abyss portal in generated in place of a runandor portal

**To Reproduce**
Steps to reproduce the behaviour:
1. Give yourself a portal for Runandor
2. Walk through

**Expected behavior**
Runandor portal should be generating instead

**Screenshots**
![2018-12-08_17 38 26](https://user-images.githubusercontent.com/44593338/49691863-51c9de00-fb11-11e8-8b73-847afd0a5436.png)

**Comment by Tslat** [comment]
Fixed in Snapshot 9
