### ISSUE TITLE
Making the Toxic Waste block a liquid.

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#150]
(another repost from one of my Discord suggestions!)

**Describe/name the existing feature this suggestion relates to**
This thing. https://adventofascension.gamepedia.com/Toxic_Waste

**Describe the change or feature you think would be good to see**
What if Toxic Waste was an actual liquid instead of just a block? It would have the same physical properties as Lava (as difficult to swim through as lava, etc.), though it would flow slower than lava and go as far as lava does in the Overworld. Also unlike lava, if the player swims in it 2 things happen: The player is inflicted with the effects of the current Toxic Waste block (poison and nausea), and takes 6 damage at the same speed lava damages stuff. It can be picked up with a bucket. (or maybe not? Depends lol)
For comparison, Lava's base damage is around 4 damage. Toxic waste would also calculate damage in the same way lava does when a player is wearing armor.

While Vox Ponds mobs aren't immune to poison, they would be immune to the toxic waste's poison, they would even be able to ignore some of the "thickness" of the toxic waste when moving through it, ~~mainly so that they don't have a hard time getting to the player, like it is currently(?)~~.
Or they would just avoid it in the same way zombies go around lava. 
Any mobs not native to Vox Ponds would get inflicted with the same effects a player does when touching the Toxic waste (except for mobs immune to poison?)
The only way for a player to make themselves immune to the Toxic waste would be poison resistance, Poison and Ghastly armor. They would still get the nausea however.

Toxic Waste could also be animated now, to make it more obvious that it's a liquid.
If possible, if items fall on Toxic waste, they should just stay floating, mainly so that items that fall in the toxic waste don't become really annoying to find. Or just make items get destroyed when they touch it lol.
If it touches water, then... I'm not exactly sure. Maybe it would just replace the water with more Toxic waste as far as it can flow?

-------------------------------------------------

This, along with making the islands in the Vox ponds more organic shapes instead of squares would really make the gen cool.

Speaking of gen changes, there should probably be parts of the gen where blocks are at the same "height" as the liquid, so that even if a player falls into the waste they could get out without having to break a block.
![image](https://user-images.githubusercontent.com/38159897/49697982-d00a9c80-fb72-11e8-9ad5-03ee02e7b8d5.png)

**Include any additional background information**
If this is considered, maybe you can also do something similar with the Toxic block in Abyss...
(Also If this is considered, you should probably make it so Exoid can't spawn in toxic pools anymore if you haven't done that already)

**Comment by Sagisolar** [comment]
Yeah I hate digging the ground up.

Guessing this is what it would look like from below.
![2018-12-09_13 38 35](https://user-images.githubusercontent.com/44548547/49698151-eab33480-fbb7-11e8-8675-471f25d37a9b.png)
