### ISSUE TITLE
Infernal and Baron Bows do exactly the same thing but not the same damage

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1511]
I don't know if I'm the only one whose noticed this but the Infernal and Baron Bows both come from the same dimension and have very similar crafting recipes. However the Baron Bow does 1 more point of average ranged damage than the Infernal Bow
![baron_recipe](https://user-images.githubusercontent.com/52132442/81075578-741c8280-8ee2-11ea-911d-9592a83f426e.jpg)
![infernal_recipe](https://user-images.githubusercontent.com/52132442/81075590-77177300-8ee2-11ea-90ba-a7ca83ef34d5.jpg)
I'd suggest maybe moving the Infernal Bow back to the Nether requiring Emberstone Ingots rather than Blazium Ingots

**Comment by Cruuk** [comment]
I've been wanting to bring this up for a while but I either forgot about it or was busy with something. Having 2 bows that do the exact same thing, crafted with materials that have equal levels of difficulty to get, but one is superior over the other. It is definitely quite odd.
I do agree with bringing Infernal bow back to the Nether, people tend to go to the Nether before Barathos so Infernal's stats would make more sense over there.

At least with Emberstone and Fireborne sword, the latter takes more materials to make compared to the easier-to-access Emberstone sword.

**Comment by Tslat** [comment]
Fixed in 3.3
