### ISSUE TITLE
Musical Dimension - Noiselands

### ISSUE THREAD

**Issue by Firch** [Tslat/Advent-Of-Ascension#1512]
Another Tier 4 Dimension suggestion: Musical-themed dimension. Giants musical instruments, mobs that looks like instruments, bard-type weapons, blocks that will create sounds if you step on them. (Just quick idea for tier 4 dimension because there only Shyrelands)

**Comment by jtrent238** [comment]
👍

**Comment by EatingSilencer** [comment]
Which dimensional path would this be on (Runandor, AC/Immortallis, Greckon/Dustopia, Lunalus, L'Borean)?
