### ISSUE TITLE
Mecha staff is unobtainable?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1513]
According to the incomplete Mecha staff page (updated by Charles "Tslat" Winston himself), you get it from Iro crates.
![image](https://user-images.githubusercontent.com/38159897/81121106-d4132900-8ee2-11ea-94b9-ce89a3c95771.png)

But...
![image](https://user-images.githubusercontent.com/38159897/81121179-f2792480-8ee2-11ea-98c3-22862a78be4c.png)
It is not there

**Comment by Tslat** [comment]
Fixed
