### ISSUE TITLE
Horndron's hitbox isn't centered horizontally

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1517]
**Mod Version**
3.2.7

**Describe the bug**
The Horndron's hitbox isn't perfectly centered horizontally; instead it's shifted forwards somewhat so that the back 1/3 of the body (not including the head) is left out. This may also contribute to the impression of it having a larger attack range than expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Type `/summon aoa3:horndron`
2. Press `F3` + `B`

**Screenshots**
![image](https://user-images.githubusercontent.com/12868968/81374505-45ee9c80-90b4-11ea-8f09-bc00f3be4f15.png)

**Comment by Tslat** [comment]
I have this intentionally

Shifting it backwards causes the player to false-swing into the front expecting to be able to hit the thing from further than they can.

Centre-body is the best way to handle this
