### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by ShinySteelix** [Tslat/Advent-Of-Ascension#152]
**Mod Version**
What version of the mod are you on?
1.2.2
**Describe the bug**
There's a somewhat-common bug (Twilight Forest has the same thing) of where Minecraft won't crash sometimes if there's conflicting biome IDs.
**To Reproduce**
Steps to reproduce the behaviour:
1: Start the game with a mod that uses the same biome IDs as AoA
2: The bug has reproduced

**Expected behavior**
The game should normally crash with an error report stating that there are conflicting biome IDs
**Screenshots**

**Comment by Tslat** [comment]
This is a not a bug, and is intentional.
Fix your ID conflicts
