### ISSUE TITLE
Baroness bomb crash game

### ISSUE THREAD

**Issue by straelok** [Tslat/Advent-Of-Ascension#1522]
**Mod Version**
3.2.7

**Describe the bug**
Baroness spam bomb and game is crashed.

**To Reproduce**
Steps to reproduce the behaviour:
Definitely not clear. Played with friend in lan mod.
1st and 2nd baroness - all ok. 3rd did crash game every time.

[crash-2020-05-11_06.14.56-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4607403/crash-2020-05-11_06.14.56-server.txt)

**Comment by Tslat** [comment]
Known bug and fixed in 3.3
