### ISSUE TITLE
Please add a cap for how many Runic Lifeforms a Rune Templar can spawn.

### ISSUE THREAD

**Issue by NeoVolt** [Tslat/Advent-Of-Ascension#1526]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.

Rune Templars

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.

There should be a cap on how many Runic Lifeforms a Rune Templar can spawn.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?

Maybe make the spawns not quite as random as they are now.

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?

ok bois story time
So I'm doing a playthrough of AoA with some friends right now and thought to myself, "Hey, Commander Armor could be nice to have for group buffs, I'm gonna grind for it." First attempt at killing a Rune Templar went over well, little to no troubles. But the second attempt, almost immediately, the Rune Templar spawned 6 Runic Lifeforms in a very short period of time. Eventually though, I kill those Runic Lifeforms off, and the HP starts to drop on the Templar again. But when they got to ~60%, it happened again, pretty much undoing all the progress that I made, and actually killing me that time. 
Needless to day, I'm kinda a bit mad about that, hence why I'm making this post.

**Comment by Tslat** [comment]
Done in 3.3
