### ISSUE TITLE
Alien Orb cannot be obtained in hardcore worlds

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1528]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Alien Orb's obtaining method

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
The Alien Orb requires that the player dies with a specific setup of items in their inventory. However, this is the problem - it requires that the player dies. This does not work for hardcore worlds, where death will be the end of the world.

The totem of undying cannot be used to get around this.

This should be changed so that death is no longer involved in the obtaining process.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
If you could make it so the totem of undying can be used to obtain it, then that would be fine.

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
No

**Comment by Cruuk** [comment]
I still think death should be an option, but an alternative should also exist. Like uhh... killing Visulon with the A-l-i-e-n setup can also give you it or something

**Comment by Tslat** [comment]
Handled in 3.3
