### ISSUE TITLE
Imbuing filled Buckets dupes them

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1529]
**Mod Version**
3.2.7

**Describe the bug**
Intervention can be applied to any unstackable item, this also applies to Buckets. However, the very nature of getting an Empty Bucket back seems to act funny with Imbuing, since this is technically the only case where a Bucket goes in the Input slot.

You can't Imbue an Empty Bucket, but imbuing a Filled Bucket will work, along with still giving you the Empty Bucket- essentially duping it. This duped Bucket is fully functional. It seems to work with all liquids.

**To Reproduce**
Steps to reproduce the behaviour:
Imbue a filled Bucket with Intervention, Empty Buckets do not appear to work.

**Expected behavior**
No dupes occurring when imbuing.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/82132227-54167a00-9792-11ea-97dc-3b95da49c02a.png)
![image](https://user-images.githubusercontent.com/38159897/82132231-5e387880-9792-11ea-8b96-598d40a7ce11.png)

**Comment by Tslat** [comment]
Fixed in 3.3
