### ISSUE TITLE
Add Iron ore (and possibly others) to Iromine

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#153]
Iromine is a "mining" dimension but it has only one ore. It's also got "Iro" in it which most likely derives from "Iron". Yet there's no iron to be found there.

I think that it should have iron ore generate just to make it slightly more interesting to be in there. Also, maybe gold, coal, and other vanilla ores too, but mostly iron of course.

Maybe another ore that isn't quite Iron but some kind of special "Iron" with different uses? I don't know.

Could also help with other mods that require a lot of iron (or your own minecart projects maybe), and give a decent reason to go there.

**Comment by Sagisolar** [comment]
How about a Special Iron?
