### ISSUE TITLE
Make llamas able to wear AoA carpets

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1534]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
In vanilla Minecraft, llamas are able to wear carpets. But the carpets added by the AoA mod don't work.

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
Make it so AoA carpets can be put on llamas, maybe with custom llama designs.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
No

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
I mentioned this on discord a long time ago. 

Here is a picture I took:
![image](https://user-images.githubusercontent.com/44556728/82255838-5825d180-9923-11ea-8400-03360a31799d.png)

**Comment by Tslat** [comment]
I'd need to make AoA a coremod or dependent on one to do this unfortunately, it can't happen (at least not in 1.12, not sure about newer versions)
