### ISSUE TITLE
Not support a Russian language in the Guides 

### ISSUE THREAD

**Issue by Hesperusrus** [Tslat/Advent-Of-Ascension#1536]
Instead of translated words "Hieroglyphs"

**Comment by EatingSilencer** [comment]
Can you clarify what you mean? Are you saying that the guides are not translated into Russian?

**Comment by Tslat** [comment]
I can only add language support if the translation has been done - and I don't speak russian

**Comment by Hesperusrus** [comment]
This is a very long time to complete the translation completely. Somewhere 4-6 Months ...

**Comment by Tslat** [comment]
Well if no-one translates it, it won't be translated.....?
