### ISSUE TITLE
Nuggets for all ingots

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1538]
I was messing around with the Oreberries mod to try to add some Oreberry Bushes of the various AoA metals then I realized no nuggets exist to do that

It be pretty cool for it to be a thing for mods to support

**Comment by EatingSilencer** [comment]
Would these be nuggets that exist in the mod 24/7? Or only when a mod needs them?

**Comment by Tslat** [comment]
What do the nuggets do? Are they just like normal iron/gold nuggets?

**Comment by EnderdragonLord** [comment]
They're pretty much like regular vanilla nuggets you get from throwing an ingot at a crafting table, they'd still exist when not using any other mods that does anything with them, there could also be some interesting uses with them like alternate ways to get ammunition or adding them through common mob drop tables or from Foraging.

**Comment by Tslat** [comment]
Done in 3.3
