### ISSUE TITLE
Skill crystals should be usable without clicking against blocks and make sounds when used

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1539]
**Describe/name the existing feature this suggestion relates to**
Skill crystals

**Describe the change or feature you think would be good to see**
Skill crystals should be usable when right clicking anywhere; in 3.2.7 they only work when right clicking on the side of a block. They should also make some sort of sound when used; especially in Creative, it seems a bit strange to have no indication that they're being used except for the skill XP popup (which can be disabled in the config).

**Comment by Tslat** [comment]
Done in 3.3
