### ISSUE TITLE
Primal sword deals only 14 damage

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1542]
**Mod Version**
3.2.7

**Describe the bug**
Primal sword deals only 14 damage. No matter how much armor you have.

**Screenshots**
With no armor
![1](https://user-images.githubusercontent.com/59332746/82727068-b505fb00-9d1a-11ea-89e1-9246efd0a2f8.png)
With Night-Vision Goggles
![2](https://user-images.githubusercontent.com/59332746/82727071-b800eb80-9d1a-11ea-8a5e-a7a67b3336ac.png)
With all Boreic Armor
![3](https://user-images.githubusercontent.com/59332746/82727076-bafbdc00-9d1a-11ea-8368-b6cc93783011.png)

**Comment by Tslat** [comment]
Unable to replicate, works fine for me and numerous other people...

**Comment by Tslat** [comment]
EDIT: NVM, some other stuff was giving me false results.
Fixed in 3.3
