### ISSUE TITLE
Tribute can be increased at nighttime, except Erebon

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1544]
**Mod Version**
3.2.7

**Describe the bug**
All types of tribute can be gained at nighttime except for killing mobs for Erebon, which seems to be the only one that checks for daytime in the code (as well as the associated decreasing of Luxon tribute). If you get full tribute during the middle of the night, there will be no sound/chat message but you will get the associated buff. I haven't tested if Krasaun's buff will be given this way.

**To Reproduce**
Steps to reproduce the behaviour:
* Harvest pixons, mine stone or harvest crops at nighttime.

**Expected behavior**
Either tribute cannot be increased at night at all, or it can for all gods and there is an indication when you reach full tribute in the middle of the night.

**Comment by Tslat** [comment]
Fixed in 3.3.1
