### ISSUE TITLE
Creeponia mobs don't make any footstep sounds

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1546]
**Mod Version**
3.2.7

**Describe the bug**
So all mobs that you find in Creeponia except the flying one don't make any type of footstep sound this could be because they don't have any specialized footstep sounds of their own (ie Cow, Iron Golem, Zombie step sounds) and that there's no event for them to play the player footstep sounds instead, so it's possible that this applies to all mobs in the mod that don't have any stepping sounds of their own, but I haven't tested further beyond Creeponia to check.

**To Reproduce**
Spawn any mob originating from Creeponia except Creepirds and have them walk around, you won't hear anything as they step on any type of block.

**Expected behavior**
They're supposed to be making player footstep sounds just like regular or friendly creepers do.

**Comment by Tslat** [comment]
Intended.
Creepers creep
