### ISSUE TITLE
Issues with AoA Spider models

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1547]
**Mod Version**
3.2.7

**Describe the bug**
Both of the Mushroom and Nightmare Spider's legs are not attached to the body, making them look like they're floating, additionally Arocknid's model isn't aligned properly like in older versions.

**Expected behavior**
The legs should be attached like other spiders, Arocknid should look like the last image.

**Screenshots**
![2020-05-23_17 35 49](https://user-images.githubusercontent.com/58011699/82741840-1da1a780-9d1c-11ea-8af1-fec8ba18f59e.png)
![2020-05-23_17 43 01](https://user-images.githubusercontent.com/58011699/82741937-6d34a300-9d1d-11ea-8eb8-61f8755d4e9b.png)
![2020-05-23_17 47 38](https://user-images.githubusercontent.com/58011699/82741960-c270b480-9d1d-11ea-9a36-0a6c462d2491.png)
![Arocknid](https://user-images.githubusercontent.com/58011699/82741965-d9170b80-9d1d-11ea-8190-608abbf2829b.png)

**Comment by Tslat** [comment]
Fixed in 3.3
