### ISSUE TITLE
Server Ticking Entity Crash

### ISSUE THREAD

**Issue by Gamerbolts** [Tslat/Advent-Of-Ascension#1548]
**Mod Version**
What version of the mod are you on?
3.2.7 1.12.2
**Describe the bug**
I run a server and one of the people on it were using guns from Tech Guns and killed a Advent of Ascension Boss. Apparently it tried exploding like mobs do sometimes with Tech Guns and crashed the server.
**To Reproduce**
Steps to reproduce the behaviour:
You can download my modpack https://www.curseforge.com/minecraft/modpacks/divine-adventure-presented-by-pxcnet
Use a Tech Guns 2 gun
Kill a Boss mob from A.O.A (could take a few tries)
Crash

**Expected behavior**
The A.O.A boss mob to explode

**Screenshots**

https://pastebin.com/LhJ8wC3E - Crash Log
Using v3.2.7 of Advent of Ascension which is the latest
Using 2.0.2.0_pre3.2 of Tech Guns
Using Minecraft 1.12.2
Using Forge 12.23.5.2847

I am not sure which mod is at fault here so I posted on both githubs. I asked the Tech Guns mod author if he could blacklist mobs from exploding. On your end is there anything you can do to stop your mobs from behaving in a way Tech Guns wants them to?

Thank you!

**Comment by Tslat** [comment]
Known bug on my end, has been fixed in the next release.
