### ISSUE TITLE
Vanilla bows can shoot holly arrows, turning them into normal arrows

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1549]
**Mod Version**
3.2.7

**Describe the bug**
Vanilla bows can consume normal and tipped holly arrows to shoot normal vanilla arrows. This behavior happens even if the bow is enchanted with Infinity; holly arrows will still be consumed and the fired arrows can be picked up as vanilla arrows. This does not work in reverse (AoA bows cannot use vanilla arrows).

**To Reproduce**
Steps to reproduce the behaviour:
1. Give yourself a vanilla bow and any type of holly arrow
2. Shoot the bow

![image](https://user-images.githubusercontent.com/12868968/82744103-f1d8ee80-9d28-11ea-94e7-74071c853046.png)
![image](https://user-images.githubusercontent.com/12868968/82744109-f9989300-9d28-11ea-8138-1e2b0b4be708.png)

**Comment by Tslat** [comment]
Fixed in 3.3
