### ISSUE TITLE
Keep Dustopia Gen From Snapshot 8

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#155]
I really like the gen. The fact that the cages spawn more often and are more see-able make the dimension more unique.

The lesser amount of trees make it less like Precasia.

**Comment by Obsinym** [comment]
Dustopia is supposed to be a dense forest (extra biomes excluded), and the new gen makes it brighter. This is probably due to being able to see the fog much more clearly.  I wouldn't be opposed to keeping the gen as a separate biome, however

**Comment by Immortallis1** [comment]
obligatory upvote

**Comment by Sagisolar** [comment]
Have this gen as a biome huh? Nah make it the forest

**Comment by DiamondWalker** [comment]
I don't actually think Dustopia should have less trees. The dimension is meant to be themed about being stalked. Having open spaces would make it easier to see enemies and takes away from that feeling. If anything I think it should have some more trees.

Also, Precasia has less trees than Dustopia. Reducing the trees in Dustopia would make it more like Precasia.

**Comment by Sagisolar** [comment]
Its not the trees, the empty cages give the stalked feeling. Because empty cages mean bad

**Comment by DiamondWalker** [comment]
> 
> 
> Its not the trees, the empty cages give the stalked feeling. Because empty cages mean bad

Still disagree. The large amounts of trees make it hard to see, therefore causing more paranoia of what awaits in the dark. If the dimension has a lot of open spaces, you can see all the mobs around you clearly, you don't have to worry about being sneaked up on. Think of it this way: would you be more afraid of being lost in a forest at night or in a dense jungle?

**Comment by Sagisolar** [comment]
Forest at night cause in a jungle, you can hive pretty easily, also there a reason all mobs in dustopia are dark in colours, so they blend in with the grass. They already have there hiding tricks already.

**Comment by Obsinym** [comment]
(not that it holds overbearing significance) but this is what the dimension is supposed to be themed around.
![image](https://user-images.githubusercontent.com/44593338/50325440-74151180-04aa-11e9-92e0-e949b90a5ef6.png)
old post from Xol btw
also speaking of slender, wouldn't the open space make you more susceptible to the static affect and increase annoyance

**Comment by Sagisolar** [comment]
Doesn't that happen already. I wouldn't say its annoying, it adds challenge to the dimension.

**Comment by Tslat** [comment]
Well past the time this could be a thing.
