### ISSUE TITLE
Projectile firing sound of goblins and other ranged mobs should have a larger range

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1550]
Ranged mobs such as goblins and spirit protectors attack you from 24 blocks, but the projectile firing sound seems to have the standard range of 16 blocks. As the projectiles don't make sounds on impact, this sometimes make it seem like you took damage out of nowhere if you're not looking in the right direction. The projectile firing sounds should be increased to 24 blocks to match the attack range IMO.

There's also quite a few mobs (such as the flying ones) that don't make any projectile sounds at all, but that's a different suggestion.

**Comment by Tslat** [comment]
Sounds in minecraft don't have a range option.

They do have an attenuation, but it wouldn't affect the overall distance.
The range of a sound is directly proportional to its volume, and I'm not just going to make the sounds thundering loud so you can hear them further away
