### ISSUE TITLE
A small part of Cryptid has no texture

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1551]
**Mod Version**
3.2.7

**Describe the bug**
Looking at one side of a Cryptid, it seems like this part of its texture is missing while on the other side it looks fine, it's a bit hard to notice but I pointed to it using the blue arrows on the screenshot.

**Expected behavior**
Both sides of the mob should be fully textured without any missing parts.

**Screenshots**
![2020-05-23_17 47 38](https://user-images.githubusercontent.com/58011699/82745239-ad108000-9d47-11ea-8389-7a99b9cfeb1c.png)

**Comment by Tslat** [comment]
Fixed in 3.3
