### ISSUE TITLE
The price of the Immortallis starting coin

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1552]
**Describe/name the existing feature this suggestion relates to**
Starting coin

**Describe the change or feature you think would be good to see**
Ever since Immortallis was first added in mid-late 2015, the price to start it has always been 10 Gold coins. However, the rate at which you can get coins today is very different than the old days where you could get free Lunaver from Foraging, later hunter mobs dropping Silver coins, Copper coins filling up your inventory way faster, etc.

Basically I do not think the 10 gold coin price is well balanced with today's coin economy- also considering how much tokens after beating Flash.
In my survival world, it took 4 runs to get all the Archaic bricks I needed for decoration. That's 2 Lunaver, which was all I had accumulated through a world I had puts lots of time in already. And I will admit that I am quite the penny pincher.

Even with all the money making methods I had, it took a while to try and get enough to buy Infusion armor. Eventually I just rushed Foraging to 100 with a maxed out Pickmax just to get the money I needed, mainly because of those 4 Immortallis runs sucking in all my cash. That's less than half of the number 9.

Anyway I would probably reduce it to like 5 Gold coins or something. I'd understand like 4-5 runs costing a Lunaver total, but just 2 runs costing a Lunaver is pretty damn brutal by today's standards. Level 90+ Foraging with a Pickmax is the 1 absolute way to actually reach that amount in a reasonable time.

**Comment by Tslat** [comment]
Done in 3.3
