### ISSUE TITLE
Shift-clicking items into the infusion table

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1553]
**Describe/name the existing feature this suggestion relates to**
Infusion table

**Describe the change or feature you think would be good to see**
It would be nice to be able to shift click items into the infusion table, since all of its recipes are shapeless (unlike crafting recipes). Similar to how shift-clicking into furnaces only works on smeltable items and automatically puts them into the appropriate slot, similar behavior could apply where weapon frames only go into the input slot, and items like enhancers, power stones and minerals only go into the grid.

**Add any alternative implementations you think might work**
Being able to shift-click items into the input slot only, if it's not feasible to make it work with the grid.

**Comment by EatingSilencer** [comment]
I think this could also be added for some other gui blocks as well, such as the Frame Bench and Divine Station.

**Comment by Tslat** [comment]
Done in 3.3
