### ISSUE TITLE
Flamewalkers create temporary fire or create fire only when aggravated

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1554]
**Describe/name the existing feature this suggestion relates to**
Flamewalkers

**Describe the change or feature you think would be good to see**
Based on [this code fragment](https://github.com/Tslat/Advent-Of-Ascension/blob/1948f67cacfac7cd3147577649a95f8da2eb0c14/source/common/registration/EntitySpawnRegister.java#L216), Flamewalkers are one of the more common Nether mobs in 3.2.7. The issue is that even if you avoid them, they will walk around and create eternal fire trails on Netherrack, leading to increasing areas of fire that you'd have to clean up (unless you replaced the Netherrack with other blocks).

I have two suggestions for this; one of them is that they only create fire when aggravated to a player (and perhaps when damaged by a ranged weapon), so that you'd still have to deal with their fires when fighting them but they don't create a mess otherwise. Their texture could change when aggravated where their eyes or other body parts light up.

The alternative suggestion is for them to create a different type of fire that extinguishes after a while even on Netherrack, making them more like the Precasian giant snails in that regard.

**Comment by Tslat** [comment]
Probably not a bad idea yeah...
I'll do this in 3.3
