### ISSUE TITLE
Attacking infernals in Creative briefly sets you on fire

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1555]
**Mod Version**
3.2.7

**Describe the bug**
If you are in Creative mode and do melee damage to an Infernal, you will be set on fire for a split second.

![image](https://user-images.githubusercontent.com/12868968/82766464-3a011b00-9dd4-11ea-8e04-101448bcb82e.png)

**Comment by Tslat** [comment]
Fixed in 3.3
