### ISSUE TITLE
Ghostly Bugeye is not aligned the same as a regular Bugeye

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1556]
**Mod Version**
3.2.7

**Describe the bug**
Ghostly Bugeye's eye (head?) is misaligned unlike the regular Bugeye despite both using the same model.

**Expected behavior**
Should look like the Bugeye to the left of the screenshot.

**Screenshots**
![2020-05-24_20 18 15](https://user-images.githubusercontent.com/58011699/82769917-38e3e400-9dfc-11ea-8f59-de3f7428260b.png)

**Comment by Tslat** [comment]
Fixed in 3.3
