### ISSUE TITLE
Rawbone's legs are not attached to its body on one side

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1557]
**Mod Version**
3.2.7

**Describe the bug**
On one side it looks fine, on the other the legs are detached from its body.

**Expected behavior**
Both sides should have the legs connected.

**Screenshots**
![2020-05-24_20 16 21](https://user-images.githubusercontent.com/58011699/82770017-95470380-9dfc-11ea-9ace-5ac4ed3a041e.png)

**Comment by Tslat** [comment]
Fixed in 3.3
