### ISSUE TITLE
Sponge Server Boss Spawn is not working

### ISSUE THREAD

**Issue by EwayZ001** [Tslat/Advent-Of-Ascension#1560]
I have the sponge server 1.12.2
Troll idol will not spawn, It just disappears after a few seconds.
In the single-player, it works well.

**Comment by Tslat** [comment]
Make sure you're not in creative difficulty.

Also, I don't support sponge. The mod is made for forge, any issues sponge has is their own problem

**Comment by EatingSilencer** [comment]
What version of the mod are you using? If its 3.0, you'll need to update and see if that fixes it.

**Comment by EwayZ001** [comment]
The spawn egg works fine, but not the troll idol.

**Comment by EwayZ001** [comment]
It's 3.2.7
Thank you guys!

**Comment by PoSayDone** [comment]
Have the same issue with sponge 7.2.1 and AoA 3.2.7/3.3.6

**Comment by EatingSilencer** [comment]
> 
> 
> Have the same issue with sponge 7.2.1 and AoA 3.2.7/3.3.6

If you are having an issue then post the latest.log file. It is possible that sponge is the culrpit but not sure.
