### ISSUE TITLE
Notice Board Won’t Close ( Brother & Others Have The Same Issue )

### ISSUE THREAD

**Issue by BruhItsMarc** [Tslat/Advent-Of-Ascension#1561]
hello, i’m currently playing on 1.7.10 AoA (because i’m trying out the omega pack) and the notice board won’t close? i have hit “INSERT” multiple times now. i’ve tried searching online and even checking config but there’s nothing. i seen socksfor1 close it so ik there’s a way. i have asked him on how he did it but never got a reply, so hopefully here i could get a reply? btw this is a problem for a lot of people as well, for example my brother can’t close it either. please let me know what is going on and how i could potentially fix this problem. also no other mod is affecting this glitch, because i tried just having the AoA by itself to see if it was a mod affecting it and it wasn’t.

**Comment by EatingSilencer** [comment]
Maybe change the Insert button to something else in the Controls menu?

**Comment by Tslat** [comment]
Change the control option from insert to something else in options.

Also, 1.7.10 is outdated and no longer supported. Update to 1.12 if you want updates and suport
