### ISSUE TITLE
Lunalus Realmstone how?

### ISSUE THREAD

**Issue by Nopschy** [Tslat/Advent-Of-Ascension#1574]
**Mod Version**
3.2.7

**Describe the bug**
How we can drop the Lunalus Realmstone?
The Wiki say:  "Jump over Haven's void with a Gravitator."
Nothing happen if we jump with a Gravitator  over the Heaven.

**Comment by Tslat** [comment]
Make sure you have the blank realmstone in your inventory, otherwise it won't work.
Hold out the gravitator, then jump from one block to another, over a gap down to the void
