### ISSUE TITLE
The mod's logo in the Advent GUI is an older logo

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1575]
**Mod Version**
What version of the mod are you on?
3.2.7

**Describe the bug**
The logo in the Advent GUI for the mod is an older version of the logo. This is apparent in that it does not have the retextured crystevia crystal.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the Advent GUI.
2. See the older logo.

**Expected behavior**
The logo is updated to match the new logo.

**Screenshots**

(Note: username is censored from this image)

![image](https://user-images.githubusercontent.com/44556728/83104636-27623c80-a087-11ea-893d-71e47b67691f.png)

Here is what the new logo looks like:
https://gamepedia.cursecdn.com/adventofascension_gamepedia/b/bc/Wiki.png?version=6d88db10dd0d8df96f2a099b4d3bcbdc

**Comment by Tslat** [comment]
Fixed in 3.3
