### ISSUE TITLE
Some item uses do not count towards Minecraft's Item use stats

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1576]
**Mod Version**
What version of the mod are you on?
3.2.7

**Describe the bug**
When you "use" an item in Minecraft, it counts towards Minecraft's use item stats, as you can see in the screenshot below - it is the third column. However, it appears that at least some of AoA's items do not count toward the Use item stat. Here is a list that I have tested in creative mode:
-Stone and Diamond bowls, using them on the Extraction Device, and by harvesting Glistening Pixons.
-Opening a shiny box. crystal box, weapons box, fish case, treasure box, rune box, and gem bag.
-Using a Shyregem Bow. I haven't tested other bows.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get any of the above items in the list.
2. Use them by right-clicking them.
3. Check item statistics (Pause game -> Press Statistics -> Items -> Scroll to item)*
*NOTE: from testing this I noticed it does not update right away. You can get a feel for how long it takes to update by using a Lava Bucket. The Lava Bucket's use tallies will increase when the others in the list above will not.
**Expected behavior**
The item use statistic is increased like normal.
**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/83105800-54afea00-a089-11ea-9ecc-d9a409cb5a06.png)

**Comment by EatingSilencer** [comment]
I'll add that tablets do not seem to be affected by this - I can place tablets and it will count towards the use stat. I have tried this with Tablet of Agility and Tablet of Breeding.

**Comment by Tslat** [comment]
For your future reference, stats take 15 seconds to update on the client.
Opening the stats window prior to that 15 second elapsing can reset the time back to 15 seconds again

**Comment by Tslat** [comment]
Fixed in 3.3
