### ISSUE TITLE
Neon lamps bugged recipe

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1577]
**Mod Version**
What version of the mod are you on?
3.2.7

**Describe the bug**
Looking in the mod's files, and based on asking this question before in Discord, the neon lamps don't seem to have recipes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Check the recipes of the neon lamps using JEI.
2. Find that the recipes don't exist.

**Expected behavior**
The neon lamps should be craftable or it should be stated why the recipes were removed.

**Comment by Tslat** [comment]
Just no current implementation as yet.
