### ISSUE TITLE
Immovable Object is granted for taking excessive fall damage, and doesn't require you to survive the hit

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1578]
**Mod Version**
3.2.7

**Describe the bug**
The Immovable Object advancement can be granted for damage that's not caused by mobs, such as fall damage. In addition, it does not actually require the player to survive the hit, so you could get it by jumping off of a tall cliff or blowing yourself up with TNT.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `/advancement revoke @s only aoa3:overworld/immovable_object` to remove the advancement if you already have it
2. Change to survival mode
3. Teleport yourself 50 blocks up

**Expected behavior**
The "immovable object" name suggests that it would require you to survive the hit, and the description ("Take a 40 damage or higher hit") suggests that the damage has to be caused by another mob/player, or at least not something like falling which is very easy to achieve.

**Comment by Cruuk** [comment]
I feel like I'm having a mandela effect of Scimi already trying to fix this like 2-3 times

**Comment by Tslat** [comment]
Minecraft's built-in advancements suck -.-

**Comment by Tslat** [comment]
Dealt with in 3.3
