### ISSUE TITLE
Incompatibility with Matter Overdrive Androids

### ISSUE THREAD

**Issue by tiffany352** [Tslat/Advent-Of-Ascension#1579]
**Mod Version**
AoA: 3.2.7
Matter Overdrive: Legacy Edition 1.12.2-0.7.1.0-universal
Minecraft: 1.12.2
Forge: 14.23.5.2847

This is a modpack with many other mods as well in case that's relevant. It's available here: https://www.curseforge.com/minecraft/modpacks/divine-adventure-presented-by-pxcnet

**Describe the bug**
Two of the realmstone challenges don't work when you become an Android:

1. To unlock Candyland, you have to eat a Heart Fruit in Precasia. You can only eat foods that can be eaten with full hunger, like golden apples.
2. To unlock Dustopia, you have to summon Shadowlord with night vision active. Androids have a perk that gives night vision, but it doesn't count for this challenge for unknown reasons. It shows up like a potion effect:
![image](https://user-images.githubusercontent.com/1254344/83314358-d9585080-a1ce-11ea-8fdd-1bfd4a3110b4.png)

Androids are immune to all status effects except fire, so you can't use a night vision potion as a workaround.

The Candyland issue can technically be worked around by resetting your upgrades. The Dustopia issue would have to be worked around by taking the Blue Pill to stop being an Android entirely, I think. Both of these are pretty tedious.

Another workaround is to have someone else (who isn't an Android) make the realmstones for you.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install both mods.
2. Obtain a Matter Overdrive Red Pill and eat it, or do the quests from the Mad Scientist villager. You'll die and respawn as an Android.
3. Obtain an Android Station and place it. Doesn't need RF.
4. Unlock the Night Vision and Zero Calories upgrades using XP levels.
5. Try to complete the two challenges listed to unlock Candyland and Dustopia.

Androids have to stay charged to stay alive, which you can do by holding shift with a battery in your hand, or using the Charging Station.

**Expected behavior**
Ideally I should be able to eat the heart fruit with full hunger. I'm not sure why the Dustopia challenge doesn't work though, seems unintended.

**Screenshots**
![image](https://user-images.githubusercontent.com/1254344/83314524-aebac780-a1cf-11ea-9947-9ae2a2018238.png)
![image](https://user-images.githubusercontent.com/1254344/83314532-b4b0a880-a1cf-11ea-9ed9-465612d83c6f.png)

I understand if this isn't worth fixing, I just saw that nobody else has reported it when I searched the issues.

**Comment by Tslat** [comment]
I'd take this to the makers of that other mod. There's really nothing I can do from my side to make it work besides changing how the mod plays for those realmstones, which I'm not doing.

IF their mod restricts gameplay, it needs to be on them to take into account the edge cases they're cutting off
