### ISSUE TITLE
1.1 portal system for some dimensions

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#158]
I think that for variety reasons, some dimensions should be "downgraded" to 1.1's portal system. For anyone who started playing the mod afterwards, back in Xol's 1.1, portals would spawn naturally in structures (greckon and runandor's portals are remnants of this system). The portals I would like to see reverted (and the reasons why) are:

Deeplands: While it might seem to be an odd choice, deeplands generated in overworld caves, and is also an early dimension. I think it would fit in nicely with Scimi's new portal system, since not only would it add yet another reason to explore caves, it would also add a side quest when searching for the ruined teleporter and something else to do in the early game.

Iromine: There are already three realmstones that drop in the Deeplands (Crystevia, Iromine, and Ancient Cavern). All of these realmstones are obtained by killing naturally spawning mobs, so there is little to no variety in obtaining them. The reason I choose Iromine to use the old system is because it fits the Deeplands' color scheme the best, and also since it already has a nice structure designed for it back in 1.1

Barathos: I don't really see too many reasons for Barathos to spawn naturally, aside from trying to keep it as consistent with Runandor as possible.

Dustopia: See Barathos.

P.S. These would still have realmstones which drop from the rare mobs in the dimensions.

**Comment by Immortallis1** [comment]
Personally I don't feel like naturally spawning portals are necessary, especially when the last two are just "consistent with runandor/greckon". The current system is fine. Realmstone obtaining variety can probably be done later

**Comment by DiamondWalker** [comment]
> 
> 
> Personally I don't feel like naturally spawning portals are necessary, especially when the last two are just "consistent with runandor/greckon". Thus far there haven't been any issues.
> 
> The current system is fine. Realmstone obtaining variety can probably be done later, and is important for all dimensions, it's just slightly more apparent for Iromine/Deeplands.

I personally don't like the idea of giving each realmstone a unique way to obtain it, since that sort of defeats the purpose of "unique" realmstones like Labricon. I do think having some naturally spawning portals are better than having to always build it yourself, but it seems most people disagree.

Unrelated, but I would actually like to see the old portal structures used for something, even if it's not for naturally spawning structures. Maybe they could serve as the portals that appear when you enter a dimension?

**Comment by Tslat** [comment]
This isn't really a viable thing with 3.2
