### ISSUE TITLE
Some textures have problems

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1580]
**Mod Version**
3.2.7

**Describe the bug**
The textures of some mobs have some small problems

I only found two. There should be more similar mistakes. Maybe need to check them once

**Screenshots**
Blissard.1
![1](https://user-images.githubusercontent.com/59332746/83317492-b0cc6700-a25f-11ea-9fb4-5b17ddec1a39.png)
Blissard.2(It's hidden)
![2](https://user-images.githubusercontent.com/59332746/83317497-bde95600-a25f-11ea-9a8a-4fe5a051eb5d.png)
Refluct
![3](https://user-images.githubusercontent.com/59332746/83317501-c9d51800-a25f-11ea-818e-7e5289785075.png)
I try to fix them,so...
![1 1](https://user-images.githubusercontent.com/59332746/83317588-639cc500-a260-11ea-9983-ad7387ed563c.png)
![2 2](https://user-images.githubusercontent.com/59332746/83317590-67c8e280-a260-11ea-88db-f1bd7671950c.png)

**Comment by Tslat** [comment]
Fixed in 3.3
