### ISSUE TITLE
Scrubby's head is not attached

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1581]
**Mod Version**
3.2.7

**Describe the bug**
Scrubby's head doesn't look like it's attached, pointed to the spot with the arrows.

**Screenshots**
![2020-05-30_13 09 15](https://user-images.githubusercontent.com/58011699/83336243-6a830200-a277-11ea-836a-a17b464eeebf.png)

**Comment by Tslat** [comment]
Fixed in 3.3
