### ISSUE TITLE
Candied Water for the Chemical Thrower (Immersive Engineering)

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1582]
The Chemical Thrower is an interesting weapon that Immersive Engineering adds, it allows you to utilize different liquids including some from certain mods to use as ammo with different effects, some are even flammable which turns the weapon into a Flamethrower.

Here's a page of examples on what some of the liquids can do:
https://ftb.gamepedia.com/Chemical_Thrower

This would help make Candied Water a lot more useful than it is right now, and at the moment it can already be used as ammo, but has no effects and is unable to put out fires.

**My suggestions on what it can do is:**

- It acts exactly like water being able to put out fires and damage Blazes or anything that can be damaged by water normally.

- It gives either the Sticky or the Slowness effect. (Sticky is a new effect added by IE that is similar to slowness but prevents jumping.)

![2020-05-30_23 21 30](https://user-images.githubusercontent.com/58011699/83344769-e8272c00-a2d0-11ea-9ec1-d9e0ba321fc4.png)

**Comment by Tslat** [comment]
Done in 3.3
