### ISSUE TITLE
The legs of these mobs are not aligned consistently on both sides

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1583]
**Mod Version**
3.2.7

**Describe the bug**
The legs of these mobs (mostly the back) are not the same alignment on both sides, some of them already looked like this on very old versions too, but I'm putting this here for consistency with other mobs.

**Mobs affected**
- Ramradon
- Hive King
- Chimera
- Rock Crawler
- Rock Critter (Part of its legs are not attached to its body either)

**Expected behavior**
Their legs should be aligned the same on both sides, Rock Critter's legs should be more attached as well. (Maybe move the legs further to the head/body?)

**Screenshots**
![models1](https://user-images.githubusercontent.com/58011699/83374850-77484880-a392-11ea-9f21-32a2378907af.png)

![models2](https://user-images.githubusercontent.com/58011699/83374853-7b746600-a392-11ea-8014-f673a79575b0.png)

**Comment by Tslat** [comment]
This was fixed in 3.3
