### ISSUE TITLE
Maybe more fog in Dustopia

### ISSUE THREAD

**Issue by lunarmaximum** [Tslat/Advent-Of-Ascension#1584]
Dustopia used to be a foggier dimension and I think that played really well with the ambience, but I noticed in 3.2.7 it was taken away

![image](https://user-images.githubusercontent.com/31499719/83388341-ea15eb80-a3b3-11ea-83bd-044c952be9cc.png)

Before: 

![image](https://user-images.githubusercontent.com/31499719/83388456-1df11100-a3b4-11ea-8007-637f14504a1a.png)

**Comment by Lithobraker** [comment]
Is that old screenshot taken with night vision? I really like the way it looks with white fog- reminds me of Silent Hill, or LIMBO.
