### ISSUE TITLE
There are stray unused loot tables in the mod's files

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1588]
**Mod Version**
What version of the mod are you on?
3.2.7

**Describe the bug**
During 3.2's development, some loot tables for mobs got placed into the wrong folders. While some of these were cleaned up, there are some that remain. These include:
1. In loot_tables/entities/mobs/haven:
    a. green_flower.json
    b. green_runic_lifeform.json
    c. red_runic_lifeform.json
2. In loot_tables/entities/mobs/barathos:
    a. rammerhorn.json
3. In loot_tables/entities/mobs/overworld:
    a. skull_creature.json

Note that these are not misplaced files - correct loot tables in the correct locations exist. These are just duplicates (In the case of green_flower.json - its a minion so it doesn't have a loot table).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to one of the above folders I listed.
2. See that the files exist where they shouldn't be.

**Expected behavior**
None of these loot tables should exist.

**Comment by Tslat** [comment]
Done in next version
