### ISSUE TITLE
Planks and stuff for the other types of mushrooms (Aqua, Peach, Black, etc.)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#159]
**Describe the new feature you think would be good to add**
![image](https://user-images.githubusercontent.com/38159897/49973115-ac37b580-fee8-11e8-80d7-cda39631f84b.png)
(Aqua and Peach don't even have stems, those blocks are just the ones you find inside the mushroom)

As it stands, all the Mysterium mushrooms have their own wooden planks and even a mini mushroom thing. However, the same cannot be said for mushroom blocks outside of Mysterium, black mushrooms in Deeplands, Aqua and Peach mushrooms in Gardencia, and I guess the mini mushroom in Vox ponds. They don't have the neat stuff the Mysterium mushrooms have, and I think it would be really cool if they did. It would really add to the biomes once they're re-added in 1.13/1.14. Also I've always liked the style of the mushroom planks so...

There is a Deep Fungal Cave biome, so adding mini black mushrooms there would be cool. Black mushroom planks would be the first wooden planks for Deeplands. Same goes for mini aqua and peach mushrooms in Gardencia, Aqua and Peach planks also being the first Gardencia planks...

Vox Ponds is a bit of a tricky one, because there's already wooden planks that have a similar shade of green, maybe the mushrooms are so rotten you can't make planks out of them? Also I think it would be perfect if giant Vox mushrooms were added to Vox ponds and got their own biome.

So yeah the mushroom planks are pretty cool and if the other mushrooms had them that would also be pretty cool.

**Include any additional background information**
Aqua and Peach mushroom stems should also be added so that the mushrooms in Gardencia don't need to use the goddamn plant stems and inside blocks as the stem.
![image](https://user-images.githubusercontent.com/38159897/49974510-9b8a3e00-feee-11e8-99f4-8d2e518150cf.png)

**Comment by Tslat** [comment]
No longer relevant
