### ISSUE TITLE
No Worn Book

### ISSUE THREAD

**Issue by MrGame1000** [Tslat/Advent-Of-Ascension#1590]
I am trying to get Blank Realmstones but for some reason, there is no Worn Book in the entire game. I a playing in the 1.7.10  AOA3 edition. No Shrines spawn, no Ruined Portals spawn, and therefore no Corrupted Travelers spawn. So I tried going into creative to get the worn book, but when I searched for it, nothing showed up. When I check the config, there is nothing there other than configuration for dimensions and skills.

**Comment by EatingSilencer** [comment]
It sounds like you are using an out of date version of the mod, even for 1.7.10. You'll need to update the mod (either to 1.12.2 or to the latest 1.7.10: Tslat 1.1.3) to get the worn book.

On that note, there is no blank realmstones in 1.7.10 period. Accessing dimensions is done differently in 1.7.10.

**Comment by MrGame1000** [comment]
I updated to 1.1.3 and it now has a Worn Book. But when I open it, it doesn't give me a Blank Realmstone. What do I do?
