### ISSUE TITLE
Broken Worn Book

### ISSUE THREAD

**Issue by MrGame1000** [Tslat/Advent-Of-Ascension#1591]
When I open a Worn Book, it doesn't give me a blank realmstone. I am in 1.7.10 version 1.1.3. How do I get realmstones, specifically the Vox one.

**Comment by EatingSilencer** [comment]
You can find out how to obtain realmstones in that version here:

[https://adventofascension.gamepedia.com/index.php?title=Ancient_Teleportation&oldid=64891](https://adventofascension.gamepedia.com/index.php?title=Ancient_Teleportation&oldid=64891)
