### ISSUE TITLE
Emberstone Pickaxe should give experience when it autosmelts

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1593]
Figured I'd put this here since the Fiery Pick from Twilight Forest and the Autosmelt modifier from Tinker's already does this, they gave the same amount of experience as what you would've gotten if you smelted the ore at a furnace.

The Autosmelt from Tinker's was compatible with Fortune too, but this is only if you don't have it turned off in the config, so I don't know how powerful that would be. 

Maybe some sort of craftable upgrade for the Emberstone Pickaxe to make it Fortune compatible?

**Comment by Tslat** [comment]
Fixed in 3.3.1
