### ISSUE TITLE
[3.3]Primal sword damage bug

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1594]
**Mod Version**
3.3

**Describe the bug**
Once in a while, primal sword will increase player's permanent damage
1.Attack with Primal sword with armor
2.Attack with empty hands with no armor
3.then...
![23](https://user-images.githubusercontent.com/59332746/83944201-376ede80-a834-11ea-809d-270814b246ff.png)
![12](https://user-images.githubusercontent.com/59332746/83944214-4c4b7200-a834-11ea-8ae1-54068dcab65d.png)

**Comment by Tslat** [comment]
Primal Sword has been a pain -.-

Fixed in 3.3.1
