### ISSUE TITLE
[1.12.2] Game crashes upon load with Industrial Craft 2.

### ISSUE THREAD

**Issue by Z-Tunic** [Tslat/Advent-Of-Ascension#1595]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 3
AoA3-3.3
industrialcraft-2-2.8.218-ex112
jei_1.12.2-4.15.0.291

Crash:
https://pastebin.com/H3rXXGrA

=====

Start up Minecraft, let it load... and... boom.

**Comment by DarkAmbientNoise** [comment]
Agreed, a temporary fix is to disable AoA's IC2 integration in the AoA config file. But who wants that?

The exact same crash report errors out for both the latest experimental version and stable version being 2.8.218-ex112 and 2.8.170ex112, respectively.

JEI is not required for this crash to occur.

**Comment by Tslat** [comment]
Fixed in 3.3.1
