### ISSUE TITLE
Missing Thaumcraft Aspects on these blocks

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1596]
These blocks are supposed to have aspects, but they seem to be missing them.

- Crystallite Ore (Crystallite already has aspects but not the ore, also just noticed that it has the extra Terra that was meant to be for the ore.)
- Pink Daylooms
- Blue Daylooms

For both Daylooms, the yellow version already has aspects but not the other two colors.

![daylooms](https://user-images.githubusercontent.com/58011699/83948140-f0a3c900-a7e0-11ea-83a9-4833fa5fdf14.png)

**Comment by Tslat** [comment]
Done in 3.3.1
