### ISSUE TITLE
Ethereal Miner Does Not Work with Dragon Egg

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#1597]
**Mod Version**
3.3

**Describe the bug**
After the block below the dragon egg is mined with a tool that has ethereal miner effect, the dragon egg still drops.

**To Reproduce**
Steps to reproduce the behaviour:
1. Craft a tinkers' tool with ethereal miner effect
2. Place the dragon egg on top of a block
3. Break the block with the tool created in step 1

**Expected behavior**
The dragon egg should be hovering in mid-air

**Screenshots**
I don't think it will help.

**Comment by Tslat** [comment]
Fixed in 3.3.1
