### ISSUE TITLE
You can get past the minion summon limit by flying

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1598]
**Mod Version**
3.3

**Describe the bug**
There's a method to "trick" the limit so you can summon as much minions as you want. It's kinda hard to explain it, but I found out that by flying and never touching the ground, the minions will never teleport to you, this can be done through either Creative or through anything that lets you fly, especially wings or jet packs.

**To Reproduce**
1. Use Creative or any item that allows flying, while having the max limit of minions.
2. Fly up and head far away enough from all your summoned minions.
3. Right click on any type of slab, it will end up summoning another minion.
4. Land back at the ground to be greeted by your party.

**Expected behavior**
Should always prevent you from summoning more minions when you're at the limit. One way that could probably be done is to have all your minions fly with you whenever you fly up, allowing them to teleport even if you're not touching the ground.

**Screenshots**
![2020-06-06_11 54 47](https://user-images.githubusercontent.com/58011699/83950052-7594df80-a7ed-11ea-9341-8a4d0189dfd0.png)

**Comment by Tslat** [comment]
The minion limit is only really a soft limit at the moment since I don't track them on the player's profile.
While this isn't intended, it's not really unintended by the current system.

The Skill rework may or may not fix this.
