### ISSUE TITLE
Resource bar texture flickers when regenerating

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1599]
**Mod Version**
3.3

**Describe the bug**
Some pixels in the resource GUI flicker when that resource is regenerating. This mostly seems to affect the top-left corner and the center icon, and only in the colored portion. I haven't tested whether this also occurs to the resource icons in the Advent GUI with the `mainWindowPausesGame=false` config setting.

See https://streamable.com/5g666k

**To Reproduce**
Steps to reproduce the behaviour:
1. Log into a world, since this currently causes resources to reset to 0.
2. Open the resources GUI

**Comment by Tslat** [comment]
I can't replicate this myself due to it being a scaling issue on certain monitors with certain resolutions.
I'll adjust something for 3.3.1, let me know if it still occurs

**Comment by Sonicwave** [comment]
There is still minor flickering in a few pixels in the center icon (for Energy and Rage, I didn't test the others), but it's slower and far less noticeable than before. I don't think I would notice it unless I was looking carefully for several seconds.
