### ISSUE TITLE
Give Crystocore The Ability To Levitate Players

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#160]
Crystocore is great intresting boss fight, but it has missed out on a huge potential.

Give it the ability to levitate players like Orbiters and Syskers. Since no other boss has this ability, I can see give the boss more of a identity than just "Boss that give defects." Make him levitate not fly so he doesn't wonder off. Also a actual attack.

![250px-crystocore](https://user-images.githubusercontent.com/44548547/50046743-5c035380-00a0-11e9-8fe5-499fd105bf67.png)

**Comment by EatingSilencer** [comment]
Maybe Crystocore can have the Levitation buff added to his buffs that he can inflict on the player?

**Comment by Sagisolar** [comment]
Levitation Buff? like orbiters
