### ISSUE TITLE
Meganeuropsis is using shik's loot table

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1600]
**Mod Version**
What version of the mod are you on?
3.3

**Describe the bug**
The new Meganeuropsis mob is using Shik's loot table. It appears to have its own loot table in the mod's files but it doesn't seem to be registered in the LootSystemRegister.

**To Reproduce**
Steps to reproduce the behaviour:
1. Check Meganeuropsis' code for the loot table [(link](https://github.com/Tslat/Advent-Of-Ascension/blob/c0e0a8c21a3dfec3218add196fec9ed47a8168ed/source/entity/passive/EntityMeganeuropsis.java#L131))
2. See that it is using the Shik loot table.

**Expected behavior**
Meganeuropsis should be dropping items from its own loot table.

**Comment by Tslat** [comment]
Fixed in 3.3.1
