### ISSUE TITLE
Shift-clicking items in the Divine Station causes problems - including duplicating items

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1601]
**Mod Version**
What version of the mod are you on?
3.3

**Describe the bug**
The 3.3 update recently added the ability to shift-click items into the Divine Station's slots. But there's a couple problems with this. The first: if an item is in both the first and second slots, you will be unable to shift-click the second item back into your inventory.

The second problem: if the item in the second slot is stackable, then when the player attempts to shift-click it while there is an item in the first slot, then the item in the second slot will automatically become a stack of 64 of that item. This appears to be a legit stack.

**To Reproduce**
Steps to reproduce the behaviour:
1. Grab a Divine Station and place it down. Also grab three items: one nonstackable item, one stackable item, and one of any item.
2. Open the Divine Station's GUI.
3. Place the "any item" in the first slot and the nonstackable item in the second slot.
4. Try to shift-click the item in the second slot. See that it does not return to the player's inventory.
5. Replace the nonstackable item with a stackable one. Make sure its not a stack of 64. Shift-click this item once it is in the second slot.
6. See that the stackable item automatically becomes a stack of 64.

**Expected behavior**
Shift-clicking the item in the second slot returns it to the player's inventory and does not duplicate items.
**Screenshots**
Before shift-click:
![image](https://user-images.githubusercontent.com/44556728/83951157-8b120580-a7fd-11ea-8049-abb0c70e6835.png)
After shift-click:
![image](https://user-images.githubusercontent.com/44556728/83951161-91a07d00-a7fd-11ea-9564-2411cb25b0f1.png)

**Comment by Tslat** [comment]
Fixed in 3.3.1
