### ISSUE TITLE
Sharp Claw Modifier can be applied to anything

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1603]
**Mod Version**
3.3

**Describe the bug**
Sharp Claw can be applied to any weapon, which includes arrows, bolts, and bows.

**Expected behavior**
Some modifiers in Tinker's are limited to some tools or weapons, the Expander modifiers are only limited to tools, which means trying to apply it with weapons wouldn't work. It would make more sense for the Sharp Claw to only work on swords.

**Screenshots**
![Modifiers](https://user-images.githubusercontent.com/58011699/83952856-99622080-a801-11ea-9699-c19cddc9f22a.png)

**Comment by Tslat** [comment]
Fixed in 3.3.1
