### ISSUE TITLE
[1.12.2] Runic Trait oddity when paired with certain other traits.

### ISSUE THREAD

**Issue by Z-Tunic** [Tslat/Advent-Of-Ascension#1604]
Refer'd Issue:
https://github.com/TeamDman/PlusTiC/issues/9

Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 7
ActuallyAdditions-1.12.2-r151-2
AoA3-3.3
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
natura-1.12.2-4.3.2.69
*plustic-8.0.1.0
TConstruct-1.12.2-2.13.0.183

*Note*
PlusTiC is found here:
https://www.curseforge.com/minecraft/mc-mods/plusticminusbad

=====

In a modded survival world that I play on, I was messing around with the traits that AoA added such as 'Runic' and noticed that certain traits when paired with Runic don't seem to work correctly.

PlusTiC, or xXx_MoreToolMats_xXx as it's called in the fork adds in usable materials & traits depending on the mods you have installed... in this case, I have have what's added in the list above in order to gain access to the listed traits & materials.

The 'Hearts' trait can only be gotten from Restonia Crystals if Actually Additions is installed. It grants a damage boost depending on your health so if you have 100% health, you'll deal up to +70% more Damage.

The 'Bloody Mary' trait can be gotten from either Natura's Bloodwood, or Thermal Foundation's signalum. You deal extra damage depending on the mob's remaining health.

Now then... I'm using a Tinkers Scythe Tool since it has 1 Head part that affects damage while the other 3 parts affects durability & such. It's Head Material is Magma Slime which gives 6.25 damage & by using 3x Sharp Modifiers... it brings it's damage to 10.69.

For these tests I am slaying an Iron Golem as it has 100 health and it doesn't KO you when on Peaceful. I will only list the traits that are on the tool but the Head Part will always be Magma Slime as well as having 3x Sharp Modifiers. My Health is at 20/20 aka 100% in order to make use for the full damage buff from 'Hearts'.

'Superheat' will only deal bonus damage if the target was on fire, but in these tests the target is never on fire so the trait does nothing. 'Lightweight' only increases Break Speed & Attack Speed and 'Ecological' very slowly repairs the tool by 1 point.

I also disabled skills so the 'Butchery' Skill doesn't add in extra damage when it procs. Finally... using ToroHUD in order to view the mob's health as well as show damage particles.

***Test 1***
Traits: Superheat, Lightweight

Damage Dealt: 11

***Test 2***
Traits: Superheat, Lightweight, Hearts

Damage Dealt: 18

***Test 3***
Traits: Superheat, Lightweight, Bloody Mary & Ecological

Damage Dealt: 11, 15, 17, 20, 22, 24

***Test 4***
Traits: Superheat, Lightweight, Hearts, Bloody Mary & Ecological

Damage Dealt: 18, 23, 26, 29, 31

=====

Now for these upcoming tests, same as before however the 'Runic' trait is added into the mix which is from Elecanium. The nice thing with ToroHUD is that it can show you the 'split' damage when Runic converts some of the the damage into Magic Damage.

Runic converts 10% of the damage into Magic Damage. Up to 30% if you have Runic III. I only had Rank 1 of the Runic Trait so that's only 10% of the damage converted.

***Test 1***
Traits: Superheat, Lightweight, Runic

Damage Dealt: 10
Particle shows 9 & 1

***Test 2***
Traits: Superheat, Lightweight, Runic, Hearts

Damage Dealt: 10
Particle shows 9 & 1

***Test 3***
Traits: Superheat, Lightweight, Runic, Bloody Mary & Ecological

Damage Dealt: 10
Particle shows 9 & 1

***Test 4***
Traits: Superheat, Runic, Hearts, Bloody Mary & Ecological

Damage Dealt: 10
Particle shows 9 & 1

=====

I've tried with vanilla Tinker traits such as 'Prickly' which appears to give an extra 1 damage sometimes and Runic doesn't seem to conflict with that. It's perhaps due to the way that Hearts & Bloody Mary work but still figure I give it a mention.

The 'Spades' Trait is also effected where it's damage boost won't work if you have the Runic trait. Spades trait which is from Palis Crystals via Actually Additions increases your damage the lower your health is.

I'll do some more testing with other mods that add in their own traits/materials or something in case anything else conflicts with Runic.

**Comment by Tslat** [comment]
I'm not really sure whether there's much I can do from my side.. I only have limited options when coding in these traits and after taking another look I don't think I could do it to be any more compatible.

The fact that it works with prickly might indicate maybe the other mods are doing something wrong?

**Comment by Z-Tunic** [comment]
It's possible, unless with the way that Runic converts the damage, and Hearts/Bloody Mary/Spades doesn't 'see' that the damage was converted.

If I were to guess with Prickly... it does bonus damage that stacks on top of the base damage. From testing it appears to be an occasional 1 bonus damage that ignores armor.

The Trait 'Morgan Le Fay' which can be gotten from Actually Addictions via Diamatine Crystals deals a random 0-5 bonus magic damage.

I'll try opening up an issue on xXx_MoreToolMats_xXx's side to see if anything could be done over there.

**Comment by Z-Tunic** [comment]
Alright... this is rather crazy... but... the the traits DO work correctly if Runic Trait is at the top of the list of the traits. If it's lower on the list then those traits above it won't work. Here's an example image.

The 'y+x' is 'Base + Magic' Damage.

![](https://cdn.discordapp.com/attachments/377171551155650560/720012385439449128/runictraittopmost.PNG)
Runic is at the top of the list so Hearts & Bloody Mary will work. According to the damage particles...

15+2, 19+2, 23+3, 25+3, 28+4...

Hearts & Bloody Mary work.

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/720013099712774185/runictraitbottommost.PNG)
In this image, Runic is at the bottom of the list, besides the Sharp Modifier. Damage particle shows...

9+1 x11...

Hearts & Bloody Mary do not work.

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/720013236237369404/runictraitmiddlemost.PNG)
In this image, Runic is somewhat in the middle but with Bloody Mary above Runic while Hearts is below Runic. Damage particle shows...

15+2 x7...

Hearts worked but Bloody Mary did not.

=====

I've never seen this before where the trait order matters. If one were to Emboss Runic... that would put it at the bottom of the list.

I kinda wonder if this could break other traits from other mods? Testing out Cold-Blood which on the list it is under Runic...

14+2 with mob at Full Health, otherwise 9+1.

Testing with Cold-Blooded which is now above Runic...

9+1 with mob at Full Health, otherwise 9+1.

So this actually happens with a Vanilla Tinker's Trait. I removed Natura, ActuallyAdditions & PlusTiC/xXx_MoreToolMats_xXx before performing the test and got the same results.

**Comment by phantamanta44** [comment]
I think you should be able to just:
* give your trait a lower priority so that it takes effect after other damage-modifying traits
* use `newDamage` to account for modified damage so as to not ignore other damage-modifying traits

**Comment by Z-Tunic** [comment]
This issue still occurs in v3.3.3 of Advent of Ascension.

**Comment by Tslat** [comment]
This issue is unlikely to be resolved at all without completely changing the trait.
