### ISSUE TITLE
Combining 2 of the same Vulcane in crafting table still doesn't repair them

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1606]
Don't know if intended, but this repairing method appears to still not work with Vulcanes.
![image](https://user-images.githubusercontent.com/38159897/83953370-cf4cd800-a7f4-11ea-9ca6-7e02d1e15881.png)
This also includes the 3x3 crafting table.

It appears all the other weapon types work with it now, but Vulcanes are the one exception.

**Comment by Tslat** [comment]
Fixed in 3.3.1
