### ISSUE TITLE
Startup Crash when loading AoA with IC2

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#1607]
**Mod Version**
3.3

**Describe the bug**
Game crashes on startup when initializing compat recipes with IC2.

**To Reproduce**
1) Create a modpack with AoA 3.3 and IC2.
2) Attempt to start the game.

**Expected behavior**
Game starting with the new compat recipes loaded.
Dusts also only seem to try and load with IC2, it would be nice to have them available for other macerator-like machines like TE's Pulverizer or IE's Crusher.

[bootcrash.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4741130/bootcrash.txt)

**Comment by Tslat** [comment]
Fixed in 3.3.1
