### ISSUE TITLE
The position of the skills icons will always go downwards no matter what position I have the resources display on

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1608]
**Mod Version**
3.3

**Describe the bug**
So I have my resources display set to the lower right corner, but no matter where I have the resources display at, the skill icons would always go downwards a bit making it look awkward.

**To Reproduce**
1. Use the config to change the position of the resources display.
2. Toggle the skills icons and then toggle the resources display.
3. Watch the icons go downwards.

**Expected behavior**
It should only go downwards when you have the resources display to the top right.

**Screenshots**
![2020-06-06_18 08 13](https://user-images.githubusercontent.com/58011699/83956213-15b82c00-a821-11ea-9d9a-91d2a85e2d68.png)

![2020-06-06_18 08 24](https://user-images.githubusercontent.com/58011699/83956216-1a7ce000-a821-11ea-8e81-eb546d26f4bd.png)

**Comment by Tslat** [comment]
Fixed in 3.3.1
