### ISSUE TITLE
[1.12.2] Crash with IC2 in latest AoA update

### ISSUE THREAD

**Issue by spooky-sooshi** [Tslat/Advent-Of-Ascension#1610]
**Mod Version**
3.3

**Describe the bug**
Crash on startup with IndustrialCraft 2 (2.8.170)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install AoA and IC2
2. Launch game
3. Crash

**Expected behavior**
Game would startup normally, with no issues.

**Screenshots**
Crash Report:
https://pastebin.com/kQhnQ42W

**Mod List**
AoA3-3.3
industrialcraft-2-2.8.170-ex112
OptiFine-1.12.2_HD_U_F4

**Comment by Tslat** [comment]
Known bug and fixed in 3.3.1

**Comment by DarianLStephens** [comment]
There's a different error when attempting to use the IC2 integration with IC2Classic.
Unless that was fixed as well, in which case I apologize for wasting your time.

The error that comes with IC2Classic is: https://pastebin.com/HXaiRcuz

**Comment by Tslat** [comment]
IC2 Classic is an entirely different mod for mod compat. The fact that they use the same mod ID is stupid.

Disable IC2 compat if you're using classic

**Comment by DarianLStephens** [comment]
Is there any chance of IC2 Classic compatibility in the future, then?

**Comment by Tslat** [comment]
Feel free to make a suggestion for it
