### ISSUE TITLE
Little Bam's sounds should be quieter

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1611]
**Describe/name the existing feature this suggestion relates to**
Little Bam

**Describe the change or feature you think would be good to see**
Little Bams use the vanilla Bat's sounds and are quite loud IMO. Vanilla bats seem to set a sound volume of 0.1; Little Bams could be a bit louder than that (since they're not ambient mobs), but still quieter than they are currently.

**Comment by Tslat** [comment]
Done in 3.3.1
