### ISSUE TITLE
Shadows below the AoA mobs are really small

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1612]
**Mod Version**
3.3

**Describe the bug**
Currently, shadows for all the AoA mobs are a small tiny size. Their size should be based on how large the mob is.

**Expected behavior**
The shadows below each of the mobs should vary by size depending on the size of the mob itself.

**Screenshots**
![2020-06-07_03 11 04](https://user-images.githubusercontent.com/58011699/83963955-2b544280-a86f-11ea-9683-2370414bfa8e.png)

![2020-06-07_03 11 11](https://user-images.githubusercontent.com/58011699/83963961-314a2380-a86f-11ea-9115-c31927690076.png)

![2020-06-07_03 12 39](https://user-images.githubusercontent.com/58011699/83963971-3dce7c00-a86f-11ea-9abf-2f34b478ff92.png)

**Comment by Tslat** [comment]
They actually are.

They're based on the entity's hitbox width, and are direction proportional.
