### ISSUE TITLE
Update the screen elements guide

### ISSUE THREAD

**Issue by VBGaming** [Tslat/Advent-Of-Ascension#1615]
**Describe/name the existing feature this suggestion relates to**
The screen elements guide is outdated

**Describe the change or feature you think would be good to see**
Remove the part that says augury makes you have more creation as augury was disabled, and add an explanation to soul power cause it still says it's unused. Also the last part of the soul scurry mentions augury training

**Add any alternative implementations you think might work**
I guess you can keep the augury if it's still true and just impossible idk

**Include any additional background information**
idk if this has been said already but probably, just putting this here just in case

**Comment by Tslat** [comment]
Done in 3.3.1
