### ISSUE TITLE
Few problems still persist despite the changelog saying they're fixed

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1619]
**Mod Version**
3.3.1 

**Screenshots**
Emberstone Pickaxe doesn't give experience when autosmelting.
![2020-06-07_15 13 34](https://user-images.githubusercontent.com/58011699/83979158-e7465980-a8d1-11ea-8c8d-c560c81f2601.png)

Crystallite still has Crystallite Ore's aspects.
![2020-06-07_15 13 46](https://user-images.githubusercontent.com/58011699/83979199-2bd1f500-a8d2-11ea-8ebf-2563aa303411.png)

Aspects are still missing from Crystallite Ore, Blue Daylooms, and Pink Daylooms. 
![2020-06-07_15 13 59](https://user-images.githubusercontent.com/58011699/83979215-46a46980-a8d2-11ea-9eb0-597b9b23f318.png)

**Comment by Tslat** [comment]
You'll need to reset your third-party mod config to get the new aspects

Try the smelt xp thing without other mods, let me know if it still persists..
It was working for me in testing, but I have a feeling there may be a mod or two removing xp from smelting to use it in its own smelting systems or something else
