### ISSUE TITLE
Egg names thing (Don't know how to call it)

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#162]
Pretty much for boss mobs do this.

Spawn (BOSS) Hydrolisk

Spawn (BOSS) Corallus

You get it.

I think this would make it easier for new player to see the bosses for the first time.

Also I feel like different eggs can work If you just want to fight 1 of the multi boss fights.
Like this.

Spawn (BOSS) Kajaros

Spawn (BOSS) Primordial Five

and

Spawn (BOSS) Red Guardians

Spawn (BOSS) Four Guardians

**Comment by Immortallis1** [comment]
those are called spawn eggs lol

**Comment by Sagisolar** [comment]
Yeah but with tags, diginushing the bosses would be easier.

**Comment by Tslat** [comment]
Not feasible with vanilla spawn eggs
