### ISSUE TITLE
IC2 Classic Compatibility

### ISSUE THREAD

**Issue by DarianLStephens** [Tslat/Advent-Of-Ascension#1620]
I would like to see compatibility with IC2 Classic.
Personally, I prefer it over the current original IC2, as this is based more on what I enjoyed back in IC1.

You will likely be able to use most of the features from the recently-added original IC2 compatibility, beyond adapting to IC2 Classic's API and the slight differences in ore processing and available armor.

**Comment by DarianLStephens** [comment]
I guess this mod had IC2 compatibility at some point, processing or something, but it didn't work with Classic?

**Comment by Tslat** [comment]
IC2 classic never moved past 1.12
I couldn't implement compatibility with it now anyway

**Comment by DarianLStephens** [comment]
Aww, oh well.
