### ISSUE TITLE
Friendly creepers take damage from their own explosion right before disappearing

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1623]
**Mod Version**
3.3.1

**Describe the bug**
Friendly creepers take damage from their own explosion before disappearing; i.e. they show a brief hurt/death animation, the hurt/death sound plays and the "Creeper hurts/dies" subtitle shows up if subtitles are enabled. In comparison, vanilla and Creeponia creepers do not take damage or die while exploding.

**To Reproduce**
1. Spawn a friendly creeper
2. Spawn a hostile mob or blow it up with flint and steel

**Screenshots**
![image](https://user-images.githubusercontent.com/12868968/84001371-4bd9d680-a91b-11ea-9e16-5093bb0f702b.png)

**Comment by Tslat** [comment]
Nvm found a way

Fixed in 3.3.2
