### ISSUE TITLE
Attack will reduce you to 20 hp

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1629]
**Mod Version**
3.3.1

**Describe the bug**
When you have more than 20 health
Make a melee attack
Health will be reduced to 20

**Screenshots**
![3](https://user-images.githubusercontent.com/59332746/84105946-5fd12580-aa4c-11ea-8be4-257d0180948a.png)
![4](https://user-images.githubusercontent.com/59332746/84105949-619ae900-aa4c-11ea-97e5-fa28a173830a.png)

**Comment by Tslat** [comment]
Unable to replicate.

Doesn't seem like something AoA would do either - try it without any other mods

**Comment by Wind-Xing** [comment]
> 
> 
> Unable to replicate.
> 
> Doesn't seem like something AoA would do either - try it without any other mods

Resolved, sorry, not an AOA issue
