### ISSUE TITLE
Skill Crystals

### ISSUE THREAD

**Issue by Armakeen** [Tslat/Advent-Of-Ascension#163]
Skill Crystals should be entirely removed,
or they shouldn't give any experience at all after a certain level (maybe level 75 - 80 ?)

**Comment by DiamondWalker** [comment]
I haven't played in a long time, but I clearly remember hauling taking ages to train. Foraging as a whole is the problem, not skill crystals themselves. Besides, even if you're using skill crystals, you need to train hauling, train another skill to level 15, and use hundreds of skill crystals to get to 100.

**Comment by Tslat** [comment]
Yeah probably won't happen, skill crystals have a valid place in the mod
