### ISSUE TITLE
Missing recipes for current IC2 integration

### ISSUE THREAD

**Issue by zero-breaker** [Tslat/Advent-Of-Ascension#1631]
Currently, there are no ways to craft purified crushed ores or plates of AoA metals, nor are there Thermal Centrifuge and Ore Washing Plant recipes for crushed ores.
Additionally, dusts for gemstones and crystals are missing, though it's a low priority as they have no use except when combined with other mods.

The following recipes would need to be added:
-Crafting Table
1 Ingot + Forge Hammer -> 1 Plate
-Block Cutting Machine
1 Block -> 9 Plates
-Metal Former
1 Ingot -> 1 Plate
-Macerator
1 Crushed Ore/Purified Crushed Ore -> 1 Metal Dust
-Thermal Centrifuge
1 Crushed Ore -> 1 Metal Dust + 1 Tiny Metal Dust (may be different from the metal the ore contains) + 1 Stone Dust
1 Purified Crushed Ore -> 1 Metal Dust + 1 Tiny Metal Dust (same as above)
-Ore Washing Plant
1 Crushed Ore -> 1 Purified Crushed Ore + 2 Tiny Metal Dust (same metal as ore) + 1 Stone Dust

**Comment by Tslat** [comment]
Done most of these in the next version.

Some of them aren't actually things in base IC2 though
