### ISSUE TITLE
Advent of Ascensions Main theme!!!

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#1639]
**Describe the new feature you think would be good to add**
I would like this song I created to be the main theme of Advent of Ascension!

[Caverns.zip](https://github.com/Tslat/Advent-Of-Ascension/files/4767117/Caverns.zip)

**Comment by Tslat** [comment]
I'm not sure main themes are a thing..

What about a record?

**Comment by mrcakesamurai** [comment]
> I'm not sure main themes are a thing..
> 
> What about a record?

Wait, what?

**Comment by Tslat** [comment]
A record? 

https://minecraft.gamepedia.com/Music_Disc

**Comment by mrcakesamurai** [comment]
> A record?
> 
> https://minecraft.gamepedia.com/Music_Disc

Oh! Okay, that's fine too!

**Comment by Infernikko** [comment]
A main theme could be cool as a title screen music or something

**Comment by Tslat** [comment]
Done in 3.3.2
