### ISSUE TITLE
Change ore minimum Y levels to 0

### ISSUE THREAD

**Issue by Lithobraker** [Tslat/Advent-Of-Ascension#1640]
At present, several ore types have a minimum Y level implemented, which varies wildly from ore to ore.

To be honest, I don't really understand why this is. A normal player would never expect ores to have a minimum Y level in the overworld, since this behavior is not present in vanilla.
While this is, of course, not vanilla, I've also never heard of this kind of thing happening in any other mod- and it's not like the game tells you this is the case. (I'm sure another mod has done this, but the point is that it's very rare.)
I know it might make low Y levels a bit crowded with ore, but since the mod adds so many different ore types anyway- all of which are important- that seems better than them being weirdly spread out like this.

A player should not have to install JER or use the wiki just to find overworld ores. It's not like this information can be inferred from gameplay- ore veins can stretch above and below the Y limits, so players who don't know how ore spawning works could easily be misled into believing there is no minimum Y level for these ores.

At the very least, I think adding a minimum Y level option to the ore config would be wise.

**Comment by Tslat** [comment]
With regards to not having to use the wiki - how do people playing vanilla know they have to go down to a certain Y level to find vanilla ores?

**Comment by Lithobraker** [comment]
> 
> 
> With regards to not having to use the wiki - how do people playing vanilla know they have to go down to a certain Y level to find vanilla ores?

Since, in vanilla Minecraft, you can't find diamonds high up. A player will never find diamonds embedded in a mountainside, and experience can easily tell you they're far down.
It's not going to tell you diamonds don't spawn above 15, but it will tell you that they can't be found high up.
This kind of thing does take time to learn, but it's simpler than ores generating only in a thin stretch,
since that's a lot harder to naturally intuit, especially with the veins stretching above and below the limits.

With vanilla, you might think diamonds can spawn a bit above 15 because of the veins, but most people will still be able to infer that the deeper you go, the greater your riches.
While this isn't the most efficient level, if you strip-mine at 5 you can still gather a ton of resources, so it's close enough.

**Comment by Tslat** [comment]
Yes but how do you know you can't find diamonds high up?

**Comment by Lithobraker** [comment]
> 
> 
> Yes but how do you know you can't find diamonds high up?

Because you never, ever do. It's simple. This kind of knowledge takes time to figure out and a bunch of experience, but if you never find something in a particular place, why would you keep searching there?

Of course there's going to be people who don't get it so easily. You can't really account for that. But if a person never, ever finds diamonds in the mountains, doesn't it make sense to try looking deeper? Just, logically.

**Comment by Tslat** [comment]
Just like you'll never ever see limonite ore below its Y level.
Just takes some time to learn that....

**Comment by Lithobraker** [comment]
But, due to ore veins, you kind of can find it there. Just not commonly.
This gives more of an impression that it's ludicrously rare, rather than an impression that you can't find it this far down. People who don't know how ore gen works won't understand that the vein is simply started at a certain level- and that by digging too deeply you'll barely find any of it.
The fact that you do still find ore there is misleading, since most people won't have other experiences to compare it to where this ore doesn't generate too far down- for those people, it makes far more sense to infer that it's really rare.

**Comment by Tslat** [comment]
It follows the same generation rules as any other vanilla ore, there'll be bleedover that happens.

You'll see diamond a bit above its Y level as well, it just happens.

So if someone sees a diamond at 2-3 above its Y level, wouldn't they then start mining everywhere at that Y level, but not really finding any, causing them to think it's super rare?

**Comment by Lithobraker** [comment]
Yeah- I think I'm going about this the wrong way. You're right in that sense, but I still think this system makes for a poor gameplay experience.

People who play other mods and vanilla Minecraft are going to expect things to work a certain way. It's unlikely that if you install AoA that you'd be inexperienced with vanilla- and with how difficult it is, that's clearly not the kind of player you expect to play it.

Having to make a bunch of separate mines at a wildly disparate range of Y levels is not something other mods typically expect the player to do- even grindy ones don't ask that of you. This means you have to do tons, tons more mining- and a lot of the time you're still just mining up stone blocks, since these Y levels are very, very sparsely populated with useful ores apart from iron and coal.
It's to the point that I don't think that many people will play beyond the first few hours of AoA, assuming that the whole game is just weirdly designed like this.

At the very least, this should be configurable.

**Comment by Tslat** [comment]
Fair enough :)

**Comment by Lithobraker** [comment]
Okay! Again, really sorry for whining. I only post all this because I really, really want AoA to improve.
You're doing a good job so far, as far as I can tell.
