### ISSUE TITLE
Two Skele-elder spawned when it is wave 7 during the skeletal army boss fight

### ISSUE THREAD

**Issue by Lhz271** [Tslat/Advent-Of-Ascension#1644]
**Mod Version**
3.3.1

**Describe the bug**
There is two Skele-elder spawned at wave 7, and only one will spawn next wave and other do nothing when you kill it.

**To Reproduce**
1.start the skeletal army fight
2.make it to the wave 7.
3.there are two skele-elder
**Expected behavior**
there should be only one Skele-elder spawns at wave 7.

**Comment by Tslat** [comment]
Fixed in next version
