### ISSUE TITLE
Day and night events should affect the appearance of the sky

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1645]
The events that happen at day and night are some of the most coolest things in the mod, but it can sometimes be hard to tell what event is going on especially if you AFK or ignore the chat messages. I also think it would be more interesting for the sky to change in appearance depending on which event is active to add a sense of creepiness or a sort of interesting mechanic.

If you ever played Terraria, the events in that game would affect the appearance of the sky in a variety of ways, so I was thinking of making a suggestion based on that here. Full Moon would be the only one that's unchanged because that's technically the only event that affects the actual appearance of the moon.

For these screenshots I used both Dynamic Surroundings and GoG Skybox. (As well as resource packs)

## Bloodhunt
![2020-06-12_19 08 29](https://user-images.githubusercontent.com/58011699/84555289-bc00a780-ace1-11ea-80bf-2da0be3ba4a0.png)
The moon and fog will change to a blood red color, phases will still be the same.
## Soul Scurry
![2020-06-12_19 06 11](https://user-images.githubusercontent.com/58011699/84555325-e8b4bf00-ace1-11ea-8014-33147db1eea3.png)
Same as Bloodhunt but with bright blue colors.
## Lunar Invasion
![2020-06-12_19 31 19](https://user-images.githubusercontent.com/58011699/84555622-63caa500-ace3-11ea-8dc8-2a0b59821db6.png)
The moon becomes purple and gains a ring. The fog is also purple and smaller planets are scattered around the sky.
## Death Day
![2020-06-12_18 57 39](https://user-images.githubusercontent.com/58011699/84555359-17cb3080-ace2-11ea-9654-57cdcbd864bf.png)
The sun and fog will change to a blood red color similar to Bloodhunt.
## Creep Day
![2020-06-12_18 51 25](https://user-images.githubusercontent.com/58011699/84555385-36312c00-ace2-11ea-8b0e-114d68e00242.png)
Same as Death Day but with green colors.
## Big Day
![2020-06-12_18 23 01](https://user-images.githubusercontent.com/58011699/84555407-5cef6280-ace2-11ea-86d1-1e7f634e5f96.png)
The sun becomes massive in size.

**Comment by TimeEarl** [comment]
That looks awesome, it'd just be nice if we could have special fish to catch during these events (I like hauling too much).
