### ISSUE TITLE
Auto-smelting Iron Ore by mining it with an Emberstone Pickaxe doesn't give xp

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1646]
I've noticed all other smelted ores give xp now when mined with an Emberstone Pickaxe so I assume it should also be the case for iron?

**Comment by Tslat** [comment]
Just worked out why this is happening.

It turns out that vanilla XP orbs don't support non-integer xp amounts for some reason...

So yeah, blame vanilla lol
