### ISSUE TITLE
Retextures for numerous blocks, and several items

### ISSUE THREAD

**Issue by Lithobraker** [Tslat/Advent-Of-Ascension#1648]
**Describe/name the existing feature this suggestion relates to**
I think a lot of people are quite unsatisfied with the textures present in AoA. Lots of them are vanilla recolors- and sometimes terrible, eye-searing ones at that.
I have a wide variety of textures I've worked on-mostly a long while ago- which might be better than the originals.
Any combination of these files can be used, and they may be tweaked and reworked as you guys see fit.
Currently, I have retextures for blocks I found lacking in the following dimensions:
The Abyss
Precasia (Also includes full overhauls for all the trees, including Cycade, and a new tall grass texture)
Lunalus
Gardencia
The Haven
Creeponia
Mysterium

It also has some palette edits of Deeplands foliage, making them very, very dark brownish rather than pure black and gray.

All three types of Precasian tree have also been totally retextured- new vine textures and underlying wood for Stranglewood which are not edits of any vanilla tree, based partially on the Baobab tree and the pinks/limes of Terraria's jungle trees, new textures for Lucalus trees inspired by birch, but also Iroko trees, and finally Cycade trees, which were based on Cecropia.

As for the item retextures, I've made some for the Golder Bomber, Golden Fury, and Gold Bringer- and the Golden Upgrade Kit they're made with. Their palettes have been updated to look less like someone spilled butter all over them, and more hue-shifted as to be more appealing. This kind of hueshifting towards an orangeish tint is common in pixel art of gold.

All gold items aside from the Golden Upgrade Kit have been reanimated with sparkles that properly grow and shrink rather than being simple layers that increase/decrease in transparency. This animation is more similar to the way that other professional pixel art does the same effect- as you might see in, for example, Super Mario World's Vanilla Dome overworld and cave backgrounds.

For more consistency with the Gold Bringer, the Doom Bringer also got some tweaks that give it more vibrant blue parts and a cleaner, less blurry look. Its blacks are now also veeery slightly blue-tinted.

The Minigun, Megagun, and Predigun received total, 100% resprites(albeit without any animation like Cruuk suggested). I have included versions which are the same size as the original sprites in the resource pack, as well as a file containing larger ones with longer barrels, which cannot be used ingame.
Terrain/Foliage:
[AoA Terrain Retextures.zip](https://github.com/Tslat/Advent-Of-Ascension/files/4778429/AoA.Terrain.Retextures.zip)

Item Resprites:
[AoA Item Resprites.zip](https://github.com/Tslat/Advent-Of-Ascension/files/4778427/AoA.Item.Resprites.zip)

Larger Minigun+upgrades sprite variants
[AoA Larger Minigun and Upgrades.zip](https://github.com/Tslat/Advent-Of-Ascension/files/4778428/AoA.Larger.Minigun.and.Upgrades.zip)

Brighter Vines on Stranglewood Logs, new Precasian Planks (Log top/bottom texture unchanged)
[AoA New Stranglewood + Precasia Planks.zip](https://github.com/Tslat/Advent-Of-Ascension/files/4802412/AoA.New.Stranglewood.%2B.Precasia.Planks.zip)

**Comment by Lithobraker** [comment]
Aside from the larger Minigun+upgrades, these are just resource packs, so you can install them and use them.
Github isn't exactly the most ideal place to host downloads, but there's no AoA forum, so...

**Comment by TimeEarl** [comment]
I made a texture for Barathos Hellstone as the current texture is just a red reskin of soul sand. 
![20180225152913!Barathos_Hellstone (2) (2)](https://user-images.githubusercontent.com/66849839/84710088-86ea9400-af31-11ea-8482-21d7508a2e92.png)
![20180225152913!Barathos_Hellstone (2) (1)](https://user-images.githubusercontent.com/66849839/84710090-86ea9400-af31-11ea-9d71-f983c7f176b2.png)
![20180225152913!Barathos_Hellstone (2) (4)](https://user-images.githubusercontent.com/66849839/84710091-87832a80-af31-11ea-99e9-6ad7e747d701.png)
![20180225152913!Barathos_Hellstone (2) (3)](https://user-images.githubusercontent.com/66849839/84710092-87832a80-af31-11ea-964c-b45cd2328b7c.png)

**Comment by Lithobraker** [comment]
Added my version of the Stranglewood log with brighter vines, and the newly-redone Precasian planks, to the original post.
