### ISSUE TITLE
Have Mechbot drop 1 Mecha Gear when killed (when it's fully added)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#165]
**Describe/name the existing feature this suggestion relates to**
Mechbot and Mecha Gear

**Describe the change or feature you think would be good to see**
I know Mechbot will eventually drop new weapons/other stuff made for him, but I think it would be cool if it **also dropped 1 Mecha Gear 100% of the time**, in a similar way Smash can drop other stuff and Cotton Candor drops all those BLOCKS.
I just always liked it when bosses could drop something else besides just weapons/armor, it gives more of a reason to kill them besides just weapons/armor/statues (yay looting system). It wouldn't be the absolute best way to get Mecha Gears (though it depends on how hard it will be to obtain Gold Spring), but it would be an alternative to buying them from the Professor and an extra reward for slaying Mechbot in general.

**Comment by Tslat** [comment]
This suggestion doesn't really work anymore
