### ISSUE TITLE
life lamp doesn't work.

### ISSUE THREAD

**Issue by Sombian** [Tslat/Advent-Of-Ascension#1650]
**Mod Version**
 3.3.1

**Describe the bug**
regardless lamp being powered it doesn't heal nearby passive entities,
despite the descriptions says it should.

**To Reproduce**
Steps to reproduce the behaviour:
1. craft an life lamp.
2. place the life lamp.
3. power the life lamp.
4. get nearby.

**Expected behavior**
should heal passive entities and player within its effect radius upon powered.

**Comment by Tslat** [comment]
Life Lamps don't heal entities anymore, haven't for a while
