### ISSUE TITLE
AoA Shield addon mod

### ISSUE THREAD

**Issue by TimeEarl** [Tslat/Advent-Of-Ascension#1651]
Addon to AoA that plans to rework vanilla shields and add shields to AoA. 
See doc below for more info and a summary of what I wish to accomplish in making this mod.

https://docs.google.com/document/d/18HEb-a107nMh988dw4XQa_tzz53IAs81DJvpfiHMynQ/edit?usp=sharing

**Comment by TimeEarl** [comment]
Serious feedback/suggestions are welcome as long as they aren't vague and pertain to the base idea of the mod.

**Comment by Tslat** [comment]
This github is for suggestions/issues with AoA itself. Addons need to stand on their own & go on curseforge when ready
