### ISSUE TITLE
Tinker’s Armor in Vox Ponds

### ISSUE THREAD

**Issue by Diedntgo** [Tslat/Advent-Of-Ascension#1652]
**Describe the new feature you think would be good to add**
A modifier for helmets using the face mask. It would have the same effect as the face mask/hazmat armor, allowing you to wear Tinker’s Armor in the Vox Ponds.

**Comment by TimeEarl** [comment]
maybe a filter or something you could make with charcoal although tinkerers armory comp hasn't been set up yet (base tinkerers modifiers from aoa havent even been set up yet) its a great idea
