### ISSUE TITLE
Horon's random explosions can trigger even after death

### ISSUE THREAD

**Issue by LokiY2K** [Tslat/Advent-Of-Ascension#1656]
Horon's random explosions can trigger even after the boss dies, destroying most if not all of his drops. This is a problem when trying to farm certain items (like Magic Mending Dust), as it will, most of the time, destroy the items the player is looking for.

**AoA Version:** 3.3.1
**Minecraft Version:** 1.12.2
**Forge Version:** 14.23.5.2847

**Comment by EnderdragonLord** [comment]
Seen this happening with C.R.E.E.P. and Baroness too due to them causing random explosions from their attacks, I don't know how they are right now though last time I had that happen was 3.2.7.

**Comment by Tslat** [comment]
Half-fixed this in 3.3.2.
