### ISSUE TITLE
Archerguns and all the bullet damage weapons still require ammo in creative

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1658]
**Mod Version**
3.3.2

**Describe the bug**
Even in creative, Archerguns, guns, shotguns, snipers, and cannons require ammo to be in the inventory. They don't consume the ammo, but just not having the ammo in the inventory makes it so they cannot be fired.

**To Reproduce**
Fire any gun of these weapon types in creative without the ammo.

**Expected behavior**
Ammo not mattering in creative. I know some methods were changed to fix something with Curse of Greed, but it will be quite annoying having to have the ammo in creative.

**Comment by Tslat** [comment]
Fixed in next version
