### ISSUE TITLE
Trees in the shyrelands dimension can generate in the archways.

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#166]
**Mod Version**
AoA3-Snapshot 8

**Describe the bug**
In the shyrelands dimension, trees can generate on the brick part of the archways.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go the the shyrelands dimension.
2. Find a tree generating on a brick part of the archway.

**Expected behavior**
Trees should only be generating in the shyre grass parts of the shyrelands dimension.

**Comment by Tslat** [comment]
Fixed in snapshot 9
