### ISSUE TITLE
Mobs should make the default footstep sounds instead of pig's

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#1660]
Relates to #1617 

**Describe the change or feature you think would be good to see**
Most ground-based hostile mobs (including ghosts and Crystevia constructs) use pig footstep sounds for some reason, making it obvious when you're about to get attacked. They should use the default block footsteps instead or other custom ones.

**Comment by Tslat** [comment]
Pig is the default footstep for entities lol

**Comment by Sonicwave** [comment]
By default I meant the sounds that players and mobs like creepers and villagers make

**Comment by Tslat** [comment]
Done in next version
