### ISSUE TITLE
Skydriver Bow should fire lingering particles rather than acid blocks

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1662]
I always found it annoying how every time you fire it, blocks form similar to snow so you'd have to clean it up right after. I think it would be more fitting for it to use lingering particles instead, the same ones used by Lingering Potions and the Toxic modifier used by Mystite.

**Comment by Tslat** [comment]
Those blocks to decay on their own btw

**Comment by EnderdragonLord** [comment]
Dang, wish I would've found out they decayed sooner. I still think lingering particles would look better though.
