### ISSUE TITLE
'Should be a mechanic' advancement

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1667]
**Mod Version**
3.3.1

**Describe the bug**
Only 5 are needed to complete the advancement
But there are actually 6

**Screenshots**
![1](https://user-images.githubusercontent.com/59332746/85128236-76a12480-b263-11ea-8195-770a74ff9302.png)
![2](https://user-images.githubusercontent.com/59332746/85128238-7739bb00-b263-11ea-85e7-ebb94f9ff664.png)

**Comment by Wind-Xing** [comment]
Wait a min,Mod Version is 3.3.2

**Comment by Tslat** [comment]
Fixed in next version
