### ISSUE TITLE
Torn Cloth Fletching unobtainable

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#1669]
**Mod Version**
3.3.2

**Describe the bug**
Each Torn Cloth only counts for 0.01 material when attempting to build a Torn Cloth Fletching via the Tinker's Construct Part Builder. Tested with no other mods present.

**To Reproduce**
Boot up a world with the latest AoA and TiCon, set up a part builder + fletching stencil, and throw some Torn Cloth in. Even with the full two stacks, you only reach 0.89 material and are unable to build the fletching.

**Expected behavior**
Being able to build the fletching.

**Screenshots**
![cloth1](https://user-images.githubusercontent.com/28516513/85129351-ca6e2800-b1e7-11ea-8ddc-312093efe657.PNG)
![cloth2](https://user-images.githubusercontent.com/28516513/85129358-ccd08200-b1e7-11ea-9311-20a8b318358a.PNG)

**Comment by Tslat** [comment]
Fixed in next version.
