### ISSUE TITLE
Portals teleporting weirdly

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#167]
**Mod Version**
AoA3-Snapshot 8

**Describe the bug**
Portals to and from dimensions seem to be behaving weirdly. Upon entering a dimension, some of the time you are placed in the portal frame correctly, while other times you spawn in the side of the portal, causing suffocation damage.

Upon exiting the portal, you are sometimes spawned in the ground one block below the portal.

Unsure how common these occurrences are.

**To Reproduce**
Steps to reproduce the behaviour (generally) - unsure how to reproduce specific results:
1. Enter/exit a dimension (more noticeable in survival mode).
2. Notice what happens.

**Expected behavior**
You are always placed in the portal correctly, no matter if you enter or exit a dimension.

**Comment by Tslat** [comment]
Fixed in snapshot 9
