### ISSUE TITLE
Resprited Seeds

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1670]
I'm surprised they were never reworked yet, but they're such a HUGE eyesore to look at that I decided to give it a go at respriting them. I've also made them more distinct from one another to prevent the really similar looking colors from confusing players.

**Update:** Made an alternate version that more closely resembles how they were originally colored and it also uses mostly only one color instead of switching between two alternate colors, some of the colors still remain changed to prevent confusion. Putting that here in case that's preferred over the other proposed one.

[Seeds.zip](https://github.com/Tslat/Advent-Of-Ascension/files/4805789/Seeds.zip)

[Alt-Seeds.zip](https://github.com/Tslat/Advent-Of-Ascension/files/4807326/Alt-Seeds.zip)

Before and After:
![2020-06-19_11 25 44](https://user-images.githubusercontent.com/58011699/85157330-f4900c00-b220-11ea-8c2a-a2271df01cab.png)

Alternate:
![2020-06-19_22 48 59](https://user-images.githubusercontent.com/58011699/85190579-47001580-b27f-11ea-9096-2a72c382e9c5.png)

**Comment by Tslat** [comment]
Done in next version. Thanks for contributing
