### ISSUE TITLE
Foraging

### ISSUE THREAD

**Issue by SoulAres** [Tslat/Advent-Of-Ascension#1672]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Foraging
**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
Changed to Prospecting
**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
Not really
**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Not that I know of

**Comment by Tslat** [comment]
To clarify - you're suggesting to change the name of Foraging to Prospecting?

**Comment by jcfinal** [comment]
Yes, because it's more accurate. But it is just a suggestion.
