### ISSUE TITLE
Fungal armor's full set effect activating without wearing the full set, along with the full set effect being inconsistent in general

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1689]
**Mod Version**
3.3.2

**Describe the bug**
It appears that Fungal armor's full set effect can activate regardless of whether you're wearing all 4 pieces not. I've seen it happen while wearing 1 piece, wearing 3 pieces, etc. I know it's not just me getting hit by mobs other than the target mob, the ones around me get Poison I instead of Poison II.

Also, even when wearing the full set, the AoE poison doesn't always proc when the per piece Poison does. At least, I assume they're supposed to happen at the same time with the full set equipped.

**To Reproduce**
Get hit by a melee mob with other mobs nearby.

**Expected behavior**
The full set only activating when wearing all 4 pieces (or the special helmet thing).

And for the AoE poison being consistent, I imagine it should activate at the same time as the per piece Poison. It would otherwise be pretty mediocre and trivial, along with the ingame description being misleading.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/85196244-b2e97a80-b28d-11ea-8c20-32f2a80e148d.png)

**Comment by Tslat** [comment]
Yeah yeah.. stupid fungal is really messing with me
Fixed.. again.. ffs

**Comment by Cruuk** [comment]
This set is cursed
