### ISSUE TITLE
Some English file mistakes

### ISSUE THREAD

**Issue by Kagaribi172** [Tslat/Advent-Of-Ascension#1690]
**Mod Version**
3.3.2

**Describe the bug**
I found some mistakes in the lang file.

(1) en_us.lang

> message.feedback.item.labriconRealmstone.create=Roses are red, violets are blue. I know you tried, but no Labricon for you.

-Labricon has been removed. So you should remove it.

(2) guides/en_us/lunar_invasion.txt

> you may even find a way to get to Lunalus,

-The way to get to Lunalus has changed. So you should remove it.

**Comment by EatingSilencer** [comment]
Pretty sure the Recreation Station one is a joke, Labricon never existed in any completed capacity in the mod.

**Comment by Tslat** [comment]
Fixed the second one in the next version
