### ISSUE TITLE
Music discs for Firch's boss music

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1691]
With the addition of two new music discs obtained in challenging ways I figured it would be a nice touch to add discs for boss music made by Firch as well. The discs would only drop by killing a boss with a certain method or under a specific condition. 
Some ideas include:
* **Coulrophobia** - Defeat Gyro outside Celeve
* **Mysterious March** - Have a Runic Guardian finish off Clunkhead
* **Irreversible Curse** - Defeat Baroness outside her arena
* **Extreme Power** - Defeat C.R.E.E.P after having him kill 5 Creepirds with his explosive tubes (Being able to jam to this in my base would be amazing)
* **Sugary Situation** - Finish off Cotton Candor with a Wind Staff (When Push comes to Shove advancement)

I have some other ideas for bosses which don't have community-made music yet:
* Finish off Smash while at least 10 blocks in the air
* Defeat Corallus while underwater and your oxygen meter is empty
* Defeat Skeletron while at least 8 Skelemen are present within 10 blocks (Alternatively use the Spooky Scary Skeletons advancement)
* Defeat the Four Guardians, having killed the last guardian within 10 seconds of the first guardian's death
* Defeat Tyrosaur without taking any damage from his earthquakes (Not sure if Firch made the track used in 3.3)

**Comment by DiamondWalker** [comment]
What about the dimension music?

**Comment by Sweaty07** [comment]
Since there isn't any dimension music at the moment I didn't really consider them, but if they're implemented the discs for them could be obtained in a similar manner by completing challenges like the ones I described above

**Comment by Firch** [comment]
I really do not want boss music discs to be in game.
Music discs have their own style. Boss themes have different style from music discs, they sounds and feels differently.

**Comment by Firch** [comment]
Another variant, I can make music discs for each dimension, they will be in style of music discs and will feel like they are came from their dimension.

**Comment by EatingSilencer** [comment]
> 
> 
> I really do not want boss music discs to be in game.
> Music discs have their own style. Boss themes have different style from music discs, they sounds and feels differently.

I see what you mean, but how else are people supposed to be able to play boss music over and over again without a boss nearby?

**Comment by DiamondWalker** [comment]
> 
> 
> I really do not want boss music discs to be in game.
> Music discs have their own style. Boss themes have different style from music discs, they sounds and feels differently.

Maybe it can be music boxes or something like that? It'd be nice to hear the boss themes whenever you want.
