### ISSUE TITLE
In-game wiki?

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#170]
When you want to know something you have to look it up on the nevermine wiki, yet that takes time in which people can be attacked by a dangerous mob. Perhaps a book that you can craft will allow users to access the wiki and get around easily. This can be staged so when you enter a new dimension then you unlock a little information about it, and when you fight/kill a specific mob you learn a bit more. It will help towards the RPG like feel and also makes players feel like they are ascending.
I have no ideas for the crafting recipe, but perhaps you can use sapphire ingots or ancient rock to do it.

This idea is already in place with other mods like Hardcore Ender Expansion, and Tinker's Construct. This helps as both mods are quite large in comparison with others, but Nevermine is probably the largest I've ever seen.

**Comment by Sagisolar** [comment]
Wouldn't that be a bit crutch tho?

**Comment by Seishan123** [comment]
Isn't the entire wiki though, Nevermine is huge. The in-game wiki is more of a directional path than a crutch, but that's my opinion.

**Comment by Garr890354839** [comment]
> Wouldn't that be a bit crutch tho?

Not really. I would like to see a book that had all the content of the game in it.

**Comment by GuerreroCraft61** [comment]
The truth is a very good idea, ja that many people are not going to look at the wiki, and would be much more comfortable directly from the game

**Comment by Tslat** [comment]
Confirmed not happening
