### ISSUE TITLE
Config option for hunter mobs: hostile add.

### ISSUE THREAD

**Issue by NuggetKitten** [Tslat/Advent-Of-Ascension#1700]
**Describe the new feature you think would be good to add**
A option to make it scan for hostile monster types. To quickly make stuff hunter mobs and generate the config for them. 

**Add any alternative implementations you think might work**
Command /huntermobaoa all/passive/hostile/passiveagressive enable/disable

**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?
Hunter leveling takes a bit of time  when packs add new monsters.

**Comment by Tslat** [comment]
How would I even determine what detected mobs' hunter lvl and xp should be

**Comment by NuggetKitten** [comment]
Maybe include a minimum value for xp and hunter level.  from there if they need to balance they could find the generated config and change it. instead of having to find the id for all the monsters etc

**Comment by Tslat** [comment]
So you'd have to go in and manually configure each mob anyway?

**Comment by NuggetKitten** [comment]
> So you'd have to go in and manually configure each mob anyway?

the point is to find each mobs registered ID as that can be painful to do. it also would be a quick set up to make the hunter mobs. say if I wanted to make them all worth 5 xp, at hunter 1.  it would gen them all that way

**Comment by Tslat** [comment]
Sounds more like something for an addon

**Comment by NuggetKitten** [comment]
> Sounds more like something for an addon

 I mean, I suggested it thinking it could be  a viable config option? what makes it sound like an addon?

**Comment by Tslat** [comment]
It's a very, very specific niche functionality that doesn't really fit in the core mod

**Comment by NuggetKitten** [comment]
I don't think adding a config is worthy of a whole mod.  which is why I asked.

**Comment by Tslat** [comment]
Addon mods can do anything :) big or small
