### ISSUE TITLE
King Bambambam's little bams drop loot if unloaded

### ISSUE THREAD

**Issue by goreae** [Tslat/Advent-Of-Ascension#1701]
On version 3.3.2

Normally, King BamBamBam's little bam summons don't drop loot. However, if its chunk is unloaded then it changes into a naturally-spawned little bam and drops loot, including plentiful explosive idols. This can be done as easily as summoning a king, letting him spawn some bams, then returning to menu and rejoining the world. Sometimes works when just changing dimensions if you leave long enough for the chunks to unload. 

I first found this after a mishap caused me to have 30 kings roaming around the nether with an army of around a thousand little bams. After they killed me once, I went back and ran a killall command and found a sea of explosive idols from all the dead bams.

**Comment by Tslat** [comment]
Fixed in next version
