### ISSUE TITLE
Some of the dimension pictures in the Realmstone GUI need updating

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1705]
**Mod Version**
What version of the mod are you on?
3.3.2

**Describe the bug**
The Realmstone GUI has pictures of the mod's dimensions, some of which are now outdated. The list of ones that are notably outdated include:
-Lunalus - the grass blocks were retextured.
-Iromine - the Iro Log was retextured.

**To Reproduce**
Steps to reproduce the behaviour:
1. Hold a Blank Realmstone in your hand.
2. Use it to open the Realmstone GUI.
3. See error. You might have to drag the screen around to see all the dimension pictures.

**Expected behavior**
The pictures are updated.
**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/85914505-6e6d5a00-b80c-11ea-95f1-523e6a17034e.png)

![image](https://user-images.githubusercontent.com/44556728/85914508-788f5880-b80c-11ea-8fd4-24671182c1b7.png)

![image](https://user-images.githubusercontent.com/44556728/85914509-7deca300-b80c-11ea-860f-88073cb8d053.png)

**Comment by EatingSilencer** [comment]
All dimensions with tree changes might need their pictures updated: The Haven, Lelyetia, Greckon, Dustopia, The Shyrelands, Creeponia, Runandor, Precasia, Celeve, Lunalus, and Iromine. Not sure if the changes were significant enough to warrant an update. Also, the Abyss got new trees but its picture doesn't have any I think...

**Comment by Cruuk** [comment]
Shit we're gonna have to update the image on the wiki if it gets changed

**Comment by EatingSilencer** [comment]
Adding on the following:
1. Precasia - I think there are mob attribute icons in the image.
2. Haven - dimension gen change in 1.15.2.
3. Celeve - I think the blocks got a texture change.
4. The Nether - the vanilla nether got a texture change for lots of blocks.
