### ISSUE TITLE
Changing boss health with commands can cause the boss bar to glitch

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1707]
**Mod Version**
What version of the mod are you on?
3.3.2

**Describe the bug**
When you modify a boss' max health using commands, it can cause the boss bar to glitch up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pick a boss to spawn. Make sure the difficulty is on anything but Peaceful, and that the boss bar can be visible (so no F1).
2. Use this command to alter the boss' health: 
/summon aoa3:mechbot ~ ~1 ~ {Attributes:[{Name:generic.maxHealth, Base:1.0}]}

3. See error. A second boss bar will appear to the right of the first. If you change the GUI scale, more boss bars will appear to the right of the first.
Setting Base: 1.0 to Base: 2501.0 will cause the other boss bar to be cut in half.
**Expected behavior**
Only one boss bar is ever displayed.

**Comment by Tslat** [comment]
Fixed in next version
