### ISSUE TITLE
Elusive and Gyro boss bar textures

### ISSUE THREAD

**Issue by Merepock** [Tslat/Advent-Of-Ascension#1708]
A minor inconsistency I've seen since the first ever versions of Eternal Isles is that where most boss bars have the boss' name on the top and a title for said boss along the status bar, it's the other way around for Elusive and Gyro.
![elusive_boss_bar](https://user-images.githubusercontent.com/52132442/85931408-37568180-b8bc-11ea-8b73-d31ac7612cd8.png)
![gyro_boss_bar](https://user-images.githubusercontent.com/52132442/85931409-3aea0880-b8bc-11ea-9441-df1e905a1101.png)
Would it be possible to slightly adjust these textures so "Master of Deception" and "The Final Act" is along the status bar of their respective boss bars rather than on the top?

**Comment by DiamondWalker** [comment]
The thing is with those health bar designs it'd be hard to fit the title, although with elusive you can just extent the flat area so this only applies to Gyro's.
