### ISSUE TITLE
Red waterweed is hard to find

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1709]
**Mod Version**
3.3.2

**Describe the bug**
Red waterweed is hard to find
And it's not like trilliad bloom
It's not 100% drop floracle seeds

**Comment by Sweaty07** [comment]
I think that's the point of Floracle Seeds. It's pretty much free xp for doing next to nothing and once you get one, you can use bone meal on the crop to get a pretty substantial amount of extra seeds and crops. If you stockpile bones you can have hundreds of rows worth of floracle seeds in a matter of minutes. It shouldn't be an easy item to obtain.

**Comment by Cruuk** [comment]
> 
> 
> I think that's the point of Floracle Seeds. It's pretty much free xp for doing next to nothing and once you get one, you can use bone meal on the crop to get a pretty substantial amount of extra seeds and crops. If you stockpile bones you can have hundreds of rows worth of floracle seeds in a matter of minutes. It shouldn't be an easy item to obtain.

Floracle seeds are quite annoying to get. If Floracles were too strong, you'd tweak the item itself, not the obtaining method. If you just made it rarer, it would still be "OP", and I think it's mostly fine.

However, while it's fine to make the foliage rare, or make it so there's only a chance to get the seeds when breaking it, doing both at the same time just makes it a pain. Just finding the Red Waterweed is a huge pain, especially with the Pixons being similar in color. And when you finally find one, just to get nothing, it can feel quite tedious.
