### ISSUE TITLE
Abyssal Lottoman uses its Overworld counterpart's skin instead of its own

### ISSUE THREAD

**Issue by LokiY2K** [Tslat/Advent-Of-Ascension#1710]
Written as of:
**AoA Version:** 3.3.2
**Forge Version:** 14.23.5.2847

Abyssal Lottoman is using the skin of his Overworld brethren rather than its own unique skin, like other Lottomen.
![2020-06-29_16 46 44](https://user-images.githubusercontent.com/67063563/86014729-5d4d6480-ba29-11ea-8771-d1853e994cbc.png)

**Comment by Tslat** [comment]
Fixed in next version
