### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jcfinal** [Tslat/Advent-Of-Ascension#1711]
**Mod Version**
What version of the mod are you on?
Latest?
**Describe the bug**
Essentially whenever the day or night cycle occurs, the game suddenly crashes. And in singleplayer, AoA mobs don't spawn, instead of crashing.
**To Reproduce**
Steps to reproduce the behaviour:
I think it's AoA mixed with Kemonocraft
**Expected behavior**
Not crash...?

**Screenshots**
[AoA-EventCrash.txt](https://github.com/Tslat/Advent-Of-Ascension/files/4849497/AoA-EventCrash.txt)

**Comment by Tslat** [comment]
Try it without any other mods present and provide the crash report from that

**Comment by jcfinal** [comment]
So run AoA by itself?

**Comment by Tslat** [comment]
Yes.

I suspect this crash is caused by another mod improperly modifying spawn lists.
If you can test whether it happens for you without other mods present we can begin narrowing down what mod may be conflicting and maybe find a solution
