### ISSUE TITLE
Spectral Archergun requires and consumes holly arrows

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1714]
**Mod Version**
3.3.2

**Describe the bug**
Unless the Spectral Archergun's ability was changed, it no longer does as the tooltip says. It consumes holly arrows when firing and you can't pick any of the arrows back up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Take a Spectral Archergun and some Holly Arrows out of the creative inventory
2. Fire the Spectral Archergun
3. Observe that holly arrows are consumed.

**Expected behavior**
The Spectral Archergun should be able to fire without holly arrows in your inventory

**Comment by Tslat** [comment]
Fixed in next version
