### ISSUE TITLE
AoA skill mod compat

### ISSUE THREAD

**Issue by AoAjunky** [Tslat/Advent-Of-Ascension#1715]
**Describe the new feature you think would be good to add**
A specific and detailed description of what you want to see.
adding on to the planned skills update: mod compat with skills. such as tech mods with the engineering skill and certain magic mods with the alchemy skill or augery, rpg mods with the expedition and combat skills, etc. also using other modsto level up skills, such as engineering exp every time you craft or use a machine from a tech mod to make something.
**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?

**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?
it may have been already suggested, if so im am sorry for resuggesting but i could not find anything about this specifically. also i know it was suggested in the poll options for the skills update, that mod compat will be looked at, but wanted to add to that idea.

**Comment by Tslat** [comment]
Third party compat suggestions need more details.

I don't know every mechanic of every mod out there, so I have no way of knowing what exactly you're suggesting when you say 'make it work'
