### ISSUE TITLE
Ghostly Charger is not semi-transparent like it's supposed to be

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1722]
**Mod Version**
3.3.2

**Describe the bug**
Compared to the other ghostly mobs, the charger is fully opaque.

**Expected behavior**
It's supposed to be semi-transparent like the other ghostly mobs.

**Screenshots**
![2020-07-06_00 33 25](https://user-images.githubusercontent.com/58011699/86558996-75891c00-bf20-11ea-920b-bbbc8f556f4d.png)

**Comment by Cruuk** [comment]
Albino Charger

**Comment by Tslat** [comment]
Fixed in next version
