### ISSUE TITLE
Change Portal Frames spawned in other dimensions to be made of Ancient Rock

### ISSUE THREAD

**Issue by NeoVolt** [Tslat/Advent-Of-Ascension#1725]
Currently, portals spawned in other dimensions are usually made of some sort of material from said dimensions, like how Haven's is made of Twinklestone. But I feel like sometimes the materials don't make too much sense. (leaves don't seem like they'd make a good portal material, especially if they're using a semi-transparent texture) I think changing the portal frames that are spawned when you enter another dimension to be made of Ancient Rock could be a good idea for the sake of consistency.

**Comment by DiamondWalker** [comment]
Just change the leaves then? I don't get why remove a feature like this for no reason other than a few of the portal frames being nonsensical

**Comment by NeoVolt** [comment]
It's not removing a feature, it's changing portal frames from being made out of leaves and stuff when they generate in another dimension to being made of ancient rock

**Comment by DiamondWalker** [comment]
> 
> 
> I think changing the portal frames that are spawned when you enter another dimension to be made of Ancient Rock could be a good idea for the sake of consistency.

Either way, why just make it ancient rock? It could be any other block from that dimension
