### ISSUE TITLE
Typos in Barathos(?) and Precasia portal messages

### ISSUE THREAD

**Issue by LokiY2K** [Tslat/Advent-Of-Ascension#1729]
Precasia and Barathos' portal opened messages have typos in them. Intended(?) messages are in brackets.

Reported as of **AoA Version 3.3.2**

**Barathos:** You heard strange noises and loud thumping. (You hear strange noises and loud thumping.)

**Precasia:** The portal looks suprisingly new as it appears. (The portal looks surprisingly new as it appears.)

**Comment by Tslat** [comment]
Fixed in next version
