### ISSUE TITLE
Dracyon's model

### ISSUE THREAD

**Issue by odw500** [Tslat/Advent-Of-Ascension#1730]
Dracyon's model and movement animation looks a little unclean. The spines on its head aren't exactly centered as shown here
![2020-07-09_12 04 12](https://user-images.githubusercontent.com/52132442/87033419-18ba8980-c1de-11ea-90c3-19d96b8f8d38.png)
It seems to be positioned on the other side of its head on the statue
![2020-07-09_12 14 07](https://user-images.githubusercontent.com/52132442/87033433-22dc8800-c1de-11ea-809b-72b1192d8c47.png)
In addition Dracyon's wings only seem to flap as it moves so it looks completely still while not moving. Ideally its wings should be able to flap on their own as with mobs like Nightwings and Flyes.

**Comment by DiamondWalker** [comment]
I know this isn't the point of the suggestion but I've always wanted him to be a bit bigger as well.
