### ISSUE TITLE
The monster is not visible sometimes and you cannot attack it.

### ISSUE THREAD

**Issue by yilangyo** [Tslat/Advent-Of-Ascension#1731]
**Mod Version**
AoA3-3.3.2.jar [1.12.2]

**Describe the bug**
The monster is not visible, f3 + c can not see the direction of the entity, And cannot attack it,when you return to death you will find that the entity can be seen

**To Reproduce**
Steps to reproduce the behaviour:

When you explore the main world in survival mode, frequently refreshed monsters such as attackers and cyclops may exhibit descriptive behavior

**Expected behavior**
My English is not very good. It seems that no one on GitHub has reported similar problems. My minecraft version is 1.12.2 and the forge is the latest version. Please fix it. This bug is really tormenting.

**Comment by yilangyo** [comment]
I want to re-describe the bug in the comments. The monsters refreshed in the main world can sometimes not be seen, but there are still sound effects. It can attack you. I played this mod for the first time. At the beginning of this kind of bug, I thought it was a ghost species. , Because I found a similar transparent generation in the monster egg, but it’s not, when you are killed by an invisible monster, you resurrect and return, you will find it is now visible [Google Translate]😭

**Comment by EatingSilencer** [comment]
Do you have Optifine installed? An invisible mobs bug is known to be caused by Optifine.

**Comment by Tslat** [comment]
This is an optifine bug

**Comment by yilangyo** [comment]
> 您安装了Optifine吗？已知是由Optifine引起的隐形暴民错误。

Yes, I found it, haha is so embarrassing (lll￢ω￢)

**Comment by Peimous** [comment]
I had a problem that I thought would be strange: in survival mode, AOA monsters don't attack and move, but monsters in Minecraft and other mods do

**Comment by Tslat** [comment]
Forge broke things
Downgrade to 47.1.3 forge
