### ISSUE TITLE
Compilation of things to add/change if we port to 1.15

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1735]
This is just a compilation of suggestions I have that pertain to having the mod in 1.15. Rather than make a bunch of small suggestions and spam the Github, I decided to put them all here.

-------------------------------

__**The Aquatic mob classification**__
1.13 added a new classification for mobs: Aquatic. In a similar vein to Undead and Arthropod, "Aquatic" obviously refers to any water-themed mobs. Aquatic mobs will take extra damage from the "Impaling" enchantment.

I think it would make sense for certain AoA mobs to be considered Aquatic. Granted, this would mainly consider all the Overworld's water themed mob/bosses, Fischer, every L'Borean mob, etc.

--------------------------------

__**New Tridents**__
I know AoA has a lot of content already, but it would feel a bit disappointing for Tridents as a weapon type to be non-viable past the Overworld, especially since they're the only type of weapon that can get certain enchantments like Impaling. I don't know how hard it is to give other weapon types Impaling, but even if it is possible I can't think of where it could fit.

You don't need to add like 20, just 1-2 per tier would be enough. Here's a couple of rough Trident concepts I have as an example:

**Devil's Pitchfork**: Nether Trident, can also surf in lava if enchanted with Riptide.

**Lightning Rod**: Iromine Trident, strikes lightning on hit regardless of if it's raining and if it's enchanted with Channeling. We already have weapons that do an Enchantment's effect without needing the effect. (See: Infernal Bow)

**Poseidon's Trident**: L'Borean Trident. Could just be the same as the vanilla Trident, but balanced around t3.

--------------------------------

__**(Maybe) change Reef Staff's ability/change it into a Trident**__
Riptide seems to be pretty powerful. And while I don't think it'll trouble any existing transportation methods like Sky Staff at all, I can't say the same for Reef staff.
Maybe you can argue that Reef staff has selective advantages like no requirement of charging up and being able to be used in the offhand, but Riptide can be used in rain. Also, Reef staff is a boss drop, while Tridents and Riptide can be obtained before leaving Overworld.

So, I'd change Reef Staff's ability to maybe something like an extended version of the fast swimming effect Dolphins give, or convert Reef Staff itself into a Trident. Maybe it could be that L'Borean trident I mentioned in the above section?

-------------------------------

__**Change the AoA Phantom's name**__
Obviously, MC itself has a mob named the "Phantom" now, and AoA already struggles with having a mode called "Hardcore" that does different things from vanilla's hardcore mode.

Personally, I think names like "Geist" or "Poltergeist" could work. "Phantasm" could also work, but it could be misleading, as it doesn't drop the Phantasm item.

------------------------------

__**Have the spawn mechanics of the Overworld NPCs work more like the Wandering Trader**__
This may be just me, but I think it would make the spawning of the Overworld NPCs a bit more intuitive compared to the current animal spawning mechanics.

For those that don't know, this is how the Wandering Trader's spawn mechanics work:
`At any time, there can be only one wandering trader naturally spawned in loaded chunks. However, it is possible to have more than one wandering trader present by having one spawn in loaded chunks, while having another in unloaded chunks. After 24000 ticks (20 real-life minutes, or 1 Minecraft day) have passed since the world is created, the game attempts to spawn a wandering trader. If there are no wandering traders currently in any loaded chunks, the game tries to spawn a new wandering trader after every following 24000 ticks, within a 48-block radius of a player. The first spawn attempt has a 2.5% chance of success; if it fails, after another 24000 ticks another spawn attempt is made with a 5% chance of success. If that fails, for all subsequent spawn attempts the chance caps at 7.5%. On average, it takes 10.411 Minecraft days for a wandering trader to spawn.`

These exact numbers don't have to be used, but I think it would work better for the Overworld NPCs. If possible, it could also be applied to the Nether Lottoman? Animal spawns are clearly awful in the Nether, and I doubt it's a Placebo thing.

------------------------------

__**Change all Archerguns to Crossbows**__
With the sole exception of Spectral Archergun, I really do think that Archerguns are underpowered. I also really disagree with an Archergun's role of being an alternative to guns if a mob has gun immunity. (Source: this page written by Scimi https://adventofascension.gamepedia.com/User:Scimiguy/Guides/Getting_Started )

First off, a weapon's role solely being a required alternative to a superior weapon type (guns) in *very* specific scenarios is not good design in my eyes. The lack of any damage enchantment also really hurts.
But this truly shows the flawed existence of these Terraria Repeater reskins. If you gave them something like Shell, then it would be constant conflict between Guns and Archerguns. And I think all this balancing stress can be wiped away by converting **all of them** into Crossbows, completely erasing the concept of Archerguns. To be honest they were always just kind of a weird concept.

Crossbows, with enchantments have a more defined role as piercing/AoE sources of Ranged damage, which isn't really present in Advent. Crossbows even partially inherit some Archergun upsides- Quick Charge III allows faster firing speed than Bows, a loaded Crossbow can be fired at full running speed, etc.

I think it would be beneficial, as I doubt anyone with a brain would miss Archerguns. Really, I'd only miss Spectral Archergun and its fire rate, but that is such an extreme edge case. After all, you can always give Crossbows varied loading speeds(?)

---------------------------------

I know there are other things to keep in mind with a 1.15 port (like L'Borean's coral blocks vs. the Coral blocks added by Vanilla, removing Colored bricks and Crate, etc.), but these are the ones I personally consider important, especially the Crossbow/Archergun one. Hopefully at least some of these are considered, I think the mod would really, really benefit from these changes.

**Comment by EatingSilencer** [comment]
I'll add other things I find to this list.

**Foxes eating AoA foods**

Foxes in 1.14+ have the ability to pick up and consume food items. They also seem to have the ability to obtain the status effects from said items according to the MC Wiki.

A quick look at AoA's food items makes it seem that only the player can get some of the effects, if not all of them. Note sure if this would cause a crash with foxes that might need addressed.
