### ISSUE TITLE
When trying to put down a tablet that you do not have enough Soul Power to use, the toast notification displays twice

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1738]
**Mod Version**
What version of the mod are you on?
3.3.2

**Describe the bug**
When you put down a tablet that you do not have enough Soul Power to use, the toast notification saying that you need more Soul Power shows up twice instead of once.

**To Reproduce**
Steps to reproduce the behaviour:
1. Grab a tablet that you have the correct Anima level to use, then go into Survival mode.
2. Put down and pick up the tablet until you run out of Soul Power to put it down again.
3. Try to place it down again.
4. See error. The toast notification displays twice. For comparison, check out running out of energy with a blaster or not having enough Creation points to spawn a minion.

**Expected behavior**
The toast notification only displays once.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/87218519-86230300-c321-11ea-9899-800dceaaf0d3.png)

Comparison image:
![image](https://user-images.githubusercontent.com/44556728/87218525-8c18e400-c321-11ea-90af-3df42af92980.png)

**Comment by Tslat** [comment]
Fixed in next version
