### ISSUE TITLE
Some names are misspelled/inconsistently spelled in their advancement descriptions

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1739]
**Mod Version**
What version of the mod are you on?
3.3.2

**Describe the bug**
Experiment W-801's name is misspelled as Experiement-W801 in the "Monster Blaster" advancement. 

Color Cannon's name is inconsistently spelled as "Colour Cannon" in the "It's a Rainbow!" advancement.

It seems that most advancement descriptions have the word "gold" in the name of the gold statue capitalized, but for gold Hydrolisk statue its lowercase: "gold Hydrolisk Statue".

**To Reproduce**
Steps to reproduce the behaviour:
1. Obtain a Experiment W-801 and the "Monster Blaster" advancement.
2. Compare the name of Experiment W-801 to its name in the advancement's description.
3. See error
4. Obtain a Color Cannon and the "It's a Rainbow!" advancement.
5. Compare the name of Color Cannon to its name in the advancement's description.
6. See error
7. Look at the description for the "Gold-Lead Seafood" advancement. See that the word "gold" is non-capitalized.
8. Compare this to the description of a different advancement about obtaining a gold statue. Notice the word "Gold" is capitalized.

**Expected behavior**
The name of Experiment W-801 is spelled correctly.

Color Cannon's name is made consistent.

The word "gold" in the advancement "Gold-Leaf Seafood" is capitalized.

**Comment by Tslat** [comment]
Fixed in next version
