### ISSUE TITLE
Counter to some mob effects

### ISSUE THREAD

**Issue by Armakeen** [Tslat/Advent-Of-Ascension#174]
When you wear a Pumpkin on your head, looking at Occulent's face will not damage you, looking at a Silencer will not drop your inventory, looking at a Lost Soul will not heal him, looking at a Stalker will not cause a static effect and looking at a Dusteiva will not teleport you into the air

It can seem really powerful, but since you lose many protection due to not wearing a helmet, I think it makes things balanced

**Comment by Tslat** [comment]
This is no longer relevant in 3.2 as look-effects were removed/nerfed
