### ISSUE TITLE
netherlike coordinate behavior for dims + new overworld portal or double portal dim behavior / portal stacking

### ISSUE THREAD

**Issue by strivenous** [Tslat/Advent-Of-Ascension#1743]
**Describe the new feature you think would be good to add**
I think dimensions could be a good way of travel, and the opportunity of portal stacking (EG: overworld > precasia > creeponia) should be considered, or just a parallel netherlike behavior (nether 1 block=8 blocks overworld or so), maybe depending on the dimension's lore or geographical aspects, the ratio could be different, making up for different options of travel with it's own cons and pros, this would take for a pretty big revamp, probably.

**Add any alternative implementations you think might work**
no other, but if this is added it might break older mod worlds, maybe a conversion tool?

**Include any additional background information**
not that I know of

**Comment by Tslat** [comment]
Portal stacking has been a thing for a long time?
