### ISSUE TITLE
older mod's texture pack release

### ISSUE THREAD

**Issue by strivenous** [Tslat/Advent-Of-Ascension#1744]
**Describe the new feature you think would be good to add**
I know a few people that liked the older AOA textures (EG: the older and bigger Emberstone sword) and I also believe that a lot of the playerbase would appreciate some of the now-revamped textures and inventory sprites.

**Add any alternative implementations you think might work**
n/a

**Include any additional background information**
n/a

**Comment by Tslat** [comment]
Those older textures were stolen from other people and therefore copyright breaches. They will not be coming back.
