### ISSUE TITLE
Mekanism's Integrations

### ISSUE THREAD

**Issue by phamthaison1207** [Tslat/Advent-Of-Ascension#1745]
**Describe the new feature you think would be good to add**
Support for the Gas Mask and Scuba Tank when going into Vox Ponds , yes i know the scuba tank sounds like it's for diving but the gas mask should protect you against the deadly environment  because the scuba tank only carries oxygen
Support for the Crusher with the Pulverizer's recipes and its counterparts : Basic/Advanced/Elite Factories
Same goes for the Energized Smelters  with the Redstone Furnace's recipes and its counterparts  Basic/Advanced/Elite

**Comment by Tslat** [comment]
Not sure what you mean about crusher/pulverizer/smelter/furnace

I don't know every mechanic of every mod, if you want some specific integration you have to detail it

**Comment by SKnight1207** [comment]
Tslat : the Crusher is just Mekanism's Pulverizer and the smelter is also Mekanism's Furnace, just with more slots and a faster speed

**Comment by SKnight1207** [comment]
And I think you only need to allow the Gas Mask to be used as a replacement for the Face Mask when it's available
and the Scuba Tank is the Oxygen needed to breath =))
