### ISSUE TITLE
Textures for crossbows for the 1.15 port

### ISSUE THREAD

**Issue by NeoVolt** [Tslat/Advent-Of-Ascension#1746]
So there's been some talk on the AoA Discord about potentially changing archerguns to crossbows in the 1.15 port. I thought it would be a good idea to make some potential textures for the new crossbows to use, so I did that, here they are.

![AoAArchergunsExceptCrossbow](https://user-images.githubusercontent.com/57927345/87384545-a50fd800-c561-11ea-8182-c729d2e85c46.png)

**Comment by NeoVolt** [comment]
Also if necessary, I can make animation frames for loading the crossbows as well

**Comment by XxDuckyUxX** [comment]
These are hot
