### ISSUE TITLE
The "Waking the Ancient Undead" advancement has an incorrect description

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1747]
**Mod Version**
What version of the mod are you on?
3.3.2

**Describe the bug**
The "Waking the Ancient Undead" advancement is now obtained by defeating a Skele-elder. However, the description for it still says "Obtain an Ancient Orb".

**To Reproduce**
Steps to reproduce the behaviour:
1. Obtain any advancement from the Precasia section to unlock it.
2. Defeat a Skele-elder.
3. Scroll over the advancement "Waking the Ancient Undead".
4. See error: its description still says "Obtain an Ancient Orb".

**Expected behavior**
The description accurately reflects the obtaining method for the advancement.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/87439514-e1bdec80-c5be-11ea-8337-ed1ecdf9fde5.png)

**Comment by Tslat** [comment]
Known and fixed
