### ISSUE TITLE
Make it so not all bosses are the same tier as their dimension

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#1749]
Currently every boss is on the same tier as their dimensions, which makes sense, but occasionally there are bosses that are too strong for their dimension's tier. Current examples of this would be baroness and skeletal army, which despite being T1 are some of the most difficult bosses in the mod. Sure you could just nerf them (and in most cases that's the ideal solution), there are some cases where it'd be a bit odd. For example, with skeletal army you're fighting a massive army of undead. Making that be a cake-walk wouldn't be make much sense, but neither does having it be a T1 boss.

There's another thing that isn't that great about the current system, and that's the fact you can go into a dimension, kill both bosses right away, and never fight another boss there. Something about having the same dimension include two bosses at the same exact level of progression feels odd, though that might just be me. Still, it would be nice if there were bosses you come back to fight after you're finished with the dimension.

I think the best way to do this would be by occasionally breaking the "Boss tier = dimension tier" rule. One way to do this would be making certain bosses require ingredients from later dimensions. This could also help weave the different dimension paths together, a change I also think would be nice. A list of changes I would do to specific bosses is:

Baroness-would include bloodstone in the warlock gem recipe, making her a T2 boss that requires the abyss as well. She's pretty powerful for a T1 boss, but her current difficulty works pretty well alongside her AI, making a fast-paced fight that is also pretty punishing and keeps you on your toes. Her style also kinda fits the abyss, so I think T2 would be a good fit for her

Skeletal army-would somehow require greckon, making it a T3 boss (idk exactly how this could work with the army's new spawn method). I already explained why above

Nethengeic Wither-I'm not sure exactly what dimension he could require, but currently he's easier to summon than the regular wither, despite being an "upgrade". He feels like he should be a T3 or T2 rather than a T1 to make him be an actual upgrade to the wither

**Comment by Hamburger666** [comment]
Not a bad thought, but actually a lot of players don't fight Skele army the normal way they should. Like me for an instance, i always empty the arena and then build a massive mob grinder to grind them. Ik the final wave's boss packs a punch(70 dmg i belive) but anyone can cheese it with a mob grinder.
