### ISSUE TITLE
Certain mobs shouldn't have bow/gun immunity

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#175]
**Describe the change or feature you think would be good to see**
Now, I think it's perfectly reasonable for certain mobs to have resistances to guns and bows, adds a bit of thinking when fighting certain mobs, but there are certain mobs that I think have the gun/bow immunities solely to force players to stop using the OP guns in 1.7.10 without actually nerfing the guns themselves.
To add to my case, there's also those certain mobs that for some reason are immune to bullets, but not arrows, hmm...
Maybe I'm wrong about all of this, but some of those mobs are pretty damn tanky, and with overall player damage lowered and guns being way more balanced than ever before, kinda don't see a reason for certain ones to still be immune...

To be honest I'm not sure what exact prerequisites a mob needs in order to have attributes, I'm just gonna name off certain mobs that are already annoying to kill without the attributes.

**Anemia**: I'm not sure if anyone likes this thing at all. And I think one of the reasons is that god damn gun immunity. As if being one of the strongest earlygame mobs isn't enough. It isn't helping the case of Overworld having crazy mobs while most dimensions have pathetic ones.

**Nethengeic Beast**: 450 hp... strength nerf... gun nerf.... I think it's fine for these things to not have those anymore. The tankiness speaks for itself.

**Megatherium**: Same reason as Nethengeic Beast, though maybe just keep the bow immunity to emphasize the tough skin? No clue. I've always wanted to use a Hunter's rifle on it.

**Rockrider**: Why was he given gun immunity in the first place?
Back in the day, only the range resistance form had gun immunity and it made perfect sense, but then it was changed so that *both forms* had gun immunity, which always seemed like a dumb change to me to be honest.

There are others I didn't point out, but I'm gonna stop posting specific mobs now because I'm sleepy. I just hope mob attributes are put onto stuff that... makes more sense in the future. Lots of effort put into this one I know

**Comment by Immortallis1** [comment]
Yeah nethengeic beasts are too tanky. let's be real here they have antikb and hit really hard (10 hearts) and spawn in an enclosed structure that almost might as well be called "claustrophobic pit".

There's no way to fight them besides rigging the dungeon so that they can't get to you but you can hit them. So it doesn't really matter if they have gun immunity

**Comment by Immortallis1** [comment]
crusilisk CAVE

**Comment by Immortallis1** [comment]
> 
> 
> > Yeah nethengeic beasts are too tanky. let's be real here they have antikb and hit really hard (10 hearts) and spawn in an enclosed structure that almost might as well be called "claustrophobic pit".
> > There's no way to fight them besides rigging the dungeon so that they can't get to you but you can hit them. So it doesn't really matter if they have gun immunity
> 
> I think it would help if the "Nethengeic Pit" was actually an open pit and not a Nethengeic HOUSE.

crusilisk CAVE
totally not an iron bar brick building

**Comment by Tslat** [comment]
3.2 Redoes the stats and immunities on every single mob, this is no longer relevant
