### ISSUE TITLE
Things to default to when the mod ports to 1.15.2

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1751]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
The following post is for all things that need to be defaulted when the mod ports to 1.15.2.

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.

**Foxes eating AoA foods**

Foxes in 1.14+ have the ability to pick up and consume food items. They also seem to have the ability to obtain the status effects from said items according to the MC Wiki.

A quick look at AoA's food items makes it seem that only the player can get some of the effects, if not all of them. Note sure if this would cause a crash with foxes that might need addressed, or if foxes should be able to obtain effects from aoa foods. For example, Floracle Sticks give the player vanilla xp, but a fox wouldn't be able to also obtain vanilla xp...what would happen then?

**Bees pollinating AoA crops**
Per title.

**Phantom in 1.13 vs Phantom in AoA**
AoA's Phantom mob might need a rename in 1.15.2 because there is a mob in 1.15.2 Minecraft called the Phantom.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
No

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Scimi mentioned wanting it on the discord. These kind of issues have been mentioned before.

**Comment by EatingSilencer** [comment]
Anyone else can post things here! If there is a thing in 1.15 that needs to be default, reply to this post!

**Comment by NeoVolt** [comment]
**General Polish**

- Certain things being craftable within the stonecutter

- Being able to strip logs with AoA axes and putting out campfires with AoA shovels

- Being able to put AoA crops in the composter

**More or Less New Additions**

- The ability to strip AoA logs

- Being able to waterlog things but with candied water instead

- Being able to use AoA flowers in suspicious stew recipes

**Comment by Sonicwave** [comment]
* Blast furnace, smoker and campfire recipes for appropriate ores/food items
* Changing rune banner pattern recipes to use the loom instead of crafting table
* Almost all vanilla undead vanilla mobs sink in water and cannot drown, should AoA undead mobs follow this behavior?

**Comment by EatingSilencer** [comment]
Should vanilla fish be able to swim in candied water? And if so, will separate bucket of fish items need to be made for candied water?

**Comment by EatingSilencer** [comment]
>     * Texture changes to items/blocks that are clearly based around vanilla textures and would therefore look inconsistent post-Texture Update...

To add to this, I think some vanilla mc mobs have texture changes. Skeletal Cowman and Skellox might need thier mob textures updated to reflect the changes to cows and skeletons due to the Texture Update.

**Comment by EatingSilencer** [comment]
> 
> 
> > ```
> > * Texture changes to items/blocks that are clearly based around vanilla textures and would therefore look inconsistent post-Texture Update...
> > ```
> 
> To add to this, I think some vanilla mc mobs have texture changes. Skeletal Cowman and Skellox might need their mob textures updated to reflect the changes to cows and skeletons due to the Texture Update (not sure about Sea Skeleton or Sea Spider).

Add Dead Tree, Tree Spirit, Wood Giant, Stone Giant, Sand Giant, Leafy Giant, and Ice Giant to the list that need changing.
