### ISSUE TITLE
About legacy versions of the AoA mod

### ISSUE THREAD

**Issue by vinicius1222** [Tslat/Advent-Of-Ascension#1754]
Do you still have legacy versions of the AoA mod: 2.0.1 or 2.0.4?
Congratulations on continuing the mod

**Comment by masterbobli** [comment]
It's possible that such versions still exists, but nobody in the community currently have those files. Currently, the closest representatives I can get is AoA 2.0, 2.02, 2.03 and 2.04 translated into chinese by the community, but I am unable to guarantee that such copies are safe to use.

**Comment by vinicius1222** [comment]
send the link where I can find it, please. I will try at my own risk

**Comment by masterbobli** [comment]
Here's the link: https://pan.baidu.com/s/1hqKp1IW#list/path=%2F
The password is    i4pd    .

**Comment by vinicius1222** [comment]
thanks

**Comment by masterbobli** [comment]
Don't forget to close this issue.

**Comment by vinicius1222** [comment]
and the username?

**Comment by masterbobli** [comment]
What do you mean? I don't think you need an account to download these files.

**Comment by vinicius1222** [comment]
I tried to download and asks for username and password for what I translated

**Comment by masterbobli** [comment]
I'm currently downloading these files. Can I send them to you via discord?

**Comment by vinicius1222** [comment]
OK
User:vinicius12012#8552

**Comment by masterbobli** [comment]
I just remembered that discord have a file limit. I think you might need to register an account. Things are getting complicated.

**Comment by vinicius1222** [comment]
ok

**Comment by masterbobli** [comment]
http://www.mediafire.com/folder/2amoinwlntu7s/AoA_Earlier_Versions

**Comment by vinicius1222** [comment]
Thank you very much

**Comment by masterbobli** [comment]
You're welcome
