### ISSUE TITLE
Re-Implement Looping Boss Music

### ISSUE THREAD

**Issue by Firch** [Tslat/Advent-Of-Ascension#1755]
Currently, if you fight bosses, music can suddenly stop in middle of fight because there is no looping. Looping existed in older versions before, but was removed because music didn't loop, but since I'm making music for the mod, I'm making it loopable.

**Comment by Cruuk** [comment]
As far as I know, looping is basically impossible to implement smoothly, at least in 1.12.2

**Comment by Hamburger666** [comment]
well it is possible if your music itself have a perfect loop
else no
