### ISSUE TITLE
Remakes for Nethengeic Pit and Crusilisk Cave

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#176]
**Describe/name the existing feature this suggestion relates to**
... Nethengeic Pit and Crusilisk Cave.

**Describe the change or feature you think would be good to see**
These structures aren't very good in their current form. They don't match the name of the structure, and even then they're pretty lazy in general in terms of build quality. (Well ok maybe Nethengeic pit isn't bad but maybe it can be repurposed into something rather than a ""pit""?)

Me and some other people have talked about wanting the structure to be remade before, however I've decided to actually remake these structures ingame and take pictures of them, here you go:

**Nethengeic Pit**
My idea for the Nethengeic Pit was to... make it an actual pit. The blocks used here were Red Nether Brick, Barathos Hellstone (I think it's fine if it's outside Barathos), and the main block is Nether Wart block. While you may think you can just use it to gather tons of Nether Wart, oddly enough unlike other Storage blocks you can't turn Nether Wart block back into Nether Wart.

While this makes the Nethengeic Beast out in the open with no way of defense, that's intended. While the beasts are extremely tanky, they would also be an easy target and don't really have a way to get to the player unless the player digs a path that allows them to get out of there.
At the same time though the player shouldn't be careless, because if they fall in it's almost a guaranteed death, unless the player places a block down fast enough or uses other methods like jump boost. It'll *especially* be a death trap for new players who decide to blindly jump in without hesitation, hahaha....
![image](https://user-images.githubusercontent.com/38159897/50273063-68641500-03ee-11e9-809b-739910f18c69.png)
![image](https://user-images.githubusercontent.com/38159897/50273099-8762a700-03ee-11e9-8346-d9675f954fe2.png)
Hell, what if "Nethengeic Parasites" were added? They'd be these small Silverfish-like mobs with a Nethengeic theme. They would occasionally spawn at the upper areas of a Nethengeic pit. They would be weak in HP and damage and serve more as a distraction, if a player isn't watching while grinding the beasts, a Nethengeic Parasite could potentially sneak behind a player and knock them into the pit with all the beasts.
They wouldn't be a hunter mob.

-----------------------------------

**Crusilisk Cave**
In the past I've suggested to make these underground structures, but even with an aboveground indicator I imagine not many people would want to dig down to them. So instead...
A Crusilisk Cave would basically be a cave that leads down to a caged room. No natural caves spawn in Dustopia so already a "normal" cave would catch the player's eye and make them curious on what's down there. It'd be much more foreboding and more fitting to the "cave" name than the house we have currently. That's my opinion at least...
![image](https://user-images.githubusercontent.com/38159897/50273732-4b304600-03f0-11e9-9640-3cd56c43fc4b.png)
![image](https://user-images.githubusercontent.com/38159897/50273742-54b9ae00-03f0-11e9-8276-9cbb8fc9b4c0.png)
![image](https://user-images.githubusercontent.com/38159897/50273761-5c795280-03f0-11e9-9311-e7df65bbbd9b.png)
![image](https://user-images.githubusercontent.com/38159897/50273777-67cc7e00-03f0-11e9-8bc0-0eaefbd129a8.png)
![image](https://user-images.githubusercontent.com/38159897/50273799-7adf4e00-03f0-11e9-8e54-ab81ec07b1fa.png)
Maybe the Primordial Guide would hint at them being underground by saying something like "Some creatures were so dangerous they had to be imprisoned deep underground" or something?

**Include any additional background information**
There could be even be size variations for the Nethengeic pits? Some would be bigger then others, etc...

You could also make the layout of the cave leading to the prison semi-randomized so it's not always the exact same cave.

**Comment by Immortallis1** [comment]
even if you could turn them back into nether wart it wouldn't really matter anyway.

+1, the "pits" in their current form are just unnaturally flat buildings that you have to rig to keep the mobs away from you. The nethengeic pit especially is how I always envisioned it before actually seeing one.

**Comment by QueenCuddles** [comment]
I think the pit shouldnt have barathos hellstone, otherwise +1

**Comment by Cruuk** [comment]
> 
> 
> I think the pit shouldnt have barathos hellstone, otherwise +1

The reasons I put it there is because I think it looks cool and it could sort of work as subtle foreshadowing to Barathos. (can just rename the block to just "Hellstone")

However, the actual ulterior reason I did it was as a callback/connection to a past suggestion of mine:
![image](https://user-images.githubusercontent.com/38159897/50311292-81ee7680-0459-11e9-945e-0260a4b577c8.png)
