### ISSUE TITLE
"Oops.." advancement

### ISSUE THREAD

**Issue by Kagaribi172** [Tslat/Advent-Of-Ascension#1762]
**Mod Version**
3.3.2

**Describe the bug**
"Oops.." advancement can be completed when you die in VoxPonds.

**To Reproduce**
1.Run /gamerule keepInventory false
2.Wear the hazmat suits
3.Go to VoxPonds
4.Run /kill @s

**Expected behavior**
"Oops.." advancement can only be completed by stepping into VoxPonds without protect.

**Screenshots**
![スクリーンショット (219)](https://user-images.githubusercontent.com/63949302/88063508-10325d80-cba5-11ea-8f2f-d9d4af920d86.png)

**Comment by Tslat** [comment]
Fixed in next version
