### ISSUE TITLE
Rain and Thunderstorms in Precasia, Greckon, and Mysterium

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1763]
Just a quick suggestion here since I always found it strange that there's no weather in Precasia, but I also think it's fitting to add weather into those other two aforementioned dimensions as well.

**Comment by profilename14** [comment]
Adding on to this, I'm pretty sure that L'Borean has no rain. There is some debate on whether it is underwater, but it would be worth considering adding rain to it.

**Comment by Sweaty07** [comment]
To add to this, Barathos could have dust storms which while active will cause small tornadoes to sometimes spawn around the landscape, pulling in and then throwing away any player that comes near one. Barathos is a relatively peaceful dimension minus Tharaflies so it's just an idea to add a sense of danger while exploring.

**Comment by EnderdragonLord** [comment]
I was thinking that dust storms would fit the Abyss and Vox Ponds too, I can also imagine a dense fog weather for Dustopia. Vox Ponds could also have acid rain as weather where you'd have to seek shelter or you'll take continuous damage unless you're wearing the Hazmat armor to make it more useful and not have the Face mask completely overshadow it in usability. Lunalus and Precasia could potentially have meteors or at least meteor showers but not too destructive and it might have a chance to spawn loot.
