### ISSUE TITLE
Aoa3 Mod in server

### ISSUE THREAD

**Issue by L-Sunny-R** [Tslat/Advent-Of-Ascension#1764]
Mod Version
3.3.2

Describe the bug
In the server online, the amount of blood added to the dominant skill will always increase or decrease.

To Reproduce
1.open the bag or chest
2.if close,the amount of blood will decrease

Expected behavior
if close,it won't decrease blood

**Comment by Tslat** [comment]
I'm not sure what you're trying to say here...
Maybe post in your native language?
