### ISSUE TITLE
Conflict NeverMine and iChun’s Hats

### ISSUE THREAD

**Issue by wb-backend** [Tslat/Advent-Of-Ascension#1765]
**Mod Version**
Mineraft: 1.7.10
Nevermine-Tslat-1.1.2 and Hats-4.0.1

**Describe the bug**
If Nevermine mod is installed then hats mod does not save received hats when leaving the server.
When entering the server, all hats are removed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Kill any animal with a hat
2. Press "H" to view the looted hat
3. Leave the server
4. Go to the server
5. Press "H" to view clear list of hats

**Comment by EatingSilencer** [comment]
Known bug, might not ever get fixed as 1.7.10 support is dropped. Downgrade to Tslat 1.0.1 if you want to play with the mods together on 1.7.10 or update to 1.12.2.
