### ISSUE TITLE
Highlighted ores from the Occult pickaxe are bugged on the underside

### ISSUE THREAD

**Issue by EnderdragonLord** [Tslat/Advent-Of-Ascension#1766]
**Mod Version**
3.3.2

**Describe the bug**
Using the Occult pickaxe effect to highlight ores causes weird flat colors to appear on the underside of them.

**To Reproduce**
1. Right click on any ore using an Occult Pickaxe.
2. Look at the underside of the highlighted ores.

**Expected behavior**
There should not be any flat colors on the underside of highlighted ores.

**Screenshots**
![2020-07-23_12 07 20](https://user-images.githubusercontent.com/58011699/88316625-be412300-ccdd-11ea-8f48-9a2329b59c00.png)
![2020-07-23_12 07 06](https://user-images.githubusercontent.com/58011699/88316644-c5683100-ccdd-11ea-82e1-4ab947767782.png)

**Comment by Tslat** [comment]
Fixed in next version
