### ISSUE TITLE
Jawe Hut Redesign

### ISSUE THREAD

**Issue by RugratCoder94** [Tslat/Advent-Of-Ascension#1769]
A redesign for the Jawe Hut, one of the most disappointing small structures in my eyes. Now with 90% more hut!

![img1](https://user-images.githubusercontent.com/44593338/88742962-28f0c500-d109-11ea-96c6-87f3c6d6e11e.png)
![img2](https://user-images.githubusercontent.com/44593338/88742970-2ee6a600-d109-11ea-8ac5-498f784d1ee6.png)

here's those files
[region.zip](https://github.com/Tslat/Advent-Of-Ascension/files/4991808/region.zip)

**Comment by Cruuk** [comment]
Pizza hut
