### ISSUE TITLE
"Sponsored By God" advancement doesn't seem to have a description

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#1776]
Given the icon is a Holy Sword, I assume the description should read 'Obtain a Holy Sword'?
![2020-08-07_15 51 44](https://user-images.githubusercontent.com/52132442/89667506-24c86280-d8d4-11ea-8dfa-5878d5031e6e.png)

**Comment by Tslat** [comment]
Fixed in 3.3.4
