### ISSUE TITLE
Add some foods to the blacklist for Fungal Staff

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#178]
**Describe/name the existing feature this suggestion relates to**
As of AoA3-Snapshot 8, the fungal staff can be used to obtain some food items that it shouldn't be able to give to the player.

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
The following food items should not be given to the player when they use a fungal staff, along with a reason for each set:

The following food items are obtained from fish cases, some of them are locked behind Hauling levels. Being able to obtain them from the Fungal Staff defeats the purpose of training Hauling.
*Ironback
*Crimson Skipper
*Crimson Stripefish
*Rainbowfish
*Sailback
*Rocketfish
*Turquoise Stripefish
*Limefish
*Finger Fish
*Pearl Stripefish
*Sapphire Strider
*Dark Hatchetfish
*Razorfish
*Candlefish
*Violet Skipper
*Golden Gullfish

The following food items are candyland candies used to make the Treat Bag.:
*Sour Pop
*Sour Candy
*Sour Gummy
*Peppermint Candy
*Spearmint Candy
*Candy Cane
*Gingerbread Cookie
*Gingerbread Wing
*Candy Corn

The following food items shouldn't be obtainable from the Fungal Staff because they would otherwise give the player free of other items:

*Halycon Milk (free bucket)
*Mushroom Soup (free wooden bowl)
*Rabbit Stew (free wooden bowl)
*Beetroot Soup (free wooden bowl)
*Tea (free cup)
*Natural Tea (free cup)
*Fungal Tea (free cup)
Possibly:
*Lunarade (free lunarade mug)

**Include any additional background information**
This suggestion was previously on Discord, in one of the snapshot channels.

**Comment by Sagisolar** [comment]
Hmmm maybe it could check what level you are for the hauling food.

**Comment by Tslat** [comment]
Done after snapshot 9
