### ISSUE TITLE
Things that rely 100% on particles in order to be visible will become invisible once particles are set to Minimal.

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1780]
**Mod Version**
What version of the mod are you on?
3.3.3

**Describe the bug**
I am not sure if this was always the case, but it seems that setting particles to minimal will cause AoA's particles to vanish completely. While this in and of itself is likely intended, it has the consequence of making parts of the game...not sure how to describe it, its not really unplayable but the experience is certainly lessened. 

I've tested this on Glistening Pixons and with the Shyre Staff. Glistening Pixons become completely invisible, only being identifiable by their sounds and hitboxes. The Shyre Staff's projectiles turn invisible.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set particles to Minimal in the options menu.
2. Spawn a pixon or fire a weapon that relies 100% on particles to be visible, such as a Shyre Staff.
3. See error

**Expected behavior**
Setting particles to minimal does not detract from the quality of gameplay. I'm not sure how you would go about fixing this though.

**Screenshots**
With Particles set to All:
![image](https://user-images.githubusercontent.com/44556728/89701170-653ed500-d902-11ea-9073-ade510b6931e.png)

With Particles set to Minimal:
![image](https://user-images.githubusercontent.com/44556728/89701177-6d971000-d902-11ea-81d4-c694480a4e6e.png)

**Comment by Tslat** [comment]
Fixed in next version
