### ISSUE TITLE
Fragmented Anima Stones should be able to bone meal crops when placed in a dispenser

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1782]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Fragmented Anima Stone

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
In 1.12.2, you can place bone meal in a dispenser and activate the dispenser to bone meal crops in front of the dispenser. Fragmented Anima Stones cannot do this, putting them in a dispenser will simply have them be ejected from the dispenser when you activate it,

I suggest to make it work just like bone meal and fertilize the crop when inside the dispenser. The only problem is that you can't give Anima xp to a dispenser so a workaround for that would be required.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
No

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Not that I know of.

**Comment by Tslat** [comment]
Sure
