### ISSUE TITLE
structure rate group changes

### ISSUE THREAD

**Issue by JAKXlll** [Tslat/Advent-Of-Ascension#1783]
Structure and ore rates configuration

Having the option to change the spawn rate of all structures/ores with a single variable.For people who alter the rates I think this will make it quicker than having to go through all the dimensions/ores one by one.

**Comment by Tslat** [comment]
How would that even work? Every structure has different rates

**Comment by JAKXlll** [comment]
> How would that even work? Every structure has different rates

I know that. But when I alter them through configuration I always put the same value to all structures.It helps me spend less time looking for them without command spawning them. Since I ll anyway put the same number in all of them I thought that having a variable that does it for all structures at once will save time for players who also want to alter the spawn rates.

**Comment by Tslat** [comment]
But that's terrible lol

The smaller less intrusive structures should be more common than the bigger more complex ones
Making a Haunted Castle spawn as frequently as a poison rune shrine would be ridiculous

**Comment by JAKXlll** [comment]
Thats fair.Hmm.The only other idea towards this then would be to categorize the structures by building types and not by dimensions(ex:All shrines share one variable,all boss altars another etc etc)That way one can still make the monster spawner buildings much more frequent while keeping the less needed buildings in check. If that is not possible or beneficial then thats it for this suggestion.
