### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by SamLam140330** [Tslat/Advent-Of-Ascension#1785]
**Mod Version**
AoA3 3.3.3

**Describe the bug**
The server can not successfully open when the mod has installed. I have tried to open the server without any other mod but still can't succeed.
Here is the log file:
https://pastebin.com/3zdEhwk0
Here is the crash report:
https://pastebin.com/aMEskQQY

**Comment by Tslat** [comment]
Known. It'll be fixed in 3.3.4
