### ISSUE TITLE
Harvesting for Selyan with AgriCraft Crop Sticks

### ISSUE THREAD

**Issue by Waterspark63** [Tslat/Advent-Of-Ascension#1789]
**Mod Version**
2.4.B on MC 1.7.10, playing the Troll Craft Modpack

**Describe the bug**
Essentially, if you have AgriCraft installed, and your harvesting crops that are growing on Crop Sticks, the bar for Selyan will not fill. I have a 18x18 farm that I'm growing crops on Crop Sticks, and even harvesting that entire field, will not fill it at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place AgriCraft's Crop Sticks
2. Place Scanned Seeds on Crop Sticks
3. Allow Growth
4. Harvest
5. Bar will not fill

**Expected behavior**
The bar filling as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/23124229/89742375-25850400-da4e-11ea-9ef1-999682b4bd91.png)

**Comment by Tslat** [comment]
1.7.10 is dead.

Update to 1.12
