### ISSUE TITLE
Bring Back Some Early Dimension Gen

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#179]
Go back in a time machine and see some of the old dimension gen. And you notice that a lot of them are better than the current one. Let me show you some.

**Lunalus**
I like the early gen cause it made it less apparent that there are 2 layers in that dimension. It also the less planets makes Lunalus more tidy. Not sure if there's a void in this pic but keep the void in the snapshot gen.
![69](https://user-images.githubusercontent.com/44548547/50374621-df64fd80-05e8-11e9-9540-fc08b393cee4.png)

**Mysterium**
The 1.0 gen is much cleaner and honestly makes it more fun to play. Not only that, the light make the dimension look beautful. The only thing the current gen has over it is its foliage. But that can easily be improve by giving the old gen foliage.
![unknownlol](https://user-images.githubusercontent.com/44548547/50552516-db8e4680-0c8c-11e9-9f66-b76eb1966881.png)

**Runandor**
The 1.1 was also better, but the early gen nails out even that gen. Not only that, it looks more fun to play on. It really made the dimension kingdom like. I would keep the water from the current gen however.
![b2qgn-sicaa7pjh png large](https://user-images.githubusercontent.com/44548547/50617631-1a6b0900-0ee6-11e9-98b9-5241468f1783.png)

**Comment by Cruuk** [comment]
When people want the old Mysterium gen back they want the current one completely gone, not linger in the game as a biome, having the old and current one next to each other would look completely terrible. We don't want a compromise.

But hey besides that I do support bringing old Lunalus gen back (it's the same as current but with less planets and more spread out, and no bedrock ocean!)

**Comment by DiamondWalker** [comment]
I'd also like to see these stalactites and stalagmites come back into the Deeplands.
![b0u_wvviiamd14x](https://user-images.githubusercontent.com/19913710/50580494-11facb80-0e1d-11e9-87e4-f17b7252a2a3.png)

Iromine also had floating rings originally, which were removed right after it was released, idk why. I honestly felt they added a bit more decoration to Lunalus, and made the sky be less barren,

**Comment by Cruuk** [comment]
> 
> 
> I'd also like to see these stalactites and stalagmites come back into the Deeplands.
> ![b0u_wvviiamd14x](https://user-images.githubusercontent.com/19913710/50580494-11facb80-0e1d-11e9-87e4-f17b7252a2a3.png)
> 
> Iromine also had floating rings originally, which were removed right after it was released, idk why. I honestly felt they added a bit more decoration to Lunalus, and made the sky be less barren,

They were never there in the first place. They were removed before 1.1 was released.

Though even then, it would be neat for Deeplands to get Stalactites and Stalagmites.

**Comment by Caralamelia** [comment]
Does anyone even still like the old runandor, mysterium and celeve generation anymore?
The chunk height based while interesting feels like it has a touch of laziness compared to the unique generation shown in the screenshots.
Just thought i comment to bring this topic back up for interest in case it has been forgotten through the 2 years its been open.

**Comment by EatingSilencer** [comment]
Some people probably like the old runandor and mysterium gen still. Did celeve have old gen? I don't think its changed much besides other than maybe a slight tweak between 1.7.10 and 1.12.2.

**Comment by Cruuk** [comment]
> 
> 
> Does anyone even still like the old runandor, mysterium and celeve generation anymore?
> The chunk height based while interesting feels like it has a touch of laziness compared to the unique generation shown in the screenshots.
> Just thought i comment to bring this topic back up for interest in case it has been forgotten through the 2 years its been open.

This was made at a time when people thought just adding the old gen would fix everything. Nowadays, it seems people are a bit more controlled about that. I think Scimi would prefer to make new gen rather than just add the old one.

Bottom line, pretty much no one likes the new gen. People orbit around the old gen because it's what they're familiar with, and people prefer familiar things to things they can't mentally image in their head yet.

**Comment by Caralamelia** [comment]
I can see were you are coming with that of people orbiting towards familiarity but if anything i say just any gen over the current one would be better, indeed the current one seems bad and the only reason why i even bother to bring old one is not for feeling familiar but ratter that it doesn't look like a bunch of chunk errors that plague the dimensions.
If anything an new issue of just not making world gen look like cubical chunk height based errors and closing this one would be the best.
