### ISSUE TITLE
Various changes to give more use to some existing materials

### ISSUE THREAD

**Issue by profilename14** [Tslat/Advent-Of-Ascension#1792]
- Gardencia petals should all be craftable into 4 dyes of their respective color.

- 4 Ice Crystals should be able to be crafted into a packed ice block.

- Flammable dust should be useable as a fuel that smelts 10 items

- Rammerhead and Urka hides should work as replacements for leather when crafting.

- The player should be able to make lunarade with an empty lunarade cup, a Lunalon, a Lunacrike, and sugar.

**Comment by Cruuk** [comment]
> 
> 
>     * 4 Ice Crystals should be able to be crafted into a packed ice block.
PLEASE Green man I just want to make Crystallanium without having to find those damn Ice spikes biomes

**Comment by AstralScourge** [comment]
Support except for the lunarade one, since I find it hard to believe that a single lunalon is all that goes into lunarade

**Comment by profilename14** [comment]
I added a bit more to the Lunarade recipe. Now it requires Lunacrike, Lunalon, Sugar, and an Empty Cup.
