### ISSUE TITLE
Instant rechambering Head Hunter

### ISSUE THREAD

**Issue by Fleega** [Tslat/Advent-Of-Ascension#1794]
**Mod Version**
What version of the mod are you on?
3.3.4

**Describe the bug**
The Head Hunter instantly reloads after a successful headshot

**To Reproduce**
Steps to reproduce the behaviour:
Grab a Head Hunter
Boom, get a headshot and keep holding the fire button down

**Expected behavior**
The Head Hunter is supposed to fire only twice as fast on a successful headshot

**Screenshots**
downloads:
https://cdn.discordapp.com/attachments/434160774546456594/743337824400703488/Minecraft_1.12.2_2020-08-13_15-16-25_Trim.mp4
https://cdn.discordapp.com/attachments/434160774546456594/743338293617360972/Minecraft_1.12.2_2020-08-13_15-20-18_Trim.mp4

**Comment by Hamburger666** [comment]
so if i line some zombies up and aim for the head this gun basicially becomes a machine gun?

**Comment by Tslat** [comment]
Fixed in next version
