### ISSUE TITLE
No Structures, No Rune Posts, and No Boss structures

### ISSUE THREAD

**Issue by faustojc** [Tslat/Advent-Of-Ascension#1797]
I've been searching for the structures like rune posts, boss structures, and some Lotto structure and Mob Hunter structure in all dimensions. I've tried to increased the spawn chance in the config to max(1000000) but nothing happened. In overworld, I still haven't found the Amphibiyte Cove. What about rune posts? still nothing

My Mods:
AoA 3.3.4
EnchantingPlus
EnchControl
JEI
Optifine HD_U_5
Living Enchantment

**Comment by Tslat** [comment]
Increasing the number makes the structures less likely, not more. Read the actual description of the config value you're changing
