### ISSUE TITLE
creeponia World infinite  BOSS

### ISSUE THREAD

**Issue by C5bb** [Tslat/Advent-Of-Ascension#1799]
When you summon the boss, the four corners call automatically
Very, very many boss! Even if you kill him, he will still appear
![X66~H5QV9_4{$9V{B5QR{SJ](https://user-images.githubusercontent.com/54109240/90309440-44d2d400-df1b-11ea-90d4-4c3a9e652dec.png)

**Comment by C5bb** [comment]
version 3.3.4

**Comment by Tslat** [comment]
Known bug, fixed in next version
