### ISSUE TITLE
Add Non-Biome Mobs In Mob Update

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#180]
Darkling, Undead Eeo, Living Comet, Star Wizard, Airstroke, Gravicus.

These mobs were intended for 2.5 to be release along side the biome mobs.

Since these mobs don't require biomes. I wish to see them in Mob Update.

:3

**Comment by Immortallis1** [comment]
i still want melonman

**Comment by Sagisolar** [comment]
Well your gonna have to wait until 1.14 lol
