### ISSUE TITLE
Trying to throw a thrown weapon when there's only one in the stack causes nothing to be thrown

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1801]
**Mod Version**
What version of the mod are you on?
3.3.4 

**Describe the bug**
When you hold a thrown weapon and try to throw it, it normally should launch a projectile while consuming the weapon from your inventory. Trying to throw the thrown weapon when there is only one in the stack causes it to be consumed without launching any projectile however.

This was reported by someone else on discord but I didn't get a clear answer if this was fixed or not, so I'm posting this here just in case.

**To Reproduce**
Steps to reproduce the behaviour:
1. Grab one of any thrown weapon.
2. Go to Survival mode.
3. Try to throw the thrown weapon.

**Expected behavior**
A projectile is launched like normal.

**Comment by Tslat** [comment]
Fixed in next version
