### ISSUE TITLE
Adding an Imbuing recipe to the crafting table's recipe book and clicking on it causes the game to crash

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1802]
**Mod Version**
What version of the mod are you on?
3.3.4

**Describe the bug**
You can manually add the imbuing (enchantment) recipes to the crafting tables with commands. Doing so will cause them to show up as Air and clicking on them crashes the game.

You can also add other recipes to the book, such as infusing and divine station recipes, but this bug report is about the game crash caused by clicking on an imbuing recipe, the others don't cause crashes as far as I know.

Crash report:
[crash-2020-08-15_13.27.49-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/5079202/crash-2020-08-15_13.27.49-client.txt)

**To Reproduce**
Steps to reproduce the behaviour:
1. Add an imbuing recipe to the crafting table using the /recipe command. An example command: /recipe give @p aoa3:infusion/imbuing/mending
2. Open the crafting table and open the recipe book.
3. Change tabs and pages until you find the Air recipe. Click on the Air recipe.
4. See error. The game with crash.

**Expected behavior**
Either imbuing recipes function the same as infusing recipes, which means that clicking on Air displays the 3x3 recipes but otherwise nothing happens, or they are unaddable to the recipe book period.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/90318098-14c80880-defc-11ea-8beb-db5957ff0749.png)

**Comment by Tslat** [comment]
Nothing I can do here.

You're using commands to override the defaults (which is to not use the recipe book).
Don't make the game crash if you don't want it to crash
