### ISSUE TITLE
Add glass panes for some AoA glass blocks

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1803]
**Describe the new feature you think would be good to add**
A specific and detailed description of what you want to see.
I think it would be neat if you added glass panes for most AoA glass blocks. They would be exactly like vanilla glass panes except with AoA glass textures.

They would only exist for the glass blocks you can obtain in survival mode:
*Abyssal Glass
*Aquatic Glass
*Archaic Glass (breakable)
*Baron Glass
*Gardencian Glass
*Haven Glass
*Iro Glass
*Lelyetian Glass
*Runic Glass
*Shyre Glass
*Vox Glass
*Zhinx Glass

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
No

**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?
This feels like a suggestion that would have been done by now...but I don't recall it ever having been mentioned before.

**Comment by Tslat** [comment]
Moved to projects - don't need an issue open for this one
