### ISSUE TITLE
Graphical glitch in multiple NPC GUIs

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1805]
**Mod Version**
What version of the mod are you on?
3.3.4

**Describe the bug**
Some NPC guis have graphical glitches in their GUIs.

There are a few blue pixels outside the GUI of the Undead Herald in the top right corner.
![image](https://user-images.githubusercontent.com/44556728/90323034-a732d100-df29-11ea-8e95-11cfe68ad1f8.png)

The same thing with Undead Herald's GUI is also present with the Assassin's GUI, except with gray pixels instead of blue.
![image](https://user-images.githubusercontent.com/44556728/90323422-3ee6ee00-df2f-11ea-9d35-bd5a5e973f49.png)

The Primordial Merchant, Primordial Spellbinder, and Primordial Wizard have some extra black pixels on the left side of their GUI:
![image](https://user-images.githubusercontent.com/44556728/90323442-7d7ca880-df2f-11ea-9ce3-b3ac34a3c711.png)

When you hover over the arrows in the Troll Trader's GUI, it causes them to glitch. When not hovered over:
![image](https://user-images.githubusercontent.com/44556728/90323451-9422ff80-df2f-11ea-8f8b-704146e74108.png)
When hovered over (its hard to tell the difference on Github but if you test in-game you'll notice a difference):
![image](https://user-images.githubusercontent.com/44556728/90323453-9d13d100-df2f-11ea-8837-91254a8e6762.png)

The arrows in the Professor's GUI have the white parts as transparent:
![image](https://user-images.githubusercontent.com/44556728/90323474-d2202380-df2f-11ea-8127-2dad7db71fae.png)
![image](https://user-images.githubusercontent.com/44556728/90323480-d8160480-df2f-11ea-97dc-5ed0ce1c775e.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Interact (right-click) an Undead Herald, Primordial Merchant, Primordial Wizard, Primordial Spellbinder, Assassin, Troll Trader, and/or Professor.
2. See error

**Expected behavior**
None of these graphical glitches are present. 
1. For Undead Herald and Assassin, the extra pixels are not present.
2. For Primordial Wizard, Primordial Spellbinder, and Primordial Merchant, the black pixels are white-colored.
3. For the Troll Trader, the texture doesn't glitch like other NPC guis.
4. For Professor, the inside of the arrows are white-colored.

**Comment by Tslat** [comment]
Fixed in next version
