### ISSUE TITLE
Make the Lelyetia Realmstone in the Realmshifter GUI properly overlap the arrow.

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1806]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Realmshifter's GUI

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
In the GUI for the realmshifter, there is a Lelyetia Realmstone next to the right arrow, the right arrow cutting it off weirdly:
![image](https://user-images.githubusercontent.com/44556728/90323125-e4e42980-df2a-11ea-80c6-8e3b327df674.png)

This should be changed so that it properly overlaps, like the Creation Banner does in the Undead Herald GUI:
![image](https://user-images.githubusercontent.com/44556728/90323131-f9282680-df2a-11ea-8c20-ba17dba061ad.png)

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
Redesign the GUI so there's no overlap at all (move the realmstone, etc)
**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Not that I know of.

**Comment by Tslat** [comment]
Fixed in next version
