### ISSUE TITLE
Erebon Scythe Is Underwhelming

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#181]
Erebon Scythe is a good weapon, but compared to the other Scythes, it struggles to find a niche.

Selyan: Probably the best Scythe in the game. Consistent, has a great ability, and great damage output.
Pluton: Also great, a RNG weapon is a great concept. Although its not very consistent, however pretty balanced.
Luxon: Not sure, depends what soul power is going to do in 3.0. I mean in 1.7 it was a combo with tablet of strength.

And last and but not least, 
Erebon: This Scythes ability is lighting opponents on fire which does 1 damage every 1.5 seconds. Since you kill most mobs at this stage in the game in 2 or 3 hits, it doesn't feel like it has a ability at all. Consistent? Sure it is but so is Selyan, Also every time I used this Scythe to test damage output, Pluton's always out performed it.

I purpose that it should give Wither III, This gives it a faster effect that makes it ability more noticeable during combat.

I guess you could get rid of its ability and make it do 25 damage, but that would make it boring.

I hope soul power is good in 3.0 :3.

**Comment by Cruuk** [comment]
You could just maybe make it so it does +2-4 extra damage to enemies on fire.  Not sure. It would still set enemies on fire on hit, making it more like Hot Shot. Making it offensive-based but without the RNG. (Pluton's is still really good)
Though I think it should also have a additional minor ability (preferably fire-based) to make it unique from Hot Shot, not sure what though...

Erebon Stickler already gives Wither, and I want the Erebon weapons to keep this duality of harmful potion effects (fire and wither, poison doesn't fit cause it's color doesn't fit with Erebon).

I do want to keep the fire, but I do agree it should be buffed. Something involving fire and damage? Hmm...

**Comment by Tslat** [comment]
Done after snapshot 9
