### ISSUE TITLE
Lunar Archgun cannot use Glowing Holly Arrows as ammo

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1812]
**Mod Version**
What version of the mod are you on?
3.3.4
**Describe the bug**
lunar archgun can't use glowing holly arrows as ammo
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to anywere
2. Get a lunar archgun
3. get some glowing holly arrows
4. try to shoot
5. See error

**Expected behavior**
i expected it to shoot normaly
**Screenshots**

**Comment by Tslat** [comment]
That's not a version number.

**Comment by Hamburger666** [comment]
It's 3.3.4
