### ISSUE TITLE
Archaic Ladder (breakable) does not exist in the creative inventory

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1815]
**Mod Version**
What version of the mod are you on?
3.3.4

**Describe the bug**
The breakable versions of the immortallis blocks are present in the creative inventory....except for the Archaic Ladder, which is absent.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the creative inventory.
2. Look for the Archaic Ladder, and maybe even the other immortallis breakable blocks.
3. Notice that Archaic Ladder is absent, but the other breakable blocks are present.

**Expected behavior**
The Archaic Ladder (breakable version) is present in the creative inventory.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/90442398-978dc680-e0a8-11ea-88a7-f6dfdaada7a0.png)

**Comment by Tslat** [comment]
Done in 3.3.5
