### ISSUE TITLE
Infusion and Pixon Level Requirements

### ISSUE THREAD

**Issue by RugratCoder94** [Tslat/Advent-Of-Ascension#1816]
Pixon harvesting levels should be changed to where they are more in line with the new dimension progression. Right now the second harvestable pixon is in a tier 3 dimension, and there are several high level pixons in tier 2 dimensions. The order just doesn't make sense right now. I'm not saying all tier 2 pixons should be the same level and such, but the level 10 harvestable pixons should be ones in a more accessible / lower tier dimension.

**Comment by Tslat** [comment]
This is a lot harder than it sounds lol

**Comment by yamijuan** [comment]
So I ran into this issue too. What's the reason of unlocking lower exp pixons into end game tier dimensions? I believe this just was a sideeffect of "hiding" realmstones into challenges inside other dimensions, and ended up like this. Am I right?

**Comment by Cruuk** [comment]
> 
> 
> So I ran into this issue too. What's the reason of unlocking lower exp pixons into end game tier dimensions? I believe this just was a sideeffect of "hiding" realmstones into challenges inside other dimensions, and ended up like this. Am I right?

They just haven't been rebalanced yet. It was only earlier this year that dimension progression was revamped to be a lot more cleaner. The same has not happened for stuff like the Pixons yet, and will likely be changed in Skill update.

**Comment by yamijuan** [comment]
was this fixed or just closed?

**Comment by EatingSilencer** [comment]
Def not fixed, just closed for some reason.
