### ISSUE TITLE
Lands of Lelyetia portal 

### ISSUE THREAD

**Issue by rechalow** [Tslat/Advent-Of-Ascension#1817]
I can't go back to overworld through the lands of lelyetia portal
I entered lands of lelyetia
But I can't get out
If this is a bug
Please fix it in the next version

**Comment by rechalow** [comment]
Mod version is 3.3.4

**Comment by EatingSilencer** [comment]
So when you walk through the portal it just doesn't work?

**Comment by rechalow** [comment]
Yes, it won't let me through

**Comment by EatingSilencer** [comment]
Are you on singleplayer or multiplayer? Also, post the latest.log.

**Comment by Tslat** [comment]
Sounds like a catserver problem

**Comment by rechalow** [comment]
I'm single. I don't have a server

**Comment by Tslat** [comment]
Does it happen consistently? or only on this one world you have?

**Comment by rechalow** [comment]
Yes, whenever I enter lands of lelyetia, I can't get out

**Comment by Tslat** [comment]
Try it on another world with no other mods

**Comment by rechalow** [comment]
I don't have a computer. I'll do you test tomorrow morning

**Comment by rechalow** [comment]
I tried, but I still couldn't get out when there was only AoA mod

**Comment by Tslat** [comment]
Can you provide the latest.log file

**Comment by rechalow** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/5094475/latest.log)

**Comment by Tslat** [comment]
It looks to me like you're lagging so much that the game can't even get enough ticks in to teleport.

You're dropping ticks everywhere

**Comment by rechalow** [comment]
But I runs very smoothly, how can I solve it

**Comment by rechalow** [comment]
I can run all the dimensions except lands of lelyetia

**Comment by Tslat** [comment]
Install Phosphor

**Comment by Hamburger666** [comment]
where is your portal?
i think if it's in the inverted layer this happans
my portal generated at y=10 and i coulden't get back in, my player modal just ignores the portal block
so i moved the portal in overworld to y 60 and it works fine ( i got back to overworld by putting everything in a chest and suffocated myself with water)

**Comment by Tslat** [comment]
Portal blocks don't care about position, they're coded to _always_ teleport you.

More likely you just had the lag issue too.
Install Phosphor

**Comment by Hamburger666** [comment]
but i run at 60-90 fps
maybe i need to see src code to understand
XD

**Comment by Tslat** [comment]
Install phosphor and try it.

FPS isn't everything

**Comment by Hamburger666** [comment]
hmmmm
i'll take it
maybe i'll never lag again with phosphor

**Comment by Hamburger666** [comment]
wait
i think my problem is somehow the portal block cannot interect with the player(me)
so i had to take damage or reload chunk to let me go back to overworld by the portal
but who needs LoL when you have shryelands realmstone
