### ISSUE TITLE
server error (?

### ISSUE THREAD

**Issue by twiceloona** [Tslat/Advent-Of-Ascension#182]
the last snapshot 1.12.2
hello! i am using this mod with friends in a server and there are skills and resources, ores too. but there aren't mobs or events! we were expecting to fight in the first full moon night but there wasn't anything, what's more we can see the skills but we can't level up them. (i am not good with english, sorry)

**Comment by BloodERazor** [comment]
@twiceloona mobs and events haven't been added to the 1.12 version yet.

**Comment by Tslat** [comment]
As BloodERazor stated, the snapshot doesn't contain any mobs or events yet.
