### ISSUE TITLE
Mega Runestones with mending and unbreaking 3 is way too overpowered

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1829]
**Describe/name the item/content this suggestion relates to**
Mega Runestone ofc, the runador boss summon item
Actually wait, Bone Horn can have Mending too! add that to the list

**Describe the change/balance you think would be good to see**
plz make Mega Runestone unenchantable since with a normal 1 spawner grinder the Mega Runestone enchanted with Mending can be repaired again and again, providing infinite loot for the player if he/she is willing to bully clunkerhead. This is extremely overpowered and should not exist for the sake of Clunkerhead

**Add any alternative implementations you think might work**
maybe modify the recipe json and make it yield 6 Mega Runestones insted of one that's breakable and enchantable

**Include any additional background information**
I definitely didn't abuse this and get ornate clunkerhead statue before coming here
also i will be glad if the particle trail of some guns' projectile can be semi-transparent or toggle-able in config, cuz it's blocking the enemy and making me miss shots

**Comment by Hamburger666** [comment]
wow that is so fast
i do hope the 1.15.2 AOA version is coming as fast ? :P

**Comment by Tslat** [comment]
Fixed in next version
