### ISSUE TITLE
(Tslat 1.1.3) Going from The Shyrelands to the Overworld doesn't always return you to the portal you entered from

### ISSUE THREAD

**Issue by BloodERazor** [Tslat/Advent-Of-Ascension#183]
Mod Version: Tslat 1.1.3 (1.7.10)

When exiting an AoA dimension (excluding Greckon/Runandor) from a different portal than the one you entered from, back to the Overworld, you are usually sent to the portal you entered from in the Overworld; however this isn't the case with The Shyrelands as it can either send you to another existing portal or create a new one.

Please can you modify this so the Shyrelands' portals function the same as most of the other AoA portals, unless this part of the portal system is simply going to be overhauled anyway?

_When I initially discovered this on the official server I thought my portal had been destroyed._

**Comment by Tslat** [comment]
Support for 1.7.10 has been dropped
