### ISSUE TITLE
Extraction is too hard to level up and the award at level 95 is just a pathetic shovel

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1832]
**Describe/name the item/content this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Extraction is very hard to level up. Like seriously i don't think anyone have got the Extraction level 1000 achivement without cheating. The shovel thing you get requires you to lower it's durablity in order to make it dig faster which is not useful since it has 3000 durablity and normally people like to give their tools unbreaking and or mending, but with unbreaking 3(4 if infused) and mending it's almost impossible to wear down, potentially making it useless and out-ranked by energistic shovel, ornamite shovel and soulstone shovel

**Describe the change/balance you think would be good to see**
A specific and detailed description of what you want to see changed.
Either overhaul the shovel and give it more effects(e.g. self-heal when mining, this effect does not trigger when a boss is alive) 
Or rework the extraction device to not consume the lava upon unsucessful use(which outputs a cobblestone insted of an obsidian)

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
yes there is, and not just one.
**first alternative:** make the extraction device yield slightly better loot and make it give way more xp on a successful extract
then make something like Terraria's Extractinator that allow various blocks (stone, cobblestone, dirt, sand, gravel etc.) to be extracted for some normal loot and gives a lot less xp on use
**second alternative:** since veinminer is a thing, the mining speed of the shovel doesn't matter that much. so make it veinmine when the player is shifting or something

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
i got the idea that this shovel is not a good idea when i saw it's tool tip and effect in wiki
then i used /give @p aoa3:occult_shovel 1 3000 {Unbreakable:1} to obtain the fastest form of the shovel(wait it's not working with other mods installed) and gave it efficiency 6 (through infusion). then it mines faster than gold shovel with efficiency 6 and haste 2 
so then i thought "this shovel is so broken, how should i get it legit then, it must be very rare" 
and i looked it up on wiki and decided to post this when i saw "obtained from Extraction."
everyone should know that extraction in aoa is a pain in the neck

**Comment by Hamburger666** [comment]
sorry for issuing such an essay

**Comment by Tslat** [comment]
Don't worry, everyone thinks the same thing.

**Comment by Hamburger666** [comment]
XDD
