### ISSUE TITLE
is Brace supposed to be like this

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1834]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
bug 1:
umm... i made 2 Megaguns and gave one of tham Brace. then i tried to use them but seems to me that the off hand one's holster time is not just stacking onto the main hand one but the main hand one is stacking onto the off hand one too, making it very slow.
bug 2:
 you made the shot cooldown for every gun to work like ender pearls. but then putting ender pearls in both offhand and main hand can only trigger one throw since the other one will enter cooldown when the main hand one throws. this made it impossible to duel wield two guns of the same kind and shoot 2 bullets at a time, making brace almost useless.

**To Reproduce**
Steps to reproduce bug 1:
1. Go to Minecraft
2. Click on any world with cheat enabled/ is creative
3. /give @s aoa3:megagun and do it for twice 
4. /enchant @s aoa3:brace to one of them
5. try to duel wield them and notice the unfairly long unholster time compared to wielding one mega gun at a time
6. calculate the ticks and notice that after calculation it's not 1.82 * 2 seconds
7. See error

Steps to reproduce bug 2:
1. Go to Minecraft
2. Click on any world that is creative
3. get two of the same guns/shotguns/archerguns
4. /enchant @s aoa3:brace to one of them
5. try to duel wield them and shoot
6. notice that only one gun/shotgun/archergun shoots
7. See error

**Expected behavior**
for bug 1:
it's not supposed to be this long

for bug 2:
both were supposed to shoot in real life
i guess you make the holster time mechanic to mimic real life and balance guns at the same time
but then y make duel wielding like this

**Screenshots**
oh well nope it's impossible to screenshot a gif and the bullet is just too fast for me to capture

**Possible ways to fix** (optional)
If possible, suggest a method to fix this bug.
for bug 1:
well i think either give guns with brace a lesser unholster time or make weapons in offhand unholster faster

for bug 2:
don't use ender pearl's cd mechanics, it's not supposed to be like that. anyways you already have holster time to prevent players from using number keys to quick switch and ignore shot cd which counters the problem very well

**Comment by Tslat** [comment]
Yes, it's intended.

Dual-wielding guns is extremely powerful, and needs to come with heavy offsets to counter

The second part is unintended though, I'll check it out

**Comment by Hamburger666** [comment]
oic
duel weilding megaguns can shread everything with the 40dps
understandable, have a great day

**Comment by Hamburger666** [comment]
it's ok for snipers cuz double mineral is way too overpowered, even if it's mineral + the gun used to make it( i used haste 100 to remove the unholster time lol )
