### ISSUE TITLE
Various Texture Changes

### ISSUE THREAD

**Issue by NeoVolt** [Tslat/Advent-Of-Ascension#1837]
So, I'm assuming you probably know that me and Equidas have been making a texture pack for the mod, and well, i'm finally putting it here as a sugguestion for some texture changes. Currently it contains a lot of various stuff from the mod (I suggest looking through the .zip file itself as the curseforge page doesn't list everything in it atm)

https://www.curseforge.com/minecraft/texture-packs/aoa-otherworld/files/3045764

As a side note, you don't have to add in all the textures (if you choose to add in any at all), you can choose which and if you want you can also ask me to change some if nescesary.

**Comment by Hamburger666** [comment]
oh! a texture pack for AOA!? how noice. i must check it out lel
