### ISSUE TITLE
Exp flask is good, so make it obtainable

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1838]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Exp flask

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
maybe make it a boss drop or a secret award for defeating the ender dragon without destroying any crystal or give it a crafting recipe.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
make it an award for getting level 100 in any skill 

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
my own idea while looking through the wiki

**Comment by Tslat** [comment]
Ok
