### ISSUE TITLE
Grappling Hook Mod exists

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1839]
in the mod there's something called "Long Fall Boots" which allows the wearer to ignore fall damage, i think it should act like elytra & the varius helmets that does not have it's repective armor in AOA

**Comment by Tslat** [comment]
In what way?

**Comment by Hamburger666** [comment]
i think it's "Stacks With Any Armor Set", right?

**Comment by Tslat** [comment]
Not really possible with the current implementation
