### ISSUE TITLE
Rammerhorn Drop

### ISSUE THREAD

**Issue by Terenx** [Tslat/Advent-Of-Ascension#184]
Rammerhorn Drops

Rammerhorns are tanky mobs that deal big knockback but have zero drops, why not add leather to allow them to drop something for a 70 health behemoth.

You could probably also make it drop something like beef or anything else related to cows or such, after all they really look like giant bulls

I have zero idea if this has been asked for before, I bet a lot of people were asking for drops to a lot of mobs without any like cyclops but I bet nobody asked for rammerhorn specifically

**Comment by EatingSilencer** [comment]
By Rammerhorn, I presume you mean Rammerhead? Rammerhorn is a minion.

Also, Rammerheads do drop something - they drop Rammerhead Hide at a 25% chance. But I suppose it could be nice if they dropped something else.

**Comment by Tslat** [comment]
3.2 Adds drops to stuff
