### ISSUE TITLE
I swear i didn't change the config, but i found this next to my home where there's already one of them

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1841]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
2 of the cove thingys generated near my home(2 chunks away) and directly below my house there's a cove made into a grinder

**To Reproduce**
Steps to reproduce the behaviour:
well i do not think this is doable

**Expected behavior**
it's not supposed to be this common, also how did they generate right in the same chunk

**Screenshots**
![image](https://user-images.githubusercontent.com/68740916/91715782-faab4d00-ebc0-11ea-9f8a-72c51c49f6b1.png)
![image](https://user-images.githubusercontent.com/68740916/91715915-3219f980-ebc1-11ea-8177-cb354e60bcec.png)

**Comment by Tslat** [comment]
RNG can do this
