### ISSUE TITLE
Craxxeus is too weak compaired to the AOA2 version, plz restore it's "Strongest Boss" title

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1842]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Change Craxxeus

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
how it is in AOA2, how it should be in AOA3

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
nope, only thing is the explosion can be removed , which is very annoying

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
nope

**Comment by Tslat** [comment]
What strongest boss title?

**Comment by Hamburger666** [comment]
it's named as the strongest boss out of all in AOA 2

**Comment by Tslat** [comment]
Where

**Comment by Hamburger666** [comment]
community
XD

**Comment by Hamburger666** [comment]
we call it the strongest
bcuz it's a bit too strong
but 1.12 pvp is annoying
so i think removing the explosion so that even if you die you're stuff will not be blown up
making it more fair

**Comment by Tslat** [comment]
Why are you calling it the strongest if it's not the strongest? lol

**Comment by EatingSilencer** [comment]
I'm confused, are you advocating to change it back to how it was pre-3.0, or...?

**Comment by Hamburger666** [comment]
no
i think making it's attacks like pre 3.0 but different pattern

**Comment by EatingSilencer** [comment]
Oh, I think I misread it before.

Regardless, craexxeus will likely be changed when bosses get redone, whenever that happens.
