### ISSUE TITLE
The Diamond Bowl sometimes cannot harvest an entire Pixon in one use.

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1846]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
Diamond bowls cannot harvest an entire pixon but the wiki said so

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Desktop
2. Click on Minecraft.exe
3. Click on Single Player
4. Make a new creative world
5. Spawn a few Pixons and get a Diamond Bowl
6. Use the diamond bowl on the pixons
7. Notice that some pixons survived while some got instantly killed
8. See error

**Expected behavior**
"The Diamond Bowl can harvest an entire Pixon in one use."
that should happan

**Screenshots**

**Comment by Tslat** [comment]
It's not intended to

The wiki is outdated info

**Comment by Hamburger666** [comment]
oic
