### ISSUE TITLE
Kror is a tier one boss not the final boss

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1848]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
he deals **90 damage**

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
do you expect anyone to fight kror with end-game gear? 90 damage is pure non-sense
and for some reasons i can't block it with a shield
nerf plz

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
no

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
nope

**Comment by EatingSilencer** [comment]
Bosses haven't been rebalanced yet, I can imagine that Kror will be changed eventually. Though tbh I don't think its terribly bad if a dimension has a boss that needs to be saved for later.

**Comment by Hamburger666** [comment]
well it's not bad but also not good
like Skeletron, they both one-shot
and they're both tier 1 bosses
