### ISSUE TITLE
Mobs spawning inside portals

### ISSUE THREAD

**Issue by Terenx** [Tslat/Advent-Of-Ascension#185]
1.1.3 Tslat Version

Mobs seem to spawn inside of portal blocks, this not only makes bases with slabs everywhere obsolete when portals are nearby, but could also cause players to be swamped with mobs if they spawn in a nether portal, aka a portal that actually teleports whats tossed/pushed into it.

There's not much steps to reproduce this all you have to do is have some portal blocks and wait placed down and wait, it may not look clear when you just have a single portal but I bet if you were to go to creative and make a giant platform with, lets say, Iromine portals (what I saw the mobs spawn in) it should become clear they spawn inside portal blocks.

I have no clue what this means for what I Expected to happen, I just expected mobs to not spawn inside portal blocks.

Stupid me decided to kill the Ghostly Cyclops that appeared in my Iromine portal

**Comment by Tslat** [comment]
Can't really do anything unless I know what version it's on.

**Comment by Tslat** [comment]
1.13 is no longer supported
