### ISSUE TITLE
Is Trackers supposed to drop god apples

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1850]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
i killed a Tracker and he dropped a god apple. but i don't see any loot table containing god apple

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Minecraft
2. Go to land of lelytia
3. start spawning Trackers and killing them
4. if you're RNG is good you can get a god apple in no time
5. See error

**Expected behavior**
it isn't supposed to drop a god apple

**Screenshots**

**Comment by EatingSilencer** [comment]
Yes they are supposed to drop them, see: [rare table](https://adventofascension.gamepedia.com/Rare_Table)

**Comment by Hamburger666** [comment]
SO THAT'sY I GOT A TON OF XP BOTTLES OUT OF MY GRINDER

Tslat <notifications@github.com> 于2020年9月4日周五 上午3:45写道：
