### ISSUE TITLE
The Ender Dragon Stopped Dropping Loot After The Second Defeat

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1856]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
title, also i made sure the final blow is done by my looting 3 sword

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Minecraft
2. Click on New World
3. goto the end
4. kill the dragon with anything but /kill @e[type=ender_dragon]
5. resummon it
6. kill it again
7. resummon it again
8. kill it yet again
9. See error

**Expected behavior**
WHERE IS MY LOOT

**Screenshots**
nah

**Comment by Hamburger666** [comment]
I WANT GOLDEN FURY BUT CAN'T GET IT LEGIT
have to abuse JEI

**Comment by Tslat** [comment]
Unable to confirm, looks like it's fine

**Comment by Hamburger666** [comment]
maybe it's just me

**Comment by EatingSilencer** [comment]
Are you playing with other mods?

**Comment by Hamburger666** [comment]
yes

**Comment by Hamburger666** [comment]
ProjectE, Waystones, Portal Guns, toro health indicators, JEI, Bloodmoon

**Comment by EatingSilencer** [comment]
Maybe try it with only AoA?

**Comment by Hamburger666** [comment]
hmm
