### ISSUE TITLE
New Item Suggestion #5: Rune Pouch

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1857]
The Rune Pouch is a formerly removed item, i think it can be added back in.
The Rune Pouch is a bag-like item that allows the player to store runes inside. The runes stored inside can be consumed by staves like normal. The player must reach Runation lv 100 in order to open the pouch. the pouch's inventory have one more row than a single chest. The Rune Pouch is bought from the Runation master for one Lunaver coin.

This may be the savior for all mages since they may fill their inventory up with runes normally, but with this item they won't.

**Comment by Tslat** [comment]
I removed it for a reason.

**Comment by Hamburger666** [comment]
what is the reason then

**Comment by Hamburger666** [comment]
what is it then


Tslat <notifications@github.com> 于2020年9月5日周六 上午10:56写道：

**Comment by Tslat** [comment]
It serves no purpose but to remove the only downside staves have.

If I wanted it in the mod I wouldn't have removed it

**Comment by Hamburger666** [comment]
oic

Tslat <notifications@github.com> 于2020年9月5日周六 上午11:01写道：
