### ISSUE TITLE
Gravity Mega-Blast

### ISSUE THREAD

**Issue by Terenx** [Tslat/Advent-Of-Ascension#186]
1.1.3 Tslat

I was right clicking fast to try and escape as quicly as possible wit my Gravity Blaster when all of a sudden I was shooting far higher than my expected destination, I tested this out with an autoclicker in singleplayer to find out that it can not only skyrocket you if you right click a bunch for the same price, if your falling it can also not work at all!

First of all you need a Gravity Blaster from Bush Babies, then get a really good clicking finger or an autoclicker, right click really fast either standing on ground or falling, this only works sometimes though, but its noticeable when it does work.

I expected to fly up around 20 blocks to the top of a nearby precasian tree when I skyrocket above the clouds when clicking fast to get up there as quickly as possible

![2018-12-22_23 18 33](https://user-images.githubusercontent.com/44249598/50380973-0f8bbb00-0640-11e9-986f-e3daa95c4707.png)

**Comment by Tslat** [comment]
Has been fixed in newer versions of the mod
