### ISSUE TITLE
/aoawiki command is missing from /help

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1862]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
The /help command lists off all aoa commands in the game it seems except for /aoawiki, which is missing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure chat is enabled.
2. Type /help, then press tab.
3. Notice how /aoawiki is missing from the list.
4. Now type /help 1, and press enter. Check the list for aoawiki, then do the same with every help page (/help 2, /help 3, etc). Notice that there's no aoawiki command.

**Expected behavior**
/aoawiki command shows up in /help command's lists.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/92314646-8b5ea000-efa8-11ea-892c-574b58653327.png)

**Comment by Hamburger666** [comment]
nani!?

**Comment by Hamburger666** [comment]
what does /tslat do

**Comment by Tslat** [comment]
Fixed in next version
