### ISSUE TITLE
When the interface size is medium, the picture will not be clear.

### ISSUE THREAD

**Issue by seien210300928** [Tslat/Advent-Of-Ascension#1864]
When the interface size is medium, the picture will not be clear. I don't know if it is because my screen is 4K. I hope the author can pay attention to it
The above is from BiliBili up translated by Baidu

**Comment by EatingSilencer** [comment]
Can you post a picture?

**Comment by seien210300928** [comment]
![捕获](https://user-images.githubusercontent.com/68688963/92317106-78db7980-f02f-11ea-839b-a7d95ccc802b.PNG)

> 你能贴一张照片吗？

**Comment by seien210300928** [comment]
> 你能贴一张照片吗？

I am Chines

**Comment by seien210300928** [comment]
> 你能贴一张照片吗？

But in the case of 4 × interface size, the text is normal

**Comment by seien210300928** [comment]
4×
![捕获](https://user-images.githubusercontent.com/68688963/92317153-37979980-f030-11ea-872a-bfe3eedd7d26.PNG)


> Can you post a picture?

**Comment by seien210300928** [comment]
> Can you post a picture?

I don't know the situation in English, but I think it's about the same. I hope the author can pay attention to it. Pictures and words are two important factors that affect the game experience

**Comment by Tslat** [comment]
There's not much I can do about it to be honest

The unicode font is very thin, and downscaling causes it to error, this is just due to how mc renders font.

I'm closing this issue because I'm aware of it, but as of yet I don't think I have a solution besides just telling you to use auto/large scale
