### ISSUE TITLE
Fragmented Anima Stones cannot instant-grow melon stems and pumpkin stems

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1865]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
Fragmented Anima Stones can insta-grow crops and saplings, but not melon or pumpkin stems.

**To Reproduce**
Steps to reproduce the behaviour:
1. Plant pumpkin seeds and/or melon seeds on farmland.
2. Use a fragmented anima stone on them.
3. See error. You can compare by using the fragmented anima stone on any other crop or sapling.

**Expected behavior**
The melon stem and pumpkin stem are instantly grown.

**Comment by Tslat** [comment]
They grow fine for me.

If you mean fully grown stems won't spawn blocks, then that's normal for bonemeal

**Comment by EatingSilencer** [comment]
I believe there was a misunderstanding of this bug. I meant that the Fragmented Anima Stones do not make the melon stem or pumpkin stem instantly grow, instead it makes them partially grow. I am not referring to instantly spawning melon blocks and pumpkin blocks.
