### ISSUE TITLE
Post-rendering entity in World

### ISSUE THREAD

**Issue by GoldenDecoder** [Tslat/Advent-Of-Ascension#1868]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
When utilizing JEI in conjunction with AoA being installed some of the entities when clicking on their recipes causes a crash on the client side. This was seen on two different platforms. On my platform (See attached crash report) I was checking to see how to craft a Crystocore. On another platform with one of my players they've mentioned they were trying to craft a silver coin and it created a very similar error and crashed their game. I'll attached the crash report at the bottom of this Bug Report.

**To Reproduce**
Steps to reproduce the behaviour:
1. JEI and AoA 3.3.5 installed
2. Click on Crystocore to see crafting recipe
3. See error

**Expected behavior**
What was expected when utilizing JEI was to see the crafting recipe associated with both items mentioned above. Instead it caused the game to crash

[crash-2020-09-02_14.58.13-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/5189562/crash-2020-09-02_14.58.13-client.txt)

**Comment by EatingSilencer** [comment]
What do you mean, click on Crystocore? Are you clicking on a spawn egg...? The boss statue? How would one craft an entity?

**Comment by GoldenDecoder** [comment]
> What do you mean, click on Crystocore? Are you clicking on a spawn egg...? The boss statue? How would one craft an entity?

The boss statue, sorry I'm still learning this mod.

**Comment by Tslat** [comment]
Looks like a problem with the MorePlanets mod to me
