### ISSUE TITLE
Full Tea Sink and active Filtration System don't drop anything when broken

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1869]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
Mining a filled Tea Sink or turned on Filtration System will cause no block to drop. This is opposed to the non-filled Tea Sink, and non-active Filtration System, which drop themselves when mined with the correct tool.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place a Tea Sink and fill it with water.
2. Go to survival mode.
3. Mine the Tea Sink.
4. See error. No Tea Sink is dropped.
5. Use commands to place an active filtration system (/setblock ~ ~ ~ aoa3:filtration_system_on).
6. Get a pickaxe,
7. Go to survival mode.
8. Mine the activate Filtration System.
9. See error.
10. For comparison, place down an empty tea sink and non-active filtration system and mine each in survival mode with the correct tools. 
11. They should drop themselves.

**Expected behavior**
The full Tea Sink drops an empty Tea Sink when mined.

The active Filtration System drop a non-active Filtration System when mined with the correct tool.

**Comment by Tslat** [comment]
Fixed in next version
