### ISSUE TITLE
Mining a full Extraction Device with a Silk Touch pickaxe will drop the full Extraction Device

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1870]
**Mod Version**
What version of the mod are you on?
3.3.5

**Describe the bug**
When an Extraction Device filled with lava is mined with a pickaxe enchanted with Silk Touch, it will drop a full Extraction Device rather than an empty one.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get an Extraction Device and place it down. Fill it up with lava.
2. Get a pickaxe enchanted with Silk Touch.
3. Go to survival mode. Mine the full extraction device with the enchanted pickaxe.

**Expected behavior**
The Extraction Device drops an empty version of itself when mined while full, rather than a full version.

**Comment by Tslat** [comment]
Fixed in next version
