### ISSUE TITLE
Nethengeic Wither's death text is duplicated.

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1871]
**Mod Version**
What version of the mod are you on?
3.3.6

**Describe the bug**
The death text of the Nethengeic Wither seems to be duplicated.

**To Reproduce**
Steps to reproduce the behaviour:
1. Defeat the Nethengeic Wither. Make sure chat is enabled.
2. See error

**Expected behavior**
Only one death text displays.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/92862179-68792500-f3c8-11ea-8750-feedf41d3b10.png)

**Comment by Tslat** [comment]
Fixed in next version
