### ISSUE TITLE
/help command is broken

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1872]
**Mod Version**
What version of the mod are you on?
3.3.6

**Describe the bug**
It seems a change in 3.3.6 broke vanilla mc's /help command. Attempting to use it causes an error message to display. This also affects the alias: /?.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the chat window and type /help or /? and press enter. Make sure chat messages are enabled.
2. See error
3. You can also try /help pageNumber or /help commandName. Also produces an error. The /? pageNumber or /? commandName do the same.

**Expected behavior**
The command works.

**Screenshots**
The error message I get from using the command:
![image](https://user-images.githubusercontent.com/44556728/92862582-e2a9a980-f3c8-11ea-8c7d-011bf74d3a48.png)

**Comment by Tslat** [comment]
Fixed in next version
