### ISSUE TITLE
/aoawiki command is broken

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1873]
**Mod Version**
What version of the mod are you on?
3.3.6

**Describe the bug**
The /aoawiki command seems to not be working. It shows up as a command you can do in the /help tab list and typing /aoawiki and pressing enter displays a message, but trying to search for a wiki page does nothing, no error message is displayed, simply nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open chat window and type /aoawiki pageName, for example /aoawiki Cyclops.
2. See error

**Expected behavior**
The command displays a chat message with a link to the searched for page.

**Comment by Tslat** [comment]
Fixed in next version
