### ISSUE TITLE
Infusion Table

### ISSUE THREAD

**Issue by infernalspectre** [Tslat/Advent-Of-Ascension#1876]
**Mod Version**
Tslat 1.1.3

**Describe the bug**
When attempting to use the infusion table to do enchanting (not holding an infusion stone in hand) all I get is a sound effect and no access to the gui mentioned one the wiki or any information about enchanting.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to set an infusion blueprint
2. Right click to attempt to use
3. Nothing happens

**Expected behavior**
The infusion table GUI opens

**Screenshots**

**Comment by Tslat** [comment]
That's because you're on an old version of AoA.

Update if you want newer features
