### ISSUE TITLE
Visage's clones appear on the roof of Immortallis

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1880]
**Mod Version**
What version of the mod are you on?
3.3.6

**Describe the bug**
The Visage mob has the ability to clone itself. However, the clones appear on the roof of Immortallis instead of in the room with it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Immortallis' eighth room, where the Visage's are. 
2. Make sure difficulty isn't peaceful. Spawn a Visage.
3. Fly above and out of the room so you can see the roof from above. 
4. See error. Might have to wait for a bit for the visage to spawn a clone.

**Expected behavior**
Visage clones appear in the room and not on the roof.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/93661087-00a78780-fa23-11ea-9a27-13751735d6b2.png)

**Comment by EatingSilencer** [comment]
It seems Occulent clones are affected by this too.
![image](https://user-images.githubusercontent.com/44556728/93661144-7c093900-fa23-11ea-9a3f-e670299e1642.png)

Unlike Visage this one is less apparent as Occulents can be found on the abyss' surface, but this could mean the ability doesn't work underground.

**Comment by Hamburger666** [comment]
hmmmmmmm
what about zargs

**Comment by EatingSilencer** [comment]
It does not effect zargs as far as I know.
