### ISSUE TITLE
Outside the Banker GUIs doesn't darken like other GUIs

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1884]
**Mod Version**
What version of the mod are you on?
3.3.6

**Describe the bug**
Lots of GUIs darken the outer parts of the screen surrounding them when the player has them opened. This is not the case for the banker GUIs however.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn any NPC besides a banker that has a GUI and open their GUI.
2. Close that GUI, then spawn a banker, doesn't matter which.
3. Open the banker's GUI.

**Expected behavior**
The background of the banker's GUIs is darken like other GUIs.

**Screenshots**
This is what a banker's GUI looks like:
![image](https://user-images.githubusercontent.com/44556728/93728604-a1668600-fb8e-11ea-9610-0d9a41885a5d.png)

Here is a comparison of a GUI with the dark background:
![image](https://user-images.githubusercontent.com/44556728/93728622-b4795600-fb8e-11ea-9edd-3a86c0673669.png)

**Comment by Tslat** [comment]
Fixed in next version
