### ISSUE TITLE
Add a command to inflict screen effects on the player's screen

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1886]
**Describe the new feature you think would be good to add**
A specific and detailed description of what you want to see.
I think it would be a good idea to add a command that allows you to inflict the mod's screen effects on the player's screen. At the moment there is no way to access screen effects without their original source.

Example for the command: /aoascreeneffect id time
An alias would be aoascreeneffects.

In the above example, id is the screen effect's id/name, while time is the amount of time (in ticks?) it lasts before disappearing.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
Not sure

**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?
Not sure

**Comment by Tslat** [comment]
I think I'll do this one, but I'm not sure when as yet. I'm generally not a fan of making changes that require localisation in patch updates because it causes the translation guys to be behind
