### ISSUE TITLE
hi guys i have tslat advent of ascension for minecraft 1.7.10 and hes dont drop me all loots pls hel me <3 <3

### ISSUE THREAD

**Issue by tommy489375892** [Tslat/Advent-Of-Ascension#1891]
### **1.1.2**

**hi guys i have tslat advent of ascension for minecraft 1.7.10 and hes dont drop me all loots pls hel me <3 <3**

**Comment by Tslat** [comment]
Update to 1.12

**Comment by EatingSilencer** [comment]
Tslat 1.1.2 is outdated anyway, Tslat 1.1.3 is the latest for 1.7.10.
