### ISSUE TITLE
Have the Battle Rage icon turn from orange to red at 180 Rage (instead of 150)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#1893]
**Describe/name the existing feature this suggestion relates to**
The Battle Rage icon.

**Describe the change or feature you think would be good to see**
Recently I decided to look into the exact details of how Battle Rage currently works- mainly the additional boost you get at high values of Rage. Thanks to Scimi's help, it turns out the extra boost was just moved from 150 Rage to 180.

Currently, the icon itself changes to a red color at 150 Rage. I have no proof of this, but I think it changed color as sort of a visual indicator of reaching the threshold for the extra 1.3x damage, making it a little misleading in modern days. Even if it wasn't used for that, changing the icon so that it turns red at 180 Rage instead would be a nice visual indicator for reaching the extra boost. I'm fairly certain there's nothing else that references this second 1.3x boost anyway.

Along with that, I'm pretty sure there's also nothing that tells you that Rage doesn't proc at all until it reaches 51 Rage or higher. So maybe the icon could be at a different color until changing to Orange at 51 Rage. Maybe yellow could work as an indicator when under 51 Rage?

EDIT: Wait shit Energy is yellow

**Comment by Tslat** [comment]
Done
