### ISSUE TITLE
infinite blank realmstones

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1894]
**Mod Version**
What version of the mod are you on?
3.3.6 ofc

**Describe the bug**
you can get infinite blank realmstones by right clicking with the worn book thing in your offhand and throw the blank realmstone on the ground

**To Reproduce**
Steps to reproduce the behaviour:
1. get a worn book and put it in your offhand slot
2. **make sure you had your mainhand slot empty**
3. do this: right click - press e(to clost the book window) - press q
4. keep repeating step 3 in a rapid manner
5. after 30 secs go to survival and pick the realmstones up to see your inventory getting filled 

**Expected behavior**
blank realmstones should count as present even if it's on the ground as an entity, so that you can't span a ton of them in mere seconds and sell the whole lot of them by turning them into another realmstone. for an instance: abyss realmstone

**Screenshots**
nope

**Comment by Tslat** [comment]
It's intended for players to be able to get as many realmstones as they need
