### ISSUE TITLE
Balancing Goofer's special ability

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#190]
A little while ago we found out that Goofer had a special attribute basically no one knew of, mainly because it's hard to notice it ingame due to the chance being so low.

Basically Goofer has a 1/6 chance to deal no damage, the chance is pretty minimal considering it doesn't take long for Goofer to attack again.
However, I think it's a neat concept that should stay, but with a bit of tweaking.

Goofer would still do high damage in general, have a bit less health than it currently has (150-200?), and the chance to deal no damage would be 1/3, and would play a wacky sound effect whenever it didn't deal any damage. Goofer would also still knock the mob back if it didn't do any damage, making it a bit more obvious. (if the mob isn't immune to knockback of course)
And the recipe for it's slab should be a little... *less* cheap.

This would make it way more comparable to the Mecha Cyclops. Mecha Cyclops would purely be the glass cannon, while Goofer is the tankier but riskier alternative with a big RNG factor.

**Comment by Tslat** [comment]
This was already changed in Snapshot 9
