### ISSUE TITLE
Physical mob versions of AoA's fish for 1.15.2

### ISSUE THREAD

**Issue by odw500** [Tslat/Advent-Of-Ascension#1901]
First of all, apologies if anyone has already suggested this.

In 1.15.2, as I'm sure you're aware, there are mob versions of fish that swim around in bodies of water which can be killed for the item version of themselves or collected in a bucket. An idea that occurred to me would be to have mob versions of AoA fish.

Since cooked variants of some AoA fish restore high values of hunger and saturation, some fish would of course be more rare, spawn in smaller groups and perhaps only at lower light/y-levels or in certain locations underwater (i.e. in regions with high amounts of kelp, inside ravines, around shipwrecks etc.)? I'm not sure how fish spawning works so I'll understand if this might not be possible.

Considering the number of types of fish that AoA adds I also understand this may throw off balance a little with how much hunger some fish are worth, but I don't think it would hurt much to adjust some of their hunger values to compensate.

**Comment by Cruuk** [comment]
Would be cool to have certain Fish be exclusive to certain dims with water like L'Borean/Gardencia/Vox ponds
