### ISSUE TITLE
Allow blocks with names in their GUI's name be changed when the block is renamed with an anvil

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1904]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Divine Station, Whitewashing Table, and Mending Table

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
When certain vanilla blocks are renamed with an anvil, placing them down in the world will show their new name in their GUI. This does not happen with Divine Station, Whitewashing Table, and Mending Table, and I think it would be consistent to make it happen.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
Not that I know of

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Not that I know of

**Comment by Tslat** [comment]
You can rename _containers_ in vanilla. Not random blocks
