### ISSUE TITLE
Add a way to freeze resource regeneration

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1905]
**Describe the new feature you think would be good to add**
A specific and detailed description of what you want to see.
Resource Systems

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
I think it would be interesting if there was some form of resource regeneration freezing. Energy, Battle Rage, Creation, and Soul Power can all regenerate naturally, but what if there was a way to freeze the regen of these temporarily so that they couldn't?

I'm merely suggesting a concept here, and it can be added in various circumstances:
1. new potion effects that freeze regen (as well as another potion effect that increases its regen speed)?
2. commands/gamerules that freeze it until reenabled.
3. armor sets that disable regen while offering other benefits.

These are just examples of how it could be done.

**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?
Not that I know of

**Comment by Tslat** [comment]
But why
