### ISSUE TITLE
Pixons can still spawn if doMobSpawning gamerule is set to false

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1911]
**Mod Version**
What version of the mod are you on?
3.3.6

**Describe the bug**
Pixons are able to spawn if doMobSpawning is set to false, unlike other mobs. This should not happen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set /gamerule doMobSpawning to false.
2. Go and load new chunks in any dimension with pixons, looking for them.
3. Eventually you should find pixons.

**Expected behavior**
Pixons do not spawn if doMobSpawning is set to false.

**Comment by Tslat** [comment]
They're not mobs

**Comment by EatingSilencer** [comment]
I'm not sure that means a fix is not warranted.

**Comment by Tslat** [comment]
A fix for what?

**Comment by EatingSilencer** [comment]
Hmmm, I thought it did work for animals but mc wiki says it doesn't....
