### ISSUE TITLE
Better portal activation messages

### ISSUE THREAD

**Issue by Merepock** [Tslat/Advent-Of-Ascension#1916]
A majority of the messages shown when activating a portal are either incredibly vague or don't make any sense at all (Looking at you Ancient Cavern). I think many people would agree that the messages could be updated to better suit the theme, atmosphere and/or appearance of the dimensions.

For example:
* Precasia: "The lush forests of Precasia fill you with life"
* Creeponia: "You catch the scent of gunpowder seeping through the portal."
* Abyss: "You gaze into the Abyss, and the Abyss gazes back into you."
* Celeve: "The whimsical appearance of the portal seems deceiving as you hear maniacal cackling on the other side."
* Vox Ponds: "Toxic fumes fill your nostrils, causing a burning pain unlike any other." (Hinting that entering the Vox Ponds with no Hazmat Suit/Face Mask will kill you)
* Crystevia: "The crystalline portal glows with an assortment of vibrant colours."
* Mysterium: "The air around you begins to feel heavy with fungal spores."
* Ancient Cavern: "The champions of the four Gods await you for a test of combat prowess."
* Dustopia: "The vantablack portal stands before you, seemingly leading into nothingness."

**Comment by EatingSilencer** [comment]
Is the Dustopia portal really vantablack? Might just be better to say 'dark' portal.

**Comment by Sweaty07** [comment]
The portal is a particularly dark shade of black, so vantablack is the first word that sprung to mind.
