### ISSUE TITLE
Get too close to a monster and resource bars white out

### ISSUE THREAD

**Issue by Zeta-Patchouli** [Tslat/Advent-Of-Ascension#1926]
**Mod Version**
1.15.2 snapshot 1

**Describe the bug**
When I get close enough for the sword icon to appear while facing a mob, then the resource bars all turn white.

**To Reproduce**
Steps to reproduce the behaviour:
1. Walk up to a monster with your resource bars open, making sure to have the + on the monster

**Expected behavior**
The resource bars to remain how they normally should

**Screenshots**
https://imgur.com/ws14zPY

**Comment by Tslat** [comment]
I'm not sure this is something I can fix on my side, might need to take this to the dev of your mob health mod
