### ISSUE TITLE
Ancient Teleporter can't be relit once lit unless broken.

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#193]
**Mod Version**
AoA3-Snapshot 9

**Describe the bug**
If you light the ancient teleporter with a realmstone, the portal can't be changed with another realmstone unless you break the existing portal.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an ancient teleporter.
2. Activate the portal with a realmstone.
3. Try and change the portal with a different realmstone.
4. See that it does not work.

**Expected behavior**
The portal can be changed without breaking it.

**Comment by Tslat** [comment]
Fixed after snapshot 9
