### ISSUE TITLE
Weirdness when trading with NPCs

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1948]
**Mod Version**
What version of the mod are you on?
3.4 snapshot 1

**Describe the bug**
I've noticed some weird things when trading with the Hunter Master and Dungeon Keeper. Notably:
1. closing the trading GUI and reopening it causes any locked trades to unlock.
2. you can bypass the max amount of items until locking by shift-clicking. For example: trading one piece of Hunter Armor will cause the trade to lock. But you can by more than one of the same piece by shift+clicking the output with multiple sets of the input in the input slot (in this case, multiple lunaver coins).

**To Reproduce**
Steps to reproduce the behaviour:
The steps are described above.

**Expected behavior**
NPCs don't unlock their trades when opening and closing their GUI, and there should be no way to bypass the max items until locking.

**Comment by Tslat** [comment]
Can't seem to replicate this, it's working fine for me?

**Comment by Tslat** [comment]
Ah it seems to exclusively affect max-1-item trades
