### ISSUE TITLE
Separate the aoastructure list command into pages

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#195]
**Describe/name the existing feature this suggestion relates to**
The new command to spawn structures added in snapshot 9

**Describe the change or feature you think would be good to see**
After so long we finally have a command to spawn AoA structure, so far I think it's pretty damn neat, but I think it can be improved.

The command also includes a list, filling your chat with every single structure name at once.
![image](https://user-images.githubusercontent.com/38159897/50404238-6d142a80-075a-11e9-960c-10c497a6d729.png)
(You can't even see all of them in the pic, it scrolls up)

It is a little spammy, so I think it should be changed so that it's separated into 10-12 pages like the /help command is.

![image](https://user-images.githubusercontent.com/38159897/50404260-ab114e80-075a-11e9-9a6e-e9c1fc6c2870.png)

Doing /aoastructure list 4 would take you to page 4, doing the command without any number would put you on page 1 by default, etc...

I think this would make it easier searching for a certain structure you don't know the name of, as trying to read through that giant wall of text can be pretty annoying. (For me at least)

**Comment by EatingSilencer** [comment]
Good idea.

**Comment by Sagisolar** [comment]
How about a special creative only book that is filled with the names?

**Comment by Tslat** [comment]
Done after snapshot 9
