### ISSUE TITLE
Deep Case drops itself along with loot when mined

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#197]
**Mod Version**
AoA3-Snapshot 9

**Describe the bug**
When you mine a deep case, it drops both its loot and itself.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place down a deep case.
2. Go to survival mode (if not already) and get a pickaxe.
3. Mine the deep case.
4. See it drop itself and its loot.

**Expected behavior**
Deep cases should not themselves when mined.

**Comment by Tslat** [comment]
Fixed after snapshot 9
