### ISSUE TITLE
In structures with iron bars, the iron bars don't link up properly

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#1979]
**Mod Version**
What version of the mod are you on?
3.4 snapshot 1
**Describe the bug**
In structures with iron bars, the iron bars don't seem to link up properly. I've noticed this in the Ancient Cavern, and the Abyssal Lotto Hut.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a structure added by the mod that has iron bars.
2. See error

**Expected behavior**
The iron bars link up properly.

**Comment by Tslat** [comment]
Not going to be fixed until worldgen update
