### ISSUE TITLE
Crash AoA3: Shell Exit Code 255

### ISSUE THREAD

**Issue by m4tzzz** [Tslat/Advent-Of-Ascension#1988]
**Mod Version**
What version of the mod are you on?
1.15.2
**Describe the bug**
It wont let me boot up the game
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Launcher'
2. Click on 'Play'
3. See error

![Screen Shot 2020-11-21 at 2 19 46](https://user-images.githubusercontent.com/73796869/99871443-32aea480-2ba0-11eb-8527-4a4ef0e03fe7.png)

**Comment by Tslat** [comment]
This looks to be an out of memory issue to me
