### ISSUE TITLE
Ores can't be smelted.

### ISSUE THREAD

**Issue by IceWaterFallL** [Tslat/Advent-Of-Ascension#1989]
**Mod Version**
AOA3.4Beta1

**Describe the bug**
The ores in the game cannot be smelted. It's a bug? or it's a new update?
I use jei to check the recipes but i can't find anything about it.
It seems that everything that needs to get in the furnaces all can't get.

**Expected behavior**
Give me an answer and fix it!

**Comment by Tslat** [comment]
The smelting recipes aren't in yet :)

**Comment by IceWaterFallL** [comment]
> The smelting recipes aren't in yet :)
k
