### ISSUE TITLE
[1.15.2]Arrows appear abnormally when they hit pets

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#1990]
**Mod Version**
3.4

**Describe the bug**
Arrows appear abnormally when they hit pets
Crossbow will fly in the opposite direction
Bow will lose momentum

**Screenshots**
bow:
![111](https://user-images.githubusercontent.com/59332746/99876847-a5695f80-2c34-11eb-8410-c37a529ac5c7.png)
crossbow:
![222](https://user-images.githubusercontent.com/59332746/99876848-aac6aa00-2c34-11eb-93fb-9fbea568bb7c.png)
![2222](https://user-images.githubusercontent.com/59332746/99876849-ae5a3100-2c34-11eb-801a-50efd0024e33.png)
(In fact, it's quite beautiful to look at. lol)

**Comment by Tslat** [comment]
That's normal for MC with deflected projectiles
