### ISSUE TITLE
Loaded crossbows not held properly

### ISSUE THREAD

**Issue by Infernikko** [Tslat/Advent-Of-Ascension#2011]
1.15.2 Beta 

In 3rd person, loaded AoA crossbows are held the same as when they are unloaded, instead of how the vanilla crossbow is held.

![image](https://user-images.githubusercontent.com/41617467/99915775-98fd0980-2cfd-11eb-8928-b01fc69968da.png)

**Comment by Tslat** [comment]
This is hardcoded into MC, cus.. Mojang...

I don't think it'll be possible without a coremod to make this a thing, sadly
