### ISSUE TITLE
Pincher idea for 1.13+

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#202]
![pincher2](https://user-images.githubusercontent.com/44548547/50457998-bda4a700-0957-11e9-8b4c-ddd202aee201.png)
Since the ocean has stuff to explore now since 1.13, Pinchers are gonna make it annoying.
Unless you do this.

Make Pinchers only spawn in the tiny ocean ravines and deep oceans (tnx Cruuk)
Ocean ravine
![2018-12-26_21 30 56](https://user-images.githubusercontent.com/44548547/50457752-00fe1600-0956-11e9-87af-b183d8734e72.png)

Also give them the code of the Drowned (They only stay on the ocean floor, and doesn't swim).

**Comment by Cruuk** [comment]
Doesn't the deep ocean biome still exist in 1.13+? If so I'd say they should still spawn there as well, mainly to have a more wider area for them to spawn rather than just ravines.

Regular/frozen/whatever oceans would be safe from them but deep oceans and ravines would have them.
