### ISSUE TITLE
Switch the Lunar creation recipes of Lunar Staff and Celestial Staff

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#203]
(Discord repost!)
**Describe/name the existing feature this suggestion relates to**
The orbs required to make Lunar Staff and Celestial Staff at the Lunar Creation Station.

**Describe the change or feature you think would be good to see**
As we know there exists a set of "basic staves".
![image](https://user-images.githubusercontent.com/38159897/50483084-ebf9a500-099e-11e9-9e94-c632b8757e4c.png)
Each of them represent the most basic form of the rune they're affiliated with (don't ask about water). And in Lunar Staff's case, it represents the common theme of Lunar rune staves raining down projectiles, it's one of the weakest "falling projectile" staves which makes sense because it is the "basic" one right? (All the falling projectile staves are really strong at the cost of being hard to aim)

Look at Lunar Staff's Lunar creation recipe:
![image](https://user-images.githubusercontent.com/38159897/50483927-bb1b6f00-09a2-11e9-9c49-67c637ea86c8.png)
You see that orb in the bottom left corner? That's the Darklight orb from **Dustopia**.
Why does the simple "Lunar Staff" require going to Dustopia? At that point if you're using falling projectile staves you should have a better one at that point.

--------------------------------

Let's look at another staff: Celestial staff. 
![image](https://user-images.githubusercontent.com/38159897/50484270-6b3da780-09a4-11e9-8378-68f3ba433c36.png)

I'd personally consider this sort of an upgrade to Lunar staff, it is a bit harder to aim but it can deal some of the highest damage output in the whole game if you consistently hit with it, like more than double Lunar Staff's DPS.
Now lets look at it's Lunar creation recipe:
![image](https://user-images.githubusercontent.com/38159897/50484311-a6d87180-09a4-11e9-9210-78cca5386bcd.png)
That's a pretty basic recipe, why can such a powerful staff be obtained as early as Lunalus? Wouldn't it make more sense for **Lunar Staff** to only require 2 Lunar orbs, and for Celestial to be the latergame equivalent that requires going to Dustopia?

So yeah basically I think their recipes should be switched, as I think it would make a lot more sense in both cases. If Lunar Staff is really strong at Lunalus level just lower the damage to like 14-15...

**Include any additional background information**
Speaking of the Lunar Creation Station, when you craft an item the item should just sort of pop up above the center table rather than fly in a random direction like it currently does, with the Bedrock ocean gone I don't want to worry about the item I just crafted falling into the void.

**Comment by Tslat** [comment]
No longer relevant
