### ISSUE TITLE
Sunken Pirate Ship Dungeon for L'Borean

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#204]
I always thought it was interesting that L'borean is water themed dimension, but never explores the idea of a wrecked ship.

So I made this.
![2018-12-27_23 44 12](https://user-images.githubusercontent.com/44548547/50497668-cbc6f600-0a31-11e9-98ba-a88e028b3200.png)
(Probably will use different blocks than wood, but I used normal wood for this image. Also Amphibior don't spawn in this, just a place holder)

There will be treasure, and a new pirate themed mob that will spawn in it.

**Comment by Immortallis1** [comment]
Well l'borean is kind of like "untouched supposedly-underwater environment". Don't think that a pirate ship really fits it too much.
