### ISSUE TITLE
If commands are used to skip the sunrise threshold, the player's tribute isn't removed

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2046]
**Mod Version**
3.4 beta 3

**Describe the bug**
It seems that letting nightfall/sunrise happen normally has no issues. However, using commands like `/time add` and such to skip the first tick that the game declares it sunrise makes things weird with tribute effects.

Basically, you still get the actual effect at night, and it vanishes at day time, but if the initial sunrise tick is skipped, you'll still keep all the tribute you had, and when nightfall happens it will still grant you the tribute effect. As long as you can skip the initial sunrise tick, you'll keep the tribute forever. Not sure if you can do this legit in survival with another method.

**To Reproduce**
Steps to reproduce the behaviour:
Get any tribute full
Have nightfall happen
Use commands to skip to day without having the game consider it sunrise (event ending messages, etc.)

**Expected behavior**
I guess having the thresholds happen even when skipped? I don't know

**Comment by Tslat** [comment]
It does have a threshold (4, actually), but unless I check constantly throughout the day, there's not much else I can do about this
