### ISSUE TITLE
Jade, Rosite, and Sapphire should still require Diamond picks

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#205]
**Describe/name the existing feature this suggestion relates to**
The change to the Overworld ores in snapshot 9.

**Describe the change or feature you think would be good to see**
For those who don't know, as of 3.0 snapshot 9 *all* the ores found in the Overworld can be mined with an Iron pickaxe or higher, Limonite can even be mined with a Stone Pickaxe.

I think this is an interesting change, and kind of makes sense. Limonite is Iron strength, and Amethyst is Diamond strength, it would make sense for them to have the same requirements as their vanilla counterparts.
This includes other things like ammo being easier to get, Lyndamyte/Amethind being easier to get, etc...
And Runium is... Runium. At least Runation will be easier to start.

However my main issue is Iron-level picks being able to mine Jade, Rosite, and Sapphire. As far as I'm aware these items are essentially above Diamond so shouldn't they require a Diamond-level pick to mine? I still think Diamond should somewhat still be tied into Overworld ore progression.
It's not like Diamonds would be 100% required, Amethyst pick is Diamond-level right? It would still be able to mine those ore.
I don't know I just don't like the idea of an Iron pick allowing you to skip all the way to stuff like Jade and Sapphire. They're rare but if you know what you're doing they're really not that hard to find.

I just think it would make the progression more "cleaner". (Stone can mine Iron/Limonite, Iron/Limonite can mine Diamond/Amethyst, Diamond/Amethyst can mine Jade, Rosite, Sapphire, etc.)

------------------------

Also from testing, it appears that Limonite pick can mine ores like Emberstone and the ores in the dimensions, despite being Iron level... Yeah.

**Include any additional background information**
Speaking of Limonite Pickaxe...
![image](https://user-images.githubusercontent.com/38159897/50518094-b6b98980-0a68-11e9-9d95-9facb1f65f38.png)
Pretty busted pick huh

EDIT: Oh my
![image](https://user-images.githubusercontent.com/38159897/50520375-d191fb00-0a74-11e9-9b81-1fb54b014883.png)

**Comment by Tslat** [comment]
Done after snapshot 9:
- Increased harvest level of jade, sapphire, rosite ores
- Reduce harvest potential of limonite tools
- Fixed up damage values of tools vs their weaponry counterparts
