### ISSUE TITLE
Ornate trophy transparent side

### ISSUE THREAD

**Issue by Nebula240** [Tslat/Advent-Of-Ascension#2069]
**Mod Version**
AOA Beta 4- 1.15.2

**Describe the bug**
If you get to the side of the ornate trophy while shifting the side disappears and it becomes totally transparent.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place ornate trophy
2. Shift
3. Get close to it
4. ???
5. Voila, transparent side

**Expected behavior**
Fix the transparent side, since it looks weird and it might have other bad uses.

**Screenshots**
![error2](https://user-images.githubusercontent.com/62150697/100550154-b9c1e380-3256-11eb-8093-dd8444da9558.png)

**Comment by Tslat** [comment]
This appears to be a vanilla bug
