### ISSUE TITLE
Hiding Fungi turns red and stays invincible

### ISSUE THREAD

**Issue by Nebula240** [Tslat/Advent-Of-Ascension#2079]
**Mod Version**
AoA beta 4, 1.15.2

**Describe the bug**
Hiding fungi turn red and stay as invincible entities.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a hiding fungi
2. Hit it
3. ????
4. Errored fungi

**Expected behavior**
Fix this bug, it might be only a visual bug but it's annoying and its not the intended behaviour.

**Screenshots**
![2020-12-01_00 59 23](https://user-images.githubusercontent.com/62150697/100695682-7d82a600-3370-11eb-8bbd-995eefe67791.png)
![2020-12-01_00 54 07](https://user-images.githubusercontent.com/62150697/100695688-7f4c6980-3370-11eb-89a3-b9f90e70c7f7.png)

**Comment by Tslat** [comment]
Unable to replicate
