### ISSUE TITLE
Slight misalignment in partially-filled resource bars

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#208]
**Mod Version**
Snapshot 9

**Describe the bug**
When partially filled, the bottom of the resource bar between the unfilled and filled sides is slightly misaligned.

**Screenshots**
![Snapshot 9](https://media.discordapp.net/attachments/434160774546456594/528317310851612673/unknown.png)

**Comment by Tslat** [comment]
Fixed after snapshot 9
