### ISSUE TITLE
Deeplands task doesn't work

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2082]
**Mod Version**
3.4 beta 4

**Describe the bug**
Even at somewhere like y=3 or so, digging ore doesn't transform the Blank realmstone. I didn't try with every ore, but I did make sure to try with a vanilla and Advent ore. Mainly Iron, Jade, Amethyst, and Limonite I think.

**To Reproduce**
Steps to reproduce the behaviour:
Dig an ore at bedrock level with the Blank realmstone in the inv.

**Expected behavior**
The task working as it should.

**Comment by Tslat** [comment]
Same issue as the other harvest problems
