### ISSUE TITLE
1.15.2 Beta Crashes on Server

### ISSUE THREAD

**Issue by Sl1pstr3am** [Tslat/Advent-Of-Ascension#2088]
**Mod Version**
What version of the mod are you on?
I am on the 1.15.2 beta of the mod.
**Describe the bug**
When I load a forge 1.15.2 server with no other mods, the server crashes with this mod installed.
**To Reproduce**
Steps to reproduce the behaviour:
Run a forge server with this mod installed. 

**Expected behavior**
The server should start as usual. 
**Screenshots**
Crash report:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/3/20 8:54 AM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Advent of Ascension (aoa3) has failed to load correctly
§7null
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:200) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 28113954000 bytes (26811 MB) / 31521243136 bytes (30061 MB) up to 31521243136 bytes (30061 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xmx30g -Xms30g
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/server.jar object_holder_definalize PLUGINSERVICE 
		/server.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/server.jar capability_inject_definalize PLUGINSERVICE 
		/server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/server.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.47
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.47-server.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		forge-1.15.2-31.2.47-universal.jar Forge {forge@31.2.47 CREATE_REGISTRIES}
		AoA3-3.4-Beta-4.jar Advent of Ascension {aoa3@3.4-Beta-4 ERROR}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Tslat** [comment]
Beta 5 fixed this
