### ISSUE TITLE
Breaking the spawners in immortallis in survival mode turns them into pig spawners

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2098]
**Mod Version**
What version of the mod are you on?
3.4-Beta-5

**Describe the bug**
If you try to break one of the exposed spawners in Immortallis with a pickaxe, it replaces it with a pig spawner.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to break the spawners in Immortallis that are exposed to air with a pickaxe. Make sure you are in survival mode.
2. See error

**Expected behavior**
The spawners come back as a spawner with the original mob that spawned in them.

**Comment by EatingSilencer** [comment]
This appears to be a temporary change - they reverted back when I left the dimension and returned.

**Comment by Tslat** [comment]
This is a vanilla bug,  and is only aesthetic (it doesn't actually change, it's just a client thing)

Annoying
