### ISSUE TITLE
Quark structures in Deeplands?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2100]
**Mod Version**
3.4 beta 5

**Describe the bug**
In Deeplands, it seems a Quark structure can spawn there, specifically an underground dungeon that's supposed to be Overworld-only. As it stands, I don't know if this can spawn in other AoA dims. It's weird, Quark adds multiple structures to the Overworld but I've only seen this specific one in Deeplands so far.

**To Reproduce**
Steps to reproduce the behaviour:
Go to Deeplands with Quark installed, and try to find any structures that aren't supposed to be there.

**Expected behavior**
This not happening lol

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/101117756-94a5db80-359c-11eb-99d8-e58d133259b2.png)

**Comment by Tslat** [comment]
This should be reported to Quark.
