### ISSUE TITLE
Quark seems to make certain dimensions not load

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2101]
Title. If you go into certain dims with Quark installed, it gets stuck at the loading screen and you have to close the game. It seems to mainly happen with non vanilla-gen dimensions (Lelyetia, Vox ponds, Mysterium, etc.). Though as of beta 5, something like Deeplands isn't affected other than https://github.com/Tslat/Advent-Of-Ascension/issues/2100 ?

If one of these dims is generated without Quark installed, then Quark is installed, the dimension runs fine at first, but then the tickrate dies soon after.

**Comment by Tslat** [comment]
Disable the dungeon structure in Quark. Nothing I can do here
