### ISSUE TITLE
making desert king armor with desert, barathos and nether stuff

### ISSUE THREAD

**Issue by vrextachropthus** [Tslat/Advent-Of-Ascension#2106]
**Describe the new feature you think would be good to add**
A specific and detailed description of what you want to see.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?

**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?

**Comment by Tslat** [comment]
What is desert king armour?

**Comment by vrextachropthus** [comment]
A New armor idea
Boots allows to go Fast in barathos blocks and sand
Armor protects fom fire and helmet allows immunity falling sand suffocation and maybe burns enemies

**Comment by XxDuckyUxX** [comment]
This is actually a good idea 👍
