### ISSUE TITLE
Change the block icon representing table used for recipe for certain recipes

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2109]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
The crafting table icon in this toast notification.
![image](https://user-images.githubusercontent.com/44556728/101215369-b8742a80-364b-11eb-96dc-b8abb1ef128f.png)
 
**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
The icon for this toast notification changes depending on what crafting station you make said recipe in. For example, the crafting table icon is replaced with a stonecutter icon for stonecutter recipes.

My suggestion is change the icon for some of aoa's tables, notably:
1. change it to divine station for divine station recipes.
2. change it to infusion table for infusion table recipes.
3. change it to frame bench/whitewashing table for those recipes?

 **Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
Not that I know of
**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Not that I know of

**Comment by Tslat** [comment]
Done in 1.15
