### ISSUE TITLE
The Ability to make minions stay where you want them to be.

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#211]
Right now minions just follow you and it can sometimes get annoying constantly hearing them (Goofer Noise plays for the 100 time), and spawning many of them is a punishment.

When you right click a minion, it should make it sit, this means It won't teleport to you and stay where you want it to be.

**Comment by Cruuk** [comment]
You could even give all the minions a "sitting" animation.
