### ISSUE TITLE
Distorting Artifact

### ISSUE THREAD

**Issue by SO12345Mine** [Tslat/Advent-Of-Ascension#2114]
I am new to this giant mod so i have minimal knowledge on how things work (Which il eventually find out somehow). But the first thing, stupid thing, i did was to jump down into the void with distorting artifact, now its just distorting the world (not really a big problem but then..). I cant open a new world without the distortion happening again even if i didn't do it again. Can someone help me with this? sorry

**Comment by Tslat** [comment]
Distorting artifact doesn't do that

**Comment by SO12345Mine** [comment]
Oh il doesnt? i believe it did cause of the description and everything just went wrong in my worlds, maybe one of the mods are clashing into it. I have never used it ever so i just assumed. Il check what might have happened by testing some things. Thanks for the comment.

**Comment by SO12345Mine** [comment]
Right i think i found out what happened, i previously config one of the other mod (FPS booster mod) before i added the advent of ascension, i found it out my turning off all but that mod. It was probably not the algorithm recommended into this system im using so im going to change that. Sorry for bothering you
