### ISSUE TITLE
Bomb carrier is very common

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2116]
**Mod Version**
3.4 beta 7

**Describe the bug**
For a little while I thought it was just luck, but I don't think it's just that. Bomb carrier is currently as common as a normal Overworld mob. I've seen him just as, if not more often than other Overworld mobs. Other rare mobs have been much more infrequent compared to Bomb carrier, as expected. Bomb carrier has been common across multiple worlds and sessions, so I don't think it's just really good luck.

**To Reproduce**
Steps to reproduce the behaviour:
Go into a world and see him spawn?

**Expected behavior**
Bomb carrier being rare

**Comment by Tslat** [comment]
He definitely has a significantly lower spawn weight than others. But for safe keeping I've lowered it further
