### ISSUE TITLE
Mobs should ignore Pixons/Bloodlusts

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#212]
**Describe/name the existing feature this suggestion relates to**
Pixons and Bloodlusts.

**Describe the change or feature you think would be good to see**
We know there exists certain hostile mobs that will attack other mobs, but I think they should ignore Pixons and Bloodlusts.
![image](https://user-images.githubusercontent.com/38159897/50568509-c86c8c80-0d07-11e9-90a6-51efe7a92151.png)
It can kind of screw up a fight in the sense that the mob will keep trying to attack the Pixon yet the Pixon can't be killed by it.
And of course, same goes for Bloodlusts.

**Comment by Tslat** [comment]
Has been fixed
