### ISSUE TITLE
Archaic Ladder ids differ from other Immortallis blocks

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2137]
**Mod Version**
What version of the mod are you on?
3.4-Beta-7 (reupload)

**Describe the bug**
Most of the archaic blocks use the id format aoa3:archaic_block for the unbreakable variant and aoa3:archaic_block_breakable for the breakable variant.

This isn't the case for the archaic ladder, which uses the id aoa3:archaic_ladder for the breakable variant and aoa3:unbreakable_archaic_ladder for the unbreakable version.
**To Reproduce**
Steps to reproduce the behaviour:
1. Get both the unbreakable and breakable variants of archaic ladders, check their ids.
2. Check the ids of some of the other archaic blocks (compare the unbreakable blocks with the breakable counterparts).
3. See error

**Expected behavior**
The archaic ladder's ids is consistent with the other archaic blocks.

**Comment by Tslat** [comment]
Also applied to runic glass
