### ISSUE TITLE
New Horse Armor

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#215]
Horse armor is something that is really uncommon in mods (with only one mod adding some afaik). Horses are some of the most useful things in vanilla, but AoA makes them pointless with all the speed/jump armor and the powerful mobs it adds. I think horse armor would not only be a unique addition, but would make horses more valuable. The armor could be obtained through different methods (crafting, mob drop, etc.), and could have special effects like regular armor.

**Comment by TekterBR** [comment]
THIS, is an awesome idea.
I think it would be hard to add useful effects to horse armors, since the only things horses do is run and jump.
If you add more detail, it may get a higher chance to be added.



Or instead the mod will get mounts...

**Comment by DiamondWalker** [comment]
> 
> 
> THIS, is an awesome idea.
> I think it would be hard to add useful effects to horse armors, since the only things horses do is run and jump.
> If you add more detail, it may get a higher chance to be added.
> 
> Or instead the mod will get mounts...

That's actually a fair point. Here's some ideas:

Lunar horse armor: Crafted. Basically the same as the regular Lunar armor.

Runicorn Armor: dropped commonly by Runicorn Riders. It's made for Runicorns, but fits on horses. Since it's made for Runicorns, it has a horn build onto it. Horses can use this horn to attack enemies (touching an enemy with your horse while wearing this armor damages the enemy).

Bloody Horse Armor: Obtained somewhere in the Abyss. The horse drains its riders health if it needs to heal (basically you take damage for your horse).

Some armor that gives your horse a speed boost.

Nethengeic Horse Armor: dropped by Nethengeic Beasts. Gives your horse fire immunity.

Aquatic Horse Armor: dropped by Mermages. Gives your horse the ability to walk on water.

Explosive Horse Armor: made from Creeponia ores. Gives your horse explosion immunity.

Some Armor that heals your horse (like commander armor).

Maybe the Expedition Armor could be made into horse armor instead?

**Comment by TekterBR** [comment]
It looks awesome
But there are some points missing

The horse would have the utility of attacking only with the Runicorn armor
It would be better to not expose your horse to danger since the only thing it would do is run
This is the main problem
There should be a benefit on using the horse apart from travelling

Something like: while riding a horse, melee damage is increased by 50% or increased depending on Butchery level (battle rage damage)
Or, all horse armors gives the horse the ability to cause damage and each armor would add its own amount of damage

**Comment by DiamondWalker** [comment]
The idea of the runicorn armor is that you could run into enemies with your horse.

You can already deal damage while riding a horse, so I don't really see why all the armors should make your horse deal damage. As long as you can keep your horse alive (the reason behind horse armor), the added mobility is a fair reward.
