### ISSUE TITLE
Ores that smelt into gems cannot be smelted in the blast furnace

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2153]
**Mod Version**
What version of the mod are you on?
3.4-Beta-7 (reupload)

**Describe the bug**
AoA's ores that smelt into gems cannot be smelted in a blast furnance. This behavior is inconsistent with vanilla, which does allowed its gem ores to be smelted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to smelt any ore-dropping gem added by the mod in a blast furnace.
2. See error

**Expected behavior**
The gem-dropping ores smelt in a blast furnace.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/101839504-7eee6400-3b10-11eb-86e6-0f53233cce16.png)

**Comment by Tslat** [comment]
The wiki lied to me
