### ISSUE TITLE
Recharge boosts Energy costs 7% per level instead of 5%

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2154]
**Mod Version**
3.4 beta 7

**Describe the bug**
Title. Instead of reducing energy costs by 5% it seems to be reducing them by 7% per level.
For reference, Spirit shower consumes 100 Energy at base.
![image](https://user-images.githubusercontent.com/38159897/101855620-96c9e600-3b18-11eb-8c29-a97f549bb209.png)
![image](https://user-images.githubusercontent.com/38159897/101855632-9b8e9a00-3b18-11eb-9c7c-a876fb7c5bc1.png)

**To Reproduce**
Steps to reproduce the behaviour:
Enchant a blaster with Recharge

**Expected behavior**
Recharge reducing Energy costs by 5% per level.

**Comment by Tslat** [comment]
Not a bug
