### ISSUE TITLE
Tamable and ride-able creatures 

### ISSUE THREAD

**Issue by geckosavage** [Tslat/Advent-Of-Ascension#2157]
Add tamable and ride-able creatures

**Comment by EatingSilencer** [comment]
Define "tamable".

**Comment by geckosavage** [comment]
https://www.thefreedictionary.com/tamable

**Comment by EatingSilencer** [comment]
I meant in the context of the game. AoA already has breedable mobs (elkanyne and coratee).

**Comment by geckosavage** [comment]
Like wolf or cat, can follow or free roam by player command.
