### ISSUE TITLE
Strange bug with ftb ultimine

### ISSUE THREAD

**Issue by GreenWither** [Tslat/Advent-Of-Ascension#2165]
**Mod Version**
3.4

**Describe the bug**
When I use ftb ultimine, it will get to a point where nothing drops from anything, blocks dont drop anything when mined, and mobs drop nothing when killed. I don't know 100% but I thought I might as well report it while it's on my mind.

**Comment by Tslat** [comment]
This should be reported to FTB ultimine
Don't think this has anything to do with AoA?

**Comment by GreenWither** [comment]
Well I thought it was an AoA issue because ever since I got it it has been happening, it's weird because it worked fine with the beta.
I could also show this to FTB as well if you're certain its on their side

**Comment by Tslat** [comment]
it doesn't seem like something AoA would do, I don't directly disable drops anywhere really
