### ISSUE TITLE
Smithing table and divine station

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#2166]
Since AoA is porting to 1.16 now I figured this would be the time to post this.

In 1.16 the smithing table is used to upgrade diamond gear into netherite gear. This is nearly identical to the divine station, which also takes a piece of gear + an extra ingredient to make a better version of said gear. Since the smithing table is only used to make a single gear set (which will most likely be easily overshadowed by AoA gear), I was thinking upgrade kit weapons could require a smithing table instead.

That would probably be bad for balance as many weapons could be instantly replaced with their upgrades, plus it would make the divine station useless. To fix that, upgrade kits could be crafted at a divine station rather than being rare RNG drops. A possible recipe could be 1 (or more) rare weapon, a huge amount of a certain common loot drop, and a lot of tokens, all from the proper dimension.

In general, it'd be nice to see AoA make the smithing table more useless, be it through upgrade kits or otherwise.

**Comment by Cruuk** [comment]
It's not a bad idea on paper, but I'm not sure if I'm a fan of having to jump through extra hoops purely for the sake of validating Smithing table as an established item in AoA's gameplay. It'd be like nerfing Sapphire because it's better than Diamonds, or nerfing Emberstone because it'll be better than Netherite. At 1 point, you have to draw a line on how relevant vanilla content should be in a mod's balance

**Comment by DiamondWalker** [comment]
> 
> 
> It's not a bad idea on paper, but I'm not sure if I'm a fan of having to jump through extra hoops purely for the sake of validating Smithing table as an established item in AoA's gameplay. It'd be like nerfing Sapphire because it's better than Diamonds, or nerfing Emberstone because it'll be better than Netherite. At 1 point, you have to draw a line on how relevant vanilla content should be in a mod's balance

Sapphire being better than diamond is fine because of how rare it is. Now that you mention it, making emberstone being gated behind sapphire/netherite pickaxes could be a good idea, but that's beside the point.

I wasn't talking about balance; it just seems a bit weird having two unrelated crafting stations have almost the exact same functionality, especially when one of them is barely useful at all.
