### ISSUE TITLE
Boss Enhancement

### ISSUE THREAD

**Issue by bbl30854** [Tslat/Advent-Of-Ascension#2169]
Boss fights should have more difficulty and tension. Most of the bosses can be defeated easily when using dirty tactics. 
For example, If you place a block, jump on it and adjust youself's position correctly, you can beat hive king easily while it can't reach you. Or you can just go far away until bosses can't detect you and bow them til they die. Really love this mod but it's so sad that I can't experience fun boss battles. 

In my opinion, bosses should be invincible it they don't detect any player. And maybe it'll be good if bosses teleport to the player if they're blocked by an object.

**Comment by DiamondWalker** [comment]
I believe a boss update is already planned. AoA really needs it imo. Even if you fixed this the fights are still really easy and boring, except for a few cases where they're extremely unfair.

**Comment by Seishan123** [comment]
Perhaps making it so that instead of summoning a boss you are teleported into another dimension where there are arenas for the bosses. This could also be used to 'force' the player to use certain items. This may also be used to make the bosses have custom actions within the arena.

**Comment by Neylar** [comment]
> Perhaps making it so that instead of summoning a boss you are teleported into another dimension where there are arenas for the bosses. This could also be used to 'force' the player to use certain items. This may also be used to make the bosses have custom actions within the arena.

We have 4 bosses with their own arenas and those bosses are cool, but unfair in some cases.
Actually, it sounds cool, but I don't know how schimi can do something like this for ALL bosses.
