### ISSUE TITLE
Extreme (or not so) change to armor skill system

### ISSUE THREAD

**Issue by TekterBR** [Tslat/Advent-Of-Ascension#217]
The main idea with this change is to be possible to **combine** different armor pieces and still get its effects. Also, i think it would become easier to change and add new armors with this new system.

Some armors have very similar effects, and because of the big amount of armors already present in the mod, it becomes hard to add effects to armors without repeating the effects from other armors.
My suggestion is to instead of activating the effects when the full armor is worn, each armor piece would give a amount of **Armor skill points**, and when a minimum amout is reached, the effect is activated.
With this system, it would be possible to use some armor effects without having all the four pieces.

Example: both Lunar and Alacrity armors give you Jump Boost VI, but if somehow you got 2 Alacrity pieces and other 2 Lunar pieces, if you mix the 4 pieces, you would still get the Jump Boost VI (and fall damage immunity too, but not the Night Vision).

I've already sorted all the armor effects, to give a good insight of how the system would work.

[Advent of Ascension - Armor Skills.txt](https://github.com/Tslat/Advent-Of-Ascension/files/2722122/Advent.of.Ascension.-.Armor.Skills.txt)

[Advent of Ascension - New Skill System.txt](https://github.com/Tslat/Advent-Of-Ascension/files/2722107/Advent.of.Ascension.-.New.Skill.System.txt)

This system is actually the same used in Monster Hunter games.

**Comment by TekterBR** [comment]
### Armors:
**[Armor name]** [Skill name] [points added] 
*[Effects]*

### Skills:
**[Skill name]** [Armor name] [points added by the full set]
[Points required to activate effect] *[Effect]*

**Comment by Tslat** [comment]
I see huge issues with balancing in doing this though, no?

The effects the armours give are wide-reaching and very powerful. Allowing users to mix them would be disastrous for balance

**Comment by TekterBR** [comment]
Take a better look at those files
Changing the values for activation and the points given by the armor piece can make an easy balancing.
Many of the armors have their own effects and could not be combined with others armors to activate their effects

You can only activate all Lunar Armor effects having all Lunar Armor pieces, or a helmet with "Stacking" (Diving helmets, Face mask and NV Goggles)

If i counted right, 19 out of 48 armors cannot be combined to mix the effects
And, even mixing the effects, the main skill of the armors would not be activated

If you use 2 Crystallis armor pieces, you will get 30% chance to deal double melee damage instead of 60%, but will still have 20% chance to deal 50% of the base damage to yourself
It's a weaker version of the original effect and with the same debuff
You could combine it with 2 Elecanyte pieces to block 20% of the damage or 2 Zargonite pieces to get 1 extra heart

Its nearly the same of having new armor sets


If you don't want an effect to activate without a especific armor set, you can adjust the amount of points needed to activate it

**Comment by TekterBR** [comment]
I lost my line of thought

Since its you that would change the system, you can decide what armors could be combined or not just changing their numbers

In the files i added weaker versions of the effects to show how it would work without the full armor
But they're optional (although i want all of them added)


If you don't do it for mixing skills, you can still do it to add new armors with more ease, since you can create the skills and armors separately and then unite them

**Comment by TekterBR** [comment]
Lastly, i had this idea because i saw that Lyndamyte and Void armors don't have any effects
Instead of just having no effects, they could give skill points that wouldn't match to activate a effect, except by combining

Example: Lyndamyte Helmet (Jump +1), Lyndamyte Chestplate (Fall +1), Lyndamite Leggings (Night Vision +1), Lyndamyte Boots (Fire Resistance +1)

**Comment by Tslat** [comment]
You'll be glad to know then that this was implemented in 3.2, huh?

**Comment by TekterBR** [comment]
I'm actually extremely surprised
When i thought about this system, i thought of it as being extremely efficient for both playing and developing, since it would simplify the creation and application of the effects and armors, and making balancing much more easy since it would only depend on chaging numbers, while making it funnier to use and experiment different combinations
Didn't knew the implications of using this system though, still don't know

I'll certainly take a look at it
