### ISSUE TITLE
Low frequency mob spawns in overworld 

### ISSUE THREAD

**Issue by Spaceboii** [Tslat/Advent-Of-Ascension#2172]
**Mod Version**
What version of the mod are you on?
Version 3.4 (release) 

**Describe the bug**
Very little Overworld hostile mobs spawning, this was better in the beta 7 release of 1.15. Also happens in other realms, Tried forcing a respawn of all entities with "kill @e[type=!player]" this helped in the Overworld to create more mobs. Before the mobs stopped spawned there were a ton of Pixons and other AOA NPC's such as vendors spawning.  We also tried this command in the nether, there it had less of an impact.

the command "/time query day" returns "The time is 100". 

**To Reproduce**
Play, wait for night, no mobs. Check if game is on peaceful, see game is on hard. 

**Expected behavior**
I expect to die at night. (ie mobs spawning at a frequency you'd expect.

**Screenshots**
Insert picture of no mobs.

**Comment by Tslat** [comment]
I didn't change it from beta 7

**Comment by Spaceboii** [comment]
Well it was better in beta 7 tho
