### ISSUE TITLE
Foraging broken in 1.15

### ISSUE THREAD

**Issue by Spaceboii** [Tslat/Advent-Of-Ascension#2173]
**Mod Version**
3.4

**Describe the bug**
During beta it was mentioned that mining stone occasionally gives the ding sound but no exp is rewarded. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'rocks 
2. Mine rocks 
3. Ding sound 
4. No exp 

**Expected behavior**
Ding sound followed by an exp drop. 

**Screenshots**
Insert level 1 skill image.

**Comment by Tslat** [comment]
Known and fixed
