### ISSUE TITLE
hmm.. This seems like a long stretch but I am just gonna go ahead and ask

### ISSUE THREAD

**Issue by XxDuckyUxX** [Tslat/Advent-Of-Ascension#2177]
Due to 1.16.4 releasing soon and we are probably going to stay in this version for a bit, You probably would have time to add this feature. 

Since there is 3-D generation in dimensions now since 1.16, I wanted to ask if Lunalus could be 3D instead of just one layer, I think it would look cool. Also, I was thinking that since it is like space, there just little to no oxygen, so maybe a spacesuit to go into this dimension. 

Since the nether is also rewriting some mobs to be Biome-Specific in the nether, I was thinking the same thing could be done with the Advent mobs. 
Embrakes, Flamewalkers, and hellcats in Basalt Deltas. These give off a lava/igneous texture vibe, I think they suit this biome (also, there is little netherrack, so Flamewalkers can't set their loot on fire as often.
Hellspots, Infernal, and Pigotrons in Nether Wastes, They tend to not spawn as common as the other mobs, so I think this suits (Also, Infernals need a new texture due to the netherrack texture change.)
Little Bams in Crimson Forests, (make sure that Piglins can't attack them). These are mostly sentient, so I wanted to put them in a biome that can support life.
Wither Wizards and Skeletal Cowmen in Soul Sand Valley (YES, PUT ALL THE MOST DANGEROUS IN THE SOUL SAND VALLEY :critty:).

Anyone, this is just a suggestion, but it would definitely be amazing to see what you have in store for us during these new update :D

**Comment by EatingSilencer** [comment]
Pigotrons spawn when one defeats a fake zombie pigman, they don't spawn on their own. Just thought I'd mention that,.

**Comment by XxDuckyUxX** [comment]
> Pigotrons spawn when one defeats a fake zombie pigman, they don't spawn on their own. Just thought I'd mention that,.

I know, I just prefer to call the, pigotrons because of their true form
