### ISSUE TITLE
Holly Tops texture bug

### ISSUE THREAD

**Issue by GrayLightTaliz** [Tslat/Advent-Of-Ascension#218]
**Mod Version**
Tslat 1.1.3

**Describe the bug**
Holly Tops texture (for stage-1) is partially invisible. When you look at planted holly tops (stage-1) from any direction only right-side part is visible.

**To Reproduce**
1. Plant holly top seed
2. Look at planted holly top from nearby (while it has 1st stage)

**Expected behavior**
All (four) parts of planted holly top (while stage 1) should be visible

**Screenshots**
![default](https://user-images.githubusercontent.com/44785582/50633454-648ed180-0f5c-11e9-8738-7f158aa15acc.png)

**Comment by Tslat** [comment]
Fixed in 3.1.2
