### ISSUE TITLE
AC bosses should drop their statues 100% of the time

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#219]
I don't get why almost every boss in the mod drops their statues 100% while the Ancient Carven's bosses drop at a 20% rate.

Make them drop their statues 100%. This really doesn't affected anything. To me, a statue is way to tell how many times you've killed a boss.

I'm not sure about their other drops. 
Banners: Not really important, just as a extra way to say you beaten them. I would say they should drop between 50% or 100%.
Scythes and Sticklers: Have no idea what the drop rate of these weapons should be. Probably should keep them as they currently are at the moment.

**Comment by Tslat** [comment]
Will be done
