### ISSUE TITLE
[1.15.2]Lang file not updated

### ISSUE THREAD

**Issue by Wind-Xing** [Tslat/Advent-Of-Ascension#2190]
**Mod Version**
3.4.2

**Describe the bug**
3.4.2's lang file not updated to new version
Similarly, there is no Lang file for zh
![22222](https://user-images.githubusercontent.com/59332746/102687274-d3889200-4228-11eb-9129-972e73e8c537.png)

**Comment by Tslat** [comment]
What do you mean not updated to new version?

**Comment by masterbobli** [comment]
The zh_cn language file is missing in the code

**Comment by Tslat** [comment]
Oh that

Yeah I didn't notice the zh_cn lang until after release, not sure what happened there.
I thought you guys were still working on it.

It'll be in the next one
