### ISSUE TITLE
Non-melee weapon types should show the damage they deal if applied with a damage-increasing enchantment (best name I had sorry)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#220]
**Describe the new feature you think would be good to add**
Damage-boosting enchantments and basically anything that isn't a melee weapon.

**Add any alternative implementations you think might work**
As we know when a melee weapon is enchanted the damage that is displayed updates to reflect the increased damage.
![image](https://user-images.githubusercontent.com/38159897/50672813-13e49c00-0f8f-11e9-9024-ffff6e1c2449.png)

However the same cannot be said for any ranged weapon like guns/bows, and I think they should for the sake of convenience.

Yeah a bunch of them are gonna display decimal damage (Megagun's damage with shell 3 is 10.4), but vanilla swords enchanted with sharpness already show decimals so I see no concern with it.

**Include any additional background information**
This suggestion also goes with weapons that have random damage, the 2 damage values displayed would just be changed to reflect the enchantment. (if possible)

**Comment by Tslat** [comment]
This is actually a lot harder to do than you may think....
Good idea regardless, but whether it happens or not remains to be seen

**Comment by Tslat** [comment]
Done in 3.3
