### ISSUE TITLE
Skeletal tools drop white dye instead of bone meal

### ISSUE THREAD

**Issue by legitadimc** [Tslat/Advent-Of-Ascension#2200]
**Mod Version**
3.4.2

**Describe the bug**
When you use skeletal tools - like a pickaxe or axe - the blocks mined have a chance to give fossils, bones and bone meal. Instead of bone meal I get white dye. Atleast on the axe.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get Skeletal tool
2. Keep breaking blocks until the table rolls
3. Get white dye instead of bone meal

**Expected behavior**
Bone meal drop instead of white dye

**Comment by EatingSilencer** [comment]
Looks to affect the shovel and axe but not the pickaxe.
