### ISSUE TITLE
The player does not get a cup back when consuming Tea/Lunarade

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2203]
**Mod Version**
3.4.2

**Describe the bug**
When Tea or Lunarade is consumed, the player does not get an empty cup/mug back. It's permanently gone upon consumption. This happens with all 3 types of Tea and Lunarade.

**To Reproduce**
Steps to reproduce the behaviour:
Drink Tea/Lunarade.

**Expected behavior**
The player getting an empty cup/mug back.

**Comment by vrextachropthus** [comment]
oh no
it failed my plan then
