### ISSUE TITLE
Craexxeus Towers can generate with a section of the structure cut out

### ISSUE THREAD

**Issue by odw500** [Tslat/Advent-Of-Ascension#2204]
(Using version 3.4.2)
These screenshots show a corner cut out of one tower's arena and under a half cut out of another tower's arena.
![2020-12-22_00 06 19](https://user-images.githubusercontent.com/52132442/102834485-1777c480-43ec-11eb-8cd6-08ea9ee76559.png)
![2020-12-22_00 09 00](https://user-images.githubusercontent.com/52132442/102834494-1cd50f00-43ec-11eb-8da1-bdbe8d8a0d03.png)

**Comment by Tslat** [comment]
Known, not fixable without converting AoA's structures to the new worldgen system.

It will happen in time, and I'm going to close this report because until it does, there's nothing else I can do
