### ISSUE TITLE
Reversed lelyetian folliage drops lelyetian grass blocks

### ISSUE THREAD

**Issue by vrextachropthus** [Tslat/Advent-Of-Ascension#2206]
**Mod Version**
1.15.2 3.4.2

**Describe the bug**
reversed lelyetin folliage drops lelyetian grass block normally they should drop nothing

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by EatingSilencer** [comment]
So far I've only reproduced this with a lelyetian wiggler (non-cap).
