### ISSUE TITLE
Curse of Greed in enchantment tables

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2219]
**Describe/name the existing feature this suggestion relates to**
Curse of greed in enchantment tables

**Describe the change or feature you think would be good to see**
I think over time I've come to moreso disagree with the current implementation of being able to get Curse of greed. It's very punishing and isn't very clear to new players on how you can avoid it. The only way to avoid it is to deliberately go for a lower-level enchantment, and it doesn't feel very good to shaft enchantment potential because you don't want to roll the dice of getting Curse of Greed. Also you have to know how to avoid it in the first place lol.

It sucks for newer players when they spent time getting a T4 upgraded weapon only for it to get Curse of Greed. You literally can't get rid of it either, not even Grindstone works I'm pretty sure. It's not so easy to get another version of something like a boss drop weapon when you already put time and commitment into getting it in the first place, only for that version to get Curse of Greed.

I believe the reason that was given for this is to incentivize imbuing those weapon types instead, but I'm not sure if this is the right way to do it. Instead of punishing the player for just wanting to normally enchant without training a grindy skill (yeah yeah skills suck blah blah), the enchantment weights should be rebalanced. i.e making higher levels of AoA impossible to get without Anvil. I'm pretty sure you can't get sharp 5 when enchanting at an Enchantment table, the same should go for AoA enchantments. (not talking about the Infusion-exclusive enchants).
Imbuing would still be the better option but there would no longer be a punishment for just wanting to normally enchant. (I don't want to use Power stones/enhancers on *everything* I get)

I think another reason given was to justify its existence in the first place, questioning on why Curse of vanishing/binding exist if you can't get them in Enchantment tables. Forgive me if I'm wrong, but that's not a very good mindset. Should everything Mojang adds be super impactful in a negative way? I'm pretty sure the curses were added to add spice to loot chests, along with versatility in multiplayer environments. There'd be no good reason for them to add the curses to enchantment tables, unless they wanted to screw players over. Could you imagine the backlash? Also if this was only done to justify it existing in the first place, wouldn't we better off without it? lol

If you wanted Greed to still impact gameplay, a less punishing way would be to make it so loot chest weapons like Beamer have a chance to spawn with Curse of Greed.

I can't think of any other reason to justify a harsh, RNG-heavy punishment. Do you not want players getting the enchants so easily? That's kind of stupid, just how broken is a shell 3 tier 0 gun really? Shouldn't the enchantments themselves be tweaked instead of adding a chance to screw players over? If you can get lucky and not get Greed, along with having a high enough Infusion level to imbue with the enchantment, what's the point of gating its power in a chance-based manner?

There's also an inherent bias in the system, why are greatblades and bows able to get all the good enchantments with 0 drawbacks while guns/blasters/etc. have to constantly worry about Greed? Again, tweak the enchantments/weapon themselves if they're the problem, instead of adding a punishment to something that is already inherently RNG with a cost of exp and Lapis.

**Add any alternative implementations you think might work**
If you still want to keep Greed in an Enchantment table, at least make some tweaks to make it less punishing:

1. Make it rarer. It really shouldn't be this common. Like 1/3 of the high level enchants have had Greed.

2. Have Greed *always* be the enchantment that shows up in the preview if it's there. This is the biggest issue with it, you can't really see it coming. If players always knew it was there, it would at least act as a deterrent rather than a punishment that comes out of nowhere. If the intent is for players to not see it coming, then... that's stupid as hell lol

**Comment by EatingSilencer** [comment]
While I agree with your comments, I was curious and discovered that there is a way to remove curse of greed, but with a cost - combine two of the same weapon in a crafting table.

**Comment by Tslat** [comment]
I agree mostly out of consistency - but tbh I feel like the best way to have had it would be for Mojang to have made curses happen on enchant tables normally, but add a way to wipe enchants off an item.

The curses as they are feel pretty nonexistant tbh

Regardless, this topic is something on my mind that I'm not yet sure what to do with

**Comment by Neylar** [comment]
Agreed with you, my first blaster enchant was with curse of greed.
