### ISSUE TITLE
Infusion stones and Power stones should have different textures

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#222]
**Describe/name the existing feature this suggestion relates to**
Infusion stones and Power stones.

**Describe the change or feature you think would be good to see**
I always found it odd that Infusion stones and Power stones have the same texture. Why? Was it to save time? Who knows, but what matters is that they should really have different textures to differentiate each other.

Infusion stones can keep their texture, it's the Power stones that need new ones. It doesn't even need to be really different, it can just be the Infusion stone texture but with a glowing aura around it or whatever. Tell Ursun I said hi.

**Comment by TekterBR** [comment]
I think it should have a "enchanted" effect

**Comment by Sagisolar** [comment]
@TekterBR If you support it, upvote it.

**Comment by Tslat** [comment]
Has been done
