### ISSUE TITLE
Red Tentacles or anything with eyeballs don't drop staring eye

### ISSUE THREAD

**Issue by CrankedGuido** [Tslat/Advent-Of-Ascension#2225]
So me and some friends have been playing on our own server with AOA version 3.4.2 and we are progressing very well but we ran into a problem trying to find staring eyeballs to fight elusive, and progress from there. We have been breaking non stop red tentacles with swords and every other took at least 64 with each block and have not yet gotten any staring eye drops. We even tried using Orange eye blocks even though the wiki says it doesn't drop them, as well as trying the eyeball block as well just in case. 
Are we just that unlucky or is the way to obtain the staring eye outdated perhaps?

**Comment by gohansaneric** [comment]
im having the same issue did you find out what to do to fix it
