### ISSUE TITLE
A couple items still say "Borean" instead of "L'Borean".

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2226]
**Mod Version**
What version of the mod are you on?
3.4.2

**Describe the bug**
"Borean Tokens" aren't called "L'Borean Tokens", "Borean Portal" isn't called "L'Borean Portal".

**To Reproduce**
Steps to reproduce the behaviour:
1. Look at the names for Borean Tokens and Borean Portal.
2. See error

**Expected behavior**
"Borean Tokens" should be called "L'Borean Tokens" and "Borean Portal" should be called "L'Borean Portal". This is to be consistent with the change from "Borean Realmstone" to "L'Borean Realmstone", which happened in 3.4.

**Comment by Tslat** [comment]
This is actually intentional

**Comment by EatingSilencer** [comment]
I can understand Borean Tokens, but...Borean Portal? The dimension is called L'Borean, not Borean.

**Comment by Tslat** [comment]
Changed portal, not tokens
