### ISSUE TITLE
Server get stuck on loading dims on startup

### ISSUE THREAD

**Issue by Nebula240** [Tslat/Advent-Of-Ascension#2230]
**Mod Version**
3.4.3 - 1.15.2

**Describe the bug**
On dedicated servers when using 3.4.3 at the startup the server will get stuck on loading dims,
`28.12 21:07:29 [Server] Server thread/INFO [n.m.c.DimensionManager/DIMS]: Registered dimension aoa3:immortallis of type aoa3:immortallis and id 15`

**Expected behavior**
Fix it because it makes impossible for dedicated servers to start.

**Comment by Tslat** [comment]
Need a log file.

Are you on forge? or a forge wrapper?
Does it do it in single player?

Have you tried it without mods?
