### ISSUE TITLE
Sticky Slime cannot be used in place of Slimeballs in crafting recipes

### ISSUE THREAD

**Issue by odw500** [Tslat/Advent-Of-Ascension#2235]
As of version 3.4.2 it seems AoA's Sticky Slime can only be used in infusion recipes and not for crafting items you would craft with Slimeballs (i.e. Sticky Pistons, Leads, Magma Cream).

Pressing the key to show Sticky Slime's uses in JEI only shows Infusion recipes as shown here:
![2020-12-30_00 48 09](https://user-images.githubusercontent.com/52132442/103323030-ce9dbc80-4a38-11eb-9e1b-65c80177c6d0.png)

This is an attempt to craft Leads with string and Sticky Slime, which does not seem possible.
![2020-12-30_00 45 00](https://user-images.githubusercontent.com/52132442/103323044-e37a5000-4a38-11eb-91a1-5dae8091058a.png)

**Comment by Tslat** [comment]
That's because forge removed the oredict for it.

**Comment by Cruuk** [comment]
Thanks forge
