### ISSUE TITLE
Negative effects should be in red text

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#224]
Pretty much every text telling what weapons and armor does is in green. (Except artistry armor).

![2019-01-05_13 02 25](https://user-images.githubusercontent.com/44548547/50724765-77371100-10ea-11e9-84bf-c1ff66ccdfca.png)

Do you think that negative effects should be in red text? I do. Cause everything being green makes it less apparent that some armor sets have downsides.

**Comment by Cruuk** [comment]
Should be the type of red seen here.
![image](https://user-images.githubusercontent.com/38159897/50724821-3e764800-10a8-11e9-946f-1bf5e2c1469b.png)
I think it would look better with the green and would be a bit easier to read than the darker variant of red.

**Comment by Sagisolar** [comment]
Change the shade red?

**Comment by TekterBR** [comment]
Red for level requirement
Dark red for negative effect
