### ISSUE TITLE
Nightfly Weird AI

### ISSUE THREAD

**Issue by GreenWither** [Tslat/Advent-Of-Ascension#2250]
**Mod Version**
3.4.4

**Describe the bug**
The nightflies will just hover in corners and not budge when they are there, this only happens when I'm building in creative so this is not while they are aggro.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to creative and build anything that has corners
2. Wait until night or spawn nightflies
3. Watch as they fly around, some may get stuck in the corner and sit there
4. Watch as they never budge from that spot

**Expected behavior**
An AI fix so they dont get stuck in corners

**Comment by GreenWither** [comment]
Another thing, I push them out of the corner and they go back in and stay there

**Comment by Tslat** [comment]
Maybe it's their favourite corner and you're just ruining their fun

**Comment by GreenWither** [comment]
maybe lol but its still strange
