### ISSUE TITLE
Breaking ancient vines or ancient vines cap breaks the rest of the vines despite the fact they are supposed to be unbreakable

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2251]
**Mod Version**
What version of the mod are you on?
3.4.4

**Describe the bug**
When you break one of the ancient vines or ancient vines cap in Ancient Cavern in survival mode, the block regenerates, but the rest of the vine it is attached to may break. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Ancient Cavern. Fly up to a spot where you can break a vine in survival mode.
2. Go to survival mode.
3. Break a random vine block.

**Expected behavior**
The rest of the vines do not break as you are not supposed to be able to break blocks in the dimension.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/103570675-8565c680-4e97-11eb-808c-332039b36ace.png)

**Comment by Tslat** [comment]
Pretty cool, forge throws that event event if the thing is blocked.
Not sure I have a way around this lol

**Comment by EatingSilencer** [comment]
As it turns out its only temporary, returning to the dimension restores the original vine.
