### ISSUE TITLE
Ultraflame and Candlefire Swords

### ISSUE THREAD

**Issue by DragWiz** [Tslat/Advent-Of-Ascension#2254]
Currently the Ultraflame sword has the ability of setting on fire every nearby enemy, has an attack damage of 17.5 and has a speed of 1.6, it is a tier 3. The Candlefire sword instead only sets the hitted enemy on fire, has an attack of 18 and a speed of 1.6, but it's a  tier 4.
I don't think it makes much sense that a tier 3 sword can set every nearby enemy on fire an have a damage that is almost identical to a tier 4 sword that sets only the hitted enemy on fire. In my opinion it would be better to switch or the effect (making the Candlefire set all nearby enemy on fire while the Ultraflame set only the hitted enemy on fire) or to switch tier and obtaining method (making the Candlefire a tier 3 and the Ultraflame a tier 4).
Alternatively it could be changed the DPS of the swords to make the use of the Candlefire justified, because right now with just a .5 difference the Ultraflame is superior. 
Wish you well.

**Comment by Tslat** [comment]
Ultraflame is actually T2.
Its stats were wrong, thanks for pointing it out.
