### ISSUE TITLE
AOA cause Server can't close

### ISSUE THREAD

**Issue by AshaSalorina** [Tslat/Advent-Of-Ascension#2255]
**Mod Version**
AoA3-3.4.4-1.15.2

**Describe the bug**
I use this mod in my server(1.15.2-forge-31.2.47)
When I want to stop with 'stop', the shell will not exit.
**To Reproduce**
1.Open Server with AOA
2.Try stop it.

**Screenshots**
![image](https://user-images.githubusercontent.com/26963881/104089980-a6268580-52b6-11eb-89cf-7bcfc8926809.png)
**Others**
I haven't try this with linux. If I got the same problem I'll report there.

**Comment by AshaSalorina** [comment]
Now I'm sure this was happened to CentOS 7.8 just like in Windows

**Comment by ZwkAlex** [comment]
same issue
CentOS-7.6
![image](https://user-images.githubusercontent.com/48624606/105621165-b35b7c80-5e3f-11eb-97b8-bc6b952ac33e.png)

**Comment by Tslat** [comment]
Unable to replicate.

At a best guess it's related to worldgen tying up, which may already be fixed, and if it's not there's not a lot I can do about it
