### ISSUE TITLE
Breaking Dawnwood bars causes player to crash

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#2257]
**Mod Version**
3.4.4

**Describe the bug**
Breaking Dawnwood bars causes player to crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter World
2. Find Dawnwood bars in Dustopia
3. Break Dawnwood Bars.

**Expected behavior**
Shouldn't crash when breaking any block.

**Comment by Tslat** [comment]
Provide the crash report.

**Comment by Psychotrickser** [comment]
> Provide the crash report.

[crash-2021-01-10_00.18.18-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/5791969/crash-2021-01-10_00.18.18-client.txt)
