### ISSUE TITLE
Horizon Maul should keep its Slowness ability

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#226]
At the moment Mauls are boring, They all do the same thing but some knock back further.

The Horzion Maul was only pre-maul to have a different ability other than Knock back. Thus, I would like to see it apply slowness again. At least this will give more variety to the Mauls at the moment.
![horizon_maul](https://user-images.githubusercontent.com/44548547/50727577-b712ee00-1114-11e9-9bf3-83db711e0a3d.png)

**Comment by Cruuk** [comment]
Thing is Horizon Maul is sort of the "basic" Maul so giving it an ability may set a false precedent for other Mauls.

You could add a Maul that can be obtained slightly earlier than Horizon. It would do slightly less damage, have around the same kb, and no ability. It can be a similar concept to Lelyetian/Royal Greatblade in balance, etc.

Or if that wouldn't work in general just give the slowness to Coralstone maul or something lol.

**Comment by Sagisolar** [comment]
I would say add a basic Maul cause the recipe for the Horizon is very expensive for early game. So a more early game Maul can help players distinguish weapon types and try them out.
![bsvds](https://user-images.githubusercontent.com/44548547/50728516-ed576a00-1122-11e9-9fd5-b80bdc8be594.png)
