### ISSUE TITLE
Lelyetia Generation issue (unknown reason)

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#2264]
**Mod Version**
Aoa 3.4.4

**Describe the bug**
Lelyetia seems to not like a specific mod. The dimension loads but only the chunks the portal is in. Blocks when broken do not drop items (or take durability form tools), and no mobs have spawned at all. Also attempting to enter creative mode or using any command fails as the command doesn't run. In fact the only function that works in Lelyetia is it's reversed gravity.

**To Reproduce**
Unknown reason of behaviour.

**Comment by Tslat** [comment]
Yeah your server has locked up.
Are you using Quark?

**Comment by Seishan123** [comment]
No I'm not using Quark.
No I don't have Quark installed. It's weird because I enter the world again just this morning to find I'm back in the overworld just before I got the realmstone for Lelyetia.
I suppose I either lagged extremely bad (in which I shouldn't have loaded Lelyetia at all, or even entered the portal) or that was the last save file. Since that moment I've only worked on AOA, no other mod so.

**Comment by Psychotrickser** [comment]
What mods are you using?

**Comment by Seishan123** [comment]
Mods I have installed as well:
Applied Energistics 2
Botania
cofhcore
Cucumber
curios-forge
Inventory pets
Iron chest
Just Enough Items
Journeymap
ProjectE
Storage Drawers
Thermal Foundation
Thermal Expansion

**Comment by Tslat** [comment]
Not really sure, might be worth some investigation from your end to try in a test world removing mods until it works to work out which mod is causing the problem

**Comment by Seishan123** [comment]
Ill try.

**Comment by Seishan123** [comment]
None of the mods seem to be causing it. Works fine in another world.

**Comment by Seishan123** [comment]
Went back to old world and it seems that the placement of the portal seems to matter. Moved it over about 10 blocks and now the world won't load at all... Is there an issue with having too many portals active within a certain area? This would be the 6th portal I've made.

**Comment by Tslat** [comment]
Shouldn't do, no

**Comment by Tslat** [comment]
It not happening in another world doesn't mean no other mods are causing it.

**Comment by Seishan123** [comment]
Could a corrupted chunk cause it? Maybe the portal spawned in one. I'm going to delete the Lelyetia file from the dimension file and try again. Perhaps that will work.

**Comment by Seishan123** [comment]
No the portal's placement is based on the seed of the world...
