### ISSUE TITLE
Kror and Elusive trophies crash the server

### ISSUE THREAD

**Issue by Nebula240** [Tslat/Advent-Of-Ascension#2266]
**Mod Version**
3.4.4

**Describe the bug**
Breaking said tropies crashes the server

**To Reproduce**
Steps to reproduce the behaviour:
-place the trophies
-break them

**Expected behavior**
To drop the item and not crash xd

[crash-2021-01-15_13.13.24-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/5822672/crash-2021-01-15_13.13.24-server.txt)
[crash-2021-01-15_14.55.27-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/5822673/crash-2021-01-15_14.55.27-server.txt)

**Comment by Tslat** [comment]
Known bug and fixed
