### ISSUE TITLE
Night vision goggles haven't a screen effect 

### ISSUE THREAD

**Issue by Kagaribi172** [Tslat/Advent-Of-Ascension#2268]
**Mod Version**
3.4.5

**Describe the bug**
Night vision goggles haven't a screen effect.

**Expected behavior**
Night vision goggles need a screen effect.

**Comment by Psychotrickser** [comment]
I thought it was on purpose that they don't turn the screen green anymore. I like them more without the ugly green

**Comment by Kagaribi172** [comment]
I'm pretty sure it's a bug, as there is a screen effect texture and a path to that texture in the mod.(https://github.com/Tslat/Advent-Of-Ascension/blob/1.15.2/source/item/armour/NightVisionGoggles.java)
I think night vision goggles without the screen effect is overpowered.

**Comment by EatingSilencer** [comment]
While I'm guessing scimi considers this to be a bug since he closed it with the bug label, it being present in the files doesn't necessarily mean that its missing. Old, unused 2.5 biome features still exist in the files but are actually likely not intended to be there.
