### ISSUE TITLE
Realmstones for natural portals

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#227]
Since there are problems with having blueprints in the mod, Runandor, Greckon, and Lunalus portals will need to be changed. Instead of completely changing the way to get the portals for these dimensions, I think the blueprints should simply be replaced with realmstones (since the way to access these dimensions are quite unique imo). Basically, you could find a Lunalus portal (or Runandor/Greckon), go in, and when you kill the rare mob you'll get a realmstone for the dimension.

**Comment by Sagisolar** [comment]
Runandor and greckon portal isn't even a blueprint

**Comment by Sagisolar** [comment]
That would make them boring tho

**Comment by Immortallis1** [comment]
> 
> 
> > Runandor and greckon portal isn't even a blueprint. Its a structure.
> 
> You get a blueprint from the rare mobs... I was suggesting to be given a realmstone instead of a blueprint.

Except you don't? The blueprint thing was disabled. The original portal is a normally spawning structure from Mysterium not tied to any mobs in any way (again pre-tslat there was a blueprint but you needed to find the structure to begin with and the blueprint thing was disabled eventually).

**Comment by DiamondWalker** [comment]
> 
> 
> > > Runandor and greckon portal isn't even a blueprint. Its a structure.
> > 
> > 
> > You get a blueprint from the rare mobs... I was suggesting to be given a realmstone instead of a blueprint.
> 
> Except you don't? The blueprint thing was disabled. The original portal is a normally spawning structure from Mysterium not tied to any mobs in any way (again pre-tslat there was a blueprint but you needed to find the structure to begin with and the blueprint thing was disabled eventually).
> 
> Lunalus...well, there's better ways to do it probably. Cruuk made a suggestion about it

Wasn't aware of the blueprint being disabled. What I say is that once you find the structure, you can bring the portal home with a realmstone.

I honestly don't see an issue with Lunalus. The terrestrial is so rare that it isn't possible to use it to grief (maybe you can spawn one portal, but I don't think that can be used to cause too much damage).

**Comment by DiamondWalker** [comment]
Reading back on this, I realize I wasn't very clear on what I meant.

Basically, the way to originally access the dimensions would still be the same. The only difference would be that once you kill the rare mob in the dimension (say runicorn rider for Runandor), you would get a realmstone for the dimension. You could go home and use this realmstone on your ancient teleporter instead of walking back to wherever you found the portal everytime you want to enter the dimension. This system would keep the uniqueness of getting to these dimensions, but would add an alternate method of traveling to it once said unique method becomes a chore.

The realmstones for Runandor and Greckon could also spawn a different variation of the portals that don't require a realm travel ticket, but idk if it would be hard or even impossible to make that work correctly.

**Comment by Sagisolar** [comment]
I think having to go though over dimensions adds to the challenge of those dimensions.

**Comment by Immortallis1** [comment]
> 
> 
> I think having to go though over dimensions adds to the challenge of those dimensions.

Personally I disagree, having to (literally) run through mysterium again isn't challenging it's just time consuming.

**Comment by Sagisolar** [comment]
Get used to it then, worked for me. There is no problem with the system atm.

**Comment by Immortallis1** [comment]
> 
> 
> Get used to it then, worked for me. There is no problem with the system atm.

somehow I agree but disagree at the same time

**Comment by Tslat** [comment]
Has been done in 3.2
