### ISSUE TITLE
Mechbot's bug in 1.15.2

### ISSUE THREAD

**Issue by ghost** [Tslat/Advent-Of-Ascension#2272]
**Mod Version**
1.15.2

**Describe the bug**
Mechbot in the newest version does not use his jump skill properly. He just slides instead of jumping.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by EatingSilencer** [comment]
Which version of the mod are you using? This bug was supposedly fixed in 3.4.5.

**Comment by ghost** [comment]
> 
> 
> Which version of the mod are you using? This bug was supposedly fixed in 3.4.5.

I recorded a video fighting with mechbot. The mod's version used in this video is 3.4.5 and as you will see, mechbot's jump skill does not work properly.
https://youtu.be/6xsEjLifSVg

**Comment by Tslat** [comment]
*Frown*
