### ISSUE TITLE
Abyss mobs appear in modified Overworld biomes (MC 1.15.2/ AoA 3.4.5)

### ISSUE THREAD

**Issue by Phantom2909** [Tslat/Advent-Of-Ascension#2273]
**Mod Version**
What version of the mod are you on?

Minecraft 1.15.2, mod version 3.4.5

**Describe the bug**

Well, this biome is the Glacier, a biome from the Ice and Fire mod, it's an icy biome. The problem is that the Abyss mobs spawn here (in the Overworld), without the Blood Hunt event taking place. As extra information, the Abyss mobs spawn only in this biome, not in the vanilla one.

**Expected behavior**

That Abyss mobs don't spawn in these modded biomes.

**Screenshots**

![2021-01-19_16 10 25](https://user-images.githubusercontent.com/70826397/105107386-00c59b80-5a86-11eb-9183-361a2d4822ff.png)
![2021-01-19_16 10 06](https://user-images.githubusercontent.com/70826397/105107398-07541300-5a86-11eb-8732-a5bd3801c4a4.png)
![2021-01-19_16 09 56](https://user-images.githubusercontent.com/70826397/105107401-0a4f0380-5a86-11eb-9a11-5fb4c39f9dfc.png)

**Comment by EatingSilencer** [comment]
Abyss mobs should never spawn in the Overworld, even if the blood hunt event is taking place. Are you sure that that biome is the glacier (as in it shows up as glacier in the F3 screen)?

**Comment by Tslat** [comment]
This is the result of another mod forcefully messing with spawns.

It isn't possible for AoA to do this on its own as dimensional mobs _only_ spawn in AoA biomes. They are not set conditionally of anything else.

**Comment by Phantom2909** [comment]
> Abyss mobs should never spawn in the Overworld, even if the blood hunt event is taking place. Are you sure that that biome is the glacier (as in it shows up as glacier in the F3 screen)?

![2021-01-19_21 39 11](https://user-images.githubusercontent.com/70826397/105119664-c9171d80-5a9e-11eb-81db-bb44d5ab6ceb.png)
It's strage, the game detects it as the Abyss, but in theory I'm in the Overworld

**Comment by Phantom2909** [comment]
> This is the result of another mod forcefully messing with spawns.
> 
> It isn't possible for AoA to do this on its own as dimensional mobs _only_ spawn in AoA biomes. They are not set conditionally of anything else.

Mmm, in that case, the real problem is the the game detects the modded biome as if it were the Abyss.

**Comment by EatingSilencer** [comment]
Normally I would say its a biome id conflict, but this is 1.15.2, so in theory biome id conflicts aren't a thing anymore...

**Comment by AstralScourge** [comment]
Can you post a list of your mods?

**Comment by Phantom2909** [comment]
> Can you post a list of your mods?

Sure

Mod List: 
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		Wyrmroost-1.15.2-1.2.7.jar Wyrmroost {wyrmroost@1.15.2-1.2.7 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		dungeons-plus-1.15.2-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		AoA3-3.4.5-1.15.2.jar Advent of Ascension {aoa3@3.4.5 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
		randomenchants-3.1.1.jar Random Enchants {randomenchants@3.1.1 DONE}
		Craftable+Saddles+[1.15.2]-1.3.jar Craftable Saddles {craftable_saddles@1.3 DONE}
		SpartanShields-1.15.2-2.1.0.jar Spartan Shields {spartanshields@2.1.0 DONE}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 DONE}
		Xaeros_Minimap_21.1.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@21.1.0 DONE}
		gravestone-1.17.6.jar Gravestone Mod {gravestone@1.17.6 DONE}
		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
		backpacked-1.7.0-1.15.2.jar Backpacked {backpacked@1.7.0 DONE}
		additionalevents-1.1.jar Additional Events {additionalevents@1.1 DONE}
		DungeonCrawl-1.15.2-2.2.4.jar Dungeon Crawl {dungeoncrawl@2.2.4 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		iceandfire-2.1.0-1.15.2.jar Ice and Fire {iceandfire@2.0.3-1.15.2 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		FpsReducer-mc1.15.2-1.18.jar FPS Reducer {fpsreducer@mc1.15.2-1.18 DONE}
		FriendlyFire-1.15.2-4.0.2.jar FriendlyFire {friendlyfire@4.0.2 DONE}
		PiratesAndLooters6.2-1.15.2.jar Pirates_And_Looters_Mod {pirates_and_looters_mod@1.0.0 DONE}
		ElementaryOres-1.15.2-1.0.0.jar Elementary Ores {elementaryores@1.15.2-1.0.0 DONE}
		forge-1.15.2-31.2.45-universal.jar Forge {forge@31.2.45 DONE}
		ScalingHealth-1.15.2-3.0.9+54.jar Scaling Health {scalinghealth@3.0.9+54 DONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
		EnchantedGApple1-15-2.jar Craftable Notch Apple {craftable_notch_apple@1.0.0 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		overloadedarmorbar-4.0.0.jar Overloaded Armor Bar {overloadedarmorbar@4.0.0 DONE}
		SimpleOres2-1.15.2-2.1.10.2.jar Simple Ores {simpleores@1.15.2-2.1.10.2 DONE}
		structure-gel-api-1.15.2-1.1.0.jar Structure Gel API {structure_gel@1.1.0 DONE}

**Comment by AstralScourge** [comment]
Some mod is most likely messing with world gen somehow. Can you remove half of the mods (except AoA + Ice and Fire) and see if it has the problem still? (If it does, the bad mod is in the other half, then pick the half it's in and keep doing this until you know which mod it is)

Can just recreate the world and copy-paste the teleport command to those coordinates to test

**Comment by Phantom2909** [comment]
> Some mod is most likely messing with world gen somehow. Can you remove half of the mods (except AoA + Ice and Fire) and see if it has the problem still? (If it does, the bad mod is in the other half, then pick the half it's in and keep doing this until you know which mod it is)
> 
> Can just recreate the world and copy-paste the teleport command to those coordinates to test

Okay, I will try it

**Comment by Phantom2909** [comment]
> Some mod is most likely messing with world gen somehow. Can you remove half of the mods (except AoA + Ice and Fire) and see if it has the problem still? (If it does, the bad mod is in the other half, then pick the half it's in and keep doing this until you know which mod it is)
> 
> Can just recreate the world and copy-paste the teleport command to those coordinates to test

20 mods:
![2021-01-19_22 55 40](https://user-images.githubusercontent.com/70826397/105125961-a17a8200-5aab-11eb-8a1c-f959e1f80f15.png)

13 mods:
![2021-01-19_22 59 24](https://user-images.githubusercontent.com/70826397/105126011-c242d780-5aab-11eb-85d9-9bebfdd1344d.png)

9 mods:
![2021-01-19_23 04 45](https://user-images.githubusercontent.com/70826397/105126051-dbe41f00-5aab-11eb-9ee7-fbce037bb44c.png)

6 mods, this is the last one, because in this case the mods are Ice and Fire, Citadel (necessary for I/F to work), AoA, Optifine, TLskincape (a TLauncher mod for a skin) and Forge:
![2021-01-19_23 09 09](https://user-images.githubusercontent.com/70826397/105126184-2cf41300-5aac-11eb-8a17-3cab14d058b4.png)

The last option is remove AoA to see if the biome changes his name.

**Comment by AstralScourge** [comment]
You're making a new world each time, right?

**Comment by AstralScourge** [comment]
Forgot to make it clearer that you have to make a new world each time...sorry about that

**Comment by EatingSilencer** [comment]
New world, same seed.

**Comment by Phantom2909** [comment]
6 mods, this time the game recognizes the biome:
![2021-01-20_00 37 58](https://user-images.githubusercontent.com/70826397/105131908-e4425700-5ab7-11eb-8f44-762a8206fcf7.png)
now, i'll try to place one by one to find the problematic mod.

**Comment by Phantom2909** [comment]
Well, after trying carefully, I finished putting all the mods and remaking the worlds (same seed), and the game kept recognizing the biome. I guess problem solved.
![2021-01-20_01 11 24](https://user-images.githubusercontent.com/70826397/105134617-b4e21900-5abc-11eb-83a5-3f65cc8f36ba.png)

**Comment by Tslat** [comment]
Potentially related:
https://github.com/Alex-the-666/Ice_and_Fire/issues/2747
