### ISSUE TITLE
Extraction tools/artistry armor skill requirements are not working correctly

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#228]
**Mod Version**
AoA3-Snapshot 9

**Describe the bug**
Normally, extraction tools can only be held in the player's hand when the player has the correct extraction level, and artistry armor can only be held/worn when the player has level 100 in the corresponding skill, in survival mode.

However, as of AoA3-Snapshot 9, this does not happen. Extraction tools cannot be held in your hand regardless of your extraction level in survival mode. 

Artistry armor cannot be held in your hand if your skill level is 100, however there is this weird part of the bug. Basically, if you try to put on the artistry armor, it appears to pop off but is actually still on.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pick an extraction tool/artistry armor piece.
2. Get your skill to the correct level.
3. Go to survival mode.
4. See that the extraction tool cannot be used/artistry armor glitches out, despite you having the correct skill level.

**Expected behavior**
You should be able to use extraction tools, and /hold/wear artistry armor, when you have the correct skill level in survival mode.

**Comment by Tslat** [comment]
Appears to have been fixed through the last couple bug fixes related to this
