### ISSUE TITLE
Some tribute bugs during the thunderstorm

### ISSUE THREAD

**Issue by Kagaribi172** [Tslat/Advent-Of-Ascension#2281]
**Mod Version**
3.4.5

**Describe the bug**
During the thunderstorm, Tribute cannot fill and it grant buffs in the daytime.

**Expected behavior**
Tribute should be able to fill and it shouldn't grant any buffs in the daytime.

**Comment by Tslat** [comment]
What kind of tribute? What are you doing exactly

**Comment by Kagaribi172** [comment]
You seem to be able to reproduce this bug exactly...
https://discord.com/channels/434160774546456590/434160774546456594/803374639975104532

**Comment by Tslat** [comment]
yes but it still helps to know what things you're doing in case there's an area I'm missing

**Comment by Kagaribi172** [comment]
To reproduce
1.Set the time to day
2.Fill any tribute
3.Set the weather to thunder
4.Check out effect

**Comment by Tslat** [comment]
This actually comes down to a vanilla bug where the game thinks it's daytime during thunder.. which is absurd, but out of my control.
