### ISSUE TITLE
Boss trophies placed by other players can't see

### ISSUE THREAD

**Issue by Kagaribi172** [Tslat/Advent-Of-Ascension#2284]
**Mod Version**
3.4.5

**Describe the bug**
Boss trophies placed by other players can't see.

Check out this video:
https://youtu.be/i79yTzhmxaM

**Comment by Tslat** [comment]
Can't seem to replicate this

**Comment by Kagaribi172** [comment]
Further info:
・Reconnecting to the server will fix.
・Trophy placed by other players is named "Gold Trophy", but it should be "Gold (Boss name) Trophy".

![Inked2021-01-26_18 51 42_LI](https://user-images.githubusercontent.com/63949302/105830710-30861d80-6009-11eb-8f38-d959fa0d847a.jpg)
![Inked2021-01-26_18 51 37_LI](https://user-images.githubusercontent.com/63949302/105830715-324fe100-6009-11eb-933f-6e690660f60d.jpg)

**Comment by Tslat** [comment]
Yeah that happens when the data isn't synced from server to client - but that's a forge function...

**Comment by Kagaribi172** [comment]
Is this a bad thing?

![スクリーンショット (436)](https://user-images.githubusercontent.com/63949302/105907864-d5841300-6068-11eb-989f-392dced7e6aa.png)

**Comment by Tslat** [comment]
no that's normal.

I'm wondering if something on your server is blocking packet syncs or something
