### ISSUE TITLE
Tea is bugged.

### ISSUE THREAD

**Issue by Neylar** [Tslat/Advent-Of-Ascension#2289]
Mod Version
3.4.5

Describe the bug
If you try to drink stacked tea all your tea will be replaced by only one empty cup, but you will receive some buffs. For example: you have 36 tea cups, you drink one and all of them turn into 1 cup, now you have only 1 empty cup.

To Reproduce just try to drink some tea.

**Comment by Tslat** [comment]
I'm gonna make t
