### ISSUE TITLE
Guardians(vanilla) do not drop biogenic armor pieces

### ISSUE THREAD

**Issue by HimmelFernweh** [Tslat/Advent-Of-Ascension#2290]
Mod Version
3.4.5 on 1.15.2

Guardians and elder guardians(vanilla hostile mobs which spawn near ocean monument) do not drop biogenic armor pieces when killed. 

To reproduce, you can just kill many guardians and view their drops, or you can view their drops by the mod Just Enough Resources.

Expected behavior: Guardians and elder guardians are supposed to drop biogenic armor pieces, as the [wiki](https://adventofascension.gamepedia.com/Biogenic_Armor) says.

**Comment by Tslat** [comment]
Known.
It was disabled due to forge not implementing loot modifiers properly.
It'll come back when they finally fix it
