### ISSUE TITLE
Spawning issues with pixons

### ISSUE THREAD

**Issue by odw500** [Tslat/Advent-Of-Ascension#2292]
(Using version 3.4.5)
While playing my survival world on 1.15.2, I noticed that I haven't seen any Glistening Pixons anywhere. I loaded a new world in creative mode to see if they still spawn and it seems they do, but only around where the player first spawns in the overworld. I flew out far in creative and did not see any clusters of pixons anywhere. To make sure I wasnt missing any pixons hiding (i.e. behind trees) I checked on a superflat world and had the same result where I could not find pixons in newly-generated chunks.

In lighter dimensions where pixons can be found, a large cluster of pixons spawns around where the portal back to the overworld is generated, and it seems that they can still spawn in new chunks but more rarely.

In darker dimensions (Abyss, Dustopia and Mysterium), Pixons do not spawn at all.

**Comment by AstralScourge** [comment]
This seems like what I experienced. They eventually appeared after a long search for me (near the origin, like he said), while after that I made a new world and teleported a couple places far away and they appeared instantly. Not sure what this implies, but it would definitely seem as if there's something wrong with pixon spawning, which is absolutely not just "vanilla animals but slightly less" right now.

Also, I did see some in the abyss both times I went there.

**Comment by Psychotrickser** [comment]
I can confirm that but there's an exception to that. 
If you type '/kill @e[type=aoa3:glistening_pixon]' in the chat and kill all pixons they start spawning again wherever you go. But this effect resets if you die. So you have to type in '/kill @e[type=aoa3:glistening_pixon]' again to allow them to start spawning again. Weird.
I've tried this with just AoA installed without texture packs or shaders

**Comment by AstralScourge** [comment]
Is there a limit to the amount of pixons in the world at one time or something? I have no idea how that would even work but that would explain all of the above behavior, as well as why they spawned at my base after I harvested them at the origin despite having looked for two hours before that and finding high double digit numbers of every animal without a single pixon.

**Comment by Neylar** [comment]
> (Using version 3.4.5)
> While playing my survival world on 1.15.2, I noticed that I haven't seen any Glistening Pixons anywhere. I loaded a new world in creative mode to see if they still spawn and it seems they do, but only around where the player first spawns in the overworld. I flew out far in creative and did not see any clusters of pixons anywhere. To make sure I wasnt missing any pixons hiding (i.e. behind trees) I checked on a superflat world and had the same result where I could not find pixons in newly-generated chunks.
> 
> In lighter dimensions where pixons can be found, a large cluster of pixons spawns around where the portal back to the overworld is generated, and it seems that they can still spawn in new chunks but more rarely.
> 
> In darker dimensions (Abyss, Dustopia and Mysterium), Pixons do not spawn at all.

Dude, pixons in dark dimensions are easiest pixons in mod if you know how they spawn. In my investigations, I discovered that pixons in those dimensions spawn nearby blocks that produce light. Just right now, go in dustopia and place some torches. They'll spawn right in front of you.
