### ISSUE TITLE
L'Borean Trench- a way to make water breathing more useful

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#230]
**Describe the new feature you think would be good to add**
As it stands, Water breathing is really only useful in the Overworld, since it's the only place with an actual deep body of water, the only exception is if you're using water + Utopian armor to cheese everything.
I think have a solution to make it more useful and give L'Borean way more water *without* screwing with the surface gen.

Rarely, giant deep lakes would spawn in L'Borean. The lakes would be around ~30-40 blocks long in length and width, and pretty much the entirety of these lakes would be around ~25 blocks deep. Coral could even spawn on the bottom of these lakes.

But at the bottom of these lakes... Would be a ravine, leading down to a trench going down to Bedrock level. (They'd be around ~30 blocks deep going by the surface's Y level and how deep the lakes are)

In terms of shape, these trenches are similar to ravines, with the exceptions being that they'd be a bit more wider at the bottom, and that they're more expansive and maze-like than vanilla ravines. Possible content in here would include an "ore" of sorts that spawns in these underwater trenches, or other materials the player could find in there to make trench-themed items, etc. 
The size of the trenches would be larger than the lakes, but the lakes would act as the main entrance to them. (Other than digging)

![image](https://user-images.githubusercontent.com/38159897/50791967-4ab0ff80-1278-11e9-860b-707eb036d857.png)

The tough mobs down here would be based on the stuff you would find in places like the Mariana trench. You can even make use of making certain parts of their body glow (https://github.com/Tslat/Advent-Of-Ascension/issues/92) to emulate bioluminescence.
You could even have naturally spawning hunter mobs down in the trench like how Fischers work in Vox Ponds.

As an added effect, swimming in the trench (AKA being at a certain Y level while underwater in L'Borean) causes your air meter to go down twice as fast due to the high pressure (and take more damage when drowning?). This wouldn't affect water breathing, and eating Bubble Berries puts the air meter back at normal speed for ~3 seconds.

It would also be neat to have a darker variant of Borean stone in this trench to really get that feel of darkness. The block itself could be pretty hard to break to sort of stop people from cheesing everything.

**Add any alternative implementations you think might work**
Actually, the trenches don't need to be limited to lakes, what if *all* of L'Borean had an underground trench maze? The lakes would mainly act as convenient entrances.

Not sure what impact it would have on performance, but I think it would do a better job of giving L'Borean a "dark side" rather than being a large "structure" under a lake...

**Comment by Tslat** [comment]
Wouldn't they just kind of feel just like normal caves but filled with water though?

**Comment by Cruuk** [comment]
> 
> 
> Wouldn't they just kind of feel just like normal caves but filled with water though?

Yes, but even then L'Borean really doesn't have anything underground at all so I think something like this could give it a "twist". And personally I've never been against more "caves" to explore as long as they're not just the exact same as vanilla ones.

**Comment by Sagisolar** [comment]
Because the L'Borean ins't really a dimension for underground stuff. Just make it very deep water that in the massive lakes.
