### ISSUE TITLE
Player model does not "aim" loaded AoA crossbows

### ISSUE THREAD

**Issue by odw500** [Tslat/Advent-Of-Ascension#2300]
(Using version 3.4.5)
Not sure if anyone's seen or pointed this out yet but when holding a loaded AoA crossbow, the player doesn't aim it as they would with a drawn-back bow or a regular loaded crossbow. 

Here, the crossbow is loaded but is being held as though it isn't loaded. The same applies to the other AoA crossbows as well.

![2021-02-01_17 21 54](https://user-images.githubusercontent.com/52132442/106494531-74b66980-64b2-11eb-98c4-c2a5ff4521f5.png)

**Comment by EatingSilencer** [comment]
This is a known issue ([https://github.com/Tslat/Advent-Of-Ascension/issues/2011](https://github.com/Tslat/Advent-Of-Ascension/issues/2011)), to which scimi confirmed its unfixable.
