### ISSUE TITLE
the creation skill remains blocked level 1

### ISSUE THREAD

**Issue by fowlc78** [Tslat/Advent-Of-Ascension#2301]
_![Modpack](https://user-images.githubusercontent.com/78416526/106592044-4d61aa00-654f-11eb-96c9-2fcc2919f452.png)
**Mod Version**
1.15.2 3.4.4/3.4.5 in server and solo
(the list of mods attached)

**Describe the bug**
It is not possible to increase skill creation using the summons tablets. On server I cannot increase the skills even using commands which cannot find the name of the skills / aoa player <target> skills <Skill Name> (not found)

thank you in advance,

Fowlc_

sorry i am stupid T_T Thx

**Comment by Tslat** [comment]
You don't increase the creation skill by using slabs, you increase it by sacrificing them on the Creation Forge.

The commands _do_ work, it's just that forge has a bug that makes it look like they don't.
If you type the command like normal, it'll still work:
`/aoa player @p skills HUNTER level set 100`

Also, update to 3.4.5
