### ISSUE TITLE
The world just stops and I can't do anything, even save my progress

### ISSUE THREAD

**Issue by DamicTM** [Tslat/Advent-Of-Ascension#2304]
**Mod Version**
3.4.6-1.15.2

**Describe the bug**
when I go to the world of Mysterium or to Lilithium, my world just stops, I can move, but all my actions do not work, mobs stop and even loading chunks, but I do not crash and show no error.
and when I try to leave the world in the main thing, I just have a picture of “Saving the World” and nothing further happens. Help me please!!
and I can close the mine only through the Task Manager otherwise.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Mysterium or to Lilithium
2. Click on (i don't click)
4. my world just stops, I can move, but all my actions do not work, mobs stop and even loading chunks, but I do not crash and show no error.
and when I try to leave the world in the main thing, I just have a picture of “Saving the World” and nothing further happens.

**Expected behavior**
The world just stops and I can't do anything, even save my progress

[**Screenshots**]
<blockquote class="imgur-embed-pub" lang="en" data-id="u9tEeHL"><a href="https://imgur.com/u9tEeHL">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by EatingSilencer** [comment]
Do you have Quark installed? If you do, you might have to disable the big dungeon in Quark's config file. 

If not, post the latest.log file after you try to access those dimensions.

**Comment by DamicTM** [comment]
IT WORKED . Thank you so much you helped me a lot !!
