### ISSUE TITLE
Client crashed when I enter The Abyss

### ISSUE THREAD

**Issue by Taoist-Yu** [Tslat/Advent-Of-Ascension#2305]
**Mod Version**
3.4.5

**Describe the bug**
As I enter The Abyss and wait for some seconds, the client crashed

**Client log**
[2021-02-07-23.log](https://github.com/Tslat/Advent-Of-Ascension/files/5937490/2021-02-07-23.log)

**Crash report**
[crash-2021-02-07_03.15.29-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/5937488/crash-2021-02-07_03.15.29-client.txt)

**Comment by Taoist-Yu** [comment]
And my seed is -8729285236589095987

**Comment by EatingSilencer** [comment]
This crash log mentions a different mod (fastutil). Not sure if that's significant.

3.4.6 is the latest version of AoA btw.

**Comment by Psychotrickser** [comment]
I'm having the exact same crashes inside of Abyss too as well as my team mates. But I think it's a client-side mod causing that. The mods you and me have in common: 
-Phosphor
-Optifine HD_U_G6

My crash report: 
[crash-2021-01-30_19.53.35-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/5937728/crash-2021-01-30_19.53.35-client.txt)

**Comment by Tslat** [comment]
This was fixed in 3.4.6.
Update your mod, both of you.
