### ISSUE TITLE
Ideas for boss reworks (covers general ideas and overworld bosses for now)

### ISSUE THREAD

**Issue by zero-breaker** [Tslat/Advent-Of-Ascension#2309]
I'm sure this won't be considered until much, much later (when every other issue for the mod has been sorted out), but reworked bosses would be big - not just for the improvement to mod content but also in exposure ~~because modded bosses make for good clickbait~~
Here's a bit (read: a lot) of ideas for (entirely personal preference, but) what'd hopefully be interesting and balanced-in-difficulty bosses.

---

### **General Stuff**
-Let bosses have multiple attacks they can cycle/pick from. Not only does it deal with the 'zombie reskin' issue, this also allows bosses to have more tools to deal with multiple situations that doesn't end up with loading up their every attack with bullshit. Randomly picking between these attacks when conditions are met should be fine enough if a player can tell what they're doing (or at least a general picture) beforehand.
 
-As an addendum to the previous point: Please let all bosses have ways to handle being outranged and shields. They don't even have to be particularly strong ways, just, keep them from being a sitting duck when it happens?

-Make sure bosses attack with motions that cover where they'd hit, and not just dealing damage to players whenever it's in range. I'm aware that hitboxes in Minecraft are all wacky and stuff, but being able to tell when and where something big's attacking is a godsend and gives more leeway in having attacks do big damage now that players don't get their health deleted without warning.
 
-Actually, just have visual indicators for everything the bosses do. Everything that's not generic movement. Faster motion for less impressive actions, slower motion for longer and more powerful moves, effects left behind from teleporting so you can actually find the bosses, fore-warning lines and marks for projectiles that aren't just lobbed at you, the likes. Having starting and end motions also create windows during which players can attack safely, and makes it possible to have reasonable fights include brutal attacks that leave no room for players to breathe outside of those windows.
 
-High HP doesn't necessarily make for a harder fight, but it absolutely makes for a more tedious one. Having bosses rely more on intense attacks or high agility to avoid being damaged instead of being damage sponges that take forever to kill would reward skill and streamline the process of grinding for drops while still being challenging to fight without experiences.
 
-Gain the ability to shift between players to target depending on how far it is from each player. Melee-focused bosses would naturally prefer closer players, while range-based bosses would seek out long- or mid-range players.
 
-Maybe give a bunch of them that do jumping attacks fall damage reduction or immunity? A boss hurting itself from how high it can jump seems hilariously ridiculous.
 
 ---

Onto the bosses.
Only the two Overworld bosses for now as an... interest check? Making sure things here aren't overboard? That kind of stuff.
Things like HP and damage don't have specified values below because I don't really feel confident in setting values for them. I'm aware that HP regeneration is extremely busted in Minecraft, so getting a good balance between piddly damage that's quickly recoverable from and big numbers that kills people with a mistake or two is hard.
These might also be asking for a lot in terms of animations and coding required, so uhhhhh... sorry in advance?

---

### **Smash**
Being the first boss most player will fight, a set of behavior that are easily understandable and displays the mechanics that bosses in general would (ideally) have seems to be the best option.
 
-Can now jump for 3 blocks tall and in the middle of attacks as well. Half of the players dump it into a hole and whack away currently, so a wake-up call can't hurt.
 
-Gains the following attacks:
-> **Swing**: A horizontal swing of its club. Simply does damage, and can be used up to two times in a row with only a brief pause inbetween. Can be blocked by shields.
-> **Slam**: Raises club up for a moment, then slams down onto the ground. Does damage and strong upwards knockback to an area around it (including below Smash itself), but has slow starting and ending animation which leaves it open to attacks. Can be blocked by shields, but disable them for 5 seconds.
 
-Gains then immediately uses the following attack when reaching 50% HP or below, and uses this attack normally afterwards:
-> **Swinging Run**: Dashes forward while swinging its club left and right repeatedly, hitting everything in its path. Moves for a set distance or until it hits a wall, after which it takes a short pause. May jump in the middle of this attack. Can be blocked by shields
 
-Gains the following attack if it cannot reach the player - whether due to distance or height difference - and use this attack at a lower rate than the ones above:
-> **Jumping Slam**: Crouches down for a moment, then launches itself at the player with a powerful jump and with club raised, landing with a slam of its club. Capable of leaping for impressive height and distance (unsure how much is too much. 8 blocks vertically and 16 blocks horizontally max?), while the slam does more damage and knockback than the regular attack. However, it's left vulnerable for longer as well, making it a great opportunity to attack. Can be blocked by shields, but disable them for 5 sec.
 
-Gains then immediately uses the folloing attack if the two conditions above (reach below 50% HP, cannot reach player) are fulfilled, and use this attack at a lower rate than the ones above:
-> **Club Lob**: Throws its club at where the player stands, then runs in with a shoulder tackle before picking the club back up. The thrown club does damage and knockback similar to its slams, but also inflict a slowness debuff on hit. The tackle does fairly high damage as well, and the two hits combined can take out unsuspecting players. It is possible to block Smash's access to the club (either physically with obstacles it can't get around, or moving it out of Smash's detection range), in which case it can no longer use this attack and its other attacks are premanently weakened in both damage and knockback. Cannot be blocked by shields, and disable them for 5 sec.
 
**Expected scenario:**
With rigid moves that leave it open to attack, Smash should be a lot more reasonable for close-range combat while also doing enough damage that players still have to be careful and watch its motions.
As a melee-oriented boss, ranged weapons will still prove advantageous against Smash, but players now have to worry about it closing the distance with Swinging Run and Jumping Slam now.
The fact that removing its access from its club weakens it can be somewhat of a reward for players who take the effort to construct ways to do so.

 ---

### **Corallus**
One of the few water-themed bosses in the mod, and the other two are both locked to Tier 3 ~~and also in a dimension that currently doesn't even have large lakes much less oceans~~
Considering it also looks more sleek than the other two, making a hydrodynamic boss out of it could be very interesting.
 
-Will attempt to stay in or close to areas that fulfill its spawn conditions. Thorough the fight, unless the player is in the water body as well or made it impossible for Corallus to access the water body, it will swim around in water and only surface occasionally to attack.
 
-When in water, it'll try to circle around the player (or strafe left and right if full circles are impossible) when not attacking. If the player is in the water body as well, it'll swim up and down to throw off the player.
 
-It'll now only shift to Strong Form if it's unable to access a suitable water body for a long period of time. In addition to the current attack damage up, it'll receive enhancements to attack and movement speed, but at the cost of losing HP every second. Strong Form here only lasts until Corallus is left with 20% of its max HP to prevent it killing itself.
 
-Gains the following attacks:
-> **Claw Swipe**: Swims past or runs at the player depending on whether they're in water or on land, while performing rapid consecutive slashes. Does middling damage and low knockback, but has a fast attack speed that allows it to hit the player multiple times at once. Can be blocked by shields.
-> **Grapple**: Swims or walks towards the player until they are in melee range, at which point it grabs hold of the player and damages them continuously with its claws and fangs. At the same time, it  will attempt to drag the player into the nearest water body if they are on land, and sink to the bottom of the water body. The grip is broken when it takes sufficient damage. Cannot be blocked by shields.
-> **Coral Bomber**: Leaps up from either the ground or water surface, and spawns 3-4 Coral Bombs (or more depending on how many players are nearby) at the peak of its jump. Pretty much the same as the current special attack, but with the added caveat of a landing animation that leaves it prone for a moment. Can be blocked by shields.
-> **Skydive**: Leaps up from either the ground or water surface, and dives from above straight towards where the player is. Deals high damage, and leaves it prone for a shorter duration than Coral Bomber upon landing. Can be blocked by shields, but leave them disabled for 5 sec.
 
-Gains the folloing attacks if the player is in water:
-> **Coral Torpedo**: Quickly moves left and right, while leaving 1-2 Coral Bombs at its previous position to fire at the player. Can be blocked by shields.
-> **Depth Charge**: Sinks to the bottom of the water body, then follows below the player while spawning Coral Bombs consecutively which will float up towards the player. Can be blocked by shields.
 
-Gains the following attack when in Strong Form:
-> **Grapple Rush**: Jumps at the player after a long starting motion, attempting to grab onto them for strong continuous damage. If the jump misses, it can quickly take another attempt at this for multiple times after landing, before needing to stop. Can be knocked off in the same way as Grapple. Cannot be blocked by shields.
-> **Coral Drive**: A combination of Coral Bomber and Skydive, where it fire the Coral Bombs then dive at the player. Ends with a significantly longer prone state upon landing, though the combination of dive and Coral Bomb can be deadly. The dive can be blocked by shields but disable them for 5 sec, while the Coral Bombs can be blocked with no issue.

**Expected scenario:**
A boss that encourages fighting it in water. Players trying to stay on shore will have to wait for it to surface while avoiding being dragged into water, while those willing to jump in can take down Corallus much faster at the cost of having to deal with a slew of Coral Bombs and Corallus' own tricky movement.
With proper planning, it's possible to deny Corallus of its water body and force it to fight a losing battle with the self-damaging effect of its Strong Form, as long as players can handle the risk of fighting/dealing with said form.

**Comment by DiamondWalker** [comment]
While bosses most definitely need improvement, I don't agree with some things here. I don't think all bosses should have attack indicators, nor should they all have low health. They should be varied, with different fighting styles. Some should be endurance tests, while others should be shorter and more chaotic. I don't think they should all have indicators because sometimes you should have to rely on your own reaction time to figure out what's going and how to dodge it. Basically, the way I see it:

-some should be long but easier to avoid

-some should be short but very deadly

-some should have clear but deadly attacks

-some should be more random (but still dodgeable)

**Comment by zero-breaker** [comment]
~~aw yeah a reply~~
This whole write-up *is* based on personal preferences, after all :P
I'm not expecting anywhere close to everything being picked up, either, but if any of the ideas get used in some form or way I'll probably go and actually celebrate lol

For the attack indicator part, perhaps I should've worded it better. Having tells for boss action is still something I find important, as it reduces confusion on inexperienced players' part (hard to learn how to deal with an attack that just brutally mauled you out of nowhere when you don't know when it's coming), and I did note that indicators (be it sound effects, motions, environmental effects, particles etc) can show up for longer or shorter periods depending on the action in question, but revising that a bit here:
-> how strong the attack is
-> how difficult the attack is to dodge/defend from
-> how hard it is to recover from failing to deal with the attack
could all be a factor of consideration for the duration, clarity and whether an indicator needs to exist at all.
Something like a simple smack wouldn't really need an indicator because it wouldn't do *that* much damage (unless it's the current Kror) and one could just hold up a shield/backstep to defend from further attacks, but things like an AoE smash that rockets players upwards certainly need more of a warning considering the range, (attack + fall) damage and the part where players' mobility is hampered in the air and the boss can follow up with another attack much more easily.
This is mostly influenced by my experiences with other games where it's easy to tell the bosses are attacking, but actually knowing where to stand/what to do and surviving the attacks are another matter. 

And for the endurance test idea, yes, endurance match bosses are a great fun at times... except with the loot system as is (equipments not guaranteed to drop, especially with armor sets) efficiency when it comes to grinding against the same boss multiple times has to be taken into consideration.
An endurance boss might be fun the first few time around, but if one has to cut all that HP down for like the tenth time or more it gets tedious, not to mention the material cost (since endurance matches naturally take more recovery items and eat away durability of items more). I feel that it's much more preferable to have bosses last longer for inexperienced players who need to learn as they go, and shorter for people who know what they're doing and has understood/memorized the patterns and mechanisms.
~~that said if there are ways to guarantee drops id kill for a long fight against some of the later bosses~~
