### ISSUE TITLE
Snowstorm Staff

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#231]
A little while ago, Xol revealed a staff called Snowstorm Staff.
![snowstorm_staff](https://user-images.githubusercontent.com/44548547/50799608-9e513680-12d4-11e9-816f-81245fd7c051.png)

I like the idea of a staff from snow biomes.
I think it could be a cool alternative to the Noxious Staff, It would fire a blizzard of projectiles like it but it would do less damage but applies slowness to the targets.

**Comment by Armakeen** [comment]
I like the idea of a staff that inflicts slowness
