### ISSUE TITLE
Add the dimension name in front of ores

### ISSUE THREAD

**Issue by CandyPillager** [Tslat/Advent-Of-Ascension#2311]
**Describe/name the existing feature this suggestion relates to**
all the different kinds of ores from all dimensions

**Describe the change or feature you think would be good to see**
just add the name in front of the ore, like "Iromine Lyon Ore" this makes knowing what dimension an ore is from way easier, and searching the ores in JEI a lot easier too. 

**Add any alternative implementations you think might work**
uh not as far as I know

this is just a simple and small idea

**Comment by EatingSilencer** [comment]
I feel this would be better as a part of the tooltip than as a part of the name, if it were implemented.
