### ISSUE TITLE
a weird glitch

### ISSUE THREAD

**Issue by xTyler200** [Tslat/Advent-Of-Ascension#2313]
1.7.10
1.1.2
a dupe glitch
I try to make a modpack on curseforge using this mod but when i joined it crashed and it said enchantment dupe id

**To Reproduce**
Steps to reproduce the behaviour:
1. i went to curseforge
2. i downloaded the mod
3. i press play

**Expected behavior**
i thought it would load up automaticly then an error popped up

**Screenshots**
![error1](https://user-images.githubusercontent.com/79031543/107866872-66b60080-6e43-11eb-9b2e-db0e8b7cc448.PNG)
![error2](https://user-images.githubusercontent.com/79031543/107866900-6d447800-6e43-11eb-8ae2-faffb2f2e331.PNG)

**Comment by Tslat** [comment]
We don't support 1.7.10 anymore, it's ancient as hell.

Probably an incompatibility with AM2, or they have their enchantments set up to be configurable IDs, might be something in their config idk

**Comment by xTyler200** [comment]
oh so its not compatible with AM2 ok now i get it
