### ISSUE TITLE
Dealing with overworld mob bloat

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#2318]
It's been pointed out a couple of times that the overworld has a huge amount of bloat, having around 90 mobs compared to all other dimensions having around 10 (a much more reasonable and manageable number). The point of this suggestion is to point out mobs that can be removed from the overworld to trim down this number without affecting the more iconic enemies.

For starters, events. The soul scurry is very unoriginal and boring; all the mobs there are just recolors. It servers no purpose, and it can easily be removed. The same goes for the lunar invasion. It's almost the same as the full moon, and the only memorable part about it was being burned alive inside your home before the walker was fixed. For me the only mob that might be worth keeping is the modulo, and it can fit much better in lunalus (same goes for any other mobs that end up staying for some reason). The blood hunt is pretty cool (at least for me), but it or its mobs could be moved to the nether or abyss.

The big day and creep day events could be removed too, for obvious reasons. Now you only have 2 night and 1 day event for the overworld; much better than the 7 there are now.

Now, for mobs in general.

-the ancient golem really has no reason for existing. He isn't iconic in any way, and there's nothing about him that stands out from other mobs.

-bonebacks are the same as other savanna mobs, except without useful drops or special abilities

-bone creatures are just skeletons but weirder and more boring. I guess the stunning is interesting, but that's already used elsewhere

-brutes are just fat cyclopes. I rarely see them, and I'm pretty sure almost no one remembers they exist

-bush babies are weird and are generic melee mobs. Stingers already make the jungles more interesting with how deadly they are, and if you want to make them even better their design would allow them to shoot darts or have some unique ability like that

-demon reapers. They're rare... and that's about it

-Everbeast. Same as demon reapers.

-Fishix: plenty of swamp mobs, and they're probably the least interesting.

-Grunt: There's already two mountain enemies, and these are pretty forgettable.

-Hondrons: forgettable and pointless

-Sasquatch: they're like cyclopes and spawn in the same conditions. Any reason to keep them?

-Skolle: enough taiga mobs

-Sphinx: how do they even move? Enough desert mobs...

-Spinux: ngl I forgot they existed

-Void charger: I honestly like the charger varieties. They're technically one enemy with many variants so they don't affect bloat too much, but void chargers feel out of place and don't really make sense.

-Warclops: Cyclopes but rare? They can just be merged with regular cyclopes

-Wickett: the desert already has sand golems and furlions. Also, these creatures look like they'd belong in the nether and feel out of place. Move or delete.

And that's 34 mobs that can be removed from the overworld while barely affecting the mod. While there's still a lot left, I think it should be fine. After all, the overworld is the "main dimension" and has many biomes. I'm assuming other dimensions might also be getting a few more mobs in the future, so mob distribution should be more even

**Comment by EatingSilencer** [comment]
Some of your reasoning for some of these seems to be "remove this mob just because". For example, you say remove the sphinx because we have enough desert mobs...but why sphinx? Why not remove sand golem under the same logic and keep the sphinx? Its not like either has a unique drop.

You also say that the charger varieties don't affect bloat too much, which isn't really true, as the 90+ number counts the chargers as separate mobs.

**Comment by AstralScourge** [comment]
Being entirely honest, there aren't really any "iconic" mobs in AoA. The closest are chargers really because they're so prevalent and have different varieties.

@EatingSilencer Chargers do not really affect bloat at all. The 90+ number means nothing. From the development side, the amount of effort required to maintain nine mobs with the same simplistic model, sounds, etc. that differ only in the potion effect they apply on hit is minimal compared to two mobs with more complex models and abilities. And from the player's side, they're just a mob that adapts to its climate, not necessarily needless or forced compared to wicketts or naturas.

**Comment by DiamondWalker** [comment]
> 
> 
> Some of your reasoning for some of these seems to be "remove this mob just because". For example, you say remove the sphinx because we have enough desert mobs...but why sphinx? Why not remove sand golem under the same logic and keep the sphinx? Its not like either has a unique drop.
> 
> You also say that the charger varieties don't affect bloat too much, which isn't really true, as the 90+ number counts the chargers as separate mobs.

I think each biome should keep 1 or 2 mobs to make exploration more interesting. As for sphinx rather than sand golem, maybe it's just me be the sphinxes in AoA look really weird, and sand golem has more potential for drops/abilities.

As for chargers, what astral said.



> 
> 
> Being entirely honest, there aren't really any "iconic" mobs in AoA. The closest are chargers really because they're so prevalent and have different varieties.

I'd say there's definitely iconic mobs. Cyclops, goblins, ghosts, clowns, and tricksters are some of the first enemies players encounter. Most people probably have memories about these mobs, and they're also pointed out in many videos about AoA.
