### ISSUE TITLE
Improving my Caverns Music Disc with a new MP3 File!

### ISSUE THREAD

**Issue by centhusiastx2** [Tslat/Advent-Of-Ascension#2320]
**Caverns music disc with much better acoustics**

**Describe the change or feature you think would be good to see**
I've revamped my Caverns Music Disc from an 8Bit mood to more of an improved orchestral feel so it seems more present!
[Caverns IMPROVED.zip](https://github.com/Tslat/Advent-Of-Ascension/files/5993806/Caverns.IMPROVED.zip)

**Comment by Tslat** [comment]
Sounds must be mono.
Minecraft uses the stereo channel to do directionality

**Comment by centhusiastx2** [comment]
[Caverns MONO.zip](https://github.com/Tslat/Advent-Of-Ascension/files/5999116/Caverns.MONO.zip)
Here is the updated song with mono.
