### ISSUE TITLE
AoA and Astral Sorcery fatal Conflict

### ISSUE THREAD

**Issue by charmquarke** [Tslat/Advent-Of-Ascension#2321]
**Mod Version**
AoA 3.4.6 for 1.15.2

**Describe the bug**
upon entering several dimensions with Astral Sorcery also Installed, sticks on the loading world screen forever. some dimensions are excluded from this, notably; precacia and iromine

**To Reproduce**
Steps to reproduce the behaviour:
1. install forge, AoA, and Astral Sorcery
2. create a portal to an AoA dimension, ex; lelyetia or Vox Ponds
3. enter portal
4. game loads forever

**Expected behavior**
expacted dimension to load, possibly with a wierd skybox

**Comment by Tslat** [comment]
Looks to be a worldgen conflict.
This isn't really fixable in AoA's current state for 1.15.
If the worldgen system gets backported at any time in the future, this will be fixed automatically as part of it.
