### ISSUE TITLE
Remove some nether mobs

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#2322]
I think some nether mobs should be removed. AoA adds 10 mobs to the nether. The nether has 9 unique mobs in vanilla. The content from vanilla and AoA combined makes the nether larger than the AoA dimensions, even though AoA tries to treat the nether as one of its own dimensions. The mobs I think should be removed are:

-Pigotron: The idea behind them is pretty cool, but with the piglins it doesn't really fit anymore (tbh it didn't make much sense before either). Their mechanic could be used in some other dimension.

-Skeletal cowman: They were supposed to be some kind of alt to zombie pigmen, but again, they don't make much sense now with piglins

-Wither wizard: If I'm being completely honest I never understood this mob. They are in no way related to the wither mobs in vanilla. They're also just another generic mage mob, so it wouldn't be a big loss.

-Hellcat: Why do they exist??? They don't even look like a panther or whatever they're meant to be, and even if they did idk why they'd be in the nether

**Comment by EatingSilencer** [comment]
Skeletal cowman is a hunter mob - I don't know if people regularly use it for grinding. Just mentioning that, as removing skeletal cowman would mean having to adjust some things.

**Comment by DiamondWalker** [comment]
I don't think it'd cause a problem since amphibiytes are just one level earlier. Worst case scenario they can drop more XP.
