### ISSUE TITLE
The Skills system in my server are not working

### ISSUE THREAD

**Issue by ghost** [Tslat/Advent-Of-Ascension#2323]
**Mod Version**
What version of the mod are you on?
1.41

**Describe the bug**
My server and the world generated with the skills system at false. Me and my buddy advanced a bit before we learned that it even existed, and immediately turned the skills, and the resources to true. But, nothing in our world generates xp to our skills. We can mine and get the doubled and treasure items, but no skill points will be earned. It fails to work for the both of us.

**Expected behavior**
For it to work.

**Comment by Tslat** [comment]
It needs to be turned on on the server side aswell

**Comment by ghost** [comment]
> It needs to be turned on on the server side aswell

How would you do that?

**Comment by Tslat** [comment]
by the config, on the server side

**Comment by ghost** [comment]
> by the config, on the server side

Thx bb

**Comment by ghost** [comment]
> by the config, on the server side

I can’t figure it out, I’m still confused

**Comment by Tslat** [comment]
Make a complaint to the hexxit modpack dev, since I assume that's what you're playing.
The skills and resources should be enabled by default, and since it's his modpack he should have no problems working with you to fix it :)
