### ISSUE TITLE
Add a message to the AoA GUI when skills are disabled

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#2332]
Something simple like "Skills and resources are disabled, and some things may not work as intended. It's recommended that you enable them in the config file. If you are on a server, you have to enable them there as well." This should prevent another Hexxit situation, or at least mitigate it significantly.

**Comment by Minecraftgamer2121** [comment]
im on 1.16.5 and i don't see anything to fix it in the config
