### ISSUE TITLE
Hard crash with minecolonies

### ISSUE THREAD

**Issue by MrChickenWingz** [Tslat/Advent-Of-Ascension#2339]
**Mod Version**
3.4.6

**Describe the bug**
When a raid occurs with minecolonies the game will instantly close upon happening.

**To Reproduce**
Have a raid start with minecolonies.

Here is the client logs:
https://paste.ee/p/TIqAA

I also made an issue on their GitHub. https://github.com/ldtteam/minecolonies/issues/6698#event-4424081963

**Comment by Tslat** [comment]
Yeah this is fixed in the next aoa version
