### ISSUE TITLE
Mobs not spawning in multiplayer

### ISSUE THREAD

**Issue by ryanaellis** [Tslat/Advent-Of-Ascension#2343]
Me and friends started a multiplayer server with some mods and the AOA mobs are not spawning in the overworld

**Comment by Tslat** [comment]
Version?
Log file?

**Comment by ryanaellis** [comment]
1.7.10
[2021-03-12-1.log.gz](https://github.com/Tslat/Advent-Of-Ascension/files/6152137/2021-03-12-1.log.gz)

**Comment by Tslat** [comment]
We don't support 1.7.10, it's long past its time.

Check you're not using a mod that messes with mob spawning like CustomMobSpawner or something
