### ISSUE TITLE
A large portion of Immortallis is missing

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2359]
**Mod Version**
What version of the mod are you on?
3.5.-Beta-1

**Describe the bug**
All rooms after the third room (Klobber's room) are not present.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Immortallis,
2. Try to find the rooms after Klobber's.
3. See error

**Expected behavior**
All rooms are present.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/111873064-f419d280-8964-11eb-86bc-185042001dfa.png)

**Comment by legitadimc** [comment]
Same for Ancient Cavern
