### ISSUE TITLE
Reload sound for snipers and shotguns and charging sounds for blasters

### ISSUE THREAD

**Issue by TekterBR** [Tslat/Advent-Of-Ascension#236]
Not actually necessary, but should be nice to have an audio feedback when using those weapons
It would add **IMMERSION** to the mod

EDIT: The reload sound should play when the weapon is ready to shoot again, that's why it's only for Snipers and Shotguns, they have slower fire rates.
Additionaly, the reload sound should have a low volume because it could get annoying

**Comment by Sagisolar** [comment]
I support shotguns and Snipers. But not energy and normal guns.
