### ISSUE TITLE
Lelyetia doesn't teleport creative players who fall into the void to y=256

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#2364]
**Mod Version**
3,5 beta

**Describe the bug**
If you fall into the void in Lelyetia, you will be teleported back up to y=~256 in survival or adventure mode; in creative mode you just fall into the void and die as normal.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Lelyetia
2. Fall into the void in survival mode
3. Fall into the void in creative

**Expected behavior**
Falling into the void to have consistent behavior across gamemodes

**Comment by Tslat** [comment]
This is intended, was gonna change it but I want to keep it this way, purely because creative players should be able to roam away as they please
