### ISSUE TITLE
Creating a superflat world with aoa3:cavern_depths causes the game to crash

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2374]
**Mod Version**
What version of the mod are you on?
3.5-Beta-1

**Describe the bug**
Creating a superflat world with the biome aoa3:cavern_depths causes the player to crash when one of the buttons in the superflat create screen is pressed.

Here's the log:
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/6176827/latest.log)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the superflat customization screen.
2. Set biome to aoa3:cavern_depths.
3. Try to create the world.

**Expected behavior**
The game does not crash.

**Comment by Tslat** [comment]
Vanilla is stupid.
