### ISSUE TITLE
Toxic Wastes ponds will make other features float [3.5-Beta-1-1.16.5]

### ISSUE THREAD

**Issue by TelepathicGrunt** [Tslat/Advent-Of-Ascension#2375]
Basically what the title said lol. Seed and coordinates are in the picture below. But it seems to be an extremely common occurrence to find floating tentacles. This tends to be caused by the pond and/or tentacles placing their blocks outside the center chunk that the feature is generating in (and should stay in) 
![image](https://user-images.githubusercontent.com/40846040/111893646-87d9b600-89da-11eb-8a44-dd3405d151e0.png)

**Comment by Tslat** [comment]
Doesn't vanilla also do this? lol

**Comment by TelepathicGrunt** [comment]
Yep. Vanilla does this and Mojang is struggling with fixing it. They tried making a new generation stage just for lakes but forgot the issue is because lakes extends into chunks where plants are already placed and because grass/flowers can also extend into chunks before the lakes are placed. Vanilla is a mess due to that

**Comment by Tslat** [comment]
Rip
