### ISSUE TITLE
MAJOR SPAWN ISSUE [Tslat-1.1.3]

### ISSUE THREAD

**Issue by Garr890354839** [Tslat/Advent-Of-Ascension#238]
So, I think there is a catastrophic issue with your mob-spawning amounts. Normally in Minecraft, no more than 100(+/- 10) mobs are allowed to exist at once. In Immortallis (Remove "Dimension" from the front of your dimension names, please), after killing all with a mod-added command "/xu_killliving" twice, I had these 2 lines appear in the console:
`
[20:15:46] [Client thread/INFO]: [CHAT] Killed 712 of type net.minecraft.entity.EntityLiving
[20:15:53] [Client thread/INFO]: [CHAT] Killed 719 of type net.minecraft.entity.EntityLiving
`
Difficulty: Peaceful, doMobSpawning false

719 mobs in 7 seconds! It slows my game down to a halt when I look down.

**Comment by Tslat** [comment]
Advent of Ascension does not modify the maximum allowable mobs in a world or chunk.
Please confirm that this issue occurs when **no other** mods are installed?

**Comment by Garr890354839** [comment]
I wonder if it attempts to spawn all of the mobs in the same frame? I will try the clean install. I also have installed NEI, but that shouldn't affect anything
