### ISSUE TITLE
Soulstone tools don't appear to work on blocks that turn into other blocks when mined (stone/cobblestone, etc.) + more

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2388]
**Mod Version**
3.5 beta

**Describe the bug**
It seems that while Soulstone tools do work on applicable blocks that drop themselves when mined (wood, dirt, etc.), it does *not* work on blocks that drop something else (Stone dropping cobblestone, Grass dropping dirt).
To further affirm this, a Soulstone pick enchanted with silk touch does work on vanilla Stone.

Also, Soulstone pick doesn't appear to work on most Nether stuff at all. Netherrack, Basalt, Blackstone, etc. But Soulstone axe does seem to work on Crimson hyphae? (the shroom wood thing)

**To Reproduce**
Steps to reproduce the behaviour:
Use Soulstone tools on applicable blocks that drop another block when mined

**Expected behavior**
Stone giving 2 cobblestone when mined with Soulstone, etc.

**Comment by Tslat** [comment]
hmm.... This poses an issue, I'll have to think about it
