### ISSUE TITLE
The background block for AoA's advancement menu should be Ancient rock

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#239]
**Describe the new feature you think would be good to add**
AoA's (potential?) advencement menu.

**Add any alternative implementations you think might work**
It's been pretty much confirmed that AoA will be getting advancements, and advancement menus have a block background that reflects the "theme" of it.
![image](https://user-images.githubusercontent.com/38159897/51020854-a1e2f880-1534-11e9-84c4-7f78cffb0c7e.png)

And... I figured that the most fitting block for AoA's would be **Ancient Rock**.
![image](https://user-images.githubusercontent.com/38159897/51020917-d48cf100-1534-11e9-87db-7d8777550264.png)
It's nice to look at Ancient Rock is basically the most important block when it comes to progressing through the mod, being the building block of the Ancient Teleporter.

Though, I imagine that AoA won't have just 1 Advancement menu. Something like a section for skills or something could use Green Ancient Tile.
![image](https://user-images.githubusercontent.com/38159897/51021254-e3c06e80-1535-11e9-96a5-575d7edb0e15.png)

**Include any additional background information**
Really it's alright with what you go with, but please don't use blocks that are hard to look at like what DRPG is apparently doing.
![image](https://user-images.githubusercontent.com/38159897/51021380-3b5eda00-1536-11e9-96f0-df655e466b0f.png)

**Comment by Sagisolar** [comment]
Or have every dimension have their own tab
