### ISSUE TITLE
Stereo (2-channel) mob/block sounds should be changed to mono

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#2390]
As of 1.14, stereo sounds no longer fade out when you move away from the sound source, due to an OpenAL limitation (see (https://bugs.mojang.com/browse/MC-146721). While stereo sounds also ignored direction in the past, the new volume behavior makes them a bigger issue, since the sounds will always be directly on top of the player and typically louder than expected. This currently affects a number of mobs including munchers, bugeyes and banshees.

Therefore, most mob, block and weapon sounds that are not currently mono (single-channel) should be changed to such; sounds like boss spawning could be an exception since direction/distance isn't as important for those. I may be able to slowly provide corrected sounds if needed.

**Comment by Tslat** [comment]
I might have to do something to go over all the sounds in AoA to convert them or something...
There's not supposed to be any stereo sounds in AoA
