### ISSUE TITLE
Replace coral block in L'Borean whith vanailla ones

### ISSUE THREAD

**Issue by ZeroDhita** [Tslat/Advent-Of-Ascension#2393]
In the 1.16.5 L'Borean has finaly became a true underwater dimension, so I think that now that there isno longer the problem of them dyng because of them being out of water, Vanilla coral block shouud replace the ones that the mod add.
Realy I don't see any reason to keep them (the coral block that the mod adds) since there are already the Vanilla ones that are also better.

**Comment by ilija04** [comment]
I don't agree with this idea, i would like them to match vanilla; like dying when placed out of water (dead variants)

**Comment by ZeroDhita** [comment]
> I don't agree with this idea, i would like them to match vanilla; like dying when placed out of water (dead variants)

Why do youthink it's necessary to have 2 different types of Blue, yellow and pink coral ?
I  agree, green orange and white should also have dead variants and match the behaviour of vanilla ones, but I think that there is no reason to have to different blocks whith the same name and use.
