### ISSUE TITLE
Make all Chargers (Except King) the same speed as Desert Charger in snapshot 10

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#240]
I think this will add to the goofiness of the Chargerkind.
I think the slippery physics balance them so I this change might make Chargers more challenging but also more funny to fight.

**Comment by Cruuk** [comment]
Desert Charger's current speed is ridiculous. No.

I think the others can get an increase in speed but not to Desert Charger levels at all. If anything that thing needs a nerf.
