### ISSUE TITLE
CHANGE CELEVE SKY COLOUR PLEASE

### ISSUE THREAD

**Issue by Nebula240** [Tslat/Advent-Of-Ascension#2402]
**Describe/name the existing feature this suggestion relates to**
Celeve sky colour

**Describe the change or feature you think would be good to see**
Make celeve have a day/night cycle or a static sun. At least please change the colour back to yellow.

**Add any alternative implementations you think might work**
SADLY NO

**Include any additional background information**
PLEASE I TRIED THE BETA AT 3 AM AND ALMOST LOST MY SIGHT

Pictures:
![2021-03-20_03 30 52](https://user-images.githubusercontent.com/62150697/112154213-cdf16e00-8bc2-11eb-88c5-c4ab69de4722.png)

**Comment by Tslat** [comment]
On the plus side it wakes you up pretty well
