### ISSUE TITLE
Not gaining hauling experience 

### ISSUE THREAD

**Issue by vasiliscsc** [Tslat/Advent-Of-Ascension#2403]
**Mod Version**
What version of the mod are you on?
3.5-Beta-1

**Describe the bug**
Fishing does not grant Hauling experience. Used an unenchanted fishing rod in a sizeable, naturally generated river in the plains biome in the overworld. I have used an entire fishing rod without gaining a single experience point. I hit the "treasure" table a couple of times.

**To Reproduce**
Steps to reproduce the behaviour:
1. Craft an unenchanted fishing rod.
2. Go to any body of water in the overworld.
3. Fish multiple items
4. No hauling experience received.

**Expected behavior**
Hauling experience should be gained after fishing a few times.

**Screenshots**
N/A

**Comment by Tslat** [comment]
Did you get any AoA fish?

Or just nothing from hauling at all?

**Comment by vasiliscsc** [comment]
No AoA fish, nothing from hauling at all. 

Only vanilla items (raw salmon, raw cod, leather boots, enchanted bow, puffer fish).
