### ISSUE TITLE
Overworld Mobs are Spawning in Mysterium

### ISSUE THREAD

**Issue by XxDuckyUxX** [Tslat/Advent-Of-Ascension#2406]
**Mod Version**
1.16.5

**Describe the bug**
Vanilla Overworld Hostile Mobs are spawning in Mysterium. I don't know if this is intended, but I believe it is a bug. 
[ (In the screenshot I have BSL Shaders on, so I need a torch to see because Night Vision goggles didn't work and I am too lazy to turn them off.
![2021-03-24_12 07 02](https://user-images.githubusercontent.com/73115094/112353272-97d2ed80-8c99-11eb-926f-63c05582f3f8.png)

**Comment by Tslat** [comment]
Unable to replicate, and I don't see this would be possible without another mod messing with things
