### ISSUE TITLE
A bug that crashes when destroying an ender crystal with a Wither'sWrath blaster

### ISSUE THREAD

**Issue by Golden-Extreme** [Tslat/Advent-Of-Ascension#2409]
**Mod Version**
   3.3.6

**Describe the bug**
If you attack the ender crystal with Wither'sWrath blasters, it will crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. shot the ender crystal with a blaster.
2. Crash report:https://pastebin.com/F1GHAtvs

**Expected behavior**
I tried to destroy the ender crystal with a blaster.

**Comment by Tslat** [comment]
Well that's annoying.
