### ISSUE TITLE
Armor Protection Buff

### ISSUE THREAD

**Issue by MikeTheMeme** [Tslat/Advent-Of-Ascension#241]
Some armors are really tough to obtain, and while they give decent buffs, I think they shouldn't have only equal protection as Diamond Armor. Certain armors in the mod should have more protection based on the process to obtain them. For example, Primordial Armor and Commander Armor are quite hard to get. A small protection buff would do great. I would prefer a sacrifice of a set bonus to get increased defense in some armors. The armors may be very useful, but a mob that hits really hard will render it useless in some cases.

**Comment by Cruuk** [comment]
This is no longer the case in 3.0. Armor sets are now dynamic and Give certain amounts of protection depending on where they are obtained (+their ability)

Some of the earliest sets (Void, Lyndamyte, Amethind), are a little less stronger than Diamond but are stronger than Iron armor. More midgame sets like Lyonic give 23 armor (compared to Diamond's 20), and endgame stuff like Archaic armor give 26 armor.

You may think 25 armor or more is invincible but the armor system is way different than it was in 1.7 in case you didn't know.
