### ISSUE TITLE
Hiding Fungi drops experience

### ISSUE THREAD

**Issue by legitadimc** [Tslat/Advent-Of-Ascension#2418]
**Mod Version**
3.5 Beta 1

**Describe the bug**
Hiding Fungi (the blue mushrooms from taiga biomes) drop experience when punched/activated.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn a Hiding Fungi
2. Punch it
3. A Living Fungi appears, but experience drops from the Hiding one.

**Expected behavior**
Only the Living Fungi should drop experience.

Also change the name from Fungi to Fungus, since Fungi is plural of Fungus.

**Comment by EatingSilencer** [comment]
Do you mean hunter xp or vanilla experience?

**Comment by legitadimc** [comment]
> Do you mean hunter xp or vanilla experience?

vanilla
