### ISSUE TITLE
Portals should be made out of ancient rock also in dimensioins

### ISSUE THREAD

**Issue by ZeroDhita** [Tslat/Advent-Of-Ascension#2421]
Portals in dimensions right now doesen't make any sense:
They are just like in 1.7.10 before ancient teleportation was a thing so the blocks they are made out of are just random blocks from that dimension (or even worst like in Haeven, Lunalas and Abyss some wierd glowstone recolor). 
This can be easily fixed by makeing portals being made out of ancient rock.

**Comment by DiamondWalker** [comment]
The different portal blocks give them a bit more variety imo. It'd be pretty boring if all portals were made out of ancient rock.

In fact, I think activating a portal should affect the texture or the ancient teleporter frame too.
