### ISSUE TITLE
Remove carpets

### ISSUE THREAD

**Issue by ZeroDhita** [Tslat/Advent-Of-Ascension#2422]
Simply remove:
-Baron carpets
-Borean carpets
-Gardencian carpets
-Iro carpets
-Lunar carpets
They are unnecessary and useless.
Realy is there any good reason for them to stay?

**Comment by DiamondWalker** [comment]
Seems fine. What would you do about the structures that use them though?

**Comment by XxDuckyUxX** [comment]
Decorative purpose

**Comment by ZeroDhita** [comment]
Yeah decorative uncraftable blocks that can be found in one structure in some dimensions, defenetly necessay.
Who will seriously miss them?
If they realy have to stay at least they need:
-a crafting (maybe different color of wool combined?)
-to have a variant for each dimension(why only five dimensions should have them) ?

I don't think it's worth keeping them just to appear in one structure and never ever be seen again.

**Comment by DiamondWalker** [comment]
I'd suggest customizable patterned carpets (similar to banners). Would be less limited, more useful, and allow for the structure carpets to stay, but I don't think something like that fits AoA. Would probably end up being another block that never gets used.
