### ISSUE TITLE
Remove tea/tea-related things

### ISSUE THREAD

**Issue by ZeroDhita** [Tslat/Advent-Of-Ascension#2423]
Tea is just a remaining of the old calorefiction mechanic, its useless, unnecessary and nobody use it.

**Comment by EatingSilencer** [comment]
I think you're wrong on the "nobody uses it". I think some tea is actually pretty useful from what I hear.

**Comment by Cruuk** [comment]
Yeah they actually have useful effects. Have you checked what they do in the past few years?

**Comment by ZeroDhita** [comment]
Oh sorry I didn't know that It has been given a propter use.I just never realy used it since a lot of time.
I still think it's unnecessary and a bit out of place but yeah at this point it's just a personal opinion.
