### ISSUE TITLE
Remove other unnecessary blocks

### ISSUE THREAD

**Issue by ZeroDhita** [Tslat/Advent-Of-Ascension#2424]
I think these blocks are useless and they should be removed.
-Lunar Enrichment Table: Why do I need to find an useless structure, to get an useless block to just get some Lunar ingot?
Just adding a Lunar ore that can be smelted into lunar lingots.
-Crystal creators: Can be removed without any problem, just give crystals a crafting wich requiers Gemstones.
-Enigma Table: I'm sure that there is a better way to allow the player to get enigma stones.
-Haunting table: Can be removed without any problem, just give Primed Ghoulasm a crafting wich requiers Ghoulasm.
-Lunar creation table: Cam be replaced easily whith some ricipe For luar armor and observing eye.
-Lunar pad: useless without Lunar creation table.
-Petal Crafting Station: just give Hydrangic Armor a recipe.
-Runic Block: give Runic Bomb a recipe which reqires Active Rune Stone.

**Comment by DiamondWalker** [comment]
While I think it's nice to have custom crafting stations throughout the dimensions, most of these are pretty poorly executed and could be removed/reworked. Lunar enrichment table is cool though, I wouldn't remove that one.

Wouldn't removing runic block defeat the purpose of that whole minigame or whatever you want to call it? It's the only thing that makes farming runic golems interesting.

**Comment by XxDuckyUxX** [comment]
I agree, but disagree. I think they should just be given a bigger purpose instead of just for one thing.

**Comment by EatingSilencer** [comment]
@DiamondWalker Are you referring to lunar enrichment table, or lunar creation table?

**Comment by DiamondWalker** [comment]
> 
> 
> @DiamondWalker Are you referring to lunar enrichment table, or lunar creation table?

Lunar creation table

**Comment by ZeroDhita** [comment]
Yeah Lunar creation table has defenetly some potential, but it needs some changes.
It should be accesible also in other dimensions (with that I mean it needs either a crafting (and be renamed to "creation table" or somthing like that)/ have a variant of that structure spawn in other dimensions)and have some other uses (maybe it can replace infusion table for Imbuting (since enhancers are block)).

**Comment by DiamondWalker** [comment]
That seems like the opposite of what should be done.

Making it a general thing sounds like a bad idea. Dimensions are lacking in unique rewards, and although minor, a special crafting station is pretty interesting. This would make it go from being one of the few pieces of unique content in lunalus to yet another general crafting station like rune shrines, mending tables, infusion tables, etc.

Giving it the enhancer use seems to cause the same problem these suggestions are trying to solve. It takes a feature that is already part of the infusion table, and gives it to another crafting station for no reason other than finding a use for more content. It just splits the infusion table into two for no benefit, in which case it might as well just be removed.

I do think lunar creation table could be improved. Perhaps more recipes and a way to make its functionality clearer, but this doesn't seem like the right way to do it.
