### ISSUE TITLE
Second ability for Primordial armor

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#243]
(I've always been a really picky person sorry)
**Describe/name the item/content this suggestion relates to**
Primordial armor (snapshot 10)

**Describe the change/balance you think would be good to see**
Primordial armor's set bonus is now Wither immunity, making it an upgrade to Wither armor. I think this is a step in the right direction, but there's something that still concerns me.
Notice the other "upgrade" armor sets like Ghastly/Nethengeic. They have the same ability as the inferior version but also include an extra ability, and of course have more armor. Primordial has extra armor but no extra ability. It even has 25 armor which isn't as much as other endgame sets with 26 (though this is mainly because of it's old ability)

I was thinking that the second ability could involve healing, but that could get hairy real fast if it's just something like Commander, and I didn't just want it to be "withers melee attackers" that would be boring. So I tried something more original:

**Being inflicted with Wither effect heals you**

Not only would you be immune to Wither, but if you're inflicted with Wither, you would get increased health regen while the hearts are black.
The increased regen would be roughly the same as regen 2.
![image](https://user-images.githubusercontent.com/38159897/51093304-12695f80-1757-11e9-9e82-c25753285fbc.png)
(Could be like ~0.33 if that's even possible?)
The regen wouldn't change depending on the potency of the Wither effect, it'd be the same across the board.

It could stack with regen 2, but only somewhat, if you had Wither and regen 2 at the same time it would be the equivalent of like regen 3 or something.

Also, I think Primordial should probably get pushed to 26 armor since it doesn't have the dodge ability anymore. (or keep it at 25 depending on how strong the healing effect is) 

**Add any alternative implementations you think might work**
If that doesn't work, you could always keep it at just Wither immunity but give it the exact same armor and toughness as Zargonite to make up for the simple ability. That's boring though...

**Comment by TekterBR** [comment]
I completely agree with this change, since it adds **IMMERSION**

I only played 1 game with this kind of effect: Valkyrie Profile 2; and I want more of it in other games

If it don't get changed, the effect could be reserved for another new possible armor set

**Comment by Sagisolar** [comment]
I think the regeneration should be amazing so we can a armor set that at least can compare to the stupidly over-centralizing Zargonite armor.

**Comment by Tslat** [comment]
3.2 Changes the balance and stats on just about every item, including this one
