### ISSUE TITLE
Infinite blank realmstone dupe.

### ISSUE THREAD

**Issue by bludde** [Tslat/Advent-Of-Ascension#2433]
**Mod Version**
AoA3-3.5-Beta-1-1.16.5.jar

**Describe the bug**
The Worn Book that you can get from finding portal and the ghost. When opened will drop a blank realmstone. If you put this realmstone in a container and open the book again you get a new Blank realmstone, Feels wrong to get infinite realmstones from one book.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Worn book and get blank realmstone
2. Put blank realmstone in chest
3. Open worn book again and get new blank realmstone.

**Expected behavior**
Just to get one blank realmstone from book

**Screenshots**
![bild](https://user-images.githubusercontent.com/1352518/112898301-eee52200-90e0-11eb-8925-795a8ce8fe85.png)

**Comment by Tslat** [comment]
Known, intended.
Players should be able to get a new one as needed to save having to go back every time.
It's not like it's OP to have multiple realmstones lol
