### ISSUE TITLE
Rework the Face Mask

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#244]
![face_mask](https://user-images.githubusercontent.com/44548547/51261750-c3b30400-19a8-11e9-8c2e-f8d14322711d.png)
My problem with this mask is because it turns a potential unique dimension into a average dimension. Having to wear a special armor set for a dimension is cool idea, in 1.1, Vox Ponds was one of the more challenging dimensions. Then the next update this helmet came and destroyed the challenge of the dimension.

I guess we can rework it. Really don't know how though. I always found it weird that this thing is made in Vox Ponds. Perhaps it could be used in another dimension? I only one I can think of is Ethereus' water. Or it could function similar to the Shadow Shield. Maybe you take less damage from Mermage and Amphibior?

Exoid will probably have to drop more than just Doom Stones to be more useful. Probably silver or gold coins.

**Comment by Armakeen** [comment]
Face Mask isn't really easy to get since the Exoid minigame has been nerfed (you can't play it in Overworld anymore). Not many players try to get it... They only use Hazmat armor most of the time

**Comment by Sagisolar** [comment]
Yeah I know, I think it would be nice to know that you can only wear hazmat armor in Vox Ponds. No item that makes it into any other dimension

**Comment by Armakeen** [comment]
I've just realised the Exoid Minigame will become really easy if there is a version of JourneyMap compatible with AoA (we will see Exoid face on the map)

**Comment by Sagisolar** [comment]
Voxel's Mini map has that feature
