### ISSUE TITLE
A Comprehensive AoA Lore Suggestion

### ISSUE THREAD

**Issue by asagami69** [Tslat/Advent-Of-Ascension#2441]
## OVERVIEW

Hello again, Nevermine fans. Based on the current update plans, my last suggestion wasn't received all that well. I'm still very disappointed in the direction the mod is going, as it's just not the same as the mod I enjoyed years ago, and the new art style is objectively inferior.

That said, I do like the fact that the new developer is introducing lore, as I feel like that's a specialty of mine, and that lore was always missing even during the mod's original run. I liked the little tidbits such as Mysterium taking place inside of the Eeos' minds, and the small amounts of planned lore that Xolova had revealed later, but it's just not enough to feel complete. I know I said that the mod had "extensive lore" last time, but after thinking about it a little more I realized that this wasn't really true. (Before you get your hopes up, none of my other opinions have changed.)

As such, I've decided to write down my take on AoA lore here. I sacrificed some more class lecture time for this, and my homework grades will probably suffer for a while, but I think it's for the greater good, since contributing to the lore of the biggest and best Minecraft mod around will impress universities and help me pursue my goal of getting into the game design industry like Xolova did.

-------------------------------------------------------------------------------------------------------------
## LORE

Krasaun was the ultimate ruler of Minecraftia, and all dimensions inside it. He once wielded unlimited power and was capable of changing anything and everything without a thought, but despite this, Krasaun was too lazy to properly oversee Minecraftia. As a result, he created the four gods and divided a large amount of his power between them: Selyan, Luxon, Erebon, and Pluton. Each represented a different aspect of the world, and he left it to them while he returned to slumber, which he believed was a welcome trade for losing most of his power and becoming more of an observer.

Selyan represented nature, but mostly plant life. He was responsible for the plants, flowers, and trees. The latent magic present in certain species of plants (referred to as either "anima" or "mana"). Selyan was also highly present in such places like the Twilight Forest, even taking it upon himself to claim the Betweenlands when no other god wanted to touch it. One of Selyan's most prized dimensions was Tyfellenoir, the former home of the Eeos.

Luxon represented light. Light was everywhere, fully permeating Minecraftia, except for in the darkest of places, such as Dustopia. Every time someone anywhere in Minecraftia used a torch, or a lamp, or simply did anything in the daylight, they were invoking the power of Luxon. Luxon was also known for his kindness - since light was in almost every dimension, Luxon was the most powerful of the four for a time, and would likely overpower them in a straight fight (again, for a time), but allowed the other three access to other dimensions, only keeping the ones he really wanted to keep. However, some of his acts were questionable (in particular when he filled the Haven with farsighted flying mobs, and when his regeneration blessing did absolutely nothing), leading some to wonder if he has a secret sadistic side, or if he was simply oblivious to the problems these caused.

Pluton represented artifice. Technology of any sort could be traced back to Pluton, especially ore-doubling multiblock structures. Any dimension with large amounts of treasure or ore would also fall under his domain. He also represented the things that no other god wanted to touch, specifically the concepts of space, living toys, and clowns. An ancient text found within the Desert Temple suggests that the clowns scared the other three gods shitless; this is why Pluton is revered as representing bravery by some of these civilizations. In particular, he also owned all of the Orespawn dimensions, with the danger dimension being a favorite of his.

Finally, there was Erebon. Erebon was the dark horse of the four, being the embodiment of both literal darkness and negative emotions. He was a close second to Luxon in power, due to darkness similarly permeating everywhere. All sorts of dark, eldritch, and similar Minecraft dimensions fell under his control. He also fought with Selyan regularly over the Erebus. Contrary to popular belief, the Erebus was actually not named after Erebon, but it was the other way around; his birth name was "Eric Ben" but he thought it was incredibly stupid and denounced it, instead deriving the name "Erebon" from that dimension because it sounded much cooler. Despite Selyan's wish to leave the Erebus mobs in their natural states, Erebon overpowered him and made most of the mobs in the Erebus more dangerous and aggressive than they would naturally be. None of the other gods helped Selyan out, as Luxon was too busy growing candy to interfere, while Pluton had his hands full committing tax fraud.

As further testament to Erebon's power, he is also the reason why everything in Advent of Ascension, upon seeing the player, immediately stops whatever it's doing and tries to kill said player. This is because he has managed to permeate into other dimensions as well, and was far less kind than Luxon was, only kept in check by the latter.

Ultimately, the four gods were able to share balance between themselves, and everything was peaceful - until Erebon, growing dissatisfied with the limits of his power, sought to overpower the other gods and rule Minecraftia for himself.

Erebon worked to sabotage the seams between the dimensions, allowing the chaos and destruction between them to slowly leak through, which would eventually strengthen him. The other gods didn't notice it - or perhaps they did, but they were too complacent. Nonetheless, Erebon slowly started to grow stronger. Some elements of various dimensions slowly leaked into other ones - as an example, much of the random plant life in dimensions was due to Selyan's concepts mixing with other dimensions. However, due to Erebon's very nature, the benefit to the other gods was marginal compared to the power that he gained from the conflict and uncertainty - especially when his darkness was allowed to corrupt or even destroy other dimensions.

He even had spies planted in other dimensions that he didn't fully corrupt - for instance, Visualent was created based off of Visular and Visulon in order to fit into Lunalus without arousing Pluton's suspicion (using a certain video game series popular in the Overworld as inspiration). In this way, he was able to gain further control over dimensions right under their noses.

Erebon's actions were only noticed following a major slip-up when converting Cyberzon, when he turned a normal computer program into a hive-mind sentient AI that launched a bunch of nuclear missiles and killed almost everything else. This was far too much to go unnoticed, and when Pluton investigated, he and the other two gods quickly deduced that Erebon was behind this and was too dangerous to be kept alive. But Erebon had gained unlimited power at this point, and used it to subdue the other three gods. 

Eventually, the dimensional seams became too weak to hold, and broke like floodgates. This was the "Great Dimensional Clash", an event that resulted in entire species moving between dimensions. For instance, Distorters were originally from Lunalus, but Erebon personally moved them to the Abyss in order to make it even more chaotic.

During this event, many dimensions that used to exist were destroyed (one of countless examples being Tyfellenoir). Furthermore, due to the absence of the other three gods, chaos reigned in the Overworld, and many large-scale wars occurred that decimated the human population.

This massive turmoil awoke Krasaun from his endless slumber. After saving the Eeos (having remembered Selyan claiming it as his favorite dimension, he moved them into a new dimension represented by their own minds), he took it upon himself to confront Erebon. Erebon had grown too strong for Krasaun to defeat outright, but by drawing on the energy of the other three gods, Krasaun was able to restrain him temporarily, keeping him from further interfering with the world. But they knew it wouldn't hold, and when he got free again, he would likely take over every dimension and remake them as dark, undesirable, and frightening places, not unlike many of the dimensions he'd already owned. Furthermore, it took the almost all of the other gods' power to do this, which also prevented them from interfering beyond blessings, dreams, and visions.

In order to prevent Erebon's seemingly inevitable takeover, they needed new power. With nobody else to turn to, Krasaun appeared to one of the last surviving humans, pushing him on a quest to save the world. He'd seen great potential in this human, and if it went right, the human would borrow strength from the other gods, adventure through the countless realms, reach divine status, and ascend to become the sixth god, finally defeating Erebon once and for all and bringing balance to Minecraftia.

This was the Advent of Ascension, and it was the only hope for the world. You can only go up; you can never go back down...

--------------------------------------------------------------------------------------------------------------
## GAME MECHANICS
Now that I've outlined my vision for the mod's lore, I'd like to also explain some other game mechanics in terms of lore. 

### TRIBUTE
Tribute is the act of taking various actions to please the gods. The gods will give their blessings to players who they find are worthy of them.

Selyan, the god of pure, unadulterated nature, enjoys watching people farm and break crops. He also enjoys thinking about how nobody has called him out on it despite how counterintuitive to his supposed nature that is.

Luxon prefers players who pay tribute to him using the ancient relics called "essences" on the ascension shrine. That said, the other gods suspect that he might take more pleasure in watching the players frantically spam-click on the ascension shrine, further owing to his questionable character.

Erebon likes players who kill stuff, which is relatively straightforward. Note that Erebon is still the villain, and any "blessings" he gives are really just temptations to make the player join him instead. In an underhanded effort to do this, he used to give a broken strength buff. Eventually, the other gods tightened their restraint on him, so now his buff is more or less negligible, making it easier for players to ignore him.

Pluton likes players who mine ores. He also likes players who cheat the system, so he purposefully gives his blessings to players who place and mine the same ore over and over again.

### ANIMA
Anima is actually a crystallized form of Soul Power. It's sometimes called mana, and there's another mod that adds flowers that are full of a special usable form of that, but all plants seem to have anima of some sort. Ironically, no being confirmed to have a soul has ever dropped any sort of anima stone, leading people to wonder if Soul Power is really what they think it is.

### AUGURY
Augury is the process of using essences on the ascension shrine. How the name "augury" was picked is unknown - "augury" actually means "birdwatching", but birds do not seem to be involved. A common theory is that the essences were fashioned out of solidified charger droppings.

### ANCIENT CAVERN
The Ancient Cavern was the place where the gods housed the strongest and most devout followers they'd found throughout the years. These individuals spent their entire lives fighting for their god, and were immortallized as fighters who would fight anybody that came in. Unfortunately, people did not come in very often, mainly because Krasaun felt that making them frantically spam-click on the ascension shrine for hours before doing so was a good idea.

Despite being a temple and not a cavern, the Ancient Cavern was named that way because they didn't think "Ancient Temple" sounded cool enough, and Pluton suggested calling it a "cavern" as humans seemed to really like those for some reason.

### IMMORTALLIS
Immortallis was created as part of a secret agreement between Pluton and Erebon, as both would gain power upon successful completion of the dungeon. They appointed zombies (and one goblin) as the guardians of the dungeon and gave them armor and small buffs. The idea was that all the trials were long and grueling, but Pluton secretly allowed a shortcut for his own trials. He did this because he knew it would increase the player's frustration against Erebon, as the spirit killing trials were lengthy and could not be sped up.

### MOB DROPS
You may wonder why mobs in the overworld are constantly carrying random things like carved runes, coal, and metal ingots. The truth is that they're all under Erebon's influence, and are working to construct a giant golem in his name using such materials. If you go a week in the Overworld without killing a mob, this golem spawns near you. It has 3000 health and picks up blocks to throw at you, and can also deal armor piercing melee damage.

--------------------------------------------------------------------------------------------------------------
## FUTURE PROGRESSION

Finally, I'd like to provide a rough outline of what progression using this lore should look like up until you fight Erebon, the final boss. This occurs after fighting Craexxeus, the current final boss, but it's incomplete, and there's likely to be several steps before the first one shown here, as well as many other dimensions that serve to heighten the tiers of the later dimensions without necessarily having much lore importance.

- In a dream, Krasaun hints that an entity serving Erebon is driving people and creatures across Minecraftia insane, further hindering their chances of survival. In the tier 6 Miragia, you find the entity he is referring to, revealed to be "True Elusive" - the Elusive in the Abyss is also a fake (capable of making other fakes), and he uses the fake Elusive to distract foolhardy adventurers and keep himself safe from the tax authorities. Killing him will ease Corrupted Traveller's mental state, and Krasaun will point you to him in another vision.

- Corrupted Traveller reveals that he was a survivor of the Great Dimensional Clash, and is a former adventurer who knows the last of Erebon's spies. His constant dimension hopping corrupted him to the point where he can't naturally die. He tells you that his constant travellng weakened the hastily-repaired dimensional seams and is actually making Erebon stronger, so you have to find his remaining spies fast, with as little travel as possible. He reveals that the Aquatic Castle is the home of another one of these spies.

- You go back to L'borean and find the aquatic castle. It comes to life, revealing itself to be a giant multi-segmented metal worm of death called "The Eradicator", another one of Erebon's spies. ("The Destructor" felt more natural, but we already have a "Destructor" mob, and while I'm aware we already have an "Eradicator" weapon, we also have a "Dark Beast" mob and weapon so I don't see anything wrong with doing it this way.) It has a unique AI where it burrows into the ground and jumps out. It shoots lasers from its segments, and contact with its head insta-kills you regardless of armor. Defeating it gives you a Cyberzon realmstone.

- In Cyberzon, you have to go and kill the evil sentient supercomputer that co-created the Eradicator to begin with.

- With Erebon's grip on technology loosened, he focuses his energy on plant life instead. This enrages Selyan (which is only made worse by Luxon/Pluton's refusal to help him in the past), and you end up having to go to the tier 7 Capricorn to kill the corrupted Aflora, which is later revealed to be one of Selyan's physical incarnations, capable of controlling plant life across multiple dimensions. Due to Selyan/Aflora's importance in the lore, Aflora has a very complex and in-depth summoning process, which I describe here:

1. Mine for ore. Ore is in veins of one to keep it rare and balanced enough, as Aflora drops incredibly powerful stuff like a gun with a 90% chance not to consume ammo and a 60 damage sword that does four hearts of true damage recoil.

2. Convert it to ingot form at a new crafted utility block that requires resources from several different mobs, including two structure mobs.

3. In a similar manner to the ancient ring system, these are turned into boss spawner fragments at three different small hut-type structures, each differing only by the utility block they have, turning the ingot into the respective fragment. There's only a 50% chance it succeeds though, otherwise the ingot is wasted. For a 90% chance you can use a second ingot that is much rarer.

4. Once you have all three fragments you need to find a combining structure in order to combine them. This is an unbreakable large multi-layered maze-type structure with a single combining utility block at the end. Crafting recipes would be far too simple. The utility block is also unbreakable in order to encourage players to replay the maze often.

5. From there you need to obtain another item as a 1% chance drop from a mob from a different structure.

6. After this you take the combined fragments and the aforementioned item to an NPC found in a village that has no other purpose besides to combine the two and give you the enhanced boss spawner item.

7. Now you need to take the enhanced boss spawner and activate it. This can be done in a separate tower-like dungeon that is described in whatever manner the wiki described the old guardian's tower as. It's devoid of spawners or loot chests so as to avoid detracting from the experience of climbing. Use the enhanced boss spawner on the GUI-less utility block at the top to activate it, but there is a 1/5 chance it will break into the fragments and you have to start from the combining structure step again.

8. Finally you find a final separate structure, Aflora's chamber, and spawn it in there by using the activated spawner on the boss altar (it is consumed of course).

- Having freed Selyan from Luxon's control, you travel to the tier 8 domains of the three non-Erebon main gods - Selyanica, Luxonica, and Plutonus, in order to gain their blessings (you can come back here and fight them in the post-game). You then confront Erebon in his own domain, Erebonius. I've got great abilities for him but for brevity I'll leave them off for now.

- Even after you "win" the first fight, Erebon remains too strong, and manages to transport you to the Arc of Ascension, which he now controls. You fight every boss you've fought to this point, all while he summons random mobs from all dimensions, and then finally attacks you himself. This is the real final boss fight, and Erebon gains dangerous new abilities, including several insta-kill attacks.
 
- Once you kill Erebon, he gives a fully voice-acted monologue before exploding into experience orbs. Krasaun gives you a similarly voice-acted speech thanking you for saving the world, and a custom AoA credits scene rolls (hopefully I get to be on it). The credits scene has its own version of the end poem, implying that the entire adventure was just a dream following some particularly nasty trauma and the gods were just hospital staff doing a roleplay in your room.

--------------------------------------------------------------------------------------------------------------

Thanks again for reading through all of this! Regardless of what you do with this, hopefully you can finally get the mod closer to how it was originally envisioned.

**Comment by HyDefier** [comment]
Posted on April 1st... Seems seriously good though.
