### ISSUE TITLE
Cyclone (That one gun in Lelyetia)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#245]
**Describe/name the item/content this suggestion relates to**
Cyclone, that lategame gun everyone forgets about.

**Describe the change/balance you think would be good to see**
Cyclone is an enigma, I basically forgot it existed until recently. Do I really need to explain why it needs a buff? 22.5 DPS, requires level 82 Hunter cause of Zhinx dust, and you also need to buy it with 2 Lunaver coins + the Zhinx dust.

However, that's not the real reason I made this Git post. When I searched "Cyclone" on the discord to see how many times it was mentioned I saw an interesting suggestion for it and I basically wanted to bring it to light. It was Fleega that originally made this suggestion.

Consider that Cyclone has a sniper scope on it, basically Cyclone would be unique in that it would be a gun **that can scope like a sniper** allowing for more accurate aiming. It wouldn't have the other features Snipers have like increase to bullet speed, decrease to accuracy without scoping or decrease of damage at close range.

Scoping would still slow you down (it just crouching), but shooting while scoping would also increase the base damage a bit to make scoping a little advantageous, other from the increased accuracy.

It wouldn't be affected by Sharpshot armor, as it still is a regular gun that doesn't shoot bullets but just happens to have a scope.

Overall it would make Cyclone stand out among other endgame guns.
Maybe if it's too gimmicky make it so the bullets are shot at sniper speed if you shoot while scoped?

**Add any alternative implementations you think might work**
It would suck if it wouldn't work, but at least we can still just buff the damage...

**Include any additional background information**
I know Vile Vanquisher is also a regular gun that has a scope but shh....

**Comment by Sagisolar** [comment]
But how about the ability on Cyclone **AND** Vile Vanquisher?

**Comment by Tslat** [comment]
3.2 Changes the balance and stats on just about every item, including this one
