### ISSUE TITLE
Toy Towers not generating, or even not existing.

### ISSUE THREAD

**Issue by legitadimc** [Tslat/Advent-Of-Ascension#2452]
**Mod Version**
3.5 beta 2

**Describe the bug**
Toy Towers probably don't exist.

**To Reproduce**
You can either try and find one in Celeve, use /locate to see it not being listed or using /aoa structures generate to see if it generates.

**Expected behavior**
They should exist.

**Comment by EatingSilencer** [comment]
Duplicate of #2379
