### ISSUE TITLE
Remove Pop shot from Weapons case

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2459]
Why.

Weapons case is screwed over so hard by Pop shot. It is ammo for literally **1** ok weapon. There are more weapons that consume **seeds**. There is no good reason for it to be there. If it's a way to balance Weapons case, then that's dumb as hell. Weapons case is a good, balanced source of ammo but the presence of Pop shot makes me actively avoid it. Just remove it from Weapons case. Might as well add seeds to Weapons case if Pop shot can be in there haha.

You can also make a good reason to remove Pop shot from the mod as a whole, but that's not relevant here right now.

**Comment by Tslat** [comment]
Yeah alright
