### ISSUE TITLE
Make Zargonite give double HP

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#246]
In the latest snapshot, Zargonite armor gives more HP (5 extra hearts iirc). I believe this should be changed so it gives 10 extra hearts or maybe even 20. The reason I think it should be buffed this much is because it is a late game armor (requiring 80 hunter levels to obtain), and there is better armor that can be obtained much earlier in the game (namely Runic). While having so much health might sound OP, keep in mind that your health usually goes down fairly quickly. What keeps you alive is the armor's effect, which Zargonite technically lacks.

Also, two full bars of health look better than 1 and a half imo, but that's not important.

**Comment by Cruuk** [comment]
Zargonite literally has the highest protection in the game now (26 armor **8** toughness, all the other endgame sets have 4 toughness), is the hp not enough? It's the top tier tanking armor, 5 hearts is fine. You have to risk your hp to get the 5 heart shield with Runic and it has a cooldown.

**Comment by Armakeen** [comment]
Worst idea
