### ISSUE TITLE
Do something about the 'Living on the Edge' advancement

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2461]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Living on the Edge

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
Lelyetia's change so that you loop around if you fall into the void doesn't make the Living on the Edge advancement make sense anymore. A change needs to be made to it, such as removing it or moving it to another dimension.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
Idk

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
I'm not sure

**Comment by Cruuk** [comment]
Could move it to Haven
