### ISSUE TITLE
Clumps orbs cause a crash when colliding with AOA portals

### ISSUE THREAD

**Issue by ghost** [Tslat/Advent-Of-Ascension#2468]
**Mod Version**
I have tested the following combinations (on single and multiplayer)

1.15.2:
- AoA (from 3.4.6 to 3.4.8)
- Clumps  (5.0.0 and 5.0.2.6)
- forge (31.2.48 and 31.2.50)

1.16.5 beta version doesn't seems to be affected:
- AoA 3.5-beta-1
- Clumps 6.0.0.17
- forge 1.16.5 36.1.0

**Describe the bug**
When one or more experience orbs from the mod Clumps (entity type is clumps:xp_orb_big) collide with one of the AoA portals (entering the portals), a crash occurs immediately or in the next few seconds.
This issue is present with all the portals blocks and regardless of whether they are created through realmstones or picked and placed alone (creative inventory).
Here is a crash report: https://pastebin.com/tZ8Ga1xV (singleplayer)

**To Reproduce**
1. install:
    Forge 31.2.48
    Clumps-5.0.2.6
    AoA3-3.4.8
3. create or load a world in creative (just to reproduce faster, survival is affected too)
4. get a portal block  / create a portal with realmstones
5. throw some bottles' o enchanting near/in the portals or drag an experience orb into the portal

**Expected behavior**
Maybe the portals shouldn't try to teleport those specific entity.

**Notes**
- An AoA nether portal causes a crash while a normal nether portal doesn't.
- It doesn't seems to matter the dimension in which the orb goes / comes from.
- I've tested with Minecraft original launcher and MultiMC.
- I haven't tried Forge 31.2.0 (recommended build) because AoA3-3.4.8 requires Forge 31.2.27
- **I'm preparing a similar issue report for Clumps' issues page.**

**Comment by Tslat** [comment]
Fixed on Clumps side

https://github.com/jaredlll08/Clumps/issues/59
