### ISSUE TITLE
1.16.5 Beta3 lelyetia world bug

### ISSUE THREAD

**Issue by carryons6** [Tslat/Advent-Of-Ascension#2469]
**Mod Version**
What version of the mod are you on?
1.16.5 Beta3
**Describe the bug**
When you jump to the void in lelyetia world, you will be kicked by server, because flying is not enabled in this server
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by Tslat** [comment]
That just sounds like server lag combined with a bad server config
