### ISSUE TITLE
Change Craexxeus' title to "Knight of War" (Or Ancient Knight of War)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#247]
**Describe/name the existing feature this suggestion relates to**
Craexxeus' title. (Xxeus has the same title)

**Describe the change or feature you think would be good to see**
When Craexxeus was first revealed in a teaser, it also showed his title, "Knight of War".
![image](https://user-images.githubusercontent.com/38159897/51366732-e114ca80-1a9b-11e9-8bd3-91e97c9cf2c4.png)
However, when he was added it seems his title was changed to "Ancient of War".
I think Craexxeus' title should be changed to "Knight of War", I don't think "Ancient of War" is even grammatically correct. Also "knight of War" just sounds better in general.

**Add any alternative implementations you think might work**
If you still want to keep the word "Ancient" you can just make the title "Ancient Knight of War", though it may be too long. Maybe it was originally going to be that but Xol thought it was too long? Who knows.

EDIT: I guess technically it is grammatically correct, as if Craexxeus *is* an "Ancient". In that case it should be something like "The Ancient of War" or "An Ancient of War". 
At least to make it a little more obvious that the word Ancient is being used in that context for people like me...
~~He always seemed like more of a knight to me than an "Ancient" but ehh whatever.~~

**Comment by Sagisolar** [comment]
Ancient of War sounds cooler

**Comment by Sagisolar** [comment]
I think its fine how it is
