### ISSUE TITLE
Mobs not spawning in the overworld (with mob spawns at 1.0)

### ISSUE THREAD

**Issue by MoonsMess** [Tslat/Advent-Of-Ascension#2478]
As the title says the mobs from aoa3 don't spawn in the overworld (except for a single sea charger)...
The mobs spawn normally in their dimensions.
I turned the config to 1.0 but no change.

I'm playing on 1.12.2 with a bunch of other mods (notably project vibrant journeys, ice and fire, srparasites, lycanites mobs, and multimob)

**Comment by Tslat** [comment]
Does it happen with AoA on its own?
Sounds like another mod breaking things

**Comment by MoonsMess** [comment]
> Does it happen with AoA on its own?
> Sounds like another mod breaking things

I tried without any other mods and they spawn just fine...
Do mobs spawn in modded biomes or on grass? I have a few mods that add both.

Is the spawn weight effected by other mods spawn weights?
I'm playing with around 250 other mods so that would explain it

**Comment by Tslat** [comment]
If it works fine without other mods, there's some sort of conflict.

To answer your question as to whether spawn weight is affected by other mods, yes. And that's usually the culprit

**Comment by MoonsMess** [comment]
Thanks :)
