### ISSUE TITLE
Applying item rarities all across AoA

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2479]
**Describe/name the existing feature this suggestion relates to**
Item rarities (AKA entirely visual coloring for certain items)

**Describe the change or feature you think would be good to see**
3.5 has started giving certain items rarity colors, mainly the trophies and items used for Experiment w-801. So I don't see why we shouldn't apply them to all other items. It'd make it slightly easier for players to realize that loot chest/boss items are more special than crafted items, etc. Here's my opinion on what items should have them.

**__Yellow names__** ("Uncommon")
* Items exclusive to loot chests. (Weapons, etc.)
* Hunter mob weapon/armor drops.
* Silver and gold coins?
* Upgrade kits and the weapons associated with them?

**__Light blue names__** ("Rare")
* Lunaver coin?
* Items crafted with Enchanted Gunpowder.
* Boss drops like weapons and other certain exclusive boss things. Now I know Nether star is yellow, but 1. that thing is a 100% drop chance from Wither, while boss weapons aren't. 2. why the hell is that thing yellow in the first place?
* Skill crystals?
* Skill armors?
* Holy sword.
* Occult tools/Tidal gb.

**__Magenta names__** ("Epic")
* Experiment W-801. The items you need for it have magenta names. Why doesn't this have it?
* Color cannon. What else would it be?

**Comment by XxDuckyUxX** [comment]
You could also make the Realmstones from each tier have each level of rarity.

Tier 1 with White, Tier 2 with Yellow, tier 3 with Blue, and Tier 4 with Purple. It kinda makes it more organized.

You could also have boss summoning items in the uncommon or rare section.
