### ISSUE TITLE
I would like to see the integration of AOA and Tinker construct

### ISSUE THREAD

**Issue by LXNAmazing** [Tslat/Advent-Of-Ascension#248]
I would like to see the integration of AOA and Tinker construct.
Twilight Forest have this integration.
I am just want use Tinkers Survival in my modpack.
I see AOA and Tinker construct integration on 1.7.10 in ExtraTIC addon.
I think tinker construct tools better vanilla tools.

**Comment by mrcakesamurai** [comment]
There is one already. ExtraTiC.

**Comment by LXNAmazing** [comment]
ExtraTIC only on 1.7.10

**Comment by Tslat** [comment]
Done in 3.3
