### ISSUE TITLE
Expanding Upon the Dimensions of AoA

### ISSUE THREAD

**Issue by MediaMix1** [Tslat/Advent-Of-Ascension#2480]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.

As much as I love the variety of Dimensions there are to Advent of Ascension, I feel as though they need some lovin’ - similar to what Mojang did with the Nether in 1.16.

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.

I want the various dimensions to feel like they’re more than just “progression”, I want each dimension to feel like an experience, with the challenge being equal to its accessibility.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?

One thing that really bothered me was how difficult it was to make portals. We can make Nether portals with nothing but obsidian and a lighter, but we somehow can’t open a portal to the Abyss unless we go chest hunting? Please allow us to craft our own portals without having to rely on RNG. I wanna craft my Realmstones too. :(

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?

Nope, I think that’ll be all, but I’ll gladly provide more specific information later.

**Comment by Tslat** [comment]
You probably should be up to date on AoA before you make suggestions lol
I'm gonna close this one because I think we're already kinda covering what you're talking about, maybe ask around the community what's new sometime
