### ISSUE TITLE
Tribute bar

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#2482]
The tribute bar is frankly a part of AoA which can be removed entirely and the mod would be completely and utterly fine. I feel that it can be used a lot more effectively.

Firstly it resets every morning, perhaps changing it so that it loses a certain amount (maybe half?) every day would make it less of a grind everyday to try and get gold coins from Krausan's rewards.

Secondly it provides a buff during the night, some nights in which you would have to sleep due to Minecraft's Phantoms. This is just a minor inconvenience but perhaps changing some of the requirements to obtain realmstones to require certain tribute bar levels, e.g. you would need a full Pluton bar as you mine ore near bedrock for the Deeplands Realmstone.

Finally there is no negative effects to not giving tribute to the gods. I feel that certain mobs spawning when you haven't given some tribute to the gods that are lots more dangerous to kill would be a perfect reason for people to put effort into the tribute bar. Of course you could also make some enemies more dangerous than they would usually, e.g. Erebon's tribute being empty increases damage you receive.

You could also provide certain benefits to the tribute bar being filled out, e.g. double rune from rune altars when Luxon's tribute bar reaches a certain level, or better chances of getting loot from extraction with a full Pluton bar.

**Comment by DiamondWalker** [comment]
Only thing I agree with here is making it go down to half instead of zero, and even then I'm not sure.

I feel like people wouldn't like being forced to participate in some random mechanic (see temperature system), and realmstone tasks are supposed to be something you do only once.
