### ISSUE TITLE
2.5 Snapshot block in Tslat 1.1.3 

### ISSUE THREAD

**Issue by Simeodu60** [Tslat/Advent-Of-Ascension#249]
Hello there dear Scimiguy i would like that you make a little update for the Tslat 1.1.3 for adding thoses 
blocks
Leveled Post, leveled Leaves, leveled wood, leveled donut lamp and leveled glass
Darkin Post, darkin leaves, darkin wood, darkin donut lamp and darkin glass
that would be very coold for me and decoration because im making a laboratory (like Labricon)

**Comment by Cruuk** [comment]
At this point there's basically gonna be no more updates for 1.7.10 (as far as I know have any new translations even finished?).

At this point I'd just wait until Labricon becomes an actual thing that is complete. The blocks are cool but a few new blocks doesn't really justify a Tslat 1.1.4.

**Comment by Simeodu60** [comment]
just a last update and don't name it a Tslat 1.1.4 that's all

**Comment by Tslat** [comment]
Support for 1.7.10 has been dropped
