### ISSUE TITLE
Remove Carved Runes dropping from AoA mobs (3.5 Beta-4)

### ISSUE THREAD

**Issue by odw500** [Tslat/Advent-Of-Ascension#2492]
As the title says. With them becoming obtainable from loot chests again, should they not be part of mob loot tables anymore?

**Comment by Sonicwave** [comment]
They've already been made half as common than before. IMO it should stay this way, since having them only obtainable from structures might pose issues on servers as structure loot is non-renewable.

**Comment by AstralScourge** [comment]
The problem with loot chests is that they're scarce and unreliable, with the one "reliable" one being strongholds which are frustrating to find. Having other ways to get them is a good thing.

**Comment by Tslat** [comment]
Yeah this is intended
