### ISSUE TITLE
Barathos realmstone

### ISSUE THREAD

**Issue by detno** [Tslat/Advent-Of-Ascension#2500]
**Mod Version**
What version of the mod are you on? beta 3

**Describe the bug**
A clear and concise description of what the bug is. killing husk with blank realmstone doesnt trigger 

**To Reproduce**
Steps to reproduce the behaviour: kill husks

**Expected behavior**

**Screenshots**

**Comment by EatingSilencer** [comment]
Update to beta 4.

**Comment by detno** [comment]
updated to beta 4 same issue.

**Comment by Sonicwave** [comment]
Do you have any other mods installed, and does the issue still occur when you remove these mods? It's working for me in beta 4 and Forge 36.1.0.

**Comment by detno** [comment]
Yes I have couple of mods installed. I was able to acquire the creeponia realmstone. Just to make sure it's the right husk. Those spawn in the desert right?

**Comment by detno** [comment]
ok i killed a husk with the realmstone (literally) and it worked. killing a husk in inventory does not trigger. is it RNG based?

**Comment by Sonicwave** [comment]
No, you have to deal the killing blow with the realmstone itself.

**Comment by detno** [comment]
ahh ok then my mistake i thought it had to be inventory
