### ISSUE TITLE
[Crash] Game crashes while I loading game.

### ISSUE THREAD

**Issue by KrolMC** [Tslat/Advent-Of-Ascension#2505]
Game crashes when i loading game in my modpack.

Forge Version: 36.1.4
Mod Version: AoA3-3.5-1.16.5-Beta-4
Crash Log: [crash-2021-04-14_10.46.45-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/6309569/crash-2021-04-14_10.46.45-client.txt)

**Comment by SageRaziel3737** [comment]
You seem to be running quite a few mods. It's highly likely that the crash is cause by an incompatibility between the mods you're using. I'd recommend following these steps and reporting any details you uncover here as a reply.

1. Launch MineCraft with only Forge and AoA loaded. It should load fine.
2. Next, launch the game with AoA and 50% of your mods. If it loads, you know the culprit mod(s) are in the other, unloaded 50%. If it fails than you know the culprit mod(s) are in the 50% you loaded.

IF IT DIDN'T FAIL
1. Grab 50% of the remaining mods that you didn't load, and load them.
2. Continue doing this until it does fail.

IF IT DID FAIL
1. Remove 50% of the added mods that you just loaded when the game failed.
2. Relaunch to see if it fails again. If it does, repeat "IF IT DID FAIL step 1."

Following these steps and playing around with what you're loading and when, you should be able to isolate the problematic mods with a little time and effort. Let me know what you find or if you need more help.
