### ISSUE TITLE
Structure paths in /aoa structures should autocomplete

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#2506]
**Describe the change or feature you think would be good to see**
Not sure if this is technically feasible, but the structure IDs/paths in the structure commands should autocomplete. This would be more convenient than digging through the mod jar file, as the structure paths are not on Github either. If this is not possible, the paths could be documented somewhere on the wiki instead.

**Comment by Tslat** [comment]
Not really feasible, there's no list of structures available and it doesn't populate one, it pulls raw from files
