### ISSUE TITLE
Keep Lunalus at the same level as Nether

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#251]
Pretty much at the moment, the recipe for the Carved Rune of Power has changed. But one thing is very important about it. The need for a Eye of Ender. If you didn't know to craft the Eye of Ender, you need a Ender Pearl and a Blaze Powder. In other words, you need to go to the Nether to be able to make the Ancient Teleporter.

This leaves Lunalus in a weird place. At the moment its teleporter isn't present. And it will probably change cause its (kind of) spawn-able structure.

Whatever the change might be, I do want it to be next to the Nether in progression cause Lunalus isn't actually a bad first Aoa dimension.

1: The naturally spawning mobs are kinda weak, even Visulon isn't very strong. Not only that, the spawn rate is low so getting ganged up on isn't very common.
![dgdhdh](https://user-images.githubusercontent.com/44548547/51432377-6c25ca00-1c2e-11e9-80e7-8884fb98e5ef.png)
![fsgsgss](https://user-images.githubusercontent.com/44548547/51432379-7942b900-1c2e-11e9-8589-211495d25664.png)
![dgdgdgd](https://user-images.githubusercontent.com/44548547/51432380-7c3da980-1c2e-11e9-87d0-76701064ffda.png)
![afasfsf](https://user-images.githubusercontent.com/44548547/51432383-82338a80-1c2e-11e9-9684-0661d69c7be1.png)

As for both Inmates, Baumba, and Refluct. Mob update can fix them.

2: Yes the gen is the hardest in the mod. But would help new players learn about building bridges and being careful around the environment. Not only that, the gen is one of the nicest in the mod so new players might get hooked immediately.

PSA: ~Plz bring back early gen~
![69](https://user-images.githubusercontent.com/44548547/51432451-1e11c600-1c30-11e9-9f6d-85c6dbee59b9.png)

3: Zal's are really useful, making the player not just brush them off as scams and avoiding NPCs for the rest of the game.

Overall, Lunalus is great first Aoa dimension.

**Comment by Sagisolar** [comment]
My argument is that Lunalus shouldn't be locked behind another dimension. It would make it unique in the game progression.
Also:
"Yes the gen is the hardest in the mod. But would help new players learn about building bridges and being careful around the environment. Not only that, the gen is one of the nicest in the mod so new players might get hooked immediately."

**Comment by Sagisolar** [comment]
Also spawn rate isn't high so a lot of time its only you and the environment.

**Comment by Tslat** [comment]
This is outdated since 3.2
