### ISSUE TITLE
Goblin scale dmg

### ISSUE THREAD

**Issue by Nebula240** [Tslat/Advent-Of-Ascension#2510]
**Describe/name the existing feature this suggestion relates to**
Make the goblin have a damage scale instead of 2.5 DMG for all difficulties.

**Describe the change or feature you think would be good to see**
Goblins are common and are mostly found in early game, problem is they fire quickly and deal lot of damage, even on easy, that is why i suggest we change the damage per difficulty like this.

Easy: 1.5 DMG
Normal: 2 DMG
Hard: 2.5 DMG

**Comment by Cruuk** [comment]
All magic ranged mobs aren't affected by difficulty. I don't know if you can make them scale, if it's impossible you should probably change this suggestion to just nerfing Goblin
