### ISSUE TITLE
World generation 

### ISSUE THREAD

**Issue by Aggronfan** [Tslat/Advent-Of-Ascension#2524]
**Mod Version**
1.16.5   3.5-beta-4

**Describe the bug**

So I will say that I do have 1 or 2 mods that may or may not affect the generation, which is biomes o plenty and better caves from what I can tell. But the world gen still does not work even when I do the default world generation (instead of biomes o plenty world generation) so idk if it affects world gen or not.

World generation is broken for me with some dimensions and the overworld. Some of them include Deeplands, The Haven, Mysterium and Lunalus. Almost all of them do not generate structures besides the rune shrine, and if they do spawn, they spawn in weird ways. Lunalus for example has structures generally generate but are cut in half with the top part being the only part to generate in. Same for Haven with it also not spawning mobs from the spawners and lack of mobs in general spawn. Deeplands has 0 structures that generate, with only bones being generated in. Mysterium has rune shrines that spawn on the surface but that's it. The overworld also doesn't spawn structures like the amphibiyte cove (did /locate and said structure is not nearby).

It is strange as dimensions like Barathos generate all structures just fine (did not test Dustopia and Greckon yet).

**Screenshots**

![2021-04-17_16 32 17](https://user-images.githubusercontent.com/82988451/115651786-952edc80-a2c7-11eb-9d85-ff77ae21c5ee.png)

The top part of Mysterium is like this, with only a few shrines spawned in floating up in the sky.

**Comment by Cruuk** [comment]
Mysterium has a whole gigantic cave system, that's where most of the structures should be

**Comment by Tslat** [comment]
Mysterium generates underground
Amphibiyte Cove doesn't generate in the overworld anymore
Lunalus structures are still a work in progress

As for everything else, no-one else has this issue.
IF another mod is breaking worldgen, they need to fix it.
Test this without any other mods present and see if the issue persists, then find out which mod breaks it
