### ISSUE TITLE
Unable to get the Gardencia realmstone

### ISSUE THREAD

**Issue by mahorych00** [Tslat/Advent-Of-Ascension#2527]
**Mod Version**
1.16.5 Beta-4

**Describe the bug**
The in-game description states that the realmstone will be created once you kill a prehistoric carrottop; it doesn't drop or spawn, and JEI addon Just Enough Resources doesn't list it as a mob drop

**To Reproduce**
Steps to reproduce the behaviour:
1. Put a dirt block in Precasia
2. Use any type of hoe on it
3. Plant a carrot, grow it with bonemeal
4. Drop an empty realmstone on it
5. Kill the resulting prehistoric carrottop

**Expected behavior**
A Precasia Realmstone should be created

**Screenshots**
None

**Comment by Tslat** [comment]
Unable to replicate
