### ISSUE TITLE
Critical Issue: Server Hangs Indefinitely on Restart with AoA

### ISSUE THREAD

**Issue by DeliciousTea** [Tslat/Advent-Of-Ascension#2528]
**AOA Version:**   AoA3 - 3.5-Beta 4
**Forge Version:**   36.1.4

When playing with AoA on a server, the server will hang indefinitely on restart. The console reads that it has saved all chunks (including those in AoA dimensions) but then never actually completes restarting or shutting down. The process has to be killed in order to stop it. I've tried this with other mods and with AoA isolated on its own. Oddly enough, everything seems to work fine in single player.

**To Reproduce**
1. Literally start a server with the mod installed and try to restart it.

**Comment by Tslat** [comment]
Yeah someone else reported this too but I have been entirely unable to replicate it, and I have no idea what would be causing it

**Comment by DeliciousTea** [comment]
That's very strange that you can't even replicate it. My initial thought was that it had something to do with the server manager I use, but I just tried it on my PC in command prompt and it does the exact same thing, hangs indefinitely until I forcibly close the process. When AoA is removed, I get the usual full shutdown and then "press any key to continue". Is it the Forge version or something? I'm really curious because I'd love to use the mod on my server.

**Comment by DeliciousTea** [comment]
Alright so, my friend and I tried to test this a bunch. We've tried it on all the valid versions of forge that work with AoA (36.1+) and on three different hardware setups and we're both getting the same issue. This happens with a server manager on Linux AND with the command prompt on Windows. It happens with all of the 1.16 versions of AoA. It happens on Intel and AMD.

The only thing we can see that seems a little weird to us is that when AoA dimensions are saved, it saves vox_ponds twice. Once at the very beginning of chunk saving and once at the very end. Not sure if that has anything to do with it.

Hopefully this information is helpful!

**Comment by Charismara** [comment]
Same problem here. i'm using forge 36.1.16.

**Comment by Charismara** [comment]
moving from a forge server to a mohist server fixed the issue for me.

**Comment by DeliciousTea** [comment]
> 
> 
> moving from a forge server to a mohist server fixed the issue for me.

That's bizarre, I wonder what changes. I'm hesitant to move to Mohist myself since it seems pretty unstable right now and we're using a bunch of other mods...

**Comment by Diversion98** [comment]
Got this issue as well.
When I remove AOA3 from my modpack, the server stops fine when doing the /stop command
If I add it back, the server hangs on "Thread Query Listener stopped" which is the last thing a server does.

Made a new test server with only AOA3 in it and still has the issue so it's not a mod conflict.

Forge: 36.1.23
AOA3: 3.5-1.16.5-Beta-4
Java: 14

I also tested this with Java 1.8.0.291 so its not java 14 causing this

[debug.log](https://github.com/Tslat/Advent-Of-Ascension/files/6551339/debug.log)
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/6551341/latest.log)

**Comment by Tslat** [comment]
I'll keep looking for anything I can find, but with me being unable to replicate this, and it being such an odd problem, it could take a while

**Comment by Diversion98** [comment]
It is very weird that you cant replicate it
I did it with just 1 mod (aoa3) and still have it :/

If you need some testing on my end, let me know!

**Comment by Diversion98** [comment]
just checked #2255
so additional info: I tested it on windows 10 and ubuntu, same problem

I enabled verbose debugging in the config of AoA3.
new debug in this post
[debug.log](https://github.com/Tslat/Advent-Of-Ascension/files/6554931/debug.log)
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/6554933/latest.log)

**Comment by Tslat** [comment]
In your server.properties, is your `enable-query` value set to true or false?

**Comment by Diversion98** [comment]
> In your server.properties, is your `enable-query` value set to true or false?

its true, just tested it with false but still not working.

old server.properties with query = true
[server-old.txt](https://github.com/Tslat/Advent-Of-Ascension/files/6562098/server-old.txt)

new server.properties with query = false with the logs
[server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/6562092/server.txt)
[debug.log](https://github.com/Tslat/Advent-Of-Ascension/files/6562093/debug.log)
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/6562094/latest.log)

**Comment by Tslat** [comment]
Damn

**Comment by Diversion98** [comment]
Such a weird problem 😅

**Comment by Diversion98** [comment]
Just tested your new version AoA3-3.5-1.16.5-Beta-5.jar

Still the same issue :/ (just wanted to let u know)

**Comment by Tslat** [comment]
Such a weird bug

**Comment by DeliciousTea** [comment]
Apparently! It's still happening here too. I've also tested the new beta. I was so hopeful!

**Comment by Tslat** [comment]
does this actually affect anything though? you basically just close the server after stopping it anyway?

**Comment by Diversion98** [comment]
It does affect things.

To keep running a server smoothly, automated server restarts needs to happen to clear the RAM. I need to manually kill the server to do a restart of it.

**Comment by Tslat** [comment]
Ah right

**Comment by Tslat** [comment]
Do you remember when this issue started? I.E. what version of AoA?

**Comment by Tslat** [comment]
Never mind, fixed it

**Comment by Diversion98** [comment]
oh what was the issue? :)
