### ISSUE TITLE
Spawners with ranged mobs do not spawn mobs on the air

### ISSUE THREAD

**Issue by vasiliscsc** [Tslat/Advent-Of-Ascension#2529]
**Mod Version**
3.4.8

**Short description**
Spawners with _RANGED_ AoA3 entities do not spawn entities on the air. 

**Long description**
This bug was first noticed with Mermages in an Aquatic Castle in L'Borean. I have constructed a farm as I do for all other entities but was receiving no spawns. I went on creative and change the entity in the spawner using spawn eggs and tried zombie - got spawns, tried amphibior - got spawns, put Mermage again, no spawns. After chatting in Discord with Silencer, he correctly identified that it appears that all entities I tried were melee and recommended I use something like a goblin - no spawns. The spawner with Mermages DID work on solid blocks.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a room, 9x9x9 without any light sources (block light level 0 everywhere).
2. Place a spawner in the dead center of that room.
3. Place a slab on top of the spawner to avoid spawns on it.
4. Put any ranged entity's spawn egg in the spawner (tested with Mermage and Goblin)
5. There are no spawns even though there should be. Can use a melee mob to see that they indeed spawn in this setup.

**Expected behavior**
Ranged entities should be able to spawn on the air from a spawner.

**Comment by Golden-Extreme** [comment]
It could also be a technical bug.
