### ISSUE TITLE
Overworld mobs spawning in AoA dimension

### ISSUE THREAD

**Issue by Sagirius** [Tslat/Advent-Of-Ascension#253]
Overworld mobs are spawning in AoA dimensions like Haven and Crystevia seems that other dimensions are fine though and Nether is fine too 
I'm using FTB Departed with Tslat 1.1.3
![2019-01-20_10 46 59](https://user-images.githubusercontent.com/35900657/51437624-12121c80-1ca1-11e9-87d8-fd46a5f3db9f.png)

**Comment by Tslat** [comment]
Fix your configs so that your biome IDs don't conflict
