### ISSUE TITLE
Smelting runes

### ISSUE THREAD

**Issue by jeskaiadept** [Tslat/Advent-Of-Ascension#2532]
Excessive amounts of rune blocks needed to create a portal drop from either mobs or skill farms so i thought that if these are made out of runium, maybe it would be possible to smelt it into runium chunks. This way acquiring materials for creation/runation would be easier to obtain and less items would take space in inventory or chests.

Instead of smelting, crafting a runium chunk from 4 different runes also might work, as long as it helps with the excess of rune blocks.

I just had this idea when i was running from my mob grinder into my chest room with all the drops to make space in grinderchests.
Also thought about my creation leveling progress being stuck.

No idea if this idea is well balanced or anything but i think it would help preserving value of rune blocks instead of them being "need only 1 of each and all copies can be just thrown into lava"

**Comment by Tslat** [comment]
Which version are you basing this on?
Drop rates were reduced heavily going into 1.16.5

**Comment by jeskaiadept** [comment]
basing on 1.15.2 but even if these were reduced, they are still gonna drop and be a slight nuisance after getting a portal going. just think about it as a "value keeping mechanic" so they won't become dead drops anyway :)

**Comment by Cruuk** [comment]
Of course you're gonna have several excessive carved runes when you kill thousands of Amphibiytes. Not only was the droprate lowered in 1.16.5, but Amphibiyte is a L'Borean mob now, it doesn't drop carved runes anymore. Overworld doesn't have non-vanilla spawner mobs anymore. Giving another use to Carved runes for when you have too many would be nice I guess

**Comment by jeskaiadept** [comment]
Ye, carved runes are not only mob drop but also lvl1 drops for some skills. If it would be only mob drop i wouldn't suggest that since drop rate get's lowered but because you can fill some of your inventory space with them while mining or fishing can also be quite unpleasant. The other part of this suggestion involving increased income of runium chunks can recompensate the fact that fortune doesn't work on runium ores while there is quite a few uses for it. Ofc. at some point even these may start being useless like everything else in lategame when you achieved most of things but still it would be a nice sideway of acquiring a rather necessary resource. Anyway it's just a suggestion, i just thought that it would be nice for the leveling process and for the value balance of both runes and runium chunks. 

Thanks for replies, stay safe!
Jeskai
