### ISSUE TITLE
tinker not compatible

### ISSUE THREAD

**Issue by detno** [Tslat/Advent-Of-Ascension#2536]
**Mod Version**
 beta 4

**Describe the bug**
tinkers smeltery is not compatible

**Expected behavior**
i read that aoa did support tinkers. and i couldnt find anything stating it no longer is or was removed. or hasnt been implemented in beta 4

**Comment by Tslat** [comment]
Tinkers isn't even released in 1.16, how would I be compatible?
It's an incomplete beta that only came out like a couple weeks ago

**Comment by detno** [comment]
Unless you dont consider their alpha. They have a 1.16.5  2 weeks ago

**Comment by Tslat** [comment]
It's not even finished lol, how would I be compatible?

**Comment by detno** [comment]
I'm not much of a coder I didn't know if you could port the code over or had to rebuilt the code from scratch or other things. my apologies.

**Comment by Tslat** [comment]
It'll likely be entirely different, both in code and content. Tinkers is completely changing

**Comment by detno** [comment]
ok should i use a different mod for ore doubling?
