### ISSUE TITLE
shyrelands bugged.

### ISSUE THREAD

**Issue by KJM11** [Tslat/Advent-Of-Ascension#2537]
**Mod Version**
What version of the mod are you on?
AoA3-3.5-1.16.5-Beta-4
**Describe the bug**
When you enter the shyrelands, there are only trees and no structures.
**To Reproduce**
Steps to reproduce the behaviour:
go to shyrelands

**Expected behavior**
If you enter the shyrelands, there must be a structure.

**Screenshots**
![image](https://user-images.githubusercontent.com/83417776/116634435-faa15e00-a996-11eb-99b5-2ddcaf4bc69c.png)

**Comment by EatingSilencer** [comment]
Not a bug, shyrelands isn't finished yet.
