### ISSUE TITLE
More Durability for armors and weapons

### ISSUE THREAD

**Issue by ZyrconAlpha** [Tslat/Advent-Of-Ascension#254]
In AoA armors and weapons are always used but they have not enought durability in my opinion because the price to repair them is very expensive and we had to repair armors and weapons because they are unique...
So, increase the durability or reduce the price to repair them because, for exemple if we farm mobs in one dimension for i don't know ... 30 minutes or 1 hour we had to repair everythings.... 
PS: I'm french sorry for my bad english ;) and i I did not know if that was a balance or a new feature, judged by your self.

**Comment by Sagisolar** [comment]
Rosite isn't really that expensive. Also Durability is a balance for the armor.

**Comment by ZyrconAlpha** [comment]
I used to use Magic Mending Compound to repair my armors and weapons because I think it's the better way to do that... You say rosite isn't really expensive but if you mine "opti" to increase foraging level at the same time, rosite is not very common. And the ingredients for the Magic Mending Compound are expensive if you had to use 5 Magic Mending Compounds every 2 hours.

**Comment by Armakeen** [comment]
Infusion gives you access to Unbreaking 3 and Unbreaking 4.
If you train Foraging level 85, you can get tons of Rosite extremely fast. Emberstone is the only thing you can't farm but it is still really easy to get.
We don't need more durability for armors.

**Comment by ZyrconAlpha** [comment]
Yes it's true but to have Blooming Infusion Stones you had to be level 80 in Infusion and it's really and game I think...

**Comment by Armakeen** [comment]
You can also get Unbreaking 3 really easyly with the new enchantment table system (MC 1.8+). You only spend 3 levels to get an enchant level 30 ^^

**Comment by ZyrconAlpha** [comment]
Yes for sure but I play in 1.7.10(the best one)
