### ISSUE TITLE
Mobs don't spawn anymore

### ISSUE THREAD

**Issue by Trikalabris** [Tslat/Advent-Of-Ascension#2540]
**Mod Version**
1.12

**Describe the bug**
In overworld there are zero hunter mobs spawning and only mobs from the mod that do spawn are very rare and give to xp to hunter lvl. It worked just fine before and it only began now.

**Expected behavior**
Moded mobs and hunter mobs spawning normally.

**Screenshots**

**Comment by Tslat** [comment]
probably a mod conflict or something.
