### ISSUE TITLE
Overpowered Dupe Glitch

### ISSUE THREAD

**Issue by ghost** [Tslat/Advent-Of-Ascension#2546]
**Mod Version**
What version of the mod are you on?

3.5 BETA

**Describe the bug**
Any vanilla crafting recipe with two items in all slots will result in a 1.5x multiplier on the crafting ingredients, and also give you the final product. The crafting ingredients may stack far about 64 and become tangible items (not just a visual bug). 

**To Reproduce**
Steps to reproduce the behaviour:
1. In survival, open the infusion table
2. Craft any ore block using ingots in a 3x3. The bug happens when each slot has at least two items in it.
3. Profit

**Expected behavior**
I don't believe you are allowed to craft things like this using an infusion table. 

**Screenshots**

**Comment by ghost** [comment]
Note: we discovered the bug with converting emberstone ingots into blocks, so I guess modded recipies work too.

**Comment by Tslat** [comment]
Unable to replicate

![image](https://user-images.githubusercontent.com/7098525/118539913-56d7f080-b793-11eb-8854-6c4185a1db29.png)

**Comment by Tslat** [comment]
Unable to replicate, no further comments made. Re-open if proof/methods found
