### ISSUE TITLE
Varsium should be an "upgrade" to Limonite (In the same way Opteryx Feathers are an upgrade to Feathers)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#255]
**Describe/name the existing feature this suggestion relates to**
Varsium ingots

**Describe the change or feature you think would be good to see**
You know how Opteryx feathers can be used to craft Holly arrows, and give more arrows than when using regular Feathers? I always thought it would be cool if Varsium ingots did that but for the other ammunition made with Limonite.

They're both a very similar color, and are the most easiest-to-find ore of their respective dimensions. I know those aren't exactly the best reasons but I just think it would be interesting.

Crafting bullets/grenades/slugs/cannonballs gives you 8 per set as of snapshot 10. Using Varsium ingots in their recipes instead of Limonite would give you **12 or 16** per set instead, similarly to how Opteryx feathers work.

The main issue I see with this are the "Limonite Bullets". It would be pretty weird to craft Limonite bullets with Varsium ingots. I don't really want a "Varsium Bullet" either, it'd be the same thing and we'd have to mention both bullets on every gun page.
~~"Limonite bullet" is just an odd name to me in general, I'd just change it to "Bullet" or "Metal Bullet" or something. You don't see cannonballs being called "Limonite Cannonballs".~~

Giving the dimension ingots more dynamic usage like this in general would be pretty cool. I'm not saying every ingot should get the same treatment Varsium does but you know what I mean...

**Include any additional background information**
It would probably be a good idea to have Holly arrows be an exception to this. It already has Opteryx feathers, just imagine that + Varsium ingots...

**Comment by Sagisolar** [comment]
Don't really agree with the last part but I will support this
