### ISSUE TITLE
Cutting out weapon bloat

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2550]
Just like mobs, you should know what the issue is by now if you're familiar with it at all. Now, personally I think players should have lots of option, I think it's what makes the mod fun, even if there are many niche options. But this mod pushes it too far with particular weapon types (GUNS), and it's a bit ridiculous.

This will inherently be opinionated, but I want to try and focus on ability-less, redundant items. Not only would it make it easier to work with the non-removed weapons and make it easy for wiki editors, it'd make space for more potential interesting weapons for future updates.

-----------------------------------------

--Swords--
**Amethyst sword and tools**: Amethyst are in this awkward middleground of being Diamond sidegrades but kind of not really, it's just really smushed in there. This is also based on that discussion of Amethyst being replaced with its vanilla counterpart if we port again.
**Emberstone sword OR Fireborne sword**: I get the dynamic, but do we really need the dynamic in the first place, it doesn't really contribute much but add more bloat. It doesn't really matter which one is removed, Candlefire would just become the upgrade for the non-removed one.
**Bloodfury OR Bloodstone sword**: Again, do we need this dynamic. Bloodfury is already different from other t2 swords purely by having different attack speed, does it need another Abyss sword. Personally I would cut Bloodstone sword because Bloodfury is cooler.

--Greatblades--
**Cotton crusher**: This is biased, but Candy blade is so much better and interesting, that even if Cotton candor was the best boss in the mod, I just don't see a strong case for it.
**Goofy greatblade**: Do we really need a random damage weapon when Lunar/Millennium gb already exist.

--Bows--
**Alacrity bow AND/OR Void bow**: I'm not sure if we really need 2 different bows that boil down to "vanilla bow but very slightly different".
**Deep bow**: Is this necessary with the existence of spectral arrows.
**Weaken bow**: Is this necessary with the existence of weakness arrows. I guess you could argue that for all potion effect weapons but at least do something interesting with them instead of a plain yellow bow.
**Poison bow OR Toxin bow**: Do we need 2 different poison bows of the same tier. I'd personally remove Poison bow because Toxin bow is at least different.
**Speed bow**: Feels smushed in there with how similar it is to Skeletal bow, kind of redundant with the other fast bow options out there.
**Slighshot**: This thing is a sinner. It's just Explosive bow, but to cause explosions you need to use this item specifically for it, and the explosion is extremely small anyway. Why is it still around?

--Crossbows--
**Viral/Coral crossbow**: Tipped arrows

HERE COMES THE FUN PARTS

--Guns--
**Tommy/Tiger Tommy**: Redundant with other 1.67 fire rate weapons.
**Discharge rifle/Apoco rifle**: If explosives can inherently be in any weapon type, why do we need this weird category of "discharge" weapons with their own out of the way ammo in the first place?
**Destruction rifle OR Baronator**: They feel kind of redundant with each other.
**Nethengeic/Precasian slugger OR Hot shot/Heat wave**: 2 different fire guns? Damn. At least Wart gun is interesting.
**Hunter's rifle**: Redundant.
**Krillinator AND/OR Vile Vanquisher**: There are THREE poison guns in t2. Germinator is a neat boss drop, but something's gotta be done about at least 1 of the crafted poison guns.
**Big Top**: Redundant.
**Crystal Carver**: Redundant.
**Iro rifle/Floro rifle**: Redundant.
**Construct/Hiver**: Redundant.
**Miasma**: Redundant with a slightly cooler (hehe) boss drop that does the same thing.
**Chair wrecker/Flame wrecker OR Mint Magnum/Aqua magnum**: Redundant in regards to 2.5 fire rate weapons.
**MK/MK fung**: Redundant with a boss drop in the same dimension.
**Abominator/Iominator**: Also redundant with a boss drop in the same dim.
**Squad gun/Spine gun**: Do we need this many 1.67 fire rate guns when you already have at least 1 in every tier.
**Artifact OR Skullifact**: Are the double upgrade guns really necessary? Could get rid of the powercrept version, or cut the middleman out and give players the the extra powerful version first.
**Roulette OR Skullete**: Same thing as other double upgraded weapons.
**Apoco assault rifle**: I don't know I just don't get this one with the existence of Roulette being an upgrade of the very first gun, making it take a lot of space for 0.83 fire rate guns if you know what I mean.
**Predigun**: Literally why? Megagun is already a thing

--Shotguns--
**Demolisher/Boulder**: Destruction/Purity shotgun have a very similar fire rate, and are just kind of better in every way. Like come on.
**Discharge shotgun**: We already have 2 explosive shotguns that use nice, normal ammo.

--Snipers--
**Bolt rifle**: Just always kind of felt redundant when we already have Deadlock.
**Baron SSR**: Just always felt really lame for a boss drop. Monster has no ability either but at least it has a t4 upgrade and just looks cooler.
**Dual sight**: Also kind of feels redundant.
**Floro500 OR Mark maker OR Moon maker**: Holy hell Ka500 has 3 different upgrades with their own balance dynamic. I think Ka500 is fine with just 1 upgrade.

--Cannons--
**Mecha cannon**: Redundant.
**Shadow blaster/Hive Blaster/Smile blaster**: Redundant.
**Bozo Blaster**: Uninteresting.
**Ghoul cannon**: Uninteresting.
**Ghast blaster/Predatorian blaster**: Feels redundant with Wither/Bulb cannon already being a thing.
**Shyre blaster**: Forgive me... Giga cannon is just better and more interesting.
**Discharge cannon/Ancient discharger: Grenade weapons already exist.

--Blasters--
**Poison Plunger OR Toxic terrorizer OR Eradicator**: 3 different poison blasters in the same tier. Wow
**Revolution**: Redundant with the other explosive blasters.
**Laser blaster OR Party popper**: Redundant.
**Doom bringer/Gold bringer**: Redundant with other explosive blasters and is also really really bad with how small the explosives are.
**Froster**: Kind of redundant?
**Illusion revolver**: Uninteresting.
**Soul Storm**: Redundant.
**Soul spark OR Light spark**: Does this thing need an upgrade?

--Staves--
No thanks I'm skipping these ones someone else can do that

--------------------------

Mauls, thrown weapons, and Vulcanes were skipped because I think they're fine.

**Comment by Tslat** [comment]
Alright so as you would expect, this is a VERY divisive topic, and there's no real clean way to handle it.
I'm not going to comment my thoughts or opinions on this one for the time being, since it tends to sway opinions too much.

However what I will say is that the 1.16.5 AoA release is the ONLY time this is viable. It's extremely unlikely a future opportunity would arise which would make this change possible for technical reasons, so if you think it's a thing that needs to happen, this needs to be discussed immediately with other members of the community.
It would probably also need to go to poll.

I'll leave it to you/the community to discuss if wanted

**Comment by Cruuk** [comment]
After a talk, I'm more obliged to mainly cut the double/triple/layered upgrade stuff compared to other weapons

**Comment by Golden-Extreme** [comment]
Will weapons (sticklers and sickles) obtained in Ancient cavern that were removed in the 1.16.5 version be removed to reduce bloating?

**Comment by Cruuk** [comment]
> 
> 
> Will weapons (sticklers and sickles) obtained in Ancient cavern that were removed in the 1.16.5 version be removed to reduce bloating?

There are no plans to remove them. I'm guessing they'll get moved to Nowhere or something. They're far from bloat anyway, they're interesting and good.
