### ISSUE TITLE
Imbuing is not working

### ISSUE THREAD

**Issue by theabsurdity** [Tslat/Advent-Of-Ascension#2552]
**Mod Version**
3.5-Beta-4

**Describe the bug**
The craft of all the enchanted books via the infusion table are not working in creative or survival mode.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try crafting any enchanted book in the infusion table.

**Expected behavior**
Enchanted books can be craft with the infusion table if the player have enought infusion level.

**Screenshots**
Sharpness I craft
![2021-05-21_10 37 33](https://user-images.githubusercontent.com/84022721/119139489-5f565280-ba43-11eb-852d-de43c9c70781.png)

Aqua affinity craft
![2021-05-19_02 06 00](https://user-images.githubusercontent.com/84022721/119139743-aa706580-ba43-11eb-9a18-a4f075cac798.png)

**Comment by EatingSilencer** [comment]
Books cannot be enchanted at an infusion table. JEI is misleading. You can only enchant gear.

**Comment by Tslat** [comment]
What silencer said

JEI uses books as a way to show that the imbuing imbues an enchantment onto the input item.
It can be a bit confusing
