### ISSUE TITLE
Elussive dissapears randomly 2 times and doesn't spawn one time at all

### ISSUE THREAD

**Issue by Piethenkens** [Tslat/Advent-Of-Ascension#2554]
Hi there I so far had the ellussive boss just despawn or something at 2 points the boss bar stays but the boss is just no where to be found in the area and one time he didnt spawn at all when I used the eye on the table it said its words that it says when it spawns but it didn't.

I am playing on the newest beta version for minecraft 1.16.5

**Comment by Tslat** [comment]
If the boss bar is still there, the boss is still there
The boss bar goes when the mob is despawned or killed.

He was probably high up in a tree or something
