### ISSUE TITLE
Minecolonies npc are attacked

### ISSUE THREAD

**Issue by dpeter99** [Tslat/Advent-Of-Ascension#2555]
**Mod Version**
AoA3-3.5-1.16.5-Beta-4.jar

**Describe the bug**
Overworld spawnd mob attack NPCs without provocation. 

**To Reproduce**
1. Run AoA with Minecolonies.
2. Open a simple flat world
3. Build a simple colony (Place town hall with build tool, than click on "create new colony")
4. Wait for a citizen to spawn in
5. The nearby AoA mobs will attack it

**Expected behavior**
AoA mobs should not attack NPCs as this makes it impossible to play with both mobs loaded.

**Comment by Tslat** [comment]
Raise this issue on the Minecolonies side too.
I don't understand what code on my side would be causing this

**Comment by ravenbuilder934** [comment]
This is intentional, hostile mobs are supposed to attack colonists. spawn rate can be tweaked on your side
