### ISSUE TITLE
Server config is overwritten on load

### ISSUE THREAD

**Issue by dpeter99** [Tslat/Advent-Of-Ascension#2556]
**Mod Version**
AoA3-3.5-1.16.5-Beta-4.jar

**Describe the bug**
When i tried to set:
``disableOverworldMobs = true``
it was reset to ``false`` after loading a world

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a world
2. Edit the serverconfig to disable mobspawns and save the file
3. Exit the world
4. join the world again
5. Open the text file again
At this point the text file will have a different order for the options and the set value bact at ``false``

**Expected behavior**
I exect the config file to stay the same, and keep the values I set.

**Comment by Tslat** [comment]
There's either a reload happening, or some other mod messing with you.
AoA lets forge's internal system handle its config saving, there's nothing I can do here
