### ISSUE TITLE
Server config disableOverworldMobs is not honored

### ISSUE THREAD

**Issue by dpeter99** [Tslat/Advent-Of-Ascension#2557]
**Mod Version**
AoA3-3.5-1.16.5-Beta-4.jar

**Describe the bug**
On a dedicated server the config ``disableOverworldMobs`` is not honred and mobs keep spawning.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a dedicated server
2. Set the config to disable the mobs
3. Be in the overworld
4. See the mobs spawing

**Expected behavior**
If the overworld spawning is disabled than no mobs should spawn in the overworld.

**Comment by Tslat** [comment]
I'm removing this config option anyway. Forge intentionally made changes after 1.12 that means this config entry doesn't even get updated until after spawns are done - thanks Forge!

Regardless, the mod isn't like it was back when this was added, so I don't believe this config option is needed anymore

**Comment by dpeter99** [comment]
The config option was needed for us, becuase of #2555. As this would allow our colony to survive, and the mobs spawn everywhere, and we don't know of any way to keep them from spawning inside the colony itself.

**Comment by Tslat** [comment]
Then take this up with MineColonies, it's intended 
https://github.com/Tslat/Advent-Of-Ascension/issues/2555#issuecomment-846283473

Additionally, AoA mobs have the same spawn rules as other mobs. Use torches and lamps or other sources of light if you don't want mobs spawning, like you would do for any hostile mob

**Comment by dpeter99** [comment]
> Use torches and lamps or other sources of light if you don't want mobs spawning, like you would do for any hostile mob

I tired this. but there are mobs that do spawn in daylight. For example a "Goalby" just killed a citizen, in full daylight.
But I also found Chargers during the day.
Also Goblins, Cyclopses.

**Comment by Tslat** [comment]
Daylight mobs are still affected by block light sources like torches :)
