### ISSUE TITLE
Dimensions for my new bosses

### ISSUE THREAD

**Issue by cosmicchip** [Tslat/Advent-Of-Ascension#2559]
So I’m the one that came up with the bosses about like 4 months ago. Remember I made that issue?

Update 1

Pharaoh Golem- Pyramaledia: An Egyptian dimension

Nightmare Catcher- The Fearlands: A nightmare dimension with dark phobias/fears

Effection- Electopia: A energy dimension with electricity

Alphabet Mage- Educatio: A school-themed dimension

Update 2

Flamethrow- Middle Agelands: A medieval-themed dimension

Update 3

Snowreck- Frozania: A snow/ice dimension

Ballboom- Gamelane: A sports/game dimension

Chef Pizzapye- Munchotha: A food-themed dimension

Update 4

Queen Healirous- Hospitalia: A hospital dimension

Update 5

Animatronic Six- Animatronic Land: An animatronic-themed dimension

Captain Piratebeard- Treasurio: A pirate-themed dimension

Mr. Jazz- Soundtrackia: A music dimension

Update 6

Charge- Overworld

King Oozalut- Overworld

Chop and Shot- Mysterium

Cactiworm- Pyramaledia

Brain-Brute- Vox Ponds

Monkey’s Music- Soundtrackia

Lavaroust- The Nether

Dr. Quetila- Iromine

**Comment by Cruuk** [comment]
I will be frank, AoA is trying to be something more than adding simplistic-themed dimensions purely for the sake of it. We're not randomly adding in dimensions anymore to make a number go up unless all the other 20+ dimensions are finally good. I would advise using these ideas for something else, they just can't really fit in with modern AoA.

**Comment by cosmicchip** [comment]
Well the old dev Xolova planned on lots of new dimensions so.

**Comment by XxDuckyUxX** [comment]
> Well the old dev Xolova planned on lots of new dimensions so.

And Tslat isn't Xolova. Rather than focusing on adding new, poorly coded, and buggy as all hell dimensions and features, Tslat is working on a better AoA as a whole and trying to help bring current features up to par like skills, bosses, and even the current dimensions. Don't expect anything new and if there was, it won't come from some random guy off the internet :)

**Comment by Cruuk** [comment]
> 
> 
> Well the old dev Xolova planned on lots of new dimensions so.

Most of those dimensions either have scattered, unused leftover assets or have absolutely nothing to them. The latter ones are referred to as name-drops. And I will emphasize, nothing was made for them at all, all they are are random names, and it is easy to generate hype by simply making up a bunch of names.

And even for the ones that do have assets, pretty much none of it has code. It is simply a better move to make new assets and improve on existing dimensions than use outdated, possibly-stolen assets for what amounts to false promises.

**Comment by cosmicchip** [comment]
Well ya know I’m saving this for my cartoon.
