### ISSUE TITLE
Caller the Hunter skill Hunting

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#256]
A skill being called "Hunter" doesn't make sense. It should be called "Hunting".

**Comment by Tslat** [comment]
Should Anima be called Animaing? or Animing?
What about Vulcanism, should it be Vulcanisming?
Infusioning?
Augurying?

**Comment by ZyrconAlpha** [comment]
Hunter is very good, don't change or change evrything ....

**Comment by Tslat** [comment]
This suggesting is closing
