### ISSUE TITLE
New Tier 4 dimension: Galaxia

### ISSUE THREAD

**Issue by Golden-Extreme** [Tslat/Advent-Of-Ascension#2567]
**Describe the new feature you think would be good to add**
### **Generation**
Galaxia generation is built on large floating islands in light blue and sky blue, with stars visible in a cosmic background.
When entering a void like Lunalus, it teleports to Y = 200 and returns to the lower dimension.
Prerequisite dimension is Lunalus.
To get the Galaxia realm stone, It can be obtained by Crafting 1 Lunar Ingots and 1 Floating Stone and 1 Hardened Confetti Ball and 1 Zhinx Dust and 1 blank realm stone.

### **Generated blocks:**
**Galaxy Grass**
**Galaxy Stone**
**Galaxium ore**
**Meteorium ore**
**Galaxia Leave**
**Galaxia Log**
Galaxium ore and Meteorium ore is It is generated with a y=30-87 and a pickaxe of Tier 3 or higher is required to mine.

### **Asethetic blocks:**
**Wood:**
Galaxia Plank
**Stone:**
Meteor Stone
Cracked Meteor Stone
**Bricks**
Galaxiy Stone Brick
Meteor Stone Brick
**Glass:**
Galaxy Glass
**Lamps**
Galaxium Lamp
Meteorium Lamp
**Ore Blocks**
Block of Galaxium
Block of Meteorium

### **Structure:**
**Half Meteor Structure:**
Half Meteor Structure are the lotto structures of Galaxia and mainly composed of Meteor Stone. They generate in mid-air, and Spawn Galaxia Lotto man.

**Meteor Cave:**
Meteor Cave are With a Single Meteor Luncher Snail Spawner in the center.

**Galaxy tower**
Galaxy tower are Massive tower home to 6 hunter mobs in Galaxia.
Galaxy Troll spawn on the first floor, Galaxy Chomper on the second floor, Alien Hunter and Rashix on the third floor, Galaxy Reaper on the 4th floor and Vol Turtle on the 5th floor.
There is a low chance that you will get a Starry Shotgun in the Large Chest on the 5th floor.

**Faceless base:**
Faceless base are With a Single Faceless Beamer Spawner in the center.

**Galactic Platform:**
Galactic Platform has a Meteor creation table in the center for creating boss summon items.

**Arc Cometter Platform**
These Structure contain Arc Cometter Altars in the middle. By using a Comet Orb on one of the altars, players can confront the boss Arc Cometter.

### **Items**
**Mining:**
**Galaxium**
The Galaxium can be obtained by mining with a Tier 3 or higher pickaxe.

**Meteorium Ingot**
Meteorium Ingot can be obtained by smelting.

**Mob Drops:**
**Meteor Stone**

**Galaxia Token**
Meteor Stone and Galaxia Token can be obtained as a drop from any hostile mob and boss in Galaxia, via the Galaxia Table.

**Galaxy Upgrade Kit**
Galaxy Upgrade kit can be obtained as a 1% chance drop from any hostile mob and boss in Galaxia, via the Galaxia Table.

**Other:**
**Comet Orb**
Using a Meteor Stone on a Meteor creation table will convert it into an Comet Orb.

### **Weapons**
**Create from Craft:**
**[Meteorium Sword]**(Sword)
Meteorium Sword is Durability is 2750 and Against mobs 19damage.
Meteorium Sword is obtained by crafting with 2 Meteorium Ingot and 1 limonite Rod.

**[Galaxy Slasher]**(Sword)
Galaxy Slasher is Durability is 2680 and Against mobs 20damage
and a mob will be levitated with a 10% chance on hit.
Galaxy Slasher is obtained by crafting with 2 Galaxium Ingot 2 Meteor Stone and 1 limonite Rod.

**[Galaxy Bow]**
Galaxy Bow is Durability is 1590 and Average Damage is 24.
Inflicts 7.5 additional damage on flying mobs.
Galaxy Slasher is obtained by crafting with 2 Galaxium Ingot 2 Meteor Stone and 1 limonite Rod.

**Create from Infusing:**
**[Meteonic Crossbow]**
Meteonic Crossbow is Durability is 1590 and Average Damage is 24.
and arrows fired by this bow explode on on contact with mobs.
Meteonic Crossbow is obtained by Infusing with 3 Meteor Stone 2 Enchanted Gunpowder and 1 Crossbow frame.

**[Meteonic Gun]**
Meteonic Gun is Durability is 1430 and Average Damage is 27.5.
Attacking a mob with a gun will explode the mob with an armor value. This explosion does not damage the user.
Meteonic Gun is obtained by Infusing with 2 Meteorium Ingot 3 Enchanted Gunpowder 1 Galaxium and 1 Gun frame.

**Mob Drops:**
**[Meteor Cannon]**
Meteor Cannon is Durability is 850 and Average Damage is 26.
Consume Meteor Stone at launch.
Meteor Cannon is can be obtained as a drop from Meteor Luncher Snail.

**[Star Sniper]**
Star Sniper is Durability is 530 and Damage is 53.7.
Bullet fired by this Sniper rifle will apply glowing to enemies on hit.
Star Sniper is can be obtained as a drop from Faceless Beamer.

**[Galaxy Gigant Blade]**
Galaxy Gigant Blade is Durability is 1990 and Damage is 28.3.
If user has a debuff, it deals 7 additional damage.
Galaxy Gigant Blade is can be obtained as a drop from Arc Cometter.

**[Rashixy Sword]**
Rashixy Sword is Durability is 2450 and Against mobs 16damage.
If there is a galaxium on hit, consume one galaxium to give the mob a weaken II.
Rashixy Sword is can be obtained as a drop from Rashix.

**[Star Staff]**
When used like Cryston Staff, the player will have an attack power increase effect for a certain period of time.
The runes consumed by Star Staff are 4 power runes and 4 life runes.
Star Staff is can be obtained as a drop from Galaxy Reaper.

**[Vols Blaster]**
Vols Blaster is Durability is 3900 and Average Damage is 20.
When hit, there is a 10% chance of dealing a large amount of explosion damage.
This explosion does not damage the user.
Vols Blaster is can be obtained as a drop from Vol Turtle.

**Obtained as a structure**
**[Starry Shotgun]**
Starry Shotgun is Durability is 1000 and Damage is 5.5x5.
Bullet fired by this Shotgun will apply glowing to enemies on hit.
A Starry Shotgun can be found in chests that spawn in Galaxy tower.

**[Upgrade from Divine station]:**
Upgrade with Galaxy Upgrade Kit:
**[Galaxy Slingshot]**
Galaxy Slingshot is Durability is 1400 and Damage is 24.
Galaxy Slingshot can be create Slingshot+Galaxy Upgrade kit.

**[Galaxy Ioner]**
Galaxy Ioner is Durability is 1010 and Damage is 12.3.
Galaxy Ioner can be create Ion Revolver+Galaxy Upgrade kit.

**[Comet Shiner]**
Comet Shiner is Durability is 1920 and Damage is 6.7.
Comet Shiner can be create Moon Shiner+Galaxy Upgrade kit.

**[Comet-O-Tron]**
Comet-O-Tron is Durability is 2570 and Damage is 4.
Comet-O-Tron can be create  Swarm-O-Tron+Galaxy Upgrade kit.

Upgrade from other Upgrade Kit:
**[Fangal Meteor]**
Fangal Meteor is Durability is 865 and Average Damage is 31.
Fangal Meteor can be create Meteor Cannon+Runic Upgrade kit.

**[Heat Starry]**
Heat Starry is Durability is 1200 and Damage is 8.5x5.
Heat Starry can be create Starry Shotgun+Nether Upgrade kit.

**Armors:**
Mob Drops:
**[Galaxy Armor]**
**Helmet:**durability is 760. Armor Value is 5.
**Chestplate:**durability is 760. Armor Value is 8.
**Leggings:**durability is 760. Armor Value is 6.
**Boots:**durability is 760. Armor Value is 5.
Tortal Armor Value is 24.
Full Set Bonus:If you fall into a void, it will be teleported to y = 257.

But, each teleport reduces the durability of Galaxy armor by 1 point.

**Mobs:**
Spawns naturally Mobs:

**[Meteor Creature]**
Meteor creature are the same size as Bush Baby and attack at high speed.

**[Radiator]**
Radiators are long enemies like Rory Popper and Sunny, and like Distorter, they have the ability to draw players towards you.
Fires the player when it hits this enemy.

**[Metropolis]**
This enemy is a rare spawning mob.
Knock back the player 4.5 blocks on hit.

**[Galaxia Spider]**
Galaxia Spider can climb blocks like a spider.

**[Flying sphere]**
A flying enemy like a small meteorite.

Spawner Mobs:

**[Meteor Luncher Snail]**
Fires a projectile that explodes with an enemy like a snail.
Spawn from a spawner with Meteor Cave.

**[Faceless Beamer]**
It looks like the body of a faceless floater is horizontally long.
Fire a sky blue projectile.
Spawn from a spawner with Faceless base.

Hunter Mobs:
**[Galaxy Troll]**
Fires a projectile like a goblin.
Galaxy Troll are can defeat if Hunter level is 88. You can get XP 2650.6 by defeating it.
Spawn from a spawner with 1st floor of Galaxy Tower.

**[Galaxy Chomper]**
Galaxy Chomper is a purple, red-eyed Chomper-like enemy.
Galaxy Chomper are can defeat if Hunter level is 89. You can get XP 2780.4 by defeating it.
Spawn from a spawner with 2nd floor of Galaxy Tower.

**[Rashix]**
Rashix ushes with enemies like reindeer.
Gives the player a weakening effect on hit.
Rashix are can defeat if Hunter level is 93. You can get XP 2960.1 by defeating it.
Spawn from a spawner with 3rd floor of Galaxy Tower.

**[Alien Hunter]**
Alien hunter are alien-like enemies with swords.
Alien hunter are can defeat if Hunter level is 94. You can get XP 3021.4 by defeating it.
Spawn from a spawner with 3rd floor of Galaxy Tower.

**[Galaxy Reaper]**
Galaxy Reaper is an enemy like the Web Reaper who wears a cloak on his back.
He shoots magic like a goblin and gives the player a nausea effect on hit.
Galaxy Reaper are can defeat if Hunter level is 96. You can get XP 4124.9 by defeating it.
Spawn from a spawner with 4rd floor of Galaxy Tower.

**[Vol Turtle]**
Vols are enemies of the shell with a starry sky pattern like a giant tortoise.
Fires a small green explosive when the player is nearby.
Vol Turtle are can defeat if Hunter level is 99. You can get XP 5964.4 by defeating it.
Spawn from a spawner with 5th floor of Galaxy Tower.

**Boss:**
**[Arc Cometter:]**
Arc Cometter is a giant scorpion like boss. (Also known as a **galaxy arthropod**)
Arc Cometter can be spawned by using an Comet Orb on a Meteor creation table.
Arc Cometter makes melee and shooting attacks.
For melee attacks, 16.5 damage deals Slowness II to the player for 3 seconds.
In the case of a shooting attack, 3-20 random damage will give the player 10 seconds of nausea and 3 seconds of Poison III effect.
Defeating Arc Cometter will drop the following items:

 - Strike Rune
 - Poison Rune
 - Lunar Rune
 - Galaxia Token
 - Galaxium Ingot
 - Silver/Gold Coins
 - Meteor Stone
 - Amethyst
 - Chitin
 - Sharp Claw
 - Magic Repair Dust
 - Galaxy Gigant Blade
 - Galaxy Helmet
 - Galaxy Chestplate
 - Galaxy Leggings
 - Galaxy Boots
 
 Arc Cometter is about the size of a Crystocore.

**Comment by vrextachropthus** [comment]
this is a good  idea

**Comment by ddship12** [comment]
l love it!

**Comment by qewrwer23qf** [comment]
good idea!

**Comment by Golden-Extreme** [comment]
It seems that it can be added in the official release of 1.16.5.

**Comment by ddship12** [comment]
Hi guys. I did not see Galaxia in 1.16.5. When will you add it?

**Comment by Cruuk** [comment]
Dimension suggestions tend to not get added in.

I would also advise making dimension suggestions for more original concepts, not something that can fit in already existing dimensions. That lowers the chance even further.
