### ISSUE TITLE
Wind Rune Shrines don't exist; unsure if intended

### ISSUE THREAD

**Issue by Not-February** [Tslat/Advent-Of-Ascension#2570]
**Describe/name the existing feature this suggestion relates to**
Firstly I apologize if this is better considered as a bug report; I couldn't figure out which kind of template seemed most fitting for my query.

Documentation both in-game on version ``AoA3-3.5-1.16.5-Beta-4`` and on the wiki indicates that a wind shrine is necessary to begin leveling the Runation skill and making runes; however, the structure is nowhere to be found either in-game or in the source code(on Github)'s structure files, despite other elemental shrine structures being present in dimensions other than the Overworld.

Currently from what I can glean the only way to obtain a rune shrine block is from a spellbinder dimensional villager's home. Is that intended to be the new progression starting point for the creation of runes, or just an optional extra way to get more shrines? Is this entire point of confusion simply a documentation/beta change mismatch?

**Comment by Tslat** [comment]
Just sounds like you're having bad luck to me.

Also the other rune shrines in 3.5 have their shrine on them.

**Comment by Not-February** [comment]
Oh! The other shrines having runes on them would pretty much mitigate that. Thanks for the quick response.
