### ISSUE TITLE
Make rune shrine structures be considered structures and not features

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2574]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Rune Shrine structure 
**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
I find it weird that the rune shrine structures are considered features in the 3.5 beta and not structures. Yes I know vanilla likes to call some of its structures "features" (e.g.: dungeon) (right?) but imo vanilla is wrong to do so, at least for non ambient structures like dungeons. 

Features should be reserved for nonfunctional structures such as desert wells. Rune shrines are functional structures and thus I believe they should be treated as a structure, not as a feature.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
Not that I know of
**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Not that I know of

**Comment by Tslat** [comment]
Structures aren't strictly functional either though?
Why does something have to be a structure if functional?

**Comment by EatingSilencer** [comment]
I was mainly intending this to create a separation between when to make something a structure and a when to make something a feature.

I also was intending to make rune shrines a structure, because let's be frank, when people look at a rune shrine, they are going to call it a structure, not a feature. I can imagine some people would find it pretty silly and ridiculous to have rune shrines singled out for no apparent reason.

**Comment by Tslat** [comment]
lol fair enough
Anyway your system isn't going to work - there's going to end up being plenty of structures that should be features, and vice-versa. This is because the two systems work differently and I may not be able to do one in the system it should for technical reasons.

**Comment by EatingSilencer** [comment]
That's fine, I was mainly providing a possible solution to make rune shrines structures.
