### ISSUE TITLE
Updated XP Drops

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#258]
**Describe/name the existing feature this suggestion relates to**
This is related to all of the mobs in advent of ascension having updated experience drops like more orbs or less orbs, maybe some mobs that drop even bigger orbs or smaller orbs.

**Describe the change or feature you think would be good to see**
Have most of the mobs drop certain amounts of experience.

**Include any additional background information**
This will make some of the mobs in Advent of Ascension with more health or less health more or less rewarding.

**Comment by Tslat** [comment]
Done in 3.0
