### ISSUE TITLE
Increase coin drop rates across all world tables

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2580]
With tokens this wasn't a huge problem due to how frequent they were, but now that *way* more trades require copper coins, getting them from mob drops will be awful. There are various good ways to get coins, but they're not obvious and the most obvious way of getting them is extremely pitiful. I understand that getting them via mob drops should be slightly worse than the others, but not by this much at all. It should not take literal hundreds of mob kills to get 1 stack of Copper, especially when the other methods are better in every way, and especially since you'll need plenty for the lotto items. The drop rates should be similar to what the tokens were.

**Comment by Tslat** [comment]
Hmm... guess I should have included the globally increased drop rate of coins in the changelog
