### ISSUE TITLE
Bestiary and Guides tabs visual glitch

### ISSUE THREAD

**Issue by SgtDrobo** [Tslat/Advent-Of-Ascension#2582]
**Mod Version**
What version of the mod are you on?
AoA3 3.5-Beta-5 (1.16.5)

**Describe the bug**
The Bestiary and Guides tabs are visually bugged; the menu is mostly missing except for a small bottom left portion

**To Reproduce**
Steps to reproduce the behaviour:
1. Mac OS (that's pretty much all I know)

**Expected behavior**
I expected the screen not to be glitched and for the guides and bestiary to be visible and readable.

**Screenshots**
<img width="1280" alt="Screen Shot 2021-05-31 at 8 19 20 PM" src="https://user-images.githubusercontent.com/85146556/120262776-3c038280-c24f-11eb-8c50-98daa8fc971d.png">
<img width="1280" alt="Screen Shot 2021-05-31 at 8 19 24 PM" src="https://user-images.githubusercontent.com/85146556/120262789-40c83680-c24f-11eb-9833-0d9b41f34148.png">
<img width="1280" alt="Screen Shot 2021-05-31 at 8 19 27 PM" src="https://user-images.githubusercontent.com/85146556/120262792-4291fa00-c24f-11eb-8fb5-dd8d6a9187a3.png">
<img width="1280" alt="Screen Shot 2021-05-31 at 8 19 28 PM" src="https://user-images.githubusercontent.com/85146556/120262799-44f45400-c24f-11eb-8a60-3f5e35c37d7c.png">
[debug.log](https://github.com/Tslat/Advent-Of-Ascension/files/6573155/debug.log)
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/6573156/latest.log)

**Comment by Tslat** [comment]
Try this again with the next release, if it still happens, let me know
