### ISSUE TITLE
NPCs make villager sounds

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#2588]
**Mod Version**
3.5 beta 5

**Describe the bug**
AoA NPCs now make villager sounds, which seems out of place as many them don't resemble villagers (or each other) at all. The expected behavior is for them to make their own sounds or have generic player/entity hurt sounds like in previous versions.

**To Reproduce**
Spawn an NPC such as an Undead Herald.

**Comment by aAndrew3030** [comment]
I am having the same issue, it seems that all traders are transformed into villagers 
They are also sleeping in my bed and doing typical villager stuff
