### ISSUE TITLE
Some blocks are in the wrong spot in the creative inventory

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2600]
**Mod Version**
What version of the mod are you on?
3.5-Beta-5

**Describe the bug**
The following blocks are in the wrong places alphabetically in the creative inventory:
1. Black Mysterium Bricks
2. Green Mysterium Bricks
3. White Shyre Bricks
4. Yellow Shyre Bricks

**To Reproduce**
Steps to reproduce the behaviour:
1. Check the the above items in the creative inventory to see if they are in alphabetical order.
2. See error

**Expected behavior**
The above items are in alphabetical order.

**Screenshots**
(You can see in the JEI the order that they should be in).
![image](https://user-images.githubusercontent.com/44556728/120887246-b4f03a80-c5bf-11eb-8e67-e58312ac3742.png)

**Comment by Tslat** [comment]
Kind of, not really

**Comment by EatingSilencer** [comment]
What do you mean?

**Comment by Tslat** [comment]
I try to keep grouped blocks together since they're part of a group. Both the mysterium bricks are together and alphabetically sorted as 'M' for Mysterium.

Same for Shyre bricks (S)

**Comment by EatingSilencer** [comment]
In that case, then the walls, stairs, and slabs need their alphabetization changed, as Black Mysterium Brick Wall is sorted with the 'B', etc.
