### ISSUE TITLE
Hive King can be sent through a portal during his spawning animation, causing his health to stop growing prematurely

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2601]
**Mod Version**
What version of the mod are you on?
3.5-Beta-5

**Describe the bug**
You can send Hive King through a portal during his spawning animation. When he arrives on the other side, he will not be at full health and will be frozen - unable to move (he can still spawn minions but is otherwise helpless).
**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn Hive King through the Hive Spawner. Make sure a portal block is placed next to the Hive Spawner like in the picture below.
2. Let Hive King go through the portal.
3. Enter the portal yourself.

**Expected behavior**
Hive King has full health/is not frozen when you enter the other side of the portal.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/120890039-5a120f80-c5ce-11eb-96d5-21e6f20f9c3a.png)

**Comment by Tslat** [comment]
Really...
