### ISSUE TITLE
Bring back Jumbo's old living sound (Or at least have something similar)

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#261]
In my opinion, it was more effective and actually builder up atmosphere. The new one makes it boring and you barely notice it. It currently sounds like he ate to much Mcdonald's **Big Macs**.

This what he used to sound like.
https://discordapp.com/channels/434160774546456590/434160774546456594/537777056055033856

~~grilled cheese is overrated~~

**Comment by Sonicwave** [comment]
I still think it should be slightly shorter than the old sound, since the sound often stacked on top of itself even with just 1 Jumbo around.

**Comment by DiamondWalker** [comment]
> 
> 
> I still think it should be slightly shorter than the old sound, since the sound often stacked on top of itself even with only 1 Jumbo around.

Can't the code be modified so it doesn't play the sound so often? Or maybe it could use the same setup as boss music.
