### ISSUE TITLE
Sea Spider climbing crash

### ISSUE THREAD

**Issue by fixer117** [Tslat/Advent-Of-Ascension#262]
**Mod Version**
aoa3-SNAPSHOT-10
**Describe the bug**
at net.tslat.aoa3.entity.mobs.misc.EntitySeaSpider.isBesideClimbableBlock(EntitySeaSpider.java:132)
**To Reproduce**
Steps to reproduce the behaviour:
Spawn/Find SeaSpider
It attempts to climb
Profit ???

**Expected behavior**
The spider should climb
**Screenshots**
N/A
[crash-2019-01-23_21.17.04-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/2789964/crash-2019-01-23_21.17.04-client.txt)

**Comment by Tslat** [comment]
Has been fixed
