### ISSUE TITLE
[1.16.5] Crash on new version

### ISSUE THREAD

**Issue by bigenergy** [Tslat/Advent-Of-Ascension#2621]
**Mod Version**
AoA3-3.5.1-1.16.5

**Describe the bug**
Client & Server crash on startup

**To Reproduce**
Steps to reproduce the behaviour:
1. Update AoA to 3.5.1
2. Install ars nouveau and geckolib
3. start server or client
4. get crash https://pastebin.com/xGPuLEz4

**Expected behavior**
Once I have updated Aoa to a new version, I cannot enter the game
If you roll back to the previous version, everything works

**Comment by Sajeyson** [comment]
Same. I tried to load without Ars Nouveau and still get crash.

**Comment by PresquePlayed** [comment]
It seems geckolib on its own already causes the crash, I experience the same thing

**Comment by Diversion98** [comment]
same thing happening over here, u only need AOA3 3.5.1 and GeckoLib
Ars nouveau is not needed.
Tried both Geckolib 3.0.38 and 3.0.39.

AOA3 3.5.0 works just fine.
if you delete geckolib or aoa3, it works fine as well

debug:
[debug.log](https://github.com/Tslat/Advent-Of-Ascension/files/6610680/debug.log)

crash:
[crash-2021-06-07_18.37.44-fml.txt](https://github.com/Tslat/Advent-Of-Ascension/files/6610682/crash-2021-06-07_18.37.44-fml.txt)

**Comment by DKLYNTLY** [comment]
i am also crashing on 3.5.1 and i dont undesratnd ur directions

**Comment by DKLYNTLY** [comment]
[crash-2021-06-07_15.57.38-fml.txt](https://github.com/Tslat/Advent-Of-Ascension/files/6611771/crash-2021-06-07_15.57.38-fml.txt)

**Comment by Diversion98** [comment]
> i am also crashing on 3.5.1 and i dont undesratnd ur directions

Downgrade to 3.5.0 for now till he fixes the bug :)

**Comment by Tslat** [comment]
It's actually an issue on Geckolib's end.
I'm waiting for Geckolib to resolve before I can fix it on my side

**Comment by Diversion98** [comment]
Oh how? I didnt update geckolib or anything.
Is it conflicting with your new code?

Sorry, interested in the technical side of things :)

**Comment by ghost** [comment]
> It's actually an issue on Geckolib's end.
> I'm waiting for Geckolib to resolve before I can fix it on my side

https://github.com/bernie-g/geckolib/issues/142#issuecomment-856393149

**Comment by AzureDoom** [comment]
> Oh how? I didnt update geckolib or anything.
> Is it conflicting with your new code?
> 
> Sorry, interested in the technical side of things :)

This is due to AoA updating it's shaded version of Geckolib (it ships with a copy so standalone users won't have to install the library). Newer versions ship with Networking code that fixed Item syncing on servers, which conflicts when shaded. I should have temp fix out soon for @Tslat to implement that should remove this conflict.

**Comment by AzureDoom** [comment]
A fix for this has been found https://github.com/bernie-g/geckolib/blob/1.16/src/main/java/software/bernie/geckolib3/GeckoLib.java#L25-L34 so this should be fixed Soon:tm:
