### ISSUE TITLE
Changing the restock message for AoA NPCs to be accurate to how it really works

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2626]
**Describe/name the existing feature this suggestion relates to**
The text you get when you hover over the X in a trade.

**Describe the change or feature you think would be good to see**
I don't know if this is possible at all, but if it is, it'd be a nice QoL change.

When you hover over this, it shows the same text as a vanilla trade.
![image](https://user-images.githubusercontent.com/38159897/121104333-afa91080-c7b6-11eb-8f46-0f0ca4a0a110.png)

But this isn't accurate to how it works for AoA NPCs, it works on a timer instead of the time of day. So changing the text to be more accurate would be nice for newer players.

**Comment by Tslat** [comment]
It's still accurate
