### ISSUE TITLE
FIY Potato Cannon

### ISSUE THREAD

**Issue by HyDefier** [Tslat/Advent-Of-Ascension#2628]
**Potato Cannon**
_Farm-It-Yourself._

_Motivation_
Jeb has stated that the poisonous potato must remain useless, and maybe that will remain the case in vanilla, this is AoA.

_Obtaining_
The Potato Cannon would have an extremely low chance of dropping when fully grown potatoes are farmed in the overworld (0.01% 1/5th as likely as Gardeners are for any Crop) Upon obtaining the player would get the **Not so Useless** achievement. 

_Usage_
The Potato Cannon would work "completely logically". It's an AoA cannon that fires poisonous potatoes (which inflict 1 second of poison), does 12 damage, has a 1 second unholster time, has a fire rate of 3/second, and a base recoil of 1. Since it burns through poisonous potatoes so fast, only the most pious potato farmers will be able to feed it's ravenous fire rate. The by-product of _regular_ potatoes could be used to eat or burn into xp or both... I guess.

_Appearance and Sounds_
It would look like a large potato launcher

There is no alternative (unless there is) maybe the cannon also feeds players when they are hit..

There are no similar previous suggestions (unless there are).

I'll keep an eye on the comments. Feel free to help develop the idea...

**Comment by Tslat** [comment]
AoA already makes use of the poisonous potato, FYI

**Comment by HyDefier** [comment]
> AoA already makes use of the poisonous potato, FYI

FYI haha

True, it appears to only be in some infusion recipes as far as I can tell (should there be wiki pages for how vanilla things are used?). The potato cannon would be a more focused on their use(to a cultish extent) and generally a more niche weapon to surprise fellow players in multiplayer.

**Comment by Cruuk** [comment]
> 
> 
> > AoA already makes use of the poisonous potato, FYI
> 
> FYI haha
> 
> True, it appears to only be in some infusion recipes as far as I can tell (should there be wiki pages for how vanilla things are used?). The potato cannon would be a more focused on their use(to a cultish extent) and generally a more niche weapon to surprise fellow players in multiplayer.

No, you give them to Store keeper for Copper coins.
![image](https://user-images.githubusercontent.com/38159897/121256229-2ef31e80-c861-11eb-8614-cca11492fc2b.png)

**Comment by HyDefier** [comment]
> > > AoA already makes use of the poisonous potato, FYI
> > 
> > 
> > FYI haha
> > True, it appears to only be in some infusion recipes as far as I can tell (should there be wiki pages for how vanilla things are used?). The potato cannon would be a more focused on their use(to a cultish extent) and generally a more niche weapon to surprise fellow players in multiplayer.
> 
> No, you give them to Store keeper for Copper coins.
> ![image](https://user-images.githubusercontent.com/38159897/121256229-2ef31e80-c861-11eb-8614-cca11492fc2b.png)

Good to know. Thanks! It would just be another use.
