### ISSUE TITLE
Heart Fruit Not Dropping Seeds

### ISSUE THREAD

**Issue by HyDefier** [Tslat/Advent-Of-Ascension#2630]
**Mod Version**
Latest (AoA3 3.5.1)

**Describe the bug**
When a mature Heart Fruit Plant is Broken in the Overworld, it does not drop any seeds.

**To Reproduce**
Steps to reproduce the behaviour:
1. Break a fully grown Heart Fruit
2. Observe lack of seeds

**Expected behavior**
From Wiki: "Harvesting a fully grown Heart Fruit crop will yield 1 to 2 seeds."

**Comment by Cruuk** [comment]
You should be able to craft the Heart fruit into more seeds. The wiki is outdated
