### ISSUE TITLE
Kror Altar isn't spawning Kror

### ISSUE THREAD

**Issue by odw500** [Tslat/Advent-Of-Ascension#2636]
(Using version 3.5.2)

I am attempting to battle Kror on my survival world, but when I use the Boulder Dash on the altar in his cave, with the charging table placed on top, it consumes the Boulder Dash but my energy doesn't get drained; neither does the corresponding chat message appear. My difficulty is not on peaceful.

**Comment by Tslat** [comment]
You're the second person I've seen suddenly have issues with threaded tasks, and I've been entirely unable to replicate it

What CPU do you have

**Comment by odw500** [comment]
Intel Core i5-6500, 3.2 GHz, 4 cores
If memory serves I was able to spawn Kror as intended in one of the beta versions of 3.5

**Comment by odw500** [comment]
I've tested out spawning all the other bosses on my PC and I seem unable to spawn the Primordial Five as well; I'm assuming it's for a similar reason that I can't spawn Kror.

**Comment by odw500** [comment]
Forgive the chain of comments, but after testing spawning the other bosses I went back to attempt spawning Kror again and it seemed to work again. The altar was playing its animation alongside the chat message and Kror spawned as he should (I was inside the variant of the Kror cave with the water pools). Not sure how to replicate this.

**Comment by EatingSilencer** [comment]
Were you in the deeplands when you spawned kror the second time?

Kror Altar only works in the deeplands.

**Comment by odw500** [comment]
Yes.
