### ISSUE TITLE
Torn Cloth

### ISSUE THREAD

**Issue by Geraldius23** [Tslat/Advent-Of-Ascension#2638]
**Mod Version**
3.3.6 Hexxit modpack

**Describe the bug**
For the knight armor in the shyrelands, I need padded cloth...this is only attainable with the help of torn cloth. But when I want to create the torn cloth using beds and banners, it does not seem to work.

**Expected behavior**
If the recipe had beds it could normally produce one torn cloth and if there was a banner it would produce two, but none of these seem to work.

**Screenshots**

<img width="676" alt="Screenshot 2021-06-11 at 4 18 14 PM" src="https://user-images.githubusercontent.com/85732746/121654887-c4481a00-cad0-11eb-9b1e-bfa1c2580a34.png">

<img width="535" alt="Screenshot 2021-06-11 at 4 18 27 PM" src="https://user-images.githubusercontent.com/85732746/121654816-b2ff0d80-cad0-11eb-8726-99bc17fa0423.png">

**Comment by Tslat** [comment]
The wiki is up to date for modern AoA versions. 1.12 is outdated, and the wiki info will be wrong for you. View page history on the wiki to find outdated info for your version

**Comment by EatingSilencer** [comment]
In other words, torn cloth being makable from beds and banners isn't a thing in 1.12.2 aoa.

**Comment by Geraldius23** [comment]
Ok thank your for the information
