### ISSUE TITLE
Monster (Weapon) Is Too Strong.

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#264]
**Describe/name the item/content this suggestion relates to**
While not necessarily overpowered, it still completely invalidates so many snipers. 75 damage allows it to completely outclass the Viper-1, Baron SSR, The Duster, and even the Terminator.
 
**Describe the change/balance you think would be good to see**
Damage nerf, what else can you do? I would say it should be nerfed to around 60 damage maybe? This would probably make the competition for your sniper slot more fair.

**Include any additional background information**
Some snipers are weak lol. Duster should at least do 60 damage or have a spread ability. Sabbath is fucking joke for one of last things you do in the mod, Its ability should be 100% of the time and also should do at least 60 damage.

**Comment by Tslat** [comment]
3.2 changes the balance on just about everything, including this
