### ISSUE TITLE
Are Carved runes too frequent? (mainly in chests)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2640]
**Describe/name the existing feature this suggestion relates to**
Carved runes

**Describe the change or feature you think would be good to see**
Having them always be in chests is nice, but having **2** of them per chest is a bit much. To the point where it's almost trivial to get all 4. In general, carved runes feel too frequent. Even when I had to get 2 sets of them for my Deeplands base, I don't think I needed to even travel more than 1000 blocks from my base to get more than 2 full sets.

I don't want to heavily nerf it, the bad RNG with these things can go a mile if you give them an inch. Here's how I would change it:
1. Reduce the amount of carved runes in a chest to 1, or just make the chance of a 2nd Carved rune really rare. Don't change the chance, there should still always be 1 in a chest.
2. Reduce the weight of the carved runes in the Overworld world table again. Even after the change they still feel really frequent.

-----------------------------

Also, I'd give them another use besides the portal, just so they aren't complete dead weight as soon as you get 1 set, even something small like 1 Carved rune= 2-4 Unpowered Runes

**Comment by Tslat** [comment]
Yes
