### ISSUE TITLE
Translations of the guide and bestiary isn't applied unless resource pack is reloaded 

### ISSUE THREAD

**Issue by Kagaribi172** [Tslat/Advent-Of-Ascension#2641]
**Mod Version**
3.5.2

**Describe the bug**
Title.

**To Reproduce**
1. Change the language to French or Chinese or Russian or Japanese
2. Restart Minecraft
3. Check out  guide and bestiary 

**Expected behavior**
Translations are applied without reload the  resource pack.

**Screenshots**
![2021-06-13_09 10 42](https://user-images.githubusercontent.com/63949302/121791774-9970d980-cc28-11eb-92e5-aee785fd8249.png)

**Comment by Tslat** [comment]
Sighhhh

This is mojang's fault, they call for resource listeners prior to setting the language.
This would affect their language stuff... if they didn't hardcode a solution around it for themselves

FFS

**Comment by Kagaribi172** [comment]
Sad...
As a temporary solution, can I add a message about reloading the resource pack to the welcome message in ja_jp.json?

**Comment by Tslat** [comment]
Leave it for now, I'll see if I can get something in for it sometime

**Comment by Kagaribi172** [comment]
ok
