### ISSUE TITLE
Decrease the chance of nothing on boss tables (because looting literally does not work on them)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2646]
Context: Mojang really dropped the ball on how Looting is coded. If I'm correct you can't really make it work with % drops somewhere post-1.12.

I was gonna wait until like boss update to make this. I don't really like the high chance of nothing on boss tables, the system of repeatedly killing a boss to maybe get what you want doesn't sit well with me. On paper it's not a bad idea, look at Terraria, but the chance to literally get nothing is way too high. In the past I ignored this issue because looting/luck drastically increased the amount of stuff. But when luck no longer affected drops in 1.15+, I really started to notice how high the chance of nothing really is.
Even if I was fighting the best boss ever, having to deal with such stacked odds is just not really good design.

And now things are even more pooped now that looting doesn't work either. Unless another solution is found, there's no excuse not decreasing the chance of nothing. Name someone that really enjoys getting nothing but a statue. Just sucks that Mojang are morons with looting code

**Comment by Cruuk** [comment]
Considering the limited options we have with looting, would it be possible for looting to just increase the quantity of non-weapon drops you get from bosses, rather than the chance?

I know this already happens with stuff like world tables, so it'd work with bosses, right? It'd at least be something
![image](https://user-images.githubusercontent.com/38159897/122307718-bf63db80-cebf-11eb-8ed6-9c5fba0cf19a.png)

**Comment by Tslat** [comment]
How would that affect getting nothing?

**Comment by Cruuk** [comment]
> 
> 
> How would that affect getting nothing?

I've shifted priorities. I'll take your word on how you've balanced the nothing chances, I'm just trying to find how you can make looting affect bosses at all. And as far as I know, having it affect the quantity and not the drop chances seems more feasible. I could be completely wrong on it being feasible but only 1 way to find out.
