### ISSUE TITLE
Deeplands Game Crash - Create Conflict???

### ISSUE THREAD

**Issue by videojamesmostlikely** [Tslat/Advent-Of-Ascension#2670]
**Mod Version**
3.5.2 - 1.16.5 minecraft release

**Describe the bug**
A game crash upon looking to the right of my portal after entering The Deeplands. Somehow caused by Create Ores; Copper and Zinc

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Create
2. Enter Deeplands
3. Load chunk (?)
4. Game Crash

**Expected behavior**
The game not crashing. I don't think it's supposed to do that

**NOTES**
Create ores were linked to crash by the mod Blame. Was a experimental report. The following was what was sent by the mod in log:
-----------------------------------------------------------------------
****************** Blame Report 1.9.2 ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

create:copper_ore
create:zinc_ore

-----------------------------------------------------------------------

**Comment by Tslat** [comment]
Provide the crash report from your crash reports folder

**Comment by videojamesmostlikely** [comment]
Got it! https://paste.ee/p/VQSFw
This is my whole log on MultiMC. It contains MANY of this crash.

**Comment by Tslat** [comment]
Looks like a mowzies mob crash to me. Go tell them
