### ISSUE TITLE
Crash involving Halos

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2673]
**Mod Version**
What version of the mod are you on?
3.5.2

**Describe the bug**
I was creating a superflat world when my game crashed:
[crash-2021-06-23_11.35.15-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/6703311/crash-2021-06-23_11.35.15-server.txt)

I have no idea how to replicate it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Unknown

**Expected behavior**
The game doesn't crash.

**Comment by Tslat** [comment]
See if this resolves in 3.5.3
