### ISSUE TITLE
Store keeper lingering poison potion trade is off

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2680]
It doesn't use the green color poison potions usually have. Also despite the length saying 7 seconds, throwing it and stepping it has it last way longer than that and gives me 30 seconds of poison when touching it.
![image](https://user-images.githubusercontent.com/38159897/123620136-be378600-d7be-11eb-82af-5a03ce7a00a3.png)

Also, using it to craft tipped arrows results in this.
![image](https://user-images.githubusercontent.com/38159897/123620192-ce4f6580-d7be-11eb-801d-dd6ca74f37ab.png)

**Comment by Tslat** [comment]
The duration is a vanilla bug
https://bugs.mojang.com/browse/MC-98310
