### ISSUE TITLE
Config Things

### ISSUE THREAD

**Issue by clowngirl7** [Tslat/Advent-Of-Ascension#2683]
**Describe the new feature you think would be good to add**
Could you possibly make it to where the overworld NPCs and the overworld mobs have separate disabled config modules?

**Add any alternative implementations you think might work**

**Include any additional background information**
My game crashes whenever Minecraft mobs attack the overworld NPCs and I would like to be able to disable just the NPCs and keep the mobs. Thank you for reading (if you have read this).

**Comment by Tslat** [comment]
Provide a crash report

**Comment by clowngirl7** [comment]
[crash-2021-06-30_13.17.29-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/6796112/crash-2021-06-30_13.17.29-server.txt)
This happened when a mob was attacking me but it accidentally hit an NPC and crashed my game. It also is not just the overworld I figured out. Its when any mob hits any NPC in any dimension.

**Comment by Tslat** [comment]
If you don't update your mods, how do you expect bug fixes to affect you?

Update AoA.
