### ISSUE TITLE
Wood from AoA trees can't be smelted into charcoal

### ISSUE THREAD

**Issue by PIXELATOR37** [Tslat/Advent-Of-Ascension#2698]
The only reason why I could see this being done is because the vanilla Crimson and Warped Stems can't be turned into charcoal. This, however, is because they're mushroom stems rather than tree logs, not merely because they're from another dimension. Seeing as how all the AoA wood blocks appear to be tree logs, it would make sense that they can be turned into charcoal, but they can't (at least, not in version 3.5.3).

**Comment by EatingSilencer** [comment]
This sounds like a bug, I suggested this a while back and it got added. Guess it was forgotten for the 1.16.5 port.
