### ISSUE TITLE
Ancient Teleporter Blueprint crafting

### ISSUE THREAD

**Issue by Silverkilla** [Tslat/Advent-Of-Ascension#270]
AoA3-Snapshot 10
![2019-01-29_04 11 54](https://user-images.githubusercontent.com/47123443/51866656-1a8ee500-237c-11e9-8225-50226f01df15.png)
![2019-01-29_04 12 05](https://user-images.githubusercontent.com/47123443/51866662-1f539900-237c-11e9-9969-9b67ec0d67a8.png)
![2019-01-29_04 12 14](https://user-images.githubusercontent.com/47123443/51866666-224e8980-237c-11e9-84b3-c1b417651e57.png)

Hello, I'm testing a new snapshot version of the mod in Survival mode and I've faced with a following issue. I can not craft an Ancient Teleporter Blueprint. Is there any other way to build a portal in Survival mode?
As you can see on the pictures I've tried to craft Ancient Teleporter in Creative mode. Also pay attention to the righ lower corner. The searcher can't find Ancient Teleporter.
I tried to find any information on the internet and haven't managed. That's why I'm writing you, hope you will reply.
By the way, thank you for such a fascinating mod =)

**Comment by Tslat** [comment]
Hi Silver,

The ancient teleporter blueprint hasn't existed for almost a year now, it was changed to a new system a long time ago.
Please see:
https://adventofascension.gamepedia.com/Ancient_Teleportation

**Comment by Silverkilla** [comment]
I've got you, thank you so much for your reply!
