### ISSUE TITLE
Glowing Pixons don't spawn in v. 3.5.3

### ISSUE THREAD

**Issue by PIXELATOR37** [Tslat/Advent-Of-Ascension#2702]
Title. I hope I'm not just extremely unlucky or something.

**Comment by oO0oO0oO0o0o00** [comment]
I don't think it's fixed. They're still not spawning in 3.5.4 (the same with 3.5.3).
 + Tested in both Normal and Flat worlds.
 + The difficulty is Normal and other mobs are spawning fine.
 + All other mods are disabled.
 + They DO spawn in version 3.5 .
 + With Forge forge-1.16.5-36.1.32 Minecraft 1.16.5.
 + Double-checked: `/kill @e[type=aoa3:glistening_pixon]` cannot find entities.

> Entities:
> * Fixed some Pixons & NPCs not spawning. (Github issue #2702)
> * Fixed Pixons not granting the killed stat. (Github issue #2708)

**Comment by Tslat** [comment]
This post was specifically for GLOWING pixons

Coincidentally (and unfortunately), the fix for glowing pixons broke other pixons lol
Yay me..
