### ISSUE TITLE
Bug with fishing loot tables (only getting lvl 1 drops)

### ISSUE THREAD

**Issue by Rodri418** [Tslat/Advent-Of-Ascension#2704]
**Mod Version**
What version of the mod are you on?
3.3.6

**Describe the bug**
After installing spongeforge to add plugins on an SMP (not 100% percent if it was the cause, but it happened the same day), I continued fishing to level up my hauling skill, but I noticed that I was only getting loot from vanilla, DungeonTactics and the level 1 fish, which is Raw Fingerfish. 
So I imagine that the bug is that when I fish, the game is not considering my level, and as a result, I only get the base drops from the loot table.
I tested this with other skills, but those gave me the appropiate items, it just bugged out with Hauling/fishing.
I am no expert regarding editing files, but if there is something I could edit, I could try it. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to fish in any water body.
2. Fish for a while, only getting level 1 AoA loot. 
3.See error

**Expected behavior**
As I have a higher level in fishing, I would expect higher tier fish, as well as rune boxes, weapons case and treasure boxes, but I only get base (level 1) drops.

**Comment by Tslat** [comment]
DungeonTactics likely overrides the loot.

Move to 1.16.5 to fix issues with multiple mods colliding loot tables.
