### ISSUE TITLE
Rosidons teleport players to base of scaffolding instead of top

### ISSUE THREAD

**Issue by PIXELATOR37** [Tslat/Advent-Of-Ascension#2706]
**Mod Version**
v. 3.5.3

**Describe the bug**
When standing in a Scaffolding tower, eating Rosidons teleports players to the base of the tower.

**To Reproduce**
1. Build a tower of scaffolding blocks
2. Stand inside the tower
3. Eat Rosidons

**Expected behavior**
The player is teleported to the top of the tower, since Rosidons are meant to teleport the player to the highest surface above them.

**Comment by Tslat** [comment]
This is a vanilla mechanic - Scaffolding isn't a solid block, it's more akin to a ladder
