### ISSUE TITLE
Monster generation

### ISSUE THREAD

**Issue by AmazingOcean** [Tslat/Advent-Of-Ascension#2707]
Hello, I have a question.
If the module runs in the server, it will only generate monsters in the main world ("world"), but not in the non main world ("world") generated by MV multi world plug-in.
Is it convenient for you to answer it?

**Comment by Tslat** [comment]
AoA doesn't cause this, something else in your list does

**Comment by AmazingOcean** [comment]
Excuse me, is it the monster that designated the main world to spawn aoa?

**Comment by Tslat** [comment]
I'm not sure what you're asking, sorry

**Comment by AmazingOcean** [comment]
Is the monster of aoa3 module generated by specifying certain worlds?

**Comment by Tslat** [comment]
No, MC spawns the mobs

**Comment by AmazingOcean** [comment]
Sorry, just asked the server developer, the other side said that aoa3 module limited the specified world to generate monsters.

**Comment by Tslat** [comment]
Yeah I have no idea what you're saying, think there's too much of a language barrier
