### ISSUE TITLE
Boss music replacements

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#271]
Some of the music currently used for bosses is copyrighted. The songs that are copyrighted are Smash, Corallus, KingBamBamBam, Nethengeic Wither, and Rockrider (let me know if I'm missing any). Anyways, the point of this suggestion is to suggest some replacements to these themes.

Smash: Kevin Macleod - Corruption (0:00 to 0:23)

Corallus: Kevin Macleod - Crossing the Chasm (0:00 to 0:38)

KingBamBamBam: Kevin Macleod - Final Battle of the Dark Wizards (0:26 to 0:55)

Nethengeic Wither: Machinamasound - the Arcade (0:29 to 0:45)

Rockrider: Kevin Macleod - Unholy Knight (0:00 to 0:41 OR 0:55 to 1:15)

Links:
https://www.youtube.com/watch?v=aax4ACs7WAw
https://www.youtube.com/watch?v=xxmcvwh37mk
https://www.youtube.com/watch?v=tWLozyS6EVU
https://www.youtube.com/watch?v=ypvFlsOetOA
https://www.youtube.com/watch?v=GxLdhLIS_LA

**Comment by Cruuk** [comment]
Music 1, 2, 3, and 5 fell too slow-paced for those bossfights, and 4 to me sounds like a dubstep mess. The one suggested for Rockrider seems to be the only decent one out of all of them for me.

**Comment by DiamondWalker** [comment]
I wasn't too sure about music 1 either. Listening to music 2 again, I can tell where you're coming from. I originally was going to suggest the level 2 (or whatever it's called) theme from Crypt of the Necrodancer, but that's probably copyrighted. As for music 3, I honestly think it fits better than the current one. I feel KingBamBamBam is the type of boss that should have slower music, considering he's slow but deadly himself. As for music 4, the reason I chose it is because it fits a chaotic boss like Nethengeic Wither.

**Comment by UnderWaves** [comment]
Hello folks!
I just talked with Scimiguy about this project, and I want to help to replace the boss musics.
I've already two projects (but only one really usable) of music...

1. Final Representation (Gyro battle)
https://www.dropbox.com/s/i1zcj3qwmqficsu/Final%20Representation%20%28Gyro%29.wav?dl=0

2. Swords of Doom (Craexxeus battle)
https://www.dropbox.com/s/6zzwoaqypg0gi13/Swords%20of%20Doom%20%28Craexxeus%29.wav?dl=0

**Comment by DiamondWalker** [comment]
Sounds great! Especially the Craexxeus one. Will he still have a phase 2 theme tho?

**Comment by TekterBR** [comment]
I think the melody on both Final Representation and Sword of Doom need some adjustments to make them fit better on the background, which is awesome
No need to change the background

**Comment by TekterBR** [comment]
Man...
Everything on this song is just perfect...
Even the title

**Comment by UnderWaves** [comment]
Heya guys...
after some work I created two other tracks.

1. Shyre Lord (Xxeus)
https://www.dropbox.com/s/48rx9ajig543ihi/Shyre%20Lord%20%28Xxeus%29.wav?dl=0

2. Crystallized (Crystocore)
https://www.dropbox.com/s/f8uppwio14jt35c/Crystallized%20%28Crystocore%29.wav?dl=0

**Comment by TekterBR** [comment]
Crystallized's background doesn't match the mood
Shyre Lord main sound doesn't match the mood
Both melodies are good

**Comment by DiamondWalker** [comment]
I don't really like Shyre Lord tbh. It's just Swords of Doom but sped up. It sounds too chaotic, which messes up some of the best parts of Swords of Doom.

Also, what do you use to make music?

**Comment by UnderWaves** [comment]
I currently use FLStudio 12. Planning to get better in some weeks

**Comment by UnderWaves** [comment]
Heya, sorry for the long nothing. I recently made some others musics

1. Lord of Crystallization (Crystocore, Evolved)
https://www.dropbox.com/s/b7sfe11qtra2k63/Lord%20of%20Crystallization%20%28Crystocore%29.mp3?dl=0

**Comment by DiamondWalker** [comment]
I like it. Pretty sure I heard so Swords of Doom motifs in there.

You should probably make a new issue whenever you make one of these. Scimi might use music suggestions, but this issue is new 3 pages back, and it's hard to notice when you make a new one. You'll probably have more chances of them being added if you made separate issues for each of them.

Also, 3.0 released and has resource pack support for music, so you could actually make a resource pack with these and publish it by yourself if they aren't used.

**Comment by UnderWaves** [comment]
Okay, thanks. I'll try to make that, even if I don't really know how to create a resource pack without RPW...

**Comment by DiamondWalker** [comment]
If you want I can set it up for you. PM me on discord if you want me to help you.

**Comment by UnderWaves** [comment]
What's your Discord?

**Comment by DiamondWalker** [comment]
Same as here (DiamondWalker).

I already sent you a PM when 3.0 first released to let you know you could make a resource pack, so you can just reply to that.
