### ISSUE TITLE
Latest Release 3.5.4 Can not run in Apple silicon (Old Version AoA3-3.5-1.16.5-Beta-4 work)

### ISSUE THREAD

**Issue by ghost** [Tslat/Advent-Of-Ascension#2712]
**Mod Version**
AoA3 3.5.4-1.16.5

**Describe the bug**
Minecraft can start, but when I create or join the world will crash (progress bar will freeze at 100%, then crash)

**Log**
log see [log](https://gist.githubusercontent.com/keke-cute/0862b4e792eea564c8ec182e415d9bfd/raw/901c54bda117b23180e36231b4d370de1e24023b/minecraft-exported-logs-2021-07-07T15-21-51.log)

**To Reproduce**
For Apple silicon, I use [m1-multimc-hack](https://github.com/DotIN13/m1-multimc-hack), run arm version minecraft, old version AoA3-3.5-1.16.5-Beta-4 very well, but latest release 3.5.4 not work

**Screenshots**
<img width="966" alt="Screen Shot 2021-07-07 at 3 44 59 PM" src="https://user-images.githubusercontent.com/37539103/124720113-5f9aa680-df3a-11eb-8491-656aaab27bbe.png">

**Comment by Tslat** [comment]
Looks to me like you're using the wrong java version.

MC requires java 8

**Comment by ghost** [comment]
> Looks to me like you're using the wrong java version.
> 
> MC requires java 8

Thank you, it works.

But AoA3-3.5-1.16.5-Beta-4 support java 11,  I can't understand latest release doesn't support.

**Comment by Tslat** [comment]
Not my problem

MC requires java8, that's what you use
