### ISSUE TITLE
Lunar creation table non-functional and can't be broken in survival (AoA 3.3.6 for MC 1.12.2)

### ISSUE THREAD

**Issue by Luxenmatori** [Tslat/Advent-Of-Ascension#2713]
**Mod Version**
version 3.3.6 for Minecraft 1.12.2

**Describe the bug**
Interacting with the table does nothing and when trying to break it while in survival mode it acts like bedrock

**To Reproduce**
Steps to reproduce the behaviour:
-find/give yourself a Lunar Crafting Table
-try to use it in any gamemode or try to break it in survival

**Expected behavior**
At the very least, I expected to be able to break it

Side note: I searched the wiki and all over google and found no mention of the block's function being removed/incomplete in this version of the mod

**Comment by EatingSilencer** [comment]
It functions differently in 1.12.2. This wiki page should tell you how to use it in that version: [https://adventofascension.fandom.com/wiki/Lunar_Creation_Table?oldid=98006](https://adventofascension.fandom.com/wiki/Lunar_Creation_Table?oldid=98006)

**Comment by Luxenmatori** [comment]
I don't know how I missed that wiki.
Seems to be working as intended in terms of function. I also didn't notice it's hardness was -1
