### ISSUE TITLE
Iromine loot chests are empty

### ISSUE THREAD

**Issue by PIXELATOR37** [Tslat/Advent-Of-Ascension#2715]
**Mod Version**
3.5.4

**Describe the bug**
Newly-generated loot chests in Iro Passages always contain nothing, even when opened with the Luck effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a not-yet-looted Iro Passage
2. Open a chest and see error

**Expected behavior**
The loot chests contain average Iromine loot when opened.

**Comment by Cruuk** [comment]
God dammit did I miss more Iro chests
