### ISSUE TITLE
Have the Conduit power given by Achelos stay at a few seconds or more above zero like Night vision goggles (vanilla bug?)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2719]
When wearing Achelos, the screen randomly gets dark for a fraction of a second. Based on this never happening with Night vision, not happening with a normal Conduit (which keeps the time at 11-12 seconds), and Achelos keeping it near zero, I'm willing to believe this is the result of a vanilla bug. To prevent this, the timer for Achelos' conduit power can just be increased.

**Comment by Tslat** [comment]
This _is_ a vanilla bug though
