### ISSUE TITLE
Crash server when mob spawn loot at death (EntityStoneGiant & EntityWoodGiant)

### ISSUE THREAD

**Issue by Upd4ting** [Tslat/Advent-Of-Ascension#272]
**Mod Version**
What version of the mod are you on? Latest

**Describe the bug**
The server crash when I kill EntityStoneGiant or EntityWoodGiant. The bug is caused by a wrong use of Random java class. Function nextInt must have a positive bound. 

**To Reproduce**
Kill EntityStoneGiant or EntityWoodGiant.

**Expected behavior**
Crash server Ticking Entity.

**Screenshots**
![image](https://user-images.githubusercontent.com/6763934/52065022-03b3e280-2576-11e9-839d-7a2dd75a8d50.png)

**Comment by Tslat** [comment]
Has been fixed
