### ISSUE TITLE
Undead herald/other NPCs don't seem to spawn in roofed dimensions

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2722]
Title. I'm noticing a severe lack of any NPC in dims with a ceiling since 3.5 in general. This includes the Nether, Deeplands, Crystevia, and L'Borean. They all share a roof of some sort. Passive mobs like Shik and Coratee work just fine, but NPCs just refuse to spawn no matter how much time passes. Maybe they are too rare? I do not know.

**Comment by Tslat** [comment]
And the cycle continues..
