### ISSUE TITLE
Placing a banner on top of another banner deletes it

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2725]
**Mod Version**
3.5.4

**Describe the bug**
Trying to place a banner while facing the sides of another banner doesn't work, but you sort of can while facing the top of an already placed banner. However, doing so quickly deletes the banner that was placed. It doesn't even end up back in your inventory.

**To Reproduce**
Steps to reproduce the behaviour:
Place a banner on the ground, then try to place another banner on top of it. 

**Expected behavior**
Not being able to place banners while facing the top of another banner, or the banner not getting deleted when placed.

**Comment by EatingSilencer** [comment]
This bug also occurs when placing a banner on top of a poppy.
