### ISSUE TITLE
Keep Snapshot 10 Haven Gen

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#273]
I think this is unintentional, but I like it like this so I will suggest keeping it.

So when snapshot 10 dropped, with the cascading gen done. We got a very beautiful looking Haven. Pretty much, trees spawn more frequently, and it makes Haven a lot more colorful.
![2019-01-31_20 31 34](https://user-images.githubusercontent.com/44548547/52083409-3f12d900-2597-11e9-8f06-a3d87acecd87.png)

In contrast, the 1.7 gen was a lot more barren, and to be honest more boring.
![2019-01-31_20 19 35](https://user-images.githubusercontent.com/44548547/52083472-6e294a80-2597-11e9-9c86-eb3c6d9dd9a8.png)
 (Sorry for particle effect, Optifine is fun).

**Comment by Immortallis1** [comment]
Don't like this idea too much, since in 1.12 there's so many trees it feels unnatural. Haven could use a few more trees than in 1.7 though so I'll avoid voting. Just not as much as in the first screenshot.

**Comment by Sagisolar** [comment]
That's a problem with Tree variety. Pretty sure Worldgen update is gonna do that anyway.
