### ISSUE TITLE
Error thrown by UUID string being too large.

### ISSUE THREAD

**Issue by havokraven** [Tslat/Advent-Of-Ascension#2734]
**Mod Version**
3.5.3

**Describe the bug**
This bug only happens on servers (as far as I noticed). The server starts up and runs fine, until a player attempts to join. Server throws an error claiming that player UUID string is too large and promptly disconnects the user. Checked and confirmed in the logs that AoA has highest priority listening onPlayerLogin and is the first mod to use UUID.fromString(). 

Suspected to be an error resulting from a mistyped UUID containing 9 characters in its first segment (where there should be 8).
Possibly faulty code can be found in Advent-Of-Ascension/source/event/PlayerEvents.java on line 316-329.

**To Reproduce**
1. Create a minecraft server running forge 1.16.5-36.1.0
2. Use AoA as one of the mods on the server and client
3. Launch server and attempt to join with client
4. See error in server console/log

**Expected behavior**
Expected to join server with client without problems.

**Screenshots**
![uuidtoolarge](https://user-images.githubusercontent.com/31316269/125138518-0df74500-e10f-11eb-8929-b30b6c3f3509.png)

**Comment by Tslat** [comment]
Minecraft uses Java 8. Use Java 8.
This has nothing to do with AoA.
