### ISSUE TITLE
Exception caught during firing event: UUID string too large

### ISSUE THREAD

**Issue by LLIaMMaH** [Tslat/Advent-Of-Ascension#2736]
**What version of the mod are you on?**
3.5.3 and 3.5.4

When trying to connect to the server, an error occurs and disconnects. With version 3.5.2 everything is fine.

[19:32:13 ERROR]: Exception caught during firing event: UUID string too large
        Index: 11
        Listeners:
                0: HIGH
                1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                2: NORMAL
                3: ASM: net.blay09.mods.trashslot.TrashSlot@2dc32c8e onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                4: ASM: class com.supermartijn642.configlib.ConfigLib$ConfigEvents onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                5: ASM: mods.waterstrainer.event.EventPlayerLoggedIn@6c575f59 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                6: ASM: class net.blay09.mods.waystones.handler.LoginHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                7: ASM: class com.leobeliik.extremesoundmuffler.eventHandlers.PlayerEventsHandler onPlayerLoggin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                8: ASM: net.minecraftforge.common.ForgeInternalHandler@60492fd9 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                9: ASM: class me.shedaniel.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                10: ASM: class xreliquary.handler.CommonEventHandler blameDrullkus(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                11: ASM: class net.tslat.aoa3.event.PlayerEvents onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                12: ASM: mcjty.theoneprobe.ForgeEventHandlers@e192ff6 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                13: ASM: dev.gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@45369c08 joinWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                14: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@1ac61658 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                15: ASM: codechicken.enderstorage.manager.EnderStorageManager$EnderStorageSaveHandler@2b0daac7 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                16: ASM: codechicken.enderstorage.network.TankSynchroniser@398f773a onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                17: ASM: shadows.apotheosis.ench.EnchModuleEvents@5f0d4a08 login(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.IllegalArgumentException: UUID string too large
        at java.base/java.util.UUID.fromString(Unknown Source)
        at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323)
        at net.minecraftforge.eventbus.ASMEventHandler_394_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:339)
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:171)
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:73)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:238)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1055)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:945)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by EatingSilencer** [comment]
Are you using a Java version besides Java 8?

**Comment by LLIaMMaH** [comment]
К сожалению для ядра, которое я использую необходимо использовать другую версию JAVA.
Unfortunately for the core I am using it is necessary to use a different version of JAVA.

Mohist 1.16.5 requires Java 11. https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot

**Comment by Tslat** [comment]
Provide your full log file

**Comment by LLIaMMaH** [comment]
Не прикрепляются к сообщению файлы и скрины. Выложил архив для скачивания.
Files and screenshots are not attached to the message. I posted an archive for download.
[https://mc.lliammah.space/download/modpack/1.16.5/OtherWorlds/logs_3.5.2-3-4.zip](https://mc.lliammah.space/download/modpack/1.16.5/OtherWorlds/logs_3.5.2-3-4.zip)

**Comment by Tslat** [comment]
Unfortunate, looks like Java 11 (perhaps only AdoptOpenJDK?) has the same issue.

Not much I can do, it's valid java.

**Comment by LLIaMMaH** [comment]
Но ведь версия 3.5.2 работает нормально. Значит с версии 3.5.3 появились какие-то изменения, которые вызывают эту ошибку.
But version 3.5.2 works fine. This means that since version 3.5.3 there have been some changes that cause this error.

**Comment by Tslat** [comment]
Correct. But those changes are valid java, and are used properly.
Minecraft runs on Java 8. If another client forces a higher java that causes conflicts, that's their fault.
Minecraft uses java 8. That's what I code for.

**Comment by LLIaMMaH** [comment]
Подскажите, я могу передать разработчикам ядра какую-нибудь информацию, для того, чтобы они внесли какие-то правки? Ведь на одном и том же ядре версия 3.5.2 работает, а начиная с версии 3.5.3 уже нет.

Tell me, can I give the developers some information so that they can make some changes? After all, version 3.5.2 works on the same kernel, since version 3.5.3 is no longer there.

**Comment by Tslat** [comment]
They need to use the correct version of java for Minecraft

**Comment by LLIaMMaH** [comment]
Разработчики ядра не вернуться на java 8. Стоит ли надеяться, что вы всё же подкорректируете код мода для корректной работы и с java 11? На данном моде основана вся сборка. В данную сборку специально не включались технологические моды, джек-паки, могилки и прочее, что облегчит прохождение всех миров.

Kernel developers will not return to java 8. Is it worth hoping that you will still correct the mod's code to work correctly with java 11? The entire assembly is based on this mod. Technological mods, jack-packs, graves and so on were not specifically included in this assembly, which will facilitate the passage of all worlds.
