### ISSUE TITLE
Bestiary and Guide GUI tabs are broken

### ISSUE THREAD

**Issue by benniekiss** [Tslat/Advent-Of-Ascension#2739]
**Mod Version**
What version of the mod are you on?
AoA3 3.5.4-1.16.5

**Describe the bug**

The GUI tabs show a small screen in the bottom left corner that can’t be resized. Can’t access those parts of the GUI. Changing GUI size in the minecraft video options does not change the problem.

**To Reproduce**
Steps to reproduce the behaviour:

macOS Big Sur, MC 1.16.5, Forge 36.1.0
join world, open AoA3 GUI, go to Bestiary or Guides tab.

**Expected behavior**
GUI should be visible

**Screenshots**

![2021-07-11_14 43 02](https://user-images.githubusercontent.com/63211101/125206669-7735a000-e256-11eb-881d-dd9bc1e4027e.png)
![2021-07-11_14 43 07](https://user-images.githubusercontent.com/63211101/125206670-7735a000-e256-11eb-9b15-22b925176c1c.png)
![2021-07-11_14 43 11](https://user-images.githubusercontent.com/63211101/125206671-77ce3680-e256-11eb-854f-59bb5aeb1774.png)

**Comment by Tslat** [comment]
Yeah Mac's new updates broke rendering in MC for a bunch of things.
There's not really anything I can do about this, because this is an apple issue
