### ISSUE TITLE
Lunalus should have colored stars in it's "sky"

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#274]
**Describe the new feature you think would be good to add**
I think a black background does fit Lunalus, however, I always thought the plain black background could use a little more.

So you know how the Overworld has stars at night?
![image](https://user-images.githubusercontent.com/38159897/52096683-90619f00-257c-11e9-9584-70c611a1166f.png)

I think it would be cool if Lunalus had stars like these in the background as well but they were pink (and maybe the occasional blue?). I think it would make Lunalus feel a bit more space-y rather than floating spheres in the middle of a void.

Not sure if the void side of the background should get the stars or not. If it doesn't, it could look weird? Not sure. The End has a dynamic background and the void side still has the background so...

Also, it would likely be best if the stars stayed in place unlike in the Overworld where they move with the moon.

**Include any additional background information**
I think various dimensions in general would really benefit from a more dynamic background rather than 1 static color. I'm not saying all of them need a detailed background nor do they need to be as insane in something like Betweenlands, I'm talking something more comparable to the End's background. I think it would be neat.
![image](https://user-images.githubusercontent.com/38159897/52097418-d704c880-257f-11e9-8a05-b3f1d13cbd9e.png)

**Comment by TekterBR** [comment]
And why not a nebula?

**Comment by DiamondWalker** [comment]
> 
> 
> **Describe the new feature you think would be good to add**
> I think a black background does fit Lunalus, however, I always thought the plain black background could use a little more.
> 
> So you know how the Overworld has stars at night?
> ![image](https://user-images.githubusercontent.com/38159897/52096683-90619f00-257c-11e9-9584-70c611a1166f.png)
> 
> I think it would be cool if Lunalus had stars like these in the background as well but they were pink (and maybe the occasional blue?). I think it would make Lunalus feel a bit more space-y rather than floating spheres in the middle of a void.
> 
> Not sure if the void side of the background should get the stars or not. If it doesn't, it could look weird? Not sure. The End has a dynamic background and the void side still has the background so...
> 
> Also, it would likely be best if the stars stayed in place unlike in the Overworld where they move with the moon.
> 
> **Include any additional background information**
> I think various dimensions in general would really benefit from a more dynamic background rather than 1 static color. I'm not saying all of them need nor do they need to be as insane in something like Betweenlands, I'm talking something more comparable to the End's background. I think it would be neat.
> ![image](https://user-images.githubusercontent.com/38159897/52097418-d704c880-257f-11e9-8a05-b3f1d13cbd9e.png)

Sounds good! If possible, there could be some randomly generated planet textures in between the stars (would work similar to tropical fish in 1.13). Also, instead of having more stars below (which would look weird, like you said), maybe there could be a large planet below (similar to galacticraft space stations). Would make sense since it's called **Luna**lus.

**Comment by Cruuk** [comment]
Wahoo
