### ISSUE TITLE
Tier 3 Dimension Voidtopia 

### ISSUE THREAD

**Issue by ddship12** [Tslat/Advent-Of-Ascension#2741]
Describe the new feature you think would be good to add

Hi guys, can we please add this to AOA3?

Generation:
Voidtopia generation can be built on world dark void background.
The prerequisite dimension is Crystevia
To get the Voidtopia realmstone a Crystocore need to be defeated.

Generated block suggestions:
Void Grass
Void Dirt
Void Stone
Voidlium Ore
Corruptlium Ore
Void Log
Void Leaves
Void Sand
Void Snow
Void Ice

Building block suggestions:
Wood
Void Plank
Stone
Void Stone Bricks
Ore
Voidlium Ingot
Corruptlium Ingot
Glass
Void Glass
Lamps
Voidlium Lamp
Corruptlium Lamp

Blocks ore suggestions:
Block of Voidlium
Block of Corruptlium

Biome suggestions:
Void Plains
Void Desert
Void tundra

Structure suggestion:
Void Pyramind

Mob suggestions:
Void Golem
Void Creeper
Void Scorpion
Void Lizard

Hunter Mob suggestions:
Void Mummy
Void Cobra

Boss suggestion:
Voidlord

Drop suggestions:
Strike Rune
Power Rune
Fire Rune
Storm Rune
Voidtopia Token
Voidlium Ingot
Corruptlium Ingot
Silver Coin
Gold Coin
Void Stone
Crystals
Gemstones
Sharp Claw
Magic Repair Dust
Void Great Blade
Void Bow
Void Helmet
Void Chestplate
Void Leggings
Void Boots

**Comment by Tslat** [comment]
Dimension suggestions must contain more information than a simple list of item/entity names.
