### ISSUE TITLE
[1.16.5] Mod Compatibility. Air is a fuel?

### ISSUE THREAD

**Issue by ZigTheHedge** [Tslat/Advent-Of-Ascension#2742]
AoA registers minecraft:air (empty stack to be exact) as a burnable item with a fuel value of 300. I'm not sure that it is supposed to be so. This issue were affecting Pneumatic Craft Air Compressors to run without fuel, maybe other mods which don't have a check of empty ItemStacks in "furnaces" will also be affected.

Mod version: 3.5.2
Minecraft: 1.16.5
Forge: 36.1.32

Steps to reproduce the behaviour:
Place down an Air Compressor from Pneumatic Craft. 
Enjoy your free airflow! )

Here's the small video: https://youtu.be/4gGVC9j9fMo

P.S: PneumaticCraft has added a check of empty ItemStacks in dev, so the issue will be resolved from their side.

**Comment by Tslat** [comment]
What makes you so sure AoA does this?

**Comment by ZigTheHedge** [comment]
Well, I've tested this with only two mods: PreumaticCraft and AoA. And here's the response from PneumaticCraft about 300 burnTime in AoA: https://github.com/TeamPneumatic/pnc-repressurized/issues/852#issuecomment-879689237
