### ISSUE TITLE
cannot not load server

### ISSUE THREAD

**Issue by 3269199948** [Tslat/Advent-Of-Ascension#2744]
**Mod Version**
What version of the mod are you on?
AoA3-3.5.4-1.16.5

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
....

https://paste.ubuntu.com/p/33DmXCFkBg/

I don't know what happened

**Comment by Tslat** [comment]
This isn't something AoA can cause. It's either a vanilla bug, or something is conflicting/causing it
