### ISSUE TITLE
The rabbit foot-dropping-probability seems not effectively influenced by looting 4.

### ISSUE THREAD

**Issue by 13930107167** [Tslat/Advent-Of-Ascension#2745]
The mc wiki says there is 19% chance to drop a rabbit`s foot with looting 3. But actually the chance is very low with looting 4.

Steps to reproduce the behaviour:
1. Create a new world
2. Kill a thousand rabbits
3. Very few foots dropping

**Comment by Tslat** [comment]
This has nothing to do with AoA
