### ISSUE TITLE
Infusion Table not working properly in 3.5.4

### ISSUE THREAD

**Issue by RMZing** [Tslat/Advent-Of-Ascension#2746]
Version 3.5.4; Advent of Ascention Plus modpack

When trying to craft Night Vision Goggles on the Infusion Table, I found that the output was missing, even after using JEI to assemble the ingredients. I tried all the frames and several ingredient configurations, but the output was not materializing. I tried this with a different recipe (Amethyst Leggings) as well, to no avail.

In addition to this, the usual behavior of converting infusion stones to power stones is also not working on the Infusion Table.

To see this yourself, all you have to do is create an Infusion Table and attempt to craft one of the recipes. I am assuming that all of the recipes are broken in the exact same way, though I can only confirm for the two listed above. Right-clicking the infusion table with infusion stones does nothing, when it should consume them and occasionally output a power stone. (Interestingly, doing this does not open the GUI, so it at least registers that the stones are _supposed_ to do something...)

![image](https://user-images.githubusercontent.com/65149251/125673036-fdf643ca-82fa-444c-9310-7d6b1c435510.png)
![image](https://user-images.githubusercontent.com/65149251/125673139-2aa135f4-ee97-4a26-a054-056ad02f9ddf.png)

I assume this is an issue with AoA itself, though another mod in the pack might have broken the table.

**Comment by Tslat** [comment]
Provide your log file.

**Comment by RMZing** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/6818343/latest.log)
[2021-07-14-1.log.gz](https://github.com/Tslat/Advent-Of-Ascension/files/6818345/2021-07-14-1.log.gz)

This should be sufficient. I haven't closed Minecraft since reporting the issue.

**Comment by Tslat** [comment]
Not sure, maybe there's a mod conflict?

At present all 3 of those things work perfectly fine for me in 3.5.4
Infusion recipes are working just fine for everyone else playing 3.5.4 that I've seen

**Comment by ghost** [comment]
Do you have FastSuite installed?

**Comment by RMZing** [comment]
Yes, FastSuite is installed.

**Comment by RMZing** [comment]
I removed FastSuite as well as FastWorkbench and FastFurnace, and the recipes are working again. Still cannot use infusion crystals on the table in my Survival world, though it works in a Creative test world.

**Comment by RMZing** [comment]
I wrote a comment on the modpack's page. Since this appears to be more an issue with FastSuite and not with this mod, I'll close it here. Thank you for your time.
