### ISSUE TITLE
Add more foliage to Precasia

### ISSUE THREAD

**Issue by PIXELATOR37** [Tslat/Advent-Of-Ascension#2749]
Since Precasia's plants only include huge, high-canopied trees and the occasional decorative plant, the forest floor seems a bit barren if you consider it's supposed to be a wild jungle, especially compared to other dimensions like Candyland. Here are some ideas I came up with for what could be added:

- Smaller, shrublike trees (like in vanilla Minecraft's jungles)
- Huge bramble vines made of blocks that act like cacti, but can be placed anywhere
- Large prehistoric flowers, with both single and double tall variants
- A carnivorous plant mob; perhaps a primitive Archvine that has yet to evolve legs and is therefore stationary

**Comment by Cruuk** [comment]
Don't forget Precasia not having any water haha

**Comment by PIXELATOR37** [comment]
There is water, it's just all at the bottom of the world
