### ISSUE TITLE
No Mobs in any of the dimensions

### ISSUE THREAD

**Issue by mitchngwen** [Tslat/Advent-Of-Ascension#275]
No AOA or vanilla mobs are spawning in the dimensions, is this normal? I am using the most recent AOA for Mincraft 1.12, am I missing something? Also is there an ingame guide book or something?

**Comment by Sagisolar** [comment]
Snapshot 10 doesn't include dimension mobs with the exception of Embrake and Arcworm. Don't worry tho, 3.0 is now getting close.

**Comment by Silverkilla** [comment]
Thats a shame, I faced with the same issue when playing survival

**Comment by Tslat** [comment]
That's because it's a snapshot. The mobs don't exist in the snapshot yet.
Wait for the full release

**Comment by Silverkilla** [comment]
Alright, i do wait for the release, i'd like to download it asap. Can i get a link where to download it from?

**Comment by Tslat** [comment]
You can join the official discord server to keep track of the mod's progress and any news

**Comment by Silverkilla** [comment]
Okay thank you
