### ISSUE TITLE
The service side reports errors after the player enters the game

### ISSUE THREAD

**Issue by xsy822** [Tslat/Advent-Of-Ascension#2750]
**Mod Version**
3.5.4

**Describe the bug**
![D~GXE_$PTDRP M_ 5A$TZO7](https://user-images.githubusercontent.com/72915608/126024905-32674804-c355-4edb-bfa1-b7ba9115c794.png)
![T7POU~2H`B YW77 YJ0TNZM](https://user-images.githubusercontent.com/72915608/126024917-c51b681f-2acb-48b8-b248-3b12354e3932.png)
There may be a mistake here?
uuid is like this:8-4-4-12?

**Comment by Tslat** [comment]
Minecraft runs on Java 8. Use java 8.
