### ISSUE TITLE
Flamewalker's ability is tied to mobGriefing instead of doStrongerMobGriefing

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2759]
**Mod Version**
What version of the mod are you on?
3.5.4

**Describe the bug**
The mobGriefing gamerule affects Flamewalker's ability to produce fire, instead of doStrongerMobGriefing.
**To Reproduce**
Steps to reproduce the behaviour:
1. Type /gamerule mobGriefing true.
2. Test a Flamewalker's ability to produce fire.
3. Type /gamerule mobGriefing false.
4. Test a Flamewalker's ability to produce fire.
5. Type /gamerule doStrongerMobGriefing true.
6. Test a Flamewalker's ability to produce fire.
7. Type /gamerule doStrongerMobGriefing false.
8. Test a Flamewalker's ability to produce fire.
9. See error

**Expected behavior**
Flamewalker's fire producing ability is tied to doStrongerMobGriefing, not mobGriefing.

**Comment by HyDefier** [comment]
Arguably Fire placement doesn't qualify as stronger mob griefing. I figure all that is necessary to satisfy this content change is a bunch of true/false settings for each mob that is capable of block changes in the mod config which are by default set to what they are always currently, but can easily be changed as desired by each player/ server operator. Maybe on a new document like "mob_config.toml" so "common_config.toml" doesn't get cluttered.

**Comment by EatingSilencer** [comment]
Closing this as doStrongerMobGriefing is gone now, and Flamewalker doesn't even have this ability anymore.
