### ISSUE TITLE
Dustopia Music

### ISSUE THREAD

**Issue by Firch** [Tslat/Advent-Of-Ascension#276]
I made a Dustopia dimension background music
Music should play while you in dustopia
EDIT:
https://soundcloud.com/hvab6gxlzwis/nevermine-dustopia/s-i2Dw1
(In-game version with fade-out effect)

**Comment by TekterBR** [comment]
Noice

**Comment by Tslat** [comment]
The track was deleted, so I'll have to remove the suggestion
