### ISSUE TITLE
Help: Spawn modifier config

### ISSUE THREAD

**Issue by goodtrailer** [Tslat/Advent-Of-Ascension#2760]
I've seen in several other issues (i.e. #1125) where a spawn modifier config is mentioned, but I just can't seem to find it. I've looked in `aoa3-server.toml`, `aoa3-common.toml`, and even `aoa3-client.toml`, all with 0 luck. What is the actual name of the config option? All I can find are structure and ore spawn configs.

**Mod Version**
3.4.9-1.15.2

**Comment by EatingSilencer** [comment]
I think it might've been removed in 1.15.2, so you can't find it.
