### ISSUE TITLE
Malformed UUID in code causing incompatibility with Java 9 and higher

### ISSUE THREAD

**Issue by s-cerevisiae** [Tslat/Advent-Of-Ascension#2761]
**Mod Version**
3.5.4-1.16.5

**Describe the bug**
Your code has a malformed UUID [here](https://github.com/Tslat/Advent-Of-Ascension/blob/12a3c6c7593a17ba13969eb0b37cf1a7ae7b996d/source/event/PlayerEvents.java#L323), but [this bug in Java 8](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8159339) "hides" it. A error will show up preventing players to join the server if Java 9 or higher is used since the bug was fixed after that.

**To Reproduce**
1. Run the server with JRE 9 or higher
2. Players trying to login will be kicked with prompt `Internal server error`, and server side shows `Exception caught during firing event: UUID string too large`.

**Expected behavior**
Everything should be fine and you should indeed write valid Java.

**Comment by Tslat** [comment]
🤔 wonder how long that UUID has been invalid.
I don't type UUIDs manually, I only copy paste, so when this one kept coming up but only on newer versions and neither the start nor end of the UUID was wrong, I could only assume it was it was correct.

Thanks for the info, fixed for next versionh
