### ISSUE TITLE
Mobs not matching WAILA display.

### ISSUE THREAD

**Issue by mitchngwen** [Tslat/Advent-Of-Ascension#277]
**Mod Version**
AoA3-Snapshot-10

**Describe the bug**
This bug happens on my server only, in single player I have not been able to see this happen. The server has been running fine with no mob texture issues for a few days after I took off optifine, now out of the blue mobs texture does not match WAILA display. 
[crash-2019-02-02_08.20.11-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/2824597/crash-2019-02-02_08.20.11-client.txt)

**To Reproduce**
I have no idea because it had been running fine with no issues

**Expected behavior**
The textures to match what the mob actually looks like

**Screenshots**
If applicable, add screenshots to help explain your pro
![2019-02-02_09 15 23](https://user-images.githubusercontent.com/45637150/52166500-52bf5c00-26cb-11e9-9ecd-d52a6046eabf.png)
blem.

**Comment by Tslat** [comment]
Known bug, fixed after snapshot 10

**Comment by mitchngwen** [comment]
Thank you that was a quick response.

**Comment by mitchngwen** [comment]
Excited for 3.0!
