### ISSUE TITLE
Smash - Overhaul

### ISSUE THREAD

**Issue by Dreadmare** [Tslat/Advent-Of-Ascension#2779]
I know that Smash is supposedly the first boss, and thus the easiest. However, it is in my opinion that Smash is indeed too easy, provided you have the items for it. Having a good armor as well as some way to negates the fall damage is the only requirement to defeat him. Therefore, some changes will have to be made to keep his fight interesting and not another zombie reskin.

Firstly, Smash melee attack will no longer knocks the player up. His speed would also be reduced. Both of these is to remove the need for anti-fall damage measure, which new players might not have, as well as to make it easier to deal with his new sets of mechanics as below. As per the mechanical changes, the way of obtaining Troll Idol should also be changed

**Phase 1 : 100%-50% HP**
_Charge_ :  Dust particles will appear behind him before charging at the player, breaking virtually all blocks in his path. Any entities that are in his path will take heavy damage and receive a knockback. On hard difficulty, Smash will charge twice in quick succession.

_ Slam_ :  Slam his weapon down, dealing high damage to anything in a cone in front of him. This attack cannot be blocked

_Heavy Slam_ : Raise his weapon and slam them down, dealing heavy damage to anyone nearby. The radius of the slam is inversely proportional to the amount of blocks he had to break. This will also break any blocks within a smaller radius around it. This attack cannot be blocked.

_Jump Attack_ : Smash will  jump into the air onto the player, creating a shockwave that must be jumped over. After this attack, Smash is vulnerable for a brief moment.

**Phase 2 : 50%-0% HP**
_Smash will empower himself, causing him to attack faster and enhancing his abilities with a new effect_

_Charge_ : His charge become faster and is capable of destroying more blocks.

_Slam_ : Now create debris projectiles in a cone in front of Smash. On hard difficulty, this will send out a shockwave in front of him.

_Heavy Slam_ : Now knocks back anyone within a 20 blocks radius, with the potency increasing the closer you are to him.

_Jump Attack_ : Now create a secondary shockwave that also must be jumped over. The secondary shockwave are slower and deal less damage.

_In both phases, if Smash is unable to access his target(i.e the target is hiding behind blocks), he'll Charge. If his target is nowhere to be found, he'll pick a new target instead. If no target is found either, he'll turn into stone and become invincible until he find an accessible target_

**Comment by HyDefier** [comment]
Like for harder bosses!

**Comment by profilename14** [comment]
Looks like he would be fun to fight. I like the flavor details with stuff like turning to stone if no players are nearby and creating dust particles when charging.
