### ISSUE TITLE
Lottoman Reskin/Rename + Related Features

### ISSUE THREAD

**Issue by HyDefier** [Tslat/Advent-Of-Ascension#2780]
INTRO:
In my opinion, Lottomen don't make sense. They certainly aren't locals; on the current lore they are identified as a mysterious group or even phenomenon that appear in each dimension to sell their wares. Lottomen strike me as the type that would strike up a conversation while convincing you to buy their goods or sell your valuables... not that they do in game, but that's the vibe I get, and if they did talk openly their origin would not be mysterious. 

DESCRIPTION PT.1:
Anyway, I have two potential variations of the inter-dimensional trader role which I think would be interesting and work well in AoA. In both variations they are still a mysterious group that sell a few set items in most every dimension, and in both Lottomen are all of one common origin, rather than looking like genetically mutated humans, and I'm open to names (as per usual)…

VARIATION 1:
The mysterious group appears in each dimension in disguises. They would be wearing a local entity costume with a few telltale signs it's not real in texture details and an eye slit at a consistent height. The group is motivated by the greater potential for profit found in interdimensional trading, while avoiding drawing attention or getting those pesky inter-dimensional tariffs and outsider prices.

VARIATION 2:
The mysterious group wear a well-known concealing uniform and have an air of mystery about them. They avoid being near any entity unless the entity has a coin in hand (perhaps crouching too) which they interpret as someone interested in doing business. The whole trade comes across as edgy and under-the-table due to some dialogue, or text in a receipt book, or just the name look and actions of the trader. 

DESCRIPTION PT.2:
Both groups could (optionally) spawn naturally(not a mob spawner block, or a one time spawn), but only in underground hideouts(or on hideout floor block), which can be found in all dimensions except structure dimensions like Nowhere. They would adventure out periodically and return. Each hideout variation would have surface camouflage so the trader has to be followed on their way back to realistically find the hideout. While traveling back to base, the trader prioritizes avoiding mobs over returning to base, so they cannot be followed closely. Inside the underground hideout, there would be trader related loot and a lead trader impressed with your locating of the base. This trader could trade blocks ([Something to address the many types of stone etc. in the mod](https://github.com/Tslat/Advent-Of-Ascension/issues/2777)). Additionally, there could be some guards at the entrance that are just plain and simple aggressive mobs, or they could have a condition like piglins (maybe no helmet?).

BACKGROUND INFORMATION:
NPCs and trading are a topic with a decent bit of mileage on this Github. I'll attach a few related Issues, but I am aware of no Issues containing the same content. I think this idea has the potential to move forward with many of these in mind.
[Have Trader NPCs follow a player holding a Lunaver coin like how animals follow players holding a certain food item #2767](https://github.com/Tslat/Advent-Of-Ascension/issues/2767)
[Villager-npcs designs #2129](https://github.com/Tslat/Advent-Of-Ascension/issues/2129)
[AoA NPCs are Villagers instead of weird humanoids. #1752](https://github.com/Tslat/Advent-Of-Ascension/issues/1752)

Anyway, this is a big idea, and I haven't included every possible detail, just enough to get some feedback and further developing thoughts..

**Comment by Cruuk** [comment]
I don't like suggestions like these that try to fix a problem that wasn't there in the first place. Sure it "makes more sense", but making the player jump through these weird hoops is gonna make playability worse, and that's most important

**Comment by HyDefier** [comment]
Lotta weird hoops in aoa. I think world immersion is a pretty big part of gameplay quality and maintaining interest for a longer duration. It's not like lottomen are a required element for reaching the next dimension in a playthrough, rather they fall into "side missions" that increase player strength. Anyway, there is lots of room for modifying the idea and bringing it closer to existing systems in function.
