### ISSUE TITLE
Discharge Sniper Crash

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#279]
**Mod Version**
Latest 1.12 snapshot

**Describe the bug**
Shot a sheep with the Discharge Sniper while scoped, causing a crash. The sheep was partially behind a log, and this wasn't the first mob shot with it.

**To Reproduce**
Have not been able to reproduce.

**Expected behavior**
Sheep should have died with no crash.

**Other notes**
Several other mods were present, though from what I can interpret from the crash log they don't seem to be involved.
[crash-2019-02-02_11.48.44-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/2824800/crash-2019-02-02_11.48.44-server.txt)

**Comment by Tslat** [comment]
I believe this is the same as the armour registration bug previously reported.
I'm gonna close this for now, let me know if it happens after 3.0
