### ISSUE TITLE
NPC trade GUIs instantly close

### ISSUE THREAD

**Issue by NoahDKitts** [Tslat/Advent-Of-Ascension#2796]
**Mod Version**
3.5.4

**Describe the bug**
Whenever I right click a naturally spawned NPC (such as the Lottoman) their trading GUIs open, but close after a split second, the GUI stays open for manually spawned NPCs via Spawn Eggs and summoning.

**To Reproduce**
Steps to reproduce the behaviour:
1. Right clicking a naturally spawned NPC will show its trading GUI for a split second, then close

**Expected behavior**
Naturally spawned NPC trading GUI to stay open

**Video**
https://user-images.githubusercontent.com/35241271/127776083-530c4a0c-3975-4a2d-8ced-c5f6bce54742.mp4

**Comment by EatingSilencer** [comment]
Post the latest.log file. NPCs work for me so something else must be going on. Does this problem occur with naturally spawning NPCs? Do you have any other mods present?

**Comment by NoahDKitts** [comment]
The problem occurs with naturally spawning NPCs, and even without the other present mods the problem still persists.
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/6913103/latest.log)

**Comment by Tslat** [comment]
Try it without any other mods present
It may be a mod conflict?

Looks strange..
