### ISSUE TITLE
Change Augury's name to "Divination" and have it be based off the tribute bar (+ how I would change Tribute)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2801]
Augury is fundamentally flawed. The old skill was nasty, and the name means birdwatching. The way I see it, it would be better off having its name changed to **Divination** and be connected to whatever is planned for the tribute system. I suggested something similar a few years ago a little too many times to be frank, so this is the last time I'm making this since it's the perfect time to.

Divination would be about appeasing the gods and having them gift you greater power. You could still please them at level 1 Divination, but the boosts would simply be weaker compared to a player with higher levels of Divination.

I am unsure what is planned for Tribute, but whatever it is, Divination would be able to amplify it. Divination training would also be connected to filling up Tribute, or whatever the equivalent will be. I'd imagine that there will be more than 1 way to "gain" tribute?

------------------------------------------

It is hard to make this post more detailed, as I don't know what's planned for Tribute. So this section is for how I would personally change Tribute to model Divination into, so that I can be more detailed.

Tribute would be a little similar to its current form- doing certain tasks to get temporary boosts. However, you would be able to fill up tribute in any dimension, and there would be more ways of doing so, based off the characteristics of each god. The difficulty of fully filling up a bar would be a bit harder, but more equalized among all 4 of them- Erebon wouldn't be so easy to please but Pluton would not be painful anymore.

Instead of waiting for night to get a boost, the boost could be obtained by using a block or item once you have a filled up Tribute bar. As mentioned before, a higher level of Divination would amplify the boost you get, increasing the potency and/or how long it lasts.
Remember the mention of a block here, I will get back to it later.

To balance things out, a tribute bar that is not currently boosting a player will slowly drain if the player isn't actively filling it up. This makes it so a player can't just "pocket" the effect and always have it at the ready. incentivising a more smooth routine of pleasing a god rather than stark intervals of metagaming it. An inactive **full** tribute bar will take far longer to start draining so the player isn't screwed over when they're about to activate it. I guess this contradicts what I just said about pocketing but it would suck for it to start draining just as you're about to activate it, it'd be a nice convenience.

Maybe to further help with this, you don't to have the bar 100% full to activate an effect. E.g. you only need 180/200 tribute to activate it. Filling up that extra optional Tribute would extend how long the effect lasts if players want that extra time. This could be indicated by a small line in the bars showing players how far they really need to fill it up at minimum.

To extend this idea further, maybe pleasing a god multiple times in a row would begin a streak of lowering the minimum requirement by a small amount. Breaking this streak increase the minimum req back to normal. Divination could also have a hand in affecting this minimum requirement.

When activated, the tribute bar will moreso act as a visual timer for how long the effect lasts, you can't fill it up more while it's activated and extend the timer. Once the effect ends, the bar will be back to empty, and you'll have to fill it up again.

Fully filling up a tribute bar is also how you would **train** Divination. It wouldn't be completely passive, as the exp would come in big scaled bursts after fully filling up any tribute bar and activating it. There would be factors that increase the amount of exp you get: Pleasing more than 1 god at once, pleasing a god multiple times in a row(?), doing god tasks while boosted by them (E.G. killing stuff while boosted by Erebon would grant you small amounts of Divination exp when it otherwise wouldn't), etc. I restricted the 3rd factor to only while boosted, as it would be a little weird to get Divination exp from doing almost anything in MC. I could be wrong though. 

The boosts themselves would also be more than just simple potion effects. Erebon could have your attacks partially pierce armor, Selyan could grant you effects similar to Hydrangic armor, Pluton could lower trade costs similar to Hero of the village, Luxon affects the Energy and/or Soul Power meters, and more. They could also affect the aspects of other skills.
Additionally, items like the god scythes and sticklers could be changed to integrate this system. They'd be on the weaker side, but would be stronger if used while boosted by a corresponding god. Maybe there could even be exclusive minor boosts by being boosted by a combination of gods. E.G Erebon + Pluton grant something related to looting, Selyan + Erebon grant some sort of thorns effect. I'm just spitballing.

Also, the boosts would definitely be longer than 10 minutes.

Going back to the **block** thing. The way I see it, you could activate full Tribute by using a block of sorts. However, it'd be a multiblock similar to a Beacon. Surrounding the block with certain items would correlate it to a god. E.G Surrounding it with flowers and stuff would make it a Selyan shrine, surrounding it with "light" things makes it a Luxon shrine, etc. It'd only require like 2-3 things, not fully surround it with stuff. The block would change color to reflect what god it is dedicated to.

The reason this whole process is robust is that to me, this powerful universal temporary effect should not be super flexible. Of course, if it's too tedious, it can be toned down. Like having the block just have a GUI you interact with instead of making it require having stuff next to it.

And of course, "Divination" armor's full set effect would be something simple like double the rate you gain Tribute, like Holy sword. Or affect the drain thing I mentioned earlier.

------------------------------

I think this does not break any of the skill update guidelines. I tried designing this with those guidelines in mind.

**Comment by Tslat** [comment]
One concern I have with this is the the amount of usefulness this actually provides.
The kind of bonuses you're talking about would have to be balanced very carefully so as not to be overpowered, but that just leads me to think that it'd end up being mostly inconsequential until you're very high level, which sounds pretty lame

**Comment by Cruuk** [comment]
> 
> 
> One concern I have with this is the the amount of usefulness this actually provides.
> The kind of bonuses you're talking about would have to be balanced very carefully so as not to be overpowered, but that just leads me to think that it'd end up being mostly inconsequential until you're very high level, which sounds pretty lame

That is fair. It would be difficult to stay in the fine line between not useful and overbearing.

One possible solution is to make the boosts at level 1 already fairly useful, and make Divination only amplify it by a smaller amount. And make it so the skill is more about unlocking more boosts given by tribute. E.G. Erebon gives a damage boost that is increased by a bit when leveling Divination, but at say level 15-20 Divination the Erebon boost also allows your attacks to partially pierce armor, and leveling Divination further amplifies this a bit. Rinse and repeat.

It's not a perfect solution, but it's just spitballing. And again, no matter what Tribute becomes, at minimum I would like to see a renamed Augury affect it in some way. It's why I have my tribute rework in a separate section.
