### ISSUE TITLE
Grammar/word issue in Living Fungi bestiary

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2804]
**Mod Version**
What version of the mod are you on?
3.5.4

**Describe the bug**
There's a grammar/word issue in Living Fungi's bestiary.
![image](https://user-images.githubusercontent.com/44556728/127977839-4de20bd4-dbce-4a1b-a2fa-fc0f5d1c7f4a.png)
Their body is extremely toxic, with a very thin spore **covering layered** over their body.

**To Reproduce**
Steps to reproduce the behaviour:
1. Check Living Fungi bestiary.
2. See error

**Expected behavior**
One of the extra words is removed.

**Comment by Tslat** [comment]
Eh, looks fine. It's just a weird combination of words.
I'll think about it

**Comment by EatingSilencer** [comment]
Oh is this a case of "the complex houses married and single soldiers?". "Covering" is a noun?

**Comment by Tslat** [comment]
Correct
