### ISSUE TITLE
Lower the fire rate of staves (and increase the damage)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2806]
**Describe/name the existing feature this suggestion relates to**
Staff fire rate

**Describe the change or feature you think would be good to see**
I know it sounds weird, but let me explain why I think it would help staves.

I like to divide the weapon types into 4 archetypes: Melee, ranged, bullet, and magic. In each archetype weapon types fill a role: swords are the fast melee, GBs are slow, mauls are utility, bows are single target, crossbows are more AoE, etc. And in magic, Vulcanes are a secondary with unlimited range, but attacking staves and blasters fill the same role- fast firing rate with good DPS. This causes a conflict, despite the difference in walkspeed with blasters slowing you down, both achieve the same playstyle in the same archetype, which is not good, as one will be better than the other. In this case, blasters are the clear winner with higher DPS and an ammo system that isn't horrible.

----------------------------------

The point is, **no matter how the rune system is improved**, Staves and blasters will continue to conflict in how they deal damage. Even though Staves don't slow your walkspeed, Blasters are just that good in PvE where it's never a problem unless you're bad at positioning. Even if we ignore these "archetypes", can't forget the guns.

I think the best solution would be to shift staves into a different global firerate. Lowering the fire rate, but increasing the damage. It would make staves not so reliant on DPS and eternally screwed over by Blasters. It'd turn them into good sources of damage with a slow fire rate, along with still having upsides of no unholster time, full walkspeed, and free offhand usage.

They would still have lower DPS than blasters, but I think it'd be better if players didn't have to spam the staff to get the damage output they want and waste ammo. This is why support staves are so much better than the attacking staves, you don't have to spam them. And I don't how you can fix a rune system to accommodate for that without changing the fire rate.

I would rather have them be slightly above average DPS with slow fire rates rather than filling my screen with particles and missing half my shots. It's like if snipers were changed into fast DPS machine guns with lowered damage, but it makes them worse cause you have to hit all those shots.
Again, even ignoring these "archetypes" this shift in fire rate would differentiate them from stuff like thrown weapons and guns, both tend to fire fast.

Lowering the fire rate would also keep the stronger support staves in check. Shyre staff, Joker staff, Crystik staff, and some others would honestly be busted if the current rune system didn't suck and they still had 1.67 "fire" rate.

--------------------

Personally I'd change the fire rate from 1.67 to 0.67 or even 0.5. The damage wouldn't equally scale cause that would be kind of busted with all the other Staff upsides

**Comment by Tslat** [comment]
Yeah I'm inclined to agree tbh
