### ISSUE TITLE
No glistening pixons spawning

### ISSUE THREAD

**Issue by Jempasam** [Tslat/Advent-Of-Ascension#2810]
** Mod Version **
3.5.4 - 1.16.5

** Describe the bug **
A pixon appeared when I created a world and then no more. I created a few other world but i did not find any.

** To Reproduce **
1.Create a world
2.Move then use /kill @e[type=aoa3:glistening_pixon]
3.No pixons are killed so there is no pixons

**Expected behavior**
Glistening pixons should spawn

**Comment by Tslat** [comment]
Known
