### ISSUE TITLE
Pixons Gone

### ISSUE THREAD

**Issue by JoolsBond** [Tslat/Advent-Of-Ascension#2813]
**Mod Version**
What version of the mod are you on?
3.5.4

**Describe the bug**
this has to be a bug, I've been playing through AOA and im still in the early stages, and i wanted to level up infusion but literally no Pixons spawn anywhere in the overworld (idk if in any other dimension i havent looked) i even looked on mountains where the glistening ones usually spawn, none at all, Pixons spawned in other versions, sadly this version doesn't 
**To Reproduce**
Steps to reproduce the behaviour:
1. get 3.5.4 and do the things you need to do to get the mod running
2. go onto survival with normal mode etc on
3. look around (plains and mountains preferably)
4. no pixons

**Expected behavior**
Pixons to spawn

**Screenshots**
![image](https://user-images.githubusercontent.com/89200466/130076914-4eb85ab8-2aff-44fd-beb0-4f40864ed412.png)

**Comment by EatingSilencer** [comment]
Known bug. Downgrade to 3.5.3 for now to fix it.

**Comment by JoolsBond** [comment]
> Known bug. Downgrade to 3.5.3 for now to fix it.

if i change the version and play on the same world would the version be fixed? I don't want to change worlds since I've made pretty good progress, ive been looking and playing on 3.5.3 and no sign of pixons still
