### ISSUE TITLE
Lelyetia is bugged?

### ISSUE THREAD

**Issue by JoolsBond** [Tslat/Advent-Of-Ascension#2816]
**Mod Version**
What version of the mod are you on?
3.5.3
**Describe the bug**
alright this might be a known bug or a change that is known but I built the ancient portal and went to lelyetia since it was the only realmstone I had, I enter and I spawn in the mirrored side, instead of the non-mirrored side, and theres none of the square holes in the ground, and the gravity effect doesn't take place (like in previous versions) I fall down testing if the gravity takes effect, and when I fall, I then fall into the sky of the top of the mirrored side and fall to my death? this was not how it was like in previous versions but I don't know

**To Reproduce**
Steps to reproduce the behaviour:
1. get the realmstone and build the portal 
2. enter the lelyetia
3. wait to load

**Expected behavior**
I expected to spawn on the non mirrored side of lelyetia
**Screenshots**
![image](https://user-images.githubusercontent.com/89200466/130601830-80ba54d3-e3ab-4a68-a379-f732b3ed7173.png)

**Comment by EatingSilencer** [comment]
1. Not sure if Lelyetia spawning you on the underside is a bug or not.
2. Lack of square holes is intended; there are a few regular holes here and there.
3. Lack of gravity intended, Lelyetia doesn't have that anymore.

**Comment by JoolsBond** [comment]
> 1. Not sure if Lelyetia spawning you on the underside is a bug or not.
> 2. Lack of square holes is intended; there are a few regular holes here and there.
> 3. Lack of gravity intended, Lelyetia doesn't have that anymore.

ah ok, yea lelyetia got weird, thanks for clarifying ^_^
