### ISSUE TITLE
Buff Crystevia Mobs Slightly

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#282]
Seriously, Construct of Speed and Construct of Range are exact physical duplicates of Charger and Goblin (except for maybe slight differences in movement speed). They spawn in a dimension that is accessible from one accessible from the overworld, so they should not have the exact same health as their overworld counterparts.

Since they appear later, I propose they are buffed (and potentially other Crystevia mobs too excluding mind/terror) just a little bit to differentiate them/add a tiny bit of difficulty.

**Comment by Sagisolar** [comment]
I think strength should be a glass cannon

**Comment by Cruuk** [comment]
The same can be said for the difficulty of a lot of dimensions...

**Comment by Tslat** [comment]
Balance for pretty much every mob in 3.2 has been changed/rebalanced
