### ISSUE TITLE
The ability to listen to PlayerLevelChangeEvent in CT scripts

### ISSUE THREAD

**Issue by Pikabyte** [Tslat/Advent-Of-Ascension#2824]
The CraftTweaker integration allows packdevs to work with skills, but to fire code when a skill level changes(which would be useful for say, making gamestages based on skill levels), we currently would need to compare each skill's level every playertick...which isn't ideal.

It would be nice if it were possible to listen to the PlayerLevelChangeEvent, so that we could check the player's current level in there instead.

**Comment by Tslat** [comment]
Is event listening a thing CT supports?
I'm not intimately familiar with the features of it

**Comment by Pikabyte** [comment]
Yes,
https://docs.blamejared.com/1.16/en/vanilla/api/event/CTEventManager/

**Comment by Tslat** [comment]
Had a look through this, I don't see why it isn't possible to listen to PlayerLevelChangeEvent?

**Comment by Pikabyte** [comment]
Is it already possible? I saw nothing about it on the wiki, and I thought there had to be compatibility specifically added for it which I didn't see in the source. I suppose I technically haven't actually tried. Sorry for the late reply, I'll look at it later today maybe.

**Comment by Tslat** [comment]
https://docs.blamejared.com/1.16/en/vanilla/api/event/CTEventManager

**Comment by Tslat** [comment]
Looks like it'd work just fine to me. I'm gonna close this for now
