### ISSUE TITLE
Voliants heart received by mining?

### ISSUE THREAD

**Issue by JoolsBond** [Tslat/Advent-Of-Ascension#2826]
**Mod Version**
3.5.4

**Describe the bug**
Voliants hearts only drop from the haven table, at least according to what the wiki has to say, when I was mining crystallite I literally just got one out of no where and didn't kill a singular mob in the haven, for more specifics I used a emberstone pickaxe with efficiency V, fortune II, and unbreaking III 

**To Reproduce**
Steps to reproduce the behaviour:
1. go to the haven
2. use the pickaxe I described or any
3. start mining
4. get one?

**Expected behavior**
I didn't expect a voliants heart to not appear in my inventory 

![2021-09-11_22 31 17](https://user-images.githubusercontent.com/89200466/132962094-370fc564-95d1-46ad-b197-69ae257de487.png)

**Comment by Tslat** [comment]
The haven table works a bit differently to other world tables. This isn't a bug

**Comment by JoolsBond** [comment]
ah oki thanks for clarification
