### ISSUE TITLE
Forge system

### ISSUE THREAD

**Issue by RiasErisDiaz** [Tslat/Advent-Of-Ascension#2829]
**Describe the new feature you think would be good to add**
A specific and detailed description of what you want to see.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?

**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?

A new complicated feature we can use on any armor in the mod with certains ore to lvl up armor's piece to increase base stat or effect
We can have more dangerous bosses and dimension who one shot players with weak armor in end game dimension

It work with forging station (and a hammer ?) and ores of a certain dimension
It can even contain few stage level of new bonus effect like increase critical damage, critical chance or defense ingnore or more attaque base

An exemple :
lvl 1 : stat (stat is level of defense)
lvl 2 : stat
lvl 3 : stat + crit dmg
lvl 4 : stat
lvl 5 : stat
lvl 6 : stat + element dmg
ect....
Each step will be reachable with luck, with a certain % of luck it up (hamme tool with luck enhancement ?)
(you can add a pity system, with a small bar that increase with each lose ore who don't lvl up and at it's 100% it will force lvl up)

If it's too easy to lvl up, you can add forge durability (not on hammer, on the system directly) who denied to try to lvl up if a certain (rare ?) item isn't use first to recover a certain quantity of forge

And for weapon it's different (change enchanting by this)
Use certain type of different colour of stone to socketing wep to add new effect
5 free slots + 5 blocked slots (to unlock with special rare item drop) of red, blue and yellow color + 1 to 3 giant grey slot for increase durability of wep or decrease the cost of repair
Red color can manage essential thing for player like HP, ennergy, hunger, ect...
Blue color manage damage type, elemental, physical, ect...
yellow color manage move like attack speed, double attack, ect...

2nd option (or take both) : 
Glyph system :
Always three colours, red, blue and gold (or other colour) Glyphs don't work if it miss one of these colour
Red for condition to trigger the effet
Exemple : While jumping, after defeating a monster, when attacked by a boss, every x seconde, when sprinting, when HP drop below x%, when taking item on the ground, when recovering x% of soul, energy or whatever, after atacking x time (miss attack reset it), ect ...
Blue for probability to trigger effect
Yellow for effect (you can create a 4th colour for power level of effect
Exemple :
critical chance, critical damage, attack, defense ignore,ect ....
Glyph's effect have 30 seconde of cooldown

**Comment by Tslat** [comment]
Armour is already reaching the cap of its effectiveness, and with protection enchants and resistance potion effects, a couple extra armour points means basically nothing

As for adding more effects, wouldn't that just mean people pick one armour set and load it up with their chosen effects rather than choosing the right set for the job?
