### ISSUE TITLE
Minor MK (+Fung) buff

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#283]
**Describe/name the item/content this suggestion relates to**
So the MK is kinda bad compared to its competition. It requires level 77 hunter to obtain it while you can get the Megagun at level 71 or the Chain Walker (+It's upgrade) at level 65. Both do more damage than it. Even the MK Fung doesn't fair much better with the Megagun and the Flame Walker.

**Describe the change/balance you think would be good to see**
I think the MK should have a 50% to not consume ammo.
I think the MK Fung should have a 50% to not consume ammo.

I think it would be a good pay off. Less damage, less ammo being used.

**Include any additional background information**
I think the MK Fung should be renamed to MK Fungi.

**Comment by Tslat** [comment]
3.2 Did things
