### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ErosZenin** [Tslat/Advent-Of-Ascension#2832]
**Mod Version**
What version of the mod are you on?
1.12.2
**Describe the bug**
Im not sure if this is a bug but when i go to another world like Barathos and i want to use the portal to go back to the overworld it doest work and i dont know what to do,

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
To go back to the overworld
**Screenshots**

**Comment by Tslat** [comment]
1.12 is no longer supported with patches
Join the Discord server and give more information if you want personal help
