### ISSUE TITLE
Mob Spawn Rate Config

### ISSUE THREAD

**Issue by Jmotta05** [Tslat/Advent-Of-Ascension#2833]
Could you please provide a config file to edit the amount of regular mob spawns overall? I'd like to be able to lower it by about half, the amount of mobs spawning in the overworld during the day and night is crazy, and they spawn very close as well, I'm struggling to get anywhere without being zapped by goblins or run down by something.

Thank you!

**Comment by Tslat** [comment]
https://www.curseforge.com/minecraft/mc-mods/in-control
