### ISSUE TITLE
JEI not showing when I install advent of ascension. removing AoA makes it reappear right away, yes I tried to unhide it..

### ISSUE THREAD

**Issue by FearAK** [Tslat/Advent-Of-Ascension#2834]
**Mod Version**
AoA3-3.5.4-1.16.5.jar

**Describe the bug**
When installing Advent of Ascension JEI dissapears. Yes I try to use the hide/unhide from jei but it doesn't work. Removing the mod makes jei appear again right away.

**To Reproduce**
Steps to reproduce the behaviour:
Download advent of ascension... open game.. jei gone

**Expected behavior**
To play advent of ascension with jei..

[latest - Copy.log](https://github.com/Tslat/Advent-Of-Ascension/files/7185413/latest.-.Copy.log)

**Comment by Tslat** [comment]
Try it withotu any other mods present (besides JEI & AoA)

We likely have a mod conflict on our hands, need you to work out which mod it is

**Comment by FlameyFaucet** [comment]
AoA and JEI works just fine. It's a mod conflict, and i might try figuring which mod it is.
_Haha, binary searching 113 mods is gonna be fun..._

**Comment by FearAK** [comment]
Didn't notice that i got replies, my bad. Tried removing 200 mods slowly and still happens.. a big pain in the butt

**Comment by FlameyFaucet** [comment]
Don't worry, i'm currently going through the pain of chopping my 112~ mods pack into halves so i can isolate the mod. It has taken me an hour >:(

**Comment by FlameyFaucet** [comment]
Hi, back from my test. Do you happen to have the mod PizzaCraft installed? My pack's JEI issue was caused by that mod, and you may have it too, so it'll be worth removing it.

**Comment by FearAK** [comment]
Ah damn, thank you for letting me know what was the cause for you, sadly I don't have pizzacraft so I guess I gotta keep diggin xD

**Comment by Xplodin** [comment]
also getting this bug on a custom pack. Added AoA and instantly JEI stopped working. No crash no nothing

**Comment by Tslat** [comment]
Work out which other mod is causing it when combined with AoA
AoA and JEI work perfectly fine together, so there must be another mod that triggers the failure
Find out which one it is and let me know

**Comment by Xplodin** [comment]
> Work out which other mod is causing it when combined with AoA AoA and JEI work perfectly fine together, so there must be another mod that triggers the failure Find out which one it is and let me know

Found it. Was futurepack for me
