### ISSUE TITLE
Rosidian Sword problem

### ISSUE THREAD

**Issue by iccarusA** [Tslat/Advent-Of-Ascension#2836]
AoA3 3.4.5 -  1.16.5

Rosidian sword crash my server

Steps to reproduce the behaviour:
1. Have low Health 
2. Use the sword
3. Server crash

only happens with this sword
[crash-2021-09-16_00.27.03-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/7189149/crash-2021-09-16_00.27.03-server.txt)

**Comment by Tslat** [comment]
Reports for outdated versions are not accepted
