### ISSUE TITLE
Entity render crash AoA3 1.15.2

### ISSUE THREAD

**Issue by Apotheosisdyl** [Tslat/Advent-Of-Ascension#2838]
**Mod Version**
Tried on both AoA3 3.4.9-1.15.2 and AoA3 3.4.8-1.15.2

**Describe the bug**
After loading into the game between 20-90 seconds in the game crashes and I get the crash report java.lang.NullPointerException: Rendering entity in world

I've reproduced this error 5 times, each time the only thing that changes is the entity spawned in from AoA3, it is not limited to one it seems to be any and all entities from the mod making me crash. I've redownloaded, switched the version of the mod, troubleshooted by removing other mods like optifine and now I'm at a loss at what to do. 

Crash report: https://pastebin.pl/view/0e782f18

**Comment by Tslat** [comment]
Try it without other mods present

This looks like a conflict problem

**Comment by Apotheosisdyl** [comment]
Me and a friend are playing on a server with the exact same issues and she doesnt get the crash upon joining despite having all the same versions and everything as me, I'm at a loss since its not the mods on the computer, going to try reinstalling forge client next.

**Comment by Apotheosisdyl** [comment]
So I did a little more troubleshooting and matched all my game settings, video settings and everything, tried to join the server and it crashed, same with single player. I then reinstalled the forge client to make sure nothing had going wrong with the forge loader and no luck, still get the same crash. Removed AoA and it works again. We use the latest version of forge and AoA for 1.15.2

**Comment by Tslat** [comment]
Yes that's all well and good, but I asked for it to be tried without any other mods
