### ISSUE TITLE
Coin Resprites

### ISSUE THREAD

**Issue by Equidas** [Tslat/Advent-Of-Ascension#2842]
I've just made a few edits to the coin sprites in the mod to give them a more polished and vibrant appearance.

![coins4x4](https://user-images.githubusercontent.com/63214689/135489726-6fdf929e-bddb-4caf-aa62-feaa9df65841.png)
(Updated versions based off community feedback)

![coins ingame](https://user-images.githubusercontent.com/63214689/135160793-f829f7c8-d8dd-4542-88d6-dbe3dd1c9c7d.png)
(alt versions ingame)

Included are two variants, the first with a dark outline similar to the original, and the second with a slightly lighter one which may be closer to the style of vanilla Minecraft. If you have any feedback or want access to the individual files my discord is Equidas#1750

**Comment by Tslat** [comment]
So I went to use these, but it turns out you never actually included the files to use. So.. I'm gonna have to close this unless you can add the files to the post
