### ISSUE TITLE
Ancient Cavern/Immortallis

### ISSUE THREAD

**Issue by Daschel1** [Tslat/Advent-Of-Ascension#2844]
I really love the new version for 1.16.5, but I was really sad when you guys removed Ancient Cavern and Immortallis since those were one of my favorite dimensions. Maybe you guys are going to bring it back or revamp it in some way, but I also think for Lunalus that there should be normal mobs that spawn in without a mob spawner as well :)

thanks for all of you guys hard work!

**Comment by EatingSilencer** [comment]
AC/Immortallis will probably see a replacement in Nowhere (Nowhere is currently an unfinished dimension).

**Comment by ddship12** [comment]
Tslat say no Timmortallis
