### ISSUE TITLE
Advent of Ascension is not compatible with Java 15? in Minecraft 1.16.5

### ISSUE THREAD

**Issue by DefaultUSERNAME9** [Tslat/Advent-Of-Ascension#2845]
**Mod Version**
Advent Of Ascension 3.5.4 Minecraft 1.16.5

I want to update to the Java 15 that is  supported by 1.16.5 in the past i played in  Java 8 thus no problems arose ,But when i updated to Java 15 the world just crash

 1.First I updated java to Java15
2.I open Minecraft it run smoothly 
3.I cant open my World 

Here is the Crash Report
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 10/7/21, 1:05 AM
Description: Ticking memory connection

java.lang.IllegalArgumentException: UUID string too large
	at java.util.UUID.fromString1(UUID.java:264) ~[?:?] {}
	at java.util.UUID.fromString(UUID.java:258) ~[?:?] {}
	at net.tslat.aoa3.event.PlayerEvents.onPlayerLogin(PlayerEvents.java:323) ~[aoa3:3.5.4-1.16.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1447_PlayerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?] {re:classloading,re:mixin}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:232) ~[?:?] {re:mixin,re:classloading,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,pl:mixin:APP:betterendforge.mixins.json:PlayerListMixin,pl:mixin:APP:cgm.mixins.json:common.PlayerListMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:connection.ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:connection.ServerLoginNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinIntegratedServer,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:832) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 15.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3961019240 bytes (3777 MB) / 6845104128 bytes (6528 MB) up to 6845104128 bytes (6528 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmn128M -Xmx6524M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.4
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotori_scala@2.13.5-build-2
	Mod List: 
		notenoughcrashes-3.2.0-forge.jar                  |Not Enough Crashes            |notenoughcrashes              |3.2.0               |DONE      |Manifest: NOSIGNATURE
		astralsorcery-1.16-1.16.5-1.13.12.jar             |Astral Sorcery                |astralsorcery                 |1.16.5-1.13.12      |DONE      |Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		AdditionalEnchantedMiner-1.16.5-16.1.9.jar        |QuarryPlus                    |quarryplus                    |16.1.9              |DONE      |Manifest: 1a:13:52:63:6f:dc:0c:ad:7f:8a:64:ac:46:58:8a:0c:90:ea:2c:5d:11:ac:4c:d4:62:85:c7:d1:00:fa:9c:76
		Hats-1.16.5-10.3.1.jar                            |Hats                          |hats                          |10.3.1              |DONE      |Manifest: NOSIGNATURE
		prefab-1.6.5.11.jar                               |Prefab                        |prefab                        |1.6.5.11            |DONE      |Manifest: NOSIGNATURE
		ProjectE-1.16.5-PE1.0.1B.jar                      |ProjectE                      |projecte                      |PE1.0.1B            |DONE      |Manifest: NOSIGNATURE
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.17.0.1_Forge_1.16.5.jar          |Xaero's World Map             |xaeroworldmap                 |1.17.0.1            |DONE      |Manifest: NOSIGNATURE
		CookingForBlockheads_1.16.5-9.3.4.jar             |Cooking for Blockheads        |cookingforblockheads          |9.3.4               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.6.0.jar                          |Placebo                       |placebo                       |4.6.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |DONE      |Manifest: NOSIGNATURE
		rangedpumps-0.8.2.jar                             |Ranged Pumps                  |rangedpumps                   |0.8.2               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.2.12.337.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.2.12.337   |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.16.5.1.2.6.jar                   |Guard Villagers               |guardvillagers                |1.2.6               |DONE      |Manifest: NOSIGNATURE
		buildinggadgets-1.16.5-3.8.0.jar                  |Building Gadgets              |buildinggadgets               |3.8.0               |DONE      |Manifest: NOSIGNATURE
		Apotheosis-1.16.5-4.8.0.jar                       |Apotheosis                    |apotheosis                    |4.8.0               |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |DONE      |Manifest: NOSIGNATURE
		Hwyla-Mod-1.16.3.jar                              |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		dynviewdist-2.0.jar                               |Dynamic view distance         |dynview                       |1.8                 |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.546-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		mob_grinding_utils-1.16.5-0.4.28.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.16.5-0.4.28       |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.9.15.jar                         |Refined Storage               |refinedstorage                |1.9.15              |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.5-1.6.1.jar                   |BetterEnd Forge               |betterendforge                |1.16.5-1.6.1        |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |Manifest: NOSIGNATURE
		alltheores-1.3.6-1.16.5-36.1.0.jar                |AllTheOres                    |alltheores                    |1.3.6-1.16.5-36.1.0 |DONE      |Manifest: NOSIGNATURE
		out_of_sight-1.16.4-1.0.1.jar                     |Out of Sight                  |out_of_sight                  |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.14.6-14.jar       |Industrial Foregoing          |industrialforegoing           |3.2.14.6            |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.2.5+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.2.5+1.16.5        |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.5.jar              |More Villagers                |morevillagers                 |1.5.5               |DONE      |Manifest: NOSIGNATURE
		fastfurnaceminusreplacement-1.1-1.16.3.jar        |Fast Furnace Minus Replacement|fastfurnaceminusreplacement   |1.1-1.16.3          |DONE      |Manifest: NOSIGNATURE
		endremastered-forge-R4.1.1.jar                    |End Remastered                |endrem                        |4.1                 |DONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-419.jar                            |Botania                       |botania                       |1.16.5-419          |DONE      |Manifest: NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		betterbiomeblend-1.16.4-1.2.9-forge.jar           |Better Biome Blend            |betterbiomeblend              |1.16.4-1.2.9-forge  |DONE      |Manifest: NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |DONE      |Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |DONE      |Manifest: NOSIGNATURE
		majruszs-difficulty-1.16.4-1.1.0.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |1.1.0               |DONE      |Manifest: NOSIGNATURE
		ChunkNoGoByeBye-1.16.5-1.3.0.jar                  |ChunkNoGoByeBye               |chunknogobyebye               |1.16.5-1.3.0        |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |Manifest: NOSIGNATURE
		observerlib-1.16.5-1.5.3.jar                      |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |DONE      |Manifest: NOSIGNATURE
		fastbenchminusreplacement-1.4.jar                 |FastWorkbench Minus Replacemen|fastbenchminusreplacement     |1.4                 |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.3.434-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.3.434           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.46.jar                  |GeckoLib                      |geckolib3                     |3.0.46              |DONE      |Manifest: NOSIGNATURE
		Cyclic-1.16.5-1.4.2.jar                           |Cyclic                        |cyclic                        |1.16.5-1.4.2        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		BorderlessWindow-1.16.5-1.2.0.jar                 |Borderless Window             |borderlesswindow              |1.16.5-1.2.0        |DONE      |Manifest: NOSIGNATURE
		miniutilities-1.2.2.jar                           |Mini Utilities                |miniutilities                 |1.2.2               |DONE      |Manifest: NOSIGNATURE
		Resynth-6.2.0-[Minecraft-Forge-1.16.5].jar        |Resynth - Growable Resources  |resynth                       |6.2.0               |DONE      |Manifest: NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |DONE      |Manifest: NOSIGNATURE
		bountifulbaubles-1.16.5-0.1.0-forge.jar           |Bountiful Baubles             |bountifulbaubles              |1.16.5-0.1.0        |DONE      |Manifest: NOSIGNATURE
		AoA3-3.5.4-1.16.5.jar                             |Advent of Ascension           |aoa3                          |3.5.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.121.jar                          |Just Enough Items             |jei                           |7.7.1.121           |DONE      |Manifest: NOSIGNATURE
		chaosawakens-1.16.5-0.9.0.2.jar                   |Chaos Awakens                 |chaosawakens                  |0.9.0.2             |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |DONE      |Manifest: NOSIGNATURE
		lemonlib-1.3.6.jar                                |Lemon Lib                     |lemonlib                      |1.3.6               |DONE      |Manifest: NOSIGNATURE
		Space-Bosstools-1.16.5-5.4.jar                    |Space-BossTools               |boss_tools                    |5.4                 |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.3.jar                        |Waystones                     |waystones                     |7.6.3               |DONE      |Manifest: NOSIGNATURE
		FastSuite-1.16.4-1.1.1.jar                        |FastSuite                     |fastsuite                     |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.25.jar                               |Clumps                        |clumps                        |6.0.0.25            |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |DONE      |Manifest: NOSIGNATURE
		OuterEnd-0.2.14.jar                               |The Outer End                 |outer_end                     |0.2.9               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.16.5-2.3.2.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.2               |DONE      |Manifest: NOSIGNATURE
		pneumaticcraft-repressurized-1.16.5-2.14.4-258.jar|PneumaticCraft: Repressurized |pneumaticcraft                |1.16.5-2.14.4-258   |DONE      |Manifest: NOSIGNATURE
		lazydfu-0.1.3.jar                                 |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.16-5.0.22.jar                          |McJtyLib                      |mcjtylib                      |1.16-5.0.22         |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.16-2.0.11.jar                       |RFToolsBase                   |rftoolsbase                   |1.16-2.0.11         |DONE      |Manifest: NOSIGNATURE
		rftoolsdim-1.16-7.0.14-beta.jar                   |RFToolsDimensions             |rftoolsdim                    |1.16-7.0.14-beta    |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |DONE      |Manifest: NOSIGNATURE
		inventorypets-1.16.5-2.0.15.jar                   |Inventory Pets                |inventorypets                 |2.0.15              |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.4.1.jar                       |iChunUtil                     |ichunutil                     |10.4.1              |DONE      |Manifest: NOSIGNATURE
		EnderStorage-1.16.5-2.8.0.168-universal.jar       |EnderStorage                  |enderstorage                  |2.8.0.168           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		ars_nouveau-1.16.5-1.23.11.jar                    |Ars Nouveau                   |ars_nouveau                   |1.23.11             |DONE      |Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-6.jar             |Immersive Petroleum           |immersivepetroleum            |3.3.0-6             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.4-universal.jar                 |Forge                         |forge                         |36.2.4              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.3-18.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.3-18     |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.17.jar                |TLSkinCape                    |tlskincape                    |1.17                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		ironchest-1.16.5-11.2.13.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.13      |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.47-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.47              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		thermal_dyenamics-1.16.4-1.0.0.jar                |Thermal Dyenamics             |thermal_dyenamics             |1.0.0               |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.3.1.jar                        |CoFH Core                     |cofh_core                     |1.3.1               |DONE      |Manifest: NOSIGNATURE
		thermal_foundation-1.16.5-1.3.2.jar               |Thermal Series                |thermal                       |1.3.2               |DONE      |Manifest: NOSIGNATURE
		thermal_innovation-1.16.5-1.3.0.jar               |Thermal Innovation            |thermal_innovation            |1.3.0               |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.16.5-1.3.0.jar                |Thermal Expansion             |thermal_expansion             |1.3.0               |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		TConstruct-1.16.5-3.1.2.265.jar                   |Tinkers' Construct            |tconstruct                    |3.1.2.265           |DONE      |Manifest: NOSIGNATURE
		luckyblock-1.16.5-1.jar                           |Lucky Block                   |lucky                         |1.16.5-1            |DONE      |Manifest: NOSIGNATURE
		titanium-1.16.5-3.2.8.5-20.jar                    |Titanium                      |titanium                      |3.2.8.5             |DONE      |Manifest: NOSIGNATURE
		mana-and-artifice-1.4.0.8.jar                     |Mana and Artifice             |mana-and-artifice             |1.4.0.8             |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.3-138.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.3-138    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		EntityCulling-1.16.5-2.1.6.jar                    |Entity Culling                |entity_culling                |2.1.6               |DONE      |Manifest: NOSIGNATURE
		allthemodium-1.5.12-1.16.5-36.1.23.jar            |Allthemodium                  |allthemodium                  |1.5.12-1.16.5-36.1.2|DONE      |Manifest: NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.16.4-2.0.1.jar                  |Majrusz Library               |majrusz_library               |2.0.1               |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.4.jar                           |Flywheel                      |flywheel                      |1.16-0.2.4          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2d.jar                       |Create                        |create                        |v0.3.2d             |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.123.jar                         |Mantle                        |mantle                        |1.6.123             |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.17.0_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |21.17.0             |DONE      |Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.7.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.7        |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.25.jar                   |Polymorph                     |polymorph                     |1.16.5-0.25         |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-316.jar                                |Quark                         |quark                         |r2.4-316            |DONE      |Manifest: NOSIGNATURE
		FluxNetworks-1.16.5-6.1.7.12.jar                  |Flux Networks                 |fluxnetworks                  |6.1.7.12            |DONE      |Manifest: NOSIGNATURE
		performant-1.16.2-5-3.72m.jar                     |Performant                    |performant                    |3.56m               |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.0.7-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.7               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		SoL-Carrot-1.16.5-1.10.1.jar                      |Spice of Life: Carrot Edition |solcarrot                     |1.16.5-1.10.1       |DONE      |Manifest: NOSIGNATURE
		byg-1.3.4.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |DONE      |Manifest: NOSIGNATURE
		battletowerslite.jar                              |Battle Towers Reforged        |battle_towers_reforged        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.10.jar                        |Valhelsia Core                |valhelsia_core                |16.0.10             |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.5.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.5        |DONE      |Manifest: NOSIGNATURE
		createaddition-1.16.5-20210911a.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20210911a    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f707f192-a948-4350-abf7-4965bd6ce45b
	Patchouli open book context: n/a
	Suspected Mods: Forge (forge), Advent of Ascension (aoa3)
	Player Count: 1 / 8; [ServerPlayerEntity['OutworldVOID'/167, l='ServerLevel[Prospect Survivial]', x=-234.07, y=66.00, z=32.58]]
	Data Packs: vanilla, mod:astralsorcery, mod:quarryplus, mod:hats, mod:projecte, mod:xaeroworldmap, mod:cookingforblockheads (incompatible), mod:placebo (incompatible), mod:citadel (incompatible), mod:alexsmobs, mod:yungsapi, mod:rangedpumps, mod:sophisticatedbackpacks, mod:guardvillagers, mod:buildinggadgets, mod:apotheosis (incompatible), mod:mekanismgenerators, mod:waila, mod:dynview (incompatible), mod:twilightforest, mod:mob_grinding_utils, mod:refinedstorage, mod:betterendforge, mod:structure_gel, mod:out_of_sight (incompatible), mod:industrialforegoing (incompatible), mod:repurposed_structures, mod:morevillagers, mod:fastfurnaceminusreplacement (incompatible), mod:endrem, mod:dungeons_plus, mod:botania, mod:sf, mod:curios, mod:patchouli (incompatible), mod:betterbiomeblend, mod:obfuscate (incompatible), mod:vehicle (incompatible), mod:majruszs_difficulty, mod:chunknogobyebye (incompatible), mod:cfm (incompatible), mod:aiimprovements, mod:observerlib, mod:fastbenchminusreplacement, mod:codechickenlib (incompatible), mod:bettermineshafts, mod:geckolib3 (incompatible), mod:cyclic (incompatible), mod:miniutilities, mod:resynth, mod:cgm (incompatible), mod:bountifulbaubles (incompatible), mod:aoa3 (incompatible), mod:jei, mod:chaosawakens, mod:abnormals_core, mod:mekanism, mod:lemonlib, mod:boss_tools, mod:waystones (incompatible), mod:fastsuite (incompatible), mod:clumps, mod:naturescompass (incompatible), mod:outer_end, mod:dungeoncrawl, mod:pneumaticcraft, mod:lazydfu, mod:mcjtylib, mod:rftoolsbase, mod:rftoolsdim, mod:iceandfire (incompatible), mod:inventorypets (incompatible), mod:ichunutil, mod:enderstorage (incompatible), mod:ars_nouveau, mod:forge, mod:bloodmagic, mod:tlskincape (incompatible), mod:ironchest, mod:dungeons_arise, mod:thermal_dyenamics, mod:cofh_core (incompatible), mod:thermal (incompatible), mod:thermal_innovation (incompatible), mod:thermal_expansion (incompatible), mod:tconstruct, mod:lucky (incompatible), mod:titanium (incompatible), mod:mana-and-artifice, mod:entity_culling, mod:allthemodium, mod:towers_of_the_wild, mod:smoothboot, mod:majrusz_library, mod:flywheel, mod:create, mod:mantle (incompatible), mod:xaerominimap, mod:gravestone, mod:polymorph, mod:autoreglib (incompatible), mod:quark (incompatible), mod:fluxnetworks, mod:performant (incompatible), mod:ferritecore (incompatible), mod:solcarrot, mod:byg, mod:battle_towers_reforged, mod:valhelsia_core, mod:valhelsia_structures, mod:createaddition, mod:notenoughcrashes, mod:alltheores, mod:chocolate, mod:borderlesswindow (incompatible), mod:immersivepetroleum, mod:immersiveengineering, mod:prefab, mod:neat (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7926
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 8

Any Thoughts

**Comment by Tslat** [comment]
There's a small addon I made to fix this until I include the fix itself in the next major version

Jump on the official discord and ask about it
Just need to throw it in your mods folder along with AoA and it'll work again

**Comment by DefaultUSERNAME9** [comment]
thanks
