### ISSUE TITLE
Certain newly spawned mobs staying put?

### ISSUE THREAD

**Issue by CorporalData** [Tslat/Advent-Of-Ascension#2846]
**Mod Version**
AoA3 3.5.4-1.16.5

**Describe the bug**
**A clear and concise description of what the bug is.**
Not very adverse, but certain newly spawned mobs (so far I've seen the Night Reaper, Bugeye, and the Ancient Golem) will, although still hostile when walked into melee distance, stay put until they are either nudged, moved, or hit.

**To Reproduce**
**Steps to reproduce the behaviour:** Wait for a new instance of mob to spawn, and approach it.

**Expected behavior**
**A clear and concise description of what you expected to happen.**
Not sure what expected behaviour means, but I guess I would expect the mob to approach me like other mobs do.

**Screenshots**
**If applicable, add screenshots to help explain your problem.**
Video: https://imgur.com/a/Bs7JtM8

**Comment by Tslat** [comment]
This is a forge bug. Update forge.
