### ISSUE TITLE
No hostile mobs spawn in Haven

### ISSUE THREAD

**Issue by ARaffler** [Tslat/Advent-Of-Ascension#2849]
**Mod Version**
AoA3 3.5.4 1.16.5

**Describe the bug**
As described in the title no hostile Mobs spawn upon entering Haven. It works fine in every other dimension.
I created a new world and had the same problem there. When I press F3 it tells me that I'm in Haven and when I summon mobs per command they don't move at all.

**Comment by EatingSilencer** [comment]
There are no naturally spawning hostile mobs in Haven. It is a peaceful dimension. Except for spirit guardian/spirit protectors, which spawn in the guardian towers/from eeos when hurt.

**Comment by ddship12** [comment]
No hostile mobs in haven for you like an monkey
