### ISSUE TITLE
When a mob enters a portal, make it so there's a cooldown before they can use a portal again

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2865]
**Describe/name the existing feature this suggestion relates to**
3.6 alpha 1

**Describe the change or feature you think would be good to see**
I'm not exactly sure how vanilla portals work, but AoA portals appear to have an inconsistency. When you push a mob through an AoA portal, it will immediately go back out as soon as you go in and load the dim. For example, if I'm in the overworld and push a mob through a Shyrelands portal, and then I go in, the mob will immediately go back to the overworld due to it being in the portal frame.

This makes transporting mobs irritating. The only way to get a mob fully through from what I've seen is having both you and the mob stand in the portal frame, and use a realmstone. This makes it so that the mob is pushed out of the frame as soon as it enters the dim.

Vanilla Nether portals do not appear to have the same problem. The mob still spawns in the portal frame, but there seems to be a "cooldown"(?) before it can enter the portal again. This is empirical, so I am not 100% sure.

**Comment by HimmelFernweh** [comment]
I think so, such a bug can be annoying sometimes. Once my trident goes into the portal, and I end up losing it.
