### ISSUE TITLE
Dying disables anti cheat

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2868]
**Mod Version**
What version of the mod are you on?
3.6-Alpha-1

**Describe the bug**
The anti cheat that activates when you use /aoa player disables when you die.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use /aoa player command to activate anti-cheat. Example: /aoa player @p skills aoa3:innervation level add 1
2. Because of #2852, you will need to leave the world and reenter it to test for this bug.
3. See that anti cheat is enabled upon rentering the world. 
4. Use /kill to defeat yourself.
5. Leave the world and reenter. Check to see if anti cheat is active.
6. See error

**Expected behavior**
Anti cheat does not disable when you die.

**Comment by EatingSilencer** [comment]
Going through an End Portal in the End also causes this issue.

**Comment by EatingSilencer** [comment]
It seems dying also disables abilities. They need to be reenabled.

**Comment by Tslat** [comment]
Unable to replicate.

See if this persists in the next version
