### ISSUE TITLE
Going through an End Portal in the End causes the game to crash

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2869]
**Mod Version**
What version of the mod are you on?
3.6-Alpha-1

**Describe the bug**
Entering through an End Portal in the End causes the game to crash.

[crash-2021-11-02_19.22.52-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/7464511/crash-2021-11-02_19.22.52-server.txt)

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter an End Portal while in the End.
2. See error

**Expected behavior**
The game does not crash.

**Comment by ddship12** [comment]
Ape Slap angry idiot
