### ISSUE TITLE
Holding 2 guns does not increase unholster time

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2875]
Holding a brace gun and a melee weapon does increase the attack speed, but when holding 2 guns at once the unholster time does not appear to change

**Comment by Tslat** [comment]
Haven't noticed that holding a gun normally doesn't increase attack speed?

**Comment by Cruuk** [comment]
I guess I wasn't clear, what I mean is that holding a melee weapon with a brace gun **slows down** the melee weapon (as it always did before), but unholstering a gun while already holding a brace gun **does not** change the unholster time (when it was increased before)

**Comment by ddship12** [comment]
Cruuk Was a Mickey mouse and like a baby and commit
