### ISSUE TITLE
Melee weapons do not work when the keybind is changed

### ISSUE THREAD

**Issue by Dontfeedthemachines** [Tslat/Advent-Of-Ascension#2882]
**Mod Version**
Version 3.3.6
**Describe the bug**
Discovered that if you change the keybind for attack, AoA melee weapons will not work (specifically greatblades, scythes, and mauls).  Regular swords work fine.  The weapon will swing and can break blocks, but will not hit entities or do damage.
**To Reproduce**
Steps to reproduce the behaviour:
1. Change attack/destroy keybind from "left click" to "right click" or any other keybind
2. Get an AoA melee weapon (greatblade, scythe, or maul)
3. Find any entity and swing at it

**Expected behavior**
You should see that the entity will not take damage/the hitbox was not affected, while the keybind is set to "right click" or any other keybind.

**Comment by Tslat** [comment]
Known issue.

Unfortunately 1.12 is now archived.
This issue has been fixed in newer AoA versions, but 1.12 will not be fixed.

Try updating to 1.16.5 :)
