### ISSUE TITLE
Flying mobs get stuck on ceilings

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2883]
**Mod Version**
3.6 alpha 1

**Describe the bug**
When non-aggroed, flying mobs fly up and down like normal, but when they come into contact with a block above them, they seem to get stuck on it indefinitely, regardless of y level. When aggroed, flying melee mobs will become unstuck, but flying ranged mobs seem to stay put, even while firing

**To Reproduce**
Have flying mobs touch the ceiling. Though, I tend to notice it more with naturally spawned mobs than manually spawned ones

**Expected behavior**
Flying mobs not getting stuck on ceilings

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/140660463-6079ef9d-5545-476c-8c40-85827f258d7a.png)
![image](https://user-images.githubusercontent.com/38159897/140660653-d678767a-1b65-4038-8678-c1d688ba2810.png)

**Comment by ddship12** [comment]
if boy was diagnosed with a rare condition one liking with one prayer and your if you don't care about his pain
