### ISSUE TITLE
specific guns not shooting

### ISSUE THREAD

**Issue by redish22** [Tslat/Advent-Of-Ascension#289]
**Mod Version**
What version of the mod are you on?
1.12.2
**Describe the bug**
can't use moon shiner or brown blaster
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...' anywhere
2. Click on '....'just right clicking to fire

**Expected behavior**
i have enough energy and metal slug for them to be use but when try to fire it, but it doesnt work in both creative and survival. other guns work  so far but not those.
**Screenshots**

**Comment by Cruuk** [comment]
For Brown Blaster, shotguns use "Spreadshot" now instead of metal slugs, try using those and see if it shoots.

For Moon Shiner, you have to hold down the fire button now to shoot it. Try holding it down and see if it fires after a bit.

**Comment by Tslat** [comment]
Please confirm the above response doesn't solve your issue...

**Comment by redish22** [comment]
thank you.. whats is the recipe for spreadshot ?
