### ISSUE TITLE
Mechbot's boss bar does not work at all

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2894]
**Mod Version**
What version of the mod are you on?
3.6-Alpha-2

**Describe the bug**
When you damage Mechbot, the boss bar does not change, no matter how much damage you do, until you defeat the boss.

**To Reproduce**
Steps to reproduce the behaviour:
1. Do damage to Mechbot. Do at least enough for it to be immediately recognizable on the boss bar.
2. See error

**Expected behavior**
The boss bar functions as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/142465296-b097b4f5-627e-4591-9c62-2319cab896bd.png)

**Comment by EatingSilencer** [comment]
I'll also point out that the boss bars still don't work when NoAI is enabled.

**Comment by Tslat** [comment]
Unable to replicate
