### ISSUE TITLE
Candy Hills generate in Deeplands dimension

### ISSUE THREAD

**Issue by Coolkc456** [Tslat/Advent-Of-Ascension#2897]
**Mod Version**
1.16.5-forge-36.2.8

**Describe the bug**
Candy Hills biome from Candyland generated in the Deeplands dimension resulting in candy mobs to spawn.

**Screenshots**
![image](https://user-images.githubusercontent.com/19354446/142802256-00bf5a72-9b17-428c-8b7a-d5e93545f0aa.png)

**Comment by EatingSilencer** [comment]
This is probably a problem on your end. Some kind of conflict.

**Comment by Tslat** [comment]
Yeah this is an issue with your modpack, not AoA
