### ISSUE TITLE
Unknown entity killing player

### ISSUE THREAD

**Issue by redish22** [Tslat/Advent-Of-Ascension#290]
**Mod Version**
What version of the mod are you on?
1.12.2
**Describe the bug**
something keeps killing me in the overworld, its name is unknown. 
can't be seen or attack only heard, it attacks out of nowhere sometimes leaving player blind. have tried to use a damage indicator to see if its there and it doesn't work. when i die  the world says i was killed by "unknown"
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'this thing appears anywhere, in the forest, savana, plains, and caves so far. not as frequent as other mobs but still there. 
2.  since the start of the world it is present. i got killed by it when i hadn't even gotten wood.
3. Scroll down to 

**Expected behavior**
is this normal, if so its pretty op for the overworld.
**Screenshots**

**Comment by Tslat** [comment]
It's a known bug in SNAPSHOT 10, has been fixed since
