### ISSUE TITLE
Crash related to Wither's projectiles

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2907]
Unsure if it's related to the mod, but I guess it doesn't hurt to check. I was in the Overworld, with mobgriefing turned off. If the Wither fires a skull, and you switch to peaceful, Wither despawns, but the skull doesn't, and as soon as the skull hits a block, it crashes. https://paste.gg/p/anonymous/eff1e55f115b4f8a80c3c96ee5874949

**Comment by Tslat** [comment]
Interesting
looks to be a forge bug

That event outright shouldn't fire with a null entity, because the whole event is predicated on the entity
