### ISSUE TITLE
visual mob bug in multiplayer 

### ISSUE THREAD

**Issue by redish22** [Tslat/Advent-Of-Ascension#291]
**Mod Version**
What version of the mod are you on?
1.12.2
**Describe the bug**
i have been playing with a group of friends and when we are fighting mobs, we all see different entity. for aoa mobs only. i can see a sphynx while someone sees a tree spirit. or when my friends can see clown in a cave, i am unable to see it. and when it shoots i see a white block going my way and i take damage.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'it is random for all of us.
2. Click on 'alway on with rare chance that we see the same thing.

**Expected behavior**

**Screenshots**

**Comment by Tslat** [comment]
Known bug in SNAPSHOT 10, has been fixed since
