### ISSUE TITLE
Remove Jewelyte

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2910]
It has a very similar color to Gemenyte, and is used in the exact same recipes as Gemenyte- besides the mineral block. At least Ornamyte makes itself distinct by being a different color and having different recipes. Even Gemenyte is used in extra trades. This makes Jewelyte the most useless of the bunch. If it's removed, additional Gemenyte or any other item can simply take its place in its recipes

**Comment by EatingSilencer** [comment]
Maybe Jewelyte can be kept as an emerald like ore in a future expansion of creeponia? This is a discussion we could probably have closer to the dimension update.

**Comment by Cruuk** [comment]
> Maybe Jewelyte can be kept as an emerald like ore in a future expansion of creeponia? This is a discussion we could probably have closer to the dimension update.

Or have Ornamyte/Gemenyte do that instead
