### ISSUE TITLE
(don't know if this is a bug, or just my version, asking to check) Naturally spawned hunters aggro

### ISSUE THREAD

**Issue by dorbsymaya** [Tslat/Advent-Of-Ascension#2913]
So I read on the wiki that if a naturally spawned hunter mob is a higher hunter lvl than the player, they won't be aggressive. For me, at least, they're being aggressive. Im on version 2.4 it looks like, am I just using too early a version, or is there an actual problem?

**Comment by Tslat** [comment]
Version 2.4 is ridiculously old, the wiki definitely doesn't support it.

Update to 3.5.4
