### ISSUE TITLE
server side crash while loading

### ISSUE THREAD

**Issue by Mikecolle** [Tslat/Advent-Of-Ascension#2915]
when using this mod with the latest forge 36.2.20 it will crash aon server side while attempting to load, does not generate a crash report, works fine on client side

**Comment by EatingSilencer** [comment]
Post your latest.log file from when you try to join the server.

**Comment by Mikecolle** [comment]
its not when trying to join a server its when trying to launch the server. would you like it in txt format, pasted as a comment or opaste since pastebin says its too long

**Comment by Mikecolle** [comment]
https://0bin.net/paste/fLHe3foe#yA4SUEdmF7qhewixB8UXlE1QVCpAqt1kLPXimZX4nUg

**Comment by Tslat** [comment]
Duplicate of #2914
