### ISSUE TITLE
[Feature] Mob Spawn Rate Config

### ISSUE THREAD

**Issue by GWSheridan** [Tslat/Advent-Of-Ascension#292]
Would like a config adding that allows the control of spawns rates of every mob or just control of overworld mob spawns 

As of at the moment day 1 spawning is a bit out of control to the older version of this mod. Every turn theres packs of mobs

Other than that i have no other issues with the mod its coming along great keep up the good work

**Comment by Tslat** [comment]
This shouldn't be a problem as of 3.2
