### ISSUE TITLE
Bugs related to boats and big swords and balance collapse class attacks using them.

### ISSUE THREAD

**Issue by hearts21** [Tslat/Advent-Of-Ascension#2922]
**Mod Version**
1.12.2 latest and 1.16.5 latest
**Describe the bug**
If you hold a big sword in a boat and move forward, you will be able to use a charge attack without charging.
In addition, the Crystal Great Sword penetrates invincible time, so if you use the Boat Bug with the Crystal Great Sword, you will be able to fire 20 to 25 damage in rapid succession.
In the meantime, I'll give you a video of a reenactment.(The video uses a continuous hitting tool.)
**To Reproduce**
Steps to reproduce the behaviour:
Ah ... I was Japanese so I didn't really understand this (´ ・ ω ・ ｀)
**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/77272892/146663034-c26b7fee-620d-4fc0-887f-70bb301201ea.mp4

**Comment by Tslat** [comment]
Does this work with vanilla swords too?

**Comment by hearts21** [comment]
With a vanilla sword, you cannot attack while the boat is moving. This also applies to ordinary swords that are not AoA's big swords.

**Comment by Tslat** [comment]
Have you tried it in the 3.6 alpha?

**Comment by hearts21** [comment]
No, I haven't. excuse me
