### ISSUE TITLE
Runandor Portal not bringing me back to the overworld

### ISSUE THREAD

**Issue by Sarus-X** [Tslat/Advent-Of-Ascension#2923]
Latest 1.12.2 Version (3.3.6)

Runandor portal keeps spawning me in a random location in Mysterium instead of bringing me back to my portal in the overworld (It thinks Mysterium is the portal spawn still from previous versions)

To reproduce this issue, just go through the Portal from the overworld using the Runandor portal stone and going through it from Runandor to overworld brings you to the Mysterium every time.

Using the portal stone, I expect this to bring you back to the overworld, where the portal I came from is at.

This is where it keeps bringing me, even after destroying the Runandor portal in mysterium. (it generates a new portal)
![2021-12-19_19 14 16](https://user-images.githubusercontent.com/69871300/146696057-e7083671-b0fb-4d5b-9a7b-6c6b36f11eec.png)

This is where it should be bringing me.
![2021-12-19_19 17 54](https://user-images.githubusercontent.com/69871300/146696068-34bd4f9f-74a6-4933-9bd9-b9cc776b0b9f.png)

**Comment by EatingSilencer** [comment]
Does this issue occur in the latest 1.16.5 version (3.5.4 or 3.6-Alpha-2)? Any bugs in 1.12.2 will not be fixed, but if the bug can be reproduced in one of the two versions I mentioned, then the dev can look into it.
