### ISSUE TITLE
Crash with new version of thermal

### ISSUE THREAD

**Issue by Inverseder** [Tslat/Advent-Of-Ascension#2925]
**Mod Version**
Advent of ascension: 3.5.4 and forge 36.2.22 on 1.16.5

**Describe the bug**
I play with the latest version of thermal expansion (1.4.1.3), foundation (5-1.4.1.7), cultivation (5-1.4.1.3), innovation (5-1.4.1.3), locomotion (1.4.1.2) and Cofhcore (1.4.0.6). when i start a world, my game crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to singleplayer
2. Click on a world or create a world and start it
4. it crash when I create a new world. When I load a world it show: "Erros in curently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe-mode"). or go back to the title screen and fix it manually."

**Expected behavior**
I don't know if it's thermal or advent who causes the crash.

**Screenshots**
Here the crash report: https://pastebin.com/QGSKUb61

**Comment by Tslat** [comment]
Yeah something seems to have happened with their recipes which makes the ones in aoa incompatible
It's known and will be fixed

**Comment by AsheX1** [comment]
this is not only a single player server thing same thing on a server this fix for now even what CoFH team says to downgrade back down to 1.3.0 of thermal  mods

**Comment by AsheX1** [comment]
i have no idea if it still crash's on the  3.6 alpha

**Comment by Tslat** [comment]
Yeah thermal changed their code and removed support for some json stuff they had in the past
if they don't fix it, I will in the next update
