### ISSUE TITLE
Throwables (grenades, slicing stars...) and weapons that use them like canons don't work

### ISSUE THREAD

**Issue by SaphiraxYtb** [Tslat/Advent-Of-Ascension#2926]
**Mod Version**
AoA 3.5.4 for Minecraft 1.16.5 , Forge : 36.2.22

**Describe the bug**
This bug happens on our multiplayer server, throwables and weapons using them do work like intended in singleplayer. Other mods installed : optifine - Tinker's construct - mantle - twilight forest - botania - curios api - appleskin - antique atlas - cloth config - gravestone mod - waystones - antique waystones - just enough items - patchouli - storage drawers - psi

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to minecraft froge modded server
2. Right click on the grenade/throwable/canon...
3. Nothing happens, the item isn't thrown or consumed

**Expected behavior**
As intended, it should throw or launch the item

**Comment by Tslat** [comment]
Fixed in next version

**Comment by SaphiraxYtb** [comment]
ok thank you
