### ISSUE TITLE
Cannot throw throwable weapons in survival

### ISSUE THREAD

**Issue by MurkyConspiracy** [Tslat/Advent-Of-Ascension#2927]
**Mod Version**
Advent of Ascension (Nevermine) 3.5.4

**Describe the bug**
Throw-able weapons only work in creative mode in both single player and on servers while using a combinations of mods. (Not Midnight). 

I enabled verbose logging in hopes of seeing if some events weren't firing properly; however, these events do not show in the logs. The latest logging file is attached. You can see I gave myself a Runic Bomb and tried to use it, no dice. I set my Game-mode to creative and could throw it just fine.

**To Reproduce**
I will be trying to test what interactions is causing this in hope of providing further information tomorrow. I have to assume this is a mod interaction issue as it works with the mod installed alone. I will update the issue here tomorrow once I have figured out what mods might be causing it. (I have also attached the mod list and export pack for reference).

**Expected behavior**
When using RMB a thrown weapon should be used in survival.

[WorldWideWack-v1.3.zip](https://github.com/Tslat/Advent-Of-Ascension/files/7782995/WorldWideWack-v1.3.zip)
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/7782997/latest.log)
[modlist.zip](https://github.com/Tslat/Advent-Of-Ascension/files/7783005/modlist.zip)

**Comment by Tslat** [comment]
Known, fixed in next version
