### ISSUE TITLE
Crash upon starting due to IC2C compatability

### ISSUE THREAD

**Issue by ArsaiGit** [Tslat/Advent-Of-Ascension#2929]
**Mod Version**
Mod version: 3.3.6 for MC 1.12.2

**Describe the bug**
Upon loading up, the game crashes. From what I can gather from the log (see below), it seems to be due to a issue with the IC2 integration. I'm using (among other mods) IC2 Classic instead of 'normal' IC2, so perhaps that's the Issue?

**To Reproduce**
If IC2 Classic is loaded alongside AoA, the game crashes upon entering mod initialization. Disabling the IC2 integration in the config files gets rid of the problem, but this does not seem like the ideal solution

**Crash Log**
[crash-2021-12-28_20.32.05-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/7786133/crash-2021-12-28_20.32.05-client.txt)

P.S. I'm new to writing GitHub issues, so please let me know if there is anything I missed or should have done differently

**Comment by Tslat** [comment]
Yes it's due to you using IC2 classic
They use the same mod id but have different code, so it causes crashes

**Comment by ArsaiGit** [comment]
Alright thank you for letting me know.
