### ISSUE TITLE
Long Shot buff

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#293]
**Describe/name the item/content this suggestion relates to**
The blue gun that drops from Rockrider at a 25% chance, not affected by looting enchantments.

**Describe the change/balance you think would be good to see**
Long Shot... It has always existed.
I mean it's pretty self-explanatory, up to 20 base damage and 13.2 DPS isn't too great for a Shotgun, especially if it's a boss drop. You also have better alternatives for shotguns in the same dimension (Haven), those alternatives being Purple Punisher (lotto item) and Red Rocket (dropped by 4 Guardians).

All it needs is just a damage increase and fire rate increase, always imagined it as being pretty speedy like 1.0 fire rate... usual stuff.

**Include any additional background information**
I think this'll be the last balance post I make before 3.0 releases. donkey kong

**Comment by Sagisolar** [comment]
It should also have bonus damage to long range hits.
Thus the name "Long Shot"

**Comment by Tslat** [comment]
3.2 Did things
