### ISSUE TITLE
Server bat/cmd crash for the Ticking entity bug

### ISSUE THREAD

**Issue by ITSGuberti82** [Tslat/Advent-Of-Ascension#2930]
**Mod Version**
AoA 3-3.5-1.16.5

**Describe the bug**
Created server with the old system. A simple server running with bat/cmd files, where i put the AoA mod and other 5 mods. Everything works fine but sometimes, after 15/20 mins in the game, the server crash with a log error. After reading it i figured out what cause the crash. It's the "Ticking entity", where minecraft vannilla's zombies after spawned they made the server crashing cause they conflict with some mod's mob. Tried so many ways to avoid the crash, like overwrinting the "forge server " txt file inside the world server folder, but some of the changes reset after starting the server. Installed the "cofh-core" mod to kill all zombies but they respawn, so it's basically useless.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'minecraft server folder'
2. Click on 'starting_server.bat'
3. plays for like 15/20 mins
4. See error in the "crash report" folder

**Screenshots**
[crash-2021-12-30_22.48.29-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/7794717/crash-2021-12-30_22.48.29-server.txt)

**Comment by Tslat** [comment]
Why are you using 3.5?
Update to 3.5.4
