### ISSUE TITLE
Hauling Bobber Glitch

### ISSUE THREAD

**Issue by envoidia** [Tslat/Advent-Of-Ascension#2936]
**Mod Version**
3.6 Alpha 3

**Describe the bug**
Fishing rod reel glitching out when you swap items around

**To Reproduce**
1. Hold a vanilla fishing rod
2. Cast out the rod
3. Swap the item that's in the slot you're holding with one of the AoA rods
4. The lure will not go away, it will still follow you, and the only way to make it go away is to stop holding any fishing rod (switching to holding a different rod will not work) or to go back to the vanilla one and reel it in. You will not be able to cast out another.

**Expected behavior**
I expected the lure to vanish when I swapped out the item.

**Comment by Tslat** [comment]
This is actually a vanilla bug
I've patched it so casting with another rod deletes the vanilla lure so it doesn't just get stuck, but that's about as much as I can do I think
