### ISSUE TITLE
java.lang.NoSuchFieldError: OxStorageModuleT2

### ISSUE THREAD

**Issue by AnimalLover567** [Tslat/Advent-Of-Ascension#294]
**Mod Version**
AoA-Tslat 1.1.3

**Describe the bug**
When loading forge on 1.7.10 minecraft crashes with NoSuchFieldError: OxStorageModuleT2, it doesn't sound like anything from your mod but crash report has UCE next to your mod, is your mod by any chance incompatible with Galaiticraft? If not then what's going on? 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by Sagisolar** [comment]
You should post a crashlog to help Scimi.

**Comment by AnimalLover567** [comment]
EDIT: nvm i think it was galaxy additions
