### ISSUE TITLE
Farming skill abuse.

### ISSUE THREAD

**Issue by Skyine918** [Tslat/Advent-Of-Ascension#296]
**Mod Version**
1.1.3 [Minecraft 1.7.10]
**Describe the bug**
Farming skill abuse. 

**To Reproduce**
Steps to reproduce the behaviour:
Just plant seeds and break them instantly (you can hold both mouse buttons). 

![2019-02-13_15 05 48](https://user-images.githubusercontent.com/35529938/52710760-319b1d00-2fa1-11e9-8786-9b679784a67d.png)

**Expected behavior**
You will get light blue crystals, despite it has not grown.

**Comment by Flamebom** [comment]
Sure it works, but at higher levels it doesn't really do that much. It doesn't give enough for the time its worth.
I even scripted it and let go on for 2 hours didn't push anima that high

**Comment by Flamebom** [comment]
Maybe add diminishing returns for different crops?  It'll make it much harder to farm

**Comment by Skyine918** [comment]
I don't know whether it will be better or even possible if we are talking about codding, but I think it would be correct if blue crystals would only drops from mature plants, because this is the only way we "create" something new. So, maybe, it will be even easier to implement.

**Comment by Tslat** [comment]
Support for 1.7.10 has been dropped
