### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by CanBoy67** [Tslat/Advent-Of-Ascension#2969]
**Mod Version**
3.5.4

**Describe the bug**
Whenever I create a world with this mod installed the game crashes with java.lang.IndexOutOfBoundsException: Index: 0, Size: 0, and I'm fairly certain it's this mod as when I disable it the world loads normally

**To Reproduce**
Steps to reproduce the behaviour:
1. Create World
2. Wait for load
3. Crashes with the aforementioned error

**Expected behavior**
The world to load normally

Crashlog: [https://pastebin.com/hS3V2Nec](https://pastebin.com/hS3V2Nec)

**Screenshots**

**Comment by Tslat** [comment]
Known bug, fixed in next version
