### ISSUE TITLE
Auto trashing UI issues

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2982]
A. It's finicky, I've figured out how to click on stuff just fine. But when it comes to removing things, I was able to do it with some jank, but now I can't remove an item from the UI for some reason.

B. The actual trashing function doesn't work, at least when I try to throw things out og my inv and pick it up

**Comment by Tslat** [comment]
A looks to be a forge bug, use a newer version of forge
B isn't how it works
