### ISSUE TITLE
Extraction's auto unbreak/fortune doesn't work with items that can't get fortune (weapons, armor, etc.)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#2983]
Title. I assume it checks to see if an item is compatible with both, and doesn't work if an item only works with 1 of them. In that case, I don't know if it's intended or not, so I'm just checking (would like free unbreak on weapons/armor haha)

**Comment by Tslat** [comment]
That's how it's meant to work
