### ISSUE TITLE
Blast Barrel Nerf

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#299]
**Describe/name the item/content this suggestion relates to**
Blast Barrel is ridiculously powerful for a weapon from Crystevia. It has the highest DPS of all Shotguns. Which is crazy because that means it outclasses the Amplifier, a weapon from the Shyrelands.
Just look at this.
![dadada](https://user-images.githubusercontent.com/44548547/52885593-a751e500-3169-11e9-92a0-455988270c56.png)

![qdadaa](https://user-images.githubusercontent.com/44548547/52885600-ac169900-3169-11e9-9309-9e38f7055645.png)
Sure its faster but that doesn't mean much when the Blast Barrel does way more damage per bullet. Oh and it has strong knockback as well, just the icing on the cake.

**Describe the change/balance you think would be good to see**
I wouldn't mind keeping the knockback since it has "Blast" in the name. But the damage output needs a nerf. Probably in the range of 6 to 9 damage per bullet. Maybe the firing rate can be toned down slightly as well.

**Comment by Tslat** [comment]
3.2 Did things
