### ISSUE TITLE
Weird bug with skill armor

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#300]
**Mod Version**
AoA3 snapshot 10

**Describe the bug**
After quickly leveling skills with giant skill crystals, I got Anima to 100 and got Anima armor and quickly put it on while in Creative (was looking at durability of stuff). But as soon as I switched to survival the armor popped off of me, but I still had the protection. When I get hit more copies of the armor appear in my inventory. If I attempt to scroll over them in the hotbar they get away from the currently selected slot. I can't put the pieces on since I technically already have it on? (but invisible)

Logging off and ./killing didn't fix it since I was wearing it. Though it seems I can still interact with the invisible pieces and take them off. Though going in creative and pressing the red x button doesn't delete them, I had to manually drop them to get rid of them. But it seems even when I spawn new ones the bug still happens? Even after I log off and ./kill again.

**To Reproduce**
Steps to reproduce the behaviour:
Get to level 100 in a skill fast (I did Anima), and quickly(?) put on a set of the corresponding skill armor, not sure if you have to be quick but I put mine on before the level 100 fanfare played.
As far as I know this all that causes the weird stuff with the copies and invisible armor, as explained before.

**Expected behavior**
I just wanted to put the armor on and nothing else man.

**Screenshots**
I think a video would help more.
https://youtu.be/u5CTTE8PMsM

Not sure if this has been already reported but just in case.
Hopefully this doesn't delay 3.0 lol

**Comment by EatingSilencer** [comment]
I think the issue here with the armor popping off is client-side, because the same thing happens with extraction tools. The tool/armor piece might be considered in your hand/on your body to the server, but the client thinks otherwise. 

As for the duplication, have you tried opening your inventory and grabbing one of the duplicating pieces? There is a possibility that it might be this bug: https://github.com/Tslat/Advent-Of-Ascension/issues/194.

**Comment by Tslat** [comment]
Does it happen when you have no other mods on?

**Comment by Cruuk** [comment]
Removed all mods except AoA and made a new world. Trained Anima to 100, put the armor on and the same bug still occurred.

Even more interestingly enough, with the armor on I had a Cyclops hit me, and instead of the armor pieces cloning, the game crashed!
https://pastebin.com/mcV1MZcj

**Comment by Tslat** [comment]
Fixed
