### ISSUE TITLE
QoL changes for Extraction harvest speed boost ability

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3001]
I know you can just toggle the whole thing off, but it'd be annoying to constantly turn it on/off when I flip flop between combat and mining. I would like the ability to be the best it can be

1: Allow the player to turn it off if they press v while mining a block again. This is the largest problem, you can screw over your energy as you cannot turn it off once active. Activating the ability is very sensitive, even if you tap a block very lightly

2: Prevent the ability from activating if you're hitting unbreakable blocks (bedrock, being in Nowhere, etc.)

3: Decrease the sensitivity for block-breaking. By just a tiny bit, at least to a point where you have to hit the block for like 0.5 seconds longer. Or maybe it could be activated by breaking a block while holding v instead. Don't know

**Comment by Tslat** [comment]
I'm not sure I understand both 1 and 3
It only activates if you're mining and press the action key. What about that is 'sensitive'?

**Comment by Cruuk** [comment]
> I'm not sure I understand both 1 and 3 It only activates if you're mining and press the action key. What about that is 'sensitive'?

Sensitive as in the threshold for activating is very tiny. Even if I start breaking Obsidian with my hand for 0.1 seconds and press v, it will activate it. To me, this translates into possibly activating during combat if I just accidentally tap a block while hitting stuff and pressing v for other stuff, which can cause problems if I need the energy. Again I know I can just turn the whole thing off, but I don't want to leave it at that, especially if something attacks me while mining and I have to very quickly turn it off in the GUI

**Comment by Tslat** [comment]
ehh. how about we see if it actually comes up, rather than hypothesizing

**Comment by Cruuk** [comment]
We shall see.......
