### ISSUE TITLE
Chum burger/Chum and Salad burger are crazy

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3006]
These foods reach almost Candy blade levels of hunger, while also being obtainable much more earlier, are relatively easy to make, and the Nausea they give only lasts 5 seconds, making it barely noticeable. They are definitely overtuned

**Comment by Tslat** [comment]
Are they though?

Chum burger requires a meat, with an extra processing step which consumes an item's durability, plus a whole other food (bread) to make, and it only gives slightly more than steak, whilst also giving you brief nausea

Chum and salad burger _does_ have a decent jump on top of steak, but it requires the meat, as well as 2 bread, and both a carrot and potato, requiring 3 separate farms & consuming effectively 5 food to make one item, whilst also giving brief nausea and no further effects

**Comment by Cruuk** [comment]
> Are they though?
> 
> Chum burger requires a meat, with an extra processing step which consumes an item's durability, plus a whole other food (bread) to make, and it only gives slightly more than steak, whilst also giving you brief nausea
> 
> Chum and salad burger _does_ have a decent jump on top of steak, but it requires the meat, as well as 2 bread, and both a carrot and potato, requiring 3 separate farms & consuming effectively 5 food to make one item, whilst also giving brief nausea and no further effects

Chum can be obtained in other ways, but I suppose. I did fail to realize that you probably wanted it to be worthwhile compared to something like 2 cooked Potatoes. The burgers had me fixated on them as very unexpected additions, but I like them
