### ISSUE TITLE
Mobs changing models every time I restart the server

### ISSUE THREAD

**Issue by Crix310** [Tslat/Advent-Of-Ascension#301]
**Mod Version**
AOA3 Snapshot 10

**Describe the bug**
I recently bought a gamehosting server because I want to play with my friends on a modpack. In this modpack we included AoA3 Snapshot 10 which caused various problems for us.
I've noticed that every time I restart server for accidental errors, the mobs spawn with other models, but their abilities are the same. For example, I restart the server once, and a Tree Spirit spawn with a Sand Giant model, or when I've tried to spawn the Smash for verification it spawns with a Charger model.
Rarely the mobs spawns with their correct models
Please solve this problem ASAP, please. And sorry for bad english. I'm italian

**To Reproduce**
I don't know how to reproduce this error in a singleplayer world.

**Expected behavior**
N/A

**Screenshots**
I haven't any screenshot or video, sorry.

**Comment by TekterBR** [comment]
Looks like the mod is very problematic on servers

**Comment by Cruuk** [comment]
This is a known issue and should be fixed on release.

**Comment by Crix310** [comment]
> This is a known issue and should be fixed on release.

in 3.0 this will be fixed?

**Comment by EatingSilencer** [comment]
> 
> 
> > This is a known issue and should be fixed on release.
> 
> in 3.0 this will be fixed?

I think so.

**Comment by Tslat** [comment]
Known bug on servers, has been fixed in 3.0
