### ISSUE TITLE
Unable to throw throwable weapons

### ISSUE THREAD

**Issue by blueassasin007** [Tslat/Advent-Of-Ascension#3010]
**Mod Version**
1.16.5

**Describe the bug**
I am unable to throw throwable weapons even while right-clicking (use)
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any merchant which sells throwables 
2. Trade to get a throwable weapon
3. Right click to throw weapon
4. You are unable to throw the weapon

**Expected behavior**
Expected the throwable weapon to be thrown at enemies.

**Screenshots**
Unable to screenshot.

**Comment by Tslat** [comment]
Come to the discord server for a fix.
