### ISSUE TITLE
Crash when trying to take ingot from oven. 1.16.5 3.6-Alpha

### ISSUE THREAD

**Issue by AntonIXO** [Tslat/Advent-Of-Ascension#3018]
Crash when trying to take ingot from oven.

Minecraft: 1.16.5
Mod version: 1.16.5 3.6-Alpha
No other mods installed except optifine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get oven 
2. Melt gold ore.
3. Try to take ingot from oven
4. Crash

Problem in: Cannot invoke "net.tslat.aoa3.player.ServerPlayerDataManager.player()" because "this.playerDataManager" is null

Full Minecraft Crash Log: https://pastebin.com/4M6EHBT1

This is happens on server and in single player

**Comment by Tslat** [comment]
Known and fixed

**Comment by AntonIXO** [comment]
But if it fixed why this bug happens to me?

**Comment by Tslat** [comment]
Because it's not fixed in the version you have
Feel free to join the discord server for more info :)
