### ISSUE TITLE
Give Destructor all attribute icons

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#302]
**Describe/name the existing feature this suggestion relates to**
Destructor and attribute icons

**Describe the change or feature you think would be good to see**
Basically I think Destructor should have all the attribute icons (except the hunter one for obvious reasons). It is already invincible yes, but this would mainly be a cosmetic change that makes it easier for newer players to know it's invincible without having to look at the wiki and/or get up close and personal with it and die.

**Comment by Tslat** [comment]
Handled in 3.0
