### ISSUE TITLE
Reintroduce Mining Traps (edited)

### ISSUE THREAD

**Issue by HyDefier** [Tslat/Advent-Of-Ascension#3023]
(edited multiple times)

Introduction:
Previously, mining a block in the ceiling of the Deeplands had a chance to spawn a shik, cause an explosion, place a lava, or spawn multiple shiks iirc. In the current version, there is only a chance of a shik spawning. I think reintroducing some randomness and essentially jump scares should be considered as it has made mining in the Deeplands something of an adrenaline rush in the past; however, this does not need to be implemented the same way, or even in the Deeplands.

Idea 1:
it could be introduced in any other dimension where it fits thematically with just minor reworks and polishing compared to the previous system. (A brief cue before an explosion trap would be an example of a useful polishing change)

Idea 2:
It could be implemented with the new foraging (assuming it still fits) as a mode which can be activated as a "high risk high reward" mode. This would make it so traps would be able to activate on blocks where foraging is trained, but they would be completely random, and not affect the cadence of the xp or gift dropping process; however, they would improve gifts. This solution would make the traps fair and expected, but still random.

Motivation:
The old traps system provided an engaging and challenging gameplay experience that was especially well suited for mining with friends. I remember really enjoying shaft mining with a friend acting as support. They were always at the ready with torches, a bucket, weapons, extra food, etc. We were also able to trade places to heal up. We choose to mine more than was required in the Deeplands because mining was dangerous, interesting, and just downright fun. I think something similar to this would still be a great fit for AoA, possibly more singleplayer friendly (idk).

**Comment by Cruuk** [comment]
No thanks, would rather have a well-designed mod than do crappy fake "difficulty" for the sake of shoehorned dopamine. Stuff that was removed for a reason don't tend to get added back in

**Comment by profilename14** [comment]
Those things were unfortunately removed for a reason, they made mining in the deeplands insufferable over the long term with unavoidable traps that lacked any cue. I feel like, for a dimension with a focus on underground and mining, deeplands has much more potential than something as basic and unfun over the long term as that, like unique cave generation, treasures, and perhaps avoidable threats like burrowing enemies (just as some random examples) to make it a unique experience from other dimensions. I'm sure Tslat has ideas planned to add some more dimensionality to mining in the deeplands without making it unfair or boring.

**Comment by HyDefier** [comment]
> Those things were unfortunately removed for a reason, they made mining in the deeplands insufferable over the long term with unavoidable traps that lacked any cue. I feel like, for a dimension with a focus on underground and mining, deeplands has much more potential than something as basic and unfun over the long term as that, like unique cave generation, treasures, and perhaps avoidable threats like burrowing enemies (just as some random examples) to make it a unique experience from other dimensions. I'm sure Tslat has ideas planned to add some more dimensionality to mining in the deeplands without making it unfair or boring.

Great comment, and you make a very good point. I'm going to edit this issue to request the feature somewhere it fits better thematically. The Deeplands are not necessarily the best place for unfair traps, but I consider them an interesting and worthwhile gameplay element nonetheless.

**Comment by Cruuk** [comment]
No good reason has been given for re-intoducing the traps beyond saying they were "unique" or "worthwhile", which on their own aren't enough. Need better gameplay reasons. Too many suggestions used the word "unique" and nothing else

**Comment by HyDefier** [comment]
> No good reason has been given for re-intoducing the traps beyond saying they were "unique" or "worthwhile", which on their own aren't enough. Need better gameplay reasons. Too many suggestions used the word "unique" and nothing else

Thanks that's a good point. I really haven't provided a proper reason for re-introduction. I have some more edits I'm gonna make.

**Comment by Tslat** [comment]
From a design standpoint, this is just a terrible idea
The only way to make this work in a reasonable manner is to have the traps be actual blocks that you can identify up close so that the player has a chance to defend/prevent the problem.
At that point however, it's an entirely different topic & suggestion

I will __not__ be reintroducing randomly trapped stone
