### ISSUE TITLE
Pressing escape in JEI closes Advent GUI while leaving the Auto Harvesting Trash GUI open.

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#3025]
**Mod Version**
What version of the mod are you on?
3.6-Alpha-4

**Describe the bug**
Normally, when you open the Auto Harvesting Trash GUI, pressing Esc or selecting an item/empty slot takes you back to the Advent GUI screen. If you try to interact with JEI by checking recipes, then press Esc, it will close the Advent GUI while leaving the Auto Harvesting Trash GUI open.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure to have JEI installed and have the JEI menu be open.
2. Open the Auto Harvesting Trash GUI.
3. Click on a block/item in JEI to see its recipe.
4. Press Esc
5. See error
6. Press Esc again to see you back outside of the Advent GUI.

**Expected behavior**
Pressing Esc in a JEI recipe page when the Auto Harvesting Trash GUI is open doesn't close the Advent GUI.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/154874092-d5c4d362-da5b-4244-8634-2427567bf674.png)

**Comment by Tslat** [comment]
There's really not much I can do about this tbh
It's just how JEI interfaces with the stacking gui system
it's not even really a functional issue as far as I can tell
