### ISSUE TITLE
No iro crates spawn in dungeons in Iromine 

### ISSUE THREAD

**Issue by ARaffler** [Tslat/Advent-Of-Ascension#3027]
As mentioned in the neweset alpha of AoA no iro crates spawn in the dungeons. Im not sure whether its intended or not but thought ill report it.

**Comment by EatingSilencer** [comment]
Do you mean they don't spawn in the chests or don't spawn in the structure? The former is a bug, the latter is intentional.

**Comment by ARaffler** [comment]
They dont spawn in loot chests either, didnt know they are Not supposed to spawn in the structures anymore.
