### ISSUE TITLE
Pixons turning invisible with Fancy Block Particles mod. (1.12.2)

### ISSUE THREAD

**Issue by DTA2YT** [Tslat/Advent-Of-Ascension#3030]
Mod Version:
1.12.2 [AoA3-3.3.6]

Whenever I add the **_Fancy Block Particles_** mod the Pixons become invisible as seen by the image below

![Screenshot_1](https://user-images.githubusercontent.com/101235272/157368640-720c7d39-3add-435e-9277-a55138ba1225.png)

I'm trying to make a pack of mods to review individually altogether for videos.

**Comment by Tslat** [comment]
Given that pixons do nothing but spawn normal, vanilla particles with a colour applied

This isn't really something that's a problem on AoA's side.
Maybe take this to the mod that breaks particles

Also, we no longer support 1.12. Move to a modern mc version if you want active support & updates
