### ISSUE TITLE
Application for Commercial Licensing about AoA3

### ISSUE THREAD

**Issue by qq482047286** [Tslat/Advent-Of-Ascension#3031]
Good morning，Tslat
I want to apply for the commercial use right of this module in minecraft zone of NetEase, but I don't know how to describe it in detail. Do you have the authorized template? I'm LingYun Studio(凌云工作室）, 

Thank you very much!

**Comment by Tslat** [comment]
Come talk to me on the official Discord.
https://discord.gg/DNYqNNq
