### ISSUE TITLE
Extraction Device Doesnt Work

### ISSUE THREAD

**Issue by puvx** [Tslat/Advent-Of-Ascension#3039]
**Mod Version**
What version of the mod are you on?
AoA3-1.16.5-3.6-Public Alpha
**Describe the bug**
When I fill the extraction device with lava and right click it with a stone bowl, it doesn't work.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Nether
2. Put extraction device one block above an air block
3. Fill bucket with lava
4. Put lava on top of extraction device
5. Right click with stone bowl
6. It doesn't work

**Expected behavior**
It's supposed to remove the lava and have a chance to give you an item

**Screenshots**
https://ibb.co/1r539Rf

**Comment by EatingSilencer** [comment]
This is not how Extraction is trained anymore.
