### ISSUE TITLE
Gun/blaster sprinting thing (is it intended)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3041]
If you sprint then start firing a gun/shotgun/sniper/Blaster, you are able to fire while sprinting.

However, if you fire before, you cannot sprint until you stop firing. If you were sprinting while firing, and you stopped sprinting during that, then you can't sprint again until you stop firing

Just want to be sure if this is intended

**Comment by Tslat** [comment]
Not intended, but is an artifact of how vanilla does things
Without getting invasive I can't fix this, so it's staying as-is
