### ISSUE TITLE
Mob Battle thingy

### ISSUE THREAD

**Issue by Voidros** [Tslat/Advent-Of-Ascension#3047]
What I'm thinking of is an item that allows 2 mobs to fight each other. You could hit the first mob (no damage) and then the second mob (also no damage) to make them aggro on each other.

Maybe right-click instead of left-click could work as well.

**Comment by Tslat** [comment]
Isn't there already mods that do this though?

**Comment by Voidros** [comment]
Yes, but I don't want to add more mods than I need to for data basically.

**Comment by Tslat** [comment]
Data?

**Comment by Cruuk** [comment]
https://www.curseforge.com/minecraft/mc-mods/mob-battle-mod Just use this mod. Not really much of a point to add features like this when other mods do them better already

**Comment by Golden-Extreme** [comment]
Perhaps addition of a third-party integration?
