### ISSUE TITLE
Quickpocket considered mob griefing

### ISSUE THREAD

**Issue by Axid-Cobravin** [Tslat/Advent-Of-Ascension#305]
Make quickpocket's ability to throw people's items on the ground considered to be mob griefing and disabled by mob griefing = false.

**Comment by Tslat** [comment]
Given that basically every single server has mobgriefing off  (for obvious reasons), this would basically render the quickpocket and silencer useless.

While I understand the sentiment, it's a bit bigger of a discussion than just this

**Comment by Axid-Cobravin** [comment]
Welp. Maybe a separate toggle for just the quickpocket ability. DoQuickpocket (true/false) similar to DoFireTrick.
