### ISSUE TITLE
Morph Mod Integration (Third-Party Mod Integration)

### ISSUE THREAD

**Issue by Golden-Extreme** [Tslat/Advent-Of-Ascension#3052]
How about adding Morph Mod integration to AoA3 mods?
With the addition of the MorphMod integration, players can transform into AoA3 mobs when they defeat AoA3 mobs. Also, after transforming into some AoA3 mobs, pressing the "V" key or attacking an enemy target can activate the unique abilities of the transformed AoA3 mobs.

**About the unique abilities of AoA3 mobs that players have transformed into:**
For example, if you press the "V" key when transforming into a Bomb Carrier, you can install a primed TNT, or if you attack the target when transforming into a king charger, you can give a weakening effect to the target.

**Third-party mods to add integration**
"https://www.curseforge.com/minecraft/mc-mods/morph"

**Comment by EatingSilencer** [comment]
Since this mod is 1.16.5 only for the time being, a morph integration cannot happen until the mod ports to 1.18.2.
