### ISSUE TITLE
Crash when loading 1.18.2 AoA

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#3055]
**Mod Version**
What version of the mod are you on?
1.18.2-3.6-Public Alpha

**Describe the bug**
Trying to load 1.18.2 AoA caused this crash:
[crash-2022-04-02_16.20.05-fml.txt](https://github.com/Tslat/Advent-Of-Ascension/files/8403324/crash-2022-04-02_16.20.05-fml.txt)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install AoA 1.18.2 as the only mod.
2. See error

**Expected behavior**
The game does not crash.

**Comment by Tslat** [comment]
I'm not currently taking reports for 1.18.2, purely because I've still got stuff to do on it and it's very likely any crashes will either be resolved by the time I'm done, or they'll be changed
