### ISSUE TITLE
Spawn Corby should have the texture as the Corby Egg

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#306]
If any of you don't remember. Before the Tslat versions Corby was the only mob with a spawn egg. It was removed as soon as Scimi started working on Aoa. Just to be a fun easter egg, I would like Corby's spawn egg to have the same texture.
![corbyegg](https://user-images.githubusercontent.com/44548547/52919847-5c1d0b00-32fe-11e9-925e-085dc64bf63e.png)

**Comment by Tslat** [comment]
I have textures for most of the spawn eggs already, but as we've discussed in discord previously, this is a much bigger issue and a single spawn egg for the sake of it isn't going to happen
