### ISSUE TITLE
Interacting with world doesn't seem to update on server

### ISSUE THREAD

**Issue by tangynacho** [Tslat/Advent-Of-Ascension#3065]
**Mod Version**
1.16.5-3.6-Public Alpha 2

**Describe the bug**
When running the mod on a Forge server on a linux machine, doing things like opening doors or breaking blocks appears to register properly on client side, but when attempting to pass through the opened door or broken block the player shakes and is unable to pass through. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Load into a server
2. Two players travel a few chunks away from each other
3. Blocks the players break start experiencing the issue
4. From that point forward any time a player loads in and moves to a point where new blocks are loaded the issue returns

**Expected behavior**
Opening doors and destroying blocks should work as intended

**Comment by Tslat** [comment]
I'm unable to replicate this - but I have fixed something that might also fix this for you anyway
Try this again in Public Alpha 3 - if it's still an issue, let me know
