### ISSUE TITLE
Allow Bayonette rifle/Nethenette rifle/Bayonette SR to gain sword enchantments

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3067]
If the sword/tool hybrids can have both sword/tool enchants, I don't see why these 3 can't have both sword/gun enchants

**Comment by Tslat** [comment]
Not really feasible without jacking into vanilla code and changing things I'm not willing to change

**Comment by Cruuk** [comment]
Oh well at least I tried
