### ISSUE TITLE
Add the mob that is originally unused: Goldface to Iromine in the future

### ISSUE THREAD

**Issue by 22zhuyansong** [Tslat/Advent-Of-Ascension#307]
**Describe the new feature you think would be good to add**
Through the biomes will be added for various dimensions, the unused mob: Goldface should be added to the new biome in Iromine: Golden Hills.

**Add any alternative implementations you think might work**
Nothing.

**Include any additional background information**
Nothing.

**Comment by Tslat** [comment]
This basically amounts to a namedrop addition - why..?
