### ISSUE TITLE
Crash when the Harvest Replant perk triggers on Thermal Cultivation 2-block plants

### ISSUE THREAD

**Issue by Chubblezap** [Tslat/Advent-Of-Ascension#3073]
**Mod Version**
3.6 Public Alpha 2 (1.16.5). Outdated, but posting anyway in case this hasn't been fixed as I can't find a changelog for Alphas 3 and 4.

**Describe the bug**
Game crashes when the Harvest Replant perk (level 49 Farming skill) triggers on a 2-block plant from Thermal Cultivation. Tested with Flax, Corn and Amaranth. Notably crashes even when not fully grown.

**To Reproduce**
Plant flax/corn/amaranth and break it in survival mode at Farming level 49 until the game crashes.

**Expected behavior**
Replanting a seed, or at least not crashing should it not be able to.

[crash-2022-04-13_03.42.18-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/8478045/crash-2022-04-13_03.42.18-server.txt)

**Comment by EatingSilencer** [comment]
Public alpha 2 is not outdated btw.
