### ISSUE TITLE
Glowing Pixons don't spawn in 1.16.5-3.6-Public Alpha 2

### ISSUE THREAD

**Issue by michalson17** [Tslat/Advent-Of-Ascension#3077]
Title. I hope I'm not just extremely unlucky or something.

**Comment by michalson17** [comment]
I didn' t see any glowing pixons in this version maybe my other mods cause it.

**Comment by Tslat** [comment]
Unable to replicate

**Comment by michalson17** [comment]
I checked this and now i have glowing pixons maybe it was a problem with a previous versions and their compatibility.
