### ISSUE TITLE
Unable to launch jar file

### ISSUE THREAD

**Issue by Conor-McNierney** [Tslat/Advent-Of-Ascension#308]
**Mod Version**
Snapshot-10

**Describe the bug**
Unable to launch jar file in any way. Using command prompt to attempt to execute the jar file reveals "no main manifest attribute, in aoa3-SNAPSHOT-10.jar" see screenshot below.

**To Reproduce**
Steps to reproduce the behaviour:
1.download file. found on curse forge(https://minecraft.curseforge.com/projects/advent-of-ascension-nevermine) or from wiki(https://adventofascension.gamepedia.com/Download)
2.attempt to launch and nothing happens, no windows pop up or error messages

**Expected behavior**
Some window to launch and run a install(I assume)

**Screenshots**
![command prompt](https://user-images.githubusercontent.com/43390462/52930058-f38d5880-3314-11e9-9a73-53686cf23d12.PNG)

**Comment by Tslat** [comment]
Hi there,

Given that you've downloaded the mod from Curse**Forge**, I assume you know that the mod requires Forge to run.

Please see the below link for instructions on how to install Forge and the subsequent mods:
https://www.minecraftmods.com/how-to-install-mods-for-minecraft-forge/

**Comment by Conor-McNierney** [comment]
Ya know, it really is the things you are so used to using that you forget about first. I feel like a idiot now. Thank you for the rapid response.
