### ISSUE TITLE
The way fully-loaded crossbows are held isn't the same as vanilla

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#3084]
**Mod Version**
What version of the mod are you on?
1.18.2-4.6-Public Alpha 3

**Describe the bug**
Crossbows in the 1.18.2 public alpha 3 aren't held the same as vanilla's when fully loaded.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load any AoA crossbow and compare how it is held to a vanilla crossbow that is loaded.
2. See error

**Expected behavior**
AoA crossbows appear the same as vanilla crossbows when fully loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/163493400-48e0bced-8126-4488-a59a-6fadf8e90758.png)
![image](https://user-images.githubusercontent.com/44556728/163493406-47a0a3ee-2f76-4ebb-bb24-db7ef42be2ca.png)

**Comment by Tslat** [comment]
ffs
