### ISSUE TITLE
Minecraft crash when entering server

### ISSUE THREAD

**Issue by ShadeNight** [Tslat/Advent-Of-Ascension#3092]
**Mod Version**
AoA3-3.5.4-1.16.5

**Describe the bug**
My friend crash when entering the server (rendering entity) look at the attachment

**Expected behavior**
Join the server and play with us
[message.txt](https://github.com/Tslat/Advent-Of-Ascension/files/8497180/message.txt)

**Comment by EatingSilencer** [comment]
Update to public alpha 2 and see if the issue persists.
