### ISSUE TITLE
Dexterity exp gaining seems off

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3105]
When sprinting (not jumping) in a straight line at level 1, you generally gain around 4.5-4.6 exp on average. However, just jumping in place appears to yield a higher average of 5-5.5 exp. From what I know, shouldn't it be the other way around? You're getting more for just jumping in place

**Comment by Tslat** [comment]
Can't seem to replicate

At level 1, a jump gives me 0.33xp, and a sprint jump gives me 0.45xp
10 jumps in a straight line gives me 3.3xp, and 10 sprint jumps in a straight line gives me 4.58xp

**Comment by Cruuk** [comment]
10 jumps in a straight line? Is that referring to jumping while walking? What I'm referring to is just holding still and jumping- holding no other key than space for a long period of time.

And I did similar tests to what you did, and I got similar amounts of exp as you did. As I said, this is referring to just continuously jumping in place without moving at all

**Comment by Tslat** [comment]
Same result
