### ISSUE TITLE
Remove some unused (and maybe future unused) blocks/items

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#3108]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Unused blocks and future unused blocks

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
The following blocks/items are unused atm and should be removed:
*All old Lunalus orbs (Darklight, Dusk, Lunar, Moonlight, Sunfire)
*Extraction Device
*One Archaic Stream variant (either)
*Structure Light
*Impure Gold and Pure Gold
*Clear Water/Clear Water Bucket
*Cosmic Dust
*Pure Rain Stone
*Dungeon Tokens
*Progress Token
*Return Crystal
*Enigma Table
*Decloging Table + declogged weapons (depends on if you want to do something with these or not)

Future unused blocks:
*Two of the rainbow grass variants. If we want all three textures preserved, we can do blockstates on a single block.
*Baron Castle Wall (to be replaced with baron bricks in builds that would use this otherwise).
*Skeletal Block (replace with bone blocks in all places that would use this).
*Baron Cube 
*Cog Block
*Toxic Stem
*Creation/Soul Power banners (all variants) (I made a post about this: #3042, the banners ought to be replaced).
*Some neon lamps: all of them except the base Lapis/Redstone Lamp. 
*Boney Block
*All AoA Coral blocks

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
Not that I know of
**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
On the Discord server

**Comment by AstralScourge** [comment]
The following are still in as of Alpha 4:
- Ancient Glass
- Ancient Light
- Ancient Tiles (all variants)
- Clear Water
- Dungeon Tokens
- Neon Lamps (circling/triangles) 
- Return Crystal
- Tentacle blocks
