### ISSUE TITLE
Missing Entity Renderer for Entities

### ISSUE THREAD

**Issue by Flemmli97** [Tslat/Advent-Of-Ascension#3111]
**Mod Version**
AoA3-1.18.2-3.6-Public Alpha 2

**Describe the bug**
The Abyssal Lottoman doesnt have an entity renderer registered causing the game upon trying to render it to crash
Noticed with "Just Enough Resources" which can render every registered entity in game so even if the mob doesnt occur naturally yet
in this mod its still an issue.
Also game will crash of course if trying to spawn it via commands.
Unsure if more entities are affected or not.

**To Reproduce**
Spawn the Abyssal Lottoman via commands causing game to crash
[https://gist.github.com/Flemmli97/56be2ee5948f4719abff60173b9783bc](https://gist.github.com/Flemmli97/56be2ee5948f4719abff60173b9783bc)

**Expected behavior**
No crash by adding (if the mob isnt done yet) at least a dummy renderer so it doesnt crash

**Comment by EatingSilencer** [comment]
Update to 1.18.2 public alpha 3.

Also, lots of entities don't have renders, this is a known thing. The mobs haven't been added yet.

**Comment by Flemmli97** [comment]
it might be good to add just a dummy renderer for them so at least it doesnt crash the game

**Comment by EatingSilencer** [comment]
This is kinda the case in 1.18.2 alpha 3 already.
