### ISSUE TITLE
Corrupted Traveller texture is broken

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#3119]
**Mod Version**
What version of the mod are you on?
1.16.5-3.6

**Describe the bug**
The texture of the Corrupted Traveller is broken.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn Corrupted Traveller.
2. See error

**Expected behavior**
The texture is not broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/164979703-7aad0bbf-8ffa-4b27-bec3-9ac20c8a0e4b.png)

**Comment by Tslat** [comment]
Can't replicate
![image](https://user-images.githubusercontent.com/7098525/165011251-add0d0e9-c170-46e5-948b-4ee6c95e8ac8.png)

**Comment by EatingSilencer** [comment]
Sigh.

I think I had a resource pack enabled with all the old mob textures in it which was causing this bug.
