### ISSUE TITLE
Infusion table recipes still don't work (in survival)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3129]
On 1.16. They do work in creative
![image](https://user-images.githubusercontent.com/38159897/165228021-9873b607-3b46-466c-9234-f4d50e0bd1e9.png)
![image](https://user-images.githubusercontent.com/38159897/165228131-29715021-abb5-4578-8249-f860443902c6.png)

**Comment by Tslat** [comment]
Alright now no-one can complain I didn't for sure test it lol
![image](https://user-images.githubusercontent.com/7098525/165289014-8b7b8fac-9275-46da-869f-aa8a20d1ea2b.png)
