### ISSUE TITLE
AoA with MineFantasyII

### ISSUE THREAD

**Issue by isd-1** [Tslat/Advent-Of-Ascension#313]
**Mod Version**
AoA-Tslat-1.1.3 & MineFantasyII-2.8.14.6(mc1710)

**Describe the bug**

MFII's skills level will auto refresh to 1 when playing game,and only MFII worked well.

**To Reproduce**
Steps to reproduce the behaviour:
1.install these two mod
2.start game 
3.add MFII skill level
4.in a few second,it will happen.

**Expected behavior**

**Screenshots**
![qq 20190221003700](https://user-images.githubusercontent.com/23614633/53109105-2af94080-3573-11e9-893d-7f7e58ed8b09.png)

sorry for my poor English,I am Chinese

**Comment by isd-1** [comment]
It seems that it will not happen in AoA-2.4.B

**Comment by Tslat** [comment]
Known bug, but not previously known with this mod. Thanks for letting me know

**Comment by Tslat** [comment]
AoA No longer updates 1.7.10 as it is an ancient version of MC
