### ISSUE TITLE
Innervation 1 hit kill protection protects you from ./kill (1.18)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3134]
![image](https://user-images.githubusercontent.com/38159897/165416721-06f67001-8088-45ae-9760-80d2bccf6832.png)

**Comment by Tslat** [comment]
Does it not also apply to 1.16?

**Comment by Cruuk** [comment]
Can confirm that it does occur on 1.16-3.6.2
