### ISSUE TITLE
Incompatibility with Hats and morph mods on minecraft 1.7.10

### ISSUE THREAD

**Issue by vinicius1222** [Tslat/Advent-Of-Ascension#3137]
AoA-Tslat-1.1.3

First of all, I know it's too late for me to report this now, and I also know that support is concentrated on recent versions of minecraft. But if you can help or suggest a way to solve the problem I would be grateful.

When I use the last version of the mod in 1.7.10 with the Hats and Morph mods, every time I close the world or leave the server and log in again, the morphs that were obtained as well as the hats are reset as if I never had obtained.

Steps to reproduce the behaviour:
1. Install the mod with Hats and Morph;
2. Open or create a world and kill any creature you will get the morphs;
3. Close the world and open it again, press the button to see the morphs and they will be gone.

Minecraft: 1.7.10
Forge: 1.7.10 - 10.13.4.1614

**Comment by Tslat** [comment]
one of the previous Tslat- versions works, it was only a newer one that broke the compat, can't remember which though

Try Tslat-1.1 maybe

**Comment by vinicius1222** [comment]
No results. But thanks for replying.

**Comment by EatingSilencer** [comment]
Try Tslat 1.0.1.

**Comment by vinicius1222** [comment]
This version works, but for some reason it crashes during immortalis progression. Same for Tslat 1.0.
I think I better try the old versions or just don't use these mods.
Thanks!

**Comment by DiamondWalker** [comment]
It's been a while, but I believe 1.0.3 is stable.

You can see a list of fixes per version here: https://github.com/Tslat/Advent-Of-Ascension/tree/1.7.10/changelogs

Maybe you can find one that doesn't have any huge issues but still works with the other two mods. There's even older versions, but I strongly suggest avoiding those since they're filled with game-breaking bugs.

**Comment by vinicius1222** [comment]
Thanks, there is also a bug with the boss Bane, the minions are buggy and don't disappear when the boss is defeated, they stay static. Happens since version Tslat 1.0

**Comment by Tslat** [comment]
Yep

Fixes were happening, and you've had to downgrade to a version prior to those fixes
This is pretty much how it is

You're always welcome to update to a modern version
1.7.10 is almost a decade old at this point

**Comment by vinicius1222** [comment]
I saw through mcedit that both mods are saving in the same place in the player's config. In this case the skills and morphs are being saved in ForgeData - PlayerPersisted.

In relation to recent versions I will download the latest from 1.16.5 and testing 1.18

Thanks for everything!

**Comment by vinicius1222** [comment]
The saved skills data is duplicated, it is in two different locations, this is causing the bug.
Another mod that can be affected is Blood magic
