### ISSUE TITLE
More block removal candidates

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#3139]
Continuation of #3108

- Bloodstone Bars
- Bloodstone Bar Bricks
- Dark Face Brick (if kept, should probably be "bricks" instead of "brick")

**Comment by EatingSilencer** [comment]
I'd like to add the following blocks to the list:
*All neon lamps except for Neon Lapis Lamp/Neon Redstone Lamp.
*All Ancient Cavern blocks: Ancient Tile Core, Ancient Tile Shrine, Black Ancient Tile, Green Ancient Tile, White Ancient Tile, Ancient Glass, Ancient Light, Ancient Vines + Ancient Vines Cap.
*Decayed Glass

Also, if you're not planning on keeping the boss altars in the future, now is the time to remove them.
