### ISSUE TITLE
Some Night Mobs Should Burn During The Day

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#314]
Zombies and Skeletons both burn during the day, this is why you don't see them during the day. However Aoa night mobs don't have this, so a lot of the time mobs like Night Reapers end up feeling like day time mobs. Since not all vanilla night mobs burn during the day like Creepers, not all of them have to.

Here a list of my mobs I think should burn during the day:
Night Reaper,
Bugeye,
Dicer,
Bone Creature,
Nightfly,
Ghostine Ancient,
Dark Beast,
Night Watcher,
Shellox,
All Ghostly mobs.

Only problem I can see with this is some of these mobs have a lot of health like Dark Beast so it may burn for a long time until death.

**Comment by 22zhuyansong** [comment]
And also some of the night mobs should be despawn during daytime.

**Comment by Angrydog001** [comment]
What Sagis described is assuring they're undead mobs tremendously.
