### ISSUE TITLE
Streamline some blocks to tie stuff together

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#3143]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
See below

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
I think some blocks have the potential to be tied to other blocks in a way that makes them less arbitrary while also cleaning up consistencies, etc. Here is a list of blocks that could be cleaned up:

1. Baron Bricks + all derivative blocks -> rename to Baron Stone Bricks.
2. Runic Bricks -> add stairs/slabs/wall, and make it craftable from 4 runic stone. Rename to Runic Stone Bricks. Change Runic Construct Bricks to chiseled Runic Bricks.
3. Greckon Bricks -> I'd like to see this become Greckon Stone Bricks, like how the old Baron Bricks essentially became Baron Stone Bricks. Would be crafted with 4 Greckon Stone, though would eventually need a texture change.
4. Iro Striped/Iro Dotted Bricks -> change the iro striped bricks to the irostone bricks (crafted with 4 irostone), and make the iro dotted bricks become the chiseled iro stone bricks. 
5. Lunar Lamp - make it the ore lamp for lunar ingots (e.g.: crafted the same as the other ore lamps, just made with lunar ingots).
6. Dark Bricks - make them Darkened Rock Bricks. If Dark Face Brick isn't removed, it can be made into the chiseled version (this does pose a problem with Haunted Dungeon being made of them, we'd have to think of a solution).

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
Not that I know of.

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
Not that I know of.

**Comment by Tslat** [comment]
I'm gonna close this, but I'll probably make something like this a trend as we go through the dims
