### ISSUE TITLE
Tinytopolis

### ISSUE THREAD

**Issue by BoringTalking** [Tslat/Advent-Of-Ascension#315]
**Describe the new feature you think would be good to add**
A dimension! Wait no no come back! I know we already have 22 dimensions already with at least another 4 down the pipeline. But this is a mod centered around dimensions, and it's probably why you downloaded the mod in the first place. But anyway, as the name would suggest, this is a dimension that's tiny. Before I go into details, all the trees, buildings and such would be all 3D models, With the people being a few pixels high. The trees would be just the one block, whereas the buildings would be comprised of 3-4 in a square. The mountains would be comprised of slabs and full blocks. Basic overview over, time for the details!

**Biomes**
Flats: a completely flat landscape with the occasional tree. A small village has the highest chance of spawning here.

Hills: just as the name suggests, there are hills! wouldn't surpass 1 1/2 blocks. Again, the occasional tree. I don't really see any villages spawning here. But it's not entirely out of the question.

Forest: has a lot of those trees mentioned earlier. The occasional ruin too.

Ruins: this place is mostly for lore. Because yes even this place has some. A really dull purple colour. Think of the kindergartens from steven universe. There would be tree stumps and ruined buildings here and there. The lore is something I'll describe later.

Giants land: this is where you'll really want to go! Unfortunately, it's end game. It would have larger (both in size and scale) It would be blocked off by a magical barrier, like how twilight forest does it.

**Mobs**
Tiny animal: this is just a blanket term. They would have proper names that aren't just tiny pig or tiny cow.

Tiny hostile mob: Again, a blanket term. I think you understand what they are.

Tiny citizen: like regular citizens, they only say things, will outline the lore.

Tiny arms dealer: will sell a small destructor(sword), quantum rifle(gun), small fire(gun), pellet launcher(shot gun)

Tiny engineer: sells 2 sets of armour. one is _very_ important. Heavy armour and Shrinking armour

Survivor: spawns in the ruins biomes. If given food it will lead the player to a dungeon.

Screnel: a mob about half a block high. Only spawns in the giant land. a passive mob.

Bixmic: a mob one block high Again, spawns in the giant land only. a passive mob.

Lolal: a mob one and a half blocks high. Is tamable and ridable. Would have multiple textures. Giant land only

Hapitot: a two block high hostile mob. has many variations

Twiptit: another two block high hostile mob that also has many variations.

Giant citizen: lives in the giants land. Again, talks about lore only.

Giant banker: also lives in the giants land. I'm sure you know what he does.

Giant engineer: sells the masquerade and embiggening armour.

**Structures**
Tiny village: spawns tiny citizens, arms dealers, and engineers. would have one building for every arms dealer and engineer and a building for every 2-5 citizens.

tiny forest cabin: spawns in the forest. Rare. Has good loot.

Small ruin: the small ruins I mentioned for the forest. Would mainly be for aesthetics. Covered in moss and crumbling. Examples could be a house, fountain, shrine, water wheel and shop.

Small dungeon: only really accessible by the shrinkage armour. would have the crafting ingredients for the item that gets rid of the barrier to giants lands.

Giants land village: Would be a regular size village, would look slightly more up to date than the small village.

Boss shrines: the one for the nibbler wouldn't be scaled to the player, the one for the wisps is however.

**Bosses**

the nibbler: sounds harmless enough. The easiest of the bosses. Would be quite hard to hit however. Deals 15 hearts of damage and has 2400 hearts. Once killed, you can speak to the villagers. I'll detail later. The shrine is found in the flats and hills. Not scaled to player.

Wisps: sort of like the skeletal army, but as big in numbers. They are what made the ruins into, well the ruins. A mid-level boss. Deals 20 hearts of damage and 2500 hearts. Killing them not only reaps rewards but it also drops ingredients needed to remove the giants land barrier.

Realm defender: like Craxxeuss, but definitely not as powerful. Protected the giants from the wisps. Spawns immediatly after the barrier is broken and around 30 blocks away from you. deals 25 hearts of damage and has 2600 hearts.

**Weapons and Armour**

Heavy armour: allows you to walk through things like leaves and cobwebs without you having to jump over them or get stuck respectively. Also allows blocks like up to the breaking level of coal to be broken with bare hands and give drops. It's also faster. Helmet has 500 durability, chest plate 800, leggings 750 and boots 650. Same for the other armour pieces

Shrinking armour: when the full set is worn, It shrinks you to be 1:1 with the tiny village, extremely helpful for looting log cabins, mandatory for doing the dungeons.

Masquerade amour: when worn, no hostile mobs will attack you unless one was already chasing you or you attack a hostile mob while wearing the armour

Embiggening armour: the exact opposite of the shrinking armour. Makes you 3 blocks taller than normal.

temporary peace armour: any mob that attacks has a chance to stop attacking for 7 seconds.

Small destructor: a regular sword. Does 20 hearts of damage. has a chance to deal an extra 4 hearts of damage with every hit.

Quantum rifle: does 15 hearts of damage. has 4000 durability. 33% chance to not consume ammo. Pretty standard.

Small fire: does 12 hearts of damage. has 5000 durability. 33% chance to not consume ammo. However, can be dual wielded with another small fire to do a total of 26 hearts of damage. The fact it's not doubled properly is intentional.

pellet launcher: does 25 hearts of damage. has 2200 durability. as a chance to fire out two slugs with only one being consumed

shrink stave: shrinks any nearby enemies, halving all their stats. lasts for 10 seconds.

growth stave: grows any nearby minions to have their stats increased by 40%. lasts for 15 seconds.

wisp whisperer: a greatblade. Deals 15 hearts of damage. Has a chance to fire a random bullet in the inventory to stack with the damage done by the greatblade.

Mind stave: allows the user to take control of a hostile mob for 15 seconds and make it attack another mob.

(there are all the ideas have in my head, but if this does become a thing I'd want scimi to come up with his own ideas too)

**Lore**

Many, many years ago, There was a war which resulted in the destruction of many realms. A race from one of those realms was able to quickly shamble together an escape by ancient teleportation. They ended up in Tinytopolis. However, with them they also brought creatures who were fighting in the war, wisps. The race was able to reduce the wisps to various shrines, but at the cost of a lot of the environment, making the ruins. The natives of Tinytopolis obviously were furious about this, and tried to kill the foreign race. The race however, didn't want to cause the species any harm. So they put up a barrier around select sections of land to distance themselves from the Tinytopolis natives. 

**Miscellaneous**

How to get there: I imagine the realm stone drops from a mob in celeve. Or perhaps even playtopia since Tinytopolis could look like toys.

Activation message: little squeeks and rustles can be heard within. 

Difficulty: Mid level. I used Barathos to scale a lot of the durability and damage, so around that level.

**Add any alternative implementations you think might work**
I dont think so, as much as dimensions may seem like something we have too much of, they are still important and interesting if nothing else.

**Include any additional background information**
Not really any bts info, though I do have other dimension ideas, if anyone would like to know them. To anyone who made it this far, say if you want to know them in the comments, also critique this idea too. Also in the comments (obviously)

**Comment by Tslat** [comment]
My concern is that with everything being tiny, from the perspective of a normal player it'd almost just be a flatland world with ground decorations.
I could see it being pretty uninteresting after the first couple of minutes

**Comment by BoringTalking** [comment]
Crap, didn't think of that. Maybe it could work? My ideas are usually hit or miss. I try to make them good but also expect them to never be used.

**Comment by Tslat** [comment]
Ideas are always good
Nothing wrong with feedback though ;)

Thanks for the suggestion
