### ISSUE TITLE
Weapons that strike lightning cause a fire on blocks (1.18)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3152]
Unsure to really call this a bug, but I recall that an update in 1.16 or earlier specifically made it so the lightning that came from weapons did not spawn fire on blocks. It was still the same lightning otherwise. However in 1.18, the lightning that comes from weapons do spread fire to blocks

**Comment by Tslat** [comment]
I don't think this has changed? I can't see anything about it

Got specific examples?

**Comment by Cruuk** [comment]
![image](https://user-images.githubusercontent.com/38159897/167066889-2d77e82b-3851-4735-b7f2-42e757847b5b.png)
All lightning weapons (Striker staff, Lightning staff, Lyonic staff, Pulsator, Predator) still appear capable of also starting a fire
