### ISSUE TITLE
Dimension Suggestion: Funtime Land Part 2

### ISSUE THREAD

**Issue by cosmiccharlie777** [Tslat/Advent-Of-Ascension#3155]
Mobs:

Danny the Duck-
168 Health
19 Melee Damage
He randomly jumps in the air.

Daphne the Duck-
179 Health
17 Melee Damage
She randomly levitates all players in a 10 block radius for 5 seconds.

Ralph the Rabbit-
169 Health
19 Melee Damage
He randomly charges at the player.

Larry the Lion-
189 Health
20 Melee Damage
He randomly roars inflicting all players with Slowness 5, Nausea 30, and Mining Fatigue 8 in a 10 block radius for 5 seconds.

Chrissy the Cow-
168 Health
18 Melee Damage
She randomly squirts out milk, and on hit, she stuns the enemy/player.

Paul the Pig-
183 Health
18 Melee Damage
He randomly sneezes a snot ball and poisons on hit.

Charlotte the Chicken-
179 Health
10 Melee Damage
She randomly throws an egg and does 30 damage on hit.

**Comment by Tslat** [comment]
Don't make multiple posts for the same thing

If it's part of the previous suggestion, edit your previous suggestion to include this
