### ISSUE TITLE
AoA mobs not spawning on BOP surface blocks

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#316]
Biomes o Plenty adds surface blocks such as "Silty Grass" that aren't classified as natural blocks. As a result, AoA mobs will not spawn on them due to being hardcoded to spawn only on certain natural vanilla blocks, and the biomes sometimes feel a bit empty (especially if a large biome has a BoP grass top block).
Will this be looked into in the future?

**Comment by Tslat** [comment]
I've made the spawning requirements more generified for overworld mobs post-SNAPSHOT-10.
If it still doesn't spawn after that, then it's a much bigger issue to resolve, and may or may not happen.
We'll see how it works in 3.0

**Comment by Immortallis1** [comment]
neat
