### ISSUE TITLE
1.18.2 Crash

### ISSUE THREAD

**Issue by Tyrius1** [Tslat/Advent-Of-Ascension#3160]
**Mod Version**
What version of the mod are you on?
AoA3-1.18.2-3.6.2
Forge 40.1.14

**Describe the bug**
Game crashes when attempting to launch my current WIP pack after adding in AoA.
I have not started the removing and adding back in mods 1 by 1 cause I'm hoping it's something you can see from the latest log/ crash report.

Crash Report:
https://pastebin.com/ZX6qt4Qv

Latest Log:
https://pastebin.com/9Z3ZFfZX

**Comment by Tslat** [comment]
Doesn't look related to AoA at all
