### ISSUE TITLE
Duplicate skills data in NBT player data and buggy Bane boss minions

### ISSUE THREAD

**Issue by vinicius1222** [Tslat/Advent-Of-Ascension#3163]
Minecraft-1.7.10
Mod: Aoa tslat 1.0.2 - 1.1.3

Again I'm insisting a lot on this because I really like this mod in version 1.7.10, even though it's a dead version, there are some mods that I like to use in this version that never received an update to the recent versions. I know the recent ones are a priority but even so it's something I really like.

I checked through mcedit and noticed that the skill information is duplicated, being saved in two places at the same time which is unnecessary. And this is causing conflicts and bugs with other mods, it is being saved in NBT PlayerPersisted as well as in ForgeData/PlayerPersisted.
Regarding Boss Bane, the minions it generates are buggy and static and don't disappear, not even in peaceful mode, having to be removed by other methods

**To Reproduce**
.Player data
1. Just install the mod and create a new world
2. Open world on MCedit program
3. Check player NBT data
.Boss Bane
1. Open a new world
2. Summon the boss bane and wait sumoning minions
3. Defeat boss and try put on peaceful mode

![2022-05-06](https://user-images.githubusercontent.com/47424107/167190331-f2f49d40-861a-4fb2-8046-b2ec72671b2d.png)

**Comment by Tslat** [comment]
1.7.10 is dead

**Comment by vinicius1222** [comment]
sounds like arrogance

**Comment by Tslat** [comment]
> sounds like arrogance

Sounds selfish

**Comment by vinicius1222** [comment]
But at least I can try to fix the bugs of version 1.7?  I will keep the old mechanics.  It's just that I like this version of the mod.
