### ISSUE TITLE
Custom map colors for natural blocks

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#318]
I think all naturally generated blocks should have custom colors on vanilla maps. I personally find minimap mods a bit unbalanced, and being forced to use them in dimensions to not get lost is a bit annoying (there's also the trail technique, but there are also many flaws with that solution). If you could see dimensions on maps properly, it would be easier to not get lost.

**Comment by Tslat** [comment]
Yeah it's basically expected..

Problem is, you have to manually come up with a colour in the correct data format for every single block.
It's a nasty undertaking, but maybe sometime in the future

**Comment by Immortallis1** [comment]
Does it really matter from a "getting lost" persepective? When you are getting lost, it doesn't really matter if the map shows all green or all orange, you're still lost. If you really want to mark where you originally came from make a big cobblestone platform above your portal and it will show up on the map anyway.

For a "consistency" or attention-to-detail perspective, sure. But yeah it sounds like it will take a while
