### ISSUE TITLE
Portal Issue

### ISSUE THREAD

**Issue by HasakiToad** [Tslat/Advent-Of-Ascension#3181]
Portals in 1.18.2 are indeed unstable as you mentioned, they dont work the portal is being created and realm key usage is possible but sadly when the portal opens it doesnt work when you step in

**Comment by EatingSilencer** [comment]
There are no dimensions in 1.18.2 yet, so there is no way for the portal to work at this time.

**Comment by HasakiToad** [comment]
Would there be a way for me to make it work, i could re program the mod if needed but idk if that allowed

**Comment by EatingSilencer** [comment]
Nope. You'll just have to wait for the dimensions to be added back in by the mod dev.
