### ISSUE TITLE
Elusive not Spawning in the Abyss Realm (Server Not On Easy Mode)

### ISSUE THREAD

**Issue by TheRealNinjaTTV** [Tslat/Advent-Of-Ascension#3187]
**Mod Version**
Minecraft: 1.16.5, AoA: 3.5.4

**Describe the bug**
I am in the Odyssey: Space modpack so you go to the Abyss Realm with the spaceship, find an Illusion Tree,
use the Stary Eye you get from a red-eye tentacle block on the Illusion Altar, Boss Bar appears, and a message in chat 
says "You see double", look everywhere around the tree, and no Elusive. Then I travel far away from the tree and the 
Boss Bar disappears which I assume it despawns. Come back to the tree and try again, use another Stary Eye on the 
Illusion Altar, chat says see double again but no boss bar this time, leave the realm then come back, do the same thing still no boss 
bar and no Elusive. So there is no way to use Nightmare Flakes on him to get the Grekon Realmstone, so I am stuck.

**To Reproduce**
1. Go to the Abyss Realm
2. Click on Illusion Altar with Stary Eye
3. Boss Healthbar on top of the screen
4. Look everywhere around the tree and no Elusive
5. Rinse and Repeat

**Expected behavior**
Elusive and clone spawns

**Screenshots**
N/A

**Comment by EatingSilencer** [comment]
Update to 3.6.4.

**Comment by TheRealNinjaTTV** [comment]
It's part of a modpack, Odyssey: Space, so if the modpack author updates your mod to that version do they have to wipe the entire world, because I need to tell them this and if it doesn't work on 1.16.5 then they won't do it. Also can you enable it or edit the config file so instead of only one option to control the spawn rate of mobs, you can have there be two options one for normal mobs and one for bosses because the modpack author said there is only one setting for all AoA mobs and he had to lower the rate because the mobs were insanely overpopulated so when he lowered it, it lowered the spawn rate of bosses as well so now you have to try to summon them 5 to 10 times for them to even spawn.

**Comment by Tslat** [comment]
Hes proably just spawning up on top of the tree
If the boss bar is working properly, then the boss is there
