### ISSUE TITLE
Optional Resource Pack for spawn egg textures

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#319]
A while back Pixelator made custom textures for every spawn egg, but it later turned out this was impossible to add to the game without a resource pack. So for people who want the textures, there should be an official optional resource pack that includes them. It could be bundled with the jar file, and people could install it if they like. If they don't, the spawn eggs would have the same vanilla texture with different colors.

**Comment by Tslat** [comment]
I'm not going to increase the download size + add a whole extra install step just to officialize something that's already obtainable
