### ISSUE TITLE
Creating modpack, 1.18.2 crash

### ISSUE THREAD

**Issue by TheRealNinjaTTV** [Tslat/Advent-Of-Ascension#3192]
Only when I add AoA does the modpack crash on startup.

[crash-2022-05-15_21.12.06-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/8696491/crash-2022-05-15_21.12.06-client.txt)

**Comment by Tslat** [comment]
See if it happens with a specific combination of mods
Just jamming it into a pack with dozens/hundreds of other mods, it could be literally anything

**Comment by Pikabyte** [comment]
I had a similar crash in my modlist, it seems this mod is incompatible with Corail Tombstone.

**Comment by Tslat** [comment]
The Coral Tombstone one might be a different crash

I've already alerted the Coral guys to the issue
https://github.com/Corail31/tombstone_lite/issues/55

**Comment by Tslat** [comment]
Can't reproduce and no further info has been provided
