### ISSUE TITLE
monster stealth

### ISSUE THREAD

**Issue by HYDeath** [Tslat/Advent-Of-Ascension#3194]
**Mod Version**
AoA3-1.18.2-3.6.3.1

**Describe the bug**
Why do I not brush monsters when I play in 1.18.2, and the monsters I manually summon are all invisible, can be played, and no error log is reported.

**To Reproduce**
NO

**Expected behavior**

**Screenshots**
![P_YQ BRSLNQLS5LP%SB)Y_C](https://user-images.githubusercontent.com/65531310/168595381-3d85e3e8-b469-47b5-8744-a1d9504963fc.png)

**Comment by HYDeath** [comment]
Difficulty is turned on

**Comment by EatingSilencer** [comment]
Some mobs have not been added back in yet.
