### ISSUE TITLE
Shouldn't the name of this be "item unlock"

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3199]
Unknown if intended, but I feel like "Item unlock" was the better name for these types of abilities rather than "level restriction"
![image](https://user-images.githubusercontent.com/38159897/168736076-f3059df7-e031-4c51-8a0a-6e0f7d00b368.png)

**Comment by Tslat** [comment]
Nah Level Restriction is definitely better
Need to keep in mind that this ability can be used for blocks or items, and may possibly in the future include entities too
