### ISSUE TITLE
[1.18.2] AoA preventing game launch in large modpacks

### ISSUE THREAD

**Issue by itsdinkd** [Tslat/Advent-Of-Ascension#3208]
**Mod Version**
AoA3-1.18.2-3.6.3.1

**Describe the bug**
Preventing the game from launching due to conflictions. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch game with mods listed in logs

**Expected behavior**
to launch without crashing

latest: https://gist.github.com/itsdinkd/d86d1bc1e7b19b7a90e23f91daa85683
debug: https://gist.github.com/itsdinkd/247258f627d4e7c5959be57c732af8a1

**Comment by EatingSilencer** [comment]
You should not be using AoA in 1.18.2 in a modpack or survival yet, as a lot of content is missing (all dimensions, most mobs, etc).

**Comment by Tslat** [comment]
This is a tombstone mod problem, not AoA
It conflicts with AoA because they haven't done their mixin correctly

**Comment by itsdinkd** [comment]
Corail tombstone? You sure it's not correct? Lol

**Comment by itsdinkd** [comment]
Makes sense. Thanks

**Comment by Tslat** [comment]
https://github.com/Corail31/tombstone_lite/issues/55
