### ISSUE TITLE
Server NPE crash - projectiles

### ISSUE THREAD

**Issue by hanakocz** [Tslat/Advent-Of-Ascension#321]
**Mod Version**
aoa3-SNAPSHOT-10.jar

**Describe the bug**
Repeated server crash on chunk load of entity from this mod. Fixed by removing the entity via NBTEdit.

**To Reproduce**
??? Apparently players just played and then it crashed.

**Expected behavior**
Check for all nulls and not let NPE happen.

Crash report: https://gist.github.com/hanakocz/f3d4463be598215549bff66040c78704

After 30 seconds of repeated play, another crash:
https://gist.github.com/hanakocz/524dc1182d6e721b5f492a11f1061773

**Comment by Tslat** [comment]
Has been resolved after SNAPSHOT 10
