### ISSUE TITLE
mod version 3.6.4, game crashes when it try to render Hiding Fungi

### ISSUE THREAD

**Issue by BaffledHedgehog** [Tslat/Advent-Of-Ascension#3210]
**Mod Version**
What version of the mod are you on?

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
[crash-2022-05-20_21.08.44-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/8743231/crash-2022-05-20_21.08.44-client.txt)

**Screenshots**

**Comment by Tslat** [comment]
Unable to replicate
![image](https://user-images.githubusercontent.com/7098525/171105843-e32a9f82-df4f-4a48-aff1-4846b8796c30.png)

**Comment by BaffledHedgehog** [comment]
Sorry, it was because i played with optifine fast render, without it game
don't crash

вт, 31 мая 2022 г., 09:20 Tslat ***@***.***>:
