### ISSUE TITLE
The portals aren't transporting me to the other dimensions. 

### ISSUE THREAD

**Issue by snipersoysoy** [Tslat/Advent-Of-Ascension#3217]
**Mod Version**
What version of the mod are you on?
1.18.2 3.6.4
**Describe the bug**
So I did the challenge for the realm stone( the one where you have to jump 26 blocks.) and when i put it in the portal it lites op and makes sound but when I try to enter it it doesn't take me to the dimension.

**To Reproduce**
I'm not sure.

**Expected behavior**
I expected for the portal to take me to the dimension but it didn't.
**Screenshots**

**Comment by EatingSilencer** [comment]
The dimensions have not been added to 1.18.2 yet.

**Comment by Tslat** [comment]
AoA3 for Minecraft 1.18.2 and up is not ready for survival

As part of the requirements of porting to the newer render system and worldgen system, AoA has some work to do yet to be ready for survival play on 1.18.2 and above. Until then, most mobs and dimensions are missing, and the mod itself is only intended for creative use or testing

Use the 1.16.5 version for now
