### ISSUE TITLE
Essence Repository

### ISSUE THREAD

**Issue by xReficul** [Tslat/Advent-Of-Ascension#322]
I feel there should be some sort-of backpack of repository for essence, somewhat like Millenaire's Denier Pouch, which stores them automatically on pickup and trade, and you may remove them into your inventory by right-clicking the pouch. Doing so with a lack of denier will store all of the ones in your inventory into the pouch once more.

For AoA, a similar system could be created to store and remove them, as well as some indicator in the item's metadata that shows the player the contents of the pouch.

*Also lower drop rates of essence pls ty*

**Comment by Sagisolar** [comment]
Other than the last I support.
