### ISSUE TITLE
Primordial armor full set appears to reduce damage from withered mobs by more than 60%?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3222]
Context: I gave myself 500 HP and a Sand giant enough strength to do exactly 199.5 (effectively 200) damage to see how much you can tank. However, with Primordial full set I'm able to reduce damage by a lot

At first I thought it was a quirk of damage calculation with such a high strength effect value. However, per piece appears to be working fine.
Example: With Primordial chestplate and leggings equipped, I take 172.4 damage from the 200 damage Sand giant that **isn't** withered. 172.4 x 0.7 is 120.68. 30% reduced damage with the 2 pieces. When the Sand giant **is** withered, it deals 120.7 damage, which effectively exactly lines up with the earlier calculation.

The same basically goes for 1 piece and 3 piece, but it's different with the full set. With full set, 158 damage is taken from the Sand Giant that **isn't** withered. With Wither, it should be reduced to around 63.2 damage. That's 158 x 0.4. However, when the Sand giant **is** withered, 33.2 damage is taken instead. I don't expect it to be 100% accurate, but that is a pretty big difference.

Could it be because full set is applying extra damage reduction when it's only supposed to allow other sources of damage to be affected by Primordial? Unknown

**Comment by Tslat** [comment]
Unable to replicate
