### ISSUE TITLE
Auto harvesting trash GUI is invisible (1.18)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3226]
I also checked it with no other mods installed, and it it's still invisible
![image](https://user-images.githubusercontent.com/38159897/170848766-7d7133d1-ed0f-47b5-ae38-c03559cc98c1.png)

**Comment by Tslat** [comment]
Are you using an outdated forge, or outdated JEI

**Comment by Cruuk** [comment]
Checked with no mods installed other than AoA. GUI was invisible still

Reinstalled the mods, then updated Forge to 40.1.25, GUI was invisible still

Removed all other mods except AoA again (Keep in mind, I have the latest Forge version this time). GUI was invisible still
