### ISSUE TITLE
Flying mobs fly high when not aggroed

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#323]
**Mod Version**
3.0

**Describe the bug**
When flying mobs aren't aggroed they go really high up into the sky on their own, not sure if intended

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a flying mob spawn naturally or manually
2. It'll begin going pretty high into the air

**Expected behavior**
I imagine flying mobs should stay around 10-15 blocks or under in the air

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/53274045-b1fd0480-36aa-11e9-9a6a-34b3b2ae90c0.png)

**Comment by Tslat** [comment]
Intended

I'll add some variance/grounded ones when I do more work on the flight AI
