### ISSUE TITLE
can't enter the portal (1.18.2)(tlauncher)

### ISSUE THREAD

**Issue by firedevil2008** [Tslat/Advent-Of-Ascension#3235]
i can't even enter every single portal(please help me
![Screenshot (460)](https://user-images.githubusercontent.com/106717957/171536117-fa63561b-8efe-41fa-bc49-0707daf8ae9a.png)

**Comment by Tslat** [comment]
AoA3 for Minecraft 1.18.2 and up is not ready for survival

As part of the requirements of porting to the newer render system and worldgen system, AoA has some work to do yet to be ready for survival play on 1.18.2 and above. Until then, most mobs and dimensions are missing, and the mod itself is only intended for creative use or testing

Use the 1.16.5 version for now
