### ISSUE TITLE
Craexxeus movment is broken

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#324]
In 3.0, Craexxeus has broken movement. I'm aware flying AI needs some more work, but it's way more noticeable with Craexxeus. He just... hovers... and occasionally flies over you until he hits a wall. If this bug will take a while to be fixed, then Craexxeus should get a temporary damage and fire rate buff, just so he's actually a decent fight.

**Comment by Tslat** [comment]
Can't seem to replicate, but regardless I have further work with flight AI which will cover this
