### ISSUE TITLE
Is the Hoe area harvest ability supposed to work if the crop you used the hoe on isn't fully grown

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3242]
Notice that the center crop isn't fully grown
![image](https://user-images.githubusercontent.com/38159897/172323788-02a3bc64-276c-44dc-894e-65f9178e65b7.png)
![image](https://user-images.githubusercontent.com/38159897/172323888-6b218ad5-61a1-4396-b8e6-71ae9a898500.png)

**Comment by Tslat** [comment]
yes
