### ISSUE TITLE
Can't enter dimensions

### ISSUE THREAD

**Issue by agoodtaco** [Tslat/Advent-Of-Ascension#3245]
AoA3-1.18.2-3.6.5

Whenever I try to enter the advent of ascension portal, nothing happens, and I am left just standing in the portal frame. The music for the portal opening still plays, but I don't teleport and no dimension forms in the files.

1. Make the advent of ascension portal
2. Get a realm stone
3. Click on the power rune to open the portal
4. Walk into portal

**Expected behavior**
I expected to be able to teleport to a dimension.

**Screenshots**
![2022-06-08_03 22 14](https://user-images.githubusercontent.com/60238674/172556879-b49d7bab-c0bd-4952-9f5a-cea4e0fb1bb4.png)
![2022-06-08_03 25 35](https://user-images.githubusercontent.com/60238674/172557113-53b72519-f88d-4578-aad7-2e02e8734203.png)

**Comment by agoodtaco** [comment]
I saw (The portals aren't transporting me to the other dimensions. #3217)

**Comment by ZiphonOfficial** [comment]
I'm having the same issue
