### ISSUE TITLE
Make tablets usable again and configurable

### ISSUE THREAD

**Issue by Nebula240** [Tslat/Advent-Of-Ascension#3248]
Create a config for tablet usage and change it to consume spirit

How would the player benefit from this?

- Tablets would be usable again, which on a multiplayer environment is very useful on various circumstances.

As a way to make up for Soul resource being removed just make the tablets consume Spirit resource.

The tablets could keep the same consume ratio that they currently have, and a config could be created to help pack developers or server owners to encourage/discourage tablet usage.

I think it would be a waste to just let the tablets die down and just leave them unused in 1.16.5, so let's give em a use!

**Comment by DarianLStephens** [comment]
Seems like they sadly did.
I haven't found any mention of tablets or anima in general, and every issue related to them was closed as 'Not planned', so it seems they're shelved entirely.
That's a shame, I was planning to base a build around them. They were a unique thing not focused solely on combat.

I also can't find the gods anymore. Do they exist? What about the events? Are they going to come back? Is there a roadmap of plans I can view somewhere?
