### ISSUE TITLE
Can't enter any other mod added dimensions on Minecraft 1.18.2

### ISSUE THREAD

**Issue by laukomatic** [Tslat/Advent-Of-Ascension#3249]
**Mod Version**
What version of the mod are you on?
Minecraft 1.18.2 forge version
**Describe the bug**
I can't enter any other realm. I have tried on version 1.16.5 and it worked flawlessly. It also didn't work on 1.19 alpha.
**To Reproduce**
1. Install forge 40.1.51
2. Install aoa
3. Create a world
4. Create a portal
5. Activate it(try many portals, because as far as I understand you can't access most of them from the beginning.)
6. Try entering
Instead of being teleported it just lets you walk through.

**Expected behavior**
Teleporting to the other dimension while entering the portal.

**Comment by EatingSilencer** [comment]
The dimensions have not been added back yet in either 1.18.2 or 1.19.
