### ISSUE TITLE
Candyland sticky message appaears to player in spectator mode

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#325]
**Mod Version**
3.0
**Describe the bug**
When you sit in Candyland's water while in spectator mode, the message still displays and the player gets Slowness.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Candyland dimension.
2. Set your gamemode to spectator.
3. Sit in the water.
4. See that the water inflicts Slowness and the message appears.

**Expected behavior**
The message and Slowness doesn't appear in spectator. mode

**Comment by Tslat** [comment]
Fixed after 3.0
