### ISSUE TITLE
Shadowlord's projectiles come from the north

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#326]
In version 3.0, Shadowlord is bugged. His particle effects spawn ~100 blocks to the north of his actual location. When he tries to shoot a mob, the projectile is fired from the particle effects, not Shadowlord himself (they are correctly aimed, mean they hit the target most of the time, the projectiles just come from the wrong place). Most of the projectiles become invisible by the time they reach the target.

**Comment by Tslat** [comment]
Fixed
