### ISSUE TITLE
1.19 Version swamp water missing

### ISSUE THREAD

**Issue by Joshernoob** [Tslat/Advent-Of-Ascension#3262]
Mod Version: AoA3-1.19-3.6.6

Bug:When loading in it throws and error saying fail to load aoa3:toxic_waste_flowing

To Reproduce:
1:add to game
2: load game
3: error should show right before last load

PIctures:
![Screenshot 2022-06-18 140208](https://user-images.githubusercontent.com/64944433/174451032-22d5d0aa-509c-4338-8faf-d088ceebcfbb.png)

**Comment by Tslat** [comment]
provide your full log

**Comment by Joshernoob** [comment]
log: https://pastebin.com/juu2d4n8
FIle: [latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/8936082/latest.log)

(added the file for the log as well in case link doesnt work)

**Comment by Tslat** [comment]
try it without any other mods present
You've got a bunch of mods erroring out there
