### ISSUE TITLE
Many mobs have broken animations that rotate too much

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#3264]
**Mod Version**
1.19 3.6.6

**Describe the bug**
Many mobs have broken animations where each of the segments move too much when idle and rotate rapidly while the mob is moving. Affected mobs include Arcbeast, Chomper, Flyes, Sysker and Night Reaper (which is completely upside down). Several other mobs such as Bush Baby and Bugeye have broken moving animations but normal-looking idle animations, but I'm not sure if this is only because their animations make the same issue less obvious.

See https://discord.com/channels/434160774546456590/434160774546456594/987582807901618207 for video

![image](https://user-images.githubusercontent.com/12868968/174459544-f1bcb337-8ce0-402f-8593-b2489fa39963.png)

**Comment by Tslat** [comment]
Does this happen to their 1.18 equivalents?

**Comment by Sonicwave** [comment]
1.18 (3.6.6) looks fine.

**Comment by Tslat** [comment]
I'll ask geckolib about it, they might have a bug
