### ISSUE TITLE
Something is causing the level 25 Dex jump boost ability to give the full accumulated 65% jump boost, regardless of Dex level

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3271]
As the title says, the level 25 jump boost instance is supposed to slowly build up the jump boost per dex level until 100, where it adds up to 65%. But something is causing players to be able to get the full 65% jump boost, regardless of Dexterity level

There is a way to reproduce this, but as far as I know it's only with commands. First you login to a world at level 100 Dex, then set your level to 24, manually train it to 25 (unknown if the bug will occur via setting it to 25 with commands), then you unlock the jump boost ability with the full 65% jump boost

However, according to someone else, they have experienced this bug in survival with no skill commands used. It seems to be in a server. As for why, I do not know as of right now

**Comment by EatingSilencer** [comment]
I did some testing of my own:
1. setting it to level 23 instead of 24 and then leveling up to 25 also does it.
2. setting the level to 25 directly does not do it.
3. leveling up normally past 25 stops the bug from happening.
