### ISSUE TITLE
Ability toasts can appear on the save and quit screen

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#3272]
**Mod Version**
What version of the mod are you on?
1.19-3.6.6

**Describe the bug**
If you have an ability toast present on screen, then save and quit, the toast will not go away immeditately. This may even lead to this crash:
[https://paste.gg/p/anonymous/43f9efac4c5d427daab4f1bf88ab5162](https://paste.gg/p/anonymous/43f9efac4c5d427daab4f1bf88ab5162)

**To Reproduce**
Steps to reproduce the behaviour:
1. Set your Dexterity skill to level 100 using commands and immediately save and quit (pause game -> press save and quit) as the toast notifications for abilities are popping up.
2. See error. 
3. Once the first page of toasts goes away, the game will crash when the second set of toasts attempts to appear (should only occur if there are enough toasts to unlock for this).

**Expected behavior**
The toasts do not appear on the save and quit screen. If this is intended, then it should at least not crash the game.

**Comment by Tslat** [comment]
Why does vanilla not clear toasts on logout.. wtf
