### ISSUE TITLE
Crash with REI [1.19]

### ISSUE THREAD

**Issue by Niketats** [Tslat/Advent-Of-Ascension#3276]
**Mod Version**
3.6.7

**Describe the bug**
Game crash during loading with REI installed

**To Reproduce**
install AoA
install REI
launch

**Screenshots**
![image](https://user-images.githubusercontent.com/68917520/175765192-acb252cd-f8ee-46da-b5cc-cb732359d09a.png)
[crash-2022-06-25_11.23.52-fml.txt](https://github.com/Tslat/Advent-Of-Ascension/files/8984200/crash-2022-06-25_11.23.52-fml.txt)

**Comment by Tslat** [comment]
Does it happen without REI installed?

**Comment by Tslat** [comment]
Unable to replicate
