### ISSUE TITLE
Add an alternative recipe for Carved rune of power that uses Echo shard instead of Ender eye

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3277]
Always wanted a method of obtaining Carved rune of power without having to leave Overworld, it did bug me a bit that you have to go to 1 of the T1 dims (Nether) before the others, even if Nether is the place you go to in vanilla progression. I guess it's like that by design, but I think it would be fine to have it behind Overworld's most dangerous biome/structure, to give players another choice

I don't know if it would seem too forced via recency bias. Thematically, there's a bunch of "portal" stuff in the city with the bigass portal, and the little structure pieces that resemble said portal

Also, Echo shard starts with the same letter as Ender Eye: E. So the Worn book would only need to be changed a tiny bit

**Comment by EatingSilencer** [comment]
I think it would need to replace Eye of Ender in the recipe and not be an alternative. Eyes of Ender are just so much easier to obtain that I can imagine most players not even going for this alternative unless there had a mod installed that made them easier to obtain.

**Comment by Cruuk** [comment]
> I think it would need to replace Eye of Ender in the recipe and not be an alternative. Eyes of Ender are just so much easier to obtain that I can imagine most players not even going for this alternative unless there had a mod installed that made them easier to obtain.

I don't know, from experience, it's a simple matter of smart playing with crouching and wool blocks. It makes it pretty easy. I could be wrong, but it seems almost easier than dealing with the shenanigans of rough Nether terrain and Fortress RNG. But that's just me. Echo shard itself seems pretty common in the loot chest tables

And even if City is more difficult, I see it as still having the upsides of being OW-accessible, compared to having to go to a whole dimension. It's supposed to be an alternative, I don't want to replace the current one. I mainly want an alternative without a Nether requirement, so I figured the most dangerous OW biome would be the most sensible obstacle

**Comment by EatingSilencer** [comment]
How rare is the Deep Dark? Is it rarer than a nether fortress?

**Comment by Cruuk** [comment]
> How rare is the Deep Dark? Is it rarer than a nether fortress?

It seems to be rare, but it seems to really condense around certain biomes

![image](https://user-images.githubusercontent.com/38159897/175811493-a69f6319-87e8-479b-89b0-dc3a2fa3bab6.png)
![image](https://user-images.githubusercontent.com/38159897/175811500-1e0d1889-9069-4581-8661-e78ed89b3bd9.png)
