### ISSUE TITLE
Missleading text in Chinese Translation.

### ISSUE THREAD

**Issue by hongze-wu** [Tslat/Advent-Of-Ascension#3279]
**Mod Version**
What version of the mod are you on?
1.16.5, 3.6.6

**Describe the bug**
"gui.realmstoneMenu.hover.mysterium", the text for obtaining a mysterium realmstone, was translated to "使一个飞翔苦力怕中毒", which means "poison a creepird". This is not correspond to english text.

**To Reproduce**
Steps to reproduce the behaviour:
1. get a blankRealmstone
2. rightclick to open the realmstone menu.
3. read the text in Chinese.

**Expected behavior**
A more proper text can be "在中毒期间，击杀一个飞翔苦力怕"

**Comment by EatingSilencer** [comment]
This is one of those things where you might want to just do a pull request to fix the translation yourself.

**Comment by Tslat** [comment]
Feel free to submit a revision in CrowdIn
