### ISSUE TITLE
Dicer has far reach

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#328]
**Mod Version**
3.0

**Describe the bug**
Dicer seems to have a pretty long reach, going beyond it's hitbox

**To Reproduce**
Fight a Dicer

**Expected behavior**
I imagine it should be like 1 block lower

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/53278952-9e10cd00-36c1-11e9-85d3-6463a729c15b.png)

**Comment by Tslat** [comment]
Fixed
