### ISSUE TITLE
Invisible Mobs

### ISSUE THREAD

**Issue by EinsteiniumTF2** [Tslat/Advent-Of-Ascension#3282]
What version of the mod are you on?
1.19 - 3.6.7

Mobs are invisible, whether it be spawning normally or via /summon or spawn eggs

I expected the mobs to appear without any hitches. I don't use optifine, either. I tried the mod by itself, the mobs still wouldn't load. Happens both server AND client side. 

Modlist:
AOA
Alex's Mobs
Forbidden and Arcanus
Valhelsia Core
GeckoLib
Blue Skies
Citadel
Dimensional Dungeons
JEI
BYG (Oh The Biomes You'll Go)
Structure Gel API
Terrablender (Forge)

**Comment by Tslat** [comment]
Intentional, for the time being

AoA is still revamping the entity models, and so to prevent crashing I've just made mobs invisible until we rework them
