### ISSUE TITLE
Armor toughness isn't in the bestiary tab

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3283]
It's not there
![image](https://user-images.githubusercontent.com/38159897/176986425-95a5dbde-92a4-457e-82c4-284b9a1b9af3.png)
![image](https://user-images.githubusercontent.com/38159897/176986441-0d0ad06f-85bc-4495-a0fc-999ba7f396ff.png)

**Comment by Tslat** [comment]
Goddamnit bestiary y u do dis

**Comment by Cruuk** [comment]
haha
