### ISSUE TITLE
Greatblades can't be used in changed control 

### ISSUE THREAD

**Issue by RobotPluto** [Tslat/Advent-Of-Ascension#3285]
**Mod Version**
AOA3 3.3.6

**Greatblades can't be used in chaneged control**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'controls'
2. Click on 'left click/right click (place block/break block)'
3. Reverse it
4. Try hitting a mob with any type of Greatblades

**Expected behavior**
It would do absolutely nothing

**Screenshots**
i can't screenshot a hitting screen

**Comment by EatingSilencer** [comment]
Does this bug still happen in the latest 1.16.5 or 1.19 version? If yes, you can try remaking the report in those versions, but this will never be fixed in 1.12.2.
