### ISSUE TITLE
Unable to gain Innervation experience in the server.

### ISSUE THREAD

**Issue by ShiinaMashiro520** [Tslat/Advent-Of-Ascension#3288]
**Mod Version**
What version of the mod are you on?
1.16.5 3.6.6

**Describe the bug**
Unable to gain Innervation experience in the server.

**Comment by Tslat** [comment]
What have you tried?
How do you know it's not working?

I need more information

**Comment by ShiinaMashiro520** [comment]
![屏幕截图 2022-07-07 145854](https://user-images.githubusercontent.com/108689272/177711470-e0cbfb61-2d8a-4cae-aee3-7e593bb1560d.png)

**Comment by Tslat** [comment]
Wonder if there's another mod interfering with it somehow

**Comment by ShiinaMashiro520** [comment]
I think it should not be the intervention of other modules, because I can normally gain Innervation experience in the case of a single machine.

**Comment by EatingSilencer** [comment]
Can you post your full modlist?

**Comment by ShiinaMashiro520** [comment]
![image](https://user-images.githubusercontent.com/108689272/178501429-896e7d33-e38f-4a6b-b2ff-3f3fff7acddf.png)
![image](https://user-images.githubusercontent.com/108689272/178501495-b015d206-80b6-4b10-ae7b-5b4282163724.png)
