### ISSUE TITLE
Not getting Farming XP while gathering crops with Simple Farming mod

### ISSUE THREAD

**Issue by thesaguaro** [Tslat/Advent-Of-Ascension#3291]
Mod Ver. AoA3-1.16.5-3.6.6

I'm playing a modpack that have a simple farming mod. There's a feature that allows player to farm crops using right click, without having to brake them. So, the issue is that I'm not getting any XP for Farming skill while right clicking the crops.

**Comment by Tslat** [comment]
Nothing I can do
Simple Farming should be sending block breaks when they break the block, but they don't.

Report it to them

**Comment by thesaguaro** [comment]
OK
