### ISSUE TITLE
Infusion Table Resprite

### ISSUE THREAD

**Issue by Equidas** [Tslat/Advent-Of-Ascension#3293]
As the main crafting station of the mod I felt it could use a more impressive design so this resprite gives its colours a nice overhaul while maintaining the rough shapes of the original. Also makes it a little more identifiable as a crafting station as an added bonus.

![2022-07-06_23 21 34](https://user-images.githubusercontent.com/63214689/177653295-595ada13-b113-43be-9882-b392593a24ce.png)

(File names were made for 1.16.5 so might need changing again for 1.19)

[Infusion Table.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9058953/Infusion.Table.zip)

**Comment by Cruuk** [comment]
The sides are nice, though the top is a bit too similar to Lunar creation table. Also, I think it should have a representation of the input slot. Pixel size gives too little room for it on the top, so maybe it could go on the side. Unsure
