### ISSUE TITLE
Rosidons tping you downward in certain scenarios

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3294]
Seems to be exclusive to roofed dims(?). It appears to occur if there is no space to tp to between you and the world height ceiling. However, this is only the case in specific scenarios I am not fully familiar with. Empirically, it mainly happens if you're close-ish to world height and have lots of space above you, like in this screenshot.
![image](https://user-images.githubusercontent.com/38159897/177908586-2669e950-61ed-4e6f-9666-254324f8d1d4.png)
But that's all I've been able to find

**Comment by Tslat** [comment]
Not sure if fixed
But made some changes
See if it's still broken after next update
