### ISSUE TITLE
Game Crash when Throwing Boss Items in Multiplayer

### ISSUE THREAD

**Issue by hongze-wu** [Tslat/Advent-Of-Ascension#3296]
**Mod Version**
What version of the mod are you on?
1.16.5-3.6.4
**Describe the bug**
In a multiplayer world, when player A throws an boss summoning items, there is a chance to crash player B's minecraft.

**To Reproduce**
Steps to reproduce the behaviour:
1. make a server
2. login to server with two account
3. let one play throw many boss items (crashes four times during we thorwn about 64 haunted_somewhat)

[crash-2022-07-09_02.24.31-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/9075686/crash-2022-07-09_02.24.31-client.txt)

**Comment by EatingSilencer** [comment]
Post the full crash report. You can just drag and drop the file onto the Github text window and it will upload it for you.

Also, update to the latest 1.16.5 aoa version (1.16.5-3.6.6).

**Comment by Tslat** [comment]
Are you using a server wrapper like catserver?

**Comment by hongze-wu** [comment]
> Are you using a server wrapper like catserver?

No. And it only crashes client side.

**Comment by hongze-wu** [comment]
> Post the full crash report. You can just drag and drop the file onto the Github text window and it will upload it for you.
> 
> Also, update to the latest 1.16.5 aoa version (1.16.5-3.6.6).

Alright, I posted the crash-report. 
And I did not update because I see nothing gonna fix those issues like this in the change log. And I believe the features are mostly the same as I was reading source codes.
