### ISSUE TITLE
Re-teleport to original world after entering portal

### ISSUE THREAD

**Issue by hongze-wu** [Tslat/Advent-Of-Ascension#3297]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
1.16.5-3.6.4 AoATeleporter
**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
Now, portals can move player back and forth when entered a portal because there is no portal cooldown.
The problem is more significant in a laggy server, because a player can be re-teleported back to original world causing network extra lag and/or extra loading cost, which lead to a disconnection. A play who login in a portal can still be teleported even if he have arrived in destination world before disconnected.
**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
One implementation is having player teleported out side the portal by adding -0.5 displacement in both x and z direction.
But it would be better to have a portal cooldown, just like vanilla nether portal.
**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
This issue is fine if portal in both worlds has the same coordinates; and it is much worse otherwise. Especially when you try to build a portal at y11, the generated portal usually cause infinate loop when trying to go back to original world through such portal.

**Comment by EatingSilencer** [comment]
Update to 1.16.5-3.6.6.

That being said I feel like this issue won't ever be fixed.

**Comment by Tslat** [comment]
moving the player out risks dropping them to their death
This isn't usually caused by laggy servers unless it's extreme - in which case I can't be responsible for incredibly laggy servers
This _does_ get caused by shitty server wrappers like catserver
