### ISSUE TITLE
Gravitators can stack despite having a durability

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#330]
**Mod Version**
AoA 3.0 with Forge 14.23.5.2768

**Describe the bug**
Gravitators can stack up to 64, which doesn't seem intentional since they now have a durability (which goes down depending on the number of blocks you fall). Using stacked gravitators depletes the durability of the entire stack, and only gravitators with the same durability values can stack on top of each other.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Advent Misc Items creative inventory tab (second page if no other mods are installed), or search "Gravitator".
2. Shift click on a stack of gravitators and put them into the hotbar.
3. Switch to survival mode.
4. Jump off of a small cliff while holding the gravitators in the main hand.
5. Split the stack of gravitators and notice that they all have the same durability.

**Screenshots**
![image](https://user-images.githubusercontent.com/12868968/53279142-d1079080-36c2-11e9-8294-23690f2513a2.png)

**Comment by Tslat** [comment]
Hilarious. And fixed
