### ISSUE TITLE
Cyclops new model texture animations

### ISSUE THREAD

**Issue by ThePixelL** [Tslat/Advent-Of-Ascension#3301]
aoa3.cyclops

New texture/animations/model

Maybe a new type of attack (will have to work on it)

[cyclops.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9088532/cyclops.zip)

**Comment by ThePixelL** [comment]
[Cyclops aoa2.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9088555/Cyclops.aoa2.zip)

**Comment by ThePixelL** [comment]
[Cyclops aoa2.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9088558/Cyclops.aoa2.zip)

**Comment by Tslat** [comment]
I can use the second one, but it'll need an attack animation
Also can we combine all animations into the same animation file please
