### ISSUE TITLE
Trickster new model animations texture

### ISSUE THREAD

**Issue by ThePixelL** [Tslat/Advent-Of-Ascension#3302]
aoa3.trickster

New model texture animations

:D

**Comment by ThePixelL** [comment]
whoops forgot to upload the new texture
[Trickster cyclops texture.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9088586/Trickster.cyclops.texture.zip)

**Comment by Tslat** [comment]
The idle anim definitely needs to be toned down or tweaked
Idle anims need to either look very natural, or very minimal, otherwise they look janky in game

The running anim also appears to be a bit slow 
And it'd need an attack anim

**Comment by ThePixelL** [comment]
[trickster animations.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9156072/trickster.animations.zip)

New animations here

**Comment by ThePixelL** [comment]
[Trickster animations.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9156097/Trickster.animations.zip)

Okay it should be fixed now, all merged into 1 json

**Comment by Tslat** [comment]
Combine into one zip pls so I have everything in one place
Atm your old zip contains the old bbmodel project with old stuff, and your new zip only contains the updated animations

**Comment by ThePixelL** [comment]
[Trickster.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9156191/Trickster.zip)

Bruh... 
Ight here's bb model, texture and json with all the animations
