### ISSUE TITLE
Mud brick style aoa bricks as placeholder textures

### ISSUE THREAD

**Issue by Technomancer666** [Tslat/Advent-Of-Ascension#3303]
Just all of aoa's bricks in the style of mc vanilla's mud bricks.
[block.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9088890/block.zip)
<img width="1792" alt="Screen Shot 2022-07-11 at 10 25 55 PM" src="https://user-images.githubusercontent.com/60552135/178395187-47740a09-0fa4-4e58-a0ce-982f265264c6.png">

**Comment by EatingSilencer** [comment]
These do look nice, but they don't appear to be in the style of vanilla's Mud Bricks? 
![image](https://user-images.githubusercontent.com/44556728/178461550-f6731a27-76a1-4b30-b1ec-d45e14cb94bf.png)

**Comment by Technomancer666** [comment]
They are all just recolored versions of mud bricks. The baron tiles are just sections of the baron stone bricks laid over the helllstone bricks (the other tiles were created in the same way). I tried to use as much as aoa’s og palettes as I could when recoloring them though so that may be making them look less like mud bricks.
