### ISSUE TITLE
Trickster Rework with full animations

### ISSUE THREAD

**Issue by ThePixelL** [Tslat/Advent-Of-Ascension#3305]
Trickster new model/texture/idle walking attack animations
[Trickster.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9098781/Trickster.zip)

**Comment by Tslat** [comment]
Can you merge this into the other trickster remodel post, this is just a duplicate
Also move the files into the bbmodel project and combine the anims into one anim file
Also see comments on that post
