### ISSUE TITLE
Fishix Rework with full animations

### ISSUE THREAD

**Issue by ThePixelL** [Tslat/Advent-Of-Ascension#3308]
New Fishix model/texture/animations (idle, walk, attack
[Fishix.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9108066/Fishix.zip)

**Comment by Tslat** [comment]
Its idle anim needs to be toned down - it's too exaggerated in movement for an idle animation
And the attack anim doesn't actually look like he opens his mouth, he just kinda adjusts it while he shoves his face into you
