### ISSUE TITLE
In version 1.12.2 allows unlimited XP bugs

### ISSUE THREAD

**Issue by haozaizai1** [Tslat/Advent-Of-Ascension#3311]
This may seem unlikely, but I also hope that in 1.12.2, unbreakable areas such as soul stones in the server or experience items obtained by destroying plants can be used to destroy grass or bricks to generate skills and experience that can be obtained indefinitely, and will soon reach the full level of skills

**Comment by EatingSilencer** [comment]
What? Can you clarify?
