### ISSUE TITLE
Charger has 2 different vision values

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3314]
In the Charger's entity file, it's 16
![image](https://user-images.githubusercontent.com/38159897/179831860-e3bc6ef0-696b-4840-af73-d4f2a7143360.png)

But in AoAEntityStats, it's 40
![image](https://user-images.githubusercontent.com/38159897/179831915-2b8e4a85-75c1-4220-8998-2d4570bb05e5.png)

Which one is it supposed to be

**Comment by Tslat** [comment]
Both

followRange is how long they'll see you once they've targeted you
searchRadius is how far away they'll be able to target you from
