### ISSUE TITLE
Rendering issue with Sand giant traps

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3316]
1. Their spawning animation does not play. They pop out of nowhere instead

2. Their rendering has a delay. In this image, they seem far from me, but in reality they are at normal spawning speed, they just aren't rendering the instant they spawn. The ones closest to me are invisible
![image](https://user-images.githubusercontent.com/38159897/179835119-a0ad1517-2f5a-4316-b004-6ff1a7cefc4e.png)

**Comment by Tslat** [comment]
Yeah geckolib currently has an issue with em, I've left it with Azure to resolve in time
