### ISSUE TITLE
Arcflower does not render correctly when in flower pot

### ISSUE THREAD

**Issue by RomanRayman** [Tslat/Advent-Of-Ascension#3317]
**Mod Version**
1.19/3.6.9

**Describe the bug**
When arcflower is putted in flower pot, some pixel are floating in mid-air

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Nowhere
2. Go to Utility lobby
3. In the north-west, see a pot flower on the bookshelf next to enchanting table.

**Expected behavior**
Flower rendered normally.

**Screenshots**
![2022-07-19_21 37 50](https://user-images.githubusercontent.com/86893332/179835412-1c46ab5b-3a89-4eda-9fc4-64ac86efff7a.png)

**Comment by Tslat** [comment]
Yeah.. that's just kinda how flowers work in pots
once it gets retextured we'll look at cleaning up the outside bits
