### ISSUE TITLE
Dark Beast moves almost as fast as the player's running speed

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#332]
**Mod Version**
3.0

**Describe the bug**
The Dark Beast moves almost as fast as the player can run, which doesn't seem intentional given its health and damage.

**To Reproduce**
Steps to reproduce the behaviour:
1. /summon aoa3:dark_beast
2. Switch to survival mode

**Comment by Tslat** [comment]
Has been changed
