### ISSUE TITLE
Giants don't save properly

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#3326]
-none of them keep their target

-leafy giant loses its shield, but it becomes permanently invincible

-sand giant's traps disappear

-stone giant's silverfish lost their healing behavior (although looking at the code I'm not sure it's possible to fix this)

I forgot to test whether wood giant's bark gets saved.

**Comment by Tslat** [comment]
Can't seem to replicate the leafy giant thing

**Comment by DiamondWalker** [comment]
Tested it again and I could kill it this time. Must have been missing a bush baby earlier.

The shield does go invisible, though.

P.S. tested that sand giant freeze theory we talked about on discord. It seems fine.
