### ISSUE TITLE
Updated army block texture

### ISSUE THREAD

**Issue by Technomancer666** [Tslat/Advent-Of-Ascension#3330]
Idk if the army block has been updated or not yet... so here is updated texture for it.
<img width="515" alt="Screen Shot 2022-07-21 at 10 53 59 PM" src="https://user-images.githubusercontent.com/60552135/180352941-80c542a8-8451-41cb-b598-3079c9ca81b1.png">
[armyblock.zip](https://github.com/Tslat/Advent-Of-Ascension/files/9164171/armyblock.zip)

**Comment by EatingSilencer** [comment]
I think this texture is better for some kind of brick rather than Army Block. Also, we don't know if Army Block is staying in the mod or not.

**Comment by Seishan123** [comment]
I'm going to be honest, but somehow I see the Bone Horn being a summoning item for the Skeletal Army over the Tyrosaur. Armies in medieval times used horns to signal when to attack, and fighting an undead army after blowing said horn makes more sense to me than using a block.
Onto the texture... perhaps changing the brick-like texture to a banner pattern of sorts (and having said banner pattern as a possible drop) would be more suitable for the Army Block.
