### ISSUE TITLE
Health Bar Resprite

### ISSUE THREAD

**Issue by Equidas** [Tslat/Advent-Of-Ascension#3332]
I've resprited the healthbar to give it a more refined appearance more in line with traditional healthbars. I've kept the quarter markings (although they're a little more subtle) and made changes to a few of the colour palettes to further distinguish them from one another. Any feedback is appreciated - I'm unsure as to whether the damage bar should be lightened further for example

![health_bar 4x4](https://user-images.githubusercontent.com/63214689/180604111-026729f4-06fc-4166-9b77-67dfe6f2ba37.png)

I've noticed that these sprites actually look much darker ingame, and I don't know whether this is intended?

Hit
![1](https://user-images.githubusercontent.com/63214689/180603116-e0293b7f-ce3d-424c-9935-3062cdef4f58.png)

Heal
![2](https://user-images.githubusercontent.com/63214689/180603126-7e2fd3b8-771b-4d94-b7e0-9e0b06bb5151.png)

Poison
![3](https://user-images.githubusercontent.com/63214689/180603131-3603f023-835a-4c8b-a055-dc21c1629c1e.png)

Absorption
![4](https://user-images.githubusercontent.com/63214689/180603141-a3016862-b26b-4683-bb9f-64d37d9b3e4a.png)

Wither
(might be nice to see the text lightened a little as the lack of contrast persists on the original sprite)
![5](https://user-images.githubusercontent.com/63214689/180603149-aab061e8-e161-40e7-909a-4ada995ab92b.png)

Health Boost
(pink text for this one would also look better)
![6](https://user-images.githubusercontent.com/63214689/180603152-3b6460fe-3812-4bab-9b78-5f28aed907a9.png)

Hardcore
![8](https://user-images.githubusercontent.com/63214689/180604572-84d94512-a45e-45ea-acaf-42ae38d4d149.png)

White background for better contrast
![7](https://user-images.githubusercontent.com/63214689/180603233-78c7103f-39e9-485f-977f-92fd40686583.png)

I don't think there's any way of triggering the frozen status effect in 1.16.5 so I don't have any ingame screenshots of it*

**Comment by Tslat** [comment]
Personally I'm still tossing up on these, but given that it looks like they have very consistent formatting and no project file was ever shared, we don't really have any reliable way of extending this to other health conditions, so I'm gonna have to close this
