### ISSUE TITLE
Incompatibility 

### ISSUE THREAD

**Issue by Maxisanmar** [Tslat/Advent-Of-Ascension#3334]
**Mod Version**
What version of the mod are you on?

[AoA3 1.16.5-3.6.6]

**Describe the bug**

TLauncher crashes whenever i run AOA and MoreVanillaWeapons mod together. I asked on a MinecraftHelp subreddit and apparently both mods try to change the same thing. Heres the link to the post where the mod tell's where's the problem

https://www.reddit.com/r/MinecraftHelp/comments/w8bg6m/problem_with_mod_advent_of_ascension_java_launcher/

Here's the log

https://pastebin.com/RF6BcrPL

**To Reproduce**

Steps to reproduce the behaviour:

**Expected behavior**
Game crashes and cannot start
**Screenshots**

**Comment by Tslat** [comment]
MoreVanillaWeapons needs to change their mixin to require = 0 so it doesn't crash the whole game when another mixin has done their mixin for them
