### ISSUE TITLE
Silverfoot should have long enough range to be able to see you across the iromaze

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#334]
After 3.0, Silverfoot is a lot more fun to fight because of his pathfinding. The fact that he could be anywhere, at anytime, makes the fight quite fun. However, I think his sight should be extended to the point he'll be able to see you anywhere in the iromaze. It's quite common to have situation where you have to run, and once you stop running, you wait, expecting him. However, he never arrives, and you have to do the maze a second time just to find him. It also ruins the "keep moving" feeling, and makes it fairly easy to heal mid-fight.

**Comment by Tslat** [comment]
Done
