### ISSUE TITLE
Portal lit but unable to enter any dimensions 

### ISSUE THREAD

**Issue by Notsureofausername** [Tslat/Advent-Of-Ascension#3346]
Mod Version: AoA3-1.19-3.6.10 

Bug description: I tried opening my first portal and it made the sound and showed the portal blocks but when I went to walk into the portal nothing happend

Steps to reproduce the behaviour:
1: obtain the blank realmstone like normal
2: complete the lelyetia challenge
3:use the stone on the portal
4: cannot enter the portal even though it's lit

Expected behavior:
I expected to be able to enter the portal and access the dimension

(I do not have any current screenshots)

**Comment by EatingSilencer** [comment]
Most dimensions have not been added back yet.

**Comment by Thisguyneedshelp** [comment]
im having this issue with the nether, granted its a modpack but i suspect this mod might be the one influencing it, especially after his testimony

**Comment by Thisguyneedshelp** [comment]
after some testing it seems that this mod was unrelated to the problem
