### ISSUE TITLE
Does Rosidian Armor work properly in 1.16?

### ISSUE THREAD

**Issue by mercifulbird** [Tslat/Advent-Of-Ascension#3347]
Contrary to its description no rosid has been spwaned while taking damage, even upon taking a damage larger than 4, which should guarantee to spwan a rosid as the full set bonus.
The mod is in the newest version on 1.16.5. I wonder if there is a bug or if there are any server property settings that prevented rosids to spawn.

**Comment by EatingSilencer** [comment]
I think the rosids got removed with the intention of readding them with a Creation skill revamp. But that revamp won't be coming in 1.16.5, so rosidian armor is broken.
