### ISSUE TITLE
Invisible Entities

### ISSUE THREAD

**Issue by saiakesani** [Tslat/Advent-Of-Ascension#3351]
**Mod Version**
V33

**Describe the bug**
Was streaming luckily when this had happened. (https://www.youtube.com/watch?v=cYwfqeGz9H0)

**Expected behavior**
well i expected the entities including my own player model to be visible

Extra Note, upon downloading this modpack the owner of the discord server Hazard had said this to me, when i never modified the modpack once i just figured hey this seems close enough to another AoA i played so ill see what its got to offer. didnt even bother updating the mods in it, asked them if it was a good idea and they said it could break some things. 
![image](https://user-images.githubusercontent.com/81065354/183269969-d1944af5-c890-46ad-9a12-9a005ef47bf5.png)

**Comment by Tslat** [comment]
This is not an AoA issue.
The fact that even impacted the player model pretty clearly shows that lol
