### ISSUE TITLE
Nowhere Crashing

### ISSUE THREAD

**Issue by ihaveacrushonjaidenanimations2068** [Tslat/Advent-Of-Ascension#3356]
**Mod Version**
What version of the mod are you on?
1.19.1-3.6.12

**Describe the bug**
When trying to go to Nowhere, the game freezes for a bit then crashes, leaving an error

**To Reproduce**
Steps to reproduce the behaviour:
1. Place down a "Nowhere Portal" either as a block or a structure.
2. Go through it
3. Wait a bit

**Expected behavior**
I thought it would send me there without anything wrong.

**Screenshots**

**Comment by Tslat** [comment]
Unable to replicate and no error provided

**Comment by ihaveacrushonjaidenanimations2068** [comment]
[crash-2022-08-09_16.16.55-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/9297401/crash-2022-08-09_16.16.55-server.txt)
crash log

**Comment by Tslat** [comment]
Was this in singleplayer? or in LAN?
Also, update your forge

**Comment by ihaveacrushonjaidenanimations2068** [comment]
Singleplayer, also I tried it with 42.0.9, still crashes

**Comment by Seishan123** [comment]
Cannot invoke "net.minecraft.server.level.ServerLevel.m_46472_()" because "world" is null
**mod:geckolib3 (incompatible)**
Incompatible mods usually means that there is a .class file somewhere in that mod which conflicts with another .class file.
My best guess is that one of these files conflicts with PortalForWorld (PortalBlock.java:238) and makes it designate itself as null.
Which causes your crash.
Firstly, try running the game without gecko-lib. And try to replicate the bug, if it persists, send over the crash log for that replication to see what happened.

**Comment by ihaveacrushonjaidenanimations2068** [comment]
![2022-08-10_20 43 32](https://user-images.githubusercontent.com/43296868/183904316-2375d1b7-579f-4808-80de-c2973553bd7a.png)
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/9300088/latest.log)
I can't run the game without geckolib

**Comment by Seishan123** [comment]
I feel stupid... forgot that happened a while ago...
Seems as though I'm going to have to look to see which file conflicts in the mods themselves... Oh boy, that will take a while.

**Comment by Seishan123** [comment]
The only other suggestion is based on ticking entity solution. Killing the entity. In this case... the crash log specifies the player itself... I hope your world isn't hardcore. If so... I would recommend going through a back-up through a back-up dedicated network.

**Comment by ihaveacrushonjaidenanimations2068** [comment]
I see. Don't worry, I usually am on creative so...lol

**Comment by Tslat** [comment]
I'm going to close this because I believe the only way this can happen is if a mod causes datapack loading to fail, or some other very serious issue is occurring.

If it happens again after the next AoA release, provide the full latest.log from the session it crashed
