### ISSUE TITLE
Upgrade Kit Duplication in 1.16.5

### ISSUE THREAD

**Issue by mercifulbird** [Tslat/Advent-Of-Ascension#3357]
**Mod Version**
1.16.5-3.6.6

**Describe the bug**
When more than one upgrade kit is put into the divine station, an upgrade does not consume the upgrade kit but duplicates it instead.

**To Reproduce**
1. Open divine station.
2. Put more than 1 upgrade kit and an upgradable weapon into the crafting gui.
3. Craft the upgraded version of the weapon by taking it out from the product slot.
4. See the number of upgrading kits increased.

**Expected behavior**
One upgrade kit should be consumed.

**Screenshots**
![image](https://user-images.githubusercontent.com/73424266/183766308-f7d160d8-dc03-45bc-a9d9-9545c5d2200c.png)
![image](https://user-images.githubusercontent.com/73424266/183766445-c60eeb0f-479f-4a33-9853-4b17aa7bf760.png)

**Comment by mercifulbird** [comment]
Besides it occurs to me that the lunar upgrade kit just does not drop from any lunar mob (I killed 480 reflutcs and about 200 inmate X's yet none had dropped for me).

**Comment by mercifulbird** [comment]
> Besides it occurs to me that the lunar upgrade kit just does not drop from any lunar mob (I killed 480 reflutcs and about 200 inmate X's yet none had dropped for me).

The lunar kits in my inventory are spawned in with commands.

**Comment by Cruuk** [comment]
Still happens in 1.19.2
