### ISSUE TITLE
I cant go to nowhere portals!

### ISSUE THREAD

**Issue by CarlosHO1** [Tslat/Advent-Of-Ascension#3364]
**Mod Version**
What version of the mod are you on?
1.16.5
**Describe the bug**
When I go to nowhere and try to enter any portal it dosent teleport me 
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/111294110/184652287-cc5b00da-76be-42be-9d59-98dc244ad1f4.png)

**Comment by Tslat** [comment]
They're not active in 1.16.5
