### ISSUE TITLE
Cant teleport

### ISSUE THREAD

**Issue by IdDevlive** [Tslat/Advent-Of-Ascension#3365]
**Mod Version**
3.6.6

**Describe the bug**
When I step in portal, it doesnt' teleport me, only nether portal works correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/111353148/184857651-43f6bb9e-7b68-4c1d-97b0-0208179bea5d.png)

**Comment by Tslat** [comment]
Provide a log file

**Comment by IdDevlive** [comment]
> Provide a log file

Where I can find it? Server is on aternos. I cant find it

**Comment by Mii283** [comment]
I have same issue on the same version, and these are mods in my server.
![image](https://user-images.githubusercontent.com/111569446/185594550-2a753121-fece-43b3-a829-aff5baaac37d.png)

This is the logfile
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/9381434/latest.log)

**Comment by Tslat** [comment]
![image](https://user-images.githubusercontent.com/7098525/185601927-b41e87ca-932e-43e8-84e1-6c2434736fe6.png)
