### ISSUE TITLE
Dying by the void in Nowhere counts as an actual death, not a fake death that just TPs you back to lobby

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3366]
In other words, you can still lose all your stuff in Nowhere if you die by Void. I feel like it should be consistent and have void deaths also be a fake death that just TPs you back to lobby. Some boss arenas are open and have the void as a hazard

**Comment by Tslat** [comment]
Void deaths are supposed to, and they were..
Wonder if I broke somethin
