### ISSUE TITLE
Custom Ornate Trophy

### ISSUE THREAD

**Issue by Inverseder** [Tslat/Advent-Of-Ascension#3367]
Hi,
I want to make customs trophies for my modpack with custom displaying item entity.
I make this command: `/give @p aoa3:ornate_trophy{BlockEntityTag: {EntityID:"minecraft:diamond_block", OriginalTrophy: 1b}}`
I get my trophy but nothing on it, can you help me with the command please?
Thanks you

**Comment by EatingSilencer** [comment]
Ask on the [Discord](https://discord.gg/DNYqNNq) server.
