### ISSUE TITLE
Cotton Candor Boss Fight Revamp

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#3377]
Having fought Cotton Candor enough times to give me diabetes over and over again, I've only just realised something. He is the longest boss fight due to the weapons you HAVE to bring in, and that you have to swap those weapons constantly. While I enjoy the idea of a boss having immunities to almost everything, I feel as if it's time to make Cotton Candor a boss, rather than the grinding disaster he is.
To start off with, the immunities. He goes through 5 forms randomly. I feel as if just having one form of Cotton Candor would be enough, but every so often he generates a shield of a certain colour. While the shield is up, he will instead heal from damage sources, until the shield is broken with the correct staff (i.e. White shield is broken by Wind Staff). This can take several hits.
While the shield is down, you can hit him with Staffs or Blasters, but not anything else. The shield itself doesn't stop Cotton Candor from attacking, merely makes it so the player has to swap weapons somewhat often to continue to deal damage.
With this new mechanic, perhaps a new staff can be introduced as a drop as well. I don't have a name for this staff, but it would generate a shield around the player which protects them from up to a portion of their health (15%?) This staff's effects run out after 3 minutes.
I feel the attack pattern can somewhat be added onto, so Cotton Candor charges the player semi-randomly which allows him to deal Melee Damage, and disable shields if they are used to block. The player may still be able to dodge, but it provides no additional benefit to do so. The Shield mentioned above should generate after the charge even if it is not a successful hit.
I know there is a planned Boss Update, but seeing the new Cotton Candor would be somewhat amazing to see.

**Comment by Tslat** [comment]
We know :)
He'll get reworked, don't worry
