### ISSUE TITLE
Strange occurrence with the alternative boss lobby and getting killed by Smash

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3381]
While I was testing respawns in the alternative boss lobby by getting killed by Smash, this happened. It worked the first time, but the second time it seemed like I was just falling through the void, got to ~-300 and still haven't taken void damage yet, none of the resources were updating, and when I tried to pause and exit, it was stuck on the "saving world" dirt screen. Had to close the game with ctrl alt del.

Currently unable to replicate, but that is how I've seen it so far

Here is the log

https://paste.gg/p/anonymous/48bb889e2d3d4b02b89294027755d4df

**Comment by Tslat** [comment]
Unable to replicate so far, and the log says nothing
