### ISSUE TITLE
Dweller clones explode by themselves when despawning, but don't explode when killed

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#339]
**Mod Version**
3.0

**Describe the bug**
Dweller clones explode by themselves (without player interaction) when despawning a few seconds after being spawned. This damages and eventually kills the original Dweller that spawns them, and causes many random explosions in the Deeplands. They also don't explode if you kill them before they despawn.

**To Reproduce**
Steps to reproduce the behaviour:
/summon aoa3:dweller, or travel to the Deeplands with mob spawning enabled

**Expected behavior**
The clones only explode when killed by the player.

**Comment by Tslat** [comment]
Handled
