### ISSUE TITLE
Enable teleportation in nowhere

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#3394]
I'm not sure if it was disabled for a specific reason, but I think teleportation shouldn't be disabled. If there is a reason, maybe it could be enabled only for boss fights. There are valid uses for it there (i.e. getting knocked off an arena), and I can't think of any way to cheese with it (that can't be done some other way).

**Comment by Tslat** [comment]
Yeah this isn't happening
The only real reason _to_ teleport at bosses is to cheese

Not to mention all the other potential issues it has
