### ISSUE TITLE
Ancient portal works awfully with ping above 80-90.

### ISSUE THREAD

**Issue by dmitrii-mitrofanoff** [Tslat/Advent-Of-Ascension#3398]
**Mod Version**
3.6.6. for 1.16.5, most probably issue exists everywhere

**Describe the bug**
With high ping modded portals works awfully. Standart portals are still fine.

**To Reproduce**
1. Open singleplayer game for multiplayer on one machine.
2. Get ping high enough any way - using VPN without direct tunnel, etc.
3. Create any ancient portal.
4. Try to move in and return into Overworld.

**Expected behavior**
You will be rollback to the portal frame and be loaded back into world you come from. Depending on ping and luck you will have this issue in 90-99% percents of attempts, which makes mod dimension experience almost unplayable.

**Suggestion how to fix**
Add accessibility setting for high ping, allow block jump into portal more then once per n seconds, for example 5. Or option to return teleport-behaviour of portals to non-modded ones.

**Comment by Tslat** [comment]
You got aether installed?

**Comment by dmitrii-mitrofanoff** [comment]
Nope. I have bunch of mods, but this was the thing even then we've have only aoa+create. Also, we was able reproduce this on clear AoA.
Offtopic: I've even don't know version of aether which will work on 1.16.5 with AoA exists.

**Comment by Tslat** [comment]
Interesting

In theory the ping shouldn't make a difference
But I'll see about doing something with it in future versions
