### ISSUE TITLE
Smash's axe swing attack doesn't disable shields (and Warden can't disable shields suddenly?)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3400]
I am very unsure on why this is happening. It still happens if only AoA/Geckolib are the only mods in the mods folder. Vindicator can still disable shields with an Axe, though

**Comment by Cruuk** [comment]
Just checked, this bug still occurs in newly-created worlds. Unfortunately, I am currently not sure what further info I can give

**Comment by Tslat** [comment]
Forge bug
