### ISSUE TITLE
Hauling rod bobber entity crash

### ISSUE THREAD

**Issue by RogertheCroc** [Tslat/Advent-Of-Ascension#3401]
**Mod Version**
Forge 1.19.2-3.6.14

**Describe the bug**
Game crashes when attempting to fish with hauling rod

**To Reproduce**
Steps to reproduce the behaviour:
1. Use a hauling rod2. 
2.wait for the bobber to hit water 

**Expected behavior**
The bobber would hit the water without issue and the normal process for fishing with a hauling rod would happen. 

**Screenshots**

**Comment by Tslat** [comment]
Crash report?

**Comment by RogertheCroc** [comment]
> Crash report?

sorry about that, here it is,

[crash-2022-09-02_14.50.31-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/9482837/crash-2022-09-02_14.50.31-server.txt)

**Comment by Tslat** [comment]
What biome are you trying to fish in?

**Comment by RogertheCroc** [comment]
I tried in several overworld biomes like plains or beaches but it happens in the nether too.
