### ISSUE TITLE
Portal not letting me through

### ISSUE THREAD

**Issue by Gloomitrix** [Tslat/Advent-Of-Ascension#3405]
**Mod Version**
What version of the mod are you on? I am on 1.19.2

**Describe the bug**
I built multiple portals and the do work the light up and everything but when it comes to going through them they just don’t expect for the Nether one, the Nether portal with this build lets me through, mind you it take a while to actually load up but if the others loaded up I would be fine with that.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Curse forge’
2. Click on 'create mod pack and add Advent of Ascension (Nevermine), Architectury API (Fabric/Forge), Better Animations Collection, Better Third Person, Biomes O’ Plenty, First-Person Model (Forge/ Fabric), GeckoLib, Geode+, Hopo Better Mineshaft, Hopo Better Ruined Portals, MCA Reborn [Fabric/Forge], Nature’s Compass, Oh The Biomes You’ll go, playerAnimator, Puzzles Lib, TerraBlender (Forge), The Twilight Forest, This Rocks! (Forge)'
3. Play the game and build a portal 
4. Try any of the stones that are connected to the mod

**Expected behavior**
I expected when I walked into the glowing portals that they would take me to a new realm instead I was able to walk through them and stand in the middle of them seeing if that would work

**Comment by Tslat** [comment]
AoA3 for Minecraft 1.18.2 and up is not ready for survival

As part of the requirements of porting to the newer render system and worldgen system, AoA has some work to do yet to be ready for survival play on 1.18.2 and above. Until then, most mobs and dimensions are missing, and the mod itself is only intended for creative use or testing

Use the 1.16.5 version for now

You should also join the discord
