### ISSUE TITLE
AoA mob spawns broke

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3409]
Have not seen any AoA overworld mob

**Comment by P3rf3ctXZer0** [comment]
for what version? THEY said 1.18.2 is ALPHA

**Comment by Cruuk** [comment]
> for what version? THEY said 1.18.2 is ALPHA

1.19.2-3.6.15. THEY have been working in the past few versions, but it seems they did a certain changed with mob spawns too harsh. I did see 1 after this post, but it took quite a while
