### ISSUE TITLE
Change NPC restocking

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3419]
My current issues with it is that the 24 block thing isn't exactly clear. Also, I know I am biased with this one, but it seems to never work at all, and it's a pain in the ass to test.

1 solution I have is just having a straight 5 minute cooldown for an individual trade to restock every time it runs out, that simple. I don't know if it's the best solution, but the current system has just been obtuse and confusing in terms of it actually working

**Comment by Tslat** [comment]
what's the point of the cooldown then

**Comment by Cruuk** [comment]
> what's the point of the cooldown then

I didn't think it through very much, I just thought you wanted a cooldown of some kind
