### ISSUE TITLE
Netherrack shouldn't work with Foraging

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#342]
I know Netherrack is the "stone" from the Nether, but it has 1 big difference compared to the other stone types... It's really easy to break. I think vanilla stone takes twice the amount of time to break when compared to Netherrack.

Basically Nether is gonna be extremely powerful for Foraging, maybe a bit too powerful?

**Comment by Angrydog001** [comment]
Well, is that exactly meant to a bug?

**Comment by Sagisolar** [comment]
You could have it rate lowered with Netherrack.

**Comment by Tslat** [comment]
Handled
