### ISSUE TITLE
Compatibility with other mods' arrows

### ISSUE THREAD

**Issue by Kasualix** [Tslat/Advent-Of-Ascension#3428]
**feature**
Arrows from other mods with specific features should work with aoa bows.

**background**
I used the alacrity bow with explosive arrows from Xtra Arrows and Archer's Paradox. They all turned into vanilla arrows when they were shot out. 
version: Minecraft 1165, aoa-3.6.8

**Comment by Tslat** [comment]
Can't.

Don't have a good way of tracking the arrow without using a custom arrow entity
