### ISSUE TITLE
Mysterium portal structure's portal blocks can be replaced with giant mushrooms

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#343]
**Mod Version**
3.0

**Describe the bug**
The portals in the Mysterium portal structure can be replaced with giant mushrooms.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a world with seed -5644277795189959102
2. Enter Mysterium
3. Teleport to -90 40 145

**Expected behavior**
The portal blocks would replace the giant mushrooms.

**Screenshots**
![image](https://user-images.githubusercontent.com/12868968/53283531-c4a02980-36fc-11e9-9581-e1d066ef5879.png)

**Comment by Tslat** [comment]
Has been dealt with
