### ISSUE TITLE
Give elite bosses custom skyboxes

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#3430]
Title. Elite bosses could have their own custom skyboxes (like how parkour areas have a different skybox than the rest of nowhere). Small change that would make them feel more impactful imo. Not sure how long making these skyboxes would take, though. Maybe some parts of them could be reused with different colors/textures.

**Comment by Tslat** [comment]
Goes against the aesthetic and lore I'm going for
Would be neat though
