### ISSUE TITLE
SBL mobs act weird in water

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3437]
They immediately shoot up to the surface and bounce on the surface. They are unable to go underwater, which breaks the gimmick of certain mobs like Chomper

**Comment by Tslat** [comment]
Isn't this the default of all mobs (except chomper)?

**Comment by Cruuk** [comment]
> Isn't this the default of all mobs (except chomper)?

Yes, but the speed at which sbl mobs launch vertically through water is very fast. Far faster than other mobs. It causes them to constantly jump while in water, I've seem them jump up to 2-3 blocks while on the surface of water. Also, sometimes they'll instead just stay in place and spin around. In general, both factors cause them to really struggle to pathfind towards a player while in water

**Comment by Cruuk** [comment]
It seems that Sasquatch and the giants (except ice for obvious reasons) float up at normal speeds to the surface of water, the others shoot up very fast
