### ISSUE TITLE
"ghast" mobs (Anemia, Voliant, etc.) have shorter vision?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#344]
I'm not sure if I'm wrong, but I think the "ghast" mobs have shorter vision compared to their 1.7 incarnations. I even tested it with a vanilla Ghast and it seems the vanilla Ghast had farther vision? Not sure

Also Construct of terror seems to shoot slower now, intended?

**Comment by Tslat** [comment]
Two different ones in one report?

Not sure what their look value was in 1.7.10, but it seems more or less ok in 1.12 with the amount I've given them for now
