### ISSUE TITLE
King Shroomus

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#345]
King Shroomus appears to have much slower walkspeed than it's 1.7 incarnation... That's all I have to say

Maybe we should have a bug reports section in the Discord so I don't have to spam git threads for small things like this? Though I guess I can always make a git thread that's a compilation of all this stuff...
EDIT Oh I made this one so fast I forgot to give it a proper name...

**Comment by Tslat** [comment]
Treat it as a new version of the mod, and consider it objectively for how it is now
