### ISSUE TITLE
Make mobs attack each other

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#3457]
A simple feature that I think would make AoA's mobs feel a lot more detailed and lively is having them attack other mobs/animals, similar to how wolves attack sheep and piglins attack hoglins. Chompers, for example, should target all non-hostile animals below a certain size limit. Ancient golem should attack humanoid mobs, like zombies (if you add some way to heal them, this could make them useful for mob grinders).

The only issue is them possibly getting distracted hunting down other mobs rather than the player. If this becomes an issue, maybe make them prioritize?

**Comment by Tslat** [comment]
Seems like a major balance issue though

**Comment by DiamondWalker** [comment]
> Seems like a major balance issue though

Yeah was worried about that. Vanilla manages to make it work, but that's mostly with neutral mobs (except hoglin).

I don't think the chomper example would be a big issue, since killing animals doesn't change much. The ancient golem thing might cause some problems since it'll end up helping you by clearing out surrounding mobs.

It also depends on the spawn rates, which I haven't tested at all.

**Comment by Tslat** [comment]
Might be worth discussing in Discord
