### ISSUE TITLE
Improve compatibility with bettercombat

### ISSUE THREAD

**Issue by 48004800** [Tslat/Advent-Of-Ascension#3459]
This MOD adds many large weapons that can increase the attack range of players.

However, these large weapons will not increase the attack distance under the influence of better combat mod.

https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine#c1797
I can change the attack distance of weapons by modifying json, but it is too troublesome to modify one by one.
![image](https://user-images.githubusercontent.com/78255094/192922609-c39afd0c-5e25-448a-affd-633fbde93f43.png)

**Comment by Tslat** [comment]
So let me just get this straight:

AoA works perfectly fine on its own, and with other mods. Its attack reach works just fine, and everything works.

Then you add BetterCombat, and it breaks.

That doesn't sound like AoA's problem?
If the other mod wants to break things, then it should be on that mod to make itself compatible

**Comment by 48004800** [comment]
> So let me just get this straight:
> 
> AoA works perfectly fine on its own, and with other mods. Its attack reach works just fine, and everything works.
> 
> Then you add BetterCombat, and it breaks.
> 
> That doesn't sound like AoA's problem? If the other mod wants to break things, then it should be on that mod to make itself compatible

I have contacted the author of Better Combat. The result is as shown in the picture

**Comment by 48004800** [comment]
In fact, you only need to add the corresponding json file to the mod
https://github.com/ZsoltMolnarrr/BetterCombat
You can modify attack distance, attack animation, and handheld weapon animation through json. However, players need to do it themselves. I hope mod can add this function.

![image](https://user-images.githubusercontent.com/78255094/192938408-0f68f9d4-e0e2-4a15-bd0e-97aa51ad9498.png)
![image](https://user-images.githubusercontent.com/78255094/192938476-c3af9109-d77f-4673-8304-594fc9255513.png)
![image](https://user-images.githubusercontent.com/78255094/192938541-83f18631-e274-4d65-8e82-4d4fec6f8abf.png)

**Comment by 48004800** [comment]
I completed it myself. It is acceptable if mod does not support it
