### ISSUE TITLE
Sniper bullets have issues going through grass

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#346]
(hopefully the last one for today)
**Mod Version**
3.0

**Describe the bug**
Unlike regular bullets, Sniper bullets can't go through grass most of the time

Due to the way they work, you can make them go through the grass if you shoot the mob from *very* specific distances. Besides that though they don't go through

**To Reproduce**
Steps to reproduce the behaviour:
1. Shoot a mob through grass with a Sniper

**Expected behavior**
Sniper bullets going through the grass like other physical projectiles

**Comment by Tslat** [comment]
Unable to replicate - and sniper slugs _are_ the same bullet types as other bullets, they're functionally the same.
Maybe you jsut had some bad luckwith a hitbox clipping a block or something?
