### ISSUE TITLE
my skill get reset

### ISSUE THREAD

**Issue by ishanganesh** [Tslat/Advent-Of-Ascension#3461]
**Mod Version**
1.16.5

**Describe the bug**
so i made a Minecraft server and was playing with my friends the server is 1 month long everything was going well until this bug occurred  our skills got reset when we deaded which unusual we had  hearts but it went away and its now annoying its been 1 day since this bug occured 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**
![Screenshot (287)](https://user-images.githubusercontent.com/108147553/193745442-6785ae12-e188-4d1f-b7c9-e441d1aa3578.png)

**Comment by ishanganesh** [comment]
the skill screenshot doesn't work

**Comment by Tslat** [comment]
Your skills don't look reset, you still have 60.7 health

**Comment by ishanganesh** [comment]
that was before i got reset
i had to kill my self
for it to work
