### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Kasualix** [Tslat/Advent-Of-Ascension#3462]
**Mod Version**
1.16.5-3.6.8

**Describe the bug**
Game crashed
latest.log: https://pastebin.ubuntu.com/p/WRjntxtmNm/

> java.lang.NullPointerException: Cannot invoke "net.tslat.aoa3.player.skill.AoASkill.getRegistryName()" because the return value of "net.tslat.aoa3.player.skill.AoASkill$Instance.type()" is null
> 	at net.tslat.aoa3.client.render.custom.AoASkillRenderer$1.renderInHud(AoASkillRenderer.java:53) ~[aoa3:1.16.5-3.6.8]
> 	at net.tslat.aoa3.client.gui.hud.toasts.AbilityUnlockToast.func_230444_a_(AbilityUnlockToast.java:48) ~[aoa3:1.16.5-3.6.8]
> 	at shadows.toaster.BetterGuiToast$BetterToastInstance.func_193684_a(BetterGuiToast.java:104) ~[toastcontrol:4.4.0]
> 	at shadows.toaster.BetterGuiToast.func_238541_a_(BetterGuiToast.java:36) ~[toastcontrol:4.4.0]
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:979) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_213241_c(Minecraft.java:1943) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_213231_b(Minecraft.java:1911) ~[?:?]
> 	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.cleanupBeforeMinecraft(InGameCatcher.java:52) ~[notenoughcrashes:?]
> 	at net.minecraft.client.Minecraft.handler$bfk000$beforeCleanUpAfterCrash(Minecraft.java:7567) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_71398_f(Minecraft.java) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:630) ~[?:?]
> 	at net.minecraft.client.main.Main.main(Main.java:184) ~[Neverise.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]

maybe related: 
https://github.com/Tslat/Advent-Of-Ascension/issues/3178
https://github.com/Tslat/Advent-Of-Ascension/issues/3150

**Comment by EatingSilencer** [comment]
For Tslat's reference, the version actually being used is 1.16.5-3.6.8.

**Comment by Kasualix** [comment]
Oh I got it wrong, it has been edited to the correct version.

**Comment by FoxyFine** [comment]
the same problem. have you solved it?

**Comment by Kasualix** [comment]
> the same problem. have you solved it?

No
 :(

**Comment by Kasualix** [comment]
solved
incompatible with toast control
