### ISSUE TITLE
Do non-Overworld ores have a lower harvest level than they're supposed to

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3466]
Despite being explicitly stronger than Diamond, Emberstone can be mined with Iron. All the other ores in <code>needs_iron_tool</code> (except Runium kind of) are all ores in T1 dims, while all the ores in <code>needs_diamond_tool</code> are the T2+ ones.

Before, the T1 ores required Diamond, while the T2+ ones required something higher than Diamond (I guess in this case it would be Netherite and the ones at the same level as Netherite), so I feel like they should all be moved up a harvest level (except Runium)

**Comment by Tslat** [comment]
I had a reason for doing this and tbh I can't really remember why, nor does it make much sense in hindsight
