### ISSUE TITLE
Elusive will apply the damage it takes to player

### ISSUE THREAD

**Issue by 13930107167** [Tslat/Advent-Of-Ascension#3473]
Mod Version: AoA3-1.16.5-3.6.8

In the Abyss dimension, if Elusive is being attacked by other mobs. It will do the player the same damage.

**Comment by 13930107167** [comment]
When I fought this boss, I was on a 3-block-high platform and there certainly was no mob attacking me while I was constantly being knockback. That's when I find this thing.

**Comment by Tslat** [comment]
No it doesn't
