### ISSUE TITLE
[1.16.5]Bug AOA3.5.4 problem

### ISSUE THREAD

**Issue by haozaizai1** [Tslat/Advent-Of-Ascension#3475]
Can AOA3.5.4 support java11, because I want to level restrictions and the previous material trouble

3.5.4 There is also an issue where throw-item survival mode cannot be used

**Comment by Tslat** [comment]
what?

**Comment by FuccSSake** [comment]
Have the same problem, but am playing a modpack (Odessey, space a new beginning). I have looked up other issues but the only thing I find is the removal of "midnight" which is not in this pack.

**Comment by Tslat** [comment]
???

**Comment by EatingSilencer** [comment]
> Have the same problem, but am playing a modpack (Odessey, space a new beginning). I have looked up other issues but the only thing I find is the removal of "midnight" which is not in this pack.

If you are talking about the thrown weapons not working, that is a known bug that got fixed in a later AoA version iirc. Not sure if there is a fix without updating aoa.

**Comment by FuccSSake** [comment]
Ah, thanks. I had no idea it was resolved. I guess the pack hasn't been
updated then. Thank you for the info.
