### ISSUE TITLE
The game crashes immediately when spawn smash boss

### ISSUE THREAD

**Issue by ghost** [Tslat/Advent-Of-Ascension#3478]
**Mod Version**
1.19.2, 3.6.17

**Describe the bug**
The game crashes immediately when spawn smash boss

**To Reproduce**
Spawn smash boss

**Expected behavior**
game crashes immediately

**Screenshots**

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.Brain.m_21952_(net.minecraft.world.entity.ai.memory.MemoryModuleType)" because "brain" is null

This is the crash log

**Comment by Tslat** [comment]
Can't do anything without a crash report
