### ISSUE TITLE
Spawning King Shroomus with a spawn egg

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#348]
**Mod Version**
AoA3 (Sagi version)

**Describe the bug**
For some reason when you spawn King Shroomus with a egg his music gets really slow.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a "Spawn King Shroomus"
2. Right Click on anywhere.
3. Compare the music to how its spawned with a Shroom Stone in Mysterium.

**Expected behavior**
Weird music bug

**Comment by Tslat** [comment]
Music System has been altered a bit since 3.0, we'll see if it brings up anything like this again
