### ISSUE TITLE
Chomper has trouble swimming downward

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3480]
Apparently, the intended behavior is that he can't swim upward, but he can move in the water otherwise

Either way, what currently occurs is that Chomper can swim and can go a tiny bit downward, but not much beyond that. He mostly sticks to the surface. Unknown if this is intended behavior
![image](https://user-images.githubusercontent.com/38159897/197426029-8e8d5767-3d83-4e37-b3b7-6f5685b9ca74.png)

**Comment by Tslat** [comment]
Dumbass scaley boi
