### ISSUE TITLE
"Standard explosions" are very picky with getting to their base damage

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3483]
RPG and Little Bam have a base explosive damage of 16 and 20 respectively. However, it appears difficult to reach the base damage

With RPG, I have managed to reach the 16 damage, but only while shooting at the side of a mob?
![image](https://user-images.githubusercontent.com/38159897/197670262-9550b062-44d5-418a-86d8-7d563857163f.png)

In a setup like this, nothing ever gets higher than 10. Only the middle creeper took 10, the rest took 8-9
![image](https://user-images.githubusercontent.com/38159897/197670504-afbaa5fd-30c8-42ae-83fe-1851d4919858.png)

But when I aim to the side like this, I more consistently get higher numbers like 12+? 1 of them took 16 here
![image](https://user-images.githubusercontent.com/38159897/197670585-ae6ad572-8015-40ab-8640-725db1e5d0be.png)

And here, I even managed to have them take no damage at all from the explosive, even though they still lit up red like they took the damage
![image](https://user-images.githubusercontent.com/38159897/197670664-20af322b-8e99-41f5-9327-d01dc320feeb.png)

Similarly with Little Bam, I have not found a spot that causes him to deal the 20 damage, I've only managed to get to 14-15 at the highest

**Comment by Tslat** [comment]
This is because this is the one spot I used vanilla code to handle damage percentage variations -.-
