### ISSUE TITLE
Assassin trades don't stack properly when shift clicked

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3486]
For some reason, this ONLY happens with Assassin villagers and no other NPC as far as I know. It happens when shift right clicking on a trade when you buy it. While in the trade window, I can't get them to stack properly when double clicking 1 of the Slice stars either, I can only do that when I'm out of the Assassin's trade GUI
![image](https://user-images.githubusercontent.com/38159897/197913097-e8b1e966-976f-469b-abcc-7b4bcdeccbfe.png)

**Comment by Tslat** [comment]
Yeah I don't think I have any control over this - it's a vanilla menu
