### ISSUE TITLE
Geckolib needs to update this mod

### ISSUE THREAD

**Issue by krjencik** [Tslat/Advent-Of-Ascension#3489]
**Mod Version**
What version of the mod are you on? 1.19.2 - 3.6.17

**Describe the bug**
Minecraft crashes while ingame

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
Be able to play

**Screenshots**

**Comment by krjencik** [comment]
um... why its closed?

**Comment by Tslat** [comment]
Because it'll be fixed
I'm working on Geckolib at the moment, I'm aware AoA is currently broken

**Comment by krjencik** [comment]
tyyyy
