### ISSUE TITLE
Goblins (and only goblins) seem to be able to spawn on anything in the overworld

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#350]
![image](https://user-images.githubusercontent.com/11131230/53289262-f697a700-3761-11e9-8b7e-64871ef69657.png)

Made a superflat world with diamond blocks as the top block and Plains biome. The only spawn in the world was goblins even after flying around for a few minutes.

Maybe because goblins are ranged mobs and ranged mobs have some sort of different spawn check? IDK, thought about trying this due to debate on what the spawn checks are for overworld blocks.

**Comment by Tslat** [comment]
Fixed
