### ISSUE TITLE
1.19.2 Origin Crash

### ISSUE THREAD

**Issue by Joshernoob** [Tslat/Advent-Of-Ascension#3500]
**Mod Version**
AoA3-1.19.2-3.6.17

**Describe the bug**
When this mod in server with origin mod seem that origin can't bring up is menu before player loads in world, this seem to be only when player though server, on client you seem to be fine and can load in without a problem

**To Reproduce**
Steps to reproduce the behaviour:
1. Add this mod and It Origin(forge) to a server and pack
2. run both
3. try to join server though pack
4. crash

**Expected behavior**
Origins (forge) should add an overlay before the start of the game to choose a race/ class

**Comment by Tslat** [comment]
If you want support with a crash.. you need to actually provide the crash report
