### ISSUE TITLE
Double Jump

### ISSUE THREAD

**Issue by cyancrayon** [Tslat/Advent-Of-Ascension#3501]
**Mod Version**
AoA3-1.16.5-3.6.8.jar

**Describe the bug**
If you jump under a two block height while having the double jump ability active, you continuously jump until you are able to get out of the two block height
**To Reproduce**
Just jump while under a two block gap
**Expected behavior**
Should just jump twice and not continuously
**Screenshots**

**Comment by Tslat** [comment]
Unable to replicate
It works as intended for me

And I'm not even sure how that would happen anyway - DoubleJump only sends a keypress if the player triggers it with a keypress
