### ISSUE TITLE
Have bestiary show the explosive damage value of a mob if it's capable of causing explosions (if possible)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3503]
Because explosions vary in damage, just have it say "up to x", x being the highest possible damage
![image](https://user-images.githubusercontent.com/38159897/205425312-2475e969-c00d-43eb-a4a6-b43e9f09ca4c.png)

**Comment by Tslat** [comment]
Not really practical/feasible
