### ISSUE TITLE
Chompers can spawn on leaves, when they're not supposed to?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3509]
Something funny is going on here (the 2nd guy in the image also spawned on there but left the tree)
![image](https://user-images.githubusercontent.com/38159897/205432829-c821a4a9-188b-467a-b25a-7459f490133a.png)
![image](https://user-images.githubusercontent.com/38159897/205432855-1925fccd-3e63-4353-84b9-7c722ab7b076.png)

**Comment by Tslat** [comment]
*shrug*
That's a vanilla problem

**Comment by Tslat** [comment]
No it's not
Fixed it

**Comment by Tslat** [comment]
Well it kinda is
But I still fixed it
