### ISSUE TITLE
Mechbot Altar erroneously called tile.MechBotAltar.name

### ISSUE THREAD

**Issue by WeegeeTheDoggo** [Tslat/Advent-Of-Ascension#351]
**Mod Version**
3.0

**Describe the bug**
The Mechbot Altar is called "tile.MechBotAltar.name" in-game

**To Reproduce**
Steps to reproduce the behaviour:
1. Look in the creative menu where all the Altar blocks are
2. Hover over them until you see "tile.MechBotAltar.name"

**Expected behavior**
The Block should probably be called Mechbot Altar

**Comment by Tslat** [comment]
Has been fixed
