### ISSUE TITLE
My idea for the upgraded King BamBamBam fight

### ISSUE THREAD

**Issue by SooshiGuy** [Tslat/Advent-Of-Ascension#3512]
Just a suggestion of what I think the remastered King BamBamBam boss fight should be.

**Design:**
I think that the design should be a giant Little Bam with his iconic staff (now with a remodel) and some black Piglin clothing along with a black cape. The horns on his head are the same as the Little Bams but just a bit bigger. The elite King BamBamBam will also wear a gold crown on his head. I also think he should have a separate throne entity which is located in the centre of the boss arena that King BamBamBam would sit on, this throne is completely indestructible and will be made out of blackstone along with some mechanical gears so that the throne can turn around.

Due to the throne, the fight can only take place in the following arenas:
- Bridge Arena
- City Arena
- Desert Arena
- Spiral Arena
- Square Arena
- Tulip Arena

Unfortunately, I don't know how to make mob textures so I can't provide any models of what he might look like :(

**Phase 1:**
I think King BamBamBam should have 2 phases, in the first phase he will remain on his throne and use the following attacks:

- Boom Shot: King BamBamBam will often use this attack in the first phase and it involves him shooting an explosive ball of magic at the player. Elite King BamBamBam will use this attack faster.

- Boom Beams: King BamBamBam will summon some beams of magic around the arena which will shrink before exploding. 5 beams will be summoned until the attack ends. Elite King BamBamBam will summon 8 beams and they will shrink slightly faster.

- Bam Summon: King BamBamBam may pull out a Goat Horn then blow it summoning 3-4 Little Bams in the process which, unlike regular Little Bams, cannot be fooled by Gold Armour and their explosions cannot destroy blocks (due to the fight taking place in Nowhere). Elite King BamBamBam will summon 4-6 Little Bams instead.

- King's Fire Breath: King BamBamBam may play an animation sucking in some smoke before shooting fire out of his mouth which will follow the player, this attack can be avoided by either getting close enough to King BamBamBam or getting far enough away from the throne. It will last for 4 seconds before ending. Elite King BamBamBam will perform this attack for 6 seconds instead.

- Pig Shriek: If the player gets too close to King BamBamBam for too long then he will emit a loud shriek which will push the player back to the otherside of the arena. In Elite King BamBamBam's fight the shriek will also summon 2 Little Bams as well.

**Phase 2:**
In phase 2, King BamBamBam would enter a transition where his staff will break, then he gets enraged and has literal fire coming out of his nostrils. He would then jump of his thrown (causing the throne to slowly submerge itself into the ground) towards the player to attempt to land on him/her, then he will roar and actually start to go on all fours as if he has gone wild. During this transition, King BamBamBam cannot be attacked until the second phase starts. During the second phase he will run around erratically in an attempt to avoid the player along with using the following attacks:

- Bomb Throw: King BamBamBam will often use this attack in the second phase and it involves him pulling out some dynamite before throwing it towards the player, creating a small explosion in the process. Elite King BamBamBam will throw the dynamite faster and will additionally throw Hellfire as well.

- Punch: If the player gets too close to King BamBamBam then he will simply punch the player to knock them away.

- Bam Roar: King BamBamBam may randomly roar, summoning 2 Little Bams on the first attempt then 4 beyond that. Elite King BamBamBam will summon 4 on his first attempt then 6 beyond that.

- Mad Pig Charge: King BamBamBam will play an animation for 2 seconds before aggressively charging at the player before needing rest. In Elite King BamBamBam's fight, he does not rest and will also charge faster.

- Mad King's Fire Breath: King BamBamBam may play an animation sucking in some smoke before shooting fire out of his mouth which will follow the player, this attack can be avoided by jumping over it. It will last for 4 seconds before ending. Elite King BamBamBam will perform this attack for 6 seconds instead.

- Flaming Fist Slam: King BamBamBam will occasionally put both of his fists into the the air, letting them go on fire, before smashing both of them down into the ground, creating a fiery shockwave that can be avoided by jumping. Elite King BamBamBam will perform this attack much faster.

Upon defeat, King BamBamBam will start shaking and a yellow orb will appear above his horns, before creating a large explosion. Any Little Bams that where around upon King BamBamBam's death will despawn to prevent an unfair death.

**Loot:**
Upon death, King BamBamBam can drop the following:
- King BamBamBam Trophy
- Ornate King BamBamBam Trophy (Elite variant only)
- Archaic Tokens
- Silver Coins
- Gold Coins
- Bottle o' Enchanting
- Gunpowder
- Enchanted Gunpowder
- Ivory
- Emberstone Nuggets
- Flammable Dust
- Torn Cloth
- Hellfire
- Grenades
- Magic Repair Dust
- Magic Mending Compound
- Fire Runes
- Power Runes
- Fiery Chops
- Explosive Bow
- Explosive Armour Set

**Bestiary Entry:**
Here is a bestiary entry of King BamBamBam I made:

"King BamBamBam is a large Piglin that underwent the same magical transformations as Little Bams, unlike other Little Bams, he ruled over them with an iron fist and used a magical staff to wreak havoc in The Nether. He died of his self destructive ability many years ago but he has been brought back to life by using an Explosive Idol which embodies his spirit. This Idol appears to be made by the Little Bams themselves as they have been observed carrying it around.

Due to his large size, magical cabibilities, ability to create fire and the strange ability to go on two or four legs, this means he can pose a big threat to anyone nearby. Combine that with his emergency self destruction, and this can make a dangerous enemy to anyone not prepared for an explosive battle."

Now I have no idea whether the team already has an idea for King BamBamBam in mind but if you do, that's okay.

**Comment by SooshiGuy** [comment]
Some other things I wanted to note down:

- King BamBamBam can't drop his staff in this fight because it breaks after phase 1 due to durability
- I also think that a Phase 1 attack where King BamBamBam will throw Hellfire to the player sounds cool although I didn't want to add that to this issue because I didn't want to add too many attacks to this guy due to The Nether being an early game dimension, but I thought I would give this idea a mention anyway
- When King BamBamBam is spawned from a spawn egg, his throne will appear alongside him just like it would in Nowhere

**Comment by EatingSilencer** [comment]
> If this fight was to be added then it would create the addition of special Nowhere arenas for certain bosses, so I hope that's okay

I don't think this is going to happen. Seeing as the first phase is built around his throne, it might be better if the throne was like an entity that is independent of the arena instead.

**Comment by SooshiGuy** [comment]
> Seeing as the first phase is built around his throne, it might be better if the throne was like an entity that is independent of the arena instead.

Yeah that's a good idea and it could still work although he does need to spawn in one specific location for each arena type (basically the best spot for the middle). It does mean that the throne will be moving which might be a bit weird.

**Comment by SooshiGuy** [comment]
**The Throne issue:**
The biggest problem with this boss is the throne but I think I might have solved it. Basically the throne will be a separate entity that King BamBamBam will sit on, it is made of blackstone and several mechanical parts meaning it will turn around so that King BamBamBam can use his attacks. The throne is also located in the centre of the arena so it will be easier to integrate with the current arenas, alongside this it will also be impossible to damage. During the transition onto phase 2, King BamBamBam will jump of the throne, causing it to despawn, then he will attempt to land onto the player then continuing the fight in the second phase. If King BamBamBam was spawned using his spawn egg then the throne will spawn alongside him.

Due to the throne, the fight can only take place in the following arenas:
- Bridge Arena
- City Arena
- Desert Arena
- Spiral Arena
- Square Arena
- Tulip Arena

Alright now I'm ending this issue for the time being so I don't confuse Tslat with all this information.
