### ISSUE TITLE
Have Bush Babies automatically aggro the mob the Leafy Giant is aggroed to.

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#3517]
Once the Leafy Giant summons a Bush Baby, they are not aggroed to any mob unless it's the player, given they are hostile creatures. I think it would be better that they are aggroed to whatever the Leafy Giant is currently aggroed to. From what I know, this was a feature a few updates before, but it is seemingly not in the current Leafy Giant build. However, this feature seems to work with the Stone Giant once a Silverfish is spawned.

**Comment by Tslat** [comment]
This should still be the case, Leafy Giant hasn't changed, and the code is still the same
Are you sure it's not applying?

**Comment by TripleThreeT** [comment]
Here's an image of what happens. They don't attack the Iron Golem despite it attacking the Leafy Giant.
![2022-12-21_12 50 44](https://user-images.githubusercontent.com/87321515/208981574-0667139a-5225-47de-84b1-152dc572d830.png)

**Comment by TripleThreeT** [comment]
I also went and checked the 3.6.10, and it worked as intended.

**Comment by Tslat** [comment]
Is Leafy Giant attacking the iron golem?

**Comment by TripleThreeT** [comment]
Yes, though the Iron Golem lost aggro due to the invincibility.

**Comment by Tslat** [comment]
mmk thanks
