### ISSUE TITLE
The Lunar Bow's string turns white when fully pulled back

### ISSUE THREAD

**Issue by WeegeeTheDoggo** [Tslat/Advent-Of-Ascension#352]
**Mod Version**
3.0

**Describe the bug**
When you pull back the Lunar Bow's string, the string becomes a lighter color than what it was, this doesn't look like it's intended

**To Reproduce**
Steps to reproduce the behaviour:
1. Equip the Lunar Bow
2. Pull the string back all the way
3. The string will change its color to white

**Expected behavior**
The string should remain the same color, no matter how much it's pulled, just like every other bow

**Comment by Tslat** [comment]
Fixed
