### ISSUE TITLE
Crash when loading 1.19.3-3.6.19

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#3520]
**Mod Version**
What version of the mod are you on?
1.19.3-3.6.19

**Describe the bug**
Game crashed on boot. Crash report:
[crash-2022-12-17_10.32.32-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/10252061/crash-2022-12-17_10.32.32-client.txt)

**To Reproduce**
Steps to reproduce the behaviour:
1. Load the game.
2. See error

**Expected behavior**
The game does not crash.

**Comment by Tslat** [comment]
Sigh. Why.
