### ISSUE TITLE
Melee mobs jitter and swerve slightly when moving while aggroed

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3527]
https://www.youtube.com/watch?v=fOfIVganl1I

**Comment by Tslat** [comment]
Does this only affect cyclops? or does it affect everything?
Were these mobs already affected in 1.19.2? or is this specifically a 1.19.3 thing

**Comment by Cruuk** [comment]
> Does this only affect cyclops? or does it affect everything? Were these mobs already affected in 1.19.2? or is this specifically a 1.19.3 thing

1.19.3 thing. From the mobs I've checked, it's all the melee-centric ones. Cyclops, Sasquatch, Charger, Chomper, Smash, Ice Giant, etc. I've mainly noticed the ranged mobs not affected by this, like Bomb Carrier, Goblin, and Flamewalker

**Comment by Cruuk** [comment]
Also, it seems to specifically happen when mobs are aggroed onto something. Fixed the title to be more accurate
