### ISSUE TITLE
orespawn incompatibility

### ISSUE THREAD

**Issue by ghost** [Tslat/Advent-Of-Ascension#3530]
*all mods version of a.a 

unfortunately the mod does not work with orespawn since it limits the damage of other swords from other mods to 15 damage, could you solve this? 

![image](https://user-images.githubusercontent.com/120964207/208310276-71a78ade-e530-43a8-9115-074c775932ff.png)

**Comment by EatingSilencer** [comment]
Go into the config file for AoA and set DMG Limit to 0. This will fix this.
