### ISSUE TITLE
Follow range seems too small for the most part

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3539]
The idea of threats being more "localized" is fine, but I feel like the follow range is too small. If the aggro range is smaller than the standard 16, then the follow range should at least be 16 or higher. The general average follow range being 12-14 feels a bit too blind for the mobs. Besides the giants/Chargers, the current implementation is an overall vision nerf

**Comment by Tslat** [comment]
I'm aware it's an overall vision nerf, and that was _partially_ the intention
I'll keep an eye on it
