### ISSUE TITLE
Urv doesn't get stronger if more mobs are next to it

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#354]
**Mod Version**
3.0

**Describe the bug**
Usually, Urv is supposed to get a damage boost and regen if Visages, Ghastus', and more Urvs are next to it. This does not occur in 3.0.

I would assume it's intended but Urv is a pretty weak mob on it's own, and Visage still seems to get a more powerful Wither effect if more mobs are nearby. I can't remember if Visage is supposed to get a regen effect as well. If it does then that's not working either.

**To Reproduce**
Steps to reproduce the behaviour:
Spawn a bunch of Urvs and have them hit you

**Expected behavior**
Urvs are usually supposed to get more powerful the more mobs are near it, along with a regen effect that increases with the amount of mobs nearby.

**Comment by Tslat** [comment]
Fixed
