### ISSUE TITLE
Error al morir por bug dos veces 

### ISSUE THREAD

**Issue by Cejota07** [Tslat/Advent-Of-Ascension#3544]
AoA3-1.19.2-3.6.18

Si muero por un mob del aoa el serigá golpeando mi tumba y al momento de pulsar revivir recivo daño del mob o me mata dos veces directamente

Lo que provoca que en el servidor donde juego se cierre automaticamente

**Comment by EatingSilencer** [comment]
Does this issue still occur in 1.19.3?

**Comment by Cejota07** [comment]
No he probado la 1.19.3 ya que mi servidor está alojado en la 1.19.2 y no puedo actualizar, ya que la mayoría de los mods no están para la 1.19.3.
Otro error que he notado es que los mobs te siguen traqueando aún estando en creativo :c

**Comment by EatingSilencer** [comment]
1.19.2 AoA is never getting any updates, so unless you can replicate this issue in 1.19.3, there's nothing on AoA's side that will be fixed.
