### ISSUE TITLE
Only nowhere Portal and nether Portal are working

### ISSUE THREAD

**Issue by DebraDave** [Tslat/Advent-Of-Ascension#3546]
**Mod Version**
1.19.3
**Describe the bug**
Only two portals are working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make ancient Teleportation portal
2. light it with the Precasia Realmstone
3. Hop in portal but it doesn't do anything

**Expected behavior**
For other portals and dimensions to work.

**Screenshots**

**Comment by EatingSilencer** [comment]
Most dimensions haven't been added to 1.19.3 yet.

**Comment by DebraDave** [comment]
Crying
