### ISSUE TITLE
This part in Aurora confused me a bit

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3555]
There's this part near the beginning that looks like a split pathway since you can jump on the blue aurora
![image](https://user-images.githubusercontent.com/38159897/209595826-afb08105-2939-4af4-b82f-528281e70b0a.png)

However, it doesn't actually lead anywhere. So I feel like that part should be higher so it doesn't look like another route

**Comment by Tslat** [comment]
Doesn't it?
