### ISSUE TITLE
Should the Silverfish summoned by Stone giant drop exp

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3573]
They currently drop exp, it would allow for an exp farm

**Comment by Tslat** [comment]
I mean I guess?
I'd have to implement a whole other entity just to counter it, and given how limited of an xp farm it is, I'm not really sure it matters that much lol

**Comment by Cruuk** [comment]
> I mean I guess? I'd have to implement a whole other entity just to counter it, and given how limited of an xp farm it is, I'm not really sure it matters that much lol

Yeah I suppose it wouldn't really be better than actual mob farms like Enderman/Piglin ones, and those give item drops while Silverfish don't drop anything (besides World table)
