### ISSUE TITLE
Attack distance

### ISSUE THREAD

**Issue by Fgsn** [Tslat/Advent-Of-Ascension#3577]
**Mod Version**
What version of the mod are you on?
 AoA3 1.16.5-3.6.8

**Describe the bug**
increased attack range (with all melee weapons ~4.5 and with greatswords and even more so about 6) compared to the vanilla version of the game ~3.5-4

I apologize in advance if this is written somewhere, but I didn’t see it, but I asked this question on your discord channel, but unfortunately no one answered this is a bug or a feature

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by Tslat** [comment]
Forge bug
