### ISSUE TITLE
The magic damage you take from fire when having Neth curse/fire resist appears to do less damage than expected?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3580]
From what I can tell, the actual numbers in the formula for Neth curse weren't changed in 3.6.21. The formula is supposed to be fire damage * x * 0.5 + 0.5 where x is the level of Nethengeic Curse or 8- the smaller value is chosen.

At level 1 Neth curse, regular fire DoT should be doing 1 magic damage. But ingame, it does 0.5 damage.

At level 2 Neth curse, regular fire DoT should be doing 1.5 magic damage, but ingame it does 1 damage.

At level 1 Neth curse, Lava should be doing 2.5 magic damage, but ingame it does 2 damage.

The trend seems to be that the damage is always off by -0.5 damage, as if the +0.5 damage porting of the formula isn't applying

**Comment by Tslat** [comment]
Just sounds like your math is off to me
I might increase it anyway though, cus it is a bit low
