### ISSUE TITLE
Weird Visual Glitch

### ISSUE THREAD

**Issue by Napstabeats** [Tslat/Advent-Of-Ascension#3588]
**Mod Version**
What version of the mod are you on?

V52 Plus
**Describe the bug**

Well, I playing with my friend this modpack for some days now and he keeps getting a visual glich and we dont find the issue for that. we googled we tried to Find the issue but not with luck, I will let down here a Video For explaination to what happend to him. we tried multiply stuff, Reinstalling, restarting, chaning versions nothing worked... (no he dont have shaders enabled.

**To Reproduce**
Steps to reproduce the behaviour:

(it just randomly Appear sometimes and than Fix itself but since yesterday it's still there)
**Expected behavior**

I have no clue, i think it is Randomly happend.
**Screenshots**

Here is the Video: https://streamable.com/ee12vc

**Comment by Tslat** [comment]
Not sure but it isn't AoA related
