### ISSUE TITLE
Buff the Nether mob weights slightly (mainly Flamewalker/Embrake)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3593]
Just a repeat of the convo that was had in the secret channel. It's fine if they're uncommon, but they are definitely too rare right now

**Comment by Tslat** [comment]
Except when they're common in other biomes?

**Comment by Cruuk** [comment]
> Except when they're common in other biomes?

That's relatively speaking. Even in Crimson forest/Basalt Delta they're quite rare, and they're really seldom seen in Nether wastes
