### ISSUE TITLE
Mobs with longer melee ranges than they should have

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#360]
**Mod Version**
3.0.1

**Describe the bug**
Certain mobs have a pretty long range, Dicer seems to be fixed but there's still more. Here's a list of them.
Arocknid
Arkback
Horndron 
Hellcat
Boneback
Emperor Beast(?)
Slimer
Megatherium

I'm not sure if there's anymore, so I probably missed 1 or 2

**Comment by Tslat** [comment]
Fixed all in the list
