### ISSUE TITLE
AOA3 item duplication bug

### ISSUE THREAD

**Issue by HenrikoMagnifico** [Tslat/Advent-Of-Ascension#3602]
**Mod Version**
3.6.21

**Describe the bug**
Spam-click in a furnace output slot to ~100% get double the output when level 16 in excavation has been achieved.

**To Reproduce**
Steps to reproduce the behaviour:
1. Unlock level 16 in excavation to get 50% chance of extra items from smelted items in furnaces
2. If looking inside furnace and spam shift-click on the smelted item slot whilst it's smelting, as soon as it finishes smelting the item there is a ~100% chance you will get 2 items instead of 1 if done correctly.
3. If combined with another mod which allows for maceration (creating dust of ores and ingots) this bug can be used to aquire infinite of any ingot that can be made into dust. (Stone Macerator & Macerator from Industrial Craft 2 or Pulverizer from Thermal Expansion for instance)
4. Enjoy infinite of everything! (including diamonds and netherrite)

**Expected behavior**
To only get 50% chance of extra items when smelting from a furnace with level 16 in excavation.

**Screenshots**

**Suggested solution:**
Allow to modpack creators and server hosts to disable the perk from unlocking level 16 in excavation.

**Comment by Cruuk** [comment]
You can use datapacks to remove certain abilities if you want to I'm pretty sure.

I looked into this, and this seems more like a balance incompatibility than a bug. The only part that possibly seems like an AoA issue is the chance of extra items from smelting being 100%, and that could be just luck.

At least for the Pulverizer from Thermal Expansion, it seems to turn 1 Ingot into 1 Dust, and that Dust can be smelted back into an ingot. The Extraction ability gives a chance of an extra item when smelting. In other words, this is an overall dupe regardless of what the chance of an extra smelted item is

**Comment by Seishan123** [comment]
I would prefer it if instead of a furnace aiding with Extraction (and it's subsequent skills) it was only in a blast furnace that you get Extraction xp and the abilities. Also maybe it's best if only the ores have the chance, at least then the chance of an extra item is restricted by the world generation and the player's efforts.

**Comment by Cruuk** [comment]
> I would prefer it if instead of a furnace aiding with Extraction (and it's subsequent skills) it was only in a blast furnace that you get Extraction xp and the abilities. Also maybe it's best if only the ores have the chance, at least then the chance of an extra item is restricted by the world generation and the player's efforts.

Bonus smelt result only affects non-food items. Having it be blast furnace only seems like a pointless and arbitrary restriction
