### ISSUE TITLE
Luxon's invisiblity doesn't work

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#361]
**Mod Version**
3.0.1

**Describe the bug**
Luxon's invisibility effect doesn't seem to work. I even made sure it wasn't a physical bug by testing if mobs could see me from ~10 blocks away, and they did.

**To Reproduce**
Steps to reproduce the behaviour:
Please Luxon and gain their tribute effect at night

**Expected behavior**
Luxon's invisibility making you invisible.

**Comment by Immortallis1** [comment]
Did you test vanilla mobs? Are you using armor?

**Comment by Tslat** [comment]
Fixed
