### ISSUE TITLE
When mobs attack each other, it causes the player to be damaged

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#3611]
**Mod Version**
What version of the mod are you on?
1.16.5-3.6.8

**Describe the bug**
When one mob attacks another mob, it can cause the player to be damaged.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have one mob attack another mob. You can use the Illusion Sword for this.
2. Pay attention to your health when the mob attacks the other mob.
3. See error

**Expected behavior**
The player is not damaged.

**Comment by Cruuk** [comment]
This may also correlate to stuff like how players take damage from Skeletron even though he's too far away, almost as if 1 of the Skeletal army mobs are "transfering" the 70 damage, but I'm not 100% sure
