### ISSUE TITLE
Server and player crash because of entity ticking

### ISSUE THREAD

**Issue by Leidz** [Tslat/Advent-Of-Ascension#3618]
on : AoA3-1.19.2-3.6.18.jar

The crash happen when you are on attack range of King charger or bomb carrier and cause entity ticking crash.

(I Play on custom modpack with a lot of mods)

Here some crash logs:
[bomber crash log.txt](https://github.com/Tslat/Advent-Of-Ascension/files/10874503/bomber.crash.log.txt)
[bomber dynamite crash log.txt](https://github.com/Tslat/Advent-Of-Ascension/files/10874504/bomber.dynamite.crash.log.txt)
[king charger crash log.txt](https://github.com/Tslat/Advent-Of-Ascension/files/10874505/king.charger.crash.log.txt)

**Comment by Tslat** [comment]
I can't accept bug reports for old versions
If it happens again on the newest version, reopen this issue
