### ISSUE TITLE
Stairs in Garden Castle isn't symmetric.

### ISSUE THREAD

**Issue by Rain-Flying** [Tslat/Advent-Of-Ascension#3623]
The two staircases in Garden Castle are asymmetrical.

Left staircases:
![%GB01UHRIPGRYJ@D UUV_9O](https://user-images.githubusercontent.com/104208949/224544202-d7a89140-a43e-4ea6-b0c3-af2806bb2fdb.png)
Right staircases:
![FII30BX{3KB_ZNB@O~E0X4C](https://user-images.githubusercontent.com/104208949/224544203-f85ff365-ed53-4bc5-97b2-89b8d4d263f8.png)

**Comment by Tslat** [comment]
Eh it's fine
I won't be fixing it, and the structure will end up being replaced in newer versions anyway
