### ISSUE TITLE
epic figth mod incompatibilitie (1.16.5)

### ISSUE THREAD

**Issue by TBPLegion** [Tslat/Advent-Of-Ascension#3624]
**Mod Version**
What version of the mod are you on?

**Describe the bug**
I created a datapack to use the weapons with epic fightmod, but the weapons with especial effects like fire target,etc only works when im not in combat mode.anyone know something about it?

**Comment by EatingSilencer** [comment]
This sounds like something you should ask on the [Discord server](https://discord.com/invite/DNYqNNq).
