### ISSUE TITLE
Skill helmet armor/toughness buff

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3629]
They're close to being good, but they're not quite there. They have the exp bonus and are unbreakable, and those are good, but the former is only applicable for the cosmetic levels.

The main thing here is the armor/toughness value. Despite being in what is a tier 3 structure by technicality (Hub is only accessed with Nowhere realmstone), along with being special level 100 skill items, they have the stats of a Diamond helmet besides the durability. With armor that low, I feel a great sense of opportunity cost since I'm not using any other helmet with higher armor values and practical abilities

And even if they do stack with full set effects, there are other helmets that do that better with both higher stats and practical abilities

I'm not suggesting to make them best-in-slot, they already lack the abilities of other helmets, and that's fine. But it would be nice to be able to wear them and not be disadvantaged stats-wise and suffer from opportunity cost. Otherwise, they're better as just armor stand decoration. Just want to show off my cool helmet on me without being disadvantaged

Based on where you obtain them, they should at least be 5 armor/7 toughness like most other T3 helmets, or maybe even a bit higher to trade in practical abilities (the xp bonus does only apply to the cosmetic levels) for raw stats (high armor/toughness + unbreakable). It would make them nice to use with stuff like T1 armor sets to make more damage values reduced to the 80% cap

**Comment by Tslat** [comment]
Gotta be careful with this, they can very easily slip into BiS
