### ISSUE TITLE
AK9's Suggestions List

### ISSUE THREAD

**Issue by AK9Official** [Tslat/Advent-Of-Ascension#363]
### **AoA 3.0+ AK9’s Suggestions**

**[ ]** Server Skills Leaderboard.

**[ ]**  Cosmetic Skill Capes for reaching level 100 & 1000 for each skill.

**[ ]** Skill Cape for reaching 100 & 1000 in all levels.

**[ ]** Fishing Rods that give bonuses like better loot but slower etc, scaling with Hauling in some way.

**[ ]** Magic Skill, skill leveled up by using Magic Abilities that later lets you do more damage as you level it up. Could also be leveled up by making magic potions of some sort.

**[ ]** Cooking Skill, skill leveled up by making certain food. By leveling it up you get access to making better & more rewarding food for battles etc.

**[ ]** Clans/Guilds system.

**[ ]** Adamantite, Crystal(gem) & Onyx(gem) Ores in the Overworld.

### _**More feature suggestions to come!**_

**Comment by Angrydog001** [comment]
Well, may I ask why you don't fill in the suggestions according to the template?

**Comment by MerekiDor** [comment]
I personally agree with the first and the fourth one, neutral about the rest.

**Comment by Tslat** [comment]
Obviously very runescape inspired lol

Anyway, capes aren't feasible - Mojang/Notch has already put their thoughts out about cosmetic capes and do not wish for them to exist in any fashion except for their own.
Optifine obviously does them, but I prefer to respect Mojang's wishes

**Comment by Tslat** [comment]
Also what exactly would a clan/guilds system entail? lol
