### ISSUE TITLE
Cannon KB buff (can't tell if it's not working correctly, 3.6.22)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3633]
This is an early reaction, so I can't tell if this is intentional, or something broke.

If it is intentional, then cannon KB is currently extremely, extremely pitiful. Before, the amount of kb roughly correlated to half the damage dealt (30 damage deals ~15 blocks kb). But it is currently so small there is almost no difference. Clowno-pulse, the highest damage cannon, only deals 3-5 blocks kb. I did try shooting at different angles, and shooting directly upwards did result decent kb, everything else was pitiful. I didn't think it was unbalanced, kb is only strong for short range targets with little kb resist

If it was buffed, and there was an issue of shooting from below producing too much kb, just change it so vertical kb is less effective, I mostly want horizontal kb to act similar as it did before. Sorry for the tangential rant but it's bugging me lol

Vortex blaster works fine. The horizontal kb is nice, but the vertical kb may be a bit much. This furthers my suspicious that more tweaks should be made to better horizontal kb and lower vertical kb

**Comment by Tslat** [comment]
Ok so this one's a bit odd

So basically the existing knockback code had a rather severe flaw, and I had to rework it
Unfortunately, that also meant that anything that used the existing knockback code (mostly just cannons ) had their knockback changed as a result.
There was no good way to translate the amount of knockback from the old system to the new system, so I just left it as-is, and I'll have to adjust the knockback back to a good point based on community feedback.

Going forward, I'm gonna need an idea of the following so I can get it right:

1. Whether the knockback across the whole category is too low
2. If it's too low, is it only too low laterally? or also vertically?
3. Should the knockback be changed for all cannons equally? or is the sliding scale wrong too, and harder-hitting cannons should be doing more, relative to lower-hitting cannons?

**Comment by Cruuk** [comment]
>     1. Whether the knockback across the whole category is too low
Not sure if Vortex blaster counts here. It was included in the changelog next to cannons. If it does count, it seems to be the exception. Its lateral kb is good, and vertical kb is actually crazy.

In all below screenshots there is a Cyclops with slowness/resistance 10, and the dark prismarine indicates where he originated from.
![image](https://user-images.githubusercontent.com/38159897/226574717-5b1f31eb-4b5b-4d6d-91f2-cad90e5a5321.png)
Vertical kb
![image](https://user-images.githubusercontent.com/38159897/226575335-47fcdad0-a200-4579-9db2-754d5299242b.png)

However, I have failed to find an exception with cannons. They appear to all be like this on average in terms of lateral kb.
![image](https://user-images.githubusercontent.com/38159897/226576116-85f77cb5-35e5-4d8c-9453-859fca0c503b.png)


>     2. If it's too low, is it only too low laterally? or also vertically?
Laterally. Vertically they seem fine. Here's the difference:
Lateral
![image](https://user-images.githubusercontent.com/38159897/226577425-3ca16301-70d9-4a02-ad5a-a2e843caae25.png)

Vertical
![image](https://user-images.githubusercontent.com/38159897/226577638-47917c9f-1d64-4ebb-b92d-d32332455ebe.png)

As soon as you go anywhere below vertical, the KB completely tanks. It's not that I'm facing downwards, it's to an extent to where you have to be below the mob to get any kb. Even when I shift and look up, it makes no difference as long as I'm on the same y level as the mob

Shifting and looking up (before)
![image](https://user-images.githubusercontent.com/38159897/226580193-5a2103a8-f022-4cd1-a385-83bb8b2443e2.png)

After
![image](https://user-images.githubusercontent.com/38159897/226580258-410f9e55-81b3-46f4-8d0e-141becc13fd1.png)

> Should the knockback be changed for all cannons equally? or is the sliding scale wrong too, and harder-hitting cannons should be doing more, relative to lower-hitting cannons?

Technically, the sliding scale works, but the difference is so little. From right to left: 12 damage cannon, 20.5 damage cannon, 35.5 damage cannon
![image](https://user-images.githubusercontent.com/38159897/226581202-49cf8ae3-ec81-4c72-a4d7-6c93a0e44b00.png)

But yes, the higher damage cannons should have more kb laterally. The way it was implemented before was that the kb amount roughly correlated to half the damage. E.G. a 20 damage cannon did ~10 blocks of kb, so ideally it should be something similar to that practically speaking. 

In general, I've noticed that lateral kb that gets the mobs off the ground is better compared to ones that just make them slide, it just so happens that you *really* have to be vertically different to get a mob off the ground at all. When I'm on the same y level as the mob, I have been unable to cause kb that gets them off the ground

As an extra note, before this change, I also noticed RPG having a similar issue of throttled kb. It seems to be because the new explosion system likes to push mobs downwards and keep them to the ground, lessening KB
