### ISSUE TITLE
Connot obtain crystallite/bloodstone

### ISSUE THREAD

**Issue by Jesuistondieux** [Tslat/Advent-Of-Ascension#364]
**Mod Version**
3.0.1

**Describe the bug**
The player cannot obtain  crystallite or blood stone because when crystallite ore/bloodstone ore are
mined (with a vanilla pickaxe or one from the mod) they drop crystallite ore/bloodstone ore and crystallite ore/bloodstone ore cannot be cooked in a furnace. The only way I found to obtain crystallite/bloodstone is to have extern mod(for example crusher from thermal). 

**To Reproduce**
Steps to reproduce the behaviour:
Go to Haven/Abyss  and try to mine a crystallite ore/bloodstone ore . After try to cook this crystallite ore/bloodstone ore .

**Expected behavior**
Absolutly no idea.

Ps1: maybe I miss something so sorry if this issue is stupid.
Ps2: sorry for my poor english.

**Comment by Tslat** [comment]
Fixed
