### ISSUE TITLE
Creative Mode Reach Distance in Survival Mode

### ISSUE THREAD

**Issue by Cuban73** [Tslat/Advent-Of-Ascension#3641]
Mod Version - AoA3 1.16.5-3.6.11

In Survival Mode the player's reach distance (how far you can hit an entity) is longer, means I can hit entity at more far distance like I'm in Creative Mode, because players in Creative have a longer reach for placing, destroying, and attacking than in Survival. 

Steps to reproduce the behaviour:
1. Create a world;
2. Be in Creative Mode;
3. Aim at Entity (any mob) from far away and start slowly walking to it;
4. Immediately stop when Hit Indicator appears;
5. Get in Survival Mode when standing still;
6. Check if the Hit Indicator still under crosshair and you can hit an entity.

Expected behavior;
A normal Survival mode reach distance (2-3 blocks).

**Comment by Tslat** [comment]
This just sounds like the long-standing forge bug to me
https://github.com/MinecraftForge/MinecraftForge/issues/9309

**Comment by Cuban73** [comment]
This thing works only when AoA is installed. There is no such bug when other mods are installed. I'm playing on 1.16.5, not 1.18.2 or higher, so I think that this is not Forge's bug (I tried the 36.2.39 build and the recommended one, which is 36.2.34). I tried installing this mod only, tried different launchers, and this bug still exists. Are you sure this is Forge's bug and not AoA's?

**Comment by Tslat** [comment]
The bug has been around in forge for a bit - that report just happens to be in 1.18.2

You can confirm the reach distance isn't changed when AoA isn't installed?
