### ISSUE TITLE
Mob Textures in 1.16.5

### ISSUE THREAD

**Issue by PadFoot2008** [Tslat/Advent-Of-Ascension#3649]
**Describe/name the existing feature this suggestion relates to**
Hye Tslat! I absolutely loved your mod and I've been playing it for a quite a while now. I came to know that the mob textures in AoA fandom wiki are for the future updates of 1.18/1.19 and not for 1.16.5.

**Describe the change or feature you think would be good to see**
I don't know how difficult or easy would this be but could you please add those mob textures and models to the 1.16.5 version too, please?.

**Comment by Cruuk** [comment]
The wiki is for information on the post-1.16 rework versions. 1.16 info is on there, but post-1.16 stuff takes priority. This includes the mob models. Backporting is not possible nor wanted because it's not just remodels, it's new AI under a new system

**Comment by PadFoot2008** [comment]
All right. :(
