### ISSUE TITLE
Nethengeic Wither can fly far away on certain arenas

### ISSUE THREAD

**Issue by Ursun1** [Tslat/Advent-Of-Ascension#3652]
**Mod Version**
1.19.3-3.16.22

**Describe the bug**
Neth Wither can fly away from the arena if it isn't aggroed

**To Reproduce**
Steps to reproduce the behaviour:
1. Summon Nethengeic Wither until you get to the bridge arena
2. Try not to get close and aggro the boss
3. See error

**Expected behavior**
Arenas having a barrier to prevent this/wither having more aggro range

**Screenshots**
best visible on the bridge arena since it's pretty large and doesn't have a glass wall around, most arenas are small enough to have the boss aggroed immediately
![image](https://user-images.githubusercontent.com/19820954/227193172-9852ac91-baa6-4c69-9210-679df8b017fa.png)

**Comment by TripleThreeT** [comment]
Agreed. There was an instance where Nethengeic Wither went underneath an arena for me.
