### ISSUE TITLE
Portal bug

### ISSUE THREAD

**Issue by VulDovahkiin** [Tslat/Advent-Of-Ascension#3659]
I have no idea how to wite these bug reports so sorry if I miss or forget something

**Mod Version**
1.18.2-2.1.2  Forge: 40.1.51
**Describe the bug**
Only the nether portal works, I can make the other portals but I can't go through
**To Reproduce**
Steps to reproduce the behaviour:
I have no idea I just can't go through 

**Expected behavior**
Portals not working

**Comment by EatingSilencer** [comment]
Not a bug. The dimensions are not added to 1.18.2.
