### ISSUE TITLE
Flamewalkers, Embrakes and Infernals shouldn't spawn in Crimson Forests

### ISSUE THREAD

**Issue by SooshiGuy** [Tslat/Advent-Of-Ascension#3660]
They don't suit the biome at all. I always imagine a Crimson Forest to be a biome filled with Mushrooms mixed with a bit of fire and lava. I don't imagine it to have mobs with a reference to blackstone and ash.

This is of course, just my opinion so if you agree or disagree then I don't mind.

**Comment by Tslat** [comment]
The basalt deltas are almost impossible for these mobs to navigate in, which is why they're not there

**Comment by SooshiGuy** [comment]
Yes I understand. But if that is the case then why do Flamewalkers spawn there?

**Comment by Tslat** [comment]
Because flamewalkers use ground-based ranged attacks that don't require them to traverse the basalt deltas

**Comment by SooshiGuy** [comment]
Okay now I see the problem.

But I still think they shouldn't spawn in Crimson Forests. I always look at that biome and think about mushrooms and a little bit of fire, not a land filled with magma and ash.

And what do you think about the soul sand valley Flamewaker? Is it a good idea or is it a waste of time?

**Comment by Tslat** [comment]
It doesn't really fit with what Mojang is doing with that biome
I could remove flamewalkers from crimson forests though, I'll have to think about it

**Comment by SooshiGuy** [comment]
Ok. I'll update this issue to be in line with what your saying.
