### ISSUE TITLE
New weapon actions

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3663]
Many new weapon actions to exflourishiate the current gameplay loop action

SWORDS:
Right click near a wall to stab the sword into it. The player can then bounce on the stabbed sword entity like a spring to reach new heights.

While more than 5 blocks in the air, look straight down and left click with a sword to stab the sword into the ground. This will deal 3x damage.

If you spin your point of view really really fast (you will need high sensitivity for this one) and left click with the sword, the player will perform a spin attack that creates a hurtbox all around them

Pressing crouch + the drop key will cause the player to throw the sword like a snowball

GREATBLADES:
Hold down right click to do a huge downward strike. This will cause different effects depending on if you hit blocks or a mob.

If the player strikes a mob, the greatblade will vertically slice through the mob and cut them in half. Both sides of the mob will fall to opposite sides of the ground. Won't work if the mob is durable.

If the player strikes a block, they will cause a huge explosion that travels along the ground.

If the player looks sideways after charging the greatblade, they will instead cause the Hyper Slash. This attack will cause a horizontal line to cleave through the land. Any mobs in the line's path are cut in half, and any trees or mountains will also fall over. This covers a 64 chunk distance

MAULS:
Holding crouch while left clicking will cause the player to slowly slam the Maul into the ground, causing a huge quake. Any small mobs can be crushed and instantly killed by this attack. Any blocks near this impact zone get affected by gravity and fall to the ground

If the player presses jump at the right time while doing this attack, they are launched into the air

THROWN:
If the player has a stack of Thrown weapons and is 10 blocks into the air, the Thrown weapons will be launched extremely quickly out of all sides of the player's body. This causes an explosion.

BOWS/CROSSBOWS:
If the player right clicks a traveling arrow entity with an empty hand, they will ride the arrow like a surfboard.

If a mob/player has arrows in their eyes, they won't be able to see.

If a player has many arrows on them, they can shift and hold right click to tense their muscles hard enough to make all the arrows pop out. This causes the arrows to quickly fly in any direction.

GUNS:
There is now reloading. Each gun has a different clip size and reload speed. The player must hold crouch and right click to reload.

There is also the "Alternative Reload" done by pressing right click while holding crouch and the drop key. This will cause the player to throw the gun out of their inventory while still holding the magazine. the player then immediately grabs another gun to slot into the magazine. This method is faster, but requires multiple guns.

There is then the "Super Reload", done by pressing both right/left click while holding crouch, drop, and the inventory key. This will cause the player to throw any gun(s) they're holding up into the air while still holding the magazine. While the guns are in the air, the player will throw those magazines away and immediately grab new ones. The guns will then fall back down in the perfect positions to land right on the magazines and have them be slotted in. This causes an explosion.

Whenever a gun is fired, there is a 0.2% chance for it to be jammed and stop firing. The player can un-jam the gun by looking down and left clicking, shaking the gun to get whatever's jamming it out of there. Having the "Smooth shaft" will also lower the jamming chance to 0.05%.

If a bullet hits another bullet that is already in the air, it will cause that bullet to go faster and do more damage.

The Brace enchantment now has more than 1 level. Each level above 1 will give the player more than 1 arm to hold a 3rd or higher gun with. All guns have to be reloaded individually.

The player can use fast firing guns to slowly redirect mob projectiles back at them. The projectile has to be fired at a lot. This causes an explosion.

SHOTGUNS:
The player can use Shotguns to propel themselves into the air. The direction they are propelled in depends on the directions of the Shotgun shot.

If the player's offhand is empty, they can use the offhand to choke the Barrel of the Shotgun to remove all projectile spread.

The player can blow a mob's goddamn brains and guts out by sticking the Shotgun in their mouth and firing.

SNIPERS:
If the player headbutts a sniper bullet at the exact right time as it's fired, it will be strong enough to pierce through any block. Any blocks affected by this will have permanent bullet holes.

All headshots will deal 3x damage.

If the player right clicks a travelling Sniper bullet, they will grab the bullet with a single hand and start riding it. This can also be used to redirect the bullet somewhere else.

CANNONS:
If a cannonball is shot out of the air, it causes a huge explosion.

A string can be attached to a cannonball. If the player fires a stringed cannonball and right clicks it, they will ride it like a swinging vine If the player left clicks it instead, they will grip the string and start swinging the cannonball around like a giant flail.

Cannonball projectiles will cause small mobs to get completely ripped and splattered on impact. BOOM. This causes an explosion.

A grenade can be stuck down a mob's mouth to cause devastating internal damage. This causes an explosion.

A grenade can be painted like an apple to trick mobs into eating it. This causes an explosion.

BLASTERS:
Being in water while firing a Blaster will cause the player and any nearby entities to get electrocuted to death.

Due to the amount of energy it takes to manifest the type of projectiles Blasters fire, firing a Blaster for too long will causes its temperature to rocket to 2,000 degrees celsius. This causes an explosion.

If lighting strikes a blaster, it causes a methanol explosion.

Due to radiation, overexposure to Blasters by holding one in the player's hand will cause side effects over time. This causes an explosion.

The player can now attach Gravity blasters onto entities like mobs/boats in any direction.

STAVES:
Only a true WIZARD can wield such magic. The player must be a WIZARD to properly wield a staff.

By overcharging a staff via crouching and holding right click, all rune ammunition can be fired at the same time. If the player has enough runes to fire 200 Destruction staff projectiles, all of those 200 projectiles will be fired at once. Do not use in creative mode.

VULCANES:
If the player has 100 rage and is struck by lightning while holding a Vulcane, they will temporarily gain the body and muscular proportions of Smash.

**Comment by Tslat** [comment]
Great ideas
