### ISSUE TITLE
Remove Alchemy and Engineering from the skills menu

### ISSUE THREAD

**Issue by Flamebom** [Tslat/Advent-Of-Ascension#367]
Currently Alchemy and Engineering are untrainable.
It's pretty misleading having two skills that you can't train still be on the skills menu.
Why not just remove it until they are real skills rather then just have them placed randomly on the menu and be untrainable.

**Comment by Tslat** [comment]
They were placed in there to fill the gap that hermetism and robbery left without disturbing the positioning of the existing skills for players who are already used to it.

I might do something else instead..
