### ISSUE TITLE
Chompers freak out in water

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3672]
They spin around a lot, and appear incapable of attacking stuff for the most part, even if you get right next to them. Their movement in water seems mostly restricted to moving up or down due to the constant spinning

**Comment by Tslat** [comment]
Did they work in 1.19.3?

**Comment by Cruuk** [comment]
> Did they work in 1.19.3?

Kind of. They also freaked out in water a bit in 1.19.3, but not to this extent. In general, their swimming has been getting more funky throughout the ports

**Comment by Tslat** [comment]
That's annoying cus I haven't been changing em

**Comment by Tslat** [comment]
Gonna mark this as a duplicate since we have a newer one of the same thing in #4043
