### ISSUE TITLE
Wood giant's toughness values mismatch what's supposed to be there(?)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3678]
Wiki says these are the values
![image](https://user-images.githubusercontent.com/38159897/229679736-250418f9-0d14-4b37-adf6-8305ef9bd43a.png)

But ingame it's 40 at the first stage, then 25, then 10, and then none at the last stage

**Comment by Tslat** [comment]
Change wiki to current values I guess?
