### ISSUE TITLE
Mob magic damage ignores armor and i frames

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3682]
E.G. the Tree spirit projectile ignores armor

Should it stay around? It is magic damage, and vanilla/the staves establish magic damage as something that ignores armor

**Comment by Tslat** [comment]
Yes?
I'm confused as to what you're asking here lol

**Comment by Cruuk** [comment]
> Yes? I'm confused as to what you're asking here lol

Mob magic damage didn't ignore armor before (at least sometimes? Old Goblin didn't ignore armor, but I think there were a couple instances that did). I just wasn't sure if this change to make all AoA mob magic damage ignore armor was intentional and was going to stay around, so I made this post just to check

There have been instances of changes that I couldn't tell were intentional or not, like when mob magic damage dealt knockback again in a patch, so I was being extra sure here

**Comment by Tslat** [comment]
Oh yeah
Yeah that was an intentional change
