### ISSUE TITLE
Electinator's AoE energy damage isn't affected by damage boosts

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3688]
The amount energy damage by default is 0.2445. But regardless of damage boosts to the gun, the energy damage stays at that value

**Comment by Tslat** [comment]
Damage boosts?
You mean shell?

**Comment by Cruuk** [comment]
> Damage boosts? You mean shell?

Yes, any damage boost like shell and sharpshot armor. The changelog says it should scale with shell, so I presume it should scale with any damage boost

**Comment by Tslat** [comment]
Where'd the changelog say that?

**Comment by Cruuk** [comment]
> Where'd the changelog say that?

![image](https://user-images.githubusercontent.com/38159897/230745847-dd2bbee5-10d3-4279-9b23-c843c73eb14e.png)
<code>accounts for damage-boosts like shell</code>
