### ISSUE TITLE
Giant slugs and flamewalkers still create acid/fire when gamerule mobGriefing is false

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#369]
**Mod Version**
3.0.1

**Describe the bug**
Giant slugs create acid and flamewalkers create fire on Netherrack when gamerule mobGriefing is set to false. The expected behavior is that both mobs only create blocks when mobGriefing is set to true.

**To Reproduce**
Steps to reproduce the behaviour:
1. Type '/gamerule mobGriefing false'
2. Summon a giant slug with '/summon aoa3:giant_slug'

**Screenshots**
![image](https://user-images.githubusercontent.com/12868968/53303843-2313f780-3824-11e9-8910-71572a4fa264.png)

**Comment by Sagisolar** [comment]
Just gonna quote Scimi here.

"Given that basically every single server has mobgriefing off (for obvious reasons), this would basically render some mobs useless."

**Comment by Tslat** [comment]
It's an interesting and painful issue to solve..

Most places have mob griefing off, however if I elect to follow the same rules then these mobs will basically be turned into normal melee mobs, which defeats the purpose of them
