### ISSUE TITLE
When trading with AoA NPCs, the screen outside of the GUI doesn't darken as with vanilla GUIs

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#370]
**Mod Version**
3.0.1, no other mods

**Describe the bug**
When trading with AoA NPCs, the screen outside of the trading GUI remains the same as before. The expected behavior is that the screen darkens, similar to what happens when trading with vanilla villagers or opening chests.

**To Reproduce**
Steps to reproduce the behaviour:
1. Summon an NPC (e.g. `/summon aoa3:corrupted_traveller`, `/summon aoa3:gorb_engineer`)
2. Trade with it
3. Type `/summon minecraft:villager` and trade with it to compare

**Screenshots**
![image](https://user-images.githubusercontent.com/12868968/53303693-856bf880-3822-11e9-91b5-917c096f8959.png)
![image](https://user-images.githubusercontent.com/12868968/53303699-8f8df700-3822-11e9-99eb-94bd04d2b334.png)

**Comment by Tslat** [comment]
Sure
