### ISSUE TITLE
Nethengeic Wither's and Nethengeic Beast's death sounds cut off before they're finished.

### ISSUE THREAD

**Issue by SooshiGuy** [Tslat/Advent-Of-Ascension#3702]
Dunno whether or not this is intentional, but when a Nethengeic Beast, the Nethengeic Wither and its elite counterpart dies, the death sound they make will cut off before they have even finished playing. It just doesn't seem right to me.

**Comment by Tslat** [comment]
This was happening to me but has since stopped
Not sure if something else I did fixed it in the meantime
Check again after next update I guess?

**Comment by SooshiGuy** [comment]
So I tried killed a Nethengeic Beast to test it and the sound still cut off.
