### ISSUE TITLE
Kill a lelyetian_warrior with firework_rocket do not get the celeve_realmstone

### ISSUE THREAD

**Issue by willis1030** [Tslat/Advent-Of-Ascension#3707]
**Mod Version**
What version of the mod are you on?
AoA3-1.16.5-3.6.11

**Describe the bug**
Using firework_rocket killed a lelyetian_warrior do not get the celeve_realmstone.
A blank_realmstone is already there.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by Tslat** [comment]
Are you firing it from a crossbow?

**Comment by willis1030** [comment]
Sorry, I think I was misunderstand the usage, Now I got a celeve_realmstone, it's no problem.
Please close this issue.
