### ISSUE TITLE
Should magic projectile damage have no_impact

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3710]
Staves did kb before, so it is weird that they aren't now. Unfortunately I don't really have much else to say. Magic effect does make sense to have it, since it's like an AoE thing(?)

**Comment by Tslat** [comment]
Idk
Magic doesn't have a physical presence - it's the defining factor _of_ magic

It kinda makes sense to me that it doesn't have a physical force behind it unless the effect itself indicates so?

**Comment by Cruuk** [comment]
I guess
