### ISSUE TITLE
Add an is_melee tag for use with Fire Melee (if it stays around at all) and mob melee attack damage types

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3711]
If I missed something, close this post. Considering these are supposed to be melee-centric damage types(?), I don't really see anything in the code (at least at a decently thorough glance that I can mostly read) that indicates that these are actually affected by stuff like thorns or armor sets that affect melee attackers (Void armor, etc.). They should be affected for obvious reasons.

These 2 types are currently unused, and /damage can't be fully trusted, so I barely know what I'm talking about here

**Comment by Tslat** [comment]
It wouldn't really be useful for anything
