### ISSUE TITLE
Ruined Temple arena

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3712]
New boss arena

[ruined_temple.txt](https://github.com/Tslat/Advent-Of-Ascension/files/11271673/ruined_temple.txt)

I know, I couldn't help myself. We do already have Ruined teleporter.

Ignoring that, I think it works well as a boss arena with the pillar platforms and vines. It also still looks like a temple when you don't associate the specific connection. Size of the playable part of the arena is 37x37.

The holes have barrier blocks covering them.

![image](https://user-images.githubusercontent.com/38159897/233042351-01c36fdf-c18d-4ad8-8e82-469d238c516d.png)
![image](https://user-images.githubusercontent.com/38159897/233042458-b7cbc0b9-04d4-4ccb-94e2-973d97976ce9.png)
![image](https://user-images.githubusercontent.com/38159897/233042506-fe330d3c-d7c3-48c8-9507-f080a7753674.png)
![image](https://user-images.githubusercontent.com/38159897/233042587-d23463a7-8395-4b42-862a-992daa439f4d.png)
![image](https://user-images.githubusercontent.com/38159897/233042713-3f5e4fcb-2642-4718-9b68-0b7d7ca08752.png)

-------------

NOTE: When testing to make sure I did the structure block stuff correctly, these ancient vines specifically lost their cap. Don't know why it does that. Just something to watch out for
![image](https://user-images.githubusercontent.com/38159897/233043361-fdf6249d-08af-41d3-ac79-633f75d3be2b.png)

**Comment by SooshiGuy** [comment]
That's a good idea for paying tribute to Ancient Cavern.

I miss that dimension a lot; I always thought it was really cool. But I understand why it was removed ;(
