### ISSUE TITLE
Storm Rune Shrines don't work correctly, and Power Runes are unobtainable.

### ISSUE THREAD

**Issue by Uknowyourbored** [Tslat/Advent-Of-Ascension#372]
**Mod Version**
Version 3.0.1 for 1.12.2.

**Describe the bug**
In the Greckon, when you use a Rune on the Storm Rune Shrine, no Runes are made. However, if you manually replace the Storm Rune Posts with Power Rune Posts, then you acquire storm runes instead. However, you now can't make Storm Runes correctly, and Power Runes can't be made.

I also tested this in the Overworld and got the same effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to/make a Storm Rune Shrine
2. Attempt to make a Rune
3. Go to/make a Power Rune Shrine
4. Attempt to make a Rune

**Expected behavior**
Storm Runes are acquired from their shrine, and Power runes are acquired from their shrine.

**Comment by Tslat** [comment]
Fixed
