### ISSUE TITLE
Reliquary incompatibility with Advent of Ascension mod.

### ISSUE THREAD

**Issue by ghost** [Tslat/Advent-Of-Ascension#3724]
**Mod Version**
What version of the mod are you on?
AoA3-1.19.2-3.6.18.jar
**Describe the bug**
Just like the title says, it's impossible to run Reliquary with Advent of Ascension. I will attach below the log file with what went wrong in hopes this will be fixed as I really do not want to give up on either, Reliquary is a mod I've been using for a lot of time and Advent of Ascension is a mod I recently stumbled upon and it's really grown on me. I will have to disable one or the other for the time being and would love to know this has helped you in any way.

**To Reproduce**
Steps to reproduce the behaviour:
1.Have both mods ON
2.Start the game, move a few blocks
3.Crash
**Expected behavior**
To work

**Screenshots**
[crash-2023-04-30_04.07.50-client (1).txt](https://github.com/Tslat/Advent-Of-Ascension/files/11362591/crash-2023-04-30_04.07.50-client.1.txt)

**Comment by EatingSilencer** [comment]
Is Reliquary on 1.19.4? If yes, does this crash occur on 1.19.4?

AoA will never receive a 1.19.2 update again. I'm not sure if this crash would affect 1.19.4 aoa (Tslat might be able to check). Regardless, you won't be able to play AoA and Reliquary on 1.19.2 unless a different solution is found.

**Comment by ghost** [comment]
This is on 1.19.2, yes. I understand, thank you kindly for your prompt answer. I will play it on 1.19.4 when most of the mods I'm playing will be updated. Have an amazing one

**Comment by Tslat** [comment]
Updated on the reliquary github report
