### ISSUE TITLE
Increase the height of Desert arena's roof

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3728]
At the lowest part of the arena, the height to the ceiling is 13 blocks. It's 10 blocks to the ceiling at the highest part. This seems to be a bit too low for stuff like Neth wither trying to fly up or BBB's bomb rain thing attack. Even square arena's ceiling seems to be high enough for these attacks, and that arena's ceiling is 16 blocks high

**Comment by Ursun1** [comment]
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/19820954/37e64597-3f4d-47fa-b7ec-48721b0cdab5)
bbb projectiles are mostly blocked by the chandelier in this arena too
