### ISSUE TITLE
Acid blocks from Giant Slug and Skydriver bow remains when block underneath is broken

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#373]
**Mod Version**
3.0.1

**Describe the bug**
When you break the block below slug or skydriver bow acid, the acid remains floating until it eventually decays on its own. The expected behavior is that the acid disappears when the block underneath is broken.

**To Reproduce**
Steps to reproduce the behaviour:
1. Shoot an arrow with a skydriver bow, or summon a giant slug
2. Break the block below some of the acid blocks placed

**Screenshots**
![image](https://user-images.githubusercontent.com/12868968/53304054-142e4480-3826-11e9-8cbb-ab8a2dd45787.png)

**Comment by Tslat** [comment]
Fixed
