### ISSUE TITLE
Precasia at night issue

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#374]
**Mod Version**
3.0.1

**Describe the bug**
In Precasia at night, lighting is wonky. When I look at one direction its dark, but then the other direction its sort of evening. And I'm not using Optifine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Precasia (Night Time)
2. Look in lots of directions

**Screenshots**

![2019-02-24_20 19 52](https://user-images.githubusercontent.com/44548547/53307073-88033800-388c-11e9-8a41-6d5f5a211ed5.png)

Other direction.

![2019-02-24_20 19 51](https://user-images.githubusercontent.com/44548547/53307080-90f40980-388c-11e9-982b-49d7d5ef28e7.png)

**Comment by Tslat** [comment]
Yeah it's a weird interaction with fog and sky lighting
It'll remain as-is for now until I do something with the dimensions
