### ISSUE TITLE
Web Reaper is invicible

### ISSUE THREAD

**Issue by withtheloveofocean** [Tslat/Advent-Of-Ascension#3746]
**Mod Version**
1.16.5 3.6.11

**Describe the bug**
Web Reaper is (almostly) immortal.
In more detail; their hp is 106 and if I attack with iron sword, then the hp will down to 100.
However, if I attacked again, it's still "100".
In addition, first, attack with iron sword and hp will be 100.
After that, attack with wodden sword... and hp become 102.

In summary; if you wanna kill Web Reaper, you should give them over 106 damage.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Abyss'(or summon)
2. Attack on 'Web Reaper'
3. You'll never get them.

**Expected behavior**
Web Reaper will hurt, but they won't be killed

**Comment by Tslat** [comment]
Unable to replicate

Confirm it happens with no other mods present

**Comment by withtheloveofocean** [comment]
I tried and certainly no problem, my bad.
"performant" was the cause.
