### ISSUE TITLE
Shield nerf

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#375]
By now it's fairly obvious that shields are being nerfed, due to how OP they are. However, I think it shouldn't be something like making it last less time against AoA mobs. The shields make fighting AoA mobs a lot fairer, and besides, it wouldn't solve the issue. It would just require you bring a few extra shields. If anything, it'd get annoying since you have to constantly spend iron making shields. Instead, I suggest a new mechanic for shields. The first time you block an attack would be normal. However, if you block an attack from the same mob shortly after (maybe 1-3 seconds afterwards), you will take knockback instead of the mob, and the shield will be thrown to the ground. If you were to somehow pickup the shield and block the same mob again before the cooldown ends, you would take 50% of the damage you would take without blocking, and the other 50% would be subtracted from the shield's durability. In addition, the second effect would repeat. Shields would still be viable while not being able to be used for immortality. It would also allow the addition of new gear and mechanics relating to shields in the future.

**Comment by Sagisolar** [comment]
At this point we should just accept that shields are good. I can't name another mod that try to nerf the shield. I think its just better to do nothing about it. The whole vanilla experience is based around protecting yourself with them. And Aoa should be no different. You could allow mobs that inflict status like poison and wither to give the effects even when holding the shield, but not a direct nerf.
