### ISSUE TITLE
Problem with projectiles

### ISSUE THREAD

**Issue by Oysumida** [Tslat/Advent-Of-Ascension#3757]
**Mod Version**
1.19.2-3.6.18

**Describe the bug**
Every enemy that uses a projectile crashes the server

**To Reproduce**
don't know if its reproducible, but i'll attach the crash report

**Screenshots**
[crash-2023-05-22_22.06.04-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/11538252/crash-2023-05-22_22.06.04-server.txt)

Thank you in advance

**Comment by Tslat** [comment]
Need to use an older version of SmartBrainLib
