### ISSUE TITLE
King Bambambam Sticky Fire Bomb Lag

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#3769]
Sometimes when King Bambambam uses his sticky fire bomb attack the game heavily lags until it is over. This may have been due to the reduced radius of the updated attack. I can't say however if this only affects my computer, however, so maybe others should test it as well.

**Comment by Tslat** [comment]
Could the quantity of particles too
Does it happen if you set particles to minimal?

**Comment by TripleThreeT** [comment]
Oh true! Particles set to minimal cause no lag. Makes sense.

**Comment by TripleThreeT** [comment]
In fact putting it on decreased instead of fancy fixed my issue as well. Honestly, I don't know why I didn't think about that lol.

**Comment by Tslat** [comment]
Yeah..

I did reduce the particles somewhat prior to release
But there's just a lot going on, and without the particles it looks quite bare
