### ISSUE TITLE
Skills have been disbled by the sever owner

### ISSUE THREAD

**Issue by Yuukl** [Tslat/Advent-Of-Ascension#3783]
**Mod Version**
3.6.11

**Describe the bug**
Me and my friends when playing multiplayer,My skills will be disabled，but my friend is no problem
not in the server
And the icon will also disappear,the shortcut keys do not respond.

**Expected behavior**
Hopefully it will be repaired

**Screenshots**
[https://s2.loli.net/2023/06/13/BOVXTsQknUG3cdK.png](url)
[https://s2.loli.net/2023/06/13/dOiy24uqHzD3ACU.png](url)

**Comment by EatingSilencer** [comment]
This bug is caused by using LAN. Tslat doesn't seem to fix there's a good fix for it so you'll just have to make do with what you can get away with (restarting LAN, or switching to a different type of server, etc).

**Comment by Yuukl** [comment]
Thanks，i see.

**Comment by 1nstoppable** [comment]
> This bug is caused by using LAN. Tslat doesn't seem to fix there's a good fix for it so you'll just have to make do with what you can get away with (restarting LAN, or switching to a different type of server, etc).

Like what? I'm using Radmin VPN and my server's abilities are turned off.

**Comment by 1nstoppable** [comment]
> Thanks，i see.

Were you able to fix that?
