### ISSUE TITLE
Going to "Nowhere 1st Portal" deletes inventorio tools

### ISSUE THREAD

**Issue by StormyShocks** [Tslat/Advent-Of-Ascension#3789]
**Mod Version**
AoA3-1.19.4-3.6.26
**Inventory Mod**
inventorio-1.19.4-forge-1.9.1

**Describe the bug**
I was just hitting level 100 in extraction and saw I could wear a new helmet. I decided to figure out how to get it and saw I had to go to "Nowhere" I went there and everything was fine. I had my tools and everything but once I went into the first teleporter on the left then came back my inventory was in my hotbar and all my tools were deleted. Im posting this bug to both mods.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Nowhere'
2. Enter '1st portal on left'
3. Exit back to 'Nowhere'
4. Tools in the Inventorio slots are gone and my inventory is moved to fill my hotbar

**Expected behavior**
Exit portal just like the other portals in AoA and still have my inventory just fine

**Screenshots**
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/137071724/55049f8b-d2b2-4890-a707-93cd65835a47)
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/137071724/9456c37d-68ca-4b66-9de4-4c4ab8ad002b)

**Comment by StormyShocks** [comment]
It had also deleted my armor. I did not notice this the first time

**Comment by Cruuk** [comment]
You can't bring items into the Parkour lobby. It should give you back your inv upon exiting parkour lobby. If it didn't, report it in detail so it can be fixed
