### ISSUE TITLE
Occult Pickaxe is buggy

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#379]
Occult pickaxes causes blocks like this if the ore it's revealing is directly visible:
![2019-02-24_19 17 36](https://user-images.githubusercontent.com/19913710/53308132-b8d37500-386c-11e9-8d2b-bfa5fbe38f36.png)

Also, the outlines are two blocks high, which is confusing.

**Comment by Tslat** [comment]
Fixed
