### ISSUE TITLE
Trim Armor, but with AOA materials

### ISSUE THREAD

**Issue by ArcticAbyss1979** [Tslat/Advent-Of-Ascension#3791]
As the armors in AOA now can be trimmed.

It would be even better if the materials in AOA could be used for trim, as the vanilla materials does not offer many colours and only covers a few hues.
![Sug1](https://github.com/Tslat/Advent-Of-Ascension/assets/132092994/d16a5454-ad7c-4698-b7a3-9a8177363bb2)

**Comment by Tslat** [comment]
Can't be done currently, the vanilla system does not support this
