### ISSUE TITLE
Upgrade kits

### ISSUE THREAD

**Issue by Moonseer12** [Tslat/Advent-Of-Ascension#3792]
Updated all the textures for the upgrade kits

![AoA Upgrade Kits](https://github.com/Tslat/Advent-Of-Ascension/assets/79872729/6bdc1b6f-a8f4-4206-9323-a38bb72a613c)

[AoA Upgrade Kits.zip](https://github.com/Tslat/Advent-Of-Ascension/files/11887793/AoA.Upgrade.Kits.zip)

Also rename the Weapon Parts to the Mystical Upgrade Kit since there's no reason for it to be different from the others

**Comment by Cruuk** [comment]
Not sure about these. They mainly just look too similar and I don't really like the shape. Don't really see a need to change the upgrade kits. Can still work as a texture pack at least
