### ISSUE TITLE
King BamBamBam Fireball Attack Problem

### ISSUE THREAD

**Issue by SooshiGuy** [Tslat/Advent-Of-Ascension#3795]
So I tried out fighting King BBB in the shrin arena, which has a very low ceiling, and the fireball attack doesn't work properly there. I would probably change it so the sticky fireballs phase through the underside of a block, only ever landing on the tops of blocks.

**Comment by Tslat** [comment]
Doesn't work properly?

**Comment by SooshiGuy** [comment]
Well idk if that is how it's supposed to work. Basically, the fireballs don't travel very far if there is a ceiling above them, making them easier to avoid.

**Comment by Tslat** [comment]
Yeah I'm ok with it
Can't be perfect
