### ISSUE TITLE
Buff Occult pickaxe

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#380]
I think Occult Pickaxe is way too underwhelming for how long it takes to get. I think the outlines should have different colors depending on the ores, and revealing should only take having the pickaxe in your hand (if that's too overpowered, make it work when mining stone. If that's still too OP, then at least increase the amount of time ores are revealed. They go away so quickly it's hard to even fully look around)

**Comment by Tslat** [comment]
Done
