### ISSUE TITLE
Lack of mobs and measurements on version 1.18.2

### ISSUE THREAD

**Issue by Morozzovvv** [Tslat/Advent-Of-Ascension#3803]
Hello creator of the Advent Of Ascension mod, when will mobs and dimensions be available on version 1.18.2?
I've been looking for this mod for this version for a long time, but why did I search the Internet for this mod for a week if everything I need is missing?=(
Thx.

**Comment by Tslat** [comment]
https://adventofascension.fandom.com/wiki/Player_questions#Why_aren't_the_portals_working?
