### ISSUE TITLE
The game crashed whilst unexpected error entity.boss.smash 1.20.1 forge

### ISSUE THREAD

**Issue by OBS3SS1ON** [Tslat/Advent-Of-Ascension#3805]
AoA3-1.20.1-3.6.27
1.20.1-forge-47.0.35
[crash-2023-07-02_17.44.33-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/11931377/crash-2023-07-02_17.44.33-client.txt)
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/11931380/latest.log)
[debug.log](https://github.com/Tslat/Advent-Of-Ascension/files/11931382/debug.log)

The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: class net.tslat.aoa3.content.entity.boss.smash.SmashEntity tried to access private field net.minecraft.world.entity.Entity.f_19793_ (net.tslat.aoa3.content.entity.boss.smash.SmashEntity is in module aoa3@3.6.27 of loader 'TRANSFORMER' @77a9ac36; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @77a9ac36)

**Comment by Tslat** [comment]
Duplicate

**Comment by OBS3SS1ON** [comment]
now 
The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: class net.tslat.aoa3.content.entity.mob.overworld.SandGiantEntity tried to access private field net.minecraft.world.entity.Entity.f_19793_ (net.tslat.aoa3.content.entity.mob.overworld.SandGiantEntity is in module aoa3@3.6.27 of loader 'TRANSFORMER' @655909e2; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @655909e2)
1.20.1-forge-47.0.43
AoA3-1.20.1-3.6.27
