### ISSUE TITLE
The game crashed whilst unexpected error mob.overworld.SandGiantEntity 1.20.1 forge

### ISSUE THREAD

**Issue by OBS3SS1ON** [Tslat/Advent-Of-Ascension#3808]
1.20.1-forge-47.0.43

The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: class net.tslat.aoa3.content.entity.mob.overworld.SandGiantEntity tried to access private field net.minecraft.world.entity.Entity.f_19793_ (net.tslat.aoa3.content.entity.mob.overworld.SandGiantEntity is in module aoa3@3.6.27 of loader 'TRANSFORMER' @655909e2; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @655909e2)

[crash-2023-07-04_21.29.23-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/11952815/crash-2023-07-04_21.29.23-client.txt)
[debug.log](https://github.com/Tslat/Advent-Of-Ascension/files/11952817/debug.log)
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/11952818/latest.log)

**Comment by Tslat** [comment]
Duplicate
