### ISSUE TITLE
New skill suggestion

### ISSUE THREAD

**Issue by TekterBR** [Tslat/Advent-Of-Ascension#381]
Skill for crafting and cooking

Crafting weapons and cooking food would increase the level of the skill
With higher levels, new weapons and food could be crafted/cooked and with higher levels, foods would have better effects
Different items would give different amounts of xp
This would give a sense of progression while making the obtainment of weapons more progression dependent

The weapons and food could be crafted/cooked in new crafting stations
I would recommend a NEI integration to add the recipes, since it became a common thing in the newest mods

The main idea of adding this skill is to add **IMMERSION**

I think other types of items could be made in the same way

**Comment by TekterBR** [comment]
Probably too much work for a simple addition

**Comment by DiamondWalker** [comment]
I believe it's been officially confirmed that alchemy and engineering will be the last skills. I do like the idea of a cooking skill, but I don't see how it's related to crafting weapons (which imo wouldn't make sense as a skill). I do think more crafting stations should be added. The only modded crafting station so far is the lunar crafting station, which is only used for a couple items anyways.

**Comment by TekterBR** [comment]
I thought more on the crafting side
Like, you have better skills at creating things, then you can create better things
Cooking better is just a result of "having good hands"

It's just a supperficial idea, but could be improved

**Comment by DiamondWalker** [comment]
In that case, it should be divided into two different skills
