### ISSUE TITLE
[1.20.1] New release crashing on new forge launch

### ISSUE THREAD

**Issue by MrKashew** [Tslat/Advent-Of-Ascension#3813]
**Mod Version**
AoA3-1.20.1-3.6.28

**Describe the bug**
[crash-2023-07-08_02.07.01-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/11990318/crash-2023-07-08_02.07.01-client.txt)

Launch crash

**Comment by Tslat** [comment]
Install TslatEntityStatus =/
I forgot to make it optional

**Comment by MrKashew** [comment]
Thanks @Tslat I see - I tried removing it from the mods.toml and it still errors
gotcha - I'll go ahead and try it with TES
will it be made optional in the future?

**Comment by Tslat** [comment]
Try redownloading from CurseForge
