### ISSUE TITLE
Add TslatEntityStatus to the required dependencies in `mods.toml`

### ISSUE THREAD

**Issue by samjviana** [Tslat/Advent-Of-Ascension#3814]
Add [TslatEntityStatus](https://www.curseforge.com/minecraft/mc-mods/tslatentitystatus-tes) dependency as required in the AoA3 `mods.toml`

As of AoA3 3.6.28 update, the game is crashing at the launch if you try to start it without the TslatEntityStatus mod, which wasn't happening before, I've looked into the `mods.toml` and this dependecy is flaged as not mandatory.

**Comment by Tslat** [comment]
It's not mandatory

I accidentally left some code in there that tries to load it even if it's not present
