### ISSUE TITLE
Idea: Make Players unable to teleport to Nowhere with Boss Items unless they are at full health and hunger.

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#3818]
I noticed that there's somewhat of a strategy to use the boss summoning items to heal to full health and hunger in Nowhere and then swiftly return back to their previous location. It's incredibly OP and ruins any challenge you have in the world. The solution I thought of is pretty simple. Unless you are at full health and hunger, you are unable to teleport to Nowhere using the Boss Items. Maybe a message would be given saying "You don't have the strength/energy to use this item". This way, the items won't used as escape and heal options.

**Comment by Cruuk** [comment]
Hmm, 1 of the more interesting solutions I've seen
