### ISSUE TITLE
Bug ( Minecraft 1.12.2 )

### ISSUE THREAD

**Issue by Kasia1403** [Tslat/Advent-Of-Ascension#3820]
Creeponia mobs don't spawn.

AoA3 version 3.3.6

Forge version 14.23.5.2860

**Comment by Tslat** [comment]
Creeponia mobs spawn fine for most people - you might have another mod conflicting with it

1.12 is old

**Comment by EatingSilencer** [comment]
You can try coming to the Discord server if you need help with this.

**Comment by Kasia1403** [comment]
I found that it is a conflict with Dr Zhark's Custom Mob Spawner mod. Could Someone fix this ?

**Comment by Tslat** [comment]
it's not a conflict
CustomMobSpawner is a broken mod, always has been
