### ISSUE TITLE
Can't attack if i switch mouse keybinds

### ISSUE THREAD

**Issue by Ciborg085** [Tslat/Advent-Of-Ascension#3824]
**Mod Version**
3.3.6, Minecraft 1.12.2

**Describe the bug**
If you switch keybinds of right and left click, i haven't tested all weapons, but at least the Tidal Greatblade and Vulcammer Maul, simply can't hit any mobs.

**To Reproduce**
Steps to reproduce the behaviour:
1. To go Options->Controls
2. Change Attack/Destroy to RightClick
3. Change Use Item/Place block to LeftClick
4. Try to hit a mob
5. Doesn't do anything

**Expected behavior**
Expected behavior would be it doing damage and the attack connecting to the target.

**Other_Comment**
So i assume that for some reason the attacks of weapons from AoA are hard coded to only work with Right Click.

**Screenshots**
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/34816162/056ddfe9-11f7-41b9-bd08-e93d2eb48a0d)

**Comment by Tslat** [comment]
1.12 is a long-dead version

It's just one of the leftover bugs on that version

**Comment by Ciborg085** [comment]
k
