### ISSUE TITLE
a crash about mob battle mod

### ISSUE THREAD

**Issue by skybirdsweet** [Tslat/Advent-Of-Ascension#3827]
Mod Version
AoA3 1.20.1-3.6.28
mob battle-1.20.1-2.4.4-forge

Describe the bug
when I use mob army want elite boss to battle with other mob in other mod ,when they fight at climax ,the game was crash 

To Reproduce
Steps to reproduce the behaviour:
1. Go to a save and summon aoa's boss and other mod's boss
2. use mob army to set their team
3. and they fight as normal as 

Expected behavior
when I used mob army make a brawl to aoa's boss and other mod's boss, when the fight a few second ,the game was crashed
Screenshots
[crash-2023-07-17_21.23.38-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/12070264/crash-2023-07-17_21.23.38-server.txt)
[crash-2023-07-17_22.29.13-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/12070465/crash-2023-07-17_22.29.13-server.txt)
[crash report-2023-7-17_22.29.22.zip](https://github.com/Tslat/Advent-Of-Ascension/files/12070469/crash.report-2023-7-17_22.29.22.zip)

**Comment by Tslat** [comment]
Take it to mob battle
