### ISSUE TITLE
Texture Improvements

### ISSUE THREAD

**Issue by Tim79000** [Tslat/Advent-Of-Ascension#3829]
Can I make updated textures for the mod?

**Comment by Tim79000** [comment]
I can't find texture resources in the project.

**Comment by Tslat** [comment]
Join the discord if you intend to do retexture stuff

**Comment by Tim79000** [comment]
I don't really want to join large servers due to personal issues.

**Comment by Tim79000** [comment]
I'm sending a Curseforge message with my Discord name.

**Comment by Tslat** [comment]
Kinda hard to go through community feedback if you can't be a part of the community lol

**Comment by Tim79000** [comment]
I sent a curseforge message lol
