### ISSUE TITLE
About spectral and more

### ISSUE THREAD

**Issue by SagvinYg** [Tslat/Advent-Of-Ascension#383]
There have been spectral arrows in 1.12, why not add glowing effect for spectral wizards, bows and archerguns?
Or change the ammo of spectral bow and archergun into spectral arrow?
Beyond all of that, what about adding more new effects in 1.12 such as levitation for mobs and weapons? I think this is a good way to bring new blood into this mod.

**Comment by Tslat** [comment]
Spectral holly arrows already exist, they're just not currently obtainable ;)

**Comment by SagvinYg** [comment]
Ummm, I mean if spectral wizard or spectral bow can inflict glowing effect since they have a same name with spectral arrow
