### ISSUE TITLE
Barathos (and maybe other AoA dimensions) are generating as a floating island

### ISSUE THREAD

**Issue by BloxMaster3** [Tslat/Advent-Of-Ascension#3832]
**Mod Version**
3.3.6

**Describe the bug**
Barathos (and maybe other AoA dimensions) are generating as a floating island with no terrain around it and no matter how far I fly, nothing generates

**To Reproduce**
Steps to reproduce the behaviour:
download all of my mods and optifine with BSL shaders and go to barathos  
**Expected behavior**
barathos should generate as a floating island

**Screenshots**
![2023-07-23_21 07 54](https://github.com/Tslat/Advent-Of-Ascension/assets/136217084/e79d1d31-016f-4629-9a72-a3c91dd9e568)
![2023-07-23_21 01 11](https://github.com/Tslat/Advent-Of-Ascension/assets/136217084/554c80a1-4c93-4304-8ce4-c7a3c21a4e65)

debug and latest logs for mod list and more info:
[Logs.zip](https://github.com/Tslat/Advent-Of-Ascension/files/12140684/Logs.zip)

**Comment by Tslat** [comment]
Mod conflict with another mod
Try removing mods until it gets fixed, to work out which mod it is
