### ISSUE TITLE
[1.18.2] Client crash while hosting lan players on toast- java.lang.NullPointerException: Cannot invoke "net.tslat.aoa3.player.skill.AoASkill.getRegistryName()" because the return value of "net.tslat.aoa3.player.skill.AoASkill$Instance.type()" is null

### ISSUE THREAD

**Issue by ProsperCraft** [Tslat/Advent-Of-Ascension#3836]
**Mod Version**
AoA3-1.18.2-3.6.6.jar

**Describe the bug**
Client crash
https://gist.github.com/ProsperCraft/93729546fc5b41b42a3c536c6b69ecef

Toast control was removed after the last crash because I saw this stacktrace in closed issues on prior Minecraft versions and someone said Toast control was not compat, so it was not running while I had this crash.

**Comment by Tslat** [comment]
1.18 aoa is done, this won't be fixed there
