### ISSUE TITLE
Make obtaining each carved rune unique

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#384]
I think each carved rune should have a unique way of obtaining it, since currently only the rune of power does.

Rune of power could stay as it is.

Rune of direction could stay as it is.

Rune of Space could be given to you by Krasaun the first time you please him

Rune of Reality could drop from bosses

Rune of Travel could be crafted using a range of materials dropped by mobs in different environments (could be connected to the loot overhaul)

**Comment by Cruuk** [comment]
Have you ever tried pleasing Krasaun legit? Mainly in earlygame? It's basically impossible unless you set up shit like giant farms ahead of time, something that'll take newer players a lot of time. It's also near impossible to please Pluton without high levels of Foraging/Logging/Extraction, unless you win the goddamn lottery. Consider all the things you have to do in the span of 10 minutes.

Honestly it's not a bad suggestion. It's interesting, though I would prefer if you could still find them in chests even if this was added.

Hell, maybe you could make the Krasaun one more rewardable by having him give you 1-3 random carved runes each time, adding a difficult method of making the carved runes renewable (which I've wanted for a while), considering that there are a limited amount of loot chests and ruined teleporters.
