### ISSUE TITLE
Haven missing message and music

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#385]
**Mod Version**
3.0.1

**Describe the bug**
Using the Haven realmstone on the ancient teleporter opens the portal, but there's no music or message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the Haven realmstone on an ancient teleporter

**Expected behavior**
Opening the Haven portal should give a message and play music.

**Comment by Tslat** [comment]
Unable to replicate

**Comment by Tslat** [comment]
Fixed
