### ISSUE TITLE
Boss fights in Nowhere

### ISSUE THREAD

**Issue by XxDuckyUxX** [Tslat/Advent-Of-Ascension#3852]
I understand the implementation of this, but having the bosses only be fought in nowhere is really strange. Even more so if you are an experienced AoA player. I can see bosses like the Primordial Five, The Four Guardians, The immortals, and the Elite bosses being fought exclusively in Nowhere, but other bosses like Skeletal Army, Voxxulon, Cotton Candor, Smash, Kror, etc. would feel out of place *not* being in their respective dimensions. 

I don't think it's a bad idea in general, but it is kind of weird having to fight them in Nowhere.

**Comment by Cruuk** [comment]
I think it's nice. Saying it's "weird" doesn't really describe anything beyond just simple change aversion.

There's a lot of reasons it was done, but to sum it up it's built off over a decade of imperfect solutions to dealing with the fact that MC is a very bad game for boss fights, and over the years there has been a large want to remove sandbox cheese from boss fights in a non-intrusive way, along with the annoyance of boss fights being interrupted by other mobs in dims

"Even more so if you are an experienced AoA player"? So just change aversion? The whole thing with it feeling "out of place" is mostly charged by change aversion. There will still be boss-esque mobs like the minibosses (the giants, etc.) in the dims for a more environmental challenge

![image](https://github.com/Tslat/Advent-Of-Ascension/assets/38159897/ff1651e5-3b38-47b1-8288-2851754da344)

There's nothing stopping you from doing custom stuff and moving the bosses to the dims anyway
