### ISSUE TITLE
Gun damage does not apply correctly.

### ISSUE THREAD

**Issue by EisiaDEV** [Tslat/Advent-Of-Ascension#3858]
**Mod Version**
What version of the mod are you on?

1.16.5

**Describe the bug**

Damage from guns firing more than one shot per second does not apply correctly. Bullets can only cause damage once a second, and all other bullets fired lesser than a second after firing cannot cause damage.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

Every gun that fires more than one shot per second must have the correct damage applied to each bullet.

**Screenshots**

[https://www.youtube.com/watch?v=uqp-Ee5ANug](url)

**Comment by EisiaDEV** [comment]
I'm new at github, so I accidently attached incorrect(?) Youtube link. 

> https://www.youtube.com/watch?v=uqp-Ee5ANug
the correct link.

**Comment by Tslat** [comment]
Looks like you have some other mod conflicting

That's definitely not how gun damage works in current AoA

Also, you're testing it on a mob with significant armour values.... of course the damage will be lower
