### ISSUE TITLE
Throwables not working in survival mode

### ISSUE THREAD

**Issue by alpkey** [Tslat/Advent-Of-Ascension#3863]
I am using the latest version of Nevermine for 1.12.2 and I am using it in the hexxit updated modpack.

I cannot throw throwables in survival mode but I can in creative. Also this makes it so I cannot use weapons that need certain throwables as ammo (like a blaster needing grenades for ammo not shooting)

Just any kind of throwable like grenades, gooballs, etc. does not work. But in creative I can throw them and use the guns that need throwables.

Other weapons that require regular ammo like popshots seem to work in survival tho.

**Comment by alpkey** [comment]
I just realized that only cannons require throwables as ammo which are grenades, so yeah I cannot use cannons.

**Comment by Cruuk** [comment]
This is a known issue with that modpack. Generally it is not recommended to play AoA in that modpack as it is not well designed and has caused issues that we are unable to fix. I recommend playing another pack like AoA Plus
