### ISSUE TITLE
aoa3 nether realmstone doesn't work

### ISSUE THREAD

**Issue by Ultimate500** [Tslat/Advent-Of-Ascension#3871]
**Mod Version**
1.19.2 aoa3

**Describe the bug**
I do the task to obtain the nether realmstone but when I throw the blank realmstone in lava, submerged by lava, the blank realmstone burns and I don't get the nether realmstone

**To Reproduce**
Steps to reproduce the behaviour:
1. Try the nether realmstone task
2. See error

**Expected behavior**
The Nether Realmstone task works.

**Screenshots**

![2023-08-26_21 08 35](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/d4af4ec0-802b-4f7f-8d00-971049499540)

![2023-08-26_21 08 38](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/a07c66c1-aad4-4916-80b1-853e666e1a91)

![2023-08-26_21 09 30](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/a14b80f2-f564-493e-b25e-a54345fca068)

![2023-08-26_21 09 42](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/0507ddd0-eb33-43f5-9f1c-3ce9f23dbd86)

![2023-08-26_21 09 45](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/4c5232c3-3e44-407a-a939-d53a4c9011be)

![2023-08-26_21 09 46](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/3ec160c6-3404-4d34-a3d1-cfefadb2ee02)

**Comment by EatingSilencer** [comment]
1.19,2 aoa is getting no more updates.

**Comment by Ultimate500** [comment]
I don't know what you say

**Comment by EatingSilencer** [comment]
> I don't know what you say

There won't be another update to 1.19.2 aoa, so this bug will never be fixed in that version.
