### ISSUE TITLE
aoa nether realmstone doesn't work and I can't enter in other dimensions like precassia

### ISSUE THREAD

**Issue by Ultimate500** [Tslat/Advent-Of-Ascension#3876]
**Mod Version**
1.19.2-3.6.18 v43.2.21 with a 100 others mods. If you want my mods list, chat me.

**Describe the bug**
When I do the task to have the nether realmstone, when I drop the blank realmstone by submerged by lava I don't receive the nether realmstone. Pls help.

**To Reproduce**
Steps to reproduce the behaviour:
1. Do the nether realmstone task
2. See error

**Expected behavior**
To unlock the other realmstone task and to go in others dimensions

**Screenshots**
![2023-08-26_21 08 35](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/6b212c7e-6fdf-4759-87c1-8eb785caf1ca)
![2023-08-26_21 08 38](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/b611fb48-0e86-4ac9-b078-a48f60e531c1)
![2023-08-26_21 09 42](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/0e11ee1d-b947-4fcb-bef6-92fd05d67f4b)
![2023-08-26_21 09 45](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/62632c85-13fb-43f2-9910-a319524051fa)
![2023-08-26_21 09 46](https://github.com/Tslat/Advent-Of-Ascension/assets/143289410/b24d8d9c-054f-4115-be1f-f778bf074ba2)

**Comment by Tslat** [comment]
PLease read any of the warning messages on the curseforge page
