### ISSUE TITLE
Update checker

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#389]
https://discordapp.com/channels/434160774546456590/434160774546456594/549389936235773982

According to this the update checker causes large hangups if it can't reach Tslat's server, which can happen due to playing offline or intermittent server issues even when playing online. I've experienced the hangup myself and it takes upwards of 10 minutes oftentimes.

I should not have to be connected to the Internet in order to avoid waiting an extra ten minutes for an update check, much less wait due to random server issues on the other end beyond my control regardless of me being connected to the Internet or not.

Maybe time out the update check faster, or add a config option to disable it (enabled by default)?

**Comment by Tslat** [comment]
This should be fixed in 3.0.2
