### ISSUE TITLE
Squids should still spawn in L'Borean

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#390]
In my opinion, Squids spawning in L'Borean was one of those things that made Aoa dimensions charming. I'm very disappointed that they don't in 3.0.1. So I think they should be brought back.

If the weird spawning issue thing with Squids in 1.12.2 is too much, I guess we would have to wait until Aoa updates to a later version idk.

**Comment by Immortallis1** [comment]
> 
> 
> In my opinion, Squids spawning in L'Borean was one of those things that made Aoa dimensions charming. I'm very disappointed that they don't in 3.0.1. So I think they should be brought back.
> 
> If the weird spawning issue thing with Squids in 1.12.2 is too much, I guess we would have to wait until Aoa updates to a later version idk.

*Aoa dimension
