### ISSUE TITLE
Hellfire not igniting or damaging targets.

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#3904]
**Mod Version**
Latest Version

**Describe the bug**
The Hellfire will be thrown and nothing will occur.

**Comment by EatingSilencer** [comment]
What is latest version? 1.20.1-3.6.30? Or 1.16.5-3.6.11?

**Comment by TripleThreeT** [comment]
1.20.1-3.6.30
