### ISSUE TITLE
Mobs have no AI

### ISSUE THREAD

**Issue by GreenWither** [Tslat/Advent-Of-Ascension#3910]
**Mod Version**
3.6.30, really any 1.20.1 version

**Describe the bug**
Almost no mobs have any AI, either standing still, or floating away when hit. This was found out with mods, so I went to test with just AoA and still had the same issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a world
2. Spawn any (implemented) mob
3. See error

**Expected behavior**
Hostile mobs to move toward the player, Passive mobs to move freely

**Screenshots**
![2023-09-12_13 19 26](https://github.com/Tslat/Advent-Of-Ascension/assets/75867133/224c633a-0340-4cee-93cc-f9cc7e068a1e)

**Comment by Tslat** [comment]
forge bug
