### ISSUE TITLE
Mobs dont spawn on dimensions

### ISSUE THREAD

**Issue by SARC192** [Tslat/Advent-Of-Ascension#3911]
**Mod Version**
AoA3-3.3.6

**Describe the bug**
In the overworld mobs spawn naturally but on dimension they dont spawn only by generators, i walked over 3000 blocks and i didnt see any mob, i have some other mods but i tried them one by one with this mod, and there were no problems in spanwning of mobs, only in the server im in, i tried to change the config file but nothing happened, also i use journey and i cant see any red mark that shows enemies around

**Expected behavior**
The mobs should spawn normally

**Screenshots**
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/144977448/d21795d9-1e6c-4edd-a096-9da6b4d54b5e)
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/144977448/972f7068-12e9-48ba-b92c-be68d7bba2e8)

**Comment by Tslat** [comment]
Probably a mod conflict

If you have custommobspawner installed, remove it

1.12 is a long dead version

**Comment by SARC192** [comment]
> Probably a mod conflict
> 
> If you have custommobspawner installed, remove it
> 
> 1.12 is a long dead version

Thank u i have it installed i will  remove that mod
Edit: It worked, now mobs spawn normally, thank you so much :)
