### ISSUE TITLE
Adjust the ui position of skills

### ISSUE THREAD

**Issue by Moshanxi** [Tslat/Advent-Of-Ascension#3912]
![ILVOQKVKLA1BVT2G(W_1F9B](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/ec9c8142-30f6-4417-97ec-859eb40bcef9)

The last digit of the number exceeds the border

**Comment by Moshanxi** [comment]
And the "force unicode font" is off

**Comment by Tslat** [comment]
I don't appear to be able to replicate this
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/7098525/9327036e-1a83-46fa-a359-f8cfa9f29d91)

**Comment by Moshanxi** [comment]
Thanks. Maybe that is caused by the ModernUI mod. Fonts of skill abilities in Chinese preform badly without MUI.
And I will try to adjust the configuration be more compatible with AoA
