### ISSUE TITLE
i crash immediately when going to any dimention besides the others i had 

### ISSUE THREAD

**Issue by geterhun** [Tslat/Advent-Of-Ascension#3914]
**Mod Version**
What version of the mod are you on? 1.20.1

**Describe the bug**
i just make the portal and i crash it crashes by itself and with my other server with modpacks

**To Reproduce**
Steps to reproduce the behaviour:
this is the error i get "java.lang.NullPointerException: Cannot invoke "net.minecraftforge.registries.RegistryObject.get()" because the return value of "net.tslat.aoa3.content.item.misc.Realmstone.getPortalBlock()" is null"

**Comment by Tslat** [comment]
The other dimensions don't exist

Read the big read bold warning message that happens every single time you join the game
or the big red warning at the very top of the curseforge page
