### ISSUE TITLE
Supremacy Sword Rework

### ISSUE THREAD

**Issue by Axid-Cobravin** [Tslat/Advent-Of-Ascension#392]
With the addition of cleave on swords, the effect of the Supremacy Sword is made obsolete. Being that amethyst is reasonably hard to acquire in large quantities, I think the Supremacy Sword should be reworked to do full damage on cleave. This will make the sword's effect relevant and buff its power level to make up for its rarity in comparison to limonite, which does almost the same damage and is extremely easy to acquire in large quantities.

**Comment by Tslat** [comment]
3.2 Did things
