### ISSUE TITLE
/weather command does not work in Precasia

### ISSUE THREAD

**Issue by Ursun1** [Tslat/Advent-Of-Ascension#3920]
**Mod Version**
3.6.31

**To Reproduce**
Steps to reproduce the behaviour:
1. Wait for it to rain
2. Type /weater clear 10000
3. See error

**Comment by Tslat** [comment]
I think this may actually be a vanilla or forge bug lol
I still haven't figured out why it's happening yet

**Comment by Moshanxi** [comment]
The mod Cross-Dim Commands may solve it.

**Comment by Tslat** [comment]
Yeah vanilla bug
