### ISSUE TITLE
Smilodon and other hostile Precasia creature issues

### ISSUE THREAD

**Issue by Ursun1** [Tslat/Advent-Of-Ascension#3922]
**Mod Version**
3.6.31

- Smilodon has no extra forward movement while it does the leap (unless it's not intended). Maybe it shoud do multiple leaps in succession and then circle around the taget to make it differ from Veloraptor?
- Smilodon has issues with hitting targets in "hugging" range even when it triggers the attack anim. Target moving sideways even slightly can completely avoid damage from the leap
- Smilodon has issues with attacking targets with large hitboxes (most notably Deinotherium). After attacking continues to bump into the target and do nothing else
- Hostile creatures continue to chase their targets, ingoring the player attacking them
- Hostile creatures refuse to do a standard melee attack unless the target is standing right in front of them. Every land mob can be defeated with no damage taken by walking backwards or circling around (even with very little distance compared to player's attack range).
IMO this is not Nether-tier difficulty. It's good that you aren't getting mobbed constantly like in old AoA dims, mobs are pretty scarce now, but also pose pretty much no danger to the player when he encounters them.

**Comment by Tslat** [comment]
Most of this is basically just the melee hitbox issue lol
See how it is after fix
