### ISSUE TITLE
Ruined Portals and Mineshafts Can Spawn in Precasia

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#3928]
AoA3-1.20.1-3.6.31

Ruined Portals and Mineshafts can spawn in Precasia.

![2023-09-21_04 42 51](https://github.com/Tslat/Advent-Of-Ascension/assets/87321515/ec7b8ae6-5351-4fdf-bcb0-4c7dc85c185e)

**Comment by Ursun1** [comment]
also can confirm that mineshafts spawn underground
