### ISSUE TITLE
Exception generating new chunk When use aoa3 in 1.16.5 Minecraft sever with MV2Core

### ISSUE THREAD

**Issue by Greezn** [Tslat/Advent-Of-Ascension#3929]
**Mod Version**
1.16.5-3.6.11

**Describe the bug**
this's a Minecreaft Sever on 1.16.5,i got this crash report when i import MV 2 Core and aoa3 in sametime.And when i open the server.properties from Bukkit and set generate-structures=false then this error will not appear. When i set it True,this error appear again.I guess aoa3 was conflict with MV 2 Core.What shoud i do?then i can play aoa3 when generate-structures=true. thks,and this's the crash report text.

Steps to reproduce the behaviour:
import MV2core and aoa3 in a sever 
keep generate-structures=true in server.properties
start the sever

**Expected behavior**
i wanna play ti in a sever with MV2Core

**Screenshots**
sorry no pic at here
[crash-2023-09-21_19.04.54-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/12686069/crash-2023-09-21_19.04.54-server.txt)

**Comment by Tslat** [comment]
1.16.5 is an old version and I'm not really updating it anymore
Try reporting it to MV

**Comment by Greezn** [comment]
very thks 4 ur reply
