### ISSUE TITLE
Precasia Boats or Rafts

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#3935]
The current wood in Precasia makes it so boats aren't craftable. The only way of getting the necessary items would be from vanilla wood types that spawn in the dim. Given that the dimension has an ocean, a boat of some kind seems necessary.

**Comment by Tslat** [comment]
Not gonna do this until forge/neoforge patches boats to be extensible
At the moment it'd require a bunch of jank I don't want to deal with
