### ISSUE TITLE
Automaton eggs should say what color they are.

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#394]
As the name of the suggestion says, I think this will make it less confusing to see which egg is which.
![2019-02-25_21 53 17](https://user-images.githubusercontent.com/44548547/53371610-957df800-3948-11e9-9231-211912862046.png)

**Comment by Tslat** [comment]
The eggs are auto-named by MC based on their localised entity name.
I'd have to change the mob name to do this, and I kinda like the uncoloured entity names
