### ISSUE TITLE
Deinotherium should not be a passive mob

### ISSUE THREAD

**Issue by skybirdsweet** [Tslat/Advent-Of-Ascension#3941]
In precasia,mobs are humdrum, either hostile mobs or passive mobs,not have any neutral mobs,and in original,deinotherium are neutral mobs,i just want to suggest:
first.precasia not have any neutral mobs,i don't wanna see either hostile mobs or passive mobs in precasia's future
second.some mobs be more suitable for neutral mobsmore than passive mobs,like terradon and deinotherium,I don't want see monotone zoology in precasia,and i don't want to see deinotherium and in future,terradon and dyrehorn are passive

**Comment by Posatasa** [comment]
Guess this issue wants to imitate the relations like between piglins and hoglins.
I also saw someone said he hoped that animals spawned in different biomes with mobs to make less fights
I'm not sure. It depends on you.

By the way, in my opinion, now Precasia have enough animals. New reworked mobs especially dinosaurs are more suitable as hostile.
