### ISSUE TITLE
Make it rain in Precasia

### ISSUE THREAD

**Issue by SooshiGuy** [Tslat/Advent-Of-Ascension#3944]
It makes sense

Obviously the Precasian Desert, Precasian Deadlands and Precasian Volcano biomes make sense not to have this

**Comment by Tslat** [comment]
It rains just fine in precasia

**Comment by SooshiGuy** [comment]
Weird, when I did /weather rain nothing happened

**Comment by SooshiGuy** [comment]
Wait, I just realized this issue was solved before. Nevermind.
