### ISSUE TITLE
Mauls Attack Range buff

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#395]
So currently Mauls have the reach of swords which makes them a bit too dangerous to use effectively. However, it could be potentially unbalanced if they had the attack range of greatblades.

But I will argue that Mauls can potentially work at a midway like 30% or 50% longer range than swords as oppose to the 75% longer range of greatblades. It would definitely make them better as a weapon type overall.

Another thing that could be cool is allowing Mauls to knock back mobs that are immune to knock back. (Although I'm not sure how balanced that would be or if its even possible).

**Comment by Tslat** [comment]
This is a thing as of 3.2
