### ISSUE TITLE
mod takes too much of RAM

### ISSUE THREAD

**Issue by jucogjucogi** [Tslat/Advent-Of-Ascension#3955]
**Mod Version**
What version of the mod are you on?

**Describe the bug**
I use Legacy Launcher and it says "not enough memory" when playing on 2-3GBs, even tho 15+ mod pack without aoa works perfectly fine

**To Reproduce**
Steps to reproduce the behaviour:
just try launching game with less than 4GB ram, it won't open

**Expected behavior**
game will launch fine

**Screenshots**

**Comment by jucogjucogi** [comment]
mod ver 1.12.2, latest CurseForge release

**Comment by EatingSilencer** [comment]
Might be something else with your setup.

Not likely this is ever going to be address from AoA's side as 1.12.2 support was dropped long ago.
