### ISSUE TITLE
Is Precasia caves biome supposed to creep up to the surface

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#3962]
This little section right here with the stranglewood trees on the surface is considered a Precasia caves biome. The max Y level should probably be reduced?

![image](https://github.com/Tslat/Advent-Of-Ascension/assets/38159897/d4bf470a-c23a-4961-a28c-e6641b54720a)

**Comment by Tslat** [comment]
Nah it's fine

Worldgen isn't cut and dry like that, and I'm ok with it creeping up sometimes
