### ISSUE TITLE
Dimension don't give effects 

### ISSUE THREAD

**Issue by Jesuistondieux** [Tslat/Advent-Of-Ascension#398]
**Mod Version**
3.0.2

**Describe the bug**
The dimension of the mod don't give effects  what are supposed to give( for example Players that visit the Deeplands will supposed to be be gifted with a Haste III)  Maybe it's intentional but as a precaution I report it

**To Reproduce**
Just go in a dimension

**Comment by Tslat** [comment]
Intended

Thanks for the report though
