### ISSUE TITLE
Flying mobs bug 1.16.5

### ISSUE THREAD

**Issue by Masterspvpro** [Tslat/Advent-Of-Ascension#3980]
**Mod Version**
3.6.11

**Describe the bug**
Flying mobs(for example "Flye") won't look at you when attacking.

**To Reproduce**
Steps to reproduce the behaviour:
Go to Lelyetia, change to survival and observe how Flyes won't look at you when attacking.

**Expected behavior**
The Flye should turn and look at the player when attacking.

**Screenshots**

**Comment by Masterspvpro** [comment]
If it helps, Forge version is 36.2.39(although I've tried other versions too and it seems like it didn't change anything)

**Comment by Tslat** [comment]
Not sure

But given that this is in 1.16.5, I'm unlikely to deal with it
Luckily doesn't sound like a huge issue

**Comment by Masterspvpro** [comment]
> Not sure
> 
> But given that this is in 1.16.5, I'm unlikely to deal with it Luckily doesn't sound like a huge issue

If you could tell me where specifically you think the problem might be, I could try to fix it and send it to you.
