### ISSUE TITLE
1.16.5 bug, Angelicas are completely broken

### ISSUE THREAD

**Issue by Masterspvpro** [Tslat/Advent-Of-Ascension#3981]
**Mod Version**
3.6.11

**Describe the bug**
Angelicas don't go to the player to levitate them, they also have really bad pathfinding, getting stuck everywhere

**To Reproduce**
Go to haven and summon Angelica, observe how they just ignore the player's existance

**Expected behavior**
Angelicas are supposed to indirectly attack the player by levitating them into the sky 

**Screenshots**

**Comment by Posatasa** [comment]
I think it's not broken. It just became passive.

**Comment by Masterspvpro** [comment]
> I think it's not broken. It just became passive.

From the wiki:
"Angelicas pursue the player, once the player gets within 16 blocks of one. The Angelica does not deal any damage directly, but instead levitates players by flying into them. Angelicas will then take the player up and up until the player does something to make themselves fall."

It could be that they were functionally removed and the wiki didn't get updated since I didn't see them spawning anywhere naturally

**Comment by Tslat** [comment]
Haven became passive, yeah
