### ISSUE TITLE
AoA Portals Don't Work on MC 1.19.4

### ISSUE THREAD

**Issue by ChromamoonMC** [Tslat/Advent-Of-Ascension#3986]
**Mod Version**
What version of the mod are you on? AoA3-1.19.4-3.6.26.jar

**Describe the bug**

When walking through or touching a portal block, the player is not transported to another dimension; nothing happens. No messages are displayed. 

I am using other dimension mods, including Twilight Forest, Aether, Blue Skies, The Undergarden, and a couple others. Not sure if any of these would affect this problem. 

**To Reproduce**
Steps to reproduce the behaviour:

1. In Creative mode, open the inventory and search for a portal block to a dimension from the mod. 
2. Place the block and attempt to walk through it. 
3. In Creative Mode, Construct a proper portal using Ancient Rock and Carved Runes and light it with a realmstone. 
4. Attempt to walk through the portal. Nothing happens. 
5. Try step 4 after switching the gamemode to Survival Mode. 

**Expected behavior**

When walking through or touching a portal block, the player should be transported to its corresponding dimension. 

**Screenshots**

**Comment by EatingSilencer** [comment]
The dimensions aren't implemented on 1.19.4.
