### ISSUE TITLE
Make the carved runes immune to explosives

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#399]
**Describe/name the existing feature this suggestion relates to**
Carved runes

**Describe the change or feature you think would be good to see**
I know the chances of it are fairly low, but I feel like Obsidian has a reason being immune to explosives (besides being very hard in general). The thought of a creeper or anything else that destroys blocks is right next to the teleporter as I come out of it is a spooky one.

I can understand the Ancient stone not being immune since you can get lots of it quickly, but Carved runes have a lot more worth to them, and it would really suck having this happen.
![image](https://user-images.githubusercontent.com/38159897/53408101-90ce3980-3972-11e9-89da-980beef05bfe.png)
I know it's actually not a big deal at all and will likely very rarely happen, but I still think it would be a nice little QoL change. You could just say the carved runes have a magic seal on them or something lol

**Comment by Tslat** [comment]
Turn mobgriefing off if you don't want blocks broken?

**Comment by Immortallis1** [comment]
Just be careful with your portal and don't let creepers near it
