### ISSUE TITLE
Stranglewood Wood and Leaves should be immune to fire?

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#3992]
Noticed that in caves they start to burn pretty easily due to lava, so I was thinking maybe they potentially like the Nether wood and leaves they could be immune. This isn't really necessary but who knows. Anyway lore-wise, since they grow in warmer biomes they are just immune to intense heat.

**Comment by Tslat** [comment]
Nah they're wood
