### ISSUE TITLE
Crash with Nethengeic Wither and Elite Nethengeic Wither. Seems to occur when they use Flamethrower and Fire Bomb

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#3999]
**Mod Version**
AoA3-1.20.1-3.7.1-all.jar

**Describe the bug**
Crash the game when Flamethrower and Firebreath activate. Occurs when Nethengeic Wither or Elite uses those attacks. This crash does not occur in the public previous version 3.7.
[message.txt](https://github.com/Tslat/Advent-Of-Ascension/files/13155155/message.txt)

**Comment by Tslat** [comment]
-.-
