### ISSUE TITLE
Nospike remodel idea

### ISSUE THREAD

**Issue by thousvillages** [Tslat/Advent-Of-Ascension#4002]
there are the remodel concept and model file

### **-----model file------:**

[nospike.zip](https://github.com/Tslat/Advent-Of-Ascension/files/13211708/nospike.zip)

![QQ图片20231031112844](https://github.com/Tslat/Advent-Of-Ascension/assets/104772874/a5d1b083-8024-4f75-aaad-8fe8574a704f)
![nospike_shot](https://github.com/Tslat/Advent-Of-Ascension/assets/104772874/f98261bd-ad10-4a1d-9620-249bf95604de)

**Comment by Posatasa** [comment]
awesome
