### ISSUE TITLE
Issue ( 1.12.2 )

### ISSUE THREAD

**Issue by Kasia1403** [Tslat/Advent-Of-Ascension#4014]
Minecraft world can't load. It's still repeating messages ( in log console ) about updating player halos and doesn't want to load a world.

**Comment by Kasia1403** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/13350140/latest.log)

**Comment by Tslat** [comment]
Your modpack has issues

AoA doesn't have anything to do with it

**Comment by Kasia1403** [comment]
But what does it mean "player halos" ? How to disable them ? I can't find this in config.

**Comment by Tslat** [comment]
It has nothing to do with that lol, that's just an info message

**Comment by Kasia1403** [comment]
@Tslat Could You look again into my latest.log and help me find the bugged mod ?
