### ISSUE TITLE
Skill showing as disabled when using Lan-World

### ISSUE THREAD

**Issue by TheNonHumanBeing** [Tslat/Advent-Of-Ascension#4016]
**Mod Version**
What version of the mod are you on?
1.16.5-3.6.11

**Describe the bug**
When I open my world to Lan, the skills are being disabled

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into World
2. Click on open to LAN
3. Open AoA Menu

**Expected behavior**
Skills not being disabled, but working.

**Comment by TheNonHumanBeing** [comment]
Addition:
This only affects me, not the people joining.

**Comment by EatingSilencer** [comment]
Known bug. Will never be fixed I think, its unfixable.
