### ISSUE TITLE
No carved runes in teleporter frame structure at all

### ISSUE THREAD

**Issue by Englander2** [Tslat/Advent-Of-Ascension#4017]
Hello,
My AOA3 version is 1.16.5-3.6.11

I played many hours in one world. I found ~15-25 ruined teleporter frames, and there weren't carved runes at all! I can found only ancient rock in this structure.

I'm a beginner in this mod, and in various videos youtubers find 5 or 6 runes per structure at once, while I don't find any

I hope that you will help me.

**Comment by Tslat** [comment]
You can also find them in loot chests, or sometimes dropped from mobs
