### ISSUE TITLE
Major bug

### ISSUE THREAD

**Issue by chessMCman** [Tslat/Advent-Of-Ascension#4018]
**Mod Version**
What version of the mod are you on?
version 3.7
**Describe the bug**
After being hit by monsters generated by mods in the lower world, the game will crash

**Expected behavior**
Hope to fix this bug as soon as possible

**Screenshots**
![Image_1702201114219](https://github.com/Tslat/Advent-Of-Ascension/assets/87481057/495a9f9e-806c-46d2-a150-0070c078be81)

**Comment by EatingSilencer** [comment]
Post crash report.

**Comment by Posatasa** [comment]
This guy google translated the Nether as the lower world
