### ISSUE TITLE
AoA Crashes while creating a new world, AOA 1.12.2

### ISSUE THREAD

**Issue by KevinZaWarrior** [Tslat/Advent-Of-Ascension#402]
AoA 3.0.1, Minecraft 1.12.2

When i create a new world with the AoA mod enabled i get an error with the words "Exception ticking world".

I tried disabling other mods, restarting mc and re-installing AoA.

Creating a world gives me this error.

**Comment by Sagisolar** [comment]
I don't know what this bug is but I would like to inform you that 3.0.2 has been released.
See here for the details.
https://adventofascension.gamepedia.com/3.0.2

**Comment by Angrydog001** [comment]
further information needed
