### ISSUE TITLE
Flamewalker attack CTD

### ISSUE THREAD

**Issue by festro** [Tslat/Advent-Of-Ascension#4021]
**Mod Version**
AoA3-1.20.1-3.6.31

**Describe the bug**
CTD or server disconnect from Flamewalker in the nether
ReportedException: Accessing LegacyRandomSource (Mixin) from multiple threads
Disabling AoA stops crash.

**To Reproduce**
Got to the nether
aggro Flamewalker
get set on fire
crash

**Expected behavior**
No Crash?

**Screenshots**
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/13694774/latest.log)

**Comment by Tslat** [comment]
Try it again on latest version
I can't/don't accept error reports on outdated versions for obvious reasons

**Comment by festro** [comment]
Where is the latest one? the one I'm using is as the latest on curseforge.

**Comment by Tslat** [comment]
3.7, it's on CurseForge

**Comment by festro** [comment]
3.7 says it's for neoforge is it compatible with forge?

**Comment by festro** [comment]
After trying the 3.7 with forge which did run, it still has the same issue.

**Comment by Tslat** [comment]
Provide new crash report
