### ISSUE TITLE
Fighting Bosses in Their Native Habitats

### ISSUE THREAD

**Issue by cerulean-2** [Tslat/Advent-Of-Ascension#4023]
Part of what makes each boss fight interesting is the terrain. Many bosses have unique arenas, or the dimensions provide distinct obstacles. For example, the Haven made the Rockrider fight dangerous thanks to the overhangs and open void. The chaos of Iromine only accentuated the MechBot fight.

Fighting the bosses in Nowhere is jarring. You would expect that summoning a boss would do only that, but teleportation to an unrelated dimension is odd. Graw should be the "Guardian of the Forest" but won't even be fought there anymore. Bane is taken out of the environment that helps along his menace. The different arenas and terrains (mountainous, flat, watery, void, etc.) are no longer part of the diversity of the different boss fights. In trying to make each boss fight different, this unified set of boss arenas in Nowhere is not helping.

My solution is something of a compromise. When the player first fights the boss, he must do so in the natural environment. Defeating the boss unlocks the option to fight the boss in Nowhere. The player may now use the summoning item to bring the boss back for later fights in Nowhere. Alternatively, he can continue to summon the boss in the dimension it is native to.

Take Clunkhead, for example. The player has a Mega Rune Stone and is forced to go to a Runic House to summon Clunkhead. The player defeats Clunkhead. Now, for further Clunkhead fights, the player has two options. (In my scenario, the only way to get to Nowhere is to have opened its portal, so it is impossible to refight Clunkhead in Nowhere without having unlocked the dimension with the Realmstone's various ingredients.)

Option 1: The player decides to go back to the Runic House to refight Clunkhead.

Option 2: The player decides to head to Nowhere, finds that an option to fight Clunkhead there has been unlocked, and fights Clunkhead in the special, lovingly made Nowhere boss arenas.

In this way, you can only grind a boss in Nowhere after proving you can fight that boss in its native terrain first. Or you can refight the boss in its dimension if you choose to.

**Comment by Posatasa** [comment]
https://adventofascension.fandom.com/wiki/Player_questions?so=search#Why_are_bosses_in_Nowhere?

**Comment by cerulean-2** [comment]
In response to the idea that Nowhere prevents cheating.

This is a valid point, but the mod should not need to meddle with the player's playstyle. If the player wants to cheat, then so be it. The rewards won't be feel as earned. It is the player's own fault. If he wants to play legitimately, then the rewards will feel earned. Everything is on singleplayer anyways. The player can go into Creative if he really wants to cheat. Cheating has no impact on other players' experiences.

This is how other mods (the Aether, the Twilight Forest) and even the base game do things. Allowing my suggestion allows better harmony with the rest of the Minecraft community's gameplay style. It's supposed to be a sandbox game.

**Comment by Tslat** [comment]
It's not meddling with the player's playstyle

The mod is designed around the boss fights being in Nowhere.
This allows me to ignore all of the edge cases and counter-cheesing I need to include in boss design since none of that matters in Nowhere.

It also fits into the lore of the mod without really subtracting much, whilst also giving AoA unique approach to bosses that other mods just do't have

**Comment by cerulean-2** [comment]
Thank you for your response. I see the merit of some of your points. This is an approach not seen in other mods, and there are few worries about counteracting many cheating scenarios.

However, a counter-example to the meddling claim is that the player can no longer use blocks in the fights, something expected of boss fights in this sandbox game. This isn't a playstyle that necessarily means cheating.

The mod itself has actually always been designed around the fights being in their native environments. Many of the boss structures are intentionally ready-made for boss fights to happen in them (see the Guardians, Gyro, C.R.E.E.P., Vinocorne, etc.).

And why concern yourself with stopping cheaters? The cheaters will find ways to cheat regardless, and the "upstanding" players will play for the fun of the challenge.

I don't mean to go off on a tangent, but the lore of Nowhere seems lacking, so it is difficult to fit anything to it. It's really just a place where a lot of quirky things happen. I like Nowhere (even more so once the Immortals and Cavern Four show up), but there's no pull that says that the other bosses just _fit_ there and "nowhere" else. Lorewise, the bosses really fit in the dimensions that they are native to. Graw is the top-dog of his forest, the Guardians guard the Haven, and Gyro flies through Celeve above all his clown compatriots.

**Comment by Cruuk** [comment]
Except that having them be in their home dim/having blocks be a factor did not benefit the mod at all. Even when you weren't cheesing, there were plenty of factors that could screw with you - the boss jumping/getting out of the arena, mobs interrupting the fight, the boss getting stuck in a hole, their drops getting blown up.

Some bosses had a sufficient arena structure, but you've conveniently left out the fact that most of them didn't. I am not interested in having to build a wall around the P5 structure and put torches everywhere again, especially when a Duston flies over those walls and screws me over, etc. Don't get me started on having to deal with Voxxulon/Candor in their dims.
This same idea applies to a lot of the bosses. Not even most of the arena structures were good on their own - Gyro often flew out of his arena, Creep/Baroness could blast you out of their's, etc.

MC is simply not a good game for boss fight variety at base. Other mods have attempted solutions like unbreakable structures or other things, which present design issues of their own and further developmental sinks that will be time not spent making the boss fights. Even a complex solution like what Blue skies does doesn't compare to Nowhere's conveniences like its keepInv system - which will allow boss fights to be as hard as we want, along with boss drops being TPed to your inventory.

There is also no interest in turning every boss into a homogenized thing that destroys blocks/goes through them in some janky way. Using blocks is encouraged? That's usually associated with block cheese, and is something vanilla attempts to cheat with - dragon has a whole giant arena and flies through blocks, and Wither's insane level of block griefing to the point where players like to use it to troll others isn't even effective enough to truly stop block cheesing. A lot of MC things - vanilla and mods, do not like block cheese.

Cheese as a whole isn't dead, this will give rise to equipment cheese - specific armor/weapon setups, which is infinitely more interesting than not having to think and surround the boss with blocks.

The community wants good boss fights, and most don't share a personalized headcanon atmosphere outlook. It's not really a good reason to justify being burdened with several gameplay issues for the sake of appealing to a vague idea of "atmosphere".

Basing it off of outdated lore that will probably get changed is also incorrect, but there's nothing stopping the lore from specifying the boss originated in their home dim - if I'm reading BBB's new lore right at least. This system only pertains to the gameplay side of the actual fight.

There will also still be large environmental hazards like the overworld giants, Neth beast, etc.
And there's nothing stopping you from doing addon stuff or whatever to move the bosses back to the dims. This is still a sandbox, there's just a lot of reasons why we're doing this solution

**Comment by Tslat** [comment]
To add to Cruuk's above points

> The mod itself has actually always been designed around the fights being in their native environments. Many of the boss structures are intentionally ready-made for boss fights to happen in them (see the Guardians, Gyro, C.R.E.E.P., Vinocorne, etc.).

The mod itself has been based on many really shitty design principles in the past.
The mod itself has always been based on extremely unbalanced mobs with cheap annoying effects, does that mean we should keep that too?


The Nowhere system allows me to better design bosses for a system I have control over, as well as doing things like loot distribution and elite fights.
It allows AoA to create arenas of all kinds and be creatively expressive.
It allows AoA to control for factors like keep-inventory.

There's functional, real reasons to use Nowhere, both from a player perspective and a dev perspective, and as far as I can tell the only real reason for _not_ using it is 'it's nice to fight the bosses in their dim'
Which feels.. very flimsy, imo
