### ISSUE TITLE
Still Mob Animations(May be a Geckolib issue)

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#4024]
Version 3.7.1-all.jar

Noticed a few mobs such as Smash and Flamewalkers animations were a bit odd. For example, Smash's idle and run animations sometimes don't play and flamewalkers arms and legs don't spin. I noticed this with some other mods related to Geckolib as well, so it may be due to that.

**Comment by Tslat** [comment]
Yeah I think this is a Geckolib Issue
