### ISSUE TITLE
The Mod failed to load (1.19.2)

### ISSUE THREAD

**Issue by ThatsSpryzen** [Tslat/Advent-Of-Ascension#4028]
**Mod Version**
What version of the mod are you on?
- AoA3-1.19-3.6.8

**Describe the bug**
The game start but the mod wont load, it say "AoA3 failed to load correctly" (i have a custom modpack)

crash report:
[crash-2023-12-28_18.25.12-fml.txt](https://github.com/Tslat/Advent-Of-Ascension/files/13788331/crash-2023-12-28_18.25.12-fml.txt)

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**
![Screenshot 2023-12-28 183025](https://github.com/Tslat/Advent-Of-Ascension/assets/92258734/be67ba46-6b5a-491e-94ef-cd28365376ee)

**Comment by Tslat** [comment]
Possibly forge broke something in a newer version

Join the discord if you want help
