### ISSUE TITLE
Portals Won't Transport

### ISSUE THREAD

**Issue by lxdia** [Tslat/Advent-Of-Ascension#4034]
**Mod Version**
1.19.2

**Describe the bug**
I made a portal to Lelyetia, but standing in the portal did not transport me to the other dimension. I tried it again with Barathos and Deeplands, but neither of those worked either. The portal was created perfectly (no error messages of something missing), so it was not an error of an incorrect portal. Nether portals do work, so it isn't an issue with vanilla portals. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a portal (Lelyetia, Barathos, Deeplands, or others)
2. Try to enter the portal

**Expected behavior**
I expected to be transported to another dimension.

**Screenshots**
![Barathos Portal](https://github.com/Tslat/Advent-Of-Ascension/assets/155204603/49ca2a5f-2b3e-43e4-b0aa-31bb1b30033c)

**Comment by TripleThreeT** [comment]
This is due to 1.19.2 not having the dimensions implemented yet. It is not ready for play. 1.16.5 has all dimensions ready.
