### ISSUE TITLE
Mobs are spawning but not attacking

### ISSUE THREAD

**Issue by ThatsSpryzen** [Tslat/Advent-Of-Ascension#4036]
**Mod Version**
What version of the mod are you on?
1.20.1 - 3.7.1 (custom modpack on aternos)

**Describe the bug**
The mobs that spawn in the overworld doesn't move/attack (like ancient golem, charger, goblin, sasquatch), they spawn but they stay still, if i hit them they will move but they don't attack me or move

**Screenshots**
![2023-12-30_15 28 30](https://github.com/Tslat/Advent-Of-Ascension/assets/92258734/5b25f631-095f-4ab8-8fdc-1a56ecfa3e3b)

(srry bad english)

**Comment by TripleThreeT** [comment]
Your forge version is above 47.1.3. Please keep it add that version or use Neoforge.

**Comment by ThatsSpryzen** [comment]
> Your forge version is above 47.1.3. Please keep it add that version or use Neoforge.

will be a bug fix in the future for 47.2.0?

**Comment by TripleThreeT** [comment]
No most mods are not going above 47.1.3 due to changes with forge.

**Comment by ThatsSpryzen** [comment]
> No most mods are not going above 47.1.3 due to changes with forge.

i don't know what to do because aternos uses the latest forge version and i can't install 47.1.3, aternos only have 47.2.0 and 47.2.19

**Comment by Tslat** [comment]
Install the latest smartbrainlib for 1.20.1 forge then
