### ISSUE TITLE
in the inventory, there are two different chinese names for the translation of advent of ascension

### ISSUE THREAD

**Issue by MCyuzhouRS** [Tslat/Advent-Of-Ascension#4037]
in the translation of advent of ascention, there are two different translations,飞升之临 and 虚无世界
![屏幕截图(243)](https://github.com/Tslat/Advent-Of-Ascension/assets/124948981/210d9ef1-a2dd-4f86-92ac-d1357d2b35eb)
![屏幕截图(244)](https://github.com/Tslat/Advent-Of-Ascension/assets/124948981/282734a3-c459-4b69-8103-16b89c14d3b1)

**Comment by Posatasa** [comment]
Already fixed on crowdin. Not synchronized in game
