### ISSUE TITLE
Convert Anima into a Gardening skill

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#404]
So, Tablets are gone (Crab rave).

So right now Anima does nothing but give you a armor set. This also means the Luxon Scythe is also useless.

But one thing about Anima, is it comes from natural stuff like breaking leaves and breaking plants you grow. I purpose the rewards for training Anima are gardening base. Like having more a Higher Anima level makes plants grow faster so you can eat them. Or more seeds and plant drops per destroyed plant. Maybe even new seeds that have level requirements idk.

Anima armor can be reworked to make all grass around you grow to Tall grass and plants.

**Comment by xReficul** [comment]
Increased drop rates per Anima sounds like a really good idea.

**Comment by Sagisolar** [comment]
@xReficul Would recommend giving this Suggestion a thumbs ups if you support it.
