### ISSUE TITLE
Frogs to Precasian River Biomes and Potentially Jungles

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#4040]
Don't think this is really necessary, but they would fit the biome due to all the Lily pads. It could also add atmosphere to the biome as Chompers can also eat them. I also wonder if frogs could eat Meganeuropsis, but that may be too much.

**Comment by Tslat** [comment]
Frogs eating insects?!??
In Minecraft!?
Blasphemy!

**Comment by TripleThreeT** [comment]
LOL. Naw only weird cube creatures!
