### ISSUE TITLE
Infinite Loading Screen

### ISSUE THREAD

**Issue by PresquePlayed** [Tslat/Advent-Of-Ascension#4057]
**Mod Version**
AoA3.73

**Describe the bug**
When starting the game, after Neoforge loaded all mods, the regular Mojang loading screen appears but never finishes loading. It is still possible to click the main menu buttons, but very hard as they are hidden by the loading screen

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Game on Neoforge 20.4.124 with no other mods installed

**Expected behavior**
The main menu appears after loading

**Screenshots**
<img width="577" alt="Screenshot 2024-01-23 at 11 53 47" src="https://github.com/Tslat/Advent-Of-Ascension/assets/30369013/e0e4b5a1-725d-4787-a260-2525e6917248">

**Comment by Tslat** [comment]
Downgrade to .99 Neoforge for now

**Comment by PresquePlayed** [comment]
thank you so much for the help!
