### ISSUE TITLE
King Bambambam Explosive Armor set is not all given when defeated.

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#4059]
**Mod Version**
3.7.3

Beating King Bambambam currently only gives one of the armor set and not the entire thing like its meant to.
<img width="444" alt="Screenshot 2024-01-24 at 8 23 08 PM" src="https://github.com/Tslat/Advent-Of-Ascension/assets/87321515/7b4f3a09-52c1-4486-8d28-456644fe3182">

**Comment by Tslat** [comment]
Goddamnit I must have misinterpreted vanilla's thing

I deleted my own one too ;(
