### ISSUE TITLE
Blocks for each ingot/gem

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#406]
Ingots/gems should have blocks like in vanilla. I know there's stuff like skeletainum, but only a few ingots have that, and they're barely related to the ingots themselves (they don't even have the same colors). I think they should be added because:

1: They compacting ingots reduces the storage space they require by a lot

2: Some of them would be nice for building (emberstone and that red barathos ore comes to mind)

3: Would make the mod more consistent with vanilla and other mods

4: Would be useful for building beacons

**Comment by Cruuk** [comment]
Yes please. You could even change the recipe of the functional blocks (crystallanium, shadonantium, etc.), to make room for actual storage blocks to make it a bit more consistent.

Plus it would allow you to gloat about obtaining Sapphire blocks.

**Comment by DiamondWalker** [comment]
I was thinking stuff like shadonantium could just have a recipe change (maybe just four ingots in a brick-like pattern). They don't even feel like ore blocks, not even the name and texture.

**Comment by Immortallis1** [comment]
> 
> 
> Yes please. You could even change the recipe of the functional blocks (crystallanium, shadonantium, etc.), to make room for actual storage blocks to make it a bit more consistent.
> 
> Plus it would allow you to gloat about obtaining Sapphire blocks.

that'd imply 9 sapphire was obtainable
