### ISSUE TITLE
Greatblades not dealing full damage all the time?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#407]
**Mod Version**
3.0.2

**Describe the bug**
An issue I've noticed for a while (since the snapshots I think?) is that greatblades tend to deal 1 less damage than they're supposed to, when it only deals the intended damage sometimes.
For example, Grandsword is supposed to do 17 damage, but even if I wait a while before hitting, it deals 16 damage. Sometimes it does deal 17 damage, but that's about it.
Swords and mauls have no issues dealing full damage all the time even if you swing the second it reaches full cooldown. Only greatblades and scythes seem to be affected by this, since they do have more range?

**To Reproduce**
Steps to reproduce the behaviour:
Hit an enemy with a greatblade/scythe, wait a while before hitting again just in case you think it's attack speed causing it.

**Expected behavior**
Greatblades/scythes dealing consistent base damage when they reach full cooldown.

**Screenshots**
https://youtu.be/f1s4Od-LTKE
(ignore the battle rage)

**Comment by Tslat** [comment]
Fixed
