### ISSUE TITLE
Extra ways to gain Luxon and Selyan tribute

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#408]
**Describe/name the existing feature this suggestion relates to**
Luxon and Selyan tribute.

**Describe the change or feature you think would be good to see**
Mainly just some extra ways you could be able to gain Luxon and Selyan tribute that I came up with a little bit ago.

**Selyan**
I think breeding animals should also add tribute. You know, creating life, nature, all that fun stuff.
It is also the other method of farming, with the other one being crops, which already gives Selyan tribute when harvested.
Killing animals wouldn't make the Selyan tribute go down, that already goes down via cutting down trees and killing stuff already makes Luxon tribute goes down, so...
(assuming it wasn't changed in 3.0)

**Luxon**
Breaking monster spawners should add a considerable amount of Luxon tribute (~10-15% of the bar?), since there are a limited amount of them, along with being pretty rare. I think it would make sense, you are breaking a thing capable of spawning an infinite amount of evil creatures and stuff.

This would also make the Erebon bar go down. Only by a little bit though, it wouldn't be an equivalent exchange between the Luxon and Erebon bars.

It wouldn't be a game changing way to please Luxon, but I think it would be a cool way to get extra Luxon tribute besides just training Infusion and Augury.

This includes any spawner that spawns hostile mobs, hypothetically no this would not work on spawners that spawn passive mobs.

**Comment by DiamondWalker** [comment]
I actually don't really agree tbh. Selyan's always seemed to be more interested in plants than in animals (all her dimensions have a lot of plants, yet barely any animals. The naturalist also only sells seeds). About the Luxon thing, I think that'd probably make his tribute bar go down. If the "evil creature" logic could also be applied to killing stuff like zombies, goblins, etc. However, that makes his tribute go down. His intention doesn't seem to be vanquishing all evil creatures, just being a pacifist.
