### ISSUE TITLE
Energy Stones give wrong exp amount

### ISSUE THREAD

**Issue by Rain-Flying** [Tslat/Advent-Of-Ascension#4082]
**Mod Version**
3.7.4

**Describe the bug**
(Don't even know how to describe it)

**Solution**
`PlayerUtil.givePartialLevelToPlayer(pl, AoASkills.IMBUING.get(), cumulativeXp, false);`
Above is the [source code](https://github.com/Tslat/Advent-Of-Ascension/blob/06441cd8244acf51b64027b982806acb4e829b74/source/content/item/misc/EnergyStone.java#L56) of Energy Stone. (Line 56)
To fix, change it like this:
`PlayerUtil.giveXpToPlayer(pl, AoASkills.IMBUING.get(), cumulativeXp, false);`

**Comment by Rain-Flying** [comment]
When I use some Energy Stones one by one, they give some exp.
When I use the same amount of Energy Stone in a single right click, they give different amount of exp!
So wierd

**Comment by Tslat** [comment]
Yeah already fixed :)
