### ISSUE TITLE
Realmstone changes

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#409]
There's a few realmstones that feel out of place, both theme-wise and progression-wise.

Vox Ponds: It's always seemed strange to me that Vox Ponds was reached through Gardencia. They have nothing in common, aside from the fact that Vox Ponds is green and _**POSSIBLY**_ was a forest/jungle before (but the old lore was scrapped). Instead, I think it should drop from Slimers (the rare mob of the Abyss). Why Slimers? Both the Abyss and Vox Ponds are dark and eerie, and the Abyss is the only dimension in its progression branch. Also, the Slimer is green, and kinda feels like something out of the Vox Ponds.

Iromine: Another dimension that makes little to no sense, either based on theme or balance. The only relation it has in relation to the Deeplands is the fact it has "mine" in its name and it being metallic (yet Vox Ponds is also fairly metallic and got tossed into a flower dimension?). I think its realmstone should be dropped from Automatons. It might be a bit of a far fetch, but the professor has been to the Haven to experiment with Automatons and came back. Maybe he left Iromine realmstones with some of them?

Barathos: I can see why this realmstone ended up in Runandor (because of the Overgrowth/Undergrowth thing), but by now they have nothing in common. Runandor is a lively blue and magical dimension. Barathos is an alien deserted red dimension. There's nothing in common. It might seem odd, but I think Barathos' realmstone should come from Lunalus. They're both alien-themed (look at the alien forest in Barathos and the Eliosapien). Also, somethings in Lunalus look straight out of Barathos (the Baumbas and Reflucts come to mind). It could also have some interesting lore possibilities. Maybe Barathos could be an alien planet, and Lunalus takes place in its ring system? To avoid making the Runandor/Greckon branches unequal, maybe move Shyrelands to be post-Runandor.

EDIT: Iromine could also be from Vox Ponds, since they're both metallic and robotic. Though that might cause another imbalance in the Abyss/Haven branches.

**Comment by Cruuk** [comment]
The Vox ponds and Barathos one is interesting. Though one thing that worries is that you'll have to rebalance the content in those dimensions if they're gonna be moved. ~~Though to be fair Barathos already seems to be balanced like a mod-game dimension despite being in the same position as Dustopia.~~

Though, Runandor and Barathos still have connections to each other. Those being Baron/Purity armor's set bonus, Baron/Purity sword/greatblade, and the Purity/Destruction guns.

I'm not a fan of moving Shyrelands at all. Shyrelands being connected to Dustopia is like the coolest symbolism ever (lightest dimension and darkest dimension) and I want to keep that

**Comment by DiamondWalker** [comment]
I don't think they'll need rebalancing. Vox Ponds requires the Hazmat armor, meaning it's fairly consistent in difficulty throughout the game, and Barathos is already balanced like a mid-game dimension, like you said. I never noticed the Barathos items being variants of the Runandor stuff, so that'll be a problem. I get the Shyrelands thing, but that's assuming Barathos is moved, since the there be too much difference between the length of the two branches (I actually think Barathos should have another dimension after it to keep them balanced, but that's a separate issue). If Barathos moves, Shyrelands would work well as the substitute "late-game extreme light dimension".

**Comment by Immortallis1** [comment]
Realmstones being dropped by rare mobs is just frustrating in my opinion.

**Comment by DiamondWalker** [comment]
> 
> 
> Realmstones being dropped by rare mobs is just frustrating in my opinion.

I picked Slimer since it was the only Abyss mob that fit. Also, I don't see much difference between a common mob dropping an item rarely, and a rare mob dropping an item commonly. At the end of the day, it's still the same (and rare mob spawns can be increased with a farm).

**Comment by Tslat** [comment]
This has become invalid since the 3.2 changes
