### ISSUE TITLE
Butcher Villager Trades

### ISSUE THREAD

**Issue by videojamesmostlikely** [Tslat/Advent-Of-Ascension#4090]
The Butcher villager is a vanilla villager that mainly trades in meat, exchanging raw meat for emeralds and emeralds for cooked meat and meat dishes, like rabbit stew. However, **there's currently no way to trade meats from AoA with it** - things like Charger Flanks and Giant Lizard meat cannot be traded, which can be an issue when the player gets lots of them from exploring! I'm not sure whether trading them for Emeralds or Copper Coins would be the better option, so I'll leave that up to you.

(This is not related to any prior bugs or suggestions to my knowledge.)

**Comment by Tslat** [comment]
Yeah alright
