### ISSUE TITLE
Add Sounds for Void Walker and Ghost

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#4091]
At the current moment, Void Walkers and Ghosts have no sounds. I'm not sure if Ghosts are meant to make a sound in this case, but Void Walkers probably should.

**Comment by Cruuk** [comment]
If I read it right, Ghost specifically has a line of code that makes it not make sound

**Comment by TripleThreeT** [comment]
Yeah, makes sense given what they are.
