### ISSUE TITLE
Mobs are not displayed and do not move

### ISSUE THREAD

**Issue by CHAENIK13** [Tslat/Advent-Of-Ascension#4107]
**Mod Version**
What version of the mod are you on?
1.20.1-3.7.1
**Describe the bug**
Mobs are not displayed and do not move
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
what needs to be done to make mobs work properly
**Screenshots**

**Comment by Tslat** [comment]
Forge broke things in 1.20.1

You need to either swap to NeoForge, or use Forge 47.1.3, or Install the latest SmartBrainLib for Forge 1.20.1
