### ISSUE TITLE
Erebon Scythe doesn't mention that it steals hp from the player if they don't have enough Energy

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#411]
**Mod Version**
3.0.2

The blue text on Erebon Scythe is different from the other Scythes
![image](https://user-images.githubusercontent.com/38159897/53595192-7a320900-3b51-11e9-8b27-9c988efe87a8.png)
The other 3 Scythes say the same thing on their blue text
![image](https://user-images.githubusercontent.com/38159897/53595253-a057a900-3b51-11e9-9d90-b263f8db65a3.png)

**Comment by Tslat** [comment]
Fixed
