### ISSUE TITLE
More FROGS in Precasia

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#4110]
Yeah, I think they should either spawn more frequently or spawn in groups in the Precasian River Biome. Bit too rare for their main purpose as scenery for the biome.

**Comment by Tslat** [comment]
They're problematic cus they're hardcoded to spawn on certain vanilla blocks only...

**Comment by TripleThreeT** [comment]
Hmm. Tadpoles could also work too if they can spawn in water in Rivers.

**Comment by Tslat** [comment]
Gotchu fam
