### ISSUE TITLE
Issues about Farming abilities

### ISSUE THREAD

**Issue by Moshanxi** [Tslat/Advent-Of-Ascension#4113]
The ability Harvest Replant and Hoe Area Harvest
1. Hoes may "harvest" block to leave a ghost block. Guess it a vanilla bug of data synchronization between client and server.
2. Replant in the given area could cause wrong replant position.

![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/57410b12-2b03-4d66-b7ac-ac931671be65)
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/ab03c2b8-b67f-40da-a795-b8081518e890)

**Comment by Moshanxi** [comment]
In addition, hoes of jade, ember and limonite still render wrong in hand

**Comment by Tslat** [comment]
I can't seem to replicate your error =/

**Comment by Moshanxi** [comment]
seems solved
