### ISSUE TITLE
Add a way to selectively remove enchants OR make it so Imbuing chamber can change the level of an enchant

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#4115]
You can't imbue an item if it already has that enchant currently. This suggestion is to just avoid situations where you want to put sharpness 5 on something, but it has sharpness 1. It ALSO has mending/unbreaking on it so you don't want to just use Grindstone on it

**Comment by Tslat** [comment]
Wasn't that bug fixed in the last version?

**Comment by Cruuk** [comment]
> Wasn't that bug fixed in the last version?

I presume you're referring to this https://github.com/Tslat/Advent-Of-Ascension/issues/4089 . If that's the case, this is different as this specifically refers to imbuing an item with an enchant it already has. I assume that's intended?

**Comment by Posatasa** [comment]
also, now imbuing chamber can't imbue enchantments beyond vanilla limit such as sharpness 6, like infusion table used to be. hope they can be added
