### ISSUE TITLE
Remorphed Mod Crash

### ISSUE THREAD

**Issue by krjencik** [Tslat/Advent-Of-Ascension#4128]
**Mod Version**
What version of the mod are you on?
3.7.5

(Neo Forge, Minecraft 1.20.4)

**Describe the bug**

my game  crashed after searching in the mods morph tab. They responded with this:

"I think you should report to the [Authors of Advent of Ascension](https://github.com/Tslat/Advent-Of-Ascension/issues), that rendering they're Toy Merchant crashes the whole game.
(I tested it- Of course I could blacklist it, but it would still crash the game when the Toy Merchant is summoned)."

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
No crash obviously

**Screenshots**

**Comment by Tslat** [comment]
No crash report?

**Comment by krjencik** [comment]
https://gist.github.com/krjencik/2c03ffc788f41ee9f3abe8d17f67e447

**Comment by Tslat** [comment]
Fixed in next version
