### ISSUE TITLE
Health bar compatibility for The Undergarden

### ISSUE THREAD

**Issue by Moshanxi** [Tslat/Advent-Of-Ascension#4129]
The effect Virulence (purple). It's alright for extra health of Blue Skies lol.

![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/5d7a5617-e7a5-4066-9431-23b4d9810122)
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/1cc6a910-3a14-48e1-93c9-1e4eb8b2c419)

**Comment by Tslat** [comment]
Yeah this is an undergarden bug, not AoA
