### ISSUE TITLE
backtracking

### ISSUE THREAD

**Issue by st920130** [Tslat/Advent-Of-Ascension#413]
**Mod Version**
What version of the mod are you on?
3.0.2
**Describe the bug**
my level just reset
**To Reproduce**
Steps to reproduce the behaviour:
so I don't know how to make this bug happen but sometime i enter my world i couldn't use command.but when i close map and enter again it fixed.but my charactor just reset to a place(ALSO MY ITEM IN BACKPACK) and my all skill return to 1.i am realy upset about it 
** Expected behavior**

**Screenshots**
![2019-03-02_02 04 27](https://user-images.githubusercontent.com/48134555/53657012-efa3f380-3c8f-11e9-8d57-2bb36fadb6fe.png)

**Comment by st920130** [comment]
![2019-03-02_01 47 30](https://user-images.githubusercontent.com/48134555/53657127-3b569d00-3c90-11e9-84c2-e0e2d8bad0bf.png)
so maybe I CAN give you another picture whitch i screen before this bug heppend(sorry about pool english)

**Comment by Tslat** [comment]
Sounds like something is messing with player construction.

What other mods are you using, and what version of forge are you using

**Comment by st920130** [comment]
here are all mods i use this time:
[1.12]bspkrsCore-universal-7.6.0.1
[1.12]TreeCapitator-client-1.43.0
AoA3-3.0.2
CodeChickenLib-1.12.2-3.2.2.354-universal
InventoryTweaks-1.63
jei_1.12.2-4.14.4.260-tw
journeymap-1.12.2-5.5.3-tw
NotEnoughItems-1.12.2-2.4.2.240-universal
OptiFine_1.12.2_HD_U_E3
torohealth-1.12.2-11
VeinMiner-1.12-0.38.2.647+b31535a

My forge is 1.12.2-forge1.12.2-14.23.5.2768

**Comment by Tslat** [comment]
You're saying the items in your backpack are resetting too?

**Comment by st920130** [comment]
yeah,but item in the chest didn't.

**Comment by st920130** [comment]
I experence 2 times.first time and second time reset to same period.but the level reset just happen at second time

**Comment by Tslat** [comment]
Remove all other mods and see if it still does it (backup your world first)

**Comment by st920130** [comment]
OK I will try

**Comment by st920130** [comment]
so i remove all other mod and try it again.it still reset my charactor back fill bad :(

**Comment by Tslat** [comment]
When there's no other mods, what do you do to make it reset? log out/in? Go between worlds?

**Comment by st920130** [comment]
log out/in i haven't go to any worlds

**Comment by st920130** [comment]
all of my equip item skill level,even where i stand it will reset to one time point.

**Comment by Tslat** [comment]
Does it do it without any mods? Take AoA out and see if it does it

**Comment by st920130** [comment]
still happen when i remove AOA3

**Comment by st920130** [comment]
but it won't happen at new map

**Comment by Angrydog001** [comment]
> 
> 
> still happen when i remove AOA3

Unfortunately, the world that you point has vanished by accident.

**Comment by Tslat** [comment]
Yeah it looks like you have some sort of issue with your world save.
You could try messing around with the files in your save, but your best bet is probably just to start a new world

**Comment by st920130** [comment]
OK THANKS

**Comment by st920130** [comment]
so it happen again maybe still have some bug inside

**Comment by Tslat** [comment]
What other mods are you using

**Comment by st920130** [comment]
[2019-03-04-1.log](https://github.com/Tslat/Advent-Of-Ascension/files/2923611/2019-03-04-1.log)
here are all mods i use this time:
[1.12]bspkrsCore-universal-7.6.0.1
[1.12]TreeCapitator-client-1.43.0
AoA3-3.0.2
CodeChickenLib-1.12.2-3.2.2.354-universal
InventoryTweaks-1.63
jei_1.12.2-4.14.4.260-tw
journeymap-1.12.2-5.5.3-tw
NotEnoughItems-1.12.2-2.4.2.240-universal
OptiFine_1.12.2_HD_U_E3
torohealth-1.12.2-11
VeinMiner-1.12-0.38.2.647+b31535a

My forge is 1.12.2-forge1.12.2-14.23.5.2768

**Comment by Tslat** [comment]
Can you remove Journeymap and see if it still happens?

If it does, provide a new log

**Comment by st920130** [comment]
[2019-03-04-3.log](https://github.com/Tslat/Advent-Of-Ascension/files/2923666/2019-03-04-3.log)
YEAH still happen

**Comment by Tslat** [comment]
If you removed Journeymap, why are you still getting journeymap errors?
java.lang.NullPointerException: null
	at **journeymap**.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:30) [WorldEventHandler.class:1.12.2-5.5.3]

**Comment by st920130** [comment]
I have no idea why still have it.I really remove journeymap,before remove it,I have 15 mods witch forge count for me but you see the second log it's only 14 mods.I did remove it.

**Comment by Tslat** [comment]
Are you playing on a server, or single player?

If it's a server you have to remove the mod on the server too

Your second log shows 15 mods loaded, not 14:

Client attempting to join with 15 mods : minecraft@1.12.2,FML@8.0.99.99,inventorytweaks@1.63+release.109.220f184,bspkrscore@7.6.0.1,aoa3@3.0.2,jei@4.14.4.260,veinminermodsupport@0.38.2,nei@2.4.2,forge@14.23.5.2768,codechickenlib@3.2.2.354,torohealthmod@1.12.2-11,mcp@9.42,treecapitator@1.43.0,journeymap@1.12.2-5.5.3,veinminer@0.38.2

**Comment by st920130** [comment]
i play single but i open to LAN once
i try to remove all journeymap's config files and load map again still happen
[2019-03-04-5.log](https://github.com/Tslat/Advent-Of-Ascension/files/2923740/2019-03-04-5.log)

**Comment by Tslat** [comment]
Can you also remove JEI and provide another log

Just trying to narrow down the potential issues

java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getActiveAdvancedGuiHandlers

**Comment by st920130** [comment]
game can't open
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/2923793/latest.log)
nei can't use without jei shoud i remove nei?

**Comment by Tslat** [comment]
Yes

**Comment by st920130** [comment]
[2019-03-04-7.log](https://github.com/Tslat/Advent-Of-Ascension/files/2923854/2019-03-04-7.log)

**Comment by st920130** [comment]
[2019-03-04-7.log](https://github.com/Tslat/Advent-Of-Ascension/files/2923858/2019-03-04-7.log)

**Comment by Tslat** [comment]
And the issue is still happening there?

**Comment by st920130** [comment]
YES still happen

**Comment by Tslat** [comment]
Remove ALL mods and provide a new log (You said it still happens when all mods were removed)

**Comment by st920130** [comment]
[2019-03-04-7.log](https://github.com/Tslat/Advent-Of-Ascension/files/2923913/2019-03-04-7.log)
still happen

**Comment by Tslat** [comment]
It says you still have mods installed

**Comment by st920130** [comment]
only forge

**Comment by st920130** [comment]
so i try to open with no forge issue didn't happen maybe i should change another forge vesion

**Comment by Tslat** [comment]
Try a clean install of Forge.. your logs indicate it's detecting mods still

**Comment by st920130** [comment]
[2019-03-04-7.log](https://github.com/Tslat/Advent-Of-Ascension/files/2924036/2019-03-04-7.log)
still happen

**Comment by Tslat** [comment]
Given that this is happening with no mods, on a clean install - this is likely something you'll have to take up with the Forge devs.

However before that, maybe right click on your save folder, click properties, and in the general tab make sure the "Read only" box is unticked, then click apply.
It might be that somehow some of your files became read only..

Beyond that, you'll have to take it to forge to have a look at

**Comment by st920130** [comment]
so i need to make my file read only?

**Comment by st920130** [comment]
[crash-2019-03-04_10.21.33-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/2924080/crash-2019-03-04_10.21.33-client.txt)
crash when i open my save file

**Comment by st920130** [comment]
still happen even i use the newest forge. maybe i need to contect with forge devs thank you for answer me.
