### ISSUE TITLE
[1.20.6] Increase stack size of Limonite bullets to 99

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#4139]
The other ammo items can stay at 64, limonite bullets being at 99 should generally fix the issue of bullets being so inventory filling. It'd allow you to fire for 50% longer, 256 bullets would now take up 2.5 inventory slots instead of 4, 640 bullets would take up 6.4 slots instead of 10. Pretty big difference

**Comment by Posatasa** [comment]
wonder if it's necessary for other ammos and runes to increase stack size like this
