### ISSUE TITLE
Incorrect subtitle for some Ancient Golem sounds

### ISSUE THREAD

**Issue by bluebear94** [Tslat/Advent-Of-Ascension#4153]
**Mod Version**
1.20.4-3.7.7

**Describe the bug**
The subtitles for some of the Ancient Golem’s sounds are incorrect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on subtitles
2. Spawn an Ancient Golem
3. Hurt or kill the Ancient Golem

**Expected behavior**
The subtitles should say “Ancient Golem hurts/dies”.

**Screenshots**
![2024-05-21_07 23 04](https://github.com/Tslat/Advent-Of-Ascension/assets/2975203/5696cf35-9f99-4e3f-8230-3cc7877e5a61)

![2024-05-21_07 22 54](https://github.com/Tslat/Advent-Of-Ascension/assets/2975203/44631d9c-804f-46ca-9dd2-7238d2b8f254)

This seems to be an issue with reusing the Iron Golem’s sound events in [the Ancient Golem’s code](https://github.com/Tslat/Advent-Of-Ascension/blob/037a9ee64ca6e0e77ebbbc77ce14da42b52b0308/source/content/entity/mob/overworld/AncientGolemEntity.java#L68).

**Comment by Tslat** [comment]
I've fixed the broken subtitle thing, but I'm gonna change this git issue to be a change
Ancient Golem intentionally re-uses iron golem sounds cus it's identical to what's wanted
Using vanilla sounds and getting vanilla subtitles is an interesting side-effect of that I'll have to think about
