### ISSUE TITLE
Revert Rosite/Jade/Sapphire/Amethyst to 2.4.B/Tslat 1.1.3 gen rates

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#416]
These ores are too rare now. They generate half as much as they did in 1.7.10 and are very annoying to get. Rosite, for instance, in Tslat 1.1.3 always generated with one vein in every chunk. Rosite in 3.0.2 generates with either 0 or 1 ore vein in every chunk, so it's already half as common. The same goes for jade and sapphire, and also amethyst.

This gets nastier when mods that add big ore veins start overwriting the little rosite that does spawn.
I get that having other mods is inherently going to make it harder to find this stuff but seriously

I've done a good deal of caving in multiple different caves in multiple different places, plus spent 2+ hours mining out a giant spawn room underground to spawn mobs. Also been through a mineshaft and several ravines that extend through y = 30. I haven't seen a single rosite or jade ore. Cruuk has experienced something similar.

I get that Rosite is kind of strong since it repairs stuff but was there really a reason to decrease the spawn rate, especially when these ingots are necessary to create the items to start training skills? (specifically the bloodlust bag lmao.) It's too much mining and is somewhat demoralizing.

Also, I'm not quite sure if ores can generate inside andesite/diorite/granite which may decrease the rate even more than it was in 1.7.10.

The biggest thing for me is the 50/50 chance to generate in a chunk though, I'm not even sure if it was intended but I do know that it's harder to get stuff now than it was before.

**Comment by Cruuk** [comment]
Don't forget the Ascension shrine requiring 5 Rosite.

**Comment by Cruuk** [comment]
1.7.10:
![image](https://user-images.githubusercontent.com/38159897/53675888-4689d880-3c50-11e9-8ad4-4193b56ed8d4.png)

--------------------

1.12.2:
![image](https://user-images.githubusercontent.com/38159897/53675900-691bf180-3c50-11e9-8630-0e2f4cb7bd16.png)

**Comment by Immortallis1** [comment]
I've gone through two emberstone picks myself
