### ISSUE TITLE
Tyrosaur boss in Precasia spawns only with some health, doesn't fight back and doesn't drop any loot

### ISSUE THREAD

**Issue by andzejsw** [Tslat/Advent-Of-Ascension#4166]
**Mod Version**
curseforge 1.20.4-3.7.7

**Describe the bug**
When spawning Tyrosaur boss in Precasia, it appears close as it should, but only with some health. It doesn't hit back when I attack it and it doesn't give any loot on death.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '.Precasia'
2. Spawn Tyrosaur boss using horn.

**Expected behavior**
Tyrosaur boss is being able to fight back, has full health when it spawns and it gives loot according to AoA wiki: https://adventofascension.fandom.com/wiki/Tyrosaur

**Comment by Tslat** [comment]
Tyrosaur is not fully implemented yet in 3.7+

**Comment by andzejsw** [comment]
> Tyrosaur is not fully implemented yet in 3.7+

Ok. Thanks for quick response.
