### ISSUE TITLE
The same NPCs generating different trades?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#417]
**Mod Version**
3.0.2

**Describe the bug**
NPCs with randomized trades appear to sometimes generate new trades randomly. For example there was a Naturalist that was selling Magic marang seeds and Heart fruit seeds, but when I got some coins and came back there was no more Magic Marang, but when I logged back in IIRC (can't remember 100%), the Magic Marang was back

**To Reproduce**
To be honest, I'm not 100% sure on how this even happens. From what I've gathered going far away from the NPC, going into a dimension, and/or logging off and logging back in changes the trades. ~~( The NPCs in my survival world still haven't despawned by the way)~~
Though from testing, I *think* the main cause is logging off, though I'm still not 100% sure.

**Expected behavior**
An NPC sticking with the trades it spawned with.

**Screenshots**
https://youtu.be/2ase5GOd2iQ

**Comment by Immortallis1** [comment]
You can put an NPC in a cage, name it, and test it to make sure it's not a new one

**Comment by Tslat** [comment]
I already confirmed this with shadow - has been fixed
