### ISSUE TITLE
No longer suitable plants in structures or features

### ISSUE THREAD

**Issue by Moshanxi** [Tslat/Advent-Of-Ascension#4171]
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/596355ef-88b4-4b0c-8b91-25fb7e078e59)
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/41af7bc9-e6ec-4336-bb87-8fc015c40318)

**Comment by Tslat** [comment]
Is this just about the alignment of the plants visually?

**Comment by Moshanxi** [comment]
Unlike other small flowers, it doesn't have random offset. And bulb stock is now short grass, which may be not suitable for y-stack (?)
of course it's up to your clear definition of its type

![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/8344beeb-84eb-4881-a19c-0b854823bfe0)
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/629fa1b4-4b21-4c0d-b2bb-44585a319638)
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/c7be362e-8f74-4dcc-89ad-fdb3bc309706)
