### ISSUE TITLE
Retexture for the Goofy and Soulstone shovel

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#418]
**POP QUIZ:** Which one is the pickaxe.
![dafghjh](https://user-images.githubusercontent.com/44548547/53680163-4ed52880-3ccf-11e9-9b69-e12088418d3c.png)
![afghhjh](https://user-images.githubusercontent.com/44548547/53680166-54327300-3ccf-11e9-82c6-0cd93ec752d2.png)
See what I mean, I always mix them up because of how similar they are.

**Comment by DiamondWalker** [comment]
![goofy shovel](https://user-images.githubusercontent.com/19913710/53688142-44d21a80-3d0d-11e9-817a-fe455041682b.png)
![goofyshovel](https://user-images.githubusercontent.com/19913710/53688143-44d21a80-3d0d-11e9-82db-9b90abac54db.png)
![soulstone shovel](https://user-images.githubusercontent.com/19913710/53688145-4996ce80-3d0d-11e9-9e6c-91a508a35911.png)

Do these look better? Also, fixed a small error on the soulstone sprite.

**Comment by Sagisolar** [comment]
I guess

**Comment by Tslat** [comment]
Fixed
