### ISSUE TITLE
Hovering Baobab tree

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#4195]
**Mod Version**
3.7.8

**Describe the bug**
Baobab trees can generate hovering in mid-air

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a world with seed -7840521252294670103
2. Go to 565,90,305 in Precasia
3. Observe that a Baobab tree exists in mid-air

**Expected behavior**
The Baobab tree should generate 1 block lower, touching the ground

**Screenshots**
<img width="1512" alt="截屏2024-06-26 17 23 12" src="https://github.com/Tslat/Advent-Of-Ascension/assets/37212918/1ebb6423-4d67-45dd-b7df-b495b237569a">

**Comment by Tslat** [comment]
🤔 I think this is a vanilla bug lol
I use the vanilla tree generator for this, which has its own dirt handling logic

**Comment by PraseodymiumSpike** [comment]
> 🤔 I think this is a vanilla bug lol I use the vanilla tree generator for this, which has its own dirt handling logic

Perhaps, there is some weird list that you need to add the modded grass to so that the tree trunk can replace it. I haven't seen this bug in a while in vanilla.
