### ISSUE TITLE
Killing Eeos has to do something with Mysterium

### ISSUE THREAD

**Issue by MerekiDor** [Tslat/Advent-Of-Ascension#420]
According to the main idea of Mysterium being placed inside of Eeos imagination, it makes no sense why killing those creatures does not impact the dimension.

I think that this should be somehow reflected on the surroundings or the player. For example, killing an Eeo would shuffle the blocks around (if mob griefing is set to true)? Or maybe it would give the player a Nausea effect and teleport them somewhere nearby? Or an overlay? Basically, killing Eeos should do something with the world, since their death should cause some kind of consequences, because its their own world.

**Comment by DiamondWalker** [comment]
I like this idea! I'm not too much of a fan of the moving block stuff, but I would like to see something like the dimension becoming darker or sound/screen effects for a while after you killed an Eeo.

**Comment by Immortallis1** [comment]
You could make the excuse that there are so many that their imagination is stable.
Regardless, I like this too.

**Comment by DiamondWalker** [comment]
Yeah, I think it should be a barely noticeable difference that becomes more obvious as you kill several Eeos. Could be something like warp from thaumcraft, but specific to Mysterium.
