### ISSUE TITLE
Mod Does Not Load

### ISSUE THREAD

**Issue by PraseodymiumSpike** [Tslat/Advent-Of-Ascension#4201]
**Mod Version**
AoA3-1.21-3.7.8.jar

**Describe the bug**
The mod does not load.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install NeoForge 21.0.42.
2. Install the mod.
3. Attempt to start up Minecraft.

**Expected behavior**
The mod loads.

**Screenshots**
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/99032794/029b66c7-2e9c-4d79-98b5-8ef709e1e460)
also a crash report
[Crash Report.txt](https://github.com/user-attachments/files/16038647/Crash.Report.txt)

**Comment by PraseodymiumSpike** [comment]
By the way, I removed my name from the crash report.

**Comment by Moshanxi** [comment]
use .30 or lower version Neoforge. it's said that .31 brings some breaking changes.it will be fixed in next aoa version
