### ISSUE TITLE
I had some issues launching minecraft in 1.12.2 with AoA and Pam's HarvestCraft

### ISSUE THREAD

**Issue by CoCuzz4** [Tslat/Advent-Of-Ascension#4203]
**Mod Version**
1.12.2 AoA 3.3.6

**Describe the bug**
I tried to make a personal mod pack, with a lot of mods, and strangely when I added the AOA it told me that there were problems with another mod "Pam's harvestcraft".
However, when I try to remove the AoA or Pam's HarvestCraft the error does not show up

**To Reproduce**
When I enter minecraft, even before going to the main menu it shows me an error screen that says "Minecraft failed to start!" and underneath "An error during startupp prevented minecraft from starting
 The following mod(s) have beed identified as potential causes: 
Forge Mo Loader, Minecraft Forge, Pam's HarvestCraft
Click any mod in the list to go to their website for a support, a has been generated with this name in you crash folder,
crash-2024-06-30_23.42.53-client.txt"
And then downstairs there's the usual link button, here it is 
https://mclo.gs/HbOKTXK

**Expected behavior**
I don't understand why it doesn't work, some time ago I made another world in 1.16.5 and with AOA and Pam's HarvestCraft and it worked very well, I expected it to work in 1.12.2 as well but it's not like that...

**Screenshots**
![Minecraft 1 12 2 30_06_2024 23_49_40](https://github.com/Tslat/Advent-Of-Ascension/assets/174279440/93204edd-f28f-4bb2-a3cb-f968106725f3)
![Vanilla 1 12 2 Crash Report  #LoGJqiS  - mclo gs - Opera 30_06_2024 23_50_14](https://github.com/Tslat/Advent-Of-Ascension/assets/174279440/d16cb652-4aa3-41b6-addf-3be6baa3f6f6)

**Comment by Tslat** [comment]
Install Not enough ids

**Comment by CoCuzz4** [comment]
THANK YOU SO MUCH MAN, you saved an entire server!!!
