### ISSUE TITLE
Decrease number of particles for nethengeic wither's firebomb ability

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#4204]
For regular nethengeic wither, this isn't a big issue. You have enough time to locate the projectiles and get out of the way.

For elite nethengeic wither, though, who is constantly spamming them out? There's so much smoke and fire that it's impossible to tell what's going on. Look at these images and notice how hard it is to find the projectiles. Now imagine having to do it every second. Also notice that the flame particles from the previous volley remain for a short period of time, which makes it look like there are 2 sets of projectiles. That means even less time to get a clear read of where the bombs are going.
![2024-06-30_23 44 51](https://github.com/Tslat/Advent-Of-Ascension/assets/19913710/a3188100-d3fb-4af3-82a2-0ea8adba94c5)
![2024-06-30_23 46 16](https://github.com/Tslat/Advent-Of-Ascension/assets/19913710/a4025720-68d8-4c57-9e5b-d66d9b2475e1)
![2024-06-30_23 46 19](https://github.com/Tslat/Advent-Of-Ascension/assets/19913710/689495a6-d09c-4dfc-ab00-afb3a97573b6)

**Comment by Tslat** [comment]
That's the point though
it's meant to be visually relevant noise so you have to focus and stay engaged

It's part of the chaos of the fight

For his firebomb attack, if you look you can see quite well defined lines showing where he'll be firing

**Comment by Moshanxi** [comment]
For Elite Neth Wither, it just has two extra times on 1/4&3/4 of max health to use the ability. Just find a large column to wait for firebombs ending
