### ISSUE TITLE
Nowhere teleport system wrong

### ISSUE THREAD

**Issue by Moshanxi** [Tslat/Advent-Of-Ascension#4207]
Before you build the portal with realmstone in a new save: 

1. use Troll Idol to enter the Disabled Boss Lobby
2. turn back and enter the portal
Then it will teleport you to the world original spawnpoint, instead of the position you right click the Troll Idol. 
And the advancement triggers.

1. repeat above
Then it will teleport you to the Boss Lobby.

**Comment by Tslat** [comment]
Nuuuuuuu
