### ISSUE TITLE
[1.21] Neoforge crash while loading LivingAttachEvent

### ISSUE THREAD

**Issue by Periam** [Tslat/Advent-Of-Ascension#4212]
**Mod Version**
What version of the mod are you on?
AoA3-1.21-3.7.8.jar

**Describe the bug**
After installing the mod and launching the game the same does start, indicating an error with  LivingAttachEvent

**To Reproduce**
Steps to reproduce the behaviour:
1.install AoA
2. Launch the Game

**Expected behavior**

To launch the game.

**Screenshots**

![image](https://github.com/Tslat/Advent-Of-Ascension/assets/13920185/d43833c0-83fc-464c-838a-a4e4db9083fd)

[crash-2024-07-04_21.36.47-fml.txt](https://github.com/user-attachments/files/16103612/crash-2024-07-04_21.36.47-fml.txt)

**Comment by masterbobli** [comment]
Use neoforge 21.0.30 instead

**Comment by Periam** [comment]
If the neoforge version if downgraded, then other mods will not run.

**Comment by VusyBery** [comment]
Then wait for AoA to update, it should work with newer Neoforge versions then
