### ISSUE TITLE
Crash server side between GregTech Modern 1.3.1 and Advent of Ascension 3.7.9 in 1.21

### ISSUE THREAD

**Issue by Ashley123477** [Tslat/Advent-Of-Ascension#4228]
**Mod Version**
AoA3-1.21-3.7.9

**Describe the bug**
NeoForge: 21.0.61-beta[16:27:29] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:

LowDragLib (ldlib) has failed to load correctly
java.lang.IllegalArgumentException: class com.lowdragmc.lowdraglib.CommonProxy has no @SubscribeEvent methods, but register was called anyway.
this only happens server side, client side loads up fine, ive attached the crash log with it
[crash-2024-07-06_16.27.29-fml.txt](https://github.com/user-attachments/files/16116618/crash-2024-07-06_16.27.29-fml.txt)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Latest Gregtech and Advent of Ascension
2. Start up server with latest neoforge
3. Watch it crash due to an issue between the two mods and LDLib

**Expected behavior**
Server to boot up as normal

I am aware that this might not be this mods issue but i have submitted bug reports in all 3 mods to see who might be able to fix it.

**Comment by Tslat** [comment]
LDlib problem
