### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by whyamiathing** [Tslat/Advent-Of-Ascension#423]
Version 3.0.2

A crash, discerning that a dimension registered at 811 is already registered. I do not know, what is wrong, as I have no other mods installed, only normal Minecraft. I am sorry if this is an easy fix, I have not familiarized myself with java, only surface Minecraft level knowledge. 

I expected the game to open like normal. Display the title screen, and allow me to play

[crash-2019-03-02_12.02.12-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/2922390/crash-2019-03-02_12.02.12-client.txt)

**Comment by Tslat** [comment]
At some point you played one of the early snapshots of the mod..
In that early snapshot, the configuration file had an error, which causes crashes with newer versions.

Go into your config folder and delete the AoA config file, that'll fix your issue

**Comment by whyamiathing** [comment]
Thanks!
