### ISSUE TITLE
Creeponia Expansion

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#424]
This suggestion is a full expansion of Creeponia: from the Creep day to that primed layer almost no one noticed. Since this suggestion is quite long, I'll go in order of the changes you'll notice from the start of the game:

Creep Day:
The creep day would have more mobs (but the Hosts would still be the only ones that drop realmstones). During the creep day, several biomes would get a unique creeper variant that has a special effect when it explodes: Sand Creeper (yellow, spawns in deserts and would inflict fire to players), Snow Creeper (white, would spawn in snow biomes and inflict slowness to players), Jungle Creeper (dark green, would spawn in jungles and would inflict poison to players), Light Creeper (light blue, spawns in mountains and throws players back), and Dark Creeper (grey, spawns in caves and inflicts wither to players).

General Creeponia changes:
The surface would be moved upwards so it's at about y=140. Most of this extra space would be assigned to the green underground layer so it takes longer to get to the primed layer, but the primed layer could also become bigger. Some of the mobs would be moved: Magical Creepers could spawn on the surface, and the Creeperlocks would be moved to the green underground layer. Bone Creepers would also be moved to the green underground layer.

Creeponia ores:
If you mine creeponia ores regularly, they will explode and not drop the ore. To mine them, you would need an "Explosive Pickaxe", which is dropped from KingBamBamBam (so you can no longer get the creeponia armor and beat him easily). When mined correctly, they will drop a fragment of the ore (for example, a Jewelyte fragment). Four of these fragments would have to be combined to make the gem (this will make mining the ores take longer, since it currently takes little to no time). The gems themselves would be useless. To use them, you would have to refine them on an "Explosive Station".

The Bunker:
A new structure that spawns underground. In it, there will be a new NPC. This new NPC would be a human that made his way into Creeponia and is hiding away from all the creepers in the bunker. He would sell the "Explosive Station" for 10 unrefined Ornamyte and 15 unrefined Jewelyte. His quotes would be:
"Be careful, you'll get blown to pieces out there!"
"These Creepers are savage! And I thought the ones in the Overworld were bad..."
"I wonder who made this bunker. All I know is it saved my life."
"If I could get my hands on some of the ore around here, I might stand a better chance out there. Bring me some, and I'll give you the key to working with them."

Primed Layer rework:

Would now generate similar to that bugged third Vox Ponds layer in 1.7, but the floor would be completely flat and be made of primed stone instead of bedrock. The opening would be about 20 blocks high. There would be huge stalagmites and stalactites made of primed stone. At the tip of these stalagmites and stalactites, Ornamyte would spawn. Ornamyte would now be "unstable" (it'd frequently fire bursts of explosive projectiles in all directions), meaning you would experience bullet hell when you're in the primed layer. This layer would be very dark, and there would be jumpscares down here. The jumpscares wouldn't the a creeper popping up in your face or something like that, instead, they would be based on sounds. Every Creeper sound (including the charging, hurt, and death sounds) would play randomly down here. There would also be explosion sounds. There would be three variants of the explosion sounds: loud (sounds like the explosion was on you), distant (sounds like the explosion was really far away and barely audible), and approaching (sounds like a chain of explosions quickly coming towards you). The mobs here would be:

Cave Creepoid: would now have completely different AI. It would walk along to bottom of the primed layer, spawning clones (like a trickster). Occasionally, it and all of its clones would jump up in unison and explode when they reach the top of their jump (the explosion wouldn't kill them).

Shadow Creeper: would be completely invisible, but its eyes and mouth would occasionally flash white, making it partially visible for a moment. It would not be affected by gravity (similar to Baroness bombs), and would slowly teleport towards you, a few blocks at a time. It will avoid being seen, and would end up behind you when it teleports. It continues this until it gets close enough to explode. If you manage to look directly at it, it will die on the spot.

Dark Creeperlock: would be the same as the regular creeperlock, but it wouldn't move. Instead, it would swap places with the creeper that is closest to you.

There could also be a new boss down here. Ideally it'd fly and randomly spawn (like Corallus, but it has a chance to spawn every certain amount of time instead of when killing a mob).

**Comment by Immortallis1** [comment]
yeah I'm not a fan of requiring a bambambam kill

**Comment by DiamondWalker** [comment]
Thing is, kingbambambam is completely pointless aside from the explosion armor. What made him important was that you needed to kill him to get explosion resistance. That is until 2.4 came along, and for whatever reason it was decided that going into one of the first dimensions and smacking some rocks should be more rewarding than training hunter, going to a harder to access dimension, finding a structure, killing some mobs, and beating a challenging boss several times.

**Comment by Immortallis1** [comment]
Yeah, maybe the fact that smacking some rocks makes it easy needs changing, but so does a lot of other stuff. I'm just not a fan of requiring boss kills for anything but ESPECIALLY not king bambambam because his structure is just incredibly annoying to find. Remember, explosion immunity isn't even much in the end

**Comment by DiamondWalker** [comment]
I think changing the structure is a better solution than making a potentially important boss useless.

**Comment by Sagisolar** [comment]
I have no problem with King BamBamBam being required. Anyway more stable content = good.
