### ISSUE TITLE
Rainicorn really rare?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#426]
**Mod Version**
3.0.2

**Describe the bug**
From what I've experienced, Rainicorns appear to be extremely rare for being regular mobs. I've seen 1 so far, along with seeing 1 Voliant.

**To Reproduce**
Steps to reproduce the behaviour:
Go in Haven and watch mobs spawn

**Comment by Tslat** [comment]
It's the exact same as 1.7.10...

**Comment by masterbobli** [comment]
Has the spawn conditions changed？Could the enlarged islands create unfavorable environment for them to spawn?

**Comment by Tslat** [comment]
Possibly, though unlikely since 1.7.10 had the same conditions
