### ISSUE TITLE
Creeponia Realmstone without TNT

### ISSUE THREAD

**Issue by VusyBery** [Tslat/Advent-Of-Ascension#4261]
**Mod Version**
3.7.9

**Describe the bug**
Blank Realmstones turns into Creeponia Realmstone whenever you get hit by a Creeper's explosion, without requiring the presence of primed TNT. This is not only unintended but also makes obtaining it comically easy lol

**Comment by Tslat** [comment]
Eh.. it's a bug
But I'm not concerned really until the realmstone actually means anything, cus I may end up changing the task at that stage anyway lol

**Comment by VusyBery** [comment]
My main concern with this one is that it's way too easy to do on accident, though, and lose a Blank Realmstone (not that they're rare or anything but it can be sort of annoying)
