### ISSUE TITLE
[1.21]  NeoForge Error SpawnPlacementRegisterEvent.

### ISSUE THREAD

**Issue by Periam** [Tslat/Advent-Of-Ascension#4263]
**Mod Version**
What version of the mod are you on?

AoA3-1.21-3.7.9.jar

**Describe the bug**

After installing the latest version of the mod the game does not load, in crash on the loading screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the mod.
2. Launch Game

**Expected behavior**

That the game launch.

**Screenshots**
![Screenshot 2024-07-10 094109](https://github.com/Tslat/Advent-Of-Ascension/assets/13920185/20ac82f3-0c7f-41ac-ad14-3fa770492d16)

Crash Logs

[latest.log](https://github.com/user-attachments/files/16162139/latest.log)

[crash-2024-07-10_09.39.05-fml.txt](https://github.com/user-attachments/files/16162145/crash-2024-07-10_09.39.05-fml.txt)

**Comment by VusyBery** [comment]
Neoforge keeps breaking AoA lately, use neoforge version .60 until AoA updates
