### ISSUE TITLE
Dexterity Level 2 and Level 5 portals don't work

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#4265]
**Mod Version**
3.7.10

**Describe the bug**
Level 2 and Level 5 portals do not teleport the player to the challenge

**To Reproduce**
1. Visit nowhere
2. Enter the Level 2 or Level 5 portals in dexterity chamber
3. Observe that you're not teleported to the corresponding level

**Expected behavior**
The portal teleports the player to the corresponding level.

**Screenshots**

**Comment by Moshanxi** [comment]
The two haven't been added yet. And it seems relatively lacking in structures.
![image](https://github.com/Tslat/Advent-Of-Ascension/assets/127667930/55714411-5a5b-4ff8-8e45-278c206ea29d)

**Comment by Posatasa** [comment]
not added
