### ISSUE TITLE
Killing Tyrosaur doesn't repair the bone horn

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#4266]
**Mod Version**
3.7.10

**Describe the bug**
After killing the wounded Tyrosaur spawned in Precasia, the bone horn remains damaged.

**To Reproduce**
Steps to reproduce the behaviour:
1. Craft a bone horn
2. Blow the horn in Precasia to summon a wounded Tyrosaur
3. Kill the tyrosaur
4. The bone horn is still damaged

**Expected behavior**
The bone horn is repaired.

**Screenshots**
<img width="1512" alt="截屏2024-07-11 10 30 04" src="https://github.com/Tslat/Advent-Of-Ascension/assets/37212918/2fdf7379-318e-47e2-a76f-6cd07c2137a3">
<img width="1512" alt="截屏2024-07-11 10 30 09" src="https://github.com/Tslat/Advent-Of-Ascension/assets/37212918/9d313cd9-3f17-48d8-b9c8-25dc31d4702c">

**Comment by Posatasa** [comment]
Think it's WIP
