### ISSUE TITLE
Dryad Sprite problems

### ISSUE THREAD

**Issue by VusyBery** [Tslat/Advent-Of-Ascension#4268]
Because of how rare they are, it is hard to say for sure, but it seems as though Dryad Sprites may not spawn.
In addition, ones summoned with the /summon command cannot be interacted with at all, and I do not see any reason why that should not apply to the ones summoned by farming as well.

Finally, these have a bestiary entry despite them not being killable and it is unused as a result.

**Comment by Tslat** [comment]
Works fine

**Comment by VusyBery** [comment]
huh
