### ISSUE TITLE
AoA GUI Appears to Be Broken

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#4269]
**Mod Version**
What version of the mod are you on?
3.7.10

**Describe the bug**
The ability of skills is empty, and the bestiary entries are misaligned.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the AoA GUI
2. Click on any skills
3. Observe that the entries section is empty
4. Click on bestiary
5. Observe that the bestiary entries are misaligned.

**Expected behavior**
The ability of skills is displayed, and the bestiary entries are aligned.

**Screenshots**
<img width="1512" alt="截屏2024-07-12 20 42 11" src="https://github.com/user-attachments/assets/eeb1a181-c29c-484a-a587-c1f0b4192a63">
<img width="1512" alt="截屏2024-07-12 20 46 19" src="https://github.com/user-attachments/assets/f1fa085c-fbb8-4226-8afc-e4684a6f34de">

**Comment by masterbobli** [comment]
A potential explanation is that I'm running on Mac OS.
And maybe it's something that causes scrollables to break.

**Comment by Tslat** [comment]
Definitely not happening on windows
Would not surprise me if it's Mac - Mac has made itself incompatible with modern rendering schemas - and I'm not sure I can do anything about that if that is the problem

**Comment by TripleThreeT** [comment]
It is a Mac thing. Not just for this mod too but several others. For some reason Macs mess up with these sorts of GUI.
