### ISSUE TITLE
Nethengeic Wither not changing textures when entering other phases

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#427]
**Mod Version**
3.0.2

**Describe the bug**
When Nethengeic Wither changes forms, his texture would change depending on what form he changed to. This is not present in 1.12.

**To Reproduce**
Steps to reproduce the behaviour:
Spawn Nethengeic Wither
Get him down to 50% or 25% health. These are where the texture changes are supposed to happen IIRC.

**Expected behavior**
Nethengeic Wither changing textures.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/53691335-93dd7700-3d30-11e9-801a-6763edfa91be.png)

**Comment by Tslat** [comment]
Fixed
