### ISSUE TITLE
Magic immunity affecting both Staves and Blasters? (when there's already a Blaster immunity icon)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#428]
**Mod Version**
3.0.2

**Describe the bug**
There appears to be a new attribute for Blasters. As far as I know Anemia is the only mob that has it, and from testing it works as intended- Blasters don't damage it but everything else does.

But for magic immunity, it appears to affect staves, blasters, and status effects. I assume it's only supposed to affect staves. (and maybe not status effects because I found an icon for that in the files haha)

**To Reproduce**
Try to damage a magic-immune mob with Blasters/status effects

**Expected behavior**
Magic immunity only affecting staves?

Though to be honest, with Blaster immunity being a new thing I get the feeling magic immunity just hasn't been updated yet to accommodate the new attributes (Blaster and "status" attribute), but I figured I might as well make this git post just in case...

**Comment by Tslat** [comment]
Fixed
