### ISSUE TITLE
Custom potion names do not show

### ISSUE THREAD

**Issue by VusyBery** [Tslat/Advent-Of-Ascension#4282]
**Mod Version**
3.7.10

**Describe the bug**
The Potion of Everlasting Strength dropped by Smash (and presumably other custom-named potions) do not use their custom names ingame.

![image](https://github.com/user-attachments/assets/cc750b66-c419-4625-aab6-80058e84b378)

**Comment by Moshanxi** [comment]
seems also wrong with trophy
![image](https://github.com/user-attachments/assets/f604e6ea-d128-4996-9d0c-20f9480be410)
![image](https://github.com/user-attachments/assets/c0a10f4c-e844-4800-af3f-5b688f2e09a6)
![image](https://github.com/user-attachments/assets/d58be77b-b0f5-4872-9ae7-a0477484aa36)

**Comment by Tslat** [comment]
What's wrong with trophies?
