### ISSUE TITLE
Extraction always giving the same exp no matter how many items you smelted

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#4286]
Grabbing 64 items gives the same exp as grabbing 1 item

**Comment by Tslat** [comment]
Believe it or not

this one isn't fixable until NeoForge fixes a longstanding forge bug

**Comment by Tslat** [comment]
https://github.com/neoforged/NeoForge/issues/1367

**Comment by Cruuk** [comment]
Nice

**Comment by Tslat** [comment]
Closing this because there's nothing I can do about it, and it'll be fixed when Neoforge fixes it
