### ISSUE TITLE
Sharp Claws be used in making arrows

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#4300]
I've been going through the items in the world I've spent the most time playing. I noticed that I have over a stack of Sharp Claws(mainly from fighting Chargers). However, Sharp Claws don't have much use in the game; they're only used in four recipes. One idea I had is to use Sharp Claws as an alternative way to craft arrows, replacing flint. Instead of getting four arrows, however, you would get only two. This could give Sharp Claws a more significant role in the game.

**Comment by Tslat** [comment]
Yeah alright
