### ISSUE TITLE
[Bug] Why are there no dimensions? (1.19.4+)

### ISSUE THREAD

**Issue by DRD2k8** [Tslat/Advent-Of-Ascension#4306]
**Mod Version**
1.20.1

**Describe the bug**
No dimensions (Already know about what the mod said when I joined the world)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Advent of Ascension
2. Join a new world
3. Go through the portal
4. Enter the dimension

**Expected behavior**
There's a dimension

**Comment by Tslat** [comment]
Join the discord to discuss if you want

https://adventofascension.fandom.com/wiki/Player_questions#Why_aren't_the_portals_working?
