### ISSUE TITLE
Hitbox problem with many mobs I think...

### ISSUE THREAD

**Issue by Darknight8151** [Tslat/Advent-Of-Ascension#431]
**Mod Version**
AoA3-3.0.2.jar

**Describe the bug**
They hit me too far "Giant wood" and "Horndron" and I have not been in the dimension yet.
Must see with other mobs if this is not the case.

**Expected behavior**
Fix hitbox of mobs it is not difficult but unplayability :(

**Video**
https://streamable.com/o3r4b

**Comment by Tslat** [comment]
Big mobs have large reach. Use a bow or something.

**Comment by Darknight8151** [comment]
Ah, so it's voluntary that it's like that in 1.12.2?

**Comment by Tslat** [comment]
No, that's just how hitboxes work on large mobs.
Vanilla Minecraft handles it like that

**Comment by Darknight8151** [comment]
In 1.7.10 AoA-Tslat-1.1.3 it was not the case this problem makes it for that which I ask for the 1.12.2 if it was voluntary :/
