### ISSUE TITLE
What to do in this situation

### ISSUE THREAD

**Issue by rjdxxxxxccc** [Tslat/Advent-Of-Ascension#4317]
![屏幕截图 2024-08-09 220552](https://github.com/user-attachments/assets/84a52b38-ac89-4d1e-a4e7-89a111ef5e62)
Minecraft version 1.20.1
forge version 47.2.21

**Comment by rjdxxxxxccc** [comment]
Mod version 1.20.1-3.7.1

**Comment by Posatasa** [comment]
see player questions page on wiki
