### ISSUE TITLE
Food in Cups or Buckets are stackable

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#432]
**Mod Version**
3.0.2

**Describe the bug**
So you can't stack normal milk but you can with Halycon Milk. You can also stack food from cups.

**Expected behavior**
Not being able to stack this stuff.

**Screenshots**
![sffgsgdf](https://user-images.githubusercontent.com/44548547/53700518-35290380-3deb-11e9-8ed5-f2980febc2bd.png)

**Comment by WeegeeTheDoggo** [comment]
I get it, consistency.. but i mean..
_I love when things stack.._ </3
