### ISSUE TITLE
Monster Meats

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#4320]
AoA has many dimensions and besides Precasia, those dimensions have monsters instead of typical animals. This was discussed a while ago on Discord, but a general monster meat for animalistic monsters would be a nice addition similar to Giant Lizard meat for lizard-type mobs.

A personal idea of mine is to have two types. One called White Monster Meat and another one called Dark Monster Meat. Both with their own unique benefits and limitations. The type of meat would depend on the dimension and their nature. For example, an Urka would drop Dark Monster Meat as it's from Dustopia a dark dimension. On the flipside, a Dawnlight would drop White Monster Meat since the dimension is more bright. 

These would help add some new food sources without having to add 20+ different ones for each kind of animalistic monster mob.

**Comment by Tslat** [comment]
I don't really want to make monsters a source of food in general - animals have a place there and it would invalidate a lot of them
