### ISSUE TITLE
Weird description for hauling ability

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#4322]
![Screenshot 2024-08-11 185918](https://github.com/user-attachments/assets/a2f0953a-910e-4b38-8c85-ca0b8372df61)
Am confused. Why "+ -0.35%" instead of just "- 0.35%"? Why is the current value negative? Is this a bug? If it isn't, maybe limit the current value display to 0% and do the other change I mentioned before. Reading this was very confusing.

**Comment by Tslat** [comment]
It's a generic description that I didn't want to spend a bunch of time doing custom parsing on

What do you mean limit the display? It's reducing the value. -0.35% is correct, showing 0 would be wrong

**Comment by DiamondWalker** [comment]
> It's a generic description that I didn't want to spend a bunch of time doing custom parsing on
> 
> What do you mean limit the display? It's reducing the value. -0.35% is correct, showing 0 would be wrong

It's telling me that at this moment, I have a -12.5% chance for a trap to spawn. What does a negative chance mean???

**Comment by VusyBery** [comment]
Means it can't happen. Trap Spawns odds were designed to never actually be possible because they're not properly implemented yet, iirc
