### ISSUE TITLE
A way for multiple players to travel to disabled boss lobby

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#4324]
If I'm not mistaken, accessing nowhere before you obtain the realmstone requires one boss totem per player. In my opinion this is kind of strange from a design standpoint; why not make it so using the totem teleports nearby players too, like the boss altar does?

**Comment by Tslat** [comment]
Because those players have not unlocked access to the boss yet

**Comment by DiamondWalker** [comment]
> Because those players have not unlocked access to the boss yet

What if those players are playing together?

This doesn't make sense to me. If one player gains access to a dimension, they can share that access with a friend. If one player gains access to Nowhere AND a boss, they can share that access with a friend, but if one player gains access to a boss but not nowhere, they can't share that access with their friend? Unless they go out of their way to create multiple boss totems?

Also, this requirement only applies to the first boss, because once you're fighting future bosses, your friend(s) can just use the previous boss totems to get to the nowhere boss lobby?

This system is odd. It can easily be bypassed and doesn't really solve anything. Why not just make it possible for multiple players to use 1 boss totem at a time?

**Comment by Cruuk** [comment]
Could cause potential issues like griefing ones. Note that you have to bring yourself to boss altar, whereas a boss token item can be brought to you if it could TP other players around it.

Not sure what Tslat is saying there, but I don't think the system was intentionally done to not allow bypassing stuff like that

**Comment by Tslat** [comment]
Preventing players using portals arbitrarily is problematic and immersion breaking

Yes, you can use someone else's portal to get to nowhere if they have one, but that's not really _intentional_, it's just a byproduct of the limitations of the system I'm working with

Teleporting to a boss arena prior to unlocking Nowhere is a separate system, and is quite literally you using the power of the totem to teleport to the boss lobby. It's not a wide-area teleport or a portal, it's a personal effect.

It's also very specifically a limited version of the lobby - you can't go back out to the prep rooms, you can't access any support areas, you can't be visited by other people in Nowhere.
It's not designed to be a full-fledged access, it's meant to be a grace that allows you to fight bosses without explicitly needing to hunt down the Nowhere realmstone.

If you want all the benefits of Nowhere, then get access to Nowhere.

**Comment by DiamondWalker** [comment]
> Preventing players using portals arbitrarily is problematic and immersion breaking
> 
> Yes, you can use someone else's portal to get to nowhere if they have one, but that's not really _intentional_, it's just a byproduct of the limitations of the system I'm working with
> 
> Teleporting to a boss arena prior to unlocking Nowhere is a separate system, and is quite literally you using the power of the totem to teleport to the boss lobby. It's not a wide-area teleport or a portal, it's a personal effect.
> 
> It's also very specifically a limited version of the lobby - you can't go back out to the prep rooms, you can't access any support areas, you can't be visited by other people in Nowhere. It's not designed to be a full-fledged access, it's meant to be a grace that allows you to fight bosses without explicitly needing to hunt down the Nowhere realmstone.
> 
> If you want all the benefits of Nowhere, then get access to Nowhere.

I wasn't suggesting portals be player-locked. That would be weird.

If the intent is that all players who fight a boss have a totem for that boss, wouldn't it be better to make the boss altar require all players in the area have the boss totem too? i.e. if you go to nowhere and use the troll idol on the boss altar, only players who also have a troll idol in their inventory AND are standing in the area will be teleported.

I just find it extremely confusing that an arbitrary milestone (accessing Nowhere) means you randomly go from "all players need a totem" to "one guy can get the totem and bring everyone else along". I don't really care whether you need one totem per player or not; I just wish it were consistent.
