### ISSUE TITLE
Remove burning animation when wearing full set of Infernal Armor

### ISSUE THREAD

**Issue by Moshanxi** [Tslat/Advent-Of-Ascension#4327]
If the armor ability is defined as a super Fire Protection enchant.

**Comment by Tslat** [comment]
Yeah there's not a lot I can do here

I could patch in a brute-force disable of rendering fire if you're immune to it, but ultimately this is more of an overarching issue with poor implementation of damage handling on vanilla and other mods' part

I can't even feasibly fix this without potentially breaking something else
