### ISSUE TITLE
Precasia worldgen crash

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4333]
3.7.12, this crush happens when I'm at the junction of precasian jungle and precasian desert.

seed is 81108640, I went into Precasia at overworld spawnpoint then teleported to nearest desert. About 15 seconds later the game crashed

[latest.txt](https://github.com/user-attachments/files/16600034/latest.txt)

**Comment by Tslat** [comment]
Closing as duplicate even though this one was first
