### ISSUE TITLE
Dexterity makes you overly sensitive to fall damage

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#4334]
Jumping from heights that would normally be harmless with dexterity means you take fall damage. This is very annoying because you're exploring, jump a bit, and suddenly take fall damage for no apparent reason.
https://streamable.com/o8797z

Jump boost avoids this issue by decreasing fall damage. Not sure how that could be applied to dexterity.

**Comment by Cruuk** [comment]
You can toggle abilities by clicking on them in the ability menu.

As for this issue, maybe as a little QoL, the fall damage reduction ability can nullify damage taken at very low heights. I don't know

**Comment by DiamondWalker** [comment]
> You can toggle abilities by clicking on them in the ability menu.
> 
> As for this issue, maybe as a little QoL, the fall damage reduction ability can nullify damage taken at very low heights. I don't know

I know you can toggle it, but the damage taken is so tiny that the benefit outweighs it. I just think it's silly that you can hurt yourself on a tiny slope like this https://streamable.com/yzbu07
