### ISSUE TITLE
Rune Templar spawning Runic Lifeforms on surface

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#434]
**Mod Version**
3.0.2

**Describe the bug**
When the Rune Templar minigame is active, the Rune Templar spawns its Runic Lifeforms on the surface, instead of in the chamber with it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a rune templar in runandor.
2. Activate the minigame.
3. Go to the surface.
4. See the Runic Lifeforms spawns on the surface.

**Expected behavior**
The Rune Templar spawns its Runic Lifeforms in its room with it.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/53701844-04d36c00-3dcf-11e9-923d-71ace9f16ff6.png)

**Comment by Tslat** [comment]
Fixed
