### ISSUE TITLE
Auto Harvesting Trash GUI not visible items

### ISSUE THREAD

**Issue by VusyBery** [Tslat/Advent-Of-Ascension#4346]
**Mod Version**
3.7.12

**Describe the bug**
The GUI for the Auto Harvesting Trash ability shows an empty inventory and hotbar regardless of what you actually have. The ability still works, ie clicking on a spot where you actually have an item will register it for the ability as normal, but the contents of the inventory are just invisible on the GUI

**Comment by Tslat** [comment]
I can't seem to replicate this

![image](https://github.com/user-attachments/assets/ef12210f-741b-485e-8232-a90893aeaf28)

**Comment by VusyBery** [comment]
Huh. I tested it in a new world and it's still glitched for me. May be hardware related since my stuff is pretty low-end?

**Comment by Tslat** [comment]
Closing this because I still can't replicate it lol
