### ISSUE TITLE
Ancient Teleporter Locator

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#435]
**THE PROBLEM:**

Ancient teleporters are rare. I found ONE ancient teleporter by chance underneath my house. After that I caved and dug for hours, and didn't find any other ones. Cruuk complaind about this too, although I'm not quite sure of his circumstances.

But, if you make them more common, then they become trivial to find, and that becomes a problem in itself.

Structures that are underground in vanilla have locators or are not important. Dungeons are underground yes but they don't give anything necessary to progress, so it's more of a " Plus, they're always (supposed to be) connected to caves by design. Mob farms using spawners are something not everyone can do, plus there are seeds for those. The same applies to mineshafts - even melons come from jungle biomes now. You may find a notch apple, or a diamond chestplate, but those are just supplements - not the ultimate goal.

And Strongholds have locators - which are tedious to get, but you CAN locate them instead of just digging around for a while and hoping you find one (+ the end doesn't have too much anyway no matter what Mojang wants you to think).

However the vast majority of AoA content (or at least the dimensions that people install the mod for in most cases. Do you know anybody who installed AoA so they could train Extraction?) is locked behind the Ancient Teleporter.

When the actually important structure generates underground randomly, rarely, and without any form of locating besides caving and digging for a while and hoping you find one, there's a problem.

**I'm aware that the point is to make sure that you have to mine, or explore, for the Ancient Teleporter.** That's the idea, to make you put effort in. But when the effort is just mining and caving for a while and you don't find it, it doesn't feel rewarding in any way. I'm just trying to make sure that if you mine/cave/explore structures for a while and you don't get the teleporter you can **eventually** craft the locator item.

------------------------

Crafting recipe:

```
R X R
J C J
S X S

R = Rosite Ingot
J = Jade Ingot
S = Sapphire Ingot
X = Carved Rune (any)
C = Compass
```
**HOW IT WORKS:**
The above gives you an unactivated locator, which is like a compass. It points to the location, and may or may not have the location in the tooltip (for immersion purposes maybe it's better to leave it out idk). Right clicking it causes it to point in the location of the nearest teleporter.

**Each locator can ONLY locate one teleporter.** Once you've used it, it "binds" to that teleporter and you can't use it to locate another one. You really shouldn't need to find multiple but if you want to you'd better make sure you go far away from that first one.

The idea here is that if you can't find a ruined teleporter, or you want a truckload of ancient rock for some reason, you can craft this item. However, it requires that you mine a good amount for sapphire, jade, and rosite, and also explore the underground for some carved runes in loot chests.

However, it's optional. If you happen to run into an ancient teleporter by chance like I did, or while digging and caving and mining for hours, then good for you. You don't need to use this, and can put all of your runes to use on the teleporter. This is just for the people who have caved and dug for hours and still not found it, so that they don't have to worry about wasting more hours searching.

Two carved runes are required so you can't just use the bonus chest rune (which is rare anyway). You HAVE to explore at least a little bit. The good thing is that since runes will be more common this will not be nearly as much of an issue, and you are decently likely to get some duplicate runes anyway. Once you've explored enough to get those duplicates you can use it without issue.

Also Focus should be usable to make the locator for the people that have it.

-----

**RECYCLING**:
So, you've found your teleporter. You got your stuff, now what? (Or you binded two locators to the same ancient teleporter, rip.)
Well, you can actually salvage some of the materials you used to make it. I don't know the exact process since crafting tables only have one output slot, but I'm sure there's a way.

But you can "recycle" the locator to get back one of each type of ingot (rosite, jade, sapphire) that you used to craft it. The carved runes/other ingots/compass are lost forever.

The point of the crafting recipe is to make sure that you mined to begin with. If you've crafted the item it means you've mined, and what happens after you craft it doesn't really matter, since you've most likely put in the work necessary to get the item to begin with. You still lose the carved runes/other ingots, but since you know you can get back even just one of the ingots you used to craft it, it ends up not feeling as punishing/a waste.

**Comment by DiamondWalker** [comment]
I like this, and actually thought of suggesting something similar a while back. The only part about it I don't like is the crafting recipe. Here's what I would make:

J  L  J
A RS S
R  F  R

J = Jade/Emerald
L = Limonite/Iron
A = Amethyst/Diamond
RS = Redstone
S = Sapphire/Nether Emberstone
R = Rosite/Nether Quartz
F = Rune of Focus

There's a few reasons why I would prefer this recipe:

It would have redstone in the middle (same as other "pointing" items)
It would give a use to the carved rune of focus
It would more closely represent "conquering the caves", as it would require every ore tier

**Comment by Immortallis1** [comment]
Rune of focus is getting removed from the vanilla loot tables in the next update.

**Comment by DiamondWalker** [comment]
In that case, replace it with runium

**Comment by UnderWaves** [comment]
good idea :)

**Comment by MechanosG** [comment]
I like the idea of this.  I'm currently trying to find a teleporter myself on a multiplayer server.  And I just..  haven't.  I have no idea how to speed up this process.  Maybe mining in a straight line between Y 10-20 and looking for anything to show up on a cave map mod like Journeymap?  Some kind of locating device would be super useful, even if it's something like..  combine an enderpearl with runium/etc, then use it like if you were looking for a stronghold.  Only it moves towards closest Ruined Teleporter instead.

**Comment by Immortallis1** [comment]
@MechanosG currently that's the best way, to mine at Y = 15 until you see an NPC underground using journeymap.

**Comment by Cruuk** [comment]
Fujino wont read this
