### ISSUE TITLE
Replace the eye of ender in carved rune of power recipe

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#4350]
It's a bit silly that you are expected to go to a T1 dimension to get to the other T1 dimensions. It just doesn't make sense. Another issue is that, if you intend to use the AoA portal exclusively, you have to make a vanilla portal, get the blaze powder, and then break it just to make the AoA portal which will likely spawn you at another location.

I think the eye of ender in the recipe should be changed to something else. I suggest an ender pearl, void scale, or echo shard, depending on how hard you want to make it to obtain.

"But you can get the runes through clerics too"

Yes, you can. However, leveling up a cleric to level 5 takes a while, not to mention that you might not get the trade offer from the first villager. If I had to guess, most players will just take the nether route, which, again, doesn't make sense. Also, clerics sell all the other teleporter items, too. If I'm not mistaken, they're supposed to be a backup plan, not the main way of obtaining the portal.

**Comment by Posatasa** [comment]
plz not ehco shard
