### ISSUE TITLE
Underground Biomes compatibility.

### ISSUE THREAD

**Issue by TheWitherlord** [Tslat/Advent-Of-Ascension#436]
Currently the foraging skill does not level up with modded stones like those in the Underground Biomes mod. If there is some integration into the ore dictionary’s stones I would appreciate the ability to level up foraging on those stones.

**Comment by Immortallis1** [comment]
Would be cool to do foraging from quark stone too like marble or limestone, it's somewhat demoralizing to mine and find a large chunk of them.

**Comment by Bradenlawhead** [comment]
Exactly
