### ISSUE TITLE
Melons and Pumpkins don't give farming exp

### ISSUE THREAD

**Issue by VusyBery** [Tslat/Advent-Of-Ascension#4363]
**Mod Version**
3.7.12

This might be intended but I wasn't sure so I thought I might as well put it here

**Comment by Moshanxi** [comment]
Think of Silk Touch. That means you can just stay there destroying and placing down them to obtain skill exps. Cocoa beans could be better to allow to grant exps.
It's not difficult to make it datapackable like extraction_trainable block, but also unnecessary imo

**Comment by Tslat** [comment]
Yeah... too abuseable without too much effort
