### ISSUE TITLE
Remove the recipes of unused/inaccessible items?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#4368]
I know I know. I know you don't like need to do x, but empirically it is a more direct source of confusion that can be seen without spawning things in creative.

The specific problem is viewing the usages of survival-accessible items, only to also see weapons/armor made with other currently-inaccessible materials. Unless you know the mod already, you won't really know what is accessible or not.

I don't want the items to be removed. They're nice for elite boss testing or messing around. If anything you can specifically remove the recipes of inaccessible items made with accessible materials, or just do a broader sweep if that would be too annoying

**Comment by Posatasa** [comment]
If so, how to deal with the items relating to shiny box
