### ISSUE TITLE
Font size and color are hard to see

### ISSUE THREAD

**Issue by uhloin** [Tslat/Advent-Of-Ascension#4369]
**Mod Version**
AoA3-1.20.1-3.7.1-all.jar

**Describe the bug**
Font is white on almost white or dark gray on dark gray.
Font size for Abilities is almost impossible to see even on 1920x1080 screen and GUI size is 2.
Better with bigger GUI size, but other mods (including Patchouli manual) looks better for size 2.
See screenshot.

**Expected behavior**
Use high contrast color scheme, like in Patchouli.
Do not use font size smaller than standard.
Do not use outline font.

For comparison

Most problematic screen:

![image](https://github.com/user-attachments/assets/6a78c747-3a39-40d0-a3c1-8caf0f236fe4)

Patchouli (Lore screen):

![image](https://github.com/user-attachments/assets/da8bd63e-9043-4382-8667-d666d36bb41a)

Patchouli for Botania:

![image](https://github.com/user-attachments/assets/161b517e-7536-424e-a218-3d79d4b63dc8)

Mana and Artifice Book:

![image](https://github.com/user-attachments/assets/dc294103-f43b-46ed-b737-3f635e95e6ef)

Alex's Mobs book:

![image](https://github.com/user-attachments/assets/905b2526-5b25-4374-9f6c-801955d5a27b)

Occultism book:

![image](https://github.com/user-attachments/assets/954658dc-27e0-4b5b-8090-91927f764570)

**Comment by Tslat** [comment]
what's your screen resolution?

**Comment by uhloin** [comment]
1920x1080

**Comment by Tslat** [comment]
Small gui scale maybe?

This is the same window on 1920x1080 auto for me

![image](https://github.com/user-attachments/assets/2f9c4db5-73e7-4150-bcab-037f8c83d821)

Maybe I just need to disable gui scaling for it

**Comment by uhloin** [comment]
As I wrote, GUI scale is 2. And you can see from comparison, how other mods look with the same scale 2. Problem is not only size of font, but also color scheme and outlining. For example, string "Xp Remaining" is big enough, but hard to read.

**Comment by Tslat** [comment]
Yeah it's multifaceted

In the meantime, you can change themes in the gui help tab
