### ISSUE TITLE
A lake feature in Precasia crashes the game when loaded?

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#4375]
It says "lake" in the log so I presume it's something related to a lake

https://paste.gg/p/anonymous/137dd374f0d1406593f6897b1f8c672b

**Comment by Posatasa** [comment]
similar to mine
https://github.com/Tslat/Advent-Of-Ascension/issues/4333

**Comment by Tslat** [comment]
Well this is concerning

LakeFeature is a vanilla feature, with no configuration for size
That makes this a vanilla bug lol

**Comment by Tslat** [comment]
Does anyone have a seed and rough coords for when this happens?

**Comment by Posatasa** [comment]
I've given a seed in my previous issue
it's 81108640, about X:-300, Z:100~200

I just tp to nearest precasian desert, but the lake should in the adjacent jungle

**Comment by Cruuk** [comment]
> Does anyone have a seed and rough coords for when this happens?

Seed: 7524527481874024656

Go to -3051, 62, 339 in Precasia, then head straight north across the ocean, roughly for 300-500 blocks. If you see a sandy landmass that's a little high up, that should be where the crash happens

**Comment by Tslat** [comment]
This is really weird

Definitely a vanilla crash, but I'm not sure why it's happening here
