### ISSUE TITLE
The mechanics for Advent's variant of the nether portal.

### ISSUE THREAD

**Issue by Sarus-X** [Tslat/Advent-Of-Ascension#4376]
**Mod Version**
1.16.5-3.6.11
**Describe the bug**
Going through Advent's nether portal forcefully pushes you either away from the portal (basically flinging you) or back into the portal sending you back to the overworld almost instantaneously. You can crouch and back up through the portal to sometimes stop it from instantly sending you back to the overworld, but this often just spawns you inside the blocks surrounding the portal and causes the "flinging" problem to occur.
**To Reproduce**
Just walk into the portal from the mod for the instant teleport, or crouch backwards for it to fling you. There is no way to "normally" walk through the nether portal without a problem.
**Expected behavior**
Not being flung into a random direction or being sent back instantly after walking through the portal.
**Screenshots**
I don't think a screenshot would be helpful as this is a bug with the portal mechanics.

**Comment by Tslat** [comment]
Weird, I've never heard of this, nor experienced it myself
