### ISSUE TITLE
Blasters keep firing when switching to spectator mode

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4379]
Begin using a blaster, then press F3+N to switch to spectator mode, it's still firing and losing durabilty.
![2024-09-03_22 51 28](https://github.com/user-attachments/assets/5892488d-7490-4f6e-92d6-6fd531272658)

**Comment by Tslat** [comment]
lol

**Comment by Tslat** [comment]
wtf...

This only works with f3+n

If you switch it via command or f3+f4, it stops it

**Comment by Tslat** [comment]
This is a vanilla bug, and affects all items and weapons

Patching it may have adverse affects on other mods, so I'm gonna leave it

Report it to [mojira](https://bugs.mojang.com/projects/MC) if you want
