### ISSUE TITLE
OBSAOA for 1.12.2

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#438]
**Describe the new feature you think would be good to add**
I want to have the goal to collect all of the weapons in 1.12.2 just like I did in 1.7.10.

**Add any alternative implementations you think might work**
Give detail about the weapon in the achievements tab in the menu, and add which bosses I should fight in order, and give achievements following on which dimensions I should visit in order, which structures to visit, and add some challenging side quest achievements! (Like the Questing Ram in Twilight Forest).

**Include any additional background information**
Obsaoa already exists, but I would like for you to improve it a little bit. You don't have to add any blocks, you don't have to add anything physical at all, (blocks, mobs, etc.) I would like achievements following the questing side of the mod.

**Comment by Tslat** [comment]
This is more of an advancements request, which has already been confirmed to be coming in time
