### ISSUE TITLE
Extraction bonus

### ISSUE THREAD

**Issue by Sarus-X** [Tslat/Advent-Of-Ascension#4385]
**Mod Version**
1.16.5-1.4.1

**Describe the bug**
The extraction bonus skill (level 16+) often takes away the bonus material(s) or grants an extra one after it has already been placed in the inventory.

**To Reproduce**
After reaching extraction level 16, place a stack of something to smelt and take out the products one at a time. Place it in your inventory and pick it back up. Sometimes the item's stack count will change after being picked back up.

**Expected behavior**
To keep the amount of the product the extraction bonus gives me, and to not update again after being placed/taken from the player inventory.

**Screenshots**
![Before](https://github.com/user-attachments/assets/37095378-46b3-425c-bc9b-514395a71ff5)
![After](https://github.com/user-attachments/assets/e9ce8b2f-2038-4d4a-a07c-dad46efb7a6f)

**Comment by Tslat** [comment]
Yeah the furnace system is very weird, and there's a bug in forge causing problems

Unfortunately 1.16.5 is a dated version, so there's not a lot to be done there
