### ISSUE TITLE
If you enter boss lobby using a boss totem item AFTER having Nowhere hub unlocked, going through the hub's exit portal takes you to 0, 0

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#4388]
I think you have to initiate a boss fight as well? Not sure. This doesn't happen if you enter Nowhere from the portal.

And also this doesn't happen when you don't have Nowhere hub unlocked. Seems fine there

**Comment by Tslat** [comment]
I swear I fixed this

**Comment by Tslat** [comment]
Can't replicate on current build in dev
