### ISSUE TITLE
Special mobs that only spawn when it's raining

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#439]
**Describe the new feature you think would be good to add**
Something that always interested me was the concept of mobs that could only spawn while it's raining. To be honest my main inspiration was Lycanites mobs, I think they have rain mobs...
This wouldn't really be a traditional event, it wouldn't be announced in chat. It would just happen any time while it's raining.

---------------------------
__**Mobs**__
Mobs that spawn while it's raining generally wouldn't be very strong, since it can rain anytime.
Rain mobs would be able to spawn anywhere where it can rain, meaning that they will not spawn in places with no rain like the underground, desert, etc. They will also still follow mob spawning rules like not spawning on man-made blocks and stuff.
The mobs would be common, but not common enough to overtake the regular mobs in terms of amount, they would be more like event mobs in terms of the amount. Also similar to event mobs Rain mobs have an increased chance to despawn if it's not raining (not 100% sure if this is true).
Even if it can rain in another dimension, these mobs would only spawn in the Overworld.

**Morph Blob**
A slime-like mob. It looks like a Slime but without a face and the body resembling water in terms of color and texture. Like a Slime, it would split into smaller pieces when killed, and is the same size as a Slime. When jumping it could also expose it's "core" a bit like the Magma Cube does.
Varying sizes of Morph Blobs could spawn in general.
__HP__: 28 (Big), 7 (Small), 2 (Tiny)
__Armor__: 8 (Big), 4 (Small), 2 (Tiny) (For reference a Zombie has 2 armor)
__Attack__: 7 (Big), 5 (Small), 4 (Tiny)
__Drops__: Sentient Rain Drop (1-1, 25%, dropped by big/small sizes only)
__Experience points__: 4 (Big), 2 (Small), 1 (Tiny)
It gives Slowness I for 2 seconds upon hitting a player. The tiny size does not give slowness.
While it acts very similar to a Slime, it still has some unique qualities.
If a Morph Blob jumps into a pool of lava, it will turn the lava into Obsidian upon contact, similar to how the Frost Walker enchantment turns water into ice upon contact.
If a Morph Blob is in contact with rain or a body of water, it will gain a minor regen effect, very similar to Regeneration II.
It has the same speed as a Slime, but it can move slightly faster in water than a Slime.
It has the attribute of fire resistance.

**Spoutux**
A flying ranged mob that resembles a Spinux, with the main differences being that it holds a staff, and that it has no legs. Instead of legs it has a little waterspout under it spinning around as it flies around in the sky.
__HP__: 24
__Armor__: 0
__Attack__: 4
__Drops__: Sentient Rain Drop (1-1, 33%)
__Experience points__: 5
In terms of abilities, it's pretty simple. It flies around and can shoot blue magic projectiles affected by gravity. The projectiles give Slowness I for 2 seconds on hit.

Rain will also allow the **Spinux** to spawn in more places besides the beach (other than places where it doesn't rain). It is still the same mob though, other than having a 33% chance to drop 1 Sentient Rain Drop while it's raining. (is that possible?)

Rain mobs would also spawn during snow storms in certain biomes and thunderstorms.
They are unchanged in thunderstorms, other than being able to spawn more often?
In snow storms, Morph Blobs and Spoutuxes would give slowness II instead of I and it would last for 3 seconds instead of 2. Spinux gives no slowness though.

**Nimbus** [Rare mob]
A flying melee mob that can only spawn during a thunderstorm. It resembles a small dark gray thundercloud with 4 eyes. The eyes would be aligned in a similar fashion to a Flye, along with being a similar size to a Flye. There would also be a couple small lightning bolts sticking out of it. The lightning bolts could also glow in the dark?
__HP__: 40
__Armor__: 0
__Attack__: 7
__Drops__: Sentient Rain Drop (2-4, 100%), Energy Rune (4-8, 66%), Silver Coin (1-1, 100%)
__Experience points__: 12
I'm not sure if it's possible, but it should be faster than other flying mobs, like 50% faster.
Similar to a Voltron, when a Nimbus hits you, lightning will strike.
Nimbus has the attributes of fire and Blaster immunity, along with being healed by lightning if it is somehow hit by it. (is healed 10 hp)
Considering that thunderstorms are already pretty rare, the Nimbus wouldn't be as rare as other rare mobs.

__**Content**__
As you've seen, each mob can drop "Sentient Rain Drops", this is the main item you can get during rain storms.
To be honest, I'm not exactly sure on what they could be used for, so here are some ideas:

-Combining Sentient Rain Drops with Bubble berries could give "enhanced versions" (whether it be a new item or the same one with the enchantment glow over it), that mainly give 1-2 more bubbles that regular Bubble berries.

-Putting an empty bucket and 3 Sentient Rain Drops in a crafting table gives you a water bucket (you wouldn't get the empty bucket back, as the result is still the bucket but with water). The same happens with empty bottles as well.

-Right clicking an empty Teasink with a Sentient rain drop fills it up, but you would only be able to use the teasink once before it's empty again. (a water bucket allows you to use it 3 times I believe)

-Trading materials for the Troll trader? It can be a way to give him more trades without using Amphibiyte lungs again.

-Something to do with the Alchemy skill....?

Not all these methods have to be considered, these are just me spitballing ideas on what they could be used for.

--------------------------------
I think it could be an interesting way to add more earlygame content in the form of an "event" that doesn't have overly strong mobs, just something that allows players to take advantage of things like the Sentient Rain drops being used to enhance Bubble Berries, an alternative to filling buckets with water, etc. etc.

**Comment by Immortallis1** [comment]
+1
almost downvoted because flyes are the most annoying s**t ever and should be renamed "armor breaker"
