### ISSUE TITLE
1.20.1 Mobs still don't have ai while using with smartbrainlib

### ISSUE THREAD

**Issue by 5A93** [Tslat/Advent-Of-Ascension#4391]
**Mod Version**
What version of the mod are you on?
AoA3-1.20.1-3.7.1，SmartBrainLib-neoforge-1.20.1-1.15
**Describe the bug**
None of mobs have ai
**To Reproduce**
Steps to reproduce the behaviour:
1. Download these two version of mods
2. Start the game

It's probably caused by wrong version of both side, please tell me which version exactly should I use.

**Comment by Tslat** [comment]
Downgrade forge to 47.1.3, or use the latest sbl for forge 1.20.1
