### ISSUE TITLE
Make Ender Dragon AoA drops spawn in the player's inventory by one who killed it.

### ISSUE THREAD

**Issue by TripleThreeT** [Tslat/Advent-Of-Ascension#4393]
Ender Dragon loot has the ability to drop on the portal, but due to the fact that the portal doesn't spawn until after the death animation, the drops can actually spawn underneath the portal. This makes it especially hard to get, so maybe the loot should just spawn in the player who killed its inventory.

**Comment by Tslat** [comment]
This is surprisingly invasive to implement for something so specific and niche, even if it is annoying

Sorry
