### ISSUE TITLE
Slightly reduce the number of lava lakes & springs of Precasia underground

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4394]
Considering there are many trees underground, now it's burning everywhere, it may cause lagging.

This screenshot is just an example, not very far, there are three big burning areas.
<img width="960" alt="2024-09-16_01 18 05" src="https://github.com/user-attachments/assets/ee0bd3cf-2be4-413f-86bc-85f8efad4d7f">

The fire is also very big.
![2024-09-16_01 16 53](https://github.com/user-attachments/assets/821a87b9-5536-4a8b-89de-a3e6019a5552)

**Comment by Tslat** [comment]
Benchmarking doesn't show any noticeable impact from this
