### ISSUE TITLE
max health became 50 after death

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4397]
3.7.13

![2024-09-21_13 24 42](https://github.com/user-attachments/assets/a41ff431-8a69-4f7a-a31b-5db94469b2da)

**Comment by schindlershadow** [comment]
also getting this on 3.7.13

**Comment by schindlershadow** [comment]
this might help 
![image](https://github.com/user-attachments/assets/71ad01f9-01c7-4562-9260-c642a8cf56ad)
