### ISSUE TITLE
[BUG] farming skill does not get xp gain with right-click farming mods

### ISSUE THREAD

**Issue by schindlershadow** [Tslat/Advent-Of-Ascension#4419]
**Mod Version**
AoA3-1.21.1-3.7.12.jar

**Describe the bug**
farming skill does not get xp gain with right-click farming mods for example quickrightclick-1.21.1-1.5.jar

**To Reproduce**
Steps to reproduce the behaviour:
1. have right click farming mod installed
2. right click on grown crop

**Expected behavior**
right clicking crop should give farming xp

modlist
https://pastebin.com/raw/kSQNMzd2

**Comment by Rain-Flying** [comment]
Many mod with **'right-click harvesting'** doesn't trigger the **'break block'** event. Without the event, your **'harvest'** behaviour can't be noticed by AoA3, so you won't get any Farming Exp.
If solving this is wanted, AoA3 will definitely add many integrations with other Right-Click-Harvest mods (such as FTB Ultimine). This is a very huge task...

**Comment by Tslat** [comment]
^ This

If the mod doesn't trigger the correct events, then I can't do much about this
