### ISSUE TITLE
Current state of the primordial armor

### ISSUE THREAD

**Issue by lmdeadinside** [Tslat/Advent-Of-Ascension#442]
3.0.2

Currently full primordial armor gives you immunity to wither effect. In my opinion this shouldn't be the set bonus. Primordial five is a rather difficult battle and I feel like killing the boss isn't as rewarding as it used to be. I mean you can get wither armor pretty early in the game and it gives you the same set bonus which makes primordial armor useless. I get that the 33% chance to dodge enemy attacks we had before was a little too op. So this is what I'm suggesting.

New primordial armour- Should give 10-15% chance to dodge enemy attacks and the wither immunity effect. This buff would make the armor worth something and make the primordial five more rewarding to kill.

Let me know what you think.

**Comment by Sagisolar** [comment]
Yeah to be honest it shouldn't of been nerfed in snapshot 10. It was changed due to a myth that it was "Outclassed" by the Innervation armor. Despite having 25 protection while the Innervation only has 20. I going to assume the Toughness of armors are placeholders for now

However its not useless because of the Wither Armors existence because that armor has lower protection at 20 protection.

**Comment by Cruuk** [comment]
Honestly I like the direction it's going in, being an upgrade to Wither armor in the same way Ghastly armor is an an upgrade to Poison armor. (And Nethengeic being an upgrade to Embrodium/Infernal)

However, I do agree that it could have a minor buff. It only has the Wither immunity while Ghastly has the poison immunity + more. Both sets even have 1 less armor than sets usually do at that point (Ghastly has 22 armor when sets usually at that point have 23 to compensate for it's abilities, and Primordial has 25 armor when sets at that point armor sets have 26 armor).

I already did try coming up with a second ability for it in this git thread here a while back. I don't think Scimi wants to add back the dodge chance so I tried being original, something to *sort of* reflect the P5 boss fight as well.
https://github.com/Tslat/Advent-Of-Ascension/issues/243

**Comment by lmdeadinside** [comment]
After reading your comments the dodging chance change I suggested is still too op. And we have the intervention armor which already gives you that 25% dodging chance so I guess adding it back to primordial armor isn't necessary. 

And about the primordial armor giving 25 protection vs wither giving 20 was me being ignorant. So yeah primordial armor isn't useless but I'd still like it to have an unique set bonus. I really liked the suggestion in #243

**Comment by Tslat** [comment]
3.2 Did things
