### ISSUE TITLE
About guardian

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4420]
3.7.13

In data/aoa3/loot_modifiers/guardian_biogenic_armour.json, the table's name is "aoa3:entities/vanilla_guardian"
![image](https://github.com/user-attachments/assets/6b35cdc0-f936-467b-a860-54609d32554e)

But the actual name of the table in data/aoa3/loot_table/entities is "guardian"
![image](https://github.com/user-attachments/assets/46a1b9d0-fe15-4745-bb32-2850487aaf5e)

Their names are not accordant, and looks like it makes guardians drop no biogenic armors.

I used a datapack to change the table name in the loot modifier, then they drops the armor.

**Comment by Cruuk** [comment]
Wonder how long it's been like this
