### ISSUE TITLE
Advent of Ascension and the 4 items after death.

### ISSUE THREAD

**Issue by CrazyBananaDisco** [Tslat/Advent-Of-Ascension#4429]
So I have a problem with this version of the mod Nevermine-Tslat-1.1.2.jar 1.7.10.
I realized that on survival, once you die, the items remain in your inventory, but only the first 4 items, every time you die. Is it intended? How do I disable it?
I thought it was from another mod, but once I put it with other mods that spawn me in the world with books in hand and die once or as many times as I want, I respawn with the books in hand.

![2024-10-19_13 17 11](https://github.com/user-attachments/assets/58d82beb-c809-446e-9b68-30b9ccacb033)
![2024-10-19_13 17 20](https://github.com/user-attachments/assets/a9109d9a-65aa-40cd-8257-9ff28af9ef00)
![2024-10-19_13 17 23](https://github.com/user-attachments/assets/9dfd14d3-fbb2-461b-a489-e466bc52ed6e)

In these screenshots, only the aoa and opencomputers modes appear, thinking it's from another mod, but doing tests it's because of aoa and I don't know what causes it?

![2024-10-19_13 24 40](https://github.com/user-attachments/assets/bd1dda44-2d9c-4055-a836-ffc0f87184ac)
![2024-10-19_13 24 42](https://github.com/user-attachments/assets/7c3d7c7e-69d3-4bc0-b946-432d39aa4d72)
![2024-10-19_13 24 57](https://github.com/user-attachments/assets/25bda73d-fe2a-43d2-8581-f21e16b46940)
![2024-10-19_13 24 59](https://github.com/user-attachments/assets/1e198f2a-e6e3-43ad-a922-7987df722d78)

Is it because of the sign on the top right with the skull wrapped in blood?

**Comment by Tslat** [comment]
Not sure, I don't know of anything in 1.7.10 aoa that would do that off the top of my head

How do you know it's not some other mod
