### ISSUE TITLE
Nethengeic armor can't deal extra damage to players

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4433]
In the video, the damage is always the original damage, no matter who is on fire.

https://github.com/user-attachments/assets/7c75eb64-c160-409a-a992-41c671b0ee90

This only happens when the target is a player

**Comment by Tslat** [comment]
Retry this in the next version
I completely redid the event handler system for AoA, and it might have fixed this

**Comment by Posatasa** [comment]
okay
