### ISSUE TITLE
Attack animations for melee mobs such as Giants

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#444]
Certain golem-like mobs such as Giants, Tree Spirits and Automatons should have similar attack animations as vanilla iron golems, where they swing both of their arms upwards at the same time. Giants and Tree Spirits currently walk into the player and deal upwards knockback without a visual indication, which may be confusing for some players. Having giants swing their arms may also explain their "large reach" better since you can physically see their arms swinging over a large distance.

Other mobs with arms (such as Warclops, Headless Destroyers and Celeve clowns) could have an attacking animation where they swing one of their arms forwards, or make a punching motion similar to the player or enderman. Apparitions and Fades could swing their arms upwards like zombies and Wither skeletons.

**Comment by Immortallis1** [comment]
Bobo/Tree Spirits needs this really badly

**Comment by Tslat** [comment]
Let's be honest - many mobs need this badly lol

**Comment by DiamondWalker** [comment]
Funny thing is I always though giants already had this, despite seeing them attack me and not do it several times.

**Comment by Immortallis1** [comment]
> 
> 
> Funny thing is I always though giants already had this, despite seeing them attack me and not do it several times.

Their legs flail so much. It's only natural you'd think that
