### ISSUE TITLE
Seems burned effect doesn't work?

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4442]
The damage didn't change.

![2024-11-15_22 35 30](https://github.com/user-attachments/assets/3523115c-11e8-4813-830c-28c856ff2d1c)
![2024-11-15_22 36 13](https://github.com/user-attachments/assets/d626fe18-724a-4954-b29d-32b1874b4035)

**Comment by Tslat** [comment]
Can't fix without NeoForge bug fix =/

https://github.com/neoforged/NeoForge/issues/1691

**Comment by Tslat** [comment]
NeoForge has fixed this in 1.21.3, but hasn't backported it =/ 
it'll be fixed in newer versions I guess
