### ISSUE TITLE
Increase petal drop rate but increase the ammount needed for petal pile

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#445]
Currently, it is extremely hard to get Rosidian armor. This is due to the fact that the petals are such a rare drop (2.5%). I think they should be increased to a 50% drop rate, but the petal pile should require 40 of each kind instead of one. When you do the math, the same amount of average kills would be needed (except it would be less luck based).

**Comment by Tslat** [comment]
This has changed in 3.2
