### ISSUE TITLE
Missing Fence Gate Tag

### ISSUE THREAD

**Issue by TheBedrockMaster** [Tslat/Advent-Of-Ascension#4451]
**Describe the change or feature you think would be good to see**
Add the `minecraft:fence_gates` item and block tags to fence gates in the mod.

**Comment by Tslat** [comment]
Sigh...
Why is there a duplicate `c` tag for this -.-

**Comment by TheBedrockMaster** [comment]
That's a good question 🤣

**Comment by TheBedrockMaster** [comment]
I saw this got added in 3.7.14, this can be closed as completed.

**Comment by TheBedrockMaster** [comment]
@Tslat I saw this got added in 3.7.14, this can be closed as completed.
