### ISSUE TITLE
New Primordial Armor ability

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#446]
I've seen a lot of posts suggesting primordial armor buffs... so I'll make my own.

The issue I've seen with these suggestions is that they are mostly just combining two armors into one. I think primordial should be special, since it's such a late-game armor. My suggestion is to give it a teleportation ability. To teleport, you would have to press the crouch and sprint buttons at the same time. Doing this will fire an invisible projectile in the direction you are looking. This projectile would be very fast (about as fast as sniper bullets), and would leave a black trail. When this projectile hits something, you will teleport to the impact zone (similar to ender pearls). When you teleport, there's a 30 second timer until you can teleport again. If you're under 50% health, the timer is decreased to 15 seconds, and below 25% health, the timer is decreased to 5 seconds.

**Comment by UnderWaves** [comment]
That's a good idea. But idk if that's easy to code...

**Comment by DiamondWalker** [comment]
I don't think it'd be too hard, since other item already have similar effects. The teleporting is already done by the Shyre staff, one of the Creeponia armors already fires projectiles, key combinations activating an ability is used by the Sealord diving helmet, and abilities becoming stronger depending on your health is already part of the Lyon/Phantasmal armor sets.
