### ISSUE TITLE
Death issue

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4464]
1. Death
2. When at "you dead" screen, the resouces adds up to random value.
3. Respawn, the resouces stop regenatation.
4. Do something (e.g., placing or break a block) to update the player, then:
    1) resouces become zero and then begin regening
    2) the skill levels and xp are cleaned up
    3) the selected item of auto harvesting trash was cleaned

https://github.com/user-attachments/assets/d9f7fd46-d939-441a-af50-0610fb8034f8

https://github.com/user-attachments/assets/a6a30c78-1847-4f84-ae0c-4ab68444b8ee

**Comment by Posatasa** [comment]
This bug is very serious. Also TV has submitted the textures, so if possible I hope there will be a hot fix after fixing this issue and issue of charging staff

**Comment by Rain-Flying** [comment]
@Tslat  Many abilities which need to load parameters from NBT also can't work properly.
Parameters can't be load into abilities. For example, the Auto Harvesting Trash ability will lost the parameter 'which item to consume' after death.
