### ISSUE TITLE
torn page issue happens again

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4465]
About "Lore" in advent GUI

It's really confusing. But it's also affected by death, so I guess this issue and https://github.com/Tslat/Advent-Of-Ascension/issues/4464 may have same reason.

The acutal things are very messy, I can't exact know the true situation, belows are only some phenomenon as tested:
1. Join the world, read the torn page, it will appear in GUI. But if you do things like run commands, open advent GUI, or die, before reading the page, it won't appear in GUI. Sometimes after one death, readed torn page still appear, but after two death, it won't appear.
2. Die, the readed torn pages won't disapper in GUI immediately, but if you quit the game then re-join the game, it will disappear. Quit without death won't cause disapper maybe.
3. Sometimes, I die, then read the page again, then quit and re-join, the page won't disapper in GUI.

**Comment by ryanalmeida271017-ui** [comment]
H
