### ISSUE TITLE
AoA explosion particles randomly don't appear

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#4466]
I suspect it has to do with the particles AoA guns/etc. now create when hitting a block. The explosive particles still appear, but it's 50/50 when they do. Not sure if how far you are from the particles also has anything to do with it

**Comment by Tslat** [comment]
🤔 
What's guns got to do with it?

**Comment by Cruuk** [comment]
> 🤔 What's guns got to do with it?

<code>Added some block impact particles for bullets</code>

I'm just guessing that's causing it, because I don't remember this happening before the update. Grenade/RPG also create those particles when hitting blocks

**Comment by Tslat** [comment]
It shouldn't.. but yeah ok
So this is more specific about grenade/rpg?

**Comment by Cruuk** [comment]
> It shouldn't.. but yeah ok So this is more specific about grenade/rpg?

Also checked a couple inaccessible explosive weapons, I.E. ones that still use vanilla explosions, and it happens with them too
