### ISSUE TITLE
1.20.1 aI NOT WORKING

### ISSUE THREAD

**Issue by riddledgem51077** [Tslat/Advent-Of-Ascension#4469]
1,20,1
i am experiencing the issue of mobs not moving at all and it is only aoa mobs. i dont know if they is becuase its unfinished or if its bugged, if its becuase its unfinished why cant you just port the old version into the new version we dont really care if the textures are good or not. please let me know how to fix the ai of the mobs

**Comment by Posatasa** [comment]
install a smartbrainlib
