### ISSUE TITLE
Amphibiyte Cave Remake

### ISSUE THREAD

**Issue by Infernikko** [Tslat/Advent-Of-Ascension#448]
**So I rebuilt the amphibiyte cave structure, and thought it could be fun to try and get it in the mod because the original is a boring blue box**
I don't know what file type is used for structures (probably schematic) but I could probably just send them in a DM in Discord or something.
As for the chest, I haven't thought of a loot table for it yet, but perhaps it could include a few bit of hauling/fishing things.
![2019-03-07_21 52 55](https://user-images.githubusercontent.com/41617467/53992770-96234500-4125-11e9-812c-887649f6ff91.png)
_The cave on its own from the outside_
![2019-03-07_21 53 02](https://user-images.githubusercontent.com/41617467/53992791-a5a28e00-4125-11e9-9e94-6831f1eff024.png)
_Inside of the cave_
![2019-03-07_21 50 52](https://user-images.githubusercontent.com/41617467/53992807-af2bf600-4125-11e9-9473-7f3a48dffd3a.png)
_I just plonked it underwater to see how it looked_

Probably could've been formatted better but it gets the point across
ok bye

**Comment by Infernikko** [comment]
help i thought i added the tag

**Comment by DiamondWalker** [comment]
I like it. The only thing I would change is the blocks. I think the bricks currently used are better, and for lamps, maybe new, red lamps. Keep in mind Guardians and Amphibiytes are complete unrelated water creature, so there isn't much of a reason for the Amphibiyte caves to be made of prismarine.

I would also remove the chest. A chest underwater doesn't make too much sense.

**Comment by Sagisolar** [comment]
> I would also remove the chest. A chest underwater doesn't make too much sense.

In 1.13 treasure maps can be found in sunken ships. The map guides the player to a **Chest** underwater.

**Comment by DiamondWalker** [comment]
> 
> 
> > I would also remove the chest. A chest underwater doesn't make too much sense.
> 
> In 1.13 treasure maps can be found in sunken ships. The map guides the player to a **Chest** underwater.

ik, but the treasure maps are buried under the sand, not in the water. The ruins and ships having them makes sense, since those structures were originally on the surface but sunk, chest included. What I don't get is a chest being purposely placed in an underwater dungeon.

**Comment by Infernikko** [comment]
I'll definitely change the bricks
As for the chest, gameplay > realism, finding loot is fun
I mean I never saw the Sasquatch I killed carrying a gun, or the tree spirit carrying copper coins
