### ISSUE TITLE
Rename some greatblades

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#4480]
Many greatblades don't look like swords at all, and have only kept that name from the olden days. Specifically, I think these should be renamed:

Creepoid Greatblade
Lelyetian Greatblade
Underworld Greatblade
Candy Blade
Lyonic Greatblade
Noxious Greatblade
Shroomic Greatblade
Primordial Greatblade

Possible ideas for other things they could be called include "Greataxe", "Spear" or "Glaive".

**Comment by Cruuk** [comment]
Shyre sword (GB) and candy blade already break the naming scheme, so it probably wouldn't hurt. Maybe all of them can have "great" as the 2nd word's 1st syllable

**Comment by DiamondWalker** [comment]
> Shyre sword (GB) and candy blade already break the naming scheme, so it probably wouldn't hurt. Maybe all of them can have "great" as the 2nd word's 1st syllable

I thought about that, but I can't think of any words with "Great" that would accurately describe the Lelyetian, Underworld, Noxious, or Primoridal ones.

**Comment by Tslat** [comment]
Yeah alright
