### ISSUE TITLE
Craexxeus Tower Remake

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#449]
Craexxeus Tower isn't horrible like some of the other boss structures but its kinda underwhelming since all you do is climb up stairs then place some blocks down to get to another staircase.

However, since I ~have to much free time~ love building for stuff. I made a remake.

Before
![2019-03-07_22 28 58](https://user-images.githubusercontent.com/44548547/53995467-04b7d100-412d-11e9-91e9-1b413c182473.png)

After
![2019-03-07_20 11 25](https://user-images.githubusercontent.com/44548547/53995480-0bdedf00-412d-11e9-802c-8a4d010d50cd.png)

This remake is 109 blocks high, making the 2nd tallest behind Sky Lotto Flower.

This structure is now way more interesting due to the many floors that have mobs ready to fight.

1st floor is empty so none of the mobs interact with you while your casually strolling by.

2nd floor
![2019-03-07_23 04 26](https://user-images.githubusercontent.com/44548547/53995690-b820c580-412d-11e9-8155-74dc58df0fb7.png)

3rd floor
![2019-03-07_23 04 37](https://user-images.githubusercontent.com/44548547/53995724-ddadcf00-412d-11e9-9920-3a82a4253920.png)

4th floor (Note: I couldn't get mob spawners to work here and above for some reason, these are Soulscorne spawners)
![2019-03-07_23 05 07](https://user-images.githubusercontent.com/44548547/53995736-e7373700-412d-11e9-8199-8c7507ad79a0.png)

Now the 5th floor changes it up a bit. Now there are 4 paths all are the same but they have loot on them. Omnilight spawn here so watch out.
![2019-03-07_23 05 26](https://user-images.githubusercontent.com/44548547/53995787-1cdc2000-412e-11e9-9285-66306db22c98.png)

![2019-03-07_23 05 21](https://user-images.githubusercontent.com/44548547/53995793-21a0d400-412e-11e9-9d34-02e8d6a798be.png)

Then finally Craexxeus' room.
![2019-03-07_23 05 35](https://user-images.githubusercontent.com/44548547/53995853-56ad2680-412e-11e9-90b8-104f43b024fe.png)

**Comment by DiamondWalker** [comment]
YES. Only problem I can see is the Shyreland's wind knocking you off the stair and the Arc~~worms~~ wizards being a high level hunter mob.

**Comment by Immortallis1** [comment]
the structure is a decoy, the real purpose of this suggestion is to make lightwalkers spawn aboveground

**Comment by Sagisolar** [comment]
> 
> 
> the structure is a decoy, the real purpose of this suggestion is to make lightwalkers spawn aboveground

gamer guy
