### ISSUE TITLE
Crashing upon startup

### ISSUE THREAD

**Issue by RogueLighttt** [Tslat/Advent-Of-Ascension#4492]
**Mod Version**
What version of the mod are you on?
3.7.15
**Describe the bug**
When loading up the game seems to crash I believe its an incompatibility issue but not sure how to resolve

**Expected behavior**
To boot up and load correctly

MCLO: 
https://mclo.gs/RW3kD2x

**Comment by Tslat** [comment]
It's fuelgoeshere

It's known to conflict with mods

I'm closing this one because this issue has already been raised, and it's ongoing

**Comment by TheBedrockMaster** [comment]
This was fixed on fuelgoeshere's end.
