### ISSUE TITLE
Lottoman - Jade Mod Compat

### ISSUE THREAD

**Issue by TheBedrockMaster** [Tslat/Advent-Of-Ascension#4494]
**Mod Version**
1.21.1 - 3.7.15

**The Bug and how to Reproduce**
Have the mod "Jade" downloaded and look at the Lottoman, under the name of the entity, the part where it would show the job on regular villagers just shows a lang entry.

**Expected behaviour**
I assume it should say "Wanderer - Novice" or just "Novice" or something similar.

**Screenshot**
![2024-12-18_09 04 54](https://github.com/user-attachments/assets/82696289-5afb-404c-9f6d-274d3aa27511)

**Comment by Tslat** [comment]
That's weird I thought I did this already 🤔
