### ISSUE TITLE
Maybe adjust the mechanic of consuming ammo?

### ISSUE THREAD

**Issue by Posatasa** [Tslat/Advent-Of-Ascension#4499]
I know this won't appear at normal situation, so just ignore this issue if you think it doesn't matter.

`  "effects": {
    "aoa3:ammo_cost": [
      {
        "effect": {
          "type": "minecraft:remove_binomial",
          "chance": {
            "type": "minecraft:linear",
            "base": 0.05,
            "per_level_above_first": 0.05
          }
        }
      }
    ]
  },`

I made this enchantment for guns to have a chance not consuming ammos. **Then, I found this enchantment makes guns still firing when there're no ammos in my inventory.**
I'm not sure if it's what  remove_bionomial should be, or can slightly change the code of guns to avoid.

**Comment by Tslat** [comment]
?

If you make the cost 0, the gun won't require ammo to fire

**Comment by Posatasa** [comment]
ohh 
I don't know exactly how this works
