### ISSUE TITLE
Realmstones for 2.5 dimensions

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#450]
I know the 2.5 dimensions won't be coming for a while, but I posted this ~~to assert dominance~~ so I don't forget.

Everlands realmstone:
Would be bought for dungeon tokens from one of the Immortallis NPCs. There are a few reasons why I would choose the obtaining method: 

It would be unique (no other realmstones are bought)

It would make Immortalis more worthwhile (currently the only important item there are vulcanes, which are rarely used anyways)

It would continue the chain of co-ruled dimensions

It would fit the theme (the immoralis NPCs already sell Ever-stuff)

It would (probably) be balanced (based on the fact the Evercron in 2.5 was around the same tier as immortalis gear).

Etherus realmstone:
Would be obtained from killing enemies in the buffed Soul Scurry event. The buffed Soul Scurry event would be unlocked by using a special soul-themed item. The item would have this crafting recipe:

G  PG  G
P   M   P
G  PG  G

G = Ghoulish Ingot
PG = Primed Ghoulasm
P = Phantasm
M = Mystite Ingot

During a Soul Scurry, using this item will cause it to be buffed, meaning all ghostly enemies will have higher spawn rates, higher stats, and drop Etherus Realmstones.

Playtopia Realmstone:
This one is a bit tricky. The obvious solution would be something in Celeve, but that would only add another dimension branch, not finish the Celeve one. Candyland would finish the "fun" branch, but wouldn't make much sense (what do candy and toys have in common? Only thing I can think of is a circus, but that only makes them related to Celeve, not each other). I think the best solution would be making the Playtopia realmstone drop in the overworld (maybe dark moon?), and move Celeve's realmstone to drop in Playtopia.

**Comment by Immortallis1** [comment]
What's wrong with adding more branches?

**Comment by DiamondWalker** [comment]
The thing is dimension progression is already too messy and has way too many branches. It isn't really too big of a problem now, but I think future dimensions should avoid adding to it before it becomes an actual problem.

Also, why add another branch when there's already another solution?

**Comment by Tslat** [comment]
Realmstone obtaining has changed in 3.2
