### ISSUE TITLE
Remove the Metal Rods Tag

### ISSUE THREAD

**Issue by TheBedrockMaster** [Tslat/Advent-Of-Ascension#4501]
**Describe the change or feature you think would be good to see**
Currently Limonite Rods have the `c:rods/metal` tag which isn't used by other mods. Recipes that use Limonite rods use this tag so they would also need to be changed. If you still want those recipes to use any metal rods and not just limonite rods, you should add a new tag like `aoa:metal_rods` for example, that contains different metal rod tags like `c:rods/iron`, etc.

**Comment by Tslat** [comment]
Nah

It's there in case another mod _does_ use it

Intended

**Comment by TheBedrockMaster** [comment]
I'll add the tag to other modded rods with Kube. From what I've seen a couple of mods use `c:rods/all_metal`, but it's not common.
