### ISSUE TITLE
Custom chests, fences, ladders, and trapdoors for structures

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#451]
It seems a lot of people are suggesting revamped structure (and some have already been made). While these structures have been great so far, there's something about them that feels very out of place: typical overworld wood being used for the doors. ladders. and chests. It feel really out of placed when the entire structure is, let's say, red. It feels really odd to have an orange block that's completely unrelated to that structure or dimension as a whole. I think all dimensions should have custom chests, fences, etc that are used for all the structures in it.

**Comment by Immortallis1** [comment]
Yeah, little changes like these are the kind of stuff that future updates need.
