### ISSUE TITLE
Realmstone changes #2

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#454]
This is a continuation of a suggestion I made a while back (#409). This one is more focused on moving realmstones away from the overworld. It's been mentioned quite a few times that too many realmstones are obtained in the overworld.

Abyss: The bloodhunt event could be moved to the Nether. If that's not possible, then maybe the mobs that drop the item spawn in the nether. There's currently no realmstones obtainable in the Nether.

Mysterium: This might seem like an odd choice, but maybe the realmstone could be obtained in the End? If you think about it, it makes sense. Both dimensions are imaginary (the End is a dream dimension and Mysterium takes place in the Eeos' minds) and mysterious.

The Deeplands could be from the Nether? idk

L'Borean should be moved back to Gardencia. It makes sense (especially since the current dimension after Gardencia is a toxic wasteland). It would also tie in fairly nicely with the change I suggested in #409.

Immortalis could be moved to Nether as well (or Etherus, but I feel the Nether fits more).

That would only leave five of the ten realmstones currently obtained in the overworld.

**Comment by Tslat** [comment]
I'm not sure this will be relevant after 3.2 :)
