### ISSUE TITLE
Banker's Table

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#455]
A new utility block: the bankers table. To obtain it, you would need to buy it from any of the bankers (but for a very high price, maybe something like 20 lunaver coins). It would act like any banker, but in block form. Having to walk to a banker everytime you need to buy something is annoying, especially if you only have one teleporter or your banker spawned far away from the portal. It could use the Hermetism Table's texture, since imo its texture looks too good to go unused.

**Comment by Immortallis1** [comment]
The Table version could be far more efficient (i.e. have several input slots instead of just one) to justify the price even if the player has safari nets or soul vials or whatever. It should also probably be no more than 10 lunaver coins because 20 is ridiculous lol

**Comment by DiamondWalker** [comment]
Eh, I'm not a fan of it having multiple slots just to beat another mod's item. Also, using a safari net takes an inventory slot, a table doesn't.

**Comment by Immortallis1** [comment]
I'm not trying to beat another mod's item. I'm trying to make banking easier for those with stacks upon stacks of copper coins because they killed a lot of mobs.
