### ISSUE TITLE
Request Tslat of Skills source code

### ISSUE THREAD

**Issue by 1640946640** [Tslat/Advent-Of-Ascension#457]
As the title shows, my server has a Tslat Mod installed, and it's a group server.
I divide the survivor world from the adventure world to ensure that the server runs smoothly.
But players have different levels of Skill Tslat on each server, so a lot of players are losing from my server because it's a serious problem.
I need the author to publish this part of the code to make the relevant Mysql cross-service plugins.
Or, if you don't want to, you can make a plug-in of the skill level of cross-service synchronization for release. We really need such plug-in. We hope the author can adopt it as soon as possible. We must be very grateful :)

**Comment by Angrydog001** [comment]
1.7.10 is no longer supported
