### ISSUE TITLE
Neutral Mobs

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#459]
So we have Hostile mobs and **2** passive mobs but one type that hasn't been explored is the neutral mob like the Enderman. I feel like some mobs would be better off being Neutral.

Heres my list:

- Horndron (Looks like a Bull or Musk Ox, it also looks like something that would only attack if it felt threatened).

- Elkanyne (Another mob that could act like pigmen, trying to get the stampede could be very dangerous).

- Rammerhead (Same reason as the latter of Horndron reasoning).

- Skeletal Cowman (I never understood why this mob is hostile, its basically the range version of Zombie Pigman which is neutral).

- Ramradon (Same reason as the latter of Horndron reasoning).

- Rainicorn and Runicorn (Same reason as the latter of Horndron reasoning).

- Dyrehorn (Same reason as the latter of Horndron reasoning).

- Megatherium (Same reason as the latter of Horndron reasoning).

- Tortione (~This is defiently not in here so I have to fight it without any splash potions or explosive weapons~ ALSO MAKE THIS MOB REALLY SLOW LIKE A ACTUALLY TORTOISE).

- Terradon (This might be a bit of a streach since its a rare mob).

**Comment by Cruuk** [comment]
Pretty good suggestion, I especially agree on Horndron being neutral since it has such insane stats for an earlygame mob.

I'm not necessarily against making Tortione neutral but you should know that Tortione is no longer immune to Blasters/Staves, due to them not being classified as the same damage as guns now.

**Comment by Sagisolar** [comment]
> 
> 
> Pretty good suggestion, I especially agree on Horndron being neutral since it has such insane stats for an earlygame mob.
> 
> I'm not necessarily against making Tortione neutral but you should know that Tortione is no longer immune to Blasters/Staves, due to them not being classified as the same damage as guns now.

Wow I didn't know its not immune to those anymore, I also looked back on this suggestion and some how missed Skeletal Cowman, my main one I wanted to be neutral.

**Comment by Immortallis1** [comment]
Yeah I kind of agree about skeletal cowman, I mean come on he rapid fires arrows at you from like 30 blocks away with his back turned. It's kind of stupid.

<s>Granted I've only died to it once and that was because my back was to a lava flow and I underestimated his sight range, but still.</s>

**Comment by EatingSilencer** [comment]
What about Runicorn Rider? Would it remain hostile because it has a rider on its back?

**Comment by Sagisolar** [comment]
I think the rider is the controller, since paladins are hostile I would say Runicorn Rider is hostile

**Comment by DiamondWalker** [comment]
I don't really agree with these tbh (aside from the skeletal cowman one). They seem like they would make some dimensions a lot easier (they are already easy enough)

**Comment by Sagisolar** [comment]
Really? I feel like neutral mobs would make dimensions more intresting. Mobs currently are just "bad mob wants to kill you" which make dimension feel the same all the time.

Also mob update should fix dimension feeling easy so don't worry. ;)

**Comment by Tslat** [comment]
We started getting passive/neutral mobs as of 3.2 :)
