### ISSUE TITLE
Cycade trees

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#460]
**Describe the new feature you think would be good to add**
Back in 1.0, there existed another type of tree that generated in Precasia, "Cycade trees".
![image](https://user-images.githubusercontent.com/38159897/54094438-2946bf80-435e-11e9-9a61-b0718b80019a.png)
![image](https://user-images.githubusercontent.com/38159897/54094440-319efa80-435e-11e9-91f9-653cf890c19d.png)
They were pretty neat, but were removed at an unknown time. Now, they are only found in the Precasian lotto structure and Coniferon's room (the blocks themselves, not the trees)

Why were they removed? Maybe it was because they didn't fit with the other trees? Personally I think they fit pretty well... So it would be neat to see them again.

Yeah I know we shouldn't go on a crusade re-adding every removed thing, but you know... they were neat...
Sagi asked someone to post this and I thought they were neat so...

**Comment by DiamondWalker** [comment]
Yeah, I really like most of the pre 1.0/1.1 things.

~~Maybe 1.0 should have been ported instead of tslat versions~~

**Comment by Sagisolar** [comment]
You could even make it a biome if it really does seem out of place

**Comment by Immortallis1** [comment]
If anything, they don't have to generate, but you can get the saplings from precashit and then bonemeal them into full trees.

**Comment by DiamondWalker** [comment]
I don't find them out of place. What does seem out of place is that the Precasia lott structure is made from a tree that doesn't exist.

**Comment by Cruuk** [comment]
> 
> 
> I don't find them out of place. What does seem out of place is that the Precasia lott structure is made from a tree that doesn't exist.

Coniferon sells them for $5 a piece.
