### ISSUE TITLE
Boss Music Copyright

### ISSUE THREAD

**Issue by UnderWaves** [Tslat/Advent-Of-Ascension#461]
While wandering on the wiki, I discovered that some boss musics were extracts of copyrighted music (example with the Nethengeic Wither, that uses the Final Fantasy X-2 boss music).

On a proposal from @DiamondWalker I decided to create a resource pack containing some ideas of new boss musics I made myself. I'll try to sometimes send you my new creations, and when I'll be finished, I'll publish the resource pack.

I already made some, like the C.R.E.E.P's music :
https://www.dropbox.com/s/oui31dvadz1ho0o/Green%20Menace%20%28C.R.E.E.P.%29.wav?dl=0

**Comment by DiamondWalker** [comment]
Actually, not all the boss music was copyrighted. The ones that were were the themes of the bosses added in 1.0 (Smash, Corallus, KingBamBamBam, Nethengeic Wither, Elusive, Shadowlord, and Rockrider).

**Comment by UnderWaves** [comment]
I know.

But when you're launched, the best thing to do is to continue, right?

**Comment by papabean** [comment]
If you're willing to make custom music for the bosses then sure, go ahead. As DiamondWalker stated, however, the only bosses that have copyrighted music are the 1.0 bosses (Smash, Corallus, King BamBamBam, Nethengeic Wither, Elusive, Shadowlord and Rockrider respectively). 

Aside from that, I'm not sure if Scimi is handling the copyrighted music yet. We will have to wait for his viewpoint on it.
