### ISSUE TITLE
Blood spikes and Toxic block ponds (Abyss)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#462]
(Unlike the other one this one isn't on behalf of someone else, I've been wanting to make this for a while)
**Describe the new feature you think would be good to add**
Personally, I find the Abyss' current gen a little lacking, I can understand why it was changed- the old one was a monster to lower-end PCs.
But, there was one aspect of the old gen that was removed with it, and I'm not sure why.
Basically, Abyss used to have hazardous blocks spawn on it's surface. **Blood Spikes and Toxic Blocks**.

--------------------------

**Blood Spikes**
![image](https://user-images.githubusercontent.com/38159897/54111910-3b4a5180-43a2-11e9-96d5-dcb814324ef8.png)
![image](https://user-images.githubusercontent.com/38159897/54111922-4309f600-43a2-11e9-852f-e30272c27af3.png)
This foliage used to spawn in the Abyss. Touching it would give you poison and blindness for 5 seconds.
Maybe these were removed cause you couldn't really tell that unlike other foliage, they were hazardous? Not sure. I think we can still communicate to the player that there's something off with them with something like this:
![image](https://user-images.githubusercontent.com/38159897/54112236-f1ae3680-43a2-11e9-8801-c8f30f0b7324.png)
If they're re-added, they could spawn in little holes like this to imply that they're different from the other foliage. ~~Or if you change Abyss to be more like an actual Abyss with big ravines you could make them only spawn down there~~

I forgot to mention that Blood spikes **are still in the game**. They've been in the game since 1.0, but just have never generated since 2.0, since that was where the gen changed IIRC.
![image](https://user-images.githubusercontent.com/38159897/54112529-9d578680-43a3-11e9-8878-e783be2292e0.png)
Though as of 3.0.2 they work a little oddly. When you go into the spikes they give the poison/blindness, but the poison only goes into effect when you go out of it, so that should probably be fixed if they're re-added...

-----------------------

**Toxic Block ponds**
![image](https://user-images.githubusercontent.com/38159897/54112774-2969ae00-43a4-11e9-8f53-a08ca2bdac0f.png)
![image](https://user-images.githubusercontent.com/38159897/54112800-35557000-43a4-11e9-9b14-17bac861ea76.png)
Toxic blocks still spawn naturally, but you can only find them really deep underground or inside Illusion trees.
I thought these were pretty neat as well. Maybe they were removed for the same reason as the Blood spikes? Either way, you can also change these to make it more clear that they're hazardous, like making their texture animated ~~and making them a liquid~~.

----------------

I just think re-adding these would make Abyss a little more interesting. Deeplands, Iromine, and Vox ponds are like the only places with Hazardous blocks/foliage, and re-adding these to Abyss would make it so the mobs aren't the only dangerous thing. It'd add a little variance.

**Comment by Immortallis1** [comment]
> Though as of 3.0.2 they work a little oddly. When you go into the spikes they give the poison/blindness, but the poison only goes into effect when you go out of it, so that should probably be fixed if they're re-added...
Worth noting that this happens with Erebus wither webs too. Probably has to do with constantly refreshing the potion effect or something
