### ISSUE TITLE
Greatblade hitreg is a little odd in certain places

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#464]
**Mod Version**
3.0,2

**Describe the bug**
I've noticed that Greatblade hitreg (hit registration) has a few issues in certain areas. It's fine when you're hitting a single mob, but if you're trying to hit a mob in a group of them, or trying to hit a mob at the very edge of it's hitbox in a corner, then issues start to arise.
When hitting a group of mobs, often the greatblade will hit the mob behind the one I'm trying to hit instead. Even when there's only 2 mobs I've had the greatblade hit the mob in the back rather than the one in front.
If you're trying to hit a mob that's mostly behind a block with a greatblade, it won't hit. You can still hit them with a sword/fist though.
And yes, Scythes have the same issue. I tested all of these in survival mode.

**To Reproduce**
Steps to reproduce the behaviour:
Fight a group of mobs and try to hit the mob you want to hit.
Try and hit a mob that's in a corner at the very edge of it's hitbox.

**Expected behavior**
Greatblades having the same hitreg as swords while still having the longer range.
I'm hoping this isn't a side effect of greatblades having longer range. Hopefully Greatblades can keep the longer range but not have to have these issues.

**Screenshots**
I have both a video and screenshots!
https://youtu.be/2alq1hg4bJY

At this position Greatblades couldn't hit it but swords/fists can
![image](https://user-images.githubusercontent.com/38159897/54120940-5aeb7500-43b6-11e9-8d2d-6f3df3bd7f92.png)
Hitbox on
![image](https://user-images.githubusercontent.com/38159897/54120875-2081d800-43b6-11e9-9064-0d449be19b2f.png)
There was another Paladin behind it.
![image](https://user-images.githubusercontent.com/38159897/54121192-0bf20f80-43b7-11e9-95f4-5eeb77b6d75e.png)

**Comment by Tslat** [comment]
Finally took this beast down.
