### ISSUE TITLE
3D models for all firearms (And aimming animations)

### ISSUE THREAD

**Issue by VioletWyvern** [Tslat/Advent-Of-Ascension#465]
**Describe the new feature you think would be good to add**
If is possable, I really like to see some 3D models for all firearms **(Included all Guns, Cannons, Shotguns, Blasters and Archerguns)**
The other weapons like swords, staffs and bows remain 2D is fine since the're only two surfaces, But peoples didn't like just holding a "Cardboard gun" for fighting (And if it possable, The firearms should have aiming position like you aiming with bows, You cannot shooting a firearms when your gun's barrel facing downside...)

**Add any alternative implementations you think might work**
This should making some weapons looking better (Since some mobs and bosses has 3D model weapons, Why not for the players?)

**Include any additional background information**
Nope !

**Comment by Sagisolar** [comment]
Wouldn't that go against the simplicity minecraft?

**Comment by Immortallis1** [comment]
This was already discussed. There are hundreds of weapons, and adding 3D models to all of them would take such a frustratingly long time it's disgusting. Mobs and Bosses do not have 3D model weapons, the "model weapons" they have are not weapons they're actually holding, but part of the mob/boss model, so they don't count.

Plus, making some weapons look better is subjective. I personally dislike the idea of 3D models for anything that isn't a novelty tech item (e.g. portal gun) to begin with.

**Comment by Tslat** [comment]
Can confirm, will not be happening
