### ISSUE TITLE
Doing the aoastructure list command in a server shows the list to everyone

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#466]
**Mod Version**
3.0.2

**Describe the bug**
Doing the aoastructure list command while in a server displays the chat message to everyone on the server, not just the person who did the command.

**To Reproduce**
Steps to reproduce the behaviour:
Do the aoastructure list command in a server, other players on it will see it.

**Expected behavior**
The command only showing to the person who did it, like the /help command.

**Screenshots**
This was Larz doing the command, not me.
![image](https://user-images.githubusercontent.com/38159897/54133929-3a321800-43d4-11e9-9cd8-9a9ea51814cf.png)

**Comment by Sagisolar** [comment]
oh No I cAn'T AnNoY mY FrIEndS iF tHiS GeTs FiXeD

**Comment by Immortallis1** [comment]
Baroness House? lolol

**Comment by Tslat** [comment]
It actually only shows to ops listening in to command feedback.
Either way, has been fixed

**Comment by DiamondWalker** [comment]
> 
> 
> Baroness House? lolol

That's because the barathos lotto house was going to be Baroness' arena.
