### ISSUE TITLE
New Runic Staff ability

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#467]
The Runic staff currently feels a bit useless. All it does is take items out of you ender chest. Why can't you just use an ender chest or ender carrier? The Runic staff takes more inventory space (one slot for the staff and one for the runes), and is more expensive. In addition to this, it takes ALL your items out, so you can't even decide which you want to take out. I think it should have a different ability.

My idea is that when you use it, it would open some menu where you can access all nearby chests. From this menu, you could select one item in a nearby chest. When you do, you will spawn a friendly runic golem. This runic golem would not attack enemies, but would find his way to the chest which contains the item you chose, take the item out of the chest, and walk back to you. Once he has the item and is standing next to you, you can absorb him with the runic staff, and the item he has will be put in your inventory. If he dies, he would explode, destroying the item he's holding.

I feel this would be more useful in several situations. If you're crafting and realize you'll need a certain item soon, you can send the golem to bring it for you. If a chest is located in a dangerous area (like a dungeon), you could send the golem in to try to take one of the items (but he can die and the item will be lost). The only issue I can see with an item like this is that it could possibly bypass claims on servers.

**Comment by Cruuk** [comment]
It literally has a new ability. It's basically a mobile ender chest now. You right-click it to gain access to your ender chest. It's basically a backpack you can put stuff like Shulker boxes in for extra storage. It's pretty neat now.

**Comment by DiamondWalker** [comment]
I mentioned that ability and why I don't find it useful at the beginning. Also, the wiki says it takes all your items out, but even if it doesn't, my other points still stand (unless I'm missing something).

**Comment by Cruuk** [comment]
> 
> 
> I mentioned that ability and why I don't find it useful at the beginning. Also, the wiki says it takes all your items out, but even if it doesn't, my other points still stand (unless I'm missing something).

Wiki is outdated in that regard. It no longer takes items out of an ender chest. You just right-click it and boom, ender chest. You don't even need to make an ender chest at to use it.
Even if you lose your Runic staff, your items are still saved in that "space", and all you need to do to access this "space" is craft an ender chest or get another Runic staff.

So what if you can use Ender Carrier? It has a Creation req of 70. Runic staff and Ender carrier are simply just the same reward for different skills.
Maybe Ender carrier is more useful overall, but it's automatically attacked by hostile mobs and it doesn't attack mobs anymore. You also still have to walk to the mob while with Runic staff you can access it from your inventory. Both have their upsides and downsides.

Anyway, I dislike your ability suggestion for Runic staff, I would rather have a simple ability like a mobile ender chest than something that requires lots of words to explain. It feels unnecessarily complicated in the worst way possible to me. It just feels like I'd get more uses out of an ender chest backpack than this Golem stuff.

**Comment by DiamondWalker** [comment]
Still, ender chests are pretty much better in most ways. It doesn't require runes, it's cheaper to make, and can be obtained much earlier on. To get a runic staff, you have to get an eye of ender (by which point you have what it takes to make an ender chest). Then you need to go into a fairly difficult dimension (Mysterium), find runic golems and a gorb village, and kill several runic golems which are hard to kill. Eyes of Ender aren't that hard to get, especially if you've gone into the End (which is fairly early game in AoA). About the Ender Carrier thing, maybe it should just be buffed?

Also, the staff ability isn't that complex. I just wanted to give as many details as possible. It could be simply explained as "Summons a golem to bring you an item of your choice".
