### ISSUE TITLE
Runic Bomb change

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#468]
I've seen a few people saying that Runic Golems are annoying to fight. Instead of just removing their ability (since it's quite unique imo), maybe change to way runic bombs work. Instead of throwing it (which can be blocked by other runic golems), make it be used directly on the runic golem (right click the golem with the bomb in your hand). It would do nothing if used on a runic golem that doesn't have an active shield so they can't be wasted. If you right click it on a shielded runic golem, you will plant the bomb on it. This will make the shield start flashing red, and he will explode after a few seconds (it wouldn't take damage from this explosion, the explosion would only serve as an extra challenge).

**Comment by Tslat** [comment]
Has this been tested in 1.12?
In 1.7.10 you had to hit the golem directly with the runic bomb to remove its shield.
In 1.12 it just has to be in its explosion radius, and it can affect multiple runic golems in one blast

**Comment by DiamondWalker** [comment]
I'm not sure. I've never had problems with runic golems myself. I was just offering a solution to those who find them annoying to deal with.
