### ISSUE TITLE
Change hauling "replacement"

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#469]
Fishing has three types of drops - fish, junk, and treasure. According to the MC wiki, there is an 85% chance to catch a fish, 10% chance to catch junk, and a 5% chance to catch treasure. In its current state Hauling has a 1/3 chance to indiscriminately replace whatever fishing drop making treasure (and junk I guess) ridiculously rare when fishing since a decent portion will be replaced with finger fish or whatever.

Personally, I think hauling could just replace the "fish" items. Since it takes a little while to get xp anyway maybe it's best to also just buff the "replacement" rate, maybe to 1/2 or even all the time. Hauling's in an odd state right now.

I'm unsure if this is possible or not, but until an actual skill rework this would probably be a better idea.

**Comment by DiamondWalker** [comment]
Maybe the hauling crates could be considered treasure and the old boot could be fished as junk?

**Comment by Immortallis1** [comment]
yeah I don't know, something tells me that just adding the items to the "treasure" and "junk" tables would make things unnecessarily complex and ruin an otherwise alright system.
