### ISSUE TITLE
Portal Sending People Back Right Away On Server

### ISSUE THREAD

**Issue by ZephhyLeo** [Tslat/Advent-Of-Ascension#470]
**Mod Version**
What version of the mod are you on?

3.0.2

**Describe the bug**
Once someone gets into a portal and tries to load a dimension it sends them back right away, they can't do anything to get out before it sends them back

**To Reproduce**
Steps to reproduce the behaviour:
Host a server on Minecraft Forge 1.12.2 with 14 GB of Ram with the mod installed.

**Expected behavior**
Maybe the server is loading faster than the client

**Screenshots**

**Comment by Tslat** [comment]
Has been fixed
