### ISSUE TITLE
Bring back the Retro Banners

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#472]
Why were these removed? They just retro banners, and honestly they look way better than the normal ones. Also add a new retro banner for creation. These banners should be **very** rare drops from the mobs that drop the normal versions.
Retro:
![Energy_Banner](https://user-images.githubusercontent.com/44548547/54194520-59a07200-44b4-11e9-93dc-af9154cc8e1e.png)
![Soul_Banner](https://user-images.githubusercontent.com/44548547/54194531-5e652600-44b4-11e9-9865-c7983fa53646.png)
Normal:
![Energy_(New)_Banner](https://user-images.githubusercontent.com/44548547/54194562-6cb34200-44b4-11e9-9dd8-321ac2701638.png)
![Soul_(New)_Banner](https://user-images.githubusercontent.com/44548547/54194604-8785b680-44b4-11e9-9603-892f3bce2875.png)
![Creation_Banner](https://user-images.githubusercontent.com/44548547/54194613-8ce30100-44b4-11e9-8c8c-bd91f66aad3c.png)
~Lets be real here, the same guy who wanted these removed made another suggestion for removing one of Creeponia's banners as well, picky.~

**Comment by Immortallis1** [comment]
Well Cruuk made a suggestion once about having them be rare finds in corrupted teleporters. While symbolically that's the best thing to do in actuality that just makes it nearly impossible to get even a gold banner. Maybe as a trade from corrupted traveller for food?

**Comment by Sagisolar** [comment]
> 
> Also we don't need a retro creation banner lol since there never was any

Make a new banner with the creation symbols. (I forgot if there still used in game, too lazy to check).
![Bring back plz - Copy](https://user-images.githubusercontent.com/44548547/54237903-f2fc7200-450e-11e9-91b0-4f23326e64ea.png)

**Comment by Cruuk** [comment]
> 
> 
> > Also we don't need a retro creation banner lol since there never was any
> 
> Make a new banner with the creation symbols. (I forgot if there still used in game, too lazy to check).
> ![Bring back plz - Copy](https://user-images.githubusercontent.com/44548547/54237903-f2fc7200-450e-11e9-91b0-4f23326e64ea.png)

The old Creation sprite was a reskin of the "Vertebrae" from Terraria.

![image](https://user-images.githubusercontent.com/38159897/54238521-f32c4b80-44d5-11e9-8120-7a9d8aeca995.png)

**Comment by Immortallis1** [comment]
well, the old banners were existing before, so there's not really a point in making a new banner for the creation symbols. that being said it wouldn't hurt I guess besides the copyright

**Comment by Sagisolar** [comment]
> 
> 
> > > Also we don't need a retro creation banner lol since there never was any
> > 
> > 
> > Make a new banner with the creation symbols. (I forgot if there still used in game, too lazy to check).
> > ![Bring back plz - Copy](https://user-images.githubusercontent.com/44548547/54237903-f2fc7200-450e-11e9-91b0-4f23326e64ea.png)
> 
> The old Creation sprite was a reskin of the "Vertebrae" from Terraria.
> 
> ![image](https://user-images.githubusercontent.com/38159897/54238521-f32c4b80-44d5-11e9-8120-7a9d8aeca995.png)

I think that's different enough.
