### ISSUE TITLE
Somes bugs (invisible ennemies, no glistening pixons, etc...)

### ISSUE THREAD

**Issue by Ryunari** [Tslat/Advent-Of-Ascension#473]
Hi guys. I have some problems on the 1.12.2 version (3.0.2 for A.o.A). 
First (and perhaps the biggest problem), sometimes I don't see one or more ennemies but they are here because I hear their sounds and they can hurt me, not me. But, if I leave the game and restart, they appears on the screen. It' is very annoying because I must leave every time when this is happening (and I do this at least one per hour).
Second, I don't have any glistening pixons (overworld and gardencia). I know that I can "spawn" them with pixon's eggs but I play in survival so it's not pleasant to use some "cheat" like the egg's creatures.
Third and last, I open a portal to go to Haven and I appear very far of all the islands nearby and at the depth of the Haven (y= 1).

**Comment by Cruuk** [comment]
Do you have Optifine? We haven't been able to find a solution for mobs going invisible, and from asking other devs it seems the likely cause is Optifine.

I have never had mobs go invisible on me at all, and I don't use Optifine.

**Comment by Ryunari** [comment]
Yes, I use Optifine. I'll try immediately.

**Comment by Ryunari** [comment]
For the moment, I have no problem with invisible ennemies. Thanks a lot for this solution.
