### ISSUE TITLE
Augury should increase the timer of the tribute effects

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#474]
(I know I included this is my original tribute rework suggestion, but with Tribute being different now I figured I might as well make it it's own suggestion)
**Describe/name the existing feature this suggestion relates to**
Augury and the Tribute effects.

**Describe the change or feature you think would be good to see**
We all know that Augury is pretty flawed as a whole, but this is more about another possible benefit of training Augury. Other than just increasing the Creation and Soul Power bars, and the AC bosses,
I always thought Augury should directly be connected to the **Tribute Bar**. I know it already affects Soul Power and Creation, but that's more of a side thing and those 2 resources already have skills connected to them.

The way I interpreted Augury was that it was a skill about *ascending* ("ascension shrine", fighting the guardians of the gods, etc.). Just like how Anima is connected to Soul power, Creation being connected to... Creation, I think Augury should be directly connected to the tribute bar.

----------------

Basically, depending on your Augury level, the dimension timer for Tribute effects would increase.
What I mean is that while in the Overworld it would still only last until night ends, but going into a dimension with a tribute effect increases the timer. I know you could just go back into the Overworld and have the increased timer, but it still requires you to go into a dimension to activate it...
(Or maybe it should, I'm not sure if it would otherwise be unintuitive or not)

From what I've tested, the dimension timer starts at 9:30 and begins counting down depending on the time of night in the Overworld. Augury would get whatever the timer is when a player first enters a dimension under a tribute effect, and increase it by a certain amount.

Basically, let's say the maximum increase was 2 extra minutes. Entering a dimension right after getting the tribute effect would have the timer be at **11:30** instead of 9:30. Entering a dimension after waiting 5 minutes would have the timer be at **6:30** instead of 4:30.

At Augury level 25, 50, 75, and 99, the dimension timer would increase. I'm not sure how much it should increase, it depends on how impactful it should be. I was thinking 30 seconds or a minute. Maybe a 30 second boost at 25/50, and a minute boost at 75/99? Not sure.

-------------------

I just think this would add a better, more impactful reason to train Augury rather than just having to think about the AC bosses the whole time (and I guess benefitting Anima and Creation but ehh...). It would feel nice knowing that I'll be able to benefit more from tribute effects as I tread on the dreadful journey of getting to Augury level 70. *And* sort of add an actual reason to train Augury beyond 70 other than just for Augury armor.

It would also make sense "lore-wise", as you ascend, you benefit more from pleasing the gods via their effects lasting longer.
Maybe someday Augury will be this cool ascending skill and not just "feed the ascension shrine essences and fight some guys in a cavern"

**Include any additional background information**
Originally I was thinking that Augury would also increase the max Energy but I feel like that wouldn't be the best idea... so I decided to have it affect the tribute bar instead.

**Comment by Tslat** [comment]
This isn't really going to work, the tribute timer isn't an arbitrary time, it's meant to replace the remaining time you would have got if you had waited the day out as normal in the overworld
