### ISSUE TITLE
Skydiver's Acid spawns below you so you take damage

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#475]
**Mod Version**
3.0.2

**Describe the bug**
When you fire Skydiver bow the acid can spawn below you so it can screw you over.

**Expected behavior**
Not spawn acid below you?

**Screenshots**
Where I shot
![2019-03-12_22 55 47](https://user-images.githubusercontent.com/44548547/54241789-0fea7280-451a-11e9-86a8-67c6416a3bb5.png)

**Comment by Tslat** [comment]
Weird, I already had this fixed on my end.
Might be a ticking thing - I'll raise the threshold a bit
