### ISSUE TITLE
Visulon should drop 4/5 eyes

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#477]
Grinding Visualent is currently painful. It takes finding an insanely rare mob to get one summoning item, and then you might not get the item you want. I think Visulon should drop 4 or 5 eyes. The reason I choose these numbers is because Visulon has 5 eyes. The reason it could drop 4 is to represent that one of the eyes got damaged during the fight.

**Comment by Tslat** [comment]
No longer relevant
