### ISSUE TITLE
Unknown Error 

### ISSUE THREAD

**Issue by Chriswow11** [Tslat/Advent-Of-Ascension#478]
Installed the mod with Roguelike Adventures and Dungeons. Can play just fine, but may cause issues later in my game.

https://paste.dimdev.org/dadidiseho.mccrash

**Comment by Tslat** [comment]
Not sure what's causing this - but has it been tested without AoA?
When does it happen? 
Is it repeatable?

**Comment by Chriswow11** [comment]
Sorry, I think this is a RAD issue-- same thing occurred without AoA but with Tinkers
