### ISSUE TITLE
Looting enchantment does not work on advent mobs

### ISSUE THREAD

**Issue by Sulferix** [Tslat/Advent-Of-Ascension#479]
**Mod Version**
1.12.2

**Describe the bug**
when farming mobs with a weapon that has the looting enchantment attached, the drop rate of items is unchanged from weapons without the looting enchant.

Steps to reproduce the behaviour:
1. go into advent dimension of any kind with any looting enchanted weapon 
2. hit mobs until dead
3. repeat the same process with an un-enchanted weapon
4. witness no difference.
**Expected behavior**
i expect drop rates of rare items to go up, and i expect to be a lot more drops.

EDIT: apparently this is intentional, but why? its a part of the game, why is it disabled throughout the entire mod? makes no sense. i would change this to a suggestion that can be put in the config then. people should be able to use the looting enchantment.

**Comment by Tslat** [comment]
This is patently false, and was tested with an extremely flawed methodology

**Comment by Immortallis1** [comment]
> 
> 
> **Mod Version**
> 1.12.2
> 
> **Describe the bug**
> when farming mobs with a weapon that has the looting enchantment attached, the drop rate of items is unchanged from weapons without the looting enchant.
> 
> Steps to reproduce the behaviour:
> 
>     1. go into advent dimension of any kind with any looting enchanted weapon
> 
>     2. hit mobs until dead
> 
>     3. repeat the same process with an un-enchanted weapon
> 
>     4. witness no difference.
>        **Expected behavior**
>        i expect drop rates of rare items to go up, and i expect to be a lot more drops.
> 
> 
> EDIT: apparently this is intentional, but why? its a part of the game, why is it disabled throughout the entire mod? makes no sense. i would change this to a suggestion that can be put in the config then. people should be able to use the looting enchantment.

I'm going to sort this out. It's NOT intentional in the latest version (1.12.2). The wiki is just out of date, because in the OLD versions it WAS intentional, and the wiki is slow to update.

**Comment by Sulferix** [comment]
patently false? definitely not. looting very obviously does not work at all. i tested with enchanted and un enchanted, what other methodology is required? lol
