### ISSUE TITLE
Make Deeplands and Iromine have more ore

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#483]
Move some of the ores to the Deeplands. The Deeplands is a cave dimension, yet it only has two ores, which is beaten by a barren dimension and a creeper dimension? Doesn't make much sense imo. I think some of the Barathos ore should be moved to Deeplands. Specifically: Varsium and Elecanium.

These two ores have nothing in relation to Barathos, and feel like they were just thrown in there in an attempt to make the underground more interesting. I think they would make more since in the Deeplands, since that dimension doesn't have enough ores and doesn't have a specific theme for the ores. For balance, maybe they could require a late-game pick to mine? That way Elecanyte armor won't overshadow the Subterranian armor.

I also havetwo new ore suggestions: Deep ore and Silvro ore. Deep ore would spawn in the Deeplands, and Silvro ore would spawn in Iromine (when biomes are added, it would replace Lyon ore that spawns under that Silvro Hills biome).

Deep ore would have the same uses as Bloodstone/Crystallite (the armor would have Necro armor's old set bonus). You could also make a special item used for opening deep cases (mining them would give them as a block). To open a deep case, you would have to right click it with the item on all six sides (every time you right-click it on a new it would remove the "screw" on that side). This would also make opening deep cases more unique than just "smash it with pickaxe until it breaks".

Silvro ore would be used to make a defensive alternative to the Lyonic armor (same set bonus, but the extra damage would be replaced by decreased damage taken). It would also replace the Lyon ingots required to buy the Silvro Coin.

**Comment by Immortallis1** [comment]
#153
