### ISSUE TITLE
More integration

### ISSUE THREAD

**Issue by ym1025** [Tslat/Advent-Of-Ascension#484]
I want more items to integration some industry mod:
metal dust
metal plate
TCon's molten metal
mekanism's ore shard,cluster and crystal
metal rod
metal gear
RF machines using these items

and I want to integration these mod:
TCon
nuclearcraft
thermal expansion
ender io
chisel
immersive enginnering
jaopca ← this mod integartion means it add above items
mekanism
heat and climate
industrial craft
techguns
tech reborn
railcraft
embers
galacticraft
advanced rocketry
chisel
heat and climate

thanks for reading,my english is bad.

**Comment by masterbobli** [comment]
Somebody has created a tinker’s construct integration mod

**Comment by Immortallis1** [comment]
yeah but that's for 1.7.10 and it's not "official". Would help to have official integration one day so that the dev can make sure it's balanced (i.e. no FTB Departed ExtraTiC crossbows)

**Comment by ym1025** [comment]
I'm going to tell these to JAOPCA developer.
Sadly,coins,rusted iron ingot,block of metals,block of gems and some other items not registered ore dictionary and Tcon integration scripts doesn't seem to work too much.

**Comment by Tslat** [comment]
A lot of things have changed since this suggestion, and 3.3 adds numerous mod supports.
Re-raise another suggestion with more detail after 3.3 if you think something is missing
