### ISSUE TITLE
Make the despawn check specific to Overworld NPCs and not check by dimension

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#485]
Right now all NPCs despawn if they're in dimension 0. This leads to people transporting bankers to the overworld with third party mods only to find they despawn. Conversely, overworld NPCs that walk into nether portals or something will never despawn.

There's only 5 overworld NPCs besides corrupted traveler and they were already classed as a "remnant" from 1.7.10 so it's not like more are going to be added in the near future. NPC spawn/despawn is weird in general but until an actual fix is found this would help immensely.

**Comment by Tslat** [comment]
Use Nametags
