### ISSUE TITLE
Better questing 3 and boss health bars

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#487]
**Mod Version**
AoA:3.0.2
BQ:3.5.294

**Describe the bug**
When looking at the quest book page which has the mob hunt task of killing an AoA boss, the boss bar appears after the book is closed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a mob hunt task (need to be an AoA boss) on a random quest
2. Select that mob hunt task page in the quest.
3. Quit the quest book
4. A bossbar appears

**Expected behavior**
No boss bars should appear.

**Screenshots**
![2019-03-17_09 05 31](https://user-images.githubusercontent.com/37212918/54483765-2125dd00-4894-11e9-9012-3fe2cbbee0f9.png)
![2019-03-17_09 05 44](https://user-images.githubusercontent.com/37212918/54483766-23883700-4894-11e9-9f78-ca28ed50266a.png)
![2019-03-17_09 07 56](https://user-images.githubusercontent.com/37212918/54483767-297e1800-4894-11e9-83fb-9cd0b3896ea9.png)

Note: the boss bar disappears after killing the boss in the real game.

**Comment by Tslat** [comment]
Has been fixed - although this should be on Better Questing 3 - they should be killing off the entity after the book is closed
