### ISSUE TITLE
Portal Loop Preventing Travel to and from other dimensions.

### ISSUE THREAD

**Issue by StrideJB** [Tslat/Advent-Of-Ascension#488]
**Mod Version**
3.0.2

**Describe the bug**
On our server, whenever someone tries to enter a portal to an Advent dimension, they are teleported there, and instantly sent back, which then becomes an inescapable loop unless the player disconnects.
**Expected behavior**
Travel is impossible, thought portal would simply teleport there with no issues.

**Screenshots**
Unable to screenshot, game freaks out during the event.

**Comment by QGM1002** [comment]
I have the same problem.

**Comment by Tslat** [comment]
Has been fixed in the next version

**Comment by QGM1002** [comment]
in 3.0.2 ?

**Comment by Sagisolar** [comment]
"Next version" so 3.1
