### ISSUE TITLE
Mending Table not repairing my items when I have Magic Mending Solution?

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#489]
**Mod Version**
3.0.2

**Describe the bug**
I'm trying to repair my Sapphire Pickaxe (which is enchanted) with Magic Mending Solution from a Mending Table by right-clicking it with my Pick, but nothing is happening!

**Expected behavior**
My tools are supposed to be repaired.

**Comment by Tslat** [comment]
Fixed in 3.1
