### ISSUE TITLE
Corruption

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#490]
If the portal ghost got corrupted by traveling dimensions, why doesn't the player? The corrupted traveler even warns you about it. I think there should be a corruption mechanic. 

Concept:
Corruption would be based on a new GUI bar. This bar would be similar to the ones that already exist (energy, anima, etc), and would be dark purple (or maybe light blue). The mechanic itself would be based around two new resources: corruption and vulnerability (both would be shown in the same bar). Corruption would be how corrupted you actually are, and vulnerability would be how much more corrupted you will become the next time you gain it. Vulnerability would be a transparent "extension" of your corruption bar.

Gaining/losing corruption/vulnerability:
At first, both bars would be zero. Whenever you go through a portal (or use a realmstone, if that's too OP), you will gain one point of vulnerability. If you have vulnerability when you go through the portal, you will have corruption points equal to your total vulnerability points added to your corruption bar (you would keep the vulnerability points, and one more will be added). Basically, if you go into a portal with 5 corruption points and 2 vulnerability points, you will end up with 7 corruption points and 3 vulnerability points. Not going into a portal for a long time (maybe an in-game week or so) would start slowly decreasing your vulnerability (but not your corruption). Dying wouldn't decrease corruption or vulnerability. The only reliable way to decrease corruption/vulnerability would be by performing certain actions or using certain items. If you go into a dimension with a full tribute bar for the owner, you will not gain extra vulnerability (but the corruption increase would still apply), and pleasing krasaun before entering a dimension would entirely cancel both the corruption and vulnerability increase.

Effects:
Vulnerability wouldn't have any special effects, but corruption would. The corruption effects would include: hallucinations (some of which could be jumpscares), increased hunger, decreased regeneration, becoming slower, randomly having items fall from your inventory, and becoming vulnerable to the sun (being occasionally blinded by the light or even damaged).

**Comment by Cruuk** [comment]
This all sounds unfun. No thanks

**Comment by Immortallis1** [comment]
I don't think such a mechanic would really work. While it would certainly add to immersion, you have to remember that AoA has already existed for a while and adding a new feature to make it more difficult (especially with the whole keep-the-mod-unconfigurable plan) would screw stuff up.

Betweenlands did something like this but the mechanic was a lot lighter (you just ate like mud balls to stay alive or something) and it was there initially so there were no people getting used to the absence of the mechanic and then suddenly having it shoved down their throats.

**Comment by DiamondWalker** [comment]
I think the betweenlands mechanic you're talking about is decay, which is basically a second hunger bar. Also, AoA had already existed for a while when skills were added. After a bit, people got used to it. The mod's already going through major changes, so I don't think one new mechanic would make the mod impossible or make people hate it.

One thing I should mention: this wouldn't be like the temperature system where you would have no idea it exists until you only have 5 seconds to live. The bar would take a long time to get to dangerous levels (unless you facetank dimensions, which shouldn't be encouraged anyways). It would be something to keep your eye on, but not something you have to deal with immediately. You would have to go into portals many times (maybe about 50 times) for corruption to become a threat. I think this mechanic looks a lot more intimidating than it would actually be because I didn't give any examples of the items that you could use (since I didn't come up with any when I wrote this), but here's a few examples of items that could be available:

An item that decreases corruption

An item that decreases vulnerability

An item that slightly decreases both corruption and vulnerability

An item that make corruption and vulnerability go "dormant" for a certain amount of time (all the corruption effects would be canceled)

An item that turns all your corruption into vulnerability (dangerous since it could make your corruption multiply)

An item that temporarily shields you against gaining corruption

An item that temporarily shields you against gaining vulnerability

The idea is you would have to use these items strategically to keep corruption under control, not being constantly in a race against time against corruption.

**Comment by Immortallis1** [comment]
Honestly now that you put it that way, it feels better. Still no vote for now

**Comment by profilename14** [comment]
I think this could be neat idea, but I don't like the randomly dropping items part as it could potentially be very annoying.

**Comment by Immortallis1** [comment]
Oh, for the record, now that I read it again, randomly dropping items is a terrible mechanic (because you can drop them near fires, or near lava, or near cacti).

**Comment by DiamondWalker** [comment]
The items wouldn't be thrown, just dropped straight down. Still would be an unfair mechanic if you're jumping over lava or something when it happens.

**Comment by Immortallis1** [comment]
but items have a cooldown from when they are throw down to being picked up. If you drop an item while you're sprinting and the item isn't in your hotbar you're not going to notice.

**Comment by vrextachropthus** [comment]
thats a good idea
