### ISSUE TITLE
Foraging at level 65 does not drop certain items

### ISSUE THREAD

**Issue by Etherandir** [Tslat/Advent-Of-Ascension#491]
**Mod Version**
3.0.2

**Describe the bug**
When Foraging reaches level 65, each world does not drop specific minerals, only ingots that do not appear on the wiki.

**Expected behavior**
After Foraging reaches level 65, certain items are rewarded when mining at different dimensions.

**Comment by Tslat** [comment]
This was changed/removed in 1.12.2
More stuff to come

**Comment by Immortallis1** [comment]
@Etherandir current foraging loot table is here
https://adventofascension.gamepedia.com/Foraging

**Comment by Etherandir** [comment]
Thank you a lot. @Tslat @Immortallis1

**Comment by Immortallis1** [comment]
> 
> 
> Thank you a lot. @Tslat @Immortallis1

np
