### ISSUE TITLE
Add portal cooldown configuration

### ISSUE THREAD

**Issue by Etherandir** [Tslat/Advent-Of-Ascension#492]
**Describe/name the existing feature this suggestion relates to**
The portal cooling configuration is missing from the configuration file. Now as soon as the player touches the portal it will teleport to the target dimension, and when it loads to another dimension, the player will be teleported back immediately by the portal, and so on. Especially when I'm playing on a server, this problem often comes up.

**Describe the change or feature you think would be good to see**
I would like the author to add a portal cooldown entry to the configuration, and the player can modify it. You could refer to the Nether Portal's teleport mode.
The reference configuration:
    # Cooldown after using a portal, increasing the value increases the delay until you can teleport again. Measured in ticks (20 ticks = 1 second).
    # [range: 10 ~ 300, default: 100]
    I:"Portal cooldown"=100

**Comment by DiamondWalker** [comment]
Being sent back instantly is a bug. While instant teleportation is intended, being teleported back and forth is a bug. You aren't supposed to be able to use the portal after teleporting until you walk out and back in it.

**Comment by Etherandir** [comment]
Thank you a lot. @DiamondWalker
