### ISSUE TITLE
Server version?

### ISSUE THREAD

**Issue by Etherandir** [Tslat/Advent-Of-Ascension#493]
**Describe the new feature you think would be good to add**
Making a server version of AOA3? Remove the textures and sound effects of AOA3 client version to reduce the burden on the server. Keep the basic logic and functionality to keep the server running. xdd

**Comment by Tslat** [comment]
The server doesn't need to load textures/renderers/other client stuff..

This wouldn't achieve anything except make it much harder to maintain and update the mod
