### ISSUE TITLE
Integration with Environmental Tech

### ISSUE THREAD

**Issue by Flamebom** [Tslat/Advent-Of-Ascension#494]
Integration with the void ore miner from environmental tech would be neat.

**Comment by Tslat** [comment]
Care to explain this at all?

**Comment by Flamebom** [comment]
Sure, Environmental Tech has this multiblock called the void ore miner. The void ore miner creates ore using rf. Some mods (Thermal series) (Nuclear Craft) allow their ores to be picked up from the void ore miner. It would be neat if it could be done with aoa. I'm not how it really works, and it may be up to the environmental tech developer to do integration.

**Comment by Immortallis1** [comment]
isn't this a clone of mfr/industrial foregoing's laser drill (which in-universe mines stuff past bedrock)?

**Comment by Tslat** [comment]
Maybe Environmental tech should use a more flexible method of ore detection rather than relying on mods to explicitly state compatibility

**Comment by Renari** [comment]
Environmental Tech configs allow you to specify what they should generate.
