### ISSUE TITLE
Tinker's Construct support

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#496]
Adding integration for tinker's construct is something that's been talked about for a while now. The biggest issue with this is coming up with unique abilities for all the ores. Here are my ideas:

Amethyst: I'm not sure. Maybe something like looting or increased experience drops?

Jade: The tool losing durability would unlock extra modifiers. Not sure how it would work with repairing

Limonite: idk

Rosite: Using a tool would have a 25% chance to repair it instead of damaging it

Sapphire: For weapons: attack cooldown would be halved if you hit a mob, but doubled if you miss. For mining tools: tool speed would be halved, but would double every time a block is broken. If you stop mining, the combo would instantly reset

Skeletal: Using the tool has a 5% chance to give you one hunger point

Emberstone: For swords: attacking burning enemies would double damage. idk about mining tools

Mystite: idk

Lyon: increased stats depending on missing player health

Varsium: idk

Elecanium: Maybe regens energy when using the item?

Blazium: Attacks inflict enemies on fire and ores are autosmelted when mined.

Ghastly: Maybe same as Emberstone but with poison?

Ghoulish: idk

Lunar: Using item would give night vision?

Baronyte: Maybe using items would increase the item's damage (or speed for mining tools) for a bit?

Shyrestone: idk

Shyregem: idk

**Comment by Sagisolar** [comment]
idk

**Comment by Flamebom** [comment]
It would be cool. Though plusTiC already has amethyst from BoP.

**Comment by Flamebom** [comment]
I would love it though

**Comment by DiamondWalker** [comment]
But plusTiC is an addon. Those traits were balanced around other tinker's construct stuff. If plusTiC traits are stronger than regular tcon, that doesn't mean AoA should try to be match plusTiC gear.

**Comment by Flamebom** [comment]
how about tinker's integration with other mods ie xu2 having demon steel?

**Comment by papabean** [comment]
I personally believe that some of the ideas in the OP are rather nice, but I'd like to suggest a few of my own tool traits/possible traits for each material:

**Supreme!**: Amethyst's main trait; works on any part of the tool (head/extra/tool rod). When an enemy is struck, there is a chance that every mob (except the player) in seven blocks of the struck enemy takes 3 damage.

**Energistic**: One of the two traits for jade tools exclusive to the head part. Mining/breaking blocks in general has a chance to give experience based on the tool type. When the player hits extraction level 70, the chance to gain experience for breaking blocks greatly increases.

**Weaken...ing**: The other trait for jade tools, also exclude for head parts. Damaging an opponent with the tool in question will inflict weakness onto them. When the player uses a melee weapon, the tool must not be in the attack cooldown phase in order for it to be inflicted.

Limonite tools could simply have the same traits as iron tools in normal Tconstruct, seeing that they're essentially just upgraded iron tools.

**Accumulating**: One of two of traits for rosite tools; exclusive to head parts. There is a greater chance for bloodlusts to spawn when the player attacks anything with the tool.

**Ascending**: The other trait for rosite tools; also exclusive to head parts. When essences enter the player's inventory, they automatically get converted into augury experience at a 0.5x multiplier. This means that they will be converted at only half the experience the player would normally be able to muster up via using them on an ascension shrine. This ability can be disabled in a configuration window similarly to some of the abilities in PlusTiC.

Sapphire material abilities in the OP sounds fine enough.

Skeletal material abilities in the OP also sounds fine here.

Emberstone dealing extra damage to burning enemies is on line with the magma slime stuff in standalone TiC, so I suppose that's fine as long as it doesn't stack and gets toned down to something like +42% more damage against burning enemies (compared to the +35% that magma slime's variant has).

That's all I have for now.

**Comment by Tslat** [comment]
Done in 3.3
