### ISSUE TITLE
If the Noticeboard GUI is disabled in config, a chat message should appear when there is an update

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#497]
If the AoA noticeboard is disabled through the config, it might be nice to have a message appear in chat if there is a new update. This allows people to be notified even if they turn off the noticeboard without causing the noticeboard to pop-up again.

Another idea is to have new updates pop-up in chat regardless of whether the noticeboard is enabled or not. This would make the message more noticeable (since people might just close the noticeboard out of instinct without carefully reading), although it somewhat defeats the purpose of the noticeboard which was to reduce chat clutter.

**Comment by Immortallis1** [comment]
I agree. Most mods don't have a noticeboard, and thus they are able to deliver update messages without one.
