### ISSUE TITLE
Blazium tools

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#500]
**Describe the new feature you think would be good to add**
I know plenty of the ingots don't have enough uses, but I chose Blazium for this case because I always thought that if any resource should get a set of non-Extraction tools, it should be Blazium.
It always bugged me that you just sort of stop getting new non-Extraction tools after the early-game dimensions. I know Skeletal tools are powerful, but I believe there are ways around this.

Why not any of the others? Varsium/Elecanium are pretty easy to find.
I also considered Baronyte since Blazium is already used for the Goofy tools, but it's red, and Rosite/Emberstone are already red.
Ok to be honest all those reasons are really stupid, not all ingots need to have 100 different uses. I just chose Blazium because I felt like it and it's the "highest" tiered ore in Barathos.

------------------

Simply put, Blazium tools would have the same efficiency as Skeletal tools, but *maybe* have like 100-200) more durability, making them the overall best tools besides the Extraction tools. (Rosite tools already have like 500 more durability than Skeletal tools so..)

Skeletal tools would still have the advantage of being found in a much earlier dimension, but require the process of finding 4 different ores.
Blazium tools would be better overall and don't require 4 different materials to make the ingot, but are obtained in a later dimension, with said dimension requiring a realm ticket which costs 1 Lunaver coin and 2 Rune stones.
~~Also this sort of alleviates the painful process of getting more Skeletal tools if you lose any you have~~

As you'd expect, Blazium tools would come in a set of a pickaxe, shovel, and axe. As for the damage... Uhh... just have Baron sword be the "base" for the tool damage or something.

Speaking of which, I don't think we really need a "Blazium sword". We already have Baron sword.
Yeah you could argue that's more associated to Baronyte but honestly who cares

**Include any additional background information**
Speaking of Barathos ingots I think Varsium could have another cool use haha https://github.com/Tslat/Advent-Of-Ascension/issues/255

**Comment by Sagisolar** [comment]
I think skeletal should be better than blazium

**Comment by Immortallis1** [comment]
auto-smelt

**Comment by Cruuk** [comment]
> 
> 
> I think skeletal should be better than blazium since its more expensive.

I don't know if it is different from 1.7, but the fragments appear to be more common now.
![image](https://user-images.githubusercontent.com/38159897/54843933-d4c30e80-4c92-11e9-9238-9eaa91fbd21f.png)

Blazium for comparison.
![image](https://user-images.githubusercontent.com/38159897/54844039-181d7d00-4c93-11e9-8631-4559987a1a1c.png)

I know Blazium is also not too rare, but going by the logic of "more expensive", shouldn't Sapphire be the best one then since it's the hardest ore to find in the mod? (even before the unintentional change to make them more rare), yes it's slightly slower than Skeletal and has 1900 durability.

I honestly don't understand the insistence of making Skeletal tools the "best", I can understand the sword, but the fragments seem to be more common now and you only need 3 of each fragment to make enough Skeletal ingots for the pick, and most fragment veins have around 3. If necessary Blazium's rarity can always be increased as well.

And remember that Precasia can be accessed early on while Barathos requires going through Mysterium and Runandor, along with buying a realm ticket.
Skeletal tools would still have their uses of being obtained early on.

**Comment by Immortallis1** [comment]
I agree

**Comment by Immortallis1** [comment]
auto-smelt

**Comment by Tslat** [comment]
Tools and stuff changed in 3.2
