### ISSUE TITLE
Portals not generating.

### ISSUE THREAD

**Issue by jtrent238** [Tslat/Advent-Of-Ascension#503]
**Mod Version**
3.0.2

**Describe the bug**
No portal is generated when entering a dimension. When entering Celeve you spawn in the void due to this.

Currently Tested 
- Iromine
- Deeplands
- Celeve

Running on sponge forge server if that matters.

**To Reproduce**
Go to a dimension

**Expected behavior**
Portal should generate

**Comment by Immortallis1** [comment]
Sponge forge is not supported

**Comment by Ryunari** [comment]
I have also this problem but I use just forge. I spawn near the layer 1 (x=1) and it's really annoying to reach to the islands.

**Comment by Tslat** [comment]
Spongeforge has its own issues that I'm not responsible for

**Comment by Immortallis1** [comment]
> 
> 
> I have also this problem but I use just forge. I spawn near the layer 1 (y=1) and it's really annoying to reach to the islands (in Haven and Celeve, not in Iromine for the moment).

Maybe you're just unlucky, try a different world. From what I know the portal tries its best to spawn on an island but if rng really hates you you might just spawn above the void rather low.
