### ISSUE TITLE
Gyro (and possibly other flying bosses) just fly off due to new flying ai and are impossible to maintain a fight with

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#506]
Encasing the arena in 1-block thick glass works but it's kind of a stupid solution tbh

![gyro1](https://user-images.githubusercontent.com/11131230/54867948-5aab8c00-4d5d-11e9-86eb-5ecc15623fe5.png)
![gyro2](https://user-images.githubusercontent.com/11131230/54867949-5b442280-4d5d-11e9-9d79-902130fe86a7.png)

Eventually he flew below y = 0 and I quit chasing him.

**Comment by Tslat** [comment]
Adjusted this in 3.3.

Re-open this if you think it's still an issue post-3.3
