### ISSUE TITLE
Robbery icon and Hermetism icon are still present in the Skill Master gui

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#507]
**Mod Version**
3.0.2

**Describe the bug**
The robbery icon and hermetism icon are still present in the Skill Master gui.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn in any skill master (Expedition Master, etc)
2. Open up their gui
3. See that the robbery icon and hermetism icons are present

**Expected behavior**
The icons would be either changed to the Engineering/Alchemy icons or flat-out removed.

**Screenshots**

![image](https://user-images.githubusercontent.com/44556728/54868429-c5ab9180-4d62-11e9-92ca-e19f77095940.png)

**Comment by Tslat** [comment]
Fixed in 3.1
