### ISSUE TITLE
NPC gui texture bugs

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#508]
**Mod Version**
3.0.2

**Describe the bug**
Some npcs have minor texture bugs in their gui when trading with them.

Examples:

Gorb Engineer and Gorb Arms Dealer - the right arrow texture is shifted down one pixel more than it should be.

![image](https://user-images.githubusercontent.com/44556728/54868765-68194400-4d66-11e9-8afa-95af003535c8.png)

Professor - inside of right arrow is transparent.

![image](https://user-images.githubusercontent.com/44556728/54868778-93039800-4d66-11e9-84ec-d38202ae8ae2.png)

When the player hovers over the right arrow of certain npcs' guis, the texture under the arrow doesn't match up with the rest of the texture in the gui/the texture changes.

For example:

Lelyetian banker with right arrow not hovered over:

![image](https://user-images.githubusercontent.com/44556728/54868805-e4138c00-4d66-11e9-8b59-3269771eb308.png)

Lelyetian banker with right arrow hovered over: 

![image](https://user-images.githubusercontent.com/44556728/54868808-ed9cf400-4d66-11e9-80aa-530c0b2a0d7b.png)

Seems to affect Lelyetian Banker, Lelyetian Trader, Expedition Master, Toy Merchant, Primordial Banker, Primordial Merchant, Gorb Arms Dealer, Gorb Engineer, and Lelyetian Lottoman (haven't tested on all Skill Masters, Primordial npcs, or Lottomen,).

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn one of the above listed npcs
2. Open their gui
3. In the case that the glitch is visible without hovering over the right arrow, see that the texture is glitched
4. In the case that the glitch only occurs when hovering over the right arrow, hover over the right arrow.
5. See the texture change under the right arrow.

**Expected behavior**
The Gorb Engineer's and Gorb Arm Dealer's guis have their right arrows up one pixel.

The Professor's gui's right arrow is colored in white/not transparent.

In the case of the texture change when hovering over the right arrow, hovering over the right arrow doesn't cause the texture to change.

**Comment by Tslat** [comment]
Had a look into this.. it affects basically every trade gui texture. Ffs.
I'll put it on the list for ursun to get to

**Comment by Tslat** [comment]
Fixed in 3.1
