### ISSUE TITLE
[Bug] Issue with Witchery and Spice of Life

### ISSUE THREAD

**Issue by pingp0nzi** [Tslat/Advent-Of-Ascension#51]
**Mod Version**
What version of the mod are you on?
AoA-Tslat-1.1.3
**Describe the bug**
Witchery player infusions dissapear after changing dimension(entering nether for example)
Spice of Life food history gets reset on every time you log on your map
After examining level.dat and player.dat files i could see that /player/forgedata/playerpersisted gets reset to a state without the witchery or spice of life lines.AoA skills are unaffected
**To Reproduce**
Steps to reproduce the behaviour:
1. Infuse player with infernal animus at altar with Rite of Infusion
2. Enter the nether
3. Try to enthrall any mob
4. Exit nether
The Witchery infusion bar at the left of the screen will have dissapeared and the level.dat file will be reset(infusion lines missing in /forgedata/playerpersisted

**Comment by BlayzerQ** [comment]
Any progress with this issue?

**Comment by Tslat** [comment]
You may need to downgrade to Tslat-1.0 or something similar

One of the newer versions broke file saving, and 1.7.10 is no longer supported (1.7.10 is **over 5 years old**)

If you want updates and bug fixes, use 1.12

**Comment by BlayzerQ** [comment]
> You may need to downgrade to Tslat-1.0 or something similar
> 
> One of the newer versions broke file saving, and 1.7.10 is no longer supported (1.7.10 is **over 5 years old**)
> 
> If you want updates and bug fixes, use 1.12

Can you give a hint to fix this problem? I could fix it myself, with your permission

**Comment by Tslat** [comment]
You can't fix this externally
