### ISSUE TITLE
Some new stuff (ideas for bosses and biomes once the mod goes to 1.13 and some other stuff)

### ISSUE THREAD

**Issue by VBGaming** [Tslat/Advent-Of-Ascension#510]
This title was way too long.

Anyways, I've had some ideas for some stuff in the mod.
First off, I thought that maybe each dimensions should have 2 bosses. The Overworld and the Nether have 2, we'll leave the End alone, the Haven and the Abyss have 2, and Precasia, Iromine and Barathos will soon have 2 two. But aside from the Ancient Cavern and technically Immortallis (and Labricon) the other dimensions only have 1 boss (I'm not accepting Hydrolisk as a boss). I think it would be good to have 2 per dimension. I also thought about some interesting ideas for a boss. You know how everything in Barathos in called Baron something? Well we get to meet the Baroness, but what about the Baron himself? He couldn't be a Barathos boss because we already have 2 of those, but maybe he could be a Runandor boss! I think this because the realmstone for Barathos is obtained from Runandor, and if he was a magician he would fit well in Runandor. Maybe to spawn him you'd need to get something from Barathos first, like something he loves so you can lure him out of his house in Runandor (he could've been exiled from Barathos by the aliens (and don't tell me the mobs in Barathos aren't aliens)).

Aside from that, I'd like new biomes for other dimensions. I think it'd be great if each dimension had at least 3 biomes. Now in the 2.5 snapshot and in Tslat versions, I fekt like the biomes were too small. While I liked them I thought that they just removed the original feeling from the dimension. So I thought that if they could be bigger biomes, maybe you would be able to look in one direction without seeing a totally unrelated place in front of you. I especially think it's essential to add biomes to the Haven, Lunalus and Mysterium, especially if you're planning to add the biome-exclusive mobs, because they had some despite not having any known other biomes. I know you said that you weren't doing biomes before 1.13 but I'd like this to happen once 1.13 has happened.

Some other, unrelated ideas

Since Greckon and Runandor can be a pain to go to, maybe they should have realmstones, but only obtainable from the rare mobs here. I know there was already something like that in older versions but maybe it'd be more stable with a realmstone. If for some reason you want to get rid entirely of the portal tower and make them simple dimensions accessed by realmstone like the others, then the mobs from haunted houses and the runic golems would be good picks for their drops.

How to get the Everland realmstone. If it's added, maybe it could be obtained by pleasing both selyan and luxon three days in a row or something along those lines. Speaking about the Everland...

How to spawn Evercron. There would be three new ores in the Everland : Evergem, Nevergem and Forevergem. To spawn Evercron you'd need to kill a whole lot of mobs all around the place. All mobs would have a 75% chance to drop a Everloot (no idea for the name). 9 Everloots would be crafted into a Impure Ever Totem. Then you can smelt the Impure Ever Totem in a special Everfurnace powered by Forevergems. It would make a Ever Totem. Then you'd need to craft together Evergems and Nevergems to get a Contradictory Gem. Two Contradictory Gems + Seven Ever Totems= Ever Pillar = Spawning item for Evercron.

And that's it. If for some reason you want to ad these stuff to AoA (even though you probably won't), feel free to do so ! Don't give credit to me if you use this if you don't want to, not that'd you do it anyways. One last question : I'm bad at coding. I don't even own AoA. But I want to make a French translation to the mod (I'm french btw). How do I do that?

Again, thanks to you and XolovA for this amazing mod!

**Comment by Tslat** [comment]
Have a read through the instructions on the main page for how to work on the french translation:
https://github.com/Tslat/Advent-Of-Ascension

**Comment by VBGaming** [comment]
So do I just go to the fr_FR.lang and rename everything?

**Comment by Tslat** [comment]
No you go to the french lang file and change the entries (the bits on the right side of the = sign) to their french translated equivalent

https://github.com/Tslat/Advent-Of-Ascension/blob/1.12/fr_fr.lang

See the chinese translation for examples:
https://github.com/Tslat/Advent-Of-Ascension/blob/1.12/zh_cn.lang

**Comment by VBGaming** [comment]
Oh okay that makes sense
I've looked through the page and seems closer to Tslat 1.1.3 tho
There's no full moon event message, hermetism and robbery are still here too
Is it an error or was it supposed to be like that and not adapted to 3.0.2?

**Comment by VBGaming** [comment]
%1$s is something I leave intact?
I gather that it means "player name"

**Comment by Tslat** [comment]
%1$s gets replaced by the variable by the mod. You place it where you would normally see the variable in your language

You're seeing the Tslat-1.13 lang files because you're not in the AoA3 branch.
If you had read the instructions that I had linked, you would understand how to get there

**Comment by VBGaming** [comment]
Oh right, my bad

**Comment by VBGaming** [comment]
Last question (OK this time it's really the last) when the mod updates, if I want to update the translation will I have to find through the 4000+ lines the new stuff or will there be an easier way to find it apart from the rest?

**Comment by VBGaming** [comment]
I found a typo in the english version
Discharge Shot says something like 'Disharge Shot'

**Comment by Tslat** [comment]
When the mod updates, the files get merged.
Just keep working on the files in that spot and you'll be fine

**Comment by VBGaming** [comment]
Why isn't there the Knight's Helmet for Knights's Armor?

**Comment by Tslat** [comment]
There is, it's at line 1542 in the fr_fr.lang for 1.12

If you want to talk further, join the discord server
