### ISSUE TITLE
"Adamant armor" (Sapphire + Rosite)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#513]
**Describe the new feature you think would be good to add**
The concept of an armor set crafted with the 2 most rarest Overworld ores was always such an interesting one to me. And I know the armor set I'm about to suggest may be dumb, but I think it would be the perfect set for the "strongest" Overworld ores.

Adamant armor would be crafted with 14 Rosite + 10 Sapphire in the usual way armor like that is crafted.

23 armor (Helmet: 3, Chestplate: 9, Leggings: 7, Boots: 4)
8 toughness
No set bonus
~10% more durability than the usual durability seen on most sets
Usual durability on most sets
![image](https://user-images.githubusercontent.com/38159897/54876489-eeb53c00-4dcd-11e9-9608-626095d5fd11.png)
(or 22 armor? It already has more dura and toughness than other sets...)

Yeah it would simply be a pure tanking armor, nothing else. I just think it would be wrong for a Sapphire/Rosite armor set to get some gimmicky set effect that makes it forgettable. Having no set effect but just more armor early on would definitely make it notable among the other sets.

Even if it isn't the most useful thing in the world, I'd say it would have uses like being used when you don't want to have your main armor take damage from doing more mundane tasks like grinding. the extra durability would make it a good backbone in "secondary armor sets", even if it is very expensive.

And of course, not every armor set needs to wildly stand out and be useful forever, another reason I made it like this was to sort of "connect" it to Zargonite I guess, with it being an "upgrade" to Adamant for obvious reasons.
(Void/Lyndamyte-->Adamant-->Zargonite?)
I guess you could say it'd stand out by.... not standing out at all...

**EDIT**: I'm not exactly sure what it would *look* like. Maybe red and blue mixed together? In the same way blue and yellow are mixed on Alacrity armor.

**Include any additional background information**
Adamant is a real word. I felt like going with "Adamantite/Adamantium" or whatever would be boring, so I just decided to go with the original word they were based off of. It would fit with other armor sets with names like "Speed" and "Alacrity".

**Comment by DiamondWalker** [comment]
I do think the armor in general is a good idea, but that "make it stand out by not making it stand out" concept doesn't work. Technically, Void and Lyndamyte use that same concept, and they are barely remembered. I actually had a unique idea for a set once, but I couldn't come up with an armor that fit it, but I think this one does. The idea was that pressing a certain key would drain all you energy and either activate "rage mode" or "shield mode" (depending on the key you press). Rage mode would decrease your defense to 0, but you will gain a massive speed boost and increased damage. You would also ignore swing cooldown. "Shield mode" would make it so you can barely move or attack, but you barely take any damage either. It would be useful for regenerating health.

**Comment by Immortallis1** [comment]
ehh if sapphire was easier to get i'd support it better
