### ISSUE TITLE
AoA 3.0.2 crashes on initialization

### ISSUE THREAD

**Issue by rodrigoasfr24022003** [Tslat/Advent-Of-Ascension#514]
I can't even play the mod witout it crashing (and I only have AoA installed).

Log:[initcrash.txt](https://github.com/Tslat/Advent-Of-Ascension/files/3000246/initcrash.txt)

**Comment by Tslat** [comment]
You're probably using a config file from a snapshot version of the mod.
Delete your aoa config file and let it regenerate
