### ISSUE TITLE
Scythes should also be a garderning tool (sorry for bad name)

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#515]
So, if you weren't aware. Scythe isn't just a weapon that the Grim Reaper uses. Its actually a old school gardening/farming tool used for cutting and moving large grass and crops.

Right now Aoa's Scythes are only attacking weapons so It would be nice to make them more like actual Scythes. I know making it a attacking hoe is boring but I can't think of anything else gardening related good. Second thing I could think of is making it chop all crops in a 5x5 radius (I really need to get good at thinking outside of the box).

**Comment by Cruuk** [comment]
AoA doesn't have any hoes yet so hey why not.
