### ISSUE TITLE
Raw/Cooked Charger

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#518]
Basically, all chargers* would drop one Raw Charger, and one Cooked Charger if they're on fire. Due to the omnipresence of Chargers across the overworld, this provides players with some sort of food source in exchange for killing mobs in most biomes. This is especially true for swamps and beaches which don't have a food source yet. It'd also be fun to have especially since Chargers are kind of the overworld's representative mobs.

They would have similar food values to chicken.

*All chargers would drop it, except Ghostly and King charger. Ghostly maybe could drop a "ghostly charger meat" or something (don't think I can texture that lol, also it MAY be superfluous idk).

King charger, due to being rare and large, could drop a super large Charger meat kind of thing, like Hydra chops from TF that fully restore your hunger. I don't exactly know what to do with that either, but the resulting food item should be more rewarding than normal food in some way.

Here's some textures for them I took a bit to make:

16x16 versions:
![raw_charger](https://user-images.githubusercontent.com/11131230/55047908-b22b4f80-501c-11e9-8f09-053df0178296.png)
![cooked_charger](https://user-images.githubusercontent.com/11131230/55047907-b22b4f80-501c-11e9-917b-152248cf57e5.png)

128x128 versions:
![Raw_Charger_128px](https://user-images.githubusercontent.com/11131230/55037560-8d22e680-4ff4-11e9-8dd2-b44273412920.png)
![Cooked_Charger_128px](https://user-images.githubusercontent.com/11131230/55037562-8dbb7d00-4ff4-11e9-9c85-007de555179e.png)

How it appears in-game:
![image](https://user-images.githubusercontent.com/11131230/55038160-54840c80-4ff6-11e9-81a2-5548a35b69e5.png)

![charger_eat](https://user-images.githubusercontent.com/11131230/55038187-6cf42700-4ff6-11e9-893a-56ba16feec1c.png)

Notes:
-Raw chargers should probably give food poisoning, since eating raw real-life poultry and Minecraft chicken does the same. Would basically force you to cook it. Also a nice detail, especially since all AoA food items are safe to eat raw at the moment (although none of them are poultry).
-The drop cannot be affected with Looting because Mojang was high when they made multiple chickens drop from one chicken. It would always drop exactly 1.
-Maybe it's better for the item to be handheld as in the screenshot below, because tell me that holding it like a club doesn't look good.
![image](https://user-images.githubusercontent.com/11131230/55037330-c60e8b80-4ff3-11e9-9125-1455ecdde01c.png)

**Comment by Tslat** [comment]
Just for the effort involved

Consider it done.

**Comment by Cruuk** [comment]
thats epic bro

**Comment by masterbobli** [comment]
Intriguing
