### ISSUE TITLE
Make Baroness and Xxeus have dialogue

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#519]
Make Baroness and Xxeus have dialogue. Not voice acting, but chat messages. They would say different lines when certain things happen (like reaching a certain amount of health). They feel like bosses that could talk (Baroness did talk in 2.5, not sure if she still does) and would actually have a reason for fighting you other than "I want to eat you". It would be more immersive and could be used to add lore (maybe Baroness needs the Warlock Gem for something?)

**Comment by Immortallis1** [comment]
the toys are all alive, and they want to eat the player

**Comment by Sagisolar** [comment]
I will kill you so hard omg - Craexxeus (~when 2.5 comes out~)
