### ISSUE TITLE
Stuck in portals

### ISSUE THREAD

**Issue by Zach0** [Tslat/Advent-Of-Ascension#520]
**Mod Version**
AoA3-3.0.2

**Describe the bug**
Literally cannot leave portal. It teleports to the new dimension the before it can even load immediately back to overworld and repeat until you crash or someone destroys the portal

**To Reproduce**
1. So far portals IroMine and Celeve do not let us escape. Immortalis does

**Comment by Tslat** [comment]
Known bug, has been fixed
