### ISSUE TITLE
Amphibiytes have wacky swimming speed

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#521]
**Mod Version**
3.0.2

For some reason, Amphibiytes go at light speeds while swimming.
Even at max flying speed I can't catch up lol.
![2019-03-27_18 09 54](https://user-images.githubusercontent.com/44548547/55101592-59ab8f00-50bc-11e9-91c9-1564ef704750.png)

**Comment by Tslat** [comment]
Fixed
