### ISSUE TITLE
Female Variants of Mobs and Herds

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#522]
This suggestion is based on another suggestion I made, see it here https://github.com/Tslat/Advent-Of-Ascension/issues/459

So if some mobs like Horndron become neutral, I think it would be a cool idea to make them always spawn in herds. Not only would they just a whole bunch of the same mob, females variants would be around in the herd. The female variants would spawn a lot more than the male (~Chads~). They're also **_a lot_** weaker. To show if its male or female, details like smaller body or horns should be a enough to distinguish between the 2.

One feature that would be cool is attacking one member would make the male go after you. You can also breed a male and a female to make a calf. There should also be a 1/5 chance to produce a male I think.

The reason I think this is a cool idea is because you can actually make a farm out of these types of mobs (like Cows, Sheep, and Chickens) which would be awesome.

~Now excuse me I got to go and defend myself from the angry mob of feminists that are probably at my door because I said the females should be weaker.~

**Comment by DiamondWalker** [comment]
I think that for some mobs the females should be stronger. There are actually species where females are the ones who hunt and are stronger.
