### ISSUE TITLE
Horndron Chops

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#523]
Horndrons should drop multiple raw horndron chops (cooked if on fire). This is because Horndrons are very large, and yet they drop absolutely nothing. Cyclops are thin humanoids but Horndrons are giant wild beasts, so there's just no reason for them to not drop at least food.

Horndrons also have a large mob equivalent in the Hellcat, which happens to drop food. The fact that it drops a food item makes the Hellcat's presence more tolerable.

I made textures for them. Tried to go for a "somewhat fatty pork" kind of look.
16x16:
![raw_horndron_chop](https://user-images.githubusercontent.com/11131230/55115443-e1909980-50ba-11e9-9cda-090ee596bb3d.png)
![cooked_horndron_chop](https://user-images.githubusercontent.com/11131230/55115442-e1909980-50ba-11e9-9ac9-1eabb284b4e5.png)

128x128:
![Raw_Horndron_Chop_128px](https://user-images.githubusercontent.com/11131230/55115448-e5242080-50ba-11e9-84c6-7472c5d33b58.png)
![Cooked_Horndron_Chop_128px](https://user-images.githubusercontent.com/11131230/55115449-e5bcb700-50ba-11e9-81b2-4658a10129f2.png)

Here's an in-game video I took to simulate how this would work in-game.
If it's slightly blurry apologies, took it at a low resolution.
They'd also restore a bit more than they did in the video (copied the charger meat values and forgot to adjust them, but they're "fattier" so).
https://youtu.be/1yWAu8917IU

I don't know if you want to call the cooked version "Cooked Horndron Chop" or just "Horndron Chop". Vanilla MC calls cooked pork "Cooked Porkchop" but cooked beef "Steak". It's not really a big deal anyways.

I'm also not too sure on the stats, like I said above. It should be around vanilla MC Pork level though (i.e. better than furlion chops which are dry and probably not very filling compared to these somewhat fatty horndron chops).

For the record, this will probably be my last food suggestion. Texturing them takes a lot more time than someone like Ursun would take (I think) and there's really not many other Overworld mobs that would sensibly have food drops (loot system would probably find a way to deal with the dimension mobs), especially since if Chargers get a food source there would realistically be a food source in every single overworld biome, except oceans but pinchers are level 93 hunter, fishing/hauling training is a thing, and you can get pam's harvestcraft for calamari from the squids I guess. Jungles too, but neither bush baby or stinger are really "food" mobs, stinger is both thin AND poisonous, and aoa jungle "integration" sucks anyways.

Plains: charger, horndron
Desert: charger, furlion
Forest: charger
Savanna: chimera
Taiga: ursa, natura
Tundra: charger, polar ursa
Mesa: charger (furlion might spawn here don't remember)
Beach: charger
Nether: hellcat

The reason I did this one was because I was encouraged by the positive reception of my last food suggestion, and I happened to have a decent amount of time. But I've just been pushing for this one for a while now (even long before 3.0 was out) since Horndron is very large and could easily drop meat, or hide, or some resource, yet it drops absolutely nothing.

I didn't just decide on the spot to make a random new food item (I was going to do basilisk bacon but I'll leave something like that for the loot system).

**Comment by Sagisolar** [comment]
Making my life easy It seems
