### ISSUE TITLE
I don't know if that's a bug or not

### ISSUE THREAD

**Issue by VBGaming** [Tslat/Advent-Of-Ascension#524]
**Mod Version**
3.0.2

**Describe the bug**
I'm not sure if that's a bug or not, but i was using spawners to make a giant 'zoo' of some kind and my pincher spawner couldn't spawn anything. I tried pretty much everything (specific blocks, heights, light levels, in/out water) yet never a pincher spawned. I'm pretty sure the place was large enough. When i went to a normal world i went to oceans and i didn't see any pinchers anywhere.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to an ocean
2. See there's no pinchers
3. create a 10x10x8 cage underground and fill with water and a pincher spawner
4. Seethere's still no pinchers

**Expected behavior**
I expected Pinchers to spawn in my zoo and naturally.

**Comment by Tslat** [comment]
Fixed in 3.1
