### ISSUE TITLE
Game keeps crashing whenever I'm killing Bugeyes.

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#527]
**Mod Version**
3.0.2

**Describe the bug**
The game crashed whilst ticking entity
Error: java.lang.IllegalArgumentException: bound must be positive

**Comment by EatingSilencer** [comment]
Were you using a sword that had a Looting level? If so, what level of Looting? 
If not, can you post the whole crashlog?

**Comment by Tslat** [comment]
Post the full crash report.

Why do people keep reporting crashes but not providing the file literally made for reporting crashes?

**Comment by mrcakesamurai** [comment]
[crash-2019-03-29_16.40.58-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/3024691/crash-2019-03-29_16.40.58-server.txt)

**Comment by Tslat** [comment]
Has been fixed
