### ISSUE TITLE
I don't know if this is the same bug I posted before about bugeyes.

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#528]
**Mod Version**
3.0.2

**Describe the bug**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  EECore (ExpandedEquivalence-1.12.2-11b.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 3/30/19 12:35 PM
Description: Ticking entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at net.tslat.aoa3.entity.mobs.overworld.EntityBugeye.dropSpecialItems(EntityBugeye.java:75)
	at net.tslat.aoa3.entity.base.AoAMeleeMob.func_184610_a(AoAMeleeMob.java:259)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1197)
	at net.tslat.aoa3.entity.base.AoAMeleeMob.func_70645_a(AoAMeleeMob.java:233)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1023)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
	at net.minecraft.enchantment.EnchantmentThorns.func_151367_b(EnchantmentThorns.java:49)
	at net.minecraft.enchantment.EnchantmentHelper$HurtIterator.func_77493_a(EnchantmentHelper.java:465)
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:124)
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:134)
	at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:168)
	at net.minecraft.entity.Entity.func_174815_a(Entity.java:2936)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:135)
	at net.tslat.aoa3.entity.base.AoAMeleeMob.func_70652_k(AoAMeleeMob.java:186)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at net.tslat.aoa3.entity.mobs.overworld.EntityBugeye.dropSpecialItems(EntityBugeye.java:75)
	at net.tslat.aoa3.entity.base.AoAMeleeMob.func_184610_a(AoAMeleeMob.java:259)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1197)
	at net.tslat.aoa3.entity.base.AoAMeleeMob.func_70645_a(AoAMeleeMob.java:233)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1023)
	at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:70)
	at net.minecraft.enchantment.EnchantmentThorns.func_151367_b(EnchantmentThorns.java:49)
	at net.minecraft.enchantment.EnchantmentHelper$HurtIterator.func_77493_a(EnchantmentHelper.java:465)
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:124)
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:134)
	at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:168)
	at net.minecraft.entity.Entity.func_174815_a(Entity.java:2936)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:135)
	at net.tslat.aoa3.entity.base.AoAMeleeMob.func_70652_k(AoAMeleeMob.java:186)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: aoa3:bugeye (net.tslat.aoa3.entity.mobs.overworld.EntityBugeye)
	Entity ID: 280
	Entity Name: Bugeye
	Entity's Exact location: 83.40, 61.00, -140.83
	Entity's Block location: World: (83,61,-141), Chunk: (at 3,3,3 in 5,-9; contains blocks 80,0,-144 to 95,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.04, 0.40, 0.45
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Creative
	All players: 1 total; [EntityPlayerMP['mmldiamonds'/438, l='Creative', x=83.00, y=61.00, z=-142.54]]
	Chunk stats: ServerChunkCache: 458 Drop: 0
	Level seed: -1756893905469140523
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,minecraft:stone,5*minecraft:air,51*minecraft:stone,2*minecraft:dirt,minecraft:grass;1;village(size=900),decoration,lake,lava_lake
	Level spawn location: World: (90,4,-96), Chunk: (at 10,0,0 in 5,-6; contains blocks 80,0,-96 to 95,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1561584 game time, 2016532 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 18521 (now: true), thunder time: 113191 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2659934288 bytes (2536 MB) / 5977931776 bytes (5701 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 37
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 99 mods loaded, 99 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                             | Signature                                |
	|:------ |:-------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                  | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2815.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2815             | forge-1.12.2-14.23.5.2815.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | uncraftingtable      | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar                | None                                     |
	| LCHIJA | aoa3                 | 3.0.2                    | AoA3-3.0.2.jar                                     | None                                     |
	| LCHIJA | applecore            | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
	| LCHIJA | jei                  | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJA | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| LCHIJA | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | avaritia             | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar             | None                                     |
	| LCHIJA | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | thaumcraft           | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LCHIJA | botania              | r1.10-360                | Botania r1.10-360.jar                              | None                                     |
	| LCHIJA | avaritiatweaks       | 1.12.2-1.1               | AvaritiaTweaks-1.12.2-1.1.jar                      | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | betteradvancements   | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar             | None                                     |
	| LCHIJA | betterbedrockgen     | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar              | None                                     |
	| LCHIJA | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
	| LCHIJA | betterquesting       | 3.5.296                  | BetterQuesting-3.5.296.jar                         | None                                     |
	| LCHIJA | bqt                  | 1.0                      | BetterQuestingTriggerer-1.0.jar                    | None                                     |
	| LCHIJA | bibliocraft          | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA | bloodmoon            | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bookshelf            | 2.3.574                  | Bookshelf-1.12.2-2.3.574.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | redstoneflux         | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | brandonscore         | 2.4.9                    | BrandonsCore-1.12.2-2.4.9.195-universal.jar        | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
	| LCHIJA | chisel               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LCHIJA | classiccombat        | 1.0.0                    | ClassicCombat-1.12-1.0.0.jar                       | None                                     |
	| LCHIJA | clumps               | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
	| LCHIJA | crafttweaker         | 4.1.15                   | CraftTweaker2-1.12-4.1.15.jar                      | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                           | None                                     |
	| LCHIJA | twilightforest       | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
	| LCHIJA | tconstruct           | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                   | None                                     |
	| LCHIJA | conarm               | 1.2.3                    | conarm-1.12.2-1.2.3.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | extendedrenderer     | v1.0                     | coroutil-1.12.1-1.2.30.jar                         | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.30            | coroutil-1.12.1-1.2.30.jar                         | None                                     |
	| LCHIJA | configmod            | v1.0                     | coroutil-1.12.1-1.2.30.jar                         | None                                     |
	| LCHIJA | craftpresence        | v1.4.9.9                 | CraftPresence-1.12.2-1.4.9.9.jar                   | eca02c6a597321ad22340897683951ba5c76720a |
	| LCHIJA | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.15.jar                      | None                                     |
	| LCHIJA | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.15.jar                      | None                                     |
	| LCHIJA | cucumber             | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LCHIJA | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | darkutils            | 1.8.223                  | DarkUtils-1.12.2-1.8.223.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | deathquotes          | 1.2.0                    | DeathQuotes-1.2.0-mc1.12-forge.jar                 | None                                     |
	| LCHIJA | draconicevolution    | 2.3.20                   | Draconic-Evolution-1.12.2-2.3.20.333-universal.jar | None                                     |
	| LCHIJA | dynamictrees         | 1.12.2-0.9.4             | DynamicTrees-1.12.2-0.9.4.jar                      | None                                     |
	| LCHIJA | dynamictreestc       | 1.12.2-1.4.1e            | DynamicTreesTC-1.12.2-1.4.1e.jar                   | None                                     |
	| LCHIJA | eplus                | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | hammercore           | 2.0.4.2                  | HammerCore-1.12.2-2.0.4.2.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | projecte             | 1.12.2-PE1.4.0           | ProjectE-1.12.2-PE1.4.0.jar                        | None                                     |
	| LCHIJA | expequiv             | 11b                      | ExpandedEquivalence-1.12.2-11b.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | extrautils2          | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | ezstorage            | 2.5.0                    | ezstorage-2.5.0-[1.12.2].jar                       | None                                     |
	| LCHIJA | forestry             | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                      | None                                     |
	| LCHIJA | gardenofglass        | sqrt(-1)                 | GardenOfGlass.jar                                  | None                                     |
	| LCHIJA | gravestone           | 1.10.1                   | gravestone-1.10.1.jar                              | None                                     |
	| LCHIJA | ichunutil            | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | inventorypets        | 1.5.3.1                  | inventorypets-1.12-1.5.3.1.jar                     | None                                     |
	| LCHIJA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest            | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                    | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zb.jar                    | None                                     |
	| LCHIJA | jehc                 | 1.12.2                   | JEHC-1.12.2-1.6.2.0.jar                            | None                                     |
	| LCHIJA | jeiintegration       | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar                 | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                        | None                                     |
	| LCHIJA | jeresources          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar            | None                                     |
	| LCHIJA | magicbees            | 1.0                      | MagicBees-1.12.2-3.1.10.jar                        | None                                     |
	| LCHIJA | mysticalagriculture  | 1.7.3                    | MysticalAgriculture-1.12.2-1.7.3.jar               | None                                     |
	| LCHIJA | matc                 | 1.0.1-hotfix             | matc-1.0.1-hotfix.jar                              | None                                     |
	| LCHIJA | mcjtylib_ng          | 3.1.1                    | mcjtylib-1.12-3.1.1.jar                            | None                                     |
	| LCHIJA | morph                | 7.1.3                    | Morph-1.12.2-7.1.3.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mousetweaks          | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
	| LCHIJA | mysticalagradditions | 1.3.1                    | MysticalAgradditions-1.12.2-1.3.1.jar              | None                                     |
	| LCHIJA | neat                 | 1.4-17                   | Neat 1.4-17.jar                                    | None                                     |
	| LCHIJA | nei                  | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | oreexcavation        | 1.4.137                  | OreExcavation-1.4.137.jar                          | None                                     |
	| LCHIJA | plustic              | 7.0.5.2                  | plustic-7.0.5.2.jar                                | None                                     |
	| LCHIJA | projecteintegration  | 1.12.2                   | ProjectEIntegration-1.12.2-1.5.0.jar               | None                                     |
	| LCHIJA | questbook            | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                           | None                                     |
	| LCHIJA | bq_rf                | CI_MOD_VERSION           | RFExpansion-3.4.28.jar                             | None                                     |
	| LCHIJA | rftools              | 7.61                     | rftools-1.12-7.61.jar                              | None                                     |
	| LCHIJA | rftoolsdim           | 5.64                     | rftoolsdim-1.12-5.64.jar                           | None                                     |
	| LCHIJA | scenter              | 1.12-3.11.0              | scenter-1.12.2-3.12.0.jar                          | None                                     |
	| LCHIJA | shearmadness         | 1.12.2                   | shearmadness-1.12.2-1.7.2.4.jar                    | None                                     |
	| LCHIJA | solarflux            | 4.32r                    | SolarFluxReborn_1.12.2-4.32r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | bq_standard          | 3.4.154                  | StandardExpansion-3.4.154.jar                      | None                                     |
	| LCHIJA | tc6aspects4jei       | 0.0.2a                   | tc6aspects4jei-0.0.2a.jar                          | None                                     |
	| LCHIJA | tcinventoryscan      | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar         | None                                     |
	| LCHIJA | thaumicjei           | 1.2.1                    | ThaumicJEI-1.12.2-1.5.5-23.jar                     | None                                     |
	| LCHIJA | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJA | tmel                 | 1.12.2-1.3.2.2           | tmel-1.12.2-1.3.2.2.jar                            | None                                     |
	| LCHIJA | torohealthmod        | 1.12.2-11                | torohealth-1.12.2-11.jar                           | None                                     |
	| LCHIJA | wailaharvestability  | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
	| LCHIJA | flymod               | 1.0                      | walaryneflymod-1.12.X-1.0.1.1.jar                  | None                                     |
	| LCHIJA | wanionlib            | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                           | None                                     |
	| LCHIJA | wawla                | 2.5.269                  | Wawla-1.12.2-2.5.269.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | waystones            | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                        | None                                     |
	| LCHIJA | weather2             | 1.12.1-2.6.12            | weather2-1.12.1-2.6.12.jar                         | None                                     |
	| LCHIJA | worldedit            | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar  | None                                     |
	| LCHIJA | unidict              | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                           | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
EECore (ExpandedEquivalence-1.12.2-11b.jar)
  com.zeitheron.expequiv.core.EETransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 2054 names; 5923 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Expanded Equivalence (expequiv) @11b

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['mmldiamonds'/438, l='Creative', x=83.00, y=61.00, z=-142.54]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Immortallis1** [comment]
what armor are you using
does it have thorns
what sword are you using
does it have looting
