### ISSUE TITLE
NPC's should stay frozen.

### ISSUE THREAD

**Issue by centhusiastx2** [Tslat/Advent-Of-Ascension#529]
**Describe/name the existing feature this suggestion relates to**
I was in Dustopia, and I finally found a Primordial Village, but all of them are running away from the village and they're never coming back! By the time I return to the village there's nobody there.

**Describe the change or feature you think would be good to see**
I want the NPC's to stay in their location they're spawned in.

**Add any alternative implementations you think might work**
Nope.

**Comment by Cruuk** [comment]
NPCs staying perfectly still was always kind of dumb and unnatural. It's nice to see them walk. Makes them more villager-like.

Though I do understand the concern of structure NPCs wandering away from their structure, it annoys me a little bit as well so it would be nice for them to always stay near their structure in the same way vanilla Villagers do (I think).

**Comment by Immortallis1** [comment]
the reason they walk away from the dustopian structure is because the walls are non-existent. Changing it slightly to have somewhat higher walls would probably fix that
