### ISSUE TITLE
Make Lunar ingots be used for upgraded repairing

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#533]
Rosite is used to repair most AoA items, except lunar armor, which is repaired with lunar ingots. This might be unique, but it feels weird to have one armor have a unique method of repair. However, it gave me an idea. Like most ingots, lunar ingots don't have too many uses. What if they could be used as an upgraded substitute to rosite in an anvil? It would make sense, since it's literally upgraded rosite. Repairing items with it in an anvil would repair the item to max durability, but magic mending solutions would still be better to avoid damaging an anvil.

**Comment by Immortallis1** [comment]
To be honest when people use MMS they're probably not worried about damaging the anvil. They're probably worried about using XP or permanently increasing the XP cost of repair
