### ISSUE TITLE
Nethengeic Rework

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#534]
Currently, there are quite a few issues I see with the way obtaining the Nethengeic stuff works. First, you have the issue where Nethengeic Wither is a mid/late game rematch of the wither (in my eyes at least), but you are most likely not going to fight the wither in AoA. There's a few other problems, such as:
Nethengeic items being extremely grindy to obtain
Nethengeic beasts having insane amounts of drops (more than basically every boss)
The summoning method of the Nethengeic Wither basically being a downgrade to the wither's unique summoning method.

I think the way nethengeic stuff is obtained should be changed.

I would start off by making the beasts no longer drop the armor, slugger, and sword (and straight up deleting the callstone from the mod). Instead, those drops would be replaced with a new mechanic: if a nether star is on the ground near a nethengeic beast, the beast will walk to it and eat it. Eating the nether star would buff the beast, giving him a damage-reducing shield, increasing its damage, and giving it health regen (basically, that nethengeic beast will turn into a mini-boss). The buffed beast would drop a Nethengeic Star.

Like a regular nether star, the nethengeic star would only have one use: crafting a new utility table (maybe called the nethengeic altar?). This table would have 2 or 3 uses: turning emberstone ingots into nethengeic ingots (used for crafting the nethengeic items), turning wither skeleton skulls into nethengeic skulls (you can probably see where this is going), and (possibly) "upgrading" nether bricks into a different decoration block.

Summoning the nethengeic wither would be similar to that suggestion cruuk made a while back, but with two changes: nether wart blocks would be used instead of barathos hellstone and the structure you have to build would look like this:

     S        S
S   N   S   N   S
N  N   N   N  N
     N        N

S = Nethengeic Skulls
N = Nether wart blocks

The Nethengeic wither itself should probably get a rework to make it more challenging and unique, but I can't come up with anything.

**Comment by Immortallis1** [comment]
where would you get the armor, sword, and slugger then? lol

**Comment by Immortallis1** [comment]
Normal wither is a bit hard to fight with only AoA installed. Perhaps AoA can add something that makes the wither somewhat easier to spawn.

**Comment by DiamondWalker** [comment]
Drop coins, banners, gems, and upgrade kit. Maybe they should keep the slugger.

Anyways, I just noticed the layout I made for the summoning structure didn't work. I'll have to upload a pic or something.
