### ISSUE TITLE
Amphibiytes Hit You 3 Blocks Away and Through Walls

### ISSUE THREAD

**Issue by Thorson123** [Tslat/Advent-Of-Ascension#535]
**Mod Version**
3.0.2

**Describe the bug**
I think this is a bug because they didn't do this before and that is that Amphibiytes hit you when your 3 blocks away from it. Also they hit you through walls most commonly found if your one block lower then it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spawn an Amphibiyte
2. Change to Survival Mode
3. Notice that they hit you when your a couple blocks away from it

Steps To reproduce the Amphibiyte hitting you through walls:

1. Make a cage
2. Spawn an Amphibiyte in the cage
3. Outside the cage go down one block lower then the Amphibiyte
4. Go up to the Cage
5. Notice how it hits you

**Expected behavior**
I expect that the Amphibiyte hits you when your close to it and that it can't hit you when your on the other side of a wall.

**Screenshots**
![2019-04-03_19 31 39](https://user-images.githubusercontent.com/49259342/55525806-5b8aca80-5647-11e9-85f1-1e1612141912.png)
![2019-04-03_19 37 01](https://user-images.githubusercontent.com/49259342/55525933-e4a20180-5647-11e9-9cfb-be720a145c77.png)

**Comment by Tslat** [comment]
Fixed in 3.1
