### ISSUE TITLE
Missing Toyland

### ISSUE THREAD

**Issue by jredfox** [Tslat/Advent-Of-Ascension#538]
Entities found here: https://twitter.com/MCXolova/status/658026631093579776
I can't look forever but, I recall a screenshot of an actual toy dimension or talk of it by xolova maybe he gave you the WIP maybe he didn't but, I am pretty sure of it

**Comment by Tslat** [comment]
Playtopia* is the correct name.
And it's already on the planned features list, but is a very low priority

**Comment by jredfox** [comment]
ok I would keep it open as enchantment but, maybe you have a separate list for those thanks anyways

**Comment by Tslat** [comment]
Enchantment...?

**Comment by jredfox** [comment]
yes an enhancment isn't a bug or issue but, is a feature or change that is reuqested often used on github issues. sometimes they are necessary to fix bugs other times they are plain out features

**Comment by quat1024** [comment]
s/enchantment/enhancement/g

**Comment by jredfox** [comment]
https://searchwindowsserver.techtarget.com/definition/enhancement don't comment unless you know what your talking about @quat1024

**Comment by Immortallis1** [comment]
because "enchantment" is totally "enhancement"

**Comment by Immortallis1** [comment]
> 
> 
> https://searchwindowsserver.techtarget.com/definition/enhancement don't comment unless you know what your talking about @quat1024. This is also very wildly used on github as not all enchantments are not suggestions

because "enchantment" is totally "enhancement"
