### ISSUE TITLE
New Candyland Edibles

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#54]
**I made another post (#55) for the rare drops (the ones existing already in the game) becoming edible. I didn't really want to make one super long post for all of them.**

So Candyland is literally made up of edible blocks...except none of them are edible. This is a large disappointment and missed opportunity for an immersive dimension. The rest explains itself.

**But this makes food too easy to obtain!** The only real complaint I can see. But let's be honest here. We have trades like Primordial Banker giving a full stack of raw beef (coal is an extremely common foraging reward by the way). We also have melons which you will find if you go to a jungle, necessary for Precasia. If a zombie drops potatoes/carrot you can make a large farm, etc. Making edible blocks isn't going to really change anything, especially if they aren't very saturating **Melons, for example, are available in vast quantities but ultimately require you to eat vast quantities in turn.** The same applies here but **it's actually a bit less convenient** because you can't have a Chocolate or Cotton Candy farm outside of your house, you have to go to the dimension to get them, which requires a bit more work and is more dangerous than just sitting in your little fence enclosure wasting your sword durability on melons. The tradeoff is that it's  **significantly easier** to get food **INSIDE** the dimension, and take it out if you please, **possibly stockpiling** if you're short on realmstones/portals (which is what you would do in real life, face it).

**This is a bad influence on kids!** OK, this was more of a joke counterargument on Xolova's part but let's be real - in this game you can eat decaying formerly-human flesh (albeit as an emergency food), you can eat spider eyes, and you can eat 100% raw freshly killed chicken without anything more than a slight hunger effect. Even if you scale Minecraft days to be 10 minutes long real salmonella poisoning is much longer and much more severe than it is in the game. And of course, vanilla Minecraft has its own share of "healthy" edibles too, such as apples and carrots and melons, the latter two requiring significantly less work than meats, and being much more worthwhile than rotten flesh and spider eyes. Finally, the future Gardencia edibles suggestion would almost certainly provide counterbalance to this nonexistent problem.

-----------------------------------------

**BLOCK EDIBLES:**

All of the following items are crafted from blocks that already exist. The recipes are irreversible, but that's OK because the blocks are renewable (except rock candy but I'll suggest a mob that drops it someday).

NOTE: **A melon has 1.2 saturation.** Using it as a benchmark, because as I said you have to eat a lot of melons to keep up your hunger bar in exchange for how many you get once you reach a jungle/find seeds somewhere.

**This fills 1.5 meat shanks/3 hunger points, and have a saturation of 1.5.**
Gingerbread (block) -> Ginger Crisp x2*
White/Milk/Dark Chocolate -> White/Black/Dark Chocolate Piece x2

**The following fill 1.5 meat shanks/3 hunger points, and have a saturation of 1.2.**
Licorice (block) -> Licorice x2
Red/green/white candy block -> Red/green/white Candy Piece x2 
Marshmallow (block) -> Marshmallow x2

**The following fill 0.5 meat shanks/1 hunger point, and have the saturation value of 1.**
Purple/green/pink/blue Rock Candy -> Purple/green/pink/blue Rock Candy Crystal x4
Pink/blue Cotton Candy -> Pink/blue Cotton Candy x4

*Ginger crisp is NOT the cookie used to make the treat bag. That one has magical icing or whatever. This is more like a piece of pure gingerbread. The treat bag candies cannot be crafted, only dropped as they are currently.

I sorted them out based on how they are in real life. The ones at the bottom are literally just concentrated sugar, the ones in the middle are concentrated sugar with slightly more stuff added, and the ones at the top are the most filling (ginger cookies have flour and whatever and chocolate has cocoa, milk, sugar, etc.).

----------------------------

**S'MORES**: 

**EDIT: Thinking of suggesting something where you start with an "Uncooked S'more", and then you hold it near a campfire and it becomes cooked, or you can just cook it in a furnace to get the cooked variant. Unsure of the technical specs so I'll just leave this as a note for now.**

A novelty item, but a useful one should you get it, since all the materials are relatively easy to obtain. 
I know they're usually made with graham crackers but we don't have those so we use the next best thing: gingerbread cookies.

**Fills 3 meat shanks/6 hunger points, and has a saturation value of 2.5.**
Ginger crisp x2 + marshmallow (item) + black/dark chocolate piece (shapeless) -> S'mores x1

**Comment by Sagisolar** [comment]
Hmm this is a good suggestion.
