### ISSUE TITLE
Runium Ore smelting

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#541]
I have found out on the 1.12 version of Nevermine that Runium Ore (Overworld version) will smelt into charged runium if done so in a mechanical furnace (MineFactoryReloaded). My only guess is that the electricity used to power the furnace charges the runium, however this make progression more difficult unless using the vanilla furnace. Can you please figure out why this occurs and fix it?

**Comment by Tslat** [comment]
Not an issue from my side. Take this to MineFactoryReloaded
