### ISSUE TITLE
Boss Summoning Animations

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#542]
Summoning the bosses in Nevermine is a bit risky because it is immediate giving the player very small time to react and retreat to engage properly. This can get a bit boring sometimes as it is immediate.

I think that having an animation of the bosses above their respective spawn structures, and their health bar fill up similar to the wither, and them being brought into existance would be cool. Also I think the respective boss' music should start at this point.

I currently have no brilliant suggestions for the animation but if you could have them being built up from the 'pixels' they are made from would work reasonably well.

If you do consider it, a good source of code can be seen with the Guardian of Gaia from the Botania Mod.

**Comment by Tslat** [comment]
This has been done in a bunch of bosses as of 3.2
