### ISSUE TITLE
Crystevia Rework

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#543]
Crystevia needs a rework. My only experience with it was back on Armakeen's server since I needed to fight Crystocore for some reason (I don't remember why. I think I wanted one of his drops for skeletal army), and it made me want to never go back to it. First is finding the structures needed (you need to find the correct crystal transfer stations, then the crystal trader, and the Crystocore platform if you want to fight him). You then have to get a bunch of crystals (880 for all the items), which would ok-ish, but you also only have a 1/8 chance of getting a crystal from each gemstone, which leaves you needing an average of 7040 gemstones (not considering you might be unlucky). Even if you only want to fight Crystocore, you need about 640 gemstones to fight Crystocore _**ONCE**_ (good luck getting the drop you want). It took me days before I could get everything, and I can't even remember if I could even fight Crystocore before the server closed because of how long it took. To make things worse, all of this trouble is only for a few items that are rarely used and a boss that is probably one of the most boring and uninteresting fights in the game (it looks cool... and that's about it).

The first thing I would do is remove gemstones and the crystal transfer structures. Just make the crystals be obtained directly. Gemstones do nothing other than overcomplicate the process and make it even more frustrating to get what you're looking for. The other thing I would do is make the crystal trader sell crystals for twice the price at which he buys them (why does he want Crystals anyways if he doesn't use the items). All the weapons and the armor currently sold by the crystal trader would be moved to a new system (except Giant Crystal, which would be deleted).

The new system would be based around a new structure: the "Crystal Charging Station". This structure would replace the Power Station. It would be an enclosed room with four doorways out. Inside, there would be 7 tables: one in the middle and 6 around it. Each of the 6 outer ones would represent a different one of the crystal colors. This new structure would be used for crafting, as well as a unique way of summoning Crystocore.

The 6 outer tables of the Crystal Charging Station can be charged by using 10 crystals of the respective color on them. After you charge one or more of the outer tables, you can right click the center table. Depending on which tables you charged, you would would get a specific item (the crystal trader items mentioned before). Each item would have a unique recipe. If you charge all the tables, the center table will spawn Crystocore on top of it when used. If you fail to recreate any of the recipes, the center table will only cause an explosion when used and waste the other tables' energy.

Crystocore himself would also get a revamp. When spawned, he would create a force field in the doorways so the player is trapped in the room. He would change colors like he currently does, but instead of inflicting a specific debuff on you, they would change his AI. The colors and their effects  would go like this:
Yellow = He gets a large speed boost
Blue = He would start "bouncing" around the room (see sun spirit from Aether legacy)
Purple = He would shoot a consistent laser beam at you.
Grey = He occasionally teleports and comes from another direction (like Visualent)
Red = He would get a large damage boost
Green = He starts shooting the construct of terror projectiles
When he is "killed", he would not die, and would instead become invulnerable and start healing. Once he heals fully, he would enter his second phase.

In his second phase, he would flash through all his colors (like this bug Scimiguy posted on the discord once).
![ha3Fuq1yt5](https://user-images.githubusercontent.com/19913710/55542201-864f4000-5694-11e9-8f28-35ab2203d593.gif)
He would start using an AI that is basically a mix of all the previous ones: he would move quickly, bouncing off of walls and dealing high damage on hit. During all of this, he would fire a consistent beam at you, meaning you have to move in circles around him at all times, and fire bursts of construct of terror projectiles in all directions. He would also sometimes teleport. When he reaches half health his third phase would start.

In his third phase, he would lose his arms and gain a shield (similar to a charged creeper) that makes him invulnerable. He would fly to the center table and start hovering over it. There, he would start spamming rainbow projectiles in all directions. He would also fire 6 beams to the 6 outer tables, and start charging them. It would take him about 20 seconds to charge them, after which you have 10 seconds to right click on the central table (the one under him. If you right click on it, it will fire a projectile upwards that breaks his shield. If you don't, he'll drain energy from it and heal for 500 hp. If you break his shield. he would fall on the table, vulnerable and stunned. He would not change colors during this time. You would have 10 seconds to deal as much damage to him as possible before he regains his shield and the pattern repeats.

**Comment by Immortallis1** [comment]
I feel like the flashing could cause epilepsy at worst and be just plain annoying at best. Haven't evaluated the mechanics yet

**Comment by DiamondWalker** [comment]
Then the speed at which it changes colors could be decreased to about the speed of Evercron's phase 2 screen effect.

That's only like 1% of the suggestion though.
