### ISSUE TITLE
Invisible mobs

### ISSUE THREAD

**Issue by Dimaster54** [Tslat/Advent-Of-Ascension#544]
**Mod Version**
What version of the mod are you on?
3.02

**Describe the bug**
Often, Invisible mobs spawn. I see them with the damage indicator of the better pvp mod but I I don’t see them in game and I can’t seem to hit them either but they can damage me.

**To Reproduce**
Steps to reproduce the behaviour:
It happens randomly when I’m exploring the world or traveling.

**Expected behavior**
An invisible mob without hitbox that damages me. I can see that they’re there because of the damage indicator of better pvp mod. It only happend with advent of asension mobs.

**Screenshots**
I’ll add a screenshot next time it happens

**Comment by Tslat** [comment]
Can you test this without other mods present? Particularly optifine and spongeforge

**Comment by Ryunari** [comment]
Are you using Optifine ? I had the same problem and I used Optifine but when I removed this, the mobs return to normal.

**Comment by Dimaster54** [comment]
Ok I’ll try it. Thank you

**Comment by Ryunari** [comment]
You're welcome.

**Comment by Tslat** [comment]
Closing this for now since I've had no followups
