### ISSUE TITLE
Greatsword Holding 

### ISSUE THREAD

**Issue by EnderYTV** [Tslat/Advent-Of-Ascension#545]
**Mod Version**
AoA3-3.0.2

**Describe the bug**
Okay basicly https://i.imgur.com/CCyH37o.png
You hold the Greatsword (all greatswords) by the blade insteed of the handle.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Advent Greatblades'
2. Click on one of the swords
3. Click f5 and go back to first person and you'll see you hold the sword by the blade insteed of the handle

**Expected behavior**
You should hold the greatsword by the handle when your in first person

**Screenshots**
https://i.imgur.com/CCyH37o.png

**Comment by DiamondWalker** [comment]
That picture shows you holding the sword by the handle... The blade is the red and white part.

**Comment by Tslat** [comment]
What Diamond said..
I think you're confusing the pommel for the handle

**Comment by Tslat** [comment]
Closing this since I've had no followup
