### ISSUE TITLE
Nethengeic Wither shader

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#546]
The Nethengeic Wither should have a stronger, red version of the wither shader.

**Comment by Tslat** [comment]
What is the wither shader?

**Comment by Sagisolar** [comment]
I've never been more confused with a suggestion ever

**Comment by Cruuk** [comment]
Maybe he's talking that gray filter the vanilla Wither sort of puts in the sky when spawned?
![image](https://user-images.githubusercontent.com/38159897/55624459-d2fd4e80-575a-11e9-9812-f3de96e9eaf5.png)
Besides that I got nothing

**Comment by DiamondWalker** [comment]
I did mean what Cruuk was talking about. I never realized it was just the sky, I always thought it was the entire screen. In that case, it wouldn't really work in the nether.
