### ISSUE TITLE
Night Vision Goggle Rework

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#547]
I thought this up because I want to switch from Ender IO end steel armor to zargonite armor but I don't want to give up on the toggleable night vision from the latter.

Night vision goggles. Basically, you spend elecanium and rosite to get goggles that give you night vision when equipped. Not too bad, right?

Well, first, the goggles take up the helmet slot. Not too bad at first glance, since the effects still stack, but the protection on the goggles is less than any decently strong helmet would give.

Then, you can't toggle the night vision. If you want to see in the dark for some reason (maybe for atmosphere or to determine where mobs spawn), you have to just take them off.

Finally there's that ugly green shader that it applies. The Minecraft/AoA world is filled with magic and night vision potions and the best we can do is keep it with a green shader? That's stupid.

Maybe for a weak early game item these would be passable, but night vision goggles require a good amount of work to get. You need to get to Barathos which means that you need to get lunaver (grind a LOT of shit), which requires getting a banker (not found in Mysterium, so Lunalus, Lelyetia, or Creeponia), then find the runic dungeon and get a couple rune stones, then go find Dumbledore in his little tower, then go enter Runandor and grind some more (although admittedly not nearly as much as for the lunaver). Then you go into barathos and mine, and then throw out another three of your precious rosite ingots (which also take a good bit of mining) just to make this thing. 

As a result, they are underwhelming. Night vision goggles aren't a reason you go to Barathos. Night vision goggles are a thing you get while going to barathos that you happen to make just for completion's sake because you have a couple extra elecanium left over. They're a niche item and it's not a very good niche at that.

There is almost no reason to use these things over extended night vision potions in practice.

I propose that night vision goggles are reworked to solve these issues.

--------------------------

**Remove the green shader:**
Come on. We live in a world with night vision potions and enchantments. We've found many boxes that magically create mobs out of thin air. We came from a world inside rabbit creatures' MINDS. We went through a world of rune magic (that has very little runes but that's another issue). And the best we could do is make night vision goggles with a green overlay?

I mean, I get the attempts at realism, but in practice it's just ugly. You can maybe add a way to remove the green shader and keep it by default, but that takes more work, and I highly doubt the amount of people that actually want the green shader is enough to warrant it anyways.

**Make night vision toggleable:**
As I said before, it would be nice to have a key to apply/remove the night vision effect without actually taking off the armor, which takes more time and is annoying especially if you have a full inventory. 

I did some research and I'm not sure that turning off real-life night vision goggles without taking them off is actually practical, but again, this is Minecraft and I'd rather have something that's somewhat unrealistic but useful and than something more realistic but useless. I mean rosite and elecanium aren't even real lol
![image](https://user-images.githubusercontent.com/11131230/55637075-43739200-5792-11e9-8cf5-111f7107721b.png)
![image](https://user-images.githubusercontent.com/11131230/55637126-5b4b1600-5792-11e9-83a3-6eb8fe832325.png)
<s>petition to rename the mod "Age of Ascension"</s>

**Allow Night Vision goggles to be combined with helmets:**

It makes no sense that you can't wear a helmet on top of these from an in-universe point of view.
This would allow you to deal with customization of your own armor abilities, as it does now. Most importantly, it would allow you to maintain the protection of the full armor set. 

The idea is that you can combine them or take them off. Maybe in the crafting table (1 helmet A + 1 night vision = 1 helmet A w/ night vision, 1 helmet A w/ night vision = 1 night vision, but leaves behind helmet A just like a bucket of milk leaves behind a bucket). Not sure if it's possible to do that with durability though.

The other change I'd suggest is to **remove the abilty stacking ability** of the Night Vision goggles to support this. You can still wear them on their own for the 1 armor point and night vision but you don't get any full set bonus even if the other three pieces are identical.

This is a slight nerf yes but it's not an annoying obstructive one (you should have a helmet to begin with anyways) and it prevents people doing stuff like using night vision solely because they don't want to go and mine more shyregem or grind more mobs for the proper helmet.

The idea is to make the night vision goggles a worthwhile target, and an actual reason to go to Barathos, which due to its very design also needs a bunch of extra stuff. But it's a start.

**Comment by DiamondWalker** [comment]
The only thing I agree with here is make it toggleable. It's very annoying having night vision forced on you even if you don't want it.

I like the green shader. Despite being something so simple, I think it adds a lot of immersion. I would make it so it doesn't show if the night vision isn't active (that might already have been changed, I'm not sure). Having a bit of a green shade on your vision seems like a fair trade for having night vision at will. The green also helps see in the dark from my experience.

I don't like merging it with helmets. I feel like that would make the system too complicated. Besides, it's not like you're likely to use night vision goggles during boss fights or something like that.

**Comment by Immortallis1** [comment]
> I like the green shader. Despite being something so simple, I think it adds a lot of immersion. I would make it so it doesn't show if the night vision isn't active (that might already have been changed, I'm not sure). Having a bit of a green shade on your vision seems like a fair trade for having night vision at will. The green also helps see in the dark from my experience.
It's not really immersive though, it's a screen overlay.

> I don't like merging it with helmets. I feel like that would make the system too complicated. Besides, it's not like you're likely to use night vision goggles during boss fights or something like that.
Being able to merge them with helmets isn't very complicated though, it's just helmets and night vision goggles in a crafting table. You are likely to use them during exploration where it does indeed come in handy.

**Comment by DiamondWalker** [comment]
The only reason the overlay is annoying is because it's always present, even if you're walking around during the day or in your base. If you could just turn it off along with the night vision, it wouldn't be annoying.

I still don't like the idea of merging it with helmets. How would its durability work? The decreased defense isn't too important either. The only late-game place where night vision goggles are useful is in Dustopia, and that dimension's currently easy. If you want the extra defense for something, switch it out.

**Comment by Immortallis1** [comment]
Now that I think of it you're right.

**Comment by DiamondWalker** [comment]
![55677957-8717ea00-58bf-11e9-856d-e363903270aa](https://user-images.githubusercontent.com/19913710/55678477-7fa90e80-58c8-11e9-911b-4cc05bfb5f4c.png)

The goggles should look something like that on the player when turned off as well.
