### ISSUE TITLE
Lunar Clock

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#548]
I've always wanted a way to make it night in AoA. It's annoying having to wait through days if you're trying to get a night item or event.

The way I came up with is an item called the "Lunar Clock". It is crafted with 4 lunar ingots and 1 moondust (shaped like a regular clock). If you right-click with it, it will immediately make it night. If it's already night, it will do nothing.

**Comment by Sagisolar** [comment]
How would this work on servers?

**Comment by Tslat** [comment]
What Sagi said.

This is a nightmare for servers. I won't be doing anything where you control the weather or the time of day.
