### ISSUE TITLE
Changes to Existing Candyland Edibles

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#55]
**This is for changes to the existing Treat Bag crafting ingredients. I made another suggestion post (#54) for entirely new edibles.**

As you all know, in the recent AoA3 snapshot, Candyland items were made to be edible. Right now though, they only fill half a hunger bar and have no special effects (I'd assume they don't saturate much either and even if they did it wouldn't make any sense honestly given that candy is not filling.) For items that drop relatively rarely from the mobs there, this is kind of underwhelming.

**Note: all these foods need to be blacklisted from Fungal Staff, for obvious reasons.** 

The effects should all be mentioned in a tooltip. At the very least buff their food values. Nobody wants to eat candies that have the food values of melons, which are obtainable in faster rates and larger quantities and are still sort of annoying to eat.

**Reasoning:** Giving these foods alternative effects allows you to choose to eat them instead of using them to spawn a boss that requires a rare mob item drop too (sour candies). You can only get like 5 peppermints or 5 gingerbread wings until you realize that it'd take you a couple months to get the sour candies needed to use them all for treat bags.

But they are mob drops, and not too common, so they should give more than the other Candyland food (see my other suggestion, #54 ). In-universe it'd be because they have magic, which is why they spawn Cotton Candor I guess. Candyland is also fairly late game so the effects can be somewhat powerful.

You could decide to use them to create a treat bag (once you get the sour candy which is pretty much the gating item along with sour gummies), or eat them for special effects, or eat them as novelties when you feel tired of steak and potatoes (and not feel underwhelmed by having only a half-shank of hunger restored).

------------------------------

Foods and effects:

-**Peppermint (red)**: 7 hunger points, 5 saturation, strength II for 20 seconds (NOTE: Strength was nerfed in 1.12 so it's OK, 1.7.10 strength for 20 seconds would be broken lmao given how relatively common peppermint is)
-**Spearmint (green)**: 7 hunger points, 5 saturation, resistance II for 20 seconds*
-**Gingerbread cookie**: 8 hunger points, 7 saturation, speed II for 20 seconds**
-**Gingerbread wing**: 8 hunger points, 7 saturation, levitation I for 5 seconds. Tooltip has a second warning in a different color stating that it's not responsible for fall damage. Pack a gravitator, feather falling, water bucket, pearls, etc. before using. Since the mod is going to 1.12.2 levitation will be there so it is not a problem. The time is 10 seconds instead to make a relatively safe slow float. Sour gummies are 4 times as potent, lasting twice as long and floating up twice as fast for that entire duration.
-**Sour gummy**: 7 hunger points, 5 saturation, levitation II for 10 seconds. Tooltip has a second warning in a different color stating that it's not responsible for fall damage. Pack a gravitator, feather falling, water bucket, pearls, etc. before using, 20 block falls are not fun. Again, a good way to escape or "fly" for a limited time. Note that the relative rarity of airheads makes this significantly harder to get, thus it's a bit more potent.
-**Candy cane**: 7 hunger points, 5 saturation, haste II for 7 seconds. NOTE: Haste is apparently quite strong in 1.12.2 due to the increase in attack speed. Anyways, this allows for some burst melee damage without being too OP. It's also gated behind hunter level 55.
-**Candy corn**: 7 hunger points, 5 saturation, absorption (3 hearts) for 20 seconds -Sour pop: 8 hunger points, 7 saturation, regeneration I for 20 seconds
-**Sour candy**: make it inedible. Mention in the tooltip either that it's too sour to eat or that the wrapper is almost impossible to get off. Was going to suggest making it a pseudo notch gapple but in all seriousness the chance that it'll come in handy is so much lower than the chance you'll want to craft the treat bag with it. It should be inedible as long as Cherry Barragers are rare and the treat bag is gated behind them.

*Now I'm a little torn on spearmint and peppermint. Apparently spearmint slugs are defensive despite having "spear" in the name. Nobody knows why. Perhaps spearmint slug should be offensive? So I'm not entirely sure whether to make spearmint the strength one or the resistance one.

**Gingerbread cookie is speed because of the gingerbread man song.

**Comment by Sagisolar** [comment]
Hmm this is a good suggestion.
