### ISSUE TITLE
More configures

### ISSUE THREAD

**Issue by iborvs** [Tslat/Advent-Of-Ascension#550]
Such as the initial cooldown. I feel annoying about it, but it may cause a balancing problem if there's not such a thing. Rather than spending too much time in balancing, more features in game should be configurable to let the players to decide whether or not.(not sure if it's ok in English)

**Comment by masterbobli** [comment]
Scimi has explicitly stated that he will NOT add configuration options because he wants a consistent gameplay experience.

**Comment by Tslat** [comment]
Making things configurable doesn't mean I can skip balancing....
