### ISSUE TITLE
Bring back some of the 1.1 dimension skies

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#551]
Bringing back 1.0/1.1 dimension gen has been mentioned a lot, but what hasn't been mentioned before (as far as I'm aware) is that the skies in the dimensions were better in 1.1.

Most of the bright dimensions had a "shine" effect, which made them much nicer. One of the best examples of this effect is Runandor. It one of the biggest parts of what made 1.1 runandor better (instead of the gen imo. The gen still was better, but I don't think it was the biggest part). To show what I mean, I compared two skies in the two versions of the dimension:

New gen with new sky (current runandor)![2019-04-07_12 50 45](https://user-images.githubusercontent.com/19913710/55687089-e238f380-5936-11e9-94d9-78d7f26756a9.png)

New gen with old sky (I think this looks better than current runandor)![2019-04-07_12 53 04](https://user-images.githubusercontent.com/19913710/55687102-08f72a00-5937-11e9-874b-b7f35af6d456.png)

Old gen with old sky (the 1.1 runandor that most people agree looks better than current)![2019-04-07_12 53 43](https://user-images.githubusercontent.com/19913710/55687112-32b05100-5937-11e9-8aad-c3ae53de4a9e.png)

Old gen with new sky (notice how it doesn't look much better than current Runandor)![2019-04-07_12 56 00](https://user-images.githubusercontent.com/19913710/55687118-49ef3e80-5937-11e9-8329-c9ade2ec6606.png)

See what I mean? The biggest part of old runandor wasn't the gen, but the sky. Several of the old dimensions had this effect, but I don't feel it fit in all of them (Precasia had it I think, which didn't make much sense). I think this effect should be brought back/added, but only for:
The Haven
Lands of Runandor
I'd say Barathos, but I think it still has it
Lands of Lelyetia
Candyland
Shyrelands

Vox Ponds was also darker, and probably one of the eerier modded dimensions I have ever seen.
![2019-04-07_12 57 05](https://user-images.githubusercontent.com/19913710/55687186-2082e280-5938-11e9-8744-1e49be419bdb.png)
![2019-04-07_12 59 22](https://user-images.githubusercontent.com/19913710/55687188-21b40f80-5938-11e9-95ed-d44e02fab1ac.png)
^That should come back (but with the new plants)

**Comment by Sagisolar** [comment]
I have a small problem with the old Runandor sky, it physically hurts my eyes when I look at it.

**Comment by DiamondWalker** [comment]
I see what you mean.

For some reason it's more painful to look at in that picture than in the game. It isn't that bad in-game.
