### ISSUE TITLE
Dimension Fog

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#552]
Currently most dimensions have a large amount of fog and to be honest I like fog a lot because it boost the atmosphere a lot. However the high amount of fog doesn't work in a lot of the dimensions. So I made a list of what should and should not have high amount of fog.

These are just my opinions.

Should have a high amount of fog:

- Mysterium
- Dustopia
- L'Borean
- Greckon (Funny thing, it has very little fog compared to the other dimensions).
- Abyss
- Lunalus
- Shyrelands
- Vox Ponds
- Lelyetia

Should have a low amount of fog:

- Barathos
- Candyland
- Celeve
- Creeponia
- Crystevia
- Deeplands
- Gardencia
- Haven (Ok fuck that fog lol)
- Iromine
- Runandor

I feel like Ancient Cavern could have its fog to the point where its just outside the boss rooms. I feel like fog would look cool in the main hall.

Immortallis should have no fog at all. (Haven't checked if it has any but just in case).

I hope you find a way to config fog.  :3

**Comment by EatingSilencer** [comment]
I would agree with this, but do you think Lunalus having a ton of fog would cause players to not realize its a void dimension?

**Comment by Tslat** [comment]
I don't think I have a method for 'amount of fog'...
Minecraft only seems to handle it per Y coordinate

Would have to be a custom thing I think

**Comment by Sagisolar** [comment]
> 
> 
> I would agree with this, but do you think Lunalus having a ton of fog would cause players to not realize its a void dimension?

Tbh it took me a year to find out that there was a ocean floor in Lunalus, I'm pretty sure people could tell that if you spawn on a flying island there will probably be void at the bottom.

**Comment by Tslat** [comment]
3.2 Did things
