### ISSUE TITLE
Old message things from 1.0

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#553]
Back in 1.0, all the mod's chat messages would show red and be "signed" by a green "Eternal Isles" the left. I think having something like that (but with AoA instead of Eternal Isles) would be helpful for players with multiple mods so they can know that the events/bosses/dimensions are from AoA, and therefore find info for them more easily.

I do think colored messages should be used more often (they're only used for events as far as I know). This would help players not confuse mod messages with player messages. Instead of giving each message a unique color (I can think of several issues with that), make each category of messages be a specific color. Boss summon messages could be bright red and boss defeat messages could be dark red or black. Portal messages could be blue (same color as the carved runes). Environmental/special messages could have unique colors (such as events, the vox ponds warning, crafting station messages, or the gods' messages). If the "AoA" in front of the message is added, it should always be green (like it was in 1.0). That way, players won't get confused and think it's part of the message itself.

The other thing that I think should be readded is the Corallus warning message. If the message categories are added as mentioned above, this message could be considered an "environmental" message and be dark blue. From what I remember, there was a chance Corallus would spawn before even getting the message, which defeated its purpose. To avoid this, maybe make it so Corallus only spawns when you get the message for the third time?

**Comment by Tslat** [comment]
Command feedback stuff got prettied and cleaned up a lot in 3.1. I'm gonna close this for now with the assumption that your suggestion will be covered. If 3.1 comes out and it's not, comment on here and I'll look again

**Comment by DiamondWalker** [comment]
3.1 sort of added the signature, but only for commands. Colored messages and Corallus' warning weren't added either, which were mostly the main point of my suggestion.
