### ISSUE TITLE
ArcWorm In Spawner Doesn't Render Crown Properly

### ISSUE THREAD

**Issue by jredfox** [Tslat/Advent-Of-Ascension#554]
**Mod Version**
AoA3-3.0.2

Steps to reproduce:
install aoa
`/setblock ~ ~ ~ mob_spawner 0 replace {SpawnData:{id:"aoa3:arcworm"},Delay:10000}`
observe crown flashing texture compared to the actual texture. This is produced with vanilla forge with aoa no other mods

**Comment by Tslat** [comment]
This is more down to how vanilla mc renders spawners.

**Comment by jredfox** [comment]
yes and there should be no reason for why your crown of archworms fails. It even fails with silkspawners which advancly renders lighting and exact same positioning. If your entity requires some sort of open gl you can enable it then reset it back right after rendering this is open gl basics.

**Comment by Tslat** [comment]
The Arcworm renders the same as any other melee mob in the mod. 
They all use the same renderer.

**Comment by jredfox** [comment]
I am going to see if silkspawners can fix it on your end. But, I bet you there are some open gl calls that you missed to enable/disable before returning from your renderer. If/when I find it I might write a pull request for you. This won't fix it for vanilla if you close the pr like you did the issue.

**Comment by Tslat** [comment]
How much are we betting here?
