### ISSUE TITLE
Wrong keybind displayed after login in Random Info overlay

### ISSUE THREAD

**Issue by Ludi87** [Tslat/Advent-Of-Ascension#555]
**Mod Version**
3.0.2

Other mods that mess with controls:
Controlling mod version 3.0.6 (I don't think it matters, just in case...)

**Describe the bug**
I changed my keybindings, it still shows the default one.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go in Options - Controls
2. Change the keybind for "Close Login Notice"
3. Create new world
4. My changed key ("NEXT") works, its just displayed wrong.

**Expected behavior**
Show the correct key to close the info overlay

**Screenshots**
![2019-04-08_21 28 40](https://user-images.githubusercontent.com/13112051/55751356-c07a6200-5a45-11e9-9ae3-cee1bf8b6431.png)

![aoa](https://user-images.githubusercontent.com/13112051/55751405-df78f400-5a45-11e9-8721-3a4cfed880fa.png)

**Comment by Tslat** [comment]
Problem solved in 3.1
