### ISSUE TITLE
Punch Enchantment Doesn't Work on Modded Bows

### ISSUE THREAD

**Issue by Thorson123** [Tslat/Advent-Of-Ascension#557]
**Mod Version**
3.0.2 

**Describe the bug**
Neither Punch 1 or Punch 2 work on any of the mod's bows (haven't tested all bows).
The punch bows don't provide and additional knock back compared to the non punch bows.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Shoot a mob with a non punch mod bow
2. It should be knocked back 2 blocks if its a normal mob that doesn't have any knock back resistance
3. Shoot a mob with either punch 1 or punch 2 mod bow. 
4. Notice how there's no difference between the punch bow and the regular bow.  

**Expected behavior**
I expect the punch bows to knock back the mobs farther than a regular bow.

**Comment by Tslat** [comment]
Was intentionally omitted for the time being, just in the rewrite to 1.12 while I figure out how to handle infusion

**Comment by Tslat** [comment]
Correcting myself here - I did actually intend to have this implemented (I just missed the lines where I did since I moved it to a different area).
But it obviously doesn't work, so I'm changing this to a bug

**Comment by Tslat** [comment]
Fixed in 3.1
