### ISSUE TITLE
New/changed food

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#558]
I think AoA needs food.

"But it already has several food items"

The problem with the food items it currently has is that they are barely ever used. Most either are only useful in oddly specific situations (Eye Candy and Bubble Berries) or are replaced by steak, of which you can get an infinite source 3 days in. I don't think a simple farm should be #1 solution all the way up to the end of the game. Divine RPG, for example, added the chicken dinner as the final food item. While it was early-game compared to stuff like halite items, it does prove there can be some "food progression". Instead, AoA has the opposite. The other issue is that it doesn't have too much food variety. Most of the food in AoA is either from the overworld (early-game), or variants of each other. I feel that existing food should be reworked, along with adding new food to the AoA dimensions. Since I'm not sure how saturation works, I won't specify the values.

Food reworks:
All raw foods would be edible (for consistency with vanilla)
Halycon Milk: It's not food but still has the same issue. Sure, it's farmable, but if you need milk, you can get it from a cow farm, along with the steak that overshadows most AoA food items. There's other ways to heal. Even instant health potions are more useful than Halycon milk. I think it could be useful if it was the opposite of regular milk and gave you buffs instead of taking them away. I'd also remove the nausea effect: it's pointless. While you're at it, rename it. It's also from creep cows.
Lunarade: Fine as is, but I've heard they might not be stackable soon. If that's the case, make it so they have 6 uses (like those botania potions). Not because they would be expensive, but because it would take a lot of inventory space for them to be worthwhile. Also, I think paying a small amount of money for a refill of the mug instead of reselling it would make more sense.
All tea: Same as Lunarade.
Eye Candy: While I admit I haven't used it in combat, it doesn't seem like restoring a bit of energy will be too useful in regular situations. Energy recovers quite quickly normally, so they aren't really necessary during exploration, and they wouldn't be too useful in boss fights either since you'd had to slow down a lot and for quite a while, making you get hit. A better use for them would be giving 4 hunger points and night vision for 10 seconds. They would act as easy to mass produce food, while also having the ability to be used as an early game substitute to the night vision goggles.
Furlion Chops: Fine as is.
Nature Melon Slice: I think its hunger and saturation values should be slightly increased, or it should give slight regen. Maybe it could also have Eye Candy's current effect?
Hot Rods: Fine as is.
Fiery Chops: It doesn't make any sense that they would be so much worse that Hot Rods. Hellcats are rare (in my experience at least), and you only get 5 at a time. Hot Rods are much easier to get, and also better. I think Fiery Chops should give 10 hunger points and 25 rage points.
Halycon Beef: Non-farmable drop from a rare mob in a dangerous dimension. Stats are worse than vanilla steak... I'd make it give 12 hunger points and replace that nausea with resistance. Also, Halycon cows would be breedable, maybe with some special item from one of the dimensions (possibly Floracles)? Like the milk, it should be renamed to also fit the creep cows.
Floracles: At the point at which they are obtained, vanilla xp isn't too important. You can already safely grind mobs, and might even be able to grind the ender dragon for xp. I think they could be used for breeding Halycon cows, and maybe 3 of them could be made into a floracle bun (they would basically be upgraded wheat). Floracle buns would give 8 hunger points, and maybe give regen.
Trilliads: I really can't see a valid use for them. They only give negative effects, except the regen, but they also give poison? Unless I'm missing something, they're basically useless. Just give them 8 hunger points and give them speed or something. Maybe they would be used instead of Floracles for breeding Creep Cows?
Rosidons: I can't really see any situation where teleporting straight up out of a cave without any idea where you'll end up is a good idea. They could summon a Rosid when eaten. I feel that'd be more unique and useful.
Goldicap Petals: If the trilliads give speed, they would conflict with this crop's ability. I think it'd be better if they had a more unique ability anyways. Maybe they could give one absorption heart when eaten?
Lunalon: Maybe make them give Levitation? There's already too many ways to get night vision.
Lunacrike: Increase the duration of the jump boost. It's way too short.
Luna Globe: Fine as is.
Mystic Shrooms: They would not be food anymore. Instead, they could be used to upgrade mushroom stew into mystic stew.
Chili Pepper: Am I missing something, or does this do nothing other than damage you? I get it's ammunition for a gun, but it's a single gun that isn't that good. I think they shouldn't burn you, and also give 10 hunger points along with strength.
Magic Marang: Again, too many night vision items. Them increasing your max hunger points would be a nice effect. I don't think any mod has done that before. Of course, if that becomes their effect, they'd be a bit too OP for the naturalist. It might seem weird, but maybe they could be dropped by Baroness? It's the only late game place I can think of where a magic item would fit.
Heart Fruit: Fine as is.
Bubble Berries: Despite what I said at the beginning, I think they are fine.

New food:
Halycon Cake: Same as regular cake, but made with Halycon milk instead of regular milk. It would give 3 hunger points per slice, and heal 3 health points.
Dyrehorn Chops: Would be obtained by killing and cooking Dyrehorns. Would give 10 hunger points.
Cooked Megatherium: Obtained by killing and cooking Megatheriums. Would give 12 hunger points.
Saber Steak: Would be obtained by killing and cooking Saber tooth. Would give 11 hunger points.
Emperor Foot: Obtained from killing and cooking an Emperor Beast. Would give 16 hunger points.
Arcback's back: Obtained from killing and cooking an Arcback. Would give 15 hunger points.
Flare Fruit: Seeds would be obtained from the Nether, but it can only be planted on Barathos hellstone near lava. They would be used for making Fire rolls.
Fire roll: Would give 14 hunger points, and give 2 minutes of fire immunity.
Hell burger: Would be made with 2 fire rolls and a fiery chop. Would give 16 hunger points and fire immunity for 5 minutes.

**Comment by profilename14** [comment]
I agree with everything except changing rosidons

Rosidons can be used to teleport up the gardencia lotto structure, escape enemies by jumping up to the tops of trees, save yourself from the void in dimensions like the haven, and climb mountains.

Additionally, while using rosidons in a cave could potentially cause you to end up in an ocean or some other bad place, making a staircase up to the surface has the same risk
