### ISSUE TITLE
Skeletal army changes

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#560]
The skeletal army is a lot more fun to fight now, but there are some thing that could be improved:

Make the elder immune until the rest of the wave is killed. At first this isn't an issue, but in the later phases, the elder starts dying a lot, ending in an endless loop of more waves and enemies spawning until you get completely surrounded.

Make the skelemen projectiles move more slowly. I know they are just standard spells, but other mage enemies don't spawn in large groups. If you get surrounded by 5 skelemen, you're most likely going to die. Buff the damage and maybe give the skeleton AI so it doesn't become too easy.

Make the skelepigs less tanky but much faster. The skelehoppers already act as tanky melee mobs. The skelepigs don't really add anything special to the fight.

Lower skeletron's damage, but make him faster and shoot projectiles. I don't think anyone can agree that an insta-kill enemy in an army of enemies that look similar is a good idea. It doesn't add anything to the fight, and just serves as a way to send people who aren't familiar with the fight all the way back to the beginning.

**Comment by Sagisolar** [comment]
I agree with most of this but how could Skeletron shoot range. Making him faster would just make him Silverfoot clone. Tbh I think Skeletron should stay as a slow hard hitting boss. He should still tie with Kror in turns of damage but Kror would have longer range making him slightly harder to fight.

**Comment by Tslat** [comment]
Alternatively you could avoid hitting the elders until you're ready...

**Comment by DiamondWalker** [comment]
The skelemen don't avoid hitting him though

**Comment by Sagisolar** [comment]
Another problem I've found is if Skele-elder is immune, wouldn't the show staff be even more op against the army?
