### ISSUE TITLE
Random explosions during Baroness fight

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#561]
**Mod Version**
3.0.2

**Describe the bug**
During the Baroness fight, there are invisible bombs that were never placed by her. These bombs don't have the explosion timer and only explode on contact. Since I only encountered this bug after failing the fight several times, it may be possible that they are bombs from previous attempts that are despawning incorrectly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Fight Baroness (you may have to die to her one or more times)
2. Walk around the arena (possibly in creative)
3. If the bug occurred, you will encounter one or more explosions when stepping on certain parts of the arena.

**Expected behavior**
The explosions should only occur after a bomb has been spawned for a few seconds or when you touch a bomb.

**Screenshots**
https://www.youtube.com/watch?v=KkG6wWFmMLc&feature=youtu.be
(I later encountered two more explosions near where I died when walking around the arena in creative)

**Comment by Tslat** [comment]
This should be fixed in 3.1, but due to the difficult in testing I'm not 100% on this.
I'm closing it for now based on my testing but if you have the issue again in the future let me know
