### ISSUE TITLE
Charging Pads changes

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#563]
I'd make the charging pads look like this:
![2019-04-14_20 15 25](https://user-images.githubusercontent.com/19913710/56101486-2ce7dc00-5ef2-11e9-8232-0d7d4947064b.png)
Since it might be hard to notice every change, here's the list:

It would be a tower. There's a few benefits to this. It makes a hard to find structure easier to see and makes it so the player doesn't have to build an arena themselves. It also makes the fight more fun and challenging by adding the threat of falling and removing cover from the Polytoms). It being a tower also adds some resemblance to a power plant.

There would be a path between the platforms. This would sort of go hand in hand with the tower change, since it would make it possible to fight the boss without falling off. imo it makes the structure nicer as well.

There's a small "cone" on top of it. The top just being flat with a hole in the middle looks ugly.

I'd also hide polytom spawners somewhere. They make the fight more interesting.

I'm not sure how to send the world file. Let me know how to send it if you're interested in adding the structure.

**Comment by Tslat** [comment]
The picture could have maybe been taken with night vision or something lol
