### ISSUE TITLE
Corallus bugs

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#564]
Corallus has a few bugs. He's very slow (along with his shots), and the shots spawn on the ground even when he's in the sky, which looks weird.

**Comment by Sagisolar** [comment]
If you were wondering Scimi, the latter part is what I meant in https://github.com/Tslat/Advent-Of-Ascension/issues/60

**Comment by Tslat** [comment]
That makes sense

**Comment by Tslat** [comment]
Fixed in 3.1
