### ISSUE TITLE
Unique ways to get to post Greckon/Ruanandor dimensions

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#566]
I've always been slightly disappointed at the fact that after Greckon and Runandor, dimension travel goes back to simply being "find realmstone and use it". I think there should be unique ways of getting to Dustopia, Barathos, and Shyrelands. Once in the dimensions (except Shyrelands), you could obtain a realmstone so you can return normally.

Dustopia: You would have to make an item called the "Mortality Orb" by using an Immortality Orb (dropped at the end of an Immortalis run) and darkly powder on a darkening station (found somewhere in Greckon). You might get a message from Erebon when making it. When you have this item in your inventory, the Greckon portal texture would be slightly eerier for you (no one else will see this change in a server). If you attempt to leave Greckon with this item in your inventory, you'll be sent to Dustopia, and possible recieve a follow-up message from Erebon so people don't think they've encountered a bug. If you throw the item on the ground while in Dustopia, the item will immidietely despawn and you will be teleported back to Greckon (right next to the portal).

Shyrelands: You would have to somehow "enlighten" night-vision goggles. Maybe you could use them on the P5 altar when all the lights are on (they won't spawn, the lights will be used on the goggles). The enlightened goggles would have this tooltip:
"Bright enough to blind any wearer"
"In the darkness, light may uncover secrets"
Putting these on anywhere but Dustopia or the Shyrelands will inflict the old Shyrelands' blind effect on the player. In Dustopia, they would teleport to the Shyrelands. If you take them off in the Shyrelands, you'll go back to Dustopia. When you teleport through the dimensions, you'll end up at the same X and Z coordinates, but you'll always end up at ground level. The lore behind this is that Dustopia will seem like an entirely different dimension if seen with enough light, but since the dimension is naturally dark, you can't see the other side without the enlightened goggles.

Barathos: I'm not sure. Maybe you would somehow "invert" the Runandor portal? Barathos doesn't have too much to do with Runandor theme-wise, so it's hard to come up with a way to tie them together.

**Comment by Tslat** [comment]
No longer relevant
