### ISSUE TITLE
Bring back random Visualent teleporting and nerf his damage

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#569]
Make it so Visualent has that old ability where he randomly teleports, but make him not damage you while doing it. Also, decrease his damage. 2 or 3 slip ups and you're dead. He isn't even a late game boss.

**Comment by Tslat** [comment]
"Late game"

**Comment by DiamondWalker** [comment]
I mean, he can be summoned right after going to Lunalus, and lunalus is early game. Doesn't that make him early game too?
