### ISSUE TITLE
Melee mobs and pathfinding

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#57]
**Describe/name the existing feature this suggestion relates to**
Every single melee mob (except like Scrubbies and Bush Babies) having no pathfinding and not caring about any hazards that may be in front of them.

**Describe the change or feature you think would be good to see**
I think most melee mobs should be able to pathfind, it would make the game just a little more difficult in that you can't fool mobs into running into hazardous stuff. It would also make the mobs feel just a little more immersive, having almost all your mobs run off of cliffs just doesn't look good for the mod's reputation, but that's just me.

**Add any alternative implementations you think might work**
It doesn't just have to be regular pathfinding, you can do some other things with melee mob AI to make more of them feel different from each other, stuff like mobs that can only get quick bursts of speed then have to stop to charge up for a couple seconds before getting a speed boost again, mobs traveling in straight lines, and changing direction every couple seconds to wherever you are, and even mobs that attack you from behind, etc.

**Include any additional background information**
Not every melee mob needs pathfinding, I think certain mobs like Chargers are fine without it as I think it kind of fits them, mainly mobs who take more "reckless" approaches in combat shouldn't have pathfinding, as I think the lack of pathfinding fits those mobs. But mobs like Cyclops, Paladins, Voltron, etc. etc. etc. etc. do need it.

Flying mobs don't really need pathfinding either (though maybe they do need it if they're trying to get around a wall or something)
Ranged mobs don't need it either since they... Already have it.

(I know I sort of suggested this on Discord before, but I'm doing it here mainly as a way to get myself used to this)

**Comment by Flameminer221** [comment]
cyclops are stupid and don't need pathfinding either

**Comment by Cruuk** [comment]
> 
> 
> cyclops are stupid and don't need pathfinding either. just look at one for more than 30 seconds and tell me it's not stupid

Excuse me sir my uncle was a cyclops

**Comment by EatingSilencer** [comment]
I'm not 100% sure, but I think AI changes to mobs in 1.12 causes them to have pathfinding by default. 

Basically, in 1.7.10 if you made your mob by extending the mob class and did nothing else, it would by default be a melee attacker.

But in 1.12, I think. that doesn't work anymore. You have to manually define the melee attacker part for each mob. I think this will cause it to have pathfinding by default (unless I'm mistaken).

**Comment by Tslat** [comment]
> I'm not 100% sure, but I think AI changes to mobs in 1.12 causes them to have pathfinding by default.
> 
> Basically, in 1.7.10 if you made your mob by extending the mob class and did nothing else, it would by default be a melee attacker.
> 
> But in 1.12, I think. that doesn't work anymore. You have to manually define the melee attacker part for each mob. I think this will cause it to have pathfinding by default (unless I'm mistaken).

This is correct, and most likely this issue with self-resolve. Keeping the ticket open until we find out for sure though

**Comment by Immortallis1** [comment]
Then maybe change it to "make chargers have no pathfinding in 1.12"? lol

**Comment by Tslat** [comment]
Yay we're finally here
