### ISSUE TITLE
Dynamic Trees doesn't give you logging. (Tree Capitator as well)

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#576]
Basically these mods change how getting wood works. In Dynamic Trees when mining the bottom tree block the hole tree falls down. But, you can't get logging from it.

Haven't tried Tree Capitator since snapshot 9. But I can remember it not working with Logging so I dropped it.

Basically It would be cool to have a check so Logging works with these mods.

**Comment by Tslat** [comment]
They use fakeplayers (as they should). AoA skills don't allow fakeplayers to gain xp.
