### ISSUE TITLE
Remove the uncharged orb drops from the inmates and buff their drop rate

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#577]
Honestly, having uncharged orbs drop from the inmates doesn't make much sense. Not only does it not make sense lore wise (why would prisoners of all things have magical orbs?), but it also doesn't make sense progression wise. Why would you grind them in Dustopia when you can grind them more easily in an early game dimension? Also, it might be just an opinion, but I personally feel that having to bring together items from different dimensions in order to make something (lunar armor in this case) is more fun than just grinding a lot of a single item.

I'd also increase their drop rate. Having to kill mobs about 900 times to get specific gear isn't fun at all. Why not just make it a 25% drop rate like every other multi-use crafting drop in the mod?

So that the inmates don't stay without any drops, I'd add something new for them: Lunar Contraband. Lunar Contraband would also have a 25% drop rate. These could be used at some sort of black market to be sold for coins, lunalus gems, or lunar scraps. Lunar scraps would used as an extra material in making Lunar ingots (since having them be basically the same but for later game crafting is a bit boring imo).

**Comment by Tslat** [comment]
No longer relevant
