### ISSUE TITLE
/aoaevent command not working?

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#579]
**Mod Version**
3.1

**Describe the bug**
I used the command like this... /aoaevent start big_day, and I'm greeted with this message: "An unknown error occurred while attempting to perform this command."

**Screenshots**
![Minecraft 1 12 2 4_20_2019 9_16_50 PM](https://user-images.githubusercontent.com/45743385/56464198-1dfd9f80-63b2-11e9-81dc-2bb75aa43740.png)

**Comment by Tslat** [comment]
Has been reported and fixed

**Comment by mrcakesamurai** [comment]
Why is it still happening?

**Comment by VBGaming** [comment]
Probably because the patch isn't out yet
