### ISSUE TITLE
[Bug] Bane's clones are static and don't move at all

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#58]
Affects version **Tslat 1.1.3**

**Describe the bug**
The clones that the boss Bane summons are glitched - they do not move at all and can be walked through.

**To Reproduce**
Steps to reproduce the behaviour:
1. Summon the boss Bane in Greckon and watch him spawn his clones.
2. See that the clones don't move and can be walked through

**Expected behavior**
Bane's clones could move and they aren't able to be walked through.

**Comment by Sagisolar** [comment]
Yeah when I trapped Bane on a minecart he created static unremoval clones.

**Comment by Tslat** [comment]
AoA No longer updates 1.7.10 as it is an ancient version of MC
