### ISSUE TITLE
After full moon, Skellox still spawns during the day.

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#586]
**Mod Version**
3.1

**Describe the bug**
title

**Expected behavior**
They're supposed to despawn.

**Screenshots**
![2019-04-21_10 36 53](https://user-images.githubusercontent.com/44548547/56468255-b0895780-6421-11e9-9a1f-a121529c22a4.png)

**Comment by Cruuk** [comment]
In my survival world after a full moon happened they've even started spawning during the day. Help

Logging off seems to fix it though... At least until the next full moon happens
