### ISSUE TITLE
Crash with Triumph

### ISSUE THREAD

**Issue by ddteam90** [Tslat/Advent-Of-Ascension#587]
**Mod Version**
Advent Of Ascension v3.1
Triumph 3.17.0

**Describe the bug**
When you joining the world and when you remove the AoA's advancements you get a crash, because startProgress and getProgress returns null and causes NullPointerException.

**To Reproduce**
Steps to reproduce the behaviour:
1. Throw Advent Of Ascension 3.1 and Triumph 3.17.0 (or any version you can grab) with dependencies into mods folder.
2. Launch the game.
3. Create a new world or try to launch existing worlds.
4. You get a crash.

**Expected behavior**
I expected that world launched without any problems. (I need to create custom advancements in my modpack and Triumph is required.)

**Screenshots**
There is no screenshots, but there's some crashlogs.
When creating a world: https://paste.dimdev.org/wahitecutu.mccrash
When joining existing world: https://paste.dimdev.org/afecimajem.mccrash

**Comment by Tslat** [comment]
This is an incompatibility with Triumph.

They decided that removing all the advancements would be the best way to go.
They might be able to fix it from their end - but to fix it from my end would involve basically just removing features. So no thanks
