### ISSUE TITLE
Add in a stupid joke mob or dimension like the moolands

### ISSUE THREAD

**Issue by BoringTalking** [Tslat/Advent-Of-Ascension#59]
You wouldn't find whatever this is if you weren't looking for it. You'd craft some stupid item that spawns in like a holy arcworm or it would take you to the arcworm dimension or something stupid. You could probably do it in like 15 minutes. If you want any help, look at moolands.

If thats not what you want to do? Add in a paintings like block thats a huge portrait of an arcworm. Or something like that.

No idea if the concept has been brought up before, but screw it. You could add it in on april fools if you so wish to.

**Comment by Immortallis1** [comment]
I'd like something stupid like that at one point but we don't even know how long it takes to make a dimension yet.

**Comment by Immortallis1** [comment]
Given the old boot he'll probably do something like this at one point tbh
