### ISSUE TITLE
Advancements Crash upon creating a new world

### ISSUE THREAD

**Issue by Rongmario** [Tslat/Advent-Of-Ascension#593]
Mod version: AoA3-3.1
Crash log: https://paste.dimdev.org/anomugegor.mccrash

**Comment by Tslat** [comment]
Out of curiosity, does this happen when you're not using fastbench?

**Comment by Rongmario** [comment]
Sorry, am outside but will try without FastBench, though other stacktraces I've encountered contains FastWorkbench in them even when its not the cause.

I will also try without Patchouli and its counterpart when I have time

**Comment by Tslat** [comment]
This is an incompatibility with Fastworkbench.

They decided that removing all the advancements would be the best way to go.
They might be able to fix it from their end - but to fix it from my end would involve basically just removing features. So no thanks

**Comment by Rongmario** [comment]
@Tslat I've got the cause, its FastWorkbench for some reason, you should add an incompatibility notice on the mod page.
