### ISSUE TITLE
No ore's in Creeponia

### ISSUE THREAD

**Issue by sakakibara779** [Tslat/Advent-Of-Ascension#595]
**Mod Version**
3.1

**Describe the bug**
No ore's in Creeponia

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Minecraft with AoA
2. Enter Creeponia
3. Search for ore

**Expected behavior**
To find ore?

**Screenshots**
![2019-04-22_00 32 11](https://user-images.githubusercontent.com/48034004/56473525-9473cd80-6496-11e9-988a-4fe549162acb.png)

**Comment by Tslat** [comment]
Killin myself over here
Tested fixed in 3.1.1, sorry
