### ISSUE TITLE
Some mobs shouldn't have Pathfinding

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#605]
- All Chargers (Don't have to explain why).

- All of these mobs (Except Skeletal Cowman) https://github.com/Tslat/Advent-Of-Ascension/issues/459

- Skellox (Fast mob with pathfinding especially early game is not fun).

- Every mob 3.5 blocks high or above (I say this because mobs like giants should try and catch you from the tree instead of climbing it).

**Comment by Cruuk** [comment]
What about Faceless Runner, he don't got eyes

**Comment by Sagisolar** [comment]
You can make your own collection here if you want
