### ISSUE TITLE
Advancements for the Hunter Skill

### ISSUE THREAD

**Issue by RugratCoder94** [Tslat/Advent-Of-Ascension#607]
With 3.1 out and the loot update presumably coming right after,  some advancements may be gaining rewards for completion as stated in the [changelog](https://pastebin.com/Qk14AVfU).  Though most of the advancements right now involve skills, boss killing, or visiting dimensions.  

Thus I propose the addition of advancements for the hunter skill, essentially acting as a milestone in your progress for the skill.  

Killing a hunter mob for the first time would grant the player an advancement, and seeing as most hunter mobs have some sort of drop (though I am unsure how these drops will be handled), given as a reward.  It could make obtaining whichever item slightly less grindy or just make the skill seem more rewarding in general.  

Alternatively they could give something different or not give anything at all; however, if nothing is gained from them there isn't really a point to them being there if the rest of the advancements have rewards.

**Comment by EatingSilencer** [comment]
Now that hunter mobs are configurable, this might be a tad awkward having advancements for defeating certain mobs when someone can just remove the hunter status from them.
