### ISSUE TITLE
Ambiguous explanation

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#608]
**Describe/name the existing feature this suggestion relates to**
The guide section

**Describe the change or feature you think would be good to see**
The following sentence quoted from line 4, creation.txt might fail to explain what the author really means:
```
 These minions offer varying benefits and abilities, and will often fight alongside you.
```
Removing all the modifications and unnecessary part of the sentence, we have:
```
Minions offer abilities.
```
The former sentence seems to imply that the minion transfers their ability to players.

For instance, Blissard has the ability to heal owners on hit. According to the explanation, whenever you summons Blissard, you will gain his ability of healing the owner on hit. Since you are an independent person, nobody will actually get healed.
I find it hard to believe that the game actually works in this way.

In my opinion, the sentence could be changed into the following one:
```
 These minions utilizes their abilities which can offer you various benefits, and will often fight alongside you.
```

**Add any alternative implementations you think might work**
In case you consider the change as over-complicates the sentence, simply removing this part will also work, which could be like this:
```
 These minions offer varying benefits, and will often fight alongside you.
```

**Include any additional background information**
I came across this error when doing translation.

**Comment by Tslat** [comment]
I... just plain don't agree at all lol

Not all minions fight alongside you, and with the vast majority doing so, it's a key feature of what they do - and is therefore notable.

**Comment by masterbobli** [comment]
What I would like to suggest is that the word "offer" is inappropriately used. What the minion offers is their help and benefits by using their abilities instead of their actual abilities, because "offering abilities" means that the minions will give you the minions' abilities. Since the description seems to contradict with what really happens in game, the word is inappropriately used.

**Comment by masterbobli** [comment]
It's nothing but a confusing wording issue.
