### ISSUE TITLE
The State of Creep Day

### ISSUE THREAD

**Issue by RugratCoder94** [Tslat/Advent-Of-Ascension#61]
As is the hot topic right now, the Creep Day event is a disaster.  The way I see it is that there are a few options for how to improve the event or the method of travelling to Creeponia in the first place. Creeponia isn't going anywhere and we all know that.  There are 3 ways I can see to improve this.

1- Remove the event entirely: exactly what is sounds like
     Pros- Removal of one of the largest complaints for Creeponia as a whole, moves dimensions further out from the overworld.
     Cons - Find appropriate dimension and mob for the realmstone to drop from (BamBamBam?)
2- Turn Creep Day into a full scale event: More mobs for the event that can each [drop a material to build the realmstone/drop the realmstone]
     Pros - Improves the creep day event without entirely scrapping it, stands out slightly from other events
     Cons - Requires the creation of more mobs and items
3- Host becomes a miniboss: Also removes the event, turns host into a hopefully challenging miniboss
     Pros -  Can be locked behind dimensional progression
     Cons - Making (good) boss AI takes a lot of work probably, could make travel to creeponia overly difficult
    
Though I'm sure you've had some of these suggested before I figured I'd throw in my two cents.  I'd appreciate feedback on how I can improve any of these options or even add/remove one.

**Comment by Cruuk** [comment]
Please do this or I will use ritual techniques to summon the Charger horde from under the Earth at the white house on June 19, 2021.

**Comment by Immortallis1** [comment]
I vote for option 2. I don't believe Creeponia needs a concept change, it just needs more content like pretty much every other dimension ever. Creep day, however, is an unfinished event.

**Comment by Cruuk** [comment]
> 
> 
> Please do this or I will use ritual techniques to summon the Charger horde from under the Earth at the white house on June 19, 2021.

But seriously though, to be honest I wouldn't even mind if Creeponia stayed in the Overworld, as long as the realmstone was just made harder and more dynamic to get, whether it required latergame materials from the Overworld, or stuff from other dimensions.
