### ISSUE TITLE
New guides in the guides tab

### ISSUE THREAD

**Issue by VBGaming** [Tslat/Advent-Of-Ascension#614]
**Describe the new feature you think would be good to add**
A specific and detailed description of what you want to see.

New guides in the guides tab, specifically about how to fill tribute bars and how to find realmstones.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?

No

**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?

Sounds useful, especially the tribute bar one
I can write one myself and send it if you don't want to bother

**Comment by Tslat** [comment]
I'm fine with writing them - mainly just what you guys think I should write them on is what would be good here
