### ISSUE TITLE
Target selectors do not seem to work in commands

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#615]
**Mod Version**
3.1.1

**Describe the bug**
Whenever you input a player into the aoaskill command, the target selectors of @p, @a, and @r do not seem to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open up a world with cheats enabled.
2. Open up the chat.
3. Type /aoaskill check @p Innervation
4. Notice that the @p does not register as a player.

**Expected behavior**
@p, @a, and @r work like they would in vanilla commands.

**Comment by Tslat** [comment]
Sure
