### ISSUE TITLE
Armor sets dropped by bosses

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#62]
**Describe/name the existing feature this suggestion relates to**
All the armor sets dropped by bosses. Candy, Commander, Explosive, Hydroplate(?), and Primordial. (I guess Archaic counts?)

**Describe the change or feature you think would be good to see**
Trying to actually get a full set of these armor sets is a frustrating experience, it's not so bad at first, but there's nothing worse than going through all the trouble of making the boss spawner and fighting the boss just to get duplicate armor pieces. Yeah grinding on mobs who rarely drop armor pieces can also be annoying, but at least the pacing is more smooth, it's like gambling small amounts of something to have a small chance of winning VS. putting all your eggs in a basket to have a higher chance of winning something, but with much bigger consequences.

I know weapons dropped by bosses won't be affected by the new looting system... But I feel like an exception should be made for any armor sets dropped by bosses. These bosses would drop special materials that would mainly be used to craft the armor sets (or you can also make it require an additional non-boss material like Jade or something).
There would still be a challenge, the amount of materials dropped by a boss would make it so you needed to kill them around 3-5 times to get enough for the full set. It would still be challenging but not so frustrating with RNG.

Example: P5 would drop like 6-8 "Primordial shards", you would use these shards to craft Primordial armor, etc. etc.
Example 2: Hydroplate armor would be made with the material Hydrolisk drops and Pure **Water** Stones. (Pure **Coral** stone is the item dropped by Amphibiors so no this wouldn't add a hunter req. to Hydrolisk)

The nice thing about weapon drops is that even if you don't get the weapon you wanted, you can easily pick up and use any weapon type (except staves). Ammo isn't hard to make/find.

**Include any additional background information**
Archaic armor can stay mostly the same, but a 33% chance to get 1 out 4 pieces is pretty insane to me, especially considering the ability isn't insane anymore. It should be 100% per run. Could also be more like Infernal where it can drop multiple pieces at a 25-33% chance each? (I think it's already like that actually but the chances are really low, like 8.25% per piece damn)

Or if we're removing all RNG of boss armor sets completely, then you could just make Archaic armor buyable from the Token Trader. Can still be pretty expensive overall though, like 15-20 tokens per piece.

**Comment by EatingSilencer** [comment]
Would this also affect the diving helmets?

**Comment by Cruuk** [comment]
> 
> 
> Would this also affect the diving helmets?

Oops I forgot about them

I mean, it's a similar argument to boss weapon drops, no matter what helmet you get you are able to just use that helmet without any other reqs.
