### ISSUE TITLE
Dimension mobs also shouldn't spawn on man-made blocks

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#624]
Overworld mobs don't spawn on man-made blocks right?

Then why do dimension mobs spawn on man-made blocks?
Is it for the "challenge"? It just seems more annoying. I can't really think of any other reason that they should be so different from Overworld mobs in that regard.
If they didn't spawn on man-made blocks I don't think it would destroy the difficulty of the dimension it would just make stuff not as stressful.

Especially in goddamn Haven where if you're unlucky with the portal you'll have to build a big-ass bridge, and when it's big enough mobs will start spawning on it, and that's when shit goes south.
Even when the bridge is 1 block wide I've still had mobs spawn on it.

Just look at this man
![image](https://user-images.githubusercontent.com/38159897/56716890-45c17000-66f0-11e9-8c53-e00519aee321.png)
![image](https://user-images.githubusercontent.com/38159897/56716915-5245c880-66f0-11e9-90a0-cbf55b2d7510.png)

I know this entire git post is very kneejerk of me, but I've had such a terrible time in Haven man

**Comment by masterbobli** [comment]
Just put some slabs

**Comment by Immortallis1** [comment]
get good loser

**Comment by Cruuk** [comment]
Maybe I was too irrational
