### ISSUE TITLE
Strange Lighting

### ISSUE THREAD

**Issue by lulu2002** [Tslat/Advent-Of-Ascension#626]
**Mod Version**
What version of the mod are you on?
3.1.1

**Describe the bug**
After I update this mod to version 3.1.1, sometime this strange lighting will appear.

**Screenshots**
Normal
![image](https://user-images.githubusercontent.com/41278925/56743067-76fd7700-67a8-11e9-835c-8e08d509683f.png)
it appears
![image](https://user-images.githubusercontent.com/41278925/56743097-867cc000-67a8-11e9-8135-79ab1a7a3641.png)

**Comment by Tslat** [comment]
That’s just a forge/mc lighting thing
Aoa doesnt touch lighting or chunk loading at all
