### ISSUE TITLE
Dimension dirt is not affected by shovels

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#627]
**Mod Version**
3.1.1

**Describe the bug**
The dirt blocks in the AoA dimensions don't get dug faster by shovels. There is no difference to using your hand with the dirt blocks. This seems to be exclusive to the **dirt** blocks, the **grass** blocks are fine. It is faster to dig grass blocks with a shovel, not dirt blocks currently.

**To Reproduce**
Steps to reproduce the behaviour:
Dig any of the dimension's dirts with a shovel, then do it again with your hand

**Expected behavior**
Shovels also digging dirt faster.

**Comment by Tslat** [comment]
Fixed
