### ISSUE TITLE
Certain foliage ends up in your inventory when broken by hand

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#629]
**Mod Version**
3.1.1

**Describe the bug**
There's a bit of an inconsistency with foliage, certain ones go into your inventory when broken by hand while others don't, I've narrowed down the ones that do go into your inventory when broken by hand.

Arcbulb
Arcflower
Blue Celevians
Purple Celevians
Red Celivians
White Celevians
Chocolate Stocks
Creep Flowers
Daileers
Dawn Bush
Dawn Flower
Blue Daylooms
Pink Daylooms
Yellow Daylooms
Haunted Flower
Horizon Daisies
Lylips
Magias
Mellians
Blue Ocealites
Red Ocealites
Pertonias
Runic Bush
Shyre Weed

I know some of these were part of the dimension biomes that aren't in the latest version, but I might as well include them as well.

**To Reproduce**
Steps to reproduce the behaviour:
Break the foliage listed with your hand or something that isn't shears.

**Expected behavior**
All the foliage being destroyed when you break them with something that isn't shears, like grass. (I know grass gives seeds but it doesn't give the grass block itself).
I know it's a pretty minor issue but it can be a little annoying when you're trying to hit a mob with your melee weapon, but instead hit foliage, with said foliage clogging up your inventory if you keep accidentally breaking them.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/56774507-d55e3180-6777-11e9-97b9-a60f4fdadeda.png)

**Comment by Tslat** [comment]
Intended, see mc flowers vs grass
