### ISSUE TITLE
Gorb Engineer

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#632]
**Describe/name the existing feature this suggestion relates to**
Gorb Engineer

**Describe the change or feature you think would be good to see**
Now, I like the new system of randomized NPC trades for the most part, it is nice that certain NPCs like bankers and skill masters are exceptions to this system as well, because it would otherwise be painful.

But... there is an NPC that isn't an exception that really suffers from this system. Gorb Engineer.
Look at these trades.
![image](https://user-images.githubusercontent.com/38159897/56843430-7ff85200-6855-11e9-9334-fcedd4b9359a.png)
Do you see it yet? You will need extreme RNG to find Gorb Engineers that have the pieces you need, and Gorb villages aren't exactly common. Just running through Mysterium is a strenuous task. It's painful when you spend all that time to find a village only for it's Gorb Engineer to sell Nightmare boots and nothing else.

Granted, there is another NPC that sells an armor set that isn't an exception- Crystal Trader. However, Crystal Trader mainly sells weapons, which don't require other items to fully utilize other than ammo for most of them. (Besides, Crystallis armor is terrible while all of Mysterium's sets are pretty good)

What I'm saying... is that maybe, Gorb Engineer should be an exception to the randomized trades. You already have to put work into getting the drops from the mobs, you shouldn't have to find like 5 Gorb Engineers just to find all the pieces needed.

**Add any alternative implementations you think might work**
If you still want them to be randomized, it should randomize the amount of sets the Gorb can sell, rather than the individual pieces.
What I mean is that for example, some Gorb Engineers would sell all 4 pieces for 1 set, other engineers could sell all the pieces for 2 sets, and other engineers would sell all 3 sets like it was in 1.7.

It's still random, but it's way more structured and alleviates stress of finding individual pieces.

**Comment by Sonicwave** [comment]
Another possibility is that only some trades are displayed initially (like now), but trading with them causes the other trades to gradually be unlocked, similar to vanilla villagers. Although given that the villages don't spawn too frequently and there is only one engineer per village (who can't breed, so you can't generate different trades in the same village), it might be better to just have them show all trades.

**Comment by Sagisolar** [comment]
No thanks

**Comment by Tslat** [comment]
No longer relevant
