### ISSUE TITLE
5 bytes extra whilst reading packet 28; crashes game

### ISSUE THREAD

**Issue by derelicthaunter** [Tslat/Advent-Of-Ascension#634]
**Mod Version**
1.7.10; AoA-Tslat-1.1.3

**Describe the bug**
Internal Exception: io.netty.handler.codec.decoderException: java.io.IOException: Packet was larger than I expected, found 5 bytes extra whilst reading packet 28"

**To Reproduce**
Steps to reproduce the behaviour:
1. Put mod in mods folder
2. Put same mod in server mods folder
3. Try to log in

**Expected behavior**
To be able to join the server with this mod enabled.

Thanks in advance for any help with this, I really just want to play the game with this mod.

Server Log:
https://gist.github.com/derelicthaunter/a417b3cef8d52bd36ae9a2fe23ab848f
Sadly it doesn't leave a client crash log as it doesn't actually crash, hope the server log may be of help.

**Comment by Tslat** [comment]
Does this happen when no other mods are present?

**Comment by derelicthaunter** [comment]
It doesn't give me any Crash Report because the game stays open, only when I try and join the server do I get this error, I can create singleplayers worlds and everything but when I try and join my server it gives me the error...

**Comment by Tslat** [comment]
Can you do an install with no other mods and provide both the client and server sides of the log when it happens

**Comment by derelicthaunter** [comment]
Thank you for your time but I figured out the issue, it was because I edited the datawatcher ids as I also has balkons weapon mod installed at the same time and they interfered with eachother.
