### ISSUE TITLE
Fire Aspect/Flame should stack with weapons that already inflict fire (+Poison arrows affecting Bows that already inflict poison?)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#642]
**Describe/name the item/content this suggestion relates to**
Every melee weapon/Bow that inflicts fire

**Describe the change/balance you think would be good to see**
It's something that has always bugged me since the beginning. Fire Aspect and Flame being useless on melee weapons and bows. I feel like it always should've affected it.

I think the best way to implement it would simply be to add the fire damage of fire aspect to the weapon's fire damage.
Nethengeic sword does 7 fire damage, and Fire aspect II adds 7 fire damage. A Nethengeic sword with Fire aspect II would deal 14 total fire damage. I know that may seem like a lot of damage, but it's still fire damage, which is like 1 DPS.
Don't get me wrong, that much fire damage would be very very reliable, but it won't be a huge damage upgrade, especially against high-health mobs and/or fire-resistant ones. You can always make fire aspect less effective on weapons that already inflict fire to make for the fire they already have... I'm not gonna get too into it.

And of course it'll only affect fire damage, for special cases like Erebon Scythe it would only affect the fire damage, not the wither damage.
Fire aspect/Flame can already stack with melee weapons and bows that give poison/wither, so why can't it stack with itself?

Also, it would be neat if poison tipped arrows could stack with bows that already inflict poison, but that seems harder to do due to the way poison works, so yeah...

Even if this somehow causes balancing issues, a bunch of stuff is already getting rebalanced in loot update so I don't think it's a huge concern.

**Include any additional background information**
Now, I know you can also argue that feather falling doesn't stack with stuff like Amethind/Alacrity, so not a big deal for fire aspect right. Wrong. This is a case of Immunity vs. boosted damage. Feather falling has a use in general since not all sets are immune to fall damage. But in the case of fire aspect it's the opposite. 
Fire aspect II adds 7 fire damage.
Fireborne does 5 fire damage
Nethengeic does 7 fire damage
Ultraflame does 9 fire damage
Underworld gb does 7 fire damage
Notice that fire aspect II contends with pretty much all the fire weapons. So really, why would you use these weapons when you can just put fire aspect II on a sword like Shadow sword. Ease of access to fire damage? You can just enchant a book with fire aspect and use an anvil to put it on an AoA sword. ~~(doesn't seem like you can put fire aspect on gbs in survival but shh)~~

Bows are also a similar scenario. Infernal Bow, Baron Bow, and the Flame enchantment all add 4 fire damage, but Flame does not stack with either bow that already inflicts fire, so yeah... that's the second time I've said "so yeah..." in this post.
(Don't get me wrong Baron Bow is still good!)

**Comment by Tslat** [comment]
May only be possible if the arrow's effect applies before the bow's.. I'll have to look into it and see how it works
