### ISSUE TITLE
Elecanyte and Exoplate work on non-physical damage

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#644]
**Mod Version**
3.1.1

**Describe the bug**
Elecanyte's text says it should only work against physical attacks (melee attacks, arrows, bullets), but it's also working on the non-kb non-physical projectiles fired by Goblins/Lingers/Web Reapers and stuff.

Exoplate also works on non-physical damage, even though it says the opposite.

**To Reproduce**
Steps to reproduce the behaviour:
Get hit by a non-physical projectile in Elecanyte/Exoplate

**Expected behavior**
Elecanyte/Exoplate not working on those types of projectiles

**Comment by Tslat** [comment]
Fixed
