### ISSUE TITLE
Can u make the ghost less aids?

### ISSUE THREAD

**Issue by Spaceboii** [Tslat/Advent-Of-Ascension#648]
**Describe the new feature you think would be good to add**
A way to see the ghost before it kills

**Add any alternative implementations you think might work**
An item maybe? or buff?
**Include any additional background information**
I have no knowledge of previous things

**Comment by Immortallis1** [comment]
Ghost just uses mc invisibility effect. It's actually not that strong and it doesn't go invis before it's within range of you. It also doesn't spawn nearly as often as it used to. Just be observant and start spam clicking if something is near you (if only to know where it is).
