### ISSUE TITLE
Item Use Delays

### ISSUE THREAD

**Issue by Fleega** [Tslat/Advent-Of-Ascension#649]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
Gun Holstering
**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
For holster times on guns, they could use the system ender pearls have https://youtu.be/svAbF--d3WA
**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?

**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
hi lol

**Comment by Tslat** [comment]
hi lol

**Comment by VBGaming** [comment]
are you okay tslat? also is the channel yours fleega?
