### ISSUE TITLE
Hydrangic armor crash

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#651]
**Mod Version**
3.1.1

**Describe the bug**
Was testing Hydrangic armor earlier and it seems when the set effect activates (going down to 10% hp), the game crashes. It seems to be a pretty deadly one because after that I could not enter my test world and had to make a new one.

Crash report: https://pastebin.com/cFPXW56q
Did test and it does happen with AoA as the only mod.

**To Reproduce**
Wear Hydrangic armor and get the set effect to activate.

**Expected behavior**
The game not crashing.

**Comment by Tslat** [comment]
Fixed
