### ISSUE TITLE
Scrubbies shouldn't attack villagers

### ISSUE THREAD

**Issue by Sonicwave** [Tslat/Advent-Of-Ascension#656]
Scrubbies currently attack villagers similar to zombies. My issue with this is that villagers don't run from them and they don't burn in sunlight like zombies do, so once it becomes day (or even during the night) villagers walk out of the house only to be instantly killed. In certain cases, they can also be attacked and killed through closed doors or corners.

This forces players (or iron golems, which spawn infrequently and are attacked by other mobs) to intervene to prevent all of the villagers from dying; they have enough trouble running from zombies as it stands.

**Comment by Tslat** [comment]
Consider it done
