### ISSUE TITLE
Improving the AoA menu

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#657]
**Describe/name the existing feature this suggestion relates to**
The AoA menu. (the ingame one)

**Describe the change or feature you think would be good to see**
I think the new GUI is really nice, though I think some things can be done to make it even better. These are mainly small nitpicks I want to see improved on.

**The key used to open the menu should also be able to close it**
Currently, the only way to exit out of the menu is pressing ESC. I think it should be like the inventory where both ESC and the key used to open the inventory can close it. I know the AoA menu also pauses the game but I think it would make things flow better.
It'd be a minor change, but it can be a little annoying reaching for ESC every time I want to close the menu.

**A way to see skills level up without opening the menu**
I think the main "issue" with the new GUI is that there's no way to see progress on skills without opening the menu, which I think can mess with the flow a bit.

You know the little scrolling text at the top right that pops when you get xp for any skill? I feel like there should also be text when you level up as well. (You don't see it in the latest version because it's not rendering correctly IIRC)

It would show up in the same place as the xp text, but it would be on screen for a bit longer (1.5 seconds?). It would also be a slightly different color to make it stand out a bit more, maybe light green? (&a). It would simply say "Reached level x in [skill name]"
And of course, disabling the xp text in the config would also disable this level up text.

The GUI would still be important for seeing exact progress on a skill, but i think the scrolling text would be helpful for those who want to immediately see what skill they leveled up in without opening the menu.

**Include any additional background information**
The guides section does not have an Extraction guide.

**Comment by Tslat** [comment]
This was basically covered in 3.1.2.b
