### ISSUE TITLE
Require a minimum forge version

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#658]
Earlier someone went on the discord with a really outdated forge version and it caused a crash. I had them update but IMO AoA should have a minimum forge version (most likely 2768, but definitely something above the "crashing versions" one) to prevent stuff like this and force people to update.

**Comment by Sagisolar** [comment]
Is it really Scimi's job to tell people to update the thing that literally makes mods work?

**Comment by Immortallis1** [comment]
If the version of forge being used is so old that it causes crashes without explicitly saying why then yes lol

**Comment by Tslat** [comment]
This has been done
