### ISSUE TITLE
Creep-Lunar Event

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#66]
**Describe/name the existing feature this suggestion relates to**
The issue of creep day has been brought up lately, so here's what I have to say. Since creep day and lunar event are both alien-ish events, so why not merge them?

**Describe the change or feature you think would be good to see**
This brings about the idea of "Creep-Lunar Event". When a Lunar Event occurs in the overworld, there is a 1/8 chance for it to be "creep-lunar event". The "Strange things are upon us" message is replaced with the "Creepy things are upon us". 

During this special variation of the event, the lunar event mobs can spawn as normal, however they all have a green palette/green aura surrounding them (maybe not all mobs, just specific ones) . They also have buffed stats. They would also be immune to explosions. Each mob of the lunar event would gain an ability:

*Irkling - creates an explosion whenever it hits the ground.
*Roloscope - weakness effect is amplified/enhanced. Heals 2x from explosions.
*Modulo - fires projectiles that make small explosions upon impact and/or has a faster fire rate.
*Walker - Maybe gains the ability to spawn bombs? Inflicting explosions AND fire to nearby players seems a little much. 
*Vertebron - hard to think up an idea for this one. Maybe amplified/enhanced knockback. Heals 4x from explosions. Maybe gets random buffs useful to itself if caught in an explosion?

<s>These mobs would still drop orbulons, but they will have an enchanted tint to them. Can be used to craft creeponian bricks, instead of lunar bricks.</s>

In addition, the Host can also spawn rarely. The Host would have a changed AI, where it would fly over the player and drop bombs on the player, instead of spawning creepers. The Host could also remain still in the air and let out a signal making all hostile lunar-creep event mobs in a 64x64x64 radius hostile to the target player.  The Host could possibly make nearby lunar event mobs who don't have the special aura have the special aura. The Host would be immune to explosions.The Host would kinda serve as a "mini-boss" in this way. 

On hard difficulty (or normal and hard) the Host could gain an additional attack where it randomly comes down on the ground, doing damage to all entities (not just player) within a 15x15 radius. Damage done is dependent on the y-elevation, the closer to the y-elevation of the host the entity is, the more damage received (max 15 blocks). 

When defeated, the host would drop gunpowder and up to 5 creeponia realmstones. Its stats would be buffed to accommodate its miniboss status. 

The event will end with "The creepy things begin to vanish" instead of "The strange things begin to vanish".

**Comment by Immortallis1** [comment]
Honestly, "creep-lunar" sounds like a weird name. That being said lunar event is kind of pointless so what you suggested make sense. I still think that both events can be expanded on their own though.
