### ISSUE TITLE
Toggle Mob Overheads

### ISSUE THREAD

**Issue by GuerreroCraft61** [Tslat/Advent-Of-Ascension#661]
**Mod Version**
What version of the mod are you on?
3.1.1
**Describe the bug**
Sometime the mod toggle automaticaly the mob overheads and is annoying
My Mod List: https://paste.dimdev.org/enanoqayuf.rb
**To Reproduce**
Steps to reproduce the behaviour:
1. Sometime when join the world

**Expected behavior**
Don't toggle automaticaly

**Screenshots**

**Comment by Tslat** [comment]
Yeah I'm not sure what your issue is here

**Comment by GuerreroCraft61** [comment]
Is this, but sometime it toggle automatically 

Gif --> https://gyazo.com/8e6d27649c6f82c7688fdf313fff5d60
![Captura](https://user-images.githubusercontent.com/30746531/57568274-45f68680-73e5-11e9-94df-2f8c04df2249.PNG)
![Captura2](https://user-images.githubusercontent.com/30746531/57568275-468f1d00-73e5-11e9-97aa-1ba13725e4bf.PNG)

**Comment by Tslat** [comment]
Ah I see what you mean..

Yeah this has been fixed in 3.1.2
