### ISSUE TITLE
The mob don't have icon

### ISSUE THREAD

**Issue by GuerreroCraft61** [Tslat/Advent-Of-Ascension#662]
**Mod Version**
What version of the mod are you on?
3.1.1
**Describe the bug**
At the top of the mobs don't show the icons (you have the level to attack, you don't have lvl, is inmune to fire,...)
**To Reproduce**
Steps to reproduce the behaviour:
Is random, sometime it word, and sometime no

**Expected behavior**
Always have icon

**Screenshots**
![2019-05-11_12 19 53](https://user-images.githubusercontent.com/30746531/57568698-42fe9480-73eb-11e9-85ab-11b6889c4e31.png)
![2019-05-11_12 20 06](https://user-images.githubusercontent.com/30746531/57568699-43972b00-73eb-11e9-9348-e46dbad43e30.png)
![2019-05-11_12 21 58](https://user-images.githubusercontent.com/30746531/57568701-43972b00-73eb-11e9-8fad-8b63e05f958b.png)

**Comment by Tslat** [comment]
You probably toggled it off - check your controls for the button that toggles them off/on

**Comment by GuerreroCraft61** [comment]
Ok, is the toggle moboverhead control
