### ISSUE TITLE
Mending table is weird if blocks are placed on it

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#669]
**Mod Version**
3.1.1

**Describe the bug**
Unlike other "table" blocks, blocks can interact with Mending table if you're not crouching.

If you place a block on mending table, the block is deleted, but if you do stuff like open your inventory or open a GUI like a chest, the blocks come back. As far as I know this is the only exception.

**To Reproduce**
Steps to reproduce the behaviour:
Place a block on Mending table

**Expected behavior**
Mending table being like other "table" blocks.

**Comment by Tslat** [comment]
Fixed
