### ISSUE TITLE
Abyssal Shadow Forest

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#67]
Hello,

I have noted that I have come across the Abyssal Shadow Forest biome in the Overworld. Here is a screen shot of the biome, with the debug menu open. I hope you sort this issue out soon.
![2018-11-03_00 55 49](https://user-images.githubusercontent.com/44715964/47946459-d10d3600-df03-11e8-9f44-dde548ab55a3.png)
![2018-11-03_00 43 41](https://user-images.githubusercontent.com/44715964/47946460-d1a5cc80-df03-11e8-86f8-c3acac7ada7a.png)

**Comment by EatingSilencer** [comment]
This is a biome ID conflict. You have to change this on your end - by going into the mod's config file and changing the biome id to something different (less than 255).

**Comment by Tslat** [comment]
This is a biome id conflict with another mod.
As Silencer said, go into your mod configs and make sure no two biomes have the same ID set.

**Comment by Seishan123** [comment]
Thanks for the feedback. I found that the Witchwood Forest from Ars Magica 2 has an ID of 100, same as Abyssal Shadow Forest. Thanks for your help.

**Comment by Seishan123** [comment]
Hey at least we know that it snows in the Abyss haha

**Comment by sirnaturewriter** [comment]
I actually had the same issue, but with biomes o'plenty biomes. So I had precasian forests and frozen abyssal biomes literally everywhere. That was NOT fun to play with.

**Comment by Tslat** [comment]
You should update to 1.12 then ;)
