### ISSUE TITLE
Crash when open world

### ISSUE THREAD

**Issue by KRYKOT** [Tslat/Advent-Of-Ascension#672]
**Mod Version**
3.1.1 

**Describe the bug**
It just crashes

**To Reproduce**
Open any world.

**Expected behavior**
I think it is clear

**Screenshots**
I have crash log instead
[crash-2019-05-16_22.21.57-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/3188947/crash-2019-05-16_22.21.57-server.txt)

**Comment by Tslat** [comment]
This will be an incompatibility with one of your mods.

Advent of ascension has advancements, and mods that remove the standard advancements code in forge break things, including AoA.
Have a look through your mods and see which one is the culprit

**Comment by KRYKOT** [comment]
Thanks, Reskillable was a problem
