### ISSUE TITLE
Crystal Creator Doesn't Work

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#678]
in 3.1.2+, it makes sure the gemstone IS null before adding it

https://github.com/Tslat/Advent-Of-Ascension/blob/aaf4806547725c6314a1f88ebf744dd9d594978a/source/block/functional/utility/CrystalCreator.java#L56

**Comment by Tslat** [comment]
It is bugged, but not the way you think it is. the null check is intentional

**Comment by Immortallis1** [comment]
this sucks
