### ISSUE TITLE
[Suggestion] Add new advancements

### ISSUE THREAD

**Issue by 22zhuyansong** [Tslat/Advent-Of-Ascension#68]
Describe the new feature you think would be good to add
Add every specific advancements for every single mod dimension.

Add any alternative implementations you think might work
No more.

Include any additional background information
No more.

**Comment by BoringTalking** [comment]
while I like the idea, some examples would be nice. Like for when you enter dustopia you get the achievement "shadow realm" or something.

**Comment by Cruuk** [comment]
Yeah examples would be nice.

Either way Scimi did talk about adding advancements a while back so there's that at least.

**Comment by Immortallis1** [comment]
"Quests" are kind of another namedropped feature that were slightly partially coded and...yeah.

**Comment by Tslat** [comment]
Done
