### ISSUE TITLE
Overworld Mob Difficulty ->Overworld Event details unclear

### ISSUE THREAD

**Issue by AtomicWaffle14** [Tslat/Advent-Of-Ascension#681]
The Overworld mobs are spawning during the daytime and within the spawn area, making starting almost impossible unless you immediately dig down. Many of these overworld mobs are able to immobilize you and/or kill you in a hit or two, and it's a major turn-off the new players. 

Perhaps something should be done to alleviate this? I would recommend making the overworld mobs only spawn at night (or the difficult ones, at least), or making the mobs get stronger the further you are from spawn. You could add a line in the Config file to do these things maybe? 

For example, spawning in just for a Death-Hunter to throw my ass 50 blocks and then I get immediately killed by something else.

I know the overworld isn't supposed to be safe with this mod, but this is kind of ridiculous.

**Comment by Tslat** [comment]
What version of the mod are you on?

**Comment by Immortallis1** [comment]
Death hunter is the ONLY mob in the overworld that can do that lol

**Comment by AtomicWaffle14** [comment]
> What version of the mod are you on?

I'm playing on version 3.1.2.a

> Most mobs are around zombie level with attack strength, the one-two shot mobs are either event mobs or just outliers.

The problem is that these stronger mobs are everywhere, such as the Headless Destroyers, Hunters, Twin Reapers, and Triclopses. And they spawn in pods too.

![2019-05-21_23 04 05](https://user-images.githubusercontent.com/39530149/58144592-f69e2a80-7c1c-11e9-85be-8e071413e43a.png)

**Comment by Tslat** [comment]
That is what it means, yeah. Rough event to get first day.

Check the Advent Gui in the guides tab, it has info on the various events.

Long story short, hide if you can't afford a fight

**Comment by Immortallis1** [comment]
Yeah. All the mobs you mentioned (except headless hunter which spawns normally in the dark) are death day only. They will not appear at all on the vast majority of days.

**Comment by AtomicWaffle14** [comment]
Okay, thanks for the tip. As a person brand-new to the mod I got very confused. It might help to make a limit on how early the events can occur in relation to when the world was created, or more realistically an option in the config to change the rarity of the events.
