### ISSUE TITLE
Events shouldn't happen on the first day/night (other than full moon for technical reasons)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#684]
**Describe/name the existing feature this suggestion relates to**
Events

**Describe the change or feature you think would be good to see**
Simply put, events should not happen on the first day and night of a Minecraft world. New players already have trouble with Overworld mobs in the daytime, and most event mobs are really strong, stronger than the mobs in the ""lategame"" dimensions.

It becomes even worse when a day event happens on the first day. Even a new player shouldn't have too much trouble with stuff like Cyclops and Chargers if they know what they're doing, but imagine a new player's face when they get thrown around by a Death Hunter and then get 1-hit by a Headless Destroyer. Even if a Death day happens on the second day, 1 day/night should at least be enough for them to get used to stuff...

The mod is supposed to be challenging, but this is too much. Other than like Nether/Candyland or something the event mobs are basically the toughest normal mobs in the mod HAHAHAHA.

Concerning Full moon: As far as I know it may have to be an exception. I'm not sure if it's possible to change what type of moon appears on the first night.

And even then, it'd just be really weird for the first full moon to not have the event, maybe that's just me. Could always balance the full moon mobs themselves. ¯\_(ツ)_/¯

**Include any additional background information**
I wonder if somewhere out there, there is someone who spawned in a savannah, and had all the day events happen... and still played the mod. That's what the legend says.

**Comment by Sagisolar** [comment]
Honestly I think Full Moon should always be the on the first day, Just not the other events.
