### ISSUE TITLE
Portal loops is back?

### ISSUE THREAD

**Issue by Zintrek** [Tslat/Advent-Of-Ascension#685]
**Mod Version**
3.1.1

**Describe the bug**
The good ol infinite portal loop

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into a portal, only tested on the two realmstones we have on the server.

Forge version/server version: forge-1.12.2-14.23.5.2768

**Comment by Tslat** [comment]
Are you running Aether II by any chance?

**Comment by Zintrek** [comment]
Oddly enough, yes I am. One of those super specific/weird conflicts?

**Comment by Tslat** [comment]
Aether II screws with other mod's portals.
It actually screws with a number of things. But either way - it's functionally impossible to fix it from my side since they're directly interfering with aoa from their side.

Take this to them, or drop Aether II

**Comment by Zintrek** [comment]
Thank you so much! I was very confused on this, time to drop Aether it is! Thank you for replying!
