### ISSUE TITLE
AoA hostile mobs not spawning on the first day 

### ISSUE THREAD

**Issue by MerekiDor** [Tslat/Advent-Of-Ascension#687]
![I'm fucked](https://user-images.githubusercontent.com/27777844/58258962-45aea180-7d7c-11e9-9dc8-7517746160bc.png)

_Note: I've seen that Cruuk's suggestion about events not happening on the first day. This idea, however, came to me before i've seen it, so yeah._

I don't really think whether this is worth the coding and stuff, but in my _humble_ opinion i think there shouldn't be any AoA mobs at all at the first very day. Why? Because tryhards like me who play without keepInventory on hardest difficulties probably need to settle in for the first day; currently, it's a struggle to build even a small house, because while building, harvesting materials or whatever else all kinds of creatures will obviously try to kill you. Sasquatches, chargers, cyclops, cyber-furries and radical feminists - they all do their best so the player can't even settle in, and such a simple task as building 1 block becomes an achievement.

Also, since the first night is a full moon, it kinda makes sense. Like at the first day there are no monsters at all, but then there's full moon and AoA creatures begin spawning, and this is where the journey begins, basically.

Alternatively there could be some better ways to protect yourself. Building a pillar out of dirt and trying to kill 30-50hp mobs with bare fists isn't really fun. Believe me.

**Comment by Sagisolar** [comment]
I think it would even more of a disaster for newbies because it would be weird having a totally peaceful first day. Then the second is when shit hits the fan. Newbies would find this really inconsistent.

**Comment by Tslat** [comment]
What Sagi said, is my opinion.

AoA is brutal, people need to stop treating it like they're a walking god
