### ISSUE TITLE
Sealord diving helmet doesn't make you surf in water

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#689]
**Mod Version**
3.1.2.b

**Describe the bug**
Sealord doesn't increase your swimming speed when in water. Went underwater and everything. Also tested with AoA as the only mod.

**To Reproduce**
Steps to reproduce the behaviour:
Go in water with Sealord diving helmet and move around.

**Expected behavior**
Sealord increasing your swimming speed.

**Comment by Tslat** [comment]
No longer relevant
