### ISSUE TITLE
Almost every single ranged mob taking every bit of my health with full armor.

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#692]
**Mod Version**
3.1.2 b

**Describe the bug**
Almost every single mob that shoots projectiles takes every single bit of my health and leaves me down to half of a heart, even when I have full armor on me.

**Screenshots**
[Bug.zip](https://github.com/Tslat/Advent-Of-Ascension/files/3218995/Bug.zip)
It's a small video showing proof.

**Comment by mrcakesamurai** [comment]
How can I explain this further!?

**Comment by Tslat** [comment]
The labels aren't for you, they're for me.

Does this happen if no other mods are installed?

**Comment by mrcakesamurai** [comment]
I honestly have no idea, because I don't have any other mods installed that have different dimensions.

**Comment by Tslat** [comment]
I'm not asking about mods that have different dimensions

Does this happen if **no other** mods are installed

**Comment by mrcakesamurai** [comment]
Oh! Yes.

**Comment by Tslat** [comment]
Upload your log file (latest.txt or whatever it is)

**Comment by mrcakesamurai** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/3221618/latest.log)

**Comment by Tslat** [comment]
Can you do one with no other mods, and make the glitch happen - then send me that log file?

**Comment by mrcakesamurai** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/3224242/latest.log)

**Comment by Tslat** [comment]
Do me a favour and use the _recommended_ version of forge
