### ISSUE TITLE
My Mysterium Portal is taking me to Greckon instead of the Overworld?

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#695]
**Mod Version**
3.1.2 b

**Describe the bug**
My mysterium portal I have takes me back to Greckon instead of going back to the Overworld.

**Expected behavior**
I'm supposed to go back to the Overworld instead of Greckon.

**Screenshots**
[Bug.zip](https://github.com/Tslat/Advent-Of-Ascension/files/3219579/Bug.zip)
A video explaining the bug.

**Comment by Tslat** [comment]
This can happen sometimes as the portal system isn't 100% perfect.
Relaunching your game should reset it to its normal state I think..

**Comment by mrcakesamurai** [comment]
It didn't work.

**Comment by Ryunari** [comment]
I confirm. I had this problem in my previous map (in 3.1.1). I relaunch the game 3 times and no change appeared so I created another map.

**Comment by Tslat** [comment]
Portal logic was cleaned up a bit in 3.2 and a command added to help alleviate this issue
