### ISSUE TITLE
Ideas for new crystevia mobs

### ISSUE THREAD

**Issue by profilename14** [Tslat/Advent-Of-Ascension#696]
I would like to suggest two new ideas for future crystevia mobs with new colors

**Dark Blue: Construct of water**

- A flying mob that looks like a large crystal bubble with some other crystal bubbles floating around it.

- Has 75 health and low speed, hovers to its target and makes bubbling sounds

- When it comes in contact with the player, instead of attacking, it attaches around the players head and fills up with water

- The breath meter is visually drained in one second and afterwards the player takes normal drowning damage.

- Sloshing sounds play while the player is drowning, and filling up sounds play while the construct is filling up with water

- Can be killed when it is attached to the player to remove it.

- If the player is immune to drowning somehow (water breathing, Oceanus diving helmet, etc.), then the construct does no damage to the player. 

- If it is not killed for 30 seconds and the payer survives, then the construct will detach and float away.

- Drops dark blue gemstones, which can be turned into crystals in a blue crystal station, just like normal blue crystals

- Dark blue crystals can be traded at the crystal trader for special items

**Rainbow: Construct of Greed**

- Rare mob

- Looks like a rainbow crystal with small spider legs that is 1 block tall, 

- Has 40 health and a high speed, wanders around until it sees a player

- When it sees a player within 16 blocks, it makes a noise and runs away from them until it is 36 blocks away

- Can climb walls to escape the player

- If it gets 36 blocks away from the player, then it will dig itself underground and despawn

- Drops 5-10 crystals (not gemstones) of a random color when killed

**Comment by Immortallis1** [comment]
A couple other ideas that float around.

Construct of Gravity: Reverses gravity around the player, may be able to reverse its own gravity (see Biphron in DRPG). Don't know what it drops.

Constructor: Semi-rare mob, spawns all types of Constructs (except itself of course) upon hitting a player with its ranged attack.
