### ISSUE TITLE
oredict food names

### ISSUE THREAD

**Issue by Jackiecrazy** [Tslat/Advent-Of-Ascension#698]
**Describe/name the existing feature this suggestion relates to**
Food. Even though certain foods are most definitely just a rehashed something else (charger shanks and halycon beef are, for all purposes, chicken and beef), they're not registered appropriately in the forge ore dictionary. This means they cannot be used in Pam's Harvestcraft recipes (or any other ones, for that matter), decreasing their utility.

**Describe the change or feature you think would be good to see**
Register foods under listAllmeatraw, listAllfishraw, listAllporkraw, listAllchickencooked, listAllfishcooked, etc. appropriately (I don't know why it's not in camelcase, naming conventions). Purely QoL but it increases compat and doesn't take long.

**Comment by Tslat** [comment]
Ore Dictionary entries are mostly community made - there's no actual standard for any of this.
If you can find a definitive list of the food lists that pam's has I'll look into it.

Without that there's not much I can do

**Comment by Jackiecrazy** [comment]
the community consensus seems to be "listAll[food name]", where food names are all uncapitalized and include:
berry, fruit, smoothie, milk, grain, fish(for meats there is both cooked and raw versions, e.g. fishcooked and fishraw), meat, beef, chicken, pork, turkey, venison, greenveggie, herb, spice, mushroom, veggie
It appears that putting foods under these oredict names would allow Harvestcraft to accept AoA food as substitutes. As there is no way to cook the hauling fish, though, I wonder if they're assumed to be cooked out of the box.

**Comment by Tslat** [comment]
yeah that's pretty vague..
I've seen at least 2 different oreDict entries that _don't_ follow that policy.
I'd need to see where the lists are defined to do so

**Comment by Jackiecrazy** [comment]
https://github.com/MatrexsVigil/harvestcraft/blob/79ed308b37e576a6ef1a15161a080cc8314476db/src/main/java/com/pam/harvestcraft/item/GeneralOreRegistry.java
lines 93-134

**Comment by Tslat** [comment]
Perfect, thanks :)

**Comment by Tslat** [comment]
This was done a while ago
