### ISSUE TITLE
Guide and bestiary displaying in Chinese

### ISSUE THREAD

**Issue by Angrydog001** [Tslat/Advent-Of-Ascension#699]
**Mod Version**
3.1.2.b

**Describe the bug**
Currently guide and bestiary has displaying issue (Garbled) in Chinese. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Switch language to Chinese (simplified Chinese, traditional Chinese). 
2. Click on 'DELETE'. 
3. You will find garbled words on guide and bestiary tab. 

**Expected behavior**

Modify charset reading from ANSI to UTF-8 in Chinese. 

p.s. 1. If there is a detailed screenshot, I will provide it later. 
2. Reported by 3182898465 (QQ).

**Comment by Tslat** [comment]
They are in UTF-8, and their contents are fine in jar 3.1.2.b.....
I'll have to see if something is going on ingame

**Comment by Tslat** [comment]
Fixed after 3.1.2.b
