### ISSUE TITLE
Mobs does not spawn in other dimensions

### ISSUE THREAD

**Issue by lolal3** [Tslat/Advent-Of-Ascension#706]
While spawners are actually active and working, mobs does not spawn on blocks in dimensions added in AoA. could someone explain why?

**Comment by Immortallis1** [comment]
What version of the mod are you on (e.g. tslat 1.1.3, 2.4.B, 3.1.2.b)
What other mods do you have installed? (full list)
What mobs aren't spawning
What dimensions don't they spawn in
What blocks are they not spawning on
Are you on peaceful difficulty

**Comment by Tslat** [comment]
Also provide a log file please

**Comment by lolal3** [comment]
1)3.1.2.b (but also with 3.1)
3) every mob from the dimensions AoA adds (so with the exception of the overworld and the nether)
4)I visited the haven, Precasia, Immortallis,Mysterium,Creeponia, Borean
5)mobs does not spawn naturally while spawners work
Difficulty:Hard

**Comment by Immortallis1** [comment]
Please provide a log file, also are you using spongeforge?

**Comment by lolal3** [comment]
2)https://paste.ubuntu.com/p/66hwQnWTkn/
log file I guess it should be this one https://paste.ubuntu.com/p/8RNdxGWbVN/
I do not use Spongeforge but Curseforge (if it's what you meant)

**Comment by Immortallis1** [comment]
Are you using custom mob spawner by any chance?

**Comment by Immortallis1** [comment]
also that's not a log btw, give your latest.log if possible

**Comment by Tslat** [comment]
The secondary link he provided is the log, all good

**Comment by Kasia1403** [comment]
@lolal3 Does this bug happen also without Custom Mob Spawner ? I have similar problem. Mobs which should spawn in Creeponia don't spawn there.  My issue number #3820
