### ISSUE TITLE
Bosses killed by throwing weapons don't drop items (for the most part?)

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#708]
**Mod Version**
3.1.2.b

**Describe the bug**
It seems that when a boss is killed by any throwing weapon, they will not drop any of their items. The "player defeated boss!" message does not appear either.

Oddly enough, it seems to be kind of finicky. Certain throwing weapons do cause the items to actually drop... Sometimes. This seems to mainly happen with Chakram, Hellfire, and Vulkram. Sometimes they drop, sometimes they don't. In one instance I killed Smash with Chakram and the items dropped, but there was no "player defeated boss!" message.

It could be dependent on the amount of HP the boss has before dying? I am not sure. Either way, from testing the most consistent throwing weapons appear to be Slice star and the grenades. Every kill done with Slice star has caused the items to not drop, and every kill done with Grenade/Runic bomb has caused the items to drop.
Maybe Slice Star can cause items to drop under the right conditions? No clue.

(EDIT: Just now I used Megagun to bring Smash down to 4 hp, then I threw 1 Slice Star and he dropped his items... but no message. Nice)

Also, even if the items don't drop and the messages doesn't pop up, advancements appear to be an exception.

**To Reproduce**
Steps to reproduce the behaviour:
Kill a boss with a throwing weapon, even if another weapon type deals 90% of the damage throwing weapons must deal the finishing blow. (I also recommend testing with all of the throwing weapons since it seems to be finicky)

**Expected behavior**
Throwing weapons being like the other weapon types and causing bosses to drop their stuff when killed.

**Comment by Tslat** [comment]
Fixed after 3.1.2.b
