### ISSUE TITLE
Weapon Parts

### ISSUE THREAD

**Issue by RugratCoder94** [Tslat/Advent-Of-Ascension#71]
The new loot system planned for AoA makes it so that weapons are to be crafted with materials.  As a result, wouldn't it make sense for upgrades to be the same way?

My proposal is to have different materials that can be used to upgrade weapons. Below is an example diagrams of how this could work.

![table](https://user-images.githubusercontent.com/44593338/47959629-c790d600-dfb6-11e8-9bec-4935a5e7ab38.png)

The items on the bottom (forgive the shoddy sprite work) would be usable for all weapons compatible with the seaside upgrade kit, the Aquatic Stones and Ocean Paint
The other items, being the magnum scope, magnum stock, and magnum barrel, would be specific to upgrading that weapon

If that doesn't sound good to you, then just universal upgrade materials would be fine.

**Comment by Sagisolar** [comment]
cool idea
