### ISSUE TITLE
Cooking Fish from Hauling

### ISSUE THREAD

**Issue by RugratCoder94** [Tslat/Advent-Of-Ascension#711]
About as simple as it sounds.  

For purposes of continuity with vanilla fish, I think it would make more sense for fish obtained from hauling to have to be cooked before having their benefits.

The amount of health restored would remain the same once cooked, it just wouldn't be there in the raw variants.  Cooked variants could give as much hunger and saturation as regular cooked fish, or a bit more depending on how high level they are.

**Comment by Tslat** [comment]
Okie dokie
