### ISSUE TITLE
Pristine jar thinks it has been modified

### ISSUE THREAD

**Issue by maladaptly** [Tslat/Advent-Of-Ascension#713]
**Mod Version**
What version of the mod are you on? 3.1.2.b

**Describe the bug**

Server shows this in the log:

> [22:33:34] [Server thread/ERROR] [FML]: The mod aoa3 is expecting signature 8B:DD:EA:C1:48:84:3F:40:E0:B9:F6:92:01:BE:2F:4B:30:71:70:0D for source AoA3-3.1.2.b.jar, however there is no signature matching that description
> [22:33:46] [Server thread/WARN] [aoa3]: AoA3-3.1.2.b.jar appears to have been modified. Why do you do this? No support will be given for this jar. No Exceptions.

But jar is *not* modified. Downloaded twice from CurseForge to make sure. Jar md5sum: 955cb92e1f646962fb23cca0ef8a2991

**To Reproduce**

Launch server with mod enabled.

**Expected behavior**

Simply shouldn't be seeing this message.

**Comment by maladaptly** [comment]
It occurred to me that Forge version is probably a critical detail: 1.12.2-14.23.5.2838

**Comment by Tslat** [comment]
Currently known, don't stress :)
First time the jar has been signed, the compiling didn't work perfectly so it gives off this error unfortunately.

IT doesn't affect anything in the mod so you can safely ignore it - thanks for the heads up

**Comment by Tslat** [comment]
Fixed in 3.2
