### ISSUE TITLE
game crashed in Immortallis

### ISSUE THREAD

**Issue by Leon5Ray** [Tslat/Advent-Of-Ascension#714]
**Mod Version**
3.0.2

**Describe the bug**
Game crashed when playing in Immortallis.

**To Reproduce**
I finished the second game and was teleported to the boss room.Then the game just crashed in a sudden.

[crash-2019-06-09_15.57.36-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/3269657/crash-2019-06-09_15.57.36-server.txt)

**Comment by Tslat** [comment]
Issue is with tinkers construct, see them
