### ISSUE TITLE
Foraging skill doesn't count XP for Underground Biomes blocks/ores

### ISSUE THREAD

**Issue by ddteam90** [Tslat/Advent-Of-Ascension#715]
**Mod Version**
Advent Of Ascension v3.1.2.b
Underground Biomes v1.3.5

**Describe the bug**
Foraging skill counts XP when you digging something, stone, ores and etc., but it doesn't work with Underground Biomes stones/ores.

**To Reproduce**
Steps to reproduce the behaviour:
1. Throw Underground Biomes and Advent Of Ascension into mods folder
2. Launch a game
3. Create a new world/launch existing world and try to dig some time to try to get some XP for Foraging Skill
4. Vanilla stone is counting, Underground Biomes ones - isn't counting.

**Expected behavior**
When digging Underground Biomes blocks/ores you get XP for Foraging skill

**Screenshots**
There is no screenshots.

Essentially, it's a duplicate of #436, but this incompatibility haven't fixed since March.

**Comment by Tslat** [comment]
Duplicate.
