### ISSUE TITLE
Greatblades dont work with changed controls 

### ISSUE THREAD

**Issue by Symetriix** [Tslat/Advent-Of-Ascension#716]
**Mod Version**
What version of the mod are you on?
I use AoA 3.1.2n
**Describe the bug**
I have changed control settings in Minecraft (left click build, right click attack) and when I tried to hit a mob with my greatblade I just got the animation but no damage whatsoever. When I left clicked a mob it instantly dealt the 24 damage (Tidal greatblade) and I was able to spam it with no cooldown.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your control settings
2. Switch your 2 mouse buttons to left click build and right click attack
3. Grab any greatblade and try right clicking a mob with the hit animation, then try left click

**Expected behavior**
I thought the greatblades would just work like a normal sword with my control settings. Had to change it now

**Comment by Tslat** [comment]
Fixed after 3.1.2.b
