### ISSUE TITLE
Metalloid gui still has sapphire ingot texture

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#717]
**Mod Version**
3.1.2.b

**Describe the bug**
The sapphire ingot texture is still on the metalloid gui.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the game.
2. Spawn a metalloid.
3. Open the gui.
4. See the sapphire ingot texture instead of the sapphire gem texture.

**Expected behavior**
The Sapphire Gem texture was in the gui instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/59350860-1e981f80-8ceb-11e9-9bd7-359433d8b8cc.png)

**Comment by Tslat** [comment]
Fixed after 3.1.2.b
