### ISSUE TITLE
Resource systems appear green sometimes when popup for how to play pops up

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#718]
**Mod Version**
3.1.2.b

**Describe the bug**
When the game is started, there sometimes exists a popup telling the player the controls to move and jump. If the resource systems pop up before this closes, they will appear green in color.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the game (must be initial launch).
2. Open a world (might have to be a new world).
3. Wait for the controls popup to appear.
4. Without making the popup disappear, open the Resource Systems.

**Expected behavior**
The resource systems do not appear green.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/59351270-ff4dc200-8ceb-11e9-8e28-2d3c5b4008ff.png)

**Comment by Tslat** [comment]
Fixed after 3.1.2.b
