### ISSUE TITLE
The Creeponia ores should be considered gems

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#721]
**Describe/name the existing feature this suggestion relates to**
The Creeponia ores

**Describe the change or feature you think would be good to see**
Currently, the Creeponia ores act like ingots, they drop the block when mined and must be smelted.

I think they should be gems, the sprites look nothing like ingots, but moreso resemble gems.
Also, they have names like "Gemenyte" and "Jewelyte". Yeah...

**Comment by Tslat** [comment]
Sure thing
