### ISSUE TITLE
A config option to disable random events or change their trigger rate.

### ISSUE THREAD

**Issue by Raithion** [Tslat/Advent-Of-Ascension#724]
**Describe/name the existing feature this suggestion relates to**
The Event system.

**Describe the change or feature you think would be good to see**
I would like an option in the config file to disable the random events or change their spawn rate. It appeals to a pretty niche crowd of people, similar to the already existing "disableOverworldMobs" option. Nonetheless, I think more customization is always a good thing.

**Comment by Tslat** [comment]
Has been done
