### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by GluttPV** [Tslat/Advent-Of-Ascension#732]
**Mod Version**
3.1.2.b for minecraft 1.12.2 on forge version 14.23.5.2836

**Describe the bug**
the mod crashes on game start-up. I have removed the mod and the game loads fine without it. I have removed optifine and replaced AoA and it still crashes. I had no previous AoA config but I deleted the generated config folder anyway and reattempted to load it up just in case. No luck.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add AoA3-3.1.2.b.jar to mods folder
2. Attempt to load Minecraft through Forge.
3. The game crashes with the following message:

**Expected behavior**
I expected to load the game normally and play Advent of Ascension

Crash report:
[crash-2019-06-17_15.43.15-client.txt] (https://github.com/Tslat/Advent-Of-Ascension/files/3297574/crash-2019-06-17_15.43.15-client.txt)

**Comment by Tslat** [comment]
This is a wazworld crash
