### ISSUE TITLE
Tree Spirit shouldn't spawn in plains

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#735]
**Describe/name the existing feature this suggestion relates to**
Tree Spirit

**Describe the change or feature you think would be good to see**
To be honest, I've always found Tree spirit to be a big pretty step-up from the other "beginner" mobs. (Horndron doesn't count!). To *try* and keep it short I don't think it should spawn in Plains. When it's not savannah, desert, or event mobs, I've noticed that the biggest hazard for new players is the Tree spirit, and I do think it may be a bit much, at least for players that just spawned.

They're pretty speedy, have 100% knockback resistance, and 1 hit from them can make you lose roughly 6 hearts from fall damage, and since most players will probably have swords as their first weapon, the window to hit Tree spirits is pretty small. You can only hit them a few times before having to turn around, run, and repeat. Otherwise they will hit you due to kb resist. The hitbox is not as bad as Horndron's but still. (and before you say "get a bow", this whole scenario is referring to like the first 5-10 minutes in a world).

I'm not really saying Tree spirit is horribly misbalanced, there are worse cases. My main issue is just how hazardous Tree spirits are for likely being one of the first mobs you see, compared to the other Plains mobs (other than Horndron).

As I've said earlier, I think Tree Spirit would be better off not spawning in the Plains biome. I don't think it would be a huge nerf, it would still spawn in its other biomes (forests and mountains according to wiki), this would just give starting players a little bit of breathing room. (The ones that spawn in the Plains at least). It would make sense, if you see those biomes as a "step-up" from the Plains biome. They also tend to have more trees.

**Add any alternative implementations you think might work**
Tree Spirit doesn't need to be completely blacklisted from the Plains biome. If for some reason Tree spirits should still spawn in the plains biome, it could rarely spawn next to trees in the Plains biome if possible. (Would still follow hostile mob spawning rules)

You could also do some stuff with regional difficulty? I have no clue how it works, I'm just spitballing here.

~~Or change the Tree Spirit itself~~

**Include any additional background information**
Horndron is probably a worse case than Tree Spirit, but hey one at a time you know.

**Comment by Sagisolar** [comment]
#MAKEHORNDRONNEUTRAL
