### ISSUE TITLE
Soul Storm Texture Change

### ISSUE THREAD

**Issue by RugratCoder94** [Tslat/Advent-Of-Ascension#736]
Soul Storm texture is pretty similar to the Aqua Scepter, might need to be changed.
![image](https://user-images.githubusercontent.com/44593338/59886232-d086ba00-9383-11e9-8925-eaa0e5df1d77.png)
![image](https://user-images.githubusercontent.com/44593338/59886240-d5e40480-9383-11e9-9e64-f863b46725e6.png)

**Comment by Sagisolar** [comment]
Its not lol

**Comment by Cruuk** [comment]
> 
> 
> Its not at all lol

Well he said it, guess we're getting no cool resprite by Ursun then

**Comment by RugratCoder94** [comment]
> Its not at all lol

Better to be safe than sorry buddy

**Comment by Sagisolar** [comment]
> 
> Better to be safe than sorry buddy

It is better to be safe, but it does not at all similar. I'm not against a re-sprite but my reasoning is because Ursun is a pretty good artist so he would probably make it look better than it currently is.
