### ISSUE TITLE
Not exactly sure what this error is, but I believe it has to do with AoA3

### ISSUE THREAD

**Issue by opticalxflamez** [Tslat/Advent-Of-Ascension#738]
**Mod Version**
3.1.2.b

**Describe the bug**
I play minecraft with multiple mods for a bit on my world then relog and attempt to enter the same world, but the game crashes and minecraft presents me with this error:

`The game crashed whilst ticking memory connection
Error: java.lang.ArrayIndexOutOfBoundsException: -96`

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch modded minecraft with this mod and other included
2. Enter a world and play normally
3. After a while leave world
4. Attempt to enter world
5. Game crashes and you see the error

**Expected behavior**
Minecraft to load the world normally

[crash-2019-06-21_18.28.22-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/3316433/crash-2019-06-21_18.28.22-server.txt)

**Comment by Tslat** [comment]
Entirely unrelated to aoa.
Youve either used a newer version of mc and come back and forgot to change your settings, or something has messed with your settings

Delete your options.txt file and let it regenerate
