### ISSUE TITLE
Allow to pack mod's ingots / ore-products to blocks

### ISSUE THREAD

**Issue by GrayLightTaliz** [Tslat/Advent-Of-Ascension#74]
**Describe/name the existing feature this suggestion relates to**
Various ingots added by mod (like limonite, rosite, etc) as well as other products of ore smelting (like runium chunk). Currenty, there is no way to convert them into "blocks" and vise versa. Only native resources allowed to do this (iron, gold, etc)

**Describe the change or feature you think would be good to see**
Add standard receipes of blocks for crafting table: 9 pieces (ingots) makes 1 solid block. Same way as it works with iron, gold, diamonds, etc in original MC.
This makes it easier to collect/transport/keep big amounts of ingots. This also adds some new decorative blocks for building.

**Add any alternative implementations you think might work**
If usual crafting table is not suitable for this feature (technicaly), you can add new (mod's) type of crafting table, which will support block receipes.
Another way of packing ingots could be some sort of backpack with its own inventory [ see reference below ]

**Include any additional background information**
Main idea is: to make working with any (native and mod's) ingot resources in same way: pack them into blocks for compact storage or for decoration.

References:
https://minecraft.gamepedia.com/Block_of_Iron
https://ftbwiki.org/Backpack_(Forestry)

**Comment by Immortallis1** [comment]
I agree with this, always wondered why there were no mineral blocks in this. DRPG was also missing mineral blocks too for the twilight dimensions iirc

**Comment by Cruuk** [comment]
I've wanted ore blocks for a long time as well.

Though granted, if these are added then the crafting recipes of Crystallanium, Shadonatium, Emberium, and Skeletanium should be changed. Their current crafting recipes are 9 Crystallite, Bloodstone, Emberstone, and Skeletal ingots respectively.
