### ISSUE TITLE
Only allow Precasia mobs to spawn above y-level 40

### ISSUE THREAD

**Issue by Merepock** [Tslat/Advent-Of-Ascension#740]
**Describe/name the existing feature this suggestion relates to**
Precasia mobs

**Describe the change or feature you think would be good to see**
When I create strip mines under Precasia to find bone fragments I see that after a short while I get all Precasia mobs that are not in underground dens spawning in the strip mines and it blocks my path to get back to my portal whenever needed. 

Its especially a problem when you just carry a sword so you have more room for stone and foraging drops and a Tortione happens to appear and prevents you from leaving if you have no way to teleport to your portal. It also wouldn't make sense for a Megatherium or a Dyrehorn to reside in a tunnel deep underground.

I think it would be a suitable restriction for precasia mobs to only spawn above a certain y-level (i.e. 40) to reduce this annoyance.

**Add any alternative implementations you think might work**

**Include any additional background information**

**Comment by Cruuk** [comment]
As a trade off let's make the underground mobs spawn naturally down there instead of in the dens haha

**Comment by EatingSilencer** [comment]
I liked this idea, but rather than y-level restrict it, I think it should be restricted based on block-type (Precasia Grass).

That way we can have superflat worlds where the mobs can spawn in low y-levels.
