### ISSUE TITLE
Crashing when adding AoA3 to Direwolf20 1.12.2 Modpack

### ISSUE THREAD

**Issue by LordyLords1** [Tslat/Advent-Of-Ascension#741]
Trying to add this mod to Direwolf20 1.12.2 and I keep crashing. No, I can not avoid using this modpack because my friend wants to use it. I was hoping someone with more expertise with looking at crash logs could tell me what exactly the problem is. Thank you!

https://pastebin.com/nDrfC8MT

**Comment by Tslat** [comment]
You ran out of block Ids.

Either you're trying to use an old world, or your pack has too many blocks.

If this happens on a clean world, then you're out of luck

**Comment by LordyLords1** [comment]
> You ran out of block Ids.
> 
> Either you're trying to use an old world, or your pack has too many blocks.
> 
> If this happens on a clean world, then you're out of luck

This happens when I'm booting the game up, not when I'm starting up a world

**Comment by Tslat** [comment]
Ok then you have too many blocks in your pack. Something needs to go

**Comment by EatingSilencer** [comment]
Alternatively, would it be possible to add notenoughids to your pack (or whatever its called)?
