### ISSUE TITLE
"there is no signature" error

### ISSUE THREAD

**Issue by rouslawn** [Tslat/Advent-Of-Ascension#742]
**Mod Version**
AoA3-3.1.2.b

**Describe the bug**
The mod aoa3 is expecting signature 8B:DD:EA:C1:48:84:3F:40:E0:B9:F6:92:01:BE:2F:4B:30:71:70:0D for source AoA3-3.1.2.b.jar, however there is no signature matching that description
[Server thread/WARN] [aoa3]: AoA3-3.1.2.b.jar appears to have been modified. Why do you do this? No support will be given for this jar. No Exceptions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Installed mod into mods folder
2. When server runs the following error appears.

I didn't modify the downloaded file and uploaded it on the server using scp

**Comment by Tslat** [comment]
Known issue - doesn't cause any problems, you can ignore it for now :)
Thanks for reporting it
