### ISSUE TITLE
Mob Drop Configs

### ISSUE THREAD

**Issue by DrDarkfire** [Tslat/Advent-Of-Ascension#743]
**Describe the new feature you think would be good to add**
As a pack dev, I want to tweak the drops of all the mobs in the mod. What I would like is a way to edit the weights, how much, and what the mobs drop in a config file.

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
crafttweaker integration to edit drops could work as well
**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?
I don't think so?

**Comment by Tslat** [comment]
The loot update intends to do this. 
This will be a thing very soon :)
