### ISSUE TITLE
AoA Mobs causing crashes

### ISSUE THREAD

**Issue by LordyLords1** [Tslat/Advent-Of-Ascension#744]
So In response for having another issue with this mod, I decided to make my own modpack to play this mod. Only to find out that after getting killed by or damaged by mobs (I don't know what it is honestly) the game decides to crash. I am open to lan and me and my friends are trying to play it. Crash report posted below.

https://pastebin.com/JNhdR2hX

**Comment by Tslat** [comment]
Take it to tinkers, this has nothing to do with me

`java.lang.ClassCastException: net.tslat.aoa3.entity.mobs.overworld.EntityWarclops cannot be cast to net.minecraft.entity.player.EntityPlayer
    at slimeknights.tconstruct.tools.modifiers.ModBeheading.getBeheadingLevel(ModBeheading.java:74)
    at slimeknights.tconstruct.tools.modifiers.ModBeheading.playerDrop(ModBeheading.java:108)`
