### ISSUE TITLE
Realm Shifter should also sell realmstones that drop in the overworld.

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#748]
**Describe/name the existing feature this suggestion relates to**
Realm Shifter Trades

**Describe the change or feature you think would be good to see**
The title of this issue is self-explanatory: Realm Shifters only take realmstones in exchange for coins, but they should also be able to sell realmstones that drop in the overworld (Haven, Abyss, Mysterium, Precasia, Deeplands, Celeve, Iromine, L'Borean, Immortallis and Creeponia). A realmstone would be more expensive based on how "Late-game" it is. If for instance a player spawns in a seed in which there is no jungle to be found whatsoever then they cannot access Precasia and therefore a decent portion of content in the mod (Gardencia, Vox Ponds, Weapons, tools and armor requiring skeletal ingots etc.). I will always spend a certain amount of time creating and deleting worlds in creative until I spawn next to or in a jungle biome just so I know I can access Precasia. This change will allow players to travel to all dimensions without being restricted by lack of jungle biomes, and thus improves the accessibility of the mod.

**Add any alternative implementations you think might work**
Perhaps realmstones could be found in chests in dungeons or more of them, like Iromine and L'Borean realmstones, could be obtained through certain skills. For example a Precasia realmstone could be crafted with jade, ancient rock and essences obtained through foraging or obtained through logging at a certain level.

**Include any additional background information**
The alternative implementation i have suggested may relate back to the post by DiamondWalker which said to spawn AoA items in chests. They may also contain specific realmstones based on the dimension the chest is found in.

**Comment by DiamondWalker** [comment]
This feels a bit OP, since it would get rid of the challenge of finding realmstones. I guess very rare chest rewards would make a bit more sense, since you would still have to explore that way.

**Comment by Sagisolar** [comment]
Maybe this could be tied with the "Visit" Advancements.

Like if you complete one of those Advancement you can unlock the specfic trade for the realmstone for said dimension..

**Comment by Tslat** [comment]
This won't be happening with 3.2's changes
