### ISSUE TITLE
Hellspot vision detection is buggy

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#749]
**Mod Version**
3.1.2.b

**Describe the bug**
I often get teleported into hellspots even if they're simply on my screen (and far away from the cursor). Other times, I look directly into a hellspot's eyes (if I want to escape a large group of mobs) and nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into the nether
2. Wait until a hellspot spawns
3. Spend a while walking around said hellspot (but don't look at it directly)
4. Get randomly teleported into it

**Expected behavior**
Only being teleported if I'm looking directly at a hellspot.

If this can't be fixed, at least change the hellspot's ability. At this point in the game where any single mob can maul you if caught off guard, it's extremely annoying to be teleported into a group of mobs. Maybe make it fire a powerful exploding fireball at you when looked at?

**Comment by Tslat** [comment]
Fixed in 3.2
