### ISSUE TITLE
Add saplings for mod's trees

### ISSUE THREAD

**Issue by GrayLightTaliz** [Tslat/Advent-Of-Ascension#75]
**Describe the new feature you think would be good to add**
Allow mod's trees (from additional dimensions) to drop saplings from leaves (like usual native trees do). Allow this saplings to be used to grow into a new tree of corresponding type (in classic manner: plant sapling on grass/dirt). Allow to plant saplings in Overworld dimension. Support various forms of trees, so they can grow into same forms, which can be found in original dimension. Allow (if possible) mod trees' leaves to decay after truck chopping and drop saplings (and, maybe, even drop anima stones as well?)

**Add any alternative implementations you think might work**
Drop saplings (sometimes) from dimension's mobs.
Buy saplings from dimension's trader.
Drop saplings as special (dimension related) logging skill drop (in same manner as foraging skill do at level 65).
Use wood blocks instead of sapling (plase wood block on grass, then apply some special item on it)
Instead of classic mechainc of saplings use special sort of item, which can be used directly on grass to spawn new tree.

**Include any additional background information**
Main target (for me): collect various trees from dimensions and plant them near my (overworld) home. Also it allows farming trees for various building planks.
Also I like to build small areas in overworld which resembles origin dimensions (such kind of dimension's "mini" copy near my home). I can do it using "silk touch", but trees usualy have random and various forms, which  too hard to build from scratch :)

**Comment by Immortallis1** [comment]
Was going to make this but you made it first, rip

Anyways, I personally think saplings are a good idea. Pretty sure xol was going to add them back in 2.5 but we all know how that turned out. Right now the trees are technically just structures iirc

**Comment by minix0** [comment]
I can't believe I suggested this when there was such a comprehensive description of the feature already.

**Comment by Tslat** [comment]
Done in 3.3
