### ISSUE TITLE
Internal Server shutting down when hit by AoA mobs

### ISSUE THREAD

**Issue by ShadowzElite** [Tslat/Advent-Of-Ascension#750]
Mod version: 3.1.2b
Minecraft 1.12.2

Internal Server shuts down after i get hit by Advent of Ascension mobs. Not all the mobs seem to do it, but i cant find a pattern to when or with which mobs cause it, it seems a bit random. Its driving me crazy, i just wanna play advent

Installed mods: 
Advent of Ascension
Damage Indicators
Just Enough Items
Optifine
Vanilla Death Chest
Xaeros Minimap (fair play version)

[crash-2019-06-30_21.04.02-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/3342923/crash-2019-06-30_21.04.02-client.txt)

**Comment by Tslat** [comment]
don't use DamageIndicators, use ToroHealth
