### ISSUE TITLE
A gamerule/config option that allows bullets to destroy glass & for explosive weapons to destroy blocks

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#751]
**Describe the new feature you think would be good to add**
Basically every gun, cannon, and blaster, and I guess any melee weapons/staves that cause explosions.

**Add any alternative implementations you think might work**
This isn't a very serious suggestion, in fact it's something we were joking about earlier in the secret channel. Scimi did say it would theoretically be "easy to do actually", so I have decided to make this.

Basically, there would be a gamerule probably called "destructiveGuns". When enabled, bullets would be able to destroy any glass blocks, and anything with an explosive projectile would be able to destroy blocks. (snipers would have trouble destroying glass due to how they work but is that really a big deal haha)
This would obviously be disabled by default, wouldn't want some accidents...............

-------------------------------------

This would mainly be something to mess around with, add some "challenge" to a survival world, or add some **spice"** to an anarchy server.

The amount of blocks a weapon can destroy depends on the explosion size. If an explosive weapon's explosion radius is the same size as TNT, it would have the same destructive power as TNT, etc.

--------------------------------------

Hell, what if mobs are affected by it as well? Whether it should be a separate gamerule or not I am not sure. (would have to rename it to destructiveAoA if they're the same thing, if they're separate things I'm getting flashbacks to keepAllInventory).
It would make certain mobs like Tricksters and Polytoms more "fun", and make Baroness' fight actual hell since I'm pretty sure baron bombs have the largest explosion radius in the whole mod.

**Include any additional background information**
You could just make it config options instead as well.

**Comment by Tslat** [comment]
What do you mean by snipers having trouble?

**Comment by Cruuk** [comment]
> 
> 
> What do you mean by snipers having trouble?

Due to the way the actual bullet sprite "skips" in a way due to the speed. Though I just realized that it was a very silly thing of me to say, considering they don't have any trouble hitting mobs. I was probably thinking too much about Deadlock's old ability when typing that.

**Comment by Tslat** [comment]
It's more of a hits-per-tick thing.
Not so much that they can't hit at all

**Comment by Tslat** [comment]
mwuahaha
