### ISSUE TITLE
Realm Portals

### ISSUE THREAD

**Issue by Dalekkar** [Tslat/Advent-Of-Ascension#753]
I think that every realm portal should be able to be made in the overworld for declaration and ease of access purposes, it would be in the same shape and for any issues with it making the game or grind process null or too easy you could have 10-15 or maybe a little more realm stones combined to make one special realmstone that allows you to connect the portal with the realm's portal block.

EX: You mine all 18 twinlestone from the haven portal, (or have a way to make the twinklestone & the other blocks) and remake the portal in the overworld, combine say 4 haven realm stone to make 1 special havenstone or so and do it 2 more times for a total of 12 haven stones for a result of 3 special havenstone > combine the 3 for a true havenstone or so and use that to activate the portal in the overworld.

**Comment by Tslat** [comment]
You can make a portal to any aoa dimension as of 3.2 in any dimension
