### ISSUE TITLE
Twinklestone/darkstone

### ISSUE THREAD

**Issue by AstralScourge** [Tslat/Advent-Of-Ascension#754]
They may be better of as glowstone analogues instead of things that exist solely for portal frames.

Give them dust maybe and make it consistent with vanilla glowstone (i.e. pickaxe drops dust that sometimes makes a full block, silk touch drops full block) and have the dust as a crafting/loot system ingredient, or have them generate randomly in the haven/abyss or whatever. Also add a darkstone fence since there's no reason for twinklestone fence to be a thing *cough*ZARG HOMEPLANET*cough* but not darkstone fence.

**Comment by Cruuk** [comment]
Twinklestone fence is a thing in Lunalus because the Lunalus portal is also made of Twinklestone haha

**Comment by Immortallis1** [comment]
it's a thing in Lunalus but that doesn't explain why it's a thing

**Comment by Cruuk** [comment]
> 
> 
> it's a thing in Lunalus but that doesn't explain why it's a thing

Because I said so
