### ISSUE TITLE
Swap foraging and extraction

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#755]
Not sure if this has been mentioned before, but I think extraction should be swapped with logging and foraging. By that I mean that extraction levels should give you drops when mining stone and wood, while foraging and logging would allow for certain tools to be used. 

_**Lore/realism benefits:**_
How does taking stuff out of lava affect holding tools? If anything, it'd improve your ability to spot rare minerals in something, which is exactly what foraging is about. It also makes sense that using tools would make you able to hold and use better tools.

_**Gameplay benefits:**_
imo at least, extraction benefits are way more important to progression than foraging rewards. Extraction actually locks items behind itself, while foraging is more of a helpful bonus. Because of this, I think it makes more sense for foraging rewards to require you going out of your way and grinding, while extraction is something you train as you progress (like hunter).

_**Specifics:**_
Extraction levels would give random drops from mining/chopping trees, foraging would unlock new pickaxes, and logging would unlock new axes. I'm not sure what could be done with shovels. Maybe include them with foraging or add a new skill for them?

**Comment by Immortallis1** [comment]
Taking stuff out of lava (including organic matter like cocoa beans and cactus dye) makes no sense to begin with. I don't think sense is really that much of a factor here. The whole "allow you to hold better tools" thing is kind of flawed to begin with, it's always been kind of limiting and I'd rather have it trashed altogether than just swapping two skills.
