### ISSUE TITLE
Advancement trigger for obtaining bestiary entries

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#756]
**Describe the new feature you think would be good to add**
A new advancement trigger that goes off when a bestiary entry is obtained. You would be able to tell it what mob(s) to trigger for.

You will be able to use this to add advancements that trigger upon obtaining a mob's bestiary.

**Comment by Tslat** [comment]
Hmm... that's a lot of advancements lol

**Comment by EatingSilencer** [comment]
It would certainly be a lot, unless a person chose to do it for only for bosses or something.

Not sure what would happen if you tried a mob without a bestiary entry.

**Comment by Cruuk** [comment]
Instead of advancements, couldn't you just use those "toaster" things or whatever they're called to show that a new bestiary entry is available?
![image](https://user-images.githubusercontent.com/38159897/60753628-5d3b9580-9f8a-11e9-9d26-e01960843b7c.png)
This ^

**Comment by EatingSilencer** [comment]
I feel like you guys are misunderstanding my post.

I'm not asking for a new advancement for every bestiary entry, I'm asking for a trigger that modpack makers can use to create their own custom advancements based on bestiary entries.

**Comment by EatingSilencer** [comment]
> 
> 
> Instead of just advancements, couldn't you just use those "toaster" things or whatever they're called to show that a new bestiary entry is available?
> ![image](https://user-images.githubusercontent.com/38159897/60753628-5d3b9580-9f8a-11e9-9d26-e01960843b7c.png)
> This ^

I do like this idea though.

**Comment by Tslat** [comment]
Bestiary entries use vanilla's killed stat, so there actually already is a useable trigger

**Comment by EatingSilencer** [comment]
If this is the case then I will just close this issue as it isn't needed.
