### ISSUE TITLE
Changing the Infusion table to no longer be a structure that can be placed.

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#76]
**Describe/name the existing feature this suggestion relates to**
The Infusion Blueprint. For reference the blocks with the arrows pointing up are called "Carved Rune of Empowering", and the carved runes in the corner of the structure are called "Carved Rune of Focus".

**Describe the change or feature you think would be good to see**
I think we all know by now that structures that can be placed down like the old ancient teleporter are pretty flawed in their design, don't even get me started on the griefing potential. While the teleporter has been reworked into a wonderful new system, and the portal blueprint has been removed, the Lunalus portal and Infusion still remain a structure you can place down. I've already suggested something for the Lunalus portal so...

Essentially, you would place down blocks in certain positions relative to each other to make it work, in a similar way the current ancient teleporter and even the vanilla Enchantment table (with the bookshelves) work, like so:
![image](https://user-images.githubusercontent.com/38159897/48039242-c7184c80-e128-11e8-98fc-62d461f0f7e8.png)
The Infusion table would be crafted in the same way the blueprint is crafted currently, with Obsidian and Amethyst.
But maybe rather than being found in chests, the Carved runes of Empowering and Focus should get their own crafting recipes? Mainly to separate them from the Carved runes used for the Ancient Teleporter. This would possibly give the ruined teleporter another use: To use the Ancient stone for making the Empowering and Focus runes.

What would the crafting recipe for the carved runes be exactly? Hmm, not sure. *Maybe* the Focus rune would be Runium + Ancient Stone? Again I'm not sure what crafting recipe would fit on the top of my head.

Besides all that the system itself would still be the same. You would still use power stones and enhancers to get the enchantments you needed. Though maybe make it so it has to be fully working before you can put Infusion stones in it to get Infusion xp.

**Add any alternative implementations you think might work**
I mean, what else can you do? Make it so only the Infusion table is needed for Infusion? I think there's a reason it was changed to be more in-depth.

**Include any additional background information**
Maybe make it so we can also place the Empowering and Focus runes in the opposite places? Like this:
![image](https://user-images.githubusercontent.com/38159897/48040153-96d2ad00-e12c-11e8-81e9-06edc7197a7d.png)

**Comment by Immortallis1** [comment]
what'd you suggest for the lunalus portal

**Comment by Cruuk** [comment]
> 
> 
> what'd you suggest for the lunalus portal

![image](https://user-images.githubusercontent.com/38159897/48050936-66a10380-e158-11e8-9474-8740e08b76f8.png)

**Comment by GrayLightTaliz** [comment]
> lunalus portal
Let me add some more ideas:
1) Currenly it is very hard to spawn portal in desired place (Terrestrial will not assist you...)
2) After obtaining the portal, other Terrestrials become needless, so I even need to ignore them just for avoiding another portal spawning.
I think good solution could be:
1) Make Terrestrial to drop portal "blueprint" (so I can use it in desired place), or main resource which needed for manual portal building (like Cruuk says).
2) Terrestrial also must drop some valued extra drop (like silver coins or so). That way other terrestrials can became valuable for kill. (they are rare mobs, after all)

**Comment by Immortallis1** [comment]
@Sagisolar possibly the portal can be any shape as long as it's greater than a certain size and contains the carved rune or whatever

@Cruuk you should probably post that suggestion on here separately

**Comment by Tslat** [comment]
Kind of done - either way it won't be reverting to a placeable blueprint
