### ISSUE TITLE
Events don't cancel when you sleep

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#760]
**Mod Version**
3.1.2.b

**Describe the bug**
When you sleep in a bed while events are active, the mobs from the events keep spawning. The mobs will keep spawning until the next time the event ends.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a world.
2. Wait for a night event to occur.
3. Sleep through the night.
4. The mobs will keep spawning when you wake up.

**Expected behavior**
The events end when you sleep and wake up.

**Comment by Tslat** [comment]
Fixed in 3.2
