### ISSUE TITLE
Missing Period

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#761]
**Mod Version**
3.1.2.b

**Describe the bug**
A period is missing in the last sentence of the guide of the full moon event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/Tslat/Advent-Of-Ascension/blob/master/lang/guides/en_us/full_moon.txt
2. Scroll down to the last sentence
3. See error

**Expected behavior**
A period is added.

**Screenshots**
![7DD4A661-DC28-42B0-9892-9A90AFCC1C71](https://user-images.githubusercontent.com/37212918/61118121-a7f96800-a4ca-11e9-95ed-71ff39fe17a5.jpeg)

**Comment by Tslat** [comment]
Fixed in 3.2
