### ISSUE TITLE
Invisible enemies that can't be killed.

### ISSUE THREAD

**Issue by MechanosG** [Tslat/Advent-Of-Ascension#762]
**Mod Version**
AoA3-3.1.2.b.jar

**Describe the bug**
After going through an AoA portal on a multiplayer server, existing enemies will sometimes turn invisible.  Both AoA enemies, vanilla enemies, and enemies from other mods have a chance of turning invisible.  These invisible enemies are still able to attack you, and if you exit the server then rejoin, they will become visible and interactable again.  I'm not 100% certain, but I do not think vanilla nether portals cause this problem.  But my portal to Deeplands does it nearly every time.

**To Reproduce**
1. Create an AoA portal.  In my specific case, it's a Deeplands portal, but I assume any AoA portal will do.
2. Go inside.  Lets some enemies spawn.
3. Go back into the portal to the overworld.  In my case, my portal is in my base that has lots of machines/etc.
4. Head back through the Deeplands portal then check the existing enemies.  In my case, some will become invisible and cannot be killed until I rejoin the server, which causes them to load in properly.

**Expected behavior**
Obviously I would expect them to not turn invisible and be killable lol.

**Screenshots**
Would be difficult to screenshot this particular bug since you can't see the invisible enemies unless they're doing something to their surroundings.

**Comment by Tslat** [comment]
Are you using optifine?

**Comment by MechanosG** [comment]
I am not.

**Comment by Tslat** [comment]
Are you playing single player or on a server?

**Comment by MechanosG** [comment]
As I mentioned in my description, I'm playing on a multiplayer server lol.

**Comment by MechanosG** [comment]
I'm on the server right now actually.  It's a test server for a modpack currently in multiplayer testing.  So if there's anything you'd like me to check out/test, I'd be happy to do so.

**Comment by Tslat** [comment]
Can you send me both the server latest.log, and the client latest.log

**Comment by MechanosG** [comment]
Oops didn't see your new message.  I can get you the client now, but won't be able to get server side 'till later when the server owner gets home.  Want the client one for now?

**Comment by Tslat** [comment]
Sure

**Comment by MechanosG** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/3388346/latest.log)

**Comment by Tslat** [comment]
Looks alright besides the usual plethora of errors.

Out of curiosity does it happen without vanillafix present?

Basically what's going on here isn't an AoA issue, since aoa doesn't handle any of the entity presentation or clientside spawning. It does seem to happen occasionally on forge, and is usually exacerbated by mods like optifine and vanillafix.

Other things to test are:
AoA on its own (no other mods)
Using the recommended forge version, not some arbitrary latest version

**Comment by MechanosG** [comment]
Hiya.  So I did some testing off and on the last couple days.

I tested removing vanillafix client side.  Immediately got a 20-30fps loss and slower laggy feeling chunk loading, but continued anyway.  I have a mob grinder of sorts set up in my base that just tricks mobs into walking into water, then uses water channels to deposit them into my base, so I'm able to test the invisible mob thing easily.  I let some mobs gather, then I went into my Deeplands portal.  Walked around a little, then went back.  No invisible mobs.  I killed the mobs, let more collect, then repeated.  No invisible mobs again.  At this point I'm starting to think maybe you're onto something.  But then I tried it a 3rd time.  This time I got the invisible/uninteractable mobs.  So removing vanillafix didn't fix the issue, at least when removing it client side.  It's still on the server, as that would be a bit more involved to test as I don't own the server box.

Testing AoA completely on it's own would also be difficult for the same reasons.  I don't own the server and don't have direct file access.  But it's not entirely out of the question to test as a last resort.

Other things of note.  I'm using forge 14.23.5.2838 which is the recommended release version and not a random beta release.  I also can't seem to replicate the invisible mobs glitch with a nether portal, which is why I posted this bug here, thinking that maybe it has something to do with your custom portals.  I'll keep testing the nether portal though just to see if it will eventually do it.

I have seen this glitch before some years ago, with different mods in a different modpack.  So I do believe you when you say that this is something that occasionally happens.  But I do know that most mainstream modpacks manage to avoid it somehow.  The modpack I'm building is something really out of the norm though, and figuring out what's causing this is pretty important, considering how important portals are in AoA.

**Comment by Tslat** [comment]
2768 is the recommended release version, not 2838

**Comment by MechanosG** [comment]
Oh, I see.  Twitch gives the option for Release, Beta, and Alpha.  I have Release selected, assuming it was recommended.  I guess I can go back to 2768 and see what happens.

**Comment by Tslat** [comment]
2838 gets pushed as the 'latest' version, but the latest tested stable version is 2768. I have known issues of various types on versions past 2768, so I generally advise testing on 2768.

Some mods' later updates do require newer than 2768 so you may need to drop a version or two on the mods that notify you of that

**Comment by Tslat** [comment]
2768 is the recommended release version, not 2838

It's not a portal specific thing, it comes down to the client syncing entities properly.
AoA just tends to get the brunt of it due to _how many_ mobs it has.

As for a solution, usually this is caused by optifine, so to see it persisting with optifine removed leaves me with little idea.
AoA doesn't handle any entity syncing or anything specific to rendering in that way, so there's not much I'm doing that would cause this, if anything at all.
