### ISSUE TITLE
Harvesting tool changes on many blocks

### ISSUE THREAD

**Issue by Questwizard** [Tslat/Advent-Of-Ascension#765]
**Describe/name the existing feature this suggestion relates to**
This involves a bunch of blocks that make up dimensions' terrain and foliage that are marked as "No Tool" for harvesting.

**Describe the change or feature you think would be good to see**
This is a rough list of changes to harvesting tools and what blocks they apply to:
Mysterium mushroom blocks, Deeplands mushroom blocks: Axe
Gardencia's giant flower blocks, flower cores, plant stem, etc.: Axe
Precasian sand: shovel
All carpets: Maybe match the hardness to vanilla carpet
Baron Ground: Pickaxe (assuming it is terracotta-like here)
Cotton Candy: Pickaxe (right now it is un-harvestable)
Eye Block: Axe
All "Tentacle" blocks: Axe
Divine Station: Pickaxe (already reported as bug, currently unbreakable)

**Add any alternative implementations you think might work**
Could lower harvest time on some of them instead.

**Include any additional background information**
Divine station is part of #764, as it is a player crafted block, but currently acts like bedrock.
I think Baron Ground used to be pickaxe harvestable back in 1.7.10. Not sure why it isn't in 1.12.2.

**Comment by Cruuk** [comment]
I'm pretty sure Baron ground not being Pickaxe harvestable is a minor mistake on Scimi's part
