### ISSUE TITLE
shyreknight banner problem

### ISSUE THREAD

**Issue by VBGaming** [Tslat/Advent-Of-Ascension#766]
so you see, in the source code it says that shyreknights have a chance to drop shiny banners. that's normal, but what's NOT normal is that it says if it doesn't it has a another rerolled chance to drop it. is that intended, or did you replace shyre banner with light banner thus giving him 2 drops for the same item? also, does this belong here?

**Comment by Tslat** [comment]
This does, and no it's a bug, and it doesn't matter now since the next update overhauls loot anyway :) Thanks for reporting it
