### ISSUE TITLE
Innervation skill

### ISSUE THREAD

**Issue by Nitsches** [Tslat/Advent-Of-Ascension#768]
**Mod Version**
3.0

**Describe the bug**
When you try to get the red item out of any chest-like block (hopper, drawer, etc..) you don't get the exp for taking up the item. Since the game give you exp when you get the item from the ground i suggest to change it and make it a usable item like the skill crystal

**Expected behavior**
Get the item, get 0 exp.

**Comment by EatingSilencer** [comment]
You're only playing on 3.0?

3.0 is not the latest version. Try it again on 3.1.2.b (the actual latest) and see if it still happens.

**Comment by Tslat** [comment]
Will be resolved in the next version anyway
