### ISSUE TITLE
Dweller explosion not working properly

### ISSUE THREAD

**Issue by Nitsches** [Tslat/Advent-Of-Ascension#769]
**Mod Version**
3.1.2.b

**Describe the bug**
Dweller just explode everywhere when entering the dimension, and it make everything lag like hell.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  the Deeplands dimension
2. Watch the dwellers explode everywhere without doing anything

**Expected behavior**
They should only explode when the clones are getting killed, as written on the official wiki

Not tested in singleplayer.

**Comment by Tslat** [comment]
No longer relevant
