### ISSUE TITLE
Shooting the Ender Dragon with a Purity Shotgun crashes server with a ClassCastException

### ISSUE THREAD

**Issue by Questwizard** [Tslat/Advent-Of-Ascension#779]
**Mod Version**
3.1.2b

**Describe the bug**
Dedicated server crashed with the following error upon shooting the Ender Dragon with a Purity Shotgun: https://gist.github.com/Questwizard/a32f2e8b2d5f0f473ee9d2af38e4b207

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a dedicated Minecraft server with AoA installed.
2. Get a Purity Shotgun and Spreadshot.
3. Go to The End and respawn the Ender Dragon if necessary.
4. Fire the Purity Shotgun at the Ender Dragon.
5. The client will get a "Server Closed" message, and the server will crash with the error report linked above.

**Expected behavior**
Ender Dragon should have taken damage from the shot instead of crashing the game.

**Screenshots**
None necessary. See crash report link above.

**Comment by Tslat** [comment]
Fixed after 3.1.2.b
