### ISSUE TITLE
Portal doesn't work.

### ISSUE THREAD

**Issue by Pewson** [Tslat/Advent-Of-Ascension#781]
**Mod Version**
AoA3-3.1.2.b
Minecraft 1.12.2
Forge version: 14.23.5.2838

I wanted to open my very first portal in this mod, but it only takes my realmstones and doesn't light up. I tried opening haven/deeplands portal but none of them worked. It played the sound but nothing else happened. I'm playing on lan server with one friend and bunch of mods installed, we also disabled overworld monsters from Advent of Ascension.

![2019-07-28_22 32 23](https://user-images.githubusercontent.com/32248985/62012556-2ff89680-b188-11e9-8b96-0756a8668977.png)

List of mods: 
AoA3-3.1.2.b
Animus-1.12-2.1.4
ArcaneArteries-1.12.2-1.0.0
armoryexpansion-1.3.1
backpack-3.0.2-1.12.2
Baubles-1.12-1.5.2
BloodArsenal-1.12.2-2.2.0-28
BloodMagic-1.12.2-2.4.1-103
bloodtinker-1.0.5
conarm-1.12.2-1.2.4
DummyCoreUnofficial-2.4.112.5
ExpandedArcanum-1.0.1
forestry_1.12.2-5.8.2.387
forgemod_VoxelMap-1.9.10_for_1.12.2
Guide-API-1.12-2.1.8-63
HammerCore-1.12.2-2.0.4.7
Hwyla-1.8.26-B41_1.12.2
ironchest-1.12.2-7.0.71.846
jei_1.12.2-4.15.0.287
jeibees-0.9.0.5-mc1.12.2
jeiintegration_1.12.2-1.5.1.36
llibrary-1.7.19-1.12.2
LootBags-1.12.2-2.5.8.5
MagicBees-1.12.2-3.1.10
Mantle-1.12-1.3.3.55
mowziesmobs-1.5.4
TConstruct-1.12.2-2.12.0.157
Thaumcraft-1.12.2-6.1.BETA26
ThaumicAdditions-1.12.2-18r
ThaumicAugmentation-1.12.2-1.1.4
thaumicbases-3.3.352.6r
ThaumicJEI-1.12.2-1.6.0-27
Wawla-1.12.2-2.5.273

**Comment by Tslat** [comment]
Try it without any other mods present

**Comment by Pewson** [comment]
Using trial and error method I found out that the portals have issue with ThaumicAugmentation-1.12.2-1.1.4.

**Comment by Tslat** [comment]
Seems unusual, since the portal creation relies on very little native code...
Are you sure this is specific to that mod?

**Comment by Pewson** [comment]
I was adding mods one by one from this list and the portal stopped working after adding thaumic augmentation which is addon to thaumcraft. Unfortunately I don't know anything besides that :(

**Comment by Tslat** [comment]
Maybe - can you report it to the mod author for that mod.
They definitely shouldn't be breaking stuff like that
