### ISSUE TITLE
Some Creeponia creepers are affected by light level when previously they weren't

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#783]
**Mod Version**
3.1.2.b

**Describe the bug**
All regular creeponia creepers except Creepirds are affected by this.

It appears that the regular creeponia creepers are affected by light level - meaning they won't spawn on the surface, or if the caves are bright enough.

In the case of Winged Creeper and King Creeper, who previously had also spawned on the surface, now spawn more limitedly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Creeponia dimension with the difficulty up.
2. Observe the spawning of mobs in the caves and on the surface.
3. Notice that winged creepers and king creepers don't appear to spawn on the surface much, if they do at all.

**Expected behavior**
Not sure if this is a bug, but thought I'd report it just in case. The expected behavior, if this is a bug, would be that winged creepers and king creepers can spawn on the surface (meaning they aren't light-level restricted).

**Comment by Tslat** [comment]
Fixed in 3.2
