### ISSUE TITLE
Complete config and mod compatibility trough the config for the skills

### ISSUE THREAD

**Issue by Zack7292** [Tslat/Advent-Of-Ascension#785]
The Skills need a complet config for modpacks sinse you put it on curse forge so... theres my idea about A complete skills config ofr compat with mods!

this desscription will be separarted by skill:

Alchemy: Beign able to add our own potions, tath if you creat them it will give you the number of XP you choose for it. like this modpacks makers will be able to creat potions from other mods like potions core and make you win a proportionnal amount of xp they choose! (they will be item tath, if you craft them, you win xp.

 Anima: simply be able to add custom plants that drop them

augury: work them same as forgering, but beign able to add some item tath give you exp , need a certain, lvl etc..

Butchery: no change ,it s good the way it is, even with mobs from other mods :)

Creation: add a new slab tath have a "?" on it where we can put certain mobs, by right clicking on them, and, depending on the config, they can take them ore not if they have the level for and can use it so it give them a number of xp choose by the player

Enginnering: don't really know this one, sinse theres no wiki page and i don't know a lot of them and im refering to this so... yea

Expedition: nothing to say about it, its really great as it is :)

Extraction: beign able to add our own loots and our own xp gain with them

Foraging: Beign able to add our own blocks tath can make use win an amount of xp choose by the creator

Hauling: Beign able to add our own drop tath when we fish them, we gain an amount of xp choose by the creator

Hunter: Beign able to add a hunter's lvl for kill certain mobs from other mods and an amount of xp tath they drop for this skill

Innervation: nothing to change there :)

Infusion: beign able to add our own enchants tath ened a lvl and how many xp you win with it, they each got their lvl etc...

Logging: beign able to add our own block tath we need to break for winning a certain amount of xp choose by the creator

Runation: nothing to say here its looking really good :)

About all of the skills: beign able to change the xp we win, the dorp (like unable some of them)(if they are), beign able to add reward trough certain lvl chosoe by the creator (exemple: when im lvl 25 of a lvl: i win a apple (depend on what the creator put as the reward for this skill)).

How to access it?: adding a config icon into the menu tath is a little bit hiding in a corner but still easely visible tath basicly, we can't access, but when we do a command like "/AoA_config Edit True" we are able to access it. 

what will it need?: the be as simple as possible, to render the mobs so we can easily know what is what bcs they usualy have an Id name (tath your mod will check for finding the mobs) tath is like (Exemple: Minecraft:Wither_Skeleton) so it kinda weird, beign able to choose the xp reward for them direcly after or an highter drop rate. and to remove some already existing mobs/block/items tath is in it. for the block breakings/ item crafting/gettings ones: you'll simply add a block (inspiring you by the Better Questing/ FTB Quest block choice when you creat a quest could be a great idea). For the rewards of certain level, add a categorie in Each of the skills categorie (bcs i think categories will fit well for the simplicity) named "Reward" where we can click on "add" choose a lvl and a reward, pretty let you choose in the same way of the  block breakings/ item crafting/gettings ones.

Alternative: by a config file but it would be lest simplist and harder and lest interesting.

so yea tath it, my idea is pretty complet and is really big!, btw your github have a good setup and srry if my english is bad je suis canadien ;) g vue que tu parlais FR sur le discord :) the goal of this addition is to put you mod into modpack by creating a lot of configurable thing so your able to amke it literally based on your system to xp trough the mod with also, other mods in it! (last idea, adding a compat with FTb:Quest and Better Questing tath when we creat quest on them we have a new categorie (int he quest creations) tath is about leveling up those skills to win reward trough those quest :) )

Thx for reading my complet idea, hope it was clear enough, if you don't understand sometihng i'll explain you later on discord : (A Zack In Time#0707) probably in frenhc (if you want) so i can try to illustre my idea and to explain it clearly. (im alreayd in your discord tho)

A Zack In Time/ Zack7292 :)

good continuation in your mods scripting

**Comment by Tslat** [comment]
I can confirm that a number of these things will already be editable via loot tables in 3.2 :)

**Comment by Zack7292** [comment]
Cool! :D i'll really like this since, im a little modpack maker since i want to amke a modpack about all the 1.12.2 mods (take some of the really known one, not knows one etc (bcs i like to give thme little "push" etc...) btw your mod use ALOT of ram but, its ( in size (Mb etc..)) smaller then beetweenland  but isntead of using not tath msuh of ram it use like 80% of 7G of Ram on my modpack x)

**Comment by Tslat** [comment]
AoA is a rather big mod, it does use a fair bit of RAM.

**Comment by Zack7292** [comment]
ik i sinceraly think this to, but idk why but i got the feeling tath there still place to improvement tho but if you can't its fine bcs this won't change my modpack since i,ll jsut recommand more Ram x)  (btw thx for the fast answer its rare to have some answer tath quickly :) )

**Comment by Tslat** [comment]
The entire mod was rewritten from scratch less than 12 months ago with a specific focus on efficiency.

There's not much more that can be done in terms of RAM usage, it's just a big mod :)
IF you intend to play heavily modded minecraft, you should expect it'll take semi-modern PC specs to do so

**Comment by Zack7292** [comment]
Ok, it seam logic xD
