### ISSUE TITLE
Mentallia dimension

### ISSUE THREAD

**Issue by NekkitXD** [Tslat/Advent-Of-Ascension#786]
I have a concept of a new dimension for AOA, new dimension: Mentallia.
Here are some renders i made:
https://imgur.com/a/cFaK2vW

Every hostile mob will have a new debuff they add to player when they attack, players screen blinks white (like a flash).

I can do all the models/mobs/textures for the dimension, if you like my idea contact me on discord: Nekkit#8224

**Comment by Zack7292** [comment]
i see those screen on the discord ;o

**Comment by Zack7292** [comment]
i think its looking great by its to flashy and is missing details (but since its jsut an exemple its understandable)

**Comment by Immortallis1** [comment]
upvoted just please don't make the color scheme such an eyesore lol

also no mobs that look like dicks

**Comment by NekkitXD** [comment]
> upvoted just please don't make the color scheme such an eyesore lol
> 
> also no mobs that look like dicks

Do you have suggestion about color scheme, but only 3 solid colors? Also lol i didnt mean them to look like dicks, i will remake them.

**Comment by Immortallis1** [comment]
yeah that was somewhat of a joke

About three solid colors, I'd say reduce the contrast a bit. It's better if it's white/black/red but the colors are milder.

**Comment by DiamondWalker** [comment]
This suggestion seems great. The only two things I would change are the name (it's a bit too generic imo) and the mob abilities. I'm not sure about the name, but the mobs should have more "confusing" abilities. Maybe they could do stuff like change the color scheme of the dimension?

**Comment by Kaldonis1** [comment]
I like the purposful harsh color scheme. A leyman might say "Durrr this is textured bad. Hurts my eyes and i can't see detail" but that would be the exact point of this dimension. Difficult to see and traverse due to no way to visually detect depth and geometry. 10/10 eldritch horror. Imagine being lost from your portal!
