### ISSUE TITLE
Need help understanding

### ISSUE THREAD

**Issue by Neox91** [Tslat/Advent-Of-Ascension#787]
Hi i just discovered this mod witha  group of friends, as soon as we spawned there were several mobs, which is cool cuz we had to escape strategically but the problem was that we realized that we could'nt damage them in anyway, we then found out that we had to become lvl 12 in hunter skill. however it takes a long time to become hunter lvl 12 and those mobs that keep killing us (that we can't kill/do damage to) are literallly everywhere.

I would like to know if there is  aconfig file that allows me to modify these aspects of the game (changing amount of xp needed to lvl up skills, lower the required levels to kill a mob etc. )

this would really help us.

i found a config file but do not understand one bit xD

We are using AoA 2.4.B if this helps

PS the config file looks a little something like this : 

''
skill {
    I:AnimaX=28
    I:AnimaY=65
    I:AuguryX=80
    I:AuguryY=30
    I:ButcheryX=184
    I:ButcheryY=65
    I:CalefactionX=54
    I:CalefactionY=65
    I:CreationSkillX=54
    I:CreationSkillY=30
    I:ExpeditionX=80
    I:ExpeditionY=65
    I:ForagingX=106
    I:ForagingY=30
    I:HaulingX=210
    I:HaulingY=65
    I:HermetismX=158
    I:HermetismY=65
    I:HunterX=28
    I:HunterY=30
    I:InfusionX=132
    I:InfusionY=30
    I:InnervationX=210
    I:InnervationY=30
    I:LoggingX=132
    I:LoggingY=65
    I:RobberyX=184
    I:RobberyY=30
    I:RunationX=158
    I:RunationY=30
    I:VulcanismX=106
    I:VulcanismY=65
''

**Comment by Tslat** [comment]
First of all - why are you playing an extremely outdated version of the mod?
Tslat-1.1.3 is the most update to date version of the mod on 1.7.10.

Secondly - why are you playing on 1.7.10? Update to 1.12

AoA doesn't not offer support for 1.7.10 as it is over **5 years old**

**Comment by Neox91** [comment]
i'm playing the FTB departed modpack,
Will any features change if i update the version of AoA.
I mean will any of the other mods be affected bye the change?

**Comment by Tslat** [comment]
Probably not.
Always back up your world first just in case
