### ISSUE TITLE
Vanilla creepers no longer spawn naturally in Creeponia

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#789]
**Mod Version**
3.1.2.b

**Describe the bug**
Prior to Tslat taking over development, Xolova had made it so vanilla creepers can also spawn naturally in Creeponia. They only spawned in areas with a light level of 7 or less.

Not sure if this is a bug or not, but will report it just in case.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Creeponia with the difficulty up.
2. See that no vanilla creepers are spawning anywhere.

**Expected behavior**
Again, I'm not sure if this is a bug, I'd thought I'd report it just in case.

The expected behavior otherwise, if it is a bug, is that vanilla creepers could spawn in Creeponia like they did before.

**Comment by Tslat** [comment]
Didn't know that - makes sense though lol
Done
