### ISSUE TITLE
Change the return portal blocks for L'Borean and Vox ponds

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#79]
**Describe/name the existing feature this suggestion relates to**
The blocks on the portal frames back to the Overworld for L'Borean and Vox Ponds.

**Describe the change or feature you think would be good to see**
The return portals for dimension almost always have a native block to that dimension, but for some reason those 2 dimensions (and Creeponia but there's already a suggestion lol) have a block that isn't in that dimension at all. It's plant stems from Gardencia.
![image](https://user-images.githubusercontent.com/38159897/48108846-c1d70280-e1f9-11e8-9f57-962b288878da.png)
There is sort of a reason it's like this; Back in the day when you would find portals in the dimensions, both L'Borean and Vox ponds were found in Gardencia... Even though the return portal for something like Dustopia didn't have Greckon blocks back in the day as well.

Either way, it doesn't really make sense for them to have plant stems as the portal frame.
L'Borean's return portal block could be any of the coral blocks, maybe the pink coral block to fit with the pink and blue colors L'Borean items seem to have, since the portal itself is blue.
![image](https://user-images.githubusercontent.com/38159897/48110012-b76b3780-e1fe-11e8-8c8c-0b6b325a191b.png)

Vox Ponds' return portal block could be the Degraded steel block (With steel lights in the corners?)
![image](https://user-images.githubusercontent.com/38159897/48110025-c356f980-e1fe-11e8-9a5c-50e11c74bd9b.png) 
![image](https://user-images.githubusercontent.com/38159897/48110033-c81bad80-e1fe-11e8-9511-2d4861de220a.png)

**Include any additional background information**
It definitely does relate to that suggestion about Creeponia's return portal blocks because it's made out of fucking Gravel and not a Creeponia block.

**Comment by Immortallis1** [comment]
I agree.

Return portals in general need a change tbh

**Comment by Tslat** [comment]
Has been done
