### ISSUE TITLE
Day mobs in the overworld ignoring light level

### ISSUE THREAD

**Issue by Freebi85** [Tslat/Advent-Of-Ascension#790]
**Mod Version**
V. 3.1.2b
Forge.: 1.12.2 - 14.23.5.2838

**Describe the bug**
"Day" mobs in the overworld ignore the light level and can spawn in a base.

**Expected behavior**
Agressive mobs should not be allowed to spawn in an illuminated area.

Keep up the Great Work! =)

Freebi

**Comment by Tslat** [comment]
Well yeah.. they're daylight mobs.. if they didn't ignore light level, they'd never spawn in the day lol

All Overworld mobs also only spawn on natural blocks, so you can counter them spawning in your base by making your floor out of anything non-natural (planks, bricks, etc..)
