### ISSUE TITLE
More drops for Runicorns

### ISSUE THREAD

**Issue by butterybiscuits** [Tslat/Advent-Of-Ascension#791]
Runicorns look great and all, but currently they only have two drops.

I think that the Runicorns should have a 5% chance of dropping a runicorn horn, which could be used to craft antipoison potions.

**Comment by Tslat** [comment]
But where would we get the Marrentill from

**Comment by butterybiscuits** [comment]
Very funny

**Comment by Tslat** [comment]
Runicorns now utilise the runandor world table as of 3.2
