### ISSUE TITLE
Incorrect Mysterium Black Bricks Stairs Texture

### ISSUE THREAD

**Issue by Infernikko** [Tslat/Advent-Of-Ascension#792]
**Mod Version**
3.1.2b for 1.12

**Describe the bug**
The texture for Mysterium Black Bricks Stairs appear to be that of regular Black Bricks instead

**Screenshots**
![image](https://user-images.githubusercontent.com/41617467/62430428-8596eb00-b714-11e9-819a-af4480f07d63.png)
![image](https://user-images.githubusercontent.com/41617467/62430451-bbd46a80-b714-11e9-882b-f84e83074c1b.png)

The slabs are the correct texture

**Comment by EatingSilencer** [comment]
I think Mysterium Green Bricks Stairs are also affected.

**Comment by Tslat** [comment]
Fixed
