### ISSUE TITLE
Make Dracyon freeze the player

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#798]
Currently Dracyon just applies strong slowness. It'd be nice if he actually froze the player, like this boss: https://www.youtube.com/watch?v=A-1bAYxN_gY&feature=youtu.be

This is from an old jar mod, which means it modified minecraft's jar and didn't use forge. I'm not sure if this will be possible with AoA, but I figured I'd post this suggestion anyways, in case it's possible.

**Comment by Tslat** [comment]
Permanently freeze the player, got it

**Comment by DiamondWalker** [comment]
> 
> 
> Permanently freeze the player, got it

And make it continue after respawns while you're at it.
