### ISSUE TITLE
Dragon Block C and AoA Issue

### ISSUE THREAD

**Issue by Wholfe1999** [Tslat/Advent-Of-Ascension#802]
I am using 1.7.10 for all of my mods.

**Describe the bug**
The bug that i am experiencing is whenever i go to create my character through Dragon Block C it always resets after a minute or so.

**To Reproduce**
Steps to reproduce the behaviour:
Im not entirely sure on how to reproduce this but i was having issues to get AoA working for me, my game was crashing because of the Dimension IDs. I set thier IDs to the thousands (im not sure if that was a good thing or not) and that managed to stop the crashing. Now whenever i get into the game i cant create my character with DBC.

**Expected behavior**
I would like to see sime sort of solution.

**Comment by Tslat** [comment]
Downgrade your version to something like Tslat-1.0.
The latest 1.7.10 versions of the mod have this issue and will not be fixed

**Comment by Wholfe1999** [comment]
On the Cruseforge site the only version is AoA-Tslat-1.1.3 for 1.7.10. Im gonna keep looking

**Comment by Tslat** [comment]
If 1.0 works, you'll likely be able to use 1.0.3 safely, since it's the same as 1.0, but with a bunch of bugfixes
