### ISSUE TITLE
Reducing certain potion effects/mobs that are extremely high

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#804]
**Describe/name the existing feature this suggestion relates to**
Potion effects

**Describe the change or feature you think would be good to see**
I'm no sociologist, but I imagine more people know about the roman numerals with I, V, and X in them than the ones with stuff like C and M in them or whatever.

Basically, I'm referring to stuff with really high tiers of potion effects like this 
![image](https://user-images.githubusercontent.com/38159897/62753715-a5ceee80-ba21-11e9-8adf-86f98030c761.png)
I haven't been to this page for a while, so I didn't immediately remember what C was in Roman numerals, and I don't want people to look up what C is to see what the number value is (I know we can just not use Roman numerals but... come on man)

To sum it up, these effects should be reduced to the minimum where they're still at their "max". Certain mobs like Koko give like Blindness 36 and Slimer gives Poison 16, and there's like no point for them being that high, when it's no different at Blindness I and Poison IV. I imagine more people would immediately identify those Roman numerals if they were reduced.

If a weapon/mob is supposed to give enough slowness to completely stop you dead, it should be the minimum max (Slowness VII is -105% speed I believe, or just Slowness X if you want to make it clean, that's fine). Wither/Poison are at their max power at IV I think, etc. 
Even making really high values X instead of like XXXVI or CI would make things better.

It's a bit nitpicky of me to suggest, I know, but I think it would make things a bit cleaner. Mainly for the wiki's sake.

--------------------------------

There are 2 edge cases to this: stuff that is supposed to stop jumping, and Vulcammer.

Basically, if you have like Jump boost 128, it stops you from jumping. I think we can really only make this an exception, can't think of any other way around it. ~~You can still jump with slime blocks so maybe we shouldn't even use jump boost 128 anymore~~

As for Vulcammer, it can give both Slowness *and* Weakness CI (101), so reducing the weakness would actually affect how much damage it negates, nerfing Vulcammer.
Even then though... Weakness X is still like -40 damage, and that still nullifies the damage of all melee mobs except like 3, so I see no issue in reducing that to X.

That is all.

**Comment by Tslat** [comment]
I mean it doesn't really matter to be honest lol - it only appears in code

**Comment by Cruuk** [comment]
> 
> 
> I mean it doesn't really matter to be honest lol - it only appears in code

It was mainly for the wiki's sake, and I didn't want to resort to using normal numbers because roman numerals are pretty cool and MC wiki uses them too.

**Comment by Tslat** [comment]
-.-

**Comment by Tslat** [comment]
No longer relevant
