### ISSUE TITLE
on server bug

### ISSUE THREAD

**Issue by 3269199948** [Tslat/Advent-Of-Ascension#805]
There is no sparkle of light and all other light on the sponge server, the server does not have any other plugins and mods

minecraft version:1.12.2
forge: 2838
server:sponge
mod version: 3.1.2.b

**Comment by Tslat** [comment]
All other light?

I'm really not sure what you're saying here

**Comment by 3269199948** [comment]
> All other light?
> 
> I'm really not sure what you're saying here

Is the light generated in the main world

**Comment by Tslat** [comment]
Probably a sponge issue, try running it without spongeforge

**Comment by 3269199948** [comment]
> Probably a sponge issue, try running it without spongeforge

There is no better server except for the sponge.

**Comment by Tslat** [comment]
Good luck then
