### ISSUE TITLE
AoA+FastWorkbench crash

### ISSUE THREAD

**Issue by Vantageright** [Tslat/Advent-Of-Ascension#808]
**Mod Version**
What version of the mod are you on?
AoA3-3.1.2.b

**Describe the bug**
Attempted to load the world, crashed before being playable.
Happens with new worlds too.

**To Reproduce**
Steps to reproduce the behaviour:
No idea

**Expected behavior**
Not crash

**Screenshots**
https://paste.dimdev.org/odavohoxaq.mccrash

**Comment by Tslat** [comment]
AoA is not current compatible with mods that remove advancements.
FastWorkbench removes advancements from the code before re-adding them under its own name.
