### ISSUE TITLE
Add Loot Chests to Dungeons [preliminary]

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#81]
**Describe the new feature you think would be good to add**

**THE PROBLEM**: "Dungeons" in the mod are usually just single rooms with spawners. Sometimes they have GUI-less tables at the end, but for the most part they don't. There are no loot chests or anything around the dungeons.

With a spawner you just wait for a while and can get an infinite amount of mob spawns with no limit. That in itself is all right but it makes it problematic since once you find one, there's really **no benefit to finding another at all**, unless you happen to break the spawner in the first one for some reason. (That'll teach you not to use your creepified sword for everything.) For example, it's better to find 1 gingerbread house and 1 gingerbread aviary than 10 gingerbread houses and 0 aviaries in the same period of time. It's no fun.

Nightmare castles: what do they have? A bunch of spawners. No loot, nothing unique, just spawners. That's cool and all but if you find another one there's just nothing good about it when it could've been a portal tower or whatever.

![useless](https://user-images.githubusercontent.com/11131230/48153870-42970c80-e295-11e8-8f53-b4a7a4f5a138.png)
(ignore the ruined teleporter that was me testing the blueprint. Note that one of the castles isn't even on the ground)

**It ruins stuff on the other side of the spectrum too:** say that you are lucky and have found one of every structure. Now there is literally no need to explore any further into the dimension - all you will find is the same structure, just further and less convenient. Nothing new, and not even extra old resources most of the time, unless you really like sitting around and mining bricks that have obsidian toughness. Just spawners.

This leads to stuff like running into multiple of them and going "oh it's the same structure what a disappointment" while not getting the structure you want. You get absolutely nothing from that second gingerbread house onwards but more grief that the RNG selected that instead of what you actually wanted.

**THE SOLUTION**: This is kind of an overarching problem with the mod, and probably not as easy to deal with as this, but it could be partially solved by adding loot chests to dungeons. Vanilla Minecraft, twilight forest, thaumcraft, galacticraft, and virtually every other mod with dungeons will add a loot chest somewhere, whether it uses a dungeon loot list or a unique table that thematically fits.

**There's a certain excitement to adding loot chests - you never really know what you're going to get.** It's the same reason that loot chests are a popular money-making model on several games, for instance. If this occurs, at the very least running into a third flesh eater hut or gingerbread house or whatever can have its merits, as the chest might have something you don't have, or a resource you needed a decent bit of. **It's also why Lucky Blocks are so popular, as a lucky block is in essence a craftable mini loot chest.** 

Perhaps some new things can even be exclusive to loot chests in certain dungeons. Either way, this would add a reason to find more than one structure and make it less discouraging to find multiple, and give some purpose to the structures besides you sitting in the spawner room the whole time.

This is more or less preliminary and I don't have a big loot table, but it could be thought up with the new loot system that's almost certainly coming at this point.

While the problem of finding multiple boss spawn altars or lottomen or whatever still holds, this at least makes it more tolerable, and is a good first step towards fleshing out dimensions.

**Add any alternative implementations you think might work**
Nothing, really. There are other things that can be done but they aren't "alternative implementations" of the same idea.

**Include any additional background information**
It has, sort of. It kind of falls under the "dimensions need fleshing out" issue.

**Comment by Sagisolar** [comment]
Yeah theirs a reason I don't remember most of the dungeons in the mod. Seroius without rewards dungeons become just structers.

**Comment by Immortallis1** [comment]
Pretty much. Nether fortresses, for instance, have several reasons to go: blaze rods which gate into brewing, the End, and most likely other mod content as well. Nether warts for brewing, loot, wither skeletons for the Wither, etc.

Gingerbread houses exist almost solely to give the candy for the boss spawner which requires a rare mob anyway so chances are you won't need to stay there for long. They also give one building material too, but the end gives several in addition to the nether bricks in the fortresses anyway.

Of course gingerbread houses are not going to be as structured or detailed as those larger vanilla structures, but it shows what kind of stuff you should expect from a structure to make it more fun.

**Comment by Cruuk** [comment]
This is also why I've always liked the Iro crates because it's one of the few times the mod does a loot chest system and I think it's pretty good here. Even the Deep cases are sort of like this.
