### ISSUE TITLE
Bestiary Filtering

### ISSUE THREAD

**Issue by VBGaming** [Tslat/Advent-Of-Ascension#816]
**Describe the new feature you think would be good to add**
See, back before the bestiary was a thing, I remember thinking mobs would be ordered in a more specific order than alphabetical. I'm not sure why, but I'd like to see implemented a way to filter your bestiary. For example, you could filter by dimension or simply by name, but it'd be easier navigating through the bestiary this way.

**Add any alternative implementations you think might work**
If this isn't possible, even a simpler way to navigate through the bestiary would be fine.

**Include any additional background information**
Not sure if something like this has been talked about.

**Comment by Tslat** [comment]
This is a thing in 3.3
