### ISSUE TITLE
Returning with Greckon/Runandor portal dumps you in midair in Mysterium

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#82]
**Mod Version**
Tslat 1.1.3

**Describe the bug**
See title. Going out of Greckon/Runandor through the entrance portal drops you in a set spot in Mysterium (I think it's where the portal in was) which is usually going to be far from the portal tower that sent you there to begin with. Tested with a proper Mysterium portal from the Overworld, on both creative and survival, and with a naturally spawning portal tower, and confirmed by one or two others.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Mysterium
2. Find a portal tower (naturally spawned)
3. Get a realm travel ticket and enter into Greckon/Runandor
4. Leave Greckon/Runandor
5. You won't be at the portal tower, and will most likely be in midair

**Expected behavior**
you would be at the portal tower, or your overworld spawn point or something

**Comment by Garr890354839** [comment]
The same happens to me, except I spawn inside the columns... Overworld spawning?

**Comment by Tslat** [comment]
AoA No longer updates 1.7.10 as it is an ancient version of MC
