### ISSUE TITLE
Upgrade villages

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#83]
**Describe/name the existing feature this suggestion relates to**
Villages in the mod are very basic. They consist of a static structure that doesn't change, a few villagers of each type, and thats about all there is to it. As of now, the three villages in AoA include Gorb Villages, Primordial Villages, and Lunar Villages. 

**Describe the change or feature you think would be good to see**
Villages could become changed up to have randomized buildings. The number and types of NPCs in the village will vary - and not every village will have every npc. 

Gorb Village: The gorb village will get a complete overhaul. The village will spawn by the ground instead of in the air. The village buildings will utilize a combination of mushrooms with the black/green mysterium bricks. Mystite lampposts will also appear in the village.  The gorb village can contain the following building types:
*A basic square building, maybe made of yellow mushrooms + black/green mysterium bricks. Corresponds to the gorb citizen.
*A slightly more advanced building with a second floor, and orange mushrooms instead of yellow. Corresponds to gorb arms dealer.
*A slightly more advanced building with lava and filled with special blocks, such as anvils or perhaps a mending table/filtration system. Corresponds to gorb engineer.
*If other types of gorbs are added, buildings for them too?
*Mystic lampposts.
*Fountains that spawn randomly in the village.

The village will spawn with at least 1 gorb, with a random population of gorbs being added upon generation. 

Primordial Village: The primordial village would be able to spawn in the Dustopian Plains biome. Possibly generates more akin to an overworld Plains village but made entirely out of dawnwood planks, with some parts suspended in the air (like the village is now). Like with gorb village, there would be different houses for the npcs. Each primordial village would spawn with at least 1 primordial npc, with a random number of them populating it upon generation.

Lunar village: The lunar village's current buildings would be randomly laid out, with every village not having every buildings. Npcs generate with the buildings.

--------------------------------------------------
The villager mobs themselves would also get a change.

They would be able to move around. They would also be attacked by certain mobs, like fungbacks, fungats, and fungiks would attack gorbs, and various dustopia mobs would go after primordial npcs.

Npcs would define their home based on where they were spawned in. (?)

**Comment by Cruuk** [comment]
We should add special doors for these villages, and allow the villagers to open these doors to hide inside the houses from any hostile mobs.
