### ISSUE TITLE
Shyrelands wind event affects players in spectator mode

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#832]
**Mod Version**
3.1.2.b
**Describe the bug**
If a player in spectator mode travels above the archways in the shyrelands dimension, they will find that the wind event chat message still appears, and they are affected by the event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Shyrelands.
2. Go into spectator mode.
3. Fly above the archways.
4. Wait until you see a wind event occurring.

**Expected behavior**
The chat message and wind event should not happen to players in spectator mode.

**Comment by Tslat** [comment]
Fixed
