### ISSUE TITLE
Not compat with shaders?

### ISSUE THREAD

**Issue by empirebattles** [Tslat/Advent-Of-Ascension#837]
**Mod Version**
AoA3 3.1.2.b

**Describe the bug**
Trying to use shaders, and when i go to other dimensions, the sky is white, and the terrain is nearly invisible.  (i've tried Sushi, SEUS, and a few others, just to see if i could get one to work)

**To Reproduce**
Install a shader, go to other dimensions.

**Expected behavior**
Have things be visible.

**Screenshots**
http://prntscr.com/othaud

Not sure if this is a problem with here, or if i should try to convince each shader pack to become compatible with AoA.

**Comment by Tslat** [comment]
It's just because shaders don't play well with fog and dark lighting.
Nothing I can do here
