### ISSUE TITLE
My modpack and advent of ascension

### ISSUE THREAD

**Issue by Bubblie01** [Tslat/Advent-Of-Ascension#839]
**Mod Version**
AoA3 3.1.2.b

**Describe the bug**
So basically I have this modpack and it involves only a few things with world generation. although this may not be a bug, the mobs don't spawn. I checked if advent works with biomes o plenty and it does very well it works with wizardry dynamic trees and almost all the mods but for some reason when I put them all together everything works but the mob generation. I will be happily to list all the mods if asked. It could be just me being dumb and not realizing which mods are compatible with advent but I am not sure if that is the case because I tested each one 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by Tslat** [comment]
I'm going to need more info than this...
So far I have:

Mobs don't spawn in 3.1.2.b
I have other mods

Provide a log file please
