### ISSUE TITLE
Crashing at world launch

### ISSUE THREAD

**Issue by Vantageright** [Tslat/Advent-Of-Ascension#840]
**Mod Version**
What version of the mod are you on?
3.1.2.b

**Describe the bug**
I try to load the world and the server dies the majority of the time.

**To Reproduce**
Steps to reproduce the behaviour:
Try to load the world

Crash log - https://paste.ubuntu.com/p/DMtKXwgX7x/
If thats not enough
Latest.log - Everything https://paste.ubuntu.com/p/YmMj6wkvnQ/

**Comment by Tslat** [comment]
Mods that remove advancements from the game break AoA, because it uses advancements in its code.
Currently AoA is incompatible with mods that mess with advancements.

**Comment by Vantageright** [comment]
Did the log give any clue as to what other mod broke it?

**Comment by Tslat** [comment]
It could be any of them

It's not caused by a mod doing something, it's caused by AoA trying to access one of its advancements, but another mod has removed it.

Triumph/Patchouli are two known mods that do this, but there might be others
