### ISSUE TITLE
Just a suggestion to make this less grindy

### ISSUE THREAD

**Issue by NuggetKitten** [Tslat/Advent-Of-Ascension#848]
I noticed that some mob drops, are about 0.1% on mobs that have a 0.01% chance of spawning. This with the fact of the area makes some of the drops, near impossible to get.  It also means that as they are mob drop only, you can't get them without cheating, or farming for hours on end. Or luck.
I suggest either adding them as some sort of raised drop, make them spawn in some sort of chest, or some sort of trade method for them.

**Comment by Tslat** [comment]
The next update deals specifically with this.
Join the official discord server sometime, we discuss the latest updates and upcoming content in there regularly
