### ISSUE TITLE
Recoil/Life Steal affects entities

### ISSUE THREAD

**Issue by Fleega** [Tslat/Advent-Of-Ascension#849]
**Mod Version**
_Latest_  3.1.2.b for 1.12.2 with Forge 14.23.5.2768

**Describe the bug**
Greatblades with recoil can be used on entities (tested with experience orbs, items, pixons, bloodlusts and arrows)

**To Reproduce**
Steps to reproduce the behaviour:
1. Find any pixon or bloodlust, item, shot arrow or experience orb
2. Attack the entity with a damaging/healing
3. Notice damage being taken/healed
4. Items/Experience orbs are destroyed as a result

**Expected behavior**
Health remaining untouched and xp/items staying

**Further information**
Swords with healing/damaging recoil also affected, but only on pixons and bloodlusts and not items, arrows or experience

**Comment by Cruuk** [comment]
hope you're having a good day fleega. I'll be back in 10 minutes

**Comment by Tslat** [comment]
This will be fixed under the changes to greatblades, swords, and mauls to only apply effects after damage
