### ISSUE TITLE
Carrot Cannon and Frosticator's slowness

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#85]
**Describe/name the item/content this suggestion relates to**
Usually when a weapon gives a high amount of slowness, it only lasts like 1-2 seconds since slowness is very powerful on melee mobs. However, Carrot Cannon gives a whopping slowness 4 (80% reduced speed), and it lasts for around 5 seconds. Frosticator is the same but the slowness lasts for around 3 seconds, which is still quite a lot.

Both guns have a pretty fast fire rate, which basically allows you to stunlock any melee mobs. That and the decent damage output essentially make them straight upgrades to Paralyzer. (Craexxeus drop!)
Paralyzer can also sort of stunlock but the energy doesn't allow you to do it for too long.

**Describe the change/balance you think would be good to see**
If Carrot Cannon should still have the extreme slowness, then the duration should be made *way* shorter than it currently is, like 1 second.

I'm kind of iffy on the idea of an earlygame gun (Frosticator) having that much slowness, so may be it should be changed to like Slowness II for 2-3 seconds instead.

**Include any additional background information**
Uhhhhhhh

**Comment by Tslat** [comment]
Did some stuff after snapshot 9
