### ISSUE TITLE
Hellcat's toe

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#850]
it is broken
**Mod Version**
3.1.2.b. Actually I'm on snapshot 4 but I know it's present on 3.1.2.b

**Describe the bug**
Hellcat's toe broken. help

**To Reproduce**
Steps to reproduce the behaviour:
Look at Hellcat walking

**Expected behavior**
Toe is not broke

**Screenshots**
![image](https://user-images.githubusercontent.com/38159897/63554713-37932d00-c4f3-11e9-9808-75385f64a1f3.png)

**Comment by Tslat** [comment]
Fixed
