### ISSUE TITLE
The htibox size of projectiles of certain weapons

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#853]
**Describe/name the existing feature this suggestion relates to**
Mainly the weapons with the long projectiles. Mind Blaster, Energy Cannon, Color Cannon, Ion Blaster, etc.

**Describe the change or feature you think would be good to see**
It always irritated me that the hitbox of these weapons were basically the same as the bullet hitbox, it makes it misleading when trying to hit mobs with it. The particles may have touched the mob, but the hitbox didn't so tough luck.
![image](https://user-images.githubusercontent.com/38159897/63644888-a44f2880-c6a7-11e9-8d5f-98b42e894f18.png)

Basically, the hitbox should be longer to reflect the particles. If this makes these types of weapons really powerful you can adjust the stats themselves.

**Add any alternative implementations you think might work**
Though, I know hitboxes are fucky, so if this doesn't work there's always a more ghetto way of doing it, because I'm really really desperate to have this happen.

Here is my thesis:
![image](https://user-images.githubusercontent.com/38159897/63645018-74555480-c6aa-11e9-8585-310ef0b547d2.png)
Thank you for reading.

I just want these weapons to have more accurate hitboxes, so I'm hoping that will change in the update that changes everything.

**Comment by Tslat** [comment]
Wut
