### ISSUE TITLE
Make Mystic shrooms work more like carrots/potatoes

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#854]
**Describe/name the existing feature this suggestion relates to**
Mystic shrooms

**Describe the change or feature you think would be good to see**
I'm no plant man, but mushrooms don't have seeds. I think it would be better if they worked like carrots/potatoes: You get the full item instantly, but you can plant it to get more when fully harvested.

I know it's not exactly like MC's mushrooms, but from experience farming those is a pain in the ass, so I think this would be better. It would in general feel a bit more... intuitive. I think.

All of our crops work via seeds, so I think it would be nice to have some variance as well.

**Comment by Immortallis1** [comment]
I agree, seeds are a useless arbitrary step thing

**Comment by Tslat** [comment]
Make seeds crafted by seed particles which are a 10% drop from bosses, got it.

**Comment by Criterion6** [comment]
I'm all for less seeds cluttering the inventory whenever it's time to farm.

**Comment by Tslat** [comment]
Done in 3.2
