### ISSUE TITLE
The Night Reaper Crash

### ISSUE THREAD

**Issue by kryptontheking** [Tslat/Advent-Of-Ascension#858]
**Mod Version**
What version of the mod are you on?
AoA3 3.1.2.b
**Describe the bug**
Everytime i touch the night reaper or get hit by one,The game instantly crashes 
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by Tslat** [comment]
I need a crash report to diagnose crashes
