### ISSUE TITLE
Make dimensions not suck.

### ISSUE THREAD

**Issue by MechanosG** [Tslat/Advent-Of-Ascension#859]
**Describe/name the existing feature this suggestion relates to**
AoA added dimensions just repeat the same things in close proximity, don't really feel natural (compared to the overworld/nether/end/dimensions from lots of other mods, take your pick), and rapidly spam mobs at you.  They're glorified arenas to drop into, grind X item, then leave.  Which was probably the intention, so maybe you don't see any problem with this.  But it could definitely be more fun.

**Describe the change or feature you think would be good to see**
I would have liked to see dimensions be more spread out, have more terrain variation, and spam less mobs.  Basically something that just feels more in line with Minecraft and other popular 1.12.2 mods.

**Add any alternative implementations you think might work**
I don't know how difficult it is, but I imagine even using the vanilla terrain algorithm, or the terrain generation from another mod (with permission), and replacing the blocks it uses with the ones from AoA, would result in much nicer looking dimensions.  Less mob spam in general would also be appreciated by most players, especially with the upcoming loot update.  I currently already do this with a 3rd party mod to reduce spawns (including making overworld mobs mainly spawn in caves rather than out in the open), and the players on my test server love it.

**Include any additional background information**
I'm fully aware that, like many other issues/suggestions, this may end up passively aggressively dismissed.  But I thought I'd throw it out there anyway.  I really do hope this mod will be popular someday.  Notifications will be off.

**Comment by Tslat** [comment]
The rudeness isn't appreciated.

Your Discord chat suggestion wasn't passive-aggressively dismissed, it's just that the world doesn't tend to revolve around you.

As for this suggestion - I'm actually not entirely clear what you're suggesting..from reading it - it appears that you're simply suggestion AoA dimensions be vanilla overworld but replace the blocks, and spawn less mobs?

Wouldn't mind some elaboration so I can tell what you're asking for here.
