### ISSUE TITLE
Only 2 staves use Water runes as of Snapshot 7

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#86]
**Describe/name the existing feature this suggestion relates to**
As it stands, there are only 2 staves in 3.0 that use Water runes: **Water Staff** and **Aquatic Staff**.
As part of the items that have been rebalanced in 1.12.2, all the staves got their costs changed. For the most part this has been a positive change, as runes that were underused like Wither and Lunar are now used by more staves.
This came at a cost though... The amount of staves that used water runes has gone down from 4 to 2. I know there are runes that are used way more often than others, but 2 seems like way too small of an amount to me, especially since Water is one of the more "basic" runes.
For comparison, the runes with the 2nd least amount of staves are both Poison and Strike rune at 4 staves each.

**Describe the change or feature you think would be good to see**
Here's a list of staves that I think should use Water runes:

![image](https://user-images.githubusercontent.com/38159897/48190438-920e2480-e2f7-11e8-9997-06c2f35e9013.png)**Atlantic Staff**: Why doesn't the "Atlantic" staff use Water runes? Seriously. I really do think 2 Water runes would fit on it better than 2 Storm runes. Yeah Water is lower-leveled than Storm but Atlantic also requires Distortion rune so...

![image](https://user-images.githubusercontent.com/38159897/48190460-a05c4080-e2f7-11e8-88bc-5682bd32c072.png)**Coral Staff**: Why doesn't a "Coral" staff also use Water runes?! Well considering that you get 6 extra hearts for **50 seconds**, I think adding a 3rd rune type would be balanced. Maybe 3-4 Water runes?

![image](https://user-images.githubusercontent.com/38159897/48190470-aa7e3f00-e2f7-11e8-95b0-5e42aaa68387.png)**Reef Staff**: Don't think I need to explain what a reef is. I think adding 2 water runes or so would be perfect. As it would fit with Shadowlord/Hive staff since they both 10 of one rune and 2 of another.

![image](https://user-images.githubusercontent.com/38159897/48190500-c1bd2c80-e2f7-11e8-8a26-b442b30794f9.png)**Rosidian Staff**: I know this one is sort of a stretch. I mean, plants need water and staff, so... I think just 1 Water rune would be good. If it makes the cost too high, just subtract 1 Wind/Life rune to make room for the 1 Water rune.
Also I chose this one because I wanted at least 1 staff that didn't come from Overworld/L'Borean

**Add any alternative implementations you think might work**
When am I gonna use this section again?

**Include any additional background information**
For a comparison, here's a list of all the runes and the amount of staves that use them.

Compass: **10**
Distortion: **15**
Energy: **13**
Fire: **5**
Kinetic: **11**
Life: **14**
Lunar: **7**
Poison: **4**
Power: **11**
Storm: **8**
Strike: **4**
Water: **2**
Wind: **21**
Wither: **5**

**Comment by Tslat** [comment]
No longer relevant
