### ISSUE TITLE
Why does Creep Cow drop Halycon beef

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#862]
**Describe/name the existing feature this suggestion relates to**
The cows we have in this modification

**Describe the change or feature you think would be good to see**
Like why, it's bugged me for a long time, I'm not sure why I've never really brought it up before in the past. It's just plain wacky. It's obvious that Creep cow is a reskin of Halycon, which is a reskin of a Cow, but this really pushes that- to the shit.

It's just strange all around, even if you made it so the lore is that "oh they're very very similar species it would still be.... stupid.
Not sure what you could change it to. Regular beef? Creep Cow chops? Gunpowder? Creepy Beefy? I mainly want to see it changed, unless it's changed to something like Chimera Chops then I'm not too concerned with what it could be changed to.

**Comment by Criterion6** [comment]
Same thing with Creep Cows giving halycon milk

**Comment by Tslat** [comment]
Fixed both of these things
