### ISSUE TITLE
Metal blocks not registered in the ore dictionary

### ISSUE THREAD

**Issue by Landmaster** [Tslat/Advent-Of-Ascension#866]
Title. I'm creating a TiC addon for this mod (or more accurately, adding AoA support to PlusTiC), and this issue prevents such blocks from melting and casting into molten metals without extra boilerplate code, and potentially affects other mods' compatibility.

(E.g. Rosite Block should be oredicted as `blockRosite`)

**Comment by Tslat** [comment]
Alright
