### ISSUE TITLE
In-game wiki

### ISSUE THREAD

**Issue by CandyPoeperRuben** [Tslat/Advent-Of-Ascension#867]
So, my idea was to add an In-game AoA3 wiki, completely replacing the Beastary and Guide, i thought it would be handy, since you can open it with a keybind, and you can search anything you could search on the Advent Of Ascension wiki, so you both, dont have to google it, but you can just very fastly access it in your game, and (if it's possible) doesn't require any wifi

this idea might lead to AoA be multiple mb's bigger then it currently is, i dont know, but let my know if that's a problem
another thing what might cause a problem with this idea, is the wiki getting updated, i dont really know how often the wiki is updated, but it would be handy if this in-game wiki would be up-to-date, but i don't know how that would lead out, let me know!

i have not really heard about this idea before, but it came into my mind when i saw this mod:
https://www.curseforge.com/minecraft/mc-mods/in-game-wiki-mod

**Comment by Immortallis1** [comment]
personally I don't agree with this, it seems like too much content and overkill even if you're just downloading it from the internet. Not to mention that anybody can edit it and put misleading stuff in there

**Comment by Seishan123** [comment]
I believe I also did a request similar to this, and I agree with Immortallis1, my idea was more of a crutch than a complete availability. This also has the issue of meaning EVERY page being needed to be loaded on the wiki which is was too much for most computers used for this mod.

**Comment by Tslat** [comment]
Won't really happen. AoA is too big to document everything ingame, and we have a perfectly viable wiki
