### ISSUE TITLE
Canceled Extraction event still produces item

### ISSUE THREAD

**Issue by tyler489** [Tslat/Advent-Of-Ascension#868]
**Mod Version**
What version of the mod are you on?
3.1.2b
**Describe the bug**
Using our custom clam mod that blocks the use event for a block if you arn't trusted in players are still able to use the extractor block and get rewards from it
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to our server with custom claim protection
2. Click on extractor in a claim you dont have access to
3. get items
**Expected behavior**
if the interact event is canceled dont extract

**Comment by Tslat** [comment]
Then your clam mod is wrong.
The extraction device doesn't rely on an event, it relies on built-in block methods which _only_ get called if the event hasn't been cancelled.

Code below from vanilla - you're likely cancelling the wrong event:
`double reachDist = player.getEntityAttribute(EntityPlayer.REACH_DISTANCE).getAttributeValue();
            net.minecraftforge.event.entity.player.PlayerInteractEvent.RightClickBlock event = net.minecraftforge.common.ForgeHooks
                    .onRightClickBlock(player, hand, pos, facing, net.minecraftforge.common.ForgeHooks.rayTraceEyeHitVec(player, reachDist + 1));
            if (event.isCanceled()) return event.getCancellationResult();

            EnumActionResult result = EnumActionResult.PASS;
            if (event.getUseItem() != net.minecraftforge.fml.common.eventhandler.Event.Result.DENY)
            {
                result = stack.onItemUseFirst(player, worldIn, pos, hand, facing, hitX, hitY, hitZ);
                if (result != EnumActionResult.PASS) return result ;
            }

            boolean bypass = player.getHeldItemMainhand().doesSneakBypassUse(worldIn, pos, player) && player.getHeldItemOffhand().doesSneakBypassUse(worldIn, pos, player);

            if (!player.isSneaking() || bypass || event.getUseBlock() == net.minecraftforge.fml.common.eventhandler.Event.Result.ALLOW)
            {
                IBlockState iblockstate = worldIn.getBlockState(pos);
                if(event.getUseBlock() != net.minecraftforge.fml.common.eventhandler.Event.Result.DENY)
                if (iblockstate.getBlock().onBlockActivated(worldIn, pos, iblockstate, player, hand, facing, hitX, hitY, hitZ))
                {
                    result = EnumActionResult.SUCCESS;
                }
            }`
