### ISSUE TITLE
Configurable health and damage

### ISSUE THREAD

**Issue by sigmaJ** [Tslat/Advent-Of-Ascension#869]
**Describe the new feature you think would be good to add**
I would like to be able to configure the values for health and damage for this mod's mobs, as well as the damage of the mod's weapons.  This could be done through the main configuration file, but I think would best be split into multiple configuration files.

**Add any alternative implementations you think might work**
This could be done in a less detailed way, such as a scaling factor and linear modifier for the whole mod or for each type of value - mod health, mob damage, weapon damage - allowing sword damage values to be changed to, for instance, 5 + 1/4 the original value.  However, this, like any alternative I can think of right now, seems less versatile for modpack makers, even if it is less individual config options.

**Include any additional background information**
I haven't seen anyone discussing this particular request, but I have seen discussion of the numbers, usually in the context of them being too large, and thus would not be surprised if other pack makers have wanted the same sort of feature.

**Comment by Tslat** [comment]
The scale of this would be insane, just like the suggestion to configure spawning values for all mobs.
It might be better suited as like.. an official addon or something.. it's just way too big to be included by default

**Comment by Ketrai** [comment]
Some more config would be nice though, the config currently is like the bare minimum to fix compatibility issues but doesn't really offer much else.

**Comment by Tslat** [comment]
Which version of the mod are you playing on?

**Comment by Ketrai** [comment]
I'm playing on 3.1.2.b

**Comment by Tslat** [comment]
Noted
