### ISSUE TITLE
Overworld mobs needlessly aggressive. Kill friendly npcs indiscriminately.

### ISSUE THREAD

**Issue by Ketrai** [Tslat/Advent-Of-Ascension#870]
**Mod Version**
R | AoA3 3.1.2.b

**Describe the bug**
I'm playing with a few mods, including millenaire. It seems that hostile creatures just attack anything that's classified an ally of the player, even when they're not a direct threat to them. This results in the annoying situation where the villagers constantly die, making it hard and nigh impossible to progress in millenaire, or other colony mods like it.

**To Reproduce**
Steps to reproduce the behaviour:
Go to a friendly, watch them to get murdered by one of the countless overworld mobs.

**Expected behavior**
To have a nice experience even with other mods like this, which fit perfectly in the MMORPG theme AOA is aiming for. It  would be nice to have a config to tweak the damage/health of mobs in a certain dimension. To lower the aggression of mobs, or to make them do less damage against friendlies. (discriminate between summoned creatures and unrelated creatures) Just some more config options in general would be epic, instead of. "Disable all overworld mobs." Which breaks the mod suffice to say.

**Screenshots**

**Comment by Tslat** [comment]
To clarify - are we specifically talking about AoA mobs attacking millenaire mobs?

AoA's mobs don't actually target villagers or summons - only AoA minions and players.
Was it just any mobs attacking? or only certain ones?

**Comment by Ketrai** [comment]
Certain mobs do indeed attack millenaire villagers unprovoked. Black ursa for example, nature, urka.

**Comment by Tslat** [comment]
Hunters aren't an overworld mob.. you have some other mod causing issues here

Can you try this millenaire thing without any other mods to see if it is an aoa thing, or whether another mod is interfering?

**Comment by Ketrai** [comment]
> Hunters aren't an overworld mob.. you have some other mod causing issues here
> 
> Can you try this millenaire thing without any other mods to see if it is an aoa thing, or whether another mod is interfering?

Sure, I'll see about testing that. The hunter thing I already figured out, which was indeed a compatability issue which forced me to remove an already problematic mod.

**Comment by Seishan123** [comment]
I have seen this occur with Scrubbies, which allows me often to get one powerful attack in before the rest notice me. I have also noticed this occurs with AoA npcs (which includes the lottoman and assassin). This doesn't happen with pixons however.

**Comment by Tslat** [comment]
This looks like a dead end issue since followups were never provided

**Comment by Ketrai** [comment]
Yeah I stopped caring, AOA provided more issues than it ended up being an enjoyable mod for me. If anything I felt there were too many dimensions and mobs, whilst they could've done with being fleshed out more. Overworld mobs spawning during daytime is too intrusive, and disabling said spawns cuts out too much content. Also mobs with extremely bloated HP bars or that couldn't be killed at all due to slayer requirements suck big time early game. Mod has potential, but "less is more"

**Comment by Tslat** [comment]
Shame, since basically all of those issues are fixed in the next update. 
Ohwell, good luck with whatever you move on to

**Comment by Ketrai** [comment]
Well I probably will try the new update eventually when the rpg mood strikes again.
