### ISSUE TITLE
Shooting a skydriver bow's arrow over the void causes the game's ai to freeze

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#875]
**Mod Version**
Technically snapshot 4, but the bug has been observed in 3.1.2.b on sweaty's stream (I think?).

**Describe the bug**
When you shoot a skydriver bow's arrow over the void, the game's ai freezes. It appears to be an ai freeze, as I am unable to fire more arrows or spawn mobs with spawn eggs after it happens initially.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a dimension with void.
2. Fire a skydriver bow's arrow making it fly over the void.
3. Watch as the game's ai freezes. 

**Expected behavior**
The game's ai does not freeze when you fire an arrow from skydriver bow over the void.

Check out the end of sweaty's stream to see this bug in action (start at 51:20 until the end)):
https://www.youtube.com/watch?v=6Z2Pn1yepHk

**Comment by EatingSilencer** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/3567013/latest.log)

**Comment by Tslat** [comment]
Fixed
