### ISSUE TITLE
Elusive Music (Update)

### ISSUE THREAD

**Issue by Firch** [Tslat/Advent-Of-Ascension#878]
Hello Scimi! This is my other (second) music suggestion. I just wrote music for Elusive boss fight, which may appear in mod (hopefully). Reason - because music needs to be exclusive, not written by KevinMacLeod :elusiveboi:

Update 06/09/2019
Music: Elusive - Mirage Lord 
Author: Me (Firch)
https://soundcloud.com/hvab6gxlzwis/mirage-lord-rework
Thank you!

**Comment by Tslat** [comment]
I'll drop some feedback here for this and any future ones you do :)

The general motif of the song is pretty good, if not maybe just a tad upbeat for a boss in a dark world that utilises dark tactics. 
I'd also recommend avoiding 8-bit synth sounds wherever possible for Minecraft/AoA as the sound of it doesn't fit what Minecraft really is.

Also, all sounds and tracks for Minecraft _must_ be mono, not stereo, as Minecraft doesn't support stereo channel sounds while ingame.

I hope you try some more of these, taking the above feedback into account
