### ISSUE TITLE
Changing Grass Hardness

### ISSUE THREAD

**Issue by RugratCoder94** [Tslat/Advent-Of-Ascension#879]
In dimensions that lack dirt, the grass usually hold the same appearance as the stone. However, the grass breaks at the same speed that dirt would, despite being on stone and not dirt.  

For consistency purposes, the following grass blocks should break as fast as the stone they're on:
Abyssal Grass
Iromine Grass
Lelyetian Grass & Inverted Lelyetian Grass
Precasia Grass
Runic Grass
Shyre Grass

**Comment by Tslat** [comment]
Done
