### ISSUE TITLE
Config drop of skills

### ISSUE THREAD

**Issue by Glazya** [Tslat/Advent-Of-Ascension#881]
Hello! I'm a minecraft server moderator that uses your mod. Please, you can add to the mod config drop of skills. This is important so that the mod can be balanced with other mods

**Comment by EatingSilencer** [comment]
Can you clarify what you mean by "config drop of skills"? If you're talking about what configuring the items dropped by skills (foraging etc) that is being made changeable in the next update.

**Comment by Glazya** [comment]
If you want to change skills globally, please consider to add configuratinon of items which are obtained. (For example drop from mining skill or extraction). It is essential to provide such option to set up modpacks with other mods. In our case we use you mod as a base to obtain different resources with tech reborn (oil from Deepland, Helium from Haven etc). And for example we need to disable diamond drop from simple mining because it devalues internal TechReborn balancing. We can replace it by some type of fuel, in order to save balancing

**Comment by Skyine918** [comment]
I agree, such option would be very powerful to use. Our server like your mod very much, and we want to give our players new game mechanics.
![unknown](https://user-images.githubusercontent.com/35529938/64489281-f40e2200-d259-11e9-9244-1354f5438d55.png)

**Comment by Tslat** [comment]
The next update will allow you to do this through data packs
