### ISSUE TITLE
Improving the readability of certain boss bar sprites

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#882]
**Describe/name the existing feature this suggestion relates to**
Boss bar sprites

**Describe the change or feature you think would be good to see**
I know lots of people use HP indicator mods, but I still think it's important for boss HP bars to be pretty readable. Besides, you can still see the boss HP bar without looking at the boss, something most hp indicator mods don't do.
Having an easy to read indicator of how much progress a player has made is pretty important for their mentality during intense fights. In AoA's case, a boss' title and the style of the bar can be a visual indicator for what the boss is like in terms of theme.

Smash's is a pretty good example of this.
![image](https://user-images.githubusercontent.com/38159897/64512821-0c069580-d29c-11e9-829c-d2788de54204.png)
But I cannot say the same for certain ones.

----------------------------------------------------

This has been a very small pet peeve of mine for years. It's not a huge deal at all, it's actually very small, but any improvement to make something more readable can be a good thing.
Basically certain HP bars make it annoying to see how much HP the boss has left without using another mod.

These gaps are a little odd.. The bar doesn't skip over them, it's essentially just invisible when BamBamBam has a certain amount of HP.
![image](https://user-images.githubusercontent.com/38159897/64513443-694f1680-d29d-11e9-8974-0079c923eb90.png)

Skeletron's isn't the worst, but when you're trying to quickly look at it, it's not very reliable.
![image](https://user-images.githubusercontent.com/38159897/64513337-1ffec700-d29d-11e9-8a5e-d30d15901d92.png)

These gray parts actually don't change color at all when you lower Silverfoot's HP. Outside the yellow/tan Silverfoot's remaining HP is a big mystery. (unless you're using another mod haha)
![image](https://user-images.githubusercontent.com/38159897/64513822-3a857000-d29e-11e9-8fb5-3b95fa353bf9.png)
The gray part could be made darker so that there's more of a difference(?)
Mechbot's also has a similar thing, but it's not as bad so I'm not sure if it's an issue? Honestly I have no clue lol
![image](https://user-images.githubusercontent.com/38159897/64513985-97812600-d29e-11e9-9495-df95831c7c8f.png)

The eyes on the far left and right are quite naughty, the shading on them doesn't change at all depending on remaining HP. Other than that it's fine.
![image](https://user-images.githubusercontent.com/38159897/64514252-1e360300-d29f-11e9-875e-0fb342447d3d.png)

The white spots on Gyro's also never change color.
![image](https://user-images.githubusercontent.com/38159897/64515116-d31cef80-d2a0-11e9-9bf7-9ee500d3edab.png)

Same case as Gyro with the white tube things...
![image](https://user-images.githubusercontent.com/38159897/64515436-73731400-d2a1-11e9-90f0-57b617906f2a.png)

The white and dark gray parts of Creep's bar is also the same case. I guess you have the words as another indicator but still...
![image](https://user-images.githubusercontent.com/38159897/64515610-baf9a000-d2a1-11e9-9d39-72926e9c6530.png)

Simply changing the shading of these parts would be good, or changing the whole color if that's necessary.
I know it's almost petty to suggest to change such small things, but you know me haha

**Include any additional background information**
Primordial 5 is a little unique. As their HP goes down, the text inside the bar vanishes entirely rather than just becoming gray like the rest of the bar. I am kind of hoping this stays though, don't ask why. 
![image](https://user-images.githubusercontent.com/38159897/64516015-8afecc80-d2a2-11e9-9816-72b34374a958.png)

**Comment by VBGaming** [comment]
~~i only need to ask if it's intentional that you screenshotted while it said 'Primordial Ass'~~
