### ISSUE TITLE
Skydriver bow's arrows can replenish acid until arrow decays if shot into the acid

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#885]
**Mod Version**
Snapshot 4 for 3.2
**Describe the bug**
When you shoot a skydriver bow's arrow into a skydriver acid block, and then try to break the block, a new acid block is immediately spawned.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a skydriver bow's acid onto the ground.
2. Shoot an arrow into it with a skydriver bow.
3. Try to break the acid.

**Expected behavior**
The arrow would drop to the ground and no new acid would be produced.

**Comment by Tslat** [comment]
I feel like i'm ok with this.
It makes sense for the arrow to be dripping acid still - and from a balancing perspective the arrows only exist inground for 60 seconds anyway

**Comment by Tslat** [comment]
Regardless of stance, this is no longer a thing
