### ISSUE TITLE
Change the "Oops" advancment

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#887]
**Describe/name the existing feature this suggestion relates to**
The "Oops..." advancement
**Describe the change or feature you think would be good to see**
This advancement is not kind to hardcore mode players who would be locked out of it (I tested with Totem of Undying and no that does not give you the advancement either).

My suggestion is change it to something else, or make it obtainable with the Totem of Undying.

**Include any additional background information**
I don't think so

**Comment by EatingSilencer** [comment]
Give me a sec accidentlly posted this.

**Comment by Tslat** [comment]
Yep
