### ISSUE TITLE
Structure maps

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#888]
Aside from loot (which is already being fixed), the second most important, annoying, and grindy thing is finding structures. I'm pretty sure I don't have to explain why.

To obtain the maps, there would be a new crafting station called the Mapping Station (since cartography table is already taken in 1.14). At a mapping station, you could add gems from a specific dimension to a blank map in order to turn it into a blank <dimension> map. You can then add specific ingredients to a blank dimension map in order to turn it into a map for a specific structure. Ideas for the structure map recipes are:

All Lotto structures: 8 gems from that dimension

All rune shrines: 4 blank runes, 2 runium, and 2 charged runium (the type of shrine depends on the type of map used)

Nethengeic pit: 4 emberstone, 3 blazium, and 1 wither skull

Guardian's tower: 4 wind runes and 4 crystallite

Rockrider boulder: 4 stone, 2 crystallite, and 2 compass runes

Dawnlight Dungeon: 4 Crystallite, 2 Amphibyte Lungs, and 2 water runes

Illusion Tree: 4 Eye blocks, 2 starring eyes, 2 observing Eyes

Flesh temple: 1 observing eye, 3 rotten flesh, 4 bloodstone

Shadowlord Platform: 1 book of shadows, 3 primordial dust, and 4 bloodstone

I'd keep making recipes, but it's quite time-consuming and they probably won't be the ones used in-game if this suggestion is added. I just wanted to give an example of how the system would work.

**Comment by minix0** [comment]
Maybe you could call combine all of the structure map options for a dimension to make a Twilight Forest-style full structure map?
