### ISSUE TITLE
Shots fired from the Jack Rocker placing cobblestone where it lands

### ISSUE THREAD

**Issue by Sweaty07** [Tslat/Advent-Of-Ascension#889]
**Describe/name the existing feature this suggestion relates to**
The Jack Rocker.

**Describe the change or feature you think would be good to see**
A screenshot shown by Cruuk of the Jack Rocker in 3.2 shows that the shots fired from the cannon is an actual block of cobblestone.

![unknown](https://user-images.githubusercontent.com/52132442/64911001-71330e80-d714-11e9-8d8c-032e6a7e1b26.png)

This has given me the idea that if the Jack Rocker's shots don't hit an enemy they could instead place a cobblestone block at the location it lands on, making it useful, for instance, for building bridges across floating islands in Haven, Celeve and Lunalus given the dimensions' often hard-to-traverse generation.

**Comment by Cruuk** [comment]
I am on edge about the idea of weapons placing blocks (Reef staff doesn't take priority over existing blocks), but other than that it's a pretty good idea.

**Comment by Tslat** [comment]
Done in 3.3
