### ISSUE TITLE
Extraction

### ISSUE THREAD

**Issue by Seishan123** [Tslat/Advent-Of-Ascension#89]
When extracting items you sometimes get nothing (When nothing is in the lava, not when it crumbles), including no experience for the process, wasting resources. Instead you should earn some experience for doing so, even when you get nothing. This will help leveling up extraction easier as it does take a long while to do so. Also it makes breaking that obsidian worthwhile.

**Comment by Tslat** [comment]
The rate is actually slightly wrong in 1.7.10, it was meant to be a bit better but missed the update cut. This will address your issues in whatever version comes next
