### ISSUE TITLE
Loading entity NBT  java.lang.NullPointerException: Loading entity NBT

### ISSUE THREAD

**Issue by Destructuctor** [Tslat/Advent-Of-Ascension#894]
Version: Latest for 1.12.2

This bug occurs on loading into a world. I have tried about 3 times to load into a world getting this error every single time. 

I honestly have not seen any reports of this bug, so you may not be able to reproduce, but just try loading into a world.

What did you expect?: For the game to load haha!

FULL Error log: 
https://hasteb.in/ihumiceh.yaml

**Comment by Tslat** [comment]
Duplicate of #840
