### ISSUE TITLE
Tweak the player teleport attack

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#895]
**Describe/name the existing feature this suggestion relates to**
The unfair instant teleport to player attack used by several bosses.

**Describe the change or feature you think would be good to see**
Make the ability dodgeable. This could be done by targeting the player coordinates and making the boss teleport to them about a second later. This way the attack would still be a threat but would not be impossible to dodge.

**Add any alternative implementations you think might work**
Some bosses could have variations of the attack. Voxxulon could slowly float to the target instead of teleporting, while Miskel could teleport randomly, similar to an enderman. I already suggested this before, but Visuallent could regain its random teleport ability.

**Include any additional background information**
Removing the attack has been suggested many times before, but this could also have negative effects on some bosses: Voxxulon would be unable to move, and Kajaros/Miskel would go back to being easy and boring.

**Comment by Cruuk** [comment]
It already got confirmed to be getting removed. I'm not too... concerned with suggestions that are trying to retain boss difficulty right now, but I'm just letting you know.
Also, Miskel doesn't have the tp in your face stuff, you may be thinking of Okazor (the guy that does 50 damage)

**Comment by Tslat** [comment]
Has been resolved in 3.2
