### ISSUE TITLE
C.R.E.E.P spawns in groups in almost every chunk

### ISSUE THREAD

**Issue by TheArtcore** [Tslat/Advent-Of-Ascension#896]
**Mod Version**
AoA3-3.1.2.b.jar

**Describe the bug**
C.R.E.E.P. spawns in the overworld almost everywhere on my server.

**To Reproduce**
Steps to reproduce the behaviour:
1. I installed OTG and the Biomes Bundle.
2. Deleted the world to generate anew.
3. After connecting to the server they spawn in almost every chunk.

**Expected behavior**

**Screenshots**
![2019-09-18_14 11 30](https://user-images.githubusercontent.com/55513627/65186693-038e2780-da1f-11e9-8cb0-e87d04039970.png)
![2019-09-18_14 12 20](https://user-images.githubusercontent.com/55513627/65186695-0426be00-da1f-11e9-941e-453119c225a5.png)
![2019-09-18_14 12 29](https://user-images.githubusercontent.com/55513627/65186697-0426be00-da1f-11e9-8755-2325ecf25471.png)
![2019-09-18_14 12 45](https://user-images.githubusercontent.com/55513627/65186698-0426be00-da1f-11e9-8e10-0ce09e44d728.png)

**Comment by Tslat** [comment]
Another mod is causing this.
AoA doesn't have a spawn registry entry for CREEP, and as such it is impossible for it to be spawning naturally without outside interference.

Figure out which other mod is causing him to spawn, that'll be your problem

**Comment by Archilyte** [comment]
umm
its otg thats causing this
get the v8r6 from their discord to fix this
