### ISSUE TITLE
[1.12.2] Bit of a HUD conflict with 'Cyberware'. AoA's Resource HUD color changes color when setting Cyberware's Energy HUD color.

### ISSUE THREAD

**Issue by Z-Tunic** [Tslat/Advent-Of-Ascension#898]
Refer'd Issue:
https://github.com/An-Sar/Cyberware/issues/112

Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 3
AoA3-3.1.2.b
cyberware-1.12.2-0.2.11.20
jei_1.12.2-4.15.0.279

-----

There appears to be a HUD conflict with Cyberware. AoA's Resource HUD changes colors whenever I change Cyberware's Energy HUD coloring as shown in the image below.

![](https://cdn.discordapp.com/attachments/377171551155650560/624292984191713301/cyberwareaovhudleak.PNG)

Top is AoA's HUD without the Cyberware HUD.

Bottom is AoA's HUD with the Cyberware's HUD. Note that the color changes depending on what color Cyberware's HUD is set at.

-----
*EDIT*
I forgot to mention how to get the HUD to show. You'll need to place a 'Robo Surgeon' on top of a 'Surgery Chamber' and then right-click on the Robo Surgeon to open it's GUI.

For the Eyes Slot, add in the 'HUDlens' and then a 'Internal Battery' for the Lower Organs Slot. To produce power... add in the 'Cardiovascular' for the Heart Slot | 'Solarskin' for the Skin Slot | Metabolic Generator for the Lower Organs Slot.

After that's done... you step into the chamber and close the doors... take some damage and then the augments will be applied and you should see the HUD appear. It'll be flashing red at first due to low power but you'll see that the AoA Resource HUD will flash red as well.

**Comment by Tslat** [comment]
This has been fixed in the next update
