### ISSUE TITLE
Indicator for when a mob is in a great blade's extended range

### ISSUE THREAD

**Issue by profilename14** [Tslat/Advent-Of-Ascension#899]
When using a normal sword, there is in indicator for when a mob is in range
![Annotation 2019-09-20 163107](https://user-images.githubusercontent.com/44542640/65364315-e3e53380-dbc5-11e9-8fbd-cc81c52afe7c.png)

However when using a greatblade, the indicator activates only when a mob is in normal sword range, even though the greatblade can hit beyond that range
![2019-09-20_16 33 16](https://user-images.githubusercontent.com/44542640/65364380-4e966f00-dbc6-11e9-9299-c32a8ab1db95.png)
![2019-09-20_16 33 18](https://user-images.githubusercontent.com/44542640/65364384-548c5000-dbc6-11e9-8008-0c69e6221173.png)

I'm not sure if this can be fixed, but if it can it would make using great blades a bit easier

**Comment by Tslat** [comment]
Huh. Didn't even notice this was a thing lol

**Comment by Tslat** [comment]
Wow this is a lot nastier than it sounds to implement lol - just checked the code
