### ISSUE TITLE
Flying Mobs Overwhelming

### ISSUE THREAD

**Issue by nrichmond** [Tslat/Advent-Of-Ascension#900]
A lot of the flying mobs in certain dimensions, like _Mysterium_, _Crystevia_, and _Creeponia_ tend to be very overwhelming. They tend to be constantly coming at you to the point where fighting _Runic Golems_ or trying to climb up into _Crystal Transfer Structures_ can be very difficult. I feel like their detection range could be too far, or the spawn rate of these enemies might be too high. I can't tell you how many times I almost died just from trying to climb up to my _Mysterium_ portal that spawned high up on top of three mushrooms.

**Comment by Tslat** [comment]
They're being nerfed in the next update
