### ISSUE TITLE
[Suggestion] Configure Resources HUD location via X, Y coordinates. Maybe for the Skill Icon Pop-Ups at the top of the screen as well?

### ISSUE THREAD

**Issue by Z-Tunic** [Tslat/Advent-Of-Ascension#901]
Would it be possible to allow one to move the Resources HUD via X,Y coordinates? Currently... there's only set options such as TOP_RIGHT, TOP_LEFT, BOTTOM_RIGHT, BOTTOM_LEFT in the config.

I was also going to mention the Skill Icon pop-ups that appear when you gain XP to be moveable via X,Y coordinates but not sure how that would look with the XP pop-ups that scroll up. I was thinking of moving it towards the hotbar in a way but... eh. If not possible for that then just the Resources HUD would do.

**Comment by Tslat** [comment]
That feature was there originally and basically no-one ever used it ever. Also it breaks when you resize your screen.
Very unlikely it'll ever come back, try switching between corners (and don't forget the horizontal/vertical toggle also in the config)

**Comment by Z-Tunic** [comment]
I've tried those options and couldn't find the sweetspot for it. I was thinking of putting it like under a minimap if I had any minimap mods installed since if it was in the TOP_RIGHT it would either cover the minimap or the minimap would cover it. Thank you, though.
