### ISSUE TITLE
Egg idea.

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#91]
So as we know 3.0 will include spawn eggs for every mob.
Its good but I have a problem with it. Back in 2.5 snapshot spawn eggs made NEI get litter with them.

So my idea is to have one egg were you can set what mob spawns in it. You can have multiable eggs with different mobs set in them.

I know this isn't really a annoyance but it would be nice to see all the cool items in JEI without having 2 pages of just eggs.

**Comment by Immortallis1** [comment]
Just skip past the pages of eggs lol

**Comment by Sagisolar** [comment]
Ehhhh still perfer it.
