### ISSUE TITLE
Add configs to disable guns/snipers

### ISSUE THREAD

**Issue by stillg0ld** [Tslat/Advent-Of-Ascension#911]
**Describe/name the existing feature this suggestion relates to**
Guns, snipers, other long range weapons

**Describe the change or feature you think would be good to see**
A config option to disable certain weapons from the mod.

**Add any alternative implementations you think might work**
I'm obviously not a creator, so I'm not sure if it is any easier or harder, but even a config option to disable ALL guns would be helpful.

**Include any additional background information**
I love the dimensions but I can't get behind guns in minecraft, and I'm sure there are quite a lot of people who would benefit from this. I could use crafttweaker to disable the recipes but not only will that take quite some time, it would not prevent those items from being added to loot tables.

**Comment by EatingSilencer** [comment]
You're not the first person I've seen that has a problem with the guns, but I don't think that a config is likely to get added unless an overwhelming amount of support for this occurs.

Best case scenario, whats more likely to happen is that someone makes an addon for this mod that just removes the guns.
