### ISSUE TITLE
Fishing rods and Shields

### ISSUE THREAD

**Issue by CandyPoeperRuben** [Tslat/Advent-Of-Ascension#913]
So, Hauling is a thing in AoA, so i thought, why not add Special Fishing rods, that add different abilities, like you get twice as much hauling xp, if you catch a AoA exclusive Fish, just an example, i think that would be fun

my second idea, is Shields, Vanilla shields are pretty good, but i think it can be a little better to, again, add shields with special abilities, like a shield with "spikes" on it and will deal damage to the enemy when they attack the player, but it get blocks etc. there will have to be like an idea section for the players to leave ideas for names, abilities and textures etc.

**Comment by Tslat** [comment]
Shield with MORE power? geez, they're already pretty OP as it is lol
