### ISSUE TITLE
Spikeback Slab gives too few xp when used on the creation forge

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#914]
**Mod Version**
3.1.2.b
**Describe the bug**
Spikeback Slab only gives 12 xp when used on the creation forge, even though its a level 35 minion.

**To Reproduce**
Steps to reproduce the behaviour:
1. Train Creation to level 16.
2. Use a Spikeback slab on the Creation forge.
3. See it only give 12 xp.

**Expected behavior**
Spikeback Slab gives more xp thats similar to its level.

**Comment by EatingSilencer** [comment]
Might I also suggest Spikeback Slab be changed so that its level is consistent. It requires level 35 to summon but only level 16 to use on the creation forge. No other slab is like this.

**Comment by EatingSilencer** [comment]
Accidentally closed this.

**Comment by Tslat** [comment]
Fixed as of 3.2
