### ISSUE TITLE
Hellquin Slab requires different level to summon than to use on creation forge

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#915]
**Mod Version**
3.1.2.b

**Describe the bug**
Hellquins can be summoned at level 34, but require level 45 to use on the creation forge.
**To Reproduce**
Steps to reproduce the behaviour:
1. Get your creation level to 34
2. Try to use a hellquin slab on the creation forge
3. See that it doesn't work

**Expected behavior**
Hellquin Slab can be used on the creation forge at the same level that it can be summoned.

**Comment by Tslat** [comment]
You know that several slabs are like this right?

**Comment by EatingSilencer** [comment]
Is this intentional?

**Comment by Tslat** [comment]
This has been a thing since long before I took over AoA. You guys didn't know this?

**Comment by Tslat** [comment]
Fixed this in 3.2
