### ISSUE TITLE
damage

### ISSUE THREAD

**Issue by erion04** [Tslat/Advent-Of-Ascension#916]
**Mod Version**
What version of the mod are you on? : 1.12.2

**Describe the bug**
A clear and concise description of what the bug is.  : is it normal that a shovel is doing more damage than a sword ? because i looked and saw that an amethyst , rosite and jade shovel do
more damage than the sword version. the other swords do more damage 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**
![2019-09-30_18 05 50](https://user-images.githubusercontent.com/55992853/65896267-31735480-e3ad-11e9-8b5c-b3715428cd9d.png)
![2019-09-30_18 05 47](https://user-images.githubusercontent.com/55992853/65896269-31735480-e3ad-11e9-8670-3d64f0398a52.png)

**Comment by Tslat** [comment]
Minecraft's tool balance is wacky. The sword still does more damage overall due to its much higher attack speed, but yeah I've gotta look at these

**Comment by Tslat** [comment]
Has been resolved as of 3.2
