### ISSUE TITLE
Goofy Pickaxe never drops gems

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#920]
**Mod Version**
3.1.2b

**Describe the bug**
If you mine gems (jade, sapphire, etc) with a goofy pickaxe, there's a 0% chance of getting drops

**Expected behavior**
The pickaxe's ability would work normally, but without the auto-smelting part.

**Comment by Cruuk** [comment]
That's pretty goofy

**Comment by Tslat** [comment]
No longer an issue in 3.2
