### ISSUE TITLE
Toggle option for which skills you can see on the game screen.

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#921]
This would be a great addition to the mod for knowing what level you're at for what you need to do next. For example: if you're at level 15 Hunter level, and you want to know when you get to level 20, you can toggle the hunter skill in the AOA Menu without having to constantly press the "INSERT" button.

**Comment by EatingSilencer** [comment]
Can you clarify this a bit more? I'm not sure what you are talking about. Are you saying that there should be a way to check the skill level without opening the gui?

**Comment by mrcakesamurai** [comment]
Exactly!

**Comment by Tslat** [comment]
Shouldn't be a problem anymore
