### ISSUE TITLE
Trees´ Sapplings

### ISSUE THREAD

**Issue by Pokesmile-modded** [Tslat/Advent-Of-Ascension#922]
I might be a good idea to add Sapplings to the Advent Of Ascension dimensions trees, some woods are pretty fancy but they´re not renovable, it would be possible to create sapplings that need to be planted on these dimensions´ soils. These sapplings would be dropped by these trees´ leaves. You could also add special fruits for every type of tree.

Sorry if I wrote something bad my english isn´t that good I am spanish

**Comment by EatingSilencer** [comment]
This is a duplicate of #75.
