### ISSUE TITLE
Immortalis Suggestions

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#923]
There's a few suggestions I've come up with over time for Immortalis, so I figured I'd compile them into one post.

_**Replace Room 2**_
I've always found the second room to be an annoyance. It's just a easier version of the 8th room. Not even the mobs are unique; they're almost the same as ghosts. I think it should be replaced. Maybe an obstacle course room with traps, dispencers, mazes, etc.

_**Make the Immortals more boss-like**_
Ah, the Immortals. I've loved them since they were originally announced. However, they are fairly underrated, and I think that's because their design makes them seem unimportant. It's arguable whether they can even be considered bosses or simply extra rooms. I think it'd be nice if they had health bars and boss music, just as a way to tell players they are bosses.

_**Replace Klobber's and Proshield's ability**_
Klobber and Proshield's abilites are really poorly made. I think they should be changed. Even if the replacement is an extremely simple attack, it'd be nice to have a somewhat decent ability as a replacement until they get reworked later on. Klobber could occasionally teleport a few blocks above the player and attempt to land on him. Proshield would get a new arena which is an empty room with lava around the perimeter. For Proshield's attack, I have two ideas. One idea would be giving making him faster and completely immune to all damage except lava. If you hit him, you would take a large ammount of knockback, but Proshield would also take some recoil. The idea is that you would have to try to throw Proshield into the lava without falling in yourself. The other idea is making him more player-like, and making him randomly enter a blocking form. If you hit him while he's blocking he won't take damage and will counter your attack by knocking you back. If you time your attack correctly he will simply take damage.

_**Alternate run/shortcut**_
Repeating several runs of Immortalis can get fairly boring, especially when you already know you can beat it. I'd add an alternate run which is unlocked by using some special item sold by the token trader on the starting block. This will teleport you to a special arena where you have to beat all four immortals at once. If you win, you get the same rewards as a regular run. This would serve as quick way to grind tokens for players who have proven they're able of beating repeated runs while still not giving them away for free.

**Comment by EatingSilencer** [comment]
By room 2 I presume you mean the room with Skelekytes and Skeledons?

Also, not sure how well a teleporting boss would be received.

**Comment by DiamondWalker** [comment]
> 
> 
> By room 2 I presume you mean the room with Skelekytes and Skeledons?
> 
> Also, not sure how well a teleporting boss would be received.

Wow I never expected such an old suggestion would get new replies. I only came across this by pure chance.

Yeah I meant the skelekytes and skeledons.

And yeah I'm well aware about the disdain for teleporting bosses. However klobber wouldn't teleport into you; instead it'd teleport a few blocks above you, giving you time to run out from beneath him once you notice he teleported. He'd still be pretty simple to beat: you'd just have to attack him, and sprint as soon as he disappears
