### ISSUE TITLE
Crash certain amount of time after world Creation

### ISSUE THREAD

**Issue by CesarRamos2003** [Tslat/Advent-Of-Ascension#924]
**Mod Version**
3.1.2b
**Describe the bug**
Crashing a short amount of time after world creation

Trying to put together a modpack, I've narrowed the crash down to this mod. I really have no clues towards what exactly is causing this

Crash log: https://pastebin.com/Q9eQSesT

**Comment by Tslat** [comment]
Unrelated to AoA. No idea what's causing it though
