### ISSUE TITLE
A change to Sling shot to make it not suck

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#925]
**Describe/name the existing feature this suggestion relates to**
Sling shot

**Describe the change or feature you think would be good to see**
It's just bad all around. In an objective way, maybe it's good. But something about it feels worthless and not worth getting. Maybe because it's Explosive bow 2? Maybe because Lunalus makes it not worth the risk? No clue, but either way I think changing its ability would be beneficial for it.

I know trying to make everything super unique is a slippery slope, but with Sling shot already being a bit distinct among the bows I think it would work.
Instead of being Explosive bow 2, it should instead be: 

**Movement isn't slowed down while drawing back**

Slingshots tend to be a bit lighter than Bows, so I think it'd be pretty cool if Sling shot allowed free movement. You'd still have to pull it back like any other bow, but the movement isn't slowed. I know it would make it a weird hybrid of throwing weapons, bows, and archer guns, but I think it could still work... and is it any worse than what it's like currently?

Anyway, every other aspect of it like average damage, durability, where you obtain it, etc. is all free game. I'm just hoping it allows free movement or something, to make it cool.
Code-wise, I'm not sure how hard it would be to implement. It it isn't, at least I'm learning something.

**Include any additional background information**
Pop shot is its own strange item...

**Comment by Tslat** [comment]
Stuff was rebalanced in 3.2.

Re-Raise this if you think it's still relevant after 3.3
