### ISSUE TITLE
3.1.2b All mod bows power enchantments do not work

### ISSUE THREAD

**Issue by onver** [Tslat/Advent-Of-Ascension#927]
**Mod Version**
3.1.2b

**Describe the bug**
All mod bows power enchantments do not work

**To Reproduce**
Anvil enchants any mod bow, compared with ordinary mod bow damage

**Expected behavior**
Revenue from power enchantment

**Screenshots**
nothing

**Comment by Tslat** [comment]
It does work, it's just very underwhelming. It's been fixed in the next version
