### ISSUE TITLE
[1.12.2] Invisible Entities spawning? *Can only catch them if using a Minimap Mod.*

### ISSUE THREAD

**Issue by Z-Tunic** [Tslat/Advent-Of-Ascension#930]
Refer'd Issue:
https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/93

Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 3
AoA3-3.1.2.b
Xaeros_Minimap_1.18.4_Forge_1.12
XaerosWorldMap_1.4.10.1_Forge_1.12

-----

There seems to be invisible entities spawning for a split second and then disappearing. You don't see these mysterious mobs at all in the world but if using a minimap mod, in this case... Xaero's Minimap which shows colored dots on the map if there are entities present for mobs, items, etc, you'll see that they appear for a split second on the map but then disappear. Here's a GIF of what it looks like while in the Nether, can also happen in the Overworld.

*Note: Watch the Yellow Dots appear & disappear.*
https://i.imgur.com/lbnDsOC.gif

Is this suppose to happen like with the way the spawning works?

**Comment by EatingSilencer** [comment]
Yes, this is supposed to happen. Basically what you are seeing is an entity called a spawn fluffer.
[](https://adventofascension.gamepedia.com/Spawn_Fluffer)
The purpose of this entity is to fill up the spawn cap to help lower the spawn rate of other mobs. It is programmed to spawn and despawn relatively quickly.

**Comment by Z-Tunic** [comment]
Ah, alright. Thank you for info.
