### ISSUE TITLE
3.1.2b On Archergun's bugs

### ISSUE THREAD

**Issue by onver** [Tslat/Advent-Of-Ascension#932]
**Mod Version**
3.1.2b

**Describe the bug**
Archergun can't reclaim arrows
Archergun can't hurt Graw

**To Reproduce**
Steps to reproduce the behaviour:
Survival mode
Archergun Attacks Ground，can't reclaim arrows
Archergun Attacks Graw

**Expected behavior**

Archergun can recycle arrows
Archergun can hurt graw

**Screenshots**
nothing

**Comment by Tslat** [comment]
These should be fixed in 3.2
