### ISSUE TITLE
Can't update mod version?

### ISSUE THREAD

**Issue by Spekkun** [Tslat/Advent-Of-Ascension#935]
**Mod Version**
AoA 3.1.2.b

**Describe the bug**
I  try to update my server from an older version to the most current on CurseForge, but my CPU usage shoots up and then I can't open the game.

**To Reproduce**
Delete old AoA server in Mods Folder
Add 3.1.2.b into mods folder
Open server

**Expected behavior**
To play the game without choppiness/lag, or CPU usage jumping all the way up yo 80-100%.

**Screenshots**

**Comment by Tslat** [comment]
Provide the latest.log file

**Comment by Spekkun** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/3731429/latest.log)

**Comment by Tslat** [comment]
That looks like it's running fine to me.

Is it your client that's lagging?
If so, provide the log file from the client instead.

**Comment by Spekkun** [comment]
[2019-10-15-5.log](https://github.com/Tslat/Advent-Of-Ascension/files/3731499/2019-10-15-5.log)

It might be? My CPU usage shoots really high, up to 100% (It doesn't on the older version I used, the one that won't let me place soul bone totems or summon bosses), and then my game lags entirely

**Comment by Tslat** [comment]
You don't have enough RAM allocated to Minecraft. Allocate more RAM
