### ISSUE TITLE
Crash Error: Ticking Entity on Modded Server

### ISSUE THREAD

**Issue by xReficul** [Tslat/Advent-Of-Ascension#939]
**Mod Version: 3.1.2b**

There seems to be an immediate crash when walking in the vicinity of a certain area on the server I run, which runs a set of mods I play with some friends. It seems to be caused by ticking an entity in a certain part of the map, in-which I have to move people out of the range of in MCEdit otherwise them joining will crash the server once again. 
[crash-2019-10-17_20.43.33-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/3742252/crash-2019-10-17_20.43.33-server.txt)

**Comment by Tslat** [comment]
Let's see if it's fixed after 3.1.2.b.
This appears to be something I may have already fixed
