### ISSUE TITLE
Summoning Limit

### ISSUE THREAD

**Issue by profilename14** [Tslat/Advent-Of-Ascension#941]
Currently there is no limit to the amount of mobs a player can have summoned at once. This allows a patient player to amass an unlimited number of minions over time, and easily kill any boss.

Instead of having this system, I suggest adding a maximum to the creation points worth of minions the player can have active at once. This limit would be equal to 2 times the players maximum creation point value. So, for example, if the player had the default creation point maximum of 200 points, they would be able to summon 400 points worth of minions at once (4 draggies, 3 penguins, or 2 constructs of servility for example). The maximum creation limit would also get higher as the player increases their maximum creation points, with a rate of 40 points added to the limit every 20 points of creation gained.

This creation point maximum could be shown in the GUI as well, with the creation bar being slightly tinted black from bottom to top, and being fully tinted black if the player reaches their total maximum creation limit.

This would make creation cost for minions more important too. As the player unlocks more minions and gets a higher maximum creation value, the player would have to design their team of minions around their limit.

**Comment by Tslat** [comment]
Done in 3.3 via config
