### ISSUE TITLE
Tree Upgrade

### ISSUE THREAD

**Issue by minix0** [Tslat/Advent-Of-Ascension#942]
The trees from dimensions in the mod are fairly terrible, specifically the ones in the Have dimension. I suggest implementing some improvements, such as saplings, a custom wood block, and some harvestable leaves, as most trees don't even have that. I have long been annoyed by this, and the change would be welcome among other people too, to just greatly improve the aesthetics of the dimensions. This would also be nice for building, and allow you to establish a decent base in other dimensions without taking materials from the Overworld.

**Comment by minix0** [comment]
Please?

**Comment by Tslat** [comment]
A custom wood block?
We have like 25 custom wood blocks

And the leaves are harvestable?

**Comment by Tslat** [comment]
Saplings are implemented in 3.3
