### ISSUE TITLE
Minions Can Be Hit by the Sword Sweep Attack

### ISSUE THREAD

**Issue by profilename14** [Tslat/Advent-Of-Ascension#943]
**Mod Version**
3.1.2.b

**Describe the bug**
Currently, it appears that minions can be hit by the sweep effect of swords when the are fully charged. This also seems to apply to rosids.

**To Reproduce**
1. Summon a large group of minions
2. Make sure your attack cooldown is fully charged
3. Hit a group of minions close to each other
4. See multiple minions get hit at once

**Expected behavior**
Minions would be immune to sword sweep attacks, letting the player easily use a sword with them nearby. This is especially bad with rosids as they can be summoned by a rosidian sword.

**Screenshots**
![2019-10-20_13 50 53](https://user-images.githubusercontent.com/44542640/67166096-47878b80-f341-11e9-89c4-c71dfaccef93.png)

**Comment by Tslat** [comment]
Fixed in 3.2
