### ISSUE TITLE
Rosids make chat messages when they die

### ISSUE THREAD

**Issue by profilename14** [Tslat/Advent-Of-Ascension#944]
**Mod Version**
3.1.2.b

**Describe the bug**
Every time a rosid dies, they leave a chat message saying how they died. Obviously, when using any rosidian tools or armor, this can quickly flood the players chat.

**To Reproduce**
1. Get  rosid rifle
2. Use it on a mob with about 60 or more heath
3. Let the rosid summoned by it die
4. See a chat message pop up saying "Rosid was slain by mob"

**Expected behavior**
I am not sure if this can be done, but making a death message not pop up when a rosid dies would be very useful for players who use rosidian items.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/44542640/67166411-eca36380-f343-11e9-8ff0-486ced7d29e6.PNG)

**Comment by Tslat** [comment]
That's what tamed creatures do in MC.

**Comment by masterbobli** [comment]
I think what he meant was that Rosidian death messages spam the chat




On 10/21/2019 05:34, Tslat wrote:

Closed #944.
