### ISSUE TITLE
Do away with the different precasia bones

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#945]
They're pointless, don't make much sense in-universe or out of it (besides to add more "content" and make you mine more), and look ugly anyway. There should be a better way to make the skeletal ingots that doesn't rely on mining four different kinds of ores that are even less useful on their own (only footbones can make boots? come on) to mix them together for no reason.

Loot update is coming anyway. If there's a time to do away with these things, it's now.

**Comment by Cruuk** [comment]
I would almost excuse the bones if Precasia's underground wasn't so boring and barebones in general.

**Comment by DiamondWalker** [comment]
Or they could at least be changed to have unique obtaining methods. The current system is just pointless.

**Comment by Sagisolar** [comment]
Yeah fuck the fragments lol. Why do I need 4 different types just for armor. There literally all bones.

**Comment by EatingSilencer** [comment]
Just curious, how do they not make sense in-universe? To me, they actually seem like an interesting concept (go digging for bones instead of for ores). Maybe if its done differently it would be better.

**Comment by Immortallis1** [comment]
There's no real explanation that can be made for requiring all four bone types for a skeletal ingot. If, one bone type is stronger/tougher than all the others, you just make it out of the one. If not, you just make it out of whatever you want because they are equally as strong. 

There's also no reason for requiring certain bones for armor. Just looking at the shape of footbones and skullbones, for instance, neither of them look remotely close to "armor material".

**Comment by Tslat** [comment]
Mostly handled in 3.2
