### ISSUE TITLE
Buff the Explosive Bow to be similar to Soulfire Bow, change Soulfire Bow effect

### ISSUE THREAD

**Issue by Lithobraker** [Tslat/Advent-Of-Ascension#947]
In the current game, the Soulfire Bow can be easily acquired(with patience) before fighting King BBB, but the Explosive Bow is just the same thing, with slightly less damage and longer draw time.

The explosive arrows effect(which does not work if the arrows hit a tile and does almost no explosion damage, like all explosives in my experience) makes sense for the Explosive Bow, but I'm a bit confused why the Soulfire Bow behaves this way.

I suggest the Soulfire Bow be modified to inflict far less damage, but cause both Wither and Fire on hit enemies(thus, soulfire). Careful consideration should be taken that its DPS is similar to items like the Deep Bow and the new Explosive Bow, making it the superior single-target option to the Explosive Bow and providing less DPS than the Deep Bow, but more sustained damage over time.

**Comment by Cruuk** [comment]
I'd personally recommend avoiding weapon suggestions until 3.2, as that's supposed to rebalance everything (though you can put ability ideas in the weapon ideas poll). Both Soulfire and Explosive bow just suck overall, along with BBB's drops. It's not the only weapon balance issue.

**Comment by Lithobraker** [comment]
> 
> 
> I'd personally recommend avoiding weapon suggestions until 3.2, as that's supposed to rebalance everything (though you can put ability ideas in the weapon ideas poll). Both Soulfire and Explosive bow just suck overall, along with BBB's drops. It's not the only weapon balance issue.

I was under the impression that the request for weapon ability ideas included balancing. To be honest, I thought that this problem may have already been planned to be fixed in the next update, but without any list of weapons that are being reworked(or at least without a statement that 'most' weapons will be looked at), it's kind of impossible to tell what I should or shouldn't suggest.
