### ISSUE TITLE
Giving a cookie to a parrot grants the Overkill and Almighty Touch achievements

### ISSUE THREAD

**Issue by Javisel** [Tslat/Advent-Of-Ascension#948]
**Mod Version**
3.1.2.b

**Describe the bug**
Giving a parrot a cookie grants the Overkill and Almighty Touch achivements.
**To Reproduce**
Steps to reproduce the behaviour:
Right click a parrot with a cookie

**Expected behavior**
I expected the parrot to die, but not grant this achievement.

**Comment by Tslat** [comment]
This is Mojang's fault for having a stupidly designed advancement trigger -.-

I'll see if there's a workaround..
