### ISSUE TITLE
Ticking memory connection

### ISSUE THREAD

**Issue by SparrowGenji9T8** [Tslat/Advent-Of-Ascension#950]
My minecraft keeps not loading or creating the world it keeps getting stuck and when i turn it off it says ticking memory conenction and the log says something to do with aoa am using version 3.1.2b am trying to play Rlcraft with other mods in it not just what it normally has.
https://pastebin.com/Pie4p6Ta here is the link to my log.

**Comment by Tslat** [comment]
Mods that remove advancements from the game break AoA, because it uses advancements in its code.
Currently AoA is incompatible with mods that mess with advancements.

**Comment by SparrowGenji9T8** [comment]
But tell me what mods are doing that and i somewhat fixed it by tping my character to another place by chaning my coordinates and i got rid of the fifth world aswell

**Comment by Tslat** [comment]
I have no idea what mod is causing it. I searched for the ones I know of, but I didn't find any of them.

**Comment by SparrowGenji9T8** [comment]
could it be the mods that have advancements?

**Comment by SparrowGenji9T8** [comment]
even though the problem is not completely fixed but thank you for trying to help and keep up the hard work with Aoa

**Comment by SparrowGenji9T8** [comment]
doesn't really fix it
