### ISSUE TITLE
Rework villages and NPCs

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#951]
Currently villages in AoA are a bit boring. You just find one, right click on the NPCs there, and buy stuff. The randomized trades give them a bit more variety, but for the most part it just makes them more annoying. I'd change a few things about them.

_**VILLAGE REWORK**_
I think villages should be reworked. Specifically, they should probably be more like the ones in vanilla, with randomized houses. The way they currently are feels boring. This could also make dealing with the randomized trades easier, as you could get more than one of each type of NPC in each village. Skill masters could get unique but rare houses in some villages.

_**NEW VILLAGES**_
I think the following dimensions should get new villages:
Vox Ponds; it's always felt like it'd be more of a "city" dimension. All the NPCs would spawn in crates
Barathos; it's partially themed around royalty, yet there's little to no civilization? I have a few ideas for this village, so I'll post it as a separate issue soon.
Celeve; it has a severe lack of content, and to me it's always felt like a dimension that would have a few slightly more civilized and less murderous individuals
Creeponia; maybe? It's a fairly lacking dimension, and the current NPCs there don't seem like they'd live on random towers in a barren jungle dimension. Think about it; who exchanges coins with the banker? Where did the banker and expert come from?
Shyrelands; same as creepoonia (minus the lacking part) and barathos.

_**NPC CHANGES**_
If the village rework gets done, the NPCs should always get only one randomized trade, and breeding should be added. NPCs from different dimensions could have different house requirements to more closely fit their village. NPCs should also be able to unlock new trades after you buy something from them to make their randomized easier to deal with.

_**NEW NPCS**_
Some of the villages (both existing and suggested above) should get more NPCs, since some of them are quite empty. Here are some ideas:
Gorb Warrior: sells swords and bows (the arms dealers should sell guns instead of bows for obvious reasons)
Gorb Excavator: sells tools
Mutant Engineer: would sell robotic stuff. Maybe ingredients to make some sort of robot?
Apoco Survivor: Would wear a face mask and hazmat armor. Could sell a face mask (rather than it being crafted) and maybe oxygen which is required for the face mask or something (it's currently OP anyways). He could also give you stuff for spare pieces of hazmat armor that you give him.
Possibly a creeper miner that acts as a "gem banker"?

**Comment by Cruuk** [comment]
When was Barathos ever "royal"

**Comment by DiamondWalker** [comment]
Aren't barons pretty much royalty?

**Comment by Cruuk** [comment]
> 
> 
> Aren't barons pretty much royalty?

It's just a name pun thing because it rhymes with barren, and it's a barren wasteland, that's all. It was so convincing I thought it was how you spelled barren for a while. Besides the word "baron", I see 0 implication of royal theming. I genuinely thought you were referring to Lelyetia only because of the "Royal greatblade", but accidentally called it Barathos instead.

**Comment by DiamondWalker** [comment]
> 
> 
> > Aren't barons pretty much royalty?
> 
> It's just a name pun thing because it rhymes with barren, and it's a barren wasteland, that's all. It was so convincing I thought it was how you spelled barren for a while. Besides the word "baron", I see 0 implication of royal theming. I genuinely thought you were referring to Lelyetia only because of the "Royal greatblade", but accidentally called it Barathos instead.

There's also the hive baron _**CASTLE**_ and hive _**KING**_, but those might just be coincidences. Still think it's a bit weird that stuff in a dimension would be named after an actual word despite having no relation to it simply because it rhymes. Might as well have "running armor" in runandor because run sounds like rune.

**Comment by DiamondWalker** [comment]
After some more thought, my ideas for the barathos village don't really fit AoA so I won't be posting them.
