### ISSUE TITLE
Underwater Dimension

### ISSUE THREAD

**Issue by minix0** [Tslat/Advent-Of-Ascension#953]
I suggest adding an underwater dimension for an eventual port to something after 1.13, because this dimension would already have some things ready-made such as swimming.
This dimension could have a Titan Cran boss, fish-themed mobs, some sunken temples, and even an Atlantis Village. If you like the idea and have something to add, comment on it.

**Comment by profilename14** [comment]
I'm actually working on a partially underwater dimension right now. I'm still working on it but I plan to create a document about as large as the suggested "Halls of Umbravar" dimension. It will be a massive dungeon tower at x=0 z=0 surrounded by a procedurally generated ocean.

**Comment by DiamondWalker** [comment]
> 
> 
> I'm actually working on a partially underwater dimension right now. Its still unfinished but I plan to create a document about as large as the suggested "Halls of Umbravar" dimension. It will be a massive dungeon tower at x=0 z=0 surrounded by a procedurally generated ocean, and will involve some water based puzzles as well as under water content.

The player spawns within 100 blocks of x=0 z=0, so you might want to make it gen somewhere.

Aside from this, I also had an idea for a dungeon dimension that filled up with water unless you killed mobs in time. However it wouldn't work too well due to water breathing and utopian armor.

**Comment by minix0** [comment]
I love how everyone just ignores that I misspelled "crab" to "cran".

**Comment by Kaldonis1** [comment]
I second this post! Dimension that is 100% underwater would be cool! Ticky and annoying indeed, and impossible to traverse without water breathing, but i could see there being some worth-while materials in here. Maybe friendly mermaids with water breathing plants, or NPCs that live in bubble cities could be found to help you along your journey.
