### ISSUE TITLE
High frame rate cause the skill exp notification to disappear faster

### ISSUE THREAD

**Issue by GTOL** [Tslat/Advent-Of-Ascension#955]
**Mod Version**
3.1.2.b

**Describe the bug**
High frame rate causes the skill exp notification to disappear faster. My Minecraft is running at 300+ fps and the notification disappears too fast that I can bearly see it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to setting
2. Change your frame rate
3. Just do something give you skill exp. e.g. running
4. The exp number will show on the top of the window, and the showing duration is based on the frame rate.

**Expected behavior**
The notification should appear for exact same duration no matter what frame rate I use.

**Screenshots**
N.A.

**Comment by Tslat** [comment]
I mean.. I guess this is a bug. But maybe you should just turn your fps down to a reasonable level?

Running at 300fps does nothing but waste resources

**Comment by Tslat** [comment]
Fixed in 3.2
