### ISSUE TITLE
Make some bosses drop crafting materials

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#957]
So far, it seems the only unique drops for bosses will still be gear after 3.2 (at least that I know of). I think certain bosses should drop crafting materials directly. This could be used to make some multi-ingredient items require a boss' defeat as part of the crafting process. This could also allow the addition of more rewards without cluttering a boss' drop list.

**Comment by Cruuk** [comment]
It's sort of already gonna be a thing. Bosses will still drop weapons/armor, along with bonus items like essences, runes, stuff from world table, etc. along with sometimes having special rare drops like Creep rarely dropping Blast prot 5 books.

I guess exclusive crafting materials could work, at least as another way of getting said weapon drops. Boss drops aren't guaranteed anymore, they work like usual mob drops now. So it could work to have another way to work towards it if RNG decides to poop on you. The only guaranteed drop is the statue now.

**Comment by DiamondWalker** [comment]
> 
> 
> It's sort of already gonna be a thing. Bosses will still drop weapons/armor, along with bonus items like essences, runes, stuff from world table, etc. along with sometimes having special rare drops like Creep rarely dropping Blast prot 5 books.
> 
> I guess exclusive crafting materials could work, at least as another way of getting said weapon drops. Boss drops aren't guaranteed anymore, they work like usual mob drops now. So it could work to have another way to work towards it if RNG decides to poop on you. The only guaranteed drop is the statue now.

What I mean is having crafting materials that drop separate from the items themselves and are unrelated to the boss' weapon drops. With this you could do stuff like making an armor set that requires you to both defeat kror and go to iromine.
