### ISSUE TITLE
Tyrosaur drops

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#958]
A few ideas I had for tyrosaur drops. I added sprites to give an idea what they'd look like in-game

Quakeblade (greatblade):
-unrelated to any and all discord messages by cruuk
-deals high damage
-uses tyrosaur's earthquake ability on attacker (only safe to use when jumping)
-![Quakeblade](https://user-images.githubusercontent.com/19913710/67743246-74e4d100-f9f4-11e9-9afd-f1d9094c660c.png) (the white things are supposed to be horns/spikes)

Shakeshot (sniper):
-deals very high damage
-when hitting a target the attacker will receive severe damage if within a certain range
-![Shake Shot](https://user-images.githubusercontent.com/19913710/67743295-95ad2680-f9f4-11e9-850b-bf894b7a3997.png)

Shakrrow (bow):
-when hitting a target it will damage all other nearby mobs
-![Shakrrow1](https://user-images.githubusercontent.com/19913710/67743346-bc6b5d00-f9f4-11e9-88a8-45fe82a5fc9b.png) (slightly modified demon bow sprite; I thought the spike things fit tyrosaur)

**Comment by Tslat** [comment]
Tyrosaur has been taken care of in 3.2 :)
