### ISSUE TITLE
Runic Golem with shield unslayable via /kill command

### ISSUE THREAD

**Issue by Persandi** [Tslat/Advent-Of-Ascension#959]
**Mod Version**
3.1.2b

**Describe the bug**
Runic Golems unkillable with the /kill command when their shield is active.

**To Reproduce**
Whether from spawners or spawn eggs, Runic Golems are unaffected by /kill @e[type=aoa3:runic_golem] or any other selector targeting them while their shield is up, but become killable if vulnerable via Runic Grenade or shortly after being spawned.

**Expected behavior**
As with other invulnerable mobs like Destructors, the /kill command should override all resistances.

**Screenshots**

Golem being slain while vulnerable, shortly after spawning:
![2019-10-29_18 10 43](https://user-images.githubusercontent.com/57157509/67814009-58d74300-fa79-11e9-8fb6-067ce728cc74.png)

Two Golems given enough time for shield to activate, remaining unharmed by the command, despite the chat log saying otherwise:
![2019-10-29_18 11 03](https://user-images.githubusercontent.com/57157509/67814067-84f2c400-fa79-11e9-857d-b7d878d027e0.png)

**Comment by Tslat** [comment]
I appear to have already fixed this
