### ISSUE TITLE
Portals letting mobs (and whatever passes through nether portals) pass through them

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#96]
Vanilla nether portals, and some other modded portals, can move mobs and other things through them. AoA portals don't do this, and it'd be nice if they could, so we could transport mobs or dropped items to the Overworld even if it meant luring them in, which increases the utility of the portals.

This suggestion originally had an extra part where portals spawned mobs from the dimension like nether portals spawned pigmen, but then I realized that could cause issues with the mobs spawning next to the portal, then walking in, and portal camping even if the portal is closed off on both ends. (With zombie pigmen this is tolerable as they are neutral. I've been portal camped by vanilla non-neutral hostile mobs and it wasn't fun due to them hitting you while you lag before you can move.)

You can prevent mobs from going through by closing it off just like you would with nether portals and AoA nether mobs.

**Comment by Tslat** [comment]
Added in 3.2
