### ISSUE TITLE
/gamerule keepAllinventory true doesn't work!

### ISSUE THREAD

**Issue by xuzh-glhf** [Tslat/Advent-Of-Ascension#960]
The version of AOA is lastest one - 3.1.2.b, and MC version is 1.12.2. 
Or I need to try another command?

**Comment by xijuUu** [comment]
So what should I do if I dont want drop any item or exp?

**Comment by Cruuk** [comment]
> 
> 
> So what should I do if I dont want to drop any item or exp?

The vanilla keepInventory command...

**Comment by xijuUu** [comment]
but keepInventory not works for me in other world...

**Comment by Tslat** [comment]
Set it to true in the other world too.
gamerules are set per-world
