### ISSUE TITLE
Crops add to green tribute bar at any growth level

### ISSUE THREAD

**Issue by Persandi** [Tslat/Advent-Of-Ascension#961]
**Mod Version**
3.1.2b

**Describe the bug**
Crops at any growth stage adds to Selyan's Green Tribute bar

**To Reproduce**
One can place and break the same seed over and over to easily fill the green tribute bar.

**Expected behavior**
Only fully grown crops should be able to give tribute, as it does with Anima.

**Comment by Tslat** [comment]
Fixed
