### ISSUE TITLE
Dimensional Fabric (and others) breakable by Wither

### ISSUE THREAD

**Issue by Persandi** [Tslat/Advent-Of-Ascension#962]
**Mod Version**
3.1.2b

**Describe the bug**
Various unbreakable blocks can be destroyed by the Wither.

**To Reproduce**
The wither will break blocks around it, but this can break the Dimensional Fabric leading to the void or ceilings in the mod's dimensions, and also normally unbreakable blocks like special crafting stations or summoning altars, and drop them as blocks.

**Expected behavior**
Due to the nature of these blocks, it should be unbreakable by all means, including the Wither.

**Comment by Tslat** [comment]
Fixed
