### ISSUE TITLE
Riding a horse into a portal causes the game to crash

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#965]
**Mod Version**
3.2 snapshot 5

**Describe the bug**
Upon riding a horse into a portal, it will cause the game to crash. The crash prevents you from re-entering the world.

Have so far only tested with horses, but I imagine it might also apply to donkeys, mules, and all other rideable mobs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Tame a horse.
2. Saddle the horse.
3. Build a portal and light it with any realmstone.
4. Ride the horse into the portal.
5. Watch game crash.

**Expected behavior**
The game should not crash. I think vanilla mc forbids you from entering another dimension while riding a mob, but I'm not 100% sure.
[crash-2019-10-31_18.43.08-client.txt](https://github.com/Tslat/Advent-Of-Ascension/files/3796089/crash-2019-10-31_18.43.08-client.txt)

**Comment by Tslat** [comment]
Has been fixed

**Comment by EatingSilencer** [comment]
For anybody reading this later: I originally posted this bug report as riding a horse causing the crash when entering the portal. It was later found out that the horse has nothing to do with it, it is the runandor portal that crashes upon entering.
