### ISSUE TITLE
Odious buff

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#97]
**Describe/name the item/content this suggestion relates to**
I know I've pushed for Odious getting it's old ability back in 1.12.2, and I still think it should. But even I don't think that will be quite enough for it. I don't recall *anyone* actually using Odious back in 1.7.10. When someone runs Immortallis, they usually do it for Vulcammer and the banner, *maybe* the Everfight/might staves and vulcane augments, but I don't see anyone ever go after Odious or Deadlock. Mainly because they're... not very good. I like Odious' ability but it wasn't anything insane, when it came to these type of weapons people usually used something like Fragment or Beamer. I know damage isn't everything but like... come on man.

**Describe the change/balance you think would be good to see**
Yes, I believe Odious should be buffed to the same damage output of something like Fragment. Buffing it from 1 -> 2 base damage brings it to 40 DPS. You can almost consider the tractor ability a downside in certain cases, like when you're fighting melee enemies at a decently close range, you're just bringing them closer to you. So yes I think it would be fair...

Ok, if that's too much, at least make the damage 1.5-1.75 (30-35 DPS).... Please?

**Add any alternative implementations you think might work**
Ok fine, maybe it shouldn't have a damage buff, and I'm being dumb again.

Instead make the tractor ability more powerful (when/if it's added back in), making it more of a powerful utility weapon than something with raw damage, with the main focus being powerful backwards kb. Almost as powerful as what Beamer is able to get in 1.12.2. (not that crazy but still haha)
I just want ol' Odious to be good.

**Include any additional background information**
Froster's slowness ability is almost non-existant, it's like slowness 1 for 1-2 seconds....

**Comment by Immortallis1** [comment]
I do it for the banner

**Comment by Cruuk** [comment]
> 
> 
> I do it for the banner

Gamer

**Comment by Sagisolar** [comment]
Girl

**Comment by Tslat** [comment]
Done some stuff after snapshot 9
