### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by mrcakesamurai** [Tslat/Advent-Of-Ascension#970]
**Mod Version**
3.1.2B

**Describe the bug**
I was fighting Cotton Candor, and then this happened.

**Crash Report**
[crash-2019-11-02_16.25.21-server.txt](https://github.com/Tslat/Advent-Of-Ascension/files/3800920/crash-2019-11-02_16.25.21-server.txt)

**Comment by Tslat** [comment]
Has been fixed, thanks
