### ISSUE TITLE
Bestiary AdventGUI

### ISSUE THREAD

**Issue by Armakeen** [Tslat/Advent-Of-Ascension#973]
.

**Comment by Tslat** [comment]
Wouldn't that be incredibly distracting?

**Comment by Armakeen** [comment]
I don't think that would disturb you from reading the informations about the mob
It would have the same purpose than the customizable AdventGUI (with Jungle, Hell & Ruins themes)

By the way, the background would be blured, to make it more discreet (that's what I did on my screen)
