### ISSUE TITLE
Rune finding a little weird

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#975]
**Mod Version**
3.2 snapshot 6 (apparently it hasn't been changed since 3.1.2.b so...)

**Describe the bug**
When a staff is consuming runes, and transitions to the next stack after consuming the previous one, it sometimes leaves 1 rune behind, and gets it "stuck"- the staff no longer works until the singular rune is placed into a conglomerate of itself.
![image](https://user-images.githubusercontent.com/38159897/68166260-a68afa00-ff16-11e9-9714-6332e6dcb14e.png)
It seems to happen when the runes are arranged vertically, horizontal arrangements have only worked correctly. It also seems to happen when the rune has an odd-numbered rune cost (not sure about costs of 1), this is empirical though.
The Staves I tested were Warlock staff (2 Power runes, 3 Kinetic runes, new staff don't ask), and Rosidian staff (3 Wind runes, 1 Life rune, 2 water runes)

**To Reproduce**
Steps to reproduce the behaviour:
Keep shooting a staff until it suddenly gets "stuck", seems to mostly happen with the observations I made up there.

**Expected behavior**
A staff only no longer shooting when it's fully out of required runes.

**Comment by Tslat** [comment]
This was a weird one, but it's fixed now
