### ISSUE TITLE
New Config Option

### ISSUE THREAD

**Issue by ddteam90** [Tslat/Advent-Of-Ascension#976]
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.

Welcome Message

**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.

![Снимок](https://user-images.githubusercontent.com/47353693/68291087-268d9d00-009a-11ea-828f-dbd3f6f70490.PNG)

Add a config option, that removes this message.

**Comment by Tslat** [comment]
Why do I feel like that's just gonna cause a whole bunch of people to come around asking how to open the menu?

**Comment by ddteam90** [comment]
I have it written in the welcome window :)

**Comment by Tslat** [comment]
Okie dokie
