### ISSUE TITLE
mod is too lagging..

### ISSUE THREAD

**Issue by Sn0w0wl** [Tslat/Advent-Of-Ascension#977]
**Mod Version**
What version of the mod are you on?
AoA3-3.1.2.b

**Describe the bug**
It takes a lot of lag as something quickly spawns / despawns.

**To Reproduce**
Steps to reproduce the behaviour:
1.go to Anywhere.  (any dimentions. Overworld is not very bad. )
2.(to seeing entity, )open the minimap, enable Entity radar, and see Friendly mobs.
3.see green dots(Friendly mobs) are appearing and disappearing.

**Expected behavior**

sometime, suddenly too many mobs are spawning. 
(that mentioned above)
maybe it is reason.
 

**Screenshots**

![minecraft](https://user-images.githubusercontent.com/57548015/68519203-f11fc400-02d2-11ea-8b54-4271c86ff134.gif)

**Comment by EatingSilencer** [comment]
Post the log file from when your game is lagging.

**Comment by Sn0w0wl** [comment]
[2019-11-08-1.log](https://github.com/Tslat/Advent-Of-Ascension/files/3827167/2019-11-08-1.log)

yap.!

**Comment by Tslat** [comment]
It's not lagging, that's just spawn fluffers popping in and out of existance. There's nothing to worry about.

**Comment by Sn0w0wl** [comment]
but I think it's a problem to  lagging that stops frequently when I moves to 1.12.2
(↑geforce 1060 6G / 8 memory + distence:very short / optifine)
