### ISSUE TITLE
Rename Crusilisk Caves to Crusilisk Cages

### ISSUE THREAD

**Issue by Merepock** [Tslat/Advent-Of-Ascension#979]
Does this look like a "Cave" to you?
![Crusilisk_Cave](https://user-images.githubusercontent.com/52132442/68548484-73001200-03e5-11ea-9124-fbe358d085b7.png)

**Comment by Cruuk** [comment]
I would prefer reworking the structure itself to look cool rather than the current poop house it is. https://github.com/Tslat/Advent-Of-Ascension/issues/176

**Comment by Seishan123** [comment]
Should I note that you have to mine into it? There's no entrance!
