### ISSUE TITLE
Bomb Carrier still explodes after being killed

### ISSUE THREAD

**Issue by freakengamer** [Tslat/Advent-Of-Ascension#98]
**Mod Version**
What version of the mod are you on?
1.1.3
**Describe the Bug**
After killing the bomb carrier, it proceeded to drop bombs invisibly around the player.
**To Reproduce**
Steps to reproduce the behaviour:
You would have to find a bomb carrier
1. Kill it then it would then continue to make the same sound
2. Dropping bombs that do damage 
3. Then disappear after a small amount of time.
**Expected behavior**
It would die or not cause harm
**Screenshots**
N/A

**Comment by Tslat** [comment]
This was fixed in 3.0.2
