### ISSUE TITLE
Get killed by nothingness. Randomly spawning no-hitbox mobs

### ISSUE THREAD

**Issue by UnderWaves** [Tslat/Advent-Of-Ascension#983]
**Mod Version**
The latest, 3.1.2.b

**Describe the bug**
I noticed a strange category of mobs spawning.
 - They are invisible, but it's not an effect as there isn't any particles
 - They don't have a hitbox so they are invulnerable by vanilla means
 - Apart from this, they have normal sounds and can attack you.
Quite rare but really annoying because you can't see them coming. It happens only with AoA mobs, other ones from oher mods work fine

**To Reproduce**
Steps to reproduce the behaviour:
1. Play on any world
2. Wait a long time, I rarely see these mobs twice in a week
3. Get randomly killed by nothingness

**Expected behavior**
Not getting killed by nothingness

**Screenshots**
I managed to take a screenshot of what should have been a Goblin, it's attacking me so you can see there's something.
![2019-11-14_20 24 49](https://user-images.githubusercontent.com/47225691/68890131-96e19180-071e-11ea-80d3-2b251591f206.png)

**Comment by Tslat** [comment]
You're most likely using optifine. Optifine causes invisible mobs sometimes. Take out optifine if you want to fix the problem.

There's nothing I can do from my side

**Comment by UnderWaves** [comment]
Okay, I'll try. Thanks
