### ISSUE TITLE
Technic Modpack cosmicRPG with AoA crashes when launch

### ISSUE THREAD

**Issue by deno76** [Tslat/Advent-Of-Ascension#984]
Every time I launch cosmicRPG, the game crashes when I launch a world, it crashes for some reason, I do not know why it crashes and the same thing happens with cosRPG which also has AoA, but when I launch Crazycraft, it works normally. Is there any reason why this happens

**Comment by Tslat** [comment]
Can't do much without a crash report.

Keeping in mind 1.7.10 is over half a decade old, and is no longer supported by AoA

**Comment by deno76** [comment]
The problem is that I was using the technic launcher and it didn't give me any crash reports. Is there any modpacks with AoA that you can recommend on Technic

**Comment by Tslat** [comment]
Technic launcher will put crash reports in the crash reports folder inside the modpack folder, wherever you've installed technic.

**Comment by deno76** [comment]
I could not find the folder, is it because of every time I try to get into my world, it freezes and it said Minecraft stopped working and won't load again, would that have a crash report

**Comment by Tslat** [comment]
If the game closed, then yes. There will be a crash report.

If the game didn't close, it'll be in your latest.log file in your logs folder

**Comment by deno76** [comment]
ok thanks

**Comment by deno76** [comment]
[fml-client-1.log](https://github.com/Tslat/Advent-Of-Ascension/files/3853857/fml-client-1.log)
This is the lastest file I found

**Comment by Tslat** [comment]
Provide the file NAMED latest.log

**Comment by deno76** [comment]
I can't find any called latest.log, but I did find a zip file with log file in it, it has the date when it crashed and .log, is it that one

**Comment by deno76** [comment]
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/3854173/latest.log)

**Comment by Tslat** [comment]
Seems to be running fine in that log

**Comment by deno76** [comment]
thats weird, I will screen shot it to you

**Comment by deno76** [comment]
It seemed to be working now, I am not sure why, thanks for your help, sorry for wasting your time
