### ISSUE TITLE
Slight issue with leaves and Lelyetian Wrigglers

### ISSUE THREAD

**Issue by NeoVolt** [Tslat/Advent-Of-Ascension#987]
**Mod Version**
What version of the mod are you on?

3.1.2.b

**Describe the bug**

Some trees generate with the inside of their leaves not filled in or with a leaf missing, specifically turquoise haven trees spawn with the top part hollow, pink trees in haven spawn with a leaf missing near the top, and the tall Stranglewood trees in Precasia have hollow leaves. I've also found that Lelyetian Wrigglers spawn on the underside of Lelyetia with the cap being the one from the upside.

**To Reproduce**
Steps to reproduce the behaviour:

1. Generate the world.
2. Enter dimension with said tree or plant.
3. Look at tree or plant.

**Expected behavior**

The trees should spawn with the areas of leaves filled in instead of hollow and have no leaves missing, and the Lelyetian Wrigglers should spawn with the correct end piece on the underside of Lelyetia.

**Screenshots**

![image](https://user-images.githubusercontent.com/57927345/69110519-ab849900-0a40-11ea-9842-b17fb41d2735.png)
![image](https://user-images.githubusercontent.com/57927345/69110537-b4756a80-0a40-11ea-86f8-1a58c11aac4e.png)
![image](https://user-images.githubusercontent.com/57927345/69110548-be976900-0a40-11ea-9c29-b875b96d6493.png)
![image](https://user-images.githubusercontent.com/57927345/69110561-c5be7700-0a40-11ea-95f4-4835c0950a05.png)

**Comment by Tslat** [comment]
Fixed in 3.2
