### ISSUE TITLE
Precasia underground den mobs should spawn naturally underground instead of in structures

### ISSUE THREAD

**Issue by Cruuk** [Tslat/Advent-Of-Ascension#991]
**Describe/name the existing feature this suggestion relates to**
The Precasian dens and the mobs in them.

**Describe the change or feature you think would be good to see**
I'm pretty sure we all know why the underground dens are quite nasty in design. Even if the ancient teleporter can be annoying to find, at least Overworld's underground has plenty of things to do and find- unlike Precasia's green Obsidian nightmare.

I don't think anyone really likes them at all, and I honestly think it would benefit everyone if the mobs just spawned naturally underground instead. Would anyone really care if it took away from the "unique" aspect of it? If there is even one.

It would be as simple as making all 3 of them spawn under a certain Y level, like 30. If you want to be funky you can give each of the mobs different Y levels they can spawn under.
For a while I was hesitant to post due to them being hunter mobs, but now that hunter mobs won't target players who aren't at the right level in 3.2, I'd say go for it.

Whether they'll still be hunter mobs at all, whether their drops are changed, I think this would be better than what we have to deal with currently. It would make the green Obsidian nightmare more tolerable and just a little more fun.

**Add any alternative implementations you think might work**
I guess you can still keep the dens around even if the mobs are changed to spawn naturally underground. For the 1 person who thinks the the dens are unique or something.

**Comment by Immortallis1** [comment]
Support, this stuff has been memed about for so long and nobody likes it whatsoever
