### ISSUE TITLE
Dimensional Fabric not removed by Vertically Stacked Dimensions

### ISSUE THREAD

**Issue by sumrex** [Tslat/Advent-Of-Ascension#997]
I can't seem to get Vertically Stacked Dimensions to remove the dimensional fabric from any of the dimension generation. This prevents me from using the mod for any cavelike dimensions completely. I'm not sure whats wrong with either mod, but I assume it could be some unconventional world generation with AoA3.

Versions:
Minecraft-1.12.2
VerticallyStackedDimensions-1.12.2-0.1.5
CD4017BE_lib-1.12.2-6.4.13
Forge-14.23.5.2847
Advent of Ascension 3.1.2.b

**Comment by Tslat** [comment]
Done in 3.3
