### ISSUE TITLE
1.12.2 (2.5) Content

### ISSUE THREAD

**Issue by SubBastion** [Tslat/Advent-Of-Ascension#999]
**Describe the new feature you think would be good to add**
Biomes:
-Add all the 2.5 Biomes from the original aoa snapshot. 
-Add modify the biomes as you see fit with new blocks / trees
-Add new structures to those biomes
-Add new bosses
-Add mob specific mobs

Dimensions:
-Please add the 2.5 planned dimensions
-Re-do from scratch the concept by xolova's atlantis mod as a separate dimension a deeper version of lborean

**Comment by Sagisolar** [comment]
> -Re-do from scratch the concept by xolova's atlantis mod as a separate dimension a deeper version of lborean

I think you can actually do that as biome in L'Borean tbh. A full water dimension sounds really unfun to explore but I haven't played Aoa in months so I might be wrong.

**Comment by Cruuk** [comment]
No one will ever see this message
